### ISSUE TITLE
Regexp bugs.

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#10011]
Migrated from [rt.perl.org#71136](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=71136) (status was 'open')

Searchable as RT71136$

**Comment by p5pRT** [comment]
### From @abigail


This is a bug report for perl from abigail@&#8203;abigail\.be\,
generated with the help of perlbug 1\.39 running under perl 5\.10\.1\.




---
\[Please describe your issue here\]

While trying to work around bug \#59792\, I found some different problems&#8203;:

&nbsp;    "a" =~ m \{\(?|\(?\<A>a\)|\(?\<B>b\)\)\} and say $\+ \{B\};

The code about prints 'a'\. This shouldn't happen\, as the \(?\<B>b\) alternation
isn't taken\.

&nbsp;    "a b" =~ m \{\(?|\(?&#8203;:\(?\<A>\(?\<B>a\)\(?\<C>\[^ab\]\*\)\(?\<D>b\)\)\) |
&nbsp;                        \(?&#8203;:\(?\<B>c\)\(?\<C>\[^cd\]\*\)\(?\<D>d\)\)\)\}x;

Afterwards\, %\- is equal to&#8203;:

&nbsp;   \(A  =>  \["a b"\]\,
&nbsp;    B  =>  \["a"\, "a b"\]\,
&nbsp;    C  =>  \[" "\, "a"\]\,
&nbsp;    D  =>  \["b"\, " "\]\)


Instead of the expected&#8203;:

&nbsp;   \(A  =>  \["a b"\]\,
&nbsp;    B  =>  \["a"\]\,
&nbsp;    C  =>  \[" "\]\,
&nbsp;    D  =>  \["b"\]\)


Replacing \(?|\) with \(?&#8203;:\) solves it partially \(at the expense of having
many undefined number variables\)\, but there are still oddities\. For 
instance\, 'keys %\+' and 'keys %\-' don't always return the same set of
keys&#8203;:

&nbsp;    "0" =~ m \{\(?&#8203;:\(?\<A>0\)|\(?\<B>1\)\)\};
&nbsp;    say for keys %\+;    \# Prints 'A'
&nbsp;    say for keys %\-;    \# Prints 'A'\, 'B'



All these issues are still present in 5\.11\.2\.

**Comment by p5pRT** [comment]
### From ben@morrow.me.uk

Quoth perl5\-porters@&#8203;perl\.org&#8203;:
> 
> Replacing \(?|\) with \(?&#8203;:\) solves it partially \(at the expense of having
> many undefined number variables\)\, but there are still oddities\. For 
> instance\, 'keys %\+' and 'keys %\-' don't always return the same set of
> keys&#8203;:
> 
>     "0" =~ m \{\(?&#8203;:\(?\<A>0\)|\(?\<B>1\)\)\};
>     say for keys %\+;    \# Prints 'A'
>     say for keys %\-;    \# Prints 'A'\, 'B'

I can't speak to the rest\, but that at least is as documented\. 'keys %\+'
gives the names that actually matched\, whereas 'keys %\-' gives all the
names that were present in the pattern\.

Ben

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @davidnicol

perldoc perlre&#8203;:
\(?\<NAME>pattern\)
A named capture buffer\. Identical in every respect to normal capturing
parentheses \(\) but for the additional fact that %\+ or %\- may be used
after a successful match to refer to a named buffer\.

Inside \(?|pattern\) the "branch reset" pattern\, the capture buffers are
numbered from the same starting point in each alternation branch\.

Apparently the branch reset pattern is implemented by aliasing the
capture buffers in the alternate branches to each other\, and this
aliasing also happens with the named capture buffers\, causing buffers
which would be separate inside \(?&#8203;:pat\) to be aliases for the same
buffer inside \(?|pat\)\.

possible paths forward&#8203;:

1&#8203;: document that using named capture buffers within the branch reset
pattern is inadvisable\, possibly including issuing an optional runtime
warning

2&#8203;: modify the branch reset pattern to respect the uniqueness of named
capture buffers\, by introducing yet another additional level of
indirection\, deferring the assignment of captured values into named
and numbered buffers until afterwards\, in a new "renumbering step"\,
instead of aliasing the buffers in advance \(which must be what
currently happens\.\)

3&#8203;: make use of a named capture buffer within a branch reset pattern a
fatal compile\-time error

4&#8203;: ?



\-\- 
intake\, compression\, power\, exhaust\, repeat\.

**Comment by p5pRT** [comment]
### From @abigail

On Wed\, Dec 09\, 2009 at 12&#8203;:01&#8203;:41PM \-0600\, David Nicol wrote&#8203;:
> perldoc perlre&#8203;:
> \(?\<NAME>pattern\)
> A named capture buffer\. Identical in every respect to normal capturing
> parentheses \(\) but for the additional fact that %\+ or %\- may be used
> after a successful match to refer to a named buffer\.
> 
> Inside \(?|pattern\) the "branch reset" pattern\, the capture buffers are
> numbered from the same starting point in each alternation branch\.
> 
> Apparently the branch reset pattern is implemented by aliasing the
> capture buffers in the alternate branches to each other\, and this
> aliasing also happens with the named capture buffers\, causing buffers
> which would be separate inside \(?&#8203;:pat\) to be aliases for the same
> buffer inside \(?|pat\)\.
> 
> possible paths forward&#8203;:
> 
> 1&#8203;: document that using named capture buffers within the branch reset
> pattern is inadvisable\, possibly including issuing an optional runtime
> warning
> 
> 2&#8203;: modify the branch reset pattern to respect the uniqueness of named
> capture buffers\, by introducing yet another additional level of
> indirection\, deferring the assignment of captured values into named
> and numbered buffers until afterwards\, in a new "renumbering step"\,
> instead of aliasing the buffers in advance \(which must be what
> currently happens\.\)
> 
> 3&#8203;: make use of a named capture buffer within a branch reset pattern a
> fatal compile\-time error
> 
> 4&#8203;: ?

I would hate for 1\) or 3\) to happen\.

The regexp I had that made this problem surface had the form&#8203;:

&nbsp;    /\(?|         \(?\<Open>PAT1\)\(?\<Body>PAT2\)          \(?\<Close>PAT3\)
&nbsp;       |\(?\<Outer>\(?\<Open>PAT3\)\(?\<Body>PAT4\(?&Outer\)?\)\(?\<Close>PAT6\)\)\)/x

If I make both alternations have the same number and order of named
captures\, it works as expected \(your explaination made me find the 
work around\)&#8203;:

&nbsp;    /\(?|\(?\<Outer>         \(?\<Open>PAT3\)\(?\<Body>PAT4\(?&Outer\)?\)\(?\<Close>PAT6\)\)\)
&nbsp;       |\(?\<Outer>\(\*FAIL\)\)?\(?\<Open>PAT1\)\(?\<Body>PAT2\)          \(?\<Close>PAT3\)/x


Not optimal \(note the necessary switch of the alternations\)\, but now 
at least I get a usuable %\-\.



Abigail

**Comment by p5pRT** [comment]
### From @demerphq

2009/12/9 David Nicol \<davidnicol@&#8203;gmail\.com>&#8203;:
> perldoc perlre&#8203;:
> \(?\<NAME>pattern\)
> A named capture buffer\. Identical in every respect to normal capturing
> parentheses \(\) but for the additional fact that %\+ or %\- may be used
> after a successful match to refer to a named buffer\.
>
> Inside \(?|pattern\) the "branch reset" pattern\, the capture buffers are
> numbered from the same starting point in each alternation branch\.
>
> Apparently the branch reset pattern is implemented by aliasing the
> capture buffers in the alternate branches to each other\, and this
> aliasing also happens with the named capture buffers\, causing buffers
> which would be separate inside \(?&#8203;:pat\) to be aliases for the same
> buffer inside \(?|pat\)\.
>
> possible paths forward&#8203;:
>
> 1&#8203;: document that using named capture buffers within the branch reset
> pattern is inadvisable\, possibly including issuing an optional runtime
> warning

no

> 2&#8203;: modify the branch reset pattern to respect the uniqueness of named
> capture buffers\, by introducing yet another additional level of
> indirection\, deferring the assignment of captured values into named
> and numbered buffers until afterwards\, in a new "renumbering step"\,
> instead of aliasing the buffers in advance \(which must be what
> currently happens\.\)

Well there is the rub&#8203;: we dont "assign" capture capture buffers into
anything at all\.

We maintain two arrays integer offsets into the strings with n\+1 items
in each array\, with the n being the number of capture buffers in a
pattern\. These are exposed to perl as&#8203;: @&#8203;\- and @&#8203;\+\.

Each OPEN regop and CLOSE regop is hard bound to a particular index in
these arrays and when the regop is executed the "current position" is
written into the hard bound slot\.

The named capture buffer hack basically just adds a HoA to this\, where
the keys in the hash are the names and the array contains the index
into the @&#8203;\-/@&#8203;\+ arrays that that name is associated to\. This structure
facilitates mapping one name to multiple buffers\, but not the other
way round\.

When you access $1 you are using a tied interface that uses the
original string\, and the contents of @&#8203;\- and @&#8203;\+ to derive \*on fetch\*
the string you speak of being "assigned"\.

The \(?|\.\.\.\) hack merely plays around with the internal buffer counter
so that the OPEN and CLOSE regop's are allowed to bind to previously
assigned "index" in the @&#8203;\- and @&#8203;\+ arrays\. There really was no
consideration of how this impacted on named capture buffers as the
original conception was that people would use one or the other as they
have overlapping domains\. I mean you dont really need to use the
branch reset pattern if you are using named capture buffers\.

Anyway the point here is that untangling or changing ANY of these is
non\-trivial\.

>
> 3&#8203;: make use of a named capture buffer within a branch reset pattern a
> fatal compile\-time error

no\.


Number 4 could just be "document the weird way it works\, and offer
some workaround patterns for those that Really Want To Go There"\.
Abigail would be my choice to write this\.

cheers\,
Yves


\-\- 
perl \-Mre=debug \-e "/just|another|perl|hacker/"

**Comment by p5pRT** [comment]
### From @abigail

On Thu\, Dec 10\, 2009 at 11&#8203;:47&#8203;:18AM \+0100\, demerphq wrote&#8203;:
> 2009/12/9 David Nicol \<davidnicol@&#8203;gmail\.com>&#8203;:
> > perldoc perlre&#8203;:
> > \(?\<NAME>pattern\)
> > A named capture buffer\. Identical in every respect to normal capturing
> > parentheses \(\) but for the additional fact that %\+ or %\- may be used
> > after a successful match to refer to a named buffer\.
> >
> > Inside \(?|pattern\) the "branch reset" pattern\, the capture buffers are
> > numbered from the same starting point in each alternation branch\.
> >
> > Apparently the branch reset pattern is implemented by aliasing the
> > capture buffers in the alternate branches to each other\, and this
> > aliasing also happens with the named capture buffers\, causing buffers
> > which would be separate inside \(?&#8203;:pat\) to be aliases for the same
> > buffer inside \(?|pat\)\.
> >
> > possible paths forward&#8203;:
> >
> > 1&#8203;: document that using named capture buffers within the branch reset
> > pattern is inadvisable\, possibly including issuing an optional runtime
> > warning
> 
> no
> 
> > 2&#8203;: modify the branch reset pattern to respect the uniqueness of named
> > capture buffers\, by introducing yet another additional level of
> > indirection\, deferring the assignment of captured values into named
> > and numbered buffers until afterwards\, in a new "renumbering step"\,
> > instead of aliasing the buffers in advance \(which must be what
> > currently happens\.\)
> 
> Well there is the rub&#8203;: we dont "assign" capture capture buffers into
> anything at all\.
> 
> We maintain two arrays integer offsets into the strings with n\+1 items
> in each array\, with the n being the number of capture buffers in a
> pattern\. These are exposed to perl as&#8203;: @&#8203;\- and @&#8203;\+\.
> 
> Each OPEN regop and CLOSE regop is hard bound to a particular index in
> these arrays and when the regop is executed the "current position" is
> written into the hard bound slot\.
> 
> The named capture buffer hack basically just adds a HoA to this\, where
> the keys in the hash are the names and the array contains the index
> into the @&#8203;\-/@&#8203;\+ arrays that that name is associated to\. This structure
> facilitates mapping one name to multiple buffers\, but not the other
> way round\.
> 
> When you access $1 you are using a tied interface that uses the
> original string\, and the contents of @&#8203;\- and @&#8203;\+ to derive \*on fetch\*
> the string you speak of being "assigned"\.
> 
> The \(?|\.\.\.\) hack merely plays around with the internal buffer counter
> so that the OPEN and CLOSE regop's are allowed to bind to previously
> assigned "index" in the @&#8203;\- and @&#8203;\+ arrays\. There really was no
> consideration of how this impacted on named capture buffers as the
> original conception was that people would use one or the other as they
> have overlapping domains\. I mean you dont really need to use the
> branch reset pattern if you are using named capture buffers\.

I disagree\. Consider \(sub\) patterns \(you don't contol the code that generates
these pattern \- they could come from Regexp&#8203;::Common510 for instance\)&#8203;:

&nbsp;    my $pat1 = "\(?&#8203;:\(?\<A>a\)1|\(?\<A>b\)2|\(?\<A>c\)3\)";
vs
&nbsp;    my $pat2 = "\(?|\(?\<A>a\)1|\(?\<A>b\)2|\(?\<A>c\)3\)";

and you create larger patterns $PAT1 = "$pat1 $pat1"; $PAT2 = "$pat2 $pat2";

Suppose you use this larger pattern to match something\, and you want to see
what's matched by the second set of 'A's\. Then the options are&#8203;:

&nbsp;    if \($str =~ /$PAT1/\) \{
&nbsp;        $A\_matched = $\- \{A\} \[3\] // $\- \{A\} \[4\] // $\- \{A\} \[5\];
&nbsp;    \}

or 

&nbsp;    if \($str =~ /$PAT2/\) \{
&nbsp;        $A\_matched = $\- \{A\} \[1\];
&nbsp;    \}

Not only is $pat2 easier to deal with\, it's also a lot easier to document\.
Also\, we have to change the code if $pat1 is changed to 
"\(?&#8203;:\(?\<A>a\)1|\(?\<A>b\)2|\(?\<A>c\)3|\(?\<A>d\)4\)"\, while changing $pat2 to
"\(?|\(?\<A>a\)1|\(?\<A>b\)2|\(?\<A>c\)3|\(?\<A>d\)4\)" doesn't require a futher
change\.


Furthermore\, despite the captures being named\, you just may want to
capture the return values and process them \(for instance\, the processing
code might have been written in the 5\.8 era\)\.

&nbsp;    my @&#8203;a1 = $str =~ /$PAT1/;   \# 6 elements\, only 2 defined\.
&nbsp;    my @&#8203;a2 = $str =~ /$PAT2/;   \# 2 elements\, both defined\.

IMO\, \(?|\) in combination with named captures is still very useful\.

> Anyway the point here is that untangling or changing ANY of these is
> non\-trivial\.


And hence unlikely \(if at all\) to happen before 5\.12\. I'll understand\.

> 
> >
> > 3&#8203;: make use of a named capture buffer within a branch reset pattern a
> > fatal compile\-time error
> 
> no\.
> 
> 
> Number 4 could just be "document the weird way it works\, and offer
> some workaround patterns for those that Really Want To Go There"\.
> Abigail would be my choice to write this\.


I will accept that challenge\.



Abigail

**Comment by p5pRT** [comment]
### From @demerphq

2009/12/10 Abigail \<abigail@&#8203;abigail\.be>&#8203;:
> On Thu\, Dec 10\, 2009 at 11&#8203;:47&#8203;:18AM \+0100\, demerphq wrote&#8203;:
>> 2009/12/9 David Nicol \<davidnicol@&#8203;gmail\.com>&#8203;:
>> > perldoc perlre&#8203;:
>> > \(?\<NAME>pattern\)
>> > A named capture buffer\. Identical in every respect to normal capturing
>> > parentheses \(\) but for the additional fact that %\+ or %\- may be used
>> > after a successful match to refer to a named buffer\.
>> >
>> > Inside \(?|pattern\) the "branch reset" pattern\, the capture buffers are
>> > numbered from the same starting point in each alternation branch\.
>> >
>> > Apparently the branch reset pattern is implemented by aliasing the
>> > capture buffers in the alternate branches to each other\, and this
>> > aliasing also happens with the named capture buffers\, causing buffers
>> > which would be separate inside \(?&#8203;:pat\) to be aliases for the same
>> > buffer inside \(?|pat\)\.
>> >
>> > possible paths forward&#8203;:
>> >
>> > 1&#8203;: document that using named capture buffers within the branch reset
>> > pattern is inadvisable\, possibly including issuing an optional runtime
>> > warning
>>
>> no
>>
>> > 2&#8203;: modify the branch reset pattern to respect the uniqueness of named
>> > capture buffers\, by introducing yet another additional level of
>> > indirection\, deferring the assignment of captured values into named
>> > and numbered buffers until afterwards\, in a new "renumbering step"\,
>> > instead of aliasing the buffers in advance \(which must be what
>> > currently happens\.\)
>>
>> Well there is the rub&#8203;: we dont "assign" capture capture buffers into
>> anything at all\.
>>
>> We maintain two arrays integer offsets into the strings with n\+1 items
>> in each array\, with the n being the number of capture buffers in a
>> pattern\. These are exposed to perl as&#8203;: @&#8203;\- and @&#8203;\+\.
>>
>> Each OPEN regop and CLOSE regop is hard bound to a particular index in
>> these arrays and when the regop is executed the "current position" is
>> written into the hard bound slot\.
>>
>> The named capture buffer hack basically just adds a HoA to this\, where
>> the keys in the hash are the names and the array contains the index
>> into the @&#8203;\-/@&#8203;\+ arrays that that name is associated to\. This structure
>> facilitates mapping one name to multiple buffers\, but not the other
>> way round\.
>>
>> When you access $1 you are using a tied interface that uses the
>> original string\, and the contents of @&#8203;\- and @&#8203;\+ to derive \*on fetch\*
>> the string you speak of being "assigned"\.
>>
>> The \(?|\.\.\.\) hack merely plays around with the internal buffer counter
>> so that the OPEN and CLOSE regop's are allowed to bind to previously
>> assigned "index" in the @&#8203;\- and @&#8203;\+ arrays\. There really was no
>> consideration of how this impacted on named capture buffers as the
>> original conception was that people would use one or the other as they
>> have overlapping domains\. I mean you dont really need to use the
>> branch reset pattern if you are using named capture buffers\.
>
> I disagree\. Consider \(sub\) patterns \(you don't contol the code that generates
> these pattern \- they could come from Regexp&#8203;::Common510 for instance\)&#8203;:
>
>    my $pat1 = "\(?&#8203;:\(?\<A>a\)1|\(?\<A>b\)2|\(?\<A>c\)3\)";
> vs
>    my $pat2 = "\(?|\(?\<A>a\)1|\(?\<A>b\)2|\(?\<A>c\)3\)";
>
> and you create larger patterns $PAT1 = "$pat1 $pat1"; $PAT2 = "$pat2 $pat2";
>
> Suppose you use this larger pattern to match something\, and you want to see
> what's matched by the second set of 'A's\. Then the options are&#8203;:
>
>    if \($str =~ /$PAT1/\) \{
>        $A\_matched = $\- \{A\} \[3\] // $\- \{A\} \[4\] // $\- \{A\} \[5\];
>    \}
>
> or
>
>    if \($str =~ /$PAT2/\) \{
>        $A\_matched = $\- \{A\} \[1\];
>    \}
>
> Not only is $pat2 easier to deal with\, it's also a lot easier to document\.
> Also\, we have to change the code if $pat1 is changed to
> "\(?&#8203;:\(?\<A>a\)1|\(?\<A>b\)2|\(?\<A>c\)3|\(?\<A>d\)4\)"\, while changing $pat2 to
> "\(?|\(?\<A>a\)1|\(?\<A>b\)2|\(?\<A>c\)3|\(?\<A>d\)4\)" doesn't require a futher
> change\.
>
>
> Furthermore\, despite the captures being named\, you just may want to
> capture the return values and process them \(for instance\, the processing
> code might have been written in the 5\.8 era\)\.
>
>    my @&#8203;a1 = $str =~ /$PAT1/;   \# 6 elements\, only 2 defined\.
>    my @&#8203;a2 = $str =~ /$PAT2/;   \# 2 elements\, both defined\.
>
> IMO\, \(?|\) in combination with named captures is still very useful\.
>
>> Anyway the point here is that untangling or changing ANY of these is
>> non\-trivial\.
>
>
> And hence unlikely \(if at all\) to happen before 5\.12\. I'll understand\.

Well i dont have any time for it for sure\. :\-\)

In the new year i will probably\.

>>
>> >
>> > 3&#8203;: make use of a named capture buffer within a branch reset pattern a
>> > fatal compile\-time error
>>
>> no\.
>>
>>
>> Number 4 could just be "document the weird way it works\, and offer
>> some workaround patterns for those that Really Want To Go There"\.
>> Abigail would be my choice to write this\.
>
>
> I will accept that challenge\.

Cool\. However if you can figure out a simple description of how it
should work then id like to see it\.

cheers\,
Yves


\-\- 
perl \-Mre=debug \-e "/just|another|perl|hacker/"

**Comment by p5pRT** [comment]
### From @davidnicol

On Thu\, Dec 10\, 2009 at 6&#8203;:02 AM\, demerphq \<demerphq@&#8203;gmail\.com> wrote&#8203;:
>
> Cool\. However if you can figure out a simple description of how it
> should work then id like to see it\.
>
> cheers\,
> Yves

currently %\- and %\+ are named aliases for slots in @&#8203;\- and @&#8203;\+\, while @&#8203;\-
and @&#8203;\+ store integer offsets into a string buffer\.

What if %\- and %\+ held the offsets directly? Ideally the part that
does that would be ifdeffed out and the code included twice\, to keep
from having to do run\-time tests all the time\.



\-\- 
intake\, compression\, power\, exhaust\, repeat\.

**Comment by p5pRT** [comment]
### From @demerphq

2009/12/10 David Nicol \<davidnicol@&#8203;gmail\.com>&#8203;:
> On Thu\, Dec 10\, 2009 at 6&#8203;:02 AM\, demerphq \<demerphq@&#8203;gmail\.com> wrote&#8203;:
>>
>> Cool\. However if you can figure out a simple description of how it
>> should work then id like to see it\.
>>
>> cheers\,
>> Yves
>
> currently %\- and %\+ are named aliases for slots in @&#8203;\- and @&#8203;\+\, while @&#8203;\-
> and @&#8203;\+ store integer offsets into a string buffer\.
>
> What if %\- and %\+ held the offsets directly? Ideally the part that
> does that would be ifdeffed out and the code included twice\, to keep
> from having to do run\-time tests all the time\.

That would mean that all users would pay a price for named captures
for ever more\.

The way we do it is because we could update a slot in these array
thousands of time in a match\, or hundreds of thousands of times\. If we
add a hash lookup every time\.\.\.\.

cheers\,
Yves

\-\- 
perl \-Mre=debug \-e "/just|another|perl|hacker/"

**Comment by p5pRT** [comment]
### From @abigail

On Thu\, Dec 10\, 2009 at 12&#8203;:50&#8203;:41PM \+0100\, Abigail wrote&#8203;:
> On Thu\, Dec 10\, 2009 at 11&#8203;:47&#8203;:18AM \+0100\, demerphq wrote&#8203;:
> > 
> > Number 4 could just be "document the weird way it works\, and offer
> > some workaround patterns for those that Really Want To Go There"\.
> > Abigail would be my choice to write this\.
> 
> 
> I will accept that challenge\.
> 

Done so as commit ab106183f6f6440236f5be52e2a171a63882946a\.


Abigail

**Comment by p5pRT** [comment]
### From @doy

Is there anything more we want to do here?

\-doy

**Comment by khwilliamson** [comment]
No response in 10 years; the docs were updated.  Closing
