### ISSUE TITLE
Add check for spurious PUSHMARKs by introducing POPBLOCK_normal

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#10013]
Migrated from [rt.perl.org#71156](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=71156) (status was 'open')

Searchable as RT71156$

**Comment by p5pRT** [comment]
### From @obra


\-\-

**Comment by p5pRT** [comment]
### From @obra

Add POPBLOCK\_normal\, which is similar to POPBLOCK\, but instead of just
resetting the stack marker\, it checks that the current stack marker is identical
to the saved stack marker\, as should be the case when a block is normally
exited \(without any flow control statement\)\.

This patch detects the spurious PUSHMARKs in Devel&#8203;::PPPort&#8203;::Perl\_ppaddr\_t and
Time&#8203;::HiRes&#8203;::stat\, and causes assertion failures without the just submitted patches\.

Gerard Goossen

**Comment by p5pRT** [comment]
### From @obra

<details><summary>0003-Add-POPBLOCK_normal-which-is-similar-to-POPBLOCK-but.patch</summary>

```diff
From 5858494a3c96d45bc6510dc9001d22feb0a6e571 Mon Sep 17 00:00:00 2001
From: Gerard Goossen <gerard@ggoossen.net>
Date: Wed, 18 Nov 2009 20:31:06 +0100
Subject: [PATCH 3/4] Add POPBLOCK_normal, which is similar to POPBLOCK, but instead of just
 resetting the stack marker, it checks that the current stack marker is identical
 to the saved stack marker, as should be the case when a block is normally
 exited (without any flow control statement).

---
 cop.h    |   12 ++++++++++++
 pp_ctl.c |   10 +++++-----
 pp_hot.c |    4 ++--
 3 files changed, 19 insertions(+), 7 deletions(-)

diff --git a/cop.h b/cop.h
index 0348324..5d5da29 100644
--- a/cop.h
+++ b/cop.h
@@ -562,6 +562,18 @@ struct block {
 	DEBUG_l( PerlIO_printf(Perl_debug_log, "Entering block %ld, type %s\n",	\
 		    (long)cxstack_ix, PL_block_type[CxTYPE(cx)]); )
 
+/* Exit a block at the end of its normal lifetime */
+#define POPBLOCK_normal(cx,pm) cx = &cxstack[cxstack_ix--],			\
+	newsp		 = PL_stack_base + cx->blk_oldsp,		\
+	PL_curcop	 = cx->blk_oldcop,				\
+	assert(PL_markstack_ptr == PL_markstack + cx->blk_oldmarksp),	\
+	PL_scopestack_ix = cx->blk_oldscopesp,				\
+	pm		 = cx->blk_oldpm,				\
+	gimme		 = cx->blk_gimme;				\
+	DEBUG_SCOPE("POPBLOCK");					\
+	DEBUG_l( PerlIO_printf(Perl_debug_log, "Leaving block %ld, type %s\n",		\
+		    (long)cxstack_ix+1,PL_block_type[CxTYPE(cx)]); )
+
 /* Exit a block (RETURN and LAST). */
 #define POPBLOCK(cx,pm) cx = &cxstack[cxstack_ix--],			\
 	newsp		 = PL_stack_base + cx->blk_oldsp,		\
diff --git a/pp_ctl.c b/pp_ctl.c
index a629887..34b17bb 100644
--- a/pp_ctl.c
+++ b/pp_ctl.c
@@ -2046,7 +2046,7 @@ PP(pp_leaveloop)
     PMOP *newpm;
     SV **mark;
 
-    POPBLOCK(cx,newpm);
+    POPBLOCK_normal(cx,newpm);
     assert(CxTYPE_is_LOOP(cx));
     mark = newsp;
     newsp = PL_stack_base + cx->blk_loop.resetsp;
@@ -3770,7 +3770,7 @@ PP(pp_leaveeval)
     const U8 save_flags = PL_op -> op_flags;
     I32 optype;
 
-    POPBLOCK(cx,newpm);
+    POPBLOCK_normal(cx,newpm);
     POPEVAL(cx);
     retop = cx->blk_eval.retop;
 
@@ -3889,7 +3889,7 @@ PP(pp_leavetry)
     register PERL_CONTEXT *cx;
     I32 optype;
 
-    POPBLOCK(cx,newpm);
+    POPBLOCK_normal(cx,newpm);
     POPEVAL(cx);
     PERL_UNUSED_VAR(optype);
 
@@ -3954,7 +3954,7 @@ PP(pp_leavegiven)
     PMOP *newpm;
     PERL_UNUSED_CONTEXT;
 
-    POPBLOCK(cx,newpm);
+    POPBLOCK_normal(cx,newpm);
     assert(CxTYPE(cx) == CXt_GIVEN);
 
     SP = newsp;
@@ -4524,7 +4524,7 @@ PP(pp_leavewhen)
     SV **newsp;
     PMOP *newpm;
 
-    POPBLOCK(cx,newpm);
+    POPBLOCK_normal(cx,newpm);
     assert(CxTYPE(cx) == CXt_WHEN);
 
     SP = newsp;
diff --git a/pp_hot.c b/pp_hot.c
index 48b57d6..9c563e7 100644
--- a/pp_hot.c
+++ b/pp_hot.c
@@ -1858,7 +1858,7 @@ PP(pp_leave)
 	cx->blk_oldpm = PL_curpm;	/* fake block should preserve $1 et al */
     }
 
-    POPBLOCK(cx,newpm);
+    POPBLOCK_normal(cx,newpm);
 
     gimme = OP_GIMME(PL_op, (cxstack_ix >= 0) ? gimme : G_SCALAR);
 
@@ -2498,7 +2498,7 @@ PP(pp_leavesublv)
     if (CxMULTICALL(&cxstack[cxstack_ix]))
 	return 0;
 
-    POPBLOCK(cx,newpm);
+    POPBLOCK_normal(cx,newpm);
     cxstack_ix++; /* temporarily protect top context */
 
     TAINT_NOT;
-- 
1.6.5


```
</details>

**Comment by p5pRT** [comment]
### From @jkeenan

The patch attached to the original post makes changes in these files&#8203;:

 cop\.h    |   12 \+\+\+\+\+\+\+\+\+\+\+\+
 pp\_ctl\.c |   10 \+\+\+\+\+\-\-\-\-\-
 pp\_hot\.c |    4 \+\+\-\-

Would anyone familiar with these source files care to evaluate the patch?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

On Wed Nov 30 19&#8203;:23&#8203;:00 2011\, jkeenan wrote&#8203;:
> The patch attached to the original post makes changes in these files&#8203;:
> 
>  cop\.h    |   12 \+\+\+\+\+\+\+\+\+\+\+\+
>  pp\_ctl\.c |   10 \+\+\+\+\+\-\-\-\-\-
>  pp\_hot\.c |    4 \+\+\-\-
> 
> Would anyone familiar with these source files care to evaluate the patch?

The patch looks good to me\, but I am no expert on how the mark and
context stacks work\.  Could Zefram or Dave Mitchell have a look?

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @cpansprout

On Wed Nov 30 22&#8203;:08&#8203;:25 2011\, sprout wrote&#8203;:
> On Wed Nov 30 19&#8203;:23&#8203;:00 2011\, jkeenan wrote&#8203;:
> > The patch attached to the original post makes changes in these files&#8203;:
> > 
> >  cop\.h    |   12 \+\+\+\+\+\+\+\+\+\+\+\+
> >  pp\_ctl\.c |   10 \+\+\+\+\+\-\-\-\-\-
> >  pp\_hot\.c |    4 \+\+\-\-
> > 
> > Would anyone familiar with these source files care to evaluate the
patch?
> 
> The patch looks good to me

Not so good\, actually&#8203;:

$ \./perl harness \-v \.\./cpan/Time\-HiRes/t/stat\.t
\.\./cpan/Time\-HiRes/t/stat\.t \.\. 
1\.\.1
\# I am the main process 71394\, starting the watchdog process\.\.\.
\# I am the watchdog process 71395\, sleeping for 360 seconds\.\.\.
\# The watchdog process 71395 launched\, continuing testing\.\.\.
Assertion failed&#8203;: \(PL\_markstack\_ptr == PL\_markstack \+
cx\->blk\_oldmarksp\)\, function Perl\_pp\_leaveloop\, file pp\_ctl\.c\, line 2296\.

Then the script hangs\.

\-\-

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @cpansprout

On Fri Dec 02 23&#8203;:02&#8203;:38 2011\, sprout wrote&#8203;:
> On Wed Nov 30 22&#8203;:08&#8203;:25 2011\, sprout wrote&#8203;:
> > On Wed Nov 30 19&#8203;:23&#8203;:00 2011\, jkeenan wrote&#8203;:
> > > The patch attached to the original post makes changes in these files&#8203;:
> > > 
> > >  cop\.h    |   12 \+\+\+\+\+\+\+\+\+\+\+\+
> > >  pp\_ctl\.c |   10 \+\+\+\+\+\-\-\-\-\-
> > >  pp\_hot\.c |    4 \+\+\-\-
> > > 
> > > Would anyone familiar with these source files care to evaluate the
> patch?
> > 
> > The patch looks good to me
> 
> Not so good\, actually&#8203;:
> 
> $ \./perl harness \-v \.\./cpan/Time\-HiRes/t/stat\.t
> \.\./cpan/Time\-HiRes/t/stat\.t \.\. 
> 1\.\.1
> \# I am the main process 71394\, starting the watchdog process\.\.\.
> \# I am the watchdog process 71395\, sleeping for 360 seconds\.\.\.
> \# The watchdog process 71395 launched\, continuing testing\.\.\.
> Assertion failed&#8203;: \(PL\_markstack\_ptr == PL\_markstack \+
> cx\->blk\_oldmarksp\)\, function Perl\_pp\_leaveloop\, file pp\_ctl\.c\, line 2296\.
> 
> Then the script hangs\.

I had to do some manual rebasing to get the patch to apply\.  It’s on the
sprout/POPBLOCK\_normal branch if anyone wants to try fixing it\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Fri Dec 02 23&#8203;:02&#8203;:38 2011\, sprout wrote&#8203;:
> On Wed Nov 30 22&#8203;:08&#8203;:25 2011\, sprout wrote&#8203;:
> > On Wed Nov 30 19&#8203;:23&#8203;:00 2011\, jkeenan wrote&#8203;:
> > > The patch attached to the original post makes changes in these files&#8203;:
> > > 
> > >  cop\.h    |   12 \+\+\+\+\+\+\+\+\+\+\+\+
> > >  pp\_ctl\.c |   10 \+\+\+\+\+\-\-\-\-\-
> > >  pp\_hot\.c |    4 \+\+\-\-
> > > 
> > > Would anyone familiar with these source files care to evaluate the
> patch?
> > 
> > The patch looks good to me
> 
> Not so good\, actually&#8203;:
> 
> $ \./perl harness \-v \.\./cpan/Time\-HiRes/t/stat\.t
> \.\./cpan/Time\-HiRes/t/stat\.t \.\. 
> 1\.\.1
> \# I am the main process 71394\, starting the watchdog process\.\.\.
> \# I am the watchdog process 71395\, sleeping for 360 seconds\.\.\.
> \# The watchdog process 71395 launched\, continuing testing\.\.\.
> Assertion failed&#8203;: \(PL\_markstack\_ptr == PL\_markstack \+
> cx\->blk\_oldmarksp\)\, function Perl\_pp\_leaveloop\, file pp\_ctl\.c\, line 2296\.
> 
> Then the script hangs\.

I had to do some manual rebasing to get the patch to apply\.  It’s on the
sprout/POPBLOCK\_normal branch if anyone wants to try fixing it\.

**Comment by richardleach** [comment]
There has been a fair amount of reworking of the context stack macros & functions since this issue stagnated.

Summarising the `sprout/POPBLOCK_normal `branch, which would need heavy rebasing, it has a `POPBLOCK` macro which does:
```
(PL_markstack_ptr = PL_markstack + cx->blk_oldmarksp)
```
and a `POPBLOCK_common` macro which does:
```
assert(PL_markstack_ptr == PL_markstack + cx->blk_oldmarksp)
```
The current `POPBLOCK_common` does do:
```
PL_markstack_ptr = PL_markstack + cx->blk_oldmarksp;
```

I don't know whether the original premise behind the `assert` that "_it checks that the current stack marker is identical
 to the saved stack marker, as should be the case when a block is normally  exited (without any flow control statement)._" is valid nowadays or not.

Also, if there's still a problem with spurious `PUSHMARK`s, is this the approach we'd want to take or do something differently?

**Comment by jkeenan** [comment]
> There has been a fair amount of reworking of the context stack macros & functions since this issue stagnated.
> 
> Summarising the `sprout/POPBLOCK_normal `branch, which would need heavy rebasing, it has a `POPBLOCK` macro which does:
> 
> ```
> (PL_markstack_ptr = PL_markstack + cx->blk_oldmarksp)
> ```
> 
> and a `POPBLOCK_common` macro which does:
> 
> ```
> assert(PL_markstack_ptr == PL_markstack + cx->blk_oldmarksp)
> ```
> 
> The current `POPBLOCK_common` does do:
> 
> ```
> PL_markstack_ptr = PL_markstack + cx->blk_oldmarksp;
> ```
> 
> I don't know whether the original premise behind the `assert` that "_it checks that the current stack marker is identical to the saved stack marker, as should be the case when a block is normally exited (without any flow control statement)._" is valid nowadays or not.
> 
> Also, if there's still a problem with spurious `PUSHMARK`s, is this the approach we'd want to take or do something differently?

(This must have been one of the first tickets I ever commented on when I began reading p5p.)

My recommendation is that we hold this issue open for, say, 30 days, then close it unless someone wants to argue for the new implementation and produce a clean pull request.

**Comment by iabyn** [comment]
On Fri, Dec 06, 2024 at 04:10:15AM -0800, Richard Leach wrote:
> There has been a fair amount of reworking of the context stack macros &
> functions since this issue stagnated.

Yeah, the macros have been completely replaced with inline functions
which do things in a bit of a different way. The original branch would
have to be mostly re-written from scratch.

I'm not aware of any big issues with markstack_ptr being corrupted which
would be detected via such a patch. I'm not sure off the top of my head
whether there are any valid cases where markstack_ptr might legitimately
not be the same as the saved version on normal scope exit.

Sprout showed Time::HiRes hitting the assertion, but it wasn't clear
whether that indicated a bug in T::HR which has been usefully detected,
or whether it indicated a flaw in the POPBLOCK_normal() idea. I don't feel
a strong urge to investigate it right now.

So I think this ticket should be closed.

-- 
Nothing ventured, nothing lost.

**Comment by jkeenan** [comment]
>  So I think this ticket should be closed.
> […](#)

Closing.
