### ISSUE TITLE
Environment becomes Whitespace when running Alien::SDL's Build.PL inside cpan2dist

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#10209]
Migrated from [rt.perl.org#73252](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=73252) (status was 'open')

Searchable as RT73252$

**Comment by p5pRT** [comment]
### From @shlomif


This is a bug report for perl from shlomif@&#8203;iglu\.org\.il\,
generated with the help of perlbug 1\.39 running under perl 5\.10\.1\.

1\. As root run the following command&#8203;:

\<\<\<
cpan2dist \-\-verbose \-\-format=CPANPLUS&#8203;::Dist&#8203;::Build Alien&#8203;::SDL
>>>

Wait for the prompt to appear\.

2\. Run the following command as root in a different console&#8203;:

\<\<\<
\[root@&#8203;telaviv1 ~\]\# hexdump \< /proc/"1
2"/environ
0000000 2020 2020 2020 2020 2020 2020 2020 2020
\*
0000ca0 0020                                   
0000ca2
>>>

What this command does is dump the /proc//environ of the only child process
of the cpan2dist process \(the perl running the Build\.PL\)\. As one can see it is
full of whitespace instead of the real values\. Running the Alien&#8203;::SDL Build\.PL
from the command line works fine\.

I've tried it on both Mandriva Cooker and inside my Debian Testing VirtualBox
VM and was able to reproduce it in both cases\.


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=high


---
Site configuration information for perl 5\.10\.1&#8203;:

Configured by Mandriva at Thu Dec 17 05&#8203;:38&#8203;:07 EST 2009\.

Summary of my perl5 \(revision 5 version 10 subversion 1\) configuration&#8203;:
&nbsp;   
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.22\.12\-server\-1mdv\, archname=i386\-linux\-thread\-multi
&nbsp;    uname='linux n4\.mandriva\.com 2\.6\.22\.12\-server\-1mdv \#1 smp tue nov 20 09&#8203;:35&#8203;:09 est 2007 i686 intel\(r\) xeon\(tm\) cpu 2\.80ghz gnulinux '
&nbsp;    config\_args='\-des \-Dinc\_version\_list=5\.10\.0 5\.10\.0/i386\-linux\-thread\-multi 5\.8\.8 5\.8\.7 5\.8\.6 5\.8\.5 5\.8\.4 5\.8\.3 5\.8\.2 5\.8\.1 5\.8\.0 5\.6\.1 5\.6\.0 \-Darchname=i386\-linux \-Dcc=i586\-mandriva\-linux\-gnu\-gcc \-Doptimize=\-O2 \-g \-pipe \-Wformat \-Werror=format\-security \-Wp\,\-D\_FORTIFY\_SOURCE=2 \-fstack\-protector \-\-param=ssp\-buffer\-size=4 \-fomit\-frame\-pointer \-march=i586 \-mtune=generic \-fasynchronous\-unwind\-tables \-DDEBUGGING=\-g \-Dprefix=/usr \-Dvendorprefix=/usr \-Dsiteprefix=/usr \-Dsitebin=/usr/local/bin \-Dsiteman1dir=/usr/local/share/man/man1 \-Dsiteman3dir=/usr/local/share/man/man3 \-Dman3ext=3pm \-Dcf\_by=Mandriva \-Dmyhostname=localhost \-Dperladmin=root@&#8203;localhost \-Dcf\_email=root@&#8203;localhost \-Dd\_dosuid \-Ud\_csh \-Duseshrplib \-Duseithreads \-Di\_db \-Di\_ndbm \-Di\_gdbm'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='i586\-mandriva\-linux\-gnu\-gcc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2 \-g \-pipe \-Wformat \-Werror=format\-security \-Wp\,\-D\_FORTIFY\_SOURCE=2 \-fstack\-protector \-\-param=ssp\-buffer\-size=4 \-fomit\-frame\-pointer \-march=i586 \-mtune=generic \-fasynchronous\-unwind\-tables'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.4\.2'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='i586\-mandriva\-linux\-gnu\-gcc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc \-lgdbm\_compat
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    libc=/lib/libc\-2\.11\.so\, so=so\, useshrplib=true\, libperl=libperl\.so
&nbsp;    gnulibc\_version='2\.11'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E \-Wl\,\-rpath\,/usr/lib/perl5/5\.10\.1/i386\-linux\-thread\-multi/CORE'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-g \-pipe \-Wformat \-Werror=format\-security \-Wp\,\-D\_FORTIFY\_SOURCE=2 \-fstack\-protector \-\-param=ssp\-buffer\-size=4 \-fomit\-frame\-pointer \-march=i586 \-mtune=generic \-fasynchronous\-unwind\-tables \-L/usr/local/lib'

Locally applied patches&#8203;:
&nbsp;    Mandriva Linux patches



---
@&#8203;INC for perl 5\.10\.1&#8203;:
&nbsp;    /home/shlomi/apps/perl/local\-lib/lib/perl5/i386\-linux\-thread\-multi
&nbsp;    /home/shlomi/apps/perl/local\-lib/lib/perl5
&nbsp;    /home/shlomi/apps/perl/local\-lib/lib/perl5/i386\-linux\-thread\-multi
&nbsp;    /home/shlomi/apps/perl/local\-lib/lib/perl5/i386\-linux\-thread\-multi
&nbsp;    /home/shlomi/apps/perl/local\-lib/lib/perl5
&nbsp;    /home/shlomi/apps/perl/local\-lib/lib/perl5/i386\-linux\-thread\-multi
&nbsp;    /home/shlomi/apps/perl/modules/lib/perl5/site\_perl/5\.10\.1/i386\-linux\-thread\-multi
&nbsp;    /home/shlomi/apps/perl/modules/lib/perl5/site\_perl/5\.10\.1
&nbsp;    /home/shlomi/apps/perl/modules/lib/site\_perl/5\.10\.1
&nbsp;    /home/shlomi/apps/perl/modules/lib/perl5/5\.10\.1/i386\-linux\-thread\-multi
&nbsp;    /home/shlomi/apps/perl/modules/lib/perl5/5\.10\.1
&nbsp;    /usr/lib/perl5/site\_perl/5\.10\.1/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/site\_perl/5\.10\.1
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.10\.1/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.10\.1
&nbsp;    /usr/lib/perl5/5\.10\.1/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/5\.10\.1
&nbsp;    /usr/lib/perl5/site\_perl/5\.10\.0
&nbsp;    /usr/lib/perl5/site\_perl/5\.10\.0/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/site\_perl/5\.8\.8
&nbsp;    /usr/lib/perl5/site\_perl
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.10\.0
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.10\.0/i386\-linux\-thread\-multi
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8\.8
&nbsp;    /usr/lib/perl5/vendor\_perl
&nbsp;    \.



---
Environment for perl 5\.10\.1&#8203;:
&nbsp;    HOME=/home/shlomi
&nbsp;    LANG=en\_GB\.UTF\-8
&nbsp;    LANGUAGE=en\_GB&#8203;:en
&nbsp;    LC\_ADDRESS=en\_US\.UTF\-8
&nbsp;    LC\_COLLATE=en\_US\.UTF\-8
&nbsp;    LC\_CTYPE=en\_US\.UTF\-8
&nbsp;    LC\_IDENTIFICATION=en\_GB\.UTF\-8
&nbsp;    LC\_MEASUREMENT=en\_GB\.UTF\-8
&nbsp;    LC\_MESSAGES=en\_US\.UTF\-8
&nbsp;    LC\_MONETARY=en\_US\.UTF\-8
&nbsp;    LC\_NAME=en\_GB\.UTF\-8
&nbsp;    LC\_NUMERIC=en\_GB\.UTF\-8
&nbsp;    LC\_PAPER=en\_US\.UTF\-8
&nbsp;    LC\_SOURCED=1
&nbsp;    LC\_TELEPHONE=en\_US\.UTF\-8
&nbsp;    LC\_TIME=en\_GB\.UTF\-8
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/shlomi/apps/perl/local\-lib/bin&#8203;:/home/shlomi/apps/apache\-maven/apache\-maven\-2\.1\.0//bin&#8203;:/home/shlomi/Download/unpack/graphics/fop/fop\-0\.93&#8203;:/home/shlomi/apps/perl/modules/local/bin&#8203;:/home/shlomi/apps/perl/modules/bin&#8203;:/home/shlomi/apps/latemp/bin&#8203;:/home/shlomi/apps/file/gringotts/bin&#8203;:/home/shlomi/apps/gimageview/bin&#8203;:/home/shlomi/apps/test/quadpres/bin&#8203;:/home/shlomi/apps/docbook\-builder/local/bin&#8203;:/home/shlomi/apps/vim/bin&#8203;:/home/shlomi/bin&#8203;:/home/shlomi/apps/perl/local\-lib/bin&#8203;:/home/shlomi/apps/apache\-maven/apache\-maven\-2\.1\.0//bin&#8203;:/home/shlomi/Download/unpack/file/docbook/docbook\-xsl\-snapshot/tools/bin&#8203;:/usr/local/bin&#8203;:/bin&#8203;:/usr/bin&#8203;:/usr/games&#8203;:/usr/lib/qt4/bin&#8203;:/usr/lib/ssh
&nbsp;    PERL5LIB=/home/shlomi/apps/perl/local\-lib/lib/perl5&#8203;:/home/shlomi/apps/perl/local\-lib/lib/perl5/i386\-linux\-thread\-multi&#8203;:/home/shlomi/apps/perl/local\-lib/lib/perl5&#8203;:/home/shlomi/apps/perl/local\-lib/lib/perl5/i386\-linux\-thread\-multi&#8203;:/home/shlomi/apps/perl/modules/lib/perl5/site\_perl/5\.10\.1&#8203;:/home/shlomi/apps/perl/modules/lib/site\_perl/5\.10\.1&#8203;:/home/shlomi/apps/perl/modules/lib/perl5/5\.10\.1
&nbsp;    PERL\_AUTOINSTALL=\-\-alldeps
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    PERL\_MM\_OPT=INSTALL\_BASE=/home/shlomi/apps/perl/local\-lib
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @shlomif

Seems like my perlbug shell script's here document messed up the hexdump
command\. Here it is&#8203;:

\<\<\<
\[root@&#8203;telaviv1 ~\]\# hexdump \< /proc/"$\(pgrep \-P "$\(pgrep
cpan2dist\)"\)"/environ
0000000 2020 2020 2020 2020 2020 2020 2020 2020
\*
0000ca0 0020                                   
0000ca2
>>>

**Comment by p5pRT** [comment]
@shlomif - Status changed from 'new' to 'open'

**Comment by jkeenan** [comment]
`cpan2dist` is [part of the CPANPLUS distribution on CPAN](
https://metacpan.org/pod/distribution/CPANPLUS/bin/cpan2dist).  Way back when, CPANPLUS was distributed with the Perl 5 core distribution, but that is no longer the case.  If this issue is still a problem, please file a bug ticket at https://rt.cpan.org/Public/Dist/Display.html?Name=CPANPLUS.

Closing this ticket.

Thank you very much.
Jim Keenan
