### ISSUE TITLE
META cygwin-1.7 5.10 regressions

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#10211]
Migrated from [rt.perl.org#73298](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=73298) (status was 'open')

Searchable as RT73298$

**Comment by p5pRT** [comment]
### From @rurban

This is a bug report for perl from rurban@&#8203;x\-ray\.at\,
generated with the help of perlbug 1\.39 running under perl 5\.11\.5\.



---
Meta ticket to cover all 5\.10 regressions for the new
cygwin\-1\.7\, unsupported with 5\.10\.

Some are just bad tests\, some require support for
the new cygwin features\.

5\.11\.5 \- cygwin\-1\.7 \- threaded&#8203;:
Failed 52 tests out of 1681\, 96\.91% okay\.
\.\./cpan/Compress\-Raw\-Bzip2/t/01bzip2\.t    \.\./cpan/Compress\-Raw\-Zlib/t/02zlib\.t
\.\./cpan/Compress\-Raw\-Zlib/t/07bufsize\.t    \.\./cpan/DB\_File/t/db\-btree\.t
\.\./cpan/DB\_File/t/db\-hash\.t    \.\./cpan/DB\_File/t/db\-recno\.t
\.\./cpan/Encode/t/enc\_data\.t    \.\./cpan/Encode/t/enc\_eucjp\.t
\.\./cpan/Encode/t/enc\_module\.t    \.\./cpan/Encode/t/enc\_utf8\.t
\.\./cpan/Encode/t/encoding\.t    \.\./cpan/Encode/t/jperl\.t
\.\./cpan/Encode/t/mime\-name\.t    \.\./cpan/Encode/t/perlio\.t
\.\./cpan/ExtUtils\-MakeMaker/t/MM\_Cygwin\.t
\.\./cpan/ExtUtils\-ParseXS/t/more\.t    \.\./cpan/Memoize/t/tie\.t
\.\./cpan/Memoize/t/tie\_gdbm\.t    \.\./cpan/Win32/t/Unicode\.t
\.\./cpan/Win32API\-File/t/file\.t    \.\./cpan/podlators/t/man\-utf8\.t
\.\./cpan/podlators/t/man\.t    \.\./cpan/podlators/t/text\-utf8\.t
\.\./dist/Safe/t/safesort\.t    \.\./ext/Devel\-DProf/t/DProf\.t
\.\./ext/GDBM\_File/t/gdbm\.t    \.\./ext/NDBM\_File/t/ndbm\.t
\.\./ext/ODBM\_File/t/odbm\.t    \.\./ext/PerlIO\-encoding/t/encoding\.t
\.\./ext/PerlIO\-encoding/t/fallback\.t    \.\./ext/SDBM\_File/t/sdbm\.t
\.\./ext/XS\-APItest/t/hash\.t    \.\./lib/AnyDBM\_File\.t
\.\./lib/DBM\_Filter/t/01error\.t    \.\./lib/DBM\_Filter/t/02core\.t
\.\./lib/DBM\_Filter/t/compress\.t    \.\./lib/DBM\_Filter/t/encode\.t
\.\./lib/DBM\_Filter/t/int32\.t    \.\./lib/DBM\_Filter/t/null\.t
\.\./lib/DBM\_Filter/t/utf8\.t    io/fs\.t    io/layers\.t    lib/cygwin\.t
op/filetest\.t    op/taint\.t    uni/chomp\.t    uni/chr\.t    uni/greek\.t
uni/latin2\.t    uni/tr\_eucjp\.t    uni/tr\_sjis\.t    uni/tr\_utf8\.t

&nbsp;     cppflags='\-DPERL\_USE\_SAFE\_PUTENV \-U\_\_STRICT\_ANSI\_\_ \-march=pentium4 
\-mfpmath=sse \-mieee\-fp \-mmmx \-msse \-msse2 \-fno\-strict\-aliasing \-pipe 
\-fstack\-protector \-I/usr/local/include'
&nbsp;     ccversion=''\, gccversion='4\.3\.4 20090804 \(release\) 1'\, gccosandvers=''
&nbsp;     intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=12345678
&nbsp;     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;     ivtype='long long'\, ivsize=8\, nvtype='double'\, nvsize=8\, 
Off\_t='off\_t'\, lseeksize=8
&nbsp;     alignbytes=8\, prototype=define
&nbsp;   Linker and Libraries&#8203;:
&nbsp;     ld='g\+\+'\, ldflags =' \-Wl\,\-\-enable\-auto\-import 
\-Wl\,\-\-export\-all\-symbols \-Wl\,\-\-stack\,8388608 
\-Wl\,\-\-enable\-auto\-image\-base \-fstack\-protector \-L/usr/local/lib'
&nbsp;     libpth=/usr/local/lib /usr/lib /lib
&nbsp;     libs=\-lgdbm \-ldb \-ldl \-lcrypt \-lgdbm\_compat
&nbsp;     perllibs=\-ldl \-lcrypt
&nbsp;     libc=/usr/lib/libc\.a\, so=dll\, useshrplib=true\, 
libperl=cygperl5\_11\_5@&#8203;f1fc40f4\.dll
&nbsp;     gnulibc\_version=''
&nbsp;   Dynamic Linking&#8203;:
&nbsp;     dlsrc=dl\_dlopen\.xs\, dlext=dll\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;     cccdlflags=' '\, lddlflags=' \-\-shared  \-Wl\,\-\-enable\-auto\-import 
\-Wl\,\-\-export\-all\-symbols \-Wl\,\-\-stack\,8388608 
\-Wl\,\-\-enable\-auto\-image\-base \-L/usr/local/lib \-fstack\-protector'

Locally applied patches&#8203;:




---
@&#8203;INC for perl 5\.11\.5&#8203;:
&nbsp;     lib
&nbsp;     lib/auto
&nbsp;     /usr/lib/perl5/site\_perl/5\.11\.5/i686\-cygwin
&nbsp;     /usr/lib/perl5/site\_perl/5\.11\.5
&nbsp;     /usr/lib/perl5/vendor\_perl/5\.11\.5/i686\-cygwin
&nbsp;     /usr/lib/perl5/vendor\_perl/5\.11\.5
&nbsp;     /usr/lib/perl5/5\.11\.5/i686\-cygwin
&nbsp;     /usr/lib/perl5/5\.11\.5
&nbsp;     /usr/lib/perl5/site\_perl
&nbsp;     /usr/lib/perl5/vendor\_perl
&nbsp;     /usr/lib/perl5/site\_perl/5\.11
&nbsp;     /usr/lib/perl5/site\_perl/5\.10
&nbsp;     /usr/lib/perl5/vendor\_perl/5\.10
&nbsp;     /usr/lib/perl5/site\_perl/5\.8
&nbsp;     \.



---
Environment for perl 5\.11\.5&#8203;:
&nbsp;     HOME=/home/rurban
&nbsp;     LANG=C\.ISO\-8859\-1
&nbsp;     LANGUAGE \(unset\)
&nbsp;     LD\_LIBRARY\_PATH \(unset\)
&nbsp;     LOGDIR \(unset\)
 
PATH=~/bin&#8203;:/usr/bin&#8203;:/usr/sbin&#8203;:/usr/local/sbin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/X11R6/bin&#8203;:/cygdrive/c/WINDOWS/system32&#8203;:/cygdrive/c/WINDOWS&#8203;:/usr/bin&#8203;:/cyg1/bin&#8203;:/cyg1/usr/local/bin&#8203;:/cygdrive/c/WINDOWS/System32/Wbem&#8203;:/cygdrive/c/Programme/ATI 
Technologies/ATI\.ACE/Core\-Static&#8203;:/cygdrive/c/Programme/Gemeinsame 
Dateien/Ulead 
Systems/MPEG&#8203;:/cygdrive/u&#8203;:/cygdrive/c/Programme/QuickTime/QTSystem/&#8203;:/usr/lib/lapack
&nbsp;     PERL\_BADLANG \(unset\)
&nbsp;     SHELL \(unset\)
\-\- 
Reini Urban
http&#8203;://phpwiki\.org/  http&#8203;://murbreak\.at/

**Comment by p5pRT** [comment]
@rurban - Status changed from 'new' to 'open'

**Comment by toddr** [comment]
Given these reports are for perl 5.11 and we're on 5.31 at this point, I'm closing this case as dated. If new information is made available for cygwin on 5.30+, we should totally look into it. Thanks!
