### ISSUE TITLE
inconsistent text to float conversion

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#10370]
Migrated from [rt.perl.org#75016](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=75016) (status was 'open')

Searchable as RT75016$

**Comment by p5pRT** [comment]
### From jmitchell@frb.gov


This is a bug report for perl from jmitchell@&#8203;frb\.gov\,
generated with the help of perlbug 1\.35 running under perl v5\.8\.8\.

\#\!/opt/local/bin/perl

use strict;
use warnings;

\# these do not become identical floating point numbers
my @&#8203;tests = \(
&nbsp;         14151\.155\,
&nbsp;         1\.4151155E4\,
&nbsp;        \);

for my $test \(@&#8203;tests\) \{
&nbsp;  printf "%\.30g\\n"\, $test;
\}

\# this might be a false lead\, but for some reason\, they are identical
\# after stringification
for my $test \(@&#8203;tests\) \{
&nbsp;  printf "%\.30g\\n"\, $test \. '';
\}

\# output on 5\.8\.8 and 5\.10\.0
\# 14151\.155000000001
\# 14151\.154999999999
\# 14151\.155000000001
\# 14151\.155000000001

\# output on 5\.8\.5 \(i\.e\. this problem hasn't always existed\)&#8203;:
\# 14151\.155000000001
\# 14151\.155000000001
\# 14151\.155000000001
\# 14151\.155000000001


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=medium


---
Site configuration information for perl v5\.8\.8&#8203;:

Configured by appadm at Mon Apr 27 10&#8203;:32&#8203;:55 EDT 2009\.

Summary of my perl5 \(revision 5 version 8 subversion 8\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.18\-92\.1\.18\.el5xen\, archname=x86\_64\-linux\-thread\-multi
&nbsp;    uname='linux jhbdev\.rsma\.frb\.gov 2\.6\.18\-92\.1\.18\.el5xen \#1 smp wed nov 5 09&#8203;:15&#8203;:48 est 2008 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;    config\_args='\-des \-Dprefix=/opt/perl \-Duseshrplib \-Dusethreads \-Accflags=\-DPERL\_REENTRANT\_MAXSIZE=65536'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=define use64bitall=define uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DPERL\_REENTRANT\_MAXSIZE=65536 \-fno\-strict\-aliasing \-pipe \-Wdeclaration\-after\-statement \-I/usr/local/include \-I/opt/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-I/usr/include/gdbm'\,
&nbsp;    optimize='\-O2'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DTHREADS\_HAVE\_PIDS \-DPERL\_REENTRANT\_MAXSIZE=65536 \-fno\-strict\-aliasing \-pipe \-Wdeclaration\-after\-statement \-I/usr/local/include \-I/opt/local/include \-I/usr/include/gdbm'
&nbsp;    ccversion=''\, gccversion='4\.1\.2 20071124 \(Red Hat 4\.1\.2\-42\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib \-L/opt/local/lib'
&nbsp;    libpth=/usr/local/lib /opt/local/lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    libc=/lib/libc\-2\.5\.so\, so=so\, useshrplib=true\, libperl=libperl\.so
&nbsp;    gnulibc\_version='2\.5'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E \-Wl\,\-rpath\,/opt/perl/lib/5\.8\.8/x86\_64\-linux\-thread\-multi/CORE'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-L/usr/local/lib \-L/opt/local/lib'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl v5\.8\.8&#8203;:
&nbsp;    /opt/perl/lib/5\.8\.8/x86\_64\-linux\-thread\-multi
&nbsp;    /opt/perl/lib/5\.8\.8
&nbsp;    /opt/perl/lib/site\_perl/5\.8\.8/x86\_64\-linux\-thread\-multi
&nbsp;    /opt/perl/lib/site\_perl/5\.8\.8
&nbsp;    /opt/perl/lib/site\_perl
&nbsp;    \.



---
Environment for perl v5\.8\.8&#8203;:
&nbsp;    HOME=/eim/home/m1jhm01
&nbsp;    LANG=en\_US
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/eim/lib&#8203;:/opt/local/bin&#8203;:/usr/kerberos/bin&#8203;:/usr/local/bin&#8203;:/bin&#8203;:/usr/bin&#8203;:/usr/X11R6/bin
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/tcsh

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Jeff Mitchell wrote&#8203;:
>\# these do not become identical floating point numbers
>my @&#8203;tests = \(
>         14151\.155\,
>         1\.4151155E4\,
>        \);

This resembles \[perl \#41202\]\.  We have a duff text\->float conversion\.

\-zefram

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From jmitchell@frb.gov

On Tue May 11 07&#8203;:46&#8203;:42 2010\, zefram@&#8203;fysh\.org wrote&#8203;:
> This resembles \[perl \#41202\]\.  We have a duff text\->float conversion\.
> 
> \-zefram
> 

I agree\, and noticed that bug as well\.  However\, it might be worth
noting that I could replicate the bug in 41202 on 5\.8\.5 whereas this bug
did not exist in 5\.8\.5\.

**Comment by p5pRT** [comment]
### From @jkeenan

On Tue May 11 08&#8203;:56&#8203;:15 2010\, jhm713 wrote&#8203;:
> On Tue May 11 07&#8203;:46&#8203;:42 2010\, zefram@&#8203;fysh\.org wrote&#8203;:
> > This resembles \[perl \#41202\]\.  We have a duff text\->float conversion\.
> > 
> > \-zefram
> > 
> 
> I agree\, and noticed that bug as well\.  However\, it might be worth
> noting that I could replicate the bug in 41202 on 5\.8\.5 whereas this bug
> did not exist in 5\.8\.5\.

Persists in 5\.16\.0\.  See attached\.

**Comment by p5pRT** [comment]
### From @jkeenan

[75016_float.pl](https://rt-archive.perl.org/perl5/Ticket/Attachment/1188653/611711/75016_float.pl)

**Comment by khwilliamson** [comment]
This is now fixed in blead.  Presumably it is from the same fix as #8730
