### ISSUE TITLE
PUSH on tied arrays

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#10433]
Migrated from [rt.perl.org#75676](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=75676) (status was 'open')

Searchable as RT75676$

**Comment by p5pRT** [comment]
### From @nwc10

Effectively this is 2 bugs in one ticket\, but I can't find a practical way to
split them\. Together\, they mean that push on a shared array isn't atomic&#8203;:

$ cat push\.pl 
\#\!perl \-w
use strict;
use threads;
use threads&#8203;::shared;

my @&#8203;array :shared;

sub hammer \{
&nbsp;    for \(0\.\.9\) \{
&nbsp;        my $got = push @&#8203;array\, 'L'\, 'R';
&nbsp;        print "Got got&#8203;: $got\\n" if $got % 2;
&nbsp;    \}
\}

my @&#8203;t;
push @&#8203;t\, threads\->new\(\\&hammer\) for 0\.\.19;
$\_\->join foreach @&#8203;t;

print join\(''\, @&#8203;array\)\, "\\n";

\_\_END\_\_
$ \./perl \-Ilib push\.pl 
LRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLR
$ \./perl \-Ilib push\.pl 
LRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLR
$ \./perl \-Ilib push\.pl 
LRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLR
$ \./perl \-Ilib push\.pl 
Got got&#8203;: 7
Got got&#8203;: 9
Got got&#8203;: 11
Got got&#8203;: 13
Got got&#8203;: 15
Got got&#8203;: 17
Got got&#8203;: 19
Got got&#8203;: 21
Got got&#8203;: 23
Got got&#8203;: 25
Got got&#8203;: 27
Got got&#8203;: 29
Got got&#8203;: 31
Got got&#8203;: 33
Got got&#8203;: 35
Got got&#8203;: 37
Got got&#8203;: 39
Got got&#8203;: 41
Got got&#8203;: 43
Got got&#8203;: 45
Got got&#8203;: 47
Got got&#8203;: 49
Got got&#8203;: 51
Got got&#8203;: 53
Got got&#8203;: 55
Got got&#8203;: 283
Got got&#8203;: 285
Got got&#8203;: 287
Got got&#8203;: 289
Got got&#8203;: 291
Got got&#8203;: 293
Got got&#8203;: 295
Got got&#8203;: 297
Got got&#8203;: 299
Got got&#8203;: 301
Got got&#8203;: 303
Got got&#8203;: 305
Got got&#8203;: 309
Got got&#8203;: 311
Got got&#8203;: 313
Got got&#8203;: 313
Got got&#8203;: 315
Got got&#8203;: 317
Got got&#8203;: 319
Got got&#8203;: 321
LRLRLLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLRLR


The return value of push is documented to be the number of elements in the
array\. As every push is of two items\, that means that after every push
completes the array will have an even number of entries\.

Note that

1&#8203;: Sometimes the script gets an odd number returns from push
2&#8203;: Sometimes another push starts before the first completes


The problem seems to be twofold

1&#8203;: threads&#8203;::shared doesn't hold a lock for the duration of push\. \(It does for
&nbsp;   unshift\.\)

I can fix this\. However\, fixing it would hide the second bug&#8203;:

2&#8203;: For push and unshift\, the PP code ignores the return value of PUSH and
&nbsp;   UNSHIFT\, and makes a \(second\) call to the tied object\, FETCHSIZE\.

That feels wrong to me\. I have a patch to fix that\. \(Which is how I stumbled
onto the threads&#8203;::shared inconsistency\)


I believe that fixing all of this is the right thing to do\, as currently the
implementation is inconsistent\, less efficient than it could be\, and prevents
some things from being done at all \(such as atomic push and unshift semantics\)\.

However\, it does mean changing the exact behaviour of tied arrays from the
emergent behaviour they have had since the second day of their implementation&#8203;:

http&#8203;://perl5\.git\.perl\.org/perl\.git/commit/a60c0954410db87b \# revision 424

\[which amends the first attempt here
http&#8203;://perl5\.git\.perl\.org/perl\.git/commit/93965878572d85da \# revision 418
\]

Nicholas Clark

**Comment by p5pRT** [comment]
### From @iabyn

On Fri\, Jun 11\, 2010 at 06&#8203;:37&#8203;:56AM \-0700\, Nicholas Clark wrote&#8203;:
> 2&#8203;: For push and unshift\, the PP code ignores the return value of PUSH and
>    UNSHIFT\, and makes a \(second\) call to the tied object\, FETCHSIZE\.

Er\, where does this happen? I can't see it\, which means I'm probably
misinterpreting something\.

\-\- 
This is a great day for France\!
&nbsp;    \-\- Nixon at Charles De Gaulle's funeral

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @nwc10

On Sat\, Jun 12\, 2010 at 12&#8203;:54&#8203;:05PM \+0100\, Dave Mitchell wrote&#8203;:
> On Fri\, Jun 11\, 2010 at 06&#8203;:37&#8203;:56AM \-0700\, Nicholas Clark wrote&#8203;:
> > 2&#8203;: For push and unshift\, the PP code ignores the return value of PUSH and
> >    UNSHIFT\, and makes a \(second\) call to the tied object\, FETCHSIZE\.
> 
> Er\, where does this happen? I can't see it\, which means I'm probably
> misinterpreting something\.

No\, it means that my description was inadequate\. I'd forgotten that I'd also
had to do a bit of chasing to figure out \*why\* it wasn't completely buggy and
simply returning the size of the underlying array\. This code at the end of
pp\_push&#8203;:

&nbsp;    if \(OP\_GIMME\(PL\_op\, 0\) \!= G\_VOID\) \{
&nbsp;    PUSHi\( AvFILL\(ary\) \+ 1 \);
&nbsp;    \}


AvFILL expands to&#8203;:

\#define AvFILL\(av\)    \(\(SvRMAGICAL\(\(const SV \*\) \(av\)\)\) \\
&nbsp;             ? mg\_size\(MUTABLE\_SV\(av\)\) : AvFILLp\(av\)\)


and for a tied array\, SvRMAGICAL\(\) is true\, hence a call to mg\_size\(\) is made\,
and that calls the FETCHSIZE method\.

Nicholas Clark

**Comment by p5pRT** [comment]
### From @iabyn

On Fri\, Jun 11\, 2010 at 06&#8203;:37&#8203;:56AM \-0700\, Nicholas Clark wrote&#8203;:
> However\, it does mean changing the exact behaviour of tied arrays from the
> emergent behaviour they have had since the second day of their implementation&#8203;:

Hmm\, looking at the various docs&#8203;:

Camel 2nd Ed says PUSH not done yet

Camel 3rd Ed \(2000\) doesn't say what PUSH should return\, but its example
PUSH has push as its last statement\, which means it returns the correct
value\, but not explicitly\.

perltie\.pod\, since 2000 \(4ae8561836\) documents PUSH\, but doesn't say what
it should return\. Its example includes
&nbsp;    return $self\->FETCHSIZE\(\);
which is a hint that PUSH should return a value\.

Tie&#8203;::Array's PUSH implementation looks to be explicitly wrong in its
return value\, and perltie\.pod recommends Tie&#8203;::Array as "a good starting
point for many tie\(\) implementations"\.

My feeling is that the combination of ambiguous documentation\, broken
Tie&#8203;::Array  and 10\-year old behaviour\, means that it would be too risky
to change now\.

\-\- 
Indomitable in retreat\, invincible in advance\, insufferable in victory
&nbsp;    \-\- Churchill on Montgomery

**Comment by toddr** [comment]
@iabyn should we close this then?

**Comment by iabyn** [comment]
On Tue, Feb 04, 2020 at 02:24:22PM -0800, Todd Rinaldo wrote:
> @iabyn should we close this then?

I guess so.

-- 
The optimist believes that he lives in the best of all possible worlds.
As does the pessimist.
