### ISSUE TITLE
Can't build 64-bit 5.12.1 on HP-UX 11.31

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#10468]
Migrated from [rt.perl.org#76302](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=76302) (status was 'open')

Searchable as RT76302$

**Comment by p5pRT** [comment]
### From pda@sdf.org

For what it's worth\, 32\-bits builds fine\, at least with gcc\.
Stack trace of miniperl follows the config info\.

Summary of my perl5 \(revision 5 version 12 subversion 1\) configuration&#8203;:

&nbsp;  Platform&#8203;:
&nbsp;    osname=hpux\, osvers=11\.31\, archname=PA\-RISC2\.0
&nbsp;    uname='hp\-ux tdcbobd1 b\.11\.31 u 9000800 2534553333 unlimited\-user license '
&nbsp;    config\_args='\-der'
&nbsp;    hint=previous\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='c89 \+e \+DD64'\, ccflags ='\+DD64 \-D\_HPUX\_SOURCE \-Wl\,\+vnocompatwarnings \-I/usr/local/free/hppa64/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g \-g'\,
&nbsp;    cppflags='\-D\_\_STDC\_EXT\_\_ \-D\_HPUX\_SOURCE \-Wl\,\+vnocompatwarnings \+DD64 \-D\_HPUX\_SOURCE \-Wl\,\+vnocompatwarnings \-I/usr/local/free/hppa64/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'
&nbsp;    ccversion='B\.11\.11\.22'\, gccversion=''\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=4321
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='/usr/bin/ld'\, ldflags =' '
&nbsp;    libpth=/usr/lib/pa20\_64 /usr/local/free/hppa64/lib
&nbsp;    libs=\-lnsl \-lnm \-ldld \-lm \-lsec \-lc
&nbsp;    perllibs=\-lnsl \-lnm \-ldld \-lm \-lsec \-lc
&nbsp;    libc=/lib/libc\.sl\, so=sl\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_hpux\.xs\, dlext=sl\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E \-Wl\,\-B\,deferred '
&nbsp;    cccdlflags='\+Z'\, lddlflags='\-b \+vnocompatwarnings '


Core was generated by \`miniperl'\.
Program terminated with signal 10\, Bus error\.
BUS\_UNKNOWN \- Unknown Error
\#0  0x40000000000be3ac in S\_reganode \(pRExC\_state=0x800003ffbfff3f38\, op=45 '\-'\, arg=1\)
&nbsp;    at regcomp\.c&#8203;:8625
8625        FILL\_ADVANCE\_NODE\_ARG\(ptr\, op\, arg\);
\(gdb\) bt
\#0  0x40000000000be3ac in S\_reganode \(pRExC\_state=0x800003ffbfff3f38\, op=45 '\-'\, arg=1\)
&nbsp;    at regcomp\.c&#8203;:8625
\#1  0x40000000000b2b38 in S\_reg \(pRExC\_state=0x800003ffbfff3f38\, paren=1\,
&nbsp;    flagp=0x800003ffbfff4910\, depth=5\) at regcomp\.c&#8203;:6139
\#2  0x40000000000b5be4 in S\_regatom \(pRExC\_state=0x800003ffbfff3f38\, flagp=0x800003ffbfff47f0\,
&nbsp;    depth=4\) at regcomp\.c&#8203;:6978
\#3  0x40000000000b3b0c in S\_regpiece \(pRExC\_state=0x800003ffbfff3f38\, flagp=0x800003ffbfff4730\,
&nbsp;    depth=3\) at regcomp\.c&#8203;:6412
\#4  0x40000000000b38cc in S\_regbranch \(pRExC\_state=0x800003ffbfff3f38\, flagp=0x800003ffbfff4398\,
&nbsp;    first=1\, depth=2\) at regcomp\.c&#8203;:6354
\#5  0x40000000000b2c10 in S\_reg \(pRExC\_state=0x800003ffbfff3f38\, paren=0\,
&nbsp;    flagp=0x800003ffbfff3e78\, depth=1\) at regcomp\.c&#8203;:6163
\#6  0x40000000000ab6ac in Perl\_re\_compile \(pattern=0x800000010003ba30\, pm\_flags=0\)
&nbsp;    at regcomp\.c&#8203;:4429
\#7  0x40000000000aaa40 in Perl\_pregcomp \(pattern=0x800000010003ba30\, flags=0\) at regcomp\.c&#8203;:4207
\#8  0x40000000001537fc in Perl\_pp\_regcomp \(\) at pp\_ctl\.c&#8203;:221
\#9  0x40000000000f6988 in Perl\_runops\_standard \(\) at run\.c&#8203;:40
\#10 0x4000000000223304 in Perl\_call\_sv \(sv=0x800000010002c108\, flags=14\) at perl\.c&#8203;:2605
\#11 0x400000000022af68 in Perl\_call\_list \(oldscope=2\, paramList=0x800000010002e2b8\) at perl\.c&#8203;:4585
\#12 0x4000000000210c98 in S\_process\_special\_blocks \(fullname=0x8000000100039588 "BEGIN"\,
&nbsp;    gv=0x800000010002e278\, cv=0x800000010002c108\) at op\.c&#8203;:5960
\#13 0x4000000000210aa8 in Perl\_newATTRSUB \(floor=25\, o=0x80000001000395a0\, proto=0x0\, attrs=0x0\,
&nbsp;    block=0x80000001000396b0\) at op\.c&#8203;:5931
\#14 0x4000000000208d84 in Perl\_utilize \(aver=1\, floor=25\, version=0x0\, idop=0x8000000100039350\,
&nbsp;    arg=0x0\) at op\.c&#8203;:3986
\#15 0x4000000000097914 in Perl\_yyparse \(\) at perly\.y&#8203;:674
\#16 0x4000000000221984 in S\_parse\_body \(env=0x0\, xsinit=0x400000000004b180 \<\.opd\+0x1a0>\)
&nbsp;    at perl\.c&#8203;:2160
\#17 0x400000000022024c in perl\_parse \(my\_perl=0x800000010000d260\,
&nbsp;    xsinit=0x400000000004b180 \<\.opd\+0x1a0>\, argc=3\, argv=0x800003ffbfff2538\, env=0x0\)
&nbsp;    at perl\.c&#8203;:1605
\#18 0x40000000001fc034 in main \(argc=3\, argv=0x800003ffbfff2538\, env=0x800003ffbfff2558\)
&nbsp;    at miniperlmain\.c&#8203;:115

**Comment by p5pRT** [comment]
### From @tux

It's been almost a year since this was posted\.

I do not have a \*PA\-RISC\* system with HP\-UX 11\.31\. Most HP\-UX 11\.31 
will be Itanium2\.

The compiler version 11\.11\.22 seems reasonably recent\, but I cannot 
check for 11\.31\, where I have

$ c89 \-\-version
cc&#8203;: HP C/aC\+\+ B3910B A\.06\.25\.02 \[Nov 25 2010\]


First question would be why you use 'c89' instead of 'cc'\, as many 
checks in Configure and hints will look at the compiler name\, and we do 
not check for the name 'c89'\.

What strikes me as inconsistent though is this combination&#8203;:

&nbsp;  config\_args='\-der'
&nbsp;  cc='c89 \+e \+DD64'\, ccflags ='\+DD64 \-D\_HPUX\_SOURCE \-Wl\,
\+vnocompatwarnings \-I/usr/local/free/hppa64/include \-D\_LARGEFILE\_SOURCE 
\-D\_FILE\_OFFSET\_BITS=64'

Which is bound to fail\. What you would need instead is

&nbsp;  $ \./Configure \-Dcc=cc \-Duse64bitall \-der

Maybe you need to get the \-I/usr/local/free/hppa64/include added 
somewhere later\, but at this point that would not be important yet\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by khwilliamson** [comment]
11 years; is this closable?

**Comment by jkeenan** [comment]
> 11 years; is this closable?

I believe it should be closed.  The original poster never responded to questions posed by a knowledgeable contributor. 5.12.1 is long out of support, so we would only be concerned if this could be demonstrated to persist on 5.32 or 5.34.
