### ISSUE TITLE
5.005_63 `Out of memory' on trivial program with @+ and @-

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#1096]
Migrated from [rt.perl.org#2050](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=2050) (status was 'resolved')

Searchable as RT2050$

**Comment by p5pRT** [comment]
### From @mjdominus



Here is fish\.pl&#8203;:

================================================================

"fish" =~ /fish/;
print @&#8203;\-;
================================================================

When I run this\, I get&#8203;:

================================================================
Out of memory\!
================================================================

If I change @&#8203;\- to $\#\-&#8203;:

================================================================
135391488
================================================================

<details><summary>Perl Info</summary>

```


Site configuration information for perl 5.00563:

Configured by mjd at Thu Dec 23 22:24:45 EST 1999.

Summary of my perl5 (revision 5.0 version 5 subversion 63) configuration:
  Platform:
    osname=linux, osvers=2.2.12, archname=i586-linux
    uname='linux plover 2.2.12 #10 mon nov 1 17:02:09 est 1999 i586 unknown '
    config_args='-des'
    hint=previous, useposix=true, d_sigaction=define
    usethreads=undef useperlio=undef d_sfio=undef
    use64bits=undef usemultiplicity=undef
  Compiler:
    cc='cc', optimize='-g', gccversion=egcs-2.90.29 980515 (egcs-1.0.3 release)
    cppflags='-Dbool=char -DHAS_BOOL -I/usr/local/include'
    ccflags ='-Dbool=char -DHAS_BOOL -I/usr/local/include'
    stdchar='char', d_stdstdio=define, usevfork=false
    intsize=4, longsize=4, ptrsize=4, doublesize=8
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /shlib /lib /usr/lib
    libs=-lndbm -lgdbm -ldbm -ldb -ldl -lm -lc
    libc=/lib/libc-2.0.7.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl 5.00563:
    lib
    /usr/local/lib/perl5/5.00563/i586-linux
    /usr/local/lib/perl5/5.00563
    /usr/local/lib/site_perl/5.00562/i586-linux
    /usr/local/lib/site_perl
    .


Environment for perl 5.00563:
    HOME=/home/mjd
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH=/lib:/usr/lib:/usr/X11R6/lib
    LOGDIR (unset)
    PATH=/home/mjd/bin:/usr/local/bin:/bin:/usr/bin:/usr/X11/bin:/usr/games:/sbin:/usr/sbin:/usr/local/bin/X11:/usr/local/bin/mh:/data/mysql/bin:/home/mjd/TPI/bin:/usr/local/mysql/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

mjd@&#8203;plover\.com writes&#8203;:
> "fish" =~ /fish/;
> print @&#8203;\-;
> ================================================================
> Out of memory\!
> ================================================================
> 
> If I change @&#8203;\- to $\#\-&#8203;:
> 
> ================================================================
> 135391488
> ================================================================

I have usemymalloc=n now\, but it does not help me reproduce your
problem\.  I get "0" in both cases\.

Ilya

**Comment by p5pRT** [comment]
### From @gsar

On Thu\, 27 Jan 2000 15&#8203;:37&#8203;:06 EST\, Ilya Zakharevich wrote&#8203;:
>mjd@&#8203;plover\.com writes&#8203;:
>> "fish" =~ /fish/;
>> print @&#8203;\-;
>> ================================================================
>> Out of memory\!
\[\.\.\.\]
>I have usemymalloc=n now\, but it does not help me reproduce your
>problem\.  I get "0" in both cases\.

&nbsp;    % gdb \./perl
&nbsp;    \(gdb\) run \-we '"fish" =~ /fish/; print @&#8203;\-;'
&nbsp;    Starting program&#8203;: /l2/src/p5p\_repo\_view/perlmulti/\./perl \-we '"fish" =~ /fish/; print @&#8203;\-;'
&nbsp;    Out of memory\!

&nbsp;    Breakpoint 1\, Perl\_my\_exit \(my\_perl=0x8169f70\, status=1\) at perl\.c&#8203;:3244
&nbsp;    Source file is more recent than executable\.
&nbsp;    3244        switch \(status\) \{
&nbsp;    \(gdb\) bt
&nbsp;    \#0  Perl\_my\_exit \(my\_perl=0x8169f70\, status=1\) at perl\.c&#8203;:3244
&nbsp;    \#1  0x80b5d3e in Perl\_safesysmalloc \(size=1073741808\) at util\.c&#8203;:106
&nbsp;    \#2  0x80c8343 in Perl\_av\_extend \(my\_perl=0x8169f70\, av=0x816a940\, key=135701757\)
&nbsp;    at av\.c&#8203;:119
&nbsp;    \#3  0x8105f07 in Perl\_stack\_grow \(my\_perl=0x8169f70\, sp=0x816c168\, p=0x816c168\, 
&nbsp;    n=135701629\) at scope\.c&#8203;:62
&nbsp;    \#4  0x80ce4bd in Perl\_pp\_rv2av \(my\_perl=0x8169f70\) at pp\_hot\.c&#8203;:504
&nbsp;    \#5  0x80cb7fc in Perl\_runops\_debug \(my\_perl=0x8169f70\) at run\.c&#8203;:56
&nbsp;    \#6  0x805d87c in S\_run\_body \(my\_perl=0x8169f70\, args=0xbffff92c\) at perl\.c&#8203;:1236
&nbsp;    \#7  0x8105e6f in Perl\_vdefault\_protect \(my\_perl=0x8169f70\, pcur\_env=0xbffff940\, 
&nbsp;    excpt=0xbffff9f0\, body=0x805d670 \<S\_run\_body>\, args=0xbffff908\) \, pcur\_env=0xbffff940\, 
&nbsp;    excpt=0xbffff9f0\, body=0x805d670 \<S\_run\_body>\) at scope\.c&#8203;:26
&nbsp;    \#9  0x805d317 in perl\_run \(my\_perl=0x8169f70\) at perl\.c&#8203;:1169
&nbsp;    \#10 0x8059820 in main \(argc=3\, argv=0xbffffa24\, env=0xbffffa34\) at perlmain\.c&#8203;:53
&nbsp;    \(gdb\) up
&nbsp;    at scope\.c&#8203;:45
&nbsp;    \#8  0x8105d45 in Perl\_default\_protect \(my\_perl=0x8169f70
&nbsp;    \(gdb\) up
&nbsp;    \#2  0x80c8343 in Perl\_av\_extend \(my\_perl=0x8169f70\, av=0x816a940\, key=135701757\)
&nbsp;    at av\.c&#8203;:119
&nbsp;    119                     New\(2\,ary\, newmax\+1\, SV\*\);
&nbsp;    \(gdb\) p newmax
&nbsp;    $2 = 268435451
&nbsp;    \(gdb\) up
&nbsp;    \#3  0x8105f07 in Perl\_stack\_grow \(my\_perl=0x8169f70\, sp=0x816c168\, p=0x816c168\, 
&nbsp;    n=135701629\) at scope\.c&#8203;:62
&nbsp;    62          av\_extend\(PL\_curstack\, \(p \- PL\_stack\_base\) \+ \(n\) \+ 128\);
&nbsp;    \(gdb\) up
&nbsp;    \#4  0x80ce4bd in Perl\_pp\_rv2av \(my\_perl=0x8169f70\) at pp\_hot\.c&#8203;:504
&nbsp;    504             EXTEND\(SP\, maxarg\);          
&nbsp;    \(gdb\) l
&nbsp;    499         \}
&nbsp;    500
&nbsp;    501         if \(GIMME == G\_ARRAY\) \{
&nbsp;    502             I32 maxarg = AvFILL\(av\) \+ 1;
&nbsp;    503             \(void\)POPs;                     /\* XXXX May be optimized away? \*/
&nbsp;    504             EXTEND\(SP\, maxarg\);          
&nbsp;    505             if \(SvRMAGICAL\(av\)\) \{
&nbsp;    506                 U32 i; 
&nbsp;    507                 for \(i=0; i \< maxarg; i\+\+\) \{
&nbsp;    508                     SV \*\*svp = av\_fetch\(av\, i\, FALSE\);
&nbsp;    \(gdb\) p maxarg
&nbsp;    $3 = 135701629
&nbsp;    \(gdb\) p av
&nbsp;    $4 = \(AV \*\) 0x81754f0
&nbsp;    \(gdb\) p Perl\_sv\_dump\(my\_perl\,av\)
&nbsp;    SV = PVAV\(0x816bf24\) at 0x81754f0
&nbsp;      REFCNT = 1
&nbsp;      FLAGS = \(RMG\)
&nbsp;      IV = 0
&nbsp;      NV = 0
&nbsp;      MAGIC = 0x8176148
&nbsp;    MG\_VIRTUAL = 0x81692dc
&nbsp;    MG\_TYPE = 'D'
&nbsp;      ARRAY = 0x0
&nbsp;      FILL = \-1
&nbsp;      MAX = \-1
&nbsp;      ARYLEN = 0x0
&nbsp;      FLAGS = \(REAL\)
&nbsp;    $5 = void

I think av\_fill\(\) doesn't know about 'D' magic\, as don't many other
functions in av\.c\.


Sarathy
gsar@&#8203;ActiveState\.com

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Thu\, Jan 27\, 2000 at 01&#8203;:03&#8203;:56PM \-0800\, Gurusamy Sarathy wrote&#8203;:
> On Thu\, 27 Jan 2000 15&#8203;:37&#8203;:06 EST\, Ilya Zakharevich wrote&#8203;:
> >mjd@&#8203;plover\.com writes&#8203;:
> >> "fish" =~ /fish/;
> >> print @&#8203;\-;
> >> ================================================================
> >> Out of memory\!

>     \#3  0x8105f07 in Perl\_stack\_grow \(my\_perl=0x8169f70\, sp=0x816c168\, p=0x816c168\, 
>     n=135701629\) at scope\.c&#8203;:62
>     \#4  0x80ce4bd in Perl\_pp\_rv2av \(my\_perl=0x8169f70\) at pp\_hot\.c&#8203;:504

>     504             EXTEND\(SP\, maxarg\);          
>     \(gdb\) l
>     499         \}
>     500
>     501         if \(GIMME == G\_ARRAY\) \{
>     502             I32 maxarg = AvFILL\(av\) \+ 1;
>     503             \(void\)POPs;                     /\* XXXX May be optimized away? \*/
>     504             EXTEND\(SP\, maxarg\);          
>     505             if \(SvRMAGICAL\(av\)\) \{
>     506                 U32 i; 
>     507                 for \(i=0; i \< maxarg; i\+\+\) \{
>     508                     SV \*\*svp = av\_fetch\(av\, i\, FALSE\);
>     \(gdb\) p maxarg
>     $3 = 135701629

> I think av\_fill\(\) doesn't know about 'D' magic\, as don't many other
> functions in av\.c\.

Why should they know about particular magic\-type letters?  Why would
not they just use mg\_len?

Ilya

**Comment by p5pRT** [comment]
### From @gsar

On Thu\, 27 Jan 2000 16&#8203;:11&#8203;:14 EST\, Ilya Zakharevich wrote&#8203;:
>> I think av\_fill\(\) doesn't know about 'D' magic\, as don't many other
>> functions in av\.c\.
>
>Why should they know about particular magic\-type letters?  Why would
>not they just use mg\_len?

I should have said mg\_size\(\)\, not av\_fill\(\)\.  mg\_size\(\) just returns
AvFILLp\(\) if there's no vtbl\->svt\_len\.

It's not clear why regular 'P' magic wasn't used for this\.  I'm beginning
to form a sense of forboding that this is just the beginning of all
manner of problems with 'D' magic\. :\-\(


Sarathy
gsar@&#8203;ActiveState\.com

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Gurusamy Sarathy writes&#8203;:
> 
> On Thu\, 27 Jan 2000 16&#8203;:11&#8203;:14 EST\, Ilya Zakharevich wrote&#8203;:
> >> I think av\_fill\(\) doesn't know about 'D' magic\, as don't many other
> >> functions in av\.c\.
> >
> >Why should they know about particular magic\-type letters?  Why would
> >not they just use mg\_len?
> 
> I should have said mg\_size\(\)\, not av\_fill\(\)\.  mg\_size\(\) just returns
> AvFILLp\(\) if there's no vtbl\->svt\_len\.

But there is one&#8203;:

EXT MGVTBL PL\_vtbl\_regdata = \{0\, 0\, MEMBER\_TO\_FPTR\(Perl\_magic\_regdata\_cnt\)\, 0\, 0\};

\#ifdef STRUCT\_MGVTBL\_DEFINITION
STRUCT\_MGVTBL\_DEFINITION;
\#else
struct mgvtbl \{
&nbsp;    int        \(CPERLscope\(\*svt\_get\)\)    \(pTHX\_ SV \*sv\, MAGIC\* mg\);
&nbsp;    int        \(CPERLscope\(\*svt\_set\)\)    \(pTHX\_ SV \*sv\, MAGIC\* mg\);
&nbsp;    U32        \(CPERLscope\(\*svt\_len\)\)    \(pTHX\_ SV \*sv\, MAGIC\* mg\);
&nbsp;    int        \(CPERLscope\(\*svt\_clear\)\)\(pTHX\_ SV \*sv\, MAGIC\* mg\);
&nbsp;    int        \(CPERLscope\(\*svt\_free\)\)    \(pTHX\_ SV \*sv\, MAGIC\* mg\);
\};
\#endif

Ilya

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Fri\, Jan 28\, 2000 at 09&#8203;:01&#8203;:53AM \-0800\, Gurusamy Sarathy wrote&#8203;:
> 
> It appears that rx\->lastparen is uninitialized\, and that's what magic\_regdata\_cnt\(\)
> returns\.

Yes\, the do\-not\-invoke\-REx\-engine optimization was not storing enough data\.

<details><summary>Inline Patch</summary>

```diff
--- ./pp_hot.c~	Fri Dec 24 17:59:24 1999
+++ ./pp_hot.c	Sat Jan 29 01:39:40 2000
@@ -1045,6 +1045,7 @@ yup:					/* Confirmed by INTUIT */
 	rx->startp[0] = s - truebase;
 	rx->endp[0] = s - truebase + rx->minlen;
     }
+    rx->nparens = rx->lastparen = 0;	/* used by @- and @+ */
     LEAVE_SCOPE(oldsave);
     RETPUSHYES;
 
```
</details>

**Comment by juntzhan** [comment]
@circlelooper

aaa
