### ISSUE TITLE
Absence of POSIX::_SC_OPEN_MAX on Windows makes perl debugger restart fail [includes workaround]

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#11235]
Migrated from [rt.perl.org#87740](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=87740) (status was 'open')

Searchable as RT87740$

**Comment by p5pRT** [comment]
### From louis.strous@gmail.com

This is a bug report for perl from louis\.strous@&#8203;gmail\.com\,
generated with the help of perlbug 1\.39 running under perl 5\.12\.3\.

SUMMARY&#8203;: Absence of POSIX&#8203;::\_SC\_OPEN\_MAX on Windows makes perl debugger
restart fail
\[includes workaround\]

Reported by&#8203;: Louis Strous\, louis\.strous@&#8203;gmail\.com\, 2011\-04\-04
\(Also found reported at
http&#8203;://community\.activestate\.com/forum\-topic/restarting\-native\-perl\-debugger\-perl\-5\-008008
on 2007\-11\-25\)

PERL VERSION&#8203;: 5\.12\.3\, 5\.10\.1\, 5\.008008

REPRODUCTION SCENARIO&#8203;: Start debugger for some perl script\, enter "R"
command to restart\.
Get no restart\, but error message about POSIX macro \_SC\_OPEN\_MAX and
termination of
debugged program\.  Entering "R" again yields a similar error message
and terminates the debugger\.  See session log below\.

SESSION LOG&#8203;:
File A\.pl contains the single line 'print "in A\\n";'\.

>>
C&#8203;:\\Users\\swtester\\Documents>perl \-d A\.pl

Loading DB routines from perl5db\.pl version 1\.33
Editor support available\.

Enter h or \`h h' for help\, or \`perldoc perldebug' for more help\.

main&#8203;::\(A\.pl&#8203;:1\)&#8203;: print "in A\\n";

&nbsp;  DB\<1> R
Warning&#8203;: some settings and command\-line options may be lost\!
Your vendor has not defined POSIX macro \_SC\_OPEN\_MAX\, used at
C&#8203;:/Perl/lib/perl5db\.pl line 3334
 at C&#8203;:/Perl/lib/POSIX\.pm line 50
&nbsp;        POSIX&#8203;::AUTOLOAD\(\) called at C&#8203;:/Perl/lib/perl5db\.pl line 3334
&nbsp;        DB&#8203;::DB called at A\.pl line 1
Debugged program terminated\.  Use q to quit or R to restart\,
&nbsp;  use o inhibit\_exit to avoid stopping after program termination\,
&nbsp;  h q\, h R or h o to get additional info\.

&nbsp;  DB\<1> R
Warning&#8203;: some settings and command\-line options may be lost\!
Your vendor has not defined POSIX macro \_SC\_OPEN\_MAX\, used at
C&#8203;:/Perl/lib/perl5db\.pl line 3334
END failed\-\-call queue aborted at A\.pl line 62\.
 at A\.pl line 62

C&#8203;:\\Users\\swtester\\Documents>
\<\<

DIAGNOSIS&#8203;:
Lines 3332\-3335 of perl5db\.pl read&#8203;:

>>
&nbsp;                    my $max\_fd = 1024; \# default if POSIX can't be loaded
&nbsp;                    if \(eval \{ require POSIX \}\) \{
&nbsp;                        $max\_fd = POSIX&#8203;::sysconf\(POSIX&#8203;::\_SC\_OPEN\_MAX\(\)\);
&nbsp;                    \}
\<\<

POSIX Is available but POSIX&#8203;::\_SC\_OPEN\_MAX is not defined on Windows\.
This yields an
exception\, which means that the "restart" code following these lines
is not executed\,
so no proper restart is done\.  If POSIX weren't available at all\, then
a default value
of 1024 would be used for $max\_fd\.

VERIFICATION OF DIAGNOSIS&#8203;:
Run the following test program&#8203;:

>>
use strict;
use warnings;

my $max\_fd = 1024;
if \(eval \{ require POSIX \}\) \{
&nbsp;  print "POSIX available\\n";
&nbsp;  $max\_fd = POSIX&#8203;::sysconf\(POSIX&#8203;::\_SC\_OPEN\_MAX\(\)\);
&nbsp;  print "max\_fd = $max\_fd\\n";
\} else \{
&nbsp;  print "POSIX not available\\n";
\}
print "Done\.\\n";
\<\<

Get output&#8203;:

>>
C&#8203;:\\Users\\swtester\\Documents>perl A\.pl
POSIX available
Your vendor has not defined POSIX macro \_SC\_OPEN\_MAX\, used at A\.pl line 7

C&#8203;:\\Users\\swtester\\Documents>
\<\<

If no exception occurred\, then at least a "Done\." message should have
been printed\.

WORKAROUND&#8203;:
A proper solution would be to implement POSIX&#8203;::\_SC\_OPEN\_MAX\(\) for
Windows\.  I don't
know how to do that\.  A workaround is to not cause an exception if
\_SC\_OPEN\_MAX is
not defined\, but instead use the default value that has already been
defined in case
POSIX cannot be loaded at all\.  Do this by wrapping line 3334 of
perl5db\.pl in an
eval \{ \}&#8203;:

>>
&nbsp;                    my $max\_fd = 1024; \# default if POSIX can't be loaded
&nbsp;                    if \(eval \{ require POSIX \}\) \{
&nbsp;                        eval \{ $max\_fd =
POSIX&#8203;::sysconf\(POSIX&#8203;::\_SC\_OPEN\_MAX\(\)\) \};
&nbsp;                    \}
\<\<

Then on Windows the default value of 1024 gets used for $max\_fd\, just
like if POSIX
were not available at all\.  This seems to work OK for me on Windows 7\.
 I can now
restart the debugger\, and breakpoints are retained\.


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=high


---
Site configuration information for perl 5\.12\.3&#8203;:

Configured by gecko at Wed Feb  9 14&#8203;:35&#8203;:46 2011\.

Summary of my perl5 \(revision 5 version 12 subversion 3\) configuration&#8203;:

&nbsp;  Platform&#8203;:
&nbsp;    osname=MSWin32\, osvers=5\.2\, archname=MSWin32\-x86\-multi\-thread
&nbsp;    uname=''
&nbsp;    config\_args='undef'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=undef
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cl'\, ccflags ='\-nologo \-GF \-W3 \-MD \-Zi \-DNDEBUG \-O1 \-DWIN32
\-D\_CONSOLE \-DNO\_STRICT \-DHAVE\_DES\_FCRYPT \-DUSE\_SITECUSTOMIZE
\-DPERL\_IMPLICIT\_CONTEXT \-DPERL\_IMPLICIT\_SYS \-DUSE\_PERLIO
\-D\_USE\_32BIT\_TIME\_T \-DPERL\_MSVCRT\_READFIX'\,
&nbsp;    optimize='\-MD \-Zi \-DNDEBUG \-O1'\,
&nbsp;    cppflags='\-DWIN32'
&nbsp;    ccversion='12\.00\.8168'\, gccversion=''\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=undef\, longlongsize=8\, d\_longdbl=define\, longdblsize=8
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\,
Off\_t='\_\_int64'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='link'\, ldflags ='\-nologo \-nodefaultlib \-debug \-opt&#8203;:ref\,icf
\-libpath&#8203;:"C&#8203;:\\Perl\\lib\\CORE"  \-machine&#8203;:x86'
&nbsp;    libpth=\\lib
&nbsp;    libs=  oldnames\.lib kernel32\.lib user32\.lib gdi32\.lib winspool\.lib
 comdlg32\.lib advapi32\.lib shell32\.lib ole32\.lib oleaut32\.lib
netapi32\.lib uuid\.lib ws2\_32\.lib mpr\.lib winmm\.lib  version\.lib
odbc32\.lib odbccp32\.lib comctl32\.lib msvcrt\.lib
&nbsp;    perllibs=  oldnames\.lib kernel32\.lib user32\.lib gdi32\.lib
winspool\.lib  comdlg32\.lib advapi32\.lib shell32\.lib ole32\.lib
oleaut32\.lib  netapi32\.lib uuid\.lib ws2\_32\.lib mpr\.lib winmm\.lib
version\.lib odbc32\.lib odbccp32\.lib comctl32\.lib msvcrt\.lib
&nbsp;    libc=msvcrt\.lib\, so=dll\, useshrplib=true\, libperl=perl512\.lib
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_win32\.xs\, dlext=dll\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags=' '\, lddlflags='\-dll \-nologo \-nodefaultlib \-debug
\-opt&#8203;:ref\,icf  \-libpath&#8203;:"C&#8203;:\\Perl\\lib\\CORE"  \-machine&#8203;:x86'

Locally applied patches&#8203;:
&nbsp;    ACTIVEPERL\_LOCAL\_PATCHES\_ENTRY
&nbsp;    c6fbf28 \[perl \#71806\] perldb does not setup %dbline with the
shebang option \-d
&nbsp;    1fd8fa4 Add Wolfram Humann to AUTHORS
&nbsp;    f120055 make string\-append on win32 100 times faster
&nbsp;    a2a8d15 Define \_USE\_32BIT\_TIME\_T for VC6 and VC7
&nbsp;    007cfe1 Don't pretend to support really old VC\+\+ compilers
&nbsp;    6d8f7c9 Get rid of obsolete PerlCRT\.dll support
&nbsp;    d956618 Make Term&#8203;::ReadLine&#8203;::findConsole fall back to STDIN if
/dev/tty can't be opened
&nbsp;    321e50c Escape patch strings before embedding them in patchlevel\.h



---
@&#8203;INC for perl 5\.12\.3&#8203;:
&nbsp;    C&#8203;:/Perl/site/lib
&nbsp;    C&#8203;:/Perl/lib
&nbsp;    \.



---
Environment for perl 5\.12\.3&#8203;:
&nbsp;    HOME \(unset\)
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=C&#8203;:\\Perl\\site\\bin;C&#8203;:\\Perl\\bin;C&#8203;:\\Windows\\system32;C&#8203;:\\Windows;C&#8203;:\\Windows\\System32\\Wbem;C&#8203;:\\Windows\\System32\\WindowsPowerShell\\v1\.0\\
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL \(unset\)

**Comment by p5pRT** [comment]
### From @cpansprout

On Mon Apr 04 01&#8203;:43&#8203;:59 2011\, louis\.strous@&#8203;gmail\.com wrote&#8203;:
> >>
>                     my $max\_fd = 1024; \# default if POSIX can't be
> loaded
>                     if \(eval \{ require POSIX \}\) \{
>                         eval \{ $max\_fd =
> POSIX&#8203;::sysconf\(POSIX&#8203;::\_SC\_OPEN\_MAX\(\)\) \};
>                     \}
> \<\<

Thank you\. Applied as 5332cc6\.

Does anyone know how to write a test for this?

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by toddr** [comment]
I think we can call that a no :)
