### ISSUE TITLE
perldoc double-encoding bog

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#11255]
Migrated from [rt.perl.org#88488](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=88488) (status was 'open')

Searchable as RT88488$

**Comment by p5pRT** [comment]
### From tchrist@perl.com

I never used perldoc\, just normal tools\, so I never noticed its output is
bollocksed up\.  Thanks you Brian for pointing this out\.  The dumb thing is
committing a double\-encoding faux pas&#8203;:

&nbsp;    % perldoc pod/perlunicode\.pod | grep 'Unicode support in Perl' 
&nbsp;       perlunicode â Unicode support in Perl

Which is explained here&#8203;:

&nbsp;    % env PERL\_UNICODE=0 perldoc pod/perlunicode\.pod | grep 'Unicode support in Perl' | uniquote \-b
&nbsp;       perlunicode \\xE2\\x88\\x92 Unicode support in Perl
&nbsp;    % env PERL\_UNICODE=S perldoc pod/perlunicode\.pod | grep 'Unicode support in Perl' | uniquote \-b
&nbsp;       perlunicode \\xC3\\xA2\\xC2\\x88\\xC2\\x92 Unicode support in Perl

&nbsp;    % env PERL\_UNICODE=0 perldoc pod/perlunicode\.pod | grep 'Unicode support in Perl' | uniquote \-x
&nbsp;       perlunicode \\x\{2212\} Unicode support in Perl
&nbsp;    % env PERL\_UNICODE=S perldoc pod/perlunicode\.pod | grep 'Unicode support in Perl' | uniquote \-x
&nbsp;       perlunicode \\x\{E2\}\\x\{88\}\\x\{92\} Unicode support in Perl

&nbsp;    % env PERL\_UNICODE=0 perldoc pod/perlunicode\.pod | grep 'Unicode support in Perl' | uniquote \-v
&nbsp;       perlunicode \\N\{MINUS SIGN\} Unicode support in Perl
&nbsp;    % env PERL\_UNICODE=S perldoc pod/perlunicode\.pod | grep 'Unicode support in Perl' | uniquote \-v
&nbsp;       perlunicode \\N\{LATIN SMALL LETTER A WITH CIRCUMFLEX\}\\N\{CHARACTER TABULATION SET\}\\N\{PRIVATE USE TWO\} Unicode support in Perl

Now compare with \(what are for me\) the standard tools\, which work correctly&#8203;:

&nbsp;    % env PERL\_UNICODE=0 pod2man pod/perlunicode\.pod | nroff \-man | grep 'Unicode support in Perl' | uniquote \-x
&nbsp;       perlunicode \\x\{2212\} Unicode support in Perl
&nbsp;    % env PERL\_UNICODE=S pod2man pod/perlunicode\.pod | nroff \-man | grep 'Unicode support in Perl' | uniquote \-x
&nbsp;       perlunicode \\x\{2212\} Unicode support in Perl

&nbsp;    % env PERL\_UNICODE=0 pod2text pod/perlunicode\.pod |  grep 'Unicode support in Perl' | uniquote \-x
&nbsp;    perlunicode \- Unicode support in Perl
&nbsp;    % env PERL\_UNICODE=S pod2text pod/perlunicode\.pod | grep 'Unicode support in Perl' | uniquote \-x
&nbsp;    perlunicode \- Unicode support in Perl

\-\-tom

**Comment by p5pRT** [comment]
### From @briandfoy

On Wed Apr 13 09&#8203;:54&#8203;:11 2011\, tom christiansen wrote&#8203;:
> I never used perldoc\, just normal tools\, so I never noticed its output
> is
> bollocksed up\.  Thanks you Brian for pointing this out\.  The dumb
> thing is
> committing a double\-encoding faux pas&#8203;:

I started to look at this and didn't immediately see where the problem could be\. I'm a bit 
swamped right now\, but as I have time\, I want to go step\-by\-step to ensure that each thing is 
respecting the data passed to it\. 

Along with that\, I want to make all of the core Perl docs use UTF\-8 as the encoding\. If they are 
ASCII now\, that shouldn't change anything\. The trick is then making the Pod tools recognize and 
respect the encoding \(even if it is something other than UTF\-8\)\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @jkeenan

On Thu Apr 14 21&#8203;:29&#8203;:50 2011\, comdog wrote&#8203;:
> On Wed Apr 13 09&#8203;:54&#8203;:11 2011\, tom christiansen wrote&#8203;:
> > I never used perldoc\, just normal tools\, so I never noticed its
> output
> > is
> > bollocksed up\.  Thanks you Brian for pointing this out\.  The dumb
> > thing is
> > committing a double\-encoding faux pas&#8203;:
> 
> I started to look at this and didn't immediately see where the problem
> could be\. I'm a bit
> swamped right now\, but as I have time\, I want to go step\-by\-step to
> ensure that each thing is
> respecting the data passed to it\.
> 
> Along with that\, I want to make all of the core Perl docs use UTF\-8 as
> the encoding\. If they are
> ASCII now\, that shouldn't change anything\. The trick is then making
> the Pod tools recognize and
> respect the encoding \(even if it is something other than UTF\-8\)\.


Tom\, brian&#8203;:  Would it be possible to get an update on the status of the
issues discussed in this ticket?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From @dcollinsn

On Fri Feb 15 19&#8203;:12&#8203;:46 2013\, jkeenan wrote&#8203;:
> Tom\, brian&#8203;:  Would it be possible to get an update on the status of the
> issues discussed in this ticket?
> 
> Thank you very much\.
> Jim Keenan

I'm having some trouble duplicating this\. The hyphen that Tom's testcase shows isn't a unicode character under any of the versions of perl/perldoc I tested\. In old 5\.14ish versions\, I found this inconsistency&#8203;:

$ PERL\_UNICODE=0 perl\-5\.14\.0/bin/perldoc perlunicode | grep "returns true if the" | uniquote \-v
&nbsp;       \\N\{MIDDLE DOT\}   "DO\_UTF8\(sv\)" returns true if the "UTF8" flag is on and the bytes
&nbsp;           pragma is not in effect\.  "SvUTF8\(sv\)" returns true if the "UTF8"
&nbsp;       \\N\{MIDDLE DOT\}   is\_utf8\_char\(s\) returns true if the pointer points to a valid UTF\-8
$ PERL\_UNICODE=S perl\-5\.14\.0/bin/perldoc perlunicode | grep "returns true if the" | uniquote \-v
&nbsp;       \\N\{LATIN CAPITAL LETTER A WITH CIRCUMFLEX\}\\N\{MIDDLE DOT\}   "DO\_UTF8\(sv\)" returns true if the "UTF8" flag is on and the bytes
&nbsp;           pragma is not in effect\.  "SvUTF8\(sv\)" returns true if the "UTF8"
&nbsp;       \\N\{LATIN CAPITAL LETTER A WITH CIRCUMFLEX\}\\N\{MIDDLE DOT\}   is\_utf8\_char\(s\) returns true if the pointer points to a valid UTF\-8

But that's just a literal \* in newer versions\. Does anyone know if this is still a potential issue?


\-\- 
Respectfully\,
Dan Collins

**Comment by khwilliamson** [comment]
This no longer occurs
