### ISSUE TITLE
No die on open pipe to unknown program

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#11407]
Migrated from [rt.perl.org#92220](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=92220) (status was 'open')

Searchable as RT92220$

**Comment by p5pRT** [comment]
### From nmqrstx-18@yahoo.de

Hi\,

Perl\-Version

This is perl\, v5\.6\.1 built for MSWin32\-x86\-multi\-thread
\(with 1 registered patch\, see perl \-V for more detail\)

Copyright 1987\-2001\, Larry Wall

Binary build 638 provided by ActiveState Corp\. http&#8203;://www\.ActiveState\.com
ActiveState is a division of Sophos\.
Built Apr 13 2004 19&#8203;:24&#8203;:21

Perl may be copied only under the terms of either the Artistic License or 
the
GNU General Public License\, which may be found in the Perl 5 source kit\.

Complete documentation for Perl\, including FAQ lists\, should be found on
this system using \`man perl' or \`perldoc perl'\.  If you have access to the
Internet\, point your browser at http&#8203;://www\.perl\.com/\, the Perl Home Page\.

OS&#8203;: Win32 XP 5\.1 SP "


Issue&#8203;:

expecting&#8203;: die


my $fh = undef;
open $fh\, "|/usr/sbin/sendmehl \-t" or die "Fehler&#8203;: $\!";
print "go on\.\.\.\."; \# no die\!?

No die\(\) but a error\-Message from OS&#8203;:
Der Befehl "/usr/sbin/sendmehl" ist entweder falsch geschrieben oder
konnte nicht gefunden werden\.
go on\.\.\.\.

Thats all\, thank you\!

Rolf

http&#8203;://rolfrost\.de/

**Comment by p5pRT** [comment]
### From @abigail




5\.6\.1 is a very old Perl; released over a decade ago\. 5\.14 is the current
version\, with 5\.12 the only other major version that is still supported\.

Having said that\, I cannot reproduce this using 5\.6\.2 \(but I'm using a
different platform\)\.

Can you reproduce your error on 5\.14?



Abigail

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @ikegami

On Sat\, Jun 4\, 2011 at 8&#8203;:16 PM\, Abigail \<abigail@&#8203;abigail\.be> wrote&#8203;:

> On Sat\, Jun 04\, 2011 at 11&#8203;:50&#8203;:47AM \-0700\, Rolf Rost wrote&#8203;:
> > \# New Ticket Created by  "Rolf Rost"
> > \# Please include the string&#8203;:  \[perl \#92220\]
> > \# in the subject line of all future correspondence about this issue\.
> > \# \<URL&#8203;: http&#8203;://rt\.perl\.org/rt3/Ticket/Display\.html?id=92220 >
> >
> >
> > Hi\,
> >
> > Perl\-Version
> >
> > This is perl\, v5\.6\.1 built for MSWin32\-x86\-multi\-thread
> > \(with 1 registered patch\, see perl \-V for more detail\)
> >
> > Copyright 1987\-2001\, Larry Wall
> >
> > Binary build 638 provided by ActiveState Corp\.
> http&#8203;://www\.ActiveState\.com
> > ActiveState is a division of Sophos\.
> > Built Apr 13 2004 19&#8203;:24&#8203;:21
> >
> > Perl may be copied only under the terms of either the Artistic License or
> > the
> > GNU General Public License\, which may be found in the Perl 5 source kit\.
> >
> > Complete documentation for Perl\, including FAQ lists\, should be found on
> > this system using \`man perl' or \`perldoc perl'\.  If you have access to
> the
> > Internet\, point your browser at http&#8203;://www\.perl\.com/\, the Perl Home
> Page\.
> >
> > OS&#8203;: Win32 XP 5\.1 SP "
> >
> >
> > Issue&#8203;:
> >
> > expecting&#8203;: die
> >
> >
> > my $fh = undef;
> > open $fh\, "|/usr/sbin/sendmehl \-t" or die "Fehler&#8203;: $\!";
> > print "go on\.\.\.\."; \# no die\!?
> >
> > No die\(\) but a error\-Message from OS&#8203;:
> > Der Befehl "/usr/sbin/sendmehl" ist entweder falsch geschrieben oder
> > konnte nicht gefunden werden\.
> > go on\.\.\.\.
>
>
>
>
> 5\.6\.1 is a very old Perl; released over a decade ago\. 5\.14 is the current
> version\, with 5\.12 the only other major version that is still supported\.
>
> Having said that\, I cannot reproduce this using 5\.6\.2 \(but I'm using a
> different platform\)\.
>
> Can you reproduce your error on 5\.14?
>

On Windows\, the single\-argument form of C\<system> invokes the shell if the
program is not found\, even if the command contains no special characters\.

>perl \-E"system\('inexistant'\); say $?"
'inexistant' is not recognized as an internal or external command\,
operable program or batch file\.
256

This allows shell builtins \(dir\, copy\) to be callable as executables\.

>perl \-E"system\('dir'\); say $?"
 Volume in drive C has no label\.
 Volume Serial Number is 080E\-1D03
\.\.\.
0

C\<open> pipes appear to work the same way\.

>perl \-E"open my $fh\, 'nonexistant |' or die $\!; print while \<$fh>;
close\($fh\); say $?"
'nonexistant' is not recognized as an internal or external command\,
operable program or batch file\.
256

>perl \-E"open my $fh\, 'dir |' or die $\!; print while \<$fh>; close\($fh\); say
$?"
 Volume in drive C has no label\.
 Volume Serial Number is 080E\-1D03
\.\.\.
0

**Comment by p5pRT** [comment]
### From @ikegami

On Sat\, Jun 4\, 2011 at 2&#8203;:50 PM\, Rolf Rost \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:

>
> Issue&#8203;:
>
> expecting&#8203;: die
>
>
> my $fh = undef;
> open $fh\, "|/usr/sbin/sendmehl \-t" or die "Fehler&#8203;: $\!";
> print "go on\.\.\.\."; \# no die\!?
>
> No die\(\) but a error\-Message from OS&#8203;:
>

It didn't die because the child\, a shell\, was successfully launched\.

You don't detect the error because you didn't check if the child succeeded
or not\. \(C\<close\($fh\); die if $?;>\)\.

**Comment by p5pRT** [comment]
### From @ikegami

On Sat\, Jun 4\, 2011 at 8&#8203;:16 PM\, Abigail \<abigail@&#8203;abigail\.be> wrote&#8203;:

> Having said that\, I cannot reproduce this using 5\.6\.2 \(but I'm using a different platform\)\.

Try running a command with C\<"> in it\.

$ perl \-E'open\(my $fh\, q\{|foo "bar"\}\) or die "open&#8203;: $\!"; close\($fh\); die
"foo&#8203;: $?" if $?;'
sh&#8203;: \./foo&#8203;: Permission denied
foo&#8203;: 32256 at \-e line 1\.

**Comment by p5pRT** [comment]
### From @cpansprout

On Sat Jun 04 21&#8203;:52&#8203;:50 2011\, ikegami@&#8203;adaelis\.com wrote&#8203;:
> On Sat\, Jun 4\, 2011 at 8&#8203;:16 PM\, Abigail \<abigail@&#8203;abigail\.be> wrote&#8203;:
> 
> > Having said that\, I cannot reproduce this using 5\.6\.2 \(but I'm using a
> >
> different platform\)\.
> >
> 
> Try running a command with C\<"> in it\.
> 
> $ perl \-E'open\(my $fh\, q\{|foo "bar"\}\) or die "open&#8203;: $\!"; close\($fh\); die
> "foo&#8203;: $?" if $?;'
> sh&#8203;: \./foo&#8203;: Permission denied
> foo&#8203;: 32256 at \-e line 1\.

Does that mean this is not a bug?

**Comment by p5pRT** [comment]
### From @ikegami

On Sun\, Jun 5\, 2011 at 4&#8203;:47 PM\, Father Chrysostomos via RT \<
perlbug\-followup@&#8203;perl\.org> wrote&#8203;:

> Does that mean this is not a bug?
>

This is a discrepancy with the docs\. From C\<exec>\,

If there is only one scalar argument or an array with one element in it\, the
argument is checked for shell metacharacters\, and if there are any\, the
entire argument is passed to the system's command shell for parsing \(this is
C\</bin/sh \-c> on Unix platforms\, but varies on other platforms\)\. If there
are no shell metacharacters in the argument\, it is split into words and
passed directly to C\<execvp>\, which is more efficient\.

There is no shell meta characters in the OP's example\, yet a shell is used\.
This can be viewed as a documentation bug\, in which case the docs could be
adjusted to read&#8203;:

If there is only one scalar argument or an array with one element in it\, the
entire argument is passed to the system's command shell for parsing \(this is
C\</bin/sh \-c> on Unix platforms\, but varies on other platforms\)\. If there
are no shell metacharacters in the argument\, it may be split into words and
passed directly to C\<execvp> instead\, which is more efficient

But it could also be viewed as a code bug\. Does anyone have an opinion? I
don't\.

Note that the observed behaviour is probably a side\-effect of the bug where
the shell can be invoked for multi\-arg system calls\.

\# Executes 'dir' even though it shouldn't\.
perl \-e"system\('dir'\, '/b'\);"

\# At least this returns an error as it should
perl \-e"system \{ 'dir' \} 'dir'\, '/b';"

\(Tested recently\, but not on my Windows machine right now\.\)

**Comment by toddr** [comment]
I get this on linux
```
perl -E'open(my $fh, q{|foo "bar"}) or die "open: $!"; close($fh); die "foo: $?" if $?;'      
sh: foo: command not found
foo: 32512 at -e line 1.
```

**Comment by richardleach** [comment]
Win 10, Strawb 5.30:

Executes 'dir' even though it shouldn't.
perl -e"system('dir', '/b');"

Doesn't exec 'dir' (or at least output any results) but doesn't return an error either
perl -e"system { 'dir' } 'dir', '/b';"

**Comment by ikegami** [comment]
> I get this on linux
> 
> ```
> perl -E'open(my $fh, q{|foo "bar"}) or die "open: $!"; close($fh); die "foo: $?" if $?;'      
> sh: foo: command not found
> foo: 32512 at -e line 1.
> ```

The matter at hand is 1) specific to Windows, and 2) specific to commands with no shell metacharacters.

The behaviour observed by the OP is intentional in order to make built-in shell commands like `dir`  and `copy` appear to be utilities.

The only issue is perhaps one of documentation.

The docs for `open "|..."` and `open "...|"` are so vague as to not have any problems.

The docs for `system` address the issue by stating the following:

>  On Windows, only the `system PROGRAM LIST` syntax will reliably avoid using the shell; `system LIST`, even with more than one element, will fall back to the shell if the first spawn fails.

This passage is missing from the docs for `exec`. But then again, `exec` doesn't really exist on Windows.

Options:

1) Copy the passage from the docs for `system` to the docs for `exec`.

2) Close the ticket with no change because `exec` is already subject to YMMV on Windows since it's emulated on Windows.

I vote for the latter.

**Comment by toddr** [comment]
I do too. If someone disagrees we can re-open it.
