### ISSUE TITLE
4 pod casemapping errors: s/(\w+)/\u\L$1/g is always wrong

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#11568]
Migrated from [rt.perl.org#96592](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=96592) (status was 'open')

Searchable as RT96592$

**Comment by p5pRT** [comment]
### From tchrist@perl.com

These are all in error&#8203;:

&nbsp;    perldata\.pod&#8203;:        s/\(\\w\+\)/\\u\\L$1/g;   \# "titlecase" words
&nbsp;    perlfaq4\.pod&#8203;:    $string =~ s/\(\[\\w'\]\+\)/\\u\\L$1/g;
&nbsp;    perlop\.pod&#8203;:    substr\($str\, \-30\) =~ s/\\b\(\\p\{Alpha\}\+\)\\b/\\u\\L$1/g;
&nbsp;    perlretut\.pod&#8203;:string\. The regexps C\<\\L\\u$word> or C\<\\u\\L$word> convert the first

They don't work because you cannot guarantee a correct titlecase
mapping if you first send it through lowercase\.  There are no 
roundtrip guarantees with Unicode casemapping\.

Here are two places where you get an error doing it the way
the pods erroneously suggest\, but there are others&#8203;:

&nbsp;    orig  => İ is 0130
&nbsp;       lc => i̇ is 0069\.0307
&nbsp;    tc    => İ is 0130
&nbsp;    tc lc => İ is 0049\.0307     \(wrong answer\)

&nbsp;    orig  => ẞ is 1E9E
&nbsp;       lc => ß is 00DF
&nbsp;    tc    => ẞ is 1E9E
&nbsp;    tc lc => Ss is 0053\.0073    \(wrong answer\)

The correct approach requires something more like

&nbsp;    s/\\b\(\\w\)\(\\w\*\)\\b/\\u$1\\L$2/g;  \# "titlecase" "words"

Because casemapA\(string\) is never guaranteed to be the
same as casemapA\(casemapB\(string\)\)\.  

\-\-tom

\#\!/usr/bin/env perl

use utf8;

use v5\.14;
use strict;
use warnings;
use open qw\(&#8203;:std :encoding\(UTF\-8\)\);
use charnames qw\(&#8203;:full\);

my @&#8203;chars = \(
&nbsp;    "\\N\{LATIN CAPITAL LETTER I WITH DOT ABOVE\}"\,
&nbsp;    "\\N\{GREEK CAPITAL THETA SYMBOL\}"\,
&nbsp;    "\\N\{LATIN CAPITAL LETTER SHARP S\}"\,
&nbsp;    "\\N\{OHM SIGN\}"\,
&nbsp;    "\\N\{KELVIN SIGN\}"\,
&nbsp;    "\\N\{ANGSTROM SIGN\}"\,

&nbsp;    "\\N\{LATIN SMALL LETTER SHARP S\}"\,
&nbsp;    "\\N\{GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI\}"\,
&nbsp;    "\\N\{LATIN SMALL LIGATURE FF\}"\,
&nbsp;    "\\N\{LATIN SMALL LIGATURE FFI\}"\,
&nbsp;    "\\N\{LATIN SMALL LIGATURE LONG S T\}"\,
&nbsp;    "\\N\{LATIN SMALL LIGATURE ST\}"\,
\);

sub report\($$;$\) \{ 
&nbsp;    my \($what\, $str\, $ok\) = @&#8203;\_;
&nbsp;    my $mask = "%\-5s => %\-3s is %v04X\\n";
&nbsp;    if \(@&#8203;\_ == 3\) \{
&nbsp;        $mask =~ s/\\n/\\t%s\\n/;
&nbsp;    \} 
&nbsp;    printf $mask\, $what\, \($str\) x 2\, $ok;
\}

for my $char \(@&#8203;chars\) \{
&nbsp;    my $lc         =         lc $char;
&nbsp;    my $tc\_good    = ucfirst    $char;
&nbsp;    my $tc\_bad\_lc  = ucfirst lc $char;
&nbsp;    my $tc\_bad\_uc  = ucfirst uc $char;

&nbsp;    report "orig " => $char;
&nbsp;    report "   lc" => $lc;
&nbsp;    report "tc   " => $tc\_good\,   "real";
&nbsp;    report "tc lc" => $tc\_bad\_lc\, \($tc\_good eq $tc\_bad\_lc\) ? "RIGHT" : "WRONG";
&nbsp;    report "tc uc" => $tc\_bad\_uc\, \($tc\_good eq $tc\_bad\_uc\) ? "RIGHT" : "WRONG";
&nbsp;    print "\\n";
\}

\_\_END\_\_

Summary of my perl5 \(revision 5 version 14 subversion 0\) configuration&#8203;:
&nbsp;   
&nbsp;  Platform&#8203;:
&nbsp;    osname=openbsd\, osvers=4\.4\, archname=OpenBSD\.i386\-openbsd
&nbsp;    uname='openbsd chthon 4\.4 generic\#0 i386 '
&nbsp;    config\_args='\-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
&nbsp;    usemymalloc=y\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'\,
&nbsp;    optimize='\-O2'\,
&nbsp;    cppflags='\-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='3\.3\.5 \(propolice\)'\, gccosandvers='openbsd4\.4'
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags ='\-Wl\,\-E  \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib
&nbsp;    libs=\-lgdbm \-lm \-lutil \-lc
&nbsp;    perllibs=\-lm \-lutil \-lc
&nbsp;    libc=/usr/lib/libc\.so\.48\.0\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags='\-DPIC \-fPIC '\, lddlflags='\-shared \-fPIC  \-L/usr/local/lib \-fstack\-protector'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: MYMALLOC PERL\_DONT\_CREATE\_GVSV PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV USE\_LARGE\_FILES USE\_PERLIO
&nbsp;                        USE\_PERL\_ATOF
&nbsp;  Built under openbsd
&nbsp;  Compiled at Jun 11 2011 11&#8203;:48&#8203;:28
&nbsp;  %ENV&#8203;:
&nbsp;    PERL\_UNICODE="SA"
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.14\.0/OpenBSD\.i386\-openbsd
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.14\.0
&nbsp;    /usr/local/lib/perl5/5\.14\.0/OpenBSD\.i386\-openbsd
&nbsp;    /usr/local/lib/perl5/5\.14\.0
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.12\.3
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.11\.3
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.10\.1
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.10\.0
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.8\.7
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.8\.0
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.6\.0
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.005
&nbsp;    /usr/local/lib/perl5/site\_perl
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @jkeenan

On Mon Aug 08 16&#8203;:17&#8203;:27 2011\, tom christiansen wrote&#8203;:
> These are all in error&#8203;:
> 
>     perldata\.pod&#8203;:        s/\(\\w\+\)/\\u\\L$1/g;   \# "titlecase" words

The first error could simply be deleted\, as the feature which it is
documenting has nothing to do with \\u\\L\.

>     perlfaq4\.pod&#8203;:    $string =~ s/\(\[\\w'\]\+\)/\\u\\L$1/g;
>     perlop\.pod&#8203;:    substr\($str\, \-30\) =~ s/\\b\(\\p\{Alpha\}\+\)\\b/\\u\\L$1/g;
>     perlretut\.pod&#8203;:string\. The regexps C\<\\L\\u$word> or C\<\\u\\L$word>
> convert the first
> 
> They don't work because you cannot guarantee a correct titlecase
> mapping if you first send it through lowercase\.  There are no
> roundtrip guarantees with Unicode casemapping\.
> 
> Here are two places where you get an error doing it the way
> the pods erroneously suggest\, but there are others&#8203;:
> 
>     orig  => İ is 0130
>        lc => i̇ is 0069\.0307
>     tc    => İ is 0130
>     tc lc => İ is 0049\.0307     \(wrong answer\)
> 
>     orig  => ẞ is 1E9E
>        lc => ß is 00DF
>     tc    => ẞ is 1E9E
>     tc lc => Ss is 0053\.0073    \(wrong answer\)
> 
> The correct approach requires something more like
> 
>     s/\\b\(\\w\)\(\\w\*\)\\b/\\u$1\\L$2/g;  \# "titlecase" "words"
> 
> Because casemapA\(string\) is never guaranteed to be the
> same as casemapA\(casemapB\(string\)\)\.
> 
> \-\-tom
> 
> \#\!/usr/bin/env perl
> 
> use utf8;
> 
> use v5\.14;
> use strict;
> use warnings;
> use open qw\(&#8203;:std :encoding\(UTF\-8\)\);
> use charnames qw\(&#8203;:full\);
> 
> my @&#8203;chars = \(
>     "\\N\{LATIN CAPITAL LETTER I WITH DOT ABOVE\}"\,
>     "\\N\{GREEK CAPITAL THETA SYMBOL\}"\,
>     "\\N\{LATIN CAPITAL LETTER SHARP S\}"\,
>     "\\N\{OHM SIGN\}"\,
>     "\\N\{KELVIN SIGN\}"\,
>     "\\N\{ANGSTROM SIGN\}"\,
> 
>     "\\N\{LATIN SMALL LETTER SHARP S\}"\,
>     "\\N\{GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI\}"\,
>     "\\N\{LATIN SMALL LIGATURE FF\}"\,
>     "\\N\{LATIN SMALL LIGATURE FFI\}"\,
>     "\\N\{LATIN SMALL LIGATURE LONG S T\}"\,
>     "\\N\{LATIN SMALL LIGATURE ST\}"\,
> \);
> 
> sub report\($$;$\) \{
>     my \($what\, $str\, $ok\) = @&#8203;\_;
>     my $mask = "%\-5s => %\-3s is %v04X\\n";
>     if \(@&#8203;\_ == 3\) \{
>         $mask =~ s/\\n/\\t%s\\n/;
>     \}
>     printf $mask\, $what\, \($str\) x 2\, $ok;
> \}
> 
> for my $char \(@&#8203;chars\) \{
>     my $lc         =         lc $char;
>     my $tc\_good    = ucfirst    $char;
>     my $tc\_bad\_lc  = ucfirst lc $char;
>     my $tc\_bad\_uc  = ucfirst uc $char;
> 
>     report "orig " => $char;
>     report "   lc" => $lc;
>     report "tc   " => $tc\_good\,   "real";
>     report "tc lc" => $tc\_bad\_lc\, \($tc\_good eq $tc\_bad\_lc\) ? "RIGHT" :
> "WRONG";
>     report "tc uc" => $tc\_bad\_uc\, \($tc\_good eq $tc\_bad\_uc\) ? "RIGHT" :
> "WRONG";
>     print "\\n";
> \}
> 

Can anyone provide a documentation patch?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by khwilliamson** [comment]
It seems to me the pods should just say, for example

>  perldata.pod​: s/(\w+)/\u$1/g; # "titlecase" words

instead of what it now says

>  perldata.pod​: s/(\w+)/\u\L$1/g; # "titlecase" words

Tom's approach is overly complicated.  `\u` titlecases the word, which is what is desired

**Comment by Grinnz** [comment]
\u will uppercase the first character, but it will leave the rest unchanged. if you want titlecase you normally want the rest lowercased which the \L does first

**Comment by khwilliamson** [comment]
Ok
