### ISSUE TITLE
timeout problem in IO::Socket

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#1197]
Migrated from [rt.perl.org#2167](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=2167) (status was 'resolved')

Searchable as RT2167$

**Comment by p5pRT** [comment]
### From wilfredm@inet.kpn.com

#### Created by wmollenvanger@yahoo.com


The LWP library I'm using had problems with defined timeouts so I traced
it
back to IO&#8203;::Socket&#8203;::connect&#8203;:

sub connect \{
&nbsp;    @&#8203;\_ == 2 || @&#8203;\_ == 3 or croak 'usage&#8203;: $fh\->connect\(NAME\) or
$fh\->connect\(PORT\, ADDR\)';
&nbsp;    my $fh = shift;
&nbsp;    my $addr = @&#8203;\_ == 1 ? shift : sockaddr\_in\(@&#8203;\_\);
&nbsp;    my $timeout = $\{\*$fh\}\{'io\_socket\_timeout'\};
&nbsp;    local\($SIG\{ALRM\}\) = $timeout ? sub \{ undef $fh; \}
&nbsp;                                 : $SIG\{ALRM\} || 'DEFAULT';

&nbsp;     eval \{
&nbsp;        croak 'connect&#8203;: Bad address'
&nbsp;            if\(@&#8203;\_ == 2 && \!defined $\_\[1\]\);

&nbsp;        if\($timeout\) \{
&nbsp;            defined $Config\{d\_alarm\} && defined alarm\($timeout\) or
&nbsp;                $timeout = 0;
&nbsp;        \}

&nbsp;        my $ok = connect\($fh\, $addr\);

&nbsp;        alarm\(0\)
&nbsp;            if\($timeout\);

&nbsp;        croak "connect&#8203;: timeout"
&nbsp;            unless defined $fh;

&nbsp;        undef $fh unless $ok;
&nbsp;    \};

&nbsp;    $fh;
\}

Shouldn't the line were the signal handler is defined read&#8203;:

local\($SIG\{ALRM\}\) = $timeout ? sub \{ undef $fh; die; \}
&nbsp;                                 : $SIG\{ALRM\} || 'DEFAULT';


otherwise it will 'never' timeout on the connect\(\) call\.


Regards\,

Wilfred\.

<details><summary>Perl Info</summary>

```


Site configuration information for perl 5.00503:

Configured by root at Mon Aug 30 23:08:56 EDT 1999.

Summary of my perl5 (5.0 patchlevel 5 subversion 3) configuration:
  Platform:
    osname=linux, osvers=2.2.5-22smp, archname=i386-linux
    uname='linux porky.devel.redhat.com 2.2.5-22smp #1 smp wed jun 2
09:11:51 edt 1999 i686 unknown '
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef useperlio=undef d_sfio=undef
  Compiler:
    cc='cc', optimize='-O2', gccversion=egcs-2.91.66 19990314/Linux
(egcs-1.1.2
release)
    cppflags='-Dbool=char -DHAS_BOOL -I/usr/local/include'
    ccflags ='-Dbool=char -DHAS_BOOL -I/usr/local/include'
    stdchar='char', d_stdstdio=undef, usevfork=false
    intsize=4, longsize=4, ptrsize=4, doublesize=8
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -ldl -lm -lc -lposix -lcrypt
    libc=, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'

    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:



@INC for perl 5.00503:
    /usr/lib/perl5/5.00503/i386-linux
    /usr/lib/perl5/5.00503
    /usr/lib/perl5/site_perl/5.005/i386-linux
    /usr/lib/perl5/site_perl/5.005
    .


Environment for perl 5.00503:
    HOME=/export/home/wilfredm
    LANG=en_US
    LANGUAGE (unset)
    LC_ALL=en_US
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)

PATH=/usr/bin:/bin:/usr/X11R6/bin:/usr/local/bin:/opt/bin:/usr/X11R6/bin:/export/home/wilfredm/bin:/usr/local/ssh/bin:

    PERL_BADLANG (unset)
    SHELL=/bin/bash





```
</details>

**Comment by p5pRT** [comment]
### From @gisle

Wilfred Mollenvanger \<wilfredm@&#8203;inet\.kpn\.com> writes&#8203;:

> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> The LWP library I'm using had problems with defined timeouts so I traced
> it back to IO&#8203;::Socket&#8203;::connect&#8203;:
> 
> sub connect \{
>     @&#8203;\_ == 2 || @&#8203;\_ == 3 or croak 'usage&#8203;: $fh\->connect\(NAME\) or
> $fh\->connect\(PORT\, ADDR\)';
>     my $fh = shift;
>     my $addr = @&#8203;\_ == 1 ? shift : sockaddr\_in\(@&#8203;\_\);
>     my $timeout = $\{\*$fh\}\{'io\_socket\_timeout'\};
>     local\($SIG\{ALRM\}\) = $timeout ? sub \{ undef $fh; \}
>                                  : $SIG\{ALRM\} || 'DEFAULT';
> 
>      eval \{
>         croak 'connect&#8203;: Bad address'
>             if\(@&#8203;\_ == 2 && \!defined $\_\[1\]\);
> 
>         if\($timeout\) \{
>             defined $Config\{d\_alarm\} && defined alarm\($timeout\) or
>                 $timeout = 0;
>         \}
> 
>         my $ok = connect\($fh\, $addr\);
> 
>         alarm\(0\)
>             if\($timeout\);
> 
>         croak "connect&#8203;: timeout"
>             unless defined $fh;
> 
>         undef $fh unless $ok;
>     \};
> 
>     $fh;
> \}
> 
> Shouldn't the line were the signal handler is defined read&#8203;:
> 
> local\($SIG\{ALRM\}\) = $timeout ? sub \{ undef $fh; die; \}
>                                  : $SIG\{ALRM\} || 'DEFAULT';
> 
> 
> otherwise it will 'never' timeout on the connect\(\) call\.

The latest version of IO&#8203;::Socket\, which is bundled with perl5\.5\.650
\(perl's latest development release\) will use non\-blocking connect
instead of alarm\.  You can can achieve the same with perl5\.005\_03 by
installing IO\-1\.20 from CPAN\.

I don't know if perl5\.005\_04 if/when it comes out will try to upgrade
the IO modules\, but I doubt it\.

Regards\,
Gisle

**Comment by hell288** [comment]
Duplicate of #23815
