### ISSUE TITLE
DynaLoader behavior w.r.t. LD_LIBRARY_PATH confuses me

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#1200]
Migrated from [rt.perl.org#2170](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=2170) (status was 'open')

Searchable as RT2170$

**Comment by p5pRT** [comment]
### From joseph@cscaper.com

#### Created by joseph@5sigma.com



DynaLoader on solaris 7 seems to ignore libpth and follow LD\_LIBRARY\_PATH
instead\.  I discovered this when some CGI programs of mine using a new
version of mysql began to fail when execute by the server \(as nobody\)
because of mysql's affection for libz\.so\.  I had libz\.so in /usr/local/lib\,
and I see the following in DynaLoader on that machine&#8203;:

&nbsp;  push\(@&#8203;dl\_library\_path\, split\(' '\, '/usr/local/lib /lib /usr/lib'\)\);

Nevertheless\, libz\.so was never found unless LD\_LIBRARY\_PATH was set\.  I
wound up having to symlink libz\.so into /lib\.  I tried a couple of other
things&#8203;:

&nbsp;  BEGIN \{ $ENV\{LD\_LIBRARY\_PATH\} = "/usr/local/lib" \}

for example\, but that didn't seem to have any effect\.

I must be missing something here\.  Is there a way other than LD\_LIBRARY\_PATH
to specify a run\-time loading path for Perl modules on Solaris?  If so\,
what is it?

Do @&#8203;dl\_library\_path and/or libpth have ANYTHING to do with how DynaLoader
actually works on Solaris?

\(Please reply via email\-\-was dropped from p5p a while ago when I had
a couple of ~1 day net outages\, and haven't bothered to resubscribe\.\)

&nbsp;  \-joseph

\-\-
Joseph N\. Hall\, 5 Sigma Productions        mailto&#8203;:" \<joseph> "@&#8203;5sigma\.com
Author\, Effective Perl Programming \. \. \. \. \. http&#8203;://www\.effectiveperl\.com
Perlfaq Prime  \. \. \. \. \. \. \. \. \. \. \. \. \. \. \. \. \. \. http&#8203;://www\.perlfaq\.com

<details><summary>Perl Info</summary>

```


Site configuration information for perl 5.00502:

Configured by root at Thu Dec 31 02:40:42 MST 1998.

Summary of my perl5 (5.0 patchlevel 5 subversion 2) configuration:
  Platform:
    osname=solaris, osvers=2.7, archname=sun4-solaris
    uname='sunos rom 5.7 generic sun4u sparc sunw,ultrasparc-iii-engine '
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef useperlio=undef d_sfio=undef
  Compiler:
    cc='gcc -B/usr/ccs/bin/', optimize='-O', gccversion=egcs-2.91.60 19981201 (egcs-1.1.1 release)
    cppflags='-I/usr/local/include'
    ccflags ='-I/usr/local/include'
    stdchar='char', d_stdstdio=define, usevfork=false
    intsize=4, longsize=4, ptrsize=4, doublesize=8
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    alignbytes=8, usemymalloc=y, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lsocket -lnsl -lgdbm -ldl -lm -lc -lcrypt
    libc=/lib/libc.so, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags=' '
    cccdlflags='-fPIC', lddlflags='-G -L/usr/local/lib'

Locally applied patches:
    


@INC for perl 5.00502:
    /usr/local/lib/perl5/5.00502/sun4-solaris
    /usr/local/lib/perl5/5.00502
    /usr/local/lib/perl5/site_perl/5.005/sun4-solaris
    /usr/local/lib/perl5/site_perl/5.005
    .


Environment for perl 5.00502:
    HOME=/home/joseph
    LANG (unset)
    LD_LIBRARY_PATH=/usr/lang/SC1.0:/usr/local/lib:/usr/lib:/usr/openwin/lib
    LOGDIR (unset)
    PATH=.:/usr/local/bin:/usr/ucb:/bin:/usr/bin:/usr/5bin:/etc:/usr/etc:/usr/lang:/usr/ccs/bin:/usr/sbin:/usr/X11/bin:/usr/openwin/bin:/usr/local/framemaker/bin:/usr/local/pbmplus/bin:/usr/local/games/bin
    PERL_BADLANG (unset)
    SHELL=/bin/tcsh


```
</details>

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

joseph@&#8203;cscaper\.com \[joseph@&#8203;cscaper\.com\] quoth&#8203;:
\*>
\*>DynaLoader on solaris 7 seems to ignore libpth and follow LD\_LIBRARY\_PATH
\*>instead\.  I discovered this when some CGI programs of mine using a new
\*>version of mysql began to fail when execute by the server \(as nobody\)
\*>because of mysql's affection for libz\.so\.  I had libz\.so in /usr/local/lib\,
\*>and I see the following in DynaLoader on that machine&#8203;:


I don't think this is a bug as I've seen this behaviour before\.\.\.From the
Dynaloader docs;

"@&#8203;dl\_library\_path

The standard/default list of directories in which
dl\_findfile\(\) will search for libraries etc\. Directories are searched in
order&#8203;: $dl\_library\_path\[0\]\, \[1\]\, \.\.\. etc 

@&#8203;dl\_library\_path is initialised to hold the list of 'normal'
directories \(/usr/lib\, etc\) determined by Configure \($Config\{'libpth'\}\)\.
This should ensure portability across a wide range of platforms\. 

@&#8203;dl\_library\_path should also be initialised with any other
directories that can be determined from the environment at runtime \(such
as LD\_LIBRARY\_PATH for SunOS\)\. 

After initialisation @&#8203;dl\_library\_path can be manipulated by
an application using push and unshift before calling dl\_findfile\(\)\.
Unshift can be used to add directories to the front of the search
order either to save search time or to override libraries with the same
name in the 'normal' directories\. 

The load function that dl\_load\_file\(\) calls may require an
absolute pathname\. The dl\_findfile\(\) function and @&#8203;dl\_library\_path can
be used to search for and return the absolute pathname for
the library/object that you wish to load\."
 
Also\, I've seen; 
"mysqld restarted on  Wed Jan 19 00&#8203;:13&#8203;:37 CST 2000
mysqld started on  Wed Jan 19 23&#8203;:44&#8203;:58 CST 2000
ld\.so\.1&#8203;: /pkg/usr\-local/mysql/libexec/mysqld&#8203;: fatal&#8203;: libz\.so&#8203;: open failed&#8203;:
No such file or directory"

But this was after I built a new version of mySQL and forgot to compile it
statically so that I needed to set LD\_LIBRARY\_PATH on start\-up\.

So\, it would appear to be a 'feature' with mySQL\.

e\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Elaine \-HFB\- Ashton writes&#8203;:
> 
> joseph@&#8203;cscaper\.com \[joseph@&#8203;cscaper\.com\] quoth&#8203;:
> \*>
> \*>DynaLoader on solaris 7 seems to ignore libpth and follow LD\_LIBRARY\_PATH
> \*>instead\.  I discovered this when some CGI programs of mine using a new
> \*>version of mysql began to fail when execute by the server \(as nobody\)
> \*>because of mysql's affection for libz\.so\.  I had libz\.so in /usr/local/lib\,
> \*>and I see the following in DynaLoader on that machine&#8203;:
> 
> 
> I don't think this is a bug as I've seen this behaviour before\.\.\.From the
> Dynaloader docs;
> 
> "@&#8203;dl\_library\_path

To make the long story short&#8203;: @&#8203;dl\_library\_path is used \*by Perl\* to
find an extension DLL\.  After DLL is found\, it is being loaded\.  But
this DLL \*in turn\* may require loading of other DLLs \- and now this
loading is done by the system\, not by Perl\.

Thus during to loading of this "chained" DLLs the value of
@&#8203;dl\_library\_path is not relevant\.

Ilya

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

How did you wind up replying to joseph@&#8203;cscaper\.com?  As I recall\, I
used "joseph@&#8203;5sigma\.com" for BOTH perlbug addresses\.  Is this a
bug in perlbug?

\(Obviously\, mail to joseph@&#8203;cscaper\.com gets a bounce message and
goes into my spam bucket\.\)

&nbsp;  \-joseph

\-\-
Joseph N\. Hall\, 5 Sigma Productions        mailto&#8203;:" \<joseph> "@&#8203;5sigma\.com
Author\, Effective Perl Programming \. \. \. \. \. http&#8203;://www\.effectiveperl\.com
Perlfaq Prime  \. \. \. \. \. \. \. \. \. \. \. \. \. \. \. \. \. \. http&#8203;://www\.perlfaq\.com

On Mon\, 21 Feb 2000 13&#8203;:32&#8203;:50 \-0600 elaine@&#8203;chaos\.wustl\.edu \(Elaine \-HFB\- Ashton\)
wrote&#8203;:

\* Return\-Path&#8203;: \<elaine@&#8203;history\.perl\.org>
\* Delivered\-To&#8203;: joseph@&#8203;cscaper\.com
\* Received&#8203;: \(qmail 29580 invoked from network\); 21 Feb 2000 19&#8203;:35&#8203;:54 \-0000
\* Received&#8203;: from chaos\.wustl\.edu \(elaine@&#8203;128\.252\.133\.13\)
\*   by rom\.cscaper\.com with SMTP; 21 Feb 2000 19&#8203;:35&#8203;:54 \-0000
\* Received&#8203;: \(from elaine@&#8203;localhost\)
\*     by chaos\.wustl\.edu \(8\.9\.3\+Sun/8\.9\.3/HappyFunMail\) id NAA20441;
\*     Mon\, 21 Feb 2000 13&#8203;:32&#8203;:50 \-0600 \(CST\)
\* Date&#8203;: Mon\, 21 Feb 2000 13&#8203;:32&#8203;:50 \-0600
\* From&#8203;: Elaine \-HFB\- Ashton \<elaine@&#8203;chaos\.wustl\.edu>
\* To&#8203;: joseph@&#8203;cscaper\.com
\* Cc&#8203;: perl5\-porters@&#8203;perl\.org
\* Subject&#8203;: Re&#8203;: \[ID 20000218\.005\] DynaLoader behavior w\.r\.t\. LD\_LIBRARY\_PATH
\* confuses me
\* Message\-ID&#8203;: \<20000221133250\.K15259@&#8203;chaos\.wustl\.edu>
\* References&#8203;: \<20000219015645\.17833\.qmail@&#8203;mail\.cscaper\.com>
\* Mime\-Version&#8203;: 1\.0
\* Content\-Type&#8203;: text/plain; charset=us\-ascii
\* X\-Mailer&#8203;: Mutt 1\.0pre3i
\* In\-Reply\-To&#8203;: \<20000219015645\.17833\.qmail@&#8203;mail\.cscaper\.com>
\* X\-HappyFunBall&#8203;: Do Not Taunt\.
\*
\* joseph@&#8203;cscaper\.com \[joseph@&#8203;cscaper\.com\] quoth&#8203;:
\* \*>
\* \*>DynaLoader on solaris 7 seems to ignore libpth and follow LD\_LIBRARY\_PATH
\* \*>instead\.  I discovered this when some CGI programs of mine using a new
\* \*>version of mysql began to fail when execute by the server \(as nobody\)
\* \*>because of mysql's affection for libz\.so\.  I had libz\.so in /usr/local/lib\,
\* \*>and I see the following in DynaLoader on that machine&#8203;:

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Mon\, 21 Feb 2000 15&#8203;:04&#8203;:18 \-0500 \(EST\) ilya@&#8203;math\.ohio\-state\.edu \(Ilya
Zakharevich\) wrote&#8203;:

\* To make the long story short&#8203;: @&#8203;dl\_library\_path is used \*by Perl\* to
\* find an extension DLL\.  After DLL is found\, it is being loaded\.  But
\* this DLL \*in turn\* may require loading of other DLLs \- and now this
\* loading is done by the system\, not by Perl\.
\*
\* Thus during to loading of this "chained" DLLs the value of
\* @&#8203;dl\_library\_path is not relevant\.
\*
\* Ilya

That's clear enough\, I guess\, although it doesn't work "right" as
far as I'm concerned and I doubt anyone else would consider it
"right" either\.

Why does changing $ENV\{LD\_LIBRARY\_PATH\} appear to have no effect?

Would it make sense for DynaLoader to alter LD\_LIBRARY\_PATH to 
ensure it contains at least the libraries mentioned in libpth or
@&#8203;dl\_library\_path?

&nbsp;  \-joseph

\-\-
Joseph N\. Hall\, 5 Sigma Productions        mailto&#8203;:" \<joseph> "@&#8203;5sigma\.com
Author\, Effective Perl Programming \. \. \. \. \. http&#8203;://www\.effectiveperl\.com
Perlfaq Prime  \. \. \. \. \. \. \. \. \. \. \. \. \. \. \. \. \. \. http&#8203;://www\.perlfaq\.com

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Tue\, Feb 22\, 2000 at 12&#8203;:37&#8203;:41PM \-0700\, Joseph N\. Hall wrote&#8203;:
> That's clear enough\, I guess\, although it doesn't work "right" as
> far as I'm concerned and I doubt anyone else would consider it
> "right" either\.
> 
> Why does changing $ENV\{LD\_LIBRARY\_PATH\} appear to have no effect?

How could it have an effect?  I would think environ structures are
parts of CRT library structures\.  How would kernel know that you
modified environ?

> Would it make sense for DynaLoader to alter LD\_LIBRARY\_PATH to 
> ensure it contains at least the libraries mentioned in libpth or
> @&#8203;dl\_library\_path?

If this is possible \(yes on OS/2\, but not via environment\)&#8203;: should
DynaLoader check that LD\_LIBRARY\_PATH did not change between loading
of two modules?  Should this propagate to kid processes?

I think this is opening a larger can of worm than what we do now\.

Ilya

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Joseph N \. Hall \<joseph@&#8203;5sigma\.com> writes&#8203;:
>
>Why does changing $ENV\{LD\_LIBRARY\_PATH\} appear to have no effect?

Perhaps because it is ignored for setuid programs\.

>
>Would it make sense for DynaLoader to alter LD\_LIBRARY\_PATH to 
>ensure it contains at least the libraries mentioned in libpth or
>@&#8203;dl\_library\_path?

Not really dlopen\(\) DynaLoader does not really work that way\, and as 
pointed out above LD\_LIBRARY\_PATH is not sufficient for setuid applications\.

On solaris and other SVR4 derived things extensions are supposed to be 
built with LD\_RUN\_PATH set so that right paths are "compiled in" and 
hence trusted for setuid purposes\.

Running 'ldd' on the loadables should show whether the LD\_RUN\_PATH 
has "worked"\. Note that if you use GNU ld then a different scheme 
is needed \(\-\-rpath ???\) is needed rather than LD\_RUN\_PATH \- that 
is assuming your can find a GNU ld that works at all ;\-\)

\-\- 
Nick Ing\-Simmons

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

\(CC to Tim Bunce and developer@&#8203;lists\.mysql\.com\)

\(To summarize\, DBD&#8203;::mysql was failing when run with a
null LD\_LIBRARY\_PATH because\, apparently\, the correct search
path including /usr/local/lib \(on my machine\) wasn't being
built into \-\- I think \-\- DBD&#8203;::mysql\, and so libz\.so wasn't
being found in /usr/local/lib on my machine\.  Was NOT linking
with GNU ld on Solaris\, of course\.\)

I guess that is either a DBI or MySQL issue then\.  I attempted to
do a more or less plain build of MySQL on Solaris\.  The last
version I built failed at first because mysql configure was
unhappy about finding its friend libz\.so in /usr/local/lib\, or
maybe not finding it\.  I reported configure's rather peculiar
behavior \(manifested as a failure in the "determine the size
of char" test program\) to the MySQL developers and I gather
something must have changed\.  Meanwhile I built \*that\* version
without compression at all\.  The current version \(which I was 
installing for the security fix\) behaved a bit differently and 
built successfully\.  I rebuilt DBI and DBD&#8203;::mysql also\, just
in case\, and except for a couple of apparently unrelated failures\,
everything worked satisfactorily when I tested DBI\.  When I threw
it into production\, though\, it blew up\, and it took me about an
hour to figure out exactly what the problem was\, and to "fix"
it by linking libz\.so to /usr/lib/libz\.so because I had no idea
how I might fix the shared library search path in this case\.

By the way\, the program in question was not running setuid\.  It
seems to me that it ought to be possible to change LD\_LIBRARY\_PATH
at runtime through %ENV but then again\, maybe it don't work thataway\.

&nbsp;  \-joseph

\-\-
Joseph N\. Hall\, 5 Sigma Productions        mailto&#8203;:" \<joseph> "@&#8203;5sigma\.com
Author\, Effective Perl Programming \. \. \. \. \. http&#8203;://www\.effectiveperl\.com
Perlfaq Prime  \. \. \. \. \. \. \. \. \. \. \. \. \. \. \. \. \. \. http&#8203;://www\.perlfaq\.com

On Tue\, 22 Feb 2000 20&#8203;:56&#8203;:06 \+0000 nick@&#8203;ing\-simmons\.net \(Nick Ing\-Simmons\)
wrote&#8203;:

\* Joseph N \. Hall \<joseph@&#8203;5sigma\.com> writes&#8203;:
\* >
\* >Why does changing $ENV\{LD\_LIBRARY\_PATH\} appear to have no effect?
\*
\* Perhaps because it is ignored for setuid programs\.
\*
\* >
\* >Would it make sense for DynaLoader to alter LD\_LIBRARY\_PATH to
\* >ensure it contains at least the libraries mentioned in libpth or
\* >@&#8203;dl\_library\_path?
\*
\* Not really dlopen\(\) DynaLoader does not really work that way\, and as
\* pointed out above LD\_LIBRARY\_PATH is not sufficient for setuid applications\.
\*
\* On solaris and other SVR4 derived things extensions are supposed to be
\* built with LD\_RUN\_PATH set so that right paths are "compiled in" and
\* hence trusted for setuid purposes\.
\*
\* Running 'ldd' on the loadables should show whether the LD\_RUN\_PATH
\* has "worked"\. Note that if you use GNU ld then a different scheme
\* is needed \(\-\-rpath ???\) is needed rather than LD\_RUN\_PATH \- that
\* is assuming your can find a GNU ld that works at all ;\-\)
\*
\* \-\-
\* Nick Ing\-Simmons

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Joseph N \. Hall \<joseph@&#8203;5sigma\.com> writes&#8203;:
>
>By the way\, the program in question was not running setuid\.  It
>seems to me that it ought to be possible to change LD\_LIBRARY\_PATH
>at runtime through %ENV but then again\, maybe it don't work thataway\.

Oh \_that\_ feature \- ld\.so read LD\_LIBRARY\_PATH when execuable starts
\(it needed it to find libc to find the thing that called main\(\) \.\.\.\)
So you have to set it then re\-exec yourself so that loader sees the update\.

>
\-\- 
Nick Ing\-Simmons

**Comment by tonycoz** [comment]
This appears to be closable, it looks like a Solaris library search issue rather than a problem with DynaLoader.

**Comment by tonycoz** [comment]
closing
