### ISSUE TITLE
:stdio + any other layer hangs

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#12146]
Migrated from [rt.perl.org#113424](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=113424) (status was 'new')

Searchable as RT113424$

**Comment by p5pRT** [comment]
### From @Leont

This is a bug report for perl from fawaka@&#8203;gmail\.com\,
generated with the help of perlbug 1\.39 running under perl 5\.16\.0\.



---
The :stdio PerlIO layer doesn't function correctly when it's not the
topmost layer\. Take this test&#8203;:

 use Test&#8203;::More tests => 1;

 pipe my $in\, my $out;
 binmode $in\,  '&#8203;:encoding\(utf\-8\)';
 syswrite $out\, "\.\.\.\\n";
 my $line = readline $in;
 is\( $line\, "\.\.\.\\n"\, 'Reading utf8' \);

It will work fine under normal circumstances\, but if you run it with
the PERLIO environmental variable set to "stdio"\, it will hang\. The
reason is that :encoding reads its buffer in blocks\, but :stdio's read
method is implemented in terms of fread\, which retries until it can
read N bytes\. Our own readline is build on top of that\, but can't take
its \(while/getc\) hack to solve this because encoding is inbetween\.

I suspect fixing this will require a complete refactor of readline to
integrate it into PerlIO\, and even then it looks rather tricky :\-/



---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=medium


---
Site configuration information for perl 5\.16\.0&#8203;:

Configured by leon at Mon May 21 12&#8203;:51&#8203;:40 CEST 2012\.

Summary of my perl5 \(revision 5 version 16 subversion 0\) configuration&#8203;:

&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.0\.0\-19\-generic\, archname=x86\_64\-linux\-thread\-multi
&nbsp;    uname='linux leon\-laptop 3\.0\.0\-19\-generic \#33\-ubuntu smp thu apr
19 19&#8203;:05&#8203;:14 utc 2012 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;    config\_args='\-de
\-Dprefix=/home/leon/perl5/perlbrew/perls/perl\-5\.16\.0 \-Dusethreads
\-Dusesphplib'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing
\-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE
\-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fno\-strict\-aliasing \-pipe
\-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.6\.1'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\,
lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib
/usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib /usr/lib
&nbsp;    libs=\-lnsl \-ldb \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    libc=\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.13'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-L/usr/local/lib
\-fstack\-protector'

Locally applied patches&#8203;:




---
@&#8203;INC for perl 5\.16\.0&#8203;:
&nbsp;    /home/leon/perl5/perlbrew/perls/perl\-5\.16\.0/lib/site\_perl/5\.16\.0/x86\_64\-linux\-thread\-multi
&nbsp;    /home/leon/perl5/perlbrew/perls/perl\-5\.16\.0/lib/site\_perl/5\.16\.0
&nbsp;    /home/leon/perl5/perlbrew/perls/perl\-5\.16\.0/lib/5\.16\.0/x86\_64\-linux\-thread\-multi
&nbsp;    /home/leon/perl5/perlbrew/perls/perl\-5\.16\.0/lib/5\.16\.0
&nbsp;    \.



---
Environment for perl 5\.16\.0&#8203;:
&nbsp;    HOME=/home/leon
&nbsp;    LANG=en\_US\.utf8
&nbsp;    LANGUAGE=en\_US&#8203;:en\_GB&#8203;:en
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/leon/perl5/perlbrew/bin&#8203;:/home/leon/perl5/perlbrew/perls/perl\-5\.16\.0/bin&#8203;:/home/leon/bin&#8203;:/usr/lib/lightdm/lightdm&#8203;:/usr/local/sbin&#8203;:/usr/local/bin&#8203;:/usr/sbin&#8203;:/usr/bin&#8203;:/sbin&#8203;:/bin&#8203;:/usr/games
&nbsp;    PERLBREW\_HOME=/home/leon/\.perlbrew
&nbsp;    PERLBREW\_PATH=/home/leon/perl5/perlbrew/bin&#8203;:/home/leon/perl5/perlbrew/perls/perl\-5\.16\.0/bin
&nbsp;    PERLBREW\_PERL=perl\-5\.16\.0
&nbsp;    PERLBREW\_ROOT=/home/leon/perl5/perlbrew
&nbsp;    PERLBREW\_VERSION=0\.25
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by Leont** [comment]
This is a duplicate of #6924
