### ISSUE TITLE
UPSTREAM=>blead modules need resource META updates

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#12260]
Migrated from [rt.perl.org#114050](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=114050) (status was 'open')

Searchable as RT114050$

**Comment by p5pRT** [comment]
### From Perl@ResonatorSoft.org

#### Created by Perl@ResonatorSoft.org



All of the core modules that are maintained in blead needs to have some META
resource additions to reflect the proper place for bug reports and the
repository&#8203;:

&nbsp;   resources => \{
&nbsp;      IRC         => 'irc&#8203;://irc\.perl\.org/\#p5p'\,
&nbsp;      MailingList => 'http&#8203;://lists\.perl\.org/list/perl5\-porters\.html'\,
&nbsp;      license     => 'http&#8203;://dev\.perl\.org/licenses/'\,
&nbsp;      repository  => 'git&#8203;://perl5\.git\.perl\.org/perl\.git'\,

&nbsp;      \# Change to related module
&nbsp;      bugtracker  =>
"https://rt-archive.perl.org/perl5/Search/Results.html?Query=Queue='perl5' AND
Content LIKE 'module=Math&#8203;::BigInt' AND \(Status='open' OR Status='new'
OR Status='stalled'\)"\,
&nbsp;      homepage    => 'https://metacpan.org/module/Math::BigInt',
&nbsp;   \}\,

Most of these modules have a bunch of rt\.cpan\.org tickets that should be
cleaned up and/or re\-opened at rt\.perl\.org\.  Of course\, this only applies
to blead modules that exist as a standalone module in CPAN\.  \(I think this is if
Maintainers\.pl contains a DISTRIBUTION attr\.\)  An audit finds the following
modules need META updates and cleanup&#8203;:

Attribute&#8203;::Handlers
autouse
B&#8203;::Lint
base
bignum
Carp
Compress&#8203;::Raw&#8203;::Bzip2
Compress&#8203;::Raw&#8203;::Zlib
constant
Devel&#8203;::SelfStubber
Dumpvalue&#8203;:
encoding&#8203;::warnings        \(UPSTREAM => undef\)
Env
Exporter
ExtUtils&#8203;::CBuilder
ExtUtils&#8203;::Command
\# ExtUtils&#8203;::Constant      \(UPSTREAM => undef\, but still maintained in CPAN\)
ExtUtils&#8203;::Install
ExtUtils&#8203;::MakeMaker       \(UPSTREAM => first\-come\)
ExtUtils&#8203;::Manifest
ExtUtils&#8203;::ParseXS
File&#8203;::CheckTree
File&#8203;::Path                \(UPSTREAM => undef\)
Filter&#8203;::Simple
I18N&#8203;::Collate
I18N&#8203;::LangTags
if
IO
IO&#8203;::Zlib                  \(UPSTREAM => undef\)
lib
libnet                    \(UPSTREAM => undef\)
Locale&#8203;::Maketext
Math&#8203;::BigInt
Math&#8203;::BigInt&#8203;::FastCalc
Math&#8203;::BigRat
Module&#8203;::CoreList
Net&#8203;::Ping
parent                    \(UPSTREAM => undef\)
PathTools
PerlIO&#8203;::via&#8203;::QuotedPrint  \(UPSTREAM => undef\)
Pod&#8203;::Escapes              \(UPSTREAM => undef\)
Pod&#8203;::LaTeX                \(UPSTREAM => undef\)
Safe
Search&#8203;::Dict
SelfLoader
Storable
Term&#8203;::Cap                 \(UPSTREAM => undef\)
Term&#8203;::Complete
Term&#8203;::ReadLine
Text&#8203;::Abbrev
Text&#8203;::ParseWords          \(UPSTREAM => undef\)
Text&#8203;::Soundex             \(UPSTREAM => undef\)
Thread&#8203;::Queue
Thread&#8203;::Semaphore
threads
threads&#8203;::shared
Tie&#8203;::File
Time&#8203;::Piece               \(UPSTREAM => undef\)
Unicode&#8203;::Collate          \(UPSTREAM => first\-come\)
Unicode&#8203;::Normalize        \(UPSTREAM => first\-come\)
version                   \(UPSTREAM => undef\)
XSLoader

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

Site configuration information for perl 5.16.0:

Configured by strawberry-perl at Mon May 21 22:08:30 2012.

Summary of my perl5 (revision 5 version 16 subversion 0) configuration:

  Platform:
    osname=MSWin32, osvers=4.0, archname=MSWin32-x86-multi-thread
    uname='Win32 strawberry-perl 5.16.0.1 #1 Mon May 21 22:07:30 2012 i386'
    config_args='undef'
    hint=recommended, useposix=true, d_sigaction=undef
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=undef, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags =' -s -O2 -DWIN32  -DPERL_TEXTMODE_SCRIPTS
-DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -fno-strict-aliasing
-mms-bitfields',
    optimize='-s -O2',
    cppflags='-DWIN32'
    ccversion='', gccversion='4.6.3', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=undef, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='long
long', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='g++', ldflags ='-s -L"C:\strawberry\perl\lib\CORE"
-L"C:\strawberry\c\lib"'
    libpth=C:\strawberry\c\lib C:\strawberry\c\i686-w64-mingw32\lib
    libs=-lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32
-ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32
-lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    perllibs=-lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool
-lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid
-lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    libc=, so=dll, useshrplib=true, libperl=libperl516.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs, dlext=dll, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags='-mdll -s
-L"C:\strawberry\perl\lib\CORE" -L"C:\strawberry\c\lib"'

Locally applied patches:



@INC for perl 5.16.0:
    C:/STRAWBERRY/perl/site/lib
    C:/STRAWBERRY/perl/vendor/lib
    C:/STRAWBERRY/perl/lib
    .


Environment for perl 5.16.0:
    HOME (unset)
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=C:\Windows\SYSTEM32;C:\Windows;C:\Windows\SYSTEM32\WBEM;C:\Windows\SYSTEM32\WINDOWSPOWERSHELL\V1.0\;C:\PROGRAM
FILES\INTEL\DMIX;C:\PROGRAM FILES\INTEL\WIFI\BIN\;C:\PROGRAM
FILES\COMMON FILES\INTEL\WIRELESSCOMMON\;C:\PROGRAM FILES\NTRU
CRYPTOSYSTEMS\NTRU TCG SOFTWARE STACK\BIN\;C:\PROGRAM FILES\WAVE
SYSTEMS CORP\GEMALTO\ACCESS CLIENT\V5\;C:\PROGRAM FILES\COMMON
FILES\ROXIO SHARED\DLLSHARED\;C:\PROGRAM FILES\COMMON FILES\ROXIO
SHARED\10.0\DLLSHARED\;C:\STRAWBERRY\C\BIN;C:\STRAWBERRY\PERL\SITE\BIN;C:\STRAWBERRY\PERL\BIN;C:\CYGWIN\USR\BIN;C:\PROGRAM
FILES\IBM\TIVOLI\NETCOOL\PLATFORM\WIN32\BIN;C:\PROGRAM
FILES\IBM\TIVOLI\NETCOOL\OMNIBUS\PLATFORM\WIN32\BIN;C:\PROGRAM
FILES\IBM\TIVOLI\NETCOOL\PLATFORM\WIN32\LIB;C:\CYGWIN\BIN;C:\Program
Files\Lua\5.1;C:\Program Files\Lua\5.1\clibs;C:\Program
Files\TortoiseGit\bin;C:\Program Files\TortoiseSVN\bin;C:\Program
Files\Nmap
    PERL_BADLANG (unset)
    SHELL (unset)

```
</details>

**Comment by p5pRT** [comment]
### From @jkeenan

On Mon Jul 09 09&#8203;:02&#8203;:54 2012\, Perl@&#8203;ResonatorSoft\.org wrote&#8203;:
> This is a bug report for perl from Perl@&#8203;ResonatorSoft\.org\,
> generated with the help of perlbug 1\.39 running under perl 5\.16\.0\.
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please describe your issue here\]
> 
> All of the core modules that are maintained in blead needs to have
> some META
> resource additions to reflect the proper place for bug reports and the
> repository&#8203;:
> 
>    resources => \{
>       IRC         => 'irc&#8203;://irc\.perl\.org/\#p5p'\,
>       MailingList => 'http&#8203;://lists\.perl\.org/list/perl5\-porters\.html'\,
>       license     => 'http&#8203;://dev\.perl\.org/licenses/'\,
>       repository  => 'git&#8203;://perl5\.git\.perl\.org/perl\.git'\,
> 
>       \# Change to related module
>       bugtracker  =>
> "https://rt-archive.perl.org/perl5/Search/Results.html?Query=Queue='perl5' AND
> Content LIKE 'module=Math&#8203;::BigInt' AND \(Status='open' OR Status='new'
> OR Status='stalled'\)"\,
>       homepage    => 'https://metacpan.org/module/Math::BigInt',
>    \}\,
> 
> Most of these modules have a bunch of rt\.cpan\.org tickets that should
> be
> cleaned up and/or re\-opened at rt\.perl\.org\.  Of course\, this only
> applies
> to blead modules that exist as a standalone module in CPAN\.  \(I think
> this is if
> Maintainers\.pl contains a DISTRIBUTION attr\.\)  An audit finds the
> following
> modules need META updates and cleanup&#8203;:

Thanks for taking the time to conduct this audit\.  However\, it's not
clear to me which files you believe should be updated\.

META\.yml ?
META\.json ?
Porting/Maintainers\.pl ?
some META files in distros on www\.cpan\.org ?

Can you clarify?

Thank you very much\.
Jim Keenan


> 
> Attribute&#8203;::Handlers
> autouse
> B&#8203;::Lint
> base
> bignum
> Carp
> Compress&#8203;::Raw&#8203;::Bzip2
> Compress&#8203;::Raw&#8203;::Zlib
> constant
> Devel&#8203;::SelfStubber
> Dumpvalue&#8203;:
> encoding&#8203;::warnings        \(UPSTREAM => undef\)
> Env
> Exporter
> ExtUtils&#8203;::CBuilder
> ExtUtils&#8203;::Command
> \# ExtUtils&#8203;::Constant      \(UPSTREAM => undef\, but still maintained in
> CPAN\)
> ExtUtils&#8203;::Install
> ExtUtils&#8203;::MakeMaker       \(UPSTREAM => first\-come\)
> ExtUtils&#8203;::Manifest
> ExtUtils&#8203;::ParseXS
> File&#8203;::CheckTree
> File&#8203;::Path                \(UPSTREAM => undef\)
> Filter&#8203;::Simple
> I18N&#8203;::Collate
> I18N&#8203;::LangTags
> if
> IO
> IO&#8203;::Zlib                  \(UPSTREAM => undef\)
> lib
> libnet                    \(UPSTREAM => undef\)
> Locale&#8203;::Maketext
> Math&#8203;::BigInt
> Math&#8203;::BigInt&#8203;::FastCalc
> Math&#8203;::BigRat
> Module&#8203;::CoreList
> Net&#8203;::Ping
> parent                    \(UPSTREAM => undef\)
> PathTools
> PerlIO&#8203;::via&#8203;::QuotedPrint  \(UPSTREAM => undef\)
> Pod&#8203;::Escapes              \(UPSTREAM => undef\)
> Pod&#8203;::LaTeX                \(UPSTREAM => undef\)
> Safe
> Search&#8203;::Dict
> SelfLoader
> Storable
> Term&#8203;::Cap                 \(UPSTREAM => undef\)
> Term&#8203;::Complete
> Term&#8203;::ReadLine
> Text&#8203;::Abbrev
> Text&#8203;::ParseWords          \(UPSTREAM => undef\)
> Text&#8203;::Soundex             \(UPSTREAM => undef\)
> Thread&#8203;::Queue
> Thread&#8203;::Semaphore
> threads
> threads&#8203;::shared
> Tie&#8203;::File
> Time&#8203;::Piece               \(UPSTREAM => undef\)
> Unicode&#8203;::Collate          \(UPSTREAM => first\-come\)
> Unicode&#8203;::Normalize        \(UPSTREAM => first\-come\)
> version                   \(UPSTREAM => undef\)
> XSLoader
>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @ikegami

On Sat\, Mar 30\, 2013 at 9&#8203;:56 PM\, James E Keenan via RT \<
perlbug\-followup@&#8203;perl\.org> wrote&#8203;:

> Thanks for taking the time to conduct this audit\.  However\, it's not
> clear to me which files you believe should be updated\.
>
> META\.yml ?
> META\.json ?
> Porting/Maintainers\.pl ?
> some META files in distros on www\.cpan\.org ?
>
> Can you clarify?
>

Makefile\.PL and Build\.PL should be changed to generate the META\.\* elements
mentioned in the ticket\.

**Comment by toddr** [comment]
These would have to be reported against those dual life distros as the code to generate those tarballs is not included in perl itself.
