### ISSUE TITLE
Win32: -e '"' always returns true

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#12431]
Migrated from [rt.perl.org#114986](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=114986) (status was 'open')

Searchable as RT114986$

**Comment by p5pRT** [comment]
### From @sisyphus

Subject&#8203;: Win32&#8203;: \-e '"' always returns true
Message\-Id&#8203;: \<5\.16\.0\_1816\_1348202385@&#8203;desktop2>
Reply\-To&#8203;: sisyphus1@&#8203;optusnet\.com\.au
To&#8203;: perlbug@&#8203;perl\.org
From&#8203;: sisyphus1@&#8203;optusnet\.com\.au


This is a bug report for perl from sisyphus1@&#8203;optusnet\.com\.au\,
generated with the help of perlbug 1\.39 running under perl 5\.16\.0\.

Hi\,

This \(raised recently at http&#8203;://www\.perlmonks\.org/index\.pl?node\_id=979494\) 
must surely have come up before ?

It's behaviour that's specific to MS Windows \- for all versions of perl back 
to 5\.6\.2 \(and presumably even further back\)\.

\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#

use warnings;
use strict;

print "1&#8203;:  huh?\\n" if \-e '"';
print "2&#8203;:  huh?\\n" if \-e '""';
print "3&#8203;:  huh?\\n" if \-e '"""';
print "4&#8203;:  huh?\\n" if \-e '""""';
print "5&#8203;:  huh?\\n" if \-e '"""""';
print "6&#8203;:  huh?\\n" if \-e '""""""""""""""';
print "7&#8203;:  huh?\\n" if defined \-f '"';
print "8&#8203;:  huh?\\n" if defined \-f '""';
print "9&#8203;:  huh?\\n" if defined \-f '"""';
print "10&#8203;: huh?\\n" if defined \-f '""""';
print "11&#8203;: huh?\\n" if defined \-f '"""""';
print "12&#8203;: huh?\\n" if defined \-f '""""""""""""""';

\_\_END\_\_
Outputs&#8203;:

1&#8203;:  huh?
2&#8203;:  huh?
3&#8203;:  huh?
4&#8203;:  huh?
5&#8203;:  huh?
6&#8203;:  huh?
7&#8203;:  huh?
8&#8203;:  huh?
9&#8203;:  huh?
10&#8203;: huh?
11&#8203;: huh?
12&#8203;: huh?

\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#

That's pretty astounding at first glance \- given that the doublequote symbol 
is an illegal filename character\.

Apparently this behaviour results from a Windows system practice of treating 
the doublequote symbol as meaning 'everything'\, and some people might hold 
the view that the output of the above demo is correct behaviour\.
As I understand it\, \-e '"' will currently return true on Windows because 
it's effectively asking "does anything exist in the cwd?" \.\.\. and something 
always exists in the cwd \(even if it's just the '\.' and '\.\.' directories\)\.

For me\, this behaviour just doesn't DWIM at all\, and it also doesn't match 
the \-X documentation\, imo\.

Dunno \.\.\. I'll leave it up to p5p to decide how this should be handled\.

My view is that if the behaviour is to be kept as is\, then we should at 
least display a notice about this in the \-X docs\. Something like&#8203;:

NOTE&#8203;: On MS windows\, if the specified filename consists solely of one
&nbsp;      or more doublequote symbols \("\) then \-e will return true\, and
&nbsp;      \-f will return false but defined\.

And perhaps a similar notice for 'stat' in the perlfunc and perlport docs\.
Note that stat\('"'\) returns the same as stat\('\.'\)\.

Cheers\,
Rob



---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=medium


---
Site configuration information for perl 5\.16\.0&#8203;:

Configured by Rob at Mon May 28 14&#8203;:31&#8203;:11 2012\.

Summary of my perl5 \(revision 5 version 16 subversion 0\) configuration&#8203;:

&nbsp;  Platform&#8203;:
&nbsp;    osname=MSWin32\, osvers=6\.0\, archname=MSWin32\-x86\-multi\-thread
&nbsp;    uname=''
&nbsp;    config\_args='undef'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=undef
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc'\, ccflags 
=' \-s \-O2 \-DWIN32  \-DPERL\_TEXTMODE\_SCRIPTS \-DPERL\_IMPLICIT\_CONTEXT \-DPERL\_IMPLICIT\_SYS 
 \-fno\-strict\-aliasing \-mms\-bitfields'\,
&nbsp;    optimize='\-s \-O2'\,
&nbsp;    cppflags='\-DWIN32'
&nbsp;    ccversion=''\, gccversion='4\.5\.2'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='long long'\, 
lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='g\+\+'\, ldflags ='\-s \-L"c&#8203;:\\MinGW\\perl516\\lib\\CORE" \-L"C&#8203;:\\MinGW\\lib"'
&nbsp;    libpth=C&#8203;:\\MinGW\\lib C&#8203;:\\MinGW\\msys\\1\.0\\local\\lib 
C&#8203;:\\MinGW\\msys\\1\.0\\local\\ssl\\lib
&nbsp;    libs=\-lmoldname \-lkernel32 \-luser32 \-lgdi32 \-lwinspool \-lcomdlg32 \-ladvapi32 
 \-lshell32 \-lole32 \-loleaut32 \-lnetapi32 \-luuid \-lws2\_32 \-lmpr \-lwinmm \-lversion 
 \-lodbc32 \-lodbccp32 \-lcomctl32
&nbsp;    perllibs=\-lmoldname \-lkernel32 \-luser32 \-lgdi32 \-lwinspool \-lcomdlg32 \-ladvapi32 
 \-lshell32 \-lole32 \-loleaut32 \-lnetapi32 \-luuid \-lws2\_32 \-lmpr \-lwinmm \-lversion 
 \-lodbc32 \-lodbccp32 \-lcomctl32
&nbsp;    libc=\, so=dll\, useshrplib=true\, libperl=libperl516\.a
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_win32\.xs\, dlext=dll\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags=' '\, 
lddlflags='\-mdll \-s \-L"c&#8203;:\\MinGW\\perl516\\lib\\CORE" \-L"C&#8203;:\\MinGW\\lib"'

Locally applied patches&#8203;:




---
@&#8203;INC for perl 5\.16\.0&#8203;:
&nbsp;    C&#8203;:\\\_32\\mpfr\_dec64\_516\\lib\\perl5\\MSWin32\-x86\-multi\-thread
&nbsp;    C&#8203;:/MinGW/perl516/site/lib
&nbsp;    C&#8203;:/MinGW/perl516/lib
&nbsp;    \.



---
Environment for perl 5\.16\.0&#8203;:
&nbsp;    HOME \(unset\)
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=C&#8203;:\\Program Files\\Windows 
NT\\Accessories;C&#8203;:\\MinGW\\bin;C&#8203;:\\\_32\\dmake;C&#8203;:\\Windows\\system32;C&#8203;:\\Windows;C&#8203;:\\Windows\\System32\\Wbem;C&#8203;:\\batch;C&#8203;:\\\_32\\lzma;C&#8203;:\\MinGW\\perl516\\bin;C&#8203;:\\MinGW\\msys\\1\.0\\bin;C&#8203;:\\\_32\\Gnuplot\\binary;C&#8203;:\\sisyphusion\\libgcc\_straw32
&nbsp;    PERL5LIB=;C&#8203;:\\\_32\\mpfr\_dec64\_516\\lib\\perl5\\MSWin32\-x86\-multi\-thread
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL \(unset\)

**Comment by p5pRT** [comment]
### From @ikegami

It performs other shell interpolation too\.

>dir /b foo bar
foo

>set XX=foo

>perl \-E"say \-e qq\{%XX%\} ?1&#8203;:0"
1

>set XX=bar

>perl \-E"say \-e qq\{%XX%\} ?1&#8203;:0"
0

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @ikegami

On Fri\, Sep 21\, 2012 at 4&#8203;:03 PM\, Eric Brine \<ikegami@&#8203;adaelis\.com> wrote&#8203;:

> It performs other shell interpolation too\.
>
> >dir /b foo bar
> foo
>
> >set XX=foo
>
> >perl \-E"say \-e qq\{%XX%\} ?1&#8203;:0"
> 1
>
> >set XX=bar
>
> >perl \-E"say \-e qq\{%XX%\} ?1&#8203;:0"
> 0
>
>
Nevermind\. Bad test\.

**Comment by p5pRT** [comment]
### From vadim.konovalov@alcatel-lucent.com

> Apparently this behaviour results from a Windows system 
> practice of treating 
> the doublequote symbol as meaning 'everything'\, and some 
> people might hold 
> the view that the output of the above demo is correct behaviour\.
> As I understand it\, \-e '"' will currently return true on 
> Windows because 
> it's effectively asking "does anything exist in the cwd?" \.\.\. 
> and something 
> always exists in the cwd \(even if it's just the '\.' and '\.\.' 
> directories\)\.

As for my knowledge\, doublequote does not mean anything\,

> My view is that if the behaviour is to be kept as is\, then we 
> should at 
> least display a notice about this in the \-X docs\. Something like&#8203;:

IMO \-f '"' should be undef

> 
> NOTE&#8203;: On MS windows\, if the specified filename consists solely of one
>       or more doublequote symbols \("\) then \-e will return true\, and
>       \-f will return false but defined\.

it appears that doublequote is prohibited in filenames on Windows\, similarily 
to '&#8203;:'\, '/'\, '\*' etc\.
Also\, spaces \(' '\) are stripped at the end and start of file name\.

So \- from one side\, \-f should return false in all such cases\, because a file
with such a name does not exist\.
Trying to still find a file with same name but doublequotes stripped is wrong\, IMO\.

Another question \- is it OS or filesystem?

**Comment by p5pRT** [comment]
### From @sisyphus


\-\-\-\-\- Original Message \-\-\-\-\- 
From&#8203;: "Konovalov\, Vadim \(Vadim\)\*\* CTR \*\*" 
\<vadim\.konovalov@&#8203;alcatel\-lucent\.com>
To&#8203;: \<perl5\-porters@&#8203;perl\.org>; \<bugs\-bitbucket@&#8203;rt\.perl\.org>
Sent&#8203;: Monday\, September 24\, 2012 4&#8203;:35 PM
Subject&#8203;: RE&#8203;: \[perl \#114986\] Win32&#8203;: \-e '"' always returns true


>> Apparently this behaviour results from a Windows system
>> practice of treating
>> the doublequote symbol as meaning 'everything'\, and some
>> people might hold
>> the view that the output of the above demo is correct behaviour\.
>> As I understand it\, \-e '"' will currently return true on
>> Windows because
>> it's effectively asking "does anything exist in the cwd?" \.\.\.
>> and something
>> always exists in the cwd \(even if it's just the '\.' and '\.\.'
>> directories\)\.
>
> As for my knowledge\, doublequote does not mean anything\,
>
>> My view is that if the behaviour is to be kept as is\, then we
>> should at
>> least display a notice about this in the \-X docs\. Something like&#8203;:
>
> IMO \-f '"' should be undef

And the way I read it\, that's what the documentation implies\.
Interestingly\, both \-T '"' and \-B '"' return undef\, it's just \-f '"' that 
returns a false but defined value\.

AFAIK\, \-e and \-f are the only switches that contravene the \-X documentation\.

>> NOTE&#8203;: On MS windows\, if the specified filename consists solely of one
>>       or more doublequote symbols \("\) then \-e will return true\, and
>>       \-f will return false but defined\.
>
> it appears that doublequote is prohibited in filenames on Windows\, 
> similarily
> to '&#8203;:'\, '/'\, '\*' etc\.

Yes\, the doublequote is prohibited\.

> Also\, spaces \(' '\) are stripped at the end and start of file name\.
>
> So \- from one side\, \-f should return false in all such cases\, because a 
> file
> with such a name does not exist\.
> Trying to still find a file with same name but doublequotes stripped is 
> wrong\, IMO\.
>
> Another question \- is it OS or filesystem?

I think it's OS \.\.\.\. but I don't really know for sure\.
How does one test this ?

Cheers\,
Rob

**Comment by p5pRT** [comment]
### From @bulk88






---
> From&#8203;: sisyphus1@&#8203;optusnet\.com\.au
> To&#8203;: vadim\.konovalov@&#8203;alcatel\-lucent\.com; perl5\-porters@&#8203;perl\.org; bugs\-bitbucket@&#8203;rt\.perl\.org
> Subject&#8203;: Re&#8203;: \[perl \#114986\] Win32&#8203;: \-e '"' always returns true
> Date&#8203;: Mon\, 24 Sep 2012 17&#8203;:47&#8203;:02 \+1000
> > Another question \- is it OS or filesystem?
>
> I think it's OS \.\.\.\. but I don't really know for sure\.
> How does one test this ?
>
> Cheers\,
> Rob
>
Use a C debugger\. Win32 Perl has alot of file path manipulation code in perlhost\.h\, win32io\.c and win32\.c to enable POSIX paths or unclean \(directory name without or without a trailing "\\"\) to work on short file name DOS Windows and other little bugs and strange things around the Win32 API\. PerlDir\_mapA is a common function that is called\. Rather than take a "read your OS's CLib manpage" approach the way perl does on Unix \(I think thats the usually explanation Perl people give for "this works on Linux but not Solaris/AIX/OSX"\)\, Win32 Perl tries to create a POSIX compatibility layer over Win32 so alot of Unix Perl scripts will work unmodified on Win32\. Plus remember the all file IO goes through the MS CRT which itself has some "posix compatibility layer" stuff going on\. So there are 3 main suspects and 2 unlikely suspects for what causes q\!"\! to be a valid file name\, Perl's /win32 directory in src code\, the MS CRT\, or the Kernel32 API\, and as a semi\-jk let us throw in NTDLL/Native API's path processing\, or the NTFS or FAT32 FS driver's path processing too\.
&nbsp;

**Comment by p5pRT** [comment]
### From @jandubois

On Mon\, 24 Sep 2012\, bulk 88 wrote&#8203;:
> PerlDir\_mapA is a common function that is called\.

I'm pretty sure that the PerlDir\_mapA\(\) processing is the underlying
cause\.  Perl on Windows uses the perlhost mechanism to provide a
virtual environment for each Perl interpreter inside the same process\.
So each interpreter will pretend to have their own environment variables
\*and\* their own working directory\.

To maintain this illusion Perl cannot rely on the system CWD to resolve
relative paths but must turn them into absolute paths relative to the CWD
of the current interpreter itself\.  This happens in PerlDir\_mapA\.  So I
suspect the '"' characters will simply be ignored and the stat\(\) call will
be made on the CWD instead\.

Cheers\,
\-Jan

**Comment by toddr** [comment]
I understand the underlying problem hasn't been resolved, but I don't see anything we can do. The last comment from @jandubois seems to indicate this is not going to be fixed, right?

**Comment by richardleach** [comment]
Possibly something that could be looked at as part of any future revamp of filename handling on Windows to fix #9578 and related "Unicode and System Calls" limitations?

**Comment by tonycoz** [comment]
This is fixed in blead, probably by e935ef333b3eab54a766de93fad1369f76ddea49.

I expect it was also fixed in builds with recent MSVC, since the UCRT uses CreateFile() to open the file to stat rather than FindFirstFile() as MSVCRT does.
