### ISSUE TITLE
miniperl creates 8gb output under shell redirection  

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#12615]
Migrated from [rt.perl.org#115904](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=115904) (status was 'open')

Searchable as RT115904$

**Comment by p5pRT** [comment]
### From @wchristian

#### Created by @wchristian



In any checkout with the following git commit id\, or after
925798f29c677c612a63a08a92ebb5f169e27b02\, the following commands
will cause a file containing 8GB of \\o to be written&#8203;:

&nbsp;  cd win32
&nbsp;  dmake \.\\config\.h \.\.\\git\_version\.h
&nbsp;  cd \.\.
&nbsp;  miniperl \-e "open STDERR\_COPY\, '>&STDERR'; print 1;" 1>log 2>&1
&nbsp;  perl \-e "print \-s 'log'"

This is on Windows 7\, using the MinGW included in
ActivePerl 5\.12\.4\. I also tried with the MinGW included in the
latest Strawberry Perl\, but that resulted only in compile errors\.

Here's a full log of the broken behavior of miniperl&#8203;:

&nbsp;  https://gist.github.com/4142366

Here's a full log of miniperl acting correctly&#8203;:

&nbsp;  https://gist.github.com/4142377

The commit in question includes this line in the commit message&#8203;:

&nbsp;  \- Set lseeksize/lseektype to 4/long in new gc64\* files
&nbsp;  \(see f7e8b52a89\)

The mentioned commit has this message\, which seems to be
related to the problem&#8203;:

&nbsp;  Change 25208 switched off USE\_LARGE\_FILES in win32/config\_H\.\*
&nbsp;  but left LSEEKSIZE/Off\_t\_size and Off\_t as 8 and \_\_int64 \(or
&nbsp;  long long\) respectively\. Similarly change 25215 switched off
&nbsp;  uselargefiles in win32/config\.\* but left lseeksize and
&nbsp;  lseektype as 8 and \_\_int64 \(or long long\) respectively\. Change
&nbsp;  25216 fixed the Borland settings in win32/config\.bc on the
&nbsp;  basis that Borland should always be using 4 and long\, but
&nbsp;  really all the other files should be using 4 and long for
&nbsp;  their default values as well to match the default values of
&nbsp;  USE\_LARGE\_FILES and uselargefiles\. Having done that\, we must
&nbsp;  then reverse the logic for fiddling with these values in
&nbsp;  win32/config\_sh\.PL&#8203;: they are now changed to 8 and \_\_int64 \(or
&nbsp;  long long\) if uselargefiles \*is\* defined \(except for Borland\,
&nbsp;  which always wants 4 and long\)\.

<details><summary>Perl Info</summary>

```

Flags:
     category=core
     severity=medium

Site configuration information for perl 5.12.4:

Configured by gecko at Mon Jun 20 18:32:45 2011.

Summary of my perl5 (revision 5 version 12 subversion 4) configuration:

   Platform:
     osname=MSWin32, osvers=5.2, archname=MSWin32-x86-multi-thread
     uname=''
     config_args='undef'
     hint=recommended, useposix=true, d_sigaction=undef
     useithreads=define, usemultiplicity=define
     useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
     use64bitint=undef, use64bitall=undef, uselongdouble=undef
     usemymalloc=n, bincompat5005=undef
   Compiler:
     cc='C:/Perl/site/bin/gcc.exe', ccflags ='-DNDEBUG -DWIN32 -D_CONSOLE  
-DNO_STRICT -DHAVE_DES_FCRYPT -DUSE_SITECUSTOMIZE -DPERL_IMPLICIT_CONTEXT  
-DPERL_IMPLICIT_SYS -DUSE_PERLIO -D_USE_32BIT_TIME_T -DPERL_MSVCRT_READFIX  
-DHASATTRIBUTE -fno-strict-aliasing -mms-bitfields',
     optimize='-O2',
     cppflags='-DWIN32'
     ccversion='', gccversion='3.4.5 (mingw-vista special r3)',  
gccosandvers=''
     intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
     d_longlong=undef, longlongsize=8, d_longdbl=define, longdblsize=8
     ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='__int64',  
lseeksize=8
     alignbytes=8, prototype=define
   Linker and Libraries:
     ld='C:\Perl\site\bin\g++.exe', ldflags ='-L"C:\Perl\lib\CORE"'
     libpth=\lib
     libs=-lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32  
-lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm  
-lversion -lodbc32 -lodbccp32 -lcomctl32 -lmsvcrt
     perllibs=-lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32  
-lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm  
-lversion -lodbc32 -lodbccp32 -lcomctl32 -lmsvcrt
     libc=msvcrt.lib, so=dll, useshrplib=true, libperl=perl512.lib
     gnulibc_version=''
   Dynamic Linking:
     dlsrc=dl_win32.xs, dlext=dll, d_dlsymun=undef, ccdlflags=' '
     cccdlflags=' ', lddlflags='-mdll -L"C:\Perl\lib\CORE"'

Locally applied patches:
     ACTIVEPERL_LOCAL_PATCHES_ENTRY
     c6fbf28 [perl #71806] perldb does not setup %dbline with the shebang  
option -d
     1fd8fa4 Add Wolfram Humann to AUTHORS
     f120055 make string-append on win32 100 times faster
     a2a8d15 Define _USE_32BIT_TIME_T for VC6 and VC7
     007cfe1 Don't pretend to support really old VC++ compilers
     6d8f7c9 Get rid of obsolete PerlCRT.dll support
     d956618 Make Term::ReadLine::findConsole fall back to STDIN if  
/dev/tty can't be opened
     321e50c Escape patch strings before embedding them in patchlevel.h


@INC for perl 5.12.4:
     C:/Perl/site/lib/MSWin32-x86-multi-thread
     C:/Perl/site/lib
     C:/Perl/lib
     .


Environment for perl 5.12.4:
     CYGWIN=nodosfilewarning
     HOME (unset)
     LANG=en_US.utf8
     LANGUAGE (unset)
     LD_LIBRARY_PATH (unset)
     LOGDIR (unset)
     PATH=C:\Program Files (x86)\ActiveState Komodo IDE 7\;C:\Program Files  
(x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\PC  
Connectivity Solution\;C:\Perl64-16\site\bin;C:\Perl64-16\bin;C:\Program  
Files (x86)\ImageMagick-6.7.7-Q16;%CommonProgramFiles%\Microsoft  
Shared\Windows  
Live;C:\Perl\site\bin;C:\Perl\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program  
Files\Intel\WiFi\bin\;C:\Program Files\Common  
Files\Intel\WirelessCommon\;C:\Program Files\ThinkPad\Bluetooth  
Software\;C:\Program Files\ThinkPad\Bluetooth  
Software\syswow64;C:\SWTOOLS\ReadyApps;C:\Program Files  
(x86)\Lenovo\Access Connections\;c:\Program Files  
(x86)\PuTTY\;c:\cygwin\bin\;C:\Program Files  
(x86)\QuickTime\QTSystem\;C:\Program Files  
(x86)\Intel\Services\IPT\;C:\Program Files  
(x86)\GtkSharp\2.12\bin;d:\j\MeCab\bin\;c:\Python27\;c:\Python27\Scripts\;c:\Program  
Files (x86)\CMake  
2.8\bin\;C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;C:\Program  
Files (x86)\Calibre2\;C:\Program Files (x86)\GNU\GnuPG\pub;C:\Program  
Files\TortoiseSVN\bin;C:\Program Files (x86)\Git\cmd;C:\Program  
Files\TortoiseGit\bin;C:\Ruby193\bin;C:\Program Files\Common  
Files\Microsoft Shared\Windows Live;C:\Program  
Files\Intel\WiFi\bin\;C:\Program Files\Common  
Files\Intel\WirelessCommon\;C:\Program Files (x86)\OpenVPN\bin;C:\Program  
Files\Mercurial
     PERL_BADLANG (unset)
     PERL_JSON_BACKEND=JSON::XS
     PERL_STRICTURES_EXTRA=1
     PERL_YAML_BACKEND=YAML::XS
     SHELL (unset)

```
</details>

**Comment by p5pRT** [comment]
### From @wchristian

Small correction\, of course i mean \\0\, not \\o\. It is a bit early in the 
morning here\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @wchristian

An extra piece of info i found out with kmx\, apparently the resulting 
miniperl executable thinks&#8203;:

 This is perl 5\, version 15\, subversion 2 \(007BB008\) built for MSWin32\-x86

This seems wrong\. Might it be caused by the makefile not correctly 
setting up a 64 bit compile?

**Comment by p5pRT** [comment]
### From @bulk88

On Sat Nov 24 20&#8203;:43&#8203;:13 2012\, walde\.christian@&#8203;googlemail\.com wrote&#8203;:
> This is a bug report for perl from walde\.christian@&#8203;googlemail\.com\,
> generated with the help of perlbug 1\.39 running under perl 5\.12\.4\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please describe your issue here\]
> 
> In any checkout with the following git commit id\, or after
> 925798f29c677c612a63a08a92ebb5f169e27b02\, the following commands
> will cause a file containing 8GB of \\o to be written&#8203;:
> 
>   cd win32
>   dmake \.\\config\.h \.\.\\git\_version\.h
>   cd \.\.
>   miniperl \-e "open STDERR\_COPY\, '>&STDERR'; print 1;" 1>log 2>&1
>   perl \-e "print \-s 'log'"
> 

I couldn't reproduce it with my VC miniperl \(the commit is probably
5c26a17602c4585ca111bd154f6c65c681cd0572 but I will soon update\)
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
C&#8203;:\\p517\\src\\lib>\.\.\\miniperl \-V
Summary of my perl5 \(revision 5 version 17 subversion 6\) configuration&#8203;:

&nbsp;  Platform&#8203;:
&nbsp;    osname=MSWin32\, osvers=5\.2\, archname=MSWin32\-x86\-multi\-thread
&nbsp;    uname=''
&nbsp;    config\_args='undef'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=undef
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cl'\, ccflags ='\-nologo \-GF \-W3 \-MD \-Zi \-DNDEBUG \-Od \-GL \-GS\-
\-arch&#8203;:SSE2
\-DWIN32 \-D\_CONSOLE \-DNO\_STRICT \-D\_CRT\_SECURE\_NO\_DEPRECATE
\-D\_CRT\_NONSTDC\_NO\_DEPR
ECATE  \-DPERL\_TEXTMODE\_SCRIPTS \-DPERL\_IMPLICIT\_CONTEXT
\-DPERL\_IMPLICIT\_SYS \-DUSE
\_PERLIO'\,
&nbsp;    optimize='\-MD \-Zi \-DNDEBUG \-Od \-GL \-GS\- \-arch&#8203;:SSE2'\,
&nbsp;    cppflags='\-DWIN32'
&nbsp;    ccversion='15\.00\.30729\.01'\, gccversion=''\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=undef\, longlongsize=8\, d\_longdbl=define\, longdblsize=8
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='\_\_int64'\,
lseeksi
ze=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='link'\, ldflags ='\-nologo \-nodefaultlib \-debug \-opt&#8203;:ref\,icf \-ltcg
 \-libpa
th&#8203;:"c&#8203;:\\p517\\lib\\CORE"  \-machine&#8203;:x86 "/manifestdependency&#8203;:type='Win32'
name='Micr
osoft\.Windows\.Common\-Controls' version='6\.0\.0\.0'
processorArchitecture='\*' publi
cKeyToken='6595b64144ccf1df' language='\*'"'
&nbsp;    libpth=\\lib
&nbsp;    libs=oldnames\.lib kernel32\.lib user32\.lib gdi32\.lib winspool\.lib 
comdlg32\.l
ib advapi32\.lib shell32\.lib ole32\.lib oleaut32\.lib  netapi32\.lib
uuid\.lib ws2\_32
\.lib mpr\.lib winmm\.lib  version\.lib odbc32\.lib odbccp32\.lib comctl32\.lib
msvcrt\.
lib
&nbsp;    perllibs=oldnames\.lib kernel32\.lib user32\.lib gdi32\.lib winspool\.lib
 comdlg
32\.lib advapi32\.lib shell32\.lib ole32\.lib oleaut32\.lib  netapi32\.lib
uuid\.lib ws
2\_32\.lib mpr\.lib winmm\.lib  version\.lib odbc32\.lib odbccp32\.lib
comctl32\.lib msv
crt\.lib
&nbsp;    libc=msvcrt\.lib\, so=dll\, useshrplib=true\, libperl=perl517\.lib
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_win32\.xs\, dlext=dll\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags=' '\, lddlflags='\-dll \-nologo \-nodefaultlib \-debug
\-opt&#8203;:ref\,icf \-l
tcg  \-libpath&#8203;:"c&#8203;:\\p517\\lib\\CORE"  \-machine&#8203;:x86
"/manifestdependency&#8203;:type='Win32'
 name='Microsoft\.Windows\.Common\-Controls' version='6\.0\.0\.0'
processorArchitectur
e='\*' publicKeyToken='6595b64144ccf1df' language='\*'"'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: HAS\_TIMES HAVE\_INTERP\_INTERN MULTIPLICITY
&nbsp;                        PERLIO\_LAYERS PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_EXTERNAL\_GLOB PERL\_IMPLICIT\_CONTEXT
&nbsp;                        PERL\_IS\_MINIPERL PERL\_MALLOC\_WRAP PERL\_PRESERVE\_IVUV
&nbsp;                        USE\_ITHREADS USE\_LARGE\_FILES USE\_LOCALE
&nbsp;                        USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_PERLIO USE\_PERL\_ATOF
&nbsp;                        USE\_SITECUSTOMIZE
&nbsp;  Built under MSWin32
&nbsp;  Compiled at Nov  7 2012 23&#8203;:42&#8203;:27
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    \.
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
I got 1 byte long file on Sever 2003 x64\, with 32 bit perl\. I know there
was a \#win32 conversation on this bug recently but I didn't log it and
dont remember what it said\.
\-\- 
bulk88 ~ bulk88 at hotmail\.com

**Comment by p5pRT** [comment]
### From @wchristian

On Tue Nov 27 02&#8203;:36&#8203;:39 2012\, bulk88 wrote&#8203;:

> I couldn't reproduce it with my VC miniperl

Thanks for checking\. So it seems this issue is only with MinGW\. \(I'm 
specifically using the MinGW included with ActivePerl 5\.12\.4\.\)

**Comment by p5pRT** [comment]
### From @bulk88

On Tue Nov 27 03&#8203;:37&#8203;:05 2012\, Mithaldu wrote&#8203;:
> On Tue Nov 27 02&#8203;:36&#8203;:39 2012\, bulk88 wrote&#8203;:
> 
> > I couldn't reproduce it with my VC miniperl
> 
> Thanks for checking\. So it seems this issue is only with MinGW\. \(I'm 
> specifically using the MinGW included with ActivePerl 5\.12\.4\.\)

Also tried with 9566f14a1e60201c203759da1798f55f226bac9e \(blead today\)\,
VC 2003\, 32 bit on x64 2003\, couldnt reproduce\.
\-\- 
bulk88 ~ bulk88 at hotmail\.com

**Comment by p5pRT** [comment]
### From @wchristian

Alright\, after a lengthy session of looking at things with bulk88\, 
another aspect of the problem is now clear&#8203;:

I compiled perl on Win7\-64\, using the MinGW included in 32 bit Perl 
distros\. Due to the OS\, the makefile decides to use 64 bit header files\, 
but due to the compiler the resulting binary is actually a 32 bit binary\, 
using 64 bit configuration values\.

The \-v/\-V output of miniperl demonstrates this&#8203;: https&#8203;://
gist\.github\.com/7673e573f642a7896d70 and analysis of the PE headers 
supports it\.

At first blush one could think that this means the correct solution is to 
use a 64 bit compiler instead\. I have started a smoke of blead with a 64 
bit MinGW \(gcc version 4\.5\.4 \(rubenvb\-4\.5\.4\)\) and its miniperl does not 
exhibit the problematic 8 gb behavior\. However now it just doesn't output 
anything anymore\. The command mentioned in the first message of this bug 
results in the file "log" being 0 bytes long\.

**Comment by p5pRT** [comment]
### From @bulk88

On Tue Nov 27 06&#8203;:44&#8203;:11 2012\, Mithaldu wrote&#8203;:
> Alright\, after a lengthy session of looking at things with bulk88\, 
> another aspect of the problem is now clear&#8203;:
> 
> I compiled perl on Win7\-64\, using the MinGW included in 32 bit Perl 
> distros\. Due to the OS\, the makefile decides to use 64 bit header files\, 
> but due to the compiler the resulting binary is actually a 32 bit binary\, 
> using 64 bit configuration values\.
> 
> The \-v/\-V output of miniperl demonstrates this&#8203;: https&#8203;://
> gist\.github\.com/7673e573f642a7896d70 and analysis of the PE headers 
> supports it\.
> 
> At first blush one could think that this means the correct solution is to 
> use a 64 bit compiler instead\. I have started a smoke of blead with a 64 
> bit MinGW \(gcc version 4\.5\.4 \(rubenvb\-4\.5\.4\)\) and its miniperl does not 
> exhibit the problematic 8 gb behavior\. However now it just doesn't output 
> anything anymore\. The command mentioned in the first message of this bug 
> results in the file "log" being 0 bytes long\.

I looked at Mithaldu's miniperl' asm code\, in pp\_sysread\, the SSize\_t
vars were 64 bit ints\. His miniperl is 32 bit asm code\. It is as if you
forgot to uncomment WIN64 at the top of the makefile\, but no
architecture is being forced from the makefile to GCC I think\, so GCC
compiles as "default" \(32 bits in this case\)\, even though perl's headers
and config\.h and makefile are set for x64 perl\.
\-\- 
bulk88 ~ bulk88 at hotmail\.com

**Comment by p5pRT** [comment]
### From @jkeenan

On Tue Nov 27 06&#8203;:44&#8203;:11 2012\, Mithaldu wrote&#8203;:
> Alright\, after a lengthy session of looking at things with bulk88\, 
> another aspect of the problem is now clear&#8203;:
> 
> I compiled perl on Win7\-64\, using the MinGW included in 32 bit Perl 
> distros\. Due to the OS\, the makefile decides to use 64 bit header files\, 
> but due to the compiler the resulting binary is actually a 32 bit binary\, 
> using 64 bit configuration values\.
> 
> The \-v/\-V output of miniperl demonstrates this&#8203;: https&#8203;://
> gist\.github\.com/7673e573f642a7896d70 and analysis of the PE headers 
> supports it\.
> 
> At first blush one could think that this means the correct solution is to 
> use a 64 bit compiler instead\. I have started a smoke of blead with a 64 
> bit MinGW \(gcc version 4\.5\.4 \(rubenvb\-4\.5\.4\)\) and its miniperl does not 
> exhibit the problematic 8 gb behavior\. However now it just doesn't output 
> anything anymore\. The command mentioned in the first message of this bug 
> results in the file "log" being 0 bytes long\.

Mithaldu\, bulk88&#8203;:  Would it be possible to get an update on the status of this ticket?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From @bulk88

On Sat Dec 14 13&#8203;:25&#8203;:05 2013\, jkeenan wrote&#8203;:
> 
> Mithaldu\, bulk88&#8203;:  Would it be possible to get an update on the status
> of this ticket?
> 
> Thank you very much\.
> Jim Keenan

I didn't compile the perl causing the 8 GB file\, I only debugged the binaries Mithaldu sent me\.

\-\- 
bulk88 ~ bulk88 at hotmail\.com

**Comment by toddr** [comment]
@wchristian barring further information, I don't see anything actionable here. Are we ok to close?

**Comment by jkeenan** [comment]
> @wchristian barring further information, I don't see anything actionable here. Are we ok to close?

Self-assigning for the purpose of closing in 7 days unless the discussion is moved forward.

**Comment by jkeenan** [comment]
> > @wchristian barring further information, I don't see anything actionable here. Are we ok to close?
> 
> Self-assigning for the purpose of closing in 7 days unless the discussion is moved forward.

Closing as per schedule.
