### ISSUE TITLE
can't install deprecated Devel::InnerPackage

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#12924]
Migrated from [rt.perl.org#117711](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=117711) (status was 'open')

Searchable as RT117711$

**Comment by p5pRT** [comment]
### From @chorny

perl 5\.17\.11\, CPAN shell\, CPAN&#8203;::SQLite is not used\.

Catalyst depends on Module&#8203;::Pluggable which contains
Devel&#8203;::InnerPackage\, but Module&#8203;::Pluggable was not reinstalled\.
So when executing Catalyst tests\, warning appears&#8203;:
"Devel&#8203;::InnerPackage will be removed from the Perl core distribution
in the next major release\. Please install it from CPAN\. It is being
used at \.\.\.\."

cpan\[2\]> install Devel&#8203;::InnerPackage
Devel&#8203;::InnerPackage is up to date \(0\.4\)\.

cpan\[3\]> install Module&#8203;::CoreList
Module&#8203;::CoreList is up to date \(2\.87\)\.

cpan\[4\]> install CPAN
CPAN is up to date \(2\.00\)\.

\-\-
Alexandr Ciornii\, http&#8203;://chorny\.net

**Comment by p5pRT** [comment]
### From @jkeenan

On Mon Apr 22 13&#8203;:03&#8203;:59 2013\, chorny wrote&#8203;:
> perl 5\.17\.11\, CPAN shell\, CPAN&#8203;::SQLite is not used\.
> 
> Catalyst depends on Module&#8203;::Pluggable which contains
> Devel&#8203;::InnerPackage\, but Module&#8203;::Pluggable was not reinstalled\.
> So when executing Catalyst tests\, warning appears&#8203;:
> "Devel&#8203;::InnerPackage will be removed from the Perl core distribution
> in the next major release\. Please install it from CPAN\. It is being
> used at \.\.\.\."
> 
> cpan\[2\]> install Devel&#8203;::InnerPackage
> Devel&#8203;::InnerPackage is up to date \(0\.4\)\.
> 
> cpan\[3\]> install Module&#8203;::CoreList
> Module&#8203;::CoreList is up to date \(2\.87\)\.
> 
> cpan\[4\]> install CPAN
> CPAN is up to date \(2\.00\)\.
> 
> \-\-
> Alexandr Ciornii\, http&#8203;://chorny\.net


Alex\,

As I read the MANIFEST and Porting/Maintainers\.pl\, Devel&#8203;::InnerPackage
is part of the Module\-Pluggable distribution\, which in turn is
maintained on CPAN\.

\#\#\#\#\#
&nbsp;    'Module&#8203;::Pluggable' => \{
&nbsp;        'MAINTAINER'   => 'simonw'\,
&nbsp;        'DISTRIBUTION' => 'SIMONW/Module\-Pluggable\-4\.7\.tar\.gz'\,
&nbsp;        'FILES'        => q\[cpan/Module\-Pluggable\]\,
&nbsp;        'UPSTREAM'     => 'cpan'\,
&nbsp;        'CUSTOMIZED'   => \['Makefile\.PL'\]\,
&nbsp;    \}\,
\#\#\#\#\#
So I think this bug should be filed at Module\-Pluggable's bug queue&#8203;: 
https://rt.cpan.org/Ticket/Create.html?Queue=Module-Pluggable

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From zefram@fysh.org

James E Keenan via RT wrote&#8203;:
>So I think this bug should be filed at Module\-Pluggable's bug queue&#8203;: 

No\, it should be filed in CPAN's bug queue\.  The bug is that CPAN\.pm
doesn't recognise the need to reinstall the module from CPAN in this
situation\.

\-zefram

**Comment by p5pRT** [comment]
### From @bingos

On Tue\, Apr 23\, 2013 at 09&#8203;:30&#8203;:48AM \+0100\, Zefram wrote&#8203;:
> James E Keenan via RT wrote&#8203;:
> >So I think this bug should be filed at Module\-Pluggable's bug queue&#8203;: 
> 
> No\, it should be filed in CPAN's bug queue\.  The bug is that CPAN\.pm
> doesn't recognise the need to reinstall the module from CPAN in this
> situation\.
> 

I think that Module&#8203;::CoreList may have been to blame as the deprecation
data for v5\.17\.10 and v5\.17\.11 was missing \(which is where the CPAN
clients get the fact that a module has been deprecated in core\)\.

I've updated Module\-CoreList and shipped 2\.88 to CPAN\.

Cheers\,

\-\- 
Chris Williams
aka BinGOs
PGP ID 0x4658671F
http&#8203;://www\.gumbynet\.org\.uk
==========================

**Comment by p5pRT** [comment]
### From @jkeenan

On Tue Apr 23 04&#8203;:45&#8203;:03 2013\, chris@&#8203;bingosnet\.co\.uk wrote&#8203;:

> 
> I think that Module&#8203;::CoreList may have been to blame as the deprecation
> data for v5\.17\.10 and v5\.17\.11 was missing \(which is where the CPAN
> clients get the fact that a module has been deprecated in core\)\.
> 
> I've updated Module\-CoreList and shipped 2\.88 to CPAN\.
> 

chorny\,

Can you update your Module\-Corelist and see if that solves the original
problem?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From @jkeenan

On Tue Apr 23 16&#8203;:01&#8203;:51 2013\, jkeenan wrote&#8203;:
> On Tue Apr 23 04&#8203;:45&#8203;:03 2013\, chris@&#8203;bingosnet\.co\.uk wrote&#8203;:
> 
> > 
> > I think that Module&#8203;::CoreList may have been to blame as the deprecation
> > data for v5\.17\.10 and v5\.17\.11 was missing \(which is where the CPAN
> > clients get the fact that a module has been deprecated in core\)\.
> > 
> > I've updated Module\-CoreList and shipped 2\.88 to CPAN\.
> > 
> 
> chorny\,
> 
> Can you update your Module\-Corelist and see if that solves the original
> problem?
> 
> Thank you very much\.
> Jim Keenan

chorny\,

Can you see if the changes shipped with Perl 5\.18\.0 clear this problem up?

Thank you very much\.
Jim Keenan

**Comment by jkeenan** [comment]
> ### From @jkeenan
> 
> On Tue Apr 23 16​:01​:51 2013, jkeenan wrote​:
> 
> > On Tue Apr 23 04​:45​:03 2013, chris@​bingosnet.co.uk wrote​:
> > > I think that Module​::CoreList may have been to blame as the deprecation
> > > data for v5.17.10 and v5.17.11 was missing (which is where the CPAN
> > > clients get the fact that a module has been deprecated in core).
> > > I've updated Module-CoreList and shipped 2.88 to CPAN.
> > 
> > 
> > chorny,
> > Can you update your Module-Corelist and see if that solves the original
> > problem?
> > Thank you very much.
> > Jim Keenan
> 
> chorny,
> 
> Can you see if the changes shipped with Perl 5.18.0 clear this problem up?
> 

@chorny, since we haven't heard back from you on this problem, I'm going to assume it's resolved and close this ticket.  Please file a new issue if the problem persists.

Thank you very much.
Jim Keenan
