### ISSUE TITLE
[EXPERIMENT] extended bracketed character classes

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#13197]
Migrated from [rt.perl.org#119451](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=119451) (status was 'new')

Searchable as RT119451$

**Comment by p5pRT** [comment]
### From @rjbs

perl 5\.18\.0 introduced extended regular expression bracketed character classes\,
such as&#8203;:

&nbsp;  /\(?\[ \\p\{Thai\} & \\p\{Digit\} \]\)/

In perl 5\.18\.0\, this is behind experimental&#8203;::regex\_sets warnings and documented
as "subject to change as we gain field experience with it\."

This ticket should collect lessons learned\, fixes made\, and the acceptance
criteria for dropping the "experimental" status of the feature\.

\-\- 
rjbs

**Comment by khwilliamson** [comment]
There have been some bugs found in this over the years, that a search through tickets could show.

Currently, there is the open ticket https://github.com/Perl/perl5/issues/16779

**Comment by khwilliamson** [comment]
This was closed via #19503
