### ISSUE TITLE
[PATCH] Generate function prototypes in pod for undocumented functions

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#13428]
Migrated from [rt.perl.org#120572](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=120572) (status was 'open')

Searchable as RT120572$

**Comment by p5pRT** [comment]
### From @wolfsage

#### Created by WolfSage@gmail.com



The attached patch changes the pod for undocumented functions
in perlintern\.pod and perlapi\.pod from this&#8203;:

&nbsp;       GetVars
&nbsp;       Gv\_AMupdate
&nbsp;       PerlIO\_clearerr
&nbsp;       \[\.\.\.\]

to this&#8203;:

&nbsp;       GetVars
&nbsp;                   struct perl\_vars \* GetVars\(\)

&nbsp;       Gv\_AMupdate
&nbsp;                   int     Gv\_AMupdate\(HV\* stash\, bool destructing\)

&nbsp;       PerlIO\_clearerr
&nbsp;                   void    PerlIO\_clearerr\(PerlIO \*f\)

&nbsp;       \[\.\.\.\]

This is nice because prototypes then don't need to be looked up in the
respective \.h/\.c files\.

I have one concern with this however\. Things that have two possible
prototypes depending
on configuration will list only one of them&#8203;:

For example&#8203;:

&nbsp;       csighandler
&nbsp;                   Signal\_t csighandler\(int sig\, siginfo\_t \*info\,
&nbsp;                                        void \*uap\)

In embed\.fnc&#8203;:

&nbsp;  \#if defined\(HAS\_SIGACTION\) && defined\(SA\_SIGINFO\)
&nbsp;  Anp     |Signal\_t |csighandler  |int sig|NULLOK siginfo\_t
\*info|NULLOK void \*uap
&nbsp;  \#else
&nbsp;  Anp     |Signal\_t |csighandler  |int sig

Is this a problem?

Also\, undocumented functions are considered to have an "unstable API"\,
so maybe this functionality
shouldn't be added at all\. \(I'd be fine with that\.\)

Thanks\.

\-\- Matthew Horsfall \(alh\)

<details><summary>Perl Info</summary>

```

Flags:
    category=docs
    severity=low

Site configuration information for perl 5.14.2:

Configured by Debian Project at Mon Mar 18 19:16:26 UTC 2013.

Summary of my perl5 (revision 5 version 14 subversion 2) configuration:

  Platform:
    osname=linux, osvers=2.6.42-37-generic,
archname=x86_64-linux-gnu-thread-multi
    uname='linux batsu 2.6.42-37-generic #58-ubuntu smp thu jan 24
15:28:10 utc 2013 x86_64 x86_64 x86_64 gnulinux '
    config_args='-Dusethreads -Duselargefiles -Dccflags=-DDEBIAN
-Dcccdlflags=-fPIC -Darchname=x86_64-linux-gnu -Dprefix=/usr
-Dprivlib=/usr/share/perl/5.14 -Darchlib=/usr/lib/perl/5.14
-Dvendorprefix=/usr -Dvendorlib=/usr/share/perl5
-Dvendorarch=/usr/lib/perl5 -Dsiteprefix=/usr/local
-Dsitelib=/usr/local/share/perl/5.14.2
-Dsitearch=/usr/local/lib/perl/5.14.2 -Dman1dir=/usr/share/man/man1
-Dman3dir=/usr/share/man/man3 -Dsiteman1dir=/usr/local/man/man1
-Dsiteman3dir=/usr/local/man/man3 -Duse64bitint -Dman1ext=1
-Dman3ext=3perl -Dpager=/usr/bin/sensible-pager -Uafs -Ud_csh
-Ud_ualarm -Uusesfio -Uusenm -Ui_libutil -DDEBUGGING=-g -Doptimize=-O2
-Duseshrplib -Dlibperl=libperl.so.5.14.2 -des'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DDEBIAN
-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include
-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2 -g',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fno-strict-aliasing
-pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.6.3', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t',
lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib /lib/x86_64-linux-gnu /lib/../lib
/usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib /usr/lib
    libs=-lgdbm -lgdbm_compat -ldb -ldl -lm -lpthread -lc -lcrypt
    perllibs=-ldl -lm -lpthread -lc -lcrypt
    libc=, so=so, useshrplib=true, libperl=libperl.so.5.14.2
    gnulibc_version='2.15'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -g -L/usr/local/lib
-fstack-protector'

Locally applied patches:



@INC for perl 5.14.2:
    /etc/perl
    /usr/local/lib/perl/5.14.2
    /usr/local/share/perl/5.14.2
    /usr/lib/perl5
    /usr/share/perl5
    /usr/lib/perl/5.14
    /usr/share/perl/5.14
    /usr/local/lib/site_perl
    .


Environment for perl 5.14.2:
    HOME=/home/mhorsfall
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/mhorsfall/perl5/perlbrew/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
    PERLBREW_BASHRC_VERSION=0.66
    PERLBREW_HOME=/home/mhorsfall/.perlbrew
    PERLBREW_ROOT=/home/mhorsfall/perl5/perlbrew
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @wolfsage

<details><summary>0001-Generate-function-prototypes-in-pod-for-undocumented.patch</summary>

```diff
From 28ec18d1deae155242ddddbdbcbdd9032ca40197 Mon Sep 17 00:00:00 2001
From: Matthew Horsfall <WolfSage@gmail.com>
Date: Mon, 18 Nov 2013 09:57:18 -0500
Subject: [PATCH] Generate function prototypes in pod for undocumented
 functions.

---
 autodoc.pl |   71 +++++++++++++++++++++++++++++++++++++-----------------------
 1 file changed, 44 insertions(+), 27 deletions(-)

diff --git a/autodoc.pl b/autodoc.pl
index bff2094..6e7fa47 100644
--- a/autodoc.pl
+++ b/autodoc.pl
@@ -174,26 +174,8 @@ DOC:
     }
 }
 
-sub docout ($$$) { # output the docs for one function
-    my($fh, $name, $docref) = @_;
-    my($flags, $docs, $ret, $file, @args) = @$docref;
-    $name =~ s/\s*$//;
-
-    if ($flags =~ /D/) {
-        $docs = "\n\nDEPRECATED!  It is planned to remove this function from a
-future release of Perl.  Do not use it for new code; remove it from
-existing code.\n\n$docs";
-    }
-    else {
-        $docs = "\n\nNOTE: this function is experimental and may change or be
-removed without notice.\n\n$docs" if $flags =~ /x/;
-    }
-    $docs .= "NOTE: the perl_ form of this function is deprecated.\n\n"
-	if $flags =~ /p/;
-    $docs .= "NOTE: this function must be explicitly called as Perl_$name with an aTHX_ parameter.\n\n"
-        if $flags =~ /o/;
-
-    print $fh "=item $name\nX<$name>\n$docs";
+sub argsout($$$$$) {
+    my ($fh, $name, $flags, $ret, $argsref) = @_;
 
     if ($flags =~ /U/) { # no usage
 	# nothing
@@ -211,7 +193,7 @@ removed without notice.\n\n$docs" if $flags =~ /x/;
 	my $indent;
 	print $fh "\t$ret" . ($large_ret ? ' ' : "\t") . "$n(";
 	my $long_args;
-	for (@args) {
+	for (@$argsref) {
 	    if ($indent_size + 2 + length > 79) {
 		$long_args=1;
 		$indent_size -= length($n) - 3;
@@ -220,15 +202,15 @@ removed without notice.\n\n$docs" if $flags =~ /x/;
 	}
 	my $args = '';
 	if ($p) {
-	    $args = @args ? "pTHX_ " : "pTHX";
+	    $args = @$argsref ? "pTHX_ " : "pTHX";
 	    if ($long_args) { print $fh $args; $args = '' }
 	}
 	$long_args and print $fh "\n";
 	my $first = !$long_args;
 	while () {
-	    if (!@args or
+	    if (!@$argsref or
 	         length $args
-	         && $indent_size + 3 + length($args[0]) + length $args > 79
+	         && $indent_size + 3 + length($argsref->[0]) + length $args > 79
 	    ) {
 		print $fh
 		  $first ? '' : (
@@ -236,16 +218,41 @@ removed without notice.\n\n$docs" if $flags =~ /x/;
 		       "\t".($large_ret ? " " x (1+length $ret) : "\t")
 		      ." "x($long_args ? 4 : 1 + length $n)
 		  ),
-		  $args, (","x($args ne 'pTHX_ ') . "\n")x!!@args;
+		  $args, (","x($args ne 'pTHX_ ') . "\n")x!!@$argsref;
 		$args = $first = '';
 	    }
-	    @args or last;
+	    @$argsref or last;
 	    $args .= ", "x!!(length $args && $args ne 'pTHX_ ')
-	           . shift @args;
+	           . shift @$argsref;
 	}
 	if ($long_args) { print $fh "\n", substr $indent, 0, -4 }
 	print $fh ")\n\n";
     }
+}
+
+sub docout ($$$) { # output the docs for one function
+    my($fh, $name, $docref) = @_;
+    my($flags, $docs, $ret, $file, @args) = @$docref;
+    $name =~ s/\s*$//;
+
+    if ($flags =~ /D/) {
+        $docs = "\n\nDEPRECATED!  It is planned to remove this function from a
+future release of Perl.  Do not use it for new code; remove it from
+existing code.\n\n$docs";
+    }
+    else {
+        $docs = "\n\nNOTE: this function is experimental and may change or be
+removed without notice.\n\n$docs" if $flags =~ /x/;
+    }
+    $docs .= "NOTE: the perl_ form of this function is deprecated.\n\n"
+	if $flags =~ /p/;
+    $docs .= "NOTE: this function must be explicitly called as Perl_$name with an aTHX_ parameter.\n\n"
+        if $flags =~ /o/;
+
+    print $fh "=item $name\nX<$name>\n$docs";
+
+    argsout($fh, $name, $flags, $ret, \@args);
+
     print $fh "=for hackers\nFound in file $file\n\n";
 }
 
@@ -304,6 +311,16 @@ it.
 _EOB_
     for my $missing (sort @$missing) {
         print $fh "=item $missing\nX<$missing>\n\n";
+
+        my $docref = $funcflags{$missing};
+
+        # Flags come from "=for apidoc <...> lines, excepting A, M, and D, which 
+        # argsout() doesn't care about anyway.
+        my $flags = ''; 
+        my $ret = $docref->{retval};
+        my @args = @{$docref->{args}};
+
+        argsout($fh, $missing, $flags, $ret, \@args);
     }
     print $fh "=back\n\n";
 }
-- 
1.7.9.5


```
</details>

**Comment by p5pRT** [comment]
### From perl5-porters@perl.org

Matthew Horsfall wrote&#8203;:
> Also\, undocumented functions are considered to have an "unstable API"\,
> so maybe this functionality
> shouldn't be added at all\. \(I'd be fine with that\.\)

That is my thought\, too\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon Nov 18 08&#8203;:27&#8203;:01 2013\, perl5\-porters@&#8203;perl\.org wrote&#8203;:
> Matthew Horsfall wrote&#8203;:
> > Also\, undocumented functions are considered to have an "unstable API"\,
> > so maybe this functionality
> > shouldn't be added at all\. \(I'd be fine with that\.\)
> 
> That is my thought\, too\.

If they're unstable that should be marked in the API with M \- is the API for
PerlIO\_read\(\) considered unstable?

Tony

**Comment by p5pRT** [comment]
### From perl5-porters@perl.org

Tony Cook wrote&#8203;:
> If they're unstable that should be marked in the API with M \- is the API for
> PerlIO\_read\(\) considered unstable?

That is the idea\, but it does not always happen in practice\.  For
instance\, there are things that were added to the API "by mistake"
which needed to change just to make things work\.  newMYSUB and
hv\_placeholders\_p come to mind\.

Reviewing which functions fall under that category is nearly impossi\-
ble\, because one can only see the problems with such functions during
bug fixing and refactoring\.

**Comment by jkeenan** [comment]
> ### From @wolfsage
> #### Created by [WolfSage@gmail.com](mailto:WolfSage@gmail.com)
> 
> The attached patch changes the pod for undocumented functions in perlintern.pod and perlapi.pod from this​:
> 
>   GetVars   Gv_AMupdate   PerlIO_clearerr   [...]
> 
> to this​:
> 
>   GetVars   struct perl_vars * GetVars()
> 
>   Gv_AMupdate   int Gv_AMupdate(HV* stash, bool destructing)
> 
>   PerlIO_clearerr   void PerlIO_clearerr(PerlIO *f)
> 
>   [...]
> 

@wolfsage, this ticket you opened in 2013 had a patch to autodoc.pl.  In subsequent comments it appears that both you and @tonycoz had second thoughts about its appropriateness.  Do you wish to pursue it further?  If not, we should close it.  Thanks.

**Comment by jkeenan** [comment]
> > ### From @wolfsage
> > #### Created by [WolfSage@gmail.com](mailto:WolfSage@gmail.com)
> > The attached patch changes the pod for undocumented functions in perlintern.pod and perlapi.pod from this​:
> > GetVars   Gv_AMupdate   PerlIO_clearerr   [...]
> > to this​:
> > GetVars   struct perl_vars * GetVars()
> > Gv_AMupdate   int Gv_AMupdate(HV* stash, bool destructing)
> > PerlIO_clearerr   void PerlIO_clearerr(PerlIO *f)
> > [...]
> 
> @wolfsage, this ticket you opened in 2013 had a patch to autodoc.pl. In subsequent comments it appears that both you and @tonycoz had second thoughts about its appropriateness. Do you wish to pursue it further? If not, we should close it. Thanks.

No response; closing.
