### ISSUE TITLE
Clarification for File::Copy documentation

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#13440]
Migrated from [rt.perl.org#120619](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=120619) (status was 'open')

Searchable as RT120619$

**Comment by p5pRT** [comment]
### From @rrthomas

File&#8203;::Copy's documentation says about syscopy&#8203;: "For Unix systems\, this is
equivalent to the simple "copy" routine\, which doesn't preserve OS\-specific
attributes\."

Does this mean that syscopy is like copy\, and not like cp\, where\, according
to the same documentation\, "as of version 2\.15\, \<cp> will preserve the
source file's permission bits like the shell utility cp\(1\) would do"? That
would not seem very logical\.

Also\, the phrase "doesn't preserve OS\-specific attributes" is confusing
when talking about a particular OS&#8203;: when reading the page\, I wondered if it
referred to file\-system\-specific attributes on UNIX\. Maybe it's better just
to leave it out\.

Assuming that sanity prevails under the hood\, and syscopy is equivalent to
cp\, I suggest rewriting this as&#8203;:

"For Unix systems\, this is equivalent to the simple "cp" routine\."

If for some reason syscopy on Unix works the same as "copy"\, then instead&#8203;:

"For Unix systems\, this is equivalent to the simple "copy" routine\, and
doesn't preserve attributes\."

\(Checked against latest version at http&#8203;://perldoc\.perl\.org/File/Copy\.html\)

\-\- 
http&#8203;://rrt\.sc3d\.org

**Comment by p5pRT** [comment]
### From @tonycoz

On Sat Nov 23 14&#8203;:11&#8203;:05 2013\, rrt wrote&#8203;:
> File&#8203;::Copy's documentation says about syscopy&#8203;: "For Unix systems\, this is
> equivalent to the simple "copy" routine\, which doesn't preserve OS\-specific
> attributes\."
> 
> Does this mean that syscopy is like copy\, and not like cp\, where\, according
> to the same documentation\, "as of version 2\.15\, \<cp> will preserve the
> source file's permission bits like the shell utility cp\(1\) would do"? That
> would not seem very logical\.
> 
> Also\, the phrase "doesn't preserve OS\-specific attributes" is confusing
> when talking about a particular OS&#8203;: when reading the page\, I wondered if it
> referred to file\-system\-specific attributes on UNIX\. Maybe it's better just
> to leave it out\.
> 
> Assuming that sanity prevails under the hood\, and syscopy is equivalent to
> cp\, I suggest rewriting this as&#8203;:
> 
> "For Unix systems\, this is equivalent to the simple "cp" routine\."
> 
> If for some reason syscopy on Unix works the same as "copy"\, then instead&#8203;:
> 
> "For Unix systems\, this is equivalent to the simple "copy" routine\, and
> doesn't preserve attributes\."
> 
> \(Checked against latest version at http&#8203;://perldoc\.perl\.org/File/Copy\.html\)

For Unix systems \(everything but OS/2\, Win32\, VMS\) syscopy is an alias for copy&#8203;:

\# &syscopy is an XSUB under OS/2
unless \(defined &syscopy\) \{
&nbsp;    if \($^O eq 'VMS'\) \{
&nbsp;    \*syscopy = \\&rmscopy;
&nbsp;    \} elsif \($^O eq 'MSWin32' && defined &DynaLoader&#8203;::boot\_DynaLoader\) \{
&nbsp;    \# Win32&#8203;::CopyFile\(\) fill only work if we can load Win32\.xs
&nbsp;    \*syscopy = sub \{
&nbsp;        return 0 unless @&#8203;\_ == 2;
&nbsp;        return Win32&#8203;::CopyFile\(@&#8203;\_\, 1\);
&nbsp;    \};
&nbsp;    \} else \{
&nbsp;    $Syscopy\_is\_copy = 1;
&nbsp;    \*syscopy = \\&copy;
&nbsp;    \}
\}


I don't think your edit of the sentence from&#8203;:

For Unix systems\, this is equivalent to the simple C\<copy> routine\, which doesn't preserve OS\-specific attributes\.

to&#8203;:

For Unix systems\, this is equivalent to the simple C\<copy> routine\, and
doesn't preserve attributes\.

adds much\, since copy\(\) does preserve OS independent attributes \- the content of the file\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @rrthomas

On Mon Dec 16 15&#8203;:38&#8203;:07 2013\, tonyc wrote&#8203;:
> On Sat Nov 23 14&#8203;:11&#8203;:05 2013\, rrt wrote&#8203;:
> > File&#8203;::Copy's documentation says about syscopy&#8203;: "For Unix systems\,
> > this is
> > equivalent to the simple "copy" routine\, which doesn't preserve OS\-
> > specific
> > attributes\."
> >
> > Does this mean that syscopy is like copy\, and not like cp\, where\,
> > according
> > to the same documentation\, "as of version 2\.15\, \<cp> will preserve
> > the
> > source file's permission bits like the shell utility cp\(1\) would do"?
> > That
> > would not seem very logical\.
> >
> > Also\, the phrase "doesn't preserve OS\-specific attributes" is
> > confusing
> > when talking about a particular OS&#8203;: when reading the page\, I wondered
> > if it
> > referred to file\-system\-specific attributes on UNIX\. Maybe it's
> > better just
> > to leave it out\.
> >
> > Assuming that sanity prevails under the hood\, and syscopy is
> > equivalent to
> > cp\, I suggest rewriting this as&#8203;:
> >
> > "For Unix systems\, this is equivalent to the simple "cp" routine\."
> >
> > If for some reason syscopy on Unix works the same as "copy"\, then
> > instead&#8203;:
> >
> > "For Unix systems\, this is equivalent to the simple "copy" routine\,
> > and
> > doesn't preserve attributes\."
> >
> > \(Checked against latest version at
> > http&#8203;://perldoc\.perl\.org/File/Copy\.html\)
> 
> For Unix systems \(everything but OS/2\, Win32\, VMS\) syscopy is an alias
> for copy&#8203;:
> 
> \# &syscopy is an XSUB under OS/2
> unless \(defined &syscopy\) \{
>     if \($^O eq 'VMS'\) \{
>         \*syscopy = \\&rmscopy;
>     \} elsif \($^O eq 'MSWin32' && defined &DynaLoader&#8203;::boot\_DynaLoader\)
> \{
>         \# Win32&#8203;::CopyFile\(\) fill only work if we can load Win32\.xs
>         \*syscopy = sub \{
>             return 0 unless @&#8203;\_ == 2;
>             return Win32&#8203;::CopyFile\(@&#8203;\_\, 1\);
>         \};
>     \} else \{
>         $Syscopy\_is\_copy = 1;
>         \*syscopy = \\&copy;
>     \}
> \}
> 
> 
> I don't think your edit of the sentence from&#8203;:
> 
> For Unix systems\, this is equivalent to the simple C\<copy> routine\,
> which doesn't preserve OS\-specific attributes\.
> 
> to&#8203;:
> 
> For Unix systems\, this is equivalent to the simple C\<copy> routine\,
> and
> doesn't preserve attributes\.
> 
> adds much\, since copy\(\) does preserve OS independent attributes \- the
> content of the file\.

I fear I was unclear\. I proposed that change in the case that the semantics were the other way around\, i\.e\. if syscopy on Unix worked the same as the description of the simple copy routine\. Since\, as you say\, it is not so\, it is my first suggestion that should be taken into account\, namely\, that the above sentence be rewritten as&#8203;:

For Unix systems\, this is equivalent to the simple "cp" routine\.

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon Dec 16 19&#8203;:52&#8203;:51 2013\, rrt wrote&#8203;:
> On Mon Dec 16 15&#8203;:38&#8203;:07 2013\, tonyc wrote&#8203;:
> > For Unix systems \(everything but OS/2\, Win32\, VMS\) syscopy is an
> > alias
> > for copy&#8203;:
> >
\.\.\.
> > I don't think your edit of the sentence from&#8203;:
> >
> > For Unix systems\, this is equivalent to the simple C\<copy> routine\,
> > which doesn't preserve OS\-specific attributes\.
> >
> > to&#8203;:
> >
> > For Unix systems\, this is equivalent to the simple C\<copy> routine\,
> > and
> > doesn't preserve attributes\.
> >
> > adds much\, since copy\(\) does preserve OS independent attributes \- the
> > content of the file\.
> 
> I fear I was unclear\. I proposed that change in the case that the
> semantics were the other way around\, i\.e\. if syscopy on Unix worked
> the same as the description of the simple copy routine\. Since\, as you
> say\, it is not so\, it is my first suggestion that should be taken into
> account\, namely\, that the above sentence be rewritten as&#8203;:
> 
> For Unix systems\, this is equivalent to the simple "cp" routine\.

I said that syscopy is an alias for copy\, neither is equivalent to cp on Unix systems\.

Tony

**Comment by p5pRT** [comment]
### From @rrthomas

On Wed Dec 18 20&#8203;:13&#8203;:12 2013\, tonyc wrote&#8203;:
> I said that syscopy is an alias for copy\, neither is equivalent to cp
> on Unix systems\.

OK\, it looks like my understanding was closer to reality the first time around\.

Rereading your first reply\, you say&#8203;:

"since copy\(\) does preserve OS independent attributes \- the content of the file\."

But "the content of the file" is not an "attribute"\. Attributes are metadata\, the contents are data\. Wikipedia\[1\] says it clearly&#8203;: "File attributes are metadata associated with computer files that define file system behavior"\, and other sources either subset this\, e\.g\. PC Magazine\[2\]\, which does not include the time and date stamp\, or agree\, e\.g\. the XXCOPY bulletin\[3\]\, which gives both sorts of definition&#8203;: "Although one can say the file size and the file date/time are file attributes \(i\.e\.\, any properties associated with a file other than the file contents\)\, with the more narrow definition and popular usage\, the file attributes are collection of flags stored as a bit mapped 32\-bit quantity which describes various aspects of the file\."

Hence\, my original suggestion seems reasonable\, that is\, to replace&#8203;:

"For Unix systems\, this is equivalent to the simple "copy" routine\, which doesn't preserve OS\-specific attributes\."

by

"For Unix systems\, this is equivalent to the simple "copy" routine\, and doesn't preserve attributes\."


\[1\] http&#8203;://en\.wikipedia\.org/wiki/File\_attribute
\[2\] http&#8203;://www\.pcmag\.com/encyclopedia/term/43154/file\-attribute
\[3\] http&#8203;://www\.xxcopy\.com/xxcopy06\.htm

**Comment by jkeenan** [comment]
We have not heard from the original poster (@rrthomas) in nearly 10 years, and no one else has argued on behalf of this change in File::Copy's documentation.  So I recommend that this ticket be closed; self-assigning it for the purpose of doing so within the next 30 days.

**Comment by rrthomas** [comment]
What else do you need from me? I have re-read the comments, and it seems that my last suggestion is correct, and backed up with references. Apologies if I overlooked something, but it didn't seem that anything further was required after my last comment.

**Comment by jkeenan** [comment]
> What else do you need from me? I have re-read the comments, and it seems that my last suggestion is correct, and backed up with references. Apologies if I overlooked something, but it didn't seem that anything further was required after my last comment.

I don't think we're asking anything more from you.  As I noted, "no one else has argued on behalf of this change in File::Copy's documentation."  In a legislature, this would fall into the "motion fails for lack of a second" category.

**Comment by rrthomas** [comment]
It's a minor change, it doesn't seem to me that it needs a second. I have found over the years that few people bother making minor improvements to documentation, often not seeing the point. I like to do it because I find a tendency to be caught out by the same misunderstanding more than once.

**Comment by Grinnz** [comment]
It's a minor change, but it does still need to be a beneficial one to be applied, and I am similarly unconvinced that it is.

**Comment by rrthomas** [comment]
Fair enough, can you help? I have reported the problem with understanding the documentation; it seems that what's needed is a better improvement than the one I suggested.

I have re-read the issue to see if I can improve on my last suggestion. I admit that I cannot, but I also can't see what's wrong with it.

As it stands, the documentation mentions "OS-specific attributes". In fact, the "OS-specific" part is, as everyone seems to agree, irrelevant. The objection by @tonycoz to my interpretation of the word "attributes" does not conform to common usage of the word (see the citations I give to support this assertion): specifically, the contents of a file is not one of its attributes as understood by the common usage of this term in the context of file systems.

Therefore, the removal of "OS-specific" seems warranted, and removes potential for confusion.

Finally, I changed "which" to "and". This is a minor improvement to my eyes, but it doesn't really matter; I don't think it adds much to change this.

Conclusion: simply drop the words "OS-specific" here, as they are irrelevant.

**Comment by rrthomas** [comment]
A shame that this was closed without change; the documentation remains confusing here.
