### ISSUE TITLE
Segmentation fault in Perl_csighandler when receiving SIGCHLD & using threads

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#13515]
Migrated from [rt.perl.org#120951](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=120951) (status was 'open')

Searchable as RT120951$

**Comment by p5pRT** [comment]
### From thierry.vignaud@gmail.com

I'have a program which uses threads \(but not willingly\) and has a custom signal handler for SIGCHLD\.\.
Those are created by libraries it rely on \(GNOME's glib & wekbitgtk\)

If a SIGCHLD is received & handled by a custom signal handler before the thread creation by the libraries\, perl segfaults\.

Here is the stacktrace from gdb&#8203;: 
Program received signal SIGSEGV\, Segmentation fault\.
\[Switching to Thread 0x7fff969b2700 \(LWP 25465\)\]
Perl\_csighandler \(sig=17\, sip=\<optimized out>\, uap=\<optimized out>\) at mg\.c&#8203;:1334
1334               sig == SIGSEGV ||
Missing separate debuginfos\, use&#8203;: debuginfo\-install adwaita\-gtk2\-theme\-3\.10\.0\-2\.mga4\.x86\_64 dconf\-0\.18\.0\-4\.mga4\.x86\_64 gnome\-shell\-3\.10\.2\.1\-5\.mga4\.x86\_64 gvfs\-1\.18\.3\-1\.mga4\.x86\_64 icedtea\-web\-1\.4\.1\-2\.mga4\.x86\_64 lib64GConf2\_4\-3\.2\.6\-4\.mga4\.x86\_64 lib64atk1\.0\_0\-2\.10\.0\-2\.mga4\.x86\_64 lib64bzip2\_1\-1\.0\.6\-4\.mga4\.x86\_64 lib64cairo2\-1\.12\.16\-2\.mga4\.x86\_64 lib64canberra\-gtk0\-0\.30\-4\.mga4\.x86\_64 lib64canberra0\-0\.30\-4\.mga4\.x86\_64 lib64dbus\-glib1\_2\-0\.100\.2\-2\.mga4\.x86\_64 lib64dbus1\_3\-1\.6\.12\-4\.mga4\.x86\_64 lib64drm2\-2\.4\.50\-2\.mga4\.x86\_64 lib64enchant1\-1\.6\.0\-9\.mga4\.x86\_64 lib64ffi6\-3\.0\.13\-2\.mga4\.x86\_64 lib64fontconfig1\-2\.11\.0\-2\.mga4\.x86\_64 lib64freetype6\-2\.5\.0\.1\-3\.mga4\.tainted\.x86\_64 lib64gbm1\-10\.0\.1\-2\.mga4\.tainted\.x86\_64 lib64gcrypt11\-1\.5\.3\-2\.mga4\.x86\_64 lib64gdk\_pixbuf2\.0\_0\-2\.30\.1\-1\.mga4\.x86\_64 lib64geoclue0\-0\.12\.99\-6\.mga4\.x86\_64 lib64glapi0\-10\.0\.1\-2\.mga4\.tainted\.x86\_64 lib64glib\-networking\-2\.38\.2\-1\.mga4\.x86\_64 lib64gpg\-error0\-1\.12\-2\.mga4\.x86\_64 lib64graphite2\_3\-1\.2\.4\-1\.mga4\.x86\_64 lib64gstreamer\-plugins\-base1\.0\_0\-1\.2\.0\-2\.mga4\.x86\_64 lib64gstreamer1\.0\_0\-1\.2\.0\-2\.mga4\.x86\_64 lib64gvfscommon0\-1\.18\.3\-1\.mga4\.x86\_64 lib64harfbuzz0\-0\.9\.22\-2\.mga4\.x86\_64 lib64hunspell1\.3\_0\-1\.3\.2\-8\.mga4\.x86\_64 lib64ice6\-1\.0\.8\-4\.mga4\.x86\_64 lib64icu52\-52\.1\-2\.mga4\.x86\_64 lib64javascriptcoregtk1\.0\_0\-2\.2\.2\-1\.mga4\.x86\_64 lib64jpeg8\-1\.3\.0\-3\.mga4\.x86\_64 lib64json\-glib1\.0\_0\-0\.16\.2\-3\.mga4\.x86\_64 lib64ltdl7\-2\.4\.2\-11\.mga4\.x86\_64 lib64lzma5\-5\.1\.2\-0\.alpha\.4\.mga4\.x86\_64 lib64mesaegl1\-10\.0\.1\-2\.mga4\.tainted\.x86\_64 lib64mesagl1\-10\.0\.1\-2\.mga4\.tainted\.x86\_64 lib64nspr4\-4\.10\.2\-1\.mga4\.x86\_64 lib64nss3\-3\.15\.3\.1\-1\.mga4\.x86\_64 lib64ogg0\-1\.3\.1\-2\.mga4\.x86\_64 lib64orc0\.4\_0\-0\.4\.18\-2\.mga4\.x86\_64 lib64pango1\.0\_0\-1\.36\.1\-1\.mga4\.x86\_64 lib64pcre1\-8\.33\-2\.mga4\.x86\_64 lib64pixman1\_0\-0\.32\.4\-1\.mga4\.x86\_64 lib64png16\_16\-1\.6\.8\-1\.mga4\.x86\_64 lib64proxy1\-0\.4\.11\-5\.mga4\.x86\_64 lib64secret1\_0\-0\.16\-3\.mga4\.x86\_64 lib64sm6\-1\.2\.2\-2\.mga4\.x86\_64 lib64soup2\.4\_1\-2\.44\.2\-1\.mga4\.x86\_64 lib64sqlite3\_0\-3\.8\.0\.2\-2\.mga4\.x86\_64 lib64tdb1\-1\.2\.12\-2\.mga4\.x86\_64 lib64totem\-plparser\-mini18\-3\.10\.0\-3\.mga4\.x86\_64 lib64udev1\-208\-5\.mga4\.x86\_64 lib64uuid1\-2\.24\-2\.mga4\.x86\_64 lib64voikko1\-3\.6\.1\-3\.mga4\.x86\_64 lib64vorbis0\-1\.3\.3\-4\.mga4\.x86\_64 lib64vorbisfile3\-1\.3\.3\-4\.mga4\.x86\_64 lib64wayland\-client0\-1\.3\.0\-2\.mga4\.x86\_64 lib64wayland\-server0\-1\.3\.0\-2\.mga4\.x86\_64 lib64webkitgtk1\.0\_0\-2\.2\.2\-1\.mga4\.x86\_64 lib64webp4\-0\.3\.1\-2\.mga4\.x86\_64 lib64x11\-xcb1\-1\.6\.2\-2\.mga4\.x86\_64 lib64x11\_6\-1\.6\.2\-2\.mga4\.x86\_64 lib64xau6\-1\.0\.8\-3\.mga4\.x86\_64 lib64xcb\-dri2\_0\-1\.9\.1\-2\.mga4\.x86\_64 lib64xcb\-glx0\-1\.9\.1\-2\.mga4\.x86\_64 lib64xcb\-render0\-1\.9\.1\-2\.mga4\.x86\_64 lib64xcb\-shm0\-1\.9\.1\-2\.mga4\.x86\_64 lib64xcb\-xfixes0\-1\.9\.1\-2\.mga4\.x86\_64 lib64xcb1\-1\.9\.1\-2\.mga4\.x86\_64 lib64xcomposite1\-0\.4\.4\-5\.mga4\.x86\_64 lib64xcursor1\-1\.1\.14\-3\.mga4\.x86\_64 lib64xdamage1\-1\.1\.4\-5\.mga4\.x86\_64 lib64xdmcp6\-1\.1\.1\-5\.mga4\.x86\_64 lib64xext6\-1\.3\.2\-3\.mga4\.x86\_64 lib64xfixes3\-5\.0\.1\-2\.mga4\.x86\_64 lib64xi6\-1\.7\.2\-3\.mga4\.x86\_64 lib64xinerama1\-1\.1\.3\-2\.mga4\.x86\_64 lib64xml2\_2\-2\.9\.1\-2\.mga4\.x86\_64 lib64xrandr2\-1\.4\.2\-2\.mga4\.x86\_64 lib64xrender1\-0\.9\.8\-2\.mga4\.x86\_64 lib64xslt1\-1\.1\.28\-4\.mga4\.x86\_64 lib64xt6\-1\.1\.4\-3\.mga4\.x86\_64 lib64xxf86vm1\-1\.1\.3\-3\.mga4\.x86\_64 lib64zlib1\-1\.2\.8\-3\.mga4\.x86\_64 libgcc1\-4\.8\.2\-3\.mga4\.x86\_64 libstdc\+\+6\-4\.8\.2\-3\.mga4\.x86\_64 perl\-Cairo\-1\.104\.0\-2\.mga4\.x86\_64 perl\-Pango\-1\.224\-3\.mga4\.x86\_64 totem\-mozilla\-3\.10\.1\-2\.mga4\.x86\_64
\(gdb\) bt
\#0  Perl\_csighandler \(sig=17\, sip=\<optimized out>\, uap=\<optimized out>\) at mg\.c&#8203;:1334
\#1  \<signal handler called>
\#2  0x00007ffff6cce302 in \_\_libc\_waitpid \(pid=25466\, stat\_loc=stat\_loc@&#8203;entry=0x7fff969b1b1c\, options=options@&#8203;entry=0\) at \.\./sysdeps/unix/sysv/linux/waitpid\.c&#8203;:40
\#3  0x00007ffff599985e in g\_spawn\_sync \(working\_directory=working\_directory@&#8203;entry=0x0\, argv=\<optimized out>\, envp=envp@&#8203;entry=0x0\, flags=flags@&#8203;entry=G\_SPAWN\_SEARCH\_PATH\, child\_setup=child\_setup@&#8203;entry=0x0\, 
&nbsp;    user\_data=user\_data@&#8203;entry=0x0\, standard\_output=standard\_output@&#8203;entry=0x7fff969b1c50\, standard\_error=standard\_error@&#8203;entry=0x7fff969b1c58\, exit\_status=exit\_status@&#8203;entry=0x7fff969b1c4c\, 
&nbsp;    error=error@&#8203;entry=0x7fff969b1cb8\) at gspawn\.c&#8203;:402
\#4  0x00007ffff5999cf7 in g\_spawn\_command\_line\_sync \(command\_line=command\_line@&#8203;entry=0x7fff8c003df0 "dbus\-launch \-\-autolaunch=748d1d9f2a26c9eda63b35055081e3c1 \-\-binary\-syntax \-\-close\-stderr"\, 
&nbsp;    standard\_output=standard\_output@&#8203;entry=0x7fff969b1c50\, standard\_error=standard\_error@&#8203;entry=0x7fff969b1c58\, exit\_status=exit\_status@&#8203;entry=0x7fff969b1c4c\, error=error@&#8203;entry=0x7fff969b1cb8\) at gspawn\.c&#8203;:731
\#5  0x00007fffee54025b in get\_session\_address\_dbus\_launch \(error=error@&#8203;entry=0x7fff969b1cb8\) at gdbusaddress\.c&#8203;:1068
\#6  0x00007fffee541aaa in get\_session\_address\_platform\_specific \(error=0x7fff969b1cb8\) at gdbusaddress\.c&#8203;:1443
\#7  g\_dbus\_address\_get\_for\_bus\_sync \(bus\_type=bus\_type@&#8203;entry=G\_BUS\_TYPE\_SESSION\, cancellable=cancellable@&#8203;entry=0x0\, error=error@&#8203;entry=0x7fff969b1da8\) at gdbusaddress\.c&#8203;:1526
\#8  0x00007fffee54c85e in get\_uninitialized\_connection \(bus\_type=G\_BUS\_TYPE\_SESSION\, cancellable=cancellable@&#8203;entry=0x0\, error=error@&#8203;entry=0x7fff969b1da8\) at gdbusconnection\.c&#8203;:6953
\#9  0x00007fffee551d2b in g\_bus\_get\_sync \(bus\_type=\<optimized out>\, cancellable=0x0\, error=0x7fff969b1da8\) at gdbusconnection\.c&#8203;:7029
\#10 0x00007fff969b98c0 in dconf\_gdbus\_get\_bus\_in\_worker \(\) from /usr/lib64/gio/modules/libdconfsettings\.so
\#11 0x00007fff969b999d in dconf\_gdbus\_method\_call \(\) from /usr/lib64/gio/modules/libdconfsettings\.so
\#12 0x00007ffff5957146 in g\_main\_dispatch \(context=0xb07510\) at gmain\.c&#8203;:3066
\#13 g\_main\_context\_dispatch \(context=context@&#8203;entry=0xb07510\) at gmain\.c&#8203;:3642
\#14 0x00007ffff5957498 in g\_main\_context\_iterate \(context=context@&#8203;entry=0xb07510\, block=block@&#8203;entry=1\, dispatch=dispatch@&#8203;entry=1\, self=\<optimized out>\) at gmain\.c&#8203;:3713
\#15 0x00007ffff595753c in g\_main\_context\_iteration \(context=0xb07510\, may\_block=1\) at gmain\.c&#8203;:3774
\#16 0x00007fff969b9add in dconf\_gdbus\_worker\_thread \(\) from /usr/lib64/gio/modules/libdconfsettings\.so
\#17 0x00007ffff597be65 in g\_thread\_proxy \(data=0xc778f0\) at gthread\.c&#8203;:798
\#18 0x00007ffff6cc6fab in start\_thread \(arg=0x7fff969b2700\) at pthread\_create\.c&#8203;:309
\#19 0x00007ffff69f9d9d in clone \(\) at \.\./sysdeps/unix/sysv/linux/x86\_64/clone\.S&#8203;:111

The segfaults happen since glib was upgraded from glib\-2\.34 to 2\.36 & were seen with both perl\-5\.16 & 5\.18\.
Newer glib use threads more widely\.

I've workarounded this in some tools by setting SIG\{CHLD\} later\.
See the 7 commits related to \#10289 in http&#8203;://gitweb\.mageia\.org/software/control\-center/log/control\-center
But some others are affected too\.

I can still make mcc \(Mageia Control Center\) to reliably segfault by setting SIG\{CHLD\} earlier \(by moving "$SIG\{CHLD\} =\.\.\." at top of /usr/libexec/drakconf\)

Basically\, we segfault in SIG\_CHLD when webkit threads exit \(webkit creates temporary ones on init\)\.
Delaying setting CHLD handler workaround this\.\.\.

So\, as far as I'm concerned there's 2 bugs&#8203;:
\- glib & webkit libraries creating threads behind our back
\- perl segfaulting when having a custom signal handler for SIG\_CHILD

There was an old bug that got fixed in perl\-5\.10\.0&#8203;:
https://rt.perl.org/Public/Bug/Display.html?id=60724
https://access.redhat.com/site/solutions/425043 \("Segfault in perl Perl\_csighndler when custom signal handler installed"\)

This report looks like a variant of this bug \(and is happening b/c of glib's & webkit's threads\)\.

It can be reproduced with either the attached script or one of the following one\-liners&#8203;:

perl \-MGtk2 \-MGtk2&#8203;::WebKit \-e '$SIG\{CHLD\} = sub \{ warn \}; Gtk2\->init; my $wiew = Gtk2&#8203;::WebKit&#8203;::WebView\->new; $w=Gtk2&#8203;::Window\->new; $w\->add\($view\); Gtk2\->main'

perl \-MGtk3 \-MGtk3&#8203;::WebKit \-e '$SIG\{CHLD\} = sub \{ warn @&#8203;\_ \}; Gtk3\->init; my $wiew = Gtk3&#8203;::WebKit&#8203;::WebView\->new; $w=Gtk3&#8203;::Window\->new; $w\->add\($view\); Gtk3\->main'

**Comment by p5pRT** [comment]
### From thierry.vignaud@gmail.com

[mcc](https://rt-archive.perl.org/perl5/Ticket/Attachment/1274893/671097/mcc)

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue Jan 07 16&#8203;:06&#8203;:32 2014\, thierry\.vignaud@&#8203;gmail\.com wrote&#8203;:
> \(gdb\) bt
> \#0  Perl\_csighandler \(sig=17\, sip=\<optimized out>\, uap=\<optimized
> out>\) at mg\.c&#8203;:1334
> \#1  \<signal handler called>

Which version of perl is this backtrace from?

Is it a vendor patched perl?

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From thierry.vignaud@gmail.com

This is perl\-5\.18\.1 as provided by Mageia and is indeed patched by vendor&#8203;:
See http&#8203;://svnweb\.mageia\.org/packages/cauldron/perl/current/SOURCES/
for patches applied by Mageia

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue Jan 07 16&#8203;:48&#8203;:15 2014\, tonyc wrote&#8203;:
> On Tue Jan 07 16&#8203;:06&#8203;:32 2014\, thierry\.vignaud@&#8203;gmail\.com wrote&#8203;:
> > \(gdb\) bt
> > \#0  Perl\_csighandler \(sig=17\, sip=\<optimized out>\, uap=\<optimized
> > out>\) at mg\.c&#8203;:1334
> > \#1  \<signal handler called>
> 
> Which version of perl is this backtrace from?
> 
> Is it a vendor patched perl?

tony@&#8203;mars&#8203;:\.\.\./git/perl2$ gdb \-\-args ~/perl/5\.18\.0\-thr\-debug/bin/perl \-MGtk2 \-MGtk2&#8203;::WebKit \-e '$SIG\{CHLD\} = sub \{ warn \}; Gtk2\->init; my $view = Gtk2&#8203;::WebKit&#8203;::WebView\->new; $w=Gtk2&#8203;::Window\->new; $w\->add\($view\); Gtk2\->main'
GNU gdb \(GDB\) 7\.4\.1\-debian
Copyright \(C\) 2012 Free Software Foundation\, Inc\.
License GPLv3\+&#8203;: GNU GPL version 3 or later \<http&#8203;://gnu\.org/licenses/gpl\.html>
This is free software&#8203;: you are free to change and redistribute it\.
There is NO WARRANTY\, to the extent permitted by law\.  Type "show copying"
and "show warranty" for details\.
This GDB was configured as "x86\_64\-linux\-gnu"\.
For bug reporting instructions\, please see&#8203;:
\<http&#8203;://www\.gnu\.org/software/gdb/bugs/>\.\.\.
Reading symbols from /home/tony/perl/5\.18\.0\-thr\-debug/bin/perl\.\.\.done\.
\(gdb\) r
Starting program&#8203;: /home/tony/perl/5\.18\.0\-thr\-debug/bin/perl \-MGtk2 \-MGtk2&#8203;::WebKit \-e \\$SIG\\\{CHLD\\\}\\ =\\ sub\\ \\\{\\ warn\\ \\\}\\;\\ Gtk2\-\\>init\\;\\ my\\ \\$view\\ =\\ Gtk2&#8203;::WebKit&#8203;::WebView\-\\>new\\;\\ \\$w=Gtk2&#8203;::Window\-\\>new\\;\\ \\$w\-\\>add\\\(\\$view\\\)\\;\\ Gtk2\-\\>main
\[Thread debugging using libthread\_db enabled\]
Using host libthread\_db library "/lib/x86\_64\-linux\-gnu/libthread\_db\.so\.1"\.
\[New Thread 0x7fffe8101700 \(LWP 11218\)\]
\[New Thread 0x7fffa77fe700 \(LWP 11219\)\]
\[New Thread 0x7fffa6bef700 \(LWP 11220\)\]

Program received signal SIGSEGV\, Segmentation fault\.
\[Switching to Thread 0x7fffa6bef700 \(LWP 11220\)\]
Perl\_csighandler \(sig=17\, sip=\<optimized out>\, uap=\<optimized out>\)
&nbsp;    at mg\.c&#8203;:1334
1334               sig == SIGSEGV ||
\(gdb\) p my\_perl
$1 = \(PerlInterpreter \*\) 0x0

which I suspect means we need to initialize THX here in a similar way we do on Win32&#8203;:

void \*
win32\_signal\_context\(void\)
\{
&nbsp;    dTHX;
\#ifdef MULTIPLICITY
&nbsp;    if \(\!my\_perl\) \{
&nbsp;    my\_perl = PL\_curinterp;
&nbsp;    PERL\_SET\_THX\(my\_perl\);
&nbsp;    \}
&nbsp;    return my\_perl;
\#else
&nbsp;    return PL\_curinterp;
\#endif
\}

Tony

**Comment by p5pRT** [comment]
### From thierry.vignaud@gmail.com

Care to suggest a patch that I can test?

**Comment by p5pRT** [comment]
### From @Leont

On Tue Jan 07 16&#8203;:06&#8203;:32 2014\, thierry\.vignaud@&#8203;gmail\.com wrote&#8203;:
> I'have a program which uses threads \(but not willingly\) and has a
> custom signal handler for SIGCHLD\.\.
> Those are created by libraries it rely on \(GNOME's glib & wekbitgtk\)
> 
> If a SIGCHLD is received & handled by a custom signal handler before
> the thread creation by the libraries\, perl segfaults\.
>
> The segfaults happen since glib was upgraded from glib\-2\.34 to 2\.36 &
> were seen with both perl\-5\.16 & 5\.18\.
> Newer glib use threads more widely\.
> 
> I've workarounded this in some tools by setting SIG\{CHLD\} later\.
> See the 7 commits related to \#10289 in
> http&#8203;://gitweb\.mageia\.org/software/control\-center/log/control\-center
> But some others are affected too\.
> 
> I can still make mcc \(Mageia Control Center\) to reliably segfault by
> setting SIG\{CHLD\} earlier \(by moving "$SIG\{CHLD\} =\.\.\." at top of
> /usr/libexec/drakconf\)
> 
> Basically\, we segfault in SIG\_CHLD when webkit threads exit \(webkit
> creates temporary ones on init\)\.
> Delaying setting CHLD handler workaround this\.\.\.
> 
> So\, as far as I'm concerned there's 2 bugs&#8203;:
> \- glib & webkit libraries creating threads behind our back
> \- perl segfaulting when having a custom signal handler for SIG\_CHILD
> 
> There was an old bug that got fixed in perl\-5\.10\.0&#8203;:
> https://rt.perl.org/Public/Bug/Display.html?id=60724
> https://access.redhat.com/site/solutions/425043 \("Segfault in perl
> Perl\_csighndler when custom signal handler installed"\)
> 
> This report looks like a variant of this bug \(and is happening b/c of
> glib's & webkit's threads\)\.
> 
> It can be reproduced with either the attached script or one of the
> following one\-liners&#8203;:
> 
> perl \-MGtk2 \-MGtk2&#8203;::WebKit \-e '$SIG\{CHLD\} = sub \{ warn \}; Gtk2\->init;
> my $wiew = Gtk2&#8203;::WebKit&#8203;::WebView\->new; $w=Gtk2&#8203;::Window\->new; $w\-
> >add\($view\); Gtk2\->main'
> 
> perl \-MGtk3 \-MGtk3&#8203;::WebKit \-e '$SIG\{CHLD\} = sub \{ warn @&#8203;\_ \}; Gtk3\-
> >init; my $wiew = Gtk3&#8203;::WebKit&#8203;::WebView\->new; $w=Gtk3&#8203;::Window\->new;
> $w\->add\($view\); Gtk3\->main'

This sounds like csighandler is running in a thread that doesn't have any associated perl interpreter\. One solution might be to block SIGCHLD \(and possibly other signals\) during thread creation \(see also Signal&#8203;::Mask or POSIX&#8203;::sigprocmask\)\, that way the signal will never be delivered to them \(unless they accidentally unblock it\)\.

Leon

**Comment by p5pRT** [comment]
### From thierry.vignaud@gmail.com

On Tue Jan 07 18&#8203;:12&#8203;:41 2014\, LeonT wrote&#8203;:
> This sounds like csighandler is running in a thread that doesn't have
> any associated perl interpreter\. One solution might be to block
> SIGCHLD \(and possibly other signals\) during thread creation \(see also
> Signal&#8203;::Mask or POSIX&#8203;::sigprocmask\)\, that way the signal will never be
> delivered to them \(unless they accidentally unblock it\)\.

As stated in my initial report\, I do not have control over the threads
creation\. My tools are mono threaded but some libraries they use
\(GNOME's glib\, WebKit\) do create some threads for their own purpose\.
I've no control over that\.

So I would have to identify every places in the libraries that can result
in creating threads\.

**Comment by p5pRT** [comment]
### From @shlomif

I am able to reproduce this problem with a perl built like so&#8203;:

\#\!/bin/sh
rm \-f config\.sh Policy\.sh
sh Configure \-de \-Dprefix="$HOME"/apps/perl/5\.18\.x\-maint \-Doptimize='\-g' \\
&nbsp;    \-Duseithreads \-Dusedevel

from the Git maint5\.18 branch\, on Mageia Linux x86\-64 4 Cauldron\, and after installing the Gtk2 and Gtk2&#8203;::WebKit modules from CPAN\.

When I run the program as my normal user everything runs fine\. When I run it as root\, it crashes\. When I run it under gdb as root\, the program does not crash\. Let me know if I can be of further assistance\.

Regards\,

\-\- Shlomi Fish

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue Jan 07 18&#8203;:12&#8203;:41 2014\, LeonT wrote&#8203;:
> This sounds like csighandler is running in a thread that doesn't have
> any associated perl interpreter\. One solution might be to block
> SIGCHLD \(and possibly other signals\) during thread creation \(see also
> Signal&#8203;::Mask or POSIX&#8203;::sigprocmask\)\, that way the signal will never be
> delivered to them \(unless they accidentally unblock it\)\.

I'll look at fixing this as part of my 81074 work\.

Tony

**Comment by p5pRT** [comment]
### From thierry.vignaud@gmail.com

On 8 January 2014 01&#8203;:48\, Tony Cook via RT \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> Which version of perl is this backtrace from?
>
> Is it a vendor patched perl?

This is perl\-5\.18\.1 as provided by Mageia and is indeed patched by vendor&#8203;:
See http&#8203;://svnweb\.mageia\.org/packages/cauldron/perl/current/SOURCES/
for patches applied by Mageia

**Comment by soig** [comment]
Looks that this doesn't happen anymore as of perl-5.30.1

**Comment by demerphq** [comment]
Closing as the bug is reported to be fixed.
