### ISSUE TITLE
[PATCH] Speedup io/through.t and io/crlf_through.t

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#13544]
Migrated from [rt.perl.org#121042](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=121042) (status was 'open')

Searchable as RT121042$

**Comment by p5pRT** [comment]
### From @wolfsage

#### Created by wolfsage@gmail.com



Currently\, io/crlf\.t and io/crlf\_through\.t takes ~10 seconds each
to run on my machine\.

They are using sleeps that I'm not convinced are needed\.

By removing all but the first sleep \(incase that's needed for
process synchronization\) I've reduced the runtime of each to 2
seconds\.

I temporarily reverted the associated fix that came with the tests
\(93c2c2ec\) to test that my versions still catch the issues\, and they
do\.

Patch attached\. Thanks\,

\-\- Matthew Horsfall \(alh\)

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl 5.14.2:

Configured by Debian Project at Mon Mar 18 19:16:26 UTC 2013.

Summary of my perl5 (revision 5 version 14 subversion 2) configuration:

  Platform:
    osname=linux, osvers=2.6.42-37-generic,
archname=x86_64-linux-gnu-thread-multi
    uname='linux batsu 2.6.42-37-generic #58-ubuntu smp thu jan 24
15:28:10 utc 2013 x86_64 x86_64 x86_64 gnulinux '
    config_args='-Dusethreads -Duselargefiles -Dccflags=-DDEBIAN
-Dcccdlflags=-fPIC -Darchname=x86_64-linux-gnu -Dprefix=/usr
-Dprivlib=/usr/share/perl/5.14 -Darchlib=/usr/lib/perl/5.14
-Dvendorprefix=/usr -Dvendorlib=/usr/share/perl5
-Dvendorarch=/usr/lib/perl5 -Dsiteprefix=/usr/local
-Dsitelib=/usr/local/share/perl/5.14.2
-Dsitearch=/usr/local/lib/perl/5.14.2 -Dman1dir=/usr/share/man/man1
-Dman3dir=/usr/share/man/man3 -Dsiteman1dir=/usr/local/man/man1
-Dsiteman3dir=/usr/local/man/man3 -Duse64bitint -Dman1ext=1
-Dman3ext=3perl -Dpager=/usr/bin/sensible-pager -Uafs -Ud_csh
-Ud_ualarm -Uusesfio -Uusenm -Ui_libutil -DDEBUGGING=-g -Doptimize=-O2
-Duseshrplib -Dlibperl=libperl.so.5.14.2 -des'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DDEBIAN
-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include
-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2 -g',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fno-strict-aliasing
-pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.6.3', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t',
lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib /lib/x86_64-linux-gnu /lib/../lib
/usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib /usr/lib
    libs=-lgdbm -lgdbm_compat -ldb -ldl -lm -lpthread -lc -lcrypt
    perllibs=-ldl -lm -lpthread -lc -lcrypt
    libc=, so=so, useshrplib=true, libperl=libperl.so.5.14.2
    gnulibc_version='2.15'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -g -L/usr/local/lib
-fstack-protector'

Locally applied patches:



@INC for perl 5.14.2:
    /etc/perl
    /usr/local/lib/perl/5.14.2
    /usr/local/share/perl/5.14.2
    /usr/lib/perl5
    /usr/share/perl5
    /usr/lib/perl/5.14
    /usr/share/perl/5.14
    /usr/local/lib/site_perl
    .


Environment for perl 5.14.2:
    HOME=/home/mhorsfall
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/mhorsfall/perl5/perlbrew/bin:/home/mhorsfall/bin:/home/mhorsfall/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
    PERLBREW_BASHRC_VERSION=0.66
    PERLBREW_HOME=/home/mhorsfall/.perlbrew
    PERLBREW_ROOT=/home/mhorsfall/perl5/perlbrew
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @wolfsage

<details><summary>0001-Sleep-only-once-so-tests-finishes-quickly.-2s-instea.patch</summary>

```diff
From af63287cda4a3bdbae03f0d80e09ff0bdcabf1ba Mon Sep 17 00:00:00 2001
From: Matthew Horsfall <WolfSage@gmail.com>
Date: Mon, 20 Jan 2014 12:25:26 -0500
Subject: [PATCH] Sleep only once so tests finishes quickly. (~2s instead of
 ~10s)

---
 t/io/through.t |    2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/t/io/through.t b/t/io/through.t
index 315de90..8c3a39f 100644
--- a/t/io/through.t
+++ b/t/io/through.t
@@ -112,7 +112,7 @@ sub testfile ($$$$$$) {
 }
 
 # shell-neutral and miniperl-enabled autoflush? qq(\x24\x7c) eq '$|'
-open my $fh, '-|', qq[$Perl -we "eval qq(\\x24\\x7c = 1) or die; binmode STDOUT; sleep 1, print for split //, qq(a\nb\n\nc\n\n\n)"] or die "open: $!";
+open my $fh, '-|', qq[$Perl -we "eval qq(\\x24\\x7c = 1) or die; binmode STDOUT; sleep 1; print for split //, qq(a\nb\n\nc\n\n\n)"] or die "open: $!";
 ok(1, 'open pipe');
 binmode $fh, q(:crlf);
 ok(1, 'binmode');
-- 
1.7.9.5


```
</details>

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon Jan 20 09&#8203;:36&#8203;:05 2014\, alh wrote&#8203;:
> Currently\, io/crlf\.t and io/crlf\_through\.t takes ~10 seconds each
> to run on my machine\.
> 
> They are using sleeps that I'm not convinced are needed\.
> 
> By removing all but the first sleep \(incase that's needed for
> process synchronization\) I've reduced the runtime of each to 2
> seconds\.
> 
> I temporarily reverted the associated fix that came with the tests
> \(93c2c2ec\) to test that my versions still catch the issues\, and they
> do\.
> 
> Patch attached\. Thanks\,

Reverting the substantive parts of 93c2c2ec \(I didn't revert the comment change\) didn't cause the test you modified to fail even without your change\. \(Win32 and Linux\)

That said\, from reading the original discussion of the problem\, I don't think your change preserves the behaviour that was required to reproduce the original problem\.

The original problem\, if I understand it\, was the user entering text from the keyboard and perlio's CRLF layer not handling those short reads correctly\.

With your change\, the child process is likely to arrive in a single read\(\) in the parent process\, so not matching the behaviour needed to reproduce the original bug\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @wolfsage

On Tue\, Jan 21\, 2014 at 10&#8203;:17 PM\, Tony Cook via RT
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> Reverting the substantive parts of 93c2c2ec \(I didn't revert the comment change\) didn't cause the test you modified to fail even without your change\. \(Win32 and Linux\)

io/through\.t passes for me with or without the application of 93c2c2ec\.

io/crlf\_through\.t is the one that fails when 93c2c2ec is reverted\,
though different tests fail\, not the one I've modified\.

I've noticed that the test I've changed&#8203;:

&nbsp;    \# shell\-neutral and miniperl\-enabled autoflush? qq\(\\x24\\x7c\) eq '$|'
&nbsp;    open my $fh\, '\-|'\, qq\[$Perl \-we "eval qq\(\\\\x24\\\\x7c = 1\) or die;
binmode STDOUT; sleep 1\, print for s$
&nbsp;    ok\(1\, 'open pipe'\);
&nbsp;    binmode $fh\, q\(&#8203;:crlf\);
&nbsp;    ok\(1\, 'binmode'\);
&nbsp;    my \(@&#8203;c\, $c\);
&nbsp;    push @&#8203;c\, ord $c while $c = getc $fh;
&nbsp;    ok\(1\, 'got chars'\);
&nbsp;    is\(scalar @&#8203;c\, 9\, 'got 9 chars'\);
&nbsp;    is\("@&#8203;c"\, '97 10 98 10 10 99 10 10 10'\, 'got expected chars'\);

passes with or without 93c2c2ec for both io/through\.t and
io/crlf\_throught\.t\, so now I'm not certain of its purpose or value\.

Unfortunately I can't get Perl to build at 93c2c2ec to see if perhaps
something else hasn't fixed it since then\.

\-\- Matthew Horsfall \(alh\)

**Comment by p5pRT** [comment]
### From @jkeenan

On Fri\, 24 Jan 2014 13&#8203;:34&#8203;:43 GMT\, alh wrote&#8203;:
> On Tue\, Jan 21\, 2014 at 10&#8203;:17 PM\, Tony Cook via RT
> \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> > Reverting the substantive parts of 93c2c2ec \(I didn't revert the
> > comment change\) didn't cause the test you modified to fail even
> > without your change\. \(Win32 and Linux\)
> 
> io/through\.t passes for me with or without the application of
> 93c2c2ec\.
> 
> io/crlf\_through\.t is the one that fails when 93c2c2ec is reverted\,
> though different tests fail\, not the one I've modified\.
> 
> I've noticed that the test I've changed&#8203;:
> 
> \# shell\-neutral and miniperl\-enabled autoflush? qq\(\\x24\\x7c\) eq '$|'
> open my $fh\, '\-|'\, qq\[$Perl \-we "eval qq\(\\\\x24\\\\x7c = 1\) or die;
> binmode STDOUT; sleep 1\, print for s$
> ok\(1\, 'open pipe'\);
> binmode $fh\, q\(&#8203;:crlf\);
> ok\(1\, 'binmode'\);
> my \(@&#8203;c\, $c\);
> push @&#8203;c\, ord $c while $c = getc $fh;
> ok\(1\, 'got chars'\);
> is\(scalar @&#8203;c\, 9\, 'got 9 chars'\);
> is\("@&#8203;c"\, '97 10 98 10 10 99 10 10 10'\, 'got expected chars'\);
> 
> passes with or without 93c2c2ec for both io/through\.t and
> io/crlf\_throught\.t\, so now I'm not certain of its purpose or value\.
> 
> Unfortunately I can't get Perl to build at 93c2c2ec to see if perhaps
> something else hasn't fixed it since then\.
> 
> \-\- Matthew Horsfall \(alh\)

Matt\, Tony&#8203;:  Should this ticket remain open?

Thank you very much\.
\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @wolfsage

On Sun\, Feb 26\, 2017 at 5&#8203;:27 PM\, James E Keenan via RT
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> Matt\, Tony&#8203;:  Should this ticket remain open?
>
> Thank you very much\.

I don't think it's worth it\. Feel free to close\, thanks\.

\-\- Matthew Horsfall \(alh\)

**Comment by p5pRT** [comment]
### From @jkeenan

On Mon\, 27 Feb 2017 14&#8203;:27&#8203;:38 GMT\, alh wrote&#8203;:
> On Sun\, Feb 26\, 2017 at 5&#8203;:27 PM\, James E Keenan via RT
> \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> > Matt\, Tony&#8203;:  Should this ticket remain open?
> >
> > Thank you very much\.
> 
> I don't think it's worth it\. Feel free to close\, thanks\.
> 

TonyC is listed as Owner\, so I'll let him make the final call\.

> \-\- Matthew Horsfall \(alh\)
> 


\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by khwilliamson** [comment]
No response in 5 years; OP says ok to close
