### ISSUE TITLE
[EXPERIMENT] subroutine signatures

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#13681]
Migrated from [rt.perl.org#121481](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=121481) (status was 'open')

Searchable as RT121481$

**Comment by p5pRT** [comment]
### From @rjbs

Subroutine signatures are being added as an experimental feature in perl
5\.20\.0\.  This ticket will collect bugs and other acceptance\-criteria tickets to
track before subroutine signatures can be considered accepted or failed in a
future version of perl\.

\-\- 
rjbs

**Comment by p5pRT** [comment]
### From zefram@fysh.org

The experiment ticket \[perl \#121481\] should depend on \[perl \#132141\]\.

\-zefram

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by alanrocker** [comment]
What's the current status, (experimental), and is it likely to change soon? I'd like to know whether to include signatures when teaching Perl to beginners. 6 versions (5.20 - 5.30) would seem like enough to decide what should be accepted and what should be deprecated. Subroutine attributes and how to describe them is possibly a separate feature?

**Comment by cxw42** [comment]
Agreed.  #16161 ([perl #132141]), the only referenced bug, is fixed in 5.27.8 per https://github.com/Perl/perl5/issues/16161#issuecomment-544091517 .

**Comment by iabyn** [comment]
See the current a big discussion on the p5p mailing list entitled "Jumbo Signatures extensions discussion".

**Comment by cxw42** [comment]
@iabyn Thanks!  For other readers:

- [Initial message](https://www.nntp.perl.org/group/perl.perl5.porters/2019/11/msg256677.html)
- [PerlMonks](https://www.perlmonks.org/?node_id=11109414)
