### ISSUE TITLE
Storable's gcc -O3 hint is obsolete

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#13693]
Migrated from [rt.perl.org#121511](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=121511) (status was 'open')

Searchable as RT121511$

**Comment by p5pRT** [comment]
### From zefram@fysh.org

#### Created by zefram@fysh.org



Storable's hints/linux\.pl has a note about gcc \-O3 causing failures on
unthreaded builds\.  I'm using gcc \-O3\, and by accident the way I'm using
it means that Storable fails to override it\.  \(I've got \-O3 in cccdlflags
as well as optimize\, and the compile command line includes both\, the
unoverridden \-O3 in cccdlflags coming later and so taking precedence\.\)
I'm not seeing the described problems\.

The helpful comment in the hints file refers to some specific and rather
old versions of gcc\.  Most likely\, the problem that led to this hint
was specific to those older versions and has now been fixed\.  If we can
confirm this\, and at least roughly bisect it\, the overriding hint should
be made conditional on gcc version\.

<details><summary>Perl Info</summary>

```

Flags:
    category=library
    severity=low
    module=Storable

Site configuration information for perl 5.18.2:

Configured by root at Tue Mar 25 13:45:07 UTC 2014.

Summary of my perl5 (revision 5 version 18 subversion 2) configuration:
   
  Platform:
    osname=linux, osvers=2.6.32-5-686, archname=i686-linux-64int-ld
    uname='linux beryllium.photobox.priv 2.6.32-5-686 #1 smp fri may 10 08:33:48 utc 2013 i686 gnulinux '
    config_args='-des -Duseshrplib -Duse64bitint -Duselongdouble -Uusethreads -Uusemultiplicity -Dprefix=/opt/perl-5.18.2-opt -Dsiteprefix=/opt/perl-5.18.2-opt -Dvendorprefix=/opt/perl-5.18.2-opt/vendor -Doptimize=-ggdb -O3 -fbranch-target-load-optimize -fgcse-las -fgcse-sm -fipa-pta -floop-block -floop-interchange -floop-strip-mine -fmodulo-sched -fomit-frame-pointer -freorder-blocks-and-partition -fsched-spec-load -fsched-spec-load-dangerous -ftree-loop-distribution -Dcccdlflags=-fPIC -O3 -pipe'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=undef, usemultiplicity=undef
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=define, use64bitall=undef, uselongdouble=define
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-ggdb -O3 -fbranch-target-load-optimize -fgcse-las -fgcse-sm -fipa-pta -floop-block -floop-interchange -floop-strip-mine -fmodulo-sched -fomit-frame-pointer -freorder-blocks-and-partition -fsched-spec-load -fsched-spec-load-dangerous -ftree-loop-distribution',
    cppflags='-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.7.2', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long long', ivsize=8, nvtype='long double', nvsize=12, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib /lib/i386-linux-gnu /lib/../lib /usr/lib/i386-linux-gnu /usr/lib/../lib /lib /usr/lib
    libs=-lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lc
    libc=, so=so, useshrplib=true, libperl=libperl.so
    gnulibc_version='2.13'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E -Wl,-rpath,/opt/perl-5.18.2-opt/lib/5.18.2/i686-linux-64int-ld/CORE'
    cccdlflags='-fPIC -O3 -pipe', lddlflags='-shared -ggdb -O3 -fbranch-target-load-optimize -fgcse-las -fgcse-sm -fipa-pta -floop-block -floop-interchange -floop-strip-mine -fmodulo-sched -fomit-frame-pointer -freorder-blocks-and-partition -fsched-spec-load -fsched-spec-load-dangerous -ftree-loop-distribution -L/usr/local/lib -fstack-protector'

Locally applied patches:
    


@INC for perl 5.18.2:
    /opt/perl-5.18.2-opt/lib/site_perl/5.18.2/i686-linux-64int-ld
    /opt/perl-5.18.2-opt/lib/site_perl/5.18.2
    /opt/perl-5.18.2-opt/vendor/lib/vendor_perl/5.18.2/i686-linux-64int-ld
    /opt/perl-5.18.2-opt/vendor/lib/vendor_perl/5.18.2
    /opt/perl-5.18.2-opt/lib/5.18.2/i686-linux-64int-ld
    /opt/perl-5.18.2-opt/lib/5.18.2
    .


Environment for perl 5.18.2:
    HOME=/root
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/opt/perl-5.18.2-opt/bin:/root/pub/i686-pc-linux-gnu/bin:/root/pub/common/bin:/usr/bin:/usr/sbin:/bin:/sbin:/usr/local/bin:/usr/local/sbin:/usr/games:/opt/geoip/bin:/opt/httpd/bin:/opt/perl/bin
    PERL5LIB=
    PERL5OPT=
    PERL5_CPANPLUS_IS_RUNNING=31762
    PERL5_CPAN_IS_RUNNING=31762
    PERL_BADLANG (unset)
    SHELL=/usr/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @jkeenan

I'm changing the subject line of this RT to '\-O3' fron 'O2' because that's what the body of the ticket discusses and what's found in dist/Storable/hints/linux\.pl\.

**Comment by p5pRT** [comment]
### From @jkeenan

On Wed Mar 26 06&#8203;:25&#8203;:41 2014\, zefram@&#8203;fysh\.org wrote&#8203;:
> 


---
> \[Please describe your issue here\]
> 
> Storable's hints/linux\.pl has a note about gcc \-O3 causing failures on
> unthreaded builds\.  I'm using gcc \-O3\, and by accident the way I'm
> using
> it means that Storable fails to override it\.  \(I've got \-O3 in
> cccdlflags
> as well as optimize\, and the compile command line includes both\, the
> unoverridden \-O3 in cccdlflags coming later and so taking precedence\.\)
> I'm not seeing the described problems\.
> 
> The helpful comment in the hints file refers to some specific and
> rather
> old versions of gcc\.  Most likely\, the problem that led to this hint
> was specific to those older versions and has now been fixed\.  If we
> can
> confirm this\, and at least roughly bisect it\, the overriding hint
> should
> be made conditional on gcc version\.
> 

Could you give a hint as to the smallest possible set of Configure arguments that would be useful in diagnosing/bisecting this problem?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by xenu** [comment]
d0071613f9303a6ad8d483f3164d6fef5bf6f0f5 made the hint conditional.
