### ISSUE TITLE
ExtUtils::Installed or ExtUtils::Packlist: add function for direct access of a distribution's packlist

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#13812]
Migrated from [rt.perl.org#121829](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=121829) (status was 'open')

Searchable as RT121829$

**Comment by p5pRT** [comment]
### From @eserte

It would be nice if either ExtUtils&#8203;::Installed or ExtUtils&#8203;::Packlist had a function for direct access of a packlist\. Currently the only way is to use ExtUtils&#8203;::Packlist\->new\->packlist\(\.\.\.\)\, but this may be very slow\(\*\) on large perl installations\, because apparently all directories and files are scanned\. On the other hand ExtUtils&#8203;::Packlist has no functionality to translate a module name to a packlist path\. So while using it would be much more efficient than the EU&#8203;::I solution\, the user has to have knowledge about the internal structure of the perl lib directory\.

\(\*\) Once I timed 13 minutes for running ExtUtils&#8203;::Installed\->new on a perl installation with a ~2\.5GB site\_perl directory\.

**Comment by p5pRT** [comment]
### From @Leont

On Thu\, May 8\, 2014 at 10&#8203;:06 PM\, slaven@&#8203;rezic\.de
\<perlbug\-followup@&#8203;perl\.org>wrote&#8203;:

> It would be nice if either ExtUtils&#8203;::Installed or ExtUtils&#8203;::Packlist had a
> function for direct access of a packlist\. Currently the only way is to use
> ExtUtils&#8203;::Packlist\->new\->packlist\(\.\.\.\)\, but this may be very slow\(\*\) on
> large perl installations\, because apparently all directories and files are
> scanned\. On the other hand ExtUtils&#8203;::Packlist has no functionality to
> translate a module name to a packlist path\. So while using it would be much
> more efficient than the EU&#8203;::I solution\, the user has to have knowledge
> about the internal structure of the perl lib directory\.
>
> \(\*\) Once I timed 13 minutes for running ExtUtils&#8203;::Installed\->new on a perl
> installation with a ~2\.5GB site\_perl directory\.
>

Yes\, this behavior is annoying and unnecessary in most cases\.

Leon

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @jkeenan

On Thu May 08 13&#8203;:06&#8203;:37 2014\, slaven@&#8203;rezic\.de wrote&#8203;:
> It would be nice if either ExtUtils&#8203;::Installed or ExtUtils&#8203;::Packlist
> had a function for direct access of a packlist\. 

Slaven\, Leon\,

Can you be a bit more specific about what you mean by "direct access of a packlist"?

What would that function or method do?  Are you referring to a \.packlist file or to something like this&#8203;:

\#\#\#\#\#
&nbsp;    'Test&#8203;::Script' => \{
&nbsp;      'packlist' => bless\( \{
&nbsp;        '/home/jkeenan/perl5/man/man3/Test&#8203;::Script\.3' => undef\,
&nbsp;        '/home/jkeenan/perl5/lib/perl5/Test/Script\.pm' => undef
&nbsp;      \}\, 'ExtUtils&#8203;::Packlist' \)\,
&nbsp;      'version' => '1\.07'\,
&nbsp;      'packlist\_valid' => 1\,
&nbsp;      'packlist\_file' => '/home/jkeenan/perl5/lib/perl5/x86\_64\-linux/auto/Test/Script/\.packlist'\,
&nbsp;      'modfile' => 'Test/Script\.pm'\,
&nbsp;      'version\_from' => '/home/jkeenan/perl5/lib/perl5/Test/Script\.pm'\,
&nbsp;      'module' => 'Test&#8203;::Script'
&nbsp;    \}\,
\#\#\#\#\#

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From @eserte

Dana Pet 22\. Kol 2014\, 17&#8203;:56&#8203;:37\, jkeenan reče&#8203;:
> On Thu May 08 13&#8203;:06&#8203;:37 2014\, slaven@&#8203;rezic\.de wrote&#8203;:
> > It would be nice if either ExtUtils&#8203;::Installed or ExtUtils&#8203;::Packlist
> >  had a function for direct access of a packlist\.
> 
> Slaven\, Leon\,
> 
> Can you be a bit more specific about what you mean by "direct access
> of a packlist"?
> 
> What would that function or method do?  Are you referring to a
> \.packlist file or to something like this&#8203;:
> 
> \#\#\#\#\#
> 'Test&#8203;::Script' => \{
>   'packlist' => bless\( \{
>     '/home/jkeenan/perl5/man/man3/Test&#8203;::Script\.3' => undef\,
>     '/home/jkeenan/perl5/lib/perl5/Test/Script\.pm' => undef
>   \}\, 'ExtUtils&#8203;::Packlist' \)\,
>   'version' => '1\.07'\,
>   'packlist\_valid' => 1\,
>   'packlist\_file' => '/home/jkeenan/perl5/lib/perl5/x86\_64\-
> linux/auto/Test/Script/\.packlist'\,
>   'modfile' => 'Test/Script\.pm'\,
>   'version\_from' => '/home/jkeenan/perl5/lib/perl5/Test/Script\.pm'\,
>   'module' => 'Test&#8203;::Script'
> \}\,
> \#\#\#\#\#
> 
> Thank you very much\.
> Jim Keenan

Currently there are the following methods to get the packlist of a module&#8203;:

&nbsp;    use ExtUtils&#8203;::Installed; $packlist = ExtUtils&#8203;::Installed\->new\->packlist\($module\);

&nbsp;    use ExtUtils&#8203;::Installed; $packlist = ExtUtils&#8203;::Installed\->packlist\($module\);

&nbsp;    use ExtUtils&#8203;::Packlist; $packlist = ExtUtils&#8203;::Packlist\->new\->packlist\("/I/know/where/the/packlist/of/$module/is/located"\);

The first two may be slow and resource hungry\. The third is fast\, but one needs the knowledge where the packlist may be found\.

I would suggest to add a new method find\_packlist which could be used like this&#8203;:

&nbsp;    $packlist\_path = ExtUtils&#8203;::Installed\->find\_packlist\($module\);
&nbsp;    $packlist = ExtUtils&#8203;::Packlist\->new\($packlist\_path\);

find\_packlist could look like this \(pseudo code\)&#8203;:

&nbsp;    sub find\_packlist \{
&nbsp;        my\(undef\, $module\) = @&#8203;\_;
&nbsp;        \(my $path = $module\) =~ s\{&#8203;::\}\{/\}g;
&nbsp;    $path \.= "/\.packlist";
&nbsp;        for my $incdir \(@&#8203;INC\) \{
&nbsp;        my $trypath = "$incdir/auto/$path";
&nbsp;            return $trypath if \-e $trypath;
&nbsp;        \}
&nbsp;    \}

Once find\_packlist is there it could be used to re\-implement the class method variant of ExtUtils&#8203;::Installed&#8203;::packlist\, so ExtUtils&#8203;::Installed\->packlist won't construct the "default object" anymore\, but fetch the packlist directly\. As pseudo code&#8203;:

&nbsp;    sub packlist \{
&nbsp;        my \($self\, $module\) = @&#8203;\_;
&nbsp;        if \(\!ref $self\) \{
&nbsp;            my $packlist\_path = $self\->find\_packlist\($module\);
&nbsp;            Carp&#8203;::croak\("$module is not installed"\) if \(\!$packlist\);
&nbsp;            return ExtUtils&#8203;::Packlist\->new\($packlist\_path\);
&nbsp;        \} else \{
&nbsp;            Carp&#8203;::croak\("$module is not installed"\) if \(\! exists\($self\->\{$module\}\)\);
&nbsp;            return\($self\->\{$module\}\{packlist\}\);
&nbsp;        \}
&nbsp;    \}

If needed\, there could also be more efficient versions for the validate\(\) and version\(\) methods in ExtUtils&#8203;::Installed\, too\. The first one could also use find\_packlist\(\)\, the second would use part of the logic of \_make\_entry\(\)\.

**Comment by jkeenan** [comment]
@eserte, we should have noted back in 2014 that ExtUtils::Installed and ExtUtils::Packlist are maintained upstream on CPAN as part of the ExtUtils-Install distribution.  Can you file an issue at its [designated bug-tracker](https://rt.cpan.org/Dist/Display.html?Name=ExtUtils-Install)?

Closing this ticket with 'sendToCPAN' label.
