### ISSUE TITLE
Pathological performance of a pattern match

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#13992]
Migrated from [rt.perl.org#122331](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=122331) (status was 'open')

Searchable as RT122331$

**Comment by p5pRT** [comment]
### From @andk

I think this bugreport deserves to be a quiz\. Test your intuition\.

Sample string to test the regexps against&#8203;:

&nbsp;  sprintf "%scould%snot%sopen%s"\, \("x"x10000\)x4;

Regexp 1&#8203;:

&nbsp;  qr\!\.\*\(?&#8203;:could ?not \(?&#8203;:open|connect|find\)\)\!

Regexp 2 \(the difference is it's case insensitive\)&#8203;:

&nbsp;  qr\!\.\*\(?i&#8203;:could ?not \(?&#8203;:open|connect|find\)\)\!

Note&#8203;: neither matches and this is correct\.

Question&#8203;: which is faster and by how much?

Answer&#8203;: regexp 1 is much more than 100 times slower than the regexp 2\.

On my machine this program takes 1\-2 wallclock seconds&#8203;:

&nbsp;  time $p \-le 'my $x = sprintf "%scould%snot%sopen%s"\, \("x"x10000\)x4;print $x =~ m\!\.\*\(?&#8203;:could ?not \(?&#8203;:open|connect|find\)\)\! ? "not ok" : "ok";' 

And on all those perls it takes less than 0\.01 wallclock seconds when I
add the "i"\.

Historical evidence&#8203;: this is not a regression\, at least not since 5\.6\. I
have witnessed the same slowness on all my perls between 5\.6\.1 and
bleadperl\.

Competition evidence&#8203;: with 'use re&#8203;::engine&#8203;::PCRE;' both regexps are
fast\.

Enjoy\,
\-\- 
andreas

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, Jul 19\, 2014 at 02&#8203;:21&#8203;:03PM \-0700\, Andreas J\. Koenig via RT wrote&#8203;:
>   sprintf "%scould%snot%sopen%s"\, \("x"x10000\)x4;
> 
> Regexp 1&#8203;:
> 
>   qr\!\.\*\(?&#8203;:could ?not \(?&#8203;:open|connect|find\)\)\!
> 
> Regexp 2 \(the difference is it's case insensitive\)&#8203;:
> 
>   qr\!\.\*\(?i&#8203;:could ?not \(?&#8203;:open|connect|find\)\)\!

The second is faster because it disables intuiting\, which causes it to
take a different path through regexec\_flags\(\)\, which causes it to fail
after the first call to regtry\(\)\, rather than re\-trying regtry at
positions 1\,2\,3\,\.\.\. and eventually failing\.

I don't know know what the fix is\, but this is tied up with how intuit\(\)
and the parent regex\_flags\(\) handle all the various flags \(like ANCH\_MBOL\,
and whether that MBOL is a fake one due the presence of a leading '\.\*'
etc\)\.

Its all a bit of a mess\, and I intend to look at this properly when I get
round to doing my second batch of intuit\(\)/regexec\_flags\(\) refactoring
sometime this year\.

\-\- 
Modern art&#8203;:
&nbsp;    "That's easy\, I could have done that\!"
&nbsp;    "Ah\, but you didn't\!"

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by xenu** [comment]
I can reproduce that on 5.18.4 but I can't on 5.30.2 so it definitely was fixed at some point.
