### ISSUE TITLE
t/op/sprintf2 fails (hex floats?) (FreeBSD 10.0)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14040]
Migrated from [rt.perl.org#122591](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=122591) (status was 'open')

Searchable as RT122591$

**Comment by p5pRT** [comment]
### From @eserte

#### Created by @eserte



One test failure on a FreeBSD 10\.0 system&#8203;:

t/op/sprintf2 \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\. \# Failed test 1419 \- '%a' '2\.71828182845905' \-> '0x1\.5bf0a8b14576ap\+1' cf '0x1\.5bf0a8b145769p\+1' at op/sprintf2\.t line 577
\#      got "0x1\.5bf0a8b14576ap\+1"
\# expected "0x1\.5bf0a8b145769p\+1"
FAILED at test 1419

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl 5.21.3:

Configured by eserte at Thu Aug 21 07:37:37 CEST 2014.

Summary of my perl5 (revision 5 version 21 subversion 3) configuration:
   
  Platform:
    osname=freebsd, osvers=10.0-release-p1, archname=amd64-freebsd
    uname='freebsd cvrsnica-freebsd-10-64bit.herceg.de 10.0-release-p1 freebsd 10.0-release-p1 #0: tue apr 8 06:45:06 utc 2014 root@amd64-builder.daemonology.net:usrobjusrsrcsysgeneric amd64 '
    config_args='-ds -e -Dprefix=/usr/perl5.21.3 -Dusedevel -Dusemallocwrap=no'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=undef, usemultiplicity=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_FORTIFY_SOURCE=2',
    optimize='-O',
    cppflags='-DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion='', gccversion='4.2.1 Compatible FreeBSD Clang 3.3 (tags/RELEASE_33/final 183502)', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16, longdblkind=3
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags ='-Wl,-E  -fstack-protector -L/usr/local/lib'
    libpth=/usr/lib /usr/local/lib /usr/include/clang/3.3 /usr/lib
    libs=-lgdbm -lm -lcrypt -lutil -lc
    perllibs=-lm -lcrypt -lutil -lc
    libc=, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags=' '
    cccdlflags='-DPIC -fPIC', lddlflags='-shared  -L/usr/local/lib -fstack-protector'



@INC for perl 5.21.3:
    /usr/perl5.21.3/lib/site_perl/5.21.3/amd64-freebsd
    /usr/perl5.21.3/lib/site_perl/5.21.3
    /usr/perl5.21.3/lib/5.21.3/amd64-freebsd
    /usr/perl5.21.3/lib/5.21.3
    .


Environment for perl 5.21.3:
    HOME=/home/eserte
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/eserte/bin/freebsd10.0:/home/eserte/bin/sh:/home/eserte/bin:/usr/games:/home/eserte/devel
    PERLDOC=-MPod::Perldoc::ToTextOverstrike
    PERL_BADLANG (unset)
    PERL_HTML_DISPLAY_CLASS=HTML::Display::Mozilla
    SHELL=/usr/local/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @jhi

Yeah\, I managed to break that just before the release :\-\(

The HEAD from http&#8203;://perl5\.git\.perl\.org/perl\.git should work fine\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Yeah\, I managed to break that just before the release :\-\(

The HEAD from http&#8203;://perl5\.git\.perl\.org/perl\.git should work fine\.

**Comment by p5pRT** [comment]
### From @jhi

On closer look\, this

\#      got "0x1\.5bf0a8b14576ap\+1"
\# expected "0x1\.5bf0a8b145769p\+1"

is a narrower failure \(and not a wider breakage which I suspect\)\, which is caused by too rigid test \(as you can see just the last digits differ\)\.

and this tweak

http&#8203;://perl5\.git\.perl\.org/perl\.git/commitdiff/61b5c6185cc0aebfbd823e601ee6c8023c6aea0d

should allow the test to pass\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On closer look\, this

\#      got "0x1\.5bf0a8b14576ap\+1"
\# expected "0x1\.5bf0a8b145769p\+1"

is a narrower failure \(and not a wider breakage which I suspect\)\, which is caused by too rigid test \(as you can see just the last digits differ\)\.

and this tweak

http&#8203;://perl5\.git\.perl\.org/perl\.git/commitdiff/61b5c6185cc0aebfbd823e601ee6c8023c6aea0d

should allow the test to pass\.

**Comment by p5pRT** [comment]
### From @jkeenan

On Thu Aug 21 13&#8203;:10&#8203;:14 2014\, jhi wrote&#8203;:
> On closer look\, this
> 
> \#      got "0x1\.5bf0a8b14576ap\+1"
> \# expected "0x1\.5bf0a8b145769p\+1"
> 
> is a narrower failure \(and not a wider breakage which I suspect\)\,
> which is caused by too rigid test \(as you can see just the last digits
> differ\)\.
> 
> and this tweak
> 
> http&#8203;://perl5\.git\.perl\.org/perl\.git/commitdiff/61b5c6185cc0aebfbd823e601ee6c8023c6aea0d
> 
> should allow the test to pass\.

Slaven \(or anyone\)&#8203;:

Can we get confirmation that Jarkko's fix resolved the problem on the OS in question?

Thank you very much\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @sisyphus

\-\-\-\-\-Original Message\-\-\-\-\- 
From&#8203;: James E Keenan via RT
Sent&#8203;: Tuesday\, September 23\, 2014 8&#8203;:49 AM
To&#8203;: OtherRecipients of perl Ticket \#122591&#8203;:
Cc&#8203;: perl5\-porters@&#8203;perl\.org
Subject&#8203;: \[perl \#122591\] t/op/sprintf2 fails \(hex floats?\) \(FreeBSD 10\.0\)

> On Thu Aug 21 13&#8203;:10&#8203;:14 2014\, jhi wrote&#8203;:
>> On closer look\, this
>>
>> \#      got "0x1\.5bf0a8b14576ap\+1"
>> \# expected "0x1\.5bf0a8b145769p\+1"

> Can we get confirmation that Jarkko's fix resolved the problem on the OS 
> in question?

Jarkko's fix \(judging by the comments in the code\) seems aimed at hiding 
off\-by\-one discrepancies\.

Are the failures on FreeBSD 10\.0 off by one ? \.\.\.\. or off by more than one ?
On Linux and/or Windows I've seen discrepancies of 2 or more ULP's\, though 
the "problem" values vary from system to system\.

Cheers\,
Rob

**Comment by jkeenan** [comment]
> ### From @eserte
> #### Created by @eserte
> 
> One test failure on a FreeBSD 10.0 system​:
> 
> t/op/sprintf2 ................................................. # Failed test 1419 - '%a' '2.71828182845905' -> '0x1.5bf0a8b14576ap+1' cf '0x1.5bf0a8b145769p+1' at op/sprintf2.t line 577 # got "0x1.5bf0a8b14576ap+1" # expected "0x1.5bf0a8b145769p+1" FAILED at test 1419
> Perl Info

This failure was reported on a version of FreeBSD which is no longer supported.  According to our [smoke-test aggregator](https://perl5.test-smoke.org/matrix), t/op/sprintf2.t is only failing on HP-UX.  That should be the subject of a separate ticket.  Closing this one.
