### ISSUE TITLE
%d really prints quads?

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#1428]
Migrated from [rt.perl.org#2580](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=2580) (status was 'stalled')

Searchable as RT2580$

**Comment by p5pRT** [comment]
### From root@dixie.cscaper.com

#### Created by root@porky.devel.redhat.com



\(this build not installed\)

\# \.\./perl \-e 'printf "%lld\\n"\, 3000000000'
3000000000
\# \.\./perl \-e 'printf "%d\\n"\, 3000000000'
\-1294967296

<details><summary>Perl Info</summary>

```


Site configuration information for perl 5.00503:

Configured by root at Mon Aug 30 23:08:56 EDT 1999.

Summary of my perl5 (5.0 patchlevel 5 subversion 3) configuration:
  Platform:
    osname=linux, osvers=2.2.5-22smp, archname=i386-linux
    uname='linux porky.devel.redhat.com 2.2.5-22smp #1 smp wed jun 2 09:11:51 edt 1999 i686 unknown '
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=undef useperlio=undef d_sfio=undef
  Compiler:
    cc='cc', optimize='-O2', gccversion=egcs-2.91.66 19990314/Linux (egcs-1.1.2 release)
    cppflags='-Dbool=char -DHAS_BOOL -I/usr/local/include'
    ccflags ='-Dbool=char -DHAS_BOOL -I/usr/local/include'
    stdchar='char', d_stdstdio=undef, usevfork=false
    intsize=4, longsize=4, ptrsize=4, doublesize=8
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    alignbytes=4, usemymalloc=n, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib
    libs=-lnsl -ldl -lm -lc -lposix -lcrypt
    libc=, so=so, useshrplib=false, libperl=libperl.a
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-rdynamic'
    cccdlflags='-fpic', lddlflags='-shared -L/usr/local/lib'

Locally applied patches:
    


@INC for perl 5.00503:
    /usr/lib/perl5/5.00503/i386-linux
    /usr/lib/perl5/5.00503
    /usr/lib/perl5/site_perl/5.005/i386-linux
    /usr/lib/perl5/site_perl/5.005
    .


Environment for perl 5.00503:
    HOME=/root
    LANG=en_US
    LANGUAGE (unset)
    LC_ALL=en_US
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/sbin:/sbin:/bin:/usr/bin:/home/joseph/bin:/usr/local/bin:/usr/X11R6/bin:/usr/local/frame/bin:/usr/local/mysql/bin:/oracle/sw/bin:/usr/sbin:/usr/games:.
    PERL_BADLANG (unset)
    SHELL=/bin/tcsh


```
</details>

**Comment by p5pRT** [comment]
### From @smpeters

> \[root@&#8203;dixie\.cscaper\.com \- Wed Mar 22 08&#8203;:44&#8203;:44 2000\]&#8203;:
> 
> 
> This is a bug report for perl from root@&#8203;porky\.devel\.redhat\.com\,
> generated with the help of perlbug 1\.26 running under perl 5\.00503\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> 
> \(this build not installed\)
> 
> \# \.\./perl \-e 'printf "%lld\\n"\, 3000000000'
> 3000000000
> \# \.\./perl \-e 'printf "%d\\n"\, 3000000000'
> \-1294967296
> 
> 

Hmmm\.\.\.I get

steve@&#8203;kirk&#8203;:\~/perl\-current$ \./perl \-e 'printf "%lld\\n"\, 3000000000'
\-1294967296
steve@&#8203;kirk&#8203;:\~/perl\-current$ \./perl \-e 'printf "%d\\n"\, 3000000000'
\-1294967296

Is this what I should be seeing with my 32\-bit CPU?

**Comment by p5pRT** [comment]
### From @ysth

On Tue\, Sep 27\, 2005 at 08&#8203;:59&#8203;:57PM \-0700\, Steve Peters via RT wrote&#8203;:
> > \[root at dixie\.cscaper\.com \- Wed Mar 22 08&#8203;:44&#8203;:44 2000\]&#8203;:
> > \(this build not installed\)
> > 
> > \# \.\./perl \-e 'printf "%lld\\n"\, 3000000000'
> > 3000000000
> > \# \.\./perl \-e 'printf "%d\\n"\, 3000000000'
> > \-1294967296
> > 
> > 
> 
> Hmmm\.\.\.I get
> 
> steve@&#8203;kirk&#8203;:\~/perl\-current$ \./perl \-e 'printf "%lld\\n"\, 3000000000'
> \-1294967296
> steve@&#8203;kirk&#8203;:\~/perl\-current$ \./perl \-e 'printf "%d\\n"\, 3000000000'
> \-1294967296
> 
> Is this what I should be seeing with my 32\-bit CPU?  

Unfortunately\, yes\.  printf doesn't interface well with perl's
way of using whatever kind of storage fits best\.  Try&#8203;:

&nbsp;  printf "%s\\n"\, 3000000000

**Comment by p5pRT** [comment]
### From @gannett-ggreer

perl \-e 'for \(3000000000\, \-3000000000\) \{ printf "s = %s\, d = %d\, u = %u\,
lld = %lld\, llu = %llu\\n"\, \($\_\)x 5; \}'

32\-bit machine \(Fedora 12's 5\.10\.0\)
s = 3000000000\, d = \-1294967296\, u = 3000000000\, lld = \-1294967296\, llu
= 3000000000
s = \-3000000000\, d = \-2147483648\, u = 2147483648\, lld = \-2147483648\, llu
= 2147483648

64\-bit machine \(blead&#8203;: v5\.13\.2\-226\-g86755f4\)
s = 3000000000\, d = 3000000000\, u = 3000000000\, lld = 3000000000\, llu =
3000000000
s = \-3000000000\, d = \-3000000000\, u = 18446744070709551616\, lld =
\-3000000000\, llu = 18446744070709551616


Perhaps it would be well\-served for an addition to the documentation of
sprintf to read&#8203;:

"It is recommended to use '%s' even for variables expected to be numeric
so that the full range of values supported by Perl will be rendered
correctly\. The numeric specifiers are better\-served when the output must
conform to specific sizes/signedness for the use of other applications\,
or when decimal places must be limited\."

\-\- 
George Greer

**Comment by p5pRT** [comment]
### From @cowens

On Sat\, Jul 10\, 2010 at 22&#8203;:13\, George Greer via RT
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> perl \-e 'for \(3000000000\, \-3000000000\) \{ printf "s = %s\, d = %d\, u = %u\,
> lld = %lld\, llu = %llu\\n"\, \($\_\)x 5; \}'
>
> 32\-bit machine \(Fedora 12's 5\.10\.0\)
> s = 3000000000\, d = \-1294967296\, u = 3000000000\, lld = \-1294967296\, llu
> = 3000000000
> s = \-3000000000\, d = \-2147483648\, u = 2147483648\, lld = \-2147483648\, llu
> = 2147483648
>
> 64\-bit machine \(blead&#8203;: v5\.13\.2\-226\-g86755f4\)
> s = 3000000000\, d = 3000000000\, u = 3000000000\, lld = 3000000000\, llu =
> 3000000000
> s = \-3000000000\, d = \-3000000000\, u = 18446744070709551616\, lld =
> \-3000000000\, llu = 18446744070709551616
>
>
> Perhaps it would be well\-served for an addition to the documentation of
> sprintf to read&#8203;:
>
> "It is recommended to use '%s' even for variables expected to be numeric
> so that the full range of values supported by Perl will be rendered
> correctly\. The numeric specifiers are better\-served when the output must
> conform to specific sizes/signedness for the use of other applications\,
> or when decimal places must be limited\."
>
> \-\-
> George Greer
>

%s has its own problems&#8203;:

perl \-e 'printf "%s\\n"\, 10\*\*20'


\-\- 
Chas\. Owens
wonkden\.net
The most important skill a programmer can have is the ability to read\.

**Comment by p5pRT** [comment]
### From @greerga

On Mon\, 12 Jul 2010\, Chas\. Owens wrote&#8203;:

> On Sat\, Jul 10\, 2010 at 22&#8203;:13\, George Greer via RT
> \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
>> perl \-e 'for \(3000000000\, \-3000000000\) \{ printf "s = %s\, d = %d\, u = %u\,
>> lld = %lld\, llu = %llu\\n"\, \($\_\)x 5; \}'
>>
>> 32\-bit machine \(Fedora 12's 5\.10\.0\)
>> s = 3000000000\, d = \-1294967296\, u = 3000000000\, lld = \-1294967296\, llu
>> = 3000000000
>> s = \-3000000000\, d = \-2147483648\, u = 2147483648\, lld = \-2147483648\, llu
>> = 2147483648
>>
>> 64\-bit machine \(blead&#8203;: v5\.13\.2\-226\-g86755f4\)
>> s = 3000000000\, d = 3000000000\, u = 3000000000\, lld = 3000000000\, llu =
>> 3000000000
>> s = \-3000000000\, d = \-3000000000\, u = 18446744070709551616\, lld =
>> \-3000000000\, llu = 18446744070709551616
>>
>>
>> Perhaps it would be well\-served for an addition to the documentation of
>> sprintf to read&#8203;:
>>
>> "It is recommended to use '%s' even for variables expected to be numeric
>> so that the full range of values supported by Perl will be rendered
>> correctly\. The numeric specifiers are better\-served when the output must
>> conform to specific sizes/signedness for the use of other applications\,
>> or when decimal places must be limited\."
>>
>> \-\-
>> George Greer
>>
>
> %s has its own problems&#8203;:
>
> perl \-e 'printf "%s\\n"\, 10\*\*20'

Er\, yes\, that's not very pretty either\.

\-\- 
George Greer

**Comment by p5pRT** [comment]
### From @ikegami

On Sat\, Jul 10\, 2010 at 10&#8203;:13 PM\, George Greer via RT \<
perlbug\-followup@&#8203;perl\.org> wrote&#8203;:

> perl \-e 'for \(3000000000\, \-3000000000\) \{ printf "s = %s\, d = %d\, u = %u\,
> lld = %lld\, llu = %llu\\n"\, \($\_\)x 5; \}'
>
> 32\-bit machine \(Fedora 12's 5\.10\.0\)
> s = 3000000000\, d = \-1294967296\, u = 3000000000\, lld = \-1294967296\, llu
> = 3000000000
> s = \-3000000000\, d = \-2147483648\, u = 2147483648\, lld = \-2147483648\, llu
> = 2147483648
>
> 64\-bit machine \(blead&#8203;: v5\.13\.2\-226\-g86755f4\)
> s = 3000000000\, d = 3000000000\, u = 3000000000\, lld = 3000000000\, llu =
> 3000000000
> s = \-3000000000\, d = \-3000000000\, u = 18446744070709551616\, lld =
> \-3000000000\, llu = 18446744070709551616
>

Is there a reason that Perl requires the "ll" modifier?

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon\, Jul 12\, 2010 at 08&#8203;:21&#8203;:14PM \-0400\, Eric Brine wrote&#8203;:
> On Sat\, Jul 10\, 2010 at 10&#8203;:13 PM\, George Greer via RT \<
> perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> 
> > perl \-e 'for \(3000000000\, \-3000000000\) \{ printf "s = %s\, d = %d\, u = %u\,
> > lld = %lld\, llu = %llu\\n"\, \($\_\)x 5; \}'
> >
> > 32\-bit machine \(Fedora 12's 5\.10\.0\)
> > s = 3000000000\, d = \-1294967296\, u = 3000000000\, lld = \-1294967296\, llu
> > = 3000000000
> > s = \-3000000000\, d = \-2147483648\, u = 2147483648\, lld = \-2147483648\, llu
> > = 2147483648
> >
> > 64\-bit machine \(blead&#8203;: v5\.13\.2\-226\-g86755f4\)
> > s = 3000000000\, d = 3000000000\, u = 3000000000\, lld = 3000000000\, llu =
> > 3000000000
> > s = \-3000000000\, d = \-3000000000\, u = 18446744070709551616\, lld =
> > \-3000000000\, llu = 18446744070709551616
> >
> 
> Is there a reason that Perl requires the "ll" modifier?

It doesn't\, none of the ll modified results are any more correct than
the equivlent normal %u or %d\.

The base problem is that the value\, whatever it is\, is converted to an
IV which can't represent 3000000000 on the 32\-bit platform\.

The only solutions I can see are&#8203;:

a\) require 64\-bit int \- but this just moves the goal\-posts

b\) implement perl\-native large integer\* handling

Tony


\* larger than the machine word\, as with Math&#8203;::BigInt

**Comment by p5pRT** [comment]
### From @ikegami

On Mon\, Jul 12\, 2010 at 8&#8203;:54 PM\, Tony Cook \<tony@&#8203;develop\-help\.com> wrote&#8203;:

> On Mon\, Jul 12\, 2010 at 08&#8203;:21&#8203;:14PM \-0400\, Eric Brine wrote&#8203;:
> > Is there a reason that Perl requires the "ll" modifier?
>
> It doesn't\, none of the ll modified results are any more correct than
> the equivlent normal %u or %d\.
>

Sorry\, I wrongly saw that "ll" was changing the output on 64\-bit\.

**Comment by p5pRT** [comment]
### From @ikegami

On Mon\, Jul 12\, 2010 at 8&#8203;:54 PM\, Tony Cook \<tony@&#8203;develop\-help\.com> wrote&#8203;:

> The only solutions I can see are&#8203;:
>
> a\) require 64\-bit int \- but this just moves the goal\-posts
>
> b\) implement perl\-native large integer\* handling
>

c\) Treating %d as %\.f for values larger than 31/63 bits\. Similar handling
for %u\.

**Comment by p5pRT** [comment]
@dcollinsn - Status changed from 'open' to 'stalled'

**Comment by toddr** [comment]
Other than a documentation change, I see no further action that can be taken here.

**Comment by jkeenan** [comment]
> Other than a documentation change, I see no further action that can be taken here.

@Toddr, can you supply a p.r. for the documentation change (or otherwise indicate what doc(s) need to change)?

**Comment by toddr** [comment]
I was just trying to move the ticket along. I've not looked at this in over 2 years.

**Comment by sisyphus** [comment]
It looks to me that the desired behaviour is already provided by perl's <code>"%D"</code> and <code>"%U"</code> formatting:
```
use strict;
use warnings;
use Config;

print "IVSIZE: $Config{ivsize}\n";
printf "%D\n", ~0;
printf "%U\n", ~0;
printf "%D\n", 3000000000;
printf "%U\n", 3000000000;

__END__

Outputs:

### On 32-bit perl, IVSIZE = 4 ###
IVSIZE: 4
-1
4294967295
-1294967296
3000000000

### On 32-bit perl, IVSIZE = 8 ###
IVSIZE: 8
-1
18446744073709551615
3000000000
3000000000

### On 64-bit perl, IVSIZE = 8 ###
IVSIZE: 8
-1
18446744073709551615
3000000000
3000000000
```
Do I misunderstand what's being sought ?

Cheers,
Rob

**Comment by khwilliamson** [comment]
Why not use %u for printing number > IV_MAX ?

**Comment by khwilliamson** [comment]
That is, internallly convert %d into %u for printing such numbers

**Comment by sisyphus** [comment]
I gather there's a perceived shortcoming in that neither "%d" nor "%D" nor "%u" nor "%U" are guaranteed to display the actual value of the IV, for all possible IV values.
At least one of those formats will display the actual value, but you have to pick the right format for certain IV values.

As noted in the thread, "%s" will always display the actual value of the IV.
This happens because perl's interpolation of IVs checks for the IsUV flag.

However, you don't want to use "%s" if the value is an NV because of the inherently inaccurate way that perl interpolates NVs.
(Mind you, I don't see anything unsatisfactory with the NV 10**20 being interpolated as "1e+20". What's wrong with that ?)
If we want "%s" to also display correctly for NVs, then we need to fix the way that NVs are interpolated - even if only in the way that Devel::Peek::Dump() does it (as of perl-5.36.0).
But I don't think this issue is about that, anyway.

I think it could be  helpful to mention in the sprintf() docs that "%s" is the only format that's guaranteed to display the actual value of an IV, irrespective of that value.

I personally don't see a reason to keep this issue open.

Cheers,
Rob

**Comment by demerphq** [comment]
Closing.
