### ISSUE TITLE
Pod::Html loses link

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14413]
Migrated from [rt.perl.org#123593](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=123593) (status was 'open')

Searchable as RT123593$

**Comment by p5pRT** [comment]
### From @tux

$ cat rt\.pl
\#\!/usr/bin/perl

1;

=head1 DEMO
X\<DEMO>

L\<DEMO|/DEMO> without NL

L\<DEMO with NL|
/DEMO> and trailing text  

=cut
$ podchecker rt\.pl
rt\.pl pod syntax OK\.
$ perl \-MV=Pod&#8203;::Checker\,Pod&#8203;::Simple\,Pod&#8203;::Html
Pod&#8203;::Checker
&nbsp;        /pro/lib/perl5/5\.20\.0/Pod/Checker\.pm&#8203;: 1\.71
Pod&#8203;::Simple
&nbsp;        /pro/lib/perl5/5\.20\.0/Pod/Simple\.pm&#8203;: 3\.28
Pod&#8203;::Html
&nbsp;        /pro/lib/perl5/5\.20\.0/Pod/Html\.pm&#8203;: 1\.21
$ pod2text rt\.pl
DEMO
&nbsp;    DEMO without NL

&nbsp;    DEMO with NL and trailing text

$ pod2html rt\.pl
Cannot find " " in podpath&#8203;: cannot find suitable replacement path\, cannot resolve link
\<?xml version="1\.0" ?>
\<\!DOCTYPE html PUBLIC "\-//W3C//DTD XHTML 1\.0 Strict//EN" "http&#8203;://www\.w3\.org/TR/xhtml1/DTD/xhtml1\-strict\.dtd">
\<html xmlns="http&#8203;://www\.w3\.org/1999/xhtml">
\<head>
\<title>\</title>
\<meta http\-equiv="content\-type" content="text/html; charset=utf\-8" />
\<link rev="made" href="mailto&#8203;:h\.m\.brand@&#8203;xs4all\.nl" />
\</head>

\<body>



\<ul id="index">
&nbsp;  \<li>\<a href="\#DEMO">DEMO \</a>\</li>
\</ul>

\<h1 id="DEMO">DEMO \</h1>

\<p>\<a href="\#DEMO">DEMO\</a> without NL\</p>

\<p>\<a>DEMO with NL\</a> and trailing text\</p>


\</body>

\</html>

**Comment by p5pRT** [comment]
### From @jkeenan

On Mon Jan 12 09&#8203;:04&#8203;:14 2015\, hmbrand wrote&#8203;:
> $ cat rt\.pl
> \#\!/usr/bin/perl
> 
> 1;
> 
> =head1 DEMO
> X\<DEMO>
> 
> L\<DEMO|/DEMO> without NL
> 
> L\<DEMO with NL|
>   /DEMO> and trailing text
> 
> =cut
> $ podchecker rt\.pl
> rt\.pl pod syntax OK\.
> $ perl \-MV=Pod&#8203;::Checker\,Pod&#8203;::Simple\,Pod&#8203;::Html
> Pod&#8203;::Checker
>         /pro/lib/perl5/5\.20\.0/Pod/Checker\.pm&#8203;: 1\.71
> Pod&#8203;::Simple
>         /pro/lib/perl5/5\.20\.0/Pod/Simple\.pm&#8203;: 3\.28
> Pod&#8203;::Html
>         /pro/lib/perl5/5\.20\.0/Pod/Html\.pm&#8203;: 1\.21
> $ pod2text rt\.pl
> DEMO
>     DEMO without NL
> 
> DEMO with NL and trailing text
> 
> $ pod2html rt\.pl
> Cannot find " " in podpath&#8203;: cannot find suitable replacement path\,
> cannot resolve link
> \<?xml version="1\.0" ?>
> \<\!DOCTYPE html PUBLIC "\-//W3C//DTD XHTML 1\.0 Strict//EN"
> "http&#8203;://www\.w3\.org/TR/xhtml1/DTD/xhtml1\-strict\.dtd">
> \<html xmlns="http&#8203;://www\.w3\.org/1999/xhtml">
> \<head>
> \<title>\</title>
> \<meta http\-equiv="content\-type" content="text/html; charset=utf\-8" />
> \<link rev="made" href="mailto&#8203;:h\.m\.brand@&#8203;xs4all\.nl" />
> \</head>
> 
> \<body>
> 
> 
> 
> \<ul id="index">
>   \<li>\<a href="\#DEMO">DEMO \</a>\</li>
> \</ul>
> 
> \<h1 id="DEMO">DEMO \</h1>
> 
> \<p>\<a href="\#DEMO">DEMO\</a> without NL\</p>
> 
> \<p>\<a>DEMO with NL\</a> and trailing text\</p>
> 
> 
> \</body>
> 
> \</html>

Additional data point\.  When the newline occurs \*before\* the pipe in the final L\<> link\, there is no error and the link is preserved\.  See attachments\.

Thank you very much\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @jkeenan

[123593-newline-before-pipe.pl](https://rt-archive.perl.org/perl5/Ticket/Attachment/1326354/707598/123593-newline-before-pipe.pl)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by jkeenan** [comment]
@Tux, I get no warnings when I run your sample program through the `pod2html` that ships with perl-5.32.0.
```
$ pod2html rt.pl 2> ./gh-14413-warnings.txt; ls -l gh-14413-warnings.txt
<?xml version="1.0" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title></title>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<link rev="made" href="mailto:jkeenan@zareason.(none)" />
</head>

<body>



<ul id="index">
  <li><a href="#DEMO">DEMO </a></li>
</ul>

<h1 id="DEMO">DEMO </h1>

<p><a href="#DEMO">DEMO</a> without NL</p>

<p><a>DEMO with NL</a> and trailing text</p>


</body>

</html>


-rw-rw-r-- 1 jkeenan jkeenan 0 Jan 30 17:22 gh-14413-warnings.txt
```
Is this still a problem for you?

Thank you very much.
Jim Keenan

**Comment by Tux** [comment]
@jkeenan I just checked, no warning, looks like being resolved
Feel free to close
