### ISSUE TITLE
FindBin dual-life on CPAN

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14479]
Migrated from [rt.perl.org#123752](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=123752) (status was 'open')

Searchable as RT123752$

**Comment by p5pRT** [comment]
### From rehsack@gmail.com

Hi\,

today I discussed about File&#8203;::ConfigDir with a user and this discussion
resulted in RT\#101966 \(https://rt.cpan.org/Public/Bug/Display.html?id=101966).

However\, with perl\-5\.16 comes FindBin having a serious bug fixed\, which might
makes it reasonable to have FindBin on CPAN to force updates in legacy
environments\.

Best regards
\-\- 
Jens Rehsack
rehsack@&#8203;gmail\.com

**Comment by p5pRT** [comment]
### From @karenetheridge

On Fri Feb 06 07&#8203;:11&#8203;:19 2015\, rehsack@&#8203;gmail\.com wrote&#8203;:
> However\, with perl\-5\.16 comes FindBin having a serious bug fixed\,
> which might
> makes it reasonable to have FindBin on CPAN to force updates in legacy
> environments\.

My assumption/understanding was that non\-dual\-lifed modules had that status if
they were so intertwined with core features that it was inpractical or
impossible to write them to work on multiple perl versions simultaneously\.
This doesn't seem to be the case for FindBin\, so I wholeheartedly support the
sentiment to make this a dual\-life module \(even if it's upstream\-blead\)\, to
facilitate having older perl installs benefit from recent bug fixes\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Sun Feb 08 15&#8203;:39&#8203;:30 2015\, ether wrote&#8203;:
> On Fri Feb 06 07&#8203;:11&#8203;:19 2015\, rehsack@&#8203;gmail\.com wrote&#8203;:
> > However\, with perl\-5\.16 comes FindBin having a serious bug fixed\,
> > which might
> > makes it reasonable to have FindBin on CPAN to force updates in
> > legacy
> > environments\.
> 
> My assumption/understanding was that non\-dual\-lifed modules had that
> status if
> they were so intertwined with core features that it was inpractical or
> impossible to write them to work on multiple perl versions
> simultaneously\.
> This doesn't seem to be the case for FindBin\, so I wholeheartedly
> support the
> sentiment to make this a dual\-life module \(even if it's upstream\-
> blead\)\, to
> facilitate having older perl installs benefit from recent bug fixes\.

There's several core\-only modules that aren't tied to core and could be released as dual\-life\, it's really just a matter of finding volunteers who are interested in doing releases\.

I think any of the following could be made dual\-life&#8203;:

&nbsp;  ext/FileCache
&nbsp;  ext/File\-Find
&nbsp;  ext/GDBM\_File
&nbsp;  ext/I18N\-LangInfo
&nbsp;  ext/IPC\-Open3
&nbsp;  ext/NDBM\_File
&nbsp;  ext/ODBM\_File
&nbsp;  ext/PerlIO\-encoding
&nbsp;  ext/PerlIO\-mmap
&nbsp;  ext/PerlIO\-scalar
&nbsp;  ext/PerlIO\-via
&nbsp;  ext/Pod\-Html
&nbsp;  ext/POSIX \(might be a lot of work\, since probing is done by Configure\)
&nbsp;  ext/SDBM\_File
&nbsp;  ext/Sys\-Hostname
&nbsp;  ext/Tie\-Memoize

&nbsp;  lib/AnyDBM\_File\.pm
&nbsp;  lib/Benchmark\.pm
&nbsp;  lib/Class/Struct\.pm
&nbsp;  lib/DBM\_Filter\.pm \(etc\)
&nbsp;  lib/DirHandle\.pm
&nbsp;  lib/File/Basename\.pm
&nbsp;  lib/File/Compare\.pm
&nbsp;  lib/File/Copy\.pm
&nbsp;  lib/FileHandle\.pm
&nbsp;  lib/File/stat\.pm
&nbsp;  lib/FindBin\.pm
&nbsp;  lib/Getopt/Std\.pm
&nbsp;  lib/Net/\*ent\.pm
&nbsp;  lib/SelectSaver\.pm
&nbsp;  lib/Tie/\*\.pm
&nbsp;  lib/Time/gmtime\.pm
&nbsp;  lib/Time/localtime\.pm
&nbsp;  lib/User/\*ent\.pm

Making some of the lib/ modules \(like File&#8203;::Copy\) available on CPAN may complicate the build process a little more \- we'll need to add their dist/Foo/lib directories to miniperl's search path\, but that's not difficult\.

Tony

**Comment by p5pRT** [comment]
### From @jkeenan

On Sun Feb 08 18&#8203;:41&#8203;:05 2015\, tonyc wrote&#8203;:
> On Sun Feb 08 15&#8203;:39&#8203;:30 2015\, ether wrote&#8203;:
> > On Fri Feb 06 07&#8203;:11&#8203;:19 2015\, rehsack@&#8203;gmail\.com wrote&#8203;:
> > > However\, with perl\-5\.16 comes FindBin having a serious bug fixed\,
> > > which might
> > > makes it reasonable to have FindBin on CPAN to force updates in
> > > legacy
> > > environments\.
> >
> > My assumption/understanding was that non\-dual\-lifed modules had that
> > status if
> > they were so intertwined with core features that it was inpractical
> > or
> > impossible to write them to work on multiple perl versions
> > simultaneously\.
> > This doesn't seem to be the case for FindBin\, so I wholeheartedly
> > support the
> > sentiment to make this a dual\-life module \(even if it's upstream\-
> > blead\)\, to
> > facilitate having older perl installs benefit from recent bug fixes\.
> 
> There's several core\-only modules that aren't tied to core and could
> be released as dual\-life\, it's really just a matter of finding
> volunteers who are interested in doing releases\.
> 

Yesterday I had a go at moving FindBin from lib/ to dist/\.  My objective was simply to understand the mechanics of making this move\, i\.e\.\, to see what would break\.

I had to add a dummy entry for a CPAN distro for this in Porting/Maintainers\.pl\.  That cleared up one failure in the porting tests\.

The one error that I didn't know how to solve was this&#8203;:

\#\#\#\#\#
$ cd t; \./perl harness \-v porting/regen\.t; cd \-

ok 1 \- generated perly\.act is up to date
\[snip\]
ok \- regen/genpacksizetables\.pl packsizetables\.c
'lib/\.gitignore\-new' and 'lib/\.gitignore' differ
ok \# Makefile\.SH is up to date
ok \# win32/Makefile is up to date
ok \# win32/makefile\.mk is up to date
not ok \- regen/lib\_cleanup\.pl lib/\.gitignore
ok \- regen/miniperlmain\.pl miniperlmain\.c
ok \- regen/feature\.pl feature\.h
not ok \- Porting/makemeta META\.json
'META\.json\-new' and 'META\.json' differ
'META\.yml\-new' and 'META\.yml' differ
not ok \- Porting/makemeta META\.yml
Failed 3/43 subtests 

Test Summary Report


---
porting/regen\.t \(Wstat&#8203;: 0 Tests&#8203;: 43 Failed&#8203;: 3\)
&nbsp;  Failed tests&#8203;:  14\, 42\-43
Files=1\, Tests=43\,  2 wallclock secs \( 0\.02 usr  0\.00 sys \+  1\.98 cusr  0\.09 csys =  2\.09 CPU\)
Result&#8203;: FAIL
/home/jkeenan/gitwork/perl
\#\#\#\#\#

I don't yet have a position as to whether making FindBin dual\-lifed is a good idea or not\.

Thank you very much\.



\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @tonycoz

On Sun Feb 08 19&#8203;:15&#8203;:25 2015\, jkeenan wrote&#8203;:
> Yesterday I had a go at moving FindBin from lib/ to dist/\.  My
> objective was simply to understand the mechanics of making this move\,
> i\.e\.\, to see what would break\.
> 
> I had to add a dummy entry for a CPAN distro for this in
> Porting/Maintainers\.pl\.  That cleared up one failure in the porting
> tests\.
> 
> The one error that I didn't know how to solve was this&#8203;:
> 
> \#\#\#\#\#
> $ cd t; \./perl harness \-v porting/regen\.t; cd \-
> 
> ok 1 \- generated perly\.act is up to date
> \[snip\]
> ok \- regen/genpacksizetables\.pl packsizetables\.c
> 'lib/\.gitignore\-new' and 'lib/\.gitignore' differ
> ok \# Makefile\.SH is up to date
> ok \# win32/Makefile is up to date
> ok \# win32/makefile\.mk is up to date
> not ok \- regen/lib\_cleanup\.pl lib/\.gitignore

Possibly\, just run&#8203;:

&nbsp;  perl regen/lib\_cleanup\.pl

Tony

**Comment by p5pRT** [comment]
### From rehsack@gmail.com


> Am 09\.02\.2015 um 03&#8203;:41 schrieb Tony Cook via RT \<perlbug\-followup@&#8203;perl\.org>&#8203;:
> 
> On Sun Feb 08 15&#8203;:39&#8203;:30 2015\, ether wrote&#8203;:
>> On Fri Feb 06 07&#8203;:11&#8203;:19 2015\, rehsack@&#8203;gmail\.com wrote&#8203;:
>>> However\, with perl\-5\.16 comes FindBin having a serious bug fixed\,
>>> which might
>>> makes it reasonable to have FindBin on CPAN to force updates in
>>> legacy
>>> environments\.
>> 
>> My assumption/understanding was that non\-dual\-lifed modules had that
>> status if
>> they were so intertwined with core features that it was inpractical or
>> impossible to write them to work on multiple perl versions
>> simultaneously\.
>> This doesn't seem to be the case for FindBin\, so I wholeheartedly
>> support the
>> sentiment to make this a dual\-life module \(even if it's upstream\-
>> blead\)\, to
>> facilitate having older perl installs benefit from recent bug fixes\.
> 
> There's several core\-only modules that aren't tied to core and could be released as dual\-life\, it's really just a matter of finding volunteers who are interested in doing releases\.

For a very few \(max 3\) I could do\.
I expect it's not necessary to have separate dists for any\, so ?DBM\_File could be in a one dist \(with or without AnyDBM\.\.\.?\)\.
Maybe Steffen could be asked to include lib/File/Basename\.pm into PathTools?

I'm familiar with the POSIX backends below File/stat\.pm and the \*/\*ent\.pm
CPAN POSIX\.pm should receive kind of probing as Config&#8203;::AutoConf provides \.\.\.

Not that I offer volunteering here and now \- but I'm open for ?DBM\_File and POSIX related stuff\.
Maybe that's something we \(Rick\) can discuss at qah in Berlin\.

> I think any of the following could be made dual\-life&#8203;:
> 
>  ext/FileCache
>  ext/File\-Find
>  ext/GDBM\_File
>  ext/I18N\-LangInfo
>  ext/IPC\-Open3
>  ext/NDBM\_File
>  ext/ODBM\_File
>  ext/PerlIO\-encoding
>  ext/PerlIO\-mmap
>  ext/PerlIO\-scalar
>  ext/PerlIO\-via
>  ext/Pod\-Html
>  ext/POSIX \(might be a lot of work\, since probing is done by Configure\)
>  ext/SDBM\_File
>  ext/Sys\-Hostname
>  ext/Tie\-Memoize
> 
>  lib/AnyDBM\_File\.pm
>  lib/Benchmark\.pm
>  lib/Class/Struct\.pm
>  lib/DBM\_Filter\.pm \(etc\)
>  lib/DirHandle\.pm
>  lib/File/Basename\.pm
>  lib/File/Compare\.pm
>  lib/File/Copy\.pm
>  lib/FileHandle\.pm
>  lib/File/stat\.pm
>  lib/FindBin\.pm
>  lib/Getopt/Std\.pm
>  lib/Net/\*ent\.pm
>  lib/SelectSaver\.pm
>  lib/Tie/\*\.pm
>  lib/Time/gmtime\.pm
>  lib/Time/localtime\.pm
>  lib/User/\*ent\.pm
> 
> Making some of the lib/ modules \(like File&#8203;::Copy\) available on CPAN may complicate the build process a little more \- we'll need to add their dist/Foo/lib directories to miniperl's search path\, but that's not difficult\.

Cheers
\-\- 
Jens Rehsack
rehsack@&#8203;gmail\.com

**Comment by p5pRT** [comment]
### From @jkeenan

On Sun Feb 08 21&#8203;:28&#8203;:02 2015\, tonyc wrote&#8203;:
> On Sun Feb 08 19&#8203;:15&#8203;:25 2015\, jkeenan wrote&#8203;:
> > Yesterday I had a go at moving FindBin from lib/ to dist/\.  My
> > objective was simply to understand the mechanics of making this move\,
> > i\.e\.\, to see what would break\.
> > 
> > I had to add a dummy entry for a CPAN distro for this in
> > Porting/Maintainers\.pl\.  That cleared up one failure in the porting
> > tests\.
> > 
> > The one error that I didn't know how to solve was this&#8203;:
> > 
> > \#\#\#\#\#
> > $ cd t; \./perl harness \-v porting/regen\.t; cd \-
> > 
> > ok 1 \- generated perly\.act is up to date
> > \[snip\]
> > ok \- regen/genpacksizetables\.pl packsizetables\.c
> > 'lib/\.gitignore\-new' and 'lib/\.gitignore' differ
> > ok \# Makefile\.SH is up to date
> > ok \# win32/Makefile is up to date
> > ok \# win32/makefile\.mk is up to date
> > not ok \- regen/lib\_cleanup\.pl lib/\.gitignore
> 
> Possibly\, just run&#8203;:
> 
>   perl regen/lib\_cleanup\.pl
> 
> Tony

That reduced the number of failures from 3 to 2\.

\#\#\#\#\#
$ perl regen/lib\_cleanup\.pl
Changed&#8203;: lib/\.gitignore
\[perl\] 108 $ cd t; \./perl harness \-v porting/regen\.t; cd \-

ok 1 \- generated perly\.act is up to date
\[snip\]
ok \- regen/feature\.pl feature\.h
not ok \- Porting/makemeta META\.json
'META\.json\-new' and 'META\.json' differ
'META\.yml\-new' and 'META\.yml' differ
not ok \- Porting/makemeta META\.yml
Failed 2/43 subtests 

Test Summary Report


---
porting/regen\.t \(Wstat&#8203;: 0 Tests&#8203;: 43 Failed&#8203;: 2\)
&nbsp;  Failed tests&#8203;:  42\-43
Files=1\, Tests=43\,  2 wallclock secs \( 0\.02 usr  0\.00 sys \+  1\.57 cusr  0\.05 csys =  1\.64 CPU\)
Result&#8203;: FAIL
/home/jkeenan/gitwork/perl
\#\#\#\#\#
\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @tonycoz

On Mon Feb 09 04&#8203;:46&#8203;:32 2015\, jkeenan wrote&#8203;:
> not ok \- Porting/makemeta META\.json
> 'META\.json\-new' and 'META\.json' differ
> 'META\.yml\-new' and 'META\.yml' differ
> not ok \- Porting/makemeta META\.yml
>  Failed 2/43 subtests

&nbsp;  make regen\-meta

should fix them both\.

Tony

**Comment by p5pRT** [comment]
### From @ap

\* Jens Rehsack \<rehsack@&#8203;gmail\.com> \[2015\-02\-09 10&#8203;:55\]&#8203;:
> I expect it's not necessary to have separate dists for any\, so
> ?DBM\_File could be in a one dist \(with or without AnyDBM\.\.\.?\)\.

If you are using a particular DBM you want to be able to depend on that
specific DBM\.

\-\- 
Aristotle Pagaltzis // \<http&#8203;://plasmasturm\.org/>

**Comment by p5pRT** [comment]
### From rehsack@gmail.com


> Am 11\.02\.2015 um 18&#8203;:40 schrieb Aristotle Pagaltzis \<pagaltzis@&#8203;gmx\.de>&#8203;:
> 
> \* Jens Rehsack \<rehsack@&#8203;gmail\.com> \[2015\-02\-09 10&#8203;:55\]&#8203;:
>> I expect it's not necessary to have separate dists for any\, so
>> ?DBM\_File could be in a one dist \(with or without AnyDBM\.\.\.?\)\.
> 
> If you are using a particular DBM you want to be able to depend on that
> specific DBM\.

We should discuss this outside of this ticket ;\)
I have a little experience with that and which OS provides you which one\.
So no\, particular dependencies on ?DBM\_File are insane except of GDBM\_File when restricted OS support \.\.\.

Cheers
\-\- 
Jens Rehsack
rehsack@&#8203;gmail\.com

**Comment by Grinnz** [comment]
This would still be really great to have.

**Comment by khwilliamson** [comment]
@jkeenan, maybe you could revive your efforts to do the move?

**Comment by jkeenan** [comment]
> @jkeenan, maybe you could revive your efforts to do the move?

No thanks.  I no longer have that code available.  Even if I did, (a) there are other CPAN distros I am more concerned about from a maintenance perspective; and (b) it would be better if someone other than me took this over.  This kind of maintenance work is the sort of thing that a new contributor to the Perl 5 core distribution can cut her teeth on.  We have to be thinking of recruiting new people rather than asking veteran contributors to extend themselves further.

Thank you very much.
Jim Keenan

**Comment by xsawyerx** [comment]
Hey. I just posted a PR to do this. It's being smoked. I put everyone here as reviewers to approve.

**Comment by jkeenan** [comment]
As far as I can tell, FindBin version 1.51 is found in both blead and perl-5.30.1.  In the repository, it's found under ```dist/FindBin```, which is appropriate for a "blead-upstream" dual life module.

However, AFAICT it has not yet received a separate CPAN release.  Searching for it on metacpan points to perl-5.30.1.

Do we need to do a CPAN release before we can close this ticket?  If so, who can do that?

Thank you very much.
Jim Keenan

**Comment by haarg** [comment]
Would it be possible to get a CPAN release of FindBin?

It's currently not viewable on metacpan because it's listed as no_index in perl, but doesn't have its own release.

**Comment by jkeenan** [comment]
> As far as I can tell, FindBin version 1.51 is found in both blead and perl-5.30.1. In the repository, it's found under `dist/FindBin`, which is appropriate for a "blead-upstream" dual life module.
> 
> However, AFAICT it has not yet received a separate CPAN release. Searching for it on metacpan points to perl-5.30.1.
> 
> Do we need to do a CPAN release before we can close this ticket? If so, who can do that?
> 
> Thank you very much.
> Jim Keenan

@xsawyerx, can you handle this upstream release of FindBin?

Thank you very much.
Jim Keenan

**Comment by Grinnz** [comment]
This has been handled by @toddr https://metacpan.org/release/TODDR/FindBin-1.52

**Comment by jkeenan** [comment]
> This has been handled by @toddr https://metacpan.org/release/TODDR/FindBin-1.52

Thanks. Closing ticket.
