### ISSUE TITLE
Respect perl6 in hashbang

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14661]
Migrated from [rt.perl.org#124346](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=124346) (status was 'open')

Searchable as RT124346$

**Comment by p5pRT** [comment]
### From @Leont

This is a bug report for perl from fawaka@&#8203;gmail\.com\,
generated with the help of perlbug 1\.40 running under perl 5\.20\.1\.




---
Currently\, when perl tries to run a script and it encounters a hashbang
line not containing the string "perl" \(e\.g\. /usr/bin/python\)\, it will
instead run that executable\. This works for most other languages\, but for
perl6 this doesn't switch gracefully for obvious reasons\.

The attached patch tries to fix that\, so that \#\!perl6 files will DWIM\.



---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=wishlist


---
Site configuration information for perl 5\.20\.1&#8203;:

Configured by leon at Tue Oct 21 13&#8203;:31&#8203;:28 CEST 2014\.

Summary of my perl5 \(revision 5 version 20 subversion 1\) configuration&#8203;:

&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=3\.13\.0\-37\-generic\,
archname=x86\_64\-linux\-thread\-multi
&nbsp;    uname='linux leon\-laptop 3\.13\.0\-37\-generic \#64\-ubuntu smp mon sep 22
21&#8203;:28&#8203;:38 utc 2014 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;    config\_args='\-de \-Dprefix=/home/leon/perl5/perlbrew/perls/perl\-5\.20\.1
\-Duseshrplib \-DDEBUGGING \-Dusethreads
\-Aeval&#8203;:scriptdir=/home/leon/perl5/perlbrew/perls/perl\-5\.20\.1/bin'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fwrapv \-DDEBUGGING
\-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include
\-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O2 \-g'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fwrapv \-DDEBUGGING
\-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.8\.2'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\,
lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/4\.8/include\-fixed
/usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib
/usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
\-lgdbm\_compat
&nbsp;    perllibs=\-lnsl \-ldl \-lm \-lcrypt \-lutil \-lpthread \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=true\, libperl=libperl\.so
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E
\-Wl\,\-rpath\,/home/leon/perl5/perlbrew/perls/perl\-5\.20\.1/lib/5\.20\.1/x86\_64\-linux\-thread\-multi/CORE'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-g \-L/usr/local/lib
\-fstack\-protector'




---
@&#8203;INC for perl 5\.20\.1&#8203;:

/home/leon/perl5/perlbrew/perls/perl\-5\.20\.1/lib/site\_perl/5\.20\.1/x86\_64\-linux\-thread\-multi
&nbsp;    /home/leon/perl5/perlbrew/perls/perl\-5\.20\.1/lib/site\_perl/5\.20\.1

/home/leon/perl5/perlbrew/perls/perl\-5\.20\.1/lib/5\.20\.1/x86\_64\-linux\-thread\-multi
&nbsp;    /home/leon/perl5/perlbrew/perls/perl\-5\.20\.1/lib/5\.20\.1
&nbsp;    \.



---
Environment for perl 5\.20\.1&#8203;:
&nbsp;    HOME=/home/leon
&nbsp;    LANG=en\_US\.UTF\-8
&nbsp;    LANGUAGE=en\_US&#8203;:en
&nbsp;    LC\_ADDRESS=en\_US\.UTF\-8
&nbsp;    LC\_IDENTIFICATION=en\_US\.UTF\-8
&nbsp;    LC\_MEASUREMENT=en\_US\.UTF\-8
&nbsp;    LC\_MONETARY=en\_US\.UTF\-8
&nbsp;    LC\_NAME=en\_US\.UTF\-8
&nbsp;    LC\_NUMERIC=en\_US\.UTF\-8
&nbsp;    LC\_PAPER=en\_US\.UTF\-8
&nbsp;    LC\_TELEPHONE=en\_US\.UTF\-8
&nbsp;    LC\_TIME=en\_US\.UTF\-8
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)

PATH=/home/leon/\.rakudobrew/bin&#8203;:/home/leon/perl5/perlbrew/bin&#8203;:/home/leon/perl5/perlbrew/perls/perl\-5\.20\.1/bin&#8203;:/home/leon/bin&#8203;:/usr/local/sbin&#8203;:/usr/local/bin&#8203;:/usr/sbin&#8203;:/usr/bin&#8203;:/sbin&#8203;:/bin&#8203;:/usr/games&#8203;:/usr/local/games
&nbsp;    PERLBREW\_BASHRC\_VERSION=0\.71
&nbsp;    PERLBREW\_HOME=/home/leon/\.perlbrew
&nbsp;    PERLBREW\_MANPATH=/home/leon/perl5/perlbrew/perls/perl\-5\.20\.1/man

PERLBREW\_PATH=/home/leon/perl5/perlbrew/bin&#8203;:/home/leon/perl5/perlbrew/perls/perl\-5\.20\.1/bin
&nbsp;    PERLBREW\_PERL=perl\-5\.20\.1
&nbsp;    PERLBREW\_ROOT=/home/leon/perl5/perlbrew
&nbsp;    PERLBREW\_VERSION=0\.71
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @Leont

<details><summary>0001-Respect-hashbangs-containing-perl6.patch</summary>

```diff
From f39a39ab79624a58283ef25ddb94a2b39f73ac06 Mon Sep 17 00:00:00 2001
From: Leon Timmermans <fawaka@gmail.com>
Date: Sun, 19 Apr 2015 13:03:28 +0200
Subject: [PATCH] Respect hashbangs containing perl6

---
 toke.c | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/toke.c b/toke.c
index 294cb8f..077ab08 100644
--- a/toke.c
+++ b/toke.c
@@ -4863,6 +4863,8 @@ Perl_yylex(pTHX)
 		d = instr(s,"perl -");
 		if (!d) {
 		    d = instr(s,"perl");
+                    if (d && d[4] == '6')
+                        d = NULL;
 #if defined(DOSISH)
 		    /* avoid getting into infinite loops when shebang
 		     * line contains "Perl" rather than "perl" */
-- 
1.9.1


```
</details>

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Leon Timmermans wrote&#8203;:
>The attached patch tries to fix that\, so that \#\!perl6 files will DWIM\.

That \#\! hack is obsolete\.  We should not change its behaviour for perl6\.
We should either leave it totally unchanged or remove it entirely\.

\-zefram

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @rjbs

\* Zefram \<zefram@&#8203;fysh\.org> \[2015\-04\-19T10&#8203;:12&#8203;:48\]
> Leon Timmermans wrote&#8203;:
> >The attached patch tries to fix that\, so that \#\!perl6 files will DWIM\.
> 
> That \#\! hack is obsolete\.  We should not change its behaviour for perl6\.
> We should either leave it totally unchanged or remove it entirely\.

I find both sides of this tempting\, because I constantly write "perl
my\-perl6\-program" and like to imagine that it would help\.  I'd need to have a
perl6 shebang\, though\, which I rarely do in the things I'm running\, which are
tests or libraries\.  If I did have a shebang\, it would probably be to run env\,
sadly\, and then I start getting nervous about the idea of picking our
executable based on things like secondary args in the shebang \(although we
already do it\)\.

Obviously\, I'm just a single data point here\.  My gut\, though\, is that this
will be added complexity with very little actual gain\.  It's also very little
added complexity\, though\.

Anybody care to convince me otherwise?

\-\- 
rjbs

**Comment by p5pRT** [comment]
### From @Leont

On Tue\, May 26\, 2015 at 1&#8203;:20 PM\, Ricardo Signes \<perl\.p5p@&#8203;rjbs\.manxome\.org>
wrote&#8203;:

> \* Zefram \<zefram@&#8203;fysh\.org> \[2015\-04\-19T10&#8203;:12&#8203;:48\]
> > Leon Timmermans wrote&#8203;:
> > >The attached patch tries to fix that\, so that \#\!perl6 files will DWIM\.
> >
> > That \#\! hack is obsolete\.  We should not change its behaviour for perl6\.
> > We should either leave it totally unchanged or remove it entirely\.
>
> I find both sides of this tempting\, because I constantly write "perl
> my\-perl6\-program" and like to imagine that it would help\.  I'd need to
> have a
> perl6 shebang\, though\, which I rarely do in the things I'm running\, which
> are
> tests or libraries\.  If I did have a shebang\, it would probably be to run
> env\,
> sadly\, and then I start getting nervous about the idea of picking our
> executable based on things like secondary args in the shebang \(although we
> already do it\)\.
>
> Obviously\, I'm just a single data point here\.  My gut\, though\, is that this
> will be added complexity with very little actual gain\.  It's also very
> little
> added complexity\, though\.
>
> Anybody care to convince me otherwise?
>

There are programs out there that depend on perl acting as a switchbox\, in
particular prove is such a program\. This patch doesn't help anyone in
perl5\-land\, but it would help a lot of people in perl6\-land\.

Leon

**Comment by p5pRT** [comment]
### From @ap

\* Leon Timmermans \<fawaka@&#8203;gmail\.com> \[2015\-06\-20 21&#8203;:50\]&#8203;:
> There are programs out there that depend on perl acting as
> a switchbox\, in particular prove is such a program\. This
> patch doesn't help anyone in perl5\-land\, but it would help
> a lot of people in perl6\-land\.

\+1

It doesn’t even add any conceptual complexity – all behaviours
already exist\, and the patch achieves its purpose by narrowing
down the special case \(i\.e\. perl\)\. I find this pleasing\.

Regards\,
\-\- 
Aristotle Pagaltzis // \<http&#8203;://plasmasturm\.org/>

**Comment by p5pRT** [comment]
### From @ribasushi

On 06/20/2015 09&#8203;:47 PM\, Leon Timmermans wrote&#8203;:
>
> \.\.\.
>This patch doesn't help anyone in
> perl5\-land\, but it would help a lot of people in perl6\-land\.

\+1

**Comment by p5pRT** [comment]
### From @rjbs

\* Leon Timmermans \<perlbug\-followup@&#8203;perl\.org> \[2015\-04\-19T09&#8203;:53&#8203;:21\]
> Currently\, when perl tries to run a script and it encounters a hashbang
> line not containing the string "perl" \(e\.g\. /usr/bin/python\)\, it will
> instead run that executable\. This works for most other languages\, but for
> perl6 this doesn't switch gracefully for obvious reasons\.
> 
> The attached patch tries to fix that\, so that \#\!perl6 files will DWIM\.

Okay\, go for it\.


\-\- 
rjbs

**Comment by p5pRT** [comment]
### From @avar

On Sun\, Apr 19\, 2015 at 3&#8203;:53 PM\, Leon Timmermans
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> \# New Ticket Created by  Leon Timmermans
> \# Please include the string&#8203;:  \[perl \#124346\]
> \# in the subject line of all future correspondence about this issue\.
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=124346 >
>
>
> This is a bug report for perl from fawaka@&#8203;gmail\.com\,
> generated with the help of perlbug 1\.40 running under perl 5\.20\.1\.
>
>
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
>
> Currently\, when perl tries to run a script and it encounters a hashbang
> line not containing the string "perl" \(e\.g\. /usr/bin/python\)\, it will
> instead run that executable\. This works for most other languages\, but for
> perl6 this doesn't switch gracefully for obvious reasons\.
>
> The attached patch tries to fix that\, so that \#\!perl6 files will DWIM\.

I think this patch makes sense\, but I wonder if other cases could also
DWYM\. Currently these shebangs trigger these behaviors\, where "exec"
is "execute other interpreter" and "ignore" is "treat it as a
comment"&#8203;:

\#\!/bin/sh => exec
\#\!sh => exec
\#\!rakudo => exec
\#\!perl => exec
\#\!/bin/perl => ignore
\#\!thewordperlinthemiddleofastring => ignore
\#\!perl5\.18\.2 => ignore
\#\!perl6 => ignore
\#\!/bin/perl6 => ignore
\#\!rakudoperl6 =>  ignore
\#\!rakudoperlsix => ignore
\#\!company\-perl => ignore
\#\!company\-perl5\.18\.2 => ignore

You patch would alter the behavior of these&#8203;:

\#\!perl6 => exec
\#\!/bin/perl6 => exec
\#\!rakudoperl6 =>  exec

I think that makes sense\, but I wonder if we're being overly eager
currently about recognizing the "perl" substring anywhere in the
shebang\. But on the other hand we have things like
"\#\!/usr/local/bin/company\-perl5\.18\.2" which relies on this behavior\.
So I don't know\.

**Comment by p5pRT** [comment]
### From perl@profvince.com

Can we have support for php and python next?


Vincent

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Vincent Pit \(VPIT\) wrote&#8203;:
>Can we have support for php and python next?

Already got that\.  perl does general shebang redirection for any shebang
that does not contain the substring "perl"; the issue is about extending
that redirection to some strings that do contain that substring\.

\-zefram

**Comment by p5pRT** [comment]
### From net@profvince.com



Le 22/06/2015 09&#8203;:49\, Zefram a écrit :
> Vincent Pit \(VPIT\) wrote&#8203;:
>> Can we have support for php and python next?
>
> Already got that\.  perl does general shebang redirection for any shebang
> that does not contain the substring "perl"; the issue is about extending
> that redirection to some strings that do contain that substring\.
>
> \-zefram
>

Thanks\, that makes sense then\.

**Comment by p5pRT** [comment]
### From @ikegami

On Mon\, Jun 22\, 2015 at 8&#8203;:36 AM\, Ævar Arnfjörð Bjarmason \<avarab@&#8203;gmail\.com>
wrote&#8203;:

> \#\!perl => exec
> \#\!/bin/perl => ignore
>

I think that's a typo?

**Comment by Leont** [comment]
Given the perl6 -> raku namechange, I think this ticket can be closed :-)
