### ISSUE TITLE
AIX locale setting fails on one machine

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14695]
Migrated from [rt.perl.org#125142](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=125142) (status was 'stalled')

Searchable as RT125142$

**Comment by p5pRT** [comment]
### From @khwilliamson

This is a bug report for perl from khw@&#8203;khw\.\(none\)\,
generated with the help of perlbug 1\.40 running under perl 5\.22\.0\.




---
This is to make this email thread into a bug report so that it can be
tracked\.  See http&#8203;://nntp\.perl\.org/group/perl\.perl5\.porters/227690
and follow\-up\.

This is being made a blocker for 5\.22 until we decide how to proceed\.
One idea is to just not do locale handling on gcc for AIX for 5\.22\.
But this may be a machine configuration error\.  This isn't consistent
with things just breaking recently\, unless there were other changes to
the now\-failing machine at the time\.  A bisect would help figure that
out\.

I have been granted access to that machine\, but there isn't enough disk
space in my home directory to make a copy of the perl file structure and
compile and test\.


---


---
Flags&#8203;:
&nbsp;     category=core
&nbsp;     severity=high


---
Site configuration information for perl 5\.22\.0&#8203;:

Configured by khw at Fri May  8 20&#8203;:27&#8203;:28 MDT 2015\.

Summary of my perl5 \(revision 5 version 22 subversion 0\) configuration&#8203;:
&nbsp;   Commit id&#8203;: 2a2c1c1d49921db69fffe2426dad61ee9c146610
&nbsp;   Platform&#8203;:
&nbsp;     osname=linux\, osvers=3\.16\.0\-37\-generic\, 
archname=x86\_64\-linux\-thread\-multi\-ld
&nbsp;     uname='linux khw 3\.16\.0\-37\-generic \#51\-ubuntu smp tue may 5 
13&#8203;:45&#8203;:59 utc 2015 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;     config\_args='\-des \-Uversiononly \-Dprefix=/home/khw/blead \-Dusedevel 
\-D'optimize=\-ggdb3' \-A'optimize=\-ggdb3' \-A'optimize=\-O0' 
\-Accflags='\-DPERL\_BOOL\_AS\_CHAR' \-Dman1dir=none \-Dman3dir=none 
\-DDEBUGGING \-Dcc=g\+\+ \-Dusemorebits \-Dusethreads'
&nbsp;     hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;     useithreads=define\, usemultiplicity=define
&nbsp;     use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;     usemymalloc=n\, bincompat5005=undef
&nbsp;   Compiler&#8203;:
&nbsp;     cc='g\+\+'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DPERL\_BOOL\_AS\_CHAR 
\-fwrapv \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong 
\-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 
\-D\_FORTIFY\_SOURCE=2'\,
&nbsp;     optimize=' \-ggdb3 \-O0'\,
&nbsp;     cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DPERL\_BOOL\_AS\_CHAR \-fwrapv 
\-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong 
\-I/usr/local/include'
&nbsp;     ccversion=''\, gccversion='4\.9\.1'\, gccosandvers=''
&nbsp;     intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, 
doublekind=3
&nbsp;     d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, 
longdblsize=16\, longdblkind=3
&nbsp;     ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, 
Off\_t='off\_t'\, lseeksize=8
&nbsp;     alignbytes=16\, prototype=define
&nbsp;   Linker and Libraries&#8203;:
&nbsp;     ld='g\+\+'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;     libpth=/usr/include/c\+\+/4\.9 /usr/include/x86\_64\-linux\-gnu/c\+\+/4\.9 
/usr/include/c\+\+/4\.9/backward /usr/local/lib 
/usr/lib/gcc/x86\_64\-linux\-gnu/4\.9/include\-fixed 
/usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib 
/usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;     libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;     perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;     libc=libc\-2\.19\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;     gnulibc\_version='2\.19'
&nbsp;   Dynamic Linking&#8203;:
&nbsp;     dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;     cccdlflags='\-fPIC'\, lddlflags='\-shared \-ggdb3 \-ggdb3 \-O0 
\-L/usr/local/lib \-fstack\-protector\-strong'

Locally applied patches&#8203;:
&nbsp;     RC0



---
@&#8203;INC for perl 5\.22\.0&#8203;:
&nbsp;     /home/khw/perl/blead/lib
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.22\.0/x86\_64\-linux\-thread\-multi\-ld
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.22\.0
&nbsp;     /home/khw/blead/lib/perl5/5\.22\.0/x86\_64\-linux\-thread\-multi\-ld
&nbsp;     /home/khw/blead/lib/perl5/5\.22\.0
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.12
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.11
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.10
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.9
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.8
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.7
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.6
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.5
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.4
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.3
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.2
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.21\.1
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.20\.0
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.19\.12
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.19\.11
&nbsp;     /home/khw/blead/lib/perl5/site\_perl/5\.19\.10
&nbsp;     /home/khw/blead/lib/perl5/site\_perl
&nbsp;     \.



---
Environment for perl 5\.22\.0&#8203;:
&nbsp;     HOME=/home/khw
&nbsp;     LANG=en\_US\.UTF\-8
&nbsp;     LANGUAGE=en\_US
&nbsp;     LD\_LIBRARY\_PATH \(unset\)
&nbsp;     LOGDIR \(unset\)
 
PATH=/home/khw/bin&#8203;:/home/khw/perl5/perlbrew/bin&#8203;:/home/khw/print/bin&#8203;:/bin&#8203;:/usr/local/sbin&#8203;:/usr/local/bin&#8203;:/usr/sbin&#8203;:/usr/bin&#8203;:/sbin&#8203;:/usr/games&#8203;:/usr/local/games&#8203;:/home/khw/iands/www&#8203;:/home/khw/cxoffice/bin
&nbsp;     PERL5OPT=\-w
&nbsp;     PERL\_BADLANG \(unset\)
&nbsp;     PERL\_POD\_PEDANTIC=1
&nbsp;     SHELL=/bin/ksh

**Comment by p5pRT** [comment]
### From @khwilliamson

I don't think this is a Perl problem\, and I know it isn't a new Perl problem\, so I have removed it as a 5\.22 blocker\.

Michael granted me access to a failing machine\, and I downloaded and compiled 5\.20\.2 and got the same failure\.  This proves it isn't a regression introduced in the 5\.21 series\, so it isn't a 5\.22 blocker\.

I don't know why it suddenly showed up\.  Michael speculated to me privately that the xlc smoke reports were masking the gcc ones\, as this shows up only with gcc\.

And\, given that truss and dbx are indicating a failing libc call\, it seems pretty unlikely to be a Perl bug\.

\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, May 10\, 2015 at 10&#8203;:11&#8203;:16AM \-0700\, Karl Williamson via RT wrote&#8203;:
> I don't think this is a Perl problem\, and I know it isn't a new Perl problem\, so I have removed it as a 5\.22 blocker\.
> 
> Michael granted me access to a failing machine\, and I downloaded and compiled 5\.20\.2 and got the same failure\.  This proves it isn't a regression introduced in the 5\.21 series\, so it isn't a 5\.22 blocker\.
> 
> I don't know why it suddenly showed up\.  Michael speculated to me privately that the xlc smoke reports were masking the gcc ones\, as this shows up only with gcc\.
> 
> And\, given that truss and dbx are indicating a failing libc call\, it seems pretty unlikely to be a Perl bug\.

Hi Karl\, any particular reason why this ticket has been marked as a 5\.26\.0
blocker?

\-\- 
I don't want to achieve immortality through my work\.\.\.
I want to achieve it through not dying\.
&nbsp;    \-\- Woody Allen

**Comment by p5pRT** [comment]
### From @khwilliamson

On 03/20/2017 09&#8203;:34 AM\, Dave Mitchell wrote&#8203;:
> On Sun\, May 10\, 2015 at 10&#8203;:11&#8203;:16AM \-0700\, Karl Williamson via RT wrote&#8203;:
>> I don't think this is a Perl problem\, and I know it isn't a new Perl problem\, so I have removed it as a 5\.22 blocker\.
>>
>> Michael granted me access to a failing machine\, and I downloaded and compiled 5\.20\.2 and got the same failure\.  This proves it isn't a regression introduced in the 5\.21 series\, so it isn't a 5\.22 blocker\.
>>
>> I don't know why it suddenly showed up\.  Michael speculated to me privately that the xlc smoke reports were masking the gcc ones\, as this shows up only with gcc\.
>>
>> And\, given that truss and dbx are indicating a failing libc call\, it seems pretty unlikely to be a Perl bug\.
>
> Hi Karl\, any particular reason why this ticket has been marked as a 5\.26\.0
> blocker?
>

See http&#8203;://nntp\.perl\.org/group/perl\.perl5\.porters/243217

All BBC tickets should be reviewed to decide if they should be blockers\.

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Mar 20\, 2017 at 10&#8203;:40&#8203;:11AM \-0600\, Karl Williamson wrote&#8203;:
> On 03/20/2017 09&#8203;:34 AM\, Dave Mitchell wrote&#8203;:
> > On Sun\, May 10\, 2015 at 10&#8203;:11&#8203;:16AM \-0700\, Karl Williamson via RT wrote&#8203;:
> > > I don't think this is a Perl problem\, and I know it isn't a new Perl problem\, so I have removed it as a 5\.22 blocker\.
> > > 
> > > Michael granted me access to a failing machine\, and I downloaded and compiled 5\.20\.2 and got the same failure\.  This proves it isn't a regression introduced in the 5\.21 series\, so it isn't a 5\.22 blocker\.
> > > 
> > > I don't know why it suddenly showed up\.  Michael speculated to me privately that the xlc smoke reports were masking the gcc ones\, as this shows up only with gcc\.
> > > 
> > > And\, given that truss and dbx are indicating a failing libc call\, it seems pretty unlikely to be a Perl bug\.
> > 
> > Hi Karl\, any particular reason why this ticket has been marked as a 5\.26\.0
> > blocker?
> > 
> 
> See http&#8203;://nntp\.perl\.org/group/perl\.perl5\.porters/243217
> 
> All BBC tickets should be reviewed to decide if they should be blockers\.

In that case\, do you think it should be a blocker\, either for 5\.26\.0 or
any other release? My feeling is not\, but this isn't my area of expertise\.

\-\- 
Art is anything that has a label \(especially if the label is "untitled 1"\)

**Comment by p5pRT** [comment]
### From @khwilliamson

On 03/20/2017 11&#8203;:04 AM\, Dave Mitchell wrote&#8203;:
> On Mon\, Mar 20\, 2017 at 10&#8203;:40&#8203;:11AM \-0600\, Karl Williamson wrote&#8203;:
>> On 03/20/2017 09&#8203;:34 AM\, Dave Mitchell wrote&#8203;:
>>> On Sun\, May 10\, 2015 at 10&#8203;:11&#8203;:16AM \-0700\, Karl Williamson via RT wrote&#8203;:
>>>> I don't think this is a Perl problem\, and I know it isn't a new Perl problem\, so I have removed it as a 5\.22 blocker\.
>>>>
>>>> Michael granted me access to a failing machine\, and I downloaded and compiled 5\.20\.2 and got the same failure\.  This proves it isn't a regression introduced in the 5\.21 series\, so it isn't a 5\.22 blocker\.
>>>>
>>>> I don't know why it suddenly showed up\.  Michael speculated to me privately that the xlc smoke reports were masking the gcc ones\, as this shows up only with gcc\.
>>>>
>>>> And\, given that truss and dbx are indicating a failing libc call\, it seems pretty unlikely to be a Perl bug\.
>>>
>>> Hi Karl\, any particular reason why this ticket has been marked as a 5\.26\.0
>>> blocker?
>>>
>>
>> See http&#8203;://nntp\.perl\.org/group/perl\.perl5\.porters/243217
>>
>> All BBC tickets should be reviewed to decide if they should be blockers\.
>
> In that case\, do you think it should be a blocker\, either for 5\.26\.0 or
> any other release? My feeling is not\, but this isn't my area of expertise\.
>

I merely did a bulk move\.  I don't think this should be a blocker

**Comment by p5pRT** [comment]
### From @khwilliamson

Michael\, since this ticket was opened\, new debugging has been added so that we can more easily see what's going on\.  If you could take a recent version of blead\, compiled with \-DDEBUGGING\, and with this set&#8203;:

export PERL\_DEBUG\_LOCALE\_INIT=1

and run your test again on it\, and send us the output


\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
### From @khwilliamson

I have now removed this from the list of 5\.26 blockers\, and renamed it so that it won't get added again\.


\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
### From @aixtools

I had many system changes\, among them one of the systems I could
borrowed \- and died\. I'll look into setting up a single partition to
run blead again \- versus the eight I had running before\.

Hope that helps\!

Michael

On Sat\, Mar 25\, 2017 at 2&#8203;:30 AM\, Karl Williamson via RT
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> Michael\, since this ticket was opened\, new debugging has been added so that we can more easily see what's going on\.  If you could take a recent version of blead\, compiled with \-DDEBUGGING\, and with this set&#8203;:
>
> export PERL\_DEBUG\_LOCALE\_INIT=1
>
> and run your test again on it\, and send us the output
>
>
> \-\-
> Karl Williamson
>
> \-\-\-
> via perlbug&#8203;:  queue&#8203;: perl5 status&#8203;: open
> https://rt-archive.perl.org/perl5/Ticket/Display.html?id=125142

**Comment by p5pRT** [comment]
### From @khwilliamson

On Tue\, 28 Mar 2017 08&#8203;:02&#8203;:26 \-0700\, aixtools@&#8203;gmail\.com wrote&#8203;:
> I had many system changes\, among them one of the systems I could
> borrowed \- and died\. I'll look into setting up a single partition to
> run blead again \- versus the eight I had running before\.
> 
> Hope that helps\!
> 
> Michael
> 
> On Sat\, Mar 25\, 2017 at 2&#8203;:30 AM\, Karl Williamson via RT
> \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> > Michael\, since this ticket was opened\, new debugging has been added
> > so that we can more easily see what's going on\.  If you could take a
> > recent version of blead\, compiled with \-DDEBUGGING\, and with this
> > set&#8203;:
> >
> > export PERL\_DEBUG\_LOCALE\_INIT=1
> >
> > and run your test again on it\, and send us the output
> >
> >
> > \-\-
> > Karl Williamson
> >
> > \-\-\-
> > via perlbug&#8203;:  queue&#8203;: perl5 status&#8203;: open
> > https://rt-archive.perl.org/perl5/Ticket/Display.html?id=125142

Any status on this?
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
### From @khwilliamson

No response from OP in a year; marking this stalled
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
@khwilliamson - Status changed from 'open' to 'stalled'

**Comment by khwilliamson** [comment]
No respone in 4 years; closing
