### ISSUE TITLE
Perl segfaults in BEGIN, write to null pointer, separate bug

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#14852]
Migrated from [rt.perl.org#125806](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=125806) (status was 'open')

Searchable as RT125806$

**Comment by p5pRT** [comment]
### From @dcollinsn

This is distinct from \#125789 \(duplicate of \#121048\, patch in \#125341\)\. This segfault occurs in a different function and appears to be unrelated\. Reini's patch in \#125341 does not affect this bug\.

The testcase is the following 15\-character file&#8203;:

BEGIN\(\)\{i or$\[\}

Bisect not attempted because this also crashes in my ancient perl 5\.10\.1 install\.

\*\*GDB\*\*
\(gdb\) run
Starting program&#8203;: /home/dcollins/perl/perl \-e BEGIN\\\(\\\)\\\{i\\ or\\$\\\[\\\}
\[Thread debugging using libthread\_db enabled\]
b
Program received signal SIGSEGV\, Segmentation fault\.
memmove \(\) at \.\./sysdeps/i386/i686/memmove\.S&#8203;:64
64    \.\./sysdeps/i386/i686/memmove\.S&#8203;: No such file or directory\.
&nbsp;    in \.\./sysdeps/i386/i686/memmove\.S
Current language&#8203;:  auto
The current source language is "auto; currently asm"\.
\(gdb\) l
59    in \.\./sysdeps/i386/i686/memmove\.S
\(gdb\) bt
\#0  memmove \(\) at \.\./sysdeps/i386/i686/memmove\.S&#8203;:64
\#1  0x083bd9b7 in Perl\_sv\_setpv \(sv=0x86f9358\, ptr=0x869c5e2 ""\) at sv\.c&#8203;:4906
\#2  0x0807bd57 in Perl\_newXS\_len\_flags \(name=0x86fd998 "BEGIN"\, len=5\, 
&nbsp;    subaddr=0x806d160 \<const\_sv\_xsub>\, filename=0x86f4c26 "\-e"\, 
&nbsp;    proto=0x869c5e2 ""\, const\_svp=0xbffff1a0\, flags=1\) at op\.c&#8203;:9151
\#3  0x0807c93f in Perl\_newCONSTSUB\_flags \(stash=0x0\, name=0x86fd998 "BEGIN"\, 
&nbsp;    len=5\, flags=0\, sv=0x86f9344\) at op\.c&#8203;:9014
\#4  0x080cb4bf in Perl\_newATTRSUB\_x \(floor=39\, o=0x86fe744\, proto=0x86fe764\, 
&nbsp;    attrs=0x0\, block=0x86fe8d4\, o\_is\_gv=false\) at op\.c&#8203;:8634
\#5  0x081c6383 in Perl\_yyparse \(gramtype=258\) at perly\.y&#8203;:293
\#6  0x08106787 in S\_parse\_body \(env=\<value optimized out>\, 
&nbsp;    xsinit=\<value optimized out>\) at perl\.c&#8203;:2296
\#7  0x08109aa3 in perl\_parse \(my\_perl=0x86e6008\, xsinit=0x8065d10 \<xs\_init>\, 
&nbsp;    argc=3\, argv=0xbffff4f4\, env=0x0\) at perl\.c&#8203;:1626
\#8  0x08065acf in main \(argc=3\, argv=0xbffff4f4\, env=0xbffff504\)
&nbsp;    at perlmain\.c&#8203;:114
\(gdb\) q

The relevant call to Move in sv\.c has the following parameters&#8203;:
4906        Move\(ptr\,SvPVX\(sv\)\,len\+1\,char\);
\(gdb\) p ptr
$1 = 0x869c5e2 ""
\(gdb\) p sv
$2 = \(SV \* const\) 0x86f9358
\(gdb\) p len
$3 = \<value optimized out>


\*\*VALGRIND\*\*
dcollins@&#8203;nagios&#8203;:\~/perl$ valgrind \./perl \-e 'BEGIN\(\)\{i or$\[\}'==20018== Memcheck\, a memory error detector
==20018== Copyright \(C\) 2002\-2010\, and GNU GPL'd\, by Julian Seward et al\.
==20018== Using Valgrind\-3\.6\.0\.SVN\-Debian and LibVEX; rerun with \-h for copyright info
==20018== Command&#8203;: \./perl \-e BEGIN\(\)\{i\\ or$\[\}
==20018== 
==20018== Invalid write of size 1
==20018==    at 0x4026534&#8203;: memmove \(mc\_replace\_strmem\.c&#8203;:629\)
==20018==    by 0x83BD9B6&#8203;: Perl\_sv\_setpv \(sv\.c&#8203;:4906\)
==20018==    by 0x807BD56&#8203;: Perl\_newXS\_len\_flags \(op\.c&#8203;:9151\)
==20018==    by 0x807C93E&#8203;: Perl\_newCONSTSUB\_flags \(op\.c&#8203;:9014\)
==20018==    by 0x80CB4BE&#8203;: Perl\_newATTRSUB\_x \(op\.c&#8203;:8634\)
==20018==    by 0x81C6382&#8203;: Perl\_yyparse \(perly\.y&#8203;:293\)
==20018==    by 0x8106786&#8203;: S\_parse\_body \(perl\.c&#8203;:2296\)
==20018==    by 0x8109AA2&#8203;: perl\_parse \(perl\.c&#8203;:1626\)
==20018==    by 0x8065ACE&#8203;: main \(perlmain\.c&#8203;:114\)
==20018==  Address 0x0 is not stack'd\, malloc'd or \(recently\) free'd
==20018== 
==20018== 
==20018== Process terminating with default action of signal 11 \(SIGSEGV\)
==20018==  Access not within mapped region at address 0x0
==20018==    at 0x4026534&#8203;: memmove \(mc\_replace\_strmem\.c&#8203;:629\)
==20018==    by 0x83BD9B6&#8203;: Perl\_sv\_setpv \(sv\.c&#8203;:4906\)
==20018==    by 0x807BD56&#8203;: Perl\_newXS\_len\_flags \(op\.c&#8203;:9151\)
==20018==    by 0x807C93E&#8203;: Perl\_newCONSTSUB\_flags \(op\.c&#8203;:9014\)
==20018==    by 0x80CB4BE&#8203;: Perl\_newATTRSUB\_x \(op\.c&#8203;:8634\)
==20018==    by 0x81C6382&#8203;: Perl\_yyparse \(perly\.y&#8203;:293\)
==20018==    by 0x8106786&#8203;: S\_parse\_body \(perl\.c&#8203;:2296\)
==20018==    by 0x8109AA2&#8203;: perl\_parse \(perl\.c&#8203;:1626\)
==20018==    by 0x8065ACE&#8203;: main \(perlmain\.c&#8203;:114\)
==20018==  If you believe this happened as a result of a stack
==20018==  overflow in your program's main thread \(unlikely but
==20018==  possible\)\, you can try to increase the size of the
==20018==  main thread stack using the \-\-main\-stacksize= flag\.
==20018==  The main thread stack size used in this run was 8388608\.
==20018== 
==20018== HEAP SUMMARY&#8203;:
==20018==     in use at exit&#8203;: 145\,310 bytes in 882 blocks
==20018==   total heap usage&#8203;: 1\,323 allocs\, 441 frees\, 211\,204 bytes allocated
==20018== 
==20018== LEAK SUMMARY&#8203;:
==20018==    definitely lost&#8203;: 168 bytes in 1 blocks
==20018==    indirectly lost&#8203;: 2\,661 bytes in 40 blocks
==20018==      possibly lost&#8203;: 30\,982 bytes in 336 blocks
==20018==    still reachable&#8203;: 111\,499 bytes in 505 blocks
==20018==         suppressed&#8203;: 0 bytes in 0 blocks
==20018== Rerun with \-\-leak\-check=full to see details of leaked memory
==20018== 
==20018== For counts of detected and suppressed errors\, rerun with&#8203;: \-v
==20018== ERROR SUMMARY&#8203;: 1 errors from 1 contexts \(suppressed&#8203;: 27 from 10\)
Segmentation fault

\*\*PERL \-V\*\*
dcollins@&#8203;nagios&#8203;:\~/perl$ \./perl \-V
Summary of my perl5 \(revision 5 version 23 subversion 2\) configuration&#8203;:
&nbsp;  Derived from&#8203;: 9728ed0a4dcaca9d7fddf6ce9c5736ed3aacd487
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.6\.32\-5\-686\, archname=i686\-linux\-64int\-ld
&nbsp;    uname='linux nagios 2\.6\.32\-5\-686 \#1 smp tue may 13 16&#8203;:33&#8203;:32 utc 2014 i686 gnulinux '
&nbsp;    config\_args=''
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=undef\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='afl\-gcc'\, ccflags ='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-g'\,
&nbsp;    cppflags='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.4\.5'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=12345678\, doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12\, longdblkind=3
&nbsp;    ivtype='long long'\, ivsize=8\, nvtype='long double'\, nvsize=12\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='afl\-gcc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/i486\-linux\-gnu/4\.4\.5/include\-fixed /usr/lib /lib/\.\./lib /usr/lib/\.\./lib /lib /usr/lib/i486\-linux\-gnu /usr/lib64
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.11\.3\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.11\.3'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-g \-L/usr/local/lib \-fstack\-protector'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: HAS\_TIMES PERLIO\_LAYERS PERL\_COPY\_ON\_WRITE
&nbsp;                        PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV USE\_64\_BIT\_INT USE\_LARGE\_FILES
&nbsp;                        USE\_LOCALE USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME USE\_LONG\_DOUBLE
&nbsp;                        USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Locally applied patches&#8203;:
&nbsp;    uncommitted\-changes
&nbsp;  Built under linux
&nbsp;  Compiled at Aug 13 2015 18&#8203;:34&#8203;:59
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.2/i686\-linux\-64int\-ld
&nbsp;    /usr/local/perl\-afl/lib/site\_perl/5\.23\.2
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.2/i686\-linux\-64int\-ld
&nbsp;    /usr/local/perl\-afl/lib/5\.23\.2
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @wolfsage

On Thu\, Aug 13\, 2015 at 7&#8203;:05 PM\, Dan Collins \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> \# New Ticket Created by  Dan Collins
> \# Please include the string&#8203;:  \[perl \#125806\]
> \# in the subject line of all future correspondence about this issue\.
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=125806 >
>
>
> This is distinct from \#125789 \(duplicate of \#121048\, patch in \#125341\)\. This segfault occurs in a different function and appears to be unrelated\. Reini's patch in \#125341 does not affect this bug\.
>
> The testcase is the following 15\-character file&#8203;:
>
> BEGIN\(\)\{i or$\[\}
>
> Bisect not attempted because this also crashes in my ancient perl 5\.10\.1 install\.

Looks like it first broke in 5\.8\.9\, and since then has failed
magnificently in different ways as Perl has aged\.

\-\- Matthew Horsfall \(alh\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From zefram@fysh.org

The test case simplifies to&#8203;:

$ perl \-e 'BEGIN \{\} BEGIN \(\) \{1\}'
zsh&#8203;: segmentation fault  perl \-e 'BEGIN \{\} BEGIN \(\) \{1\}'

The necessary elements are a BEGIN block with constant\-value \(foldable\)
body and empty prototype\, compilation of which completes after some other
real or implied BEGIN block\.  The effect of $\[ in the original test case
was merely to imply a BEGIN block that is used to load the arybase module\.

The mode by which it fails is that the constant\-value BEGIN block gets
compiled as a constant subroutine\, taking quite a different path through
construction from what a normal sub would get\, and this code path doesn't
cope with the sub getting automatically run and SvREFCNT\_dec\(\)ed partway
through construction\.  The segv specifically happens when sv\_setpv\(\) is
invoked to attach the prototype\, just after the sub has been automatically
run\, so sv\_setpv\(\) sees a freed SV\.

Fixing this is not trivial\.  It's easy enough to prevent sv\_setpv\(\)
being called from newXS\_len\_flags\(\) if it's been freed\, just as some of
the stuff at the end of newATTRSUB\_x\(\) is conditional\.  But it returns
to newCONSTSUB\_flags\(\)\, which performs further work on the CV\, and in so
doing assumes that it's still alive\.  In fact\, in principle it's wrong
to perform the automatic run so early\, because it's being run before
newCONSTSUB\_flags\(\) has completed construction; it hasn't even put the
constant value in at that point\, though nothing currently depends on
that value\.  It's tempting to create an extra mortal reference to the
sub when it's automatically run as a BEGIN block\, but that lasts too
long in some situations\.

So I think the automatic running and freeing needs to be shifted around\,
and this will probably require a flag to newXS\_len\_flags\(\) to suppress
the automatic run \(which is still required when it's called from other
places\)\.  But its flag word is currently in a silly state\, taking two
sets of flags that overlap in their bit usage\, so that really needs to
be sorted out first\.  We could also do with documenting these functions\,
particularly in how to handle their potentially\-freed result\.

\-zefram

**Comment by p5pRT** [comment]
### From @cpansprout

On Mon\, 04 Dec 2017 08&#8203;:20&#8203;:43 \-0800\, zefram@&#8203;fysh\.org wrote&#8203;:
> So I think the automatic running and freeing needs to be shifted around\,
> and this will probably require a flag to newXS\_len\_flags\(\) to suppress
> the automatic run \(which is still required when it's called from other
> places\)\.  But its flag word is currently in a silly state\, taking two
> sets of flags that overlap in their bit usage\, so that really needs to
> be sorted out first\.  We could also do with documenting these functions\,
> particularly in how to handle their potentially\-freed result\.

newXS\_len\_flags is not API\, so we can change it however we want\.  I also think it should remain private\, precisely so that we have wiggle room to fix problems such as this in future\.  \(This is not the first time it has needed a significant rework to fix bug\.\)

\-\- 

Father Chrysostomos

**Comment by demerphq** [comment]
This does not segfault in 5.34.1. Possibly because the prototype is ignored because the expression is not constant.  See also #16057 for the same reduced bug.

**Comment by bram-perl** [comment]
> This does not segfault in 5.34.1. Possibly because the prototype is ignored because the expression is not constant. See also #16057 for the same reduced bug.

Doing some testing: on v5.34.1:

This no longer segfaults on v5.34.1:
```
$ ./perl  -Ilib -le 'BEGIN(){i or$[};'
```
but something like:
```
$ ./perl  -Ilib -le 'no strict; BEGIN(){i or$[};'
```
still does (on v5.34.1, not on blead).

Digging a bit deeper: using `$[` used to imply `use arybase;` but that got removed in perl v5.30.0:
```
$ ./perl -wle 'print $];'
5.030000
$ ./perl  -le 'BEGIN(){i or$[};'
$ ./perl -Ilib -le 'no strict; BEGIN(){i or$[};'
Segmentation fault (core dumped)
```

So you are indeed somewhat correct: the example in the issue description no longer segfaults - on v5.34.1 - but that's simply because there no longer is an earlier `BEGIN` block (or no longer a `use` statement since that too implies a BEGIN block).

The real solution is the one you committed for #16057

**Comment by demerphq** [comment]
Ah, i guess you mean e5d2a2ef8ab1139143d2cad7a2d0db63a6f7d8f5

Cool. :-) Closing.
