### ISSUE TITLE
various glob() bugs

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#1496]
Migrated from [rt.perl.org#2707](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=2707) (status was 'open')

Searchable as RT2707$

**Comment by p5pRT** [comment]
### From tchrist@chthon.perl.com

Summary&#8203;:

&nbsp;    1\.  Prototype change breaks documented examples\.
&nbsp;    2\.  :globally problems
&nbsp;    3\.  Incompatible breakage 
&nbsp;    4\.  Missing docs

\+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\+
| 1\.  Prototype change breaks documented examples\. |
\+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\+

I seem to recall that this is my own fault&#8203;:

\[  5163\] By&#8203;: gsar                                  on 2000/02/20  16&#8203;:34&#8203;:33
&nbsp;        Log&#8203;: glob\(\) takes one or no user arguments and a non\-user\-visible second
&nbsp;             hidden argument\, fix its prototype\-checking accordingly
&nbsp;     Branch&#8203;: perl

That made this&#8203;:

&nbsp;    glob            glob                    ck\_glob         t@&#8203;      S? S?
become this
&nbsp;    glob            glob                    ck\_glob         t@&#8203;      S?

And that breaks this&#8203;:

&nbsp;     use File&#8203;::Glob '&#8203;:glob';
&nbsp;     @&#8203;list = glob\('\*\.\[ch\]'\);
&nbsp;     $homedir = glob\('~gnat'\, GLOB\_TILDE | GLOB\_ERR\);
&nbsp;     if \(GLOB\_ERROR\) \{
&nbsp;         print "can't glob ~gnat&#8203;: $\!\\n";
&nbsp;     \} else \{
&nbsp;      print "Gnat lives in $homedir\\n";
&nbsp;     \} 

Which used to say

&nbsp;    Gnat lives in /home/gnat

But now says

&nbsp;    Too many arguments for glob at \- line 3\, near "GLOB\_ERR\)"

So even though you import it\, and even though it goes into \<\*> fileglobs\,
you have to say this&#8203;:

&nbsp;     use File&#8203;::Glob '&#8203;:glob';
&nbsp;     @&#8203;list = glob\('\*\.\[ch\]'\);
&nbsp;     $homedir = &glob\('~gnat'\, GLOB\_TILDE | GLOB\_ERR\);
&nbsp;     if \(GLOB\_ERROR\) \{
&nbsp;         print "can't glob ~gnat&#8203;: $\!\\n";
&nbsp;     \} else \{
&nbsp;      print "Gnat lives in $homedir\\n";
&nbsp;     \} 

Yes\, you have to use &glob to give another argument\. 

I don't know a perfect solution here\, but right now\, there's
a problem\.  Well\, yes\, I do know a perfect solution&#8203;: if one
could \(effectively\) frob the opcode\.pl output so that

&nbsp;    \*CORE&#8203;::GLOBAL&#8203;::glob = \\&File&#8203;::Glob&#8203;::csh\_glob;

would make the parser tolerate 0 or 1 arguments\, but with 

&nbsp;    \*CORE&#8203;::GLOBAL&#8203;::glob = \\&File&#8203;::Glob&#8203;::glob;

it would tolerate 0\, 1\, or 2 arguments\.

\+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\+
| 2\.  :globally problems |
\+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\+

There are other problems with this module\.  The import

&nbsp;     use File&#8203;::Glob '&#8203;:globally';

is a silent no\-op on systems compiled with \-DPERL\_EXTERNAL\_GLOB\.
That's because all it does is                 

&nbsp;    \*CORE&#8203;::GLOBAL&#8203;::glob = \\&File&#8203;::Glob&#8203;::csh\_glob;

but that's what you have already\.  If you want to have space\-sensitive
globbing\, then you use

&nbsp;    use File&#8203;::Glob '&#8203;:glob';

But that's just that package\.  You can't use '&#8203;:globally'
to do a 

&nbsp;    \*CORE&#8203;::GLOBAL&#8203;::glob = \\&File&#8203;::Glob&#8203;::glob;

So you have to do it yourself\, which feels sleasy\.  Here's the demo\.
You can't get qw/&#8203;:glob :globally/ or or qw/&#8203;:globally :glob/ to do
what you need done\.  \(Yeah\, I know\, CORE&#8203;::GLOBAL is "evil"\.\)

&nbsp;    \#\!/bin/sh \-x
&nbsp;    rm \-rf /tmp/fred "/tmp/fred stuff"
&nbsp;    mkdir "/tmp/fred stuff"
&nbsp;    touch "/tmp/fred stuff/a"
&nbsp;    touch "/tmp/fred stuff/b"
&nbsp;    perl \-We '
&nbsp;    use File&#8203;::Glob qw/&#8203;:glob :globally/;
&nbsp;    \#use File&#8203;::Glob qw/&#8203;:globally :glob/;
&nbsp;    \# BEGIN \{ \*CORE&#8203;::GLOBAL&#8203;::glob = \\&File&#8203;::Glob&#8203;::glob \};
&nbsp;    package bad;
&nbsp;    @&#8203;a = \</tmp/fred stu\*>;
&nbsp;    print "File Glob globbed @&#8203;a\\n"
&nbsp;    ';

I think I prefer "&#8203;:everywhere"  to "&#8203;:globally"\.  It's far far too
close to "&#8203;:glob"\, and means something completely different\.

It would also be nice to get at File&#8203;::Glob&#8203;::glob without overriding the
built\-in\.  But then you don't get the flags and such you need\.  Too
bad it's not "POSIX&#8203;::glob" \-\- less typing\.

I think you should be able to say whether 

&nbsp;    This package uses POSIX glob for the Perl fileglob operator\.
&nbsp;    This package uses csh   glob for the Perl fileglob operator\.
&nbsp;    All packages use  POSIX glob for the Perl fileglob operator\.
&nbsp;    All packages use  csh   glob for the Perl fileglob operator\.

\+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\+
| 3\.  Incompatible breakage  |
\+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\+

&nbsp;    % perl5\.004 \-le 'print glob\("\*\.\[^x\]"\)'

That gets all the files that end in a dot followed by anything not
an x\.  But it is silently broken now&#8203;:

&nbsp;    % perl \-le 'print glob\("\*\.\[^x\]"\)'

Because of this \*\.\[\!x\] thing\.  And there's no way to get back
what it used to do\.

\+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\+
| 4\. Missing docs |
\+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\+

I notice in passing that csh\_glob is not documented\.  And when it is\,
the space bug should be explained\.  Also\, this $^O oddity isn't
explained\, either\.  Iff you call glob with only one argument\, then
iff you're on a case\-screwed system \(happy unicode\, mate\!\)\, then 
you get the default weirdness\.

All of these things need doc'ing\, including the various breakages\.
What you import to get what to happen is highly unclear\.  It could
really use some work\.

\-\-tom

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Here's more\.

&nbsp;    % touch foo\.x foo\.X

&nbsp;    % perl \-le 'use File&#8203;::Glob qw/&#8203;:nocase glob/; print join\(" "\, glob\("\*\.x"\)\)'
&nbsp;    foo\.x

&nbsp;    % perl \-le 'use File&#8203;::Glob qw/&#8203;:nocase glob/; print join\(" "\, &glob\("\*\.x"\)\)'
&nbsp;    foo\.x foo\.X

It is hard to see how that is an expected feature\.


&nbsp;    % perl \-le 'use File&#8203;::Glob qw/&#8203;:nocase :globally/; print join\(" "\, glob\("\*\.x"\)\)'
&nbsp;    foo\.x foo\.X

&nbsp;    % perl \-le 'use File&#8203;::Glob qw/&#8203;:nocase :globally glob/; print join\(" "\, glob\("\*\.x"\)\)'
&nbsp;    foo\.x 

&nbsp;    % perl \-le '\{package XXX; use File&#8203;::Glob qw/&#8203;:nocase :globally/\} print join\(" "\, glob\("\*\.x"\)\)'
&nbsp;    foo\.x foo\.X

\-\-tom

**Comment by p5pRT** [comment]
### From @smpeters

This is an old bug\, but much of it appears to be fixed\.  My comments are
interspersed within what's below\.

> \[tchrist@&#8203;chthon\.perl\.com \- Fri Mar 24 09&#8203;:13&#8203;:34 2000\]&#8203;:
> 
> Summary&#8203;:
> 
>     1\.  Prototype change breaks documented examples\.
>     2\.  :globally problems
>     3\.  Incompatible breakage
>     4\.  Missing docs
> 
> \+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\+
> | 1\.  Prototype change breaks documented examples\. |
> \+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\+
> 
> I seem to recall that this is my own fault&#8203;:
> 
> \[  5163\] By&#8203;: gsar                                  on 2000/02/20
> 16&#8203;:34&#8203;:33
>         Log&#8203;: glob\(\) takes one or no user arguments and a non\-user\-
> visible second
>              hidden argument\, fix its prototype\-checking accordingly
>      Branch&#8203;: perl
> 
> That made this&#8203;:
> 
>     glob            glob                    ck\_glob         t@&#8203;      S?
> S?
> become this
>     glob            glob                    ck\_glob         t@&#8203;      S?
> 
> And that breaks this&#8203;:
> 
>      use File&#8203;::Glob '&#8203;:glob';
>      @&#8203;list = glob\('\*\.\[ch\]'\);
>      $homedir = glob\('~gnat'\, GLOB\_TILDE | GLOB\_ERR\);
>      if \(GLOB\_ERROR\) \{
>          print "can't glob ~gnat&#8203;: $\!\\n";
>      \} else \{
>       print "Gnat lives in $homedir\\n";
>      \}
> 
> Which used to say
> 
>     Gnat lives in /home/gnat
> 
> But now says
> 
>     Too many arguments for glob at \- line 3\, near "GLOB\_ERR\)"
> 
> So even though you import it\, and even though it goes into \<\*>
> fileglobs\,
> you have to say this&#8203;:
> 
>      use File&#8203;::Glob '&#8203;:glob';
>      @&#8203;list = glob\('\*\.\[ch\]'\);
>      $homedir = &glob\('~gnat'\, GLOB\_TILDE | GLOB\_ERR\);
>      if \(GLOB\_ERROR\) \{
>          print "can't glob ~gnat&#8203;: $\!\\n";
>      \} else \{
>       print "Gnat lives in $homedir\\n";
>      \}
> 
> Yes\, you have to use &glob to give another argument\.
> 
> I don't know a perfect solution here\, but right now\, there's
> a problem\.  Well\, yes\, I do know a perfect solution&#8203;: if one
> could \(effectively\) frob the opcode\.pl output so that
> 
>     \*CORE&#8203;::GLOBAL&#8203;::glob = \\&File&#8203;::Glob&#8203;::csh\_glob;
> 
> would make the parser tolerate 0 or 1 arguments\, but with
> 
>     \*CORE&#8203;::GLOBAL&#8203;::glob = \\&File&#8203;::Glob&#8203;::glob;
> 
> it would tolerate 0\, 1\, or 2 arguments\.

Magic seems to have been performed somewhere within the bowels\.  With
Perl\-5\.8\.6\, I get\.\.\.

> perl rt\_2707\_part1\.pl
Steve lives in /home/steve
 
> \+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\+
> | 2\.  :globally problems |
> \+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\+
> 
> There are other problems with this module\.  The import
> 
>      use File&#8203;::Glob '&#8203;:globally';
> 
> is a silent no\-op on systems compiled with \-DPERL\_EXTERNAL\_GLOB\.
> That's because all it does is
> 
>     \*CORE&#8203;::GLOBAL&#8203;::glob = \\&File&#8203;::Glob&#8203;::csh\_glob;
> 
> but that's what you have already\.  If you want to have space\-sensitive
> globbing\, then you use
> 
>     use File&#8203;::Glob '&#8203;:glob';
> 
> But that's just that package\.  You can't use '&#8203;:globally'
> to do a
> 
>     \*CORE&#8203;::GLOBAL&#8203;::glob = \\&File&#8203;::Glob&#8203;::glob;
> 
> So you have to do it yourself\, which feels sleasy\.  Here's the demo\.
> You can't get qw/&#8203;:glob :globally/ or or qw/&#8203;:globally :glob/ to do
> what you need done\.  \(Yeah\, I know\, CORE&#8203;::GLOBAL is "evil"\.\)
> 
>     \#\!/bin/sh \-x
>     rm \-rf /tmp/fred "/tmp/fred stuff"
>     mkdir "/tmp/fred stuff"
>     touch "/tmp/fred stuff/a"
>     touch "/tmp/fred stuff/b"
>     perl \-We '
>     use File&#8203;::Glob qw/&#8203;:glob :globally/;
>     \#use File&#8203;::Glob qw/&#8203;:globally :glob/;
>     \# BEGIN \{ \*CORE&#8203;::GLOBAL&#8203;::glob = \\&File&#8203;::Glob&#8203;::glob \};
>     package bad;
>     @&#8203;a = \</tmp/fred stu\*>;
>     print "File Glob globbed @&#8203;a\\n"
>     ';
> 
> I think I prefer "&#8203;:everywhere"  to "&#8203;:globally"\.  It's far far too
> close to "&#8203;:glob"\, and means something completely different\.
> 
> It would also be nice to get at File&#8203;::Glob&#8203;::glob without overriding
> the
> built\-in\.  But then you don't get the flags and such you need\.  Too
> bad it's not "POSIX&#8203;::glob" \-\- less typing\.
> 
> I think you should be able to say whether
> 
>     This package uses POSIX glob for the Perl fileglob operator\.
>     This package uses csh   glob for the Perl fileglob operator\.
>     All packages use  POSIX glob for the Perl fileglob operator\.
>     All packages use  csh   glob for the Perl fileglob operator\.
>

File&#8203;::Glob and its funkiness has been embedded within Perl long enough
like this that changing it would break backwards compatibility\.  Maybe
one solution would be to implement a pragma or hint to clean it up\.  So\, 

&nbsp;  use glob 'POSIX'; \# Explicitly take the POSIX behavior\, or
&nbsp;  use glob 'csh';   \# Explicitly take the csh behavior

For the global usage \(although I personally believe this could break
things\)\.\.\.

&nbsp;  use glob qw\(POSIX everywhere\); \# Explicitly take the POSIX behavior
globally\, or
&nbsp;  use glob qw\(csh everywhere\);   \# Explicitly take the csh behavior globally

This is mostly an incomplete thought\, but I'd be happy to listen to
suggestions\, criticisms\, complaints\, etc\.  But\, this looks like even
less typing :\)  

> \+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\+
> | 3\.  Incompatible breakage  |
> \+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\+
> 
>     % perl5\.004 \-le 'print glob\("\*\.\[^x\]"\)'
> 
> That gets all the files that end in a dot followed by anything not
> an x\.  But it is silently broken now&#8203;:
> 
>     % perl \-le 'print glob\("\*\.\[^x\]"\)'
> 
> Because of this \*\.\[\!x\] thing\.  And there's no way to get back
> what it used to do\.
> 
That's due to a POSIX change \(see
http&#8203;://www\.opengroup\.org/onlinepubs/009695399/utilities/xcu\_chap02\.html\#tag\_02\_13\_01\)
for an explanation\.\)  Maybe we could support both to do the same\, but
since its been this way now for five years\, do we need too? 

> \+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\+
> | 4\. Missing docs |
> \+\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\+
> 
> I notice in passing that csh\_glob is not documented\.  And when it is\,
> the space bug should be explained\.  Also\, this $^O oddity isn't
> explained\, either\.  Iff you call glob with only one argument\, then
> iff you're on a case\-screwed system \(happy unicode\, mate\!\)\, then
> you get the default weirdness\.
> 
> All of these things need doc'ing\, including the various breakages\.
> What you import to get what to happen is highly unclear\.  It could
> really use some work\.

The current description contains the following\. 

"The glob angle\-bracket operator \<> is a pathname generator that
implements the rules for file name pattern matching used by Unix\-like
shells such as the Bourne shell or C shell\.

File&#8203;::Glob&#8203;::bsd\_glob\(\) implements the FreeBSD glob\(3\) routine\, which is
a superset of the POSIX glob\(\) \(described in IEEE Std 1003\.2 "POSIX\.2"\)\.
bsd\_glob\(\) takes a mandatory pattern argument\, and an optional flags
argument\, and returns a list of filenames matching the pattern\, with
interpretation of the pattern modified by the flags variable\.

Since v5\.6\.0\, Perl's CORE&#8203;::glob\(\) is implemented in terms of bsd\_glob\(\)\.
Note that they don't share the same prototype\-\-CORE&#8203;::glob\(\) only accepts
a single argument\. Due to historical reasons\, CORE&#8203;::glob\(\) will also
split its argument on whitespace\, treating it as multiple patterns\,
whereas bsd\_glob\(\) considers them as one pattern\."

As far as documenting csh\_glob\, its documented internally with the
following comment\.  

&nbsp;    "csh\_glob\(\) should not be used directly\, unless you know what you're
doing\."

I'm not sure why this is\, but this makes it difficult for me to suggest
documenting it\.  There is also a note that a nice thing to do would be
to create a flag to avoid the default space handling behavior \(reading
this\, though\, is giving me what I need to close another more bug\)\.  That
will take a bit of thought on how best to implement it \(a hint\, perhaps?
 Sorry I wrote this before what I wrote above\, but it could be a
separate tweak all on its own\)\.  Overall\, I think I'll take a deeper
look into the docs to see if more clarity is needed\.  Perhaps\, a quick
example in the synopsis would help\. 

The problems encountered by Mac OS Classic users has been documented\, as
well as issues for Win32 users\.  Mac OS X is also case\-insensative\.  A
small note that essentially says "we do what your libc glob wants us to
do" would probably be nice\.

Overall\, though\, things seem better than the world of File&#8203;::Glob at the
time you opened this ticket\, but I agree that some things still need to
be looked into further\.

**Comment by tonycoz** [comment]
the glob() operator has been 0-1 argument for over 24 years now, and has been documented to take 0 or 1 arguments since at least 5.005. 

The glob export was deprecated in 5.008 (see a0e213fcb5a), started producing deprecation warnings in 5.26, and was removed in 5.30.

Nothing left here is still relevant.

Closing.
