### ISSUE TITLE
$File::Spec::AmigaOS::VERSION is broken (and breaks Module::CoreList)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15246]
Migrated from [rt.perl.org#127765](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=127765) (status was 'open')

Searchable as RT127765$

**Comment by p5pRT** [comment]
### From @eserte

In File/Spec/AmigaOS\.pm I see&#8203;:

&nbsp;    $VERSION = ';\.64';

Consequently\, Module&#8203;::CoreList 5\.20160320 also contains a broken line

The \{5\.023009\}\->\{changed\} entry contains&#8203;:

&nbsp;    'File&#8203;::Spec&#8203;::AmigaOS'   => ';\.64'\,

See also https://rt.cpan.org/Ticket/Display.html?id=113253

Regards\,
&nbsp;    Slaven

**Comment by p5pRT** [comment]
### From @ilmari

slaven@&#8203;rezic\.de \(via RT\) \<perlbug\-followup@&#8203;perl\.org> writes&#8203;:

> In File/Spec/AmigaOS\.pm I see&#8203;:
>
>     $VERSION = ';\.64';

Fixed with commit b10f34abb55ae2504baa9b770b3bff979de781c2
&nbsp;    
Interestingly\, ';' is a single bitflip away from '3'\, which must have
happened on khw's machine before he committed e46aa1dd\, since the SHA\-1
hashes are all consistent\.

> Consequently\, Module&#8203;::CoreList 5\.20160320 also contains a broken line
>
> The \{5\.023009\}\->\{changed\} entry contains&#8203;:
>
>     'File&#8203;::Spec&#8203;::AmigaOS'   => ';\.64'\,

I did not touch Module&#8203;::CoreList\, I'll leave that to BinGOs\.

\-\- 
"A disappointingly low fraction of the human race is\,
 at any given time\, on fire\." \- Stig Sandbeck Mathisen

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by thibaultduponchelle** [comment]
I think it is fixed by the commit mentioned above ? 
And I just checked right now and it seems ok : https://github.com/Perl/perl5/blob/blead/dist/PathTools/lib/File/Spec/AmigaOS.pm#L6

**Comment by jkeenan** [comment]
> I think it is fixed by the commit mentioned above ?
> And I just checked right now and it seems ok : https://github.com/Perl/perl5/blob/blead/dist/PathTools/lib/File/Spec/AmigaOS.pm#L6

Confirmed; problem was fixed 5 years ago.  Closing ticket.
