### ISSUE TITLE
ERROR : Can't locate object method "match" via package "DateTime::Event::Cron" at /home/zenoss/check_activemq.pl line 96.

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15415]
Migrated from [rt.perl.org#128521](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=128521) (status was 'open')

Searchable as RT128521$

**Comment by p5pRT** [comment]
### From abhishek.chordia@homeshop18.com

Hi Team\,

I am trying to use attached script from to different servers\, one is runng with perl version v5\.8\.8 and second is running with v5\.10\.1\.

I getting below error with version v5\.10\.1 :

Can't locate object method "match" via package "DateTime&#8203;::Event&#8203;::Cron" at /home/zenoss/check\_activemq\.pl line 96\.


Can you please help me on this\.

Regards
Abhishek

**Comment by p5pRT** [comment]
### From abhishek.chordia@homeshop18.com

[check_activemq.pl](https://rt-archive.perl.org/perl5/Ticket/Attachment/1407014/759693/check_activemq.pl)

**Comment by p5pRT** [comment]
### From @cpansprout

On Sat Jul 02 10&#8203;:14&#8203;:35 2016\, abhishek\.chordia@&#8203;homeshop18\.com wrote&#8203;:
> Hi Team\,
> 
> I am trying to use attached script from to different servers\, one is
> runng with perl version v5\.8\.8 and second is running with v5\.10\.1\.
> 
> I getting below error with version v5\.10\.1 :
> 
> Can't locate object method "match" via package "DateTime&#8203;::Event&#8203;::Cron"
> at /home/zenoss/check\_activemq\.pl line 96\.
> 
> 
> Can you please help me on this\.

perlbug is not the correct place to ask such questions\.  It is for reporting bugs in the perl interpreter and modules that come with it\.

Nevertheless\, I think I see your problem\.  DateTime&#8203;::Event&#8203;::Cron did not get a \->match method until version 0\.08 \(see \<http&#8203;://cpansearch\.perl\.org/src/MSISK/DateTime\-Event\-Cron\-0\.08/Changes>\)\.  I suspect you have an older version of DateTime&#8203;::Event&#8203;::Cron in your 5\.10\.1 installation\.


\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by xenu** [comment]
`DateTime::Event::Cron` is a CPAN module and the correct place to report problems with it is [its RT queue](https://rt.cpan.org/Public/Dist/Display.html?Name=DateTime-Event-Cron).
