### ISSUE TITLE
modfl() is horribly broken in MinGW-W64 

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15463]
Migrated from [rt.perl.org#128673](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=128673) (status was 'open')

Searchable as RT128673$

**Comment by p5pRT** [comment]
### From @dcollinsn

Hello

Found another one\. In builds of blead using the MinGW\-W64 toolchain for x86\_64\, with long doubles enabled\, calls to modfl\(\) will segfault the perl interpreter\. This is not a perlbug\, the below C test crashes \(segfaults\) in the call to modfl\(\)&#8203;:

\-\-\- modftest\.c

\#include \<tgmath\.h>
\#include \<stdio\.h>

int main\(\) \{
&nbsp;  long double a\, b\, c;
&nbsp;  a = 1\.76;
&nbsp;  \_\_mingw\_printf\("About to call modfl\(1\.76\, &b\)\\n"\);
&nbsp;  c = modfl\(a\, &b\);
&nbsp;  \_\_mingw\_printf\("Alive\. b = %Le\, c = %Le\\n"\, b\, c\);
&nbsp;  return 0;
\}

\_\_END\_\_

However\, as a result\, ext\\POSIX\\t\\math\.t \*crashes\* after test 28&#8203;:

\.\./ext/POSIX/t/math\.t                                            \(Wstat&#8203;: 65280 Tests&#8203;: 28 Failed&#8203;: 0\)
&nbsp;  Non\-zero exit status&#8203;: 255
&nbsp;  Parse errors&#8203;: No plan found in TAP output

This has been open upstream for about a year\. There is a patch in the upstream ticket\, which I have bumped\. You can find the ticket here&#8203;:

https://sourceforge.net/p/mingw-w64/bugs/478/

versions\, for fun&#8203;:

W&#8203;:\\buildbot\\windows1\\win64\-mingww64\-4\_9\_3\-ld\\build>gcc \-v
Using built\-in specs\.
COLLECT\_GCC=gcc
COLLECT\_LTO\_WRAPPER=C&#8203;:/mingw\-w64/x86\_64\-4\.9\.3/mingw64/bin/\.\./libexec/gcc/x86\_64\-w64\-mingw32/4\.9\.3/lto\-wrapper\.exe
Target&#8203;: x86\_64\-w64\-mingw32
Configured with&#8203;: \.\./\.\./\.\./src/gcc\-4\.9\.3/configure \-\-host=x86\_64\-w64\-mingw32 \-\-build=x86\_64\-w64\-mingw32 \-\-target=x86\_64\-w64\-mingw32 \-\-prefix=/mingw64 \-\-with\-sysroot=/c/mingw493/x86\_64\-493\-posix\-seh\-rt\_v4\-rev1/mingw64 \-\-with\-gxx\-include\-dir=/mingw64/x86\_64\-w64\-mingw32/include/c\+\+ \-\-enable\-shared \-\-enable\-static \-\-disable\-multilib \-\-enable\-languages=c\,c\+\+\,fortran\,objc\,obj\-c\+\+\,lto \-\-enable\-libstdcxx\-time=yes \-\-enable\-threads=posix \-\-enable\-libgomp \-\-enable\-libatomic \-\-enable\-lto \-\-enable\-graphite \-\-enable\-checking=release \-\-enable\-fully\-dynamic\-string \-\-enable\-version\-specific\-runtime\-libs \-\-disable\-isl\-version\-check \-\-disable\-cloog\-version\-check \-\-disable\-libstdcxx\-pch \-\-disable\-libstdcxx\-debug \-\-enable\-bootstrap \-\-disable\-rpath \-\-disable\-win32\-registry \-\-disable\-nls \-\-disable\-werror \-\-disable\-symvers \-\-with\-gnu\-as \-\-with\-gnu\-ld \-\-with\-arch=nocona \-\-with\-tune=core2 \-\-with\-libiconv \-\-with\-system\-zlib \-\-with\-gmp=/c/mingw493/prerequisites/x86\_64\-w64\-mingw32\-static \-\-with\-mpfr=/c/mingw493/prerequisites/x86\_64\-w64\-mingw32\-static \-\-with\-mpc=/c/mingw493/prerequisites/x86\_64\-w64\-mingw32\-static \-\-with\-isl=/c/mingw493/prerequisites/x86\_64\-w64\-mingw32\-static \-\-with\-cloog=/c/mingw493/prerequisites/x86\_64\-w64\-mingw32\-static \-\-enable\-cloog\-backend=isl \-\-with\-pkgversion='x86\_64\-posix\-seh\-rev1\, Built by MinGW\-W64 project' \-\-with\-bugurl=http&#8203;://sourceforge\.net/projects/mingw\-w64 CFLAGS='\-O2 \-pipe \-I/c/mingw493/x86\_64\-493\-posix\-seh\-rt\_v4\-rev1/mingw64/opt/include \-I/c/mingw493/prerequisites/x86\_64\-zlib\-static/include \-I/c/mingw493/prerequisites/x86\_64\-w64\-mingw32\-static/include' CXXFLAGS='\-O2 \-pipe \-I/c/mingw493/x86\_64\-493\-posix\-seh\-rt\_v4\-rev1/mingw64/opt/include \-I/c/mingw493/prerequisites/x86\_64\-zlib\-static/include \-I/c/mingw493/prerequisites/x86\_64\-w64\-mingw32\-static/include' CPPFLAGS= LDFLAGS='\-pipe \-L/c/mingw493/x86\_64\-493\-posix\-seh\-rt\_v4\-rev1/mingw64/opt/lib \-L/c/mingw493/prerequisites/x86\_64\-zlib\-static/lib \-L/c/mingw493/prerequisites/x86\_64\-w64\-mingw32\-static/lib '
Thread model&#8203;: posix
gcc version 4\.9\.3 \(x86\_64\-posix\-seh\-rev1\, Built by MinGW\-W64 project\)

Summary of my perl5 \(revision 5 version 25 subversion 3\) configuration&#8203;:

&nbsp;  Platform&#8203;:
&nbsp;    osname=MSWin32
&nbsp;    osvers=10\.0
&nbsp;    archname=MSWin32\-x64\-multi\-thread\-ld
&nbsp;    uname=''
&nbsp;    config\_args='undef'
&nbsp;    hint=recommended
&nbsp;    useposix=true
&nbsp;    d\_sigaction=undef
&nbsp;    useithreads=define
&nbsp;    usemultiplicity=define
&nbsp;    use64bitint=define
&nbsp;    use64bitall=undef
&nbsp;    uselongdouble=define
&nbsp;    usemymalloc=n
&nbsp;    bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc'
&nbsp;    ccflags =' \-s \-O2 \-DWIN32 \-DWIN64 \-DCONSERVATIVE  \-DPERL\_TEXTMODE\_SCRIPTS \-DPERL\_IMPLICIT\_CONTEXT \-DPERL\_IMPLICIT\_SYS \-D\_\_USE\_MINGW\_ANSI\_STDIO \-fwrapv \-fno\-strict\-aliasing \-mms\-bitfields'
&nbsp;    optimize='\-s \-O2'
&nbsp;    cppflags='\-DWIN32'
&nbsp;    ccversion=''
&nbsp;    gccversion='4\.9\.3'
&nbsp;    gccosandvers=''
&nbsp;    intsize=4
&nbsp;    longsize=4
&nbsp;    ptrsize=8
&nbsp;    doublesize=8
&nbsp;    byteorder=12345678
&nbsp;    doublekind=3
&nbsp;    d\_longlong=define
&nbsp;    longlongsize=8
&nbsp;    d\_longdbl=define
&nbsp;    longdblsize=16
&nbsp;    longdblkind=3
&nbsp;    ivtype='long long'
&nbsp;    ivsize=8
&nbsp;    nvtype='long double'
&nbsp;    nvsize=16
&nbsp;    Off\_t='long long'
&nbsp;    lseeksize=8
&nbsp;    alignbytes=8
&nbsp;    prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='g\+\+'
&nbsp;    ldflags ='\-s \-L"c&#8203;:\\perl\\lib\\CORE" \-L"C&#8203;:\\mingw\-w64\\x86\_64\-4\.9\.3\\mingw64\\lib"'
&nbsp;    libpth=C&#8203;:\\mingw\-w64\\x86\_64\-4\.9\.3\\mingw64\\lib
&nbsp;    libs=\-lmoldname \-lkernel32 \-luser32 \-lgdi32 \-lwinspool \-lcomdlg32 \-ladvapi32 \-lshell32 \-lole32 \-loleaut32 \-lnetapi32 \-luuid \-lws2\_32 \-lmpr \-lwinmm \-lversion \-lodbc32 \-lodbccp32 \-lcomctl32
&nbsp;    perllibs=\-lmoldname \-lkernel32 \-luser32 \-lgdi32 \-lwinspool \-lcomdlg32 \-ladvapi32 \-lshell32 \-lole32 \-loleaut32 \-lnetapi32 \-luuid \-lws2\_32 \-lmpr \-lwinmm \-lversion \-lodbc32 \-lodbccp32 \-lcomctl32
&nbsp;    libc=
&nbsp;    so=dll
&nbsp;    useshrplib=true
&nbsp;    libperl=libperl525\.a
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_win32\.xs
&nbsp;    dlext=dll
&nbsp;    d\_dlsymun=undef
&nbsp;    ccdlflags=' '
&nbsp;    cccdlflags=' '
&nbsp;    lddlflags='\-mdll \-s \-L"c&#8203;:\\perl\\lib\\CORE" \-L"C&#8203;:\\mingw\-w64\\x86\_64\-4\.9\.3\\mingw64\\lib"'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;:
&nbsp;    HAS\_TIMES
&nbsp;    HAVE\_INTERP\_INTERN
&nbsp;    MULTIPLICITY
&nbsp;    PERLIO\_LAYERS
&nbsp;    PERL\_COPY\_ON\_WRITE
&nbsp;    PERL\_DONT\_CREATE\_GVSV
&nbsp;    PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD
&nbsp;    PERL\_IMPLICIT\_CONTEXT
&nbsp;    PERL\_IMPLICIT\_SYS
&nbsp;    PERL\_MALLOC\_WRAP
&nbsp;    PERL\_OP\_PARENT
&nbsp;    PERL\_PRESERVE\_IVUV
&nbsp;    USE\_64\_BIT\_INT
&nbsp;    USE\_ITHREADS
&nbsp;    USE\_LARGE\_FILES
&nbsp;    USE\_LOCALE
&nbsp;    USE\_LOCALE\_COLLATE
&nbsp;    USE\_LOCALE\_CTYPE
&nbsp;    USE\_LOCALE\_NUMERIC
&nbsp;    USE\_LOCALE\_TIME
&nbsp;    USE\_LONG\_DOUBLE
&nbsp;    USE\_PERLIO
&nbsp;    USE\_PERL\_ATOF
&nbsp;  Built under MSWin32
&nbsp;  Compiled at Jul 19 2016 16&#8203;:34&#8203;:24
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    W&#8203;:/buildbot/windows1/win64\-mingww64\-4\_9\_3\-ld/build/lib
&nbsp;    \.


\-\- 
Respectfully\,
Dan Collins

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue Jul 19 14&#8203;:20&#8203;:33 2016\, dcollinsn@&#8203;gmail\.com wrote&#8203;:
> Hello
> 
> Found another one\. In builds of blead using the MinGW\-W64 toolchain
> for x86\_64\, with long doubles enabled\, calls to modfl\(\) will segfault
> the perl interpreter\. This is not a perlbug\, the below C test crashes
> \(segfaults\) in the call to modfl\(\)&#8203;:

This came up in #14865 and resulted in #14876.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by toddr** [comment]
@tonycoz are you saying this is resolved?

**Comment by tonycoz** [comment]
It's fixed upstream in https://sourceforge.net/p/mingw-w64/mingw-w64/ci/9a2479858b3bb7df36a09c4472fa1adca7e84f19/

Closing.
