### ISSUE TITLE
[PATCH] Time::HiRes broken in blead on darwin

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15641]
Migrated from [rt.perl.org#129789](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=129789) (status was 'open')

Searchable as RT129789$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



Commit 1c5665476f0d7250c7d93f82eab2b7cda1e6937f broke Time&#8203;::HiRes on
darwin\, patch attached\.

<details><summary>Perl Info</summary>

```

Flags:
    category=library
    severity=low
    module=Time::HiRes

Site configuration information for perl 5.25.6:

Configured by dur-randir at Sun Oct  2 23:51:57 MSK 2016.

Summary of my perl5 (revision 5 version 25 subversion 6) configuration:
  Derived from: 1c5665476f0d7250c7d93f82eab2b7cda1e6937f
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0:
mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64
x86_64 '
    config_args='-de -Dusedevel'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include
-DPERL_USE_SAFE_PUTENV'
    optimize='-O3'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9
-fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib'
    libpth=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/lib
/usr/local/lib /usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector'

Locally applied patches:
    uncommitted-changes


@INC for perl 5.25.6:
    lib
    /usr/local/lib/perl5/site_perl/5.25.6/darwin-2level
    /usr/local/lib/perl5/site_perl/5.25.6
    /usr/local/lib/perl5/5.25.6/darwin-2level
    /usr/local/lib/perl5/5.25.6


Environment for perl 5.25.6:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin
    PERLBREW_BASHRC_VERSION=0.69
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.22.1/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.22.1/bin
    PERLBREW_PERL=perl-5.22.1
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_VERSION=0.69
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @dur-randir

<details><summary>0001-Time-HiRes-fix-compilation-on-darwin.patch</summary>

```diff
From d837a12f49f64a9e671e8e22c2821116c4d70b60 Mon Sep 17 00:00:00 2001
From: Sergey Aleynikov <sergey.aleynikov@gmail.com>
Date: Mon, 3 Oct 2016 00:21:40 +0300
Subject: [PATCH] Time::HiRes: fix compilation on darwin

Commit 1c5665476f0d7250c7d93f82eab2b7cda1e6937f added explicit cast
for one of the clock_gettime() arguments, but darwin lacks clockid_t,
so update emulation layer to match function prototype too.
---
 dist/Time-HiRes/HiRes.xs | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/dist/Time-HiRes/HiRes.xs b/dist/Time-HiRes/HiRes.xs
index 1b9ee23..e7d26f1 100644
--- a/dist/Time-HiRes/HiRes.xs
+++ b/dist/Time-HiRes/HiRes.xs
@@ -803,7 +803,9 @@ static int darwin_time_init() {
 }
 
 #ifdef TIME_HIRES_CLOCK_GETTIME_EMULATION
-static int clock_gettime(int clock_id, struct timespec *ts) {
+typedef int clockid_t;
+
+static int clock_gettime(clockid_t clock_id, struct timespec *ts) {
   if (darwin_time_init() && timebase_info.denom) {
     switch (clock_id) {
       case CLOCK_REALTIME:
-- 
2.10.0


```
</details>

**Comment by p5pRT** [comment]
### From @jkeenan

On Sun Oct 02 14&#8203;:32&#8203;:10 2016\, randir wrote&#8203;:
> This is a bug report for perl from sergey\.aleynikov@&#8203;gmail\.com\,
> generated with the help of perlbug 1\.40 running under perl 5\.25\.6\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please describe your issue here\]
> 
> Commit 1c5665476f0d7250c7d93f82eab2b7cda1e6937f broke Time&#8203;::HiRes on
> darwin\, patch attached\.
> 

Making this available for smoke\-testing in branch&#8203;:
smoke\-me/jkeenan/aleynikov/129789\-darwin\-time\-hires

Thank you very much\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @jkeenan

On Sun Oct 02 14&#8203;:32&#8203;:10 2016\, randir wrote&#8203;:
> This is a bug report for perl from sergey\.aleynikov@&#8203;gmail\.com\,
> generated with the help of perlbug 1\.40 running under perl 5\.25\.6\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please describe your issue here\]
> 
> Commit 1c5665476f0d7250c7d93f82eab2b7cda1e6937f broke Time&#8203;::HiRes on
> darwin\, patch attached\.
> 

For reference\, I am attaching the 'make' failure output I got when I attempted to compile on an older Darwin system\.

The patch \(as run in the smoke branch\) appears to do no harm on my regular Linux and FreeBSD builds and appears to resolve the build failures on Darwin/PPC and permit 'make test\_harness' to complete successfully\.

However\, because the revisions to HiRes\.xs proposed in the aptch are not scoped to apply only to Darwin\, we should get more testing of\, and focus on\, the patch before applying\.

Thank you very much\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @jkeenan

Failure to build Time\-HiRes at 1c5665476f0d7250c7d93f82eab2b7cda1e6937f on
Darwin Macintosh\-9\.local 8\.11\.0 Darwin Kernel Version 8\.11\.0&#8203;: Wed Oct 10 18&#8203;:26&#8203;:00 PDT 2007;
root&#8203;:xnu\-792\.24\.17~1/RELEASE\_PPC Power Macintosh powerpc

Configuration&#8203;: sh \./Configure \-des \-Dusedevel

\./miniperl \-Ilib make\_ext\.pl lib/auto/Time/HiRes/HiRes\.bundle  MAKE="make" LIBPERL\_A=libperl\.a LINKTYPE=dynamic
/Users/jimk/gitwork/perl/dist/Time\-HiRes/\.\./\.\./miniperl "\-I\.\./\.\./lib" \-MExtUtils&#8203;::Command&#8203;::MM \-e 'cp\_nonempty' \-\- HiRes\.bs \.\./\.\./lib/auto/Time/HiRes/HiRes\.bs 644
cc \-c   \-fno\-common \-DPERL\_DARWIN \-fno\-strict\-aliasing \-pipe \-I/usr/local/include \-I/opt/local/include \-D\_FORTIFY\_SOURCE=2 \-DPERL\_USE\_SAFE\_PUTENV \-Wall \-Wextra \-Wwrite\-strings \-O3   \-DVERSION=\\"1\.9740\_01\\" \-DXS\_VERSION=\\"1\.9740\_01\\"  "\-I\.\./\.\."  \-DTIME\_HIRES\_NANOSLEEP \-DTIME\_HIRES\_CLOCK\_GETTIME \-DTIME\_HIRES\_CLOCK\_GETTIME\_EMULATION \-DTIME\_HIRES\_CLOCK\_GETRES \-DTIME\_HIRES\_CLOCK\_GETRES\_EMULATION \-DTIME\_HIRES\_CLOCK\_NANOSLEEP \-DTIME\_HIRES\_CLOCK\_NANOSLEEP\_EMULATION \-DTIME\_HIRES\_CLOCK \-DTIME\_HIRES\_STAT\_ST\_XTIMESPEC \-DTIME\_HIRES\_STAT=1 \-DATLEASTFIVEOHOHFIVE HiRes\.c
HiRes\.xs&#8203;: In function 'XS\_Time\_\_HiRes\_clock\_gettime'&#8203;:
HiRes\.xs&#8203;:1442&#8203;: error&#8203;: 'clockid\_t' undeclared \(first use in this function\)
HiRes\.xs&#8203;:1442&#8203;: error&#8203;: \(Each undeclared identifier is reported only once
HiRes\.xs&#8203;:1442&#8203;: error&#8203;: for each function it appears in\.\)
HiRes\.xs&#8203;:1442&#8203;: error&#8203;: parse error before 'clock\_id'
HiRes\.xs&#8203;: In function 'XS\_Time\_\_HiRes\_clock\_getres'&#8203;:
HiRes\.xs&#8203;:1475&#8203;: error&#8203;: 'clockid\_t' undeclared \(first use in this function\)
HiRes\.xs&#8203;:1475&#8203;: error&#8203;: parse error before 'clock\_id'
make\[1\]&#8203;: \*\*\* \[HiRes\.o\] Error 1
/Users/jimk/gitwork/perl/dist/Time\-HiRes/\.\./\.\./miniperl "\-I\.\./\.\./lib" \-MExtUtils&#8203;::Command&#8203;::MM \-e 'cp\_nonempty' \-\- HiRes\.bs \.\./\.\./lib/auto/Time/HiRes/HiRes\.bs 644
cc \-c   \-fno\-common \-DPERL\_DARWIN \-fno\-strict\-aliasing \-pipe \-I/usr/local/include \-I/opt/local/include \-D\_FORTIFY\_SOURCE=2 \-DPERL\_USE\_SAFE\_PUTENV \-Wall \-Wextra \-Wwrite\-strings \-O3   \-DVERSION=\\"1\.9740\_01\\" \-DXS\_VERSION=\\"1\.9740\_01\\"  "\-I\.\./\.\."  \-DTIME\_HIRES\_NANOSLEEP \-DTIME\_HIRES\_CLOCK\_GETTIME \-DTIME\_HIRES\_CLOCK\_GETTIME\_EMULATION \-DTIME\_HIRES\_CLOCK\_GETRES \-DTIME\_HIRES\_CLOCK\_GETRES\_EMULATION \-DTIME\_HIRES\_CLOCK\_NANOSLEEP \-DTIME\_HIRES\_CLOCK\_NANOSLEEP\_EMULATION \-DTIME\_HIRES\_CLOCK \-DTIME\_HIRES\_STAT\_ST\_XTIMESPEC \-DTIME\_HIRES\_STAT=1 \-DATLEASTFIVEOHOHFIVE HiRes\.c
HiRes\.xs&#8203;: In function 'XS\_Time\_\_HiRes\_clock\_gettime'&#8203;:
HiRes\.xs&#8203;:1442&#8203;: error&#8203;: 'clockid\_t' undeclared \(first use in this function\)
HiRes\.xs&#8203;:1442&#8203;: error&#8203;: \(Each undeclared identifier is reported only once
HiRes\.xs&#8203;:1442&#8203;: error&#8203;: for each function it appears in\.\)
HiRes\.xs&#8203;:1442&#8203;: error&#8203;: parse error before 'clock\_id'
HiRes\.xs&#8203;: In function 'XS\_Time\_\_HiRes\_clock\_getres'&#8203;:
HiRes\.xs&#8203;:1475&#8203;: error&#8203;: 'clockid\_t' undeclared \(first use in this function\)
HiRes\.xs&#8203;:1475&#8203;: error&#8203;: parse error before 'clock\_id'
make\[1\]&#8203;: \*\*\* \[HiRes\.o\] Error 1
Unsuccessful make\(dist/Time\-HiRes\)&#8203;: code=512 at make\_ext\.pl line 569\.
make&#8203;: \*\*\* \[lib/auto/Time/HiRes/HiRes\.bundle\] Error 2

**Comment by p5pRT** [comment]
### From @ilmari

"James E Keenan via RT" \<perlbug\-followup@&#8203;perl\.org> writes&#8203;:

> On Sun Oct 02 14&#8203;:32&#8203;:10 2016\, randir wrote&#8203;:
>> This is a bug report for perl from sergey\.aleynikov@&#8203;gmail\.com\,
>> generated with the help of perlbug 1\.40 running under perl 5\.25\.6\.
>> 
>> 
>> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
>> \[Please describe your issue here\]
>> 
>> Commit 1c5665476f0d7250c7d93f82eab2b7cda1e6937f broke Time&#8203;::HiRes on
>> darwin\, patch attached\.
>> 
>
> For reference\, I am attaching the 'make' failure output I got when I
> attempted to compile on an older Darwin system\.

That's because the typedef is inside the

&nbsp;    \#ifdef TIME\_HIRES\_CLOCK\_GETTIME\_EMULATION

guard\. It needs to go before it\, so it's visible to all the emulated
functions\.

> However\, because the revisions to HiRes\.xs proposed in the aptch are
> not scoped to apply only to Darwin\, we should get more testing of\, and
> focus on\, the patch before applying\.

They are\, the entire block of code is guarded by the following&#8203;:

&nbsp;    /\* Until Apple implements clock\_gettime\(\)
&nbsp;     \* \(ditto clock\_getres\(\) and clock\_nanosleep\(\)\)
&nbsp;     \* we will emulate them using the Mach kernel interfaces\. \*/
&nbsp;    \#if defined\(PERL\_DARWIN\) && \\
&nbsp;      \(defined\(TIME\_HIRES\_CLOCK\_GETTIME\_EMULATION\)   || \\
&nbsp;       defined\(TIME\_HIRES\_CLOCK\_GETRES\_EMULATION\)    || \\
&nbsp;       defined\(TIME\_HIRES\_CLOCK\_NANOSLEEP\_EMULATION\)\)

On a tangent\, I was wondering if it would make sense to make all the
clock\_id arguments clockid\_t \(and add it to the typemap\)\, instead of the
casts introduced in 1c566547\.

\-\- 
"The surreality of the universe tends towards a maximum" \-\- Skud's Law
"Never formulate a law or axiom that you're not prepared to live with
 the consequences of\."                              \-\- Skud's Meta\-Law

**Comment by p5pRT** [comment]
### From @jkeenan

On Tue Oct 04 05&#8203;:04&#8203;:12 2016\, ilmari wrote&#8203;:
> "James E Keenan via RT" \<perlbug\-followup@&#8203;perl\.org> writes&#8203;:
> 
> > On Sun Oct 02 14&#8203;:32&#8203;:10 2016\, randir wrote&#8203;:
> >> This is a bug report for perl from sergey\.aleynikov@&#8203;gmail\.com\,
> >> generated with the help of perlbug 1\.40 running under perl 5\.25\.6\.
> >> 
> >> 
> >> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> >> \[Please describe your issue here\]
> >> 
> >> Commit 1c5665476f0d7250c7d93f82eab2b7cda1e6937f broke Time&#8203;::HiRes on
> >> darwin\, patch attached\.
> >> 
> >
> > For reference\, I am attaching the 'make' failure output I got when I
> > attempted to compile on an older Darwin system\.
> 
> That's because the typedef is inside the
> 
>     \#ifdef TIME\_HIRES\_CLOCK\_GETTIME\_EMULATION
> 
> guard\. It needs to go before it\, so it's visible to all the emulated
> functions\.
> 
> > However\, because the revisions to HiRes\.xs proposed in the aptch are
> > not scoped to apply only to Darwin\, we should get more testing of\, and
> > focus on\, the patch before applying\.
> 
> They are\, the entire block of code is guarded by the following&#8203;:
> 
>     /\* Until Apple implements clock\_gettime\(\)
>      \* \(ditto clock\_getres\(\) and clock\_nanosleep\(\)\)
>      \* we will emulate them using the Mach kernel interfaces\. \*/
>     \#if defined\(PERL\_DARWIN\) && \\
>       \(defined\(TIME\_HIRES\_CLOCK\_GETTIME\_EMULATION\)   || \\
>        defined\(TIME\_HIRES\_CLOCK\_GETRES\_EMULATION\)    || \\
>        defined\(TIME\_HIRES\_CLOCK\_NANOSLEEP\_EMULATION\)\)
> 
> On a tangent\, I was wondering if it would make sense to make all the
> clock\_id arguments clockid\_t \(and add it to the typemap\)\, instead of the
> casts introduced in 1c566547\.
> 

Could you and Jarkko discuss that\, so we can move this ticket to resolution?

Thank you very much\.
\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @dur-randir

Here's an updated patch \(in case a non\-typemap route is chosen\) that should compile and pass on all darwins and that provides POSIX\-like prototypes for all emulated functions\. I've also noticed that a call to sleep\_nanotime\(\) lacks a cast to clockid\_t for it's argument \- was that intended?

**Comment by p5pRT** [comment]
### From @dur-randir

<details><summary>0001-Time-HiRes-fix-compilation-on-darwin.patch</summary>

```diff
From 06f69371e9a63e53fdf6ca41b1e9a703622be51d Mon Sep 17 00:00:00 2001
From: Sergey Aleynikov <sergey.aleynikov@gmail.com>
Date: Wed, 5 Oct 2016 18:29:34 +0300
Subject: [PATCH] Time::HiRes: fix compilation on darwin

Commit 1c5665476f0d7250c7d93f82eab2b7cda1e6937f added explicit cast
for one of the clock_gettime() arguments, but darwin lacks clockid_t,
so update emulation layer to match function prototype too.
---
 dist/Time-HiRes/HiRes.xs | 8 +++++---
 1 file changed, 5 insertions(+), 3 deletions(-)

diff --git a/dist/Time-HiRes/HiRes.xs b/dist/Time-HiRes/HiRes.xs
index 1b9ee23..de63b93 100644
--- a/dist/Time-HiRes/HiRes.xs
+++ b/dist/Time-HiRes/HiRes.xs
@@ -802,8 +802,10 @@ static int darwin_time_init() {
   return success;
 }
 
+typedef int clockid_t; /* to conform with POSIX prototypes */
+
 #ifdef TIME_HIRES_CLOCK_GETTIME_EMULATION
-static int clock_gettime(int clock_id, struct timespec *ts) {
+static int clock_gettime(clockid_t clock_id, struct timespec *ts) {
   if (darwin_time_init() && timebase_info.denom) {
     switch (clock_id) {
       case CLOCK_REALTIME:
@@ -837,7 +839,7 @@ static int clock_gettime(int clock_id, struct timespec *ts) {
 #endif /* TIME_HIRES_CLOCK_GETTIME_EMULATION */
 
 #ifdef TIME_HIRES_CLOCK_GETRES_EMULATION
-static int clock_getres(int clock_id, struct timespec *ts) {
+static int clock_getres(clockid_t clock_id, struct timespec *ts) {
   if (darwin_time_init() && timebase_info.denom) {
     switch (clock_id) {
       case CLOCK_REALTIME:
@@ -859,7 +861,7 @@ static int clock_getres(int clock_id, struct timespec *ts) {
 #endif /* TIME_HIRES_CLOCK_GETRES_EMULATION */
 
 #ifdef TIME_HIRES_CLOCK_NANOSLEEP_EMULATION
-static int clock_nanosleep(int clock_id, int flags,
+static int clock_nanosleep(clockid_t clock_id, int flags,
 			   const struct timespec *rqtp,
 			   struct timespec *rmtp) {
   if (darwin_time_init()) {
-- 
2.10.0


```
</details>

**Comment by p5pRT** [comment]
### From @jkeenan

On Wed Oct 05 08&#8203;:41&#8203;:56 2016\, randir wrote&#8203;:
> Here's an updated patch \(in case a non\-typemap route is chosen\) that
> should compile and pass on all darwins and that provides POSIX\-like
> prototypes for all emulated functions\. I've also noticed that a call
> to sleep\_nanotime\(\) lacks a cast to clockid\_t for it's argument \- was
> that intended?

I have created a \*new\* smoke\-testing branch with Sergey's second submitted patch&#8203;:

smoke\-me/jkeenan/aleynikov/2nd\-129789\-darwin\-time\-hires

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @arc

James E Keenan via RT \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> I have created a \*new\* smoke\-testing branch with Sergey's second submitted patch&#8203;:
>
> smoke\-me/jkeenan/aleynikov/2nd\-129789\-darwin\-time\-hires

Jim\, thanks very much for following up on this ticket and creating that branch\.

The smoke results for the patch are mixed\, but&#8203;:

\- The Darwin build failures were because of an unrelated local
configuration issue \(need root privs to accept XCode licence terms\)

\- The patch does fix the build failures on Darwin for me

\- There's at least one smoke success for both Linux and Win32\, and a
build success for Solaris\, so the change doesn't seem to break other
platforms

I'm therefore merging this patch\.

Sergey\, thanks\, applied as d1e7b5aaf871f3bb4562cefa3ee3153d9aa9506f\.

\-\- 
Aaron Crane \*\* http&#8203;://aaroncrane\.co\.uk/

**Comment by p5pRT** [comment]
### From @jkeenan

On Sun Oct 16 04&#8203;:14&#8203;:25 2016\, arc wrote&#8203;:
> James E Keenan via RT \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> > I have created a \*new\* smoke\-testing branch with Sergey's second
> > submitted patch&#8203;:
> >
> > smoke\-me/jkeenan/aleynikov/2nd\-129789\-darwin\-time\-hires
> 
> Jim\, thanks very much for following up on this ticket and creating
> that branch\.
> 
> The smoke results for the patch are mixed\, but&#8203;:
> 
> \- The Darwin build failures were because of an unrelated local
> configuration issue \(need root privs to accept XCode licence terms\)
> 
> \- The patch does fix the build failures on Darwin for me
> 
> \- There's at least one smoke success for both Linux and Win32\, and a
> build success for Solaris\, so the change doesn't seem to break other
> platforms
> 
> I'm therefore merging this patch\.
> 
> Sergey\, thanks\, applied as d1e7b5aaf871f3bb4562cefa3ee3153d9aa9506f\.

Reported by jarkko on p5p list&#8203;:

\#\#\#\#\#
The http&#8203;://perl5\.git\.perl\.org/perl\.git/commit/d1e7b5aaf871f3bb4562cefa3ee3153d9aa9506f looks likely culprit\.

cc \-c   \-fno\-common \-DPERL\_DARWIN \-mmacosx\-version\-min=10\.12 \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-I/opt/local/include \-DPERL\_USE\_SAFE\_PUTENV \-Wall \-Werror=declaration\-after\-statement \-Wextra \-Wc\+\+\-compat \-Wwrite\-strings \-O3   \-DVERSION=\\"1\.9740\_01\\" \-DXS\_VERSION=\\"1\.9740\_01\\"  "\-I\.\./\.\." \-DTIME\_HIRES\_NANOSLEEP \-DTIME\_HIRES\_CLOCK\_GETTIME \-DTIME\_HIRES\_CLOCK\_GETRES \-DTIME\_HIRES\_CLOCK\_NANOSLEEP \-DTIME\_HIRES\_CLOCK\_NANOSLEEP\_EMULATION \-DTIME\_HIRES\_CLOCK \-DTIME\_HIRES\_STAT\_ST\_XTIMESPEC \-DTIME\_HIRES\_STAT=1 \-DATLEASTFIVEOHOHFIVE HiRes\.c
HiRes\.xs&#8203;:805&#8203;:13&#8203;: error&#8203;: typedef redefinition with different types \('int' vs 'enum clockid\_t'\)
typedef int clockid\_t; /\* to conform with POSIX prototypes \*/
&nbsp;            ^
/usr/include/time\.h&#8203;:171&#8203;:3&#8203;: note&#8203;: previous definition is here
\} clockid\_t;
&nbsp;  ^
1 error generated\. 
\#\#\#\#\#

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by jkeenan** [comment]
> ### From @arc
> 
> James E Keenan via RT <perlbug-followup@​perl.org> wrote​:
> 
> > I have created a *new* smoke-testing branch with Sergey's second submitted patch​:
> > smoke-me/jkeenan/aleynikov/2nd-129789-darwin-time-hires
> 
> Jim, thanks very much for following up on this ticket and creating that branch.
> 
> The smoke results for the patch are mixed, but​:
> 
> - The Darwin build failures were because of an unrelated local
> configuration issue (need root privs to accept XCode licence terms)
> 
> - The patch does fix the build failures on Darwin for me
> 
> - There's at least one smoke success for both Linux and Win32, and a
> build success for Solaris, so the change doesn't seem to break other
> platforms
> 
> I'm therefore merging this patch.
> 
> Sergey, thanks, applied as [d1e7b5a](https://github.com/Perl/perl5/commit/d1e7b5aaf871f3bb4562cefa3ee3153d9aa9506f).
> 
> --
> Aaron Crane ** http​://aaroncrane.co.uk/

This patch was merged to blead in 2016 but the ticket (in RT) was never closed.  Is there any reason to keep it open?

Thank you very much.
Jim Keenan

**Comment by dur-randir** [comment]
There's no reason, it can be closed.
