### ISSUE TITLE
Fwd: OS X PowerPC is available again

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15702]
Migrated from [rt.perl.org#130056](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130056) (status was 'open')

Searchable as RT130056$

**Comment by p5pRT** [comment]
### From noloader@gmail.com

Robert\,

Does the issue below sound like something you want to investigate? If
you want to investigate it\, then send over your SSH keys\.

I don't want to waste my time trying to file a bug report if Perl is
not going to do anything with it\.

Jeff

\-\-\-\-\-\-\-\-\-\- Forwarded message \-\-\-\-\-\-\-\-\-\-
From&#8203;: Andy Polyakov \<appro@&#8203;openssl\.org>
Date&#8203;: Tue\, Nov 8\, 2016 at 2&#8203;:59 PM
Subject&#8203;: Re&#8203;: OS X PowerPC is available again
To&#8203;: noloader@&#8203;gmail\.com\, Matt Caswell \<matt@&#8203;openssl\.org>\, Richard
Levitte \<levitte@&#8203;openssl\.org>\, Peter Gutmann
\<pgut001@&#8203;cs\.auckland\.ac\.nz>


> You can find the PPC at 71\.244\.244\.203\, port 1522\. All the previous
> accounts are still on the box\.

Cool\. https://github.com/openssl/openssl/pull/1880 is direct result of
this :\-\)

> The Solaris 11/Intel box is also available\. Its older with dual Xeons
> and 140 GB drives in a RAID 1 config\. It can be found at
> 71\.244\.244\.203\, port 1523\. If you have problems with the Solaris
> login\, then I may need to setup the account\.

For reference\, that Solaris problem that you reported was traced down
mis\-compiled\(?\) perl\. Unlike all other perls it fails to do nothing
about $x\<\<32>>32\. I mean in 64\-bit perl this does sign extension for
32\-bit value\, and in 32\-bit perl it should do nothing\, and it does
nothing in ones I tried\. For reference I for one run 32\-bit perl version
5\.10\.1\, i\.e\. minimally required\, as default\.

> The AMD/ARM64 machine never shipped\. I asked them to process a refund
> for it last month\. I believe the CentOS\-ARM devs have one\, and you
> might be able to get access to it\. Or\, you can pick\-up a Pine64 board\.
> Its bad ass \- ARMv8/Aarch64\, 2 GHz cpu\, 4 cores\, 2 GB ram\, $30 or $40
> USD\.

Well\, for my part processor diversity is the key\. Pine64 is Cortex\-A53
and I have access to one of those\. I don't have access to Cortex\-A57\, so
that's interesting\.\.\.

> I also got two new MIPS64 servers for testing\. I need to set them up
> and get them online\. I can ping you if you are interested in access\.

What is the processor? GCC compile farm has Octeon II\. \[Though I seem to
fail to logon for the moment\.\.\.\]

**Comment by p5pRT** [comment]
### From noloader@gmail.com

>> The Solaris 11/Intel box is also available\. Its older with dual Xeons
>> and 140 GB drives in a RAID 1 config\. It can be found at
>> 71\.244\.244\.203\, port 1523\. If you have problems with the Solaris
>> login\, then I may need to setup the account\.
>
> For reference\, that Solaris problem that you reported was traced down
> mis\-compiled\(?\) perl\. Unlike all other perls it fails to do nothing
> about $x\<\<32>>32\. I mean in 64\-bit perl this does sign extension for
> 32\-bit value\, and in 32\-bit perl it should do nothing\, and it does
> nothing in ones I tried\. For reference I for one run 32\-bit perl version
> 5\.10\.1\, i\.e\. minimally required\, as default\.

I reported the issue to the Perl folks through their perlbug tool\. It
may or may not be investigated and fixed\.

As a dumb user\, my fingers are crossed that they will take an interest in it\.

Jeff

**Comment by p5pRT** [comment]
### From appro@openssl.org

>>> The Solaris 11/Intel box is also available\. Its older with dual Xeons
>>> and 140 GB drives in a RAID 1 config\. It can be found at
>>> 71\.244\.244\.203\, port 1523\. If you have problems with the Solaris
>>> login\, then I may need to setup the account\.
>>
>> For reference\, that Solaris problem that you reported was traced down
>> mis\-compiled\(?\) perl\. Unlike all other perls it fails to do nothing
>> about $x\<\<32>>32\. I mean in 64\-bit perl this does sign extension for
>> 32\-bit value\, and in 32\-bit perl it should do nothing\, and it does
>> nothing in ones I tried\. For reference I for one run 32\-bit perl version
>> 5\.10\.1\, i\.e\. minimally required\, as default\.
> 
> I reported the issue to the Perl folks through their perlbug tool\. It
> may or may not be investigated and fixed\.

I want to clarify couple of things\. First of all it's absolutely
essential that there is 'use integer' in the scope where $x\<\<32>>32 is
executed\. Secondly\, it's probably compiler specific\. As already
mentioned I have no and never had problem with 32\-bit perl compiled with
gcc \(I've tested a number of versions\)\, and I'd guess that your perl is
compiled with vendor compiler\. Finally\, it \*might\* be possible to argue
that this shouldn't have worked universally\, because it might rely on
unspecified C behaviour\, and consequently it is $x\<\<32>>32 that is
flawed\. As implied\, it was verified in a range of configurations and
found to be working\, and worked for several years on multiple platforms\.
This doesn't mean that it can't be flawed\, it's just an explanation on
how it achieved its status\-quo\.

For reference\, it's possible to work around the problem by compiling
32\-bit perl with 64\-bit integer support\, there is additional flag\. But
not if you compile with gcc\. My default 32\-bit perl mentioned above is
\*not\* compiled with 64\-bit integer support\.

**Comment by p5pRT** [comment]
### From noloader@gmail.com

>> I reported the issue to the Perl folks through their perlbug tool\. It
>> may or may not be investigated and fixed\.
>
> I want to clarify couple of things\. First of all it's absolutely
> essential that there is 'use integer' in the scope where $x\<\<32>>32 is
> executed\. Secondly\, it's probably compiler specific\. As already
> mentioned I have no and never had problem with 32\-bit perl compiled with
> gcc \(I've tested a number of versions\)\, and I'd guess that your perl is
> compiled with vendor compiler\. Finally\, it \*might\* be possible to argue
> that this shouldn't have worked universally\, because it might rely on
> unspecified C behaviour\, and consequently it is $x\<\<32>>32 that is
> flawed\. As implied\, it was verified in a range of configurations and
> found to be working\, and worked for several years on multiple platforms\.
> This doesn't mean that it can't be flawed\, it's just an explanation on
> how it achieved its status\-quo\.
>
> For reference\, it's possible to work around the problem by compiling
> 32\-bit perl with 64\-bit integer support\, there is additional flag\. But
> not if you compile with gcc\. My default 32\-bit perl mentioned above is
> \*not\* compiled with 64\-bit integer support\.

Ack\. For completeness\, I just re\-\{downloaded|built|installed\} Perl
5\.24 again\. I noticed Perl started off by mis\-identifying the shell\.
It claimed I was using a Korn shell rather than a Bash shell\.
Unfortunately\, I know nothing about Perl or its build process\, so I
don't know what looks right and what does not\. About all I know is is
it produces incorrect results on this machine\.

I pulled the latest OpenSSL from GitHub and it hung in self tests again&#8203;:

\.\./test/recipes/03\-test\_internal\.t \.\.\.\.\.\.\.\.\.
1\.\.5
\.\./util/shlib\_wrap\.sh \./poly1305\_internal\_test => 139
not ok 1 \- Running poly1305\_internal\_test

\#   Failed test 'Running poly1305\_internal\_test'
\#   at \.\./test/recipes/03\-test\_internal\.t line 29\.
asn1 tbl\_standard&#8203;: Table order OK
asn1 standard methods&#8203;: Table order OK
\<hang here>

Jeff

**Comment by p5pRT** [comment]
### From alex@chmrr.net

On Wed\, 09 Nov 2016 02&#8203;:28&#8203;:44 \-0800 "noloader@&#8203;gmail\.com via RT"
\<perlbug\-admin@&#8203;perl\.org> wrote&#8203;:
> \[snip\]

perlbug\-admin@&#8203;perl\.org is for the maintainers of the bug system\, not
for discussion of perl bugs themselves\.  I've merged the relevant
tickets together\[1\]; please use this thread \(i\.e\. subject and reply\-to\)
to properly thread discussion of the issue from here on out\.

Thanks\,
 \- Alex

\[1\] https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130056

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From appro@openssl.org

Hi\,

> perlbug\-admin@&#8203;perl\.org is for the maintainers of the bug system\, not
> for discussion of perl bugs themselves\.  I've merged the relevant
> tickets together\[1\]; please use this thread \(i\.e\. subject and reply\-to\)
> to properly thread discussion of the issue from here on out\.
> 
> Thanks\,
>  \- Alex
> 
> \[1\] https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130056

My reply to Jeffery \(as quoted in first message in this thread\) is
terrible as problem description and probably shouldn't have made to you\.
Clarification in
https://rt.perl.org/Public/Bug/Display.html?id=130056#txn-1434773 is a
step forward\, but probably still not something directly useful\. I
suggest to wait with looking into it till better description is provided\.

**Comment by p5pRT** [comment]
### From @tonycoz

On Wed\, 09 Nov 2016 11&#8203;:48&#8203;:17 \-0800\, appro@&#8203;openssl\.org wrote&#8203;:
> > \[1\] https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130056
> 
> My reply to Jeffery \(as quoted in first message in this thread\) is
> terrible as problem description and probably shouldn't have made to you\.
> Clarification in
> https://rt.perl.org/Public/Bug/Display.html?id=130056#txn-1434773 is a
> step forward\, but probably still not something directly useful\. I
> suggest to wait with looking into it till better description is provided\.
> 

Did you end up having a perl bug to report here?

Tony

**Comment by p5pRT** [comment]
### From noloader@gmail.com

>> Did you end up having a perl bug to report here?
>
> After some consideration I've decided to settle for
> https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=82e089308bd9a7794a45f0fa3973d7659420fbd8
> that works around the problem\. Please note the accompanying commit
> message\. The line responsible for Jeffrey's problem did work initially
> and for a while\(\*\)\, but then behaviour changed in some later perl
> version\, but went unnoticed\, because \-Duse64bitint is option customarily
> used by package providers\, e\.g\. Solaris perl is compiled with it by the
> vendor\, so is ActivePerl\, cygwin\, all 32\-bit builds that is\. Either way\,
> this case can be dismissed\.\.\.
>
> \(\*\) Keyword here is that if you just download perl and run default
> installation on Solaris like Jeffrey did\, you end up with "pure" 32\-bit
> perl version\. Even if installation is 64\-bit one\. "Pure" refers to fact
> that perl can't handle 64\-bit integer values\. For reference I myself
> normally use "pure" 32\-bit perl version 5\.10\, because it's one minimally
> required by OpenSSL\.

Confirmed the issue has been cleared\.

If the Perl folks want to investigate why Perl lacked
\{proper|expected?\} 64\-bit support\, then they are welcomed to the
machine\. Solaris is a drag at times\, and I don't know enough about
Perl to help\.

Jeff

**Comment by p5pRT** [comment]
### From appro@openssl.org

>>> \[1\] https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130056
>>
>> My reply to Jeffery \(as quoted in first message in this thread\) is
>> terrible as problem description and probably shouldn't have made to you\.
>> Clarification in
>> https://rt.perl.org/Public/Bug/Display.html?id=130056#txn-1434773 is a
>> step forward\, but probably still not something directly useful\. I
>> suggest to wait with looking into it till better description is provided\.
>>
> 
> Did you end up having a perl bug to report here?

After some consideration I've decided to settle for
https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=82e089308bd9a7794a45f0fa3973d7659420fbd8
that works around the problem\. Please note the accompanying commit
message\. The line responsible for Jeffrey's problem did work initially
and for a while\(\*\)\, but then behaviour changed in some later perl
version\, but went unnoticed\, because \-Duse64bitint is option customarily
used by package providers\, e\.g\. Solaris perl is compiled with it by the
vendor\, so is ActivePerl\, cygwin\, all 32\-bit builds that is\. Either way\,
this case can be dismissed\.\.\.

\(\*\) Keyword here is that if you just download perl and run default
installation on Solaris like Jeffrey did\, you end up with "pure" 32\-bit
perl version\. Even if installation is 64\-bit one\. "Pure" refers to fact
that perl can't handle 64\-bit integer values\. For reference I myself
normally use "pure" 32\-bit perl version 5\.10\, because it's one minimally
required by OpenSSL\.

**Comment by xenu** [comment]
It doesn't seem this ticket is about a bug in Perl.
