### ISSUE TITLE
perl 5.25.6 fails a test on Solaris 10

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15719]
Migrated from [rt.perl.org#130116](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130116) (status was 'open')

Searchable as RT130116$

**Comment by p5pRT** [comment]
### From @glasswalk3r

Trying to compile perl 5\.25\.6 fails a test on Solaris 10&#8203;:

Test Summary Report


---
\.\./cpan/Archive\-Tar/t/09\_roundtrip\.t                             \(Wstat&#8203;: 1024 Tests&#8203;: 7 Failed&#8203;: 4\)
  Failed tests&#8203;:  4\-7
  Non\-zero exit status&#8203;: 4
Files=2508\, Tests=912091\, 746 wallclock secs \(58\.65 usr 18\.95 sys \+ 334\.79 cusr 61\.43 csys = 473\.82 CPU\)
Result&#8203;: FAIL
make&#8203;: \*\*\* \[makefile&#8203;:840&#8203;: test\_harness\] Error 4

\.\./cpan/Archive\-Tar/t/08\_ptargrep\.t \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\. ok
\# Using IPC&#8203;::Cmd

\#   Failed test 'src/long/bar\.tar roundtrip on file names'
\#   at t/09\_roundtrip\.t line 157\.
\#     Structures begin differing at&#8203;:
\#          $got\->\[3\] = 'directory/really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-long\-directory\-name'
\#     $expected\->\[3\] = 'directory/really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-long\-directory\-name/'
tar&#8203;: tape blocksize error

\#   Failed test 'src/linktest/linktest\_with\_dir\.tar roundtrip on file names'
\#   at t/09\_roundtrip\.t line 157\.
\#     Structures begin differing at&#8203;:
\#          $got\->\[0\] = 'linktest/orig'
\#     $expected\->\[0\] = 'linktest/orig/'
tar&#8203;: z&#8203;: unknown function modifier
Usage&#8203;: tar \{c|r|t|u|x\}\[BDeEFhilmnopPqTvw@&#8203;\[0\-7\]\]\[bfk\]\[X\.\.\.\] \[blocksize\] \[tarfile\] \[size\] \[exclude\-file\.\.\.\] \{file | \-I include\-file | \-C directory file\}\.\.\.

\#   Failed test 'src/long/foo\.tgz roundtrip on file names'
\#   at t/09\_roundtrip\.t line 157\.
\#     Structures begin differing at&#8203;:
\#          $got\->\[2\] = 'directory'
\#     $expected\->\[2\] = 'directory/'
tar&#8203;: j&#8203;: unknown function modifier
Usage&#8203;: tar \{c|r|t|u|x\}\[BDeEFhilmnopPqTvw@&#8203;\[0\-7\]\]\[bfk\]\[X\.\.\.\] \[blocksize\] \[tarfile\] \[size\] \[exclude\-file\.\.\.\] \{file | \-I include\-file | \-C directory file\}\.\.\.

\#   Failed test 'src/long/foo\.tbz roundtrip on file names'
\#   at t/09\_roundtrip\.t line 157\.
\#     Structures begin differing at&#8203;:
\#          $got\->\[2\] = 'directory'
\#     $expected\->\[2\] = 'directory/'
\# Looks like you failed 4 tests of 7\.
\.\./cpan/Archive\-Tar/t/09\_roundtrip\.t \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.
Dubious\, test returned 4 \(wstat 1024\, 0x400\)
Failed 4/7 subtests

All procures were executed with perlbrew\.

Compiling perl 5\.24\.0 pass all the tests&#8203;:

bash\-3\.2$ perlbrew use perl\-5\.24\.0

A sub\-shell is launched with perl\-5\.24\.0 as the activated perl\. Run 'exit' to finish it\.

bash\-3\.2$
bash\-3\.2$ perl \-V
Summary of my perl5 \(revision 5 version 10 subversion 1\) configuration&#8203;:
  Commit id&#8203;: 2006d6e6d7ea518cfcbce6368ec454403ebc984f
  Platform&#8203;:
    osname=solaris\, osvers=2\.10\, archname=i86pc\-solaris\-thread\-multi
    uname='sunos unstable10x 5\.10 generic\_142910\-17 i86pc i386 i86pc'
    config\_args=''
    hint=recommended\, useposix=true\, d\_sigaction=define
    useithreads=define\, usemultiplicity=define
    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
    use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
    usemymalloc=n\, bincompat5005=undef
  Compiler&#8203;:
    cc='/opt/SUNWspro/bin/cc'\, ccflags ='\-D\_REENTRANT \-xO3 \-m32 \-xarch=pentium\_pro \-xchip=pentium\_pro \-I/opt/csw/bdb48/include \-I/opt/csw/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-DPERL\_USE\_SAFE\_PUTENV'\,
    optimize='\-xO3 \-m32 \-xarch=pentium\_pro \-xchip=pentium\_pro'\,
    cppflags='\-D\_REENTRANT \-xO3 \-m32 \-xarch=pentium\_pro \-xchip=pentium\_pro \-I/opt/csw/bdb48/include \-I/opt/csw/include'
    ccversion='Sun C 5\.9 SunOS\_i386 Patch 124868\-15 2010/08/11'\, gccversion=''\, gccosandvers=''
    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
    alignbytes=4\, prototype=define
  Linker and Libraries&#8203;:
    ld='/opt/SUNWspro/bin/cc'\, ldflags ='\-m32 \-xarch=pentium\_pro \-xchip=pentium\_pro \-L/opt/csw/lib \-lperl \-L/opt/csw/bdb48/lib \-L/opt/csw/lib \-L/usr/lib \-L/usr/ccs/lib \-L/lib'
    libpth=/usr/lib /usr/ccs/lib /lib /opt/csw/lib
    libs=\-lsocket \-lnsl \-lgdbm \-ldb\-4\.8 \-ldl \-lm \-lpthread \-lc \-lperl
    perllibs=\-lsocket \-lnsl \-ldb\-4\.8 \-ldl \-lm \-lpthread \-lc \-lperl
    libc=/lib/libc\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.10\.1
    gnulibc\_version=''
  Dynamic Linking&#8203;:
    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-R /opt/csw/lib'
    cccdlflags='\-KPIC'\, lddlflags='\-G \-L/opt/csw/lib \-L/opt/csw/bdb48/lib \-L/usr/lib \-L/usr/ccs/lib \-L/lib'


Characteristics of this binary \(from libperl\)&#8203;:
  Compile\-time options&#8203;: MULTIPLICITY PERL\_DONT\_CREATE\_GVSV
                        PERL\_IMPLICIT\_CONTEXT PERL\_MALLOC\_WRAP
                        PERL\_USE\_SAFE\_PUTENV USE\_ITHREADS USE\_LARGE\_FILES
                        USE\_PERLIO USE\_REENTRANT\_API USE\_SITECUSTOMIZE
  Built under solaris
  Compiled at Jul 24 2012 14&#8203;:23&#8203;:44
  %ENV&#8203;:
    PERL5LIB=""
    PERLBREW\_BASHRC\_VERSION="0\.77"
    PERLBREW\_HOME="/export/home/alceu/\.perlbrew"
    PERLBREW\_LIB=""
    PERLBREW\_MANPATH="/export/home/alceu/perl5/perlbrew/perls/perl\-5\.24\.0/man"
    PERLBREW\_PATH="/export/home/alceu/perl5/perlbrew/bin&#8203;:/export/home/alceu/perl5/perlbrew/perls/perl\-5\.24\.0/bin"
    PERLBREW\_PERL="perl\-5\.24\.0"
    PERLBREW\_ROOT="/export/home/alceu/perl5/perlbrew"
    PERLBREW\_SKIP\_INIT="1"
    PERLBREW\_VERSION="0\.77"
    PERL\_LOCAL\_LIB\_ROOT=""
  @&#8203;INC&#8203;:
    /opt/csw/lib/perl/site\_perl
    /opt/csw/share/perl/site\_perl
    /opt/csw/share/perl/site\_perl
    /opt/csw/lib/perl/csw
    /opt/csw/share/perl/csw
    /opt/csw/share/perl/csw
    /opt/csw/lib/perl/5\.10\.1
    /opt/csw/share/perl/5\.10\.1
    \.
bash\-3\.2$

Here is information from the standard perl available with the OS&#8203;:

bash\-3\.2$ perl \-V
Summary of my perl5 \(revision 5 version 10 subversion 1\) configuration&#8203;:
  Commit id&#8203;: 2006d6e6d7ea518cfcbce6368ec454403ebc984f
  Platform&#8203;:
    osname=solaris\, osvers=2\.10\, archname=i86pc\-solaris\-thread\-multi
    uname='sunos unstable10x 5\.10 generic\_142910\-17 i86pc i386 i86pc'
    config\_args=''
    hint=recommended\, useposix=true\, d\_sigaction=define
    useithreads=define\, usemultiplicity=define
    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
    use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
    usemymalloc=n\, bincompat5005=undef
  Compiler&#8203;:
    cc='/opt/SUNWspro/bin/cc'\, ccflags ='\-D\_REENTRANT \-xO3 \-m32 \-xarch=pentium\_pro \-xchip=pentium\_pro \-I/opt/csw/bdb48/include \-I/opt/csw/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-DPERL\_USE\_SAFE\_PUTENV'\,
    optimize='\-xO3 \-m32 \-xarch=pentium\_pro \-xchip=pentium\_pro'\,
    cppflags='\-D\_REENTRANT \-xO3 \-m32 \-xarch=pentium\_pro \-xchip=pentium\_pro \-I/opt/csw/bdb48/include \-I/opt/csw/include'
    ccversion='Sun C 5\.9 SunOS\_i386 Patch 124868\-15 2010/08/11'\, gccversion=''\, gccosandvers=''
    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
    alignbytes=4\, prototype=define
  Linker and Libraries&#8203;:
    ld='/opt/SUNWspro/bin/cc'\, ldflags ='\-m32 \-xarch=pentium\_pro \-xchip=pentium\_pro \-L/opt/csw/lib \-lperl \-L/opt/csw/bdb48/lib \-L/opt/csw/lib \-L/usr/lib \-L/usr/ccs/lib \-L/lib'
    libpth=/usr/lib /usr/ccs/lib /lib /opt/csw/lib
    libs=\-lsocket \-lnsl \-lgdbm \-ldb\-4\.8 \-ldl \-lm \-lpthread \-lc \-lperl
    perllibs=\-lsocket \-lnsl \-ldb\-4\.8 \-ldl \-lm \-lpthread \-lc \-lperl
    libc=/lib/libc\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.10\.1
    gnulibc\_version=''
  Dynamic Linking&#8203;:
    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-R /opt/csw/lib'
    cccdlflags='\-KPIC'\, lddlflags='\-G \-L/opt/csw/lib \-L/opt/csw/bdb48/lib \-L/usr/lib \-L/usr/ccs/lib \-L/lib'


Characteristics of this binary \(from libperl\)&#8203;:
  Compile\-time options&#8203;: MULTIPLICITY PERL\_DONT\_CREATE\_GVSV
                        PERL\_IMPLICIT\_CONTEXT PERL\_MALLOC\_WRAP
                        PERL\_USE\_SAFE\_PUTENV USE\_ITHREADS USE\_LARGE\_FILES
                        USE\_PERLIO USE\_REENTRANT\_API USE\_SITECUSTOMIZE
  Built under solaris
  Compiled at Jul 24 2012 14&#8203;:23&#8203;:44
  %ENV&#8203;:
    PERLBREW\_BASHRC\_VERSION="0\.77"
    PERLBREW\_HOME="/export/home/alceu/\.perlbrew"
    PERLBREW\_PATH="/export/home/alceu/perl5/perlbrew/bin"
    PERLBREW\_ROOT="/export/home/alceu/perl5/perlbrew"
    PERLBREW\_VERSION="0\.77"
  @&#8203;INC&#8203;:
    /opt/csw/lib/perl/site\_perl
    /opt/csw/share/perl/site\_perl
    /opt/csw/share/perl/site\_perl
    /opt/csw/lib/perl/csw
    /opt/csw/share/perl/csw
    /opt/csw/share/perl/csw
    /opt/csw/lib/perl/5\.10\.1
    /opt/csw/share/perl/5\.10\.1
    \.
bash\-3\.2$
bash\-3\.2$ perlbug \-d
Use of uninitialized value $category in concatenation \(\.\) or string at /opt/csw/bin/perlbug line 639\.
Use of uninitialized value $severity in concatenation \(\.\) or string at /opt/csw/bin/perlbug line 639\.


---
Flags&#8203;:
    category=
    severity=


---
Site configuration information for perl 5\.10\.1&#8203;:

Configured by bonivart at Tue Jul 24 14&#8203;:20&#8203;:58 CEST 2012\.

Summary of my perl5 \(revision 5 version 10 subversion 1\) configuration&#8203;:
  Commit id&#8203;: 2006d6e6d7ea518cfcbce6368ec454403ebc984f
  Platform&#8203;:
    osname=solaris\, osvers=2\.10\, archname=i86pc\-solaris\-thread\-multi
    uname='sunos unstable10x 5\.10 generic\_142910\-17 i86pc i386 i86pc'
    config\_args=''
    hint=recommended\, useposix=true\, d\_sigaction=define
    useithreads=define\, usemultiplicity=define
    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
    use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
    usemymalloc=n\, bincompat5005=undef
  Compiler&#8203;:
    cc='/opt/SUNWspro/bin/cc'\, ccflags ='\-D\_REENTRANT \-xO3 \-m32 \-xarch=pentium\_pro \-xchip=pentium\_pro \-I/opt/csw/bdb48/include \-I/opt/csw/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-DPERL\_USE\_SAFE\_PUTENV'\,
    optimize='\-xO3 \-m32 \-xarch=pentium\_pro \-xchip=pentium\_pro'\,
    cppflags='\-D\_REENTRANT \-xO3 \-m32 \-xarch=pentium\_pro \-xchip=pentium\_pro \-I/opt/csw/bdb48/include \-I/opt/csw/include'
    ccversion='Sun C 5\.9 SunOS\_i386 Patch 124868\-15 2010/08/11'\, gccversion=''\, gccosandvers=''
    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
    alignbytes=4\, prototype=define
  Linker and Libraries&#8203;:
    ld='/opt/SUNWspro/bin/cc'\, ldflags ='\-m32 \-xarch=pentium\_pro \-xchip=pentium\_pro \-L/opt/csw/lib \-lperl \-L/opt/csw/bdb48/lib \-L/opt/csw/lib \-L/usr/lib \-L/usr/ccs/lib \-L/lib'
    libpth=/usr/lib /usr/ccs/lib /lib /opt/csw/lib
    libs=\-lsocket \-lnsl \-lgdbm \-ldb\-4\.8 \-ldl \-lm \-lpthread \-lc \-lperl
    perllibs=\-lsocket \-lnsl \-ldb\-4\.8 \-ldl \-lm \-lpthread \-lc \-lperl
    libc=/lib/libc\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.10\.1
    gnulibc\_version=''
  Dynamic Linking&#8203;:
    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-R /opt/csw/lib'
    cccdlflags='\-KPIC'\, lddlflags='\-G \-L/opt/csw/lib \-L/opt/csw/bdb48/lib \-L/usr/lib \-L/usr/ccs/lib \-L/lib'

Locally applied patches&#8203;:




---
@&#8203;INC for perl 5\.10\.1&#8203;:
    /opt/csw/lib/perl/site\_perl
    /opt/csw/share/perl/site\_perl
    /opt/csw/share/perl/site\_perl
    /opt/csw/lib/perl/csw
    /opt/csw/share/perl/csw
    /opt/csw/share/perl/csw
    /opt/csw/lib/perl/5\.10\.1
    /opt/csw/share/perl/5\.10\.1
    \.



---
Environment for perl 5\.10\.1&#8203;:
    HOME=/export/home/alceu
    LANG=C
    LANGUAGE \(unset\)
    LD\_LIBRARY\_PATH \(unset\)
    LOGDIR \(unset\)
    PATH=/export/home/alceu/perl5/perlbrew/bin&#8203;:/opt/csw/bin&#8203;:/usr/bin&#8203;:/usr/openwin/bin&#8203;:/usr/ucb
    PERLBREW\_BASHRC\_VERSION=0\.77
    PERLBREW\_HOME=/export/home/alceu/\.perlbrew
    PERLBREW\_PATH=/export/home/alceu/perl5/perlbrew/bin
    PERLBREW\_ROOT=/export/home/alceu/perl5/perlbrew
    PERLBREW\_VERSION=0\.77
    PERL\_BADLANG \(unset\)
    SHELL=/bin/bash
bash\-3\.2$

**Comment by p5pRT** [comment]
### From @jkeenan

On Wed\, 16 Nov 2016 21&#8203;:04&#8203;:40 GMT\, glasswalk3r wrote&#8203;:
> Trying to compile perl 5\.25\.6 fails a test on Solaris 10&#8203;:
> 
> Test Summary Report
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \.\./cpan/Archive\-Tar/t/09\_roundtrip\.t                            
> \(Wstat&#8203;: 1024 Tests&#8203;: 7 Failed&#8203;: 4\)
>   Failed tests&#8203;:  4\-7
>   Non\-zero exit status&#8203;: 4
> Files=2508\, Tests=912091\, 746 wallclock secs \(58\.65 usr 18\.95 sys \+
> 334\.79 cusr 61\.43 csys = 473\.82 CPU\)
> Result&#8203;: FAIL
> make&#8203;: \*\*\* \[makefile&#8203;:840&#8203;: test\_harness\] Error 4
> 
> \.\./cpan/Archive\-Tar/t/08\_ptargrep\.t \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.
> ok
> \# Using IPC&#8203;::Cmd
> 
> \#   Failed test 'src/long/bar\.tar roundtrip on file names'
> \#   at t/09\_roundtrip\.t line 157\.
> \#     Structures begin differing at&#8203;:
> \#          $got\->\[3\] = 'directory/really\-really\-really\-really\-really\-
> really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-
> really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-
> really\-really\-really\-long\-directory\-name'
> \#     $expected\->\[3\] = 'directory/really\-really\-really\-really\-really\-
> really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-
> really\-really\-really\-really\-really\-really\-really\-really\-really\-really\-
> really\-really\-really\-long\-directory\-name/'
> tar&#8203;: tape blocksize error
> 
> \#   Failed test 'src/linktest/linktest\_with\_dir\.tar roundtrip on file
> names'
> \#   at t/09\_roundtrip\.t line 157\.
> \#     Structures begin differing at&#8203;:
> \#          $got\->\[0\] = 'linktest/orig'
> \#     $expected\->\[0\] = 'linktest/orig/'
> tar&#8203;: z&#8203;: unknown function modifier
> Usage&#8203;: tar \{c|r|t|u|x\}\[BDeEFhilmnopPqTvw@&#8203;\[0\-7\]\]\[bfk\]\[X\.\.\.\] \[blocksize\]
> \[tarfile\] \[size\] \[exclude\-file\.\.\.\] \{file | \-I include\-file | \-C
> directory file\}\.\.\.
> 
> \#   Failed test 'src/long/foo\.tgz roundtrip on file names'
> \#   at t/09\_roundtrip\.t line 157\.
> \#     Structures begin differing at&#8203;:
> \#          $got\->\[2\] = 'directory'
> \#     $expected\->\[2\] = 'directory/'
> tar&#8203;: j&#8203;: unknown function modifier
> Usage&#8203;: tar \{c|r|t|u|x\}\[BDeEFhilmnopPqTvw@&#8203;\[0\-7\]\]\[bfk\]\[X\.\.\.\] \[blocksize\]
> \[tarfile\] \[size\] \[exclude\-file\.\.\.\] \{file | \-I include\-file | \-C
> directory file\}\.\.\.
> 
> \#   Failed test 'src/long/foo\.tbz roundtrip on file names'
> \#   at t/09\_roundtrip\.t line 157\.
> \#     Structures begin differing at&#8203;:
> \#          $got\->\[2\] = 'directory'
> \#     $expected\->\[2\] = 'directory/'
> \# Looks like you failed 4 tests of 7\.
> \.\./cpan/Archive\-Tar/t/09\_roundtrip\.t \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.
> Dubious\, test returned 4 \(wstat 1024\, 0x400\)
> Failed 4/7 subtests
> 
> All procures were executed with perlbrew\.
> 
> Compiling perl 5\.24\.0 pass all the tests&#8203;:
> 

I \*think\* this is the same bug which has already been reported upstream at https://rt.cpan.org/Ticket/Display.html?id=118476.

Could someone confirm that\, please?

Thank you very much\.
\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @jkeenan

On Thu\, 17 Nov 2016 22&#8203;:44&#8203;:03 GMT\, jkeenan wrote&#8203;:
> On Wed\, 16 Nov 2016 21&#8203;:04&#8203;:40 GMT\, glasswalk3r wrote&#8203;:
> > Trying to compile perl 5\.25\.6 fails a test on Solaris 10&#8203;:
> >
> > Test Summary Report
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > \.\./cpan/Archive\-Tar/t/09\_roundtrip\.t
> > \(Wstat&#8203;: 1024 Tests&#8203;: 7 Failed&#8203;: 4\)
> >   Failed tests&#8203;:  4\-7
> >   Non\-zero exit status&#8203;: 4
> > Files=2508\, Tests=912091\, 746 wallclock secs \(58\.65 usr 18\.95 sys \+
> > 334\.79 cusr 61\.43 csys = 473\.82 CPU\)
> > Result&#8203;: FAIL
> > make&#8203;: \*\*\* \[makefile&#8203;:840&#8203;: test\_harness\] Error 4
> >
> > \.\./cpan/Archive\-Tar/t/08\_ptargrep\.t \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.
> > ok
> > \# Using IPC&#8203;::Cmd
> >
> > \#   Failed test 'src/long/bar\.tar roundtrip on file names'
> > \#   at t/09\_roundtrip\.t line 157\.
> > \#     Structures begin differing at&#8203;:
> > \#          $got\->\[3\] = 'directory/really\-really\-really\-really\-really\-
> > really\-really\-really\-really\-really\-really\-really\-really\-really\-
> > really\-
> > really\-really\-really\-really\-really\-really\-really\-really\-really\-
> > really\-
> > really\-really\-really\-long\-directory\-name'
> > \#     $expected\->\[3\] = 'directory/really\-really\-really\-really\-really\-
> > really\-really\-really\-really\-really\-really\-really\-really\-really\-
> > really\-
> > really\-really\-really\-really\-really\-really\-really\-really\-really\-
> > really\-
> > really\-really\-really\-long\-directory\-name/'
> > tar&#8203;: tape blocksize error
> >
> > \#   Failed test 'src/linktest/linktest\_with\_dir\.tar roundtrip on file
> > names'
> > \#   at t/09\_roundtrip\.t line 157\.
> > \#     Structures begin differing at&#8203;:
> > \#          $got\->\[0\] = 'linktest/orig'
> > \#     $expected\->\[0\] = 'linktest/orig/'
> > tar&#8203;: z&#8203;: unknown function modifier
> > Usage&#8203;: tar \{c|r|t|u|x\}\[BDeEFhilmnopPqTvw@&#8203;\[0\-7\]\]\[bfk\]\[X\.\.\.\]
> > \[blocksize\]
> > \[tarfile\] \[size\] \[exclude\-file\.\.\.\] \{file | \-I include\-file | \-C
> > directory file\}\.\.\.
> >
> > \#   Failed test 'src/long/foo\.tgz roundtrip on file names'
> > \#   at t/09\_roundtrip\.t line 157\.
> > \#     Structures begin differing at&#8203;:
> > \#          $got\->\[2\] = 'directory'
> > \#     $expected\->\[2\] = 'directory/'
> > tar&#8203;: j&#8203;: unknown function modifier
> > Usage&#8203;: tar \{c|r|t|u|x\}\[BDeEFhilmnopPqTvw@&#8203;\[0\-7\]\]\[bfk\]\[X\.\.\.\]
> > \[blocksize\]
> > \[tarfile\] \[size\] \[exclude\-file\.\.\.\] \{file | \-I include\-file | \-C
> > directory file\}\.\.\.
> >
> > \#   Failed test 'src/long/foo\.tbz roundtrip on file names'
> > \#   at t/09\_roundtrip\.t line 157\.
> > \#     Structures begin differing at&#8203;:
> > \#          $got\->\[2\] = 'directory'
> > \#     $expected\->\[2\] = 'directory/'
> > \# Looks like you failed 4 tests of 7\.
> > \.\./cpan/Archive\-Tar/t/09\_roundtrip\.t \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.
> > Dubious\, test returned 4 \(wstat 1024\, 0x400\)
> > Failed 4/7 subtests
> >
> > All procures were executed with perlbrew\.
> >
> > Compiling perl 5\.24\.0 pass all the tests&#8203;:
> >
> 
> I \*think\* this is the same bug which has already been reported
> upstream at https://rt.cpan.org/Ticket/Display.html?id=118476.
> 
> Could someone confirm that\, please?
> 
> Thank you very much\.

Jarkko\, can you confirm that this problem was fixed by the work you did in https://rt.cpan.org/Ticket/Display.html?id=118476?

If so\, we can close this ticket\.

Thank you very much\.
\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @jhi

On Thursday\-201612\-29 8&#8203;:54\, James E Keenan via RT wrote&#8203;:
> On Thu\, 17 Nov 2016 22&#8203;:44&#8203;:03 GMT\, jkeenan wrote&#8203;:
>> On Wed\, 16 Nov 2016 21&#8203;:04&#8203;:40 GMT\, glasswalk3r wrote&#8203;:
>>> Trying to compile perl 5\.25\.6 fails a test on Solaris 10&#8203;:
>>>
>>> Test Summary Report
>>> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
>>> \.\./cpan/Archive\-Tar/t/09\_roundtrip\.t
>>> \(Wstat&#8203;: 1024 Tests&#8203;: 7 Failed&#8203;: 4\)
>>>   Failed tests&#8203;:  4\-7
>>>   Non\-zero exit status&#8203;: 4
>>> Files=2508\, Tests=912091\, 746 wallclock secs \(58\.65 usr 18\.95 sys \+
>>> 334\.79 cusr 61\.43 csys = 473\.82 CPU\)
>>> Result&#8203;: FAIL
>>> make&#8203;: \*\*\* \[makefile&#8203;:840&#8203;: test\_harness\] Error 4
>>>
>>> \.\./cpan/Archive\-Tar/t/08\_ptargrep\.t \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.
>>> ok
>>> \# Using IPC&#8203;::Cmd
>>>
>>> \#   Failed test 'src/long/bar\.tar roundtrip on file names'
>>> \#   at t/09\_roundtrip\.t line 157\.
>>> \#     Structures begin differing at&#8203;:
>>> \#          $got\->\[3\] = 'directory/really\-really\-really\-really\-really\-
>>> really\-really\-really\-really\-really\-really\-really\-really\-really\-
>>> really\-
>>> really\-really\-really\-really\-really\-really\-really\-really\-really\-
>>> really\-
>>> really\-really\-really\-long\-directory\-name'
>>> \#     $expected\->\[3\] = 'directory/really\-really\-really\-really\-really\-
>>> really\-really\-really\-really\-really\-really\-really\-really\-really\-
>>> really\-
>>> really\-really\-really\-really\-really\-really\-really\-really\-really\-
>>> really\-
>>> really\-really\-really\-long\-directory\-name/'
>>> tar&#8203;: tape blocksize error
>>>
>>> \#   Failed test 'src/linktest/linktest\_with\_dir\.tar roundtrip on file
>>> names'
>>> \#   at t/09\_roundtrip\.t line 157\.
>>> \#     Structures begin differing at&#8203;:
>>> \#          $got\->\[0\] = 'linktest/orig'
>>> \#     $expected\->\[0\] = 'linktest/orig/'
>>> tar&#8203;: z&#8203;: unknown function modifier
>>> Usage&#8203;: tar \{c|r|t|u|x\}\[BDeEFhilmnopPqTvw@&#8203;\[0\-7\]\]\[bfk\]\[X\.\.\.\]
>>> \[blocksize\]
>>> \[tarfile\] \[size\] \[exclude\-file\.\.\.\] \{file | \-I include\-file | \-C
>>> directory file\}\.\.\.
>>>
>>> \#   Failed test 'src/long/foo\.tgz roundtrip on file names'
>>> \#   at t/09\_roundtrip\.t line 157\.
>>> \#     Structures begin differing at&#8203;:
>>> \#          $got\->\[2\] = 'directory'
>>> \#     $expected\->\[2\] = 'directory/'
>>> tar&#8203;: j&#8203;: unknown function modifier
>>> Usage&#8203;: tar \{c|r|t|u|x\}\[BDeEFhilmnopPqTvw@&#8203;\[0\-7\]\]\[bfk\]\[X\.\.\.\]
>>> \[blocksize\]
>>> \[tarfile\] \[size\] \[exclude\-file\.\.\.\] \{file | \-I include\-file | \-C
>>> directory file\}\.\.\.
>>>
>>> \#   Failed test 'src/long/foo\.tbz roundtrip on file names'
>>> \#   at t/09\_roundtrip\.t line 157\.
>>> \#     Structures begin differing at&#8203;:
>>> \#          $got\->\[2\] = 'directory'
>>> \#     $expected\->\[2\] = 'directory/'
>>> \# Looks like you failed 4 tests of 7\.
>>> \.\./cpan/Archive\-Tar/t/09\_roundtrip\.t \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.
>>> Dubious\, test returned 4 \(wstat 1024\, 0x400\)
>>> Failed 4/7 subtests
>>>
>>> All procures were executed with perlbrew\.
>>>
>>> Compiling perl 5\.24\.0 pass all the tests&#8203;:
>>>
>>
>> I \*think\* this is the same bug which has already been reported
>> upstream at https://rt.cpan.org/Ticket/Display.html?id=118476.
>>
>> Could someone confirm that\, please?
>>
>> Thank you very much\.
>
> Jarkko\, can you confirm that this problem was fixed by the work you did in https://rt.cpan.org/Ticket/Display.html?id=118476?

Whichever AT&#8203;::T is in blead seems to pass in Solaris 10 \(x86\)\.

You might also want to ping Craig Berry on what's the situation in VMS 
since that got mentioned in the thread and was addressed with the
patches\.

**Comment by xenu** [comment]
According to @jhi's comments in the linked [rt.cpan.org ticket](https://rt.cpan.org/Public/Bug/Display.html?id=118476), these commits have fixed the issue:

202b0c8a3ba3de0efe5cb730b242b8c0502e1add
356a893ca85ec4486fe0880f5146186a2ae417d0
d81914c7e2432828ca2291fcd5c68e0a285f2bf1
ef77c312fc9d05923d4e2e14d85c8120ee33e38b

Closing.
