### ISSUE TITLE
Installing Perl 5.24. (Attempting to)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15808]
Migrated from [rt.perl.org#130560](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=130560) (status was 'open')

Searchable as RT130560$

**Comment by p5pRT** [comment]
### From mgbunem@verizon.net

Hello\,

I have downloaded perl\-5\.24 \(supposedly latest version\, as recommended\)\, but cannot get it to install\. 

 Last login&#8203;: Sat Jan 14 16&#8203;:47&#8203;:24 on ttys001
Michaels\-MBP&#8203;:\~ michael\.bunnemeyer$ /Users/michael\.bunnemeyer/Downloads/perl\-5\.24\\ 5\.0/installperl ; exit;
\-bash&#8203;: /Users/michael\.bunnemeyer/Downloads/perl\-5\.24 5\.0/installperl&#8203;: \./perl&#8203;: bad interpreter&#8203;: No such file or directory
logout
Saving session\.\.\.
\.\.\.copying shared history\.\.\.
\.\.\.saving history\.\.\.truncating history files\.\.\.
…completed\.

Please help\!
MGB

**Comment by p5pRT** [comment]
### From @jkeenan

On Sun\, 15 Jan 2017 02&#8203;:16&#8203;:41 GMT\, mgbunem@&#8203;verizon\.net wrote&#8203;:
> Hello\,
> 
> I have downloaded perl\-5\.24 \(supposedly latest version\, as
> recommended\)\, but cannot get it to install\.
> 
> Last login&#8203;: Sat Jan 14 16&#8203;:47&#8203;:24 on ttys001
> Michaels\-MBP&#8203;:\~ michael\.bunnemeyer$
> /Users/michael\.bunnemeyer/Downloads/perl\-5\.24\\ 5\.0/installperl ; exit;
> \-bash&#8203;: /Users/michael\.bunnemeyer/Downloads/perl\-5\.24 5\.0/installperl&#8203;:
> \./perl&#8203;: bad interpreter&#8203;: No such file or directory
> logout
> Saving session\.\.\.
> \.\.\.copying shared history\.\.\.
> \.\.\.saving history\.\.\.truncating history files\.\.\.
> …completed\.
> 
> Please help\!
> MGB

Can you supply more information as to where and how you are trying to install perl?

More specifically&#8203;:

Can you attach the output of 'perl \-V' from the perl you already have installed?  \(That will tell us your operating system\, etc\.\)

Can you tell us where \(link\) you obtained the version of perl you are trying to install?

Can you provide us the commands you issued to try to install perl?  \(If you are on a Unix\-ish system you might try invoking the program 'script' before proceeding\, then typing Ctrl\-D when done\, in order to save a typescript of the whole operation\.\)

Thank you very much\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Sat\, 14 Jan 2017 18&#8203;:16&#8203;:41 \-0800\, mgbunem@&#8203;verizon\.net wrote&#8203;:
> Hello\,
> 
> I have downloaded perl\-5\.24 \(supposedly latest version\, as
> recommended\)\, but cannot get it to install\.
> 
> Last login&#8203;: Sat Jan 14 16&#8203;:47&#8203;:24 on ttys001
> Michaels\-MBP&#8203;:\~ michael\.bunnemeyer$
> /Users/michael\.bunnemeyer/Downloads/perl\-5\.24\\ 5\.0/installperl ; exit;
> \-bash&#8203;: /Users/michael\.bunnemeyer/Downloads/perl\-5\.24 5\.0/installperl&#8203;:
> \./perl&#8203;: bad interpreter&#8203;: No such file or directory

It looks like you have the source extracted into a path with a space in it\.

Building from a path with a space in it isn't supported\.

Tony

**Comment by p5pRT** [comment]
### From mgbunem@verizon.net

$ Perl \-v

This is perl 5\, version 18\, subversion 2 \(v5\.18\.2\) built for darwin\-thread\-multi\-2level
\(with 2 registered patches\, see perl \-V for more detail\)

Copyright 1987\-2013\, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License\, which may be found in the Perl 5 source kit\.

Complete documentation for Perl\, including FAQ lists\, should be found on
this system using "man perl" or "perldoc perl"\.  If you have access to the
Internet\, point your browser at http&#8203;://www\.perl\.org/\, the Perl Home Page\.

Michaels\-MBP&#8203;:\~ michael\.bunnemeyer$  attempt v24&#8203;:
> Last login&#8203;: Tue Jan 17 09&#8203;:20&#8203;:39 on ttys000
> Michaels\-MBP&#8203;:\~ michael\.bunnemeyer$ /Users/michael\.bunnemeyer/Downloads/perl\-5\.24\\ 5\.0/installperl ; exit;
> \-bash&#8203;: /Users/michael\.bunnemeyer/Downloads/perl\-5\.24 5\.0/installperl&#8203;: \./perl&#8203;: bad interpreter&#8203;: No such file or directory
> logout
> Saving session\.\.\.
> \.\.\.copying shared history\.\.\.
> \.\.\.saving history\.\.\.truncating history files\.\.\.
> \.\.\.completed\.
> Deleting expired sessions\.\.\.24 completed\.
> 
> \[Process completed\]

The path apparently is&#8203;: MacIntosh\(Sierra 10\.12\.2\) HD—>Users—>Michael Bunnemeyer—>Downloads—>perl\-5\.24\.D—>Installperl


> On Jan 17\, 2017\, at 8&#8203;:24 AM\, James E Keenan via RT \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> 
> On Sun\, 15 Jan 2017 02&#8203;:16&#8203;:41 GMT\, mgbunem@&#8203;verizon\.net wrote&#8203;:
>> Hello\,
>> 
>> I have downloaded perl\-5\.24 \(supposedly latest version\, as
>> recommended\)\, but cannot get it to install\.
>> 
>> Last login&#8203;: Sat Jan 14 16&#8203;:47&#8203;:24 on ttys001
>> Michaels\-MBP&#8203;:\~ michael\.bunnemeyer$
>> /Users/michael\.bunnemeyer/Downloads/perl\-5\.24\\ 5\.0/installperl ; exit;
>> \-bash&#8203;: /Users/michael\.bunnemeyer/Downloads/perl\-5\.24 5\.0/installperl&#8203;:
>> \./perl&#8203;: bad interpreter&#8203;: No such file or directory
>> logout
>> Saving session\.\.\.
>> \.\.\.copying shared history\.\.\.
>> \.\.\.saving history\.\.\.truncating history files\.\.\.
>> …completed\.
>> 
>> Please help\!
>> MGB
> 
> Can you supply more information as to where and how you are trying to install perl?
> 
> More specifically&#8203;:
> Can you attach the output of 'perl \-V' from the perl you already have installed?  \(That will tell us your operating system\, etc\.\) — see above
> 
> Can you tell us where \(link\) you obtained the version of perl you are trying to install? https://www.perl.org/get.html —>\(Download latest Stable Source\(5\.24\.0\)\)
 \<https&#8203;://www\.google\.com/\#> \<https&#8203;://webcache\.googleusercontent\.com/search?q=cache&#8203;:cFxnXfRQ9DQJ&#8203;:https://www.perl.org/get.html+&cd=1&hl=en&ct=clnk&gl=us>
 \<https&#8203;://www\.google\.com/search?biw=1024&bih=529&q=related&#8203;:https&#8203;://www\.perl\.org/get\.html\+https://www.perl.org/get.html&tbo=1&sa=X&ved=0ahUKEwiBxcGpucnRAhUG94MKHSE4AoEQHwgtMAA>Can you provide us the commands you issued to try to install perl?  \(If you are on a Unix\-ish system you might try invoking the program 'script' before proceeding\, then typing Ctrl\-D when done\, in order to save a typescript of the whole operation\.\) I do not know anything about “invoking script”\.

Since Perl6 is apparently available\, should I use this?
I suspect my problem may relate to shells?
Please also note my posting this AM to PerlMonks \(I initially dowloaded Perl from an NCBI website \-\-> Applications of the E\-Utilities\. The version turned out to be v18\. Later I found that the latest version is recommended\. This turned out to be version 24\. I downloaded this version\, but cannot get it to install\. E\.g $ Perl \-v This is perl 5\, version 18\, subversion 2 \(v5\.18\.2\) built for darwin\-thread\-multi\-2level \(with 2 registered patches\, see perl \-V for more detail\) Copyright 1987\-2013\, Larry Wall $ /Users/michael\.bunnemeyer/Downloads/perl\-5\.24\\ 5\.0/installperl ; exit; \-bash&#8203;: /Users/michael\.bunnemeyer/Downloads/perl\-5\.24 5\.0/installperl&#8203;: \./perl&#8203;: bad interpreter&#8203;: No such file or directory logout Saving session\.\.\. \.\.\.copying shared history\.\.\. \.\.\.saving history\.\.\.truncating history files\.\.\. \.\.\.completed\. Deleting expired sessions\.\.\.24 completed\. Process completed \<http&#8203;://perlmonks\.org/?node=Process%20completed> Apparently v24 is not installed\, as per $ perl \-v Wooden shoe
> 
> Thank you very much\.
> 
> \-\- 
> James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @tonycoz

On Tue\, 17 Jan 2017 18&#8203;:57&#8203;:32 \-0800\, mgbunem@&#8203;verizon\.net wrote&#8203;:
> $ Perl \-v

James asked for the perl \-V output \(capital \-V\)

> Michaels\-MBP&#8203;:\~ michael\.bunnemeyer$  attempt v24&#8203;:
> > Last login&#8203;: Tue Jan 17 09&#8203;:20&#8203;:39 on ttys000
> > Michaels\-MBP&#8203;:\~ michael\.bunnemeyer$
> > /Users/michael\.bunnemeyer/Downloads/perl\-5\.24\\ 5\.0/installperl ;
> > exit;

> > \-bash&#8203;: /Users/michael\.bunnemeyer/Downloads/perl\-5\.24 5\.0/installperl&#8203;:

There's a space in the path at "perl\-5\.24 5\.0"\.

Please read the file INSTALL for instructions on building and installing perl\.

make will run installperl as needed\, don't run it directly\, since it just does the installation step\, not the build processing needed to perform the installation\.

> The path apparently is&#8203;: MacIntosh\(Sierra 10\.12\.2\) HD—>Users—>Michael
> Bunnemeyer—>Downloads—>perl\-5\.24\.D—>Installperl

That's not the path you're running above\.

> > Can you tell us where \(link\) you obtained the version of perl you are
> > trying to install? https://www.perl.org/get.html —>\(Download latest
> > Stable Source\(5\.24\.0\)\)
> \<https://www.google.com/#>
> \<https&#8203;://webcache\.googleusercontent\.com/search?q=cache&#8203;:cFxnXfRQ9DQJ&#8203;:https://www.perl.org/get.html+&cd=1&hl=en&ct=clnk&gl=us>
> \<https&#8203;://www\.google\.com/search?biw=1024&bih=529&q=related&#8203;:https&#8203;://www\.perl\.org/get\.html\+https://www.perl.org/get.html&tbo=1&sa=X&ved=0ahUKEwiBxcGpucnRAhUG94MKHSE4AoEQHwgtMAA>

None of these is the URL for a perl source download\, though there are links to perl sources on some of those pages\.

> Can
> you provide us the commands you issued to try to install perl?  \(If
> you are on a Unix\-ish system you might try invoking the program
> 'script' before proceeding\, then typing Ctrl\-D when done\, in order to
> save a typescript of the whole operation\.\) I do not know anything
> about “invoking script”\.

You just run "script" in the terminal before starting to build perl\, and then in the \*same\* shell\, perform the build steps from INSTALL\.

> Since Perl6 is apparently available\, should I use this?
> I suspect my problem may relate to shells?

No\, it doesn't appear to be related to shells\.

perl6 is available\, but it's a different language to perl5\.

Tony

**Comment by p5pRT** [comment]
### From mgbunem@verizon.net

Results of additional attempt  to install Perl5\.24&#8203;:
bash\-3\.2$ 
bash\-3\.2$ sh Configure \-de
sh&#8203;: Configure&#8203;: No such file or directory
bash\-3\.2$ make
make&#8203;: \*\*\* No targets specified and no makefile found\.  Stop\.
bash\-3\.2$ make test
make&#8203;: \*\*\* No rule to make target \`test'\.  Stop\.
bash\-3\.2$ make install
make&#8203;: Nothing to be done for \`install'\.
bash\-3\.2$ 

Michael

> On Jan 17\, 2017\, at 10&#8203;:37 PM\, Tony Cook via RT \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:

> On Tue\, 17 Jan 2017 18&#8203;:57&#8203;:32 \-0800\, mgbunem@&#8203;verizon\.net wrote&#8203;:
>> $ Perl \-v
> 
> James asked for the perl \-V output \(capital \-V\)
> 
>> Michaels\-MBP&#8203;:\~ michael\.bunnemeyer$  attempt v24&#8203;:
>>> Last login&#8203;: Tue Jan 17 09&#8203;:20&#8203;:39 on ttys000
>>> Michaels\-MBP&#8203;:\~ michael\.bunnemeyer$
>>> /Users/michael\.bunnemeyer/Downloads/perl\-5\.24\\ 5\.0/installperl ;
>>> exit;
> 
>>> \-bash&#8203;: /Users/michael\.bunnemeyer/Downloads/perl\-5\.24 5\.0/installperl&#8203;:
> 
> There's a space in the path at "perl\-5\.24 5\.0"\.
> 
> Please read the file INSTALL for instructions on building and installing perl\.
> 
> make will run installperl as needed\, don't run it directly\, since it just does the installation step\, not the build processing needed to perform the installation\.
> 
>> The path apparently is&#8203;: MacIntosh\(Sierra 10\.12\.2\) HD—>Users—>Michael
>> Bunnemeyer—>Downloads—>perl\-5\.24\.D—>Installperl
> 
> That's not the path you're running above\.
> 
>>> Can you tell us where \(link\) you obtained the version of perl you are
>>> trying to install? https://www.perl.org/get.html —>\(Download latest
>>> Stable Source\(5\.24\.0\)\)
>> \<https://www.google.com/#>
>> \<https&#8203;://webcache\.googleusercontent\.com/search?q=cache&#8203;:cFxnXfRQ9DQJ&#8203;:https://www.perl.org/get.html+&cd=1&hl=en&ct=clnk&gl=us>
>> \<https&#8203;://www\.google\.com/search?biw=1024&bih=529&q=related&#8203;:https&#8203;://www\.perl\.org/get\.html\+https://www.perl.org/get.html&tbo=1&sa=X&ved=0ahUKEwiBxcGpucnRAhUG94MKHSE4AoEQHwgtMAA>
> 
> None of these is the URL for a perl source download\, though there are links to perl sources on some of those pages\.
> 
>> Can
>> you provide us the commands you issued to try to install perl?  \(If
>> you are on a Unix\-ish system you might try invoking the program
>> 'script' before proceeding\, then typing Ctrl\-D when done\, in order to
>> save a typescript of the whole operation\.\) I do not know anything
>> about “invoking script”\.
> 
> You just run "script" in the terminal before starting to build perl\, and then in the \*same\* shell\, perform the build steps from INSTALL\.
> 
>> Since Perl6 is apparently available\, should I use this?
>> I suspect my problem may relate to shells?
> 
> No\, it doesn't appear to be related to shells\.
> 
> perl6 is available\, but it's a different language to perl5\.
> 
> Tony

**Comment by p5pRT** [comment]
### From mgbunem@verizon.net

Results for adding “script” to the terminal”&#8203;:
> Michaels\-MBP&#8203;:\~ michael\.bunnemeyer$ script
> Script started\, output file is typescript
> bash\-3\.2$ 
This information  is useless to me\.  When I  performed “Perl \-v”\, the program still produces&#8203;: Perl 5\.18\, instead of the 5\.24 I am aiming for\.

Michael

> 
> On Jan 17\, 2017\, at 10&#8203;:37 PM\, Tony Cook via RT \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> 
> On Tue\, 17 Jan 2017 18&#8203;:57&#8203;:32 \-0800\, mgbunem@&#8203;verizon\.net wrote&#8203;:
>> $ Perl \-v
> 
> James asked for the perl \-V output \(capital \-V\)
> 
>> Michaels\-MBP&#8203;:\~ michael\.bunnemeyer$  attempt v24&#8203;:
>>> Last login&#8203;: Tue Jan 17 09&#8203;:20&#8203;:39 on ttys000
>>> Michaels\-MBP&#8203;:\~ michael\.bunnemeyer$
>>> /Users/michael\.bunnemeyer/Downloads/perl\-5\.24\\ 5\.0/installperl ;
>>> exit;
> 
>>> \-bash&#8203;: /Users/michael\.bunnemeyer/Downloads/perl\-5\.24 5\.0/installperl&#8203;:
> 
> There's a space in the path at "perl\-5\.24 5\.0"\.
> 
> Please read the file INSTALL for instructions on building and installing perl\.
> 
> make will run installperl as needed\, don't run it directly\, since it just does the installation step\, not the build processing needed to perform the installation\.
> 
>> The path apparently is&#8203;: MacIntosh\(Sierra 10\.12\.2\) HD—>Users—>Michael
>> Bunnemeyer—>Downloads—>perl\-5\.24\.D—>Installperl
> 
> That's not the path you're running above\.
> 
>>> Can you tell us where \(link\) you obtained the version of perl you are
>>> trying to install? https://www.perl.org/get.html —>\(Download latest
>>> Stable Source\(5\.24\.0\)\)
>> \<https://www.google.com/#>
>> \<https&#8203;://webcache\.googleusercontent\.com/search?q=cache&#8203;:cFxnXfRQ9DQJ&#8203;:https://www.perl.org/get.html+&cd=1&hl=en&ct=clnk&gl=us>
>> \<https&#8203;://www\.google\.com/search?biw=1024&bih=529&q=related&#8203;:https&#8203;://www\.perl\.org/get\.html\+https://www.perl.org/get.html&tbo=1&sa=X&ved=0ahUKEwiBxcGpucnRAhUG94MKHSE4AoEQHwgtMAA>
> 
> None of these is the URL for a perl source download\, though there are links to perl sources on some of those pages\.
> 
>> Can
>> you provide us the commands you issued to try to install perl?  \(If
>> you are on a Unix\-ish system you might try invoking the program
>> 'script' before proceeding\, then typing Ctrl\-D when done\, in order to
>> save a typescript of the whole operation\.\) I do not know anything
>> about “invoking script”\.
> 
> You just run "script" in the terminal before starting to build perl\, and then in the \*same\* shell\, perform the build steps from INSTALL\.
> 
>> Since Perl6 is apparently available\, should I use this?
>> I suspect my problem may relate to shells?
> 
> No\, it doesn't appear to be related to shells\.
> 
> perl6 is available\, but it's a different language to perl5\.
> 
> Tony

**Comment by p5pRT** [comment]
### From @tonycoz

On Wed\, 18 Jan 2017 22&#8203;:19&#8203;:32 \-0800\, mgbunem@&#8203;verizon\.net wrote&#8203;:
> Results for adding “script” to the terminal”&#8203;:
> > Michaels\-MBP&#8203;:\~ michael\.bunnemeyer$ script
> > Script started\, output file is typescript
> >  bash\-3\.2$
> This information  is useless to me\.  When I  performed “Perl \-v”\, the
> program still produces&#8203;: Perl 5\.18\, instead of the 5\.24 I am aiming
> for\.

Sorry for the late response\.

The purpose of running script is to capture the commands you type and the output\, which all goes into the file typescript unless you supply a different name\.

If you've since managed to solve your problems here \(or given up\)\, please let me know and I'll close the ticket\.

Thanks\,
Tony

**Comment by xenu** [comment]
No response from the OP, closing.
