### ISSUE TITLE
perl test suite bug

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15939]
Migrated from [rt.perl.org#131093](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131093) (status was 'new')

Searchable as RT131093$

**Comment by p5pRT** [comment]
### From perl-diddler@tlinx.org

#### Created by perl-diddler@tlinx.org



The perl test suite doesn't accurately test copying of permission
bits in it's copy routines \(in lib/File/Copy\)&#8203;:

lib/File/Copy \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\. \#   Failed test 'Permission bits set correctly'
\#   at \.\./lib/File/Copy\.t line 363\.
\#          got&#8203;: 'rw\-rw\-r\-\-'
\#     expected&#8203;: 'rw\-rw\-rw\-'
\#   Failed test 'Permission bits set correctly'
\#   at \.\./lib/File/Copy\.t line 364\.
\#          got&#8203;: 'rw\-rw\-r\-\-'
\#     expected&#8203;: 'rw\-rw\-rw\-'
\#   Failed test 'Permission bits set correctly'
\.\.\.
\#   Failed test 'Permission bits set correctly'
\#   at \.\./lib/File/Copy\.t line 364\.
\#          got&#8203;: 'rw\-rw\-r\-\-'
\#     expected&#8203;: '\-\-\-\-\-\-\-\-\-'
\# Looks like you failed 112 tests of 466\.
FAILED at test 73


It seems to think that 'other' should have write permission
in the 1st tests\, but in the last test shown\, 
it thinks the file should have no access permissions\, but
it does \(should that be flagged as a security bug?\)\.

If the test suite is running on a file system with ACL's\,
\(not uncommon these days\)\, and perl was built in a directory
\(like "/home"\) that has a default\-file acl with a default
for "other" limited to r\-x\, as in this acl&#8203;:

Ishtar&#8203;:perl/perl\-5\.24/lib/File> lsacl \.
\[u&#8203;::rwx\,g&#8203;::rwx\,o&#8203;::r\-x/u&#8203;::rwx\,g&#8203;::rwx\,o&#8203;::r\-x\] \.

\(the 1st ACL\, from the '\[' to the '/' is the acl on the directory\,
the 2nd ACL from '/' to '\]' is the default acl for things created in
the directory\.  New files & dirs get the default acl&#8203;:

Ishtar&#8203;:perl/perl\-5\.24/lib/File> ll file
\-rw\-rw\-r\-\- 1 0 Apr  3 00&#8203;:56 file
Ishtar&#8203;:perl/perl\-5\.24/lib/File> umask 0
Ishtar&#8203;:perl/perl\-5\.24/lib/File> touch file2
Ishtar&#8203;:perl/perl\-5\.24/lib/File> ll file2
\-rw\-rw\-r\-\- 1 0 Apr  3 00&#8203;:56 file2
Ishtar&#8203;:perl/perl\-5\.24/lib/File> mkdir test
Ishtar&#8203;:perl/perl\-5\.24/lib/File> ll \-d test
drwxrwxr\-x 2 6 Apr  3 00&#8203;:56 test/
Ishtar&#8203;:perl/perl\-5\.24/lib/File> lsacl \.
\[u&#8203;::rwx\,g&#8203;::rwx\,o&#8203;::r\-x/u&#8203;::rwx\,g&#8203;::rwx\,o&#8203;::r\-x\] \.

Changing both acls on dir 'test'&#8203;:
chacl  \-b u&#8203;::rwx\,g&#8203;::rwx\,o&#8203;::rwx u&#8203;::rwx\,g&#8203;::rwx\,o&#8203;::rwx test

Now touch creates file w/expected permissions&#8203;:
Ishtar&#8203;:perl/perl\-5\.24/lib/File> touch test/file2
Ishtar&#8203;:perl/perl\-5\.24/lib/File> ll test/file2
\-rw\-rw\-rw\- 1 0 Apr  3 01&#8203;:01 test/file2

\-\-\-\-\-\-\-\-\-\-\-\-\-\-

Note\, linux 'cp' shows the same behavior \(write bit turned off
on file created in dir defaulting to no\-write for other\)&#8203;:

Ishtar&#8203;:perl/perl\-5\.24/lib/File> /usr/bin/cp file2 file3
Ishtar&#8203;:perl/perl\-5\.24/lib/File> ll file?
\-rw\-rw\-rw\- 1 0 Apr  3 00&#8203;:56 file2
\-rw\-rw\-r\-\- 1 0 Apr  3 01&#8203;:04 file3

But in dir w/all bits defaulted to on for 'other'\, \(in dir test\)&#8203;:

Ishtar&#8203;:perl/perl\-5\.24/lib/File> /usr/bin/cp file2 test/file3
Ishtar&#8203;:perl/perl\-5\.24/lib/File> ll test/file3
\-rw\-rw\-rw\- 1 0 Apr  3 01&#8203;:05 test/file3

Now it works\.


Hopefully perl not setting perms\-bits to '000' isn't
a security problem somewhere\, as it isn't working\.


FWIW\, 'lsacl' is a bash script to show file acl's in the
same form as used by 'chacl'\.  "chacl \-l" should perform
a similar function\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=high

Site configuration information for perl 5.16.3:

Configured by law at Wed Jan 22 12:58:58 PST 2014.

Summary of my perl5 (revision 5 version 16 subversion 3) configuration:
   
  Platform:
    osname=linux, osvers=3.12.0-isht-van, archname=x86_64-linux-thread-multi-ld
    uname='linux ishtar 3.12.0-isht-van #1 smp preempt wed nov 13 16:50:51 pst 2013 x86_64 x86_64 x86_64 gnulinux '
    config_args=''
    hint=previous, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=define, use64bitall=define, uselongdouble=define
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-g -O2',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    ccversion='', gccversion='4.8.1 20130909 [gcc-4_8-branch revision 202388]', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='long double', nvsize=16, Off_t='off_t', lseeksize=8
    alignbytes=16, prototype=define
  Linker and Libraries:
    ld='gcc', ldflags ='-g -fstack-protector -fPIC'
    libpth=/usr/lib64 /lib64
    libs=-lnsl -lndbm -lgdbm -ldb -ldl -lm -lcrypt -lutil -lpthread -lc -lgdbm_compat
    perllibs=-lnsl -ldl -lm -lcrypt -lutil -lpthread -lc
    libc=/lib/libc-2.18.so, so=so, useshrplib=true, libperl=libperl-5.16.3.so
    gnulibc_version='2.18'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E -Wl,-rpath,/home/perl/perl-5.16.3/lib/x86_64-linux-thread-multi-ld/CORE'
    cccdlflags='-fPIC', lddlflags='-shared -g -O2 -fstack-protector -fPIC'

Locally applied patches:
    


@INC for perl 5.16.3:
    /home/perl/perl-5.16.3/lib/site/x86_64-linux-thread-multi-ld
    /home/perl/perl-5.16.3/lib/site
    /home/perl/perl-5.16.3/lib/x86_64-linux-thread-multi-ld
    /home/perl/perl-5.16.3/lib
    .


Environment for perl 5.16.3:
    HOME=/home/law
    LANG (unset)
    LANGUAGE (unset)
    LC_COLLATE=C
    LC_CTYPE=en_US.UTF-8
    LC_MESSAGES=C
    LC_MONETARY=C
    LC_NUMERIC=C
    LC_TIME=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/perl/perl-5.24:/sbin:.::/home/law/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/opt/kde3/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/usr/sbin:/etc/local/func_lib:/home/law/lib:/home/law/bin/lib
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From perl-diddler@tlinx.org

Seems my initial report picked up a different libperl than the one
I ran the test suite with\.

The perl \-V output for this bug should be&#8203;:


Summary of my perl5 \(revision 5 version 24 subversion 0\) configuration&#8203;:
&nbsp;  
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=4\.10\.1\-isht\-van\, archname=x86\_64\-linux\-multi\-ld
&nbsp;    uname='linux ishtar 4\.10\.1\-isht\-van \#1 smp preempt tue feb 28 
18&#8203;:57&#8203;:48 pst 2017 x86\_64 gnulinux '
&nbsp;    config\_args=''
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=define
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=define
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc'\, ccflags ='\-fwrapv \-fno\-strict\-aliasing \-pipe 
\-fstack\-protector\-strong \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 
\-D\_FORTIFY\_SOURCE=2'\,
&nbsp;    optimize='\-O2'\,
&nbsp;    cppflags='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong'
&nbsp;    ccversion=''\, gccversion='4\.9\.0'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=12345678\, 
doublekind=3
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16\, 
longdblkind=3
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='long double'\, nvsize=16\, 
Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=16\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='gcc'\, ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/lib64/gcc/x86\_64\-suse\-linux/4\.9/include\-fixed /usr/lib 
/usr/local/lib /lib/\.\./lib64 /usr/lib/\.\./lib64 /lib /lib64 /usr/lib64
&nbsp;    libs=\-lpthread \-lnsl \-lgdbm \-ldl \-lm \-lcrypt \-lutil \-lc \-lgdbm\_compat
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.19\.so\, so=so\, useshrplib=true\, libperl=libperl\.so
&nbsp;    gnulibc\_version='2\.19'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-Wl\,\-E 
\-Wl\,\-rpath\,/home/perl/perl\-5\.24\.0/usr/lib/x86\_64\-linux\-multi\-ld/CORE'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-O2 \-L/usr/local/lib 
\-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;: HAS\_TIMES MULTIPLICITY PERLIO\_LAYERS
&nbsp;                        PERL\_COPY\_ON\_WRITE PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD
&nbsp;                        PERL\_IMPLICIT\_CONTEXT PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_PRESERVE\_IVUV USE\_64\_BIT\_ALL USE\_64\_BIT\_INT
&nbsp;                        USE\_LARGE\_FILES USE\_LOCALE USE\_LOCALE\_COLLATE
&nbsp;                        USE\_LOCALE\_CTYPE USE\_LOCALE\_NUMERIC USE\_LOCALE\_TIME
&nbsp;                        USE\_LONG\_DOUBLE USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Apr  2 2017 17&#8203;:08&#8203;:11
&nbsp;  %ENV&#8203;:
&nbsp;    PERL5LIB="/home/perl/perl\-5\.24/lib"
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /home/perl/perl\-5\.24/lib
&nbsp;    /home/perl/perl\-5\.24\.0/usr/lib/site/x86\_64\-linux\-multi\-ld
&nbsp;    /home/perl/perl\-5\.24\.0/usr/lib/site
&nbsp;    /home/perl/perl\-5\.24\.0/usr/lib/vendor/x86\_64\-linux\-multi\-ld
&nbsp;    /home/perl/perl\-5\.24\.0/usr/lib/vendor
&nbsp;    /home/perl/perl\-5\.24\.0/usr/lib/x86\_64\-linux\-multi\-ld
&nbsp;    /home/perl/perl\-5\.24\.0/usr/lib

**Comment by jkeenan** [comment]
This ticket has been open for 4-1/2 years, but the original test failure report has never been reported again or confirmed.  Closing ticket.
