### ISSUE TITLE
bleadperl breaks HARDAKER/QWizard-3.15.tar.gz on Windows

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#15968]
Migrated from [rt.perl.org#131224](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131224) (status was 'open')

Searchable as RT131224$

**Comment by p5pRT** [comment]
### From @jkeenan

#### Created by @chorny



Result of running Makefile\.PL&#8203;:
Checking if your kit is complete\.\.\.
Looks good
ERROR from evaluation of
strawberry\-perl\-5\.25\.12\.1\\cpan\\build\\QWizard\-3\.15\-0\\Generator\_base/Makefile\.PL&#8203;:
panic&#8203;: attempt to copy freed scalar 3f8d0c to 1358a54 at
strawberry\-perl\-5\.25\.12\.1/perl/lib/Carp\.pm line 229\.
Writing MYMETA\.yml and MYMETA\.json
Writing MYMETA\.yml and MYMETA\.json
Writing MYMETA\.yml and MYMETA\.json

See also 
http&#8203;://www\.cpantesters\.org/cpan/report/74da0c86\-6c12\-1014\-8ecb\-069185000ecc

Tested on Strawberry perl 5\.25\.12\, 5\.25\.10 and 5\.25\.8 32\-bit int\,
Windows XP\. Does not fail on 5\.24\.0\. Has problems on Linux too\, but
different\, see http&#8203;://matrix\.cpantesters\.org/?dist=QWizard\+3\.15 \.

Also reported in modules bug tracker&#8203;:
https://rt.cpan.org/Ticket/Display.html?id=121401

<details><summary>Perl Info</summary>

```

Flags:
     category=core
     severity=low

Site configuration information for perl 5.25.10:

Configured by strawberry-perl at Fri Feb 24 21:38:44 2017.

Summary of my perl5 (revision 5 version 25 subversion 10) configuration:

   Platform:
     osname=MSWin32
     osvers=4.0
     archname=MSWin32-x86-multi-thread
     uname='Win32 strawberry-perl 5.25.10.1-beta1 #1 Fri Feb 24
21:36:42 2017 i386'
     config_args='undef'
     hint=recommended
     useposix=true
     d_sigaction=undef
     useithreads=define
     usemultiplicity=define
     use64bitint=undef
     use64bitall=undef
     uselongdouble=undef
     usemymalloc=n
     bincompat5005=undef
   Compiler:
     cc='gcc'
     ccflags =' -s -O2 -DWIN32  -DPERL_TEXTMODE_SCRIPTS
-DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -fwrapv
-fno-strict-aliasing -mms-bitfields'
     optimize='-s -O2'
     cppflags='-DWIN32'
     ccversion=''
     gccversion='4.9.2'
     gccosandvers=''
     intsize=4
     longsize=4
     ptrsize=4
     doublesize=8
     byteorder=1234
     doublekind=3
     d_longlong=define
     longlongsize=8
     d_longdbl=define
     longdblsize=12
     longdblkind=3
     ivtype='long'
     ivsize=4
     nvtype='double'
     nvsize=8
     Off_t='long long'
     lseeksize=8
     alignbytes=8
     prototype=define
   Linker and Libraries:
     ld='g++'
     ldflags ='-s -L"C:\STRAWB~1\perl\lib\CORE" -L"C:\STRAWB~1\c\lib"'
     libpth=C:\STRAWB~1\c\lib C:\STRAWB~1\c\i686-w64-mingw32\lib
C:\STRAWB~1\c\lib\gcc\i686-w64-mingw32\4.9.2
     libs=-lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32
-ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32
-lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
     perllibs=-lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool
-lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid
-lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
     libc=
     so=dll
     useshrplib=true
     libperl=libperl525.a
     gnulibc_version=''
   Dynamic Linking:
     dlsrc=dl_win32.xs
     dlext=xs.dll
     d_dlsymun=undef
     ccdlflags=' '
     cccdlflags=' '
     lddlflags='-mdll -s -L"C:\STRAWB~1\perl\lib\CORE" 
-L"C:\STRAWB~1\c\lib"'



@INC for perl 5.25.10:
     C:/Strawberry2510/perl/site/lib
     C:/Strawberry2510/perl/vendor/lib
     C:/Strawberry2510/perl/lib


Environment for perl 5.25.10:
     HOME (unset)
     LANG (unset)
     LANGUAGE (unset)
     LD_LIBRARY_PATH (unset)
     LOGDIR (unset)
     PATH=C:\Program Files\Far
Manager\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Git\cmd;C:\Strawberry2510\c\bin;C:\Strawberry2510\perl\site\bin;C:\Strawberry2510\perl\bin
     PERL_BADLANG (unset)
     SHELL (unset)


-- 
Alexandr Ciornii, http://chorny.net

```
</details>

**Comment by p5pRT** [comment]
### From @jkeenan

On Fri\, 28 Apr 2017 19&#8203;:06&#8203;:17 GMT\, jkeenan@&#8203;pobox\.com wrote&#8203;:
> This should have originally been sent to perlbug@&#8203;perl\.org\.
> 
> 
> \-\-\-\-\-\-\-\- Forwarded Message \-\-\-\-\-\-\-\-
> Subject&#8203;: bleadperl breaks HARDAKER/QWizard\-3\.15\.tar\.gz on Windows
> Date&#8203;: Fri\, 28 Apr 2017 16&#8203;:11&#8203;:49 \+0300
> From&#8203;: Alexandr Ciornii \<alexchorny@&#8203;gmail\.com>
> To&#8203;: p5p \<perl5\-porters@&#8203;perl\.org>
> Newsgroups&#8203;: perl\.perl5\.porters
> 
> This is a bug report for perl from alexchorny@&#8203;gmail\.com\,
> generated with the help of perlbug 1\.40 running under perl 5\.25\.10\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please describe your issue here\]
> 
> Result of running Makefile\.PL&#8203;:
> Checking if your kit is complete\.\.\.
> Looks good
> ERROR from evaluation of
> strawberry\-perl\-5\.25\.12\.1\\cpan\\build\\QWizard\-3\.15\-
> 0\\Generator\_base/Makefile\.PL&#8203;:
> panic&#8203;: attempt to copy freed scalar 3f8d0c to 1358a54 at
> strawberry\-perl\-5\.25\.12\.1/perl/lib/Carp\.pm line 229\.
> Writing MYMETA\.yml and MYMETA\.json
> Writing MYMETA\.yml and MYMETA\.json
> Writing MYMETA\.yml and MYMETA\.json
> 
> See also
> http&#8203;://www\.cpantesters\.org/cpan/report/74da0c86\-6c12\-1014\-8ecb\-
> 069185000ecc
> 
> Tested on Strawberry perl 5\.25\.12\, 5\.25\.10 and 5\.25\.8 32\-bit int\,
> Windows XP\. Does not fail on 5\.24\.0\. Has problems on Linux too\, but
> different\, see http&#8203;://matrix\.cpantesters\.org/?dist=QWizard\+3\.15 \.
> 
> Also reported in modules bug tracker&#8203;:
> https://rt.cpan.org/Ticket/Display.html?id=121401
> 

Bisection \(manual\) on Linux suggests that the following commit is responsible&#8203;:

\#\#\#\#\#
commit 8b0c3377906a6f991cd6c21a674bf9561d85e3cb
Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
AuthorDate&#8203;: Wed Oct 5 10&#8203;:10&#8203;:56 2016 \+0100
Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
CommitDate&#8203;: Wed Oct 26 08&#8203;:37&#8203;:27 2016 \+0100

&nbsp;    Better optimise array and hash assignment
&nbsp;    
&nbsp;    \[perl \#127999\] Slowdown in split \+ list assign
\.\.\.
\#\#\#\#\#

Dave\, can you take a look?

Thank you very much\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Fri\, Apr 28\, 2017 at 12&#8203;:13&#8203;:26PM \-0700\, James E Keenan via RT wrote&#8203;:
> > Result of running Makefile\.PL&#8203;:
> > Checking if your kit is complete\.\.\.
> > Looks good
> > ERROR from evaluation of
> > strawberry\-perl\-5\.25\.12\.1\\cpan\\build\\QWizard\-3\.15\-
> > 0\\Generator\_base/Makefile\.PL&#8203;:
> > panic&#8203;: attempt to copy freed scalar 3f8d0c to 1358a54 at
> > strawberry\-perl\-5\.25\.12\.1/perl/lib/Carp\.pm line 229\.
> > Writing MYMETA\.yml and MYMETA\.json
> > Writing MYMETA\.yml and MYMETA\.json
> > Writing MYMETA\.yml and MYMETA\.json
> > 
> > See also
> > http&#8203;://www\.cpantesters\.org/cpan/report/74da0c86\-6c12\-1014\-8ecb\-
> > 069185000ecc
> > 
> > Tested on Strawberry perl 5\.25\.12\, 5\.25\.10 and 5\.25\.8 32\-bit int\,
> > Windows XP\. Does not fail on 5\.24\.0\. Has problems on Linux too\, but
> > different\, see http&#8203;://matrix\.cpantesters\.org/?dist=QWizard\+3\.15 \.
> > 
> > Also reported in modules bug tracker&#8203;:
> > https://rt.cpan.org/Ticket/Display.html?id=121401
> > 
> 
> Bisection \(manual\) on Linux suggests that the following commit is responsible&#8203;:
> 
> \#\#\#\#\#
> commit 8b0c3377906a6f991cd6c21a674bf9561d85e3cb
> Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
> AuthorDate&#8203;: Wed Oct 5 10&#8203;:10&#8203;:56 2016 \+0100
> Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
> CommitDate&#8203;: Wed Oct 26 08&#8203;:37&#8203;:27 2016 \+0100
> 
>     Better optimise array and hash assignment
>     
>     \[perl \#127999\] Slowdown in split \+ list assign
> \.\.\.
> \#\#\#\#\#
> 
> Dave\, can you take a look?

Given Zefram's daignosis that its an issue with @&#8203;DB&#8203;::args viewing args on
the stack which aren't ref counted\, that commit is likely to be a ref
herring \- it is likely to have just altered whether some stack args happen
to have had their lives artificially extended\.

\-\- 
I thought I was wrong once\, but I was mistaken\.

**Comment by p5pRT** [comment]
### From @sisyphus

On Sat\, 29 Apr 2017 01&#8203;:26&#8203;:21 \-0700\, davem wrote&#8203;:
> On Fri\, Apr 28\, 2017 at 12&#8203;:13&#8203;:26PM \-0700\, James E Keenan via RT wrote&#8203;:
> > > Result of running Makefile\.PL&#8203;:
> > > Checking if your kit is complete\.\.\.
> > > Looks good
> > > ERROR from evaluation of
> > > strawberry\-perl\-5\.25\.12\.1\\cpan\\build\\QWizard\-3\.15\-
> > > 0\\Generator\_base/Makefile\.PL&#8203;:
> > > panic&#8203;: attempt to copy freed scalar 3f8d0c to 1358a54 at
> > > strawberry\-perl\-5\.25\.12\.1/perl/lib/Carp\.pm line 229\.
> > > Writing MYMETA\.yml and MYMETA\.json
> > > Writing MYMETA\.yml and MYMETA\.json
> > > Writing MYMETA\.yml and MYMETA\.json
> > >
> > > See also
> > > http&#8203;://www\.cpantesters\.org/cpan/report/74da0c86\-6c12\-1014\-8ecb\-
> > > 069185000ecc
> > >
> > > Tested on Strawberry perl 5\.25\.12\, 5\.25\.10 and 5\.25\.8 32\-bit int\,
> > > Windows XP\. Does not fail on 5\.24\.0\. Has problems on Linux too\, but
> > > different\, see http&#8203;://matrix\.cpantesters\.org/?dist=QWizard\+3\.15 \.
> > >
> > > Also reported in modules bug tracker&#8203;:
> > > https://rt.cpan.org/Ticket/Display.html?id=121401
> > >
> >
> > Bisection \(manual\) on Linux suggests that the following commit is
> > responsible&#8203;:
> >
> > \#\#\#\#\#
> > commit 8b0c3377906a6f991cd6c21a674bf9561d85e3cb
> > Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
> > AuthorDate&#8203;: Wed Oct 5 10&#8203;:10&#8203;:56 2016 \+0100
> > Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
> > CommitDate&#8203;: Wed Oct 26 08&#8203;:37&#8203;:27 2016 \+0100
> >
> > Better optimise array and hash assignment
> >
> > \[perl \#127999\] Slowdown in split \+ list assign
> > \.\.\.
> > \#\#\#\#\#
> >
> > Dave\, can you take a look?
> 
> Given Zefram's daignosis that its an issue with @&#8203;DB&#8203;::args viewing args
> on
> the stack which aren't ref counted\, that commit is likely to be a ref
> herring \- it is likely to have just altered whether some stack args
> happen
> to have had their lives artificially extended\.

At about lines 655 to 658 of ExtUtils/MakeMaker\.pm we have&#8203;:

&nbsp;    \# This is for old Makefiles written pre 5\.00\, will go away
&nbsp;    if \( Carp&#8203;::longmess\(""\) =~ /runsubdirpl/s \)\{
&nbsp;        carp\("WARNING&#8203;: Please rerun 'perl Makefile\.PL' to regenerate your Makefiles\\n"\);
&nbsp;    \}

Commenting out those 3 lines of code allows 'perl Makefile\.PL' step to run to completion on Windows for me\.
\(I was initially getting the same error as reported by the OP\.\)

HTH

Cheers\,
Rob

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Sat\, 29 Apr 2017 01&#8203;:26&#8203;:21 \-0700\, davem wrote&#8203;:
> On Fri\, Apr 28\, 2017 at 12&#8203;:13&#8203;:26PM \-0700\, James E Keenan via RT wrote&#8203;:
> > > Result of running Makefile\.PL&#8203;:
> > > Checking if your kit is complete\.\.\.
> > > Looks good
> > > ERROR from evaluation of
> > > strawberry\-perl\-5\.25\.12\.1\\cpan\\build\\QWizard\-3\.15\-
> > > 0\\Generator\_base/Makefile\.PL&#8203;:
> > > panic&#8203;: attempt to copy freed scalar 3f8d0c to 1358a54 at
> > > strawberry\-perl\-5\.25\.12\.1/perl/lib/Carp\.pm line 229\.
> > > Writing MYMETA\.yml and MYMETA\.json
> > > Writing MYMETA\.yml and MYMETA\.json
> > > Writing MYMETA\.yml and MYMETA\.json
> > >
> > > See also
> > > http&#8203;://www\.cpantesters\.org/cpan/report/74da0c86\-6c12\-1014\-8ecb\-
> > > 069185000ecc
> > >
> > > Tested on Strawberry perl 5\.25\.12\, 5\.25\.10 and 5\.25\.8 32\-bit int\,
> > > Windows XP\. Does not fail on 5\.24\.0\. Has problems on Linux too\, but
> > > different\, see http&#8203;://matrix\.cpantesters\.org/?dist=QWizard\+3\.15 \.
> > >
> > > Also reported in modules bug tracker&#8203;:
> > > https://rt.cpan.org/Ticket/Display.html?id=121401
> > >
> >
> > Bisection \(manual\) on Linux suggests that the following commit is
> > responsible&#8203;:
> >
> > \#\#\#\#\#
> > commit 8b0c3377906a6f991cd6c21a674bf9561d85e3cb
> > Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
> > AuthorDate&#8203;: Wed Oct 5 10&#8203;:10&#8203;:56 2016 \+0100
> > Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
> > CommitDate&#8203;: Wed Oct 26 08&#8203;:37&#8203;:27 2016 \+0100
> >
> > Better optimise array and hash assignment
> >
> > \[perl \#127999\] Slowdown in split \+ list assign
> > \.\.\.
> > \#\#\#\#\#
> >
> > Dave\, can you take a look?
> 
> Given Zefram's daignosis that its an issue with @&#8203;DB&#8203;::args viewing args
> on
> the stack which aren't ref counted\, that commit is likely to be a ref
> herring \- it is likely to have just altered whether some stack args
> happen
> to have had their lives artificially extended\.

At about lines 655 to 658 of ExtUtils/MakeMaker\.pm we have&#8203;:

&nbsp;    \# This is for old Makefiles written pre 5\.00\, will go away
&nbsp;    if \( Carp&#8203;::longmess\(""\) =~ /runsubdirpl/s \)\{
&nbsp;        carp\("WARNING&#8203;: Please rerun 'perl Makefile\.PL' to regenerate your Makefiles\\n"\);
&nbsp;    \}

Commenting out those 3 lines of code allows 'perl Makefile\.PL' step to run to completion on Windows for me\.
\(I was initially getting the same error as reported by the OP\.\)

HTH

Cheers\,
Rob

**Comment by p5pRT** [comment]
### From @iabyn

Doesn't seem to be a 5\.26\.0 blocker\. Removing\.

**Comment by jkeenan** [comment]
The QWizard distro seems to be doing fairly well at [CPANtesters](http://matrix.cpantesters.org/?dist=QWizard).

@sisyphus @chorny Are you still having problems with QWizard, particularly on Windows?

If not, then we can close this ticket.

Thank you very much.
Jim Keenan

**Comment by sisyphus** [comment]
Apparently it has a dependency on CGI.pm, but fails to acknowledge that.
I just tried 'cpan -i QWizard' on a Windows perl-5.30.0 that didn't have CGI.pm, and it failed tests because CGI.pm couldn't be loaded.
A simple 'cpan -i CGI' followed by another 'cpan -i QWizard' worked fine.

Is that a reason to keep the ticket open ?
(I've no objection to it being closed.)
Cheers,
Rob

**Comment by jkeenan** [comment]
> Apparently it has a dependency on CGI.pm, but fails to acknowledge that.
> I just tried 'cpan -i QWizard' on a Windows perl-5.30.0 that didn't have CGI.pm, and it failed tests because CGI.pm couldn't be loaded.
> A simple 'cpan -i CGI' followed by another 'cpan -i QWizard' worked fine.
> 
> Is that a reason to keep the ticket open ?
> (I've no objection to it being closed.)
> Cheers,
> Rob

No further correspondence or complaints, so, closing.
