### ISSUE TITLE
testsuite lib/Benchmark unresponsive on older SPARC Solaris 10 server

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16003]
Migrated from [rt.perl.org#131531](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131531) (status was 'open')

Searchable as RT131531$

**Comment by p5pRT** [comment]
### From dclarke@blastwave.org

#### Created by dclarke@blastwave.org



Please ignore the version of perlbug used to submit this bug\.

I performed a normal compile of Perl 5\.26\.0 from the release 
tarball\.  No issues seen during compile\.

Ran the testsuite and the process seemed fine until the Benchmark
test \.\./lib/Benchmark\.t which seemed to become nonresponsive and
sat running for two days before I hit CTRL\-C to stop it\. 

CPU usage was seen to be at 98% for the entire duration\. 

Some details here are the environment variables in place during
the compile and then testsuite run : 

mimas$ env | sort 
AR=/usr/ccs/bin/ar
AS=/usr/ccs/bin/as
AWK=/usr/local/bin/gawk
BUILD=/usr/local/build
CC=/opt/solarisstudio12\.4/bin/cc
CFLAGS=\-errfmt=error \-erroff=%none \-errshort=full \-xstrconst \-xildoff \-m64 \-xmemalign=8s \-xnolibmil \-Xa \-xcode=pic32 \-xregs=no%appl \-xlibmieee \-mc \-g \-xs \-ftrap=%none \-Qy \-xbuiltin=%none \-xdebugformat=dwarf \-xunroll=1 \-D\_TS\_ERRNO \-D\_POSIX\_PTHREAD\_SEMANTICS \-D\_LARGEFILE64\_SOURCE
COLUMNS=132
CONFIG\_SHELL=/usr/local/bin/bash
CPPFLAGS=\-I/usr/local/include \-D\_TS\_ERRNO \-D\_POSIX\_PTHREAD\_SEMANTICS \-D\_LARGEFILE64\_SOURCE
CXX=/opt/solarisstudio12\.4/bin/CC
CXXFLAGS=\-dalign \-erroff=%none \-errtags=yes \-ftrap=%none \-g \-xcode=pic32 \-m64 \-mc \-xunroll=1 \-xbuiltin=%none \-xdepend=no \-xnolibmopt \-xlinkopt=0 \-xnolibmil \-xregs=no%appl \-xs \-D\_POSIX\_PTHREAD\_SEMANTICS \-D\_LARGEFILE64\_SOURCE \-D\_TS\_ERRNO
EDITOR=/usr/xpg6/bin/vi
GREP=/usr/xpg4/bin/grep
HOME=/export/home/dclarke
JAVA\_HOME=/usr/jdk/latest
LANG=C
LC\_ALL=C
LC\_COLLATE=C
LC\_CTYPE=C
LC\_MESSAGES=C
LC\_MONETARY=C
LC\_NUMERIC=C
LC\_TIME=C
LD=/usr/ccs/bin/sparcv9/ld
LD\_OPTIONS=\-64 \-R/usr/local/lib \-L/usr/local/lib
LD\_RUN\_PATH=/usr/local/lib
LINES=43
LOGNAME=dclarke
M4=/usr/local/bin/m4
MACHTYPE=sparc\-sun\-solaris
MAIL=/usr/mail/dclarke
MAKE=/usr/local/bin/gmake
NM=/usr/ccs/bin/sparcv9/nm \-p
OLDPWD=/usr/local/build
OSTYPE=solaris
PATH=/usr/local/bin&#8203;:/usr/local/sbin&#8203;:/usr/local/openssl/bin&#8203;:/usr/xpg6/bin&#8203;:/usr/xpg4/bin&#8203;:/usr/ccs/bin&#8203;:/opt/developerstudio12\.5/bin&#8203;:/usr/bin&#8203;:/sbin&#8203;:/bin&#8203;:/usr/sbin&#8203;:/usr/dt/bin&#8203;:/usr/openwin/bin&#8203;:/opt/schily/bin
PERL=/usr/local/bin/perl
PKG\_CONFIG\_PATH=/usr/local/lib/pkgconfig
POSIXLY\_CORRECT=1
PWD=/usr/local/build/perl\-5\.26\.0\_SunOS\_5\.10\.001
SED=/usr/local/bin/sed
SHELL=/bin/bash
SHLVL=2
SRC=/usr/local/src
SSH\_CLIENT=99\.253\.103\.29 40168 443
SSH\_CONNECTION=99\.253\.103\.29 40168 68\.179\.116\.203 443
SSH\_TTY=/dev/pts/1
STY=2411\.pts\-1\.mimas
TERM=xterm
TZ=GMT0
USER=dclarke
VISUAL=/usr/xpg6/bin/vi
WINDOW=7
XTERM\_LOCALE=C
\_=/usr/xpg4/bin/env


I then tried to run the test in a more verbose manner : 

$ LD\_LIBRARY\_PATH=/usr/local/build/perl\-5\.26\.0\_SunOS\_5\.10\.001 \./perl harness \-v \.\./lib/Benchmark\.t 
\.\./lib/Benchmark\.t \.\. 
1\.\.213
ok 1 \- 'Ensure we can create a benchmark object' isa 'Benchmark'


While this was running and seemingly wedged I ran truss also : 

mimas \# ps \-ef | grep perl
 dclarke 18648 13068   0 17&#8203;:16&#8203;:55 pts/11      0&#8203;:00 \./perl harness \-v \.\./lib/Benchmark\.t
&nbsp;    root 18650 13332   0 17&#8203;:20&#8203;:11 pts/2       0&#8203;:00 grep perl
 dclarke 18649 18648  97 17&#8203;:16&#8203;:58 pts/11      0&#8203;:00 \./perl \-I\.\. \-MTestInit=U1 \.\./lib/Benchmark\.t
mimas \# 
mimas \# truss \-faeild \-p 18649
Base time stamp&#8203;:  1496856031\.9867  \[ Wed Jun  7 17&#8203;:20&#8203;:31 GMT 2017 \]
18649/1&#8203;:        psargs&#8203;: \./perl \-I\.\. \-MTestInit=U1 \.\./lib/Benchmark\.t
18649/1&#8203;:        11\.2054 time\(\)                                          = 1496856043
18649/1&#8203;:        11\.2070 times\(0xFFFFFFFF7FFFEFA0\)                       = 170345051
18649/1&#8203;:        33\.5034 time\(\)                                          = 1496856065
18649/1&#8203;:        33\.5049 times\(0xFFFFFFFF7FFFEFA0\)                       = 170347281
18649/1&#8203;:        57\.6346 time\(\)                                          = 1496856089
18649/1&#8203;:        57\.6360 times\(0xFFFFFFFF7FFFEFA0\)                       = 170349694
18649/1&#8203;:        84\.5803 time\(\)                                          = 1496856116
18649/1&#8203;:        84\.5817 times\(0xFFFFFFFF7FFFEFA0\)                       = 170352389
18649/1&#8203;:        114\.3768        time\(\)                                          = 1496856146
18649/1&#8203;:        114\.3782        times\(0xFFFFFFFF7FFFEFA0\)                       = 170355368
18649/1&#8203;:        146\.8824        time\(\)                                          = 1496856178
18649/1&#8203;:        146\.8838        times\(0xFFFFFFFF7FFFEFA0\)                       = 170358619
18649/1&#8203;:        183\.2270        time\(\)                                          = 1496856215
18649/1&#8203;:        183\.2284        times\(0xFFFFFFFF7FFFEFA0\)                       = 170362253
18649/1&#8203;:        222\.5844        time\(\)                                          = 1496856254
18649/1&#8203;:        222\.5859        times\(0xFFFFFFFF7FFFEFA0\)                       = 170366189
18649/1&#8203;:        265\.6841        time\(\)                                          = 1496856297
18649/1&#8203;:        265\.6855        times\(0xFFFFFFFF7FFFEFA0\)                       = 170370499
18649/1&#8203;:        313\.7977        time\(\)                                          = 1496856345
18649/1&#8203;:        313\.7991        times\(0xFFFFFFFF7FFFEFA0\)                       = 170375310
mimas \# 
mimas \# 

Seemed to be in a loop doing not very much\. 

On the advice of some folks in the perl IRC chan p5p we ran a 
smaller test : 

$ /usr/local/bin/wget  https://rt-archive.perl.org/perl5/Ticket/Attachment/1463473/794827/xBenchmark.t 
\-\-2017\-06\-07 18&#8203;:14&#8203;:14\-\-  https://rt-archive.perl.org/perl5/Ticket/Attachment/1463473/794827/xBenchmark.t
Resolving rt\.perl\.org \(rt\.perl\.org\)\.\.\. 207\.171\.7\.176
Connecting to rt\.perl\.org \(rt\.perl\.org\)|207\.171\.7\.176|&#8203;:443\.\.\. connected\.
HTTP request sent\, awaiting response\.\.\. 302 Found
Location&#8203;: /Public/Ticket/Attachment/1463473/794827/xBenchmark\.t \[following\]
\-\-2017\-06\-07 18&#8203;:14&#8203;:16\-\-  https://rt-archive.perl.org/perl5/Ticket/Attachment/1463473/794827/xBenchmark.t
Connecting to rt\.perl\.org \(rt\.perl\.org\)|207\.171\.7\.176|&#8203;:443\.\.\. connected\.
HTTP request sent\, awaiting response\.\.\. 200 OK
Length&#8203;: unspecified \[text/plain\]
Saving to&#8203;: 'xBenchmark\.t'

&nbsp;     0K                                                        3\.16M=0\.001s

2017\-06\-07 18&#8203;:14&#8203;:16 \(3\.16 MB/s\) \- 'xBenchmark\.t' saved \[2711\]

dclarke@&#8203;mimas\_$ file xBenchmark\.t
xBenchmark\.t&#8203;: executable \./perl script

dclarke@&#8203;mimas\_$ cd \.\./t
dclarke@&#8203;mimas\_$ LD\_LIBRARY\_PATH=/usr/local/build/perl\-5\.26\.0\_SunOS\_5\.10\.001 \./perl harness \-v \.\./lib/xBenchmark\.t 
\.\./lib/xBenchmark\.t \.\. 
1\.\.10
ok 1 \- 'Ensure we can create a benchmark object' isa 'Benchmark'

Again this seemed wedged and nonresponsive\. 

Here is some data from the built perl 5\.26\.0 : 


mimas$ pwd
/usr/local/build/perl\-5\.26\.0\_SunOS\_5\.10\.001
mimas$ cd \.\.
mimas$ LD\_LIBRARY\_PATH=/usr/local/lib /usr/local/bin/perl \-Ilib \-V
Summary of my perl5 \(revision 5 version 20 subversion 1\) configuration&#8203;:
&nbsp;   
&nbsp;  Platform&#8203;:
&nbsp;    osname=solaris\, osvers=2\.10\, archname=sun4\-solaris\-64
&nbsp;    uname='sunos ns1 5\.10 generic\_148888\-05 sun4u sparc sunw\,ultraax\-i2 '
&nbsp;    config\_args='\-Dprefix=/usr/local \-Dmksymlinks \-Accflags=\-errfmt=error \-erroff=%none \-errshort=full \-xstrconst \-xildoff \-m64 \-xmemalign=8s \-xnolibmil \-Xa \-xcode=pic32 \-xregs=no%appl \-xlibmieee \-mc \-g \-xs \-ftrap=%none \-Qy \-xbuiltin=%none \-xdebugformat=dwarf \-xunroll=1 \-xtarget=ultra2'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    use64bitint=define\, use64bitall=define\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-errfmt=error \-erroff=%none \-errshort=full \-xstrconst \-xildoff \-m64 \-xmemalign=8s \-xnolibmil \-Xa \-xcode=pic32 \-xregs=no%appl \-xlibmieee \-mc \-g \-xs \-ftrap=%none \-Qy \-xbuiltin=%none \-xdebugformat=dwarf \-xunroll=1 \-xtarget=ultra2 \-I/usr/local/include \-m64 \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-xO1'\,
&nbsp;    cppflags='\-errfmt=error \-erroff=%none \-errshort=full \-xstrconst \-xildoff \-m64 \-xmemalign=8s \-xnolibmil \-Xa \-xcode=pic32 \-xregs=no%appl \-xlibmieee \-mc \-g \-xs \-ftrap=%none \-Qy \-xbuiltin=%none \-xdebugformat=dwarf \-xunroll=1 \-xtarget=ultra2 \-I/usr/local/include'
&nbsp;    ccversion='Sun C 5\.9 SunOS\_sparc Patch 124867\-16 2010/08/11'\, gccversion=''\, gccosandvers=''
&nbsp;    intsize=4\, longsize=8\, ptrsize=8\, doublesize=8\, byteorder=87654321
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/opt/studio/SOS12/SUNWspro/prod/lib/sparcvis/64 \-L/opt/studio/SOS12/SUNWspro/prod/lib/v9 \-L/lib/sparcv9 \-L/usr/local/lib \-m64 '
&nbsp;    libpth=/usr/lib/sparcv9 /usr/ccs/lib/sparcv9 /opt/studio/SOS12/SUNWspro/prod/lib/sparcvis/64 /opt/studio/SOS12/SUNWspro/prod/lib/v9 /lib/sparcv9 /usr/local/lib
&nbsp;    libs=\-lsocket \-lnsl \-ldl \-lm \-lc
&nbsp;    perllibs=\-lsocket \-lnsl \-ldl \-lm \-lc
&nbsp;    libc=/usr/lib/sparcv9/libc\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags='\-xregs=no%appl \-xmemalign=8s \-xnolibmil \-xcode=pic32 \-mc \-g \-xs \-Qy \-KPIC'\, lddlflags=' \-G \-m64 \-L/opt/studio/SOS12/SUNWspro/prod/lib/sparcvis/64 \-L/opt/studio/SOS12/SUNWspro/prod/lib/v9 \-L/lib/sparcv9 \-L/usr/local/lib'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;: HAS\_TIMES PERLIO\_LAYERS PERL\_DONT\_CREATE\_GVSV
&nbsp;                        PERL\_HASH\_FUNC\_ONE\_AT\_A\_TIME\_HARD PERL\_MALLOC\_WRAP
&nbsp;                        PERL\_NEW\_COPY\_ON\_WRITE PERL\_PRESERVE\_IVUV
&nbsp;                        USE\_64\_BIT\_ALL USE\_64\_BIT\_INT USE\_LARGE\_FILES
&nbsp;                        USE\_LOCALE USE\_LOCALE\_COLLATE USE\_LOCALE\_CTYPE
&nbsp;                        USE\_LOCALE\_NUMERIC USE\_PERLIO USE\_PERL\_ATOF
&nbsp;  Built under solaris
&nbsp;  Compiled at Nov 11 2014 22&#8203;:23&#8203;:10
&nbsp;  %ENV&#8203;:
&nbsp;    PERL="/usr/local/bin/perl"
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.20\.1/sun4\-solaris\-64
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.20\.1
&nbsp;    /usr/local/lib/perl5/5\.20\.1/sun4\-solaris\-64
&nbsp;    /usr/local/lib/perl5/5\.20\.1
&nbsp;    \.
mimas$ 


Seems to be a single test failure on a machine which is older and slower
and with limited memory\. In this case 1536MB of memory\. However the
system is on contract and is entirely up to date patchwise and the
compiler is Oracle Studio 12\.4 cc with CFLAGS seen above\.  Note the
debug options are used to allow later single stepping and debugging of
downstream projects if needed\.

Dennis Clarke
dclarke@&#8203;blastwave\.org

<details><summary>Perl Info</summary>

```

Flags:
    category=install
    severity=medium

Site configuration information for perl 5.20.1:

Configured by root at Tue Nov 11 21:30:40 GMT 2014.

Summary of my perl5 (revision 5 version 20 subversion 1) configuration:
   
  Platform:
    osname=solaris, osvers=2.10, archname=sun4-solaris-64
    uname='sunos ns1 5.10 generic_148888-05 sun4u sparc sunw,ultraax-i2 '
    config_args='-Dprefix=/usr/local -Dmksymlinks -Accflags=-errfmt=error -erroff=%none -errshort=full -xstrconst -xildoff -m64 -xmemalign=8s -xnolibmil -Xa -xcode=pic32 -xregs=no%appl -xlibmieee -mc -g -xs -ftrap=%none -Qy -xbuiltin=%none -xdebugformat=dwarf -xunroll=1 -xtarget=ultra2'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=undef, usemultiplicity=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-errfmt=error -erroff=%none -errshort=full -xstrconst -xildoff -m64 -xmemalign=8s -xnolibmil -Xa -xcode=pic32 -xregs=no%appl -xlibmieee -mc -g -xs -ftrap=%none -Qy -xbuiltin=%none -xdebugformat=dwarf -xunroll=1 -xtarget=ultra2 -I/usr/local/include -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-xO1',
    cppflags='-errfmt=error -erroff=%none -errshort=full -xstrconst -xildoff -m64 -xmemalign=8s -xnolibmil -Xa -xcode=pic32 -xregs=no%appl -xlibmieee -mc -g -xs -ftrap=%none -Qy -xbuiltin=%none -xdebugformat=dwarf -xunroll=1 -xtarget=ultra2 -I/usr/local/include'
    ccversion='Sun C 5.9 SunOS_sparc Patch 124867-16 2010/08/11', gccversion='', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=87654321
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/opt/studio/SOS12/SUNWspro/prod/lib/sparcvis/64 -L/opt/studio/SOS12/SUNWspro/prod/lib/v9 -L/lib/sparcv9 -L/usr/local/lib -m64 '
    libpth=/usr/lib/sparcv9 /usr/ccs/lib/sparcv9 /opt/studio/SOS12/SUNWspro/prod/lib/sparcvis/64 /opt/studio/SOS12/SUNWspro/prod/lib/v9 /lib/sparcv9 /usr/local/lib
    libs=-lsocket -lnsl -ldl -lm -lc
    perllibs=-lsocket -lnsl -ldl -lm -lc
    libc=/usr/lib/sparcv9/libc.so, so=so, useshrplib=false, libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags=' '
    cccdlflags='-xregs=no%appl -xmemalign=8s -xnolibmil -xcode=pic32 -mc -g -xs -Qy -KPIC', lddlflags=' -G -m64 -L/opt/studio/SOS12/SUNWspro/prod/lib/sparcvis/64 -L/opt/studio/SOS12/SUNWspro/prod/lib/v9 -L/lib/sparcv9 -L/usr/local/lib'



@INC for perl 5.20.1:
    /usr/local/lib/perl5/site_perl/5.20.1/sun4-solaris-64
    /usr/local/lib/perl5/site_perl/5.20.1
    /usr/local/lib/perl5/5.20.1/sun4-solaris-64
    /usr/local/lib/perl5/5.20.1
    .


Environment for perl 5.20.1:
    HOME=/export/home/dclarke
    LANG=C
    LANGUAGE (unset)
    LC_ALL=C
    LC_COLLATE=C
    LC_CTYPE=C
    LC_MESSAGES=C
    LC_MONETARY=C
    LC_NUMERIC=C
    LC_TIME=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/usr/local/bin:/usr/local/sbin:/usr/local/openssl/bin:/usr/xpg6/bin:/usr/xpg4/bin:/usr/ccs/bin:/opt/developerstudio12.5/bin:/usr/bin:/sbin:/bin:/usr/sbin:/usr/dt/bin:/usr/openwin/bin:/opt/schily/bin
    PERL=/usr/local/bin/perl
    PERL_BADLANG (unset)
    SHELL=/bin/bash

```
</details>

**Comment by p5pRT** [comment]
### From @jkeenan

On Wed\, 07 Jun 2017 19&#8203;:57&#8203;:52 GMT\, dclarke@&#8203;blastwave\.org wrote&#8203;:
> 
> 
> I performed a normal compile of Perl 5\.26\.0 from the release
> tarball\.  No issues seen during compile\.
> 
> Ran the testsuite and the process seemed fine until the Benchmark
> test \.\./lib/Benchmark\.t which seemed to become nonresponsive and
>  sat running for two days before I hit CTRL\-C to stop it\.
> 

More diagnostic suggestions\.  Two possible approaches&#8203;:

1\. via 'git'

If you have 'git' on the machine in question\, do a checkout of the 'jkeenan/131531\-benchmark' from our repository\.  \(Call&#8203;: 'perldoc perlhack' and 'perldoc perlgit' for more details\.\)  Configure as you normally would\.  Call 'make' as you normally would\.  Then run \(I'm guessing somewhat here\)&#8203;:

LD\_LIBRARY\_PATH=\`pwd\` \./perl \-Ilib lib/yBenchmark\.t

'yBenchmark\.t' is a very stripped\-down version of lib/Benchmark\.t\.

2\. via already\-checked\-out tarball

Store the version of 'lib/Benchmark\.pm' in build directory someplace safe\.  Replace it with the 'Benchmark\.pm' attached\, to which I have added extra debugging statements\.  Place attached 'yBenchmark\.t' in lib/\.  Call the same command as \(1\) above\.

In either approach\, assuming you get the inordinate slowness\, you can try to use the Perl debugger to step through the test file\, probably like this&#8203;:

\#\#\#\#\#
LD\_LIBRARY\_PATH=\`pwd\` \./perl \-Ilib \-d lib/yBenchmark\.t
\#\#\#\#\#

Good luck\!

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @jkeenan

[Benchmark.pm](https://rt-archive.perl.org/perl5/Ticket/Attachment/1464498/795198/Benchmark.pm)

**Comment by p5pRT** [comment]
### From @jkeenan

\#\!\./perl \-w
\# https://rt-archive.perl.org/perl5/Ticket/Display.html?id=131531
BEGIN \{
&nbsp;    chdir 't' if \-d 't';
&nbsp;    @&#8203;INC = \('\.\./lib'\);
\}

use warnings;
use strict;

use Benchmark qw\(&#8203;:all\);
$Benchmark&#8203;::Debug\+\+;

my $foo = 0;
my $reps = 5;
my $coderef = sub \{\+\+$foo\};
my $t = timeit\($reps\, $coderef\);
\($t\->isa\('Benchmark'\)\)
&nbsp;    ? print "timeit CODEREF returned a Benchmark object\\n"
&nbsp;    : print "timeit CODEREF did NOT return a Benchmark object\\n";
\($foo == $reps\)
&nbsp;    ? print "benchmarked code was run $reps times\\n"
&nbsp;    : print "FAIL&#8203;: requested $reps reps\, but $foo were run\\n";

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by jkeenan** [comment]
Emailed original poster today to inform re issue tracker change.

**Comment by jkeenan** [comment]
> ### From [dclarke@blastwave.org](mailto:dclarke@blastwave.org)
> #### Created by [dclarke@blastwave.org](mailto:dclarke@blastwave.org)
> 
> Please ignore the version of perlbug used to submit this bug.
> 
> I performed a normal compile of Perl 5.26.0 from the release tarball. No issues seen during compile.
> 
> Ran the testsuite and the process seemed fine until the Benchmark test ../lib/Benchmark.t which seemed to become nonresponsive and sat running for two days before I hit CTRL-C to stop it.
> 
> CPU usage was seen to be at 98% for the entire duration.
> 

We haven't heard from the original poster since June 2017.  I am taking this ticket for the purpose of closing it (and corresponding p.r. https://github.com/Perl/perl5/pull/18777) at the end of this month unless we get a response.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> > ### From [dclarke@blastwave.org](mailto:dclarke@blastwave.org)
> > #### Created by [dclarke@blastwave.org](mailto:dclarke@blastwave.org)
> > Please ignore the version of perlbug used to submit this bug.
> > I performed a normal compile of Perl 5.26.0 from the release tarball. No issues seen during compile.
> > Ran the testsuite and the process seemed fine until the Benchmark test ../lib/Benchmark.t which seemed to become nonresponsive and sat running for two days before I hit CTRL-C to stop it.
> > CPU usage was seen to be at 98% for the entire duration.
> 
> We haven't heard from the original poster since June 2017. I am taking this ticket for the purpose of closing it (and corresponding p.r. #18777) at the end of this month unless we get a response.
> 

Closing ticket as per schedule.
