### ISSUE TITLE
'miniperl' not well documented

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16158]
Migrated from [rt.perl.org#132137](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132137) (status was 'open')

Searchable as RT132137$

**Comment by p5pRT** [comment]
### From @jkeenan

I would have expected to be able to find a paragraph or two underneath 
'pod/' describing the purpose and functionality of 'miniperl'\.

As the attachment demonstrates\, no such documentation exists\.

Is that deliberate?

If not\, could we add a paragraph about 'miniperl'?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From @jkeenan

Summary of my perl5 \(revision 5 version 27 subversion 4\) configuration&#8203;:
&nbsp;  Commit id&#8203;: e271727ef27311aecfec2f87d6c8eecdb3f09d05
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux
&nbsp;    osvers=4\.4\.0\-93\-generic
&nbsp;    archname=x86\_64\-linux
&nbsp;    uname='linux zareason 4\.4\.0\-93\-generic \#116\-ubuntu smp fri aug 11 21&#8203;:17&#8203;:51 utc 2017 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;    config\_args='\-des \-Dusedevel'
&nbsp;    hint=recommended
&nbsp;    useposix=true
&nbsp;    d\_sigaction=define
&nbsp;    useithreads=undef
&nbsp;    usemultiplicity=undef
&nbsp;    use64bitint=define
&nbsp;    use64bitall=define
&nbsp;    uselongdouble=undef
&nbsp;    usemymalloc=n
&nbsp;    default\_inc\_excludes\_dot=define
&nbsp;    bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'
&nbsp;    ccflags ='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'
&nbsp;    optimize='\-O2'
&nbsp;    cppflags='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''
&nbsp;    gccversion='5\.4\.0 20160609'
&nbsp;    gccosandvers=''
&nbsp;    intsize=4
&nbsp;    longsize=8
&nbsp;    ptrsize=8
&nbsp;    doublesize=8
&nbsp;    byteorder=12345678
&nbsp;    doublekind=3
&nbsp;    d\_longlong=define
&nbsp;    longlongsize=8
&nbsp;    d\_longdbl=define
&nbsp;    longdblsize=16
&nbsp;    longdblkind=3
&nbsp;    ivtype='long'
&nbsp;    ivsize=8
&nbsp;    nvtype='double'
&nbsp;    nvsize=8
&nbsp;    Off\_t='off\_t'
&nbsp;    lseeksize=8
&nbsp;    alignbytes=8
&nbsp;    prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'
&nbsp;    ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/5/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib /lib64 /usr/lib64
&nbsp;    libs=\-lpthread \-lnsl \-ldb \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.23\.so
&nbsp;    so=so
&nbsp;    useshrplib=false
&nbsp;    libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.23'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs
&nbsp;    dlext=so
&nbsp;    d\_dlsymun=undef
&nbsp;    ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'
&nbsp;    lddlflags='\-shared \-O2 \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;:
&nbsp;    HAS\_TIMES
&nbsp;    PERLIO\_LAYERS
&nbsp;    PERL\_COPY\_ON\_WRITE
&nbsp;    PERL\_DONT\_CREATE\_GVSV
&nbsp;    PERL\_MALLOC\_WRAP
&nbsp;    PERL\_OP\_PARENT
&nbsp;    PERL\_PRESERVE\_IVUV
&nbsp;    PERL\_USE\_DEVEL
&nbsp;    USE\_64\_BIT\_ALL
&nbsp;    USE\_64\_BIT\_INT
&nbsp;    USE\_LARGE\_FILES
&nbsp;    USE\_LOCALE
&nbsp;    USE\_LOCALE\_COLLATE
&nbsp;    USE\_LOCALE\_CTYPE
&nbsp;    USE\_LOCALE\_NUMERIC
&nbsp;    USE\_LOCALE\_TIME
&nbsp;    USE\_PERLIO
&nbsp;    USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Sep 16 2017 10&#8203;:17&#8203;:33
&nbsp;  %ENV&#8203;:
&nbsp;    PERLBREW\_BASHRC\_VERSION="0\.78"
&nbsp;    PERLBREW\_HOME="/home/jkeenan/\.perlbrew"
&nbsp;    PERLBREW\_MANPATH="/home/jkeenan/perl5/perlbrew/perls/perl\-5\.26\.0/man"
&nbsp;    PERLBREW\_PATH="/home/jkeenan/perl5/perlbrew/bin&#8203;:/home/jkeenan/perl5/perlbrew/perls/perl\-5\.26\.0/bin"
&nbsp;    PERLBREW\_PERL="perl\-5\.26\.0"
&nbsp;    PERLBREW\_ROOT="/home/jkeenan/perl5/perlbrew"
&nbsp;    PERLBREW\_VERSION="0\.78"
&nbsp;    PERL\_WORKDIR="/home/jkeenan/gitwork/perl"
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.27\.4/x86\_64\-linux
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.27\.4
&nbsp;    /usr/local/lib/perl5/5\.27\.4/x86\_64\-linux
&nbsp;    /usr/local/lib/perl5/5\.27\.4

**Comment by p5pRT** [comment]
### From @jkeenan

pod/perlgit\.pod&#8203;:720&#8203;:If you make any changes that affect miniperl or core routines that have
pod/perlgit\.pod&#8203;:721&#8203;:different code paths for miniperl\, be sure to run C\<make minitest>\.
pod/perlgit\.pod\-722\-This will catch problems that even the full test suite will not catch
pod/perlgit\.pod&#8203;:723&#8203;:because it runs a subset of tests under miniperl rather than perl\.
pod/perlgit\.pod\-724\-
\-\-
pod/perl5260delta\.pod&#8203;:2078&#8203;:F\<Configure> now builds C\<miniperl> and C\<generate\_uudmap> if you
pod/perl5260delta\.pod\-2079\-invoke it with C\<\-Dusecrosscompiler> but not C\<\-Dtargethost=somehost>\.
\-\-
pod/Makefile\.SH&#8203;:63&#8203;:PERL = \.\./miniperl
pod/Makefile\.SH\-64\-PERLILIB = $\(PERL\) \-I\.\./lib
\-\-
pod/perlinterp\.pod&#8203;:28&#8203;:The action begins in F\<perlmain\.c>\. \(or F\<miniperlmain\.c> for miniperl\)
pod/perlinterp\.pod\-29\-This is very high\-level code\, enough to fit on a single screen\, and it
\-\-
pod/Makefile&#8203;:25&#8203;:PERL = \.\./miniperl
pod/Makefile\-26\-PERLILIB = $\(PERL\) \-I\.\./lib
\-\-
pod/perl5123delta\.pod&#8203;:46&#8203;:A separate DTrace is now build for miniperl\, which means that perl can be
pod/perl5123delta\.pod\-47\-compiled with \-Dusedtrace on Solaris again\.
\-\-
pod/perl5180delta\.pod&#8203;:2209&#8203;:with miniperl's C\<glob> operator \(which uses the C\<perlglob> program\)
pod/perl5180delta\.pod\-2210\-deleting the PATH environment variable \[perl \#113798\]\.
\-\-
pod/perl5240delta\.pod&#8203;:1190&#8203;:The Win32 miniperl now has a real C\<getcwd> which increases build performance
pod/perl5240delta\.pod&#8203;:1191&#8203;:resulting in C\<getcwd\(\)> being 605x faster in Win32 miniperl\.
pod/perl5240delta\.pod\-1192\-
\-\-
pod/perl5240delta\.pod&#8203;:1456&#8203;:During miniperl's process startup\, during the build process\, 4 to 8 IO calls
pod/perl5240delta\.pod\-1457\-related to the process starting F\<\.pl> and the F\<buildcustomize\.pl> file were
\-\-
pod/perl5220delta\.pod&#8203;:2400&#8203;:Pathtools no longer tries to load XS on miniperl\. This speeds up building perl
pod/perl5220delta\.pod\-2401\-slightly\.
\-\-
pod/perl5220delta\.pod&#8203;:2532&#8203;:F\<miniperl\.exe> is now built with C\<\-fno\-strict\-aliasing>\, allowing 64\-bit
pod/perl5220delta\.pod\-2533\-builds to complete on GCC 4\.8\.
\-\-
pod/perlhack\.pod&#8203;:856&#8203;:Run F\<miniperl> on F\<t/base>\, F\<t/comp>\, F\<t/cmd>\, F\<t/run>\, F\<t/io>\,
pod/perlhack\.pod\-857\-F\<t/op>\, F\<t/uni> and F\<t/mro> tests\.
\-\-
pod/perlhack\.pod&#8203;:1065&#8203;:    cc \-fstack\-protector \-L/usr/local/lib \-o miniperl \\
pod/perlhack\.pod\-1066\-      gv\.o toke\.o perly\.o pad\.o regcomp\.o dump\.o util\.o \\
\-\-
pod/perlhack\.pod&#8203;:1076&#8203;:    makefile&#8203;:348&#8203;: recipe for target 'miniperl' failed
pod/perlhack\.pod&#8203;:1077&#8203;:    make&#8203;: \*\*\* \[miniperl\] Error 1
pod/perlhack\.pod\-1078\-
\-\-
pod/perlmodlib\.PL&#8203;:1&#8203;:\#\!\.\./miniperl
pod/perlmodlib\.PL\-2\-
\-\-
pod/perl5200delta\.pod&#8203;:1913&#8203;:invocations of F\<miniperl> are no longer made\.
pod/perl5200delta\.pod\-1914\-
\-\-
pod/perl5200delta\.pod&#8203;:1944&#8203;:We now build binaries for miniperl and generate\_uudmap to be used on the host\,
pod/perl5200delta\.pod&#8203;:1945&#8203;:rather than running every miniperl call on the target; this means that\, short
pod/perl5200delta\.pod\-1946\-of 'make test'\, we no longer need access to the target system once Configure is
\-\-
pod/perl5200delta\.pod&#8203;:2192&#8203;:\(for B\<miniperl\.exe> only\)\.
pod/perl5200delta\.pod\-2193\-\[L\<perl \#121119|https://rt.perl.org/Public/Bug/Display.html?id=121119>]
\-\-
pod/perl5200delta\.pod&#8203;:2216&#8203;:When building a 64\-bit perl\, an uninitialized memory read in B\<miniperl\.exe>\,
pod/perl5200delta\.pod\-2217\-used during the build process\, could lead to a 4GB B\<wperl\.exe> being created\.
\-\-
pod/perl5203delta\.pod&#8203;:150&#8203;:B\<miniperl\.exe> is now built with B\<\-fno\-strict\-aliasing>\, allowing 64\-bit
pod/perl5203delta\.pod\-151\-builds to complete with GCC 4\.8\.
\-\-
pod/perl5120delta\.pod&#8203;:470&#8203;:To support the bootstrapping process\, F\<miniperl> no longer builds with
pod/perl5120delta\.pod\-471\-UTF\-8 support in the regexp engine\.
\-\-
pod/perl5120delta\.pod&#8203;:474&#8203;:Without this there's a bootstrapping problem\, as miniperl can't load
pod/perl5120delta\.pod\-475\-the UTF\-8 components of the regexp engine\, because they're not yet built\.
\-\-
pod/perl5120delta\.pod&#8203;:479&#8203;:F\<miniperl>'s @&#8203;INC is now restricted to just C\<\-I\.\.\.>\, the split of
pod/perl5120delta\.pod\-480\-C\<$ENV\{PERL5LIB\}>\, and "C\<\.>"
\-\-
pod/perl5120delta\.pod&#8203;:1609&#8203;:issue with linking C\<miniperl> has been fixed in the process\.
pod/perl5120delta\.pod\-1610\-
\-\-
pod/perl5160delta\.pod&#8203;:3031&#8203;:Under miniperl \(used to configure modules when perl itself is built\)\,
pod/perl5160delta\.pod\-3032\-C\<glob> now clears %ENV before calling csh\, since the latter croaks on some
\-\-
pod/perl58delta\.pod&#8203;:2083&#8203;:VOS\.  The older methods\, which build miniperl\, are still
pod/perl58delta\.pod\-2084\-available\.  See L\<perlvos>\. \[561\+\]
\-\-
pod/perl5161delta\.pod&#8203;:55&#8203;:with miniperl's C\<glob> operator \(which uses the C\<perlglob> program\)
pod/perl5161delta\.pod\-56\-deleting the PATH environment variable \[perl \#113798\]\.

**Comment by p5pRT** [comment]
### From @tonycoz

On Wed\, 20 Sep 2017 15&#8203;:55&#8203;:44 \-0700\, jkeenan@&#8203;pobox\.com wrote&#8203;:
> I would have expected to be able to find a paragraph or two underneath 
> 'pod/' describing the purpose and functionality of 'miniperl'\.
> 
> As the attachment demonstrates\, no such documentation exists\.
> 
> Is that deliberate?
> 
> If not\, could we add a paragraph about 'miniperl'?

If we described miniperl I'd think it would be part of perlhackbuild\.pod or something similar describing the build process for perl\, and how/where to back on it\.

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by jkeenan** [comment]
> ### From @tonycoz
> 
> On Wed, 20 Sep 2017 15​:55​:44 -0700, jkeenan@​pobox.com wrote​:
> 
> > I would have expected to be able to find a paragraph or two underneath
> > 'pod/' describing the purpose and functionality of 'miniperl'.
> > As the attachment demonstrates, no such documentation exists.
> > Is that deliberate?
> > If not, could we add a paragraph about 'miniperl'?
> 
> If we described miniperl I'd think it would be part of perlhackbuild.pod or something similar describing the build process for perl, and how/where to back on it.
> 
> Tony

We have these 3 hacking-related POD files:
```
$ ls pod/perlhack* |cat
pod/perlhack.pod
pod/perlhacktips.pod
pod/perlhacktut.pod
```
We don't have a `perlhackbuild.pod`.  Are you saying we should?

In any event, could we get a 1- or 2-paragraph description of the purpose and usage of `miniperl` -- regardless of where we stick it?

Thank you very much.
Jim Keenan

**Comment by tonycoz** [comment]
Something like:
````
F<miniperl> is a minimalistic perl built to bootstrap building extensions, utilties,
documentation etc.  It doesn't support dynamic loading and depending
on the point in the build process will only have access to a limited set of core
modules.  F<miniperl> is not intended for day to day use.
````

I still don't know where it belongs.

**Comment by khwilliamson** [comment]
+1 to the text

**Comment by jkeenan** [comment]
Also +1 to text.  See p.r. https://github.com/Perl/perl5/pull/17538 or branch jkeenan/tonyc/ghi-16158/miniperl-doc.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
Resolved by merge of https://github.com/Perl/perl5/pull/17538 into blead earlier today.  Closing.
