### ISSUE TITLE
'make minitest' non-zero error code ignored

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16160]
Migrated from [rt.perl.org#132139](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132139) (status was 'open')

Searchable as RT132139$

**Comment by p5pRT** [comment]
### From @jkeenan

As documented in https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132138, 
't/run/switches\.t' fails when run under 'miniperl'\, probably because it 
'require's module File&#8203;::Spec\.

I stumbled upon this by accident today\.  Following up on a discussion on 
IRC \#p5p and in https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132092, when 
testing the perl\-5\.27\.4 tarball provided by John SJ Anderson on 
FreeBSD\-11\.0\, instead of saying\, as I normally would&#8203;:

\#\#\#\#\#
$ regular\_configure && make test\_harness
\#\#\#\#\#

\.\.\. \(where 'regular\_configure' is a shell script that\, on FreeBSD\, 
builds a threaded perl very close to the 'system perl'\)\, I said&#8203;:

\#\#\#\#\#
$ regular\_configure && make minitest && make test\_harness
\#\#\#\#\#

I guessed that if 'make minitest' were to FAIL\, then 'make test\_harness' 
would never be run and my attention would immediately be drawn to 
failing tests\.

I sat watching the terminal and thought I saw a test failure during 
'make minitest'\.  But it quickly became apparent that this failure \-\- 
subsequently confirmed as being in 't/run/switches\.t' did not prevent 
'make test\_harness' from starting to run\.

So I then cleaned the directory\, re\-configured and then said 'make 
minitest'\.  'make minitest' did find and report the error in 
't/run/switches\.t' but its error code is ignored\!  \(See gzipped 
attachment for complete output as reproduced on Linux\.\)

\#\#\#\#\#
\.\.\.
t/run/switchd \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\. ok
t/run/switches \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\. Can't locate File/Spec\.pm in @&#8203;INC \(you 
may need to install the File&#8203;::Spec module\) \(@&#8203;INC contains&#8203;: \.\./lib\) at 
run/switches\.t line 424\.
\# Looks like you planned 137 tests but ran 111\.
FAILED\-\-expected 137 tests\, saw 111
t/run/switchn \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\. ok
\.\.\.
t/perf/taint \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\. skipped
Failed 1 test out of 343\, 99\.71% okay\.
&nbsp;    run/switches\.t
\#\#\# Since not all tests were successful\, you may want to run some of
\#\#\# them individually and examine any diagnostic messages they produce\.
\#\#\# See the INSTALL document's section on "make test"\.
\#\#\# You have a good chance to get more information by running
\#\#\#   \./perl harness
\#\#\# in the 't' directory since most \(>=80%\) of the tests succeeded\.
\#\#\# You may have to set your dynamic library search path\,
\#\#\# LD\_LIBRARY\_PATH\, to point to the build directory&#8203;:
\#\#\#   setenv LD\_LIBRARY\_PATH \`pwd\`; cd t; \./perl harness
\#\#\#   LD\_LIBRARY\_PATH=\`pwd\`; export LD\_LIBRARY\_PATH; cd t; \./perl harness
\#\#\#   export LD\_LIBRARY\_PATH=\`pwd\`; cd t; \./perl harness
\#\#\# for csh\-style shells\, like tcsh; or for traditional/modern
\#\#\# Bourne\-style shells\, like bash\, ksh\, and zsh\, respectively\.
Elapsed&#8203;: 124 sec
u=1\.69  s=0\.24  cu=39\.93  cs=1\.73  scripts=343  tests=348120
makefile&#8203;:824&#8203;: recipe for target 'minitest' failed
make&#8203;: \[minitest\] Error 1 \(ignored\)
\#\#\#\#\#

Ignoring this error code\, IMO\, diminishes the value of 'make minitest' 
to an author or committer trying to evaluate the correctness of a patch\.

Is there a rationale for ignoring this error code?

If not\, what is the recommended fix?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From @jkeenan

[make.minitest.linux.output.txt.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/1492215/803726/make.minitest.linux.output.txt.gz)

**Comment by p5pRT** [comment]
### From @jkeenan

Summary of my perl5 \(revision 5 version 27 subversion 4\) configuration&#8203;:
&nbsp;  Commit id&#8203;: e271727ef27311aecfec2f87d6c8eecdb3f09d05
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux
&nbsp;    osvers=4\.4\.0\-93\-generic
&nbsp;    archname=x86\_64\-linux
&nbsp;    uname='linux zareason 4\.4\.0\-93\-generic \#116\-ubuntu smp fri aug 11 21&#8203;:17&#8203;:51 utc 2017 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;    config\_args='\-des \-Dusedevel'
&nbsp;    hint=recommended
&nbsp;    useposix=true
&nbsp;    d\_sigaction=define
&nbsp;    useithreads=undef
&nbsp;    usemultiplicity=undef
&nbsp;    use64bitint=define
&nbsp;    use64bitall=define
&nbsp;    uselongdouble=undef
&nbsp;    usemymalloc=n
&nbsp;    default\_inc\_excludes\_dot=define
&nbsp;    bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'
&nbsp;    ccflags ='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'
&nbsp;    optimize='\-O2'
&nbsp;    cppflags='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''
&nbsp;    gccversion='5\.4\.0 20160609'
&nbsp;    gccosandvers=''
&nbsp;    intsize=4
&nbsp;    longsize=8
&nbsp;    ptrsize=8
&nbsp;    doublesize=8
&nbsp;    byteorder=12345678
&nbsp;    doublekind=3
&nbsp;    d\_longlong=define
&nbsp;    longlongsize=8
&nbsp;    d\_longdbl=define
&nbsp;    longdblsize=16
&nbsp;    longdblkind=3
&nbsp;    ivtype='long'
&nbsp;    ivsize=8
&nbsp;    nvtype='double'
&nbsp;    nvsize=8
&nbsp;    Off\_t='off\_t'
&nbsp;    lseeksize=8
&nbsp;    alignbytes=8
&nbsp;    prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'
&nbsp;    ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/5/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib /lib64 /usr/lib64
&nbsp;    libs=\-lpthread \-lnsl \-ldb \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.23\.so
&nbsp;    so=so
&nbsp;    useshrplib=false
&nbsp;    libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.23'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs
&nbsp;    dlext=so
&nbsp;    d\_dlsymun=undef
&nbsp;    ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'
&nbsp;    lddlflags='\-shared \-O2 \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;:
&nbsp;    HAS\_TIMES
&nbsp;    PERLIO\_LAYERS
&nbsp;    PERL\_COPY\_ON\_WRITE
&nbsp;    PERL\_DONT\_CREATE\_GVSV
&nbsp;    PERL\_MALLOC\_WRAP
&nbsp;    PERL\_OP\_PARENT
&nbsp;    PERL\_PRESERVE\_IVUV
&nbsp;    PERL\_USE\_DEVEL
&nbsp;    USE\_64\_BIT\_ALL
&nbsp;    USE\_64\_BIT\_INT
&nbsp;    USE\_LARGE\_FILES
&nbsp;    USE\_LOCALE
&nbsp;    USE\_LOCALE\_COLLATE
&nbsp;    USE\_LOCALE\_CTYPE
&nbsp;    USE\_LOCALE\_NUMERIC
&nbsp;    USE\_LOCALE\_TIME
&nbsp;    USE\_PERLIO
&nbsp;    USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Sep 16 2017 10&#8203;:17&#8203;:33
&nbsp;  %ENV&#8203;:
&nbsp;    PERLBREW\_BASHRC\_VERSION="0\.78"
&nbsp;    PERLBREW\_HOME="/home/jkeenan/\.perlbrew"
&nbsp;    PERLBREW\_MANPATH="/home/jkeenan/perl5/perlbrew/perls/perl\-5\.26\.0/man"
&nbsp;    PERLBREW\_PATH="/home/jkeenan/perl5/perlbrew/bin&#8203;:/home/jkeenan/perl5/perlbrew/perls/perl\-5\.26\.0/bin"
&nbsp;    PERLBREW\_PERL="perl\-5\.26\.0"
&nbsp;    PERLBREW\_ROOT="/home/jkeenan/perl5/perlbrew"
&nbsp;    PERLBREW\_VERSION="0\.78"
&nbsp;    PERL\_WORKDIR="/home/jkeenan/gitwork/perl"
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.27\.4/x86\_64\-linux
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.27\.4
&nbsp;    /usr/local/lib/perl5/5\.27\.4/x86\_64\-linux
&nbsp;    /usr/local/lib/perl5/5\.27\.4

**Comment by p5pRT** [comment]
### From @tonycoz

On Wed\, 20 Sep 2017 16&#8203;:33&#8203;:32 \-0700\, jkeenan@&#8203;pobox\.com wrote&#8203;:
> As documented in https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132138, 
> 't/run/switches\.t' fails when run under 'miniperl'\, probably because it 
> 'require's module File&#8203;::Spec\.
> 
> I stumbled upon this by accident today\.  Following up on a discussion on 
> IRC \#p5p and in https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132092, when 
> testing the perl\-5\.27\.4 tarball provided by John SJ Anderson on 
> FreeBSD\-11\.0\, instead of saying\, as I normally would&#8203;:
> 
> \#\#\#\#\#
> $ regular\_configure && make test\_harness
> \#\#\#\#\#
> 
> \.\.\. \(where 'regular\_configure' is a shell script that\, on FreeBSD\, 
> builds a threaded perl very close to the 'system perl'\)\, I said&#8203;:
> 
> \#\#\#\#\#
> $ regular\_configure && make minitest && make test\_harness
> \#\#\#\#\#
> 
> I guessed that if 'make minitest' were to FAIL\, then 'make test\_harness' 
> would never be run and my attention would immediately be drawn to 
> failing tests\.
> 
> I sat watching the terminal and thought I saw a test failure during 
> 'make minitest'\.  But it quickly became apparent that this failure \-\- 
> subsequently confirmed as being in 't/run/switches\.t' did not prevent 
> 'make test\_harness' from starting to run\.
> 
> So I then cleaned the directory\, re\-configured and then said 'make 
> minitest'\.  'make minitest' did find and report the error in 
> 't/run/switches\.t' but its error code is ignored\!  \(See gzipped 
> attachment for complete output as reproduced on Linux\.\)

minitest has ignored errors since it was introduced in 16d20bd98cd29be76029ebf04027a7edd34d817b&#8203;:

commit 16d20bd98cd29be76029ebf04027a7edd34d817b
Author&#8203;: Andy Dougherty \<doughera@&#8203;lafcol\.lafayette\.edu>
Date&#8203;:   Tue May 30 22&#8203;:59&#8203;:41 1995 \+0000

&nbsp;    This is my patch  patch\.1i  for perl5\.001\.
&nbsp;    
\.\.\.
&nbsp;    Makefile\.SH
\.\.\.
&nbsp;        Add 'minitest' target\.
&nbsp;    
\.\.\.
<details><summary>Inline Patch</summary>

```diff
diff --git a/Makefile.SH b/Makefile.SH
index f5dff60..cdd6333 100644
--- a/Makefile.SH
+++ b/Makefile.SH

```
</details>
...
@&#8203;@&#8203; \-374\,6 \+395\,11 @&#8203;@&#8203; test&#8203;: miniperl perl preplibrary $\(dynamic\_ext\)
&nbsp;        \- cd t && chmod \+x TEST \*/\*\.t
&nbsp;        \- cd t && \(rm \-f perl; $\(LNS\) \.\./perl perl\) && \./perl TEST \</dev/tty
 
\+minitest&#8203;: miniperl
\+       \- cd t && chmod \+x TEST \*/\*\.t
\+       \- cd t && \(rm \-f perl; $\(LNS\) \.\./miniperl perl\) \\
\+               && \./perl TEST base/\*\.t comp/\*\.t cmd/\*\.t io/\*\.t op/\*\.t \</dev/tty
\+
 clist&#8203;: $\(c\)
&nbsp;        echo $\(c\) | tr ' ' '\\012' >\.clist
 

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @jkeenan

On Thu\, 21 Sep 2017 00&#8203;:47&#8203;:45 GMT\, tonyc wrote&#8203;:
> On Wed\, 20 Sep 2017 16&#8203;:33&#8203;:32 \-0700\, jkeenan@&#8203;pobox\.com wrote&#8203;:
> > As documented in https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132138,
> > 't/run/switches\.t' fails when run under 'miniperl'\, probably because
> > it
> > 'require's module File&#8203;::Spec\.
> >
> > I stumbled upon this by accident today\.  Following up on a discussion
> > on
> > IRC \#p5p and in https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132092,
> > when
> > testing the perl\-5\.27\.4 tarball provided by John SJ Anderson on
> > FreeBSD\-11\.0\, instead of saying\, as I normally would&#8203;:
> >
> > \#\#\#\#\#
> > $ regular\_configure && make test\_harness
> > \#\#\#\#\#
> >
> > \.\.\. \(where 'regular\_configure' is a shell script that\, on FreeBSD\,
> > builds a threaded perl very close to the 'system perl'\)\, I said&#8203;:
> >
> > \#\#\#\#\#
> > $ regular\_configure && make minitest && make test\_harness
> > \#\#\#\#\#
> >
> > I guessed that if 'make minitest' were to FAIL\, then 'make
> > test\_harness'
> > would never be run and my attention would immediately be drawn to
> > failing tests\.
> >
> > I sat watching the terminal and thought I saw a test failure during
> > 'make minitest'\.  But it quickly became apparent that this failure \-\-
> > subsequently confirmed as being in 't/run/switches\.t' did not prevent
> > 'make test\_harness' from starting to run\.
> >
> > So I then cleaned the directory\, re\-configured and then said 'make
> > minitest'\.  'make minitest' did find and report the error in
> > 't/run/switches\.t' but its error code is ignored\!  \(See gzipped
> > attachment for complete output as reproduced on Linux\.\)
> 
> minitest has ignored errors since it was introduced in
> 16d20bd98cd29be76029ebf04027a7edd34d817b&#8203;:
> 
> commit 16d20bd98cd29be76029ebf04027a7edd34d817b
> Author&#8203;: Andy Dougherty \<doughera@&#8203;lafcol\.lafayette\.edu>
> Date&#8203;:   Tue May 30 22&#8203;:59&#8203;:41 1995 \+0000
> 
> This is my patch  patch\.1i  for perl5\.001\.
> 
> \.\.\.
>     Makefile\.SH
> \.\.\.
>         Add 'minitest' target\.
> 
> \.\.\.
> diff \-\-git a/Makefile\.SH b/Makefile\.SH
> index f5dff60\.\.cdd6333 100644
> \-\-\- a/Makefile\.SH
> \+\+\+ b/Makefile\.SH
> \.\.\.
> @&#8203;@&#8203; \-374\,6 \+395\,11 @&#8203;@&#8203; test&#8203;: miniperl perl preplibrary $\(dynamic\_ext\)
>         \- cd t && chmod \+x TEST \*/\*\.t
>         \- cd t && \(rm \-f perl; $\(LNS\) \.\./perl perl\) && \./perl TEST
> \</dev/tty
> 
> \+minitest&#8203;: miniperl
> \+       \- cd t && chmod \+x TEST \*/\*\.t
> \+       \- cd t && \(rm \-f perl; $\(LNS\) \.\./miniperl perl\) \\
> \+               && \./perl TEST base/\*\.t comp/\*\.t cmd/\*\.t io/\*\.t op/\*\.t
> \</dev/tty
> \+
>  clist&#8203;: $\(c\)
>         echo $\(c\) | tr ' ' '\\012' >\.clist
> 
> 
> Tony

So\, on the one hand\, I would argue\, it does not DWIM for the purpose for which it is recommended in pod/perlgit\.pod and by commenters on list today\.

On the other hand\, to change that situation would require changing the way it has worked for 22 years \(and I'm always inclined to trust Andy D's judgment\)\.

I'm inclined to the first hand\.  I want to use it in a string of commands and I want that string to fail if and when 'make minitest' fails\.  Otherwise I'm inclined to never use it\.

Thank you very much\.
\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @doughera88

On Wed\, Sep 20\, 2017 at 06&#8203;:54&#8203;:20PM \-0700\, James E Keenan via RT wrote&#8203;:
> On Thu\, 21 Sep 2017 00&#8203;:47&#8203;:45 GMT\, tonyc wrote&#8203;:

> > minitest has ignored errors since it was introduced in
> > 16d20bd98cd29be76029ebf04027a7edd34d817b&#8203;:
> > 
> > commit 16d20bd98cd29be76029ebf04027a7edd34d817b
> > Author&#8203;: Andy Dougherty \<doughera@&#8203;lafcol\.lafayette\.edu>
> > Date&#8203;:   Tue May 30 22&#8203;:59&#8203;:41 1995 \+0000
> > 
> > This is my patch  patch\.1i  for perl5\.001\.
> > 
> > \.\.\.
> >     Makefile\.SH
> > \.\.\.
> >         Add 'minitest' target\.
> > 
> > \.\.\.
> > diff \-\-git a/Makefile\.SH b/Makefile\.SH
> > index f5dff60\.\.cdd6333 100644
> > \-\-\- a/Makefile\.SH
> > \+\+\+ b/Makefile\.SH
> > \.\.\.
> > @&#8203;@&#8203; \-374\,6 \+395\,11 @&#8203;@&#8203; test&#8203;: miniperl perl preplibrary $\(dynamic\_ext\)
> >         \- cd t && chmod \+x TEST \*/\*\.t
> >         \- cd t && \(rm \-f perl; $\(LNS\) \.\./perl perl\) && \./perl TEST
> > \</dev/tty
> > 
> > \+minitest&#8203;: miniperl
> > \+       \- cd t && chmod \+x TEST \*/\*\.t
> > \+       \- cd t && \(rm \-f perl; $\(LNS\) \.\./miniperl perl\) \\
> > \+               && \./perl TEST base/\*\.t comp/\*\.t cmd/\*\.t io/\*\.t op/\*\.t
> > \</dev/tty
> > \+
> >  clist&#8203;: $\(c\)
> >         echo $\(c\) | tr ' ' '\\012' >\.clist
> > 
> > 
> > Tony
> 
> So\, on the one hand\, I would argue\, it does not DWIM for the purpose for which it is recommended in pod/perlgit\.pod and by commenters on list today\.
> 
> On the other hand\, to change that situation would require changing the way it has worked for 22 years \(and I'm always inclined to trust Andy D's judgment\)\.
> 
> I'm inclined to the first hand\.  I want to use it in a string of commands and I want that string to fail if and when 'make minitest' fails\.  Otherwise I'm inclined to never use it\.

While I appreciate the thought\, I don't recall exercising any judgment
there\.  The 'minitest' target was pretty much a cut & paste of the 'test'
target\, which ignored the exit status\.  I don't recall why\.  Your inclination
sounds sensible to me\.  

\-\- 
&nbsp;    Andy Dougherty        doughera@&#8203;lafayette\.edu

**Comment by p5pRT** [comment]
### From @jkeenan

On Thu\, 21 Sep 2017 02&#8203;:25&#8203;:47 GMT\, doughera wrote&#8203;:
> On Wed\, Sep 20\, 2017 at 06&#8203;:54&#8203;:20PM \-0700\, James E Keenan via RT wrote&#8203;:
> > On Thu\, 21 Sep 2017 00&#8203;:47&#8203;:45 GMT\, tonyc wrote&#8203;:
> 
> > > minitest has ignored errors since it was introduced in
> > > 16d20bd98cd29be76029ebf04027a7edd34d817b&#8203;:
> > >
> > > commit 16d20bd98cd29be76029ebf04027a7edd34d817b
> > > Author&#8203;: Andy Dougherty \<doughera@&#8203;lafcol\.lafayette\.edu>
> > > Date&#8203;:   Tue May 30 22&#8203;:59&#8203;:41 1995 \+0000
> > >
> > > This is my patch  patch\.1i  for perl5\.001\.
> > >
> > > \.\.\.
> > >     Makefile\.SH
> > > \.\.\.
> > >         Add 'minitest' target\.
> > >
> > > \.\.\.
> > > diff \-\-git a/Makefile\.SH b/Makefile\.SH
> > > index f5dff60\.\.cdd6333 100644
> > > \-\-\- a/Makefile\.SH
> > > \+\+\+ b/Makefile\.SH
> > > \.\.\.
> > > @&#8203;@&#8203; \-374\,6 \+395\,11 @&#8203;@&#8203; test&#8203;: miniperl perl preplibrary $\(dynamic\_ext\)
> > >         \- cd t && chmod \+x TEST \*/\*\.t
> > >         \- cd t && \(rm \-f perl; $\(LNS\) \.\./perl perl\) && \./perl TEST
> > > \</dev/tty
> > >
> > > \+minitest&#8203;: miniperl
> > > \+       \- cd t && chmod \+x TEST \*/\*\.t
> > > \+       \- cd t && \(rm \-f perl; $\(LNS\) \.\./miniperl perl\) \\
> > > \+               && \./perl TEST base/\*\.t comp/\*\.t cmd/\*\.t io/\*\.t
> > > op/\*\.t
> > > \</dev/tty
> > > \+
> > >  clist&#8203;: $\(c\)
> > >         echo $\(c\) | tr ' ' '\\012' >\.clist
> > >
> > >
> > > Tony
> >
> > So\, on the one hand\, I would argue\, it does not DWIM for the purpose
> > for which it is recommended in pod/perlgit\.pod and by commenters on
> > list today\.
> >
> > On the other hand\, to change that situation would require changing
> > the way it has worked for 22 years \(and I'm always inclined to trust
> > Andy D's judgment\)\.
> >
> > I'm inclined to the first hand\.  I want to use it in a string of
> > commands and I want that string to fail if and when 'make minitest'
> > fails\.  Otherwise I'm inclined to never use it\.
> 
> While I appreciate the thought\, I don't recall exercising any judgment
> there\.  The 'minitest' target was pretty much a cut & paste of the
> 'test'
> target\, which ignored the exit status\.  I don't recall why\.  Your
> inclination
>   sounds sensible to me\.

It turns out that having 'make' take the exit status of 'make minitest' into consideration is very simple; see patch attached\.

However\, I want to re\-read all references to 'minitest' in the core distro and to allow time for other people to comment\.

Thank you very much\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @jkeenan

<details><summary>132139-minitest.diff</summary>

```diff
diff --git a/Makefile.SH b/Makefile.SH
index 730dcca..b0f0d9d 100755
--- a/Makefile.SH
+++ b/Makefile.SH
@@ -1631,15 +1631,15 @@ minitest_prep:
 	@echo "You may see some irrelevant test failures if you have been unable"
 	@echo "to build lib/Config.pm, or the Unicode data files."
 	@echo " "
-	- cd t && (rm -f $(PERL_EXE); $(LNS) ../$(MINIPERL_EXE) $(PERL_EXE))
+	cd t && (rm -f $(PERL_EXE); $(LNS) ../$(MINIPERL_EXE) $(PERL_EXE))
 
 MINITEST_TESTS = base/*.t comp/*.t cmd/*.t run/*.t io/*.t re/*.t opbasic/*.t op/*.t uni/*.t perf/*.t
 
 minitest: $(MINIPERL_EXE) minitest_prep
-	- cd t && $(RUN_PERL) TEST $(MINITEST_TESTS) <$(devtty)
+	cd t && $(RUN_PERL) TEST $(MINITEST_TESTS) <$(devtty)
 
 minitest-notty minitest_notty: $(MINIPERL_EXE) minitest_prep
-	- cd t && PERL_SKIP_TTY_TEST=1 $(RUN_PERL) TEST $(MINITEST_TESTS)
+	cd t && PERL_SKIP_TTY_TEST=1 $(RUN_PERL) TEST $(MINITEST_TESTS)
 
 # Test via harness
 

```
</details>

**Comment by jkeenan** [comment]
This ticket should have been closed in February 2020 when the following commit was applied:
```
commit 2b689a479128e6b86e3d180f70dcf1b447caf0e6
Author:     James E Keenan <jkeenan@cpan.org>
AuthorDate: Fri Jan 31 03:23:18 2020 +0000
Commit:     James E Keenan <jkeenan@cpan.org>
CommitDate: Tue Feb 4 09:27:50 2020 -0500

    Do not ignore non-zero error code from 'make minitest'
```
Closing now.
