### ISSUE TITLE
pod2usage can invoke system($Config{pager},...) which is "less -R" => error

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16246]
Migrated from [rt.perl.org#132446](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132446) (status was 'open')

Searchable as RT132446$

**Comment by p5pRT** [comment]
### From karl@freefriends.org


This is a bug report for perl from karl@&#8203;freefriends\.org\,
generated with the help of perlbug 1\.40 running under perl 5\.26\.1\.

With stock perl 5\.26\.1\, installed from source\, I got this error message
from the pod2usage function&#8203;:

&nbsp;  Can't exec "/usr/bin/less \-R"&#8203;: No such file or directory at
&nbsp;  /usr/local/lib/perl5/5\.26\.1/Pod/Usage\.pm line 164\.

I was running "tlmgr help | head"\, where tlmgr is the "TeX Live manager"
program \(tug\.org/texlive\)\, but I think any invocation with \-noperldoc
will suffice\. Sorry\, I don't have a minimal example at hand\.

That line 164 is&#8203;:
&nbsp;  system\(\($Config\{pager\} || $ENV\{PAGER\} || '/bin/more'\)\, $1\);

With 5\.26\.1\, my $Config\{pager\} is "less \-R"\. system takes that string
literally as the command name\, not breaking it at spaces\, because it's
being called with the list form\. Hence the failure\.

In an earlier perl \(5\.16\.3\, distributed as the system version with
current CentOS7\)\, $Config\{pager\} is "less \-isr"\. Same problem\.

I compiled 5\.26\.1 myself and did nothing special about the pager value;
perl somehow determined the "less \-R" itself\.

I don't know if it is the $Config\{pager\} value that should be a simple
command name\, or Pod&#8203;::Usage at fault for assuming it is such\.


Also on that line&#8203;: it seems like the user's value $ENV\{PAGER\} should be
used in preference to Perl's value?

Thanks for Perl\. \-\-karl

P\.S\. The line before that says&#8203;:
&nbsp;  \# RT16091&#8203;: fall back to more if perldoc failed
but enter 16091 at rt\.perl\.org says "could not load bug"\,
and at rt\.cpan\.org goes to something unrelated\.


---
Flags&#8203;:
&nbsp;    category=library
&nbsp;    severity=medium
&nbsp;    module=Pod&#8203;::Usage


---
Site configuration information for perl 5\.26\.1&#8203;:

Configured by karl at Tue Oct 31 22&#8203;:13&#8203;:49 CET 2017\.

Summary of my perl5 \(revision 5 version 26 subversion 1\) configuration&#8203;:
&nbsp;   
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux
&nbsp;    osvers=3\.10\.0\-693\.5\.2\.el7\.x86\_64
&nbsp;    archname=x86\_64\-linux
&nbsp;    uname='linux tug\.org 3\.10\.0\-693\.5\.2\.el7\.x86\_64 \#1 smp fri oct 20 20&#8203;:32&#8203;:50 utc 2017 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;    config\_args='\-d \-e \-Uinstallusrbinperl \-Dprefix=/usr/local'
&nbsp;    hint=recommended
&nbsp;    useposix=true
&nbsp;    d\_sigaction=define
&nbsp;    useithreads=undef
&nbsp;    usemultiplicity=undef
&nbsp;    use64bitint=define
&nbsp;    use64bitall=define
&nbsp;    uselongdouble=undef
&nbsp;    usemymalloc=n
&nbsp;    default\_inc\_excludes\_dot=define
&nbsp;    bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'
&nbsp;    ccflags ='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-D\_FORTIFY\_SOURCE=2'
&nbsp;    optimize='\-O2'
&nbsp;    cppflags='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''
&nbsp;    gccversion='4\.8\.5 20150623 \(Red Hat 4\.8\.5\-16\)'
&nbsp;    gccosandvers=''
&nbsp;    intsize=4
&nbsp;    longsize=8
&nbsp;    ptrsize=8
&nbsp;    doublesize=8
&nbsp;    byteorder=12345678
&nbsp;    doublekind=3
&nbsp;    d\_longlong=define
&nbsp;    longlongsize=8
&nbsp;    d\_longdbl=define
&nbsp;    longdblsize=16
&nbsp;    longdblkind=3
&nbsp;    ivtype='long'
&nbsp;    ivsize=8
&nbsp;    nvtype='double'
&nbsp;    nvsize=8
&nbsp;    Off\_t='off\_t'
&nbsp;    lseeksize=8
&nbsp;    alignbytes=8
&nbsp;    prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'
&nbsp;    ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib /lib/\.\./lib64 /usr/lib/\.\./lib64 /lib /lib64 /usr/lib64 /usr/local/lib64
&nbsp;    libs=\-lpthread \-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lc \-lgdbm\_compat
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.17\.so
&nbsp;    so=so
&nbsp;    useshrplib=false
&nbsp;    libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.17'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs
&nbsp;    dlext=so
&nbsp;    d\_dlsymun=undef
&nbsp;    ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'
&nbsp;    lddlflags='\-shared \-O2 \-L/usr/local/lib \-fstack\-protector\-strong'




---
@&#8203;INC for perl 5\.26\.1&#8203;:
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.26\.1/x86\_64\-linux
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.26\.1
&nbsp;    /usr/local/lib/perl5/5\.26\.1/x86\_64\-linux
&nbsp;    /usr/local/lib/perl5/5\.26\.1
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.24\.1
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.24\.0
&nbsp;    /usr/local/lib/perl5/site\_perl



---
Environment for perl 5\.26\.1&#8203;:
&nbsp;    HOME=/home/karl
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LC\_ALL=C
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=\.&#8203;:/home/karl/bin&#8203;:/l/bin&#8203;:/usr/local/gnu/emacs21/bin&#8203;:/usr/local/gnu/bin&#8203;:/home/texlive/karl/Master/bin/x86\_64\-linux&#8203;:/home/texlive/karl/Master/tlpkg/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/usr/sbin&#8203;:/usr/lib/mailman/bin
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @jkeenan

On Tue\, 14 Nov 2017 18&#8203;:30&#8203;:30 GMT\, karl@&#8203;freefriends\.org wrote&#8203;:
> 
> This is a bug report for perl from karl@&#8203;freefriends\.org\,
> generated with the help of perlbug 1\.40 running under perl 5\.26\.1\.
> 
> With stock perl 5\.26\.1\, installed from source\, I got this error
> message
> from the pod2usage function&#8203;:
> 
> Can't exec "/usr/bin/less \-R"&#8203;: No such file or directory at
> /usr/local/lib/perl5/5\.26\.1/Pod/Usage\.pm line 164\.
> 

Do you in fact not have a program '/usr/bin/less'?

> I was running "tlmgr help | head"\, where tlmgr is the "TeX Live
> manager"
> program \(tug\.org/texlive\)\, but I think any invocation with \-noperldoc
> will suffice\. Sorry\, I don't have a minimal example at hand\.
> 

In the absence of an example we'll have trouble responding to this\.  pod2usage works well for \(no warnings or exceptions\)\.

Also\, AFAICT\, '\-noperldoc' is a possible switch for the function Pod&#8203;::Usage&#8203;::pod2usage\(\) but is \*not\* a possible switch for the executable program 'pod2usage'\.


> That line 164 is&#8203;:
>   system\(\($Config\{pager\} || $ENV\{PAGER\} || '/bin/more'\)\, $1\);
> 
> With 5\.26\.1\, my $Config\{pager\} is "less \-R"\. system takes that string
> literally as the command name\, not breaking it at spaces\, because it's
> being called with the list form\. Hence the failure\.
> 
> In an earlier perl \(5\.16\.3\, distributed as the system version with
> current CentOS7\)\, $Config\{pager\} is "less \-isr"\. Same problem\.
> 
> I compiled 5\.26\.1 myself and did nothing special about the pager
> value;
> perl somehow determined the "less \-R" itself\.
> 
> I don't know if it is the $Config\{pager\} value that should be a simple
> command name\, or Pod&#8203;::Usage at fault for assuming it is such\.
> 
> 
> Also on that line&#8203;: it seems like the user's value $ENV\{PAGER\} should
> be
> used in preference to Perl's value?
> 
> Thanks for Perl\. \-\-karl
> 
> P\.S\. The line before that says&#8203;:
>   \# RT16091&#8203;: fall back to more if perldoc failed
> but enter 16091 at rt\.perl\.org says "could not load bug"\,
> and at rt\.cpan\.org goes to something unrelated\.

In addition\, Pod&#8203;::Usage is maintained upstream on CPAN\.  So if there really is a bug here \(I'm not convinced yet\)\, it will have to be reported here&#8203;: https://rt.cpan.org/Dist/Display.html?Name=Pod-Usage

Thank you very much\.
\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From zefram@fysh.org

James E Keenan via RT wrote&#8203;:
>Do you in fact not have a program '/usr/bin/less'?

I think he does have the file '/usr/bin/less'\, but not the file
'/usr/bin/less \-R'\.  The question is whether $Config\{pager\} is a filename
or a fragment of shell code\.

\-zefram

**Comment by p5pRT** [comment]
### From @xsawyerx



On 11/15/2017 05&#8203;:41 PM\, Zefram wrote&#8203;:
> James E Keenan via RT wrote&#8203;:
>> Do you in fact not have a program '/usr/bin/less'?
> I think he does have the file '/usr/bin/less'\, but not the file
> '/usr/bin/less \-R'\.  The question is whether $Config\{pager\} is a filename
> or a fragment of shell code\.

What would be setting $Config\{pager\} to shell code?

My inclination is to view these as paths and not shell code\, but I'm not
sure what it is setting this and whether this is the way it has been
done thusfar\.

**Comment by p5pRT** [comment]
### From @Leont

On Thu\, Nov 16\, 2017 at 12&#8203;:22 PM\, Sawyer X \<xsawyerx@&#8203;gmail\.com> wrote&#8203;:

> On 11/15/2017 05&#8203;:41 PM\, Zefram wrote&#8203;:
> > James E Keenan via RT wrote&#8203;:
> >> Do you in fact not have a program '/usr/bin/less'?
> > I think he does have the file '/usr/bin/less'\, but not the file
> > '/usr/bin/less \-R'\.  The question is whether $Config\{pager\} is a filename
> > or a fragment of shell code\.
>
> What would be setting $Config\{pager\} to shell code?
>
> My inclination is to view these as paths and not shell code\, but I'm not
> sure what it is setting this and whether this is the way it has been
> done thusfar\.
>

Setting \-R is necessary to support ANSI color codes\, which is necessary to
support perldoc\-without\-man\.

IMHO the preferred solution here is to pass $Config\{pager\} through
Text&#8203;::ParseWords's shellwords\. Alternatively\, we could add a pagerflags
entry to %Config\, but I'm not convinced that that would be the path of
least resistance\.

Leon

**Comment by p5pRT** [comment]
### From @xsawyerx



On 11/16/2017 03&#8203;:14 PM\, Leon Timmermans wrote&#8203;:
> On Thu\, Nov 16\, 2017 at 12&#8203;:22 PM\, Sawyer X \<xsawyerx@&#8203;gmail\.com
> \<mailto&#8203;:xsawyerx@&#8203;gmail\.com>> wrote&#8203;:
>
>     On 11/15/2017 05&#8203;:41 PM\, Zefram wrote&#8203;:
>     > James E Keenan via RT wrote&#8203;:
>     >> Do you in fact not have a program '/usr/bin/less'?
>     > I think he does have the file '/usr/bin/less'\, but not the file
>     > '/usr/bin/less \-R'\.  The question is whether $Config\{pager\} is a
>     filename
>     > or a fragment of shell code\.
>
>     What would be setting $Config\{pager\} to shell code?
>
>     My inclination is to view these as paths and not shell code\, but
>     I'm not
>     sure what it is setting this and whether this is the way it has been
>     done thusfar\.
>
>
> Setting \-R is necessary to support ANSI color codes\, which is
> necessary to support perldoc\-without\-man\.

If I understand you correctly\, perldoc is actually using a different
mechanism by running it with "\-R" manually\.

**Comment by p5pRT** [comment]
### From karl@freefriends.org

1\) I'll be happy to send a report to bug\-Pod\-Usage if that is desired\.
Or maybe you can just redirect this RT ticket there? Whatever works\.

Meanwhile\, to answer some of the questions that have been asked&#8203;:

2\) It is perl's Configure which is setting $Config\{pager\} to
"/usr/bin/less \-R"\, including the argument\. \(If you search for the
literal string "$less" in Configure\, you will see\.\)

Configure has evidently been doing this since perl 5\.12 \(ca\.2011\)\.
Perl 5\.10\.1 sets it to just "/full/path/name/less"\, without options\.
I am not passing any special arguments to Configure\.
FWIW\, example command that I used to inspect&#8203;:
&nbsp;  \./perl5\.10\.1 \-e 'use Config; print $Config\{pager\}\, "\\n"'

2\) The bug is evident\. To repeat\, line 164 of current Pod/Usage\.pm is&#8203;:
&nbsp;  system\(\($Config\{pager\} || $ENV\{PAGER\} || '/bin/more'\)\, $1\);
which assumes $Config\{pager\} is merely the executable name\, because
it's calling system\(\) with a list\. Thus whitespace is not parsed
into words\. I can construct an example if I must\.

3\) This code in Pod/Usage\.pm has not changed since at least 5\.10\.1\. Thus
the assumption that $Config\{pager\} was a simple string was valid when it
was written\, and the Configure script changed\. FWIW\, command I used to inspect&#8203;:
&nbsp;  grep 'Config\{pager\}' \`locate Pod/Usage\.pm\`

4\) I am nobody\, but nevertheless\, FWIW & IMHO\, it seems a lot more
sensible to change Pod/Usage\.pm\, as Leon suggested\, than to change
Configure back to making $Config\{pager\} being a bare pathname\, merely
for this obscure case\. That would surely break many more things which
rely on the current \(and good\) Configure behavior\.

5\) Independently\, it still seems to me that\, on that line\, $ENV\{PAGER\}
should be preferred to the Perl\-determined pager\.

Thanks\,
Karl

**Comment by kberry** [comment]
I opened bugs with Pod::Usage at CPAN for these two issues. So I think this can be closed. (Apparently I don't have permission to do so.)
https://rt.cpan.org/Ticket/Display.html?id=131844
https://rt.cpan.org/Ticket/Display.html?id=131845

**Comment by jkeenan** [comment]
> I opened bugs with Pod::Usage at CPAN for these two issues. So I think this can be closed. (Apparently I don't have permission to do so.)
> https://rt.cpan.org/Ticket/Display.html?id=131844
> https://rt.cpan.org/Ticket/Display.html?id=131845

Closing as Sent to CPAN.
