### ISSUE TITLE
[PATCH] Tie::StdHandle::BINMODE does not handle LAYER argument

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16262]
Migrated from [rt.perl.org#132475](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132475) (status was 'open')

Searchable as RT132475$

**Comment by p5pRT** [comment]
### From @haukex

Dear Perl 5 Porters\,

The final test in the attached script always fails \(tested on Linux\, 
Perl 5\.8\.1 thru blead\, and Windows on several Perl versions\)\. The reason 
is that Tie&#8203;::StdHandle&#8203;::BINMODE is implemented like this&#8203;:

&nbsp;  sub BINMODE \{ binmode\($\_\[0\]\) \}

meaning that the layer argument is not passed through\. The attached 
patch fixes this \(tests included\) by changing the implementation to&#8203;:

&nbsp;  sub BINMODE \{ &CORE&#8203;::binmode\(shift\, @&#8203;\_\) \}

This is based on the first of the patches that I wrote about a while ago 
here \(this time submitted as a bug for tracking\)&#8203;:
https://www.nntp.perl.org/group/perl.perl5.porters/2017/09/msg246402.html

Thanks\, Best Regards\,
\-\- Hauke D

**Comment by p5pRT** [comment]
### From @haukex

[tie_stdhandle_binmode_2.pl](https://rt-archive.perl.org/perl5/Ticket/Attachment/1509166/809240/tie_stdhandle_binmode_2.pl)

**Comment by p5pRT** [comment]
### From @haukex

<details><summary>0001-Tie-StdHandle-BINMODE-handle-layer-argument.patch</summary>

```diff
From 6d372dc31841cd31461dc3f5d86e0f80fc2ebd0a Mon Sep 17 00:00:00 2001
From: Hauke D <haukex@zero-g.net>
Date: Mon, 20 Nov 2017 15:31:57 +0100
Subject: [PATCH] Tie::StdHandle::BINMODE: handle layer argument

BINMODE was not handling the LAYER argument.
Also bump the version number.
---
 lib/Tie/Handle/stdhandle.t | 13 ++++++++++++-
 lib/Tie/StdHandle.pm       |  4 ++--
 2 files changed, 14 insertions(+), 3 deletions(-)

diff --git a/lib/Tie/Handle/stdhandle.t b/lib/Tie/Handle/stdhandle.t
index d2f04bcc5c..6c20d90f2b 100644
--- a/lib/Tie/Handle/stdhandle.t
+++ b/lib/Tie/Handle/stdhandle.t
@@ -5,7 +5,7 @@ BEGIN {
     @INC = '../lib';
 }
 
-use Test::More tests => 27;
+use Test::More tests => 29;
 
 use_ok('Tie::StdHandle');
 
@@ -72,6 +72,17 @@ is($b, "rhubarbX\n", "b eq rhubarbX");
 $b = <$f>;
 is($b, "89\n", "b eq 89");
 
+# binmode should pass through layer argument
+
+binmode $f, ':raw';
+ok !grep( $_ eq 'utf8', PerlIO::get_layers(tied(*$f)) ),
+    'no utf8 in layers after binmode :raw';
+binmode $f, ':utf8';
+ok grep( $_ eq 'utf8', PerlIO::get_layers(tied(*$f)) ),
+    'utf8 is in layers after binmode :utf8';
+
+# finish up
+
 ok(eof($f), "eof");
 ok(close($f), "close");
 
diff --git a/lib/Tie/StdHandle.pm b/lib/Tie/StdHandle.pm
index dfb86634f0..fb79a986c6 100644
--- a/lib/Tie/StdHandle.pm
+++ b/lib/Tie/StdHandle.pm
@@ -4,7 +4,7 @@ use strict;
 
 use Tie::Handle;
 our @ISA = 'Tie::Handle';
-our $VERSION = '4.5';
+our $VERSION = '4.6';
 
 =head1 NAME
 
@@ -48,7 +48,7 @@ sub TELL    { tell($_[0]) }
 sub FILENO  { fileno($_[0]) }
 sub SEEK    { seek($_[0],$_[1],$_[2]) }
 sub CLOSE   { close($_[0]) }
-sub BINMODE { binmode($_[0]) }
+sub BINMODE { &CORE::binmode(shift, @_) }
 
 sub OPEN
 {
-- 
2.15.0


```
</details>

**Comment by p5pRT** [comment]
### From @atoomic

Thanks for the patch\, I've kicked a smoker run with it
https://github.com/p5h/perl5demo/pull/32

nicolas

On Mon\, 20 Nov 2017 07&#8203;:31&#8203;:23 \-0800\, haukex@&#8203;zero\-g\.net wrote&#8203;:
> Dear Perl 5 Porters\,
> 
> The final test in the attached script always fails \(tested on Linux\, 
> Perl 5\.8\.1 thru blead\, and Windows on several Perl versions\)\. The reason 
> is that Tie&#8203;::StdHandle&#8203;::BINMODE is implemented like this&#8203;:
> 
>   sub BINMODE \{ binmode\($\_\[0\]\) \}
> 
> meaning that the layer argument is not passed through\. The attached 
> patch fixes this \(tests included\) by changing the implementation to&#8203;:
> 
>   sub BINMODE \{ &CORE&#8203;::binmode\(shift\, @&#8203;\_\) \}
> 
> This is based on the first of the patches that I wrote about a while ago 
> here \(this time submitted as a bug for tracking\)&#8203;:
> https://www.nntp.perl.org/group/perl.perl5.porters/2017/09/msg246402.html
> 
> Thanks\, Best Regards\,
> \-\- Hauke D

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @jkeenan

On Mon\, 20 Nov 2017 15&#8203;:58&#8203;:42 GMT\, atoomic@&#8203;cpan\.org wrote&#8203;:
> Thanks for the patch\, I've kicked a smoker run with it
> https://github.com/p5h/perl5demo/pull/32
> 
> nicolas
> 
> On Mon\, 20 Nov 2017 07&#8203;:31&#8203;:23 \-0800\, haukex@&#8203;zero\-g\.net wrote&#8203;:
> > Dear Perl 5 Porters\,
> > 
> > The final test in the attached script always fails \(tested on Linux\, 
> > Perl 5\.8\.1 thru blead\, and Windows on several Perl versions\)\. The reason 
> > is that Tie&#8203;::StdHandle&#8203;::BINMODE is implemented like this&#8203;:
> > 
> >   sub BINMODE \{ binmode\($\_\[0\]\) \}
> > 
> > meaning that the layer argument is not passed through\. The attached 
> > patch fixes this \(tests included\) by changing the implementation to&#8203;:
> > 
> >   sub BINMODE \{ &CORE&#8203;::binmode\(shift\, @&#8203;\_\) \}
> > 
> > This is based on the first of the patches that I wrote about a while ago 
> > here \(this time submitted as a bug for tracking\)&#8203;:
> > https://www.nntp.perl.org/group/perl.perl5.porters/2017/09/msg246402.html
> > 
> > Thanks\, Best Regards\,
> > \-\- Hauke D
> 

Also available in this branch&#8203;:

smoke\-me/jkeenan/haukex/132475\-binmode
\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @haukex

Hi\,

Bump\! Thanks for the smokers\, how are things looking there?

Best\,
\-\- Hauke D

On Mon\, 20 Nov 2017 14&#8203;:43&#8203;:13 \-0800\, jkeenan wrote&#8203;:
> On Mon\, 20 Nov 2017 15&#8203;:58&#8203;:42 GMT\, atoomic@&#8203;cpan\.org wrote&#8203;:
> > Thanks for the patch\, I've kicked a smoker run with it
> > https://github.com/p5h/perl5demo/pull/32
> >
> > nicolas
> 
> Also available in this branch&#8203;:
> 
> smoke\-me/jkeenan/haukex/132475\-binmode

**Comment by toddr** [comment]
@haukex it passed :) https://travis-ci.org/p5h/perl5demo/builds/304812396?utm_source=github_status&utm_medium=notification

**Comment by xsawyerx** [comment]
Can we merge, then?

**Comment by haukex** [comment]
Thanks all!
