### ISSUE TITLE
possible documentation error in perldata

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16288]
Migrated from [rt.perl.org#132537](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132537) (status was 'open')

Searchable as RT132537$

**Comment by p5pRT** [comment]
### From calestyo@scientia.net


This is a bug report for perl from calestyo@&#8203;scientia\.net\,
generated with the help of perlbug 1\.40 running under perl 5\.26\.1\.




---
Hi\.

https://perldoc.perl.org/perldata.html says&#8203;:
>LISTs do automatic interpolation of sublists\. That is\, when a LIST is evaluated\,
>each element of the list is evaluated in list context\, and the resulting list
>value is interpolated into LIST just as if each individual element were a member of LIST\.

This seems to be wrong\, in the sense\, that the list
itself doesn't mandate its elements to be evaluated
in list context\.
It's rather the context in which the list is evaluated
which determines the context which can be scalar
or list contect\.

E\.g\.
$ perl \-de1

Loading DB routines from perl5db\.pl version 1\.51
Editor support available\.

Enter h or 'h h' for help\, or 'man perldebug' for more help\.

main&#8203;::\(\-e&#8203;:1\)&#8203;:    1
&nbsp;  DB\<1> @&#8203;a=\("a"\, "b"\, "c"\, "d"\);

&nbsp;  DB\<2> @&#8203;b=\(1\, 2\, @&#8203;a\);

&nbsp;  DB\<3> print "@&#8203;b";
1 2 a b c d
&nbsp;  DB\<4> $b=\(1\, 2\, @&#8203;a\);

&nbsp;  DB\<5> print "$b";
4
&nbsp;  DB\<6> @&#8203;a=\("a"\, "b"\, "c"\, "d"\, "e"\, "f"\);

&nbsp;  DB\<7> $b=\(1\, 2\, @&#8203;a\);

&nbsp;  DB\<8> print "$b";
6
&nbsp;  DB\<9> 


When doing $b=\(1\, 2\, @&#8203;a\); the list is evaluated in scalar context
and thus $b gets the last element of the list assigned\.
If the list itself\, i\.e\. it's elements\, would be evaluated in list
context\, as the above text claims\, the last element should become
"d"\, however it seems to be evaluated in scalar context\, which means
@&#8203;a evaluates to the length of the array a\, which is then also the
last element of the list\, being assigned to $b\.


Cheers\,
Chris\.


---


---
Flags&#8203;:
&nbsp;    category=docs
&nbsp;    severity=medium


---
Site configuration information for perl 5\.26\.1&#8203;:

Configured by Debian Project at Tue Nov 28 17&#8203;:44&#8203;:14 UTC 2017\.

Summary of my perl5 \(revision 5 version 26 subversion 1\) configuration&#8203;:
&nbsp;   
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux
&nbsp;    osvers=4\.9\.0
&nbsp;    archname=x86\_64\-linux\-gnu\-thread\-multi
&nbsp;    uname='linux localhost 4\.9\.0 \#1 smp debian 4\.9\.0 x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusethreads \-Duselargefiles \-Dcc=x86\_64\-linux\-gnu\-gcc \-Dcpp=x86\_64\-linux\-gnu\-cpp \-Dld=x86\_64\-linux\-gnu\-gcc \-Dccflags=\-DDEBIAN \-Wdate\-time \-D\_FORTIFY\_SOURCE=2 \-g \-O2 \-fdebug\-prefix\-map=/build/perl\-w2lU16/perl\-5\.26\.1=\. \-fstack\-protector\-strong \-Wformat \-Werror=format\-security \-Dldflags= \-Wl\,\-z\,relro \-Dlddlflags=\-shared \-Wl\,\-z\,relro \-Dcccdlflags=\-fPIC \-Darchname=x86\_64\-linux\-gnu \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.26 \-Darchlib=/usr/lib/x86\_64\-linux\-gnu/perl/5\.26 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/x86\_64\-linux\-gnu/perl5/5\.26 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.26\.1 \-Dsitearch=/usr/local/lib/x86\_64\-linux\-gnu/perl/5\.26\.1 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1 \-Dsiteman3dir=/usr/local/man/man3 \-Duse64bitint \-Dman1ext=1 \-Dman3ext=3perl
\-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Ud\_ualarm \-Uusesfio \-Uusenm \-Ui\_libutil \-Ui\_xlocale \-Uversiononly \-DDEBUGGING=\-g \-Doptimize=\-O2 \-dEs \-Duseshrplib \-Dlibperl=libperl\.so\.5\.26\.1'
&nbsp;    hint=recommended
&nbsp;    useposix=true
&nbsp;    d\_sigaction=define
&nbsp;    useithreads=define
&nbsp;    usemultiplicity=define
&nbsp;    use64bitint=define
&nbsp;    use64bitall=define
&nbsp;    uselongdouble=undef
&nbsp;    usemymalloc=n
&nbsp;    default\_inc\_excludes\_dot=define
&nbsp;    bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='x86\_64\-linux\-gnu\-gcc'
&nbsp;    ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fwrapv \-fno\-strict\-aliasing \-pipe \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'
&nbsp;    optimize='\-O2 \-g'
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fwrapv \-fno\-strict\-aliasing \-pipe \-I/usr/local/include'
&nbsp;    ccversion=''
&nbsp;    gccversion='7\.2\.0'
&nbsp;    gccosandvers=''
&nbsp;    intsize=4
&nbsp;    longsize=8
&nbsp;    ptrsize=8
&nbsp;    doublesize=8
&nbsp;    byteorder=12345678
&nbsp;    doublekind=3
&nbsp;    d\_longlong=define
&nbsp;    longlongsize=8
&nbsp;    d\_longdbl=define
&nbsp;    longdblsize=16
&nbsp;    longdblkind=3
&nbsp;    ivtype='long'
&nbsp;    ivsize=8
&nbsp;    nvtype='double'
&nbsp;    nvsize=8
&nbsp;    Off\_t='off\_t'
&nbsp;    lseeksize=8
&nbsp;    alignbytes=8
&nbsp;    prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='x86\_64\-linux\-gnu\-gcc'
&nbsp;    ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/7/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lgdbm \-lgdbm\_compat \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    libc=libc\-2\.25\.so
&nbsp;    so=so
&nbsp;    useshrplib=true
&nbsp;    libperl=libperl\.so\.5\.26
&nbsp;    gnulibc\_version='2\.25'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs
&nbsp;    dlext=so
&nbsp;    d\_dlsymun=undef
&nbsp;    ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'
&nbsp;    lddlflags='\-shared \-L/usr/local/lib \-fstack\-protector\-strong'

Locally applied patches&#8203;:
&nbsp;    DEBPKG&#8203;:debian/cpan\_definstalldirs \- Provide a sensible INSTALLDIRS default for modules installed from CPAN\.
&nbsp;    DEBPKG&#8203;:debian/db\_file\_ver \- https://bugs.debian.org/340047 Remove overly restrictive DB\_File version check\.
&nbsp;    DEBPKG&#8203;:debian/doc\_info \- Replace generic man\(1\) instructions with Debian\-specific information\.
&nbsp;    DEBPKG&#8203;:debian/enc2xs\_inc \- https://bugs.debian.org/290336 Tweak enc2xs to follow symlinks and ignore missing @&#8203;INC directories\.
&nbsp;    DEBPKG&#8203;:debian/errno\_ver \- https://bugs.debian.org/343351 Remove Errno version check due to upgrade problems with long\-running processes\.
&nbsp;    DEBPKG&#8203;:debian/libperl\_embed\_doc \- https://bugs.debian.org/186778 Note that libperl\-dev package is required for embedded linking
&nbsp;    DEBPKG&#8203;:fixes/respect\_umask \- Respect umask during installation
&nbsp;    DEBPKG&#8203;:debian/writable\_site\_dirs \- Set umask approproately for site install directories
&nbsp;    DEBPKG&#8203;:debian/extutils\_set\_libperl\_path \- EU&#8203;:MM&#8203;: set location of libperl\.a under /usr/lib
&nbsp;    DEBPKG&#8203;:debian/no\_packlist\_perllocal \- Don't install \.packlist or perllocal\.pod for perl or vendor
&nbsp;    DEBPKG&#8203;:debian/fakeroot \- Postpone LD\_LIBRARY\_PATH evaluation to the binary targets\.
&nbsp;    DEBPKG&#8203;:debian/instmodsh\_doc \- Debian policy doesn't install \.packlist files for core or vendor\.
&nbsp;    DEBPKG&#8203;:debian/ld\_run\_path \- Remove standard libs from LD\_RUN\_PATH as per Debian policy\.
&nbsp;    DEBPKG&#8203;:debian/libnet\_config\_path \- Set location of libnet\.cfg to /etc/perl/Net as /usr may not be writable\.
&nbsp;    DEBPKG&#8203;:debian/mod\_paths \- Tweak @&#8203;INC ordering for Debian
&nbsp;    DEBPKG&#8203;:debian/perlivp \- https://bugs.debian.org/510895 Make perlivp skip include directories in /usr/local
&nbsp;    DEBPKG&#8203;:debian/deprecate\-with\-apt \- https://bugs.debian.org/747628 Point users to Debian packages of deprecated core modules
&nbsp;    DEBPKG&#8203;:debian/squelch\-locale\-warnings \- https://bugs.debian.org/508764 Squelch locale warnings in Debian package maintainer scripts
&nbsp;    DEBPKG&#8203;:debian/patchlevel \- https://bugs.debian.org/567489 List packaged patches for 5\.26\.1\-3 in patchlevel\.h
&nbsp;    DEBPKG&#8203;:fixes/document\_makemaker\_ccflags \- https://bugs.debian.org/628522 \[rt\.cpan\.org \#68613\] Document that CCFLAGS should include $Config\{ccflags\}
&nbsp;    DEBPKG&#8203;:debian/find\_html2text \- https://bugs.debian.org/640479 Configure CPAN&#8203;::Distribution with correct name of html2text
&nbsp;    DEBPKG&#8203;:debian/perl5db\-x\-terminal\-emulator\.patch \- https://bugs.debian.org/668490 Invoke x\-terminal\-emulator rather than xterm in perl5db\.pl
&nbsp;    DEBPKG&#8203;:debian/cpan\-missing\-site\-dirs \- https://bugs.debian.org/688842 Fix CPAN&#8203;::FirstTime defaults with nonexisting site dirs if a parent is writable
&nbsp;    DEBPKG&#8203;:fixes/memoize\_storable\_nstore \- \[rt\.cpan\.org \#77790\] https://bugs.debian.org/587650 Memoize&#8203;::Storable&#8203;: respect 'nstore' option not respected
&nbsp;    DEBPKG&#8203;:debian/makemaker\-pasthru \- https://bugs.debian.org/758471 Pass LD settings through to subdirectories
&nbsp;    DEBPKG&#8203;:debian/makemaker\-manext \- https://bugs.debian.org/247370 Make EU&#8203;::MakeMaker honour MANnEXT settings in generated manpage headers
&nbsp;    DEBPKG&#8203;:debian/kfreebsd\-softupdates \- https://bugs.debian.org/796798 Work around Debian Bug\#796798
&nbsp;    DEBPKG&#8203;:fixes/autodie\-scope \- https://bugs.debian.org/798096 Fix a scoping issue with "no autodie" and the "system" sub
&nbsp;    DEBPKG&#8203;:fixes/memoize\-pod \- \[rt\.cpan\.org \#89441\] Fix POD errors in Memoize
&nbsp;    DEBPKG&#8203;:debian/hurd\-softupdates \- https://bugs.debian.org/822735 Fix t/op/stat\.t failures on hurd
&nbsp;    DEBPKG&#8203;:fixes/math\_complex\_doc\_great\_circle \- https://bugs.debian.org/697567 \[rt\.cpan\.org \#114104\] Math&#8203;::Trig&#8203;: clarify definition of great\_circle\_midpoint
&nbsp;    DEBPKG&#8203;:fixes/math\_complex\_doc\_see\_also \- https://bugs.debian.org/697568 \[rt\.cpan\.org \#114105\] Math&#8203;::Trig&#8203;: add missing SEE ALSO
&nbsp;    DEBPKG&#8203;:fixes/math\_complex\_doc\_angle\_units \- https://bugs.debian.org/731505 \[rt\.cpan\.org \#114106\] Math&#8203;::Trig&#8203;: document angle units
&nbsp;    DEBPKG&#8203;:fixes/cpan\_web\_link \- https://bugs.debian.org/367291 CPAN&#8203;: Add link to main CPAN web site
&nbsp;    DEBPKG&#8203;:fixes/time\_piece\_doc \- https://bugs.debian.org/817925 Time&#8203;::Piece&#8203;: Improve documentation for add\_months and add\_years
&nbsp;    DEBPKG&#8203;:fixes/extutils\_makemaker\_reproducible \- https&#8203;://bugs\.debian\.org/835815 https://bugs.debian.org/834190 Make perllocal\.pod files reproducible
&nbsp;    DEBPKG&#8203;:fixes/file\_path\_hurd\_errno \- File\-Path&#8203;: Fix test failure in Hurd due to hard\-coded ENOENT
&nbsp;    DEBPKG&#8203;:debian/hppa\_op\_optimize\_workaround \- https://bugs.debian.org/838613 Temporarily lower the optimization of op\.c on hppa due to gcc\-6 problems
&nbsp;    DEBPKG&#8203;:debian/installman\-utf8 \- https://bugs.debian.org/840211 Generate man pages with UTF\-8 characters
&nbsp;    DEBPKG&#8203;:fixes/file\_path\_chmod\_race \- https://bugs.debian.org/863870 \[rt\.cpan\.org \#121951\] Prevent directory chmod race attack\.
&nbsp;    DEBPKG&#8203;:fixes/extutils\_file\_path\_compat \- Correct the order of tests of chmod\(\)\. \(\#294\)
&nbsp;    DEBPKG&#8203;:fixes/getopt\-long\-2 \- \[rt\.cpan\.org \#120300\] Withdraw part of commit 5d9947fb445327c7299d8beb009d609bc70066c0\, which tries to implement more GNU getopt\_long campatibility\. GNU
&nbsp;    DEBPKG&#8203;:fixes/getopt\-long\-3 \- provide a default value for optional arguments
&nbsp;    DEBPKG&#8203;:fixes/getopt\-long\-4 \- https://bugs.debian.org/864544 \[rt\.cpan\.org \#122068\] Fix issue \#122068\.
&nbsp;    DEBPKG&#8203;:fixes/test\-builder\-reset \- https://bugs.debian.org/865894 Reset inside subtest maintains parent
&nbsp;    DEBPKG&#8203;:debian/hppa\_opmini\_optimize\_workaround \- https://bugs.debian.org/869122 Lower the optimization level of opmini\.c on hppa
&nbsp;    DEBPKG&#8203;:debian/sh4\_op\_optimize\_workaround \- https://bugs.debian.org/869373 Also lower the optimization level of op\.c and opmini\.c on sh4
&nbsp;    DEBPKG&#8203;:fixes/json\-pp\-example \- \[rt\.cpan\.org \#92793\] https://bugs.debian.org/871837 fix RT\-92793&#8203;: bug in SYNOPSIS
&nbsp;    DEBPKG&#8203;:debian/perldoc\-pager \- https://bugs.debian.org/870340 \[rt\.cpan\.org \#120229\] Fix perldoc terminal escapes when sensible\-pager is less
&nbsp;    DEBPKG&#8203;:debian/prune\_libs \- https://bugs.debian.org/128355 Prune the list of libraries wanted to what we actually need\.
&nbsp;    DEBPKG&#8203;:debian/configure\-regen \- https://bugs.debian.org/762638 Regenerate Configure et al\. after probe unit changes
&nbsp;    DEBPKG&#8203;:fixes/rename\-filexp\.U\-phase1 \- regen\-configure&#8203;: rename filexp\.U to filexp\_path\.U\, phase 1
&nbsp;    DEBPKG&#8203;:fixes/rename\-filexp\.U\-phase2 \- regen\-configure&#8203;: rename filexp\.U to filexp\_path\.U\, phase 2
&nbsp;    DEBPKG&#8203;:fixes/packaging\_test\_skips \- Skip various tests if PERL\_BUILD\_PACKAGING is set



---
@&#8203;INC for perl 5\.26\.1&#8203;:
&nbsp;    /etc/perl
&nbsp;    /usr/local/lib/x86\_64\-linux\-gnu/perl/5\.26\.1
&nbsp;    /usr/local/share/perl/5\.26\.1
&nbsp;    /usr/lib/x86\_64\-linux\-gnu/perl5/5\.26
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/x86\_64\-linux\-gnu/perl/5\.26
&nbsp;    /usr/share/perl/5\.26
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    /usr/lib/x86\_64\-linux\-gnu/perl\-base



---
Environment for perl 5\.26\.1&#8203;:
&nbsp;    HOME=/home/calestyo
&nbsp;    LANG=en\_DE\.UTF\-8
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/local/games&#8203;:/usr/games
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @iabyn

On Wed\, Dec 06\, 2017 at 06&#8203;:02&#8203;:52PM \-0800\, via RT wrote&#8203;:
> https://perldoc.perl.org/perldata.html says&#8203;:
> >LISTs do automatic interpolation of sublists\. That is\, when a LIST is evaluated\,
> >each element of the list is evaluated in list context\, and the resulting list
> >value is interpolated into LIST just as if each individual element were a member of LIST\.
> 
> This seems to be wrong\, in the sense\, that the list
> itself doesn't mandate its elements to be evaluated
> in list context\.

It does by definition&#8203;:

> When doing $b=\(1\, 2\, @&#8203;a\); the list is evaluated in scalar context

No\, in scalar context\, there isn't a list; instead there is merely
a sequence of comma operators \(which return their RH argument\)\, with
parentheses added for the purpose of precedence\.

\-\- 
Hofstadter's Law&#8203;: It always takes longer than you expect\, even when you
take into account Hofstadter's Law\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From cm.perl@abtela.com

Le 08/12/2017 à 10&#8203;:12\, Dave Mitchell a écrit :
> On Wed\, Dec 06\, 2017 at 06&#8203;:02&#8203;:52PM \-0800\, via RT wrote&#8203;:
>> https://perldoc.perl.org/perldata.html says&#8203;:
>>> LISTs do automatic interpolation of sublists\. That is\, when a LIST is evaluated\,
>>> each element of the list is evaluated in list context\, and the resulting list
>>> value is interpolated into LIST just as if each individual element were a member of LIST\.
>>
>> This seems to be wrong\, in the sense\, that the list
>> itself doesn't mandate its elements to be evaluated
>> in list context\.
> 
> It does by definition&#8203;:
> 
>> When doing $b=\(1\, 2\, @&#8203;a\); the list is evaluated in scalar context
> 
> No\, in scalar context\, there isn't a list; instead there is merely
> a sequence of comma operators \(which return their RH argument\)\, with
> parentheses added for the purpose of precedence\.
> 
FWIW I find the sentence above clearer than the current wording in perldata

&nbsp;  677 =head2 List value constructors
&nbsp;  678 X\<list>
&nbsp;  679
&nbsp;  680 List values are denoted by separating individual values by commas
&nbsp;  681 \(and enclosing the list in parentheses where precedence requires it\)&#8203;:
&nbsp;  682
&nbsp;  683     \(LIST\)
&nbsp;  684
&nbsp;  685 In a context not requiring a list value\, the value of what appears
&nbsp;  686 to be a list literal is simply the value of the final element\, as
&nbsp;  687 with the C comma operator\.  For example\,
&nbsp;  688
&nbsp;  689     @&#8203;foo = \('cc'\, '\-E'\, $bar\);
&nbsp;  690
&nbsp;  691 assigns the entire list value to array @&#8203;foo\, but
&nbsp;  692
&nbsp;  693     $foo = \('cc'\, '\-E'\, $bar\);
&nbsp;  694
&nbsp;  695 assigns the value of variable $bar to the scalar variable $foo\.

YMMV\. From experience this is a significant hurdle for beginners\.

@&#8203;array  = \(\.\.\.\)&#8203;: \# OK
%hash   = \(\.\.\.\); \# OK
$scalar = \(\.\.\.\); \# Possibly not what was intended\,
&nbsp;                  \# consider $scalar = \[\.\.\.\] instead ?

**Comment by p5pRT** [comment]
### From calestyo@scientia.net

On Fri\, 2017\-12\-08 at 01&#8203;:12 \-0800\, Dave Mitchell via RT wrote&#8203;:
> It does by definition&#8203;:
> No\, in scalar context\, there isn't a list; instead there is merely
> a sequence of comma operators \(which return their RH argument\)\, with
> parentheses added for the purpose of precedence\.

That's at least not how the text in perldata or perlop does it make
look like\.
It's rather written as it's still a list \(and it even says\, that all
elements are actually evaluated\)\, just that it doesn't "return" the
whole list\, but rather only it's last element\.


\- \(x\, y\, z\) seems to be clearly what is defined to be a list\, every
&nbsp;  beginner will consider it as such\, regardless of its context
\- other text places say that in both contexts \(scalar/list\) all
&nbsp;  elements are evaluated\, just that in scalar context everything but
&nbsp;  the last is discarded

So conceptually it still seems to be a list\, and then the text that I
was mentioning is still ambiguous\.\.\.
People would think \(by operator precedence\)&#8203;:
1\. evaluation of the x\, y\, z \(i\.e\. the list\)
&nbsp;   and the text says always in list context
2\. for list context   = return all evaluated elements as a list
&nbsp;   for scalar context = return only the last element \(which would
&nbsp;   however\, by the documentation\, be evaluated in list context\, which
&nbsp;   it is not\.


Cheers\,
Chris\.

**Comment by p5pRT** [comment]
### From @grinnz

On Sat\, Dec 9\, 2017 at 11&#8203;:11 PM\, Christoph Anton Mitterer \<
calestyo@&#8203;scientia\.net> wrote&#8203;:

> On Fri\, 2017\-12\-08 at 01&#8203;:12 \-0800\, Dave Mitchell via RT wrote&#8203;:
> > It does by definition&#8203;:
> > No\, in scalar context\, there isn't a list; instead there is merely
> > a sequence of comma operators \(which return their RH argument\)\, with
> > parentheses added for the purpose of precedence\.
>
> That's at least not how the text in perldata or perlop does it make
> look like\.
> It's rather written as it's still a list \(and it even says\, that all
> elements are actually evaluated\)\, just that it doesn't "return" the
> whole list\, but rather only it's last element\.
>
>
> \- \(x\, y\, z\) seems to be clearly what is defined to be a list\, every
>   beginner will consider it as such\, regardless of its context
> \- other text places say that in both contexts \(scalar/list\) all
>   elements are evaluated\, just that in scalar context everything but
>   the last is discarded
>
> So conceptually it still seems to be a list\, and then the text that I
> was mentioning is still ambiguous\.\.\.
> People would think \(by operator precedence\)&#8203;:
> 1\. evaluation of the x\, y\, z \(i\.e\. the list\)
>    and the text says always in list context
> 2\. for list context   = return all evaluated elements as a list
>    for scalar context = return only the last element \(which would
>    however\, by the documentation\, be evaluated in list context\, which
>    it is not\.


The definition of 'list' in perl is more precise than that\. In scalar
context x\, y\, z \(with or without parentheses\) is not a list\, it is instead
a sequence of expressions like in C\. They are evaluated in order and then
the last one is returned\.

\-Dan

**Comment by khwilliamson** [comment]
Is this closable?

**Comment by demerphq** [comment]
I think the OP has a point that this is a painful point for beginners and we could do better at documenting it, but there is no proposed language change, and the wording of the ticket isn't really correct. I think we could close it and create a new ticket that is more clear about what needs to be done.

**Comment by demerphq** [comment]
BTW, this language in perldata:

```
If you evaluate an array in scalar context, it returns the length
of the array.  (Note that this is not true of lists, which return
the last value, like the C comma operator, nor of built-in functions,
which return whatever they feel like returning.)  The following is
always true:
X<array, length>
```

seems to contradict what @iabyn and @Grinnz say in this ticket. I am not arguing with their interpretation which I agree with in principal, but it seems a slippery ground. Most people would say:

```
my $x= (1,2,3,4,5);
```

is a `list in scalar context` similar to what the docs I quoted above imply. However @iabyn and @Grinnz are arguing its not a list at all. If its not a list then what is it to be called? "comma operator with parens for precedence" doesn't exactly roll off the tongue.

**Comment by Grinnz** [comment]
I suppose you could call it syntactically/visually a list, but functionally no list is formed by the comma operator in that context. As a similar example `my $x = 1..5;` is neither syntactically nor functionally a list because that becomes the flipflop operator. The danger of referring to that construct as a list is extending assumptions about other list-like things which all behave differently (most commonly arrays).

**Comment by demerphq** [comment]
BTW, right next to the text that the OP quotes it basically says the same thing @Grinnz and @iabyn said. I think we can close this ticket. What do you think @Grinnz ?

**Comment by Grinnz** [comment]
If you're referring to `In a context not requiring a list value, the value of what appears to be a list literal is simply the value of the final element, as with the C comma operator.` - if anything it could be clearer which operators it's talking about, it only calls out arrays specifically after but there are some other exceptional cases. But really this section is about lists, so I don't think it's necessary for it to go too in depth about scalar context.

**Comment by demerphq** [comment]
On Tue, 19 Apr 2022 at 18:33, Dan Book ***@***.***> wrote:

> If you're referring to In a context not requiring a list value, the value
> of what appears to be a list literal is simply the value of the final
> element, as with the C comma operator. - if anything it could be clearer
> which operators it's talking about, it only calls out arrays specifically
> after but there are some other exceptional cases. But really this section
> is about lists, so I don't think it's necessary for it to go too in depth
> about scalar context.
>
Yeah, to me the "what appears to be a list literal" supports the notion
that even thought

$x= (1,2,3);

looks like a list constructor it is not.

My question was actually: do you agree given that clause that we can close
the ticket?

 --
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by Grinnz** [comment]
Yes, I think it is sufficiently covered though improvements are always welcome
