### ISSUE TITLE
uninitialized variable and integer overrun in pp.c and toke.c

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16290]
Migrated from [rt.perl.org#132540](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132540) (status was 'open')

Searchable as RT132540$

**Comment by p5pRT** [comment]
### From marc-philip@die-werners.de

 From&#8203;: marc\-philip@&#8203;die\-werners\.de
To&#8203;: perlbug@&#8203;perl\.org
Message\-Id&#8203;: \<5\.26\.1\_51638\_1512643179@&#8203;WDFM33972517A>
Reply\-To&#8203;: marc\-philip@&#8203;die\-werners\.de
Subject&#8203;: uninitialized variable and integer overrun in pp\.c and toke\.c


This is a bug report for perl from marc\-philip@&#8203;die\-werners\.de\,
generated with the help of perlbug 1\.40 running under perl 5\.26\.1\.




---
Hi\,
we have some coverity code scans here\. They have found this 
uninitialized variable in pp\.c and the integer overrun in toke\.c\.
Though it might be possible that these are false positives \(no 
reasonable control path gets there\)\, it's good to mute the scan here to 
better see other \(possibly real\) problems\.

I'm attaching a patchfile\.

Best Regards
Marc\-Philip



---


---
Flags&#8203;:
&nbsp;     category=core
&nbsp;     severity=medium


---
Site configuration information for perl 5\.26\.1&#8203;:

Configured by sap at Thu Dec  7 10&#8203;:39&#8203;:47 CET 2017\.

Summary of my perl5 \(revision 5 version 26 subversion 1\) configuration&#8203;:

&nbsp;   Platform&#8203;:
&nbsp;     osname=darwin
&nbsp;     osvers=17\.2\.0
&nbsp;     archname=darwin\-thread\-multi\-2level
&nbsp;     uname='darwin wdfm33972517a 17\.2\.0 darwin kernel version 17\.2\.0&#8203;: fri 
sep 29 18&#8203;:27&#8203;:05 pdt 2017; root&#8203;:xnu\-4570\.20\.62~3release\_x86\_64 x86\_64 '
&nbsp;     config\_args='\-der \-Dmyhostname=buildhost \-Dmydomain=\.com \-Dcf\_by=sap 
\-Dprivlib=\.\.\./\.\./lib \-Dsitelib=\.\.\./\.\./lib \-Darchlib=\.\.\./\.\./lib 
\-Dsitearch=\.\.\./\.\./lib \-Dnoextensions=GDBM\_File NDBM\_File ODBM\_File 
SDBM\_File \-Ddynamic\_ext=MIME/Base64 Socket IO Time/HiRes Cwd Encode 
Data/Dumper Compress/Raw/Zlib \-Dusethreads \-Duseshrplib 
\-Duserelocatableinc 
\-Dprefix=/Users/d026948/SAPDevelop/hmexternals/perl/gen/out/perl\-5\.26\.1\-sap2\-SNAPSHOT\-darwinintel64\-release\-c 
\-Duse64bitall \-Accflags=\-B$SDKROOT/usr/include/gcc 
\-Accflags=\-B$SDKROOT/usr/lib/gcc \-Accflags=\-isystem$SDKROOT/usr/include 
\-Accflags=\-F$SDKROOT/System/Library/Frameworks 
\-Aldflags=\-Wl\,\-syslibroot\,$SDKROOT 
\-Accdlflags=\-B$SDKROOT/usr/include/gcc 
\-Accdlflags=\-B$SDKROOT/usr/lib/gcc 
\-Accdlflags=\-isystem$SDKROOT/usr/include 
\-Accdlflags=\-F$SDKROOT/System/Library/Frameworks 
\-Alddlflags=\-Wl\,\-syslibroot\,$SDKROOT'
&nbsp;     hint=recommended
&nbsp;     useposix=true
&nbsp;     d\_sigaction=define
&nbsp;     useithreads=define
&nbsp;     usemultiplicity=define
&nbsp;     use64bitint=define
&nbsp;     use64bitall=define
&nbsp;     uselongdouble=undef
&nbsp;     usemymalloc=n
&nbsp;     default\_inc\_excludes\_dot=define
&nbsp;     bincompat5005=undef
&nbsp;   Compiler&#8203;:
&nbsp;     cc='cc'
&nbsp;     ccflags ='\-fno\-common \-DPERL\_DARWIN \-mmacosx\-version\-min=10\.13 \-arch 
x86\_64 
\-B/Applications/Xcode\.app/Contents/Developer/Platforms/MacOSX\.platform/Developer/SDKs/MacOSX\.sdk/usr/include/gcc 
\-B/Applications/Xcode\.app/Contents/Developer/Platforms/MacOSX\.platform/Developer/SDKs/MacOSX\.sdk/usr/lib/gcc 
\-isystem/Applications/Xcode\.app/Contents/Developer/Platforms/MacOSX\.platform/Developer/SDKs/MacOSX\.sdk/usr/include 
\-F/Applications/Xcode\.app/Contents/Developer/Platforms/MacOSX\.platform/Developer/SDKs/MacOSX\.sdk/System/Library/Frameworks 
\-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong 
\-DPERL\_USE\_SAFE\_PUTENV'
&nbsp;     optimize='\-O3'
&nbsp;     cppflags='\-arch x86\_64 \-fno\-common \-DPERL\_DARWIN 
\-mmacosx\-version\-min=10\.13 \-arch x86\_64 
\-B/Applications/Xcode\.app/Contents/Developer/Platforms/MacOSX\.platform/Developer/SDKs/MacOSX\.sdk/usr/include/gcc 
\-B/Applications/Xcode\.app/Contents/Developer/Platforms/MacOSX\.platform/Developer/SDKs/MacOSX\.sdk/usr/lib/gcc 
\-isystem/Applications/Xcode\.app/Contents/Developer/Platforms/MacOSX\.platform/Developer/SDKs/MacOSX\.sdk/usr/include 
\-F/Applications/Xcode\.app/Contents/Developer/Platforms/MacOSX\.platform/Developer/SDKs/MacOSX\.sdk/System/Library/Frameworks 
\-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong'
&nbsp;     ccversion=''
&nbsp;     gccversion='4\.2\.1 Compatible Apple LLVM 9\.0\.0 \(clang\-900\.0\.38\)'
&nbsp;     gccosandvers=''
&nbsp;     intsize=4
&nbsp;     longsize=8
&nbsp;     ptrsize=8
&nbsp;     doublesize=8
&nbsp;     byteorder=12345678
&nbsp;     doublekind=3
&nbsp;     d\_longlong=define
&nbsp;     longlongsize=8
&nbsp;     d\_longdbl=define
&nbsp;     longdblsize=16
&nbsp;     longdblkind=3
&nbsp;     ivtype='long'
&nbsp;     ivsize=8
&nbsp;     nvtype='double'
&nbsp;     nvsize=8
&nbsp;     Off\_t='off\_t'
&nbsp;     lseeksize=8
&nbsp;     alignbytes=8
&nbsp;     prototype=define
&nbsp;   Linker and Libraries&#8203;:
&nbsp;     ld='cc \-arch x86\_64'
&nbsp;     ldflags =' \-mmacosx\-version\-min=10\.13 \-arch x86\_64 
\-Wl\,\-syslibroot\,/Applications/Xcode\.app/Contents/Developer/Platforms/MacOSX\.platform/Developer/SDKs/MacOSX\.sdk 
\-fstack\-protector\-strong'
&nbsp;     
libpth=/Applications/Xcode\.app/Contents/Developer/Toolchains/XcodeDefault\.xctoolchain/usr/lib/clang/9\.0\.0/lib 
/Applications/Xcode\.app/Contents/Developer/Toolchains/XcodeDefault\.xctoolchain/usr/lib 
/Applications/Xcode\.app/Contents/Developer/Platforms/MacOSX\.platform/Developer/SDKs/MacOSX10\.13\.sdk/usr/lib 
/usr/lib
&nbsp;     libs=\-lpthread \-ldbm \-ldl \-lm \-lutil \-lc
&nbsp;     perllibs=\-lpthread \-ldl \-lm \-lutil \-lc
&nbsp;     libc=
&nbsp;     so=dylib
&nbsp;     useshrplib=true
&nbsp;     libperl=libperl\.dylib
&nbsp;     gnulibc\_version=''
&nbsp;   Dynamic Linking&#8203;:
&nbsp;     dlsrc=dl\_dlopen\.xs
&nbsp;     dlext=bundle
&nbsp;     d\_dlsymun=undef
&nbsp;     ccdlflags=' 
\-B/Applications/Xcode\.app/Contents/Developer/Platforms/MacOSX\.platform/Developer/SDKs/MacOSX\.sdk/usr/include/gcc 
\-B/Applications/Xcode\.app/Contents/Developer/Platforms/MacOSX\.platform/Developer/SDKs/MacOSX\.sdk/usr/lib/gcc 
\-isystem/Applications/Xcode\.app/Contents/Developer/Platforms/MacOSX\.platform/Developer/SDKs/MacOSX\.sdk/usr/include 
\-F/Applications/Xcode\.app/Contents/Developer/Platforms/MacOSX\.platform/Developer/SDKs/MacOSX\.sdk/System/Library/Frameworks'
&nbsp;     cccdlflags=' '
&nbsp;     lddlflags=' \-mmacosx\-version\-min=10\.13 \-bundle \-undefined 
dynamic\_lookup 
\-Wl\,\-syslibroot\,/Applications/Xcode\.app/Contents/Developer/Platforms/MacOSX\.platform/Developer/SDKs/MacOSX\.sdk 
\-fstack\-protector\-strong'




---
@&#8203;INC for perl 5\.26\.1&#8203;:
&nbsp;     
/Users/d026948/SAPDevelop/hmexternals/perl/gen/out/perl\-5\.26\.1\-sap2\-SNAPSHOT\-darwinintel64\-release\-c/lib
&nbsp;     
/Users/d026948/SAPDevelop/hmexternals/perl/gen/out/perl\-5\.26\.1\-sap2\-SNAPSHOT\-darwinintel64\-release\-c/lib



---
Environment for perl 5\.26\.1&#8203;:
&nbsp;     
DYLD\_LIBRARY\_PATH=/Users/d026948/SAPDevelop/hmexternals/perl/gen/out/perl\-5\.26\.1\-sap2\-SNAPSHOT\-darwinintel64\-release\-c/lib/CORE
&nbsp;     HOME=/Users/d026948
&nbsp;     LANG=en\_GB\.UTF\-8
&nbsp;     LANGUAGE \(unset\)
&nbsp;     LD\_LIBRARY\_PATH \(unset\)
&nbsp;     LOGDIR \(unset\)
&nbsp;     
PATH=/Users/d026948/SAPDevelop/hmexternals/perl/gen/out/perl\-5\.26\.1\-sap2\-SNAPSHOT\-darwinintel64\-release\-c/bin&#8203;:/Users/d026948/SAPDevelop/xmake\-0\.9\.3\-8/bin&#8203;:/opt/local/bin&#8203;:/opt/local/sbin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/sbin&#8203;:/sbin&#8203;:/opt/X11/bin
&nbsp;     PERL\_BADLANG \(unset\)
&nbsp;     SHELL=/bin/csh

**Comment by p5pRT** [comment]
### From marc-philip@die-werners.de

<details><summary>coverity_5.26.1.patch</summary>

```diff
diff -Naur perl-5.26.1.orig/pp.c perl-5.26.1/pp.c
--- perl-5.26.1.orig/pp.c	2017-08-23 20:22:51.000000000 +0000
+++ perl-5.26.1/pp.c	2017-11-27 15:18:24.000000000 +0000
@@ -3811,6 +3811,7 @@
     if (! slen) {   /* If empty */
 	need = 1; /* still need a trailing NUL */
 	ulen = 0;
+        *tmpbuf = '\0';
     }
     else if (DO_UTF8(source)) {	/* Is the source utf8? */
 	doing_utf8 = TRUE;
diff -Naur perl-5.26.1.orig/toke.c perl-5.26.1/toke.c
--- perl-5.26.1.orig/toke.c	2017-07-18 23:00:00.000000000 +0000
+++ perl-5.26.1/toke.c	2017-11-27 15:33:36.000000000 +0000
@@ -8943,7 +8943,7 @@
 		HEK * const stashname = HvNAME_HEK(stash);
 		SV *  const sym = newSVhek(stashname);
                 sv_catpvs(sym, "::");
-                sv_catpvn_flags(sym, PL_tokenbuf+1, tokenbuf_len - 1, (UTF ? SV_CATUTF8 : SV_CATBYTES ));
+                sv_catpvn_flags(sym, PL_tokenbuf+1, tokenbuf_len > 0 ? tokenbuf_len - 1 : 0, (UTF ? SV_CATUTF8 : SV_CATBYTES ));
                 pl_yylval.opval = newSVOP(OP_CONST, 0, sym);
                 pl_yylval.opval->op_private = OPpCONST_ENTERED;
                 if (pit != '&')
@@ -8971,7 +8971,7 @@
         && PL_lex_state != LEX_NORMAL
         && !PL_lex_brackets)
     {
-        GV *const gv = gv_fetchpvn_flags(PL_tokenbuf + 1, tokenbuf_len - 1,
+        GV *const gv = gv_fetchpvn_flags(PL_tokenbuf + 1, tokenbuf_len > 0 ? tokenbuf_len - 1 : 0,
                                          ( UTF ? SVf_UTF8 : 0 ) | GV_ADDMG,
                                          SVt_PVAV);
         if ((!gv || ((PL_tokenbuf[0] == '@') ? !GvAV(gv) : !GvHV(gv)))
@@ -8988,11 +8988,11 @@
     /* build ops for a bareword */
     pl_yylval.opval = newSVOP(OP_CONST, 0,
 				   newSVpvn_flags(PL_tokenbuf + 1,
-						      tokenbuf_len - 1,
+                                                      tokenbuf_len > 0 ? tokenbuf_len - 1 : 0,
                                                       UTF ? SVf_UTF8 : 0 ));
     pl_yylval.opval->op_private = OPpCONST_ENTERED;
     if (pit != '&')
-	gv_fetchpvn_flags(PL_tokenbuf+1, tokenbuf_len - 1,
+        gv_fetchpvn_flags(PL_tokenbuf+1, tokenbuf_len > 0 ? tokenbuf_len - 1 : 0,
 		     (PL_in_eval ? GV_ADDMULTI : GV_ADD)
                      | ( UTF ? SVf_UTF8 : 0 ),
 		     ((PL_tokenbuf[0] == '$') ? SVt_PV

```
</details>

**Comment by p5pRT** [comment]
### From @avar

On Thu\, Dec 7\, 2017 at 1&#8203;:00 PM\, Marc\-Philip \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> we have some coverity code scans here\. They have found this
> uninitialized variable in pp\.c and the integer overrun in toke\.c\.
> Though it might be possible that these are false positives \(no
> reasonable control path gets there\)\, it's good to mute the scan here to
> better see other \(possibly real\) problems\.

Thanks\, the first hunk probably looks sensible\, although maybe it
should be done when the variable is first allocated \(i\.e\. add a \\0 at
the end\)\, but I don't know enough to be sure\.

All the rest of the hunks are paranoia that strlen\(\) will return a
negative value\. This seems to just be coverty getting confused\, the
STRLEN type is eventually defined in terms of size\_t\, which AFAIK is
always unsigned\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From marc-philip.werner@sap.com

On Thu\, 07 Dec 2017 06&#8203;:01&#8203;:35 \-0800\, avarab@&#8203;gmail\.com wrote&#8203;:
> On Thu\, Dec 7\, 2017 at 1&#8203;:00 PM\, Marc\-Philip \<perlbug\-
> followup@&#8203;perl\.org> wrote&#8203;:
> > we have some coverity code scans here\. They have found this
> > uninitialized variable in pp\.c and the integer overrun in toke\.c\.
> > Though it might be possible that these are false positives \(no
> > reasonable control path gets there\)\, it's good to mute the scan here
> > to
> > better see other \(possibly real\) problems\.
> 
> Thanks\, the first hunk probably looks sensible\, although maybe it
> should be done when the variable is first allocated \(i\.e\. add a \\0 at
> the end\)\, but I don't know enough to be sure\.
wherever you like\.

> 
> All the rest of the hunks are paranoia that strlen\(\) will return a
> negative value\. This seems to just be coverty getting confused\, the
> STRLEN type is eventually defined in terms of size\_t\, which AFAIK is
> always unsigned\.
The problem here is when tokenbuf\_len==0\. 0 is a value that strlen\(\) can return\. This does not look like a coverity confusion to me\.

Regards
MP

**Comment by p5pRT** [comment]
### From Eirik-Berg.Hanssen@allverden.no

On Thu\, Dec 7\, 2017 at 3&#8203;:01 PM\, Ævar Arnfjörð Bjarmason \<avarab@&#8203;gmail\.com>
wrote&#8203;:

> On Thu\, Dec 7\, 2017 at 1&#8203;:00 PM\, Marc\-Philip \<perlbug\-followup@&#8203;perl\.org>
> wrote&#8203;:
> > we have some coverity code scans here\. They have found this
> > uninitialized variable in pp\.c and the integer overrun in toke\.c\.
> > Though it might be possible that these are false positives \(no
> > reasonable control path gets there\)\, it's good to mute the scan here to
> > better see other \(possibly real\) problems\.
>
> Thanks\, the first hunk probably looks sensible\, although maybe it
> should be done when the variable is first allocated \(i\.e\. add a \\0 at
> the end\)\, but I don't know enough to be sure\.
>
> All the rest of the hunks are paranoia that strlen\(\) will return a
> negative value\. This seems to just be coverty getting confused\, the
> STRLEN type is eventually defined in terms of size\_t\, which AFAIK is
> always unsigned\.
>

&nbsp;  An unsigned int can still be zero\, in which case \-1 gives a negative\.  Or
is that still not worth complaining about?

&nbsp;  \(Perhaps testing for \!=0 instead of >0 would be clearer? :\) \)


Eirik

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Marc\-Philip wrote&#8203;:
>we have some coverity code scans here\. They have found this 
>uninitialized variable in pp\.c and the integer overrun in toke\.c\.

Neither is a real bug\.  In the empty string case in pp\_ucfirst\(\)\, tmpbuf
will not be read from\.  In S\_pending\_ident\(\)\, the function will not be
called with an empty string in PL\_tokenbuf \(in fact the minimum string
length is 2\)\.

\-zefram

**Comment by khwilliamson** [comment]
Is this closable then

**Comment by demerphq** [comment]
I dont think Zefram is going to answer so I will close it.
