### ISSUE TITLE
t/op/sprintf2.t: 6 test failures when compiling with g++7

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16441]
Migrated from [rt.perl.org#132913](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132913) (status was 'open')

Searchable as RT132913$

**Comment by p5pRT** [comment]
### From @jkeenan

Today I installed the gcc7 package on both FreeBSD\-10\.3 and 11\.0\.  I 
then compiled and build perl configuring like this&#8203;:

\#\#\#\#\#
sh \./Configure \-des \-Dusedevel \-Duseithreads \\
\-Doptimize="\-O2 \-pipe \-fstack\-protector \-fno\-strict\-aliasing" \\
\-Dcc="g\+\+7" \\
\-Accflags="\-Wl\,\-rpath=/usr/local/lib/gcc7" \\
\-Aldflags="\-Wl\,\-rpath=/usr/local/lib/gcc7"
\#\#\#\#\#

There were plenty of warnings during 'make'\, but since we have not yet 
heavily explored building perl with gcc7 or g\+\+7\, I'll defer discussion 
of them; 'make' completed successfully\.

During 'make test\_harness'\, however\, I got failures in t/op/sprintf2\.t\. 
Please see attachments\.

Note that we have one other long\-standing Open ticket for t/op/sprintf2\.t&#8203;:

https://rt-archive.perl.org/perl5/Ticket/Display.html?id=122591

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From @jkeenan

\# Failed test 1530 \- subnormal 0x1\.fffffffffffffp\-1022 %a 0x1\.fffffffffffffp\-1022 got 0x0p\+0 at op/sprintf2\.t line 812
\#      got "0x0p\+0"
\# expected "0x1\.fffffffffffffp\-1022"
\# Failed test 1531 \- subnormal 0x0\.fffffffffffffp\-1022 %a 0x1\.ffffffffffffep\-1023 got 0x0p\+0 at op/sprintf2\.t line 812
\#      got "0x0p\+0"
\# expected "0x1\.ffffffffffffep\-1023"
\# Failed test 1532 \- subnormal 0x0\.7ffffffffffffp\-1022 %a 0x1\.ffffffffffffcp\-1024 got 0x0p\+0 at op/sprintf2\.t line 812
\#      got "0x0p\+0"
\# expected "0x1\.ffffffffffffcp\-1024"
\# Failed test 1533 \- subnormal 0x0\.3ffffffffffffp\-1022 %a 0x1\.ffffffffffff8p\-1025 got 0x0p\+0 at op/sprintf2\.t line 812
\#      got "0x0p\+0"
\# expected "0x1\.ffffffffffff8p\-1025"
\# Failed test 1534 \- subnormal 0x0\.1ffffffffffffp\-1022 %a 0x1\.ffffffffffffp\-1026 got 0x0p\+0 at op/sprintf2\.t line 812
\#      got "0x0p\+0"
\# expected "0x1\.ffffffffffffp\-1026"
\# Failed test 1535 \- subnormal 0x0\.0ffffffffffffp\-1022 %a 0x1\.fffffffffffep\-1027 got 0x0p\+0 at op/sprintf2\.t line 812
\#      got "0x0p\+0"
\# expected "0x1\.fffffffffffep\-1027"
op/sprintf2\.t \.\. 
\# uvsize = 8
\# nvsize = 8
\# nv\_preserves\_uv\_bits = 53
\# d\_quad = define
\# uselongdouble = undef
ok 1 \- the sprintf "%\.\<number>g" optimization
ok 2 \- the sprintf "%\.\<number>f" optimization
ok 3 \- width calculation under utf8 upgrade\, length=1
ok 4 \- width calculation under utf8 upgrade\, length=5
ok 5 \- width calculation under utf8 upgrade\, length=10
ok 6 \- width calculation under utf8 upgrade\, length=20
ok 7 \- width calculation under utf8 upgrade\, length=50
ok 8 \- width calculation under utf8 upgrade\, length=100
ok 9 \- width & precision interplay with utf8 strings\, length=1
ok 10 \- width & precision interplay with utf8 strings\, length=3
ok 11 \- width & precision interplay with utf8 strings\, length=5
ok 12 \- width & precision interplay with utf8 strings\, length=10
\.\.\.
ok 1505 \- subnormal 1e\-320 %a 0x1\.fap\-1064 got 0x1\.fap\-1064
ok 1506 \- subnormal 1e\-321 %a 0x1\.94p\-1067 got 0x1\.94p\-1067
ok 1507 \- subnormal 1e\-322 %a 0x1\.4p\-1070 got 0x1\.4p\-1070
ok 1508 \- subnormal 1e\-323 %a 0x1p\-1073 got 0x1p\-1073
ok 1509 \- subnormal 1e\-324 %a 0x0p\+0 got 0x0p\+0
ok 1510 \- subnormal 3e\-320 %a 0x1\.7b8p\-1062 got 0x1\.7b8p\-1062
ok 1511 \- subnormal 3e\-321 %a 0x1\.2f8p\-1065 got 0x1\.2f8p\-1065
ok 1512 \- subnormal 3e\-322 %a 0x1\.e8p\-1069 got 0x1\.e8p\-1069
ok 1513 \- subnormal 3e\-323 %a 0x1\.8p\-1072 got 0x1\.8p\-1072
ok 1514 \- subnormal 3e\-324 %a 0x1p\-1074 got 0x1p\-1074
ok 1515 \- subnormal 7e\-320 %a 0x1\.bacp\-1061 got 0x1\.bacp\-1061
ok 1516 \- subnormal 7e\-321 %a 0x1\.624p\-1064 got 0x1\.624p\-1064
ok 1517 \- subnormal 7e\-322 %a 0x1\.1cp\-1067 got 0x1\.1cp\-1067
ok 1518 \- subnormal 7e\-323 %a 0x1\.cp\-1071 got 0x1\.cp\-1071
ok 1519 \- subnormal 7e\-324 %a 0x1p\-1074 got 0x1p\-1074
ok 1520 \- subnormal 3e\-320 %\.4a 0x1\.7b80p\-1062 got 0x1\.7b80p\-1062
ok 1521 \- subnormal 3e\-321 %\.4a 0x1\.2f80p\-1065 got 0x1\.2f80p\-1065
ok 1522 \- subnormal 3e\-322 %\.4a 0x1\.e800p\-1069 got 0x1\.e800p\-1069
ok 1523 \- subnormal 3e\-323 %\.4a 0x1\.8000p\-1072 got 0x1\.8000p\-1072
ok 1524 \- subnormal 3e\-324 %\.4a 0x1\.0000p\-1074 got 0x1\.0000p\-1074
ok 1525 \- subnormal 3e\-320 %\.1a 0x1\.8p\-1062 got 0x1\.8p\-1062
ok 1526 \- subnormal 3e\-321 %\.1a 0x1\.3p\-1065 got 0x1\.3p\-1065
ok 1527 \- subnormal 3e\-322 %\.1a 0x1\.ep\-1069 got 0x1\.ep\-1069
ok 1528 \- subnormal 3e\-323 %\.1a 0x1\.8p\-1072 got 0x1\.8p\-1072
ok 1529 \- subnormal 3e\-324 %\.1a 0x1\.0p\-1074 got 0x1\.0p\-1074
not ok 1530 \- subnormal 0x1\.fffffffffffffp\-1022 %a 0x1\.fffffffffffffp\-1022 got 0x0p\+0
not ok 1531 \- subnormal 0x0\.fffffffffffffp\-1022 %a 0x1\.ffffffffffffep\-1023 got 0x0p\+0
not ok 1532 \- subnormal 0x0\.7ffffffffffffp\-1022 %a 0x1\.ffffffffffffcp\-1024 got 0x0p\+0
not ok 1533 \- subnormal 0x0\.3ffffffffffffp\-1022 %a 0x1\.ffffffffffff8p\-1025 got 0x0p\+0
not ok 1534 \- subnormal 0x0\.1ffffffffffffp\-1022 %a 0x1\.ffffffffffffp\-1026 got 0x0p\+0
not ok 1535 \- subnormal 0x0\.0ffffffffffffp\-1022 %a 0x1\.fffffffffffep\-1027 got 0x0p\+0
ok 1536
ok 1537
ok 1538 \- \[rt\.perl\.org \\\#128888\]
ok 1539 \- \[rt\.perl\.org \\\#128889\]
ok 1540
ok 1541
ok 1542 \- \[rt\.perl\.org \\\#128890\]
ok 1543
ok 1544
\.\.\.
ok 1696 \- special\-case %\.0f on \-4503599627370503
1\.\.1696
Failed 6/1696 subtests 
&nbsp;    \(less 30 skipped subtests&#8203;: 1660 okay\)

Test Summary Report


---
op/sprintf2\.t \(Wstat&#8203;: 0 Tests&#8203;: 1696 Failed&#8203;: 6\)
&nbsp;  Failed tests&#8203;:  1530\-1535
Files=1\, Tests=1696\,  0 wallclock secs \( 0\.10 usr  0\.01 sys \+  0\.16 cusr  0\.09 csys =  0\.37 CPU\)
Result&#8203;: FAIL

**Comment by p5pRT** [comment]
### From @jkeenan

Summary of my perl5 \(revision 5 version 27 subversion 9\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 9fa1876f8c85a45e62dadb781de3c3a20361cd6f
&nbsp;  Platform&#8203;:
&nbsp;    osname=freebsd
&nbsp;    osvers=11\.0\-release\-p1
&nbsp;    archname=amd64\-freebsd\-thread\-multi
&nbsp;    uname='freebsd kid51\-freebsd\-11\-install\-3 11\.0\-release\-p1 freebsd 11\.0\-release\-p1 \#0 r306420&#8203;: thu sep 29 01&#8203;:43&#8203;:23 utc 2016 root@&#8203;releng2\.nyi\.freebsd\.org&#8203;:usrobjusrsrcsysgeneric amd64 '
&nbsp;    config\_args='\-des \-Dusedevel \-Duseithreads \-Doptimize=\-O2 \-pipe \-fstack\-protector \-fno\-strict\-aliasing \-Dcc=/usr/local/bin/g\+\+7 \-Accflags=\-Wl\,\-rpath=/usr/local/lib/gcc7 \-Aldflags=\-Wl\,\-rpath=/usr/local/lib/gcc7'
&nbsp;    hint=recommended
&nbsp;    useposix=true
&nbsp;    d\_sigaction=define
&nbsp;    useithreads=define
&nbsp;    usemultiplicity=define
&nbsp;    use64bitint=define
&nbsp;    use64bitall=define
&nbsp;    uselongdouble=undef
&nbsp;    usemymalloc=n
&nbsp;    default\_inc\_excludes\_dot=define
&nbsp;    bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='/usr/local/bin/g\+\+7'
&nbsp;    ccflags ='\-DHAS\_FPSETMASK \-DHAS\_FLOATINGPOINT\_H \-Wl\,\-rpath=/usr/local/lib/gcc7 \-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_FORTIFY\_SOURCE=2'
&nbsp;    optimize='\-O2 \-pipe \-fstack\-protector \-fno\-strict\-aliasing'
&nbsp;    cppflags='\-DHAS\_FPSETMASK \-DHAS\_FLOATINGPOINT\_H \-Wl\,\-rpath=/usr/local/lib/gcc7 \-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''
&nbsp;    gccversion='7\.2\.0'
&nbsp;    gccosandvers=''
&nbsp;    intsize=4
&nbsp;    longsize=8
&nbsp;    ptrsize=8
&nbsp;    doublesize=8
&nbsp;    byteorder=12345678
&nbsp;    doublekind=3
&nbsp;    d\_longlong=define
&nbsp;    longlongsize=8
&nbsp;    d\_longdbl=define
&nbsp;    longdblsize=16
&nbsp;    longdblkind=3
&nbsp;    ivtype='long'
&nbsp;    ivsize=8
&nbsp;    nvtype='double'
&nbsp;    nvsize=8
&nbsp;    Off\_t='off\_t'
&nbsp;    lseeksize=8
&nbsp;    alignbytes=8
&nbsp;    prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='/usr/local/bin/g\+\+7'
&nbsp;    ldflags ='\-pthread \-Wl\,\-E  \-Wl\,\-rpath=/usr/local/lib/gcc7 \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/lib /usr/local/lib /usr/local/lib/gcc7/include/c\+\+/ /usr/local/lib/gcc7/include/c\+\+//x86\_64\-portbld\-freebsd11\.1 /usr/local/lib/gcc7/include/c\+\+//backward /usr/local/lib /usr/lib
&nbsp;    libs=\-lpthread \-lgdbm \-lm \-lcrypt \-lutil
&nbsp;    perllibs=\-lpthread \-lm \-lcrypt \-lutil
&nbsp;    libc=
&nbsp;    so=so
&nbsp;    useshrplib=false
&nbsp;    libperl=libperl\.a
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs
&nbsp;    dlext=so
&nbsp;    d\_dlsymun=undef
&nbsp;    ccdlflags=' '
&nbsp;    cccdlflags='\-DPIC \-fPIC'
&nbsp;    lddlflags='\-shared  \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;:
&nbsp;    HAS\_TIMES
&nbsp;    MULTIPLICITY
&nbsp;    PERLIO\_LAYERS
&nbsp;    PERL\_COPY\_ON\_WRITE
&nbsp;    PERL\_DONT\_CREATE\_GVSV
&nbsp;    PERL\_IMPLICIT\_CONTEXT
&nbsp;    PERL\_MALLOC\_WRAP
&nbsp;    PERL\_OP\_PARENT
&nbsp;    PERL\_PRESERVE\_IVUV
&nbsp;    PERL\_USE\_DEVEL
&nbsp;    USE\_64\_BIT\_ALL
&nbsp;    USE\_64\_BIT\_INT
&nbsp;    USE\_ITHREADS
&nbsp;    USE\_LARGE\_FILES
&nbsp;    USE\_LOCALE
&nbsp;    USE\_LOCALE\_COLLATE
&nbsp;    USE\_LOCALE\_CTYPE
&nbsp;    USE\_LOCALE\_NUMERIC
&nbsp;    USE\_LOCALE\_TIME
&nbsp;    USE\_PERLIO
&nbsp;    USE\_PERL\_ATOF
&nbsp;    USE\_REENTRANT\_API
&nbsp;  Built under freebsd
&nbsp;  Compiled at Feb 26 2018 11&#8203;:52&#8203;:18
&nbsp;  %ENV&#8203;:
&nbsp;    PERL2DIR="/home/jkeenan/gitwork/perl2"
&nbsp;    PERL\_WORKDIR="/home/jkeenan/gitwork/perl"
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.27\.9/amd64\-freebsd\-thread\-multi
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.27\.9
&nbsp;    /usr/local/lib/perl5/5\.27\.9/amd64\-freebsd\-thread\-multi
&nbsp;    /usr/local/lib/perl5/5\.27\.9

**Comment by p5pRT** [comment]
### From @jkeenan

On Mon\, 26 Feb 2018 17&#8203;:32&#8203;:31 GMT\, jkeenan@&#8203;pobox\.com wrote&#8203;:
> Today I installed the gcc7 package on both FreeBSD\-10\.3 and 11\.0\.  I 
> then compiled and build perl configuring like this&#8203;:
> 
> \#\#\#\#\#
> sh \./Configure \-des \-Dusedevel \-Duseithreads \\
> \-Doptimize="\-O2 \-pipe \-fstack\-protector \-fno\-strict\-aliasing" \\
> \-Dcc="g\+\+7" \\
> \-Accflags="\-Wl\,\-rpath=/usr/local/lib/gcc7" \\
> \-Aldflags="\-Wl\,\-rpath=/usr/local/lib/gcc7"
> \#\#\#\#\#
> 
> There were plenty of warnings during 'make'\, but since we have not yet 
> heavily explored building perl with gcc7 or g\+\+7\, I'll defer discussion 
> of them; 'make' completed successfully\.
> 
> During 'make test\_harness'\, however\, I got failures in t/op/sprintf2\.t\. 
> Please see attachments\.
> 
> Note that we have one other long\-standing Open ticket for t/op/sprintf2\.t&#8203;:
> 
> https://rt-archive.perl.org/perl5/Ticket/Display.html?id=122591
> 
> Thank you very much\.
> Jim Keenan

Curiously\, if I configure with '\-Dcc="gcc7" instead of g\+\+7\, the 6 tests now PASS\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Mon\, 26 Feb 2018 17&#8203;:32&#8203;:31 GMT\, jkeenan@&#8203;pobox\.com wrote&#8203;:
> Today I installed the gcc7 package on both FreeBSD\-10\.3 and 11\.0\.  I 
> then compiled and build perl configuring like this&#8203;:
> 
> \#\#\#\#\#
> sh \./Configure \-des \-Dusedevel \-Duseithreads \\
> \-Doptimize="\-O2 \-pipe \-fstack\-protector \-fno\-strict\-aliasing" \\
> \-Dcc="g\+\+7" \\
> \-Accflags="\-Wl\,\-rpath=/usr/local/lib/gcc7" \\
> \-Aldflags="\-Wl\,\-rpath=/usr/local/lib/gcc7"
> \#\#\#\#\#
> 
> There were plenty of warnings during 'make'\, but since we have not yet 
> heavily explored building perl with gcc7 or g\+\+7\, I'll defer discussion 
> of them; 'make' completed successfully\.
> 
> During 'make test\_harness'\, however\, I got failures in t/op/sprintf2\.t\. 
> Please see attachments\.
> 
> Note that we have one other long\-standing Open ticket for t/op/sprintf2\.t&#8203;:
> 
> https://rt-archive.perl.org/perl5/Ticket/Display.html?id=122591
> 
> Thank you very much\.
> Jim Keenan

Curiously\, if I configure with '\-Dcc="gcc7" instead of g\+\+7\, the 6 tests now PASS\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @jhi

On 2/26/18 19&#8203;:32\, James E Keenan wrote&#8203;:
> Today I installed the gcc7 package on both FreeBSD\-10\.3 and 11\.0\.  I
> then compiled and build perl configuring like this&#8203;:
> 
> \#\#\#\#\#
> sh \./Configure \-des \-Dusedevel \-Duseithreads \\
> \-Doptimize="\-O2 \-pipe \-fstack\-protector \-fno\-strict\-aliasing" \\
> \-Dcc="g\+\+7" \\
> \-Accflags="\-Wl\,\-rpath=/usr/local/lib/gcc7" \\
> \-Aldflags="\-Wl\,\-rpath=/usr/local/lib/gcc7"
> \#\#\#\#\#
> 
> There were plenty of warnings during 'make'\, but since we have not yet
> heavily explored building perl with gcc7 or g\+\+7\, I'll defer discussion
> of them; 'make' completed successfully\.
> 
> During 'make test\_harness'\, however\, I got failures in t/op/sprintf2\.t\.
> Please see attachments\.

Off\-hand\, since the only tests that started failing are to do with 
subnormal handling\, and since the tests have previously passed \(right?\)
with freebsd/gcc \(some older gcc\)\, maybe something has changed in the
subnormal handling?

CCing Zefram explicitly since he usually has a good hunch about these 
things\.

> Note that we have one other long\-standing Open ticket for t/op/sprintf2\.t&#8203;:
> 
> https://rt-archive.perl.org/perl5/Ticket/Display.html?id=122591
> 
> Thank you very much\.
> Jim Keenan
>

**Comment by p5pRT** [comment]
### From @jkeenan

On Mon\, 26 Feb 2018 18&#8203;:27&#8203;:16 GMT\, jhi wrote&#8203;:
> On 2/26/18 19&#8203;:32\, James E Keenan wrote&#8203;:
> > Today I installed the gcc7 package on both FreeBSD\-10\.3 and 11\.0\.  I
> > then compiled and build perl configuring like this&#8203;:
> > 
> > \#\#\#\#\#
> > sh \./Configure \-des \-Dusedevel \-Duseithreads \\
> > \-Doptimize="\-O2 \-pipe \-fstack\-protector \-fno\-strict\-aliasing" \\
> > \-Dcc="g\+\+7" \\
> > \-Accflags="\-Wl\,\-rpath=/usr/local/lib/gcc7" \\
> > \-Aldflags="\-Wl\,\-rpath=/usr/local/lib/gcc7"
> > \#\#\#\#\#
> > 
> > There were plenty of warnings during 'make'\, but since we have not yet
> > heavily explored building perl with gcc7 or g\+\+7\, I'll defer discussion
> > of them; 'make' completed successfully\.
> > 
> > During 'make test\_harness'\, however\, I got failures in t/op/sprintf2\.t\.
> > Please see attachments\.
> 
> Off\-hand\, since the only tests that started failing are to do with 
> subnormal handling\, and since the tests have previously passed \(right?\)
> with freebsd/gcc \(some older gcc\)\, maybe something has changed in the
> subnormal handling?
> 

I only installed gcc7 \(and\, hence\, g\+\+7\) on FreeBSD\-11\.0 for the first time today\.

I previously installed gcc6\, but where was some problem installing g\+\+6\, so I've never built with the latter on this platform\.

On IRC \#p5p\, Tux mentioned that he had observed g\+\+7 test failures several months ago at the time of the core hackathon in Amsterdam \(mid\-October\)\.


> CCing Zefram explicitly since he usually has a good hunch about these 
> things\.
> 
> > Note that we have one other long\-standing Open ticket for t/op/sprintf2\.t&#8203;:
> > 
> > https://rt-archive.perl.org/perl5/Ticket/Display.html?id=122591
> > 
> > Thank you very much\.
> > Jim Keenan
> > 


\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tux

On Mon\, 26 Feb 2018 10&#8203;:57&#8203;:52 \-0800\, "James E Keenan via RT"
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:

> On Mon\, 26 Feb 2018 18&#8203;:27&#8203;:16 GMT\, jhi wrote&#8203;:
> > On 2/26/18 19&#8203;:32\, James E Keenan wrote&#8203;:  
> > > Today I installed the gcc7 package on both FreeBSD\-10\.3 and 11\.0\.  I
> > > then compiled and build perl configuring like this&#8203;:
> > > 
> > > \#\#\#\#\#
> > > sh \./Configure \-des \-Dusedevel \-Duseithreads \\
> > > \-Doptimize="\-O2 \-pipe \-fstack\-protector \-fno\-strict\-aliasing" \\
> > > \-Dcc="g\+\+7" \\
> > > \-Accflags="\-Wl\,\-rpath=/usr/local/lib/gcc7" \\
> > > \-Aldflags="\-Wl\,\-rpath=/usr/local/lib/gcc7"
> > > \#\#\#\#\#
> > > 
> > > There were plenty of warnings during 'make'\, but since we have not yet
> > > heavily explored building perl with gcc7 or g\+\+7\, I'll defer discussion
> > > of them; 'make' completed successfully\.
> > > 
> > > During 'make test\_harness'\, however\, I got failures in t/op/sprintf2\.t\.
> > > Please see attachments\.  
> > 
> > Off\-hand\, since the only tests that started failing are to do with 
> > subnormal handling\, and since the tests have previously passed \(right?\)
> > with freebsd/gcc \(some older gcc\)\, maybe something has changed in the
> > subnormal handling?
> 
> I only installed gcc7 \(and\, hence\, g\+\+7\) on FreeBSD\-11\.0 for the
> first time today\.
> 
> I previously installed gcc6\, but where was some problem installing
> g\+\+6\, so I've never built with the latter on this platform\.
> 
> On IRC \#p5p\, Tux mentioned that he had observed g\+\+7 test failures
> several months ago at the time of the core hackathon in Amsterdam
> \(mid\-October\)\.

Several month being over a year now

It is g\+\+\-6 \+ g\+\+\-7 specific \(g\+\+\-5 is ok\)

Search on \[All versions\] for host \[lx09\] on http&#8203;://perl5\.test\-smoke\.org/search

 Last  pass&#8203;: 2016\-06\-02 13&#8203;:31&#8203;:52\+00 v5\.25\.1\-98\-gad1bab9
&nbsp;             http&#8203;://perl5\.test\-smoke\.org/report/47121
&nbsp;   lx09&#8203;: Intel\(R\) Core\(TM\) i7\-2620M CPU @&#8203; 2\.70GHz \(GenuineIntel 1377MHz\) \(x86\_64/4\[8 cores\] cpus\)
&nbsp;       on        linux 4\.6\.0\-1\-default \[openSUSE Tumbleweed \(20160422\) \(x86\_64\)\]
&nbsp;       using     g\+\+ version 5\.3\.1 20160412 \[gcc\-5\-branch revision 234894\] \(\*1\)
&nbsp;       smoketime 4 hours 18 minutes \(average 32 minutes 21 seconds\)

 First fail&#8203;: 2016\-08\-27 19&#8203;:55&#8203;:14\+00 v5\.25\.4\-21\-g51068c1
&nbsp;             http&#8203;://perl5\.test\-smoke\.org/report/49402
&nbsp;   lx09&#8203;: Intel\(R\) Core\(TM\) i7\-2620M CPU @&#8203; 2\.70GHz \(GenuineIntel 1385MHz\) \(x86\_64/4\[8 cores\] cpus\)
&nbsp;       on        linux 4\.7\.2\-1\-default \[openSUSE Tumbleweed \(20160812\) \(x86\_64\)\]
&nbsp;       using     g\+\+ version 6\.1\.1 20160815 \[gcc\-6\-branch revision 239479\] \(\*1\)
&nbsp;       smoketime 2 hours 33 minutes \(average 19 minutes 9 seconds\)

> > CCing Zefram explicitly since he usually has a good hunch about these 
> > things\.
> >   
> > > Note that we have one other long\-standing Open ticket for t/op/sprintf2\.t&#8203;:
> > > 
> > > https://rt-archive.perl.org/perl5/Ticket/Display.html?id=122591
> > > 
> > > Jim Keenan

\-\- 
H\.Merijn Brand  http&#8203;://tux\.nl   Perl Monger  http&#8203;://amsterdam\.pm\.org/
using perl5\.00307 \.\. 5\.27   porting perl5 on HP\-UX\, AIX\, and openSUSE
http&#8203;://mirrors\.develooper\.com/hpux/        http&#8203;://www\.test\-smoke\.org/
http&#8203;://qa\.perl\.org   http&#8203;://www\.goldmark\.org/jeff/stupid\-disclaimers/

**Comment by jkeenan** [comment]
This was fixed by Hugo in commit a06a4d45d476265b6d5143171126fe6f33ef2c44; closing.
