### ISSUE TITLE
Fwd: [rt.cpan.org #124722] NULL pointer dereference in Perl_runops_standard

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16457]
Migrated from [rt.perl.org#132953](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132953) (status was 'open')

Searchable as RT132953$

**Comment by p5pRT** [comment]
### From bug-Perl-Core@rt.cpan.org


This is forward of transaction \#1775448 of a ticket \#124722

**Comment by p5pRT** [comment]
### From bug-Perl-Core@rt.cpan.org

Message RFC822:
X-Mailer: MIME-tools 5.504 (Entity 5.504)
Content-Disposition: inline
Message-ID: <rt-4.0.18-25284-1520499031-1810.0-0-0@rt.cpan.org>
X-RT-Interface: Web
X-RT-Encrypt: 0
Content-Transfer-Encoding: binary
MIME-Version: 1.0
X-RT-Sign: 0
From: hackyzh002@gmail.com
Subject: NULL pointer dereference in Perl_runops_standard
Content-Length: 907
Content-Type: text/plain; charset="utf-8"
X-RT-Original-Encoding: utf-8

/perl-5.27.9/perl -le 'BEGIN{$SIG{__DIE__} =sub{exit(0)}}unshift'


==95151==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000abccbd bp 0x00000119cb28 sp 0x7ffdbda5a550 T0)
    #0 0xabccbc in Perl_pp_unshift /home/hackyzh/Desktop/perl-5.27.9/pp.c:5524
    #1 0x92c74a in Perl_runops_standard /home/hackyzh/Desktop/perl-5.27.9/run.c:41
    #2 0x555b39 in S_run_body /home/hackyzh/Desktop/perl-5.27.9/perl.c:2750
    #3 0x555b39 in perl_run /home/hackyzh/Desktop/perl-5.27.9/perl.c:2671
    #4 0x42b6e5 in main /home/hackyzh/Desktop/perl-5.27.9/perlmain.c:122
    #5 0x7f29c157682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #6 0x42c6c8 in _start (/home/hackyzh/Desktop/perl-5.27.9/perl+0x42c6c8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/hackyzh/Desktop/perl-5.27.9/pp.c:5524 Perl_pp_unshift
==95151==ABORTING

**Comment by p5pRT** [comment]
### From bug-Perl-Core@rt.cpan.org

/perl\-5\.27\.9/perl \-le 'BEGIN\{$SIG\{\_\_DIE\_\_\} =sub\{exit\(0\)\}\}unshift'


==95151==ERROR&#8203;: AddressSanitizer&#8203;: SEGV on unknown address 0x000000000000 \(pc 0x000000abccbd bp 0x00000119cb28 sp 0x7ffdbda5a550 T0\)
&nbsp;    \#0 0xabccbc in Perl\_pp\_unshift /home/hackyzh/Desktop/perl\-5\.27\.9/pp\.c&#8203;:5524
&nbsp;    \#1 0x92c74a in Perl\_runops\_standard /home/hackyzh/Desktop/perl\-5\.27\.9/run\.c&#8203;:41
&nbsp;    \#2 0x555b39 in S\_run\_body /home/hackyzh/Desktop/perl\-5\.27\.9/perl\.c&#8203;:2750
&nbsp;    \#3 0x555b39 in perl\_run /home/hackyzh/Desktop/perl\-5\.27\.9/perl\.c&#8203;:2671
&nbsp;    \#4 0x42b6e5 in main /home/hackyzh/Desktop/perl\-5\.27\.9/perlmain\.c&#8203;:122
&nbsp;    \#5 0x7f29c157682f in \_\_libc\_start\_main \(/lib/x86\_64\-linux\-gnu/libc\.so\.6\+0x2082f\)
&nbsp;    \#6 0x42c6c8 in \_start \(/home/hackyzh/Desktop/perl\-5\.27\.9/perl\+0x42c6c8\)

AddressSanitizer can not provide additional info\.
SUMMARY&#8203;: AddressSanitizer&#8203;: SEGV /home/hackyzh/Desktop/perl\-5\.27\.9/pp\.c&#8203;:5524 Perl\_pp\_unshift
==95151==ABORTING

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Mar 08\, 2018 at 12&#8203;:51&#8203;:53AM \-0800\, via RT wrote&#8203;:
> \# New Ticket Created by   
> \# Please include the string&#8203;:  \[perl \#132953\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132953 >
> 
> 
> 
> This is forward of transaction \#1775448 of a ticket \#124722

> /perl\-5\.27\.9/perl \-le 'BEGIN\{$SIG\{\_\_DIE\_\_\} =sub\{exit\(0\)\}\}unshift'

The unshift is a syntax error\, so compilation triggers the \_\_DIE\_\_
handler\, which does an exit\(0\)\. This causes a longjmp back to
perl\_parse\(\)\, which sees a zero STATUS\_EXIT and returns 0 \(success\)\.
main\(\) sees a successful return from perl\_parse\(\) and so continues
with perl\_run\(\)\, which then crashes on the badly\-formed optree\.

I don't think its a security issue\, as it involves feeding code with
syntax errors into the parser\.

I'm not very confident about how to fix it though&#8203;: the whole exit
semantics is beyond my ken\.

In particular\, in perl\_parse\(\) there is this&#8203;:

&nbsp;    case 2&#8203;:
&nbsp;    /\* my\_exit\(\) was called \*/
&nbsp;    \.\.\. pop stacks \.\.\.
&nbsp;    ret = STATUS\_EXIT;
&nbsp;    if \(ret == 0\) \{
&nbsp;        /\*
&nbsp;         \* At this point we should do
&nbsp;         \*     ret = 0x100;
&nbsp;         \* to avoid \[perl \#2754\]\, but that bugfix has been postponed
&nbsp;         \* because of the Module&#8203;::Install breakage it causes
&nbsp;         \* \[perl \#132577\]\.
&nbsp;         \*/
&nbsp;    \}

\#2754 is&#8203;: From a CHECK\{\}\, you cannot exit\(0\)

which had a fix from Zefram in Dec 2017\, which was reverted because
it broke Module&#8203;::Install \(and you can't get people to upgrade
Module&#8203;::Install\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Thu\, 08 Mar 2018 03&#8203;:39&#8203;:36 \-0800\, davem wrote&#8203;:
> On Thu\, Mar 08\, 2018 at 12&#8203;:51&#8203;:53AM \-0800\, via RT wrote&#8203;:
> > \# New Ticket Created by   
> > \# Please include the string&#8203;:  \[perl \#132953\]
> > \# in the subject line of all future correspondence about this issue\. 
> > \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=132953 >
> > 
> > 
> > 
> > This is forward of transaction \#1775448 of a ticket \#124722
> 
> > /perl\-5\.27\.9/perl \-le 'BEGIN\{$SIG\{\_\_DIE\_\_\} =sub\{exit\(0\)\}\}unshift'
> 
> The unshift is a syntax error\, so compilation triggers the \_\_DIE\_\_
> handler\, which does an exit\(0\)\. This causes a longjmp back to
> perl\_parse\(\)\, which sees a zero STATUS\_EXIT and returns 0 \(success\)\.
> main\(\) sees a successful return from perl\_parse\(\) and so continues
> with perl\_run\(\)\, which then crashes on the badly\-formed optree\.
> 
> I don't think its a security issue\, as it involves feeding code with
> syntax errors into the parser\.

I agree\, now public\.

Tony

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Dave Mitchell wrote&#8203;:
>I'm not very confident about how to fix it though&#8203;:

It \*was\* fixed in 5\.27\.7\, as part of \[perl \#2754\]\.  5\.27\.7 doesn't crash
on the test case for this ticket\, but cleanly exits as requested\.  It was
de\-fixed in 5\.27\.8 due to CPAN breakage \[perl \#132577\]\.  The current
intent is to re\-fix all of that in 5\.29\.

\-zefram

**Comment by demerphq** [comment]
I believe this is fixed as of Perl 5.37.4. Likely by 375d68c017193cf7263947ef5c595647f04eb9b8

**Comment by demerphq** [comment]
Bisect said it was 197bb3f4412b47e2f91dcf54c64d12d9fd05967b
