### ISSUE TITLE
Bleadperl breaks DROLSKY/Fey-0.43.tar.gz on Windows and other OSes

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16524]
Migrated from [rt.perl.org#133139](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133139) (status was 'open')

Searchable as RT133139$

**Comment by p5pRT** [comment]
### From @chorny



Worked on 5\.26\.1 and 5\.27\.6\, fails on 5\.27\.8\. Also fails on 5\.26\.2RC1&#8203;:
http&#8203;://www\.cpantesters\.org/cpan/report/a38b01d5\-6c17\-1014\-a45b\-c247befa3bc8

t/SQL/Select\-from\-clause\.t&#8203;:

ok 1 \- from\(\) without any parameters is an error
ok 2 \- from\_clause\(\) for one table
ok 3 \- from\(\) called with one non\-table argument
ok 4 \- from\_clause\(\) for one table alias
ok 5 \- from\_clause\(\) with self\-join to alias using fake FK
ok 6 \- Cannot join two tables without a foreign key
ok 7 \- from\(\) called with two args\, one not a table
ok 8 \- from\(\) called with two args\, one not a table
ok 9 \- from\_clause\(\) for two tables\, fk not provided
ok 10 \- from\_clause\(\) for two joins
Use of freed value in iteration at
C&#8203;:/Strawberry2710/perl/site/lib/Test/MockObject\.pm line 257\.
Attempt to free unreferenced scalar&#8203;: SV 0x2615824\, Perl interpreter&#8203;:
0x3f9fb4 at C&#8203;:/Strawberry2710/perl/site/lib/Test/MockObject\.pm line
257\.


Also reported in this module bug tracker
https://rt.cpan.org/Ticket/Display.html?id=125168

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl 5.27.10:

Configured by strawberry-perl at Mon Apr  2 14:39:04 2018.

Summary of my perl5 (revision 5 version 27 subversion 10) configuration:

  Platform:
    osname=MSWin32
    osvers=5.1.2600
    archname=MSWin32-x86-multi-thread-64int
    uname='Win32 strawberry-perl 5.27.10.1-beta1 #1 Mon Apr  2
14:36:35 2018 i386'
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags =' -s -O2 -DWIN32 -D__USE_MINGW_ANSI_STDIO
-DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS
-DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields'
    optimize='-s -O2'
    cppflags='-DWIN32'
    ccversion=''
    gccversion='7.1.0'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=4
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=12
    longdblkind=3
    ivtype='long long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='long long'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags ='-s -L"C:\STRAWB~1\perl\lib\CORE" -L"C:\STRAWB~1\c\lib"'
    libpth=C:\STRAWB~1\c\lib C:\STRAWB~1\c\i686-w64-mingw32\lib
C:\STRAWB~1\c\lib\gcc\i686-w64-mingw32\7.1.0
    libs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32
-ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32
-lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool
-lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid
-lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    libc=
    so=dll
    useshrplib=true
    libperl=libperl527.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=xs.dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-mdll -s -L"C:\STRAWB~1\perl\lib\CORE" -L"C:\STRAWB~1\c\lib"'



@INC for perl 5.27.10:
    C:/Strawberry2710/perl/site/lib
    C:/Strawberry2710/perl/vendor/lib
    C:/Strawberry2710/perl/lib


Environment for perl 5.27.10:
    HOME (unset)
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=C:\Program Files\Far
Manager\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Git\cmd;C:\Strawberry2710\c\bin;C:\Strawberry2710\perl\site\bin;C:\Strawberry2710\perl\bin
    PERL_BADLANG (unset)
    PERL_HASH_SEED=0x11111111
    SHELL (unset)


-- 
Alexandr Ciornii, http://chorny.net

```
</details>

**Comment by p5pRT** [comment]
### From @jkeenan

On Sat\, 21 Apr 2018 21&#8203;:59&#8203;:00 GMT\, chorny wrote&#8203;:
> This is a bug report for perl\,
> generated with the help of perlbug 1\.41 running under perl 5\.27\.10\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please describe your issue here\]
> 
> Worked on 5\.26\.1 and 5\.27\.6\, fails on 5\.27\.8\. Also fails on 5\.26\.2RC1&#8203;:
> http&#8203;://www\.cpantesters\.org/cpan/report/a38b01d5\-6c17\-1014\-a45b\-
> c247befa3bc8
> 
> t/SQL/Select\-from\-clause\.t&#8203;:
> 
> ok 1 \- from\(\) without any parameters is an error
> ok 2 \- from\_clause\(\) for one table
> ok 3 \- from\(\) called with one non\-table argument
> ok 4 \- from\_clause\(\) for one table alias
> ok 5 \- from\_clause\(\) with self\-join to alias using fake FK
> ok 6 \- Cannot join two tables without a foreign key
> ok 7 \- from\(\) called with two args\, one not a table
> ok 8 \- from\(\) called with two args\, one not a table
> ok 9 \- from\_clause\(\) for two tables\, fk not provided
> ok 10 \- from\_clause\(\) for two joins
> Use of freed value in iteration at
> C&#8203;:/Strawberry2710/perl/site/lib/Test/MockObject\.pm line 257\.
> Attempt to free unreferenced scalar&#8203;: SV 0x2615824\, Perl interpreter&#8203;:
> 0x3f9fb4 at C&#8203;:/Strawberry2710/perl/site/lib/Test/MockObject\.pm line
> 257\.
> 

But not just on Windows\.  I just tried to build it on FreeBSD\-11\.0 at commit 41ed02688 and got a FAIL with the rather uninformative output attached\.

> 
> Also reported in this module bug tracker
> https://rt.cpan.org/Ticket/Display.html?id=125168
> 
> 
> \[Please do not change anything below this line\]
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \-\-\-
> Flags&#8203;:
>     category=core
>     severity=low
> \-\-\-
> Site configuration information for perl 5\.27\.10&#8203;:
> 
> Configured by strawberry\-perl at Mon Apr  2 14&#8203;:39&#8203;:04 2018\.
> 
> Summary of my perl5 \(revision 5 version 27 subversion 10\)
> configuration&#8203;:
> 
> Platform&#8203;:
>   osname=MSWin32
>   osvers=5\.1\.2600
>   archname=MSWin32\-x86\-multi\-thread\-64int
>   uname='Win32 strawberry\-perl 5\.27\.10\.1\-beta1 \#1 Mon Apr  2
> 14&#8203;:36&#8203;:35 2018 i386'
>   config\_args='undef'
>   hint=recommended
>   useposix=true
>   d\_sigaction=undef
>   useithreads=define
>   usemultiplicity=define
>   use64bitint=define
>   use64bitall=undef
>   uselongdouble=undef
>   usemymalloc=n
>   default\_inc\_excludes\_dot=define
>   bincompat5005=undef
> Compiler&#8203;:
>   cc='gcc'
>   ccflags =' \-s \-O2 \-DWIN32 \-D\_\_USE\_MINGW\_ANSI\_STDIO
> \-DPERL\_TEXTMODE\_SCRIPTS \-DPERL\_IMPLICIT\_CONTEXT \-DPERL\_IMPLICIT\_SYS
> \-DUSE\_PERLIO \-fwrapv \-fno\-strict\-aliasing \-mms\-bitfields'
>   optimize='\-s \-O2'
>   cppflags='\-DWIN32'
>   ccversion=''
>   gccversion='7\.1\.0'
>   gccosandvers=''
>   intsize=4
>   longsize=4
>   ptrsize=4
>   doublesize=8
>   byteorder=12345678
>   doublekind=3
>   d\_longlong=define
>   longlongsize=8
>   d\_longdbl=define
>   longdblsize=12
>   longdblkind=3
>   ivtype='long long'
>   ivsize=8
>   nvtype='double'
>   nvsize=8
>   Off\_t='long long'
>   lseeksize=8
>   alignbytes=8
>   prototype=define
> Linker and Libraries&#8203;:
>   ld='g\+\+'
>   ldflags ='\-s \-L"C&#8203;:\\STRAWB~1\\perl\\lib\\CORE" \-L"C&#8203;:\\STRAWB~1\\c\\lib"'
>   libpth=C&#8203;:\\STRAWB~1\\c\\lib C&#8203;:\\STRAWB~1\\c\\i686\-w64\-mingw32\\lib
> C&#8203;:\\STRAWB~1\\c\\lib\\gcc\\i686\-w64\-mingw32\\7\.1\.0
>   libs= \-lmoldname \-lkernel32 \-luser32 \-lgdi32 \-lwinspool \-lcomdlg32
> \-ladvapi32 \-lshell32 \-lole32 \-loleaut32 \-lnetapi32 \-luuid \-lws2\_32
> \-lmpr \-lwinmm \-lversion \-lodbc32 \-lodbccp32 \-lcomctl32
>   perllibs= \-lmoldname \-lkernel32 \-luser32 \-lgdi32 \-lwinspool
> \-lcomdlg32 \-ladvapi32 \-lshell32 \-lole32 \-loleaut32 \-lnetapi32 \-luuid
> \-lws2\_32 \-lmpr \-lwinmm \-lversion \-lodbc32 \-lodbccp32 \-lcomctl32
>   libc=
>   so=dll
>   useshrplib=true
>   libperl=libperl527\.a
>   gnulibc\_version=''
> Dynamic Linking&#8203;:
>   dlsrc=dl\_win32\.xs
>   dlext=xs\.dll
>   d\_dlsymun=undef
>   ccdlflags=' '
>   cccdlflags=' '
>   lddlflags='\-mdll \-s \-L"C&#8203;:\\STRAWB~1\\perl\\lib\\CORE"
> \-L"C&#8203;:\\STRAWB~1\\c\\lib"'
> 
> 
> \-\-\-
> @&#8203;INC for perl 5\.27\.10&#8203;:
>     C&#8203;:/Strawberry2710/perl/site/lib
>     C&#8203;:/Strawberry2710/perl/vendor/lib
>     C&#8203;:/Strawberry2710/perl/lib
> 
> \-\-\-
> Environment for perl 5\.27\.10&#8203;:
>     HOME \(unset\)
>     LANG \(unset\)
>     LANGUAGE \(unset\)
>     LD\_LIBRARY\_PATH \(unset\)
>     LOGDIR \(unset\)
>     PATH=C&#8203;:\\Program Files\\Far
> Manager\\;C&#8203;:\\WINDOWS\\system32;C&#8203;:\\WINDOWS;C&#8203;:\\WINDOWS\\System32\\Wbem;C&#8203;:\\Git\\cmd;C&#8203;:\\Strawberry2710\\c\\bin;C&#8203;:\\Strawberry2710\\perl\\site\\bin;C&#8203;:\\Strawberry2710\\perl\\bin
>     PERL\_BADLANG \(unset\)
>     PERL\_HASH\_SEED=0x11111111
>     SHELL \(unset\)


\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @jkeenan

t/SQL/Select\-from\-clause\.t \.\. 
ok 1 \- from\(\) without any parameters is an error
ok 2 \- from\_clause\(\) for one table
ok 3 \- from\(\) called with one non\-table argument
ok 4 \- from\_clause\(\) for one table alias
ok 5 \- from\_clause\(\) with self\-join to alias using fake FK
ok 6 \- Cannot join two tables without a foreign key
ok 7 \- from\(\) called with two args\, one not a table
ok 8 \- from\(\) called with two args\, one not a table
All 8 subtests passed 

Test Summary Report


---
t/SQL/Select\-from\-clause\.t \(Wstat&#8203;: 139 Tests&#8203;: 8 Failed&#8203;: 0\)
&nbsp;  Non\-zero wait status&#8203;: 139
&nbsp;  Parse errors&#8203;: No plan found in TAP output
Files=1\, Tests=8\,  1 wallclock secs \( 0\.03 usr  0\.01 sys \+  0\.94 cusr  0\.16 csys =  1\.14 CPU\)
Result&#8203;: FAIL

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @jkeenan

On Sat\, 21 Apr 2018 22&#8203;:31&#8203;:49 GMT\, jkeenan wrote&#8203;:
> On Sat\, 21 Apr 2018 21&#8203;:59&#8203;:00 GMT\, chorny wrote&#8203;:
> > This is a bug report for perl\,
> > generated with the help of perlbug 1\.41 running under perl 5\.27\.10\.
> >
> >
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > \[Please describe your issue here\]
> >
> > Worked on 5\.26\.1 and 5\.27\.6\, fails on 5\.27\.8\. Also fails on
> > 5\.26\.2RC1&#8203;:
> > http&#8203;://www\.cpantesters\.org/cpan/report/a38b01d5\-6c17\-1014\-a45b\-
> > c247befa3bc8
> >
> > t/SQL/Select\-from\-clause\.t&#8203;:
> >
> > ok 1 \- from\(\) without any parameters is an error
> > ok 2 \- from\_clause\(\) for one table
> > ok 3 \- from\(\) called with one non\-table argument
> > ok 4 \- from\_clause\(\) for one table alias
> > ok 5 \- from\_clause\(\) with self\-join to alias using fake FK
> > ok 6 \- Cannot join two tables without a foreign key
> > ok 7 \- from\(\) called with two args\, one not a table
> > ok 8 \- from\(\) called with two args\, one not a table
> > ok 9 \- from\_clause\(\) for two tables\, fk not provided
> > ok 10 \- from\_clause\(\) for two joins
> > Use of freed value in iteration at
> > C&#8203;:/Strawberry2710/perl/site/lib/Test/MockObject\.pm line 257\.
> > Attempt to free unreferenced scalar&#8203;: SV 0x2615824\, Perl interpreter&#8203;:
> > 0x3f9fb4 at C&#8203;:/Strawberry2710/perl/site/lib/Test/MockObject\.pm line
> > 257\.
> >
> 
> But not just on Windows\.  I just tried to build it on FreeBSD\-11\.0 at
> commit 41ed02688 and got a FAIL with the rather uninformative output
> attached\.
> 

Attaching excerpt from running the file through the debugger\.


> >
> > Also reported in this module bug tracker
> > https://rt.cpan.org/Ticket/Display.html?id=125168
> >


\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @jkeenan

main&#8203;::\(t/SQL/Select\-from\-clause\.t&#8203;:11\)&#8203;:
11&#8203;:    my $s   = Fey&#8203;::Test\->mock\_test\_schema\_with\_fks\(\);
ok 1 \- from\(\) without any parameters is an error
ok 2 \- from\_clause\(\) for one table
ok 3 \- from\(\) called with one non\-table argument
ok 4 \- from\_clause\(\) for one table alias
ok 5 \- from\_clause\(\) with self\-join to alias using fake FK
ok 6 \- Cannot join two tables without a foreign key
ok 7 \- from\(\) called with two args\, one not a table
ok 8 \- from\(\) called with two args\, one not a table
Signal SEGV at blib/lib/Fey/SQL/Select\.pm line 237\.

&nbsp;    Fey&#8203;::SQL&#8203;::Select&#8203;::\_join\(Fey&#8203;::SQL&#8203;::Select=HASH\(0x809edcdf8\)\, Fey&#8203;::Table=HASH\(0x809ed2af8\)\, Fey&#8203;::Table=HASH\(0x809ed41b0\)\) called at blib/lib/Fey/SQL/Select\.pm line 206

&nbsp;    Fey&#8203;::SQL&#8203;::Select&#8203;::from\(Fey&#8203;::SQL&#8203;::Select=HASH\(0x809edcdf8\)\, Fey&#8203;::Table=HASH\(0x809ed2af8\)\, Fey&#8203;::Table=HASH\(0x809ed41b0\)\) called at t/SQL/Select\-from\-clause\.t line 111

Abort trap \(core dumped\)

**Comment by p5pRT** [comment]
### From @jkeenan

On Sat\, 21 Apr 2018 22&#8203;:40&#8203;:45 GMT\, jkeenan wrote&#8203;:
> On Sat\, 21 Apr 2018 22&#8203;:31&#8203;:49 GMT\, jkeenan wrote&#8203;:
> > On Sat\, 21 Apr 2018 21&#8203;:59&#8203;:00 GMT\, chorny wrote&#8203;:
> > > This is a bug report for perl\,
> > > generated with the help of perlbug 1\.41 running under perl 5\.27\.10\.
> > >
> > >
> > > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > > \[Please describe your issue here\]
> > >
> > > Worked on 5\.26\.1 and 5\.27\.6\, fails on 5\.27\.8\. Also fails on
> > > 5\.26\.2RC1&#8203;:
> > > http&#8203;://www\.cpantesters\.org/cpan/report/a38b01d5\-6c17\-1014\-a45b\-
> > > c247befa3bc8
> > >
> > > t/SQL/Select\-from\-clause\.t&#8203;:
> > >
> > > ok 1 \- from\(\) without any parameters is an error
> > > ok 2 \- from\_clause\(\) for one table
> > > ok 3 \- from\(\) called with one non\-table argument
> > > ok 4 \- from\_clause\(\) for one table alias
> > > ok 5 \- from\_clause\(\) with self\-join to alias using fake FK
> > > ok 6 \- Cannot join two tables without a foreign key
> > > ok 7 \- from\(\) called with two args\, one not a table
> > > ok 8 \- from\(\) called with two args\, one not a table
> > > ok 9 \- from\_clause\(\) for two tables\, fk not provided
> > > ok 10 \- from\_clause\(\) for two joins
> > > Use of freed value in iteration at
> > > C&#8203;:/Strawberry2710/perl/site/lib/Test/MockObject\.pm line 257\.
> > > Attempt to free unreferenced scalar&#8203;: SV 0x2615824\, Perl interpreter&#8203;:
> > > 0x3f9fb4 at C&#8203;:/Strawberry2710/perl/site/lib/Test/MockObject\.pm line
> > > 257\.
> > >
> > 
> > But not just on Windows\.  I just tried to build it on FreeBSD\-11\.0 at
> > commit 41ed02688 and got a FAIL with the rather uninformative output
> > attached\.
> > 
> 
> Attaching excerpt from running the file through the debugger\.
> 
> 
> > >
> > > Also reported in this module bug tracker
> > > https://rt.cpan.org/Ticket/Display.html?id=125168
> > >
> 

On Linux\, I got&#8203;:

\#\#\#\#\#
$ bleadperl \-Iblib/lib  t/SQL/Select\-from\-clause\.t 
ok 1 \- from\(\) without any parameters is an error
ok 2 \- from\_clause\(\) for one table
ok 3 \- from\(\) called with one non\-table argument
ok 4 \- from\_clause\(\) for one table alias
ok 5 \- from\_clause\(\) with self\-join to alias using fake FK
ok 6 \- Cannot join two tables without a foreign key
ok 7 \- from\(\) called with two args\, one not a table
ok 8 \- from\(\) called with two args\, one not a table
ok 9 \- from\_clause\(\) for two tables\, fk not provided
perl&#8203;: sv\.c&#8203;:6513&#8203;: Perl\_sv\_clear&#8203;: Assertion \`SvTYPE\(sv\) \!= \(svtype\)SVTYPEMASK' failed\.
Aborted \(core dumped\)
\#\#\#\#\#
\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @dur-randir

On Sat\, 21 Apr 2018 14&#8203;:59&#8203;:00 \-0700\, chorny wrote&#8203;:

> Worked on 5\.26\.1 and 5\.27\.6\, fails on 5\.27\.8\. Also fails on 5\.26\.2RC1&#8203;:
> http&#8203;://www\.cpantesters\.org/cpan/report/a38b01d5\-6c17\-1014\-a45b\-
> c247befa3bc8

16ada235c332e017667585e1a5a00ce43a31c529 is the first bad commit
commit 16ada235c332e017667585e1a5a00ce43a31c529
Author&#8203;: Zefram \<zefram@&#8203;fysh\.org>
Date&#8203;:   Tue Dec 12 09&#8203;:47&#8203;:41 2017 \+0000

&nbsp;    fix GvSV refcounting in sort

&nbsp;    Where a sort operation passes the comparands to a comparison block in $a
&nbsp;    and $b\, it wasn't taking account of the fact that the GvSV slots in \*a
&nbsp;    and \*b are refcounted\.  It would write the comparands into those slots
&nbsp;    without altering any reference counts\, and end by restoring the values
&nbsp;    those slots had to start with\.  This was all fine so long as nothing
&nbsp;    else touched those slots during the process\.  But code running during
&nbsp;    the comparison is free to write to them by "\*a = \\1"\, which does frob
&nbsp;    the reference counts\.

&nbsp;    Fix it by switching sort to manipulate GvSV in a refcount\-preserving
&nbsp;    manner\, compatible with all other operations on those slots\.  Fixes
&nbsp;    \[perl \#92264\]\.

**Comment by p5pRT** [comment]
### From @autarch

I took a look at this and I'm not sure exactly what's going on\. I narrowed down the failure to this bit of code in Fey&#8203;::SQL&#8203;::Fragment&#8203;::Join&#8203;:L

&nbsp;    my @&#8203;tables = $self\->tables\(\);
&nbsp;    @&#8203;tables = sort \{ $a\->name\(\) cmp $b\->name\(\) \} @&#8203;tables
&nbsp;        unless $self\->\_is\_left\_or\_right\_outer\_join\(\);

Specifically\, the \`sort\` is blowing up\. The values in @&#8203;tables are Fey&#8203;::Table objects\. The \`\->name\` method simply returns a regular string\.

This seems to me like a bug in the Perl core that needs to be fixed before 5\.28 is released\.

**Comment by p5pRT** [comment]
### From @khwilliamson

On 04/22/2018 09&#8203;:38 AM\, Dave Rolsky via RT wrote&#8203;:
> This seems to me like a bug in the Perl core that needs to be fixed before 5\.28 is released\.

James Keenan had already added this to the blockers list

**Comment by p5pRT** [comment]
### From @dur-randir

Switching from List&#8203;::AllUtils to List&#8203;::MoreUtils&#8203;::PP makes this crash go away\. So\, it looks like a \#132671 duplicate\.

**Comment by p5pRT** [comment]
### From @jkeenan

On Sun\, 22 Apr 2018 20&#8203;:15&#8203;:53 GMT\, randir wrote&#8203;:
> Switching from List&#8203;::AllUtils to List&#8203;::MoreUtils&#8203;::PP makes this crash
> go away\. So\, it looks like a \#132671 duplicate\.

At which points in Fey's codebase would you make such changes?

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @grinnz

On Sun\, 22 Apr 2018 17&#8203;:38&#8203;:44 \-0700\, jkeenan wrote&#8203;:
> On Sun\, 22 Apr 2018 20&#8203;:15&#8203;:53 GMT\, randir wrote&#8203;:
> > Switching from List&#8203;::AllUtils to List&#8203;::MoreUtils&#8203;::PP makes this crash
> > go away\. So\, it looks like a \#132671 duplicate\.
> 
> At which points in Fey's codebase would you make such changes?

I think he was stating in terms of diagnosing the issue to be due to List&#8203;::SomeUtils&#8203;::XS \(used by List&#8203;::AllUtils\) which is a fork of List&#8203;::MoreUtils&#8203;::XS\, which the mentioned issue refers to\. Thus it should be fixed in those modules\.

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Apr 22\, 2018 at 09&#8203;:11&#8203;:03PM \-0700\, Dan Book via RT wrote&#8203;:
> On Sun\, 22 Apr 2018 17&#8203;:38&#8203;:44 \-0700\, jkeenan wrote&#8203;:
> > On Sun\, 22 Apr 2018 20&#8203;:15&#8203;:53 GMT\, randir wrote&#8203;:
> > > Switching from List&#8203;::AllUtils to List&#8203;::MoreUtils&#8203;::PP makes this crash
> > > go away\. So\, it looks like a \#132671 duplicate\.
> > 
> > At which points in Fey's codebase would you make such changes?
> 
> I think he was stating in terms of diagnosing the issue to be due to
> List&#8203;::SomeUtils&#8203;::XS \(used by List&#8203;::AllUtils\) which is a fork of
> List&#8203;::MoreUtils&#8203;::XS\, which the mentioned issue refers to\. Thus it should
> be fixed in those modules\.

So I'll remove this ticket form the 5\.28 blockers


\-\- 
Nothing ventured\, nothing lost\.

**Comment by xenu** [comment]
This is a duplicate of #16346. Closing.
