### ISSUE TITLE
Threaded builds failing on Fedora 28

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16552]
Migrated from [rt.perl.org#133184](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133184) (status was 'open')

Searchable as RT133184$

**Comment by p5pRT** [comment]
### From @jkeenan

Threaded builds of Perl 5 blead are failing\, apparently during miniperl\, 
on very recent Linux kernels\.  See any of the smoke tests generated by 
Carlos Guevara on linux \- 4\.16\.5 or higher\, e\.g\.\,
http&#8203;://perl5\.test\-smoke\.org/report/65701\.  In that report\, this 
configuration was tested&#8203;:

\#\#\#\#\#
Automated smoke report for branch blead 5\.28\.0 patch 
38c84d6ad1b77d7b1de424eab465e018c7cef576 v5\.27\.11\-30\-g38c84d6ad1
cjg\-fedora28&#8203;: Intel\(R\) Xeon\(R\) CPU E5420 @&#8203; 2\.50GHz \(GenuineIntel 
2500MHz\) \(x86\_64/1 cpus\)
&nbsp;     on        linux 4\.16\.5\-300\.fc28\.x86\_64 \[Fedora 28 \(Server Edition\)\]
&nbsp;     using     cc version 8\.0\.1 20180324 \(Red Hat 8\.0\.1\-0\.20\)
\#\#\#\#\#

\.\.\. which ultimately fails with&#8203;:

\#\#\#\#\#
pp\.c&#8203;: In function 'Perl\_pp\_crypt'&#8203;:
&nbsp;   pp\.c&#8203;:3657&#8203;:47&#8203;: error&#8203;: 'struct crypt\_data' has no member named 
'current\_saltbits'

\#\#\#\#\#

Here's some dialog from \#p5p about this problem&#8203;:

\#\#\#\#\#
\(05&#8203;:16&#8203;:06 PM\) khw&#8203;: Is anyone working on the blead failures with the new 
Linux?
\(05&#8203;:16&#8203;:08 PM\) khw&#8203;: pp\.c&#8203;: In function 'Perl\_pp\_crypt'&#8203;:
\(05&#8203;:16&#8203;:09 PM\) khw&#8203;: pp\.c&#8203;:3657&#8203;:47&#8203;: error&#8203;: 'struct crypt\_data' has no 
member named 'current\_saltbits'
\.\.\.
\(06&#8203;:11&#8203;:30 PM\) xenu&#8203;: khw&#8203;: nginx had exactly the same problem 
https://trac.nginx.org/nginx/ticket/1469
\(06&#8203;:12&#8203;:04 PM\) xenu&#8203;: imo that code should be removed\, it's a workaround 
for bug in glibc from 2002
\.\.\.
\(06&#8203;:20&#8203;:26 PM\) khw&#8203;: right\.  4\.16
\(06&#8203;:20&#8203;:36 PM\) khw&#8203;: which I presumed was new
\(06&#8203;:23&#8203;:20 PM\) xenu&#8203;: also\, that bug is specific to fedora
\.\.\.
\(06&#8203;:29&#8203;:06 PM\) xenu&#8203;: i think that no one noticed that before because 
fedora 28 was released just a week ago
\(06&#8203;:32&#8203;:17 PM\) xenu&#8203;: 
https://src.fedoraproject.org/cgit/rpms/perl.git/tree/perl-5.26.1-guard_old_libcrypt_fix.patch
\(06&#8203;:32&#8203;:56 PM\) xenu&#8203;: that's the patch fedora is using to fix the problem
\(06&#8203;:33&#8203;:43 PM\) xenu&#8203;: \(imo it's too defensive\, i really don't think 
there's a valid reason to keep supporting ancient glibc versions\)
\(06&#8203;:39&#8203;:13 PM\) \*\*\*khw wonders if 5\.28 will be released before YAPC
\#\#\#\#\#

**Comment by p5pRT** [comment]
### From @jkeenan

Summary of my perl5 \(revision 5 version 27 subversion 10\) configuration&#8203;:
&nbsp;  Commit id&#8203;: f0282de6e1af44f945ea5d4ec9c7cf6469324731
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux
&nbsp;    osvers=4\.4\.0\-112\-generic
&nbsp;    archname=x86\_64\-linux
&nbsp;    uname='linux zareason 4\.4\.0\-112\-generic \#135\-ubuntu smp fri jan 19 11&#8203;:48&#8203;:36 utc 2018 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;    config\_args='\-des \-Dusedevel'
&nbsp;    hint=recommended
&nbsp;    useposix=true
&nbsp;    d\_sigaction=define
&nbsp;    useithreads=undef
&nbsp;    usemultiplicity=undef
&nbsp;    use64bitint=define
&nbsp;    use64bitall=define
&nbsp;    uselongdouble=undef
&nbsp;    usemymalloc=n
&nbsp;    default\_inc\_excludes\_dot=define
&nbsp;    bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'
&nbsp;    ccflags ='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'
&nbsp;    optimize='\-O2'
&nbsp;    cppflags='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''
&nbsp;    gccversion='5\.4\.1 20160904'
&nbsp;    gccosandvers=''
&nbsp;    intsize=4
&nbsp;    longsize=8
&nbsp;    ptrsize=8
&nbsp;    doublesize=8
&nbsp;    byteorder=12345678
&nbsp;    doublekind=3
&nbsp;    d\_longlong=define
&nbsp;    longlongsize=8
&nbsp;    d\_longdbl=define
&nbsp;    longdblsize=16
&nbsp;    longdblkind=3
&nbsp;    ivtype='long'
&nbsp;    ivsize=8
&nbsp;    nvtype='double'
&nbsp;    nvsize=8
&nbsp;    Off\_t='off\_t'
&nbsp;    lseeksize=8
&nbsp;    alignbytes=8
&nbsp;    prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'
&nbsp;    ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/5/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib /lib64 /usr/lib64
&nbsp;    libs=\-lpthread \-lnsl \-ldb \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.23\.so
&nbsp;    so=so
&nbsp;    useshrplib=false
&nbsp;    libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.23'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs
&nbsp;    dlext=so
&nbsp;    d\_dlsymun=undef
&nbsp;    ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'
&nbsp;    lddlflags='\-shared \-O2 \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;:
&nbsp;    HAS\_TIMES
&nbsp;    PERLIO\_LAYERS
&nbsp;    PERL\_COPY\_ON\_WRITE
&nbsp;    PERL\_DONT\_CREATE\_GVSV
&nbsp;    PERL\_MALLOC\_WRAP
&nbsp;    PERL\_OP\_PARENT
&nbsp;    PERL\_PRESERVE\_IVUV
&nbsp;    PERL\_USE\_DEVEL
&nbsp;    USE\_64\_BIT\_ALL
&nbsp;    USE\_64\_BIT\_INT
&nbsp;    USE\_LARGE\_FILES
&nbsp;    USE\_LOCALE
&nbsp;    USE\_LOCALE\_COLLATE
&nbsp;    USE\_LOCALE\_CTYPE
&nbsp;    USE\_LOCALE\_NUMERIC
&nbsp;    USE\_LOCALE\_TIME
&nbsp;    USE\_PERLIO
&nbsp;    USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Mar 20 2018 17&#8203;:28&#8203;:52
&nbsp;  %ENV&#8203;:
&nbsp;    PERL2DIR="/home/jkeenan/gitwork/perl2"
&nbsp;    PERLBREW\_BASHRC\_VERSION="0\.78"
&nbsp;    PERLBREW\_HOME="/home/jkeenan/\.perlbrew"
&nbsp;    PERLBREW\_MANPATH="/home/jkeenan/perl5/perlbrew/perls/perl\-5\.26\.0/man"
&nbsp;    PERLBREW\_PATH="/home/jkeenan/perl5/perlbrew/bin&#8203;:/home/jkeenan/perl5/perlbrew/perls/perl\-5\.26\.0/bin"
&nbsp;    PERLBREW\_PERL="perl\-5\.26\.0"
&nbsp;    PERLBREW\_ROOT="/home/jkeenan/perl5/perlbrew"
&nbsp;    PERLBREW\_VERSION="0\.78"
&nbsp;    PERL\_WORKDIR="/home/jkeenan/gitwork/perl"
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.27\.10/x86\_64\-linux
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.27\.10
&nbsp;    /usr/local/lib/perl5/5\.27\.10/x86\_64\-linux
&nbsp;    /usr/local/lib/perl5/5\.27\.10

**Comment by p5pRT** [comment]
### From @jkeenan

On Mon\, 07 May 2018 23&#8203;:08&#8203;:34 GMT\, jkeenan@&#8203;pobox\.com wrote&#8203;:
> Threaded builds of Perl 5 blead are failing\, apparently during
> miniperl\,
> on very recent Linux kernels\.  See any of the smoke tests generated by
> Carlos Guevara on linux \- 4\.16\.5 or higher\, e\.g\.\,
> http&#8203;://perl5\.test\-smoke\.org/report/65701\.  In that report\, this
> configuration was tested&#8203;:
> 
> \#\#\#\#\#
> Automated smoke report for branch blead 5\.28\.0 patch
> 38c84d6ad1b77d7b1de424eab465e018c7cef576 v5\.27\.11\-30\-g38c84d6ad1
> cjg\-fedora28&#8203;: Intel\(R\) Xeon\(R\) CPU E5420 @&#8203; 2\.50GHz \(GenuineIntel
> 2500MHz\) \(x86\_64/1 cpus\)
>     on        linux 4\.16\.5\-300\.fc28\.x86\_64 \[Fedora 28 \(Server
> Edition\)\]
>     using     cc version 8\.0\.1 20180324 \(Red Hat 8\.0\.1\-0\.20\)
> \#\#\#\#\#
> 
> \.\.\. which ultimately fails with&#8203;:
> 
> \#\#\#\#\#
> pp\.c&#8203;: In function 'Perl\_pp\_crypt'&#8203;:
>     pp\.c&#8203;:3657&#8203;:47&#8203;: error&#8203;: 'struct crypt\_data' has no member named
> 'current\_saltbits'
> 
> \#\#\#\#\#
> 
> Here's some dialog from \#p5p about this problem&#8203;:
> 
> \#\#\#\#\#
> \(05&#8203;:16&#8203;:06 PM\) khw&#8203;: Is anyone working on the blead failures with the
> new
> Linux?
> \(05&#8203;:16&#8203;:08 PM\) khw&#8203;: pp\.c&#8203;: In function 'Perl\_pp\_crypt'&#8203;:
> \(05&#8203;:16&#8203;:09 PM\) khw&#8203;: pp\.c&#8203;:3657&#8203;:47&#8203;: error&#8203;: 'struct crypt\_data' has no
> member named 'current\_saltbits'
> \.\.\.
> \(06&#8203;:11&#8203;:30 PM\) xenu&#8203;: khw&#8203;: nginx had exactly the same problem
> https://trac.nginx.org/nginx/ticket/1469
> \(06&#8203;:12&#8203;:04 PM\) xenu&#8203;: imo that code should be removed\, it's a workaround
> for bug in glibc from 2002
> \.\.\.
> \(06&#8203;:20&#8203;:26 PM\) khw&#8203;: right\.  4\.16
> \(06&#8203;:20&#8203;:36 PM\) khw&#8203;: which I presumed was new
> \(06&#8203;:23&#8203;:20 PM\) xenu&#8203;: also\, that bug is specific to fedora
> \.\.\.
> \(06&#8203;:29&#8203;:06 PM\) xenu&#8203;: i think that no one noticed that before because
> fedora 28 was released just a week ago
> \(06&#8203;:32&#8203;:17 PM\) xenu&#8203;:
> https://src.fedoraproject.org/cgit/rpms/perl.git/tree/perl-5.26.1-
> guard\_old\_libcrypt\_fix\.patch
> \(06&#8203;:32&#8203;:56 PM\) xenu&#8203;: that's the patch fedora is using to fix the
> problem
> \(06&#8203;:33&#8203;:43 PM\) xenu&#8203;: \(imo it's too defensive\, i really don't think
> there's a valid reason to keep supporting ancient glibc versions\)
> \(06&#8203;:39&#8203;:13 PM\) \*\*\*khw wonders if 5\.28 will be released before YAPC
> \#\#\#\#\#

For discussion purposes\, I have applied the Fedora patch indicated by xenu to the following smoke\-test branch&#8203;:

smoke\-me/jkeenan/133184\-crypt\-data

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, May 07\, 2018 at 04&#8203;:08&#8203;:34PM \-0700\, James E Keenan \(via RT\) wrote&#8203;:
> \(06&#8203;:32&#8203;:56 PM\) xenu&#8203;: that's the patch fedora is using to fix the problem
> \(06&#8203;:33&#8203;:43 PM\) xenu&#8203;: \(imo it's too defensive\, i really don't think 
> there's a valid reason to keep supporting ancient glibc versions\)

It's probably overly defensive\, but erring on the side of safety
during code freeze is probably a good thing\.

I propose we use the fedora glibc version\-based patch for 5\.28\,
then remove the line altogether post 5\.28\.


\-\- 
Never do today what you can put off till tomorrow\.

**Comment by p5pRT** [comment]
### From @doughera88

On Tue\, May 08\, 2018 at 08&#8203;:43&#8203;:25AM \+0100\, Dave Mitchell wrote&#8203;:
> On Mon\, May 07\, 2018 at 04&#8203;:08&#8203;:34PM \-0700\, James E Keenan \(via RT\) wrote&#8203;:
> > \(06&#8203;:32&#8203;:56 PM\) xenu&#8203;: that's the patch fedora is using to fix the problem
> > \(06&#8203;:33&#8203;:43 PM\) xenu&#8203;: \(imo it's too defensive\, i really don't think 
> > there's a valid reason to keep supporting ancient glibc versions\)
> 
> It's probably overly defensive\, but erring on the side of safety
> during code freeze is probably a good thing\.

I didn't know the specific versions at play\, but this patch is what I was
about to suggest\.

> I propose we use the fedora glibc version\-based patch for 5\.28\,
> then remove the line altogether post 5\.28\.

Yes\, I agree\.

\-\- 
&nbsp;    Andy Dougherty        doughera@&#8203;lafayette\.edu

**Comment by p5pRT** [comment]
### From @ppisar

On 2018\-05\-07\, "James E Keenan \(via RT\)" \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> Threaded builds of Perl 5 blead are failing\, apparently during miniperl\, 
> on very recent Linux kernels\.

That's not casued by the Linux kernel\.

>      on        linux 4\.16\.5\-300\.fc28\.x86\_64 \[Fedora 28 \(Server Edition\)\]

But by Fedora 18's glibc that replaced upstream's libcrypt library with
a new libxcrypt implementation\. libxcrypt is not bug compatible\.

> https://src.fedoraproject.org/cgit/rpms/perl.git/tree/perl-5.26.1-guard_old_libcrypt_fix.patch

I tried to send this patch to p5p at least four times via e\-mail\, but
none of the my attempts were successfull\. These days sysadmins do their
best not to deliver e\-mails\. Then I forgot on the patch\.

> \(06&#8203;:32&#8203;:56 PM\) xenu&#8203;: that's the patch fedora is using to fix the problem
> \(06&#8203;:33&#8203;:43 PM\) xenu&#8203;: \(imo it's too defensive\, i really don't think 
> there's a valid reason to keep supporting ancient glibc versions\)
> \(06&#8203;:39&#8203;:13 PM\) \*\*\*khw wonders if 5\.28 will be released before YAPC
> \#\#\#\#\#
>
glibc 2\.2 and 2\.3 contain the bug\. 2\.4 was released on 2006\-03\-06\.
Provided Perl still supports pre\-ISO\-C99 compilers\, I worry it's too
early for removing the workaround\.

\-\- Petr

**Comment by p5pRT** [comment]
### From @xsawyerx



On 05/08/2018 03&#8203;:17 PM\, Andy Dougherty wrote&#8203;:
> On Tue\, May 08\, 2018 at 08&#8203;:43&#8203;:25AM \+0100\, Dave Mitchell wrote&#8203;:
>> On Mon\, May 07\, 2018 at 04&#8203;:08&#8203;:34PM \-0700\, James E Keenan \(via RT\) wrote&#8203;:
>>> \(06&#8203;:32&#8203;:56 PM\) xenu&#8203;: that's the patch fedora is using to fix the problem
>>> \(06&#8203;:33&#8203;:43 PM\) xenu&#8203;: \(imo it's too defensive\, i really don't think 
>>> there's a valid reason to keep supporting ancient glibc versions\)
>> It's probably overly defensive\, but erring on the side of safety
>> during code freeze is probably a good thing\.
> I didn't know the specific versions at play\, but this patch is what I was
> about to suggest\.
>
>> I propose we use the fedora glibc version\-based patch for 5\.28\,
>> then remove the line altogether post 5\.28\.
> Yes\, I agree\.

Sounds good to me\.

**Comment by p5pRT** [comment]
### From @xsawyerx

Hi Petr\,

Let's take this offline with Robert to see if we can figure out any
possible patch submission issues\.

If anyone experiences anything like this\, please let me know\.
Thanks\!

On 05/09/2018 03&#8203;:45 PM\, Petr Pisar wrote&#8203;:
> On 2018\-05\-07\, "James E Keenan \(via RT\)" \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
>> Threaded builds of Perl 5 blead are failing\, apparently during miniperl\, 
>> on very recent Linux kernels\.
> That's not casued by the Linux kernel\.
>
>>      on        linux 4\.16\.5\-300\.fc28\.x86\_64 \[Fedora 28 \(Server Edition\)\]
> But by Fedora 18's glibc that replaced upstream's libcrypt library with
> a new libxcrypt implementation\. libxcrypt is not bug compatible\.
>
>> https://src.fedoraproject.org/cgit/rpms/perl.git/tree/perl-5.26.1-guard_old_libcrypt_fix.patch
> I tried to send this patch to p5p at least four times via e\-mail\, but
> none of the my attempts were successfull\. These days sysadmins do their
> best not to deliver e\-mails\. Then I forgot on the patch\.
>
>> \(06&#8203;:32&#8203;:56 PM\) xenu&#8203;: that's the patch fedora is using to fix the problem
>> \(06&#8203;:33&#8203;:43 PM\) xenu&#8203;: \(imo it's too defensive\, i really don't think 
>> there's a valid reason to keep supporting ancient glibc versions\)
>> \(06&#8203;:39&#8203;:13 PM\) \*\*\*khw wonders if 5\.28 will be released before YAPC
>> \#\#\#\#\#
>>
> glibc 2\.2 and 2\.3 contain the bug\. 2\.4 was released on 2006\-03\-06\.
> Provided Perl still supports pre\-ISO\-C99 compilers\, I worry it's too
> early for removing the workaround\.
>
> \-\- Petr

**Comment by p5pRT** [comment]
### From @xenu

On 9 May 2018 12&#8203;:45&#8203;:25 \-0000
Petr Pisar \<ppisar@&#8203;redhat\.com> wrote&#8203;:

> glibc 2\.2 and 2\.3 contain the bug\. 2\.4 was released on 2006\-03\-06\.
> Provided Perl still supports pre\-ISO\-C99 compilers\, I worry it's too
> early for removing the workaround\.
> 
> \-\- Petr

I see no connection between targeting C89 compilers and supporting
ancient Linux distributions\.

**Comment by p5pRT** [comment]
### From @iabyn

On Wed\, May 09\, 2018 at 10&#8203;:21&#8203;:38PM \+0300\, Sawyer X wrote&#8203;:
> >> I propose we use the fedora glibc version\-based patch for 5\.28\,
> >> then remove the line altogether post 5\.28\.
> > Yes\, I agree\.
> 
> Sounds good to me\.

Fedora fix now applied with v5\.27\.11\-33\-ge9c9cf5759\.

I'll remove this ticket from the 5\.28 blockers now\.

\(I've also changed the ticket's title again \- its Fedora 28 rather than
18 which is failing\)

\-\- 
"Do not dabble in paradox\, Edward\, it puts you in danger of fortuitous wit\."
&nbsp;    \-\- Lady Croom\, "Arcadia"

**Comment by jkeenan** [comment]
In May 2018 we applied e9c9cf57594854df9f5802f7f149be4738212e96 patching `pp.c` in response to build-time failures on Fedora 28.  Is there anything we still need to do in this ticket?

Thank you very much.
Jim Keenan

**Comment by iabyn** [comment]
On Fri, Jan 31, 2020 at 07:23:35PM -0800, James E Keenan wrote:
> In May 2018 we applied e9c9cf57594854df9f5802f7f149be4738212e96 patching `pp.c` in response to build-time failures on Fedora 28.  Is there anything we still need to do in this ticket?

What remained to to I have just done with v5.31.8-91-g7b1d420218, so the
ticket can be closed now.

-- 
Monto Blanco... scorchio!
