### ISSUE TITLE
PERL_BOOL_AS_CHAR doesn't work on g++ 7.3 

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16559]
Migrated from [rt.perl.org#133203](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133203) (status was 'open')

Searchable as RT133203$

**Comment by p5pRT** [comment]
### From @khwilliamson


This is a bug report for perl from khw@&#8203;khw\-xps\-8930\.\(none\)\,
generated with the help of perlbug 1\.41 running under perl 5\.28\.0\.




---
inline\.h&#8203;:20&#8203;:5&#8203;: note&#8203;: in expansion of macro ‘PERL\_ARGS\_ASSERT\_AV\_TOP\_INDEX’
&nbsp;          PERL\_ARGS\_ASSERT\_AV\_TOP\_INDEX;
&nbsp;          ^
&nbsp;     inline\.h&#8203;: In function ‘STRLEN S\_sv\_or\_pv\_pos\_u2b\(PerlInterpreter\*\, 
SV\*\, const c har\*\, STRLEN\, STRLEN\*\)’&#8203;:
&nbsp;    \*proto\.h&#8203;:4565&#8203;:2&#8203;: error&#8203;: invalid static\_cast from type ‘SV\* \{aka sv\*\}’ 
to type ‘c\*har’
&nbsp;       assert\(sv\); assert\(pv\)

If I redefine assert\(\) to get past this\, it fails later with things like

sv\.h&#8203;:334&#8203;:24&#8203;: error&#8203;: expression cannot be used as a function
\#define SvFLAGS\(sv\) \(sv\)\->sv\_flags

Since it continues to compile with gcc 7\.3\, this is not a 5\.28 blocker\.


---


---
Flags&#8203;:
&nbsp;     category=core
&nbsp;     severity=medium


---
Site configuration information for perl 5\.28\.0&#8203;:

Configured by khw at Tue May 15 16&#8203;:11&#8203;:21 MDT 2018\.

Summary of my perl5 \(revision 5 version 28 subversion 0\) configuration&#8203;:
&nbsp;   Commit id&#8203;: 64a9c780950becebc7326a31d067801ec9b187a2
&nbsp;   Platform&#8203;:
&nbsp;     osname=linux
&nbsp;     osvers=4\.15\.0\-20\-generic
&nbsp;     archname=x86\_64\-linux\-thread\-multi\-ld
&nbsp;     uname='linux khw\-xps\-8930 4\.15\.0\-20\-generic \#21\-ubuntu smp tue apr 
24 06&#8203;:16&#8203;:15 utc 2018 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;     config\_args='\-des \-Dprefix=/home/khw/fastbleadperl \-Dusedevel 
\-Accflags='\-Wno\-deprecated' \-Dman1dir=none \-Dman3dir=none \-Dcc=gcc 
\-Dusemorebits \-Dusecbacktrace \-Dusethreads'
&nbsp;     hint=recommended
&nbsp;     useposix=true
&nbsp;     d\_sigaction=define
&nbsp;     useithreads=define
&nbsp;     usemultiplicity=define
&nbsp;     use64bitint=define
&nbsp;     use64bitall=define
&nbsp;     uselongdouble=define
&nbsp;     usemymalloc=n
&nbsp;     default\_inc\_excludes\_dot=define
&nbsp;     bincompat5005=undef
&nbsp;   Compiler&#8203;:
&nbsp;     cc='gcc'
&nbsp;     ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-Wno\-deprecated \-fwrapv 
\-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include 
\-DUSE\_C\_BACKTRACE \-g \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'
&nbsp;     optimize='\-O2'
&nbsp;     cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-Wno\-deprecated \-fwrapv 
\-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;     ccversion=''
&nbsp;     gccversion='7\.3\.0'
&nbsp;     gccosandvers=''
&nbsp;     intsize=4
&nbsp;     longsize=8
&nbsp;     ptrsize=8
&nbsp;     doublesize=8
&nbsp;     byteorder=12345678
&nbsp;     doublekind=3
&nbsp;     d\_longlong=define
&nbsp;     longlongsize=8
&nbsp;     d\_longdbl=define
&nbsp;     longdblsize=16
&nbsp;     longdblkind=3
&nbsp;     ivtype='long'
&nbsp;     ivsize=8
&nbsp;     nvtype='long double'
&nbsp;     nvsize=16
&nbsp;     Off\_t='off\_t'
&nbsp;     lseeksize=8
&nbsp;     alignbytes=16
&nbsp;     prototype=define
&nbsp;   Linker and Libraries&#8203;:
&nbsp;     ld='gcc'
&nbsp;     ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;     libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/7/include\-fixed 
/usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib 
/usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;     libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;     perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;     libc=libc\-2\.27\.so
&nbsp;     so=so
&nbsp;     useshrplib=false
&nbsp;     libperl=libperl\.a
&nbsp;     gnulibc\_version='2\.27'
&nbsp;   Dynamic Linking&#8203;:
&nbsp;     dlsrc=dl\_dlopen\.xs
&nbsp;     dlext=so
&nbsp;     d\_dlsymun=undef
&nbsp;     ccdlflags='\-Wl\,\-E'
&nbsp;     cccdlflags='\-fPIC'
&nbsp;     lddlflags='\-shared \-O2 \-L/usr/local/lib \-fstack\-protector\-strong'




---
@&#8203;INC for perl 5\.28\.0&#8203;:
&nbsp;     lib
 
/home/khw/fastbleadperl/lib/site\_perl/5\.28\.0/x86\_64\-linux\-thread\-multi\-ld
&nbsp;     /home/khw/fastbleadperl/lib/site\_perl/5\.28\.0
&nbsp;     /home/khw/fastbleadperl/lib/5\.28\.0/x86\_64\-linux\-thread\-multi\-ld
&nbsp;     /home/khw/fastbleadperl/lib/5\.28\.0
&nbsp;     /home/khw/fastbleadperl/lib/site\_perl



---
Environment for perl 5\.28\.0&#8203;:
&nbsp;     HOME=/home/khw
&nbsp;     LANG=en\_US\.UTF\-8
&nbsp;     LANGUAGE \(unset\)
&nbsp;     LD\_LIBRARY\_PATH \(unset\)
&nbsp;     LOGDIR \(unset\)
 
PATH=/home/khw/bin&#8203;:/home/khw/perl5/perlbrew/bin&#8203;:/home/khw/print/bin&#8203;:/bin&#8203;:/usr/local/sbin&#8203;:/usr/local/bin&#8203;:/usr/sbin&#8203;:/usr/bin&#8203;:/sbin&#8203;:/usr/games&#8203;:/usr/local/games&#8203;:/snap/bin&#8203;:/home/khw/iands/www&#8203;:/home/khw/cxoffice/bin
&nbsp;     PERL5OPT=\-w
&nbsp;     PERL\_BADLANG \(unset\)
&nbsp;     PERL\_DIFF\_TOOL=wgdiff
&nbsp;     PERL\_POD\_PEDANTIC=1
&nbsp;     SHELL=/bin/ksh

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, May 15\, 2018 at 05&#8203;:12&#8203;:20PM \-0700\, karl williamson \(via RT\) wrote&#8203;:
> inline\.h&#8203;:20&#8203;:5&#8203;: note&#8203;: in expansion of macro ‘PERL\_ARGS\_ASSERT\_AV\_TOP\_INDEX’
>           PERL\_ARGS\_ASSERT\_AV\_TOP\_INDEX;
>           ^
>      inline\.h&#8203;: In function ‘STRLEN S\_sv\_or\_pv\_pos\_u2b\(PerlInterpreter\*\, 
> SV\*\, const c har\*\, STRLEN\, STRLEN\*\)’&#8203;:
>     \*proto\.h&#8203;:4565&#8203;:2&#8203;: error&#8203;: invalid static\_cast from type ‘SV\* \{aka sv\*\}’ 
> to type ‘c\*har’
>        assert\(sv\); assert\(pv\)
> 
> If I redefine assert\(\) to get past this\, it fails later with things like
> 
> sv\.h&#8203;:334&#8203;:24&#8203;: error&#8203;: expression cannot be used as a function
> \#define SvFLAGS\(sv\) \(sv\)\->sv\_flags
> 
> Since it continues to compile with gcc 7\.3\, this is not a 5\.28 blocker\.

It builds ok for me with&#8203;:

&nbsp;    $ g\+\+ \-\-version
&nbsp;    g\+\+ \(GCC\) 7\.3\.1 20180303 \(Red Hat 7\.3\.1\-5\)


\-\- 
A major Starfleet emergency breaks out near the Enterprise\, but
fortunately some other ships in the area are able to deal with it to
everyone's satisfaction\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#13

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tux

On Wed\, 16 May 2018 13&#8203;:43&#8203;:01 \+0100\, Dave Mitchell \<davem@&#8203;iabyn\.com>
wrote&#8203;:

> On Tue\, May 15\, 2018 at 05&#8203;:12&#8203;:20PM \-0700\, karl williamson \(via RT\) wrote&#8203;:
> > inline\.h&#8203;:20&#8203;:5&#8203;: note&#8203;: in expansion of macro ‘PERL\_ARGS\_ASSERT\_AV\_TOP\_INDEX’
> >           PERL\_ARGS\_ASSERT\_AV\_TOP\_INDEX;
> >           ^
> >      inline\.h&#8203;: In function ‘STRLEN S\_sv\_or\_pv\_pos\_u2b\(PerlInterpreter\*\, 
> > SV\*\, const c har\*\, STRLEN\, STRLEN\*\)’&#8203;:
> >     \*proto\.h&#8203;:4565&#8203;:2&#8203;: error&#8203;: invalid static\_cast from type ‘SV\* \{aka sv\*\}’ 
> > to type ‘c\*har’
> >        assert\(sv\); assert\(pv\)
> > 
> > If I redefine assert\(\) to get past this\, it fails later with things like
> > 
> > sv\.h&#8203;:334&#8203;:24&#8203;: error&#8203;: expression cannot be used as a function
> > \#define SvFLAGS\(sv\) \(sv\)\->sv\_flags
> > 
> > Since it continues to compile with gcc 7\.3\, this is not a 5\.28 blocker\.  
> 
> It builds ok for me with&#8203;:
> 
>     $ g\+\+ \-\-version
>     g\+\+ \(GCC\) 7\.3\.1 20180303 \(Red Hat 7\.3\.1\-5\)

http&#8203;://perl5\.test\-smoke\.org/report/65972
g\+\+ version 8\.0\.1 20180425 \(prerelease\) \[gcc\-8\-branch revision 259638\]
PASS

\-\- 
H\.Merijn Brand  http&#8203;://tux\.nl   Perl Monger  http&#8203;://amsterdam\.pm\.org/
using perl5\.00307 \.\. 5\.27   porting perl5 on HP\-UX\, AIX\, and openSUSE
http&#8203;://mirrors\.develooper\.com/hpux/        http&#8203;://www\.test\-smoke\.org/
http&#8203;://qa\.perl\.org   http&#8203;://www\.goldmark\.org/jeff/stupid\-disclaimers/

**Comment by p5pRT** [comment]
### From @jkeenan

On Wed\, 16 May 2018 00&#8203;:12&#8203;:20 GMT\, public@&#8203;khwilliamson\.com wrote&#8203;:
> 
> This is a bug report for perl from khw@&#8203;khw\-xps\-8930\.\(none\)\,
> generated with the help of perlbug 1\.41 running under perl 5\.28\.0\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> inline\.h&#8203;:20&#8203;:5&#8203;: note&#8203;: in expansion of macro
> ‘PERL\_ARGS\_ASSERT\_AV\_TOP\_INDEX’
>               PERL\_ARGS\_ASSERT\_AV\_TOP\_INDEX;
>               ^
>           inline\.h&#8203;: In function ‘STRLEN
> S\_sv\_or\_pv\_pos\_u2b\(PerlInterpreter\*\,
> SV\*\, const c har\*\, STRLEN\, STRLEN\*\)’&#8203;:
>          \*proto\.h&#8203;:4565&#8203;:2&#8203;: error&#8203;: invalid static\_cast from type ‘SV\*
> \{aka sv\*\}’
> to type ‘c\*har’
>            assert\(sv\); assert\(pv\)
> 
> If I redefine assert\(\) to get past this\, it fails later with things
> like
> 
> sv\.h&#8203;:334&#8203;:24&#8203;: error&#8203;: expression cannot be used as a function
> \#define SvFLAGS\(sv\) \(sv\)\->sv\_flags
> 
> Since it continues to compile with gcc 7\.3\, this is not a 5\.28
> blocker\.
> 

I can build blead on FreeBSD\-11\.1 using g\+\+ 7\.3\.0\.  'make test\_harness' PASSes\.  I get some warnings during 'make test\_prep'\, but most of those are from cpan\-upstream modules\.   The warnings I get from blead\-upstream code appear to be limited to the following&#8203;:

\#\#\#\#\#
$ zgrep  'warning&#8203;:' gpp\.7\.3\.build\.log\.txt\.gz | head \-4
op\.c&#8203;:5469&#8203;:34&#8203;: warning&#8203;: argument 'o' might be clobbered by 'longjmp' or 'vfork' \[\-Wclobbered\]
sv\.c&#8203;:11813&#8203;:1&#8203;: warning&#8203;: '%\.\*g' directive writing between 1 and 133 bytes into a region of size 127 \[\-Wformat\-overflow=\]
perl\.h&#8203;:6728&#8203;:34&#8203;: warning&#8203;: option '\-Wc\+\+\-compat' is valid for C/ObjC but not for C\+\+ \[\-Wpragmas\]
op\.c&#8203;:5469&#8203;:34&#8203;: warning&#8203;: argument 'o' might be clobbered by 'longjmp' or 'vfork' \[\-Wclobbered\]
\#\#\#\#\#

perl \-V output attached\. Thank you very much\.
\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @jkeenan

Summary of my perl5 \(revision 5 version 28 subversion 0\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 64a9c780950becebc7326a31d067801ec9b187a2
&nbsp;  Platform&#8203;:
&nbsp;    osname=freebsd
&nbsp;    osvers=11\.1\-release\-p9
&nbsp;    archname=amd64\-freebsd\-thread\-multi
&nbsp;    uname='freebsd kid51\-freebsd\-11\-install\-3 11\.1\-release\-p9 freebsd 11\.1\-release\-p9 \#0&#8203;: tue apr 3 16&#8203;:59&#8203;:16 utc 2018 root@&#8203;amd64\-builder\.daemonology\.net&#8203;:usrobjusrsrcsysgeneric amd64 '
&nbsp;    config\_args='\-des \-Dusedevel \-Duseithreads \-Doptimize=\-O2 \-pipe \-fstack\-protector \-fno\-strict\-aliasing \-Dcc=g\+\+7'
&nbsp;    hint=recommended
&nbsp;    useposix=true
&nbsp;    d\_sigaction=define
&nbsp;    useithreads=define
&nbsp;    usemultiplicity=define
&nbsp;    use64bitint=define
&nbsp;    use64bitall=define
&nbsp;    uselongdouble=undef
&nbsp;    usemymalloc=n
&nbsp;    default\_inc\_excludes\_dot=define
&nbsp;    bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='g\+\+7'
&nbsp;    ccflags ='\-DHAS\_FPSETMASK \-DHAS\_FLOATINGPOINT\_H \-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_FORTIFY\_SOURCE=2'
&nbsp;    optimize='\-O2 \-pipe \-fstack\-protector \-fno\-strict\-aliasing'
&nbsp;    cppflags='\-DHAS\_FPSETMASK \-DHAS\_FLOATINGPOINT\_H \-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''
&nbsp;    gccversion='7\.3\.0'
&nbsp;    gccosandvers=''
&nbsp;    intsize=4
&nbsp;    longsize=8
&nbsp;    ptrsize=8
&nbsp;    doublesize=8
&nbsp;    byteorder=12345678
&nbsp;    doublekind=3
&nbsp;    d\_longlong=define
&nbsp;    longlongsize=8
&nbsp;    d\_longdbl=define
&nbsp;    longdblsize=16
&nbsp;    longdblkind=3
&nbsp;    ivtype='long'
&nbsp;    ivsize=8
&nbsp;    nvtype='double'
&nbsp;    nvsize=8
&nbsp;    Off\_t='off\_t'
&nbsp;    lseeksize=8
&nbsp;    alignbytes=8
&nbsp;    prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='g\+\+7'
&nbsp;    ldflags ='\-pthread \-Wl\,\-E  \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/lib /usr/local/lib /usr/local/lib/gcc7/include/c\+\+/ /usr/local/lib/gcc7/include/c\+\+//x86\_64\-portbld\-freebsd11\.1 /usr/local/lib/gcc7/include/c\+\+//backward /usr/local/lib /usr/lib
&nbsp;    libs=\-lpthread \-lgdbm \-lm \-lcrypt \-lutil
&nbsp;    perllibs=\-lpthread \-lm \-lcrypt \-lutil
&nbsp;    libc=
&nbsp;    so=so
&nbsp;    useshrplib=false
&nbsp;    libperl=libperl\.a
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs
&nbsp;    dlext=so
&nbsp;    d\_dlsymun=undef
&nbsp;    ccdlflags=' '
&nbsp;    cccdlflags='\-DPIC \-fPIC'
&nbsp;    lddlflags='\-shared  \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;:
&nbsp;    HAS\_TIMES
&nbsp;    MULTIPLICITY
&nbsp;    PERLIO\_LAYERS
&nbsp;    PERL\_COPY\_ON\_WRITE
&nbsp;    PERL\_DONT\_CREATE\_GVSV
&nbsp;    PERL\_IMPLICIT\_CONTEXT
&nbsp;    PERL\_MALLOC\_WRAP
&nbsp;    PERL\_OP\_PARENT
&nbsp;    PERL\_PRESERVE\_IVUV
&nbsp;    PERL\_USE\_DEVEL
&nbsp;    USE\_64\_BIT\_ALL
&nbsp;    USE\_64\_BIT\_INT
&nbsp;    USE\_ITHREADS
&nbsp;    USE\_LARGE\_FILES
&nbsp;    USE\_LOCALE
&nbsp;    USE\_LOCALE\_COLLATE
&nbsp;    USE\_LOCALE\_CTYPE
&nbsp;    USE\_LOCALE\_NUMERIC
&nbsp;    USE\_LOCALE\_TIME
&nbsp;    USE\_PERLIO
&nbsp;    USE\_PERL\_ATOF
&nbsp;    USE\_REENTRANT\_API
&nbsp;  Built under freebsd
&nbsp;  Compiled at May 16 2018 09&#8203;:25&#8203;:31
&nbsp;  %ENV&#8203;:
&nbsp;    PERL2DIR="/home/jkeenan/gitwork/perl2"
&nbsp;    PERL\_WORKDIR="/home/jkeenan/gitwork/perl"
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.28\.0/amd64\-freebsd\-thread\-multi
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.28\.0
&nbsp;    /usr/local/lib/perl5/5\.28\.0/amd64\-freebsd\-thread\-multi
&nbsp;    /usr/local/lib/perl5/5\.28\.0

**Comment by p5pRT** [comment]
### From @khwilliamson

Further investigation indicates the real issue is not what I thought\, given that others successfully compile with this compiler\.  As a result\, I have changed the title of this ticket to

PERL\_BOOL\_AS\_CHAR doesn't work on g\+\+ 7\.3 

That is\, if you pass \-DPERL\_BOOL\_AS\_CHAR to Configure\, and then try to compile with g\+\+ 7\.3\, you get the messages described in this ticket\.  Regular gcc 7\.3 works\.
\-\- 
Karl Williamson

**Comment by khwilliamson** [comment]
Closing this ticket as we now use c99 making the Configure option obsolete
