### ISSUE TITLE
Perl fails to build with libxcrypt

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16573]
Migrated from [rt.perl.org#133236](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133236) (status was 'rejected')

Searchable as RT133236$

**Comment by p5pRT** [comment]
### From @ppisar

Hello\,

Fedora Linux distribution decided
\<https://fedoraproject.org/wiki/Changes/Replace_glibc_libcrypt_with_libxcrypt>.
to replace GNU libc's libcrypt with libxcrypt implementation
\<https://github.com/besser82/libxcrypt>. This caused perl to fail to build
like this&#8203;:

cc \-c \-DPERL\_CORE \-D\_REENTRANT \-D\_GNU\_SOURCE \-I/usr/src/kernels/4\.15\.0\-0\.rc8\.git0\.1\.fc28\.x86\_64/arch/x86/include \-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-D\_FORTIFY\_SOURCE=2 \-std=c89 \-O2 \-Wall \-Werror=declaration\-after\-statement \-Werror=pointer\-arith \-Wextra \-Wc\+\+\-compat \-Wwrite\-strings pp\.c
pp\.c&#8203;: In function ‘Perl\_pp\_crypt’&#8203;:
pp\.c&#8203;:3654&#8203;:47&#8203;: error&#8203;: ‘struct crypt\_data’ has no member named ‘current\_saltbits’
&nbsp;      PL\_reentrant\_buffer\->\_crypt\_struct\_buffer\->current\_saltbits = 0;
&nbsp;                                               ^~
This is caused by a workaround for a broken glibc perl implements\.

Attached patch fixes the failure by constraining the workaround only to broken
glibc versions\.

Original patch author is Björn Esser\.

\-\- Petr

**Comment by p5pRT** [comment]
### From @ppisar

<details><summary>0001-pp-Guard-fix-for-really-old-bug-in-glibc-libcrypt.patch</summary>

```diff
From 046b0bfd29a9bec4e40dadfb1ebf0321efff3f8b Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Bj=C3=B6rn=20Esser?= <besser82@fedoraproject.org>
Date: Thu, 25 Jan 2018 09:10:49 +0100
Subject: [PATCH] pp: Guard fix for really old bug in glibc libcrypt
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Signed-off-by: Petr Písař <ppisar@redhat.com>
---
 pp.c | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/pp.c b/pp.c
index d50ad7ddbf..6510c7b15c 100644
--- a/pp.c
+++ b/pp.c
@@ -3650,8 +3650,12 @@ PP(pp_crypt)
 #if defined(__GLIBC__) || defined(__EMX__)
 	if (PL_reentrant_buffer->_crypt_struct_buffer) {
 	    PL_reentrant_buffer->_crypt_struct_buffer->initialized = 0;
-	    /* work around glibc-2.2.5 bug */
+#if (defined(__GLIBC__) && __GLIBC__ == 2) && \
+    (defined(__GLIBC_MINOR__) && __GLIBC_MINOR__ >= 2 && __GLIBC_MINOR__ < 4)
+	    /* work around glibc-2.2.5 bug, has been fixed at some
+	     * time in glibc-2.3.X */
 	    PL_reentrant_buffer->_crypt_struct_buffer->current_saltbits = 0;
+#endif
 	}
 #endif
     }
-- 
2.13.6


```
</details>

**Comment by p5pRT** [comment]
### From @ppisar

You can close this ticket as a duplicate of RT\#133184\. This one was created to
check whether my e\-mails can reach the RT\.

\-\- Petr

**Comment by p5pRT** [comment]
@iabyn - Status changed from 'new' to 'rejected'

**Comment by p5pRT** [comment]
### From @tux

On Thu\, 31 May 2018 13&#8203;:43&#8203;:23 \-0700\, "Petr Pisar \\\(via RT\\\)"
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:

> \# New Ticket Created by  Petr Pisar 
> \# Please include the string&#8203;:  \[perl \#133236\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133236 >
> 
> 
> Hello\,
> 
> Fedora Linux distribution decided
> \<https://fedoraproject.org/wiki/Changes/Replace_glibc_libcrypt_with_libxcrypt>.
> to replace GNU libc's libcrypt with libxcrypt implementation
> \<https://github.com/besser82/libxcrypt>. This caused perl to fail to build
> like this&#8203;:
> 
> cc \-c \-DPERL\_CORE \-D\_REENTRANT \-D\_GNU\_SOURCE \-I/usr/src/kernels/4\.15\.0\-0\.rc8\.git0\.1\.fc28\.x86\_64/arch/x86/include \-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-D\_FORTIFY\_SOURCE=2 \-std=c89 \-O2 \-Wall \-Werror=declaration\-after\-statement \-Werror=pointer\-arith \-Wextra \-Wc\+\+\-compat \-Wwrite\-strings pp\.c
> pp\.c&#8203;: In function ‘Perl\_pp\_crypt’&#8203;:
> pp\.c&#8203;:3654&#8203;:47&#8203;: error&#8203;: ‘struct crypt\_data’ has no member named ‘current\_saltbits’
>       PL\_reentrant\_buffer\->\_crypt\_struct\_buffer\->current\_saltbits = 0;
>                                                ^~
> This is caused by a workaround for a broken glibc perl implements\.
> 
> Attached patch fixes the failure by constraining the workaround only to broken
> glibc versions\.
> 
> Original patch author is Björn Esser\.
> 
> \-\- Petr

I vote \+1 for this patch\. Completely makes sense\, esp for non\-gcc
compilers \(Solaris\, HP\-UX\, AIX\, \.\.\.\)

\-\- 
H\.Merijn Brand  http&#8203;://tux\.nl   Perl Monger  http&#8203;://amsterdam\.pm\.org/
using perl5\.00307 \.\. 5\.27   porting perl5 on HP\-UX\, AIX\, and openSUSE
http&#8203;://mirrors\.develooper\.com/hpux/        http&#8203;://www\.test\-smoke\.org/
http&#8203;://qa\.perl\.org   http&#8203;://www\.goldmark\.org/jeff/stupid\-disclaimers/

**Comment by nikmanadli** [comment]
Hi

> ### From @Tux
> On Thu, 31 May 2018 13​:43​:23 -0700, "Petr Pisar \(via RT\)" <perlbug-followup@​perl.org> wrote​:
> 
> > # New Ticket Created by  Petr Pisar
> > # Please include the string​:  [perl #133236]
> > # in the subject line of all future correspondence about this issue.
> > # <URL​: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133236 >
> > Hello,
> > Fedora Linux distribution decided
> > <[https://fedoraproject.org/wiki/Changes/Replace_glibc_libcrypt_with_libxcrypt>](https://fedoraproject.org/wiki/Changes/Replace_glibc_libcrypt_with_libxcrypt%3E).
> > to replace GNU libc's libcrypt with libxcrypt implementation
> > <[https://github.com/besser82/libxcrypt>](https://github.com/besser82/libxcrypt%3E). This caused perl to fail to build
> > like this​:
> > cc -c -DPERL_CORE -D_REENTRANT -D_GNU_SOURCE -I/usr/src/kernels/4.15.0-0.rc8.git0.1.fc28.x86_64/arch/x86/include -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -std=c89 -O2 -Wall -Werror=declaration-after-statement -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings pp.c
> > pp.c​: In function ‘Perl_pp_crypt’​:
> > pp.c​:3654​:47​: error​: ‘struct crypt_data’ has no member named ‘current_saltbits’
> > PL_reentrant_buffer->_crypt_struct_buffer->current_saltbits = 0;
> > ^~
> > This is caused by a workaround for a broken glibc perl implements.
> > Attached patch fixes the failure by constraining the workaround only to broken
> > glibc versions.
> > Original patch author is Björn Esser.
> > -- Petr
> 
> I vote +1 for this patch. Completely makes sense, esp for non-gcc compilers (Solaris, HP-UX, AIX, ...)
> 
> -- H.Merijn Brand http​://tux.nl Perl Monger http​://amsterdam.pm.org/ using perl5.00307 .. 5.27 porting perl5 on HP-UX, AIX, and openSUSE http​://mirrors.develooper.com/hpux/ http​://www.test-smoke.org/ http​://qa.perl.org http​://www.goldmark.org/jeff/stupid-disclaimers/

Hi, I am a total newbie in scripting. I had similar error message and do not know how to apply this patch fix. Please kindly teach me on how to apply this patch. I tried to install perl v5.14.2 because one of the tools can only run using that perl version. please advise me, thank you for your time. :D

**Comment by ppisar** [comment]
V Thu, Nov 11, 2021 at 03:28:30AM -0800, nikmanadli napsal(a):
> Hi, I am a total newbie in scripting. I had similar error message and do not
> know how to apply this patch fix. Please kindly teach me on how to apply
> this patch. I tried to install perl v5.14.2 because one of the tools can
> only run using that perl version. please advise me, thank you for your time.
> :D
> 
I recommend you to study how to use a "patch" tool from this manual
<https://www.gnu.org/software/diffutils/manual/diffutils.html#Invoking-patch>.

In short, save the fix into a FILE, then move you working directory to the
unpacked perl sources, and apply the fix with "patch -p1 <FILE" command.

**Comment by nikmanadli** [comment]
> V Thu, Nov 11, 2021 at 03:28:30AM -0800, nikmanadli napsal(a):
> Hi, I am a total newbie in scripting. I had similar error message and do not know how to apply this patch fix. Please kindly teach me on how to apply this patch. I tried to install perl v5.14.2 because one of the tools can only run using that perl version. please advise me, thank you for your time. :D
> I recommend you to study how to use a "patch" tool from this manual <https://www.gnu.org/software/diffutils/manual/diffutils.html#Invoking-patch>. In short, save the fix into a FILE, then move you working directory to the unpacked perl sources, and apply the fix with "patch -p1 <FILE" command.

Thank you very much, you're a lifesaver! it worked! :))
