### ISSUE TITLE
Time::HiRes failing on installing 5.26.2

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16600]
Migrated from [rt.perl.org#133310](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133310) (status was 'open')

Searchable as RT133310$

**Comment by p5pRT** [comment]
### From jjn1056@gmail.com

Hi\,

This is in regards to

https://rt.cpan.org/Public/Bug/Display.html?id=116127#txn-1793016

I can verify that this fail occurs on several versions of Macosx but
installing from CPAN works fine\.  This is to request we bak port and
release via 5\.26\.3 since 5\.28 is still very new\.  Here's the details
\(attached Perl \-V\, the rest is inline\)

Thanks\!

jjnapiok

\./dist/Time\-HiRes/t/usleep\.t \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\. ok


\#   Failed test 'atime set correctly'

\#   at t/utime\.t line 73\.

\#          got&#8203;: '1'

\#     expected&#8203;: '1\.111111111'


\#   Failed test 'mtime set correctly'

\#   at t/utime\.t line 74\.

\#          got&#8203;: '2'

\#     expected&#8203;: '2\.222222222'


\#   Failed test 'atime set correctly'

\#   at t/utime\.t line 82\.

\#          got&#8203;: '1'

\#     expected&#8203;: '1\.111111111'


\#   Failed test 'mtime set correctly'

\#   at t/utime\.t line 83\.

\#          got&#8203;: '2'

\#     expected&#8203;: '2\.222222222'


\#   Failed test 'File 1 atime set correctly'

\#   at t/utime\.t line 93\.

\#          got&#8203;: '1'

\#     expected&#8203;: '1\.111111111'


\#   Failed test 'File 1 mtime set correctly'

\#   at t/utime\.t line 94\.

\#          got&#8203;: '2'

\#     expected&#8203;: '2\.222222222'


\#   Failed test 'File 2 atime set correctly'

\#   at t/utime\.t line 98\.

\#          got&#8203;: '1'

\#     expected&#8203;: '1\.111111111'


\#   Failed test 'File 2 mtime set correctly'

\#   at t/utime\.t line 99\.

\#          got&#8203;: '2'

\#     expected&#8203;: '2\.222222222'


\#   Failed test 'File 1 atime set correctly'

\#   at t/utime\.t line 113\.

\#     '0\.382514953613281'

\#         \<

\#     '0\.1'


\#   Failed test 'File 1 mtime set correctly'

\#   at t/utime\.t line 114\.

\#     '0\.382514953613281'

\#         \<

\#     '0\.1'


\#   Failed test 'File 2 atime set correctly'

\#   at t/utime\.t line 118\.

\#     '0\.382514953613281'

\#         \<

\#     '0\.1'


\#   Failed test 'File 2 mtime set correctly'

\#   at t/utime\.t line 119\.

\#     '0\.382514953613281'

\#         \<

\#     '0\.1'

\# Looks like you failed 12 tests of 18\.

\.\./dist/Time\-HiRes/t/utime\.t \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.

Dubious\, test returned 12 \(wstat 3072\, 0xc00\)

Failed 12/18 subtests


From looking around the reports this seems to be the consistent fail

**Comment by p5pRT** [comment]
### From jjn1056@gmail.com

[perlinfo](https://rt-archive.perl.org/perl5/Ticket/Attachment/1563483/824007/perlinfo)

**Comment by p5pRT** [comment]
### From @jkeenan

On Tue\, 26 Jun 2018 17&#8203;:01&#8203;:19 GMT\, jjn1056@&#8203;gmail\.com wrote&#8203;:
> Hi\,
> 
> This is in regards to
> 
> https://rt.cpan.org/Public/Bug/Display.html?id=116127#txn-1793016
> 
> I can verify that this fail occurs on several versions of Macosx but
> installing from CPAN works fine\.  This is to request we bak port and
> release via 5\.26\.3 since 5\.28 is still very new\.  Here's the details
> \(attached Perl \-V\, the rest is inline\)
> 
> Thanks\!
> 
> jjnapiok
> 
> \./dist/Time\-HiRes/t/usleep\.t \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\. ok
> 
> 
> \#   Failed test 'atime set correctly'
> 
> \#   at t/utime\.t line 73\.
> 
> \#          got&#8203;: '1'
> 
> \#     expected&#8203;: '1\.111111111'
> 
> 
> \#   Failed test 'mtime set correctly'
> 
> \#   at t/utime\.t line 74\.
> 
> \#          got&#8203;: '2'
> 
> \#     expected&#8203;: '2\.222222222'
> 
> 
> \#   Failed test 'atime set correctly'
> 
> \#   at t/utime\.t line 82\.
> 
> \#          got&#8203;: '1'
> 
> \#     expected&#8203;: '1\.111111111'
> 
> 
> \#   Failed test 'mtime set correctly'
> 
> \#   at t/utime\.t line 83\.
> 
> \#          got&#8203;: '2'
> 
> \#     expected&#8203;: '2\.222222222'
> 
> 
> \#   Failed test 'File 1 atime set correctly'
> 
> \#   at t/utime\.t line 93\.
> 
> \#          got&#8203;: '1'
> 
> \#     expected&#8203;: '1\.111111111'
> 
> 
> \#   Failed test 'File 1 mtime set correctly'
> 
> \#   at t/utime\.t line 94\.
> 
> \#          got&#8203;: '2'
> 
> \#     expected&#8203;: '2\.222222222'
> 
> 
> \#   Failed test 'File 2 atime set correctly'
> 
> \#   at t/utime\.t line 98\.
> 
> \#          got&#8203;: '1'
> 
> \#     expected&#8203;: '1\.111111111'
> 
> 
> \#   Failed test 'File 2 mtime set correctly'
> 
> \#   at t/utime\.t line 99\.
> 
> \#          got&#8203;: '2'
> 
> \#     expected&#8203;: '2\.222222222'
> 
> 
> \#   Failed test 'File 1 atime set correctly'
> 
> \#   at t/utime\.t line 113\.
> 
> \#     '0\.382514953613281'
> 
> \#         \<
> 
> \#     '0\.1'
> 
> 
> \#   Failed test 'File 1 mtime set correctly'
> 
> \#   at t/utime\.t line 114\.
> 
> \#     '0\.382514953613281'
> 
> \#         \<
> 
> \#     '0\.1'
> 
> 
> \#   Failed test 'File 2 atime set correctly'
> 
> \#   at t/utime\.t line 118\.
> 
> \#     '0\.382514953613281'
> 
> \#         \<
> 
> \#     '0\.1'
> 
> 
> \#   Failed test 'File 2 mtime set correctly'
> 
> \#   at t/utime\.t line 119\.
> 
> \#     '0\.382514953613281'
> 
> \#         \<
> 
> \#     '0\.1'
> 
> \# Looks like you failed 12 tests of 18\.
> 
> \.\./dist/Time\-HiRes/t/utime\.t \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.
> 
> Dubious\, test returned 12 \(wstat 3072\, 0xc00\)
> 
> Failed 12/18 subtests
> 
> 
> From looking around the reports this seems to be the consistent fail

Steve Hay\, can you evaluate this for 5\.26\.3?

Thank you very much\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by khwilliamson** [comment]
What's the status of this?

**Comment by jkeenan** [comment]
> What's the status of this?

1. perl-5.26 is long out-of-support, so we're not going to do anything there.
2. The [latest non-trial release of Time-HiRes to CPAN](http://matrix.cpantesters.org/?dist=Time-HiRes%201.9764) is generally doing okay on production releases of perl.  This distro is always a bit flaky, but I don't see anything warranting keeping this ticket open.  Closing now.
