### ISSUE TITLE
stack checks make -DDEBUGGING builds incompatible with normal ones

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16607]
Migrated from [rt.perl.org#133327](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133327) (status was 'open')

Searchable as RT133327$

**Comment by p5pRT** [comment]
### From @ntyni


This is a bug report for perl from Niko Tyni \<ntyni@&#8203;debian\.org>\,
generated with the help of perlbug 1\.41 running under perl 5\.28\.0\.




---
The stack 'high water mark' checks introduced in v5\.27\.1\-66\-g87058c31e9
seem to have introduced an incompatibility when XS modules are built
with a normal Perl but run with a \(otherwise similarly configured\)
\-DDEBUGGING Perl\.

We're using this combination in Debian as we offer a \-DDEBUGGING
interpreter \(called /usr/bin/debugperl\) in a separate package for the
benefit of our users\, but we don't rebuild all the XS modules with that\.

It would be useful for us to keep these builds binary compatible\.
Last time an incompatibility happened it was deemed worth fixing&#8203;:
see \[perl \#127212\] and Aaron's related commit message in 5ca5a62834a7f \.

Some symptoms of the breakage&#8203;:

 \# debugperl \-MDateTime \-e 'print DateTime\->today'
 panic&#8203;: XSUB DateTime&#8203;::\_rd2ymd \(DateTime\.c\) failed to extend arg stack&#8203;: base=55b63e6b3b48\, sp=55b63e6b3b80\, hwm=5
5b63e6b3b68

 \# printf '\<AAA>\\n\<DDD/>\<CCC>\<DDD>\\n\</DDD>\</CCC>\\n\</AAA>' | debugperl \-MXML&#8203;::LibXML \-e 'XML&#8203;::LibXML\->new\->parse\_f
h\(\*STDIN\)\->documentElement\->childNodes; '
 panic&#8203;: XSUB XML&#8203;::LibXML&#8203;::Node&#8203;::\_childNodes \(LibXML\.c\) failed to extend arg stack&#8203;: base=561827c61b48\, sp=561827c6
1b68\, hwm=561827c61b60

These are just examples\, and I believe the fault is not with the
modules\.

If I grok this correctly\, the problem is that EXTEND only updates
the high\-water mark when the DEBUGGING preprocessor symbol is defined
\(i\.e\. the choice is done at compile time\.\) If the XS module is built
without \-DDEBUGGING in ccflags \(as is the case for Debian XS module
packages\)\, the high\-water mark doesn't get updated\.  If the interpreter
side is built with \-DDEBUGGING \(as our debugperl is\)\, it will still
check the hwm\, resulting in the panic\.

Would it be feasible move the \-DDEBUGGING check in EXTEND to run time\,
for instance by calling a function that's a no\-op in non\-DEBUGGING
interpreters\, or checking for an interpreter variable that's only set
in \-DDEBUGGING builds? This has a runtime cost\, but I'm not sure how
significant that is?

Many thanks for your work\, and congratulations for another great Perl
stable release\!

\( This is also https://bugs.debian.org/902779 \)



---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=medium


---
Site configuration information for perl 5\.28\.0&#8203;:

Configured by Debian at Mon Jun 25 19&#8203;:20&#8203;:16 UTC 2018\.

Summary of my perl5 \(revision 5 version 28 subversion 0\) configuration&#8203;:
&nbsp;   
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux
&nbsp;    osvers=4\.9\.0
&nbsp;    archname=x86\_64\-linux\-gnu\-thread\-multi
&nbsp;    uname='linux localhost 4\.9\.0 \#1 smp debian 4\.9\.0 x86\_64 gnulinux '
&nbsp;    config\_args='\-Dusethreads \-Duselargefiles \-Dcc=x86\_64\-linux\-gnu\-gcc \-Dcpp=x86\_64\-linux\-gnu\-cpp \-Dld=x86\_64\-linux\-gnu\-gcc \-Dccflags=\-DDEBIAN \-Wdate\-time \-D\_FORTIFY\_SOURCE=2 \-g \-O2 \-fdebug\-prefix\-map=/build/perl\-yH5Gew/perl\-5\.28\.0=\. \-fstack\-protector\-strong \-Wformat \-Werror=format\-security \-Dldflags= \-Wl\,\-z\,relro \-Dlddlflags=\-shared \-Wl\,\-z\,relro \-Dcccdlflags=\-fPIC \-Darchname=x86\_64\-linux\-gnu \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.28 \-Darchlib=/usr/lib/x86\_64\-linux\-gnu/perl/5\.28 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/x86\_64\-linux\-gnu/perl5/5\.28 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.28\.0 \-Dsitearch=/usr/local/lib/x86\_64\-linux\-gnu/perl/5\.28\.0 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dsiteman1dir=/usr/local/man/man1 \-Dsiteman3dir=/usr/local/man/man3 \-Duse64bitint \-Dman1ext=1 \-Dman3ext=3perl
\-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Ud\_ualarm \-Uusesfio \-Uusenm \-Ui\_libutil \-Ui\_xlocale \-Uversiononly \-DDEBUGGING=\-g \-Doptimize=\-O2 \-dEs \-Duseshrplib \-Dlibperl=libperl\.so\.5\.28\.0'
&nbsp;    hint=recommended
&nbsp;    useposix=true
&nbsp;    d\_sigaction=define
&nbsp;    useithreads=define
&nbsp;    usemultiplicity=define
&nbsp;    use64bitint=define
&nbsp;    use64bitall=define
&nbsp;    uselongdouble=undef
&nbsp;    usemymalloc=n
&nbsp;    default\_inc\_excludes\_dot=define
&nbsp;    bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='x86\_64\-linux\-gnu\-gcc'
&nbsp;    ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fwrapv \-fno\-strict\-aliasing \-pipe \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'
&nbsp;    optimize='\-O2 \-g'
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fwrapv \-fno\-strict\-aliasing \-pipe \-I/usr/local/include'
&nbsp;    ccversion=''
&nbsp;    gccversion='7\.3\.0'
&nbsp;    gccosandvers=''
&nbsp;    intsize=4
&nbsp;    longsize=8
&nbsp;    ptrsize=8
&nbsp;    doublesize=8
&nbsp;    byteorder=12345678
&nbsp;    doublekind=3
&nbsp;    d\_longlong=define
&nbsp;    longlongsize=8
&nbsp;    d\_longdbl=define
&nbsp;    longdblsize=16
&nbsp;    longdblkind=3
&nbsp;    ivtype='long'
&nbsp;    ivsize=8
&nbsp;    nvtype='double'
&nbsp;    nvsize=8
&nbsp;    Off\_t='off\_t'
&nbsp;    lseeksize=8
&nbsp;    alignbytes=8
&nbsp;    prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='x86\_64\-linux\-gnu\-gcc'
&nbsp;    ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/7/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib
&nbsp;    libs=\-lgdbm \-lgdbm\_compat \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    libc=libc\-2\.27\.so
&nbsp;    so=so
&nbsp;    useshrplib=true
&nbsp;    libperl=libperl\.so\.5\.28
&nbsp;    gnulibc\_version='2\.27'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs
&nbsp;    dlext=so
&nbsp;    d\_dlsymun=undef
&nbsp;    ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'
&nbsp;    lddlflags='\-shared \-L/usr/local/lib \-fstack\-protector\-strong'

Locally applied patches&#8203;:
&nbsp;    DEBPKG&#8203;:debian/cpan\_definstalldirs \- Provide a sensible INSTALLDIRS default for modules installed from CPAN\.
&nbsp;    DEBPKG&#8203;:debian/db\_file\_ver \- https://bugs.debian.org/340047 Remove overly restrictive DB\_File version check\.
&nbsp;    DEBPKG&#8203;:debian/doc\_info \- Replace generic man\(1\) instructions with Debian\-specific information\.
&nbsp;    DEBPKG&#8203;:debian/enc2xs\_inc \- https://bugs.debian.org/290336 Tweak enc2xs to follow symlinks and ignore missing @&#8203;INC directories\.
&nbsp;    DEBPKG&#8203;:debian/errno\_ver \- https://bugs.debian.org/343351 Remove Errno version check due to upgrade problems with long\-running processes\.
&nbsp;    DEBPKG&#8203;:debian/libperl\_embed\_doc \- https://bugs.debian.org/186778 Note that libperl\-dev package is required for embedded linking
&nbsp;    DEBPKG&#8203;:fixes/respect\_umask \- Respect umask during installation
&nbsp;    DEBPKG&#8203;:debian/writable\_site\_dirs \- Set umask approproately for site install directories
&nbsp;    DEBPKG&#8203;:debian/extutils\_set\_libperl\_path \- EU&#8203;:MM&#8203;: set location of libperl\.a under /usr/lib
&nbsp;    DEBPKG&#8203;:debian/no\_packlist\_perllocal \- Don't install \.packlist or perllocal\.pod for perl or vendor
&nbsp;    DEBPKG&#8203;:debian/fakeroot \- Postpone LD\_LIBRARY\_PATH evaluation to the binary targets\.
&nbsp;    DEBPKG&#8203;:debian/instmodsh\_doc \- Debian policy doesn't install \.packlist files for core or vendor\.
&nbsp;    DEBPKG&#8203;:debian/ld\_run\_path \- Remove standard libs from LD\_RUN\_PATH as per Debian policy\.
&nbsp;    DEBPKG&#8203;:debian/libnet\_config\_path \- Set location of libnet\.cfg to /etc/perl/Net as /usr may not be writable\.
&nbsp;    DEBPKG&#8203;:debian/perlivp \- https://bugs.debian.org/510895 Make perlivp skip include directories in /usr/local
&nbsp;    DEBPKG&#8203;:debian/squelch\-locale\-warnings \- https://bugs.debian.org/508764 Squelch locale warnings in Debian package maintainer scripts
&nbsp;    DEBPKG&#8203;:debian/patchlevel \- https://bugs.debian.org/567489 List packaged patches for 5\.28\.0\-1 in patchlevel\.h
&nbsp;    DEBPKG&#8203;:fixes/document\_makemaker\_ccflags \- https://bugs.debian.org/628522 \[rt\.cpan\.org \#68613\] Document that CCFLAGS should include $Config\{ccflags\}
&nbsp;    DEBPKG&#8203;:debian/find\_html2text \- https://bugs.debian.org/640479 Configure CPAN&#8203;::Distribution with correct name of html2text
&nbsp;    DEBPKG&#8203;:debian/perl5db\-x\-terminal\-emulator\.patch \- https://bugs.debian.org/668490 Invoke x\-terminal\-emulator rather than xterm in perl5db\.pl
&nbsp;    DEBPKG&#8203;:debian/cpan\-missing\-site\-dirs \- https://bugs.debian.org/688842 Fix CPAN&#8203;::FirstTime defaults with nonexisting site dirs if a parent is writable
&nbsp;    DEBPKG&#8203;:fixes/memoize\_storable\_nstore \- \[rt\.cpan\.org \#77790\] https://bugs.debian.org/587650 Memoize&#8203;::Storable&#8203;: respect 'nstore' option not respected
&nbsp;    DEBPKG&#8203;:debian/makemaker\-pasthru \- https://bugs.debian.org/758471 Pass LD settings through to subdirectories
&nbsp;    DEBPKG&#8203;:debian/makemaker\-manext \- https://bugs.debian.org/247370 Make EU&#8203;::MakeMaker honour MANnEXT settings in generated manpage headers
&nbsp;    DEBPKG&#8203;:debian/kfreebsd\-softupdates \- https://bugs.debian.org/796798 Work around Debian Bug\#796798
&nbsp;    DEBPKG&#8203;:fixes/autodie\-scope \- https://bugs.debian.org/798096 Fix a scoping issue with "no autodie" and the "system" sub
&nbsp;    DEBPKG&#8203;:fixes/memoize\-pod \- \[rt\.cpan\.org \#89441\] Fix POD errors in Memoize
&nbsp;    DEBPKG&#8203;:debian/hurd\-softupdates \- https://bugs.debian.org/822735 Fix t/op/stat\.t failures on hurd
&nbsp;    DEBPKG&#8203;:fixes/math\_complex\_doc\_great\_circle \- https://bugs.debian.org/697567 \[rt\.cpan\.org \#114104\] Math&#8203;::Trig&#8203;: clarify definition of great\_circle\_midpoint
&nbsp;    DEBPKG&#8203;:fixes/math\_complex\_doc\_see\_also \- https://bugs.debian.org/697568 \[rt\.cpan\.org \#114105\] Math&#8203;::Trig&#8203;: add missing SEE ALSO
&nbsp;    DEBPKG&#8203;:fixes/math\_complex\_doc\_angle\_units \- https://bugs.debian.org/731505 \[rt\.cpan\.org \#114106\] Math&#8203;::Trig&#8203;: document angle units
&nbsp;    DEBPKG&#8203;:fixes/cpan\_web\_link \- https://bugs.debian.org/367291 CPAN&#8203;: Add link to main CPAN web site
&nbsp;    DEBPKG&#8203;:debian/hppa\_op\_optimize\_workaround \- https://bugs.debian.org/838613 Temporarily lower the optimization of op\.c on hppa due to gcc\-6 problems
&nbsp;    DEBPKG&#8203;:debian/installman\-utf8 \- https://bugs.debian.org/840211 Generate man pages with UTF\-8 characters
&nbsp;    DEBPKG&#8203;:fixes/getopt\-long\-4 \- https://bugs.debian.org/864544 \[rt\.cpan\.org \#122068\] Fix issue \#122068\.
&nbsp;    DEBPKG&#8203;:debian/hppa\_opmini\_optimize\_workaround \- https://bugs.debian.org/869122 Lower the optimization level of opmini\.c on hppa
&nbsp;    DEBPKG&#8203;:debian/sh4\_op\_optimize\_workaround \- https://bugs.debian.org/869373 Also lower the optimization level of op\.c and opmini\.c on sh4
&nbsp;    DEBPKG&#8203;:debian/perldoc\-pager \- https://bugs.debian.org/870340 \[rt\.cpan\.org \#120229\] Fix perldoc terminal escapes when sensible\-pager is less
&nbsp;    DEBPKG&#8203;:debian/prune\_libs \- https://bugs.debian.org/128355 Prune the list of libraries wanted to what we actually need\.
&nbsp;    DEBPKG&#8203;:debian/mod\_paths \- Tweak @&#8203;INC ordering for Debian
&nbsp;    DEBPKG&#8203;:debian/configure\-regen \- https://bugs.debian.org/762638 Regenerate Configure et al\. after probe unit changes
&nbsp;    DEBPKG&#8203;:debian/deprecate\-with\-apt \- https://bugs.debian.org/747628 Point users to Debian packages of deprecated core modules



---
@&#8203;INC for perl 5\.28\.0&#8203;:
&nbsp;    /etc/perl
&nbsp;    /usr/local/lib/x86\_64\-linux\-gnu/perl/5\.28\.0
&nbsp;    /usr/local/share/perl/5\.28\.0
&nbsp;    /usr/lib/x86\_64\-linux\-gnu/perl5/5\.28
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/x86\_64\-linux\-gnu/perl/5\.28
&nbsp;    /usr/share/perl/5\.28
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    /usr/lib/x86\_64\-linux\-gnu/perl\-base



---
Environment for perl 5\.28\.0&#8203;:
&nbsp;    HOME=/home/ntyni
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH=/usr/lib/libeatmydata
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/local/games&#8203;:/usr/games
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @dur-randir

On Tue\, 03 Jul 2018 08&#8203;:49&#8203;:38 \-0700\, ntyni@&#8203;debian\.org wrote&#8203;:

> Would it be feasible move the \-DDEBUGGING check in EXTEND to run time\,
> for instance by calling a function that's a no\-op in non\-DEBUGGING
> interpreters\, or checking for an interpreter variable that's only set
> in \-DDEBUGGING builds? This has a runtime cost\, but I'm not sure how
> significant that is?

A lot of module authors use EXTEND pessimistically\, like the whole XPUSH\* macro family\, effectively calling EXTEND in O\(return values\) number of times\. And the suggested approach will surely penalize this\. Cpan search showed more than 1000 distribution with this pattern\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, Jul 03\, 2018 at 08&#8203;:49&#8203;:39AM \-0700\, Niko Tyni \(via RT\) wrote&#8203;:
> The stack 'high water mark' checks introduced in v5\.27\.1\-66\-g87058c31e9
> seem to have introduced an incompatibility when XS modules are built
> with a normal Perl but run with a \(otherwise similarly configured\)
> \-DDEBUGGING Perl\.
> 
> We're using this combination in Debian as we offer a \-DDEBUGGING
> interpreter \(called /usr/bin/debugperl\) in a separate package for the
> benefit of our users\, but we don't rebuild all the XS modules with that\.
\[snip\]
> If I grok this correctly\, the problem is that EXTEND only updates
> the high\-water mark when the DEBUGGING preprocessor symbol is defined
> \(i\.e\. the choice is done at compile time\.\) If the XS module is built
> without \-DDEBUGGING in ccflags \(as is the case for Debian XS module
> packages\)\, the high\-water mark doesn't get updated\.  If the interpreter
> side is built with \-DDEBUGGING \(as our debugperl is\)\, it will still
> check the hwm\, resulting in the panic\.
> 
> Would it be feasible move the \-DDEBUGGING check in EXTEND to run time\,
> for instance by calling a function that's a no\-op in non\-DEBUGGING
> interpreters\, or checking for an interpreter variable that's only set
> in \-DDEBUGGING builds? This has a runtime cost\, but I'm not sure how
> significant that is?

I wouldn't like any solution that adds extra run\-time overhead to
non\-debugging\-build XS modules\.

To avoid that\, the debugging part of the perl interperter would need to be
able to determine when it calls an XS sub or a non\-core pp\_foo\(\) function\,
whether that code what compiled under DEBUGGING\. I can't think of a way to
determine this\.

A fall\-back position would be to add support for a PERL\_NO\_STACK\_HWM\_CHECK
define / build option which would completely disable checks\, even if
the core was built with DEBUGGING\. That would of course disable
the check even for XS modules built with DEBUGGING\.

\-\- 
Overhead\, without any fuss\, the stars were going out\.
&nbsp;    \-\- Arthur C Clarke

**Comment by p5pRT** [comment]
### From @bulk88

On Tue\, 03 Jul 2018 08&#8203;:49&#8203;:38 \-0700\, ntyni@&#8203;debian\.org wrote&#8203;:
> 
> This is a bug report for perl from Niko Tyni \<ntyni@&#8203;debian\.org>\,
> generated with the help of perlbug 1\.41 running under perl 5\.28\.0\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> 
> The stack 'high water mark' checks introduced in v5\.27\.1\-66\-
> g87058c31e9
> seem to have introduced an incompatibility when XS modules are built
> with a normal Perl but run with a \(otherwise similarly configured\)
> \-DDEBUGGING Perl\.
> 
> We're using this combination in Debian as we offer a \-DDEBUGGING
> interpreter \(called /usr/bin/debugperl\) in a separate package for the
> benefit of our users\, but we don't rebuild all the XS modules with
> that\.
> 
> It would be useful for us to keep these builds binary compatible\.
> Last time an incompatibility happened it was deemed worth fixing&#8203;:
> see \[perl \#127212\] and Aaron's related commit message in 5ca5a62834a7f
> \.
> 
> Some symptoms of the breakage&#8203;:
> 
> \# debugperl \-MDateTime \-e 'print DateTime\->today'
> panic&#8203;: XSUB DateTime&#8203;::\_rd2ymd \(DateTime\.c\) failed to extend arg stack&#8203;:
> base=55b63e6b3b48\, sp=55b63e6b3b80\, hwm=5
> 5b63e6b3b68
> 
> \# printf '\<AAA>\\n\<DDD/>\<CCC>\<DDD>\\n\</DDD>\</CCC>\\n\</AAA>' | debugperl
> \-MXML&#8203;::LibXML \-e 'XML&#8203;::LibXML\->new\->parse\_f
> h\(\*STDIN\)\->documentElement\->childNodes; '
> panic&#8203;: XSUB XML&#8203;::LibXML&#8203;::Node&#8203;::\_childNodes \(LibXML\.c\) failed to extend
> arg stack&#8203;: base=561827c61b48\, sp=561827c6
> 1b68\, hwm=561827c61b60
> 
> These are just examples\, and I believe the fault is not with the
> modules\.
> 
> If I grok this correctly\, the problem is that EXTEND only updates
> the high\-water mark when the DEBUGGING preprocessor symbol is defined
> \(i\.e\. the choice is done at compile time\.\) If the XS module is built
> without \-DDEBUGGING in ccflags \(as is the case for Debian XS module
> packages\)\, the high\-water mark doesn't get updated\.  If the
> interpreter
> side is built with \-DDEBUGGING \(as our debugperl is\)\, it will still
> check the hwm\, resulting in the panic\.
> 
> Would it be feasible move the \-DDEBUGGING check in EXTEND to run time\,
> for instance by calling a function that's a no\-op in non\-DEBUGGING
> interpreters\, or checking for an interpreter variable that's only set
> in \-DDEBUGGING builds? This has a runtime cost\, but I'm not sure how
> significant that is?

DEBUGGING is a build option\, either the whole interp has it or it doesn't\. P5P already questionably added struct fields that are unused on non\-DEBUGGING to make DEBUGGING vs not binary compatible but I disagree with that quick fix\. Perhaps perl\.h should be tweaked to turn on libc assert\(\) without rest of DEBUGGING features and /usr/bin/debugperl should be compiled with that just\-libc\-assert flag\.

\-\- 
bulk88 ~ bulk88 at hotmail\.com

**Comment by p5pRT** [comment]
### From @ntyni

On Wed\, Jul 04\, 2018 at 05&#8203;:28&#8203;:21AM \-0700\, Dave Mitchell via RT wrote&#8203;:
> On Tue\, Jul 03\, 2018 at 08&#8203;:49&#8203;:39AM \-0700\, Niko Tyni \(via RT\) wrote&#8203;:

> > Would it be feasible move the \-DDEBUGGING check in EXTEND to run time\,
> > for instance by calling a function that's a no\-op in non\-DEBUGGING
> > interpreters\, or checking for an interpreter variable that's only set
> > in \-DDEBUGGING builds? This has a runtime cost\, but I'm not sure how
> > significant that is?
> 
> I wouldn't like any solution that adds extra run\-time overhead to
> non\-debugging\-build XS modules\.
> 
> To avoid that\, the debugging part of the perl interperter would need to be
> able to determine when it calls an XS sub or a non\-core pp\_foo\(\) function\,
> whether that code what compiled under DEBUGGING\. I can't think of a way to
> determine this\.

I see\.
 
> A fall\-back position would be to add support for a PERL\_NO\_STACK\_HWM\_CHECK
> define / build option which would completely disable checks\, even if
> the core was built with DEBUGGING\. That would of course disable
> the check even for XS modules built with DEBUGGING\.

Yeah\, I suppose we will have to disable the checks in the Debian
debugperl for now\. A supported way to do that in 5\.30 would be very
much appreciated\.

Thanks for looking at this\,
\-\- 
Niko

**Comment by leonerd** [comment]
I've just encountered this in the wild and it took  me a long time to realise what was going on.

The only obvious failing when you actually run the code is the "panic: XSUB ... failed to extend arg stack", and leads you off in a very wrong path debugging it, when the actual failure is "You built your XS module without -DDEBUGGING and now you're running it with a -DDEBUGGING perl".

Surely the presence of -DDEBUGGING ought to be involved in the XS module handshake mechanism, such that a failure of this kind would be much more obviously visible at module load time instead?

**Comment by Leont** [comment]
> Surely the presence of -DDEBUGGING ought to be involved in the XS module handshake mechanism, such that a failure of this kind would be much more obviously visible at module load time instead?

That would break the sort of setup that debian has been using since forever..

**Comment by iabyn** [comment]
On Mon, Apr 08, 2024 at 01:54:36PM -0700, Leon Timmermans wrote:
> > Surely the presence of -DDEBUGGING ought to be involved in the XS
> > module handshake mechanism, such that a failure of this kind would be
> > much more obviously visible at module load time instead?
> 
> That would break the sort of setup that debian has been using since forever.. 

Just out of curiosity, why is that the case?

-- 
"I used to be with it, but then they changed what ‘it’ was, and now what
I’m with isn’t it. And what’s ‘it’ seems weird and scary to me."
  -- Grandpa Simpson
(It will happen to you too.)

**Comment by leonerd** [comment]
And moreover, how is it that debian's setup doesn't break here? Is there something we could steal from that to make these things work better?

**Comment by Leont** [comment]
Looks to me like @tonycoz's solution is the right one. And arguably that `PERL_USE_HWM` should be part of the handshake instead of `DEBUGGING`

**Comment by tonycoz** [comment]
> And arguably that `PERL_USE_HWM` should be part of the handshake instead of `DEBUGGING`

I do think the HWM checks should be enabled by default for -DDEBUGGING, the checks it performs are just too useful, especially for XS.

**Comment by ntyni** [comment]
On Tue, Apr 09, 2024 at 03:02:27AM -0700, iabyn wrote:
> On Mon, Apr 08, 2024 at 01:54:36PM -0700, Leon Timmermans wrote:
> > > Surely the presence of -DDEBUGGING ought to be involved in the XS
> > > module handshake mechanism, such that a failure of this kind would be
> > > much more obviously visible at module load time instead?
> > 
> > That would break the sort of setup that debian has been using since forever.. 
> 
> Just out of curiosity, why is that the case?

Hi, as I explained in the original submission, we offer a -DDEBUGGING
interpreter (called /usr/bin/debugperl) in a separate package for the
benefit of our users, but we don't rebuild all the XS modules with that
(as providing hundreds of debug builds alongside the main ones seems
an obviously bad tradeoff.)

It would be useful for us to keep these builds binary compatible, so that
users could run the -DDEBUGGING build with the normal XS module packages
in the Debian archive when investigating segfaults and the like. This
was the case until Perl 5.28 or so, and based on the earlier discussion
in this ticket we have since been patching the high-water mark checks
away in Debian to keep things so.

Making -DDEBUGGING part of the handshake would improve the failure mode
to provide better diagnostics, but would still mean that debugperl could
not load the modules, and make it even harder for us to patch it. So it
would not solve the underlying issue for us.

Tony's fix in #22131 adds a supported way to disable the checks at the
Configure stage, so we could drop our patch altogether. I'm all for that
of course.

Hope this clarifies,
-- 
Niko

**Comment by ntyni** [comment]
On Tue, Apr 09, 2024 at 03:54:46AM -0700, Paul Evans wrote:
> And moreover, how is it that debian's setup doesn't break here? Is there something we could steal from that to make these things work better?

We're just patching the high water checks away currently with

  https://salsa.debian.org/perl-team/interpreter/perl/-/blob/debian-5.38/debian/patches/debian/disable-stack-check.diff

Tony's fix in #22131 gives a way to disable them at Configure time,
so it's clearly superior.
-- 
Niko
