### ISSUE TITLE
pp_gpwent - could skip shadow call when euid > 0 on linux

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16637]
Migrated from [rt.perl.org#133388](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133388) (status was 'open')

Searchable as RT133388$

**Comment by p5pRT** [comment]
### From @atoomic

#### Created by @atoomic



The perl implementation of getpw\* \(pp\_gpwent\) does a calls to both the
normal getpw\*\(\) functions and getspnam\(\)\. When EUID \!=0\, the shadow file
will be unreadable\, so this second getspnam\(\) call is just wasted effort\.
The comments in pp\_gpwent acknowledge this fact\, but make the call anyway
to handle platforms where the EUID is meaningless\.

Here is an attempt to avoid this extra check on some "known platforms”

https://github.com/atoomic/perl5/pull/6

I'm not sure if \_\_linux\_\_ is the best preprocessor check here\. Is it too
wide? Can we assume all linux platform will behave the same? Should not we
also add \_\_APPLE\_\_ ?

I will attach the patch and some benchmark metrics in a future reply to
this thread

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl 5.26.2:

Configured by nicolas at Fri Apr 20 11:44:33 CEST 2018.

Summary of my perl5 (revision 5 version 26 subversion 2) configuration:
  Commit id: c5b1997939178730653db9e80f90cd53d722fe8d
  Platform:
    osname=darwin
    osvers=17.5.0
    archname=darwin-2level
    uname='darwin macnico.local 17.5.0 darwin kernel version 17.5.0: mon
mar 5 22:24:32 pst 2018; root:xnu-4570.51.1~1release_x86_64 x86_64 '
    config_args='-Dcc=ccache gcc -Dusedevel -Doptimize=-g3 -des'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='ccache gcc'
    ccflags ='-fno-common -DPERL_DARWIN -no-cpp-precomp
-mmacosx-version-min=10.13 -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-g3'
    cppflags='-no-cpp-precomp -fno-common -DPERL_DARWIN -no-cpp-precomp
-mmacosx-version-min=10.13 -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='ccache gcc'
    ldflags =' -mmacosx-version-min=10.13 -fstack-protector-strong
-L/usr/local/lib'
    libpth=/usr/local/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/lib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/lib
/usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.13 -bundle -undefined
dynamic_lookup -L/usr/local/lib -fstack-protector-strong'



@INC for perl 5.26.2:
    lib
    .
    /Users/nicolas/.dotfiles/perl-must-have/lib
    /Users/nicolas/perl5/lib/perl5/
    /usr/local/lib/perl5/site_perl/5.26.2/darwin-2level
    /usr/local/lib/perl5/site_perl/5.26.2
    /usr/local/lib/perl5/5.26.2/darwin-2level
    /usr/local/lib/perl5/5.26.2


Environment for perl 5.26.2:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/nicolas
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_CTYPE=en_US.UTF-8
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)

PATH=/Users/nicolas/perl5/perlbrew/bin:/Users/nicolas/perl5/perlbrew/perls/perl-5.26.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/usr/local/git/bin:/Users/nicolas/.dotfiles/bin:/Users/nicolas/perl5/bin:/Applications/Rakudo/bin:/Applications/Rakudo/share/perl6/site/bin
    PERL5DB=use Devel::NYTProf

PERL5LIB=/Users/nicolas/.dotfiles/perl-must-have/lib:/Users/nicolas/perl5/lib/perl5/
    PERLBREW_HOME=/Users/nicolas/.perlbrew
    PERLBREW_MANPATH=/Users/nicolas/perl5/perlbrew/perls/perl-5.26.1/man

PERLBREW_PATH=/Users/nicolas/perl5/perlbrew/bin:/Users/nicolas/perl5/perlbrew/perls/perl-5.26.1/bin
    PERLBREW_PERL=perl-5.26.1
    PERLBREW_ROOT=/Users/nicolas/perl5/perlbrew
    PERLBREW_SHELLRC_VERSION=0.82
    PERLBREW_VERSION=0.82
    PERL_BADLANG (unset)
    PERL_CPANM_OPT=--quiet
    SHELL=/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
### From @atoomic

Here's the suggested patch attached to the message

On Tue\, 17 Jul 2018 11&#8203;:05&#8203;:25 \-0700\, atoomic@&#8203;cpan\.org wrote&#8203;:
> This is a bug report for perl from atoomic@&#8203;cpan\.org\,
> generated with the help of perlbug 1\.40 running under perl 5\.26\.2\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please describe your issue here\]
> 
> The perl implementation of getpw\* \(pp\_gpwent\) does a calls to both the
> normal getpw\*\(\) functions and getspnam\(\)\. When EUID \!=0\, the shadow
> file
> will be unreadable\, so this second getspnam\(\) call is just wasted
> effort\.
> The comments in pp\_gpwent acknowledge this fact\, but make the call
> anyway
> to handle platforms where the EUID is meaningless\.
> 
> Here is an attempt to avoid this extra check on some "known platforms”
> 
> https://github.com/atoomic/perl5/pull/6
> 
> I'm not sure if \_\_linux\_\_ is the best preprocessor check here\. Is it
> too
> wide? Can we assume all linux platform will behave the same? Should
> not we
> also add \_\_APPLE\_\_ ?
> 
> I will attach the patch and some benchmark metrics in a future reply
> to
> this thread
> 
> \[Please do not change anything below this line\]
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \-\-\-
> Flags&#8203;:
>     category=core
>     severity=low
> \-\-\-
> Site configuration information for perl 5\.26\.2&#8203;:
> 
> Configured by nicolas at Fri Apr 20 11&#8203;:44&#8203;:33 CEST 2018\.
> 
> Summary of my perl5 \(revision 5 version 26 subversion 2\)
> configuration&#8203;:
>   Commit id&#8203;: c5b1997939178730653db9e80f90cd53d722fe8d
>   Platform&#8203;:
>     osname=darwin
>     osvers=17\.5\.0
>     archname=darwin\-2level
>     uname='darwin macnico\.local 17\.5\.0 darwin kernel version 17\.5\.0&#8203;:
> mon
> mar 5 22&#8203;:24&#8203;:32 pst 2018; root&#8203;:xnu\-4570\.51\.1~1release\_x86\_64 x86\_64 '
>     config\_args='\-Dcc=ccache gcc \-Dusedevel \-Doptimize=\-g3 \-des'
>     hint=recommended
>     useposix=true
>     d\_sigaction=define
>     useithreads=undef
>     usemultiplicity=undef
>     use64bitint=define
>     use64bitall=define
>     uselongdouble=undef
>     usemymalloc=n
>     default\_inc\_excludes\_dot=define
>     bincompat5005=undef
>   Compiler&#8203;:
>     cc='ccache gcc'
>     ccflags ='\-fno\-common \-DPERL\_DARWIN \-no\-cpp\-precomp
> \-mmacosx\-version\-min=10\.13 \-fno\-strict\-aliasing \-pipe
> \-fstack\-protector\-strong \-I/usr/local/include \-DPERL\_USE\_SAFE\_PUTENV'
>     optimize='\-g3'
>     cppflags='\-no\-cpp\-precomp \-fno\-common \-DPERL\_DARWIN \-no\-cpp\-
> precomp
> \-mmacosx\-version\-min=10\.13 \-fno\-strict\-aliasing \-pipe
> \-fstack\-protector\-strong \-I/usr/local/include'
>     ccversion=''
>     gccversion='4\.2\.1 Compatible Apple LLVM 9\.1\.0 \(clang\-902\.0\.39\.1\)'
>     gccosandvers=''
>     intsize=4
>     longsize=8
>     ptrsize=8
>     doublesize=8
>     byteorder=12345678
>     doublekind=3
>     d\_longlong=define
>     longlongsize=8
>     d\_longdbl=define
>     longdblsize=16
>     longdblkind=3
>     ivtype='long'
>     ivsize=8
>     nvtype='double'
>     nvsize=8
>     Off\_t='off\_t'
>     lseeksize=8
>     alignbytes=8
>     prototype=define
>   Linker and Libraries&#8203;:
>     ld='ccache gcc'
>     ldflags =' \-mmacosx\-version\-min=10\.13 \-fstack\-protector\-strong
> \-L/usr/local/lib'
>     libpth=/usr/local/lib
> /Applications/Xcode\.app/Contents/Developer/Toolchains/XcodeDefault\.xctoolchain/usr/lib/clang/9\.1\.0/lib
> /Applications/Xcode\.app/Contents/Developer/Toolchains/XcodeDefault\.xctoolchain/usr/lib
> /Applications/Xcode\.app/Contents/Developer/Platforms/MacOSX\.platform/Developer/SDKs/MacOSX10\.13\.sdk/usr/lib
> /usr/lib
>     libs=\-lpthread \-lgdbm \-ldbm \-ldl \-lm \-lutil \-lc
>     perllibs=\-lpthread \-ldl \-lm \-lutil \-lc
>     libc=
>     so=dylib
>     useshrplib=false
>     libperl=libperl\.a
>     gnulibc\_version=''
>   Dynamic Linking&#8203;:
>     dlsrc=dl\_dlopen\.xs
>     dlext=bundle
>     d\_dlsymun=undef
>     ccdlflags=' '
>     cccdlflags=' '
>     lddlflags=' \-mmacosx\-version\-min=10\.13 \-bundle \-undefined
> dynamic\_lookup \-L/usr/local/lib \-fstack\-protector\-strong'
> 
> 
> \-\-\-
> @&#8203;INC for perl 5\.26\.2&#8203;:
>     lib
>     \.
>     /Users/nicolas/\.dotfiles/perl\-must\-have/lib
>     /Users/nicolas/perl5/lib/perl5/
>     /usr/local/lib/perl5/site\_perl/5\.26\.2/darwin\-2level
>     /usr/local/lib/perl5/site\_perl/5\.26\.2
>     /usr/local/lib/perl5/5\.26\.2/darwin\-2level
>     /usr/local/lib/perl5/5\.26\.2
> 
> \-\-\-
> Environment for perl 5\.26\.2&#8203;:
>     DYLD\_LIBRARY\_PATH \(unset\)
>     HOME=/Users/nicolas
>     LANG=en\_US\.UTF\-8
>     LANGUAGE \(unset\)
>     LC\_CTYPE=en\_US\.UTF\-8
>     LD\_LIBRARY\_PATH \(unset\)
>     LOGDIR \(unset\)
> 
> PATH=/Users/nicolas/perl5/perlbrew/bin&#8203;:/Users/nicolas/perl5/perlbrew/perls/perl\-
> 5\.26\.1/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/sbin&#8203;:/sbin&#8203;:/usr/local/MacGPG2/bin&#8203;:/opt/X11/bin&#8203;:/usr/local/git/bin&#8203;:/Users/nicolas/\.dotfiles/bin&#8203;:/Users/nicolas/perl5/bin&#8203;:/Applications/Rakudo/bin&#8203;:/Applications/Rakudo/share/perl6/site/bin
>     PERL5DB=use Devel&#8203;::NYTProf
> 
> PERL5LIB=/Users/nicolas/\.dotfiles/perl\-must\-
> have/lib&#8203;:/Users/nicolas/perl5/lib/perl5/
>     PERLBREW\_HOME=/Users/nicolas/\.perlbrew
>     PERLBREW\_MANPATH=/Users/nicolas/perl5/perlbrew/perls/perl\-
> 5\.26\.1/man
> 
> PERLBREW\_PATH=/Users/nicolas/perl5/perlbrew/bin&#8203;:/Users/nicolas/perl5/perlbrew/perls/perl\-
> 5\.26\.1/bin
>     PERLBREW\_PERL=perl\-5\.26\.1
>     PERLBREW\_ROOT=/Users/nicolas/perl5/perlbrew
>     PERLBREW\_SHELLRC\_VERSION=0\.82
>     PERLBREW\_VERSION=0\.82
>     PERL\_BADLANG \(unset\)
>     PERL\_CPANM\_OPT=\-\-quiet
>     SHELL=/bin/zsh

**Comment by p5pRT** [comment]
### From @atoomic

<details><summary>0001-skip-shadow-call-when-euid-0-on-linux.patch</summary>

```diff
From b6c147cd2c970a847fdde502af2f9423c103872d Mon Sep 17 00:00:00 2001
From: Nicolas R <atoomic@cpan.org>
Date: Mon, 16 Jul 2018 11:26:59 -0600
Subject: [PATCH] skip shadow call when euid > 0 on linux

maybe __linux__ is not restrictive enough
and we could consider using a hint sh file
to enable it only on some specific distro?
---
 pp_sys.c | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/pp_sys.c b/pp_sys.c
index 4ae475d460..08b2752572 100644
--- a/pp_sys.c
+++ b/pp_sys.c
@@ -5562,7 +5562,11 @@ PP(pp_gpwent)
 	 * --jhi */
 	/* Some AIX setups falsely(?) detect some getspnam(), which
 	 * has a different API than the Solaris/IRIX one. */
+
 #   if defined(HAS_GETSPNAM) && !defined(_AIX)
+#      ifdef __linux__
+    if (!PerlProc_geteuid())
+#      endif
 	{
 	    dSAVE_ERRNO;
 	    const struct spwd * const spwent = getspnam(pwent->pw_name);
-- 
2.15.2 (Apple Git-101.1)


```
</details>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @atoomic

Some basic benchmark using the attached file bench\-getpw and the Porting/bench\.pl tool

\*\*  when run as root \*\* close to no difference

\./perl \-Ilib Porting/bench\.pl \-\-benchfile=/tmp/bench\-getpw \.\./perl2/perl=blead \./perl=blead\+patch
Key&#8203;:
&nbsp;    Ir   Instruction read
&nbsp;    Dr   Data read
&nbsp;    Dw   Data write
&nbsp;    COND conditional branches
&nbsp;    IND  indirect branches
&nbsp;    \_m   branch predict miss
&nbsp;    \_m1  level 1 cache miss
&nbsp;    \_mm  last cache \(e\.g\. L3\) miss
&nbsp;    \-    indeterminate percentage \(e\.g\. 1/0\)

The numbers represent relative counts per loop iteration\, compared to
blead at 100\.0%\.
Higher is better&#8203;: for example\, using half as many instructions gives 200%\,
while using twice as many gives 50%\.

getpwuid
getpwuid

&nbsp;        blead blead\+patch
&nbsp;       \-\-\-\-\-\- \-\-\-\-\-\-\-\-\-\-\-
&nbsp;    Ir 100\.00       99\.92
&nbsp;    Dr 100\.00       99\.92
&nbsp;    Dw 100\.00       99\.93
&nbsp;  COND 100\.00       99\.94
&nbsp;   IND 100\.00       98\.99

COND\_m 100\.00      104\.34
 IND\_m 100\.00       97\.37

 Ir\_m1 100\.00       99\.45
 Dr\_m1 100\.00      100\.00
 Dw\_m1 100\.00      100\.00

 Ir\_mm 100\.00      100\.00
 Dr\_mm 100\.00      100\.00
 Dw\_mm 100\.00      100\.00

getpwent
getpwent

&nbsp;        blead blead\+patch
&nbsp;       \-\-\-\-\-\- \-\-\-\-\-\-\-\-\-\-\-
&nbsp;    Ir 100\.00       99\.97
&nbsp;    Dr 100\.00       99\.97
&nbsp;    Dw 100\.00       99\.97
&nbsp;  COND 100\.00       99\.98
&nbsp;   IND 100\.00       99\.39

COND\_m 100\.00      100\.57
 IND\_m 100\.00       97\.29

 Ir\_m1 100\.00       99\.95
 Dr\_m1 100\.00      110\.53
 Dw\_m1 100\.00      100\.00

 Ir\_mm 100\.00      100\.00
 Dr\_mm 100\.00      100\.00
 Dw\_mm 100\.00      100\.00

getpwnam
getpwnam\(root\)

&nbsp;        blead blead\+patch
&nbsp;       \-\-\-\-\-\- \-\-\-\-\-\-\-\-\-\-\-
&nbsp;    Ir 100\.00       99\.93
&nbsp;    Dr 100\.00       99\.92
&nbsp;    Dw 100\.00       99\.94
&nbsp;  COND 100\.00       99\.95
&nbsp;   IND 100\.00       98\.99

COND\_m 100\.00      102\.59
 IND\_m 100\.00       97\.37

 Ir\_m1 100\.00       99\.95
 Dr\_m1 100\.00      100\.00
 Dw\_m1 100\.00      100\.00

 Ir\_mm 100\.00      100\.00
 Dr\_mm 100\.00      100\.00
 Dw\_mm 100\.00      100\.00

AVERAGE

&nbsp;        blead blead\+patch
&nbsp;       \-\-\-\-\-\- \-\-\-\-\-\-\-\-\-\-\-
&nbsp;    Ir 100\.00       99\.94
&nbsp;    Dr 100\.00       99\.94
&nbsp;    Dw 100\.00       99\.94
&nbsp;  COND 100\.00       99\.96
&nbsp;   IND 100\.00       99\.12

COND\_m 100\.00      102\.48
 IND\_m 100\.00       97\.34

 Ir\_m1 100\.00       99\.79
 Dr\_m1 100\.00      103\.28
 Dw\_m1 100\.00      100\.00

 Ir\_mm 100\.00      100\.00
 Dr\_mm 100\.00      100\.00
 Dw\_mm 100\.00      100\.00

\*\* when run as non root \*\* this is where the improvement can be noticed

\./perl \-Ilib Porting/bench\.pl \-\-benchfile=/tmp/bench\-getpw \.\./perl2/perl=blead \./perl=blead\+patch
Key&#8203;:
&nbsp;    Ir   Instruction read
&nbsp;    Dr   Data read
&nbsp;    Dw   Data write
&nbsp;    COND conditional branches
&nbsp;    IND  indirect branches
&nbsp;    \_m   branch predict miss
&nbsp;    \_m1  level 1 cache miss
&nbsp;    \_mm  last cache \(e\.g\. L3\) miss
&nbsp;    \-    indeterminate percentage \(e\.g\. 1/0\)

The numbers represent relative counts per loop iteration\, compared to
blead at 100\.0%\.
Higher is better&#8203;: for example\, using half as many instructions gives 200%\,
while using twice as many gives 50%\.

getpwuid
getpwuid

&nbsp;        blead blead\+patch
&nbsp;       \-\-\-\-\-\- \-\-\-\-\-\-\-\-\-\-\-
&nbsp;    Ir 100\.00      137\.64
&nbsp;    Dr 100\.00      130\.24
&nbsp;    Dw 100\.00      146\.70
&nbsp;  COND 100\.00      137\.26
&nbsp;   IND 100\.00      117\.57

COND\_m 100\.00      211\.55
 IND\_m 100\.00      117\.24

 Ir\_m1 100\.00     1200\.00
 Dr\_m1 100\.00      100\.00
 Dw\_m1 100\.00      100\.00

 Ir\_mm 100\.00      100\.00
 Dr\_mm 100\.00      100\.00
 Dw\_mm 100\.00      100\.00

getpwent
getpwent

&nbsp;        blead blead\+patch
&nbsp;       \-\-\-\-\-\- \-\-\-\-\-\-\-\-\-\-\-
&nbsp;    Ir 100\.00      117\.19
&nbsp;    Dr 100\.00      117\.45
&nbsp;    Dw 100\.00      122\.08
&nbsp;  COND 100\.00      116\.20
&nbsp;   IND 100\.00      115\.85

COND\_m 100\.00      123\.67
 IND\_m 100\.00      114\.08

 Ir\_m1 100\.00      717\.86
 Dr\_m1 100\.00      130\.00
 Dw\_m1 100\.00       33\.33

 Ir\_mm 100\.00           \-
 Dr\_mm 100\.00      100\.00
 Dw\_mm 100\.00      100\.00

getpwnam
getpwnam\(root\)

&nbsp;        blead blead\+patch
&nbsp;       \-\-\-\-\-\- \-\-\-\-\-\-\-\-\-\-\-
&nbsp;    Ir 100\.00      137\.34
&nbsp;    Dr 100\.00      129\.98
&nbsp;    Dw 100\.00      146\.59
&nbsp;  COND 100\.00      136\.53
&nbsp;   IND 100\.00      117\.57

COND\_m 100\.00      211\.11
 IND\_m 100\.00      117\.24

 Ir\_m1 100\.00     1040\.00
 Dr\_m1 100\.00      100\.00
 Dw\_m1 100\.00      100\.00

 Ir\_mm 100\.00      100\.00
 Dr\_mm 100\.00      100\.00
 Dw\_mm 100\.00      100\.00

AVERAGE

&nbsp;        blead blead\+patch
&nbsp;       \-\-\-\-\-\- \-\-\-\-\-\-\-\-\-\-\-
&nbsp;    Ir 100\.00      129\.99
&nbsp;    Dr 100\.00      125\.60
&nbsp;    Dw 100\.00      137\.43
&nbsp;  COND 100\.00      129\.22
&nbsp;   IND 100\.00      116\.99

COND\_m 100\.00      170\.94
 IND\_m 100\.00      116\.17

 Ir\_m1 100\.00      941\.06
 Dr\_m1 100\.00      108\.33
 Dw\_m1 100\.00       60\.00

 Ir\_mm 100\.00      100\.00
 Dr\_mm 100\.00      100\.00
 Dw\_mm 100\.00      100\.00


On Tue\, 17 Jul 2018 12&#8203;:02&#8203;:43 \-0700\, atoomic wrote&#8203;:
> Here's the suggested patch attached to the message
> 
> On Tue\, 17 Jul 2018 11&#8203;:05&#8203;:25 \-0700\, atoomic@&#8203;cpan\.org wrote&#8203;:
> > This is a bug report for perl from atoomic@&#8203;cpan\.org\,
> > generated with the help of perlbug 1\.40 running under perl 5\.26\.2\.
> >
> >
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > \[Please describe your issue here\]
> >
> > The perl implementation of getpw\* \(pp\_gpwent\) does a calls to both
> > the
> > normal getpw\*\(\) functions and getspnam\(\)\. When EUID \!=0\, the shadow
> > file
> > will be unreadable\, so this second getspnam\(\) call is just wasted
> > effort\.
> > The comments in pp\_gpwent acknowledge this fact\, but make the call
> > anyway
> > to handle platforms where the EUID is meaningless\.
> >
> > Here is an attempt to avoid this extra check on some "known
> > platforms”
> >
> > https://github.com/atoomic/perl5/pull/6
> >
> > I'm not sure if \_\_linux\_\_ is the best preprocessor check here\. Is it
> > too
> > wide? Can we assume all linux platform will behave the same? Should
> > not we
> > also add \_\_APPLE\_\_ ?
> >
> > I will attach the patch and some benchmark metrics in a future reply
> > to
> > this thread
> >
> > \[Please do not change anything below this line\]
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > \-\-\-
> > Flags&#8203;:
> >     category=core
> >     severity=low
> > \-\-\-
> > Site configuration information for perl 5\.26\.2&#8203;:
> >
> > Configured by nicolas at Fri Apr 20 11&#8203;:44&#8203;:33 CEST 2018\.
> >
> > Summary of my perl5 \(revision 5 version 26 subversion 2\)
> > configuration&#8203;:
> >   Commit id&#8203;: c5b1997939178730653db9e80f90cd53d722fe8d
> >   Platform&#8203;:
> >     osname=darwin
> >     osvers=17\.5\.0
> >     archname=darwin\-2level
> >     uname='darwin macnico\.local 17\.5\.0 darwin kernel version 17\.5\.0&#8203;:
> > mon
> > mar 5 22&#8203;:24&#8203;:32 pst 2018; root&#8203;:xnu\-4570\.51\.1~1release\_x86\_64 x86\_64 '
> >     config\_args='\-Dcc=ccache gcc \-Dusedevel \-Doptimize=\-g3 \-des'
> >     hint=recommended
> >     useposix=true
> >     d\_sigaction=define
> >     useithreads=undef
> >     usemultiplicity=undef
> >     use64bitint=define
> >     use64bitall=define
> >     uselongdouble=undef
> >     usemymalloc=n
> >     default\_inc\_excludes\_dot=define
> >     bincompat5005=undef
> >   Compiler&#8203;:
> >     cc='ccache gcc'
> >     ccflags ='\-fno\-common \-DPERL\_DARWIN \-no\-cpp\-precomp
> > \-mmacosx\-version\-min=10\.13 \-fno\-strict\-aliasing \-pipe
> > \-fstack\-protector\-strong \-I/usr/local/include \-DPERL\_USE\_SAFE\_PUTENV'
> >     optimize='\-g3'
> >     cppflags='\-no\-cpp\-precomp \-fno\-common \-DPERL\_DARWIN \-no\-cpp\-
> > precomp
> > \-mmacosx\-version\-min=10\.13 \-fno\-strict\-aliasing \-pipe
> > \-fstack\-protector\-strong \-I/usr/local/include'
> >     ccversion=''
> >     gccversion='4\.2\.1 Compatible Apple LLVM 9\.1\.0 \(clang\-902\.0\.39\.1\)'
> >     gccosandvers=''
> >     intsize=4
> >     longsize=8
> >     ptrsize=8
> >     doublesize=8
> >     byteorder=12345678
> >     doublekind=3
> >     d\_longlong=define
> >     longlongsize=8
> >     d\_longdbl=define
> >     longdblsize=16
> >     longdblkind=3
> >     ivtype='long'
> >     ivsize=8
> >     nvtype='double'
> >     nvsize=8
> >     Off\_t='off\_t'
> >     lseeksize=8
> >     alignbytes=8
> >     prototype=define
> >   Linker and Libraries&#8203;:
> >     ld='ccache gcc'
> >     ldflags =' \-mmacosx\-version\-min=10\.13 \-fstack\-protector\-strong
> > \-L/usr/local/lib'
> >     libpth=/usr/local/lib
> > /Applications/Xcode\.app/Contents/Developer/Toolchains/XcodeDefault\.xctoolchain/usr/lib/clang/9\.1\.0/lib
> > /Applications/Xcode\.app/Contents/Developer/Toolchains/XcodeDefault\.xctoolchain/usr/lib
> > /Applications/Xcode\.app/Contents/Developer/Platforms/MacOSX\.platform/Developer/SDKs/MacOSX10\.13\.sdk/usr/lib
> > /usr/lib
> >     libs=\-lpthread \-lgdbm \-ldbm \-ldl \-lm \-lutil \-lc
> >     perllibs=\-lpthread \-ldl \-lm \-lutil \-lc
> >     libc=
> >     so=dylib
> >     useshrplib=false
> >     libperl=libperl\.a
> >     gnulibc\_version=''
> >   Dynamic Linking&#8203;:
> >     dlsrc=dl\_dlopen\.xs
> >     dlext=bundle
> >     d\_dlsymun=undef
> >     ccdlflags=' '
> >     cccdlflags=' '
> >     lddlflags=' \-mmacosx\-version\-min=10\.13 \-bundle \-undefined
> > dynamic\_lookup \-L/usr/local/lib \-fstack\-protector\-strong'
> >
> >
> > \-\-\-
> > @&#8203;INC for perl 5\.26\.2&#8203;:
> >     lib
> >     \.
> >     /Users/nicolas/\.dotfiles/perl\-must\-have/lib
> >     /Users/nicolas/perl5/lib/perl5/
> >     /usr/local/lib/perl5/site\_perl/5\.26\.2/darwin\-2level
> >     /usr/local/lib/perl5/site\_perl/5\.26\.2
> >     /usr/local/lib/perl5/5\.26\.2/darwin\-2level
> >     /usr/local/lib/perl5/5\.26\.2
> >
> > \-\-\-
> > Environment for perl 5\.26\.2&#8203;:
> >     DYLD\_LIBRARY\_PATH \(unset\)
> >     HOME=/Users/nicolas
> >     LANG=en\_US\.UTF\-8
> >     LANGUAGE \(unset\)
> >     LC\_CTYPE=en\_US\.UTF\-8
> >     LD\_LIBRARY\_PATH \(unset\)
> >     LOGDIR \(unset\)
> >
> > PATH=/Users/nicolas/perl5/perlbrew/bin&#8203;:/Users/nicolas/perl5/perlbrew/perls/perl\-
> > 5\.26\.1/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/sbin&#8203;:/sbin&#8203;:/usr/local/MacGPG2/bin&#8203;:/opt/X11/bin&#8203;:/usr/local/git/bin&#8203;:/Users/nicolas/\.dotfiles/bin&#8203;:/Users/nicolas/perl5/bin&#8203;:/Applications/Rakudo/bin&#8203;:/Applications/Rakudo/share/perl6/site/bin
> >     PERL5DB=use Devel&#8203;::NYTProf
> >
> > PERL5LIB=/Users/nicolas/\.dotfiles/perl\-must\-
> > have/lib&#8203;:/Users/nicolas/perl5/lib/perl5/
> >     PERLBREW\_HOME=/Users/nicolas/\.perlbrew
> >     PERLBREW\_MANPATH=/Users/nicolas/perl5/perlbrew/perls/perl\-
> > 5\.26\.1/man
> >
> > PERLBREW\_PATH=/Users/nicolas/perl5/perlbrew/bin&#8203;:/Users/nicolas/perl5/perlbrew/perls/perl\-
> > 5\.26\.1/bin
> >     PERLBREW\_PERL=perl\-5\.26\.1
> >     PERLBREW\_ROOT=/Users/nicolas/perl5/perlbrew
> >     PERLBREW\_SHELLRC\_VERSION=0\.82
> >     PERLBREW\_VERSION=0\.82
> >     PERL\_BADLANG \(unset\)
> >     PERL\_CPANM\_OPT=\-\-quiet
> >     SHELL=/bin/zsh

**Comment by p5pRT** [comment]
### From @atoomic

[bench-getpw](https://rt-archive.perl.org/perl5/Ticket/Attachment/1568442/825109/bench-getpw)

**Comment by p5pRT** [comment]
### From @iabyn

On Tue\, Jul 17\, 2018 at 11&#8203;:05&#8203;:25AM \-0700\, Nicolas R\. \(via RT\) wrote&#8203;:
> The perl implementation of getpw\* \(pp\_gpwent\) does a calls to both the
> normal getpw\*\(\) functions and getspnam\(\)\. When EUID \!=0\, the shadow file
> will be unreadable\, so this second getspnam\(\) call is just wasted effort\.
> The comments in pp\_gpwent acknowledge this fact\, but make the call anyway
> to handle platforms where the EUID is meaningless\.
> 
> Here is an attempt to avoid this extra check on some "known platforms”

Is this really a performance critical function? I'd be reluctant to add
extra complexity and platform\-specific hard coding to an already complex
function?

\-\- 
My get\-up\-and\-go just got up and went\.

**Comment by toddr** [comment]
Suggested pull request is at https://github.com/Perl/perl5/pull/16

**Comment by Leont** [comment]
> Is this really a performance critical function? I'd be reluctant to add
extra complexity and platform-specific hard coding to an already complex
function?

Agreed. Also, I'm not so sure the logic is correct, or that it's easy to get it correct (e.g. correct may change over time)

**Comment by khwilliamson** [comment]
Can we close this?

**Comment by jkeenan** [comment]
> Can we close this?

The [associated pull request](https://github.com/Perl/perl5/pull/16) was closed (withdrawn) on Oct 31 2019.  So, yes, this is closable; doing so now.
