### ISSUE TITLE
perlvar.pod incorrect link

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16652]
Migrated from [rt.perl.org#133432](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133432) (status was 'open')

Searchable as RT133432$

**Comment by p5pRT** [comment]
### From @grinnz

The link in the @&#8203;\{^CAPTURE\} section to $\<digits> is not correct\. It's
currently L\</$I\<digits>> which ends up linking to $digits \(which doesn't
exist\)\. The correct link would currently be&#8203;:

L\<\<\< /$\<I\<digits>> \($1\, $2\, \.\.\.\) >>>

**Comment by p5pRT** [comment]
### From @jkeenan

On Wed\, 08 Aug 2018 20&#8203;:58&#8203;:44 GMT\, grinnz@&#8203;gmail\.com wrote&#8203;:
> The link in the @&#8203;\{^CAPTURE\} section to $\<digits> is not correct\. It's
> currently L\</$I\<digits>> which ends up linking to $digits \(which doesn't
> exist\)\. The correct link would currently be&#8203;:
> 
> L\<\<\< /$\<I\<digits>> \($1\, $2\, \.\.\.\) >>>

I tried out your suggestion in this branch&#8203;:

jkeenan/dbook/133440\-perlvar

I ran the revised file through pod2html\.  When I clicked on the resulting hyperlink\, it did not jump to the intended location\.

\(I tried out a couple of other things\, which created a jumpable link but failed to pass t/porting/podcheck\.t\.\)

Suggestions?

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @grinnz

On Sun\, Aug 12\, 2018 at 11&#8203;:23 AM James E Keenan via RT \<
perlbug\-followup@&#8203;perl\.org> wrote&#8203;:

> On Wed\, 08 Aug 2018 20&#8203;:58&#8203;:44 GMT\, grinnz@&#8203;gmail\.com wrote&#8203;:
> > The link in the @&#8203;\{^CAPTURE\} section to $\<digits> is not correct\. It's
> > currently L\</$I\<digits>> which ends up linking to $digits \(which doesn't
> > exist\)\. The correct link would currently be&#8203;:
> >
> > L\<\<\< /$\<I\<digits>> \($1\, $2\, \.\.\.\) >>>
>
> I tried out your suggestion in this branch&#8203;:
>
> jkeenan/dbook/133440\-perlvar
>
> I ran the revised file through pod2html\.  When I clicked on the resulting
> hyperlink\, it did not jump to the intended location\.
>
> \(I tried out a couple of other things\, which created a jumpable link but
> failed to pass t/porting/podcheck\.t\.\)
>
> Suggestions?
>

I think this is a bug in Pod&#8203;::Simple&#8203;::HTML\, I don't know if there is a way
to generate a link to that anchor\. In Pod&#8203;::Simple&#8203;::XHTML\, which is used by
most websites rendering perldocs now\, the mentioned link tag works\.

perl \-MPod&#8203;::Simple&#8203;::XHTML \-E'my $parser = Pod&#8203;::Simple&#8203;::XHTML\->new;
$parser\->anchor\_items\(1\); $parser\->parse\_string\_document\("=pod\\n\\nL\<\<\<
/\\$\<I\<digits>> \(\\$1\, \\$2\, \.\.\.\) >>>\\n\\n=over\\n\\n=item \\$\<I\<digits>> \(\\$1\,
\\$2\, \.\.\.\) >>>\\n\\n=back"\)'

\-Dan

**Comment by p5pRT** [comment]
### From @grinnz

On Sun\, Aug 12\, 2018 at 11&#8203;:23 AM James E Keenan via RT \<
perlbug\-followup@&#8203;perl\.org> wrote&#8203;:

> On Wed\, 08 Aug 2018 20&#8203;:58&#8203;:44 GMT\, grinnz@&#8203;gmail\.com wrote&#8203;:
> > The link in the @&#8203;\{^CAPTURE\} section to $\<digits> is not correct\. It's
> > currently L\</$I\<digits>> which ends up linking to $digits \(which doesn't
> > exist\)\. The correct link would currently be&#8203;:
> >
> > L\<\<\< /$\<I\<digits>> \($1\, $2\, \.\.\.\) >>>
>
> I tried out your suggestion in this branch&#8203;:
>
> jkeenan/dbook/133440\-perlvar
>
> I ran the revised file through pod2html\.  When I clicked on the resulting
> hyperlink\, it did not jump to the intended location\.
>
> \(I tried out a couple of other things\, which created a jumpable link but
> failed to pass t/porting/podcheck\.t\.\)
>
> Suggestions?
>

I think this is a bug in Pod&#8203;::Simple&#8203;::HTML\, I don't know if there is a way
to generate a link to that anchor\. In Pod&#8203;::Simple&#8203;::XHTML\, which is used by
most websites rendering perldocs now\, the mentioned link tag works\.

perl \-MPod&#8203;::Simple&#8203;::XHTML \-E'my $parser = Pod&#8203;::Simple&#8203;::XHTML\->new;
$parser\->anchor\_items\(1\); $parser\->parse\_string\_document\("=pod\\n\\nL\<\<\<
/\\$\<I\<digits>> \(\\$1\, \\$2\, \.\.\.\) >>>\\n\\n=over\\n\\n=item \\$\<I\<digits>> \(\\$1\,
\\$2\, \.\.\.\) >>>\\n\\n=back"\)'

\-Dan

**Comment by khwilliamson** [comment]
The link was, apparently without noticing this ticket, changed to what @Grinnz  suggested, and it passed podcheck.

If there is a Pod::Simple bug, a ticket should be opened in its queue
