### ISSUE TITLE
no assignment to "my" variable

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16655]
Migrated from [rt.perl.org#133441](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133441) (status was 'open')

Searchable as RT133441$

**Comment by p5pRT** [comment]
### From wolf-dietrich_moeller@t-online.de

The following error is a regression in Perl 5.28.
No assignment to the "my" variable $m, but correct
assignment to $t.

```perl
my $m = 'TEST_my';
$t = 'TEST___';
$k = 'k';
($m = '??'.$k) .= ' m';
($t = '??'.$k) .= ' t';
print $m,"\n",$t,"\n";
```

### output for Perl 5.26.2.1 (correct)
```
??k m
??k t
```

### output for Perl 5.28.0.1 (no assignment in line 4 to $m)
```
TEST_my
??k t
```

<details><summary>Perl Info</summary>

```
-----------------------------------------------------------------
---
Flags:
category=core
severity=medium
---
Site configuration information for perl 5.28.0:

Configured by strawberry-perl at Sat Jun 23 11:55:17 2018.

Summary of my perl5 (revision 5 version 28 subversion 0) configuration:

Platform:
osname=MSWin32
osvers=10.0.17134.112
archname=MSWin32-x86-multi-thread-64int
uname='Win32 strawberry-perl 5.28.0.1 #1 Sat Jun 23 11:54:23 2018 i386'
config_args='undef'
hint=recommended
useposix=true
d_sigaction=undef
useithreads=define
usemultiplicity=define
use64bitint=define
use64bitall=undef
uselongdouble=undef
usemymalloc=n
default_inc_excludes_dot=define
bincompat5005=undef
Compiler:
cc='gcc'
ccflags =' -s -O2 -DWIN32 -D__USE_MINGW_ANSI_STDIO
-DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS
-DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields'
optimize='-s -O2'
cppflags='-DWIN32'
ccversion=''
gccversion='7.1.0'
gccosandvers=''
intsize=4
longsize=4
ptrsize=4
doublesize=8
byteorder=12345678
doublekind=3
d_longlong=define
longlongsize=8
d_longdbl=define
longdblsize=12
longdblkind=3
ivtype='long long'
ivsize=8
nvtype='double'
nvsize=8
Off_t='long long'
lseeksize=8
alignbytes=8
prototype=define
Linker and Libraries:
ld='g++'
ldflags ='-s -L"C:\Perl\perl\lib\CORE" -L"C:\Perl\c\lib"'
libpth=C:\Perl\c\lib C:\Perl\c\i686-w64-mingw32\lib
C:\Perl\c\lib\gcc\i686-w64-mingw32\7.1.0
libs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32
-ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr
-lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32
-ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr
-lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
libc=
so=dll
useshrplib=true
libperl=libperl528.a
gnulibc_version=''
Dynamic Linking:
dlsrc=dl_win32.xs
dlext=xs.dll
d_dlsymun=undef
ccdlflags=' '
cccdlflags=' '
lddlflags='-mdll -s -L"C:\Perl\perl\lib\CORE" -L"C:\Perl\c\lib"'


---
@INC for perl 5.28.0:
C:/Perl/perl/site/lib
C:/Perl/perl/vendor/lib
C:/Perl/perl/lib

---
Environment for perl 5.28.0:
HOME (unset)
LANG (unset)
LANGUAGE (unset)
LD_LIBRARY_PATH (unset)
LOGDIR (unset)
PATH=C:\Perl\c\bin;C:\Perl\perl\site\bin;C:\Perl\perl\bin ## some
entries deleted
PERL_BADLANG (unset)
SHELL (unset)
```
</details>

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, Aug 11\, 2018 at 01&#8203;:11&#8203;:15PM \-0700\, Wolf\-Dietrich Moeller \(via RT\) wrote&#8203;:
> \#\#\# test program \#\#\#
> my $m = 'TEST\_my';
> $t = 'TEST\_\_\_';
> $k = 'k';
> \($m = '??'\.$k\) \.= ' m';
> \($t = '??'\.$k\) \.= ' t';
> print $m\,"\\n"\,$t\,"\\n";
> \#\#\# end test program
> 
> \#\#\# output for Perl 5\.26\.2\.1 \(correct\)
> ??k m
> ??k t
> \#\#\# end
> 
> \#\#\# output for Perl 5\.28\.0\.1 \(no assignment in line 4 to $m\)
> TEST\_my
> ??k t
> \#\#\# end

The optimiser is misinterpreting the optree in the \($m = '??'\.$k\) \.= ' m'
case\. I'll look into it further on monday

\-\- 
O Unicef Clearasil\!
Gibberish and Drivel\!
&nbsp;    \-\- "Bored of the Rings"

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Sat\, Aug 11\, 2018 at 11&#8203;:03&#8203;:34PM \+0100\, Dave Mitchell wrote&#8203;:
> On Sat\, Aug 11\, 2018 at 01&#8203;:11&#8203;:15PM \-0700\, Wolf\-Dietrich Moeller \(via RT\) wrote&#8203;:
> > \#\#\# test program \#\#\#
> > my $m = 'TEST\_my';
> > $t = 'TEST\_\_\_';
> > $k = 'k';
> > \($m = '??'\.$k\) \.= ' m';
> > \($t = '??'\.$k\) \.= ' t';
> > print $m\,"\\n"\,$t\,"\\n";
> > \#\#\# end test program
> > 
> > \#\#\# output for Perl 5\.26\.2\.1 \(correct\)
> > ??k m
> > ??k t
> > \#\#\# end
> > 
> > \#\#\# output for Perl 5\.28\.0\.1 \(no assignment in line 4 to $m\)
> > TEST\_my
> > ??k t
> > \#\#\# end
> 
> The optimiser is misinterpreting the optree in the \($m = '??'\.$k\) \.= ' m'
> case\. I'll look into it further on monday

Now fixe din blead with the following commit\. This is suitable for
backporting to 5\.28\.x\.


commit 0fe04e1dc741a43190e79a985fb0cec0493ebfe9
Author&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
AuthorDate&#8203;: Wed Aug 29 14&#8203;:32&#8203;:24 2018 \+0100
Commit&#8203;:     David Mitchell \<davem@&#8203;iabyn\.com>
CommitDate&#8203;: Wed Aug 29 14&#8203;:32&#8203;:24 2018 \+0100

&nbsp;    multiconcat&#8203;: mutator not seen in \(lex = \.\.\.\) \.= \.\.\.
&nbsp;    
&nbsp;    RT \#133441
&nbsp;    
&nbsp;    TL;DR&#8203;:
&nbsp;    \(\($lex = expr1\.expr2\) \.= expr3\) was being misinterpreted as
&nbsp;    \(expr1 \. expr2 \. expr3\) when the \($lex = expr1\) subtree had had the
&nbsp;    assign op optimised away by the OPpTARGET\_MY optimisation\.
&nbsp;    
&nbsp;    Full details\.
&nbsp;    
&nbsp;    S\_maybe\_multiconcat\(\) looks for suitable chains of OP\_CONCAT to convert
&nbsp;    into a single OP\_MULTICONCAT\.
&nbsp;    
&nbsp;    Part of the code needs to distinguish between \(expr \. expr\) and
&nbsp;    \(expr \.= expr\)\. This didn't used to be easy\, as both are just OP\_CONCAT
&nbsp;    ops\, but with the OPf\_STACKED set on the second one\. But\.\.\.
&nbsp;    
&nbsp;    perl also used to optimise \($a \. $b \. $c\) into \($a \. $b\) \.= $c\, to
&nbsp;    reuse the padtmp returned by the $a\.$b concat\. This meant that an
&nbsp;    OP\_CONCAT could have the OPf\_STACKED flag on even when it was a '\.'
&nbsp;    rather than a '\.='\.
&nbsp;    
&nbsp;    I disambiguated these cases by seeing whether the top op in the LHS
&nbsp;    expression had the OPf\_MOD flag set too \- if so\, it implies '\.='\.
&nbsp;    
&nbsp;    This fails in the specific case where the LHS expression is a
&nbsp;    sub\-expression which is assigned to a lexical variable\, e\.g\.
&nbsp;    
&nbsp;        \($lex = $a\+$b\) \.= $c\.
&nbsp;    
&nbsp;    Initially the top node in the LHS expression above is OP\_SASSIGN\, with
&nbsp;    OPf\_MOD set due to the enclosing '\.='\. Then the OPpTARGET\_MY
&nbsp;    optimisation kicks in\, and the \($lex = $a \+ $b\) part of the optree is
&nbsp;    converted from
&nbsp;    
&nbsp;        sassign sKPRMS
&nbsp;            add\[t4\] sK
&nbsp;                padsv\[a$\] s
&nbsp;                padsv\[$b\] s
&nbsp;            padsv\[$lex\] s
&nbsp;    
&nbsp;    to
&nbsp;            add\[$lex\] sK/TARGMY
&nbsp;                padsv\[a$\] s
&nbsp;                padsv\[$b\] s
&nbsp;    
&nbsp;    which is all fine and dandy\, except that the top node of that optree no
&nbsp;    longer has the OPf\_MOD flag set\, which trips up S\_maybe\_multiconcat into
&nbsp;    no longer spotting that the outer concat is a '\.=' rather than a '\.'\.
&nbsp;    
&nbsp;    Whether the OPpTARGET\_MY optimising code should copy the OPf\_MOD from
&nbsp;    the being\-removed sassign op to its successor is an issue I won't
&nbsp;    address here\. But in the meantime\, the good news is that for 5\.28\.0
&nbsp;    I added the OPpCONCAT\_NESTED private flag\, which is set whenever
&nbsp;    \($a \. $b \. $c\) is optimised into \($a \. $b\) \.= $c\. This means that it's
&nbsp;    no longer necessary to inspect the OPf\_MOD flag of the first child to
&nbsp;    disambiguate the two cases\. So the fix is trivial\.


\-\- 
Little fly\, thy summer's play my thoughtless hand
has terminated with extreme prejudice\.
&nbsp;        \(with apologies to William Blake\)

**Comment by toddr** [comment]
This is fixed in 5.30. @jkeenan do we need to label this before closing it?

**Comment by jkeenan** [comment]
> This is fixed in 5.30. @jkeenan do we need to label this before closing it?

I'm not sure what label you would want to apply?  Can you clarify?

**Comment by toddr** [comment]
I was thinking we need to label it with a mile stone or something so we know where it was fixed?

**Comment by jkeenan** [comment]
On 1/31/20 11:29 AM, Todd Rinaldo wrote:
> I was thinking we need to label it with a mile stone or something so we 
> know where it was fixed?
> 

Perhaps we should do that going forward, but it hasn't been SOP so far 
and I don't recall us being insistent on (or consistent at) that sort of 
thing when we were in RT.
