### ISSUE TITLE
more comprehensive documentation of bug submission processes needed

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16662]
Migrated from [rt.perl.org#133461](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133461) (status was 'open')

Searchable as RT133461$

**Comment by p5pRT** [comment]
### From @wchristian

Operating under a tuit shortness but want this to be retained&#8203;:

Right now the process of submitting bugs/patches is not documented well and has a very high barrier of entry\. By adding some documentation to the perl repo this might be improved at least\.

Details in attached IRC log\.

\-\- 
With regards\,
Christian Walde

**Comment by p5pRT** [comment]
### From @wchristian

\[2018\-08\-21 16&#8203;:31&#8203;:38\] \<Mithaldu\_> can we propose branches via github yet or do i need to learn how to do git patches on windows again
\[2018\-08\-21 16&#8203;:31&#8203;:46\] \<khw> The windows vm attached to dromedary doesn't appear to have either gmake nor dmake\.  It appears to be Microsoft Visual Studio 10\.0\.  Did these come along later?
\[2018\-08\-21 16&#8203;:31&#8203;:58\] \<ilmari> khw&#8203;: it has nmake\, afaik
\[2018\-08\-21 16&#8203;:32&#8203;:06\] \<alh> You can hand a link to the patch in your email\, I think we'll be reasonable about it
\[2018\-08\-21 16&#8203;:32&#8203;:09\] \<Mithaldu\_> gmake is relatively new to the toolchain
\[2018\-08\-21 16&#8203;:32&#8203;:18\] \<Mithaldu\_> alh&#8203;: woop
\[2018\-08\-21 16&#8203;:32&#8203;:41\] \<ilmari> 'git format\-patch blead' doesn't work on windows?
\[2018\-08\-21 16&#8203;:32&#8203;:46\] → Hinrik joined \(hinrik@&#8203;u\.nix\.is\)
\[2018\-08\-21 16&#8203;:32&#8203;:47\] → atomicstak joined \(matt@&#8203;u\.nix\.is\)
\[2018\-08\-21 16&#8203;:32&#8203;:54\] \<khw> It does have nmake\, but that doesn't do parallel compiling/testing\, so is slow
\[2018\-08\-21 16&#8203;:33&#8203;:25\] \<Mithaldu\_> https://github.com/Perl/perl5/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc \# cute
\[2018\-08\-21 16&#8203;:33&#8203;:27\] \<alh> Mithaldu\_&#8203;: Oh\, if you open a pull request\, you can append '\.diff' to the end of it '/pull/32\.diff' and you'll get a unified patch
\[2018\-08\-21 16&#8203;:34&#8203;:41\] \<Mithaldu\_> alh&#8203;: useful
\[2018\-08\-21 16&#8203;:35&#8203;:14\] \<khw> should these hints be documented somewhere?
\[2018\-08\-21 16&#8203;:35&#8203;:34\] \<Mithaldu\_> ilmari&#8203;: i don't know\, and i'd prefer not to spend time on learning the details of that if i can avoid it\, but heck\, now i'm also remembering i can't send perlbugs with a web interface so i need to figure out again how to make emails for that
\[2018\-08\-21 16&#8203;:35&#8203;:49\] \<alh> Can you run perlbug?
\[2018\-08\-21 16&#8203;:36&#8203;:01\] \<Mithaldu\_> yeah but i don't have sendmail
\[2018\-08\-21 16&#8203;:36&#8203;:09\] \<Mithaldu\_> last i remember i had to have it make a file
\[2018\-08\-21 16&#8203;:36&#8203;:09\] \<alh> So\, it's awful
\[2018\-08\-21 16&#8203;:36&#8203;:13\] \<alh> But I usually run it and have it make a file
\[2018\-08\-21 16&#8203;:36&#8203;:15\] \<alh> And then copy
\[2018\-08\-21 16&#8203;:36&#8203;:18\] \<Mithaldu\_> and then i copied the file to my email client
\[2018\-08\-21 16&#8203;:36&#8203;:20\] \<alh> Yup
\[2018\-08\-21 16&#8203;:36&#8203;:27\] \<Mithaldu\_> which is very dumb
\[2018\-08\-21 16&#8203;:36&#8203;:28\] \<xenu> Mithaldu\_&#8203;: you can just send email to perlbug@&#8203;perl\.org\, you \*don't\* have to use that stupid template
\[2018\-08\-21 16&#8203;:36&#8203;:30\] \<khw> I've gotten used to it
\[2018\-08\-21 16&#8203;:36&#8203;:34\] \<xenu> you just have to make sure that your email contains word 'perl'
\[2018\-08\-21 16&#8203;:36&#8203;:38\] \<xenu> otherwise it will be discarded
\[2018\-08\-21 16&#8203;:36&#8203;:38\] \<Mithaldu\_> xenu&#8203;: oh
\[2018\-08\-21 16&#8203;:36&#8203;:40\] \<Mithaldu\_> neat
\[2018\-08\-21 16&#8203;:37&#8203;:46\] → Bucciarati joined \(buccia@&#8203;u\.nix\.is\)
\[2018\-08\-21 16&#8203;:38&#8203;:06\] \<Mithaldu\_> khw&#8203;: perlhack documents some of it\, but also assumes perlbug works entirely
\[2018\-08\-21 16&#8203;:38&#8203;:06\] \<xenu> also i'm not sure if attachements are allowed\, so just to be safe\, if you want to attach something\, attach it in a reply to your ticket
\[2018\-08\-21 16&#8203;:38&#8203;:19\] \<Mithaldu\_> also perlhack is kind of hidden deep in the pod bowels
\[2018\-08\-21 16&#8203;:38&#8203;:24\] \<alh> They are
\[2018\-08\-21 16&#8203;:38&#8203;:34\] \<xenu> iirc bulk88 had problems with that
\[2018\-08\-21 16&#8203;:38&#8203;:47\] \<Mithaldu\_> a README\.contributing or similar would be nice
\[2018\-08\-21 16&#8203;:39&#8203;:00\] \<Mithaldu\_> also\, fun fact\, all i want right now is to propose a doc fix
\[2018\-08\-21 16&#8203;:39&#8203;:09\] \<Mithaldu\_> so yay\, high barrier of entry
\[2018\-08\-21 16&#8203;:39&#8203;:25\] \<alh> You could try the "Send a bare email to perlbug with a patch attachment"
\[2018\-08\-21 16&#8203;:39&#8203;:27\] \<alh> And if that works great\!
\[2018\-08\-21 16&#8203;:39&#8203;:40\] \<Mithaldu\_> right
\[2018\-08\-21 16&#8203;:39&#8203;:44\] \<alh> If it's a simple "this word or sentence is wrong" you can probably mention it here and someone may fix it
\[2018\-08\-21 16&#8203;:39&#8203;:48\] \<alh> But yeah\, I hear you
\[2018\-08\-21 16&#8203;:39&#8203;:49\] \<xenu> Mithaldu\_&#8203;: there are other problems like perlbug@&#8203;perl\.org not working at all for some people
\[2018\-08\-21 16&#8203;:40&#8203;:02\] \<xenu> our bug reporting system is \*insane\*
\[2018\-08\-21 16&#8203;:40&#8203;:22\] \<xenu> and i'm surprised that we get bug reports from non\-p5p people at all
\[2018\-08\-21 16&#8203;:40&#8203;:26\] \<Mithaldu\_> the bug is more\, as khw mentions&#8203;: all of this should be documented\, and the docs for it easy to find\, even if it's just a file saying "look at pod/perlhacks\.pod"
\[2018\-08\-21 16&#8203;:40&#8203;:54\] \<Mithaldu\_> and maybe not do this&#8203;: https://github.com/Perl/perl5/pull/11
\[2018\-08\-21 16&#8203;:41&#8203;:28\] \<alh> You planning on writing the file or opening a bug saying the file should be written?
\[2018\-08\-21 16&#8203;:41&#8203;:29\] \<alh> =x
\[2018\-08\-21 16&#8203;:42&#8203;:00\] \<Mithaldu\_> i'm empted to copy the irc log and dump it into an email? :P
\[2018\-08\-21 16&#8203;:42&#8203;:08\] \<alh> x\.x
\[2018\-08\-21 16&#8203;:42&#8203;:10\] \<alh> It's a start
\[2018\-08\-21 16&#8203;:42&#8203;:13\] \<Mithaldu\_> i have an extreme lack of tuits at the moment
\[2018\-08\-21 16&#8203;:42&#8203;:25\] \<alh> Give me your mailing address I can send you a bunch I got from liz and wendy
\[2018\-08\-21 16&#8203;:42&#8203;:33\] \<Mithaldu\_> haha
\[2018\-08\-21 16&#8203;:42&#8203;:46\] → avar joined \(avar@&#8203;u\.nix\.is\)
\[2018\-08\-21 16&#8203;:42&#8203;:50\] \<Mithaldu\_> all i wanted is to try and not get knowledge lost\, but even keeping the knowledge in itself costs a surprising amount of time
\[2018\-08\-21 16&#8203;:43&#8203;:13\] \<Mithaldu\_> so i guess i'll send two mails to perlbug

**Comment by p5pRT** [comment]
### From @jkeenan

On Tue\, 21 Aug 2018 14&#8203;:48&#8203;:11 GMT\, walde\.christian@&#8203;gmail\.com wrote&#8203;:
> Operating under a tuit shortness but want this to be retained&#8203;:
> 
> Right now the process of submitting bugs/patches is not documented
> well and has a very high barrier of entry\. By adding some
> documentation to the perl repo this might be improved at least\.
> 
> Details in attached IRC log\.

Can you work this into a patch?

Those of us\, including myself\, who read all New submissions to rt\.perl\.org\, will need some persuasion to agree with your claim that the barrier to entry is "very high"\.

So a specific patch would help move the discussion forward\.
 
Thank you very much\.
\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by khwilliamson** [comment]
Is this now fixed by our use of github?

**Comment by jkeenan** [comment]
> Is this now fixed by our use of github?

No specific patch was ever proposed.  And we've certainly had lots of patches (in the form of pull requests) submitted since that conversion took place.  So +1 to closing.

**Comment by wchristian** [comment]
Yeah, Github use fixes this.
