### ISSUE TITLE
Perl: command line switches

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16674]
Migrated from [rt.perl.org#133480](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133480) (status was 'open')

Searchable as RT133480$

**Comment by p5pRT** [comment]
### From c.willis111@btinternet.com

Hi

would it be possible to add a switch \( \-b ?\) so that all files opened \(in particular STDIN and STDOUT\) were binmoded? This would be useful for one liners tweaking PDFs \(inter alia\)\.

regards \- Chris Willis



---
This email has been checked for viruses by Avast antivirus software\.
https://www.avast.com/antivirus

**Comment by p5pRT** [comment]
### From @jkeenan

On Tue\, 28 Aug 2018 11&#8203;:27&#8203;:41 GMT\, c\.willis111@&#8203;btinternet\.com wrote&#8203;:
> Hi
> 
> would it be possible to add a switch \( \-b ?\) so that all files opened
> \(in particular STDIN and STDOUT\) were binmoded? This would be useful
> for one liners tweaking PDFs \(inter alia\)\.
> 
> regards \- Chris Willis
> 

Changes to the perl executable's command\-line switches have profound implications for the maintenance and development of the language\.  Hence\, we approach requests for such changes with great caution\, even skepticism\.

To get a taste of what this might entail\, please call 'perldoc \-f binmode'\.  Adding a command\-line switch to binmode all filehandle opens would entail writing and testing code for everything mentioned in that documentation\.

I could imagine\, however\, that this is something which might be implemented as a CPAN module \-\- or may even exist as such already\.  I would recommend that you post at a location such as perlmonks\.org with specific instances of how you need to "tweak PDFs"\.

Thank you very much\.
Jim Keenan

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @grinnz

On Tue\, Sep 4\, 2018 at 11&#8203;:17 AM James E Keenan via RT \<
perlbug\-followup@&#8203;perl\.org> wrote&#8203;:

> I could imagine\, however\, that this is something which might be
> implemented as a CPAN module \-\- or may even exist as such already\.  I would
> recommend that you post at a location such as perlmonks\.org with specific
> instances of how you need to "tweak PDFs"\.
>

You don't even need a CPAN module; the switch \-Mopen=&#8203;:raw\,&#8203;:std should do it\.

\-Dan

**Comment by jkeenan** [comment]
"The motion fails for lack of a second."

There's been no support for this feature request since it was filed in 2018.  Taking the ticket for the purpose of closing it within 7 days unless someone wants to take the discussion forward.

**Comment by jkeenan** [comment]
> "The motion fails for lack of a second."
> 
> There's been no support for this feature request since it was filed in 2018. Taking the ticket for the purpose of closing it within 7 days unless someone wants to take the discussion forward.

No one has spoken up for keeping this feature request open.  Closing.
