### ISSUE TITLE
perl 5 (v.5.26.1) interpreter crashes on 64-bit Windows

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16673]
Migrated from [rt.perl.org#133477](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133477) (status was 'open')

Searchable as RT133477$

**Comment by p5pRT** [comment]
### From patrickmclot@gmail.com

I am running ActiveState Perl \(v5\.26\.1\) on a 64\-bit Windows 7 installation\.
I checked on perlMonks and it turns out this bug is in Strawberry Perl
64\-bit as well\. It runs fine on 32\-bit Windows and 64\-bit Linux\.  The
file that reproduces the bug is attached as "small"\.

Cheers\,
Patrick

**Comment by p5pRT** [comment]
### From patrickmclot@gmail.com

[small](https://rt-archive.perl.org/perl5/Ticket/Attachment/1577447/826643/small)

**Comment by p5pRT** [comment]
### From @jkeenan

On Sun\, 26 Aug 2018 22&#8203;:34&#8203;:18 GMT\, patrickmclot@&#8203;gmail\.com wrote&#8203;:
> I am running ActiveState Perl \(v5\.26\.1\) on a 64\-bit Windows 7 installation\.
> I checked on perlMonks and it turns out this bug is in Strawberry Perl
> 64\-bit as well\. It runs fine on 32\-bit Windows and 64\-bit Linux\.  The
> file that reproduces the bug is attached as "small"\.
> 
> Cheers\,
> Patrick

Let me see if I correctly understand your sample program \(re\-attached with a \.pl extension\)\.

You open a \(global\) filehandle to read from a file \-\- that file being the program itself\.

For each line read you call a subroutine\, parser\(\)\, which takes the line as input but then does nothing with it\, since all the subroutine does is to print "Hello\, world"\.

If I run it on Linux\, all I get is&#8203;:

\#\#\#\#\#
$ perl 133477\-small\.pl 
"?\) at 133477\-small\.pl line 10\, \<INFILE> line 1\."\#\!perl
\#\#\#\#\#

I confess that I don't understand the point of such a program \-\- but I concede that that doesn't explain why it crashes on Windows \(which I don't have available\)\.

Thank you very much\.
\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @jkeenan

[133477-small.pl](https://rt-archive.perl.org/perl5/Ticket/Attachment/1577465/826649/133477-small.pl)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @sisyphus

The sample program crashes on x64 Strawberry Perl 5\.26\.0\, but on x64 Strawberry Perl 5\.28\.0 it produces output of&#8203;:

Can't locate object method "parser" via package "\#\!perl" \(perhaps you forgot to
load "\#\!perl"?\) at small\.pl line 10\, \<INFILE> line 1\.

I believe that's the expected output \- and therefore I would suggest that this bug has already been fixed\.

Cheers\,
Rob

**Comment by p5pRT** [comment]
### From @xenu

On Sun\, 26 Aug 2018 21&#8203;:31&#8203;:09 \-0700
"sisyphus@&#8203;cpan\.org via RT" \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:

> The sample program crashes on x64 Strawberry Perl 5\.26\.0\, but on x64 Strawberry Perl 5\.28\.0 it produces output of&#8203;:
> 
> Can't locate object method "parser" via package "\#\!perl" \(perhaps you forgot to
> load "\#\!perl"?\) at small\.pl line 10\, \<INFILE> line 1\.
> 
> I believe that's the expected output \- and therefore I would suggest that this bug has already been fixed\.
> 
> Cheers\,
> Rob

The crash was caused by the fact that the name of the filehandle starts
with 'INF'\, change it to anything else\, the code will stop crashing\. 

While the code crashes only on Windows\, it also behaves weirdly on other
platforms\. For example\, the following code executed with perl 5\.26\.2 on 
dragonfly or linux&#8203;:

open INFILE\, '\<'\, \\'foo';
while \(\<INFILE>\) \{
&nbsp;        warn 'bar';
\}

outputs "bar at a\.pl line 3\, \<INFILE> line 0\.000000\."\. Note that the line
number is a float\.

The following commit has fixed those problems&#8203;:



---
commit 559a021f1d52c32a82cbdf9184aa59a58e898b08
Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
Date&#8203;:   Tue May 16 16&#8203;:30&#8203;:13 2017 \+0100

&nbsp;    sprintf&#8203;: handle sized int\-ish formats with Inf/Nan
&nbsp;    
&nbsp;    The code path taken when int\-ish formats saw an Inf/Nan was to jump to the
&nbsp;    floating\-point handler\, but then that would warn about \(valid\) size
&nbsp;    qualifiers\. For example before&#8203;:
&nbsp;    
&nbsp;        $ perl \-we'printf "\[%hi\]\\n"\, Inf'
&nbsp;        Invalid conversion in printf&#8203;: "%hi" at \-e line 1\.
&nbsp;        Redundant argument in printf at \-e line 1\.
&nbsp;        \[%hi\]
&nbsp;        $
&nbsp;    
&nbsp;    After this commit&#8203;:
&nbsp;    
&nbsp;        $ perl \-we'printf "\[%hi\]\\n"\, Inf'
&nbsp;        \[Inf\]
&nbsp;        $
&nbsp;    
&nbsp;    It also makes the code simpler\.


---
However\, the commit message doesn't say anything about crashing or float
line numbers\, which makes me think that the fix was accidental\.

I wonder if the bug was actually fixed or maybe it was just hidden\. 

CC\-ing Dave to get his opinion\.

**Comment by p5pRT** [comment]
### From @xenu

On Sun\, 26 Aug 2018 21&#8203;:31&#8203;:09 \-0700
"sisyphus@&#8203;cpan\.org via RT" \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:

> The sample program crashes on x64 Strawberry Perl 5\.26\.0\, but on x64 Strawberry Perl 5\.28\.0 it produces output of&#8203;:
> 
> Can't locate object method "parser" via package "\#\!perl" \(perhaps you forgot to
> load "\#\!perl"?\) at small\.pl line 10\, \<INFILE> line 1\.
> 
> I believe that's the expected output \- and therefore I would suggest that this bug has already been fixed\.
> 
> Cheers\,
> Rob

The crash was caused by the fact that the name of the filehandle starts
with 'INF'\, change it to anything else\, the code will stop crashing\. 

While the code crashes only on Windows\, it also behaves weirdly on other
platforms\. For example\, the following code executed with perl 5\.26\.2 on 
dragonfly or linux&#8203;:

open INFILE\, '\<'\, \\'foo';
while \(\<INFILE>\) \{
&nbsp;        warn 'bar';
\}

outputs "bar at a\.pl line 3\, \<INFILE> line 0\.000000\."\. Note that the line
number is a float\.

The following commit has fixed those problems&#8203;:



---
commit 559a021f1d52c32a82cbdf9184aa59a58e898b08
Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
Date&#8203;:   Tue May 16 16&#8203;:30&#8203;:13 2017 \+0100

&nbsp;    sprintf&#8203;: handle sized int\-ish formats with Inf/Nan
&nbsp;    
&nbsp;    The code path taken when int\-ish formats saw an Inf/Nan was to jump to the
&nbsp;    floating\-point handler\, but then that would warn about \(valid\) size
&nbsp;    qualifiers\. For example before&#8203;:
&nbsp;    
&nbsp;        $ perl \-we'printf "\[%hi\]\\n"\, Inf'
&nbsp;        Invalid conversion in printf&#8203;: "%hi" at \-e line 1\.
&nbsp;        Redundant argument in printf at \-e line 1\.
&nbsp;        \[%hi\]
&nbsp;        $
&nbsp;    
&nbsp;    After this commit&#8203;:
&nbsp;    
&nbsp;        $ perl \-we'printf "\[%hi\]\\n"\, Inf'
&nbsp;        \[Inf\]
&nbsp;        $
&nbsp;    
&nbsp;    It also makes the code simpler\.


---
However\, the commit message doesn't say anything about crashing or float
line numbers\, which makes me think that the fix was accidental\.

I wonder if the bug was actually fixed or maybe it was just hidden\. 

CC\-ing Dave to get his opinion\.

**Comment by p5pRT** [comment]
### From @iabyn

On Wed\, Aug 29\, 2018 at 04&#8203;:24&#8203;:33PM \+0200\, Tomasz Konojacki wrote&#8203;:
> 
> However\, the commit message doesn't say anything about crashing or float
> line numbers\, which makes me think that the fix was accidental\.
> 
> I wonder if the bug was actually fixed or maybe it was just hidden\. 
> 
> CC\-ing Dave to get his opinion\.

It appears to be a combination of bugs\, all of which were fixed
by my extensive reworking of Perl\_sv\_vcatpvfn\_flags\(\) for 5\.28\.0\.

It's caused by the warn code doing&#8203;:

&nbsp;        Perl\_sv\_catpvf\(aTHX\_ sv\, "\, \<%" SVf "> %s %" IVdf\,
&nbsp;               SVfARG\(PL\_last\_in\_gv == PL\_argvgv
&nbsp;                                 ? &PL\_sv\_no
&nbsp;                                 : sv\_2mortal\(newSVhek\(GvNAME\_HEK\(PL\_last\_in\_gv\)\)\)\)\,
&nbsp;                                \(IV\)IoLINES\(GvIOp\(PL\_last\_in\_gv\)\)\);


i\.e\. doing the 'C' variant rather than the 'perl' variant of sprintf\,
so it gets its args from a va\_list rather than from an array of SVs\.

Handling the special\-cased %SVf format \(which actually expands to "%\-p"
triggered a code path where a variable\, argsv\, got left set on later %'s\.
This meant that the later %IVdf \(i\.e\. %ld\) was using the "INFILE" SV as
its arg rather than the intended IoLINES\(\)\. Which then triggered a second
bug with the poor handling of INF in integer formats\.

I haven't fully diagnosed this \(life is too short\)\, but I suspect my 100\+
commits that worked on Perl\_sv\_vcatpvfn\_flags\(\) will have fixed all the
issues here\.


\-\- 
Red sky at night \- gerroff my land\!
Red sky at morning \- gerroff my land\!
&nbsp;    \-\- old farmers' sayings \#14

**Comment by richardleach** [comment]
> ### From @sisyphus
> The sample program crashes on x64 Strawberry Perl 5.26.0, but on x64 Strawberry Perl 5.28.0 it produces output of​:
> 
> Can't locate object method "parser" via package "#!perl" (perhaps you forgot to
> load "#!perl"?) at small.pl line 10, <INFILE> line 1.
> 
> I believe that's the expected output - and therefore I would suggest that this bug has already been fixed.

Also, if the sample program is modified slightly to call a parser sub that outputs each parsed line, it produces the expected output without crashing:

```
C:\>perl -v

This is perl 5, version 30, subversion 0 (v5.30.0) built for MSWin32-x64-multi-thread

C:\>perl small.pl
> #!perl
>
> use strict;
> use warnings;
>
>
> open INFILE, '<', $0;
>
> while (<INFILE>) {
>       chomp;
>       parser($_);
> }
>
> sub parser {
>       print "> $_[0]\n";
> }
>
>
> __END__
```

Definitely seems like this ticket can be closed?

**Comment by xsawyerx** [comment]
> Definitely seems like this ticket can be closed?

Seems like that to me.
