### ISSUE TITLE
Dumper.c: loadable library and perl binaries are mismatched (got handshake key 0xdb00080, needed 0xde00080)

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16703]
Migrated from [rt.perl.org#133545](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133545) (status was 'open')

Searchable as RT133545$

**Comment by p5pRT** [comment]
### From patricia.brito@nms.unl.pt

Hi\,

I  need some help regarding the way to fix some incompatibility issues between loadable library and perl binaries\.


End goal is to be able to run the following application&#8203;:

\<https&#8203;://github\.com/tseemann/mlst/blob/master/README\.md>https://github.com/tseemann/mlst


I am working on a Ubuntu machine and using conda to install the packages that I need\. Recently I need to install this mlst software and to avoid incompatibilities between perl versions \(\!\!\) decided to do that inside a new virtual environment\. I am wondering if perl still reads files outside the virtual environment and if that is the reason for the error message\.

Any help is deeply appreciated as I do not know how to fix this\.


I pasted below the info from perl \-V

Thanks\!

Patrícia


Summary of my perl5 \(revision 5 version 26 subversion 2\) configuration&#8203;:

&nbsp;  Platform&#8203;:
&nbsp;    osname=linux
&nbsp;    osvers=4\.4\.0\-96\-generic
&nbsp;    archname=x86\_64\-linux\-thread\-multi
&nbsp;    uname='linux 1d1a811e559a 4\.4\.0\-96\-generic \#119~14\.04\.1\-ubuntu smp wed sep 13 08&#8203;:40&#8203;:48 utc 2017 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;    config\_args='\-de \-Dprefix=/home/ubuntu/miniconda3/envs/mlst \-Dusethreads \-Duserelocatableinc \-Dcccdlflags=\-fPIC \-Dldflags= \-Wl\,\-rpath\,/home/ubuntu/miniconda3/envs/mlst/lib \-L/home/ubuntu/miniconda3/envs/mlst/lib \-Ddefault\_inc\_excludes\_dot=n \-Dcc=gcc'
&nbsp;    hint=recommended
&nbsp;    useposix=true
&nbsp;    d\_sigaction=define
&nbsp;    useithreads=define
&nbsp;    usemultiplicity=define
&nbsp;    use64bitint=define
&nbsp;    use64bitall=define
&nbsp;    uselongdouble=undef
&nbsp;    usemymalloc=n
&nbsp;    default\_inc\_excludes\_dot=undef
&nbsp;    bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc'
&nbsp;    ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-D\_FORTIFY\_SOURCE=2'
&nbsp;    optimize='\-O2'
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''
&nbsp;    gccversion='4\.8\.2 20140120 \(Red Hat 4\.8\.2\-15\)'
&nbsp;    gccosandvers=''
&nbsp;    intsize=4
&nbsp;    longsize=8
&nbsp;    ptrsize=8
&nbsp;    doublesize=8
&nbsp;    byteorder=12345678
&nbsp;    doublekind=3
&nbsp;    d\_longlong=define
&nbsp;    longlongsize=8
&nbsp;    d\_longdbl=define
&nbsp;    longdblsize=16
&nbsp;    longdblkind=3
&nbsp;    ivtype='long'
&nbsp;    ivsize=8
&nbsp;    nvtype='double'
&nbsp;    nvsize=8
&nbsp;    Off\_t='off\_t'
&nbsp;    lseeksize=8
&nbsp;    alignbytes=8
&nbsp;    prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='gcc'
&nbsp;    ldflags =' \-Wl\,\-rpath\,/home/ubuntu/miniconda3/envs/mlst/lib \-L/home/ubuntu/miniconda3/envs/mlst/lib \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /opt/rh/devtoolset\-2/root/usr/lib /usr/lib /lib/\.\./lib64 /usr/lib/\.\./lib64 /lib /lib64 /usr/lib64 /usr/local/lib64
&nbsp;    libs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.12\.so
&nbsp;    so=so
&nbsp;    useshrplib=false
&nbsp;    libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.12'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs
&nbsp;    dlext=so
&nbsp;    d\_dlsymun=undef
&nbsp;    ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'
&nbsp;    lddlflags='\-shared \-O2 \-L/home/ubuntu/miniconda3/envs/mlst/lib \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;:
&nbsp;  Compile\-time options&#8203;:
&nbsp;    HAS\_TIMES
&nbsp;    MULTIPLICITY
&nbsp;    PERLIO\_LAYERS
&nbsp;    PERL\_COPY\_ON\_WRITE
&nbsp;    PERL\_DONT\_CREATE\_GVSV
&nbsp;    PERL\_IMPLICIT\_CONTEXT
&nbsp;    PERL\_MALLOC\_WRAP
&nbsp;    PERL\_OP\_PARENT
&nbsp;    PERL\_PRESERVE\_IVUV
&nbsp;    USE\_64\_BIT\_ALL
&nbsp;    USE\_64\_BIT\_INT
&nbsp;    USE\_ITHREADS
&nbsp;    USE\_LARGE\_FILES
&nbsp;    USE\_LOCALE
&nbsp;    USE\_LOCALE\_COLLATE
&nbsp;    USE\_LOCALE\_CTYPE
&nbsp;    USE\_LOCALE\_NUMERIC
&nbsp;    USE\_LOCALE\_TIME
&nbsp;    USE\_PERLIO
&nbsp;    USE\_PERL\_ATOF
&nbsp;    USE\_REENTRANT\_API
&nbsp;  Built under linux
&nbsp;  Compiled at Jul  6 2018 15&#8203;:53&#8203;:32
&nbsp;  %ENV&#8203;:
&nbsp;    PERL5LIB="/home/ubuntu/miniconda3/lib/perl5/site\_perl/5\.22\.0"
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    /home/ubuntu/miniconda3/lib/perl5/site\_perl/5\.22\.0/x86\_64\-linux\-thread\-multi
&nbsp;    /home/ubuntu/miniconda3/lib/perl5/site\_perl/5\.22\.0
&nbsp;    /home/ubuntu/miniconda3/envs/mlst/lib/site\_perl/5\.26\.2/x86\_64\-linux\-thread\-multi
&nbsp;    /home/ubuntu/miniconda3/envs/mlst/lib/site\_perl/5\.26\.2
&nbsp;    /home/ubuntu/miniconda3/envs/mlst/lib/5\.26\.2/x86\_64\-linux\-thread\-multi
&nbsp;    /home/ubuntu/miniconda3/envs/mlst/lib/5\.26\.2
&nbsp;    \.

**Comment by p5pRT** [comment]
### From @jkeenan

On Thu\, 27 Sep 2018 10&#8203;:21&#8203;:17 GMT\, patricia\.brito@&#8203;nms\.unl\.pt wrote&#8203;:
> Hi\,
> 
> I  need some help regarding the way to fix some incompatibility issues
> between loadable library and perl binaries\.
> 
> 
> End goal is to be able to run the following application&#8203;:
> 
> \<https&#8203;://github\.com/tseemann/mlst/blob/master/README\.md>https://github.com/tseemann/mlst
> 
> 
> I am working on a Ubuntu machine and using conda to install the
> packages that I need\. Recently I need to install this mlst software
> and to avoid incompatibilities between perl versions \(\!\!\) decided to
> do that inside a new virtual environment\. I am wondering if perl still
> reads files outside the virtual environment and if that is the reason
> for the error message\.
> 
> Any help is deeply appreciated as I do not know how to fix this\.
> 
> 
> I pasted below the info from perl \-V
> 
> Thanks\!
> 
> Patrícia
> 

Can you provide more of the sequence of commands that culminated in the error message?

Thank you very much\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @Leont

On Sun\, Sep 30\, 2018 at 12&#8203;:47 AM James E Keenan via RT
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> On Thu\, 27 Sep 2018 10&#8203;:21&#8203;:17 GMT\, patricia\.brito@&#8203;nms\.unl\.pt wrote&#8203;:
> > Hi\,
> >
> > I  need some help regarding the way to fix some incompatibility issues
> > between loadable library and perl binaries\.
> >
> >
> > End goal is to be able to run the following application&#8203;:
> >
> > \<https&#8203;://github\.com/tseemann/mlst/blob/master/README\.md>https://github.com/tseemann/mlst
> >
> >
> > I am working on a Ubuntu machine and using conda to install the
> > packages that I need\. Recently I need to install this mlst software
> > and to avoid incompatibilities between perl versions \(\!\!\) decided to
> > do that inside a new virtual environment\. I am wondering if perl still
> > reads files outside the virtual environment and if that is the reason
> > for the error message\.
> >
> > Any help is deeply appreciated as I do not know how to fix this\.
> >
> >
> > I pasted below the info from perl \-V
> >
> > Thanks\!
> >
> > Patrícia
> >
>
> Can you provide more of the sequence of commands that culminated in the error message?
>
> Thank you very much\.

It's sounds like a cousin of \#133440\, though indeed we need more
information to understand what's going on\.

Leon

**Comment by jkeenan** [comment]
> ### From @jkeenan
> 
> On Thu, 27 Sep 2018 10​:21​:17 GMT, patricia.brito@​nms.unl.pt wrote​:
> 
> > Hi,
> > I  need some help regarding the way to fix some incompatibility issues
> > between loadable library and perl binaries.
> > End goal is to be able to run the following application​:
> > <https​://github.com/tseemann/mlst/blob/master/README.md>https://github.com/tseemann/mlst
> > I am working on a Ubuntu machine and using conda to install the
> > packages that I need. Recently I need to install this mlst software
> > and to avoid incompatibilities between perl versions (!!) decided to
> > do that inside a new virtual environment. I am wondering if perl still
> > reads files outside the virtual environment and if that is the reason
> > for the error message.
> > Any help is deeply appreciated as I do not know how to fix this.
> > I pasted below the info from perl -V
> > Thanks!
> > Patrícia
> 
> Can you provide more of the sequence of commands that culminated in the error message?

Since we have not heard back from the original poster in more than 2 years, I propose we close this ticket in 14 days.  Self-assigning for that purpose.

Thank you very much.
Jim Keenan

**Comment by phbrito** [comment]
I do not recall to have seen your reply at the time, apologies for that.
You can close this ticket. I am not working with this machine anymore.
