### ISSUE TITLE
Test failures on Windows with 8.3 filenames disabled

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16804]
Migrated from [rt.perl.org#133754](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133754) (status was 'open')

Searchable as RT133754$

**Comment by p5pRT** [comment]
### From @steve-m-hay

#### Created by @steve-m-hay



If I run the test suite on my C&#8203;: drive then all tests pass\, but on my
D&#8203;: drive I get a bunch of failures&#8203;:

Test Summary Report
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
\.\./cpan/ExtUtils\-MakeMaker/t/02\-xsdynamic\.t
\(Wstat&#8203;: 2048 Tests&#8203;: 54 Failed&#8203;: 8\)
&nbsp;  Failed tests&#8203;:  3\, 9\, 15\, 21\, 27\, 33\, 39\, 45
&nbsp;  Non\-zero exit status&#8203;: 8
\.\./cpan/Win32/t/GetShortPathName\.t
\(Wstat&#8203;: 0 Tests&#8203;: 5 Failed&#8203;: 1\)
&nbsp;  Failed test&#8203;:  2
\.\./cpan/Win32/t/Unicode\.t
\(Wstat&#8203;: 0 Tests&#8203;: 11 Failed&#8203;: 8\)
&nbsp;  Failed tests&#8203;:  1\-3\, 5\, 8\-11
&nbsp;  Parse errors&#8203;: Bad plan\.  You planned 12 tests but ran 11\.
Files=2649\, Tests=1100728\, 2184 wallclock secs \(73\.52 usr \+ 10\.45 sys
= 83\.97 CPU\)
Result&#8203;: FAIL

The difference seems to be that 8\.3 filenames are disabled on my D&#8203;:
drive\, as I can see using the fsutil\.exe program&#8203;:

D&#8203;:\\Dev\\Git\\perl>fsutil 8dot3name query C&#8203;:
The volume state is&#8203;: 0 \(8dot3 name creation is enabled\)\.
The registry state is&#8203;: 2 \(Per volume setting \- the default\)\.

Based on the above settings\, 8dot3 name creation is enabled on C&#8203;:

D&#8203;:\\Dev\\Git\\perl>fsutil 8dot3name query D&#8203;:
The volume state is&#8203;: 1 \(8dot3 name creation is disabled\)\.
The registry state is&#8203;: 2 \(Per volume setting \- the default\)\.

Based on the above settings\, 8dot3 name creation is disabled on D&#8203;:

However\, modifying the test scripts to check this for themselves isn't
easy because \(a\) fsutil\.exe doesn't exist on all older versions of
Windows \(I'm running Windows 10\) and \(b\) even if fsutil\.exe is
available it needs an Admin Command Prompt to run\. In a normal Command
Prompt on the same machine I just get&#8203;:

D&#8203;:\\Dev\\Git\\perl>fsutil 8dot3name query C&#8203;:
Error&#8203;:  Access is denied\.

D&#8203;:\\Dev\\Git\\perl>fsutil 8dot3name query D&#8203;:
Error&#8203;:  Access is denied\.

It is possible to query the registry\, but if \(as on my system\) the
setting has been made per\-volume rather than globally on or off then
I'm not sure exactly which settings need querying&#8203;:

D&#8203;:\\Dev\\Git\\perl>reg query
HKLM\\System\\CurrentControlSet\\Control\\FileSystem /v
NtfsDisable8dot3NameCreation

HKEY\_LOCAL\_MACHINE\\System\\CurrentControlSet\\Control\\FileSystem
&nbsp;    NtfsDisable8dot3NameCreation    REG\_DWORD    0x2

This just tells me that the setting is per\-volume\. I'm not sure where
to look in the registry to find the settings for the individual
volumes\.

There is information about this online\, of course\, e\.g\. see the
following\, but I haven't found the answers I'm looking for yet&#8203;:

https://support.microsoft.com/en-gb/help/121007/how-to-disable-8-3-file-name-creation-on-ntfs-partitions
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/ff621566(v=ws.11)
https://guyrleech.wordpress.com/2014/04/11/ntfs-8-3-short-names-primer/
https://guyrleech.wordpress.com/2014/04/15/ntfs-8-3-short-names-solving-the-issues/

In the meantime perhaps it would be wise to at least add a note to
README\.win32 about these possible test failures?

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl 5.29.7:

Configured by shay at Mon Jan  7 13:24:20 2019.

Summary of my perl5 (revision 5 version 29 subversion 7) configuration:
  Commit id: 35ad0133df9b65a4e32f2f07a2a05b387bd79591
  Platform:
    osname=MSWin32
    osvers=10.0.17763.195
    archname=MSWin32-x64-multi-thread
    uname=''
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cl'
    ccflags ='-nologo -GF -W3 -O1 -MD -Zi -DNDEBUG -GL -fp:precise
-DWIN32 -D_CONSOLE -DNO_STRICT -DWIN64 -DCONSERVATIVE
-D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE
-D_WINSOCK_DEPRECATED_NO_WARNINGS  -DPERL_TEXTMODE_SCRIPTS
-DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS'
    optimize='-O1 -MD -Zi -DNDEBUG -GL -fp:precise'
    cppflags='-DWIN32'
    ccversion='19.16.27025.1'
    gccversion=''
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=undef
    longlongsize=8
    d_longdbl=define
    longdblsize=8
    longdblkind=0
    ivtype='__int64'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='__int64'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='link'
    ldflags ='-nologo -nodefaultlib -debug -opt:ref,icf -ltcg
-libpath:"c:\perl\lib\CORE"  -machine:AMD64'
    libpth="C:\Program Files (x86)\Microsoft Visual Studio\2017
15.9\Professional\VC\Tools\MSVC\14.16.27023\\lib\x64"
    libs=oldnames.lib kernel32.lib user32.lib gdi32.lib winspool.lib
comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib
netapi32.lib uuid.lib ws2_32.lib mpr.lib winmm.lib version.lib
odbc32.lib odbccp32.lib comctl32.lib msvcrt.lib vcruntime.lib ucrt.lib
    perllibs=oldnames.lib kernel32.lib user32.lib gdi32.lib
winspool.lib  comdlg32.lib advapi32.lib shell32.lib ole32.lib
oleaut32.lib netapi32.lib uuid.lib ws2_32.lib mpr.lib winmm.lib
version.lib odbc32.lib odbccp32.lib comctl32.lib msvcrt.lib
vcruntime.lib ucrt.lib
    libc=ucrt.lib
    so=dll
    useshrplib=true
    libperl=perl529.lib
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-dll -nologo -nodefaultlib -debug -opt:ref,icf -ltcg
-libpath:"c:\perl\lib\CORE"  -machine:AMD64'



@INC for perl 5.29.7:
    C:/perl/site/lib
    C:/perl/lib


Environment for perl 5.29.7:
    HOME (unset)
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=C:\Program Files (x86)\Microsoft Visual Studio\2017
15.9\Professional\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64;C:\Program
Files (x86)\Microsoft Visual Studio\2017
15.9\Professional\Common7\IDE\VC\VCPackages;C:\Program Files
(x86)\Microsoft SDKs\TypeScript\3.1;C:\Program Files (x86)\Microsoft
Visual Studio\2017
15.9\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program
Files (x86)\Microsoft Visual Studio\2017
15.9\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team
Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2017
15.9\Professional\MSBuild\15.0\bin\Roslyn;C:\Program Files
(x86)\Microsoft Visual Studio\2017 15.9\Professional\Team
Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual
Studio\2017 15.9\Professional\Team Tools\Performance Tools;C:\Program
Files (x86)\Microsoft Visual
Studio\Shared\Common\VSPerfCollectionTools\\x64;C:\Program Files
(x86)\Microsoft Visual
Studio\Shared\Common\VSPerfCollectionTools\;C:\Program Files
(x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1
Tools\x64\;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files
(x86)\Microsoft Visual Studio\2017
15.9\Professional\Common7\IDE\CommonExtensions\Microsoft\FSharp\;C:\Program
Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64;C:\Program Files
(x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual
Studio\2017 15.9\Professional\\MSBuild\15.0\bin;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program
Files (x86)\Microsoft Visual Studio\2017
15.9\Professional\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual
Studio\2017 15.9\Professional\Common7\Tools\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\wbem;C:\Program
Files (x86)\Microsoft Visual Studio\2017
15.9\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program
Files (x86)\Microsoft Visual Studio\2017
15.9\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
    PERL_BADLANG (unset)
    SHELL (unset)

```
</details>

**Comment by p5pRT** [comment]
### From rich@hyphen-dash-hyphen.info

On Mon\, Jan 7\, 2019 at 1&#8203;:37 PM Steve Hay \(via RT\)
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> If I run the test suite on my C&#8203;: drive then all tests pass\, but on my
> D&#8203;: drive I get a bunch of failures&#8203;:
>
> \.\.\.
> The difference seems to be that 8\.3 filenames are disabled on my D&#8203;:
> drive\, as I can see using the fsutil\.exe program&#8203;:
> \.\.\.
> It is possible to query the registry\, but if \(as on my system\) the
> setting has been made per\-volume rather than globally on or off then
> I'm not sure exactly which settings need querying&#8203;:

Hi Steve\,

The per\-volume setting doesn't appear to be stored in the Registry
\(based on use of Procmon on a test VM\)\. Instead\, it's stored in the
FILE\_FS\_PERSISTENT\_VOLUME\_INFORMATION structure \[1\]\, intended to be
queried with the NtFsControlFile function \[2\]

There are a few online discussions where people advise using
GetVolumeInformation \(which underpins Win32&#8203;::FsType\)\, but that advice
seems to be bogus\. \[3\]

\[1\] https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/ns-ntifs-_file_fs_persistent_volume_information
\[2\] https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/d4bc551b-7aaf-4b4f-ba0e-3a75e7c528f0
\[3\] https://stackoverflow.com/questions/18479322/how-to-check-programatically-that-8-3-short-path-name-is-enabled-on-system

HTH\,
Rich

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From rich@hyphen-dash-hyphen.info

On Thu\, Apr 4\, 2019 at 8&#8203;:54 PM Richard Leach
\<rich@&#8203;hyphen\-dash\-hyphen\.info> wrote&#8203;:
> The per\-volume setting doesn't appear to be stored in the Registry
> \(based on use of Procmon on a test VM\)\. Instead\, it's stored in the
> FILE\_FS\_PERSISTENT\_VOLUME\_INFORMATION structure \[1\]\, intended to be
> queried with the NtFsControlFile function \[2\]

Just noticed that this is also mentioned in a pending pull request&#8203;:
https://github.com/perl-libwin32/win32/pull/12/commits/7cf0da647c973a64ccc120dd81749e7494930193

**Comment by p5pRT** [comment]
### From @steve-m-hay

This may also be the cause of \#121461\.

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

This may also be the cause of \#121461\.

**Comment by p5pRT** [comment]
### From rich@hyphen-dash-hyphen.info

On Thu\, Apr 4\, 2019 at 9&#8203;:02 PM Richard Leach
\<rich@&#8203;hyphen\-dash\-hyphen\.info> wrote&#8203;:
> Just noticed that this is also mentioned in a pending pull request&#8203;:
> https://github.com/perl-libwin32/win32/pull/12/commits/7cf0da647c973a64ccc120dd81749e7494930193

Coming back to this\, is the ideal approach here \(1\) wchristian's patch
at the above link \(2\) some kind of SKIP tests if short paths aren't
present \(3\) add a probe for ntifs\.h and add support for retrieving
FILE\_FS\_PERSISTENT\_VOLUME\_INFORMATION\.

Asking 'cos if not \(1\)\, then I'm prepared to have a go at it\.

Thanks\,
Richard

**Comment by p5pRT** [comment]
### From @steve-m-hay

On Sat\, 25 May 2019 15&#8203;:35&#8203;:50 \-0700\, rich@&#8203;hyphen\-dash\-hyphen\.info wrote&#8203;:
> On Thu\, Apr 4\, 2019 at 9&#8203;:02 PM Richard Leach
> \<rich@&#8203;hyphen\-dash\-hyphen\.info> wrote&#8203;:
> > Just noticed that this is also mentioned in a pending pull request&#8203;:
> > https://github.com/perl-
> > libwin32/win32/pull/12/commits/7cf0da647c973a64ccc120dd81749e7494930193
> 
> Coming back to this\, is the ideal approach here \(1\) wchristian's patch
> at the above link \(2\) some kind of SKIP tests if short paths aren't
> present \(3\) add a probe for ntifs\.h and add support for retrieving
> FILE\_FS\_PERSISTENT\_VOLUME\_INFORMATION\.
> 
> Asking 'cos if not \(1\)\, then I'm prepared to have a go at it\.
> 

All 3? ;\-\)

\(3\) would be useful to decide which test to perform in GetShortPathName\.t \(i\.e\. do the current test if 8\.3 is supported\, change to the simplified test in wchristian's patch if not\)\.
\(2\) would be needed for the other failing tests if 8\.3 is not supported \(or perhaps conditionally change the test being done\, like in \(1\)\, rather than skipping completely?\)\.
\(1\) has a useful documentation update that ought to go in either way\.

**Comment by p5pRT** [comment]
### From rich@hyphen-dash-hyphen.info

On Fri\, May 31\, 2019 at 8&#8203;:48 PM Steve Hay via RT
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> \(3\) would be useful to decide which test to perform in GetShortPathName\.t \(i\.e\. do the current test if 8\.3 is supported\, change to the simplified test in wchristian's patch if not\)\.
> \(2\) would be needed for the other failing tests if 8\.3 is not supported \(or perhaps conditionally change the test being done\, like in \(1\)\, rather than skipping completely?\)\.
> \(1\) has a useful documentation update that ought to go in either way\.

Unsatisfactory results here\. I've got XS code that allows elevated
users to create a handle to \(e\.g\.\) \\\\\.\\c&#8203;: and pass that handle
DeviceIoControl\(\) in order to retrieve
FILE\_FS\_PERSISTENT\_VOLUME\_INFORMATION\.

Doesn't work for non\-elevated users though\. Via WinObj\, EVERYONE has&#8203;:
\* the QUERY STATE permissions on \(e\.g\.\) the C&#8203;: symbolic link\.
\* READ permissions on the \\Device\\HarddiskVolume\{X\} object

But although that seems like it should be sufficient\, it isn't\, and
normal users can't create the necessary handle\. I'll play a little
more\, but it's looking like this won't be a viable approach\.



---
via perlbug&#8203;:  queue&#8203;: perl5 status&#8203;: open
https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133754

**Comment by p5pRT** [comment]
### From rich@hyphen-dash-hyphen.info

On Sun\, Jun 9\, 2019 at 11&#8203;:04 PM Richard Leach
\<rich@&#8203;hyphen\-dash\-hyphen\.info> wrote&#8203;:
> > \(3\) would be useful to decide which test to perform in GetShortPathName\.t \(i\.e\. do the current test if 8\.3 is supported\, change to the simplified test in wchristian's patch if not\)\.

How about the attached simple approach? DWIMs in both 8dot3name
configurations locally\.



---
via perlbug&#8203;:  queue&#8203;: perl5 status&#8203;: open
https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133754

**Comment by p5pRT** [comment]
### From rich@hyphen-dash-hyphen.info

use strict;
use Test;
use Win32;

my $path = "Long Path $$";
unlink\($path\);
END \{ unlink $path \}

plan tests => 5;

Win32&#8203;::CreateFile\($path\);

my $short\_disabled = 'Current volume does not support short path names';
if \(\-f $path && unlink 'LONGPA~1'\) \{
&nbsp;    $short\_disabled = undef;
&nbsp;    Win32&#8203;::CreateFile\($path\);
\}

ok\(\-f $path\);

my $short = Win32&#8203;::GetShortPathName\($path\);
skip\($short\_disabled\, $short\, qr/^\\S\{1\,8\}\(\\\.\\S\{1\,3\}\)?$/\);
skip\($short\_disabled\, \-f $short\);

unlink\($path\);
ok\(\!\-f $path\);
ok\(\!defined Win32&#8203;::GetShortPathName\($path\)\);

**Comment by p5pRT** [comment]
### From @steve-m-hay

On Fri\, 14 Jun 2019 15&#8203;:20&#8203;:22 \-0700\, rich@&#8203;hyphen\-dash\-hyphen\.info wrote&#8203;:
> On Sun\, Jun 9\, 2019 at 11&#8203;:04 PM Richard Leach
> \<rich@&#8203;hyphen\-dash\-hyphen\.info> wrote&#8203;:
> > > \(3\) would be useful to decide which test to perform in
> > > GetShortPathName\.t \(i\.e\. do the current test if 8\.3 is supported\,
> > > change to the simplified test in wchristian's patch if not\)\.
> 
> How about the attached simple approach? DWIMs in both 8dot3name
> configurations locally\.
> 

Yes\, that works for me\.

**Comment by p5pRT** [comment]
### From rich@hyphen-dash-hyphen.info

On Wed\, Jun 19\, 2019 at 1&#8203;:38 PM Steve Hay via RT
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> On Fri\, 14 Jun 2019 15&#8203;:20&#8203;:22 \-0700\, rich@&#8203;hyphen\-dash\-hyphen\.info wrote&#8203;:
> > How about the attached simple approach? DWIMs in both 8dot3name
> > configurations locally\.
> >
>
> Yes\, that works for me\.


Thanks\. I'll look into whether the same sort of logic can be used to
keep the non\-short path tests in unicode\.t\, or whether those are
effectively covered elsewhere and so just use the logic to skip the
lot if short paths aren't enabled\. Then lob patches upstream\.

Maybe EUMM too\, if it rains at the weekend\. ;\-\)



---
via perlbug&#8203;:  queue&#8203;: perl5 status&#8203;: open
https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133754

**Comment by p5pRT** [comment]
### From @steve-m-hay

On Wed\, 19 Jun 2019 16&#8203;:12&#8203;:13 \-0700\, rich@&#8203;hyphen\-dash\-hyphen\.info wrote&#8203;:
> On Wed\, Jun 19\, 2019 at 1&#8203;:38 PM Steve Hay via RT
> \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> > On Fri\, 14 Jun 2019 15&#8203;:20&#8203;:22 \-0700\, rich@&#8203;hyphen\-dash\-hyphen\.info wrote&#8203;:
> > > How about the attached simple approach? DWIMs in both 8dot3name
> > > configurations locally\.
> > >
> >
> > Yes\, that works for me\.
> 
> 
> Thanks\. I'll look into whether the same sort of logic can be used to
> keep the non\-short path tests in unicode\.t\, or whether those are
> effectively covered elsewhere and so just use the logic to skip the
> lot if short paths aren't enabled\. Then lob patches upstream\.
> 
> Maybe EUMM too\, if it rains at the weekend\. ;\-\)
> 

Thanks\! Don't forget that changes to these CPAN module test scripts need to be sent upstream to their respective module maintainers\. It would be great to get fixes checked in to new releases of those distros\, and then we can pull them into blead\.

**Comment by p5pRT** [comment]
### From rich@hyphen-dash-hyphen.info

On Thu\, Jun 20\, 2019 at 8&#8203;:10 AM Steve Hay via RT
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> > Maybe EUMM too\, if it rains at the weekend\. ;\-\)


Steve\,

Are those EUMM tests still failing for you with blead? They pass for
me on Win10\, using Strawberry's tools\, building in C&#8203;:\\ with 8dot3names
disabled on that volume\.

I've added a comment to wchristian's pull request on win32 for
GetShortPathName\.t\.  \(The explanatory text in that PR looks good\, so
maybe easier to tweak the submitted test than submit a new PR on the
same topic\)\.

Couldn't see an easy fix for Unicode\.t\, without really fixing Unicode
filesystem handling\.

Cheers\,
Richard



---
via perlbug&#8203;:  queue&#8203;: perl5 status&#8203;: open
https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133754

**Comment by p5pRT** [comment]
### From @steve-m-hay

On Sun\, 23 Jun 2019 at 23&#8203;:10\, Richard Leach
\<rich@&#8203;hyphen\-dash\-hyphen\.info> wrote&#8203;:
>
> On Thu\, Jun 20\, 2019 at 8&#8203;:10 AM Steve Hay via RT
> \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> > > Maybe EUMM too\, if it rains at the weekend\. ;\-\)
>
>
> Steve\,
>
> Are those EUMM tests still failing for you with blead? They pass for
> me on Win10\, using Strawberry's tools\, building in C&#8203;:\\ with 8dot3names
> disabled on that volume\.
>

Yes\, they still fail for me \(on Win10 D&#8203;:\\ with 8\.3 disabled\, using
MSVC\+\+\)\. Verbose output is as follows&#8203;:

>\.\\perl harness \-v \.\./cpan/ExtUtils\-MakeMaker/t/02\-xsdynamic\.t
\.\./cpan/ExtUtils\-MakeMaker/t/02\-xsdynamic\.t \.\.
compilet\-Q3iDu\.c
&nbsp;   Creating library compilet\.lib and object compilet\.exp
Generating code
Finished generating code
1\.\.54
ok 1 \- setup basic
ok 2 \- chdir'd to XS\-Testbasic
not ok 3 \- Makefile\.PL exited with zero

\#   Failed test 'Makefile\.PL exited with zero'
\#   at lib/MakeMaker/Test/Setup/XS\.pm line 423\.
\#          got&#8203;: 512
\#     expected&#8203;: 0
\# Tried to use make dependency with space for non\-GNU make&#8203;:
\#   'type map'
\# Fallback to short pathname failed\.
ok 4 \# skip perl Makefile\.PL failed
ok 5 \# skip perl Makefile\.PL failed
ok 6 \- teardown XS\-Testbasic
ok 7 \- setup subdirs
ok 8 \- chdir'd to XS\-Testsubdirs
not ok 9 \- Makefile\.PL exited with zero

\#   Failed test 'Makefile\.PL exited with zero'
\#   at lib/MakeMaker/Test/Setup/XS\.pm line 423\.
\#          got&#8203;: 512
\#     expected&#8203;: 0
\# Tried to use make dependency with space for non\-GNU make&#8203;:
\#   'type map'
\# Fallback to short pathname failed\.
\# Writing MYMETA\.yml and MYMETA\.json
ok 10 \# skip perl Makefile\.PL failed
ok 11 \# skip perl Makefile\.PL failed
ok 12 \- teardown XS\-Testsubdirs
ok 13 \- setup subdirsstaticLINKTYPEdynamic
ok 14 \- chdir'd to XS\-TestsubdirsstaticLINKTYPEdynamic
not ok 15 \- Makefile\.PL exited with zero

\#   Failed test 'Makefile\.PL exited with zero'
\#   at lib/MakeMaker/Test/Setup/XS\.pm line 423\.
\#          got&#8203;: 512
\#     expected&#8203;: 0
\# Tried to use make dependency with space for non\-GNU make&#8203;:
\#   'type map'
\# Fallback to short pathname failed\.
\# Writing MYMETA\.yml and MYMETA\.json
ok 16 \# skip perl Makefile\.PL failed
ok 17 \# skip perl Makefile\.PL failed
ok 18 \- teardown XS\-TestsubdirsstaticLINKTYPEdynamic
ok 19 \- setup subdirsstaticdynamic
ok 20 \- chdir'd to XS\-Testsubdirsstaticdynamic
not ok 21 \- Makefile\.PL exited with zero

\#   Failed test 'Makefile\.PL exited with zero'
\#   at lib/MakeMaker/Test/Setup/XS\.pm line 423\.
\#          got&#8203;: 512
\#     expected&#8203;: 0
\# Tried to use make dependency with space for non\-GNU make&#8203;:
\#   'type map'
\# Fallback to short pathname failed\.
\# Writing MYMETA\.yml and MYMETA\.json
ok 22 \# skip perl Makefile\.PL failed
ok 23 \# skip perl Makefile\.PL failed
ok 24 \- teardown XS\-Testsubdirsstaticdynamic
ok 25 \- setup multi
ok 26 \- chdir'd to XS\-Testmulti

\#   Failed test 'Makefile\.PL exited with zero'
\#   at lib/MakeMaker/Test/Setup/XS\.pm line 423\.
not ok 27 \- Makefile\.PL exited with zero
\#          got&#8203;: 512
\#     expected&#8203;: 0
\# Tried to use make dependency with space for non\-GNU make&#8203;:
\#   'lib/XS/type map'
\# Fallback to short pathname failed\.
ok 28 \# skip perl Makefile\.PL failed
ok 29 \# skip perl Makefile\.PL failed
ok 30 \- teardown XS\-Testmulti
ok 31 \- setup staticmultiLINKTYPEdynamic
ok 32 \- chdir'd to XS\-TeststaticmultiLINKTYPEdynamic
not ok 33 \- Makefile\.PL exited with zero

\#   Failed test 'Makefile\.PL exited with zero'
\#   at lib/MakeMaker/Test/Setup/XS\.pm line 423\.
\#          got&#8203;: 512
\#     expected&#8203;: 0
\# Tried to use make dependency with space for non\-GNU make&#8203;:
\#   'lib/XS/type map'
\# Fallback to short pathname failed\.
ok 34 \# skip perl Makefile\.PL failed
ok 35 \# skip perl Makefile\.PL failed
ok 36 \- teardown XS\-TeststaticmultiLINKTYPEdynamic
ok 37 \- setup staticmultidynamic
ok 38 \- chdir'd to XS\-Teststaticmultidynamic
not ok 39 \- Makefile\.PL exited with zero

\#   Failed test 'Makefile\.PL exited with zero'
\#   at lib/MakeMaker/Test/Setup/XS\.pm line 423\.
\#          got&#8203;: 512
\#     expected&#8203;: 0
\# Tried to use make dependency with space for non\-GNU make&#8203;:
\#   'lib/XS/type map'
\# Fallback to short pathname failed\.
ok 40 \# skip perl Makefile\.PL failed
ok 41 \# skip perl Makefile\.PL failed
ok 42 \- teardown XS\-Teststaticmultidynamic
ok 43 \- setup xsbuild
ok 44 \- chdir'd to XS\-Testxsbuild

\#   Failed test 'Makefile\.PL exited with zero'
\#   at lib/MakeMaker/Test/Setup/XS\.pm line 423\.
not ok 45 \- Makefile\.PL exited with zero
\#          got&#8203;: 512
\#     expected&#8203;: 0
\# Tried to use make dependency with space for non\-GNU make&#8203;:
\#   'lib/XS/type map'
\# Fallback to short pathname failed\.
ok 46 \# skip perl Makefile\.PL failed
ok 47 \# skip perl Makefile\.PL failed
ok 48 \- teardown XS\-Testxsbuild
ok 49 \- setup subdirsskip
ok 50 \- chdir'd to XS\-Testsubdirsskip
ok 51 \- Makefile\.PL exited with zero
ok 52 \- "nmake"   exited normally
ok 53 \- "nmake" test  exited normally
ok 54 \- teardown XS\-Testsubdirsskip
\# Looks like you failed 8 tests of 54\.
Dubious\, test returned 8 \(wstat 2048\, 0x800\)
Failed 8/54 subtests
&nbsp;        \(less 16 skipped subtests&#8203;: 30 okay\)

Test Summary Report


---
\.\./cpan/ExtUtils\-MakeMaker/t/02\-xsdynamic\.t \(Wstat&#8203;: 2048 Tests&#8203;: 54 Failed&#8203;: 8\)
&nbsp;  Failed tests&#8203;:  3\, 9\, 15\, 21\, 27\, 33\, 39\, 45
&nbsp;  Non\-zero exit status&#8203;: 8
Files=1\, Tests=54\, 110 wallclock secs \( 0\.02 usr \+  0\.01 sys =  0\.03 CPU\)
Result&#8203;: FAIL

**Comment by p5pRT** [comment]
### From rich@hyphen-dash-hyphen.info

On Mon\, Jun 24\, 2019 at 5&#8203;:38 PM Steve Hay \<steve\.m\.hay@&#8203;googlemail\.com> wrote&#8203;:
> > Are those EUMM tests still failing for you with blead? They pass for
> > me on Win10\, using Strawberry's tools\, building in C&#8203;:\\ with 8dot3names
> > disabled on that volume\.
> >
>
> Yes\, they still fail for me \(on Win10 D&#8203;:\\ with 8\.3 disabled\, using
> MSVC\+\+\)\. Verbose output is as follows&#8203;:


Ah\, ok\. I'm having trouble building with a freshly downloaded copy of
MSVC build tools\, but will keep at it\.

**Comment by richardleach** [comment]
Updated some comments on Mithaldu's PR in https://github.com/perl-libwin32/win32/pull/12 for skipping GetShortPathName.t and Unicode.t tests in the absence of short name support.

**Comment by richardleach** [comment]
@steve-m-hay Just completed a fresh test run against blead and didn't get failures in /cpan/ExtUtils-MakeMaker/t/02-xsdynamic.t with Mingw-64. Are you still seeing them with MSVC?

**Comment by richardleach** [comment]
Oh, wait. Just remembered, may relate to quote_dep() in MM_Win32.pm, so I wouldn't see it with gmake anyway.

**Comment by steve-m-hay** [comment]
On Mon, 24 Feb 2020 at 00:29, Richard Leach <notifications@github.com>
wrote:

> @steve-m-hay <https://github.com/steve-m-hay> Just completed a fresh test
> run against blead and didn't get failures in
> /cpan/ExtUtils-MakeMaker/t/02-xsdynamic.t with Mingw-64. Are you still
> seeing them with MSVC?
>
>
> Yes, I still get failures in at least
cpan/ExtUtils-MakeMaker/t/02-xsdynamic.t, cpan/Win32/t/GetShortPathName.t
and cpan/Win32/t/Unicode.t.

**Comment by richardleach** [comment]
Steve's above 02-xsdynamic.t errors come from MM_Win32.pm's `quote_dep` being unable to handle the "type map" argument in the absence of short path support.

"type map" comes from MakeMaker::Test::Setup::XS, which will actually remove the space if the make flavour cannot handle spaces (`can_dep_space`):
```
my $typemap = 'type map';
my $MM = MM->new({NAME=>'name', NORECURS=>1});
$typemap =~ s/ //g unless $MM->can_dep_space;
```
MM_Win32.pm always assumes that short path support will be present:
```
sub can_dep_space {
    my $self = shift;
    1; # with Win32::GetShortPathName
}
```
So resolving these test errors might be as straightforward of revising MM_Win32.pm's `can_dep_space` to check for short path support:
```
sub can_dep_space {
    # can_dep_space via GetShortPathName, if short paths are supported
    Win32::CreateFile("8dot3test_canary_can_dep_space $$");
    my $canary = Win32::GetShortPathName("8dot3test_canary_can_dep_space $$");
    unlink("8dot3test_canary_can_dep_space $$");
    return ( length $canary > 12 ) ? 0 : 1;
}
```
@steve-m-hay - do you have time to quickly test this idea? Otherwise, I'll try to get an nmake test environment built.

**Comment by richardleach** [comment]
Good news:  Got a MSVC build working.
Bad news: The above doesn't work (or doesn't work without something else being changed). Back to that MakeMaker::Test::Setup::XS snippet:
```
my $MM = MM->new({NAME=>'name', NORECURS=>1});
$typemap =~ s/ //g unless $MM->can_dep_space;
```
$MM is a PACK001 object and $MM->can_dep_space:
1. returns 1
2. Doesn't hit the can_dep_space subroutine in MM_Win32.pm on the way

I see from [EUMM's MakeMaker object hierarchy (real)](https://github.com/Perl/perl5/blob/blead/cpan/ExtUtils-MakeMaker/lib/ExtUtils/MakeMaker/FAQ.pod) that here be dragons...

Edit: Probable PEBKAC, trying a fresh build.

**Comment by richardleach** [comment]
Confirmed that the suggested fix for 02-dynamic.t does work. Upstream PR at https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/pull/351

**Comment by richardleach** [comment]
Currently known test failures due to 8dot3filename support being disabled should be fixed in the next stable perl release via:
* https://github.com/Perl/perl5/commit/2b8fc250cda86dddcc8e7c8418c67d5bb24036c8 for Win32's GetShortPathName.t and Unicode.t
* When EUMM v7.49_04 (or a later build) is pulled in (assuming this happens prior to blead freeze) for EUMM's 02-dynamic.t.
