### ISSUE TITLE
BBC: 4288c5b broke test in CPAN module XML::Easy

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16833]
Migrated from [rt.perl.org#133816](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133816) (status was 'open')

Searchable as RT133816$

**Comment by p5pRT** [comment]
### From @jkeenan

As originally reported in 
https://rt.cpan.org/Ticket/Display.html?id=127416, a failure has 
appeared during this development cycle in the test suite for CPAN 
distribution XML\-Easy\.

\#\#\#\#\#
$ ~/bin/perl/dumpjson ZEFRAM\.XML\-Easy\-0\.011\.log\.json
\{
&nbsp;   author => "ZEFRAM"\,
&nbsp;   dist => "XML\-Easy"\,
&nbsp;   distname => "XML\-Easy\-0\.011"\,
&nbsp;   distversion => 0\.011\,
&nbsp;   grade => "FAIL"\,
&nbsp;   prereqs => undef\,
&nbsp;   test\_output => \[
&nbsp;     "Building and testing XML\-Easy\-0\.011"\,
&nbsp;     "Building XML\-Easy"\,
&nbsp;     "cc 
\-I/home/jkeenan/var/tad/testing/perl\-5\.29\.4/lib/5\.29\.4/amd64\-freebsd\-thread\-multi/CORE 
\-DVERSION=\\"0\.011\\" \-DXS\_VERSION=\\"0\.011\\" \-DPIC \-fPIC \-c 
\-DHAS\_FPSETMASK \-DHAS\_FLOATINGPOINT\_H \-fno\-strict\-aliasing \-pipe 
\-fstack\-protector\-strong \-I/usr/local/include \-D\_FORTIFY\_SOURCE=2 \-O2 
\-pipe \-fstack\-protector \-fno\-strict\-aliasing \-o lib/XML/Easy\.o 
lib/XML/Easy\.c"\,

"ExtUtils&#8203;::Mkbootstrap&#8203;::Mkbootstrap\('blib/arch/auto/XML/Easy/Easy\.bs'\)"\,
&nbsp;     "cc \-shared \-L/usr/local/lib \-fstack\-protector\-strong \-o 
blib/arch/auto/XML/Easy/Easy\.so lib/XML/Easy\.o"\,
&nbsp;     "t/classify\.t \.\.\.\.\.\.\.\. ok"\,
&nbsp;     "t/classify\_pp\.t \.\.\.\.\. ok"\,
&nbsp;     "t/easy\_module\.t \.\.\.\.\. ok"\,
&nbsp;     "t/easy\_module\_pp\.t \.\. ok"\,
&nbsp;     "t/node\_basics\.t \.\.\.\.\. ok"\,
&nbsp;     "t/node\_basics\_pp\.t \.\. ok"\,
&nbsp;     "t/node\_object\.t \.\.\.\.\. ok"\,
&nbsp;     "t/node\_object\_pp\.t \.\. ok"\,
&nbsp;     "t/pod\_cvg\.t \.\.\.\.\.\.\.\.\. ok"\,
&nbsp;     "t/pod\_cvg\_pp\.t \.\.\.\.\.\. ok"\,
&nbsp;     "t/pod\_syn\.t \.\.\.\.\.\.\.\.\. ok"\,
&nbsp;     "t/read\.t \.\.\.\.\.\.\.\.\.\.\.\. ok"\,
&nbsp;     "t/read\_pp\.t \.\.\.\.\.\.\.\.\. ok"\,
&nbsp;     "WARNING&#8203;: Complex regular subexpression recursion limit \(65534\) 
exceeded at t/syntax\_main\.t line 79\, \<GEN0> line 1635\."\,
&nbsp;     "\# Looks like your test exited with 25 just after 369\."\,
&nbsp;     "t/syntax\_main\.t \.\.\.\.\. "\,
&nbsp;     "Dubious\, test returned 25 \(wstat 6400\, 0x1900\)"\,
&nbsp;     "Failed 640/1009 subtests "\,
&nbsp;     "t/version\_synch\.t \.\.\. ok"\,
&nbsp;     "t/write\.t \.\.\.\.\.\.\.\.\.\.\. ok"\,
&nbsp;     "t/write\_pp\.t \.\.\.\.\.\.\.\. ok"\,
&nbsp;     ""\,
&nbsp;     "Test Summary Report"\,
&nbsp;     "\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-"\,
&nbsp;     "t/syntax\_main\.t   \(Wstat&#8203;: 6400 Tests&#8203;: 369 Failed&#8203;: 0\)"\,
&nbsp;     "  Non\-zero exit status&#8203;: 25"\,
&nbsp;     "  Parse errors&#8203;: Bad plan\.  You planned 1009 tests but ran 369\."\,
&nbsp;     "Files=17\, Tests=100677\, 47 wallclock secs \( 0\.46 usr  7\.45 sys \+ 
40\.20 cusr  6\.88 csys = 54\.98 CPU\)"\,
&nbsp;     "Result&#8203;: FAIL"\,
&nbsp;   \]\,
&nbsp;   via => "App&#8203;::cpanminus&#8203;::reporter 0\.17 \(1\.7044\)"\,
\}
\#\#\#\#\#

I provided a patch \(which has not yet been applied\)\.  Slaven 
subsequently observed that this was probably was related to a change in 
blead\.  Bisection points to&#8203;:

\#\#\#\#\#
HEAD is now at 4288c5b93b Change REG\_INFTY to 2\*\*16\-1\, instead of 2\*\*15\-1
bad \- non\-zero exit from /tmp/GLUOqiNNx2/bin/perl \-I /home/jkeenan/\.cpan 
\-MCPAN&#8203;::MyConfig \-MCPAN \-e 
$CPAN&#8203;::Config\->\{build\_dir\}=q\{/tmp/wRUfXf4y2y\}; \-e install\('XML&#8203;::Easy'\); 
die unless CPAN&#8203;::Shell\->expand\(Module => 'XML&#8203;::Easy'\)\->uptodate;
4288c5b93b3823465d8a11e569547afd41b5d1b8 is the first bad commit
commit 4288c5b93b3823465d8a11e569547afd41b5d1b8
Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
Date&#8203;:   Sun Sep 30 12&#8203;:10&#8203;:17 2018 \-0600

Change REG\_INFTY to 2\*\*16\-1\, instead of 2\*\*15\-1

This commit doubles the upper limit that unbounded regular expression 
quantifiers can match up to\.  Things like \{m\,\} "\+" and "\*" now can match 
up to U16\_MAX times\.

We probably should make this a 32 bit value\, but doing this doubling was 
easy and has fewer potential implications\.

See http&#8203;://nntp\.perl\.org/group/perl\.perl5\.porters/251413 and followups

:040000 040000 5180c35445d2089ef994fcb0634d5e0064197f50 
ca323198918692cde3d4d80cca850138f4a1e58b M    pod
:100644 100644 ea3a0661d9ffe614167b9e183394e9d89514e1f4 
0c5222692138a5614401d0c9b41a1183aee3bc27 M    regcomp\.h
:040000 040000 fd6ac6b4d41de9a65f73f5ee7c61bbd4b70b9db3 
a911dcc50233fe4b31104610c85325128598f631 M    t
bisect run success
That took 2991 seconds\.
\#\#\#\#\#

Thank you very much\.

**Comment by p5pRT** [comment]
### From @jkeenan


This is perl 5\, version 29\, subversion 7 \(v5\.29\.7 \(v5\.29\.6\-69\-gc011174cae\)\) built for x86\_64\-linux
\(with 93 registered patches\, see perl \-V for more detail\)

Copyright 1987\-2018\, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License\, which may be found in the Perl 5 source kit\.

Complete documentation for Perl\, including FAQ lists\, should be found on
this system using "man perl" or "perldoc perl"\.  If you have access to the
Internet\, point your browser at http&#8203;://www\.perl\.org/\, the Perl Home Page\.

**Comment by p5pRT** [comment]
### From @jkeenan

On Sat\, 02 Feb 2019 15&#8203;:18&#8203;:52 GMT\, jkeenan@&#8203;pobox\.com wrote&#8203;:
> As originally reported in
> https://rt.cpan.org/Ticket/Display.html?id=127416, a failure has
> appeared during this development cycle in the test suite for CPAN
> distribution XML\-Easy\.
> 
> \#\#\#\#\#
> $ ~/bin/perl/dumpjson ZEFRAM\.XML\-Easy\-0\.011\.log\.json
> \{
>    author => "ZEFRAM"\,
>    dist => "XML\-Easy"\,
>    distname => "XML\-Easy\-0\.011"\,
>    distversion => 0\.011\,
>    grade => "FAIL"\,
>    prereqs => undef\,
>    test\_output => \[
>      "Building and testing XML\-Easy\-0\.011"\,
>      "Building XML\-Easy"\,
>       "cc
>  \-I/home/jkeenan/var/tad/testing/perl\-5\.29\.4/lib/5\.29\.4/amd64\-freebsd\-
> thread\-multi/CORE
>  \-DVERSION=\\"0\.011\\" \-DXS\_VERSION=\\"0\.011\\" \-DPIC \-fPIC \-c
>  \-DHAS\_FPSETMASK \-DHAS\_FLOATINGPOINT\_H \-fno\-strict\-aliasing \-pipe
>  \-fstack\-protector\-strong \-I/usr/local/include \-D\_FORTIFY\_SOURCE=2 \-O2
>  \-pipe \-fstack\-protector \-fno\-strict\-aliasing \-o lib/XML/Easy\.o
> lib/XML/Easy\.c"\,
> 
> "ExtUtils&#8203;::Mkbootstrap&#8203;::Mkbootstrap\('blib/arch/auto/XML/Easy/Easy\.bs'\)"\,
>       "cc \-shared \-L/usr/local/lib \-fstack\-protector\-strong \-o
> blib/arch/auto/XML/Easy/Easy\.so lib/XML/Easy\.o"\,
>      "t/classify\.t \.\.\.\.\.\.\.\. ok"\,
>      "t/classify\_pp\.t \.\.\.\.\. ok"\,
>      "t/easy\_module\.t \.\.\.\.\. ok"\,
>      "t/easy\_module\_pp\.t \.\. ok"\,
>      "t/node\_basics\.t \.\.\.\.\. ok"\,
>      "t/node\_basics\_pp\.t \.\. ok"\,
>      "t/node\_object\.t \.\.\.\.\. ok"\,
>      "t/node\_object\_pp\.t \.\. ok"\,
>      "t/pod\_cvg\.t \.\.\.\.\.\.\.\.\. ok"\,
>      "t/pod\_cvg\_pp\.t \.\.\.\.\.\. ok"\,
>      "t/pod\_syn\.t \.\.\.\.\.\.\.\.\. ok"\,
>      "t/read\.t \.\.\.\.\.\.\.\.\.\.\.\. ok"\,
>      "t/read\_pp\.t \.\.\.\.\.\.\.\.\. ok"\,
>       "WARNING&#8203;: Complex regular subexpression recursion limit \(65534\)
> exceeded at t/syntax\_main\.t line 79\, \<GEN0> line 1635\."\,
>      "\# Looks like your test exited with 25 just after 369\."\,
>      "t/syntax\_main\.t \.\.\.\.\. "\,
>      "Dubious\, test returned 25 \(wstat 6400\, 0x1900\)"\,
>      "Failed 640/1009 subtests "\,
>      "t/version\_synch\.t \.\.\. ok"\,
>      "t/write\.t \.\.\.\.\.\.\.\.\.\.\. ok"\,
>      "t/write\_pp\.t \.\.\.\.\.\.\.\. ok"\,
>      ""\,
>      "Test Summary Report"\,
>      "\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-"\,
>      "t/syntax\_main\.t   \(Wstat&#8203;: 6400 Tests&#8203;: 369 Failed&#8203;: 0\)"\,
>      "  Non\-zero exit status&#8203;: 25"\,
>      "  Parse errors&#8203;: Bad plan\.  You planned 1009 tests but ran 369\."\,
>       "Files=17\, Tests=100677\, 47 wallclock secs \( 0\.46 usr  7\.45 sys
> \+
> 40\.20 cusr  6\.88 csys = 54\.98 CPU\)"\,
>      "Result&#8203;: FAIL"\,
>    \]\,
>    via => "App&#8203;::cpanminus&#8203;::reporter 0\.17 \(1\.7044\)"\,
> \}
> \#\#\#\#\#
> 
> I provided a patch \(which has not yet been applied\)\.  Slaven
> subsequently observed that this was probably was related to a change
> in
> blead\.  Bisection points to&#8203;:
> 
> \#\#\#\#\#
> HEAD is now at 4288c5b93b Change REG\_INFTY to 2\*\*16\-1\, instead of
> 2\*\*15\-1
>  bad \- non\-zero exit from /tmp/GLUOqiNNx2/bin/perl \-I
> /home/jkeenan/\.cpan
>  \-MCPAN&#8203;::MyConfig \-MCPAN \-e
>  $CPAN&#8203;::Config\->\{build\_dir\}=q\{/tmp/wRUfXf4y2y\}; \-e
> install\('XML&#8203;::Easy'\);
> die unless CPAN&#8203;::Shell\->expand\(Module => 'XML&#8203;::Easy'\)\->uptodate;
> 4288c5b93b3823465d8a11e569547afd41b5d1b8 is the first bad commit
> commit 4288c5b93b3823465d8a11e569547afd41b5d1b8
> Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
> Date&#8203;:   Sun Sep 30 12&#8203;:10&#8203;:17 2018 \-0600
> 
> Change REG\_INFTY to 2\*\*16\-1\, instead of 2\*\*15\-1
> 
> This commit doubles the upper limit that unbounded regular expression
> quantifiers can match up to\.  Things like \{m\,\} "\+" and "\*" now can
> match
> up to U16\_MAX times\.
> 
> We probably should make this a 32 bit value\, but doing this doubling
> was
> easy and has fewer potential implications\.
> 
> See http&#8203;://nntp\.perl\.org/group/perl\.perl5\.porters/251413 and followups
> 
> :040000 040000 5180c35445d2089ef994fcb0634d5e0064197f50
> ca323198918692cde3d4d80cca850138f4a1e58b M    pod
> :100644 100644 ea3a0661d9ffe614167b9e183394e9d89514e1f4
> 0c5222692138a5614401d0c9b41a1183aee3bc27 M    regcomp\.h
> :040000 040000 fd6ac6b4d41de9a65f73f5ee7c61bbd4b70b9db3
> a911dcc50233fe4b31104610c85325128598f631 M    t
> bisect run success
> That took 2991 seconds\.
> \#\#\#\#\#
> 
> Thank you very much\.

Although the test failure reported in this ticket occurred during the 5\.29 development cycle\, I'm inclined to say that this should \*not\* be classified as a blocker for perl\-5\.30 \-\- at least not until we have other failure reports due to the same commit\.

I've supplied a patch to the upstream test file\.  If it's not the best patch\, I'm sure the CPAN maintainer will let us know\.

At this point\, however\, I think the benefit of the change in blead outweighs the \(minor\) CPAN breakage\.

My two cents\.

Thank you very much\.
\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @khwilliamson

On 3/8/19 4&#8203;:34 PM\, James E Keenan via RT wrote&#8203;:
> On Sat\, 02 Feb 2019 15&#8203;:18&#8203;:52 GMT\, jkeenan@&#8203;pobox\.com wrote&#8203;:
>> As originally reported in
>> https://rt.cpan.org/Ticket/Display.html?id=127416, a failure has
>> appeared during this development cycle in the test suite for CPAN
>> distribution XML\-Easy\.
>>
>> \#\#\#\#\#
>> $ ~/bin/perl/dumpjson ZEFRAM\.XML\-Easy\-0\.011\.log\.json
>> \{
>>     author => "ZEFRAM"\,
>>     dist => "XML\-Easy"\,
>>     distname => "XML\-Easy\-0\.011"\,
>>     distversion => 0\.011\,
>>     grade => "FAIL"\,
>>     prereqs => undef\,
>>     test\_output => \[
>>       "Building and testing XML\-Easy\-0\.011"\,
>>       "Building XML\-Easy"\,
>>        "cc
>>   \-I/home/jkeenan/var/tad/testing/perl\-5\.29\.4/lib/5\.29\.4/amd64\-freebsd\-
>> thread\-multi/CORE
>>   \-DVERSION=\\"0\.011\\" \-DXS\_VERSION=\\"0\.011\\" \-DPIC \-fPIC \-c
>>   \-DHAS\_FPSETMASK \-DHAS\_FLOATINGPOINT\_H \-fno\-strict\-aliasing \-pipe
>>   \-fstack\-protector\-strong \-I/usr/local/include \-D\_FORTIFY\_SOURCE=2 \-O2
>>   \-pipe \-fstack\-protector \-fno\-strict\-aliasing \-o lib/XML/Easy\.o
>> lib/XML/Easy\.c"\,
>>
>> "ExtUtils&#8203;::Mkbootstrap&#8203;::Mkbootstrap\('blib/arch/auto/XML/Easy/Easy\.bs'\)"\,
>>        "cc \-shared \-L/usr/local/lib \-fstack\-protector\-strong \-o
>> blib/arch/auto/XML/Easy/Easy\.so lib/XML/Easy\.o"\,
>>       "t/classify\.t \.\.\.\.\.\.\.\. ok"\,
>>       "t/classify\_pp\.t \.\.\.\.\. ok"\,
>>       "t/easy\_module\.t \.\.\.\.\. ok"\,
>>       "t/easy\_module\_pp\.t \.\. ok"\,
>>       "t/node\_basics\.t \.\.\.\.\. ok"\,
>>       "t/node\_basics\_pp\.t \.\. ok"\,
>>       "t/node\_object\.t \.\.\.\.\. ok"\,
>>       "t/node\_object\_pp\.t \.\. ok"\,
>>       "t/pod\_cvg\.t \.\.\.\.\.\.\.\.\. ok"\,
>>       "t/pod\_cvg\_pp\.t \.\.\.\.\.\. ok"\,
>>       "t/pod\_syn\.t \.\.\.\.\.\.\.\.\. ok"\,
>>       "t/read\.t \.\.\.\.\.\.\.\.\.\.\.\. ok"\,
>>       "t/read\_pp\.t \.\.\.\.\.\.\.\.\. ok"\,
>>        "WARNING&#8203;: Complex regular subexpression recursion limit \(65534\)
>> exceeded at t/syntax\_main\.t line 79\, \<GEN0> line 1635\."\,
>>       "\# Looks like your test exited with 25 just after 369\."\,
>>       "t/syntax\_main\.t \.\.\.\.\. "\,
>>       "Dubious\, test returned 25 \(wstat 6400\, 0x1900\)"\,
>>       "Failed 640/1009 subtests "\,
>>       "t/version\_synch\.t \.\.\. ok"\,
>>       "t/write\.t \.\.\.\.\.\.\.\.\.\.\. ok"\,
>>       "t/write\_pp\.t \.\.\.\.\.\.\.\. ok"\,
>>       ""\,
>>       "Test Summary Report"\,
>>       "\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-"\,
>>       "t/syntax\_main\.t   \(Wstat&#8203;: 6400 Tests&#8203;: 369 Failed&#8203;: 0\)"\,
>>       "  Non\-zero exit status&#8203;: 25"\,
>>       "  Parse errors&#8203;: Bad plan\.  You planned 1009 tests but ran 369\."\,
>>        "Files=17\, Tests=100677\, 47 wallclock secs \( 0\.46 usr  7\.45 sys
>> \+
>> 40\.20 cusr  6\.88 csys = 54\.98 CPU\)"\,
>>       "Result&#8203;: FAIL"\,
>>     \]\,
>>     via => "App&#8203;::cpanminus&#8203;::reporter 0\.17 \(1\.7044\)"\,
>> \}
>> \#\#\#\#\#
>>
>> I provided a patch \(which has not yet been applied\)\.  Slaven
>> subsequently observed that this was probably was related to a change
>> in
>> blead\.  Bisection points to&#8203;:
>>
>> \#\#\#\#\#
>> HEAD is now at 4288c5b93b Change REG\_INFTY to 2\*\*16\-1\, instead of
>> 2\*\*15\-1
>>   bad \- non\-zero exit from /tmp/GLUOqiNNx2/bin/perl \-I
>> /home/jkeenan/\.cpan
>>   \-MCPAN&#8203;::MyConfig \-MCPAN \-e
>>   $CPAN&#8203;::Config\->\{build\_dir\}=q\{/tmp/wRUfXf4y2y\}; \-e
>> install\('XML&#8203;::Easy'\);
>> die unless CPAN&#8203;::Shell\->expand\(Module => 'XML&#8203;::Easy'\)\->uptodate;
>> 4288c5b93b3823465d8a11e569547afd41b5d1b8 is the first bad commit
>> commit 4288c5b93b3823465d8a11e569547afd41b5d1b8
>> Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
>> Date&#8203;:   Sun Sep 30 12&#8203;:10&#8203;:17 2018 \-0600
>>
>> Change REG\_INFTY to 2\*\*16\-1\, instead of 2\*\*15\-1
>>
>> This commit doubles the upper limit that unbounded regular expression
>> quantifiers can match up to\.  Things like \{m\,\} "\+" and "\*" now can
>> match
>> up to U16\_MAX times\.
>>
>> We probably should make this a 32 bit value\, but doing this doubling
>> was
>> easy and has fewer potential implications\.
>>
>> See http&#8203;://nntp\.perl\.org/group/perl\.perl5\.porters/251413 and followups
>>
>> :040000 040000 5180c35445d2089ef994fcb0634d5e0064197f50
>> ca323198918692cde3d4d80cca850138f4a1e58b M    pod
>> :100644 100644 ea3a0661d9ffe614167b9e183394e9d89514e1f4
>> 0c5222692138a5614401d0c9b41a1183aee3bc27 M    regcomp\.h
>> :040000 040000 fd6ac6b4d41de9a65f73f5ee7c61bbd4b70b9db3
>> a911dcc50233fe4b31104610c85325128598f631 M    t
>> bisect run success
>> That took 2991 seconds\.
>> \#\#\#\#\#
>>
>> Thank you very much\.
> 
> Although the test failure reported in this ticket occurred during the 5\.29 development cycle\, I'm inclined to say that this should \*not\* be classified as a blocker for perl\-5\.30 \-\- at least not until we have other failure reports due to the same commit\.
> 
> I've supplied a patch to the upstream test file\.  If it's not the best patch\, I'm sure the CPAN maintainer will let us know\.
> 
> At this point\, however\, I think the benefit of the change in blead outweighs the \(minor\) CPAN breakage\.
> 
> My two cents\.
> 
> Thank you very much\.
> 

I added all BBC tickets to be 5\.30 blockers to ensure adequate 
discussion of them\.  I don't take a position on any of them\.  There are 
8 open BBC tickets\.

**Comment by p5pRT** [comment]
### From @khwilliamson

Removed from blockers list
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
### From @iabyn

On Wed\, Apr 24\, 2019 at 10&#8203;:21&#8203;:05AM \-0700\, Karl Williamson via RT wrote&#8203;:
> Removed from blockers list

I concur\(\*\)\.

As as aside\, I've just attached an improved patch to the rt\.cpan\.org
ticket\.

\(\*\) "I concur\, said William\. I agree completely\. If you think it's for the
best\, then of course do it\. Happy to oblige"\.
&nbsp;    \-\- good old William the Concurrer\.

\-\- 
The crew of the Enterprise encounter an alien life form which is
surprisingly neither humanoid nor made from pure energy\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#22

**Comment by jkeenan** [comment]
> ### From @iabyn
> 
> On Wed, Apr 24, 2019 at 10​:21​:05AM -0700, Karl Williamson via RT wrote​:
> 
> > Removed from blockers list
> 
> I concur(*).
> 
> As as aside, I've just attached an improved patch to the rt.cpan.org
> ticket.
> 

That [patch](https://rt.cpan.org/Ticket/Attachment/1844929/991441/syntax_main.t.diff) has not yet been applied, nor has a new CPAN release been issued.

@zefram can you take a look?

Thank you very much.
Jim Keenan

**Comment by toddr** [comment]
```diff
--- t/syntax_main.t-	2019-04-24 11:47:08.365496801 +0100
+++ t/syntax_main.t	2019-04-24 12:01:50.459442769 +0100
@@ -35,16 +35,34 @@
 
 # This code checks whether the regexp iteration limit bug (#60034) is
 # present.  The regexp match expression checks for getting the wrong
-# result with a long input, and suffices to diagnose the bug.  However,
-# running that test on a pre-5.10 perl causes the stack to grow large,
+# result with a long input, and suffices to diagnose the bug.
+# for a pattern like /X*/, where X is sub-pattern that can match variable
+# length string, e.g. (ab?), it is currently known that:
+#
+# on < 5.10.0,  the old recursive engine will crash on too long a match;
+# on < 5.29.4,  /X*/ is misinterpreted as /X{0,32767}/
+# on   5.29.4+, /X*/ is misinterpreted as /X{0,65535}/
+#
+# Running that test on a pre-5.10 perl causes the stack to grow large,
 # and if there's a limited stack size then this may overflow it and
 # cause perl to crash.  All pre-5.10 perls have the iteration limit
 # bug, so there's no need to run the proper test on those verions.
 # 5.10 fixed the stack issue, so it's safe to run the proper test there.
-my $have_iterlimit_bug = "$]" < 5.010 || do {
-	local $SIG{__WARN__} = sub { };
-	("a"x40000) !~ /\A(?:X?[a-z])*\z/;
-};
+
+my $iterlimit; # if defined, sets an upper limit for iterations
+
+if ($] < 5.010) {
+    $iterlimit = 0;
+}
+else {
+    local $SIG{__WARN__} = sub { };
+    for my $i (32767, 65535) {
+        if (("a"x($i+1)) !~ /\A(?:X?[a-z])*\z/) {
+            $iterlimit = $i;
+            last;
+        }
+    }
+}
 
 my $data_in = IO::File->new("t/read.data", "r") or die;
 my $line = $data_in->getline;
@@ -75,7 +93,7 @@
 	}
 	SKIP: {
 		skip "perl bug affects long inputs", 2
-			if $have_iterlimit_bug && length($input) >= 32766;
+                    if defined $iterlimit && length($input) >= $iterlimit;
 		is upgraded($input) =~ $recogniser{$prod}, !$syntax_error;
 		is downgraded($input) =~ $recogniser{$prod}, !$syntax_error;
 	}
```

**Comment by toddr** [comment]
If the only thing remaining is a new CPAN release and this isn't a blocker any more, what's the outstanding on this?

**Comment by toddr** [comment]
Given the blocker was removed, 5.30 is released, and there is a report to the module in question, I am closing this ticket.
