### ISSUE TITLE
bug of regex lookaround assertions?

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16894]
Migrated from [rt.perl.org#133940](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133940) (status was 'open')

Searchable as RT133940$

**Comment by p5pRT** [comment]
### From malincns@163.com

#### Created by malincns@163.com



This report is about capture group\.
I'm not sure whether it's a bug of Perl\, or an intended policy\.

string : "abab"
pattern&#8203;: /\(?&#8203;:\[^b\]\*\(?=\(b\)|\(a\)\)ab\)\*/

print defined\($1\)?"\\"$1\\""&#8203;:"undef"\,"\, "\,defined\($2\)?"\\"$2\\""&#8203;:"undef"\, if 
"abab" =~ /\(?&#8203;:\[^b\]\*\(?=\(b\)|\(a\)\)ab\)\*/;

Output&#8203;:
"b"\, "a"

Excepted output&#8203;:
undef\, "a"

Some engines output&#8203;:

Perl 5\.28\.1      "b"\, "a"
PHP 7\.3\.2      NULL\, "a"
Java 11\.0\.2      "b"\, "a" \[1\]
Ruby 2\.6\.1      nil\, "a"
Go 1\.12       \[2\]
Rust 1\.32\.0      \[2\]
Node\.js 10\.15\.1   undef\, "a"
Python 3\.7\.2      "b"\, "a" \[3\]

\[1\] seems this bug&#8203;: 
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=7145888
\[2\] doesn't support lookaround\.
\[3\] it's a bug&#8203;: https://bugs.python.org/issue35859


Another doubtful case&#8203;:

string : "ab"
pattern&#8203;: /\.\*?\(?=\(a\)|\(b\)\)b$/

print defined\($1\)?"\\"$1\\""&#8203;:"undef"\,"\, "\,defined\($2\)?"\\"$2\\""&#8203;:"undef"\, if 
"ab" =~ /\.\*?\(?=\(a\)|\(b\)\)b$/;

Output&#8203;:
"a"\, "b"

Except output&#8203;:
undef\, "b"

<details><summary>Perl Info</summary>

```

Flags:
     category=core
     severity=low

Site configuration information for perl 5.28.1:

Configured by strawberry-perl at Sun Dec  2 14:25:09 2018.

Summary of my perl5 (revision 5 version 28 subversion 1) configuration:

   Platform:
     osname=MSWin32
     osvers=10.0.17134.407
     archname=MSWin32-x64-multi-thread
     uname='Win32 strawberry-perl 5.28.1.1 #1 Sun Dec  2 14:24:00 2018 x64'
     config_args='undef'
     hint=recommended
     useposix=true
     d_sigaction=undef
     useithreads=define
     usemultiplicity=define
     use64bitint=define
     use64bitall=undef
     uselongdouble=undef
     usemymalloc=n
     default_inc_excludes_dot=define
     bincompat5005=undef
   Compiler:
     cc='gcc'
     ccflags =' -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE 
-D__USE_MINGW_ANSI_STDIO -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT 
-DPERL_IMPLICIT_SYS -DUSE_PERLIO -fwrapv -fno-strict-aliasing 
-mms-bitfields'
     optimize='-s -O2'
     cppflags='-DWIN32'
     ccversion=''
     gccversion='7.1.0'
     gccosandvers=''
     intsize=4
     longsize=4
     ptrsize=8
     doublesize=8
     byteorder=12345678
     doublekind=3
     d_longlong=define
     longlongsize=8
     d_longdbl=define
     longdblsize=16
     longdblkind=3
     ivtype='long long'
     ivsize=8
     nvtype='double'
     nvsize=8
     Off_t='long long'
     lseeksize=8
     alignbytes=8
     prototype=define
   Linker and Libraries:
     ld='g++.exe'
     ldflags ='-s -L"D:\perl\perl\lib\CORE" -L"D:\perl\c\lib"'
     libpth=D:\perl\c\lib D:\perl\c\x86_64-w64-mingw32\lib 
D:\perl\c\lib\gcc\x86_64-w64-mingw32\7.1.0
     libs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 
-ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr 
-lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
     perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool 
-lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid 
-lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
     libc=
     so=dll
     useshrplib=true
     libperl=libperl528.a
     gnulibc_version=''
   Dynamic Linking:
     dlsrc=dl_win32.xs
     dlext=xs.dll
     d_dlsymun=undef
     ccdlflags=' '
     cccdlflags=' '
     lddlflags='-mdll -s -L"D:\perl\perl\lib\CORE" -L"D:\perl\c\lib"'



@INC for perl 5.28.1:
     D:/perl/perl/site/lib
     D:/perl/perl/vendor/lib
     D:/perl/perl/lib


Environment for perl 5.28.1:
     HOME (unset)
     LANG (unset)
     LANGUAGE (unset)
     LD_LIBRARY_PATH (unset)
     LOGDIR (unset)
PATH=E:\Python37\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;E:\Program 
Files\git\bin;D:\Qt\5.9.7\mingw53_32\bin;E:\Program 
Files\Java\jdk-11.0.2"\bin;E:\Python37\Scripts\;E:\Program 
Files\TortoiseGit\bin;C:\Users\anima\.cargo\bin;C:\Users\anima\AppData\Local\Microsoft\WindowsApps;;E:\Program 
Files\Microsoft VS Code\bin
     PERL_BADLANG (unset)
     SHELL (unset)

```
</details>

**Comment by p5pRT** [comment]
### From @jkeenan

On Mon\, 18 Mar 2019 01&#8203;:19&#8203;:11 GMT\, malincns@&#8203;163\.com wrote&#8203;:
> This is a bug report for perl from malincns@&#8203;163\.com\,
> generated with the help of perlbug 1\.41 running under perl 5\.28\.1\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please describe your issue here\]
> 
> This report is about capture group\.
> I'm not sure whether it's a bug of Perl\, or an intended policy\.
> 
> string : "abab"
> pattern&#8203;: /\(?&#8203;:\[^b\]\*\(?=\(b\)|\(a\)\)ab\)\*/
> 
> print defined\($1\)?"\\"$1\\""&#8203;:"undef"\,"\, "\,defined\($2\)?"\\"$2\\""&#8203;:"undef"\,
> if
> "abab" =~ /\(?&#8203;:\[^b\]\*\(?=\(b\)|\(a\)\)ab\)\*/;
> 
> Output&#8203;:
> "b"\, "a"
> 
> Excepted output&#8203;:
> undef\, "a"
> 
> Some engines output&#8203;:
> 
> Perl 5\.28\.1      "b"\, "a"
> PHP 7\.3\.2      NULL\, "a"
> Java 11\.0\.2      "b"\, "a" \[1\]
> Ruby 2\.6\.1      nil\, "a"
> Go 1\.12       \[2\]
> Rust 1\.32\.0      \[2\]
> Node\.js 10\.15\.1   undef\, "a"
> Python 3\.7\.2      "b"\, "a" \[3\]
> 
> \[1\] seems this bug&#8203;:
> https://bugs.java.com/bugdatabase/view_bug.do?bug_id=7145888
> \[2\] doesn't support lookaround\.
> \[3\] it's a bug&#8203;: https://bugs.python.org/issue35859
> 
> 
> Another doubtful case&#8203;:
> 
> string : "ab"
> pattern&#8203;: /\.\*?\(?=\(a\)|\(b\)\)b$/
> 
> print defined\($1\)?"\\"$1\\""&#8203;:"undef"\,"\, "\,defined\($2\)?"\\"$2\\""&#8203;:"undef"\,
> if
> "ab" =~ /\.\*?\(?=\(a\)|\(b\)\)b$/;
> 
> Output&#8203;:
> "a"\, "b"
> 
> Except output&#8203;:
> undef\, "b"
> 

In each of these two cases\, can you explain \-\- in your own words\, and without reference to any other language's regex engines \-\- why you have come to the expectations you have?

Thank you very much\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From malincns@163.com

在 19\-3\-20 21&#8203;:14\, James E Keenan via RT 写道&#8203;:
> On Mon\, 18 Mar 2019 01&#8203;:19&#8203;:11 GMT\, malincns@&#8203;163\.com wrote&#8203;:
>> This is a bug report for perl from malincns@&#8203;163\.com\,
>> generated with the help of perlbug 1\.41 running under perl 5\.28\.1\.
>>
>>
>> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
>> \[Please describe your issue here\]
>>
>> This report is about capture group\.
>> I'm not sure whether it's a bug of Perl\, or an intended policy\.
>>
>> string : "abab"
>> pattern&#8203;: /\(?&#8203;:\[^b\]\*\(?=\(b\)|\(a\)\)ab\)\*/
>>
>> print defined\($1\)?"\\"$1\\""&#8203;:"undef"\,"\, "\,defined\($2\)?"\\"$2\\""&#8203;:"undef"\,
>> if
>> "abab" =~ /\(?&#8203;:\[^b\]\*\(?=\(b\)|\(a\)\)ab\)\*/;
>>
>> Output&#8203;:
>> "b"\, "a"
>>
>> Excepted output&#8203;:
>> undef\, "a"
>>
>> Some engines output&#8203;:
>>
>> Perl 5\.28\.1      "b"\, "a"
>> PHP 7\.3\.2      NULL\, "a"
>> Java 11\.0\.2      "b"\, "a" \[1\]
>> Ruby 2\.6\.1      nil\, "a"
>> Go 1\.12       \[2\]
>> Rust 1\.32\.0      \[2\]
>> Node\.js 10\.15\.1   undef\, "a"
>> Python 3\.7\.2      "b"\, "a" \[3\]
>>
>> \[1\] seems this bug&#8203;:
>> https://bugs.java.com/bugdatabase/view_bug.do?bug_id=7145888
>> \[2\] doesn't support lookaround\.
>> \[3\] it's a bug&#8203;: https://bugs.python.org/issue35859
>>
>>
>> Another doubtful case&#8203;:
>>
>> string : "ab"
>> pattern&#8203;: /\.\*?\(?=\(a\)|\(b\)\)b$/
>>
>> print defined\($1\)?"\\"$1\\""&#8203;:"undef"\,"\, "\,defined\($2\)?"\\"$2\\""&#8203;:"undef"\,
>> if
>> "ab" =~ /\.\*?\(?=\(a\)|\(b\)\)b$/;
>>
>> Output&#8203;:
>> "a"\, "b"
>>
>> Except output&#8203;:
>> undef\, "b"
>>
> In each of these two cases\, can you explain \-\- in your own words\, and without reference to any other language's regex engines \-\- why you have come to the expectations you have?
>
> Thank you very much\.

Please see these two cases&#8203;:

1\,

print defined\($1\)?"\\"$1\\""&#8203;:"undef"\,"\, "\,defined\($2\)?"\\"$2\\""&#8203;:"undef"\,
if "abc" =~ /\.\*?\(?&#8203;:\(a\)|\(b\)\)c/;

Output&#8203;: undef\, "b"

/\(a\)c/ this pattern can't match\, so $1 is undef\.

2\,

print defined\($1\)?"\\"$1\\""&#8203;:"undef"\,"\, "\,defined\($2\)?"\\"$2\\""&#8203;:"undef"\,
if "ab" =~ /\.\*?\(?=\(a\)|\(b\)\)b/;

Output&#8203;: "a"\, "b"

/\(?=\(a\)\)b/ this pattern can't match too\, but $1 is not undef\,

It seems a bit inconsistent\.

**Comment by p5pRT** [comment]
### From @jkeenan

On Wed\, 20 Mar 2019 14&#8203;:08&#8203;:07 GMT\, malincns@&#8203;163\.com wrote&#8203;:
> 在 19\-3\-20 21&#8203;:14\, James E Keenan via RT 写道&#8203;:
> > On Mon\, 18 Mar 2019 01&#8203;:19&#8203;:11 GMT\, malincns@&#8203;163\.com wrote&#8203;:
> >> This is a bug report for perl from malincns@&#8203;163\.com\,
> >> generated with the help of perlbug 1\.41 running under perl 5\.28\.1\.
> >>
> >>
> >> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> >> \[Please describe your issue here\]
> >>
> >> This report is about capture group\.
> >> I'm not sure whether it's a bug of Perl\, or an intended policy\.
> >>
> >> string : "abab"
> >> pattern&#8203;: /\(?&#8203;:\[^b\]\*\(?=\(b\)|\(a\)\)ab\)\*/
> >>
> >> print defined\($1\)?"\\"$1\\""&#8203;:"undef"\,"\,
> >> "\,defined\($2\)?"\\"$2\\""&#8203;:"undef"\,
> >> if
> >> "abab" =~ /\(?&#8203;:\[^b\]\*\(?=\(b\)|\(a\)\)ab\)\*/;
> >>
> >> Output&#8203;:
> >> "b"\, "a"
> >>
> >> Excepted output&#8203;:
> >> undef\, "a"
> >>
> >> Some engines output&#8203;:
> >>
> >> Perl 5\.28\.1      "b"\, "a"
> >> PHP 7\.3\.2      NULL\, "a"
> >> Java 11\.0\.2      "b"\, "a" \[1\]
> >> Ruby 2\.6\.1      nil\, "a"
> >> Go 1\.12       \[2\]
> >> Rust 1\.32\.0      \[2\]
> >> Node\.js 10\.15\.1   undef\, "a"
> >> Python 3\.7\.2      "b"\, "a" \[3\]
> >>
> >> \[1\] seems this bug&#8203;:
> >> https://bugs.java.com/bugdatabase/view_bug.do?bug_id=7145888
> >> \[2\] doesn't support lookaround\.
> >> \[3\] it's a bug&#8203;: https://bugs.python.org/issue35859
> >>
> >>
> >> Another doubtful case&#8203;:
> >>
> >> string : "ab"
> >> pattern&#8203;: /\.\*?\(?=\(a\)|\(b\)\)b$/
> >>
> >> print defined\($1\)?"\\"$1\\""&#8203;:"undef"\,"\,
> >> "\,defined\($2\)?"\\"$2\\""&#8203;:"undef"\,
> >> if
> >> "ab" =~ /\.\*?\(?=\(a\)|\(b\)\)b$/;
> >>
> >> Output&#8203;:
> >> "a"\, "b"
> >>
> >> Except output&#8203;:
> >> undef\, "b"
> >>
> > In each of these two cases\, can you explain \-\- in your own words\, and
> > without reference to any other language's regex engines \-\- why you
> > have come to the expectations you have?
> >
> > Thank you very much\.
> 
> Please see these two cases&#8203;:
> 
> 1\,
> 
> print defined\($1\)?"\\"$1\\""&#8203;:"undef"\,"\, "\,defined\($2\)?"\\"$2\\""&#8203;:"undef"\,
> if "abc" =~ /\.\*?\(?&#8203;:\(a\)|\(b\)\)c/;
> 
> Output&#8203;: undef\, "b"
> 
> /\(a\)c/ this pattern can't match\, so $1 is undef\.
> 
> 2\,
> 
> print defined\($1\)?"\\"$1\\""&#8203;:"undef"\,"\, "\,defined\($2\)?"\\"$2\\""&#8203;:"undef"\,
> if "ab" =~ /\.\*?\(?=\(a\)|\(b\)\)b/;
> 
> Output&#8203;: "a"\, "b"
> 
> /\(?=\(a\)\)b/ this pattern can't match too\, but $1 is not undef\,
> 
> It seems a bit inconsistent\.

I doubt there are bugs here\, but understanding what is going on with respect to the interaction of positive\-lookahead assertions and capture groups is very tricky\.  There are things I don't understand myself\.

To be able to consider different cases\, I've written a subroutine to handle each combination of string and pattern which you have mentioned in your two posts so far\.  Please see attached program 133940\-regex\.pl\.  When I run it\, I get this output&#8203;:

\#\#\#\#\#
Case&#8203;:    1
string&#8203;:  abab
pattern&#8203;: \(?^u&#8203;:\(?&#8203;:\[^b\]\*\(?=\(b\)|\(a\)\)ab\)\*\)
pre\-match&#8203;: |match&#8203;: abab|post\-match&#8203;: 
$1&#8203;: b
$2&#8203;: a

Case&#8203;:    2
string&#8203;:  ab
pattern&#8203;: \(?^u&#8203;:\.\*?\(?=\(a\)|\(b\)\)b$\)
pre\-match&#8203;: |match&#8203;: ab|post\-match&#8203;: 
$1&#8203;: a
$2&#8203;: b

Case&#8203;:    3
string&#8203;:  abc
pattern&#8203;: \(?^u&#8203;:\.\*?\(?&#8203;:\(a\)|\(b\)\)c\)
pre\-match&#8203;: |match&#8203;: abc|post\-match&#8203;: 
$1&#8203;: undef
$2&#8203;: b

Case&#8203;:    4
string&#8203;:  abc
pattern&#8203;: \(?^u&#8203;:\(a\)c\)
string 'abc' did not match pattern '\(?^u&#8203;:\(a\)c\)'

Case&#8203;:    5
string&#8203;:  ab
pattern&#8203;: \(?^u&#8203;:\.\*?\(?=\(a\)|\(b\)\)b\)
pre\-match&#8203;: |match&#8203;: ab|post\-match&#8203;: 
$1&#8203;: a
$2&#8203;: b

Case&#8203;:    6
string&#8203;:  ab
pattern&#8203;: \(?^u&#8203;:\(?=\(a\)\)b\)
string 'ab' did not match pattern '\(?^u&#8203;:\(?=\(a\)\)b\)'

\#\#\#\#\#

The things I myself don't understand are&#8203;:

\* In Case 3\, if the string matches the pattern\, and if that pattern includes captures\, how can any element in this list of captures be undefined?

\* In Case 6\, why doesn't the string match the pattern?

Can someone on list clarify?

Thank you very much\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @jkeenan

[133940-regex.pl](https://rt-archive.perl.org/perl5/Ticket/Attachment/1620089/834183/133940-regex.pl)

**Comment by p5pRT** [comment]
### From @iabyn

On Wed\, Mar 20\, 2019 at 08&#8203;:49&#8203;:21AM \-0700\, James E Keenan via RT wrote&#8203;:
> > >> This report is about capture group\.
> > >> I'm not sure whether it's a bug of Perl\, or an intended policy\.
> > >>
> > >> string : "abab"
> > >> pattern&#8203;: /\(?&#8203;:\[^b\]\*\(?=\(b\)|\(a\)\)ab\)\*/
> > >>
> > >> print defined\($1\)?"\\"$1\\""&#8203;:"undef"\,"\,
> > >> "\,defined\($2\)?"\\"$2\\""&#8203;:"undef"\,
> > >> if
> > >> "abab" =~ /\(?&#8203;:\[^b\]\*\(?=\(b\)|\(a\)\)ab\)\*/;
> > >>
> > >> Output&#8203;:
> > >> "b"\, "a"
> > >>
> > >> Excepted output&#8203;:
> > >> undef\, "a"

This looks to be a variant of

&nbsp;    \[perl \#133352\] Ancient Regex Regression


\-\- 
It's not that I'm afraid to die\, I just don't want to be there when it
happens\.
&nbsp;    \-\- Woody Allen

**Comment by khwilliamson** [comment]
This has been fixed by

commit acababb42be12ff2986b73c1bfa963b70bb5d54e
Author: Yves Orton <demerphq@gmail.com>
Date:   Mon Jan 9 22:34:13 2023 +0100

    regexec.c - teach BRANCH and BRANCHJ nodes to reset capture buffers
    
    In /((a)(b)|(a))+/ we should not end up with $2 and $4 being set at
    the same time. When a branch fails it should reset any capture buffers
    that might be touched by its branch.
