### ISSUE TITLE
pod/perlhacktips.pod: misleading instructions for AddressSanitizer

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16910]
Migrated from [rt.perl.org#133965](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133965) (status was 'open')

Searchable as RT133965$

**Comment by p5pRT** [comment]
### From @jkeenan

Today Karl Williamson and I were discussing some as yet inexplicable 
smoke\-test results in FreeBSD\-13\.  He advised me to build with 
AddressSanitizer 
\(https://github.com/google/sanitizers/wiki/AddressSanitizer) and pointed 
to pod/perlhacktips\.pod for guidance\.  The relevant section of the 
documentation is&#8203;:

\#\#\#\#\#
&nbsp;  AddressSanitizer
&nbsp;   AddressSanitizer is a clang and gcc extension\, included in
&nbsp;   clang since v3\.1 and gcc since v4\.8\. It checks illegal
&nbsp;   heap pointers\, global pointers\, stack pointers and use
&nbsp;   after free errors\, and is fast enough that you can easily
&nbsp;   compile your debugging or optimized perl with it\. It does
&nbsp;   not check memory leaks though\. AddressSanitizer is
&nbsp;   available for Linux\, Mac OS X and soon on Windows\.

&nbsp;   To build perl with AddressSanitizer\, your Configure
&nbsp;   invocation should look like&#8203;:

&nbsp;       sh Configure \-des \-Dcc=clang \\
&nbsp;          \-Accflags=\-faddress\-sanitizer \-Aldflags=\-faddress\-sanitizer \\
&nbsp;          \-Alddlflags=\-shared\\ \-faddress\-sanitizer

&nbsp;   where these arguments mean&#8203;:

&nbsp;   \*   \-Dcc=clang

&nbsp;       This should be replaced by the full path to your clang
&nbsp;       executable if it is not in your path\.

&nbsp;   \*   \-Accflags=\-faddress\-sanitizer

&nbsp;       Compile perl and extensions sources with
&nbsp;       AddressSanitizer\.

&nbsp;   \*   \-Aldflags=\-faddress\-sanitizer

&nbsp;       Link the perl executable with AddressSanitizer\.

&nbsp;   \*   \-Alddlflags=\-shared\\ \-faddress\-sanitizer

&nbsp;       Link dynamic extensions with AddressSanitizer\. You
&nbsp;       must manually specify "\-shared" because using
&nbsp;       "\-Alddlflags=\-shared" will prevent Configure from
&nbsp;       setting a default value for "lddlflags"\, which usually
&nbsp;       contains "\-shared" \(at least on Linux\)\.
\#\#\#\#\#

Note the repeated use of the string 'address\-sanitizer'\.  Based on that\, 
I invoked Configure as follows&#8203;:

\#\#\#\#\#
sh \./Configure \-des \-Dusedevel \-Duseithreads \-Dcc=clang \\
&nbsp;        \-Accflags=\-faddress\-sanitizer \-Aldflags=\-faddress\-sanitizer \\
&nbsp;        \-Alddlflags=\-shared\\ \-faddress\-sanitizer
\#\#\#\#\#

\./Configure quickly failed\.

\#\#\#\#\#
First let's make sure your kit is complete\.  Checking\.\.\.

\[snip unproblematic output\]

Operating system name? \[freebsd\]
Operating system version? \[13\.0\-current\]
Installation prefix to use? \(~name ok\) \[/usr/local\]
AFS does not seem to be running\.\.\.
What installation prefix should I use for installing files? \(~name ok\)
\[/usr/local\]
Getting the current patchlevel\.\.\.
Build a threading Perl? \[y\]
Use which C compiler? \[clang\]
clang&#8203;: error&#8203;: unknown argument&#8203;: '\-faddress\-sanitizer'
clang&#8203;: error&#8203;: unknown argument&#8203;: '\-faddress\-sanitizer'
Uh\-oh\, the C compiler 'clang' doesn't seem to be working\.
\./trygcc&#8203;: gcc&#8203;: not found
clang&#8203;: error&#8203;: unknown argument&#8203;: '\-faddress\-sanitizer'
clang&#8203;: error&#8203;: unknown argument&#8203;: '\-faddress\-sanitizer'
Uh\-oh\, the C compiler 'clang' doesn't seem to be working\.
You need to find a working C compiler\.
Either \(purchase and\) install the C compiler supplied by your OS vendor\,
or for a free C compiler try http&#8203;://gcc\.gnu\.org/
I cannot continue any further\, aborting\.
\#\#\#\#\#

I consulted the AddressSanitizer github page cited above as well as some 
code Karl had sent me which he uses to build perl with AddressSanitizer\. 
&nbsp;  On that basis I next called&#8203;:

\#\#\#\#\#
sh \./Configure \-des \-Dusedevel \-Duseithreads \-Dcc=clang \\
&nbsp;        \-Accflags=\-fsanitize=address \-Aldflags=\-fsanitize=address \\
&nbsp;        \-Alddlflags=\-shared\\ \-fsanitize=address
\#\#\#\#\#

Note that the string used in 3 places is now&#8203;: '\-fsanitize=address'\.  The 
two words are reversed and are joined with an '=' sign rather than a 
hyphen\.  Using this syntax\, \./Configure completed\, as did 'make'\.

The documentation in pod/perlhacktips\.pod was written in 2012\.  It is 
misleading and needs to be reviewed\.

Thank you very much\.
Jim Keenan

perl perl perl

**Comment by p5pRT** [comment]
### From @jkeenan

On Fri\, 29 Mar 2019 21&#8203;:44&#8203;:22 GMT\, jkeenan@&#8203;pobox\.com wrote&#8203;:
> Today Karl Williamson and I were discussing some as yet inexplicable 
> smoke\-test results in FreeBSD\-13\.  He advised me to build with 
> AddressSanitizer 
> \(https://github.com/google/sanitizers/wiki/AddressSanitizer) and pointed 
> to pod/perlhacktips\.pod for guidance\.  The relevant section of the 
> documentation is&#8203;:
> 
> \#\#\#\#\#
>   AddressSanitizer
>    AddressSanitizer is a clang and gcc extension\, included in
>    clang since v3\.1 and gcc since v4\.8\. It checks illegal
>    heap pointers\, global pointers\, stack pointers and use
>    after free errors\, and is fast enough that you can easily
>    compile your debugging or optimized perl with it\. It does
>    not check memory leaks though\. AddressSanitizer is
>    available for Linux\, Mac OS X and soon on Windows\.
> 
>    To build perl with AddressSanitizer\, your Configure
>    invocation should look like&#8203;:
> 
>        sh Configure \-des \-Dcc=clang \\
>           \-Accflags=\-faddress\-sanitizer \-Aldflags=\-faddress\-sanitizer \\
>           \-Alddlflags=\-shared\\ \-faddress\-sanitizer
> 
>    where these arguments mean&#8203;:
> 
>    \*   \-Dcc=clang
> 
>        This should be replaced by the full path to your clang
>        executable if it is not in your path\.
> 
>    \*   \-Accflags=\-faddress\-sanitizer
> 
>        Compile perl and extensions sources with
>        AddressSanitizer\.
> 
>    \*   \-Aldflags=\-faddress\-sanitizer
> 
>        Link the perl executable with AddressSanitizer\.
> 
>    \*   \-Alddlflags=\-shared\\ \-faddress\-sanitizer
> 
>        Link dynamic extensions with AddressSanitizer\. You
>        must manually specify "\-shared" because using
>        "\-Alddlflags=\-shared" will prevent Configure from
>        setting a default value for "lddlflags"\, which usually
>        contains "\-shared" \(at least on Linux\)\.
> \#\#\#\#\#
> 
> Note the repeated use of the string 'address\-sanitizer'\.  Based on that\, 
> I invoked Configure as follows&#8203;:
> 
> \#\#\#\#\#
> sh \./Configure \-des \-Dusedevel \-Duseithreads \-Dcc=clang \\
>         \-Accflags=\-faddress\-sanitizer \-Aldflags=\-faddress\-sanitizer \\
>         \-Alddlflags=\-shared\\ \-faddress\-sanitizer
> \#\#\#\#\#
> 
> \./Configure quickly failed\.
> 
> \#\#\#\#\#
> First let's make sure your kit is complete\.  Checking\.\.\.
> 
> \[snip unproblematic output\]
> 
> Operating system name? \[freebsd\]
> Operating system version? \[13\.0\-current\]
> Installation prefix to use? \(~name ok\) \[/usr/local\]
> AFS does not seem to be running\.\.\.
> What installation prefix should I use for installing files? \(~name ok\)
> \[/usr/local\]
> Getting the current patchlevel\.\.\.
> Build a threading Perl? \[y\]
> Use which C compiler? \[clang\]
> clang&#8203;: error&#8203;: unknown argument&#8203;: '\-faddress\-sanitizer'
> clang&#8203;: error&#8203;: unknown argument&#8203;: '\-faddress\-sanitizer'
> Uh\-oh\, the C compiler 'clang' doesn't seem to be working\.
> \./trygcc&#8203;: gcc&#8203;: not found
> clang&#8203;: error&#8203;: unknown argument&#8203;: '\-faddress\-sanitizer'
> clang&#8203;: error&#8203;: unknown argument&#8203;: '\-faddress\-sanitizer'
> Uh\-oh\, the C compiler 'clang' doesn't seem to be working\.
> You need to find a working C compiler\.
> Either \(purchase and\) install the C compiler supplied by your OS vendor\,
> or for a free C compiler try http&#8203;://gcc\.gnu\.org/
> I cannot continue any further\, aborting\.
> \#\#\#\#\#
> 
> I consulted the AddressSanitizer github page cited above as well as some 
> code Karl had sent me which he uses to build perl with AddressSanitizer\. 
>   On that basis I next called&#8203;:
> 
> \#\#\#\#\#
> sh \./Configure \-des \-Dusedevel \-Duseithreads \-Dcc=clang \\
>         \-Accflags=\-fsanitize=address \-Aldflags=\-fsanitize=address \\
>         \-Alddlflags=\-shared\\ \-fsanitize=address
> \#\#\#\#\#
> 
> Note that the string used in 3 places is now&#8203;: '\-fsanitize=address'\.  The 
> two words are reversed and are joined with an '=' sign rather than a 
> hyphen\.  Using this syntax\, \./Configure completed\, as did 'make'\.
> 
> The documentation in pod/perlhacktips\.pod was written in 2012\.  It is 
> misleading and needs to be reviewed\.
> 

Is there anyone familiar with address\-sanitizer who could confirm my evaluation of our documentation above?

Thank you very much\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Oct 13\, 2019 at 11&#8203;:10&#8203;:04AM \-0700\, James E Keenan via RT wrote&#8203;:
> Is there anyone familiar with address\-sanitizer who could confirm my
> evaluation of our documentation above?

It should indeed be \-fsanitize=address

\-\- 
31 Dec 1661&#8203;: "I have newly taken a solemne oath about abstaining from plays"\.
 1 Jan 1662&#8203;: "And after \.\.\. we went by coach to the play"\.
&nbsp;    \-\- The Diary of Samuel Pepys

**Comment by richardleach** [comment]
@jkeenan does #17834 cover all the points you wanted addressing in this issue or is anything still outstanding?

**Comment by jkeenan** [comment]
Yes, as long as the code examples are correct, then my immediate concerns are satisfied.

I have just now built perl with AddressSanitizer in the same FreeBSD-13 VM from which I submitted my original report.
```
sh ./Configure -des -Dusedevel -Duseithreads -Dcc=clang \
  -Accflags=-fsanitize=address -Aldflags=-fsanitize=address \
  -Alddlflags=-shared\ -fsanitize=address
```
We could, of course, mention that AddressSanitizer is also available on FreeBSD, as documented [here](https://github.com/google/sanitizers/wiki/AddressSanitizer#introduction) and shown by the fact that I just build with it there.

**Comment by xsawyerx** [comment]
Clang website shows the supported OS:

https://clang.llvm.org/docs/AddressSanitizer.html#supported-platforms

OpenBSD is not one, but FreeBSD and NetBSD are supported, as well as Android ARM. What I want to avoid is having to play "catch-up" with the documentation on what's supported with the risk of being obsolete. (If OpenBSD introduces it prior to 5.32.1, we need to chase it down with the documentation.

I would much rather have the docs saying "ASan is supported on several major operating system. Please review the list provided by compilers, such as Clang (link)." There also seems to be the official documentation (including supported OS) here: https://github.com/google/sanitizers/wiki/AddressSanitizer so that's probably better to point to. (Hopefully, it's maintained.)
