### ISSUE TITLE
[Win32] Latest devel release (5.29.9) won't build if _WIN32_WINNT >= 0x0600

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16917]
Migrated from [rt.perl.org#133974](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133974) (status was 'open')

Searchable as RT133974$

**Comment by p5pRT** [comment]
### From @sisyphus

This will affect more than perl\-5\.29\.9 \- it's just that perl\-5\.29\.9 is the
first version of perl that I've tried to build using a new gcc\-8\.2\.1
toolchain built by the MSYS2 project\.

BTW\, where is \_WIN32\_WINNT actually being defined ?
I couldn't find it \- but with this 8\.2\.1 toolchain it's being defined to
0x0601\, while earlier compilers set it to 0x0502\.

When it's >= 0x0600\, extra stuff gets defined in winsock2\.h \(including the
symbol POLLWRBAND\)\, and that prevents dist/IO from compiling\.

A similar thing also happens with cpan/Socket\, though I'm not sure whether
that also traces back to winsock2\.h or whether the problem arises
elsewhere\. \(I didn't check on that\.\)

My workaround was to insert&#8203;:

\#undef \_WIN32\_WINNT
\#define \_WIN32\_WINNT 0x0502

at the top of&#8203;:

 dist/IO/IO\.xs
 dist/IO/poll\.c
 cpan/Socket/Socket\.xs

and that enables the build of 5\.29\.9 to proceed normally\.

But is that the correct approach to dealing with this issue ?
Or should we be looking at modifying the perl source such that it doesn't
need to reduce the value of  \_WIN32\_WINNT whenever it's >= 0x0600 ?

Cheers\,
Rob

**Comment by p5pRT** [comment]
### From @xenu

On Mon\, 01 Apr 2019 21&#8203;:29&#8203;:50 \-0700
"sisyphus \\\(via RT\\\)" \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:

> \# New Ticket Created by  sisyphus 
> \# Please include the string&#8203;:  \[perl \#133974\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133974 >
> 
> 
> This will affect more than perl\-5\.29\.9 \- it's just that perl\-5\.29\.9 is the
> first version of perl that I've tried to build using a new gcc\-8\.2\.1
> toolchain built by the MSYS2 project\.
> 
> BTW\, where is \_WIN32\_WINNT actually being defined ?
> I couldn't find it \- but with this 8\.2\.1 toolchain it's being defined to
> 0x0601\, while earlier compilers set it to 0x0502\.

It has nothing to do with the version of MinGW\. It can be set using
\-\-with\-default\-win32\-winnt switch in one of MinGW configure scripts and\, if
you build it by yourself\, the default is still 0x0502&#8203;:

https://github.com/mirror/mingw-w64/blob/master/mingw-w64-headers/configure.ac#L144

\(the switch affects the \_WIN32\_WINNT definition in \_mingw\.h file\)

> 
> When it's >= 0x0600\, extra stuff gets defined in winsock2\.h \(including the
> symbol POLLWRBAND\)\, and that prevents dist/IO from compiling\.
> 
> A similar thing also happens with cpan/Socket\, though I'm not sure whether
> that also traces back to winsock2\.h or whether the problem arises
> elsewhere\. \(I didn't check on that\.\)
> 
> My workaround was to insert&#8203;:
> 
> \#undef \_WIN32\_WINNT
> \#define \_WIN32\_WINNT 0x0502
> 
> at the top of&#8203;:
> 
>  dist/IO/IO\.xs
>  dist/IO/poll\.c
>  cpan/Socket/Socket\.xs
> 
> and that enables the build of 5\.29\.9 to proceed normally\.
> 
> But is that the correct approach to dealing with this issue ?
> Or should we be looking at modifying the perl source such that it doesn't
> need to reduce the value of  \_WIN32\_WINNT whenever it's >= 0x0600 ?
> 
> Cheers\,
> Rob

On non\-windows systems we set macros such as \_GNU\_SOURCE\, \_XOPEN\_SOURCE
or \_POSIX\_SOURCE in ccflags\. Those macros do the same thing as
\_WIN32\_WINNT\, that is\, they control the visibility of certain things in
the system headers\. IMO we should the same thing with \_WIN32\_WINNT\.

The only problem with this approach is the fact that it will force our
\_WIN32\_WINNT define on CPAN XS modules\, but unfortunately\, I don't think
it can be avoided\.

BTW\, in the future we should consider dropping winxp support and
defining \_WIN32\_WINNT as 0x0601\, but that's another conversation\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by sisyphus** [comment]
I was about to close this issue, but discovered that I don't have the permissions for that.
If someone else can close it, then please do so (with my blessing).
