### ISSUE TITLE
ExtUtils::ParseXS release, plus bug with clang++ on 5.14-5.16 on EUPXS 3.04_01+

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16916]
Migrated from [rt.perl.org#133973](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133973) (status was 'open')

Searchable as RT133973$

**Comment by p5pRT** [comment]
### From ej_zg@hotmail.com

ExtUtils&#8203;::ParseXS is 3\.40 in perl blead\, 3\.35 on CPAN\. Can someone release it?

Also\, there is a problem with v3\.04\_01\+ on 5\.14\-5\.16 on clang\+\+\, which I will expand on using the web UI\.

**Comment by p5pRT** [comment]
### From @mohawk2

On Mon\, 01 Apr 2019 10&#8203;:09&#8203;:03 \-0700\, ej\_zg@&#8203;hotmail\.com wrote&#8203;:
> ExtUtils&#8203;::ParseXS is 3\.40 in perl blead\, 3\.35 on CPAN\. Can someone
> release it?

I'm content to be co\-maint on this if wished\, by the way\, to go with EU&#8203;::CppGuess etc\.

> Also\, there is a problem with v3\.04\_01\+ on 5\.14\-5\.16 on clang\+\+\, which
> I will expand on using the web UI\.

To expand slightly&#8203;: the problem was exposed by this CPANTesters report&#8203;: http&#8203;://www\.cpantesters\.org/cpan/report/4d4205da\-541f\-11e9\-9066\-e374b0ba08e8

Basically\, perl\.h on 5\.14 didn't correctly detect that dNOOP should use a C\+\+\-style thing for clang\, but the right thing happens if HASATTRIBUTE\_UNUSED is manually undefined after config\.h\, and before perl\.h&#8203;: see https://github.com/tsee/extutils-cppguess/commit/07ec6d78221accea959a165119f757ff0aecdb26

On 5\.16\, that didn't work\, but redefining dNOOP after perl\.h does work&#8203;: https://github.com/tsee/extutils-cppguess/commit/c622bb7c033ca697a544db11864d6d16e21fe668

On 5\.18\, nothing is necessary\.

If it is desired\, I can look at making EUPXS do the right thing \(obviously that would require further checking for C\+\+\, which is redundant for this already\-guaranteed\-C\+\+ bit of XS\)\. Let me know\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @mohawk2

Deafening silence on this so far\.

I attach a bug\-fix for when a typemap does not have the type\. In trying to create the error message\, it currently calls $type\->xstype\. Unfortunately\, as shown by my making the patch with 4 lines of context not 3\, $type is a string\. This therefore blows up\.

Please apply it\.

Please release ExtUtils&#8203;::ParseXS on CPAN\.

**Comment by p5pRT** [comment]
### From @mohawk2

<details><summary>0001-fix-obvious-error-message-bug.patch</summary>

```diff
From f29a139cef1a63ec5b3d3a7b5d0448aa99fe06ad Mon Sep 17 00:00:00 2001
From: Ed J <mohawk2@users.noreply.github.com>
Date: Sun, 21 Apr 2019 22:18:13 +0100
Subject: [PATCH] fix obvious error-message bug

---
 dist/ExtUtils-ParseXS/lib/ExtUtils/ParseXS.pm | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/dist/ExtUtils-ParseXS/lib/ExtUtils/ParseXS.pm b/dist/ExtUtils-ParseXS/lib/ExtUtils/ParseXS.pm
index fba7f4d73d..05030a4d94 100644
--- a/dist/ExtUtils-ParseXS/lib/ExtUtils/ParseXS.pm
+++ b/dist/ExtUtils-ParseXS/lib/ExtUtils/ParseXS.pm
@@ -1903,9 +1903,9 @@ sub generate_init {
   $type =~ tr/:/_/ unless $self->{RetainCplusplusHierarchicalTypes};
 
   my $inputmap = $typemaps->get_inputmap(xstype => $xstype);
   if (not defined $inputmap) {
-    $self->blurt("Error: No INPUT definition for type '$type', typekind '" . $type->xstype . "' found");
+    $self->blurt("Error: No INPUT definition for type '$type', typekind '" . $xstype . "' found");
     return;
   }
 
   my $expr = $inputmap->cleaned_code;
-- 
2.17.1


```
</details>

**Comment by mohawk2** [comment]
@jkeenan Thanks for your attention on this! What would be the process on getting ExtUtils::ParseXS released on CPAN, which doesn't seem to have happened yet?

**Comment by jkeenan** [comment]
> @jkeenan Thanks for your attention on this! What would be the process on getting ExtUtils::ParseXS released on CPAN, which doesn't seem to have happened yet?

@rjbs @xsawyerx

**Comment by mohawk2** [comment]
Please can the current EUPXS be released on CPAN?

**Comment by xsawyerx** [comment]
I'm willing to cut a release.

**Comment by mohawk2** [comment]
> I'm willing to cut a release.

Great!
