### ISSUE TITLE
BBC Commit 73b9584 breaks Roman::Unicode

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16915]
Migrated from [rt.perl.org#133970](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133970) (status was 'open')

Searchable as RT133970$

**Comment by p5pRT** [comment]
### From @khwilliamson

The commit involved moving user-defined properties into core. It is a
separate issue from #16850 which stems from the same commit, but
the cause is actually that module inadvertently relying on a bug that
this commit fixes.

**Comment by p5pRT** [comment]
### From @khwilliamson

On Sun\, 31 Mar 2019 21&#8203;:50&#8203;:32 \-0700\, public@&#8203;khwilliamson\.com wrote&#8203;:
> This is a bug report for perl from khw@&#8203;khw\-XPS\-
> 8930\.hsd1\.co\.comcast\.net\,
> generated with the help of perlbug 1\.40 running under perl 5\.26\.1\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> The commit involved moving user\-defined properties into core\.  It is a
> separate issue from \[perl \#133860\] which stems from the same commit\,
> but
> the cause is actually that module inadvertently relying on a bug that
> this commit fixes\.
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \-\-\-
> Flags&#8203;:
>      category=core
>      severity=high
> \-\-\-

I wrote this ticket with the system perl info instead of blead's\.  But it is actually irrelevant\.

Tony Cook\+\+ tracked down the cause of this for me\.  The stack needed to pushed/popped around the call to the user\-defined perl subroutine\.  But then he wanted to see what the code this replaces does\, and it turns out it does several more things\, which are similar to what the code block regex code does\, which is similar to what other places do that call out to perl code\.

But not exact

So is it a bug that for code blocks\, there is no SAVEHINTS\, or that it pushes \(the undocumented\) PERLSI\_REQUIRE instead of \(the undocumented\) PERLSI\_MAGIC?  And when should one use save\_re\_context\(\)?  My guess is that SAVETMPS and FREETMPS are just niceties\, but I don't know\.

None of this is obvious to me\.  My guess is that the disparities in calling things are actually bugs\, and there should be a routine that standardizes things\, or at least documentation as to what to do\.

\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Sun\, 31 Mar 2019 22&#8203;:12&#8203;:02 \-0700\, khw wrote&#8203;:
> On Sun\, 31 Mar 2019 21&#8203;:50&#8203;:32 \-0700\, public@&#8203;khwilliamson\.com wrote&#8203;:
> > This is a bug report for perl from khw@&#8203;khw\-XPS\-
> > 8930\.hsd1\.co\.comcast\.net\,
> > generated with the help of perlbug 1\.40 running under perl 5\.26\.1\.
> >
> >
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > The commit involved moving user\-defined properties into core\.  It is
> > a
> > separate issue from \[perl \#133860\] which stems from the same commit\,
> > but
> > the cause is actually that module inadvertently relying on a bug that
> > this commit fixes\.
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > \-\-\-
> > Flags&#8203;:
> >      category=core
> >      severity=high
> > \-\-\-
> 
> I wrote this ticket with the system perl info instead of blead's\.  But
> it is actually irrelevant\.
> 
> Tony Cook\+\+ tracked down the cause of this for me\.  The stack needed
> to pushed/popped around the call to the user\-defined perl subroutine\.
> But then he wanted to see what the code this replaces does\, and it
> turns out it does several more things\, which are similar to what the
> code block regex code does\, which is similar to what other places do
> that call out to perl code\.
> 
> But not exact
> 
> So is it a bug that for code blocks\, there is no SAVEHINTS\, or that it
> pushes \(the undocumented\) PERLSI\_REQUIRE instead of \(the undocumented\)
> PERLSI\_MAGIC?  And when should one use save\_re\_context\(\)?  My guess is
> that SAVETMPS and FREETMPS are just niceties\, but I don't know\.
> 
> None of this is obvious to me\.  My guess is that the disparities in
> calling things are actually bugs\, and there should be a routine that
> standardizes things\, or at least documentation as to what to do\.

They're required because you're doing something unusual \- calling a perl sub while compiling a regular expression\, \*or\* while matching\[1\] a regular expression\.

For compile\-time the SAVEHINTS is required so that changes to $^H or %^H don't result in lexical changes to the code being compiled \(like turning off strict\.\)

The PUSHSTACK is needed because the code seems to be called from places that don't expect the stack to move\.  I'm not sure exactly where that is in this case\,  but it's an issue for various types of magic\, eg\.

&nbsp;  pv = SvPV\(somesv\); /\* can call get or overload magic \*/

but since that's the uncommon case it's best to optimize for magic not being called and put the magic code through the extra work of switching stacks\.

The re\_save\_context\(\) is more a run\-time issue\, so that the code you call doesn't modify $1 etc from underneath the caller\.

All that said\, I don't know that I would have realized this was necessary if I was writing the code\.

Tony

\[1\] IIRC from a \#p5p conversation a while back\, the user sub can be called at runtime if it wasn't defined at regular expression compile\-time\.  It did appear to be called at runtime when I was debugging this issue\.

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Apr 01\, 2019 at 04&#8203;:34&#8203;:33PM \-0700\, Tony Cook via RT wrote&#8203;:
> On Sun\, 31 Mar 2019 22&#8203;:12&#8203;:02 \-0700\, khw wrote&#8203;:
> > None of this is obvious to me\.  My guess is that the disparities in
> > calling things are actually bugs\, and there should be a routine that
> > standardizes things\, or at least documentation as to what to do\.
> 

Basically what Tony says below\.

> They're required because you're doing something unusual \- calling a perl
> sub while compiling a regular expression\, \*or\* while matching\[1\] a
> regular expression\.
> 
> For compile\-time the SAVEHINTS is required so that changes to $^H or %^H
> don't result in lexical changes to the code being compiled \(like turning
> off strict\.\)
> 
> The PUSHSTACK is needed because the code seems to be called from places
> that don't expect the stack to move\.  I'm not sure exactly where that is
> in this case\,  but it's an issue for various types of magic\, eg\.
> 
>   pv = SvPV\(somesv\); /\* can call get or overload magic \*/

Yeah\, I think the "stack\-of\-stacks" mechanism was introduced when it was
realised that calling out to magic or overload methods could extend and
relloc\(\) the stack from under you\.  But we still try very hard in the
caller code to be immune to that too\, via PUTBACK/SPAGAIN etc\. So a sort
of belt and braces approach\.

> The re\_save\_context\(\) is more a run\-time issue\, so that the code you
> call doesn't modify $1 etc from underneath the caller\.

s/re\_save\_context/save\_re\_context/

I remember save\_re\_context\(\) being a bit of a hack\, but can't remember
why\.

> On Sun\, 31 Mar 2019 22&#8203;:12&#8203;:02 \-0700\, khw wrote&#8203;:
> > So is it a bug that for code blocks\, there is no SAVEHINTS\, or that it
> > pushes \(the undocumented\) PERLSI\_REQUIRE instead of \(the undocumented\)
> > PERLSI\_MAGIC?  And when should one use save\_re\_context\(\)?  My guess is
> > that SAVETMPS and FREETMPS are just niceties\, but I don't know\.

The regex code\-block calling mechanism \(?\{\.\.\.\}\) is very specialised\,
because its optimised to call the same code block many times in quick
succession\, and because the design of code blocks decreed that there is
no local scope\, so in \(?\{ local $x = \.\.\. \}\) the locals are only undone
at the end of the match\, or during backtracking\, not at the end of executing an individual code block\.

In general\, when calling code you should do ENTER/LEAVE and
SAVETMPS/FREETMPS to ensure things are cleaned up in a timely manner\.
Otherwise destructors may not get called until the caller also exits its
own scope\, and multiple calls to the code may accumulate temps which
again aren't freed until the caller exits\.

\-\- 
The Enterprise is involved in a bizarre time\-warp experience which is in
some way unconnected with the Late 20th Century\.
&nbsp;    \-\- Things That Never Happen in "Star Trek" \#14

**Comment by p5pRT** [comment]
### From @khwilliamson

On 4/3/19 4&#8203;:39 AM\, Dave Mitchell wrote&#8203;:
> On Mon\, Apr 01\, 2019 at 04&#8203;:34&#8203;:33PM \-0700\, Tony Cook via RT wrote&#8203;:
>> On Sun\, 31 Mar 2019 22&#8203;:12&#8203;:02 \-0700\, khw wrote&#8203;:
>>> None of this is obvious to me\.  My guess is that the disparities in
>>> calling things are actually bugs\, and there should be a routine that
>>> standardizes things\, or at least documentation as to what to do\.
>>
> 
> Basically what Tony says below\.
> 
>> They're required because you're doing something unusual \- calling a perl
>> sub while compiling a regular expression\, \*or\* while matching\[1\] a
>> regular expression\.
>>
>> For compile\-time the SAVEHINTS is required so that changes to $^H or %^H
>> don't result in lexical changes to the code being compiled \(like turning
>> off strict\.\)
>>
>> The PUSHSTACK is needed because the code seems to be called from places
>> that don't expect the stack to move\.  I'm not sure exactly where that is
>> in this case\,  but it's an issue for various types of magic\, eg\.
>>
>>    pv = SvPV\(somesv\); /\* can call get or overload magic \*/
> 
> Yeah\, I think the "stack\-of\-stacks" mechanism was introduced when it was
> realised that calling out to magic or overload methods could extend and
> relloc\(\) the stack from under you\.  But we still try very hard in the
> caller code to be immune to that too\, via PUTBACK/SPAGAIN etc\. So a sort
> of belt and braces approach\.
> 
>> The re\_save\_context\(\) is more a run\-time issue\, so that the code you
>> call doesn't modify $1 etc from underneath the caller\.
> 
> s/re\_save\_context/save\_re\_context/
> 
> I remember save\_re\_context\(\) being a bit of a hack\, but can't remember
> why\.
> 
>> On Sun\, 31 Mar 2019 22&#8203;:12&#8203;:02 \-0700\, khw wrote&#8203;:
>>> So is it a bug that for code blocks\, there is no SAVEHINTS\, or that it
>>> pushes \(the undocumented\) PERLSI\_REQUIRE instead of \(the undocumented\)
>>> PERLSI\_MAGIC?  And when should one use save\_re\_context\(\)?  My guess is
>>> that SAVETMPS and FREETMPS are just niceties\, but I don't know\.
> 
> The regex code\-block calling mechanism \(?\{\.\.\.\}\) is very specialised\,
> because its optimised to call the same code block many times in quick
> succession\, and because the design of code blocks decreed that there is
> no local scope\, so in \(?\{ local $x = \.\.\. \}\) the locals are only undone
> at the end of the match\, or during backtracking\, not at the end of executing an individual code block\.
> 
> In general\, when calling code you should do ENTER/LEAVE and
> SAVETMPS/FREETMPS to ensure things are cleaned up in a timely manner\.
> Otherwise destructors may not get called until the caller also exits its
> own scope\, and multiple calls to the code may accumulate temps which
> again aren't freed until the caller exits\.
> 

The code in swash\_init has this&#8203;:

/\* We might get here via a subroutine signature which uses a utf8 
&nbsp;    \* parameter name\, at which point PL\_subname will have been set
\* but not yet used\. \*/
save\_item\(PL\_subname\);

I'm wondering if that could affect code blocks

**Comment by p5pRT** [comment]
### From @iabyn

On Wed\, Apr 10\, 2019 at 03&#8203;:21&#8203;:21PM \-0600\, Karl Williamson wrote&#8203;:
> The code in swash\_init has this&#8203;:
> 
> /\* We might get here via a subroutine signature which uses a utf8    \*
> parameter name\, at which point PL\_subname will have been set
> \* but not yet used\. \*/
> save\_item\(PL\_subname\);
> 
> I'm wondering if that could affect code blocks

PL\_subname is the name of the currently\-compiling sub\, so I can't really
see that pattern code\-blocks\, which are called at runtime\, would be
affected\. The swash stuff was a bit special because it could be called at
compile time\.

\-\- 
I before E\. Except when it isn't\.

**Comment by p5pRT** [comment]
### From @khwilliamson

The module now tests OK\, so removing from blockers list\.  I still need to write a test so keeping the ticket open
\-\- 
Karl Williamson

**Comment by jkeenan** [comment]
> 
> The module now tests OK, so removing from blockers list. I still need to write a test so keeping the ticket open
> --
> Karl Williamson

@khwilliamson Have you written the test indicated above?  If so, is this ticket closable?

Thank you very much.
Jim Keenan

**Comment by xsawyerx** [comment]
I think we can resolve this ticket and open a ticket for the test we want to write. I don't consider this a blocker anymore since the BBC tests pass.

Any strong objections?

**Comment by khwilliamson** [comment]
I'm afraid I can't remember what test I was supposed to write, nor do I see any guidance in the ticket.  

But, since then, there have been a bunch of tests written exercising this area of the code.  So I am closing the ticket
