### ISSUE TITLE
Link is dead in the documentation

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16927]
Migrated from [rt.perl.org#133987](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=133987) (status was 'open')

Searchable as RT133987$

**Comment by p5pRT** [comment]
### From @KES777

Hello Perlbug\,

On the page&#8203;: https://perldoc.perl.org/mro.html next link is dead&#8203;:

The original Dylan paper
&nbsp;    http&#8203;://haahr\.tempdomainname\.com/dylan/linearization\-oopsla96\.html


This also is not opened&#8203;: http&#8203;://use\.perl\.org/~autrijus/journal/25768

and 404 for these&#8203;:

Python 2\.3 MRO related links

&nbsp;    http&#8203;://www\.python\.org/2\.3/mro\.html
&nbsp;    http&#8203;://www\.python\.org/2\.2\.2/descrintro\.html\#mro



And here https://perldoc.perl.org/mro.html#mro%3a%3ais_universal(%24classname)

> or one of UNIVERSAL 's parents by @&#8203;ISA inheritance\.
As  far  as  I  know UNIVERSAL has no parents\. Probably here should be
UNIVERSAL's children?

\-\- 
Best regards\,
Eugen Konkov

**Comment by p5pRT** [comment]
### From @dur-randir

On Thu\, 04 Apr 2019 23&#8203;:11&#8203;:40 \-0700\, kes\-kes@&#8203;yandex\.ru wrote&#8203;:
> > or one of UNIVERSAL 's parents by @&#8203;ISA inheritance\.
> As  far  as  I  know UNIVERSAL has no parents\. Probably here should be
> UNIVERSAL's children?

Nothing\, except for the sense of sanity\, prevents you from pushing into @&#8203;UNIVERSAL&#8203;::ISA\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @iabyn

On Thu\, Apr 04\, 2019 at 11&#8203;:28&#8203;:22PM \-0700\, Sergey Aleynikov via RT wrote&#8203;:
> On Thu\, 04 Apr 2019 23&#8203;:11&#8203;:40 \-0700\, kes\-kes@&#8203;yandex\.ru wrote&#8203;:
> > > or one of UNIVERSAL 's parents by @&#8203;ISA inheritance\.
> > As  far  as  I  know UNIVERSAL has no parents\. Probably here should be
> > UNIVERSAL's children?
> 
> Nothing\, except for the sense of sanity\, prevents you from pushing into
> @&#8203;UNIVERSAL&#8203;::ISA\.

And there's this insanity&#8203;:

&nbsp;    $ perl5280 \-MAttribute&#8203;::Handlers \-le'print for @&#8203;UNIVERSAL&#8203;::ISA'
&nbsp;    Attribute&#8203;::Handlers&#8203;::UNIVERSAL
&nbsp;    $

\-\- 
"Procrastination grows to fill the available time"
&nbsp;    \-\- Mitchell's corollary to Parkinson's Law

**Comment by p5pRT** [comment]
### From @tomhukins

On Thu\, Apr 04\, 2019 at 11&#8203;:11&#8203;:40PM \-0700\, KES \(via RT\) wrote&#8203;:
> Hello Perlbug\,
> 
> On the page&#8203;: https://perldoc.perl.org/mro.html next link is dead&#8203;:

This mailing list does not maintain the perldoc\.perl\.org site\.  That
site contains information from the perl5 git repository\, but it isn't
alway up to date\.  Some of the issues you mention are fixed in the perl5
git repository while others are not\.

I've attached a patch for committers to review\.

> The original Dylan paper
>     http&#8203;://haahr\.tempdomainname\.com/dylan/linearization\-oopsla96\.html

This has already been fixed in commit 142e623\.

> This also is not opened&#8203;: http&#8203;://use\.perl\.org/~autrijus/journal/25768

That site has been offline for a while\.  I managed to find the link in
archive\.org but removed it in my patch\.

> and 404 for these&#8203;:
> 
> Python 2\.3 MRO related links
> 
>     http&#8203;://www\.python\.org/2\.3/mro\.html
>     http&#8203;://www\.python\.org/2\.2\.2/descrintro\.html\#mro

I've fixed the first and removed the second\.

> And here https://perldoc.perl.org/mro.html#mro%3a%3ais_universal(%24classname)
> 
> > or one of UNIVERSAL 's parents by @&#8203;ISA inheritance\.
> As  far  as  I  know UNIVERSAL has no parents\. Probably here should be
> UNIVERSAL's children?

Other replies have described modules that alter @&#8203;UNIVERSAL&#8203;::ISA\.

Tom

**Comment by p5pRT** [comment]
### From @tomhukins

<details><summary>0001-Fix-a-broken-link.patch</summary>

```diff
From f5d6d0f135b7dc07100e4e8a00f98ad4d59c6861 Mon Sep 17 00:00:00 2001
From: Tom Hukins <tom@eborcom.com>
Date: Fri, 12 Apr 2019 18:18:15 +0100
Subject: [PATCH] Fix a broken link

While I'm here, remove mentions of Parrot and Pugs as both have little
relevance today.

These changes were inspired by problems raised in [perl #133987].
---
 ext/mro/mro.pm | 20 ++------------------
 1 file changed, 2 insertions(+), 18 deletions(-)

diff --git a/ext/mro/mro.pm b/ext/mro/mro.pm
index 4a7685cc04..4773bf39cd 100644
--- a/ext/mro/mro.pm
+++ b/ext/mro/mro.pm
@@ -312,27 +312,11 @@ works (like C<goto &maybe::next::method>);
 
 =back
 
-=head2 Pugs
-
-The Pugs prototype Perl 6 Object Model uses C3
-
-=head2 Parrot
-
-Parrot now uses C3
-
-=over 4
-
-=item L<http://use.perl.org/~autrijus/journal/25768>
-
-=back
-
-=head2 Python 2.3 MRO related links
+=head2 Python 2.3 MRO
 
 =over 4
 
-=item L<http://www.python.org/2.3/mro.html>
-
-=item L<http://www.python.org/2.2.2/descrintro.html#mro>
+=item L<https://www.python.org/download/releases/2.3/mro/>
 
 =back
 
-- 
2.21.0


```
</details>

**Comment by Corion** [comment]
Hi @KES777 , @tomhukins !

I've applied the attached patch, thanks for noticing and patching this!
