### ISSUE TITLE
perl5 blead fails to build on NetBSD-8.0 with g++

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16950]
Migrated from [rt.perl.org#134023](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134023) (status was 'open')

Searchable as RT134023$

**Comment by p5pRT** [comment]
### From @jkeenan

Go to http&#8203;://perl5\.test\-smoke\.org/search and select 'netbsd'\, '8\.0' and 
'g\+\+' from the top 3 drop\-downs on the right\-hand side\.

It appears this has been the case ever we since we started to get smoke 
test reports from Carlos in September 2018\.

blead does appear to build on NetBSD\-7\.2 with g\+\+ \(modulo test failures 
reported in other tickets\)\.

blead does appear to build on NetBSD\-8\.0 with gcc \(same qualification\)\.

Thank you very much\.
Jim Keenan

perl perl perl

**Comment by p5pRT** [comment]
### From @khwilliamson

On 4/11/19 12&#8203;:45 PM\, James E Keenan \(via RT\) wrote&#8203;:
> \# New Ticket Created by  James E Keenan
> \# Please include the string&#8203;:  \[perl \#134023\]
> \# in the subject line of all future correspondence about this issue\.
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134023 >
> 
> 
> Go to http&#8203;://perl5\.test\-smoke\.org/search and select 'netbsd'\, '8\.0' and
> 'g\+\+' from the top 3 drop\-downs on the right\-hand side\.
> 
> It appears this has been the case ever we since we started to get smoke
> test reports from Carlos in September 2018\.
> 
> blead does appear to build on NetBSD\-7\.2 with g\+\+ \(modulo test failures
> reported in other tickets\)\.
> 
> blead does appear to build on NetBSD\-8\.0 with gcc \(same qualification\)\.
> 
> Thank you very much\.
> Jim Keenan
> 
> perl perl perl
> 
> 

I had noticed that a while back\, and just not investigated\.  There's 
something wrong/different with static asserts in this version of g\+\+

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @jkeenan

On Thu\, 11 Apr 2019 19&#8203;:58&#8203;:50 GMT\, public@&#8203;khwilliamson\.com wrote&#8203;:
> On 4/11/19 12&#8203;:45 PM\, James E Keenan \(via RT\) wrote&#8203;:
> > \# New Ticket Created by  James E Keenan
> > \# Please include the string&#8203;:  \[perl \#134023\]
> > \# in the subject line of all future correspondence about this issue\.
> > \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134023 >
> > 
> > 
> > Go to http&#8203;://perl5\.test\-smoke\.org/search and select 'netbsd'\, '8\.0' and
> > 'g\+\+' from the top 3 drop\-downs on the right\-hand side\.
> > 
> > It appears this has been the case ever we since we started to get smoke
> > test reports from Carlos in September 2018\.
> > 
> > blead does appear to build on NetBSD\-7\.2 with g\+\+ \(modulo test failures
> > reported in other tickets\)\.
> > 
> > blead does appear to build on NetBSD\-8\.0 with gcc \(same qualification\)\.
> > 
> > Thank you very much\.
> > Jim Keenan
> > 
> > perl perl perl
> > 
> > 
> 
> I had noticed that a while back\, and just not investigated\.  There's 
> something wrong/different with static asserts in this version of g\+\+\.

Can you elaborate on what you think the problems with this version of g\+\+ are?

Should we expect them to show up other OS/version combinations?

Thank you very much\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @khwilliamson

On 4/29/19 4&#8203;:32 PM\, James E Keenan via RT wrote&#8203;:
> On Thu\, 11 Apr 2019 19&#8203;:58&#8203;:50 GMT\, public@&#8203;khwilliamson\.com wrote&#8203;:
>> On 4/11/19 12&#8203;:45 PM\, James E Keenan \(via RT\) wrote&#8203;:
>>> \# New Ticket Created by  James E Keenan
>>> \# Please include the string&#8203;:  \[perl \#134023\]
>>> \# in the subject line of all future correspondence about this issue\.
>>> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134023 >
>>>
>>>
>>> Go to http&#8203;://perl5\.test\-smoke\.org/search and select 'netbsd'\, '8\.0' and
>>> 'g\+\+' from the top 3 drop\-downs on the right\-hand side\.
>>>
>>> It appears this has been the case ever we since we started to get smoke
>>> test reports from Carlos in September 2018\.
>>>
>>> blead does appear to build on NetBSD\-7\.2 with g\+\+ \(modulo test failures
>>> reported in other tickets\)\.
>>>
>>> blead does appear to build on NetBSD\-8\.0 with gcc \(same qualification\)\.
>>>
>>> Thank you very much\.
>>> Jim Keenan
>>>
>>> perl perl perl
>>>
>>>
>>
>> I had noticed that a while back\, and just not investigated\.  There's
>> something wrong/different with static asserts in this version of g\+\+\.
> 
> Can you elaborate on what you think the problems with this version of g\+\+ are?
> 
> Should we expect them to show up other OS/version combinations?
> 
> Thank you very much\.
> 

All I know is that's where the logs indicate the failure is&#8203;:
p\.c&#8203;: In function 'void S\_maybe\_multiconcat\(OP\*\)'&#8203;:
perl\.h&#8203;:3472&#8203;:61&#8203;: error&#8203;: '\_Static\_assert' was not declared in this scope
perl\.h&#8203;:3488&#8203;:52&#8203;: note&#8203;: in expansion of macro 'STATIC\_ASSERT\_DECL'
op\.c&#8203;:2861&#8203;:5&#8203;: note&#8203;: in expansion of macro 'STATIC\_ASSERT\_STMT'
op\.c&#8203;:2863&#8203;:5&#8203;: note&#8203;: in expansion of macro 'STATIC\_ASSERT\_STMT'
op\.c&#8203;: In function 'void Perl\_rpeep\(OP\*\)'&#8203;:
op\.c&#8203;:15799&#8203;:21&#8203;: note&#8203;: in expansion of macro 'STATIC\_ASSERT\_STMT'
op\.c&#8203;: In function 'void S\_maybe\_multiconcat\(PerlInterpreter\*\, OP\*\)'&#8203;:
op\.c&#8203;: In function 'OP\* Perl\_ck\_rvconst\(PerlInterpreter\*\, OP\*\)'&#8203;:
op\.c&#8203;:11646&#8203;:6&#8203;: note&#8203;: in expansion of macro 'STATIC\_ASSERT\_STMT'
op\.c&#8203;: In function 'void Perl\_rpeep\(PerlInterpreter\*\, OP\*\)'&#8203;:

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Apr 29\, 2019 at 04&#8203;:57&#8203;:09PM \-0600\, Karl Williamson wrote&#8203;:
> On 4/29/19 4&#8203;:32 PM\, James E Keenan via RT wrote&#8203;:
> > Should we expect them to show up other OS/version combinations?

No\, this looks like a specific netbsd \+ g\+\+ issue\.

> perl\.h&#8203;:3472&#8203;:61&#8203;: error&#8203;: '\_Static\_assert' was not declared in this scope
> perl\.h&#8203;:3488&#8203;:52&#8203;: note&#8203;: in expansion of macro 'STATIC\_ASSERT\_DECL'

Perl\.h has this&#8203;:

&nbsp;    \#if \(defined\(static\_assert\) || \(defined\(\_\_cplusplus\) && \_\_cplusplus >= 201103L\)\) && \(\!defined\(\_\_IBMC\_\_\) || \_\_IBMC\_\_ >= 1210\)
&nbsp;    /\* static\_assert is a macro defined in \<assert\.h> in C11 or a compiler
&nbsp;       builtin in C\+\+11\.  But IBM XL C V11 does not support \_Static\_assert\, no
&nbsp;       matter what \<assert\.h> says\.
&nbsp;    \*/
&nbsp;    \#  define STATIC\_ASSERT\_DECL\(COND\) static\_assert\(COND\, \#COND\)
&nbsp;    \#else
&nbsp;      \.\.\.\.

On my linux platform\, /usr/include/assert\.h has&#8203;:

&nbsp;    \#if defined \_\_USE\_ISOC11 && \!defined \_\_cplusplus
&nbsp;    \# undef static\_assert
&nbsp;    \# define static\_assert \_Static\_assert
&nbsp;    \#endif

and /usr/include/sys/cdefs\.h has&#8203;:

&nbsp;    \#if \(\!defined \_Static\_assert && \!defined \_\_cplusplus \\
&nbsp;         && \(defined \_\_STDC\_VERSION\_\_ ? \_\_STDC\_VERSION\_\_ : 0\) \< 201112 \\
&nbsp;         && \(\!\_\_GNUC\_PREREQ \(4\, 6\) || defined \_\_STRICT\_ANSI\_\_\)\)
&nbsp;    \# define \_Static\_assert\(expr\, diagnostic\) \\
&nbsp;        extern int \(\*\_\_Static\_assert\_function \(void\)\) \\
&nbsp;          \[\!\!sizeof \(struct \{ int \_\_error\_if\_negative&#8203;: \(expr\) ? 2 : \-1; \}\)\]
&nbsp;    \#endif


I assume NetBSD 8\+\+ has similar\-ish header file\(s\)\, but something is not
quite right with all the version checks and/or the version of g\+\+\.


\-\- 
"I do not resent criticism\, even when\, for the sake of emphasis\,
it parts for the time with reality"\.
&nbsp;    \-\- Winston Churchill\, House of Commons\, 22nd Jan 1941\.

**Comment by p5pRT** [comment]
### From coypu@sdf.org

yeah\, the netbsd headers are wrong for this scenario\.
\_Static\_assert is a thing for >= C11
static\_assert is a thing for >= C\+\+11\.

The use of \-ansi forces us to a really old standard so these are not available\.

NetBSD should probably supply a fallback definition for \_Static\_assert like glibc does\, or at least restrict the definition for when it is available\.

I'd like to fix this in NetBSD \(and backport it etc\.\)
Is a fix for Perl also desired?

**Comment by p5pRT** [comment]
### From coypu@sdf.org

On Wed\, 22 May 2019 05&#8203;:03&#8203;:18 \-0700\, coypu@&#8203;sdf\.org wrote&#8203;:
> Is a fix for Perl also desired?

And by fix I mean\, "hack workaround"\, hence the question :\-\)

**Comment by p5pRT** [comment]
### From @jkeenan

On Wed\, 22 May 2019 12&#8203;:04&#8203;:13 GMT\, coypu@&#8203;sdf\.org wrote&#8203;:
> On Wed\, 22 May 2019 05&#8203;:03&#8203;:18 \-0700\, coypu@&#8203;sdf\.org wrote&#8203;:
> > Is a fix for Perl also desired?
> 
> And by fix I mean\, "hack workaround"\, hence the question :\-\)
> 
> 

Yes\, a fix is desired\.  It appears evident to me \(note&#8203;: note a NetBSD user\) that the best place to address this problem would be in appropriate \.c and \.h header files such as those that have already been cited by Karl Williamson in this ticket\.

For many uses\, however\, we can get by with changes to the hints/netbsd\.sh file included in the Perl 5 core distribution\.  If you are not already familiar with that file\, which is run as part of the configuration process\, please take a look at it\.

Thank you very much\.
\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
### From @khwilliamson

On Wed\, 22 May 2019 05&#8203;:48&#8203;:07 \-0700\, jkeenan wrote&#8203;:
> On Wed\, 22 May 2019 12&#8203;:04&#8203;:13 GMT\, coypu@&#8203;sdf\.org wrote&#8203;:
> > On Wed\, 22 May 2019 05&#8203;:03&#8203;:18 \-0700\, coypu@&#8203;sdf\.org wrote&#8203;:
> > > Is a fix for Perl also desired?
> >
> > And by fix I mean\, "hack workaround"\, hence the question :\-\)
> >
> >
> 
> Yes\, a fix is desired\.  It appears evident to me \(note&#8203;: note a NetBSD
> user\) that the best place to address this problem would be in
> appropriate \.c and \.h header files such as those that have already
> been cited by Karl Williamson in this ticket\.
> 
> For many uses\, however\, we can get by with changes to the
> hints/netbsd\.sh file included in the Perl 5 core distribution\.  If you
> are not already familiar with that file\, which is run as part of the
> configuration process\, please take a look at it\.
> 
> Thank you very much\.

My reply did not make it to this ticket\.  And I now see that there was already something to the effect of what I was going to say\, which is perl already has code to emulate static asserts for systems that don't have it\.  

https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134023#txn-1629956

I'm thinking the definition there could be tweaked so that perl's definition is enabled in this situation\.  I don't really understand what copypu is proposing\, but this option should be considered
\-\- 
Karl Williamson

**Comment by p5pRT** [comment]
### From coypu@sdf.org

this is the netbsd fix\, and will be in netbsd 8\.1 when it is released \(soon\)&#8203;: http&#8203;://mail\-index\.netbsd\.org/source\-changes\-hg/2019/05/29/msg057353\.html

why the code was failing on netbsd&#8203;:

/\* from netbsd assert\.h \*/
\#define static\_assert bad\_definition

/\* from perl\.h \*/
\#ifndef static\_assert
\#define static\_assert good\_definition
\#endif


why the definition was bad&#8203;:
it relied on GCC \_Static\_assert\.
Building for old C\+\+ standards it's not available\.

**Comment by jkeenan** [comment]
> ### From [coypu@sdf.org](mailto:coypu@sdf.org)
> 
> this is the netbsd fix, and will be in netbsd 8.1 when it is released (soon)​: http​://mail-index.netbsd.org/source-changes-hg/2019/05/29/msg057353.html
> 
> why the code was failing on netbsd​:
> 
> /* from netbsd assert.h */
> #define static_assert bad_definition
> 
> /* from perl.h */
> #ifndef static_assert
> #define static_assert good_definition
> #endif
> 
> why the definition was bad​:
> it relied on GCC _Static_assert.
> Building for old C++ standards it's not available.

I'm going to assume that the correction to `include/assert.h` did make it into NetBSD-8.1 (and that it will also be in the upcoming 9.0).  I doubt the fix will be backported to 8.0.  I don't think it's worth our while to alter our `hints/netbsd.sh` file for this.  So I'm closing this ticket.

Thank you very much.
Jim Keenan
