### ISSUE TITLE
[PATCH] Devel::PPPort: Fix commit d6d4687 vmess is already implemented

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#16997]
Migrated from [rt.perl.org#134101](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134101) (status was 'open')

Searchable as RT134101$

**Comment by p5pRT** [comment]
### From @pali

Attached patch fixes commit d6d4687 as Devel&#8203;::PPPort's vmess was already implemented as part of commit f87c37b\.

**Comment by p5pRT** [comment]
### From @pali

<details><summary>0001-Devel-PPPort-Fix-commit-d6d4687-vmess-is-already-imp.patch</summary>

```diff
From 0d94812e9df532cffcb030b7b073b50fc4329720 Mon Sep 17 00:00:00 2001
From: Pali <pali@cpan.org>
Date: Tue, 14 May 2019 12:54:30 +0200
Subject: [PATCH] Devel::PPPort: Fix commit d6d4687 vmess is already
 implemented

---
 dist/Devel-PPPort/parts/todo/5006000 | 1 -
 1 file changed, 1 deletion(-)

diff --git a/dist/Devel-PPPort/parts/todo/5006000 b/dist/Devel-PPPort/parts/todo/5006000
index 2d95331488..cd79d1ce3f 100644
--- a/dist/Devel-PPPort/parts/todo/5006000
+++ b/dist/Devel-PPPort/parts/todo/5006000
@@ -94,6 +94,5 @@ utf8_distance                  # U
 utf8_hop                       # U
 vcroak                         # U
 vform                          # U
-vmess                          # U
 vwarn                          # U
 vwarner                        # U
-- 
2.11.0


```
</details>

**Comment by p5pRT** [comment]
### From @atoomic

On Tue\, 14 May 2019 04&#8203;:00&#8203;:27 \-0700\, pali@&#8203;cpan\.org wrote&#8203;:
> Attached patch fixes commit d6d4687 as Devel&#8203;::PPPort's vmess was
> already implemented as part of commit f87c37b\.

thanks for the patch this going to be merged as 
https://github.com/Dual-Life/Devel-PPPort/issues/61

then we will bump blead with the next release
using GitHub repo allow us to have some basic Travis Integration running

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by khwilliamson** [comment]
atoomic is this applied?

**Comment by atoomic** [comment]
this was applied as https://github.com/Dual-Life/Devel-PPPort/commit/e40b007be9ea80ad7a621868da33318ff2c0d848
we can close this case
