### ISSUE TITLE
[PATCH] Devel::PPPort: Run make regen after regenerating Makefile

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#17003]
Migrated from [rt.perl.org#134114](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134114) (status was 'open')

Searchable as RT134114$

**Comment by p5pRT** [comment]
### From @pali

This would ensure that all auto\-generated files are up\-to\-date after running configure phase\.

**Comment by p5pRT** [comment]
### From @pali

<details><summary>0001-Devel-PPPort-Run-make-regen-after-regenerating-Makef.patch</summary>

```diff
From 8a037a891e54845dff21805dae30369e4dc1ac45 Mon Sep 17 00:00:00 2001
From: Pali <pali@cpan.org>
Date: Fri, 17 May 2019 12:41:03 +0200
Subject: [PATCH] Devel::PPPort: Run make regen after regenerating Makefile

This would ensure that all auto-generated files are up-to-date after running configure phase.
---
 dist/Devel-PPPort/Makefile.PL | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/dist/Devel-PPPort/Makefile.PL b/dist/Devel-PPPort/Makefile.PL
index 62ba014cf6..4b86444613 100644
--- a/dist/Devel-PPPort/Makefile.PL
+++ b/dist/Devel-PPPort/Makefile.PL
@@ -17,6 +17,7 @@ require 5.003;
 
 use strict;
 use ExtUtils::MakeMaker;
+use Config;
 
 use vars '%opt';  # needs to be global, and we can't use 'our'
 
@@ -37,6 +38,7 @@ my %mf = (
 );
 delete $mf{META_MERGE} unless eval { ExtUtils::MakeMaker->VERSION (6.46) };
 WriteMakefile(%mf);
+system({$Config{make}} $Config{make}, 'regen');
 
 sub configure
 {
-- 
2.11.0


```
</details>

**Comment by p5pRT** [comment]
### From @atoomic

On Fri\, 17 May 2019 03&#8203;:43&#8203;:57 \-0700\, pali@&#8203;cpan\.org wrote&#8203;:
> This would ensure that all auto\-generated files are up\-to\-date after
> running configure phase\.

great idea will apply it to our git repo waiting for the freeze to have this merge to blead
leaving the ticket open for now until its merge to blead

https://github.com/Dual-Life/Devel-PPPort/issues/76

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by khwilliamson** [comment]
@atoomic is this applied?

**Comment by atoomic** [comment]
I think part of this was applied as https://github.com/Dual-Life/Devel-PPPort/pull/83
but not sure if the other part is in

**Comment by atoomic** [comment]
As mentionned in https://github.com/Dual-Life/Devel-PPPort/pull/77
this is now fixed with  https://github.com/Dual-Life/Devel-PPPort/pull/83 and https://github.com/Dual-Life/Devel-PPPort/pull/95

We can close this case
