### ISSUE TITLE
[META]: Tickets blocking release of perl-5.30.1

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#17012]
Migrated from [rt.perl.org#134127](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134127) (status was 'new')

Searchable as RT134127$

**Comment by p5pRT** [comment]
### From @jkeenan

This ticket will hold a list of other RTs blocking the release of 
perl\-5\.30\.1\, the first maintenance release in the perl\-5\.30 series\.

Discussion of those RTs should go into the tickets themselves so that we 
can keep this ticket in "New" status in RT\.

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From @jkeenan

Summary of my perl5 \(revision 5 version 31 subversion 0\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 58f4626762668e1c1948832073998af84b2c85d0
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux
&nbsp;    osvers=4\.15\.0\-50\-generic
&nbsp;    archname=x86\_64\-linux
&nbsp;    uname='linux zareason 4\.15\.0\-50\-generic \#54\-ubuntu smp mon may 6 18&#8203;:46&#8203;:08 utc 2019 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;    config\_args='\-des \-Dusedevel \-Dusemymalloc=y'
&nbsp;    hint=recommended
&nbsp;    useposix=true
&nbsp;    d\_sigaction=define
&nbsp;    useithreads=undef
&nbsp;    usemultiplicity=undef
&nbsp;    use64bitint=define
&nbsp;    use64bitall=define
&nbsp;    uselongdouble=undef
&nbsp;    usemymalloc=y
&nbsp;    default\_inc\_excludes\_dot=define
&nbsp;    bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'
&nbsp;    ccflags ='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'
&nbsp;    optimize='\-O2'
&nbsp;    cppflags='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''
&nbsp;    gccversion='7\.4\.0'
&nbsp;    gccosandvers=''
&nbsp;    intsize=4
&nbsp;    longsize=8
&nbsp;    ptrsize=8
&nbsp;    doublesize=8
&nbsp;    byteorder=12345678
&nbsp;    doublekind=3
&nbsp;    d\_longlong=define
&nbsp;    longlongsize=8
&nbsp;    d\_longdbl=define
&nbsp;    longdblsize=16
&nbsp;    longdblkind=3
&nbsp;    ivtype='long'
&nbsp;    ivsize=8
&nbsp;    nvtype='double'
&nbsp;    nvsize=8
&nbsp;    Off\_t='off\_t'
&nbsp;    lseeksize=8
&nbsp;    alignbytes=8
&nbsp;    prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'
&nbsp;    ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/7/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib /lib64 /usr/lib64
&nbsp;    libs=\-lpthread \-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.27\.so
&nbsp;    so=so
&nbsp;    useshrplib=false
&nbsp;    libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.27'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs
&nbsp;    dlext=so
&nbsp;    d\_dlsymun=undef
&nbsp;    ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'
&nbsp;    lddlflags='\-shared \-O2 \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;:
&nbsp;    HAS\_TIMES
&nbsp;    MYMALLOC
&nbsp;    PERLIO\_LAYERS
&nbsp;    PERL\_COPY\_ON\_WRITE
&nbsp;    PERL\_DONT\_CREATE\_GVSV
&nbsp;    PERL\_MALLOC\_WRAP
&nbsp;    PERL\_OP\_PARENT
&nbsp;    PERL\_PRESERVE\_IVUV
&nbsp;    PERL\_USE\_DEVEL
&nbsp;    USE\_64\_BIT\_ALL
&nbsp;    USE\_64\_BIT\_INT
&nbsp;    USE\_LARGE\_FILES
&nbsp;    USE\_LOCALE
&nbsp;    USE\_LOCALE\_COLLATE
&nbsp;    USE\_LOCALE\_CTYPE
&nbsp;    USE\_LOCALE\_NUMERIC
&nbsp;    USE\_LOCALE\_TIME
&nbsp;    USE\_PERLIO
&nbsp;    USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at May 22 2019 14&#8203;:58&#8203;:04
&nbsp;  %ENV&#8203;:
&nbsp;    PERL2DIR="/home/jkeenan/gitwork/perl2"
&nbsp;    PERLBREW\_HOME="/home/jkeenan/\.perlbrew"
&nbsp;    PERLBREW\_MANPATH="/home/jkeenan/perl5/perlbrew/perls/perl\-5\.28\.0/man"
&nbsp;    PERLBREW\_PATH="/home/jkeenan/perl5/perlbrew/bin&#8203;:/home/jkeenan/perl5/perlbrew/perls/perl\-5\.28\.0/bin"
&nbsp;    PERLBREW\_PERL="perl\-5\.28\.0"
&nbsp;    PERLBREW\_ROOT="/home/jkeenan/perl5/perlbrew"
&nbsp;    PERLBREW\_SHELLRC\_VERSION="0\.84"
&nbsp;    PERLBREW\_VERSION="0\.84"
&nbsp;    PERL\_WORKDIR="/home/jkeenan/gitwork/perl"
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.31\.0/x86\_64\-linux
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.31\.0
&nbsp;    /usr/local/lib/perl5/5\.31\.0/x86\_64\-linux
&nbsp;    /usr/local/lib/perl5/5\.31\.0

**Comment by p5pRT** [comment]
### From @tonycoz

On Wed\, 22 May 2019 13&#8203;:14&#8203;:43 \-0700\, jkeenan@&#8203;pobox\.com wrote&#8203;:
> This ticket will hold a list of other RTs blocking the release of 
> perl\-5\.30\.1\, the first maintenance release in the perl\-5\.30 series\.
> 
> Discussion of those RTs should go into the tickets themselves so that we 
> can keep this ticket in "New" status in RT\.

Both of the dependent tickets are resolved\, and 5\.31\.1 has been released\.  Do we still need this?

Tony

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @jkeenan

On Wed\, 10 Jul 2019 04&#8203;:46&#8203;:45 GMT\, tonyc wrote&#8203;:
> On Wed\, 22 May 2019 13&#8203;:14&#8203;:43 \-0700\, jkeenan@&#8203;pobox\.com wrote&#8203;:
> > This ticket will hold a list of other RTs blocking the release of
> > perl\-5\.30\.1\, the first maintenance release in the perl\-5\.30 series\.
> >
> > Discussion of those RTs should go into the tickets themselves so that
> > we
> > can keep this ticket in "New" status in RT\.
> 
> Both of the dependent tickets are resolved\, and 5\.31\.1 has been
> released\.  Do we still need this?
> 

Yes\, we still need this ticket\.

This ticket is for 5\.30\.1 \-\- the first \*maintenance\* release of production version 5\.30 \-\- not for the first monthly \*development\* release in the 5\.31 cycle\.

There will presumably be other tickets that we will want to assess before releasing 5\.30\.1\, 5\.30\.2\, etc\.

Thank you very much\.
\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
@jkeenan - Status changed from 'open' to 'new'

**Comment by toddr** [comment]
I'm closing this case since there is now a milestone for this purpose https://github.com/Perl/perl5/milestone/2
