### ISSUE TITLE
New compilation warnings with gcc 9.1.0

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#17014]
Migrated from [rt.perl.org#134130](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134130) (status was 'open')

Searchable as RT134130$

**Comment by p5pRT** [comment]
### From @dur-randir

#### Created by @dur-randir



I get the following warnings when building perl on Debian with gcc 9\.1\.0

Wformat\-overflow&#8203;:

locale\.c&#8203;: In function ‘Perl\_\_is\_cur\_LC\_category\_utf8’&#8203;:
locale\.c&#8203;:5087&#8203;:17&#8203;: warning&#8203;: ‘%s’ directive argument is null \[\-Wformat\-overflow=\]
 5087 |                 Perl\_croak\(aTHX\_
&nbsp;      |                 ^~~~~~~~~~~~~~~~
 5088 |                            "panic&#8203;: %s&#8203;: %d&#8203;: Corrupt
utf8ness\_cache&#8203;: missing"
&nbsp;      |
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 5089 |                            " separator %\.\*s\<\-\- HERE %s\\n"\,
&nbsp;      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 5090 |                            \_\_FILE\_\_\, \_\_LINE\_\_\,
&nbsp;      |                            ~~~~~~~~~~~~~~~~~~~
 5091 |                            \(int\) \(e \- PL\_locale\_utf8ness\)\,
PL\_locale\_utf8ness\,
&nbsp;      |
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 5092 |                            e\);
&nbsp;      |                            ~~
locale\.c&#8203;:5089&#8203;:53&#8203;: note&#8203;: format string is defined here
 5089 |                            " separator %\.\*s\<\-\- HERE %s\\n"\,
&nbsp;      |                                                     ^~

Wc\+\+\-compat \(lots of\, here's the pattern\)&#8203;:

byte\_t\.c&#8203;:322&#8203;:24&#8203;: warning&#8203;: uninitialized const ‘utf8\_viscii’ is invalid
in C\+\+ \[\-Wc\+\+\-compat\]
&nbsp;  322 | static const encpage\_t utf8\_viscii\[\];
&nbsp;      |                        ^~~~~~~~~~~
byte\_t\.c&#8203;:1144&#8203;:24&#8203;: warning&#8203;: duplicate declaration of
‘utf8\_AdobeStandardEncoding’ is invalid in C\+\+ \[\-Wc\+\+\-compat\]
 1144 | static const encpage\_t utf8\_AdobeStandardEncoding\[10\] = \{
&nbsp;      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
byte\_t\.c&#8203;:12&#8203;:24&#8203;: note&#8203;: previous declaration of
‘utf8\_AdobeStandardEncoding’ was here
&nbsp;   12 | static const encpage\_t utf8\_AdobeStandardEncoding\[\];
&nbsp;      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl 5.31.0:

Configured by dur-randir at Wed Feb 27 14:51:01 MSK 2019.

Summary of my perl5 (revision 5 version 31 subversion 0) configuration:
  Commit id: 58f4626762668e1c1948832073998af84b2c85d0
  Platform:
    osname=linux
    osvers=4.19.0-5-amd64
    archname=x86_64-linux
    uname='linux dorothy 4.19.0-5-amd64 #1 smp debian 4.19.37-3
(2019-05-15) x86_64 gnulinux '
    config_args='-de -Dusedevel -DDEBUGGING -Dcc=gcc-9'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc-9'
    ccflags ='-fwrapv -DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE
-D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2 -g'
    cppflags='-fwrapv -DDEBUGGING -fno-strict-aliasing -pipe
-fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='9.1.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='gcc-9'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib
/usr/lib/gcc/x86_64-linux-gnu/9/include-fixed
/usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu
/lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.28.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.28'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl):
  Compile-time options:
    DEBUGGING
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at May 23 2019 12:15:21
  %ENV:
    PERLBREW_BASHRC_VERSION="0.78"
    PERLBREW_HOME="/home/afl/.perlbrew"
    PERLBREW_MANPATH="/home/afl/perlbrew/perls/perl-5.20.2/man"
    PERLBREW_PATH="/home/afl/perlbrew/bin:/home/afl/perlbrew/perls/perl-5.20.2/bin"
    PERLBREW_PERL="perl-5.20.2"
    PERLBREW_ROOT="/home/afl/perlbrew"
    PERLBREW_VERSION="0.78"
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/5.31.0/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.31.0
    /usr/local/lib/perl5/5.31.0/x86_64-linux
    /usr/local/lib/perl5/5.31.0

```
</details>

**Comment by p5pRT** [comment]
### From @hvds

On Thu\, 23 May 2019 02&#8203;:23&#8203;:48 \-0700\, randir wrote&#8203;:
> This is a bug report for perl from sergey\.aleynikov@&#8203;gmail\.com\,
> generated with the help of perlbug 1\.41 running under perl 5\.31\.0\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please describe your issue here\]
> 
> I get the following warnings when building perl on Debian with gcc
> 9\.1\.0
> 
> Wformat\-overflow&#8203;:
> 
> locale\.c&#8203;: In function ‘Perl\_\_is\_cur\_LC\_category\_utf8’&#8203;:
> locale\.c&#8203;:5087&#8203;:17&#8203;: warning&#8203;: ‘%s’ directive argument is null \[\-Wformat\-
> overflow=\]

This one definitely looks like a bug\, code was added by Karl in de3a3072\.

> Wc\+\+\-compat \(lots of\, here's the pattern\)&#8203;:
> 
> byte\_t\.c&#8203;:322&#8203;:24&#8203;: warning&#8203;: uninitialized const ‘utf8\_viscii’ is invalid
> in C\+\+ \[\-Wc\+\+\-compat\]
>   322 | static const encpage\_t utf8\_viscii\[\];
>       |                        ^~~~~~~~~~~
> byte\_t\.c&#8203;:1144&#8203;:24&#8203;: warning&#8203;: duplicate declaration of
> ‘utf8\_AdobeStandardEncoding’ is invalid in C\+\+ \[\-Wc\+\+\-compat\]
>  1144 | static const encpage\_t utf8\_AdobeStandardEncoding\[10\] = \{
>       |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
> byte\_t\.c&#8203;:12&#8203;:24&#8203;: note&#8203;: previous declaration of
> ‘utf8\_AdobeStandardEncoding’ was here
>    12 | static const encpage\_t utf8\_AdobeStandardEncoding\[\];
>       |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~

These I don't think we should care about\, we explicitly use different code \#ifdef \_\_cplusplus\.

Hugo

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @dur-randir

On Thu\, 23 May 2019 08&#8203;:25&#8203;:25 \-0700\, hv wrote&#8203;:
> These I don't think we should care about\, we explicitly use different
> code \#ifdef \_\_cplusplus\.

They've enabled them by default\, so should perl add \-Wno\-c\+\+\-compat \(or whatever is it called\)?

**Comment by p5pRT** [comment]
### From @hvds

On Thu\, 23 May 2019 08&#8203;:25&#8203;:25 \-0700\, hv wrote&#8203;:
> On Thu\, 23 May 2019 02&#8203;:23&#8203;:48 \-0700\, randir wrote&#8203;:
> > This is a bug report for perl from sergey\.aleynikov@&#8203;gmail\.com\,
> > generated with the help of perlbug 1\.41 running under perl 5\.31\.0\.
> >
> >
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > \[Please describe your issue here\]
> >
> > I get the following warnings when building perl on Debian with gcc
> > 9\.1\.0
> >
> > Wformat\-overflow&#8203;:
> >
> > locale\.c&#8203;: In function ‘Perl\_\_is\_cur\_LC\_category\_utf8’&#8203;:
> > locale\.c&#8203;:5087&#8203;:17&#8203;: warning&#8203;: ‘%s’ directive argument is null \[\-Wformat\-
> > overflow=\]
> 
> This one definitely looks like a bug\, code was added by Karl in
> de3a3072\.

This was fixed in 01b91050db552dbb89e4bd2eb6d089ebd0f28c1e\.

Hugo

**Comment by p5pRT** [comment]
### From @hvds

On Thu\, 23 May 2019 09&#8203;:43&#8203;:35 \-0700\, randir wrote&#8203;:
> On Thu\, 23 May 2019 08&#8203;:25&#8203;:25 \-0700\, hv wrote&#8203;:
> > These I don't think we should care about\, we explicitly use different
> > code \#ifdef \_\_cplusplus\.
> 
> They've enabled them by default\, so should perl add \-Wno\-c\+\+\-compat
> \(or whatever is it called\)?

I have little opinion on that\, I know little about the use or intent of perl's C\+\+ support\. If it's possible\, ideal would be to disable such warnings only within the ifndef \_\_cplusplus branches&#8203;: they're potentially useful elsewhere\.

Hugo

**Comment by jkeenan** [comment]
As of Dec 8, the state of build-time warnings with gcc-9 looked like this:
```
$ ~/bin/perl/report-build-warnings make.freebsd13.gcc9.useithreads.output.txt.gz
File:  make.freebsd13.gcc9.useithreads.output.txt.gz

  Wc++-compat                              240
  Wcast-function-type                        1
  Wformat-overflow=                          3
  Wunused-variable                           4
```
Now, this was measured on FreeBSD-31 (I don't have gcc-9 available on my linuxes) with a threaded build.  I can supply a list of all the specific warnings if so desired.

I really would like to see the `-Wc++-compat` warnings (almost all of which are in file `byte_t.c`) cleared up.  Rationale:  We will inevitably see much more testing (smoke-testing and otherwise) with gcc-9 in the year to come.  To have this many warnings of one category may obscure the first appearance of other, more serious warnings.

@khwilliamson , @hvds, @dur-randir , what can we do to make this happen?

Thank you very much.
Jim Keenan

**Comment by hvds** [comment]
Thinking further on this, as long as we're regularly building with C++ we get no additional value from C++-compat warnings when building in non-C++ mode. So I think disabling those warnings in C builds would be the right thing to do.

Hugo

**Comment by jkeenan** [comment]
> Thinking further on this, as long as we're regularly building with C++ we get no additional value from C++-compat warnings when building in non-C++ mode. So I think disabling those warnings in C builds would be the right thing to do.
> 
> Hugo

The problem I see with simply turning a particular category of warnings off is that we would not thereafter be prompted to write source code with enough precision to cover different C-compilers.  Rather than suppressing reporting of a problem, shouldn't we learn how to fix the problem (assuming it's actually possible to do so)?

Thank you very much.
Jim Keenan

**Comment by hvds** [comment]
> > Thinking further on this, as long as we're regularly building with C++ we get no additional value from C++-compat warnings when building in non-C++ mode. So I think disabling those warnings in C builds would be the right thing to do.
> 
> The problem I see with simply turning a particular category of warnings off is that we would not thereafter be prompted to write source code with enough precision to cover different C-compilers. Rather than suppressing reporting of a problem, shouldn't we learn how to fix the problem (assuming it's actually possible to do so)?

Sorry, I don't think I understand your point. The warning is about C++-compatibility, but we handle C++-compatibility ourselves by having distinct code branches. Where we have two code branches, one for C compilers and the other for C++ compilers, we do not need the former to be C++-compatible.

If we compile the code under g++ at the same version, we'll get all the C++-compatibility warnings that are useful to us. Those are the ones we should care about.

Hugo

**Comment by jkeenan** [comment]
> > > Thinking further on this, as long as we're regularly building with C++ we get no additional value from C++-compat warnings when building in non-C++ mode. So I think disabling those warnings in C builds would be the right thing to do.
> > 
> > 
> > The problem I see with simply turning a particular category of warnings off is that we would not thereafter be prompted to write source code with enough precision to cover different C-compilers. Rather than suppressing reporting of a problem, shouldn't we learn how to fix the problem (assuming it's actually possible to do so)?
> 
> Sorry, I don't think I understand your point. The warning is about C++-compatibility, but we handle C++-compatibility ourselves by having distinct code branches. Where we have two code branches, one for C compilers and the other for C++ compilers, we do not need the former to be C++-compatible.
> 

@hvds Would you be able to supply an example of your suggested ("two-branch") approach would work with one of our source-code files?

> If we compile the code under g++ at the same version, we'll get all the C++-compatibility warnings that are useful to us. Those are the ones we should care about.
> 

Thank you very much.
Jim Keenan

**Comment by hvds** [comment]
> > Sorry, I don't think I understand your point. The warning is about C++-compatibility, but we handle C++-compatibility ourselves by having distinct code branches. Where we have two code branches, one for C compilers and the other for C++ compilers, we do not need the former to be C++-compatible.
> 
> @hvds Would you be able to supply an example of your suggested ("two-branch") approach would work with one of our source-code files?

The "two-branch" approach is what we _currently_ have anywhere we compile distinct code depending on `#ifdef __cpluspus`. Just grep the code for 'cplusplus' to see all the examples.

Any code that is explicitly not compiled when __cplusplus is not defined is not expected to be C++-compatible, and it is not useful to get warnings that it is not.

**Comment by jkeenan** [comment]
> As of Dec 8, the state of build-time warnings with gcc-9 looked like this:
> 
> ```
> $ ~/bin/perl/report-build-warnings make.freebsd13.gcc9.useithreads.output.txt.gz
> File:  make.freebsd13.gcc9.useithreads.output.txt.gz
> 
>   Wc++-compat                              240
>   Wcast-function-type                        1
>   Wformat-overflow=                          3
>   Wunused-variable                           4
> ```
> 
> Now, this was measured on FreeBSD-31 (I don't have gcc-9 available on my linuxes) with a threaded build. I can supply a list of all the specific warnings if so desired.
> 

I now have gcc-9.3.0 available on Linux following an upgrade to Ubuntu 20.04 LTS.  Here is the current status of build-time warnings on an unthreaded build on Linux with that C-compiler:
```
$ report-build-warnings blead.2ce8ebb919.linux.unthreaded.maketp.output.txt.gz 
File:  blead.2ce8ebb919.linux.unthreaded.maketp.output.txt.gz

  Wc++-compat                              240
```
Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> 
> I now have gcc-9.3.0 available on Linux following an upgrade to Ubuntu 20.04 LTS. Here is the current status of build-time warnings on an unthreaded build on Linux with that C-compiler:
> 
> ```
> $ report-build-warnings blead.2ce8ebb919.linux.unthreaded.maketp.output.txt.gz 
> File:  blead.2ce8ebb919.linux.unthreaded.maketp.output.txt.gz
> 
>   Wc++-compat                              240
> ```
> 


Status unchanged as of commit 3e25f6d2dc (Mar 21 2021).

**Comment by jkeenan** [comment]
> > I now have gcc-9.3.0 available on Linux following an upgrade to Ubuntu 20.04 LTS. Here is the current status of build-time warnings on an unthreaded build on Linux with that C-compiler:
> > ```
> > $ report-build-warnings blead.2ce8ebb919.linux.unthreaded.maketp.output.txt.gz 
> > File:  blead.2ce8ebb919.linux.unthreaded.maketp.output.txt.gz
> > 
> >   Wc++-compat                              240
> > ```
> 
> Status unchanged as of commit [3e25f6d](https://github.com/Perl/perl5/commit/3e25f6d2dce9289bf3894d673f992195fb530d8e) (Mar 21 2021).

The status of build-time warnings when we compile with gcc-9 has changed since the last update to this ticket.

This commit:
```
commit 9cc5c436f846b78979eaa14aa6678db1270f7a46
CommitDate: Sat May 22 10:21:26 2021 +0200

    Update Scalar-List-Utils to 1.56
```
... introduced warnings in these categories:
```
  Wsign-compare                              4
  Wtype-limits                               2
```
If you compile with `clang10`, you set a slightly different set of the same warnings categories associated with the same commit.

I have filed this ticket upstream: https://rt.cpan.org/Ticket/Display.html?id=136985

@leonerd, can you take a look?

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> > I now have gcc-9.3.0 available on Linux following an upgrade to Ubuntu 20.04 LTS. Here is the current status of build-time warnings on an unthreaded build on Linux with that C-compiler:
> > ```
> > $ report-build-warnings blead.2ce8ebb919.linux.unthreaded.maketp.output.txt.gz 
> > File:  blead.2ce8ebb919.linux.unthreaded.maketp.output.txt.gz
> > 
> >   Wc++-compat                              240
> > ```
> 
> Status unchanged as of commit [3e25f6d](https://github.com/Perl/perl5/commit/3e25f6d2dce9289bf3894d673f992195fb530d8e) (Mar 21 2021).

Status unchanged as of 765cd54646 (Feb 22 2022).

**Comment by demerphq** [comment]
With the merge of Encode 3.17 I believe we have no further gcc 9.1.0 warnings from -Wc++-compat, so I am closing this issue.
