### ISSUE TITLE
Adjust macros dealing with UTF-8 to require extra parameter

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#17024]
Migrated from [rt.perl.org#134142](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134142) (status was 'new')

Searchable as RT134142$

**Comment by p5pRT** [comment]
### From @jkeenan

pod/perldeprecation\.pod contains the following entry for perl\-5\.32&#8203;:

\#\#\#\#\#
In XS code\, use of various macros dealing with UTF\-8\.

These macros will require an extra parameter in Perl 5\.32&#8203;:
"isALPHANUMERIC\_utf8"\, "isASCII\_utf8"\, "isBLANK\_utf8"\,
"isCNTRL\_utf8"\, "isDIGIT\_utf8"\, "isIDFIRST\_utf8"\,
"isPSXSPC\_utf8"\, "isSPACE\_utf8"\, "isVERTWS\_utf8"\,
"isWORDCHAR\_utf8"\, "isXDIGIT\_utf8"\,
"isALPHANUMERIC\_LC\_utf8"\, "isALPHA\_LC\_utf8"\,
"isASCII\_LC\_utf8"\, "isBLANK\_LC\_utf8"\, "isCNTRL\_LC\_utf8"\,
"isDIGIT\_LC\_utf8"\, "isGRAPH\_LC\_utf8"\, "isIDCONT\_LC\_utf8"\,
"isIDFIRST\_LC\_utf8"\, "isLOWER\_LC\_utf8"\, "isPRINT\_LC\_utf8"\,
"isPSXSPC\_LC\_utf8"\, "isPUNCT\_LC\_utf8"\, "isSPACE\_LC\_utf8"\,
"isUPPER\_LC\_utf8"\, "isWORDCHAR\_LC\_utf8"\,
"isXDIGIT\_LC\_utf8"\, "toFOLD\_utf8"\, "toLOWER\_utf8"\,
"toTITLE\_utf8"\, and "toUPPER\_utf8"\.

There is now a macro that corresponds to each one of these\,
simply by appending "\_safe" to the name\. It takes the extra
parameter\. For example\, "isDIGIT\_utf8\_safe" corresponds to
"isDIGIT\_utf8"\, but takes the extra parameter\, and its use
doesn't generate a deprecation warning\. All are documented
in "Character case changing" in perlapi and "Character
classification" in perlapi\.

You can change to use these versions at any time\, or\, if
you can live with the deprecation messages\, wait until 5\.32
and add the parameter to the existing calls\, without
changing the names\.

This change was originally scheduled for 5\.30\, but was
delayed\.
\#\#\#\#\#

This entry was recorded in the following commit&#8203;:

\#\#\#\#\#
commit 5203d63deea0ef134714a48c272a928fbbe64ce1
Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
Date&#8203;: Tue Jan 8 21&#8203;:04&#8203;:36 2019 \-0700

Delay fatalization of deprecation of unsafe UTF\-8 macros
from XS

Trying to earlier make this fatal led to some issues in
primarily Tk\, which I haven't had a chance to address\, and
it's getting to late in the development cycle to do it now\.
\#\#\#\#\#

Make it so\.

**Comment by p5pRT** [comment]
### From @jkeenan

```
Summary of my perl5 (revision 5 version 31 subversion 0) configuration​:
  Commit id​: 58f4626
  Platform​:
  osname=linux
  osvers=4.15.0-50-generic
  archname=x86_64-linux
  uname='linux zareason 4.15.0-50-generic #54-ubuntu smp mon may 6 18​:46​:08 utc 2019 x86_64 x86_64 x86_64 gnulinux '
  config_args='-des -Dusedevel -Dusemymalloc=y'
  hint=recommended
  useposix=true
  d_sigaction=define
  useithreads=undef
  usemultiplicity=undef
  use64bitint=define
  use64bitall=define
  uselongdouble=undef
  usemymalloc=y
  default_inc_excludes_dot=define
  bincompat5005=undef
  Compiler​:
  cc='cc'
  ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
  optimize='-O2'
  cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
  ccversion=''
  gccversion='7.4.0'
  gccosandvers=''
  intsize=4
  longsize=8
  ptrsize=8
  doublesize=8
  byteorder=12345678
  doublekind=3
  d_longlong=define
  longlongsize=8
  d_longdbl=define
  longdblsize=16
  longdblkind=3
  ivtype='long'
  ivsize=8
  nvtype='double'
  nvsize=8
  Off_t='off_t'
  lseeksize=8
  alignbytes=8
  prototype=define
  Linker and Libraries​:
  ld='cc'
  ldflags =' -fstack-protector-strong -L/usr/local/lib'
  libpth=/usr/local/lib /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed /usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib /lib64 /usr/lib64
  libs=-lpthread -lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc
  perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
  libc=libc-2.27.so
  so=so
  useshrplib=false
  libperl=libperl.a
  gnulibc_version='2.27'
  Dynamic Linking​:
  dlsrc=dl_dlopen.xs
  dlext=so
  d_dlsymun=undef
  ccdlflags='-Wl,-E'
  cccdlflags='-fPIC'
  lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'

Characteristics of this binary (from libperl)​:
  Compile-time options​:
  HAS_TIMES
  MYMALLOC
  PERLIO_LAYERS
  PERL_COPY_ON_WRITE
  PERL_DONT_CREATE_GVSV
  PERL_MALLOC_WRAP
  PERL_OP_PARENT
  PERL_PRESERVE_IVUV
  PERL_USE_DEVEL
  USE_64_BIT_ALL
  USE_64_BIT_INT
  USE_LARGE_FILES
  USE_LOCALE
  USE_LOCALE_COLLATE
  USE_LOCALE_CTYPE
  USE_LOCALE_NUMERIC
  USE_LOCALE_TIME
  USE_PERLIO
  USE_PERL_ATOF
  Built under linux
  Compiled at May 22 2019 14​:58​:04
  %ENV​:
  PERL2DIR="/home/jkeenan/gitwork/perl2"
  PERLBREW_HOME="/home/jkeenan/.perlbrew"
  PERLBREW_MANPATH="/home/jkeenan/perl5/perlbrew/perls/perl-5.28.0/man"
  PERLBREW_PATH="/home/jkeenan/perl5/perlbrew/bin​:/home/jkeenan/perl5/perlbrew/perls/perl 5.28.0/bin"
  PERLBREW_PERL="perl-5.28.0"
  PERLBREW_ROOT="/home/jkeenan/perl5/perlbrew"
  PERLBREW_SHELLRC_VERSION="0.84"
  PERLBREW_VERSION="0.84"
  PERL_WORKDIR="/home/jkeenan/gitwork/perl"
  @​INC​:
  lib
  /usr/local/lib/perl5/site_perl/5.31.0/x86_64-linux
  /usr/local/lib/perl5/site_perl/5.31.0
  /usr/local/lib/perl5/5.31.0/x86_64-linux
  /usr/local/lib/perl5/5.31.0
```

**Comment by toddr** [comment]
@khwilliamson

**Comment by khwilliamson** [comment]
I don't understand why I'm being pinged on this.  The macros have now been changed, but doing so led to BBC tickets, as expected, and those have to be fixed before we can close this.

**Comment by xsawyerx** [comment]
I can't find the distributions this affects.

**Comment by khwilliamson** [comment]
Tk and Devel::Cover.

After the next release of Devel::PPPort, I will submit a PR for Tk.  I haven't looked at Devel::Cover.  It's using "stolen_chunk_of_toke", which should be fixed.  Hopefully its the same chunk as another distro was using and we can do the same thing as we did for that.  I'd have to research which distro.

**Comment by xsawyerx** [comment]
Looping in @pjcj on this. Is this the same breakage as [this issue](https://github.com/pjcj/Devel--Cover/issues/245)?

**Comment by pjcj** [comment]
At a first glance, I suspect it is not.  The Devel::Cover breakage in that ticket, I think, comes from 4df857782a14d0973f58f6a629019d29259b2aad

**Comment by khwilliamson** [comment]
https://github.com/eserte/perl-tk/pull/61 has been issued for this

**Comment by toddr** [comment]
The PR for eserte/perl-tk#61 seems to be ready to merge. I assume we can close this.

**Comment by jkeenan** [comment]
> The PR for [eserte/perl-tk#61](https://github.com/eserte/perl-tk/pull/61) seems to be ready to merge. I assume we can close this.

Let's give the maintainer the breathing room he has requested to get a new Tk release out.
