### ISSUE TITLE
Further elimination of unescaped left braces in regular expressions

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#17023]
Migrated from [rt.perl.org#134141](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134141) (status was 'open')

Searchable as RT134141$

**Comment by p5pRT** [comment]
### From @jkeenan

pod/perldeprecation\.pod contains the following entry for perl\-5\.32&#8203;:

\#\#\#\#\#
Unescaped left braces in regular expressions

The simple rule to remember\, if you want to match a literal
"\{" character \(U\+007B "LEFT CURLY BRACKET"\) in a regular
expression pattern\, is to escape each literal instance of
it in some way\. Generally easiest is to precede it with a
backslash\, like "\\\{" or enclose it in square brackets
\("\[\{\]"\)\. If the pattern delimiters are also braces\, any
matching right brace \("\}"\) should also be escaped to avoid
confusing the parser\, for example\,

qr\{abc\\\{def\\\}ghi\}

Forcing literal "\{" characters to be escaped will enable
the Perl language to be extended in various ways in future
releases\. To avoid needlessly breaking existing code\, the
restriction is is not enforced in contexts where there are
unlikely to ever be extensions that could conflict with the
use there of "\{" as a literal\. A non\-deprecation warning
that the left brace is being taken literally is raised in
contexts where there could be confusion about it\.

Literal uses of "\{" were deprecated in Perl 5\.20\, and some
uses of it started to give deprecation warnings since\.
These cases were made fatal in Perl 5\.26\. Due to an
oversight\, not all cases of a use of a literal "\{" got a
deprecation warning\. Some cases started warning in Perl
5\.26\, and were made fatal in Perl 5\.30\. Other cases started
in Perl 5\.28\, and will be made fatal in 5\.32\.
\#\#\#\#\#

This entry was recorded in the following commit&#8203;:

\#\#\#\#\#
commit 0367231ce260cd08bcb13082d510e5778668bcc1
Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
Date&#8203;: Thu Jan 4 12&#8203;:53&#8203;:29 2018 \-0700

Raise deprecation for qr/\(?foo\}\)/

An unescaped left brace that is meant to be taken literally
is officially deprecated\, though there are no plans to
remove it in contexts where we don't expect to use it to
mean something else\, and no warning is raised in those
contexts\.

reg\_mesg\.t tests the known set of these contexts\, currently
\(after this commit\)&#8203;:

/^\{/ /foo|\{/ /foo|^\{/ /foo\(&#8203;:?\{bar\)/ /\\s\*\{/ /a\{3\,4\}\{/

This commit deprecates this context&#8203;: /foo\(\{bar\}\)/

This probably should have been illegal all along when 'bar'
is a valid quantifier\, as we do with the other quantifiers
that follow a left paren whose illegality we haven't
already taken advantage of to mean something else&#8203;:

qr/\(\+0\)/ Quantifier follows nothing in regex

This deprecation will allow \(\{\.\.\.\}\) to be usable for a
possible future regex extension
\#\#\#\#\#

Make it so\.

**Comment by p5pRT** [comment]
### From @jkeenan

Summary of my perl5 \(revision 5 version 31 subversion 0\) configuration&#8203;:
&nbsp;  Commit id&#8203;: 58f4626762668e1c1948832073998af84b2c85d0
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux
&nbsp;    osvers=4\.15\.0\-50\-generic
&nbsp;    archname=x86\_64\-linux
&nbsp;    uname='linux zareason 4\.15\.0\-50\-generic \#54\-ubuntu smp mon may 6 18&#8203;:46&#8203;:08 utc 2019 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;    config\_args='\-des \-Dusedevel \-Dusemymalloc=y'
&nbsp;    hint=recommended
&nbsp;    useposix=true
&nbsp;    d\_sigaction=define
&nbsp;    useithreads=undef
&nbsp;    usemultiplicity=undef
&nbsp;    use64bitint=define
&nbsp;    use64bitall=define
&nbsp;    uselongdouble=undef
&nbsp;    usemymalloc=y
&nbsp;    default\_inc\_excludes\_dot=define
&nbsp;    bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'
&nbsp;    ccflags ='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'
&nbsp;    optimize='\-O2'
&nbsp;    cppflags='\-fwrapv \-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''
&nbsp;    gccversion='7\.4\.0'
&nbsp;    gccosandvers=''
&nbsp;    intsize=4
&nbsp;    longsize=8
&nbsp;    ptrsize=8
&nbsp;    doublesize=8
&nbsp;    byteorder=12345678
&nbsp;    doublekind=3
&nbsp;    d\_longlong=define
&nbsp;    longlongsize=8
&nbsp;    d\_longdbl=define
&nbsp;    longdblsize=16
&nbsp;    longdblkind=3
&nbsp;    ivtype='long'
&nbsp;    ivsize=8
&nbsp;    nvtype='double'
&nbsp;    nvsize=8
&nbsp;    Off\_t='off\_t'
&nbsp;    lseeksize=8
&nbsp;    alignbytes=8
&nbsp;    prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'
&nbsp;    ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/gcc/x86\_64\-linux\-gnu/7/include\-fixed /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib /lib64 /usr/lib64
&nbsp;    libs=\-lpthread \-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.27\.so
&nbsp;    so=so
&nbsp;    useshrplib=false
&nbsp;    libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.27'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs
&nbsp;    dlext=so
&nbsp;    d\_dlsymun=undef
&nbsp;    ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'
&nbsp;    lddlflags='\-shared \-O2 \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;:
&nbsp;    HAS\_TIMES
&nbsp;    MYMALLOC
&nbsp;    PERLIO\_LAYERS
&nbsp;    PERL\_COPY\_ON\_WRITE
&nbsp;    PERL\_DONT\_CREATE\_GVSV
&nbsp;    PERL\_MALLOC\_WRAP
&nbsp;    PERL\_OP\_PARENT
&nbsp;    PERL\_PRESERVE\_IVUV
&nbsp;    PERL\_USE\_DEVEL
&nbsp;    USE\_64\_BIT\_ALL
&nbsp;    USE\_64\_BIT\_INT
&nbsp;    USE\_LARGE\_FILES
&nbsp;    USE\_LOCALE
&nbsp;    USE\_LOCALE\_COLLATE
&nbsp;    USE\_LOCALE\_CTYPE
&nbsp;    USE\_LOCALE\_NUMERIC
&nbsp;    USE\_LOCALE\_TIME
&nbsp;    USE\_PERLIO
&nbsp;    USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at May 22 2019 14&#8203;:58&#8203;:04
&nbsp;  %ENV&#8203;:
&nbsp;    PERL2DIR="/home/jkeenan/gitwork/perl2"
&nbsp;    PERLBREW\_HOME="/home/jkeenan/\.perlbrew"
&nbsp;    PERLBREW\_MANPATH="/home/jkeenan/perl5/perlbrew/perls/perl\-5\.28\.0/man"
&nbsp;    PERLBREW\_PATH="/home/jkeenan/perl5/perlbrew/bin&#8203;:/home/jkeenan/perl5/perlbrew/perls/perl\-5\.28\.0/bin"
&nbsp;    PERLBREW\_PERL="perl\-5\.28\.0"
&nbsp;    PERLBREW\_ROOT="/home/jkeenan/perl5/perlbrew"
&nbsp;    PERLBREW\_SHELLRC\_VERSION="0\.84"
&nbsp;    PERLBREW\_VERSION="0\.84"
&nbsp;    PERL\_WORKDIR="/home/jkeenan/gitwork/perl"
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.31\.0/x86\_64\-linux
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.31\.0
&nbsp;    /usr/local/lib/perl5/5\.31\.0/x86\_64\-linux
&nbsp;    /usr/local/lib/perl5/5\.31\.0

**Comment by p5pRT** [comment]
### From @jkeenan

On Sat\, 25 May 2019 02&#8203;:18&#8203;:57 GMT\, jkeenan@&#8203;pobox\.com wrote&#8203;:
> pod/perldeprecation\.pod contains the following entry for perl\-5\.32&#8203;:
> 
> \#\#\#\#\#
> Unescaped left braces in regular expressions
> 
> The simple rule to remember\, if you want to match a literal
> "\{" character \(U\+007B "LEFT CURLY BRACKET"\) in a regular
> expression pattern\, is to escape each literal instance of
> it in some way\. Generally easiest is to precede it with a
> backslash\, like "\\\{" or enclose it in square brackets
> \("\[\{\]"\)\. If the pattern delimiters are also braces\, any
> matching right brace \("\}"\) should also be escaped to avoid
> confusing the parser\, for example\,
> 
> qr\{abc\\\{def\\\}ghi\}
> 
> Forcing literal "\{" characters to be escaped will enable
> the Perl language to be extended in various ways in future
> releases\. To avoid needlessly breaking existing code\, the
> restriction is is not enforced in contexts where there are
> unlikely to ever be extensions that could conflict with the
> use there of "\{" as a literal\. A non\-deprecation warning
> that the left brace is being taken literally is raised in
> contexts where there could be confusion about it\.
> 
> Literal uses of "\{" were deprecated in Perl 5\.20\, and some
> uses of it started to give deprecation warnings since\.
> These cases were made fatal in Perl 5\.26\. Due to an
> oversight\, not all cases of a use of a literal "\{" got a
> deprecation warning\. Some cases started warning in Perl
> 5\.26\, and were made fatal in Perl 5\.30\. Other cases started
> in Perl 5\.28\, and will be made fatal in 5\.32\.
> \#\#\#\#\#
> 
> This entry was recorded in the following commit&#8203;:
> 
> \#\#\#\#\#
> commit 0367231ce260cd08bcb13082d510e5778668bcc1
> Author&#8203;: Karl Williamson \<khw@&#8203;cpan\.org>
> Date&#8203;: Thu Jan 4 12&#8203;:53&#8203;:29 2018 \-0700
> 
> Raise deprecation for qr/\(?foo\}\)/
> 
> An unescaped left brace that is meant to be taken literally
> is officially deprecated\, though there are no plans to
> remove it in contexts where we don't expect to use it to
> mean something else\, and no warning is raised in those
> contexts\.
> 
> reg\_mesg\.t tests the known set of these contexts\, currently
> \(after this commit\)&#8203;:
> 
> /^\{/ /foo|\{/ /foo|^\{/ /foo\(&#8203;:?\{bar\)/ /\\s\*\{/ /a\{3\,4\}\{/
> 
> This commit deprecates this context&#8203;: /foo\(\{bar\}\)/
> 
> This probably should have been illegal all along when 'bar'
> is a valid quantifier\, as we do with the other quantifiers
> that follow a left paren whose illegality we haven't
> already taken advantage of to mean something else&#8203;:
> 
> qr/\(\+0\)/ Quantifier follows nothing in regex
> 
> This deprecation will allow \(\{\.\.\.\}\) to be usable for a
> possible future regex extension
> \#\#\#\#\#
> 
> Make it so\.

Karl\, do you expect to be taking this ticket on soon?  It's on our 5\.32 blockers list\.

Thanks\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by khwilliamson** [comment]
I'm now closing this ticket.  There will not be warnings when a left brace immediately follows a parenthesis, as there is a lot of code out there that has that, and wants the brace to be treated literally.  I think we got cleared up the places where we want to change the meaning of unescaped lbraces.  Those contexts have been fatal for a while now.  But I'm thinking of giving it all of 5.32 as well to generate errors rather than jumping in and changing the meaning.
