### ISSUE TITLE
BBC: f23e1643 breaks Data::Alias

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#17072]
Migrated from [rt.perl.org#134252](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134252) (status was 'open')

Searchable as RT134252$

**Comment by p5pRT** [comment]
### From @jkeenan

This was first reported to me off list by Carlos Guevara, based on his
smoke testing rigs.


http://matrix.cpantesters.org/?dist=Data-Alias

http://matrix.cpantesters.org/?dist=Syntax-Keyword-Try

Carlos also reported that test(s) in the latter distro hung. I can
confirm that on FreeBSD-11, Syntax::Keyword::Try's test t/11loop.t hung
indefinitely and had to be Ctrl-C-ed for smoking to proceed. I was
consequently not able to get a definitive bisection for that module.

On Linux I was able to bisect the problem with Data::Alias to:

#####
```
f23e164367e8b9494783181262bf4a1a16d26961 is the first bad commit
commit f23e164367e8b9494783181262bf4a1a16d26961
Author: David Mitchell <davem@iabyn.com>
Date: Tue Jun 18 15:11:12 2019 +0100

Perl_list() tail-call optimise

The part of this function that scans the children of e.g.

@a = do { void; void; list }

applying list context only to the last child, tail call
optimise that call to list().

(See also a few commits later entitled "Perl_scalar()
tail-call optimise" for a discourse on setting PL_curcop
(in)correctly.)

:100644 100644 77dc177ec9bfd8c488d2a62aacaaaedc4f2658b7
a30740f2a5a449b1644665331ba560cbc9c167ee M op.c
#####
```

No further diagnose yet attempted.

Thank you very much.
Jim Keenan

perl perl perl

**Comment by p5pRT** [comment]
### From @jkeenan

On Tue\, 02 Jul 2019 03&#8203;:02&#8203;:02 GMT\, jkeenan@&#8203;pobox\.com wrote&#8203;:
> This was first reported to me off list by Carlos Guevara\, based on his 
> smoke testing rigs\.
> 
> 
> http&#8203;://matrix\.cpantesters\.org/?dist=Data\-Alias
> 
> http&#8203;://matrix\.cpantesters\.org/?dist=Syntax\-Keyword\-Try
> 
> Carlos also reported that test\(s\) in the latter distro hung\.  I can 
> confirm that on FreeBSD\-11\, Syntax&#8203;::Keyword&#8203;::Try's test t/11loop\.t hung 
> indefinitely and had to be Ctrl\-C\-ed for smoking to proceed\.  I was 
> consequently not able to get a definitive bisection for that module\.
> 

Discussion of the hanging test in Syntax&#8203;::Keyword&#8203;::Try's test suite is moved to #17076.

Thank you very much\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by toddr** [comment]
@jkeenan Is there something left to discuss here then?

**Comment by jkeenan** [comment]
> @jkeenan Is there something left to discuss here then?

We reported the breakage to Data::Alias in its [bugtracker](https://rt.cpan.org/Ticket/Display.html?id=130156).  However, the author has not yet responded.  So the ticket is not closable.  We should review its status as we get closer to 5.32.0 release.

**Comment by xsawyerx** [comment]
I reached out to the maintainer. I don't know if I'll get a response. Still not sure what decision to make here.

**Comment by xsawyerx** [comment]
At the moment, I'm thinking of making this a non-blocker. The author is w5ill non-responsive, and there's only so far we can go without responsiveness.

A few modules are dependent on this, but not enough to break CPAN considerably.

**Comment by jkeenan** [comment]
> At the moment, I'm thinking of making this a non-blocker. The author is w5ill non-responsive, and there's only so far we can go without responsiveness.
> 
> A few modules are dependent on this, but not enough to break CPAN considerably.

Has @iabyn (the original committer) commented on this yet?

**Comment by iabyn** [comment]
On Wed, Apr 15, 2020 at 11:36:16AM -0700, James E Keenan wrote:
> > At the moment, I'm thinking of making this a non-blocker. The author is w5ill non-responsive, and there's only so far we can go without responsiveness.
> > 
> > A few modules are dependent on this, but not enough to break CPAN considerably.
> 
> Has @iabyn (the original committer) commented on this yet?

I haven't looked closely at it - also that distribution currently fails
even to compile.

But I would guess the module need its op_parent handling tweaked.

That commit of mine relies on ops' 'parent' pointers always being valid;
before this nothing much relied on them. So  mistakes in setting them
weren't getting flagged.

-- 
"I do not resent criticism, even when, for the sake of emphasis,
it parts for the time with reality".
    -- Winston Churchill, House of Commons, 22nd Jan 1941.

**Comment by jkeenan** [comment]
On 4/17/20 7:38 AM, iabyn wrote:
> On Wed, Apr 15, 2020 at 11:36:16AM -0700, James E Keenan wrote:
>  > > At the moment, I'm thinking of making this a non-blocker. The 
> author is w5ill non-responsive, and there's only so far we can go 
> without responsiveness.
>  > >
>  > > A few modules are dependent on this, but not enough to break CPAN 
> considerably.
>  >
>  > Has @iabyn (the original committer) commented on this yet?
> 
> I haven't looked closely at it - also that distribution currently fails
> even to compile.
> 
> But I would guess the module need its op_parent handling tweaked.
> 
> That commit of mine relies on ops' 'parent' pointers always being valid;
> before this nothing much relied on them. So mistakes in setting them
> weren't getting flagged.
> 

Thanks for looking into this.  On that basis, I agree that this should 
not be a blocker.

**Comment by hvds** [comment]
This was eventually fixed, latest Data::Alias shows no problems. Closing ticket.

**Comment by jkeenan** [comment]
> This was eventually fixed, latest Data::Alias shows no problems. Closing ticket.

Confirmed.  Thanks.
