### ISSUE TITLE
Bleadperl v5.31.1-58-g73cdf3a836 breaks YVES/Sereal-Decoder-4.007.tar.gz on -DDEBUGGING builds

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#17114]
Migrated from [rt.perl.org#134320](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134320) (status was 'open')

Searchable as RT134320$

**Comment by p5pRT** [comment]
### From @andk

commit 73cdf3a836756ebe82b64077bf38de0bf44736dc
Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
Date&#8203;:   Mon Apr 8 14&#8203;:17&#8203;:59 2019 \+0100

&nbsp;    Make op\_free\(\) non\-recursive

Sample fail report&#8203;: http&#8203;://www\.cpantesters\.org/cpan/report/65866002\-ac5b\-11e9\-bbd9\-42315acb998f

Enjoy\,
\-\- 
andreas
PS&#8203;: perl

**Comment by p5pRT** [comment]
### From @iabyn

On Sun\, Jul 28\, 2019 at 09&#8203;:58&#8203;:58AM \-0700\, \(Andreas J\. Koenig\) \(via RT\) wrote&#8203;:
> \# New Ticket Created by  \(Andreas J\. Koenig\) 
> \# Please include the string&#8203;:  \[perl \#134320\]
> \# in the subject line of all future correspondence about this issue\. 
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134320 >
> 
> 
> commit 73cdf3a836756ebe82b64077bf38de0bf44736dc
> Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
> Date&#8203;:   Mon Apr 8 14&#8203;:17&#8203;:59 2019 \+0100
> 
>     Make op\_free\(\) non\-recursive
> 
> Sample fail report&#8203;: http&#8203;://www\.cpantesters\.org/cpan/report/65866002\-ac5b\-11e9\-bbd9\-42315acb998f

THX\_ck\_entersub\_args\_sereal\_decoder\(\) in Decoder\.xs wasn't setting the
parent link correctly when munging an op tree\.
The following diff makes all tests pass on blead\. I haven't tested against
older perls\.

<details><summary>Inline Patch</summary>

```diff
--- Decoder.xs-	2019-08-05 15:33:13.414931329 +0100
+++ Decoder.xs	2019-08-05 17:05:14.761365063 +0100
@@ -223,13 +223,17 @@
     if (arity > min_arity)
         opopt |= OPOPT_OUTARG_HEADER;
 
-    OpMORESIB_set(pushop, cvop);
-    OpLASTSIB_set(lastargop, op_parent(lastargop));
+    /* cut out all ops between the pushmark and the RV2CV */
+    op_sibling_splice(NULL, pushop, arity, NULL);
+    /* then throw everything else out */
     op_free(entersubop);
-    newop = newUNOP(OP_NULL, 0, firstargop);
+    newop = newUNOP(OP_NULL, 0, NULL);
     newop->op_type    = OP_CUSTOM;
     newop->op_private = opopt;
     newop->op_ppaddr = opopt & OPOPT_LOOKS_LIKE ? THX_pp_looks_like_sereal : THX_pp_sereal_decode;
+    /* attach the spliced-out args as children of the custom op, while
+     * deleting the stub op created by newUNOP() */
+    op_sibling_splice(newop, NULL, 1, firstargop);
     return newop;
 }
 


-- 
```
</details>

You never really learn to swear until you learn to drive\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @jkeenan

On Mon\, 05 Aug 2019 16&#8203;:09&#8203;:50 GMT\, davem wrote&#8203;:
> On Sun\, Jul 28\, 2019 at 09&#8203;:58&#8203;:58AM \-0700\, \(Andreas J\. Koenig\) \(via RT\)
> wrote&#8203;:
> > \# New Ticket Created by  \(Andreas J\. Koenig\)
> > \# Please include the string&#8203;:  \[perl \#134320\]
> > \# in the subject line of all future correspondence about this issue\.
> > \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134320 >
> >
> >
> > commit 73cdf3a836756ebe82b64077bf38de0bf44736dc
> > Author&#8203;: David Mitchell \<davem@&#8203;iabyn\.com>
> > Date&#8203;:   Mon Apr 8 14&#8203;:17&#8203;:59 2019 \+0100
> >
> > Make op\_free\(\) non\-recursive
> >
> > Sample fail report&#8203;: http&#8203;://www\.cpantesters\.org/cpan/report/65866002\-
> > ac5b\-11e9\-bbd9\-42315acb998f
> 
> THX\_ck\_entersub\_args\_sereal\_decoder\(\) in Decoder\.xs wasn't setting the
> parent link correctly when munging an op tree\.
> The following diff makes all tests pass on blead\. I haven't tested
> against
> older perls\.
> 
> \-\-\- Decoder\.xs\- 2019\-08\-05 15&#8203;:33&#8203;:13\.414931329 \+0100
> \+\+\+ Decoder\.xs  2019\-08\-05 17&#8203;:05&#8203;:14\.761365063 \+0100
> @&#8203;@&#8203; \-223\,13 \+223\,17 @&#8203;@&#8203;
>      if \(arity > min\_arity\)
>          opopt |= OPOPT\_OUTARG\_HEADER;
> 
> \-    OpMORESIB\_set\(pushop\, cvop\);
> \-    OpLASTSIB\_set\(lastargop\, op\_parent\(lastargop\)\);
> \+    /\* cut out all ops between the pushmark and the RV2CV \*/
> \+    op\_sibling\_splice\(NULL\, pushop\, arity\, NULL\);
> \+    /\* then throw everything else out \*/
>      op\_free\(entersubop\);
> \-    newop = newUNOP\(OP\_NULL\, 0\, firstargop\);
> \+    newop = newUNOP\(OP\_NULL\, 0\, NULL\);
>      newop\->op\_type    = OP\_CUSTOM;
>      newop\->op\_private = opopt;
>      newop\->op\_ppaddr = opopt & OPOPT\_LOOKS\_LIKE ?
> THX\_pp\_looks\_like\_sereal : THX\_pp\_sereal\_decode;
> \+    /\* attach the spliced\-out args as children of the custom op\,
> while
> \+     \* deleting the stub op created by newUNOP\(\) \*/
> \+    op\_sibling\_splice\(newop\, NULL\, 1\, firstargop\);
>      return newop;
>  \}
> 

Entered comment in https://github.com/Sereal/Sereal/issues/207 citing this patch\.

Thank you very much\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by jkeenan** [comment]
I have made the patch originally submitted inline by @iabyn into a pull request to the Sereal repository:  https://github.com/Sereal/Sereal/pull/210

**Comment by toddr** [comment]
Which was merged. I assume we can close this?

**Comment by jkeenan** [comment]
> Which was merged. I assume we can close this?

Yes, I believe all the distros downstream from Sereal are now PASSing again.

Thank you very much.
Jim Keenan
