### ISSUE TITLE
Allow access to outer $_'s

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#17165]
Migrated from [rt.perl.org#134466](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134466) (status was 'open')

Searchable as RT134466$

**Comment by p5pRT** [comment]
### From @jidanni

#### Created by jidanni@gmail.com



$ man perlvar

 $\_ : the default iterator variable in a "foreach" loop if no other
variable is supplied\.

OK\, but wouldn't it be neat if one could reference "outer $\_'s" too\,
without the fuss of naming them?

for \( $doc\->createElement\('Folder'\) \) \{
&nbsp;    for \( $doc\->createElement\('Placemark'\) \) \{
$\_\_\->appendChild\($\_\);
for \( $doc\->createElement\('Camera'\) \) \{
&nbsp;   $\_\_\->appendChild\($\_\);
\}
&nbsp;    \}

Here $\_\_ refers to the "parent $\_"\.

A $\_\_\_ could refer to the "grandparent $\_"\.

Anyway\, all of them are remembered in some stack\, just currently not
accessible from inner loops\, for "no good reason\." \($\_\_ probably isn't
the best name for it\, I just made it up on the spur of the moment\.
Maybe have a number in the variable indication how many levels up it
is to access\.\)

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=wishlist

Site configuration information for perl 5.28.1:...

```
</details>

**Comment by p5pRT** [comment]
### From @jkeenan

On Wed\, 02 Oct 2019 19&#8203;:45&#8203;:48 GMT\, jidanni wrote&#8203;:
> This is a bug report for perl from jidanni@&#8203;gmail\.com\,
> generated with the help of perlbug 1\.41 running under perl 5\.28\.1\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please describe your issue here\]
> 
> $ man perlvar
> 
>  $\_ : the default iterator variable in a "foreach" loop if no other
> variable is supplied\.
> 
> OK\, but wouldn't it be neat if one could reference "outer $\_'s" too\,
> without the fuss of naming them?
> 
> for \( $doc\->createElement\('Folder'\) \) \{
>     for \( $doc\->createElement\('Placemark'\) \) \{
> $\_\_\->appendChild\($\_\);
> for \( $doc\->createElement\('Camera'\) \) \{
>    $\_\_\->appendChild\($\_\);
> \}
>     \}
> 
> Here $\_\_ refers to the "parent $\_"\.
> 
> A $\_\_\_ could refer to the "grandparent $\_"\.
> 
> Anyway\, all of them are remembered in some stack\, just currently not
> accessible from inner loops\, for "no good reason\." \($\_\_ probably isn't
> the best name for it\, I just made it up on the spur of the moment\.
> Maybe have a number in the variable indication how many levels up it
> is to access\.\)
> 

I suspect that\, given the many other uses of '$\_' \(perldoc perlvar\)\, this would be an implementation nightmare and very bug\-prone\.

Thank you very much\.

\-\- 
James E Keenan \(jkeenan@&#8203;cpan\.org\)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Wed\, 02 Oct 2019 12&#8203;:45&#8203;:48 \-0700\, jidanni wrote&#8203;:
> $ man perlvar
> 
>  $\_ : the default iterator variable in a "foreach" loop if no other
> variable is supplied\.
> 
> OK\, but wouldn't it be neat if one could reference "outer $\_'s" too\,
> without the fuss of naming them?
> 
> for \( $doc\->createElement\('Folder'\) \) \{
>     for \( $doc\->createElement\('Placemark'\) \) \{
> $\_\_\->appendChild\($\_\);
> for \( $doc\->createElement\('Camera'\) \) \{
>    $\_\_\->appendChild\($\_\);
> \}
>     \}
> 
> Here $\_\_ refers to the "parent $\_"\.
> 
> A $\_\_\_ could refer to the "grandparent $\_"\.
> 
> Anyway\, all of them are remembered in some stack\, just currently not
> accessible from inner loops\, for "no good reason\." \($\_\_ probably isn't
> the best name for it\, I just made it up on the spur of the moment\.
> Maybe have a number in the variable indication how many levels up it
> is to access\.\)

They are remembered on the save stack\, but it's non\-trivial to get to it\, which strikes me as not "no good reason"\.

We could make it simpler to get to those values \(add magic to each $\_ to point to the parent for example\)\, but that would cost to all such localizing of $\_\, since $\_ is global\, and we don't know if the programmer is accessing $\_\_\, $\_\_\_ etc in a called function\.

The $\_\_\, $\_\_\_ names are bad\, since you'd forcing a maintainer to count \_ which due to the \_ glyph joining together will be difficult to count at a glance\.

You could just name the values\, which will make the code more readable\.

Tony

**Comment by tonycoz** [comment]
I plan to reject this, unless someone else has an opposing opinion.

**Comment by jidanni** [comment]
OK go ahead. Maybe it wasn't a good idea.
