### ISSUE TITLE
regcomp.c: New build-time warning when compiling with clang

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#17182]
Migrated from [rt.perl.org#134495](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134495) (status was 'open')

Searchable as RT134495$

**Comment by p5pRT** [comment]
### From @jkeenan

When compiling perl 5 blead with clang\, I noticed two instances of a 
build\-time warning not previously noted&#8203;:

warning&#8203;: result of comparison of constant 223 with expression of type 
'char' is always false \[\-Wtautological\-constant\-out\-of\-range\-compare\]\.

See attachment\.

The code in regcomp\.c in question was recently added in commit 
3ae8ec479bc \(2019\-09\-22\)\.

Karl\, can you take a look?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From @jkeenan

\[p5p\] 531 $ report\-build\-warnings make\.blead\.gcc\.Wundef\.output\.txt
File&#8203;:  make\.blead\.gcc\.Wundef\.output\.txt

&nbsp;  Wimplicit\-fallthrough=                    35
&nbsp;  Wundef                                   155
&nbsp;  Wunused\-variable                           2

\[p5p\] 532 $ report\-build\-warnings make\.134494\-Wundef\.gcc\.Wundef\.output\.txt
File&#8203;:  make\.134494\-Wundef\.gcc\.Wundef\.output\.txt

&nbsp;  Wimplicit\-fallthrough=                    35
&nbsp;  Wundef                                    42
&nbsp;  Wunused\-variable                           2


\[perlmonger&#8203;: p5p\] $ ~/bin/perl/report\-build\-warnings make\.blead\.g\+\+\.Wundef\.output\.txt
File&#8203;:  make\.blead\.g\+\+\.Wundef\.output\.txt

&nbsp;  Wformat\-overflow=                          2
&nbsp;  Wimplicit\-fallthrough=                    32
&nbsp;  Wpragmas                                   2
&nbsp;  Wundef                                   156
&nbsp;  Wunused\-variable                           2

\[perlmonger&#8203;: p5p\] $ ~/bin/perl/report\-build\-warnings make\.134494\-Wundef\.g\+\+\.Wundef\.output\.txt
File&#8203;:  make\.134494\-Wundef\.g\+\+\.Wundef\.output\.txt

&nbsp;  Wformat\-overflow=                          2
&nbsp;  Wimplicit\-fallthrough=                    32
&nbsp;  Wpragmas                                   2
&nbsp;  Wundef                                    42
&nbsp;  Wunused\-variable                           2


\[p5p\] 533 $ report\-build\-warnings make\.blead\.clang\.Wundef\.output\.txt
File&#8203;:  make\.blead\.clang\.Wundef\.output\.txt

&nbsp;  Wtautological\-constant\-out\-of\-range\-compare   2
&nbsp;  Wundef                                   155
&nbsp;  Wunused\-variable                           2

\[p5p\] 534 $ report\-build\-warnings make\.134494\-Wundef\.clang\.Wundef\.output\.txt
File&#8203;:  make\.134494\-Wundef\.clang\.Wundef\.output\.txt

&nbsp;  Wtautological\-constant\-out\-of\-range\-compare   2
&nbsp;  Wundef                                    42
&nbsp;  Wunused\-variable                           2

**Comment by p5pRT** [comment]
### From @jkeenan

Summary of my perl5 \(revision 5 version 31 subversion 5\) configuration&#8203;:
&nbsp;  Commit id&#8203;: d1747a5aff00591af555d096abeefe31b18408f6
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux
&nbsp;    osvers=4\.15\.0\-65\-generic
&nbsp;    archname=x86\_64\-linux
&nbsp;    uname='linux zareason 4\.15\.0\-65\-generic \#74\-ubuntu smp tue sep 17 17&#8203;:06&#8203;:04 utc 2019 x86\_64 x86\_64 x86\_64 gnulinux '
&nbsp;    config\_args='\-des \-Dusedevel \-Dcc=clang'
&nbsp;    hint=recommended
&nbsp;    useposix=true
&nbsp;    d\_sigaction=define
&nbsp;    useithreads=undef
&nbsp;    usemultiplicity=undef
&nbsp;    use64bitint=define
&nbsp;    use64bitall=define
&nbsp;    uselongdouble=undef
&nbsp;    usemymalloc=n
&nbsp;    default\_inc\_excludes\_dot=define
&nbsp;    bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='clang'
&nbsp;    ccflags ='\-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64 \-D\_FORTIFY\_SOURCE=2'
&nbsp;    optimize='\-O2'
&nbsp;    cppflags='\-fno\-strict\-aliasing \-pipe \-fstack\-protector\-strong \-I/usr/local/include'
&nbsp;    ccversion=''
&nbsp;    gccversion='4\.2\.1 Compatible Clang 6\.0\.0 \(tags/RELEASE\_600/final\)'
&nbsp;    gccosandvers=''
&nbsp;    intsize=4
&nbsp;    longsize=8
&nbsp;    ptrsize=8
&nbsp;    doublesize=8
&nbsp;    byteorder=12345678
&nbsp;    doublekind=3
&nbsp;    d\_longlong=define
&nbsp;    longlongsize=8
&nbsp;    d\_longdbl=define
&nbsp;    longdblsize=16
&nbsp;    longdblkind=3
&nbsp;    ivtype='long'
&nbsp;    ivsize=8
&nbsp;    nvtype='double'
&nbsp;    nvsize=8
&nbsp;    Off\_t='off\_t'
&nbsp;    lseeksize=8
&nbsp;    alignbytes=8
&nbsp;    prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='clang'
&nbsp;    ldflags =' \-fstack\-protector\-strong \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib/llvm\-6\.0/lib/clang/6\.0\.0/lib /usr/include/x86\_64\-linux\-gnu /usr/lib /lib/x86\_64\-linux\-gnu /lib/\.\./lib /usr/lib/x86\_64\-linux\-gnu /usr/lib/\.\./lib /lib /lib64 /usr/lib64
&nbsp;    libs=\-lpthread \-lnsl \-lgdbm \-ldb \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    perllibs=\-lpthread \-lnsl \-ldl \-lm \-lcrypt \-lutil \-lc
&nbsp;    libc=libc\-2\.27\.so
&nbsp;    so=so
&nbsp;    useshrplib=false
&nbsp;    libperl=libperl\.a
&nbsp;    gnulibc\_version='2\.27'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs
&nbsp;    dlext=so
&nbsp;    d\_dlsymun=undef
&nbsp;    ccdlflags='\-Wl\,\-E'
&nbsp;    cccdlflags='\-fPIC'
&nbsp;    lddlflags='\-shared \-O2 \-L/usr/local/lib \-fstack\-protector\-strong'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Compile\-time options&#8203;:
&nbsp;    HAS\_TIMES
&nbsp;    PERLIO\_LAYERS
&nbsp;    PERL\_COPY\_ON\_WRITE
&nbsp;    PERL\_DONT\_CREATE\_GVSV
&nbsp;    PERL\_MALLOC\_WRAP
&nbsp;    PERL\_OP\_PARENT
&nbsp;    PERL\_PRESERVE\_IVUV
&nbsp;    PERL\_USE\_DEVEL
&nbsp;    USE\_64\_BIT\_ALL
&nbsp;    USE\_64\_BIT\_INT
&nbsp;    USE\_LARGE\_FILES
&nbsp;    USE\_LOCALE
&nbsp;    USE\_LOCALE\_COLLATE
&nbsp;    USE\_LOCALE\_CTYPE
&nbsp;    USE\_LOCALE\_NUMERIC
&nbsp;    USE\_LOCALE\_TIME
&nbsp;    USE\_PERLIO
&nbsp;    USE\_PERL\_ATOF
&nbsp;  Built under linux
&nbsp;  Compiled at Oct 12 2019 22&#8203;:51&#8203;:39
&nbsp;  %ENV&#8203;:
&nbsp;    PERL2DIR="/home/jkeenan/gitwork/perl2"
&nbsp;    PERLBREW\_HOME="/home/jkeenan/\.perlbrew"
&nbsp;    PERLBREW\_MANPATH="/home/jkeenan/perl5/perlbrew/perls/perl\-5\.30\.0/man"
&nbsp;    PERLBREW\_PATH="/home/jkeenan/perl5/perlbrew/bin&#8203;:/home/jkeenan/perl5/perlbrew/perls/perl\-5\.30\.0/bin"
&nbsp;    PERLBREW\_PERL="perl\-5\.30\.0"
&nbsp;    PERLBREW\_ROOT="/home/jkeenan/perl5/perlbrew"
&nbsp;    PERLBREW\_SHELLRC\_VERSION="0\.84"
&nbsp;    PERLBREW\_VERSION="0\.84"
&nbsp;    PERL\_WORKDIR="/home/jkeenan/gitwork/perl"
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    lib
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.31\.5/x86\_64\-linux
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.31\.5
&nbsp;    /usr/local/lib/perl5/5\.31\.5/x86\_64\-linux
&nbsp;    /usr/local/lib/perl5/5\.31\.5

**Comment by p5pRT** [comment]
### From @khwilliamson

On 10/12/19 8&#8203;:12 PM\, James E Keenan \(via RT\) wrote&#8203;:
> \# New Ticket Created by  James E Keenan
> \# Please include the string&#8203;:  \[perl \#134495\]
> \# in the subject line of all future correspondence about this issue\.
> \# \<URL&#8203;: https://rt-archive.perl.org/perl5/Ticket/Display.html?id=134495 >
> 
> 
> When compiling perl 5 blead with clang\, I noticed two instances of a
> build\-time warning not previously noted&#8203;:
> 
> warning&#8203;: result of comparison of constant 223 with expression of type
> 'char' is always false \[\-Wtautological\-constant\-out\-of\-range\-compare\]\.
> 
> See attachment\.
> 
> The code in regcomp\.c in question was recently added in commit
> 3ae8ec479bc \(2019\-09\-22\)\.
> 
> Karl\, can you take a look?
> 
> Thank you very much\.
> Jim Keenan
> 

This actually doesn't cause a bug due to the the current contents of 
Unicode\.  But there is a bug in the vicinity that I am working on\, and 
will fix this at the same time\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by khwilliamson** [comment]
This is fixed by 4e4df0522939c9283b72776a4779e87429296b52
