### ISSUE TITLE
perlbug needs to be adjusted to point to github

### ISSUE THREAD

**Issue by toddr** [Perl/perl5#17197]
As a result of the conversion to github, the directive from perlbug to submit tickets to perlbug@perl.org is no longer accurate. We need to come up with alternate advice. This ticket is a TODO to make this happen. I am not yet working on it but thought we should get a bug open to track the need.

**Comment by Grinnz** [comment]
Once it's decided how this is to be handled I could work on a PR to update references to perlbug throughout the documentation.

**Comment by toddr** [comment]
I haven't had time to look but this is what has been said so far.

**Issue:** What about perlbug on new versions of perl?
**Response:** The current proposal is to change perlbug to provide a
template for you to enter your information in and then direct you to
GitHub to copy/paste your submission.

**Comment by toddr** [comment]
@xsawyerx any opinions here?

**Comment by xsawyerx** [comment]
When you open a ticket on GitHub now, it asks which type of ticket and provides a template. This was done by you (@toddr) and @atoomic. I think `perlbug` would be helpful if it followed the same path. The template can then be opened by an editor (`EDITOR` environment variable) or can be configured to email (`sendmail` or `mail` or something).

Sounds good?

**Comment by toddr** [comment]
So theoretically, perlbug could be changed to:
```Please go to http://.... and open a ticket. Thanks!```

The only value I see would be for it to gather system information. Do we want to still do that? Is it useful to anyone?

**Comment by khwilliamson** [comment]
On 10/23/19 12:35 PM, Todd Rinaldo wrote:
> So theoretically, perlbug could be changed to:
> |Please go to http://.... and open a ticket. Thanks!|

Can a non-github user open a ticket?

> 
> The only value I see would be for it to gather system information. Do we 
> want to still do that? Is it useful to anyone?
>

**Comment by atoomic** [comment]
No, we explicitly want someone logged in to report a bug,
this should help limit spam, and yes a GitHub account is required in order to open a ticket.

Many other open sources projects have the same requirements using other bug trackers like redline, bugzilla, ...

**Comment by xsawyerx** [comment]
> So theoretically, perlbug could be changed to:
> `Please go to http://.... and open a ticket. Thanks!`

`perlbug` is already interactive. We could start with "What kind of ticket do you want to open?" so it could render the right template with your data. That would already be an improvement.

For example, having the entire `perl -V` to report a documentation patch is unnecessary noise - you only need to make sure it's against blead. If you want to submit a feature request, there is no need for the entire `perl -V`. If it's a security issue, it can point you to the right direction as well.

For the security, the emailing capability is useful too.

> The only value I see would be for it to gather system information. Do we want to still do that? Is it useful to anyone?

Filling in the right template and directing the user is useful, IMHO. Additionally, it could also suggest which tags to use as well to help the triaging.

**Comment by Grinnz** [comment]
Given that https://github.com/Perl/perl5/issues/new/choose already provides options for what type of ticket and presents a template with appropriate queries, including asking for perl -V output if it is a standard bug report, I think that implementing such interaction in perlbug would be a duplication of effort. Unless someone feels strongly enough to implement something more involved, I think the simplest option is to remove all major functionality and documentation from perlbug and have it direct to the GitHub issue queue.

It is true that security bugs are still reported by email, but as far as I can tell there is no current functionality or documentation in perlbug for this; this would be new behavior.

**Comment by toddr** [comment]
I agree. Probably perlbug just needs to be something that directs you to the correct URL with some sort of short explanation like "We have moved...."

**Comment by Grinnz** [comment]
For posterity, https://www.nntp.perl.org/group/perl.perl5.porters/2019/07/msg255469.html is a p5p thread that contains significant prior discussion.

**Comment by toddr** [comment]
Q What will happen to tickets that continue to be reported by perlbug
via email?

A: Reviewing the rate of new reporters, we don't expect a significant
impact. The email address will auto-reply with instructions on how to
report the issue via GitHub. For an initial interim period, we will
monitor perlbug@perl.org so issues are not lost.


Q: Can I continue reporting bugs using perlbug?

A: The current workflow using perlbug is fully supported at the moment.
We will communicate prior to any changes to this workflow.


Q: What will happen to perlbug in future versions of the language?

A: We propose transitioning it to a tool that collects report
information and then make it easy for people to then submit this report
to GitHub.

**Comment by Grinnz** [comment]
Since no one has stepped up to add or modify functionality of perlbug so far, I will proceed for the time being with a documentation PR to remove mentions of using perlbug and direct users directly to the GitHub issue queue. If perlbug is improved in the future it can be documented for its new use.

**Comment by jidanni** [comment]
Today I, after reading the perlbug man page, and checking the https://rt.perl.org/ website, and finally running the perlbug command, never suspected I was wasting my time, until getting a email back,

> f you were trying to file a Perl bug report, we suggest going to
> GitHub.
> ...
> If you didn't send it, please ignore this message.  I won't send you
> another autoresponse.

Which make me worry that next time I find another bug I won't even get the email.

So

- The man page needs to warn that you have moved to github
- The command needs to warn that you have moved to github
- https://rt.perl.org/ needs to warn that you have moved to github

**Comment by toddr** [comment]
@rspier I like the idea of redirecting the base url https://rt.perl.org/ to https://github.com/Perl/perl5/issues/

**Comment by toddr** [comment]
@Grinnz this ticket is about updating perlbug. do you consider that to be done? if so we should close this.

**Comment by toddr** [comment]
@jidanni We can't update the man page on legacy versions of perl AFAIK, right?

**Comment by Grinnz** [comment]
No this is not ready yet, the perlbug program itself still should be updated in some way to indicate the changes to bug submission.

**Comment by toddr** [comment]
@jibsheet actually the link for perl5 bugs already points to github at https://rt.perl.org/

**Comment by demerphq** [comment]
On Thu, 24 Oct 2019, 04:35 Nicolas R., <notifications@github.com> wrote:

> No, we explicitly want someone logged in to report a bug,
> this should help limit spam, and yes a GitHub account is required in order
> to open a ticket.
>
> Many other open sources projects have the same requirements using other
> bug trackers like redline,
>

I'm extremely uncomfortable with this.  I dont think we should force users
to create an account with a third party corporation to file a bug with us
or to participate in p5p dev.

Frankly if that is the end game we should stop the migration and rethink
the entire thing. For me that is a 100% showstopper.

I'm fine with us using github. Im not fine with blocking out contributions
from those who choose not to.

We need a solution for this that doesnt require people creating github
accounts.

Yves

**Comment by xenu** [comment]
Having to create a github account isn't a big barrier at all. Github accounts are free and anyone can make one.

**Comment by toddr** [comment]
> I'm extremely uncomfortable with this. I dont think we should force users to create an account with a third party corporation to file a bug with us or to participate in p5p dev. 

This was discussed on the mailing list in July. It was part of the FAQ.

**Comment by toddr** [comment]
https://www.nntp.perl.org/group/perl.perl5.porters/2019/07/msg255469.html

> Q: Will I need a GitHub account?
> 
> A: Yes. Most active perl5-porters already have an account. Requiring an
account helps address a major problem over the years: spam.
> 
> The problem with anonymous ticket submission is that it inevitably
becomes a spam target. You can of course get rid of much of the bad
traffic with filtering. However you are still left with processes that
are fragile and/or overly dependent on humans.
> 
> Q: I won't sign up for a GitHub account.
> 
> A: We understand not everyone wishes to open a GitHub account.
Unfortunately, we still need to deal with the reality of not being able
to maintain the current system.
> 
> Read access to issues and the repo do not require an account, so
everything will be open to view by anonymous access.

**Comment by jibsheet** [comment]
> @jibsheet actually the link for perl5 bugs already points to github at https://rt.perl.org/

Kindly leave me off tickets I don't have anything to do with - I haven't touched rt.perl.org in years.  Thanks!

**Comment by demerphq** [comment]
Yeah I was fine with that for active contributors but i didnt realize it
was an absolute requirement for participation. Imo that is completely
unreasonable.

Yves

**Comment by Grinnz** [comment]
What do you propose we do about it? In the mean time, we need an issue tracker that works for the majority of potential contributors, instead of the opposite that we had.

**Comment by Grinnz** [comment]
That appears to have been a mistag meant for @jidanni (you can unsubscribe yourself)

**Comment by demerphq** [comment]
On Mon, 3 Feb 2020 at 04:32, Dan Book <notifications@github.com> wrote:

> What do you propose we do about it? In the mean time, we need an issue
> tracker that works for the majority of potential contributors, instead of
> the opposite that we had.
>

Let people use Perlbug to send to p5p using their own email accounts. We
can then move the bugs to github ourselves. I expect that if perlbug says
"If you have a github account we strongly prefer that you use Github $url
to report this bug. Please ONLY use this tool if you do not have a github
account and are unwilling to create one". I expect people will just post to
p5p *anyway* if they are unwilling to use github.

Anyway, lets start a new ticket for this issue so we don't bug folks that
aren't interested.

Yves

**Comment by toddr** [comment]
> Anyway, lets start a new ticket for this issue so we don't bug folks that aren't interested. Yves

The topic remains correct and anyone that doesn't want to participate has already unsubscribed. opening a new ticket seems counterproductive.

**Comment by toddr** [comment]
> Let people use Perlbug to send to p5p using their own email accounts. We can then move the bugs to github ourselves. I expect that if perlbug says "If you have a github account we strongly prefer that you use Github $url to report this bug. Please ONLY use this tool if you do not have a github account and are unwilling to create one". I expect people will just post to p5p *anyway* if they are unwilling to use github. 

This sounds reasonable. But then won't we have exactly the problem you had the other day where you have the reporter unable to participate in the primary stream of conversation?

**Comment by demerphq** [comment]
On Mon, 3 Feb 2020 at 16:39, Todd Rinaldo <notifications@github.com> wrote:

> Let people use Perlbug to send to p5p using their own email accounts. We
> can then move the bugs to github ourselves. I expect that if perlbug says
> "If you have a github account we strongly prefer that you use Github $url
> to report this bug. Please ONLY use this tool if you do not have a github
> account and are unwilling to create one". I expect people will just post to
> p5p *anyway* if they are unwilling to use github.
>
> This sounds reasonable.
>
Thanks, I really didn't mean to sound unreasonable myself, or ungrateful
for the migration to github.


> But then won't we have exactly the problem you had the other day where you
> have the reporter unable to participate in the primary stream of
> conversation?
>
Actually the non-member *was* able to participate, it was just that github
mistakenly attributed his emails to me. Since I filed a bug report with
them about it I am hopeful that they will figure out a solution to it.
Especially as it opens them up legal liability issues that they probably
will be keen to avoid. :-)

cheers,
Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by Grinnz** [comment]
As mentioned on IRC, my proposal is to change perlbug's behavior, so that both interactively and through commandline options, the default is now to save to a file rather than email the report, the default address (-a) to be changed to `perl5-porters@perl.org`, and the information printed to the user to strongly recommend submitting bugs to GitHub for the highest chance of being usefully managed.

**Comment by demerphq** [comment]
On Mon, 3 Feb 2020 at 17:40, Dan Book <notifications@github.com> wrote:

> As mentioned on IRC, my proposal is to change perlbug's behavior, so that
> both interactively and through commandline options, the default is now to
> save to a file rather than email the report, the default address (-a) to be
> changed to perl5-porters@perl.org, and the information printed to the
> user to strongly recommend submitting bugs to GitHub for the highest chance
> of being usefully managed.
>
+1

Yves

**Comment by toddr** [comment]
> As mentioned on IRC, my proposal is to change perlbug's behavior, so that both interactively and through commandline options, the default is now to save to a file rather than email the report, the default address (-a) to be changed to `perl5-porters@perl.org`, and the information printed to the user to strongly recommend submitting bugs to GitHub for the highest chance of being usefully managed.

Ideally they would be encouraged to go to github first. I know I would be annoyed to go through the Q&A process in perlbug and then discover that I really should have just gone to github?

**Comment by karenetheridge** [comment]
Why can't the RT-to-github migration user continue to post new issues (or comments on existing issues) on behalf of users who do not wish to use the github interfaces themselves?  The perlbug utility can submit issues for users with no github accounts, and a new tool could be written to allow them to post to existing issues (with some sort of captcha to prevent spam).

**Comment by Grinnz** [comment]
Posting issues on behalf of another user has identity concerns, and this authentication information would need to be shipped with Perl which has more concerns.

**Comment by Grinnz** [comment]
You can only post to github issues with a github identity, and a captcha is not sufficient.

**Comment by karenetheridge** [comment]
I'm saying to use the github user that ported all the issues from RT in the first place (or create another one that also indicates it is a bot proxying for a user).

**Comment by Grinnz** [comment]
There is a significant difference between a github user posting a known set of data from another bug tracking system, and a github user posting data from users not authenticated to github in perpetuity. Github unfortunately has no system for this sort of interaction and such a service would have a significant burden of verification - much like that which failed in the case of RT.

**Comment by xsawyerx** [comment]
I think this discussion has derailed somewhat (though not entirely).

I'll try to recap so we could determine where to move forward:

* Github is required for submission of tickets - all tickets. We hoped we made that clear and I apologize it wasn't 100% clear. The reason is for authentication and credibility. SPAM being one of the most difficult things for the RT setup, we decided to pick a solution that reduces it almost entirely.
* `perlbug` can be kept send reports to p5p, but not to submit new tickets to GitHub.
* `perlbug` should, at the very least, change the defaults to save the file, to change the email address, and to strongly suggest using GitHub.
* `perlbug` can also be made smarter. If there's a GitHub flow, allowing it for CLI could make it easier for people to do the right thing. However, that's time and effort and will need to stay in-sync with the GitHub template flows.

I believe making these changes, for now, would be good enough. We can revisit this in future versions.

Any objections to the following steps that @Grinnz offered?

* `perlbug` save file by default.
* Change of email address to p5p.
* `perlbug` should strongly recommend using GitHub instead of sending an email report.

**Comment by Grinnz** [comment]
https://github.com/Perl/perl5/pull/17651 implements the steps mentioned, btw.

**Comment by jidanni** [comment]
All I know is currently,
```
$ man perldoc | col -b | grep -ci github
0
```
I.e., not one peep. I would just put the words "See GitHub (https...)" atop this man page and the command output.

**Comment by Grinnz** [comment]
`perlbug`, not `perldoc`

**Comment by jidanni** [comment]
> `perlbug`, not `perldoc`

Oh yeah,

```
$ man perlbug | col -b | grep -ci github
0
```

**Comment by Grinnz** [comment]
The documentation is already updated: https://perldoc.pl/perlbug

**Comment by subrook** [comment]
[If comments can be edited after they're posted, it would substantially reduce confusion if xsawyerx could change the five instances of `perldoc` in his last comment to the intended `perlbug`.  Or is this his subtle April Fool's joke?]

**Comment by toddr** [comment]
> If comments can be edited after they're posted, it would substantially reduce confusion

done.

**Comment by xsawyerx** [comment]
> [If comments can be edited after they're posted, it would substantially reduce confusion if xsawyerx could change the five instances of `perldoc` in his last comment to the intended `perlbug`. Or is this his subtle April Fool's joke?]

Nice catch. Sorry for the confusion! :)
