### ISSUE TITLE
Forbid squash and merge

### ISSUE THREAD

**Issue by khwilliamson** [Perl/perl5#17207]
One of the options that comes up is a squash and merge.  If the PR is in a shambles that it needs this, the PR should be closed and the submitter told to rebase him/her self.  And the option fo just create a merge commit comes up.  If we allow this, we have a bunch of useless commits.  The submitter can create a merge commit if necessary.

So I think these possible actions should be forbidden.

**Comment by atoomic** [comment]
@toddr initially disabled this option before reenabling it...
I also trend to agree, if we want to squash it, we should probably ask the original author.

We had the use case for one pull request, but I doubt this will be used a lot.

@toddr any opinions on this?

**Comment by haarg** [comment]
I'm not sure how using this option would cause useless commits.  The result is a single commit without a merge.

**Comment by Grinnz** [comment]
I believe that sentence was regarding the merge commit option.

**Comment by simcop2387** [comment]
Something to keep in mind with this came from the discussion in #p5p yesterday.  The commit message should contain any relevant additional authors with Co-authored-by: blah lines.  https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors  This way github at least will correctly identify the multiple authors involved and we could update any other tests/processes to work with those.

**Comment by atoomic** [comment]
I would suggest a quick vote by leaving a feedback to that message:

- leave a 👍 if you think we should ban squash and merge
- leave a 👎 if you think we should leave the `squash and merge` option available

Let's try to see where we are in the next 24/48 hours and come with a decision.

**Comment by toddr** [comment]
Squash is disabled.

I am concerned that this will lead to merges with multiple commits that are potentially incomplete and break during bisect. I don't know how to programatically enforce that short of asking people with too many commits to squash if the individual commits make no sense.
