### ISSUE TITLE
Tweak Travis CI configuration to limit the smoker outside of blead to a single flavor

### ISSUE THREAD

**Issue by atoomic** [Perl/perl5#17209]
The idea is to speedup Travis CI smoke run time.

Most of the time when submitting a case, you do not really need to run the test suite on all Perl Flavors.

I'm suggesting to limit it to a single flavor on all PR or commit outside of blead,
and let blead do the complete smoking.

Another thing we should consider is abort the Travis CI build on the first failure.

**Comment by toddr** [comment]
@atoomic If you can setup that config, I think it's the right thing to do. Alternatively we could distribute the load by sending some of it to appveyor.

**Comment by toddr** [comment]
Another thing that might speed things up significantly is to drop darwin. I notice on one of my commits that the Debian runs finish quick but it's been 2 hours and the darwin runs haven't even started.

https://travis-ci.org/Perl/perl5/builds/601909755?utm_medium=notification&utm_source=github_status
