### ISSUE TITLE
[doc] perlfaq3, a graveyard?

### ISSUE THREAD

**Issue by peterdd** [Perl/perl5#17208]
**Where**
perlfaq3
for example here: https://perldoc.pl/perlfaq3#Is-there-an-IDE-or-Windows-Perl-Editor?

**Description**
I just followed a few links in perlfaq3..

From probably worst outdated/dead to mild issues:

**OptiPerl** www.optiperl.com links now to a gaming site, so that IDE is dead?

**PerlBuilder** www.solutionsoft.com/perl.htm Domain not reachable

**visiPerl+** helpconsulting.net/visiperl/index.html a broken IIS

**Komodo** http://www.activestate.com/Products/Komodo/  Oops, This Page Could Not Be Found! (I know, they could establish a catch 404 redirect to https://www.activestate.com/products/komodo-ide/ , but they didn't. :-P )

**Visual Perl** https://www.activestate.com/Products/Visual_Perl/ Oops, This Page Could Not Be Found!

**Open Perl IDE** http://open-perl-ide.sourceforge.net/ Last release 2003 for perl 5.8 ...

**Enginsite** www.enginsite.com still exists, but the very last entry on entire site and was 2009.

**IntelliJ IDEA** https://plugins.jetbrains.com/plugin/7796 There is no 'Camelcade plugin' on that site, but was able to install the 'Perl' plugin within PhpStorm (IntelliJ IDEA family)

Also a categorization between open source/closed source and free/freemium/commercial like alternative.to has would be useful there.

**Comment by Grinnz** [comment]
The issue tracker for perlfaqs is here: https://github.com/perl-doc-cats/perlfaq/issues

**Comment by toddr** [comment]
@peterdd are you ok to open the issue in the other queue? I'm not able to transfer this ticket.

**Comment by atoomic** [comment]
we need to update the list of IDEs and add more recent ones which support Perl:

- komodo
- Sublime Text
- Visual Studio Code
...

**Comment by karenetheridge** [comment]
Looks like we can only transfer issues within the same org :/

**Comment by karenetheridge** [comment]
I created https://github.com/perl-doc-cats/perlfaq/issues/83.
