### ISSUE TITLE
isless probe in Configure broken

### ISSUE THREAD

**Issue by craigberry** [Perl/perl5#17216]
The probe for the isless macro in Configure as of v5.31.5-83-g8b64b5d162 looks like this:

```C
#include <math.h>
int main() { return isless(0.0); }
```

However, isless requires two arguments so that will always fail for any compiler that checks against the prototype.  I think it should be something like:

```C
int main() { return isless(2.0, 1.0); }
```

which will return 0 if it correctly identifies 2.0 as not being less than 1.0.

**Comment by toddr** [comment]
@tux not sure if you have notifications on yet.

**Comment by Tux** [comment]
Fixed and pushed to metaconfig. When I finished finding all the Configure changes in the backlog of 500+ github mails, I will close this

**Comment by tonycoz** [comment]
This is in blead since f40bbcb, closing.
