### ISSUE TITLE
[feature] Remove CONSERVATIVE and LIBERAL

### ISSUE THREAD

**Issue by xenu** [Perl/perl5#17232]
**Describe the solution you'd like**
In perl.h we have:
```C
/* Overall memory policy? */
#ifndef CONSERVATIVE
#   define LIBERAL 1
#endif
```
Only three places check for it:
- [doop.c:1008](https://github.com/Perl/perl5/blob/2680ac6d3569b970e651742561b6e6e4062e323f/doop.c#L1008)
- [doop.c:1118](https://github.com/Perl/perl5/blob/2680ac6d3569b970e651742561b6e6e4062e323f/doop.c#L1118)
- [pp.c:2552](https://github.com/Perl/perl5/blob/2680ac6d3569b970e651742561b6e6e4062e323f/pp.c#L2552)

All platforms except Win64 use the default, i.e. `LIBERAL`.

I have no idea why win32 makefiles define `CONSERVATIVE` for 64-bit builds. It was added in commit c623ac675720b3145d48cc2ea9474a0f3e0cbbca. Since it was in 2002, and x86_64 didn't even exist back then, my guess is that it had something to do with Windows on Itanium requiring strict alignment.

However, we don't define `CONSERVATIVE` for the other platforms that require strict alignment, so maybe it was a workaround for some ancient compiler bug?

My proposal is to remove those constants. They are undocumented and I don't think `CONSERVATIVE` provides any significant memory savings. In practice all that `CONSERVATIVE` does is making some code slightly different on Win64 for no good reason.

**Comment by khwilliamson** [comment]
Is this closable?

**Comment by xenu** [comment]
I think so.
