### ISSUE TITLE
BBC: Acme-POE-Tree-1.022 test suite fails for perl 5.31.x

### ISSUE THREAD

**Issue by eserte** [Perl/perl5#17243]
**Description**
There are no pass reports for Acme-POE-Tree-1.022 with perl 5.31.1 .. 5.31.4. Please see http://fast-matrix.cpantesters.org/?dist=Acme-POE-Tree%201.022 for an overview and sample fail reports. (5.31.5 is not listed here because it broke the dependency POE)

**Comment by dur-randir** [comment]
Bisect points to:

commit 5cf88abdca2d5d3d5c7adb953cb5f971f3c4539a
Author: Andreas Koenig <root@dubravka.in-berlin.de>
Date:   Thu Jun 13 19:04:47 2019 +0000

    [PATCH] Updates CPAN.pm to ANDK/CPAN-2.27-TRIAL2.tar.gz

PS: i haven't rechecked that it works on 5.31.4 with dowgraded CPAN.

**Comment by xsawyerx** [comment]
I wonder why that commit would break it. I can't load any of the reports. Looping in @rcaputo.

**Comment by jkeenan** [comment]
> **Description**
> There are no pass reports for Acme-POE-Tree-1.022 with perl 5.31.1 .. 5.31.4. Please see http://fast-matrix.cpantesters.org/?dist=Acme-POE-Tree%201.022 for an overview and sample fail reports. (5.31.5 is not listed here because it broke the dependency POE)

FWIW, I was able to install Acme::POE::Tree on my laptop at

> Bisect points to:
> 
> commit [5cf88ab](https://github.com/Perl/perl5/commit/5cf88abdca2d5d3d5c7adb953cb5f971f3c4539a)
> Author: Andreas Koenig [root@dubravka.in-berlin.de](mailto:root@dubravka.in-berlin.de)
> Date: Thu Jun 13 19:04:47 2019 +0000
> 
> ```
> [PATCH] Updates CPAN.pm to ANDK/CPAN-2.27-TRIAL2.tar.gz
> ```
> 
> PS: i haven't rechecked that it works on 5.31.4 with dowgraded CPAN.

FWIW, I was able to install Acme::POE::Tree on my laptop on a ```perl``` built at commit 5cf88ab.  Note that, much like Tk's test suite, running this module's sole test file produces an image to the desktop.  Could that have affected whether the test was graded ```PASS``` or not?

Thank you very much.
Jim Keenan

**Comment by dur-randir** [comment]
I don't see anything unusual/specific for a successful run:

```
Running make for R/RC/RCAPUTO/Acme-POE-Tree-1.022.tar.gz
cp lib/Acme/POE/Tree.pm blib/lib/Acme/POE/Tree.pm
Manifying 1 pod document
  RCAPUTO/Acme-POE-Tree-1.022.tar.gz
  /usr/bin/make -- OK
Running make test for RCAPUTO/Acme-POE-Tree-1.022.tar.gz
PERL_DL_NONLAZY=1 "/tmp/5QgRfbJY3C/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/01_basic.t .. ok
All tests successful.
Files=1, Tests=2,  5 wallclock secs ( 0.02 usr  0.01 sys +  0.19 cusr  0.01 csys =  0.23 CPU)
Result: PASS
  RCAPUTO/Acme-POE-Tree-1.022.tar.gz
  /usr/bin/make test -- OK
Running make install for RCAPUTO/Acme-POE-Tree-1.022.tar.gz
```

I'm running it the second time, to check that both runs agree on the same revision.

**Comment by dur-randir** [comment]
Second bisect arrived to the same commit. Command line was:

```
perl Porting/bisect.pl --start v5.30.0 --end v5.31.4 -j 20 --module=Acme::POE::Tree
```

**Comment by jkeenan** [comment]
> Bisect points to:
> 
> commit [5cf88ab](https://github.com/Perl/perl5/commit/5cf88abdca2d5d3d5c7adb953cb5f971f3c4539a)
> Author: Andreas Koenig [root@dubravka.in-berlin.de](mailto:root@dubravka.in-berlin.de)
> Date: Thu Jun 13 19:04:47 2019 +0000
> 
> ```
> [PATCH] Updates CPAN.pm to ANDK/CPAN-2.27-TRIAL2.tar.gz
> ```
> 
> PS: i haven't rechecked that it works on 5.31.4 with dowgraded CPAN.

As I conduct bisections of Perl 5 blead with the ```--module=XXX``` switch, I notice that I am now getting a lot of warnings that look like this:
```
The current configuration of allow_installing_outdated_dists is 'ask/yes', 
but for this option we would need 'CPAN::DistnameInfo' installed. Please 
install 'CPAN::DistnameInfo' as soon as possible. As long as we are not 
equipped with 'CPAN::DistnameInfo' this option does not take effect
```
This warning was introduced into ```cpan/CPAN/lib/CPAN/Distribution.pm``` in the commit identified by bisection.  Could this warning be problematic with an "Acme" module?

**Comment by jkeenan** [comment]
> > Bisect points to:
> > commit [5cf88ab](https://github.com/Perl/perl5/commit/5cf88abdca2d5d3d5c7adb953cb5f971f3c4539a)
> > Author: Andreas Koenig [root@dubravka.in-berlin.de](mailto:root@dubravka.in-berlin.de)
> > Date: Thu Jun 13 19:04:47 2019 +0000
> > ```
> > [PATCH] Updates CPAN.pm to ANDK/CPAN-2.27-TRIAL2.tar.gz
> > ```
> > 
> > 
> > PS: i haven't rechecked that it works on 5.31.4 with dowgraded CPAN.
> 
> As I conduct bisections of Perl 5 blead with the `--module=XXX` switch, I notice that I am now getting a lot of warnings that look like this:
> 
> ```
> The current configuration of allow_installing_outdated_dists is 'ask/yes', 
> but for this option we would need 'CPAN::DistnameInfo' installed. Please 
> install 'CPAN::DistnameInfo' as soon as possible. As long as we are not 
> equipped with 'CPAN::DistnameInfo' this option does not take effect
> ```
> 
> This warning was introduced into `cpan/CPAN/lib/CPAN/Distribution.pm` in the commit identified by bisection. Could this warning be problematic with an "Acme" module?

@andk @dur-randir Do you have more thoughts about this BBC(?) problem with Acme-POE-Tree?

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
Following a new release of POE today, I was able to install both POE and Acme-POE-Tree on Linux.  However, there haven't yet been [fresh CPANtesters runs](http://matrix.cpantesters.org/?dist=Acme-POE-Tree), so we'll have to keep this open a while.

**Comment by xsawyerx** [comment]
All reports show failure on `Acme-POE-Tree`, but if the testing machines use older versions of CPAN/POE, that might be the cause.

Considering `POE` works (which is what truly matters) and the reported problem is on an `Acme` module, I'm not inclined to keep this as a blocker.

Strong objections?

**Comment by jkeenan** [comment]
On 4/1/20 2:51 AM, Sawyer X wrote:
> All reports show failure on |Acme-POE-Tree|, but if the testing machines 
> use older versions of CPAN/POE, that might be the cause.
> 
> Considering |POE| works (which is what truly matters) and the reported 
> problem is on an |Acme| module, I'm not inclined to keep this as a blocker.
> 
> Strong objections?
> 

No objection.  POE is passing CPANtesters.  This is not a blocker.

Thank you very much.
Jim Keenan
