### ISSUE TITLE
BBC: Blead breaks Moose

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#17261]
Breakage brought to my attention by CPANtester Carlos Guevara, who pointed to recent reports on [Linux](http://www.cpantesters.org/cpan/report/df12a90c-ff45-11e9-8426-1e22778e3209) and [NetBSD](http://www.cpantesters.org/cpan/report/9268fc24-fed1-11e9-ab79-c3db71ecd10b), respectively.

One test in the Moose test suite is failing.  Looks like this:
```
t/basics/rebless.t ............................................... ok

#   Failed test 'but it does give a warning'
#   at t/basics/require_superclasses.t line 42.
#                   'While trying to resolve method call Bling->isa() can not locate package "No::Class" yet it is mentioned in @Bling::ISA (perhaps you forgot to load "No::Class"?) at /home/cpan/.cpan/build/Moose-2.2011-0/blib/lib/Class/MOP/Class.pm line 957.
# '
#     doesn't match '(?^:^Can't locate package No::Class for \@Bling::ISA)'
# Looks like you failed 1 test of 7.
t/basics/require_superclasses.t .................................. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/7 subtests 
```
There has been no new release of [Moose](https://metacpan.org/pod/Moose) since May 2018, so the failure is unlikely to come from the CPAN distro.

Bisection points to the following commit:

448aac914b0b0182b7d462d88f99a40dc08b6d9e is the first bad commit
commit 448aac914b0b0182b7d462d88f99a40dc08b6d9e
Author: Max Maischein <corion@corion.net>
Date:   Fri Oct 25 20:20:56 2019 +0200

    And silence some silly examples.
    From RT88754
    Adapted to the current Perl by Max Maischein
    Created from https://github.com/Perl/perl5/issues/11259

commit 448aac914b0b0182b7d462d88f99a40dc08b6d9e

Corion *et al.* can you take a look?

Thank you very much.
Jim Keenan

**Comment by haarg** [comment]
This is an intentional warning change, and is easy enough to fix in Moose's tests.

The wording of the new warning seems a bit odd though.

**Comment by xsawyerx** [comment]
Looping in @Corion on this.

**Comment by Corion** [comment]
I'm not a native English speaker so I merely kept the original phrasing. If it is odd, I'm open to changes that make it less odd.

Otherwise, I'm not sure what we want here. The breakage is expected to me, as the error message of Perl changes for unknown classes in `@ISA`. Either Moose changes its test suite to match the text of the error message, or we revert (and discard) this change.

**Comment by jkeenan** [comment]
Xref (from Andreas): https://rt.cpan.org/Ticket/Display.html?id=130929

**Comment by karenetheridge** [comment]
Moose 2.2012 has been released. I structured the regex in the test a little loosely to allow for more flexibility in the error message in the future.
