### ISSUE TITLE
New compilation warning in blead (invlist_inline.h)

### ISSUE THREAD

**Issue by dur-randir** [Perl/perl5#17275]
This is a bug report for perl from sergey.aleynikov@gmail.com,
generated with the help of perlbug 1.41 running under perl 5.31.6.

-----------------------------------------------------------------
[Please describe your issue here]

Recent commit a9269870d0bdf863ca3ff8c0027e0894d4847393 introduced the following compilation warning:

cc -c -DPERL_CORE -fno-common -DPERL_DARWIN -mmacosx-version-min=10.9 -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -I/opt/local/include -DPERL_USE_SAFE_PUTENV -std=c89 -O3 -g -Wall -Werror=declaration-after-statement -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings doop.c
In file included from doop.c:25:
./invlist_inline.h:202:1: warning: unused function 'S_invlist_iternext' [-Wunused-function]
S_invlist_iternext(SV* invlist, UV* start, UV* end)
^
1 warning generated.

[Please do not change anything below this line]
-----------------------------------------------------------------
---
Flags:
    category=core
    severity=low
---
Site configuration information for perl 5.31.6:

Configured by dur-randir at Fri Nov  8 05:18:19 MSK 2019.

Summary of my perl5 (revision 5 version 31 subversion 6) configuration:
  Commit id: 1462134e8b9d0b0b9184117b33a82887ad9711aa
  Platform:
    osname=darwin
    osvers=13.4.0
    archname=darwin-2level
    uname='darwin isengard.local 13.4.0 darwin kernel version 13.4.0: mon jan 11 18:17:34 pst 2016; root:xnu-2422.115.15~1release_x86_64 x86_64 '
    config_args='-de -Dusedevel -DDEBUGGING'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9 -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -I/opt/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3 -g'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.9 -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -I/opt/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.9 -fstack-protector -L/usr/local/lib -L/opt/local/lib'
    libpth=/usr/local/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.0/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib /usr/lib /opt/local/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.9 -bundle -undefined dynamic_lookup -L/usr/local/lib -L/opt/local/lib -fstack-protector'

---
@INC for perl 5.31.6:
    lib
    /usr/local/lib/perl5/site_perl/5.31.6/darwin-2level
    /usr/local/lib/perl5/site_perl/5.31.6
    /usr/local/lib/perl5/5.31.6/darwin-2level
    /usr/local/lib/perl5/5.31.6

---
Environment for perl 5.31.6:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/dur-randir
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_CTYPE=en_US.UTF-8
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.26.0/bin:/opt/local/bin:/usr/texbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Library/TeX/texbin
    PERLBREW_HOME=/Users/dur-randir/.perlbrew
    PERLBREW_MANPATH=/Users/dur-randir/perlbrew/perls/perl-5.26.0/man
    PERLBREW_PATH=/Users/dur-randir/perlbrew/bin:/Users/dur-randir/perlbrew/perls/perl-5.26.0/bin
    PERLBREW_PERL=perl-5.26.0
    PERLBREW_ROOT=/Users/dur-randir/perlbrew
    PERLBREW_SHELLRC_VERSION=0.86
    PERLBREW_VERSION=0.86
    PERL_BADLANG (unset)
    SHELL=/opt/local/bin/zsh

**Comment by jkeenan** [comment]
I built unthreaded perls, without and with ```-DDEBUGGING```, on both Linux and FreeBSD-11 at 6484c45ed9 using clang-6.0 as the compiler.  I got no ```-Wunused_function``` warning in any of the 4 builds.

Is it possible that this was fixed by commit f34acfecc286f2eff2450db713da005d888a7317?
```
Author:     Karl Williamson <khw@cpan.org>
AuthorDate: Mon Nov 4 21:30:48 2019 -0700
Commit:     Karl Williamson <khw@cpan.org>
CommitDate: Wed Nov 6 21:22:24 2019 -0700
```

**Comment by dur-randir** [comment]
No, this build is from 1462134e8b9d0b0b9184117b33a82887ad9711aa, which is later than f34acfecc286f2eff2450db713da005d888a7317

**Comment by jkeenan** [comment]
> No, this build is from [1462134](https://github.com/Perl/perl5/commit/1462134e8b9d0b0b9184117b33a82887ad9711aa), which is later than [f34acfe](https://github.com/Perl/perl5/commit/f34acfecc286f2eff2450db713da005d888a7317)

Well, then as in https://github.com/Perl/perl5/issues/17276, I suspect this must be specific to an older compiler version in use on Darwin.

Thank you very much.
Jim Keenan

**Comment by khwilliamson** [comment]
@dur-randir  Could you see if this branch fixes it? https://git.io/JeoKP

**Comment by dur-randir** [comment]
@khwilliamson, yes, it's gone.
