### ISSUE TITLE
[feature] indicate when a subroutine is called in lvalue mode

### ISSUE THREAD

**Issue by djerius** [Perl/perl5#17270]
It would be useful if a subroutine knew whether or not it was called in a context which used its return value as an lvalue.

Here's an existing scenario which isn't currently possible:

Subroutine `foo` returns a hash value.  If the value is being used as an r-value, the subroutine should throw if the hash value does not exist.  If the value is being used as an l-value, it should create an element in the hash and return that.  Something like this:
```
sub foo :lvalue ( $key ) {
    state %hash;

    die( "non-existent key: $key" )
        if ! in_lvalue_context && ! exists $hash{$key}; 

    return $hash{$key}
}
```

So, this would throw:
```
$a += foo( $non_existent_key );
```
and this would succeed:
```
foo( $non_existent_key ) = 2;
```

**Comment by Leont** [comment]
That's not quite how lvalue-ness works, but you can achieve the equivalent of what you want using a module like [Sentinel](https://metacpan.org/pod/Sentinel)

**Comment by djerius** [comment]
I'm familiar with Sentinel. Unfortunately it adds an extra layer of slowness by using tie if XS isn't available, which makes it somewhat unattractive for fatpacking.

Could you explain what you mean by 

> That's not quite how lvalue-ness works,

Here's some sample code which implements my original idea with an explicit lvalue_context flag:


```
use 5.10.0;
use experimental 'signatures';

sub foo :lvalue ( $key, $lvalue_context=0 ) {
    state %hash;
    die( "non-existent key: $key" )
        if ! $lvalue_context && ! exists $hash{$key}; 
    return $hash{$key}
}

foo( 'a', 1 ) = 2;
foo( 'b', 1 ) = 1;

say foo('a');
say foo('b');
say foo('c');
```
Here's the output:

```
% perl try.pl
2
1
non-existent key: c at try.pl line 11.
```

**Comment by Leont** [comment]
> Could you explain what you mean by
> > That's not quite how lvalue-ness works,

```perl
sub foo :lvalue ($key) {
    state %hash;
    return $hash{$key}
}

sub bar {
    if (@ARGV) {
        $_[0] = $ARGV[0];
    }
}
say bar(foo('baz'))
```

When `foo` is being called, it doesn't know if the result will be used as lvalue or not.

**Comment by djerius** [comment]
D'oh.  L-valueness has to be attached to the value itself.  Thanks for the reminder.

**Comment by tonycoz** [comment]
This wouldn't be all that hard to implement, if I add the following into `pp_wantarray`:

```
        {
        U8   lval    = CxLVAL(cx);
        bool is_lval = (lval && !(lval & OPpENTERSUB_INARGS));
        DEBUG_U( PerlIO_printf(Perl_debug_log, "is_lval %d\n", (int)is_lval) );
        }
```

then:

```
$ ./perl -DU -e 'my $foo; sub foo :lvalue { wantarray; $foo } foo() = 1; $z = 1+foo();'

EXECUTING...

is_lval 1
is_lval 0
```

though it returns is_lval 0 for function arguments

**Comment by djerius** [comment]
The `wantarray` approach seems promising, but I don't follow your comment:

> though it returns is_lval 0 for function arguments

**Comment by tonycoz** [comment]
Functions can modify their arguments, so if an lvalue function is called as an argument to another function, is_lval should probably be true.

**Comment by djerius** [comment]
Got it.  Thanks.

**Comment by tonycoz** [comment]
Did you intentionally re-open this? (I don't know if github re-opened it because you replied.)

**Comment by djerius** [comment]
I'm not sure. Could be I hit the wrong button.
