### ISSUE TITLE
Safe.pm

### ISSUE THREAD

**Issue by khwilliamson** [Perl/perl5#17271]
Safe.pm starting at line 60 talks about swashes.
The code it uses to load swashes hasn't done anything in the last release or so.
The only remaining use of swashes in the core C files has been in tr/// where the lhs and/or rhs have above-255 code points.
That means that if one of these is encountered, utf8_heavy.pl would need to be loaded
It's not clear to me if Safe cares about that and should try to preload it or not.
But if it does care, it needs to use a tr/// to cause it to get loaded instead of the current method, as that has been out-of-date.  As of today, utf8_heavy is gone from core, but Safe is supposed to work in earlier perl versions.  So, if it really does need utf8_heavy to be loaded when that file existed, it needs to use tr/// to force this.

**Comment by coypoop** [comment]
It's needed: https://bugzilla.mozilla.org/show_bug.cgi?id=1588175

**Comment by khwilliamson** [comment]
@coypoop   Do we know that mozilla is using Safe?  Because if not, this isn't the cause of the bug, but something similar.

**Comment by coypoop** [comment]
it's using Safe and the suggested fix (use tr///) works
