### ISSUE TITLE
[doc] perl 5.30.1 source download 404s.

### ISSUE THREAD

**Issue by dylanaraps** [Perl/perl5#17287]
**Where**

Page containing link which 404s: https://www.perl.org/get.html

**Description**

The download link for the latest (5.30.1) source 404s.

- Link: https://www.cpan.org/src/5.0/perl-5.30.1.tar.gz

**Comment by tonycoz** [comment]
It works here, it's possible whatever mirror/cdn is being pulled from wasn't up to date.

Do you still see the same error now?

**Comment by dylanaraps** [comment]
All is well now. :+1:
