### ISSUE TITLE
IRC #p5p commit bot should report branch deletions

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#17294]
The Not-f214 bot currently in use on irc.perl.org #p5p reports pushes which create new branches:
```
(10:03:07 PM) Not-f214: [perl5] jkeenan pushed 1 commit to jkeenan/make-minitest-t-re-pat [+0/-0/±1] https://git.io/JewwY
(10:03:09 PM) Not-f214: [perl5] jkeenan 58cfa81 - Test IRC bot on branches.
```
The above appeared within seconds after I executed `git push -u origin jkeenan/make-minitest-t-re-pat` in my terminal.

However, I subsequently deleted this branch.  In my terminal:
```
$ git push origin :jkeenan/make-minitest-t-re-pat
To github.com:Perl/perl5.git
 - [deleted]               jkeenan/make-minitest-t-re-pat
```
Nothing appeared within 5 minutes on \#p5p.

Our erstwhile commit bot, p5commits, reported all pushes to branches, whether for creation, update or deletion.  We should get the same functionality out of this new bot.  (This would be particularly helpful during upcoming branch cleanups.)

Thank you very much.
Jim Keenan

**Comment by atoomic** [comment]
just confirmed that the bot is now reporting deleted branch
please reopen me or comment on that case if the behavior is not the one expected
