### ISSUE TITLE
t/re/pat.t: Compilation error during make minitest due to @{^CAPTURE}

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#17293]
When running `make minitest` on blead (following up on a #p5p comment by @khwilliamson), `t/re/pat.t` fails to compile.  A trimmed-down version of the error message:
```
t/re/pat ....................... Can't locate Tie/Hash/NamedCapture.pm in @INC 
(you may need to install the Tie::Hash::NamedCapture module) 
(@INC contains: ../lib . ../ext/re 
# ... long list of directories -- not including ext/Tie-Hash-NamedCapture ...
... 
/home/jkeenan/gitwork/perl/lib .. . .) at re/pat.t line 674.
BEGIN failed--compilation aborted at re/pat.t line 674.
```
In the core distribution, we have `ext/Tie-Hash-NamedCapture/NamedCapture.pm`.  I tried various ways of dealing with this failure.  I tried adding `../ext/Tie-Hash-NamedCapture` to `@INC`.  I tried adding a `skip("message") if is_miniperl;` statement (as in `t/re/subst.t`).  None of these worked, i.e., none of them enabled the file to compile.  Whenever I hit line 674 below, I got the fatal error.
```
 672         $_= "ace";
 673         /c(?=.$)/;
 674         is($#{^CAPTURE}, -1, $message);
```
Any ideas?

**Comment by khwilliamson** [comment]
@hvds I'm proposing that we schedule regular smokes of minitest in order to catch breaking changes like this.  Can you offer insights into the importance of this?

**Comment by demerphq** [comment]
I was under the impression that miniperl can't load xs libraries. If that
is correct then named captures won't work under miniperl and we should skip
any XS related tests when we run under it.

Yves

**Comment by jkeenan** [comment]
> On Tue, 12 Nov 2019, 04:01 James E Keenan, <notifications@github.com> wrote:
> 
>  > When running make minitest on blead (following up on a #p5p comment by
>  > @khwilliamson <https://github.com/khwilliamson>), t/re/pat.t fails to
>  > compile. A trimmed-down version of the error message:
>  >
>  > t/re/pat ....................... Can't locate 
> Tie/Hash/NamedCapture.pm in @INC
>  > (you may need to install the Tie::Hash::NamedCapture module)
>  > (@INC contains: ../lib . ../ext/re
>  > # ... long list of directories -- not including 
> ext/Tie-Hash-NamedCapture ...
>  > ...
>  > /home/jkeenan/gitwork/perl/lib .. . .) at re/pat.t line 674.
>  > BEGIN failed--compilation aborted at re/pat.t line 674.
>  >
>  > In the core distribution, we have
>  > ext/Tie-Hash-NamedCapture/NamedCapture.pm. I tried various ways of
>  > dealing with this failure. I tried adding ../ext/Tie-Hash-NamedCapture to
>  > @INC. I tried adding a skip("message") if is_miniperl; statement (as in
>  > t/re/subst.t). None of these worked, i.e., none of them enabled the file
>  > to compile. Whenever I hit line 674 below, I got the fatal error.
>  >
>  > 672 $_= "ace";
>  > 673 /c(?=.$)/;
>  > 674 is($#{^CAPTURE}, -1, $message);
>  >
>  > Any ideas?
>  >

On 11/12/19 1:07 PM, Yves Orton wrote:> I was under the impression that 
miniperl can't load xs libraries. If that
> is correct then named captures won't work under miniperl and we should skip
> any XS related tests when we run under it.
> 
> Yves
> 

Yves:

The thing is:  Up until recently the test file was compiling and passing 
under 'miniperl'.  AFAICT, miniperl had no problem with this code from 
the time you added it in 2016 until recently.

I am currently trying to bisect to find the point of failure.

As mentioned earlier in the thread, last night I tried to add a SKIP 
block where the 'skip' condition was that test.pl's is_miniperl() sub 
returned true.  We have code like that in other files, e.g., 
t/re/subst.t.  But miniperl reported a compile-time error when 
attempting to run t/re/pat.t, so it never made it as far as running the 
SKIP block.

jimk

**Comment by demerphq** [comment]
I'll take a look later...

Yves

**Comment by jkeenan** [comment]
Bisection points to: 22f05786af0b7f963440e47908cd5f35cf074c12
```
22f05786af0b7f963440e47908cd5f35cf074c12 is the first bad commit
commit 22f05786af0b7f963440e47908cd5f35cf074c12
Author: Tony Cook <tony@develop-help.com>
Date:   Thu Jun 13 10:05:15 2019 +1000

    (perl #134193) allow %{^CAPTURE} to work when @{^CAPTURE} comes first
    
    gv_magicalize() is called when the GV is created, so when the array
    was mentioned first, the hash wouldn't reach this code and the magic
    wouldn't be added to the hash.
    
    This also fixes a similar problem with (%|@){^CAPTURE_ALL}, though
    @{^CAPTURE_ALL} is unused at this point.
```
Bisection invocation:
```
perl Porting/bisect.pl --target=miniperl --start=2ec4590ec8255732ec2d163daabd237cdaf886f4   -e 'q|ace| =~ /c(?=.$)/; print ((($#{^CAPTURE} == -1) ? q|AAA| : q|BBB|), "\n") && exit 0'
```
```
commit 22f05786af0b7f963440e47908cd5f35cf074c12 (refs/bisect/bad)
Author:     Tony Cook <tony@develop-help.com>
AuthorDate: Thu Jun 13 10:05:15 2019 +1000
Commit:     Tony Cook <tony@develop-help.com>
CommitDate: Wed Jun 19 14:22:10 2019 +1000
```
@tonycoz, can you take a look?

Thank you very much.
Jim Keenan

**Comment by tonycoz** [comment]
My commit made access to `*{^CAPTURE}` and `*{^CAPTURE_ALL}` load `Tie::Hash::NamedCapture` unconditionally due to `gv_magicalize()` only being called once for each GV with a name longer than one character, which is why the use of @{^CAPTURE} in this code is trying (and failing) to load it.

I can see a few solutions, which are either non-trivial or could reduce performance:

- call gv_magicalize() every time and revert the gv.c changes - this would add a performance penalty to every gv access.
- add a gvmini.o, like we have opmini.o and #ifdef out the Tie::Hash::NamedCapture load for miniperl - I'm not fond of the *mini.o hack
- move the implementation of `%{^CAPTURE}` and `%{^CAPTURE_ALL}` (and `%+`, `%-`) into the core binary - this would be largely be moving the tie code into universal.c

I'm most inclined to go for the last.

**Comment by khwilliamson** [comment]
On 11/12/19 2:49 PM, Tony Cook wrote:
> My commit made access to |*{^CAPTURE}| and |*{^CAPTURE_ALL}| load 
> |Tie::Hash::NamedCapture| unconditionally due to |gv_magicalize()| only 
> being called once for each GV with a name longer than one character, 
> which is why the use of @{^CAPTURE} in this code is trying (and failing) 
> to load it.
> 
> I can see a few solutions, which are either non-trivial or could reduce 
> performance:
> 
>   * call gv_magicalize() every time and revert the gv.c changes - this
>     would add a performance penalty to every gv access.
>   * add a gvmini.o, like we have opmini.o and #ifdef out the
>     Tie::Hash::NamedCapture load for miniperl - I'm not fond of the
>     *mini.o hack
>   * move the implementation of |%{^CAPTURE}| and |%{^CAPTURE_ALL}| (and
>     |%+|, |%-|) into the core binary - this would be largely be moving
>     the tie code into universal.c
> 
> I'm most inclined to go for the last.

I think that merely skipping this test under minitest is the way to go. 
Unless this has uncovered a performance issue.  minitest is known to be 
crippled, and many tests are skipped in it that would require a load.

**Comment by demerphq** [comment]
I'd go for the last too.

Yves
Ps on a phone sorry for top posting...

**Comment by tonycoz** [comment]
> I think that merely skipping this test under minitest is the way to go. Unless this has uncovered a performance issue. minitest is known to be crippled, and many tests are skipped in it that would require a load.

The gv is magicalized at compile-time, to prevent it under minitest we'd have to move the relevant tests to a new file or put them in a string eval, both of which is ugly.

**Comment by jkeenan** [comment]
TonyC wrote:

> My commit made access to `*{^CAPTURE}` and `*{^CAPTURE_ALL}` load `Tie::Hash::NamedCapture` unconditionally due to `gv_magicalize()` only being called once for each GV with a name longer than one character, which is why the use of @{^CAPTURE} in this code is trying (and failing) to load it.
> 
> I can see a few solutions, which are either non-trivial or could reduce performance:
> 
>     * call gv_magicalize() every time and revert the gv.c changes - this would add a performance penalty to every gv access.
> 
>     * add a gvmini.o, like we have opmini.o and #ifdef out the Tie::Hash::NamedCapture load for miniperl - I'm not fond of the *mini.o hack
> 
>     * move the implementation of `%{^CAPTURE}` and `%{^CAPTURE_ALL}` (and `%+`, `%-`) into the core binary - this would be largely be moving the tie code into universal.c
> 
> 
> I'm most inclined to go for the last.

The last sounds good to me, too.

**Comment by jkeenan** [comment]
khw wrote:
> I think that merely skipping this test under minitest is the way to go. Unless this has uncovered a performance issue. minitest is known to be crippled, and many tests are skipped in it that would require a load.

As I wrote previously, I made several attempts to skip this test (or, at least, the tests within the file that pertain to `@{$^CAPTURE}` under `make minitest` but was unsuccessful.  If you can figure out how to do so, please do.

Thanks.
jimk

**Comment by hvds** [comment]
> @hvds I'm proposing that we schedule regular smokes of minitest in order to catch breaking changes like this. Can you offer insights into the importance of this?

I think it would be valuable to do so, but the value is limited: it's handy for it to work when you want it, but if the full test suite is not failing it's likely only telling you something about the testsuite rather than about perl - in most cases one could just as usefully discover and fix that at the point one tries to use it.

As for the fix: I agree that string eval is probably the way to go.

Hugo
