### ISSUE TITLE
[doc] Syntax error on Math::Complex man page

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#17308]
Version: 5.30.0-9
File: /usr/share/man/man3/Math::Complex.3perl.gz

               $j = ((root(1, 3))[1];

is a syntax error.

**Comment by Grinnz** [comment]
This module is maintained on CPAN, the bugtracker for it is https://rt.cpan.org/Public/Dist/Display.html?Name=Math-Complex.

**Comment by jidanni** [comment]
OK. Made https://rt.cpan.org/Ticket/Display.html?id=131037 .
