### ISSUE TITLE
git blame doesn't work on large files (sv.c)

### ISSUE THREAD

**Issue by toddr** [Perl/perl5#17310]
@craigberry stated:

My current pet peeve is that there is no replacement for the  "git blame" interface of standard gitweb.  Try to do any blame view in GitHub on any file more than a few hundred lines long and you'll get a great big angry unicorn icon and a message that says, "This page is taking way too long to load. Sorry about that. Please try refreshing and contact us if the problem persists."  I don't know what metrics they are using exactly, but whether it's number of lines in the file or number of commits on the file, it gives up way too easily and hangs up on you in a fraction of a second.  There seems to have been an explicit decision made that making a version control system show versions is too expensive and one shouldn't ask for it.

I know we had no choice, really, and that BitBucket or GitLab or SourceForge or whatever would have had various different and possibly worse problems. But not being able to do archive diving for a long-running project with large source files is a major defect in GitHub, and is something that standard gitweb does quite handily out of the box.  I spent an hour a week or two ago trying to teach myself how to do git blame with line ranges from the command line and it didn't go well.  Is there any chance we could get https://perl5.git.perl.org/perl.git to be a reasonably up-to-date

**Comment by toddr** [comment]
@craigberry, From what I can tell blame is available? https://github.com/Perl/perl5/blame/blead/caretx.c

When viewing a file via this link, I can see  https://github.com/Perl/perl5/blob/blead/caretx.c

<img width="602" alt="Screen Shot 2019-11-18 at 10 55 07 AM" src="https://user-images.githubusercontent.com/97892/69072918-03e07a00-09f2-11ea-9a44-1b8524a005e8.png">

**Comment by xenu** [comment]
"Blame" button is always there, but when you try using it on e.g. `sv.c`, it gives an error.

**Comment by toddr** [comment]
OK. I see blame doesn't work on larger files.

Example: https://github.com/Perl/perl5/blame/blead/sv.c

**Comment by demerphq** [comment]
On Mon, 18 Nov 2019 at 18:23, Todd Rinaldo <notifications@github.com> wrote:
>
> OK. I see blame doesn't work on larger files.
>
> Example: https://github.com/Perl/perl5/blame/blead/sv.c

Blame is an extremely heavy operation in git, I can understand why
github wouldnt want to expose it as an endpoint. I think you need to
just learn to use git blame properly. Tip, -L can take a line number
and length, eg, -L1234,+23 will show the 23 lines starting with line
1234.

IMO what we could do is set up a little browser thingee that allows
you to use our old gitweb blame locally via a browser.

Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by khwilliamson** [comment]
On 11/18/19 11:39 AM, Yves Orton wrote:
> On Mon, 18 Nov 2019 at 18:23, Todd Rinaldo <notifications@github.com> wrote:
>  >
>  > OK. I see blame doesn't work on larger files.
>  >
>  > Example: https://github.com/Perl/perl5/blame/blead/sv.c
> 
> Blame is an extremely heavy operation in git, I can understand why
> github wouldnt want to expose it as an endpoint. I think you need to
> just learn to use git blame properly. Tip, -L can take a line number
> and length, eg, -L1234,+23 will show the 23 lines starting with line
> 1234.
> 
> IMO what we could do is set up a little browser thingee that allows
> you to use our old gitweb blame locally via a browser.
> 
> Yves
> 
> -- 


If you clone the repository onto your local machine that has git, you 
can do blame from there.  That's what I do, but I haven't tried backing 
up over changes to find the original thing I'm looking for, which I used 
to do solely on the web interface.

**Comment by toddr** [comment]
FYI I'm planning on moving the backup mirror in which case a RO mirror will again be available by the original interface.

**Comment by demerphq** [comment]
>
> If you clone the repository onto your local machine that has git, you
> can do blame from there. That's what I do, but I haven't tried backing
> up over changes to find the original thing I'm looking for, which I used
> to do solely on the web interface.
>

I do it fairly often. The trick is to use the caret operator and use the
-LX,+n form.

So for instance you blame a file in your working dir to find the source
line:

git blame foo.txt

from that you get a hash (deadbeef) and a line number (123). your next step
is to do

git blame deadbeef^ -L115,+20 foo.txt

that is likely to show you the same line in the previous commit as part of
the 20 lines it shows, if it doesnt you just git blame deadbeef^.

The caret means "parent of the hash" (probably there is a more specific
explanation, i think it chooses a specific side of a merge).

You then repeat this process as many times as you like following the change
through its history. IMO its about as easy, or easier than the gitweb
approach. Certainly it can be faster as the +n form is relatively efficient
versus blaming the whole file.

Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by demerphq** [comment]
On Mon, 18 Nov 2019 at 20:01, demerphq <demerphq@gmail.com> wrote:
>>
>> If you clone the repository onto your local machine that has git, you
>> can do blame from there. That's what I do, but I haven't tried backing
>> up over changes to find the original thing I'm looking for, which I used
>> to do solely on the web interface.
>
>
> I do it fairly often. The trick is to use the caret operator and use the -LX,+n form.
>
> So for instance you blame a file in your working dir to find the source line:
>
> git blame foo.txt
>
> from that you get a hash (deadbeef) and a line number (123). your next step is to do
>
> git blame deadbeef^ -L115,+20 foo.txt

BTW the discrepancy between 123 and 115 is deliberate.  I find that a
good rule of thumb is move the line BACK a modest number of lines, and
then use a +n that will go forward to AFTER the line by the same
window. Eg, go back 10 lines but show the 20 lines following that
point. Generally you will find the line you are looking in that
window. Obviously after a serious code restructure you wont...

>
> that is likely to show you the same line in the previous commit as part of the 20 lines it shows, if it doesnt you just git blame deadbeef^.
>
> The caret means "parent of the hash" (probably there is a more specific explanation, i think it chooses a specific side of a merge).
>
> You then repeat this process as many times as you like following the change through its history. IMO its about as easy, or easier than the gitweb approach. Certainly it can be faster as the +n form is relatively efficient versus blaming the whole file.
>
> Yves
>
> --
> perl -Mre=debug -e "/just|another|perl|hacker/"



-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by toddr** [comment]
Looks like this takes 30 seconds to run but you should be able to use https://perl5.git.perl.org/perl5.git/blame/HEAD:/sv.c now.
