### ISSUE TITLE
[doc]  grep.cpan.me is down

### ISSUE THREAD

**Issue by khwilliamson** [Perl/perl5#17336]
This appears to be a casualty of the migration. @dgl can no longer access it.  This is important to have, as the metacpan grep is insufficient. @toddr @xsawyerx

**Comment by dgl** [comment]
I've brought it back, hosted elsewhere for now (give ~1hr for DNS TTL to expire).

(Funny how times change, originally this needed basically its own dedicated server, now it fits in the spare space on my development machine. I'm not sure how long term I can guarantee that but I can probably find something if our previous generous hosting offer is no more...)

**Comment by dgl** [comment]
n.b.: Not yet on SSL, so make sure to access http://grep.cpan.me, your browser may remember it was https before.

**Comment by jkeenan** [comment]
http://grep.cpan.me/ is now available, so I am closing this issue.
