### ISSUE TITLE
IVdf or IV_MAX macros are broken on 32bit Perl in blead branch

### ISSUE THREAD

**Issue by pali** [Perl/perl5#17338]
Compiling 32bit version of Perl on Linux from blead branch generates this warning:

```
RealPPPort.xs:1006:27: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘int’ [-Wformat=]
         RETVAL = newSVpvf("%" IVdf, IV_MAX);
                           ^
```

It seems that macros `IVdf` or `IV_MAX` are defined incorrectly. And I guess this can cause problems.

CC @atoomic 

I do not think that this is relevant to Devel::PPPort, but to core perl itself.

Compilation of 32bit perl is done by these commands:
```
./Configure -de -Dusedevel -Dcc='gcc -m32' -Dlibs='-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc'
make
```

`-m32` option cause that gcc generates 32bit code even on 64bit platform.

Relevant part of logs is there:
```
"../../miniperl" "-I../../lib" "../../lib/ExtUtils/xsubpp" -noprototypes -typemap '/home/pali/perl/perlblead32/dist/Devel-PPPort/../../lib/ExtUtils/typemap' -typemap '/home/pali/perl/perlblead32/dist/Devel-PPPort/typemap'  RealPPPort.xs > RealPPPort.xsc
mv RealPPPort.xsc RealPPPort.c
gcc -m32 -c   -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -Wall -Werror=declaration-after-statement -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings -O2   -DVERSION=\"3.56\" -DXS_VERSION=\"3.56\" -fPIC "-I../.."  -W -Wall -Wdeclaration-after-statement RealPPPort.c
RealPPPort.xs: In function ‘XS_Devel__PPPort_sprintf_ivmax’:
RealPPPort.xs:1006:27: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘int’ [-Wformat=]
         RETVAL = newSVpvf("%" IVdf, IV_MAX);
                           ^
RealPPPort.xs: In function ‘XS_Devel__PPPort_sprintf_uvmax’:
RealPPPort.xs:1013:27: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 2 has type ‘unsigned int’ [-Wformat=]
         RETVAL = newSVpvf("%" UVuf, UV_MAX);
```

**Comment by khwilliamson** [comment]
This looks to be some issue with Configure probes with -m32.  I doubt that it is a problem on real 32-bit boxes.  It might just be that Configure doesn't use -m32 when compiling its test programs.
@Tux does that sound plausible?

**Comment by pali** [comment]
> This looks to be some issue with Configure probes with -m32.

I do not think so. I set `-Dcc` to `gcc -m32`, so I must use it. Otherwise which compiler Configure use if not one set in `-Dcc`?

Also I looked at Configure output and it used 'gcc -m32'.

**Comment by pali** [comment]
This is for sure problem in Perl source, not in Configure. See output for blead branch:
```
$ git grep '#\s*define\s\s*IVdf\s'
NetWare/config_H.wc:#define	IVdf		"ld"		/**/
Porting/config_H:#define	IVdf		"ld"		/**/
config_h.SH:#define	IVdf		$ivdformat		/**/
cpan/Win32API-File/const2perl.h:#  define IVdf "ld"
dist/Devel-PPPort/parts/inc/format:#    define     IVdf      "ld"
dist/Devel-PPPort/parts/inc/format:#    define   IVdf      "d"
plan9/config.plan9:#define	IVdf		"ld"		/**/
plan9/config_h.sample:#define	IVdf		"ld"		/**/
uconfig.h:#define	IVdf		"ld"		/**/
win32/GNUmakefile:	@(echo #define IVdf "I64d"&& \
win32/GNUmakefile:	echo #define IVdf "ld"&& \
win32/Makefile:	echo #define IVdf "I64d"&& \
win32/Makefile:	echo #define IVdf "ld"&& \
win32/config_H.gc:#define	IVdf		"ld"		/**/
win32/config_H.vc:#define	IVdf		"ld"		/**/
win32/makefile.mk:	@(echo #define IVdf "I64d"&& \
win32/makefile.mk:	echo #define IVdf "ld"&& \
```
```
$ git grep '#\s*define\s\s*IV_MAX\s'
perl.h:#    define IV_MAX INT64_MAX
perl.h:#    define IV_MAX PERL_QUAD_MAX
perl.h:#    define IV_MAX INT32_MAX
perl.h:#    define IV_MAX PERL_LONG_MAX
```

Lot of times `IVdf` is defined to `"ld"` format means `long int`, but `IV_MAX` is defined also as `INT32_MAX`, which is of type `uint32_t`.

So you had to either use `PRId32` format when `uint32_t` is used. Or `long int` type when `ld` format is used.

**Comment by tonycoz** [comment]
This occurs with a 32-bit built on a 32-bit operating system too, and appears to have been an issue since support for `inttypes.h` was added in 1999.

The older definitions include a cast of the values, so IV_MAX became `((long)LONG_MAX)` which has the correct type for `%ld`.

So the fix is likely to add casts to each of these.
