### ISSUE TITLE
False warning that character is ignored

### ISSUE THREAD

**Issue by khwilliamson** [Perl/perl5#17340]
The string "\xAG" will raise the warning that the 'G' is ignored.  This is a lie.  What happens is that the string becomes "\x0AG"  Similarly in a pattern.  The G is definitely not ignored, but it terminates finding the \x translation early.

I propose to change this false message to something like 
"Non-hex character 'G' terminates \x early.  Resolved as \x0AG"

I searched CPAN and did not find any module that appeared to be dependent on the existing warning text.

If the non-hex isn't a printable, I would omit printing it in the warning.

**Comment by xsawyerx** [comment]
I'm in favor of changing this warning. However, taking the ignorant perspective on this one, this error message tells me nothing. I don't understand what is wrong, nor how to fix it.

Maybe "Incorrect hex code '\xAG' translated to '\x0AG'" as explaining *what* is wrong. Thoughts?

**Comment by khwilliamson** [comment]
I used similar text to what you suggest, but using wording similar to some other already-existing messages.  This would be in the above case

    Non-hex character 'G' terminates \x early.  Resolved as "\x0AG"
