### ISSUE TITLE
APItest.xs:1087:16: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘line_t {aka long unsigned int}’

### ISSUE THREAD

**Issue by pali** [Perl/perl5#17347]
Compiling 32bit Perl from current git blead branch cause following compile warning:
```
gcc -m32 -c   -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -Wno-deprecated-declarations -Wall -Werror=declaration-after-statement -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings -O2   -DVERSION=\"1.04\" -DXS_VERSION=\"1.04\" -fPIC "-I../.."   APItest.c
In file included from ../../perl.h:5543:0,
                 from APItest.xs:10:
APItest.xs: In function ‘THX_parse_keyword_subsignature’:
APItest.xs:1087:16: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘line_t {aka long unsigned int}’ [-Wformat=]
       newSVpvf("nextstate:%d", cCOPx(kid)->cop_line)));
                ^
../../embed.h:400:61: note: in definition of macro ‘op_append_list’
 #define op_append_list(a,b,c) Perl_op_append_list(aTHX_ a,b,c)
                                                             ^
APItest.xs:1085:42: note: in expansion of macro ‘newSVOP’
   retop = op_append_list(OP_LIST, retop, newSVOP(OP_CONST, 0,
                                          ^
```
Specifying incorrect type in variadic printf-like function may cause undefined behavior.
Type `line_t` is defined as `typedef U32 line_t;` in handy.h

**Comment by jkeenan** [comment]
On 12/5/19 6:35 AM, pali wrote:
> Compiling 32bit Perl from current git blead branch cause following 
> compile warning:
> 
> |gcc -m32 -c -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong 
> -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 
> -D_FORTIFY_SOURCE=2 -Wno-deprecated-declarations -Wall 
> -Werror=declaration-after-statement -Werror=pointer-arith -Wextra 
> -Wc++-compat -Wwrite-strings -O2 -DVERSION=\"1.04\" 
> -DXS_VERSION=\"1.04\" -fPIC "-I../.." APItest.c In file included from 
> ../../perl.h:5543:0, from APItest.xs:10: APItest.xs: In function 
> ‘THX_parse_keyword_subsignature’: APItest.xs:1087:16: warning: format 
> ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘line_t 
> {aka long unsigned int}’ [-Wformat=] newSVpvf("nextstate:%d", 
> cCOPx(kid)->cop_line))); ^ ../../embed.h:400:61: note: in definition of 
> macro ‘op_append_list’ #define op_append_list(a,b,c) 
> Perl_op_append_list(aTHX_ a,b,c) ^ APItest.xs:1085:42: note: in 
> expansion of macro ‘newSVOP’ retop = op_append_list(OP_LIST, retop, 
> newSVOP(OP_CONST, 0, ^ |
> 
> Specifying incorrect type in variadic printf-like function may cause 
> undefined behavior.
> Type |line_t| is defined as |typedef U32 line_t;| in handy.h
> 
Can you provide the exact invocation of ./Configure that you used in 
this attempt?

Also, basic information about the operating system?

Thank you very much.
Jim Keenan

**Comment by pali** [comment]
> Can you provide the exact invocation of ./Configure that you used in
this attempt?
```
./Configure -de -Dusedevel -Dcc='gcc -m32' -Dlibs='-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc'
```

> Also, basic information about the operating system?

Debian 9.11

**Comment by jkeenan** [comment]
> `./Configure -de -Dusedevel -Dcc='gcc -m32' -Dlibs='-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc'`

I am attempting to reproduce your report.  When I configure with:
```
./Configure -de -Dusedevel -Dcc='gcc -m32' -Dlibs='-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc'
```
on this platform:
```
$ uname -mrs
Linux 4.15.0-70-generic x86_64
$ gcc --version | head -1
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
```
... `Configure` quickly bombs out:
```
Good, your tr supports [:lower:] and [:upper:] to convert case.
Using [:upper:] and [:lower:] to convert case.
/usr/bin/ld: cannot find Scrt1.o: No such file or directory
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
collect2: error: ld returned 1 exit status
You need to find a working C compiler.
Either (purchase and) install the C compiler supplied by your OS vendor,
or for a free C compiler try http://gcc.gnu.org/
I cannot continue any further, aborting.
```
What am I missing?

Thank you very much.
Jim Keenan

**Comment by pali** [comment]
Ok, you have Ubuntu. Try installing gcc-multilib and libc6-dev:i386 packages:
```
sudo apt-get install gcc-multilib libc6-dev:i386
```

**Comment by jkeenan** [comment]
With **many** hours of work I was eventually able to reproduce this warning.

```
Writing Makefile for XS::APItest
make[1]: Entering directory '/tmp/gitwork/perl/ext/XS-APItest'
Running Mkbootstrap for APItest ()
Writing APItest.bs
chmod 644 "APItest.bs"
/tmp/gitwork/perl/ext/XS-APItest/../../miniperl "-I../../lib" -MExtUtils::Command::MM -e 'cp_nonempty' -- APItest.bs ../../lib/auto/XS/APItest/APItest.bs 644
"../../miniperl" "-I../../lib" "../../lib/ExtUtils/xsubpp"  -typemap '/tmp/gitwork/perl/ext/XS-APItest/../../lib/ExtUtils/typemap' -typemap '/tmp/gitwork/perl/ext/XS-APItest/typemap'  APItest.xs > APItest.xsc
mv APItest.xsc APItest.c
gcc-8 -m32 -c   -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wno-deprecated-declarations -Wall -Werror=declaration-after-statement -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings -O2   -DVERSION=\"1.02\" -DXS_VERSION=\"1.02\" -fPIC "-I../.."   APItest.c
In file included from ../../perl.h:5395,
                 from APItest.xs:10:
APItest.xs: In function ‘THX_parse_keyword_subsignature’:
APItest.xs:1080:16: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘line_t’ {aka ‘long unsigned int’} [-Wformat=]
       newSVpvf("nextstate:%d", cCOPx(kid)->cop_line)));
                ^~~~~~~~~~~~~~
../../embed.h:563:61: note: in definition of macro ‘op_append_list’
 #define op_append_list(a,b,c) Perl_op_append_list(aTHX_ a,b,c)
                                                             ^
APItest.xs:1078:42: note: in expansion of macro ‘newSVOP’
   retop = op_append_list(OP_LIST, retop, newSVOP(OP_CONST, 0,
                                          ^~~~~~~

```

Some initial remarks ...

The longer and more complex your invocation of `Configure` is, the greater the likelihood that you will get build-time warnings that you would not get with a simpler invocation.

The complaint in this case was that a particular warning was being generated with this invocation:

```
./Configure -des -Dusedevel -Dcc='gcc-8 -m32' \
    -Dlibs='-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc'
```

When I saw those seven linked libraries (not to mention `-m32`), I knew this was going to be difficult.  Was the addition of one of those seven libraries what triggered the warning?  If so, which one?  Or, more likely, which combination of ones?

And to what extent was this triggered by a change in blead?  The original poster did not explicitly assert that this was a regression, but that possibility had to be investigated.  (Indeed, it does not occur with perl-5.30.0.)  And, to the best of my knowledge, `Porting/bisect.pl` cannot answer the question, "When did this particular warning first appear?"

While I had previously installed gcc-8 on both my Linux and FreeBSD machines, I had to install gcc-multilib and  libc6-dev:i386 on Linux and gcc8-devel on FreeBSD to have any success in getting `Configure` and `make` to run to completion.

Once I had done that, I tried to configure and build.  I took the approach of adding just one library at a time to the `-Dlibs` switch to see (a) whether `Configure` would complete; (b) whether `make` would complete; and finally (c) whether would the warning in question be generated in the course of a satisfactory `make`.

After several dozen attempts, I finally got `Configure` and `make` to complete with this invocation:
```
./Configure -des -Dusedevel -Dcc='gcc-8 -m32' -Dlibs='-lpthread -lm -lcrypt'
```
... but without generating the warning.  So I inferred that the warning was being triggered by the interaction of one or more of the remaining three libraries in the OP's invocation.

At this point, however, I had had enough and decided to take a different approach.  In 2016 I developed a CPAN distribution, [Devel-Git-MultiBisect](https://metacpan.org/release/Devel-Git-MultiBisect), for the purpose of diagnosing errors in the Perl 5 test suite when run on FreeBSD.  At the time we completely lacked smoke test reports on that operating system and so had to deal with the possibility that a given test file and failed in different ways over many months of commits to the core.  In 2018 I extended that distro's functionality to compile-time errors.  Now, I decided to extend the functionality to compile-time warnings.

Version 0.13 has been released to CPAN and is what I used to identify the commit in blead which triggered the warning.  Multiple bisectioning points to:
```
commit 996b0cb8b8b219f477902fa7cadd7d6d10f5d079
Author:     Paul "LeoNerd" Evans <leonerd@leonerd.org.uk>
AuthorDate: Thu Jul 11 18:34:28 2019 +0100
Commit:     Dagfinn Ilmari Mannsåker <ilmari@ilmari.org>
CommitDate: Mon Jul 22 11:18:26 2019 +0100

    [perl #132474] Add function for parsing sub signatures
    
    This exposes a GRAMSUBSIGNATURE top-level production from perly.y for
    toke.c to consume, which parses a subroutine signature, inside the
    parens.
    
    This needed a small change to the existing rules, to pull out a rule
    that handles all of the insides of the parens but not the parens
    themselves.
    
    (h/t to ilmari for the suggestion)
```
(Should anyone want to reproduce this result, see https://st.aticpan.org/source/JKEENAN/Devel-Git-MultiBisect-0.13/xt/104-gcc-build-transitions-warnings.t.)

@leonerd, @ilmari, any thoughts as to why this commit, given the configuration, might have triggered this warning?

@pali, can you try to determine the combination of linked libraries needed to trigger this warning?

Now, given that this warning (a) only began to appear with gcc-8, (b) only appears with the `-m32` compiler switch; and (c) only appears with some as-yet-unknown combination of 7 linked libraries, silencing this warning is not exactly a high priority.  But if we *can* find out the cause of the warning here it may enable us to write code more initially free of warnings in the future.

Thank you very much.
Jim Keenan

**Comment by pali** [comment]
To automatize building of 32bit Perl I extended .travis.yml to test also 32bit Perl versions. See PR: https://github.com/Perl/perl5/pull/17348

To build 32bit Perl on Ubuntu you just need to install packages:
```
sudo apt-get install -yq --no-install-suggests --no-install-recommends libdb-dev:i386 libgdbm-dev:i386 zlib1g-dev:i386 libbz2-dev:i386 libc6-dev:i386 gcc-multilib
```

And then run simple:
```
./Configure -des -Dusedevel -Dcc='gcc -m32'
```
without any need to specify libraries.

**Comment by pali** [comment]
> @pali, can you try to determine the combination of linked libraries needed to trigger this warning?

This compile warning has nothing with linked libraries. Libraries are linked **after** that warning is generated.

Problem seems to be more relevant to gcc version. I used version `gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)` which is default in Debian 9.11.

> But if we can find out the cause of the warning

Root cause of problem is really simple. Just look at problematic line:
```c
newSVpvf("nextstate:%d", cCOPx(kid)->cop_line)));
```
Modifier `"%d"` expects type `int`. And argument `cop_line` is of type `line_t`, which is incorrect.

So you either need to cast `cop_line` to `int` (beware of loosing precision) or changing `"%d"` modifier to some `"%"line_t` modifier.

Why this warning is not triggered on 64bit build? Because above problem is hidden on 64bit platform. `line_t` type is on 64bit platform defined as `U32` which is on 64bit platform defined as `unsigned int`. So in final result `%d` is somehow compatible with `unsigned int`.

And on 32bit build it is defined as `unsigned long int` which is incompatible with `%d` type. So warning appear.

**Comment by jkeenan** [comment]
> > @pali, can you try to determine the combination of linked libraries needed to trigger this warning?
> 
> This compile warning has nothing with linked libraries. Libraries are linked **after** that warning is generated.
> 
> Problem seems to be more relevant to gcc version. I used version `gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)` which is default in Debian 9.11.
> 
> > But if we can find out the cause of the warning
> 
> Root cause of problem is really simple. Just look at problematic line:
> 
> ```c
> newSVpvf("nextstate:%d", cCOPx(kid)->cop_line)));
> ```
> 
> Modifier `"%d"` expects type `int`. And argument `cop_line` is of type `line_t`, which is incorrect.
> 
> So you either need to cast `cop_line` to `int` (beware of loosing precision) or changing `"%d"` modifier to some `"%"line_t` modifier.
> 
> Why this warning is not triggered on 64bit build? Because above problem is hidden on 64bit platform. `line_t` type is on 64bit platform defined as `U32` which is on 64bit platform defined as `unsigned int`. So in final result `%d` is somehow compatible with `unsigned int`.
> 
> And on 32bit build it is defined as `unsigned long int` which is incompatible with `%d` type. So warning appear.

Okay, so can you propose a patch to APItest.xs which would quiet the warning in your particular case without doing harm to the 64-bit builds?

Thank you very much.
Jim Keenan

**Comment by pali** [comment]
> Okay, so can you propose a patch to APItest.xs which would quiet the warning in your particular case without doing harm to the 64-bit builds?

Do we have printf format modifier for `U32` Perl type? This is probably the right way to use in `newSVpvf` for `cop_line`.

**Comment by khwilliamson** [comment]
We do not have such a modifier AFAIK.  But why not cast it to a UV, then use UVdf?

**Comment by pali** [comment]
Maybe casting to `unsigned int` and using `%u`? Is perl expecting that `unsigned int` is at least 32bit? (C standard allows that `int` can be also only 16bit).

**Comment by demerphq** [comment]
Or use %j and cast appropriately.

Yves

**Comment by pali** [comment]
I used `unsigned int` as it should be enough. PR is here: https://github.com/Perl/perl5/issues/17347
