### ISSUE TITLE
Perl 5.30 64 bit XS.c loadable library and perl binaries are mismatched

### ISSUE THREAD

**Issue by walter-borchia** [Perl/perl5#17352]
Hi,
my name is Walter Borchia and I am Italian.
I am trying to interface perl and Tesseract-OCR .

the response to perl -v is
This is perl 5, version 30, subversion 1 (v5.30.1) built for MSWin32-x64-multi-thread
Copyright 1987-2019, Larry Wall
 the OS is Windows 10 Professional.
-----------------------------------------------

with the same perl and msys2 MINGW64 subsystem I wrote an interface to Leptonica that has no problems. 
I tried to install Image::Leptonica but I got errors till I decided to write a new XSUB.

I used MSYS2 MINGW64 to install Tesseract-OCR alpha 5.0  and the last Leptonica (1.78) (no problems)
Leptonica was installed via pacman Tesseract was compiled

Writing an XSUB for Tesseract-OCR I got the error

Tesseract.c: loadable library and perl binaries are mismatched (got handshake key 0000000010500080, needed 0000000010a00080)

The xs file is Tesseract.xs

Looking at the generated code Tesseract.c and searching in the perl code I got the statements

XS_EXTERNAL(boot_XXXXXX_Tesseract)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif

the error occurs in the expansion of the macro dXSBOOTARGSXSAPIVERCHK

so I changed #if PERL_VERSION_LE(5, 21, 5) to #if PERL_VERSION_LE(5, 71, 5)

and It works very nicely till now !!

I didn't try to follow the code to get the why of the error.

I hope this may be useful. 

thank you in advance
best regards

**Comment by jkeenan** [comment]
> Hi,
> my name is Walter Borchia and I am Italian.
> I am trying to interface perl and Tesseract-OCR .
> ## the response to perl -v is
> This is perl 5, version 30, subversion 1 (v5.30.1) built for MSWin32-x64-multi-thread
> Copyright 1987-2019, Larry Wall
> the OS is Windows 10 Professional.
> 
> with the same perl and msys2 MINGW64 subsystem I wrote an interface to Leptonica that has no problems.
> I tried to install Image::Leptonica but I got errors till I decided to write a new XSUB.
> 
> I used MSYS2 MINGW64 to install Tesseract-OCR alpha 5.0 and the last Leptonica (1.78) (no problems)
> Leptonica was installed via pacman Tesseract was compiled
> 
> Writing an XSUB for Tesseract-OCR I got the error
> 
> Tesseract.c: loadable library and perl binaries are mismatched (got handshake key 0000000010500080, needed 0000000010a00080)
> 
> The xs file is Tesseract.xs
> 
> Looking at the generated code Tesseract.c and searching in the perl code I got the statements
> 
> XS_EXTERNAL(boot_XXXXXX_Tesseract)
> {
> #if PERL_VERSION_LE(5, 21, 5)
> dVAR; dXSARGS;
> #else
> dVAR; dXSBOOTARGSXSAPIVERCHK;
> #endif
> 
> the error occurs in the expansion of the macro dXSBOOTARGSXSAPIVERCHK
> 
> so I changed #if PERL_VERSION_LE(5, 21, 5) to #if PERL_VERSION_LE(5, 71, 5)
> 
> and It works very nicely till now !!
> 
> I didn't try to follow the code to get the why of the error.
> 
> I hope this may be useful.
> 
> thank you in advance
> best regards

First of all, let's try to clarify your problem?

Are you having problems with respect to **both** Leptonica and Tesseract?

Are you aware of CPAN distributions [Image-Leptonica](https://metacpan.org/pod/Image::Leptonica) and [Image-OCR-Tesseract](https://metacpan.org/release/Image-OCR-Tesseract)?  Do they not meet your needs?

Thank you very much.
Jim Keenan

**Comment by walter-borchia** [comment]
I wrote an interface with Leptonica beacause I was not able to install Image::Leptonica. In linux too.
Image-OCR-Tesseract is only a wrapper around the line command.
The Leptonica library is a wonderful piece of software (very well written and very fast).
I want to go deep in image and OCR operations. How they works and why.
Tesseract is deeply intertwined with Leptonica. So I am trying to understand deeply the process.
I use Windows and Windows is not fully compatible with POSIX/Unix/Linux.

The best results I got are with MSYS2 MINGW64 and Strawberry Perl 64 bits.

Leptonica works, on my system, also in 32bits. Tesseract NOT.  I am now able to interface deeply with
Leptonica. and to Tesseract baseapi interface. I am trying now to go down in Tesseract.

When I got the reported problem I was a little desperate. so I looked to the Perl sources and I found a point referring to the XSUB BOOT part.  So I tried the reported bypass. and it works.
Then I discovered the same problem reported by someone working on an XSUB for PostgreSql.

I read something about the why of the check and I don't think to be able to understand the why of the problem in a reasonable time period.

For now I am happy because it works and I can go on.

PS:  (just sentiments from a perl user)
I tried the FFI interface but I got errors. It seems to me fragile.
The build (not the makefile) is a nightmare for me.  Difficult to debug.
The Alien too is, imho, fragile. I prefer to install required software by myself.
The MSYS/MINGW were wonderful in 32 bits MSYS2 now works well in 64.

**Comment by walter-borchia** [comment]
thank you all

I posted a comment to the problem thread. I am not always online so I din't note the email.

I never posted a bug before.

I like perl a lot.

best regards

walter borchia

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by walter-borchia** [comment]
I don't need a solution because I have a bypass

thank you
