### ISSUE TITLE
(?*...) and (?<*...) should be reserved until non-atomic lookarounds are implemented

### ISSUE THREAD

**Issue by Davidebyzero** [Perl/perl5#17363]
**Where**
https://perldoc.perl.org/perlreref.html under **EXTENDED CONSTRUCTS**

**Description**

* `(*pla:...)`, the synonym for `(?=...)`, is incorrectly shown as `(?*pla:...)`
* `(*nla:...)`, the synonym for `(?!...)`, is incorrectly shown as `(?*nla:...)`
* `(*plb:...)`, the synonym for `(?<=...)`, is incorrectly shown as `(?*plb:...)`
* `(*nlb:...)`, the synonym for `(?<!...)`, is incorrectly shown as `(?*nlb:...)`
* `(*atomic:...)`, the synonym for `(?>...)`, is incorrectly shown as `(?*atomic:...)`

When testing these in Perl v5.30.1, the versions without `?` are the only ones that work. Any attempt to use ones with `?` results in the error `Sequence (?*...) not recognized in regex; marked by <-- HERE in `...

In https://perldoc.perl.org/perlre.html these are already documented correctly.

---

Now, for a proposal: `(?*...)` is currently not mapped to anything in any regex engine [except for mine](https://github.com/Davidebyzero/RegexMathEngine/blob/master/parser.cpp#L408), in which it is **non-atomic** lookahead (a.k.a. [molecular lookahead](https://github.com/Davidebyzero/RegexMathEngine/commit/db4e4a266d55ec66663ccaa17de944508ace4067)). I believe this mapping makes a great deal of sense, and is the best meaning `(?*...)` and `(?<*...)` could have (lookahead and lookbehind, respectively). My rationale:

* The `*` shows that it tries all possibilities when backtracked into, rather than sticking with the first one it finds and being skipped over by backtracking, like regular atomic positive lookarounds do.
* If non-atomic negative lookarounds were needed, that might be an argument for using a symbol that contains `=` for the positive version (for symmetry). But there is no need for negative non-atomic lookarounds, because a negative lookaround that results in a match outside will always have already tried all possibilities the first time it was hit; when backtracking into it, there would be no possibilities left to try, anyway. (As far as PCRE is concerned, a second reason could be given: molecular lookaround is only useful when capture(s) are made inside, and no captures made inside a negative lookaround should survive outside of it. But I realize that in Perl, once a negative lookaround is exited after failing to find any match, thus matching outside, captures made inside of it will contain the last thing they did when it made its last failed match inside.)
* The one case in which a negative non-atomic lookaround might make sense is for lookaround conditionals, because in Perl and PCRE2, a negative lookaround conditional that matches inside (thus failing to match outside) will give its captures from that match to the conditional's negative alternative. However, anything that a negative lookaround conditional can do, a positive one can also do, just by swapping the two alternatives. So the argument holds, that negative non-atomic lookaround is not needed. It's not worth putting one extra character in the symbol for non-atomic positive lookaround just so there can be a symmetric negative non-atomic lookaround conditional.

`(?*...)` and `(?<*...)` have no meaning in any other engine, and are ripe for the taking. And somebody has to take the initiative, otherwise this opportunity for intuitive and useful symbol mapping will just go unused (or worse, used for something less useful).

So, I would argue that in Perl, `(?*...)` and `(?<*...)` should be reserved until non-atomic lookarounds are implemented, and then mapped to those functions when they are.

**Comment by khwilliamson** [comment]
The typos have been fixed.  I'm renaming this to the remaining issue of reserving some constructs.

**Comment by Davidebyzero** [comment]
Thank you very much.

**Comment by khwilliamson** [comment]
See the commit message for the patch listed.

**Comment by Davidebyzero** [comment]
Thank you very much, Karl!
