### ISSUE TITLE
POSIX:: wcstombs and mbstowcs are broken:  Suggest dropping them

### ISSUE THREAD

**Issue by khwilliamson** [Perl/perl5#17388]
Module: POSIX

**Description**

In working on wctomb and mbtowc, I realized that the s versions can't possibly work.

Further, they deal in strings of wide chars, for which there is no good Perl equivalent.  The closest I can think of in Perl space is an array containing numeric code points.

The few uses of them in CPAN are in C language files.

I don't believe they ever could have worked.  Besides not having a suitable data type, even if we could coerce them into scalars, the existing code would segfault unless those scalars were preallocated to have enough space in them.  The C library functions have a mode to calculate the needed space, but the typemap for these functions doesn't allow the particular input required to trigger that mdoe; and even if that is fixed, say by pre-allocating lots of space in a scalar, there is no provision for handling COW, which the inputs could be.
 
Rather than trying to get these to (awkwardly) work, I think we should remove them from the list of supported functions.

**Comment by dur-randir** [comment]
>but the typemap for these functions doesn't allow the particular input required to trigger that mdoe

Typemap can be updated to account for this, but if nobody cared in 25 years, I don't think there's much point in continuing their existence.

**Comment by tonycoz** [comment]
I think these functions are mostly covered by Encode, the only limitation being that Encode won't detect the current locale for you and work with the mbcs/wcs for that locale.

I do think they could be made to work (as we discussed in IRC), but it probably isn't worth the bother.
