### ISSUE TITLE
assertion failure in utf8_to_uvchr_buf_helper with DEBUGGING build on VMS

### ISSUE THREAD

**Issue by craigberry** [Perl/perl5#17406]
Module:

static function in inline.h via Devel::PPPort

**Description**

assertion failure in utf8_to_uvchr_buf_helper with DEBUGGING build on VMS

**Steps to Reproduce**

The utf8.t test for Devel::PPPort fails like so:

```
$ perl ../dist/Devel-PPPort/t/utf8.t
1..93
ok 1
...
ok 35
assert error: expression = s < send, in file D0:[craig.blead]inline.h;1 at line 1851
```

which can be reduced to:

```
$ perl -"MDevel::PPPort" -e "package Devel::PPPort; use vars '@ISA'; require DynaLoader; @ISA=qw(DynaLoader); bootstrap Devel::PPPort; print &Devel::PPPort::utf8_to_uvchr_buf('A', -1);"
assert error: expression = s < send, in file D0:[craig.blead]inline.h;1 at line 1851
```

Stepping through to the error in the VMS debugger and examining the values of s and send right before the crash looks like this:

```
go
!break at routine PERLMAIN\main
!483671:     PL_use_safe_putenv = FALSE;
set image dbgperlshr
set module pp_hot
set break PP_HOT\Perl_pp_entersub\%LINE 487877
for i = 1 to 15 do (go)
!break at PP_HOT\Perl_pp_entersub\%LINE 487877
!487877:         CvXSUB(cv)(aTHX_ cv);
!break at PP_HOT\Perl_pp_entersub\%LINE 487877
!487877:         CvXSUB(cv)(aTHX_ cv);
!break at PP_HOT\Perl_pp_entersub\%LINE 487877
!487877:         CvXSUB(cv)(aTHX_ cv);
!break at PP_HOT\Perl_pp_entersub\%LINE 487877
!487877:         CvXSUB(cv)(aTHX_ cv);
!break at PP_HOT\Perl_pp_entersub\%LINE 487877
!487877:         CvXSUB(cv)(aTHX_ cv);
!break at PP_HOT\Perl_pp_entersub\%LINE 487877
!487877:         CvXSUB(cv)(aTHX_ cv);
!break at PP_HOT\Perl_pp_entersub\%LINE 487877
!487877:         CvXSUB(cv)(aTHX_ cv);
!break at PP_HOT\Perl_pp_entersub\%LINE 487877
!487877:         CvXSUB(cv)(aTHX_ cv);
!break at PP_HOT\Perl_pp_entersub\%LINE 487877
!487877:         CvXSUB(cv)(aTHX_ cv);
!break at PP_HOT\Perl_pp_entersub\%LINE 487877
!487877:         CvXSUB(cv)(aTHX_ cv);
!break at PP_HOT\Perl_pp_entersub\%LINE 487877
!487877:         CvXSUB(cv)(aTHX_ cv);
!break at PP_HOT\Perl_pp_entersub\%LINE 487877
!487877:         CvXSUB(cv)(aTHX_ cv);
!break at PP_HOT\Perl_pp_entersub\%LINE 487877
!487877:         CvXSUB(cv)(aTHX_ cv);
!break at PP_HOT\Perl_pp_entersub\%LINE 487877
!487877:         CvXSUB(cv)(aTHX_ cv);
!break at PP_HOT\Perl_pp_entersub\%LINE 487877
!487877:         CvXSUB(cv)(aTHX_ cv);
step/into
!%DEBUG-I-DYNIMGSET, setting image PL_DEVEL__PPPORT
!%DEBUG-I-DYNMODSET, setting module REALPPPORT
!stepped to REALPPPORT\XS_Devel__PPPort_utf8_to_uvchr_buf\%LINE 500306
!500306:     dVAR; dXSARGS;
s
!stepped to REALPPPORT\XS_Devel__PPPort_utf8_to_uvchr_buf\%LINE 500307
!500307:     if (items != 2)
s
!stepped to REALPPPORT\XS_Devel__PPPort_utf8_to_uvchr_buf\%LINE 500310
!500310:         unsigned char * s = (unsigned char *)SvPV_nolen(ST(0))
s
!stepped to REALPPPORT\XS_Devel__PPPort_utf8_to_uvchr_buf\%LINE 500312
!500312:         int     adjustment = (int)SvIV(ST(1))
s
!stepped to REALPPPORT\XS_Devel__PPPort_utf8_to_uvchr_buf\%LINE 500318
!500318:             av = newAV();
s
!stepped to REALPPPORT\XS_Devel__PPPort_utf8_to_uvchr_buf\%LINE 500319
!500319:             const_s = s;
s
!stepped to REALPPPORT\XS_Devel__PPPort_utf8_to_uvchr_buf\%LINE 500320
!500320:             av_push(av, newSVuv(utf8_to_uvchr_buf(const_s,
step/into
!stepped to REALPPPORT\Perl_utf8_to_uvchr_buf_helper\%LINE 478912
!478912:     PERL_ARGS_ASSERT_UTF8_TO_UVCHR_BUF_HELPER;
s
!stepped to REALPPPORT\Perl_utf8_to_uvchr_buf_helper\%LINE 478914
!478914:     assert(s < send);
ex s
!REALPPPORT\Perl_utf8_to_uvchr_buf_helper\s:     40107456
ex send
!REALPPPORT\Perl_utf8_to_uvchr_buf_helper\send:  40107456
ex *s
!*REALPPPORT\Perl_utf8_to_uvchr_buf_helper\s:    "A"
ex *send
!*REALPPPORT\Perl_utf8_to_uvchr_buf_helper\send: "A"
step
!%DEBUG-I-EXITSTATUS, is '%SYSTEM-F-OPCCUS, opcode reserved to customer fault at PC=0000000000000000, PS=00000000'
EXIT

```

So `s` and `send` are identical and at identical addresses, but the `assert` expects `s` to have a lower address than `send`. I have no idea what this function is intended to do, so I can't really guess why that's a problem. Unless it's another case where having 64-bit UV/IV but 32-bit STRLEN has confused something.

**Perl configuration**

```
$ perl -V
Summary of my perl5 (revision 5 version 31 subversion 8) configuration:
  Snapshot of: 4eeaed3791af175b5840f626d4d1a4e3b4cb3543
  Platform:
    osname=VMS
    osvers=V8.4-2L1
    archname=VMS_IA64
    uname='VMS alma V8.4-2L1 HP rx2660  (1.67GHz/9.0MB)'
    config_args='-"Dusedevel" -"DDEBUGGING" -"Dusevmsdebug" -"des"'
    hint=none
    useposix=false
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=undef
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='CC/DECC'
    ccflags ='/Include=[]/Standard=Relaxed_ANSI/Prefix=All/Obj=.obj /NOANSI_ALIAS/float=ieee/ieee=denorm/NAMES=(SHORTENED)/Define=_USE_STD_STAT=1'
    optimize='/List/Debug/NoOpt'
    cppflags='undef'
    ccversion='70490001'
    gccversion=''
    gccosandvers='undef'
    intsize=4
    longsize=4
    ptrsize=4
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=1
    ivtype='long long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='Link/nodebug'
    ldflags ='/Debug/Trace/Map'
    libpth=/sys$share /sys$library
    libs=
    perllibs=
    libc=(DECCRTL)
    so=exe
    useshrplib=true
    libperl=undef
    gnulibc_version='undef'
  Dynamic Linking:
    dlsrc=dl_vms.xs
    dlext=exe
    d_dlsymun=undef
    ccdlflags=''
    cccdlflags=''
    lddlflags='/Share'


Characteristics of this PERLSHR image:
  Compile-time options:
    DEBUGGING
    HAS_TIMES
    HAVE_INTERP_INTERN
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_EXTERNAL_GLOB
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    USE_64_BIT_INT
    USE_IEEE
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    VMS_DO_SOCKETS
    VMS_SHORTEN_LONG_SYMBOLS
  Built under VMS
  Compiled at Jan  1 2020 18:05:43
  %ENV:
    PERLDB_PIDS="1078"
    PERLSHR="perl_root:[000000]perlshr.exe"
    PERL_ROOT="$2$DKA7:[craig.blead.]"
  @INC:
    /perl_root/lib/site_perl/VMS_IA64
    /perl_root/lib/site_perl
    /perl_root/lib/VMS_IA64/5_31_8
    /perl_root/lib
```

**Comment by khwilliamson** [comment]
I can reproduce this on my blead linux box.  And it is actually working as it is supposed to.

You got this by running the Devel::PPPort test suite, and distilled it down to this incantation.  The actual problem is that the test is supposed to be skipped on DEBUGGING builds.  It is deliberately creating malformed UTF-8 input, which in modern perls is caught at a higher level, hence the assert.

The bug then is that this test isn't getting skipped in vms when it should be.  The test for skipping is 

    if ($Config{ccflags} =~ /-DDEBUGGING/) {

I see from the Perl configuration you provided that you have a debugging build without that pattern matching.  What then is the proper way for a perl script to portably test if it is being run on a DEBUGGING build?  I imagine I cargo culted that line of code.  Therefore, we need to examine blead source for similar occurrences, as they won't work on vms.  Any other platforms with similar issues?

**Comment by craigberry** [comment]
Thanks for tracking that down.  This pattern stands a better chance of working (can't test at the moment):

`  if ($Config{ccflags} =~ /\bDDEBUGGING\b/) {`

I suspect the problem with the current check in Devel::PPPort is the quoting of the argument to configure.com like so:

`-"DDEBUGGING"`

where the quote gets in between the "-" and the initial "D".

**Comment by khwilliamson** [comment]
The listed ccflags however are

ccflags ='/Include=[]/Standard=Relaxed_ANSI/Prefix=All/Obj=.obj /NOANSI_ALIAS/float=ieee/ieee=denorm/NAMES=(SHORTENED)/Define=_USE_STD_STAT=1'

with no sign of DEBUGGING in it.

**Comment by craigberry** [comment]
Oops.  I knew that at some point but clearly wasn't paying attention.  I think it gets written to config.h rather than appearing in ccflags.  If we changed that, it would look like:

`/Define=(_USE_STD_STAT=1,DEBUGGING)`

which wouldn't match the existing patterns.  I think

`$Config{config_args} =~ /\bDDEBUGGING\b/)`

would probably be best but again I can't do a thorough test right now.

**Comment by khwilliamson** [comment]
Please try out the branch smoke-me/khw-vms
which uses the Configure args instead of ccflags.  

I found these other instances with the same paradigm:

./t/op/aassign.t:    skip "DEBUGGING build" if $::Config{ccflags} =~ /(?<!\S)-DDEBUGGING(?!\S)/
./t/run/switchDx.t:  unless $::Config{ccflags} =~ /(?<!\S)-DDEBUGGING(?!\S)/
./t/win32/system_tests:	    if ($Config{ccflags} =~ /\bDDEBUGGING\b/) {
./t/win32/system_tests:	    if ($Config{ccflags} =~ /\bDDEBUGGING\b/) {
./dist/Storable/t/threads.t:    if ($] == 5.008002 and eval q{ $Config{'ccflags'} =~ /(?<!\S)-DDEBUGGING(?!\S)/ }) {

Note that one can call Configure with -DEBUGGING (missing a 'D') and it still works.  I also found this, don't know if there is any significance:

./vms/gen_shrfls.pl:  $debugging_enabled ||= $defines =~ /\bDEBUGGING\b/;

**Comment by craigberry** [comment]
`$Config{config_args}` works on VMS, but it appears that Windows does not even populate that key in %Config so it would break on Windows.  On 5.14 and later, it looks like we can do this by calling `Config::non_bincompat_options()`, so at least that's a solution for core tests:

```
$ perl -MConfig -e "print scalar(grep /^DEBUGGING$/, Config::non_bincompat_options());"
1
```

I will try to do some testing with this in the next couple of days.

**Comment by craigberry** [comment]
We can't use Config::non_bincompat_options() in Devel::PPPort tests because of its absurd "forever" support policy, so I have fixed this case with the following.  As Karl points out, there are a few other tests that may need to be looked at, but they aren't causing failures currently.


```
commit 68ce2ab964838e77cdf58bd0a42e1716fc4ed49c (HEAD -> blead)
Author: Craig A. Berry <craigberry@mac.com>
Date:   Fri Jan 17 12:20:42 2020 -0600

    Fix DEBUGGING check in Devel-PPPort/t/utf8.t

    Devel::PPPort claims to support Perl back to 5.003_07, which means
    that we can't use a more rational method here such as
    Config::non_bincompat_options().

diff --git a/dist/Devel-PPPort/t/utf8.t b/dist/Devel-PPPort/t/utf8.t
index bcd22b89d7..3ba2e8acf9 100644
--- a/dist/Devel-PPPort/t/utf8.t
+++ b/dist/Devel-PPPort/t/utf8.t
@@ -189,7 +189,11 @@ else {
     # deliberately the first test.
     require Config; import Config;
     use vars '%Config';
-    if ($Config{ccflags} =~ /-DDEBUGGING/) {
+    # VMS doesn't put DEBUGGING in ccflags and Windows doesn't have $Config{config_args}.
+    # When 5.14 or later can be assumed, use Config::non_bincompat_options(), but for
+    # now we're stuck with this.
+    if ($Config{ccflags} =~ /-DDEBUGGING/
+        || $^O eq 'VMS' && $Config{config_args} =~ /\bDDEBUGGING\b/) {
         shift @buf_tests;
         skip("Test not valid on DEBUGGING builds", 5);
     }

```
