### ISSUE TITLE
New warning - scalar assignment from @_

### ISSUE THREAD

**Issue by leonerd** [Perl/perl5#17418]
I've now lost count of the number of bugs I've caused by

    my $message = @_;

when I meant either of

    my $message = shift;
    my ( $message ) = @_;

In the frigtningly rare case I wanted a count of the arguments, I'd likely want to write it using the `scalar` operator explicitly, to remind the human reader as much as perl itself:

    my $argc = scalar @_;

Therefore, would we consider adding a new warning?

    $ perl -Mwarnings -ce 'my $message = @_'
    Use of @_ in scalar assignment may be unintentional at -e line 1.

(cc to perl5-porters@)

**Comment by leonerd** [comment]
Further clarification: The warning is purely for `@_` appearing on its own on the RHS of
scalar assignment. None of the following would apply, for example:

    if( @_ ) ...

    if( @_ > 2 ) ...

    my $argc = 0 + @_;

**Comment by iabyn** [comment]
On Mon, Jan 13, 2020 at 10:38:34AM -0800, Paul Evans wrote:
> Further clarification: The warning is purely for `@_` appearing on its own on the RHS of
> scalar assignment. None of the following would apply, for example:
> 
>     if( @_ ) ...
> 
>     if( @_ > 2 ) ...
> 
>     my $argc = 0 + @_; 

While such a warning will of course flush out possible bugs, it will also
warn on existing perfectly valid code, such as

    my $nargs = @_;

A quick CPAN grep of \$\w+\s*=\s*\@_; matches 267 distributions, and
looking at the first few hits, about 2/3 appear to be valid uses.

Coupled with code that may have done "use warnings FATAL => 'all'", there
is lots of scope for breakage of existing code. So its a -1 from me.

-- 
"You're so sadly neglected, and often ignored.
A poor second to Belgium, When going abroad."
    -- Monty Python, "Finland"

**Comment by hvds** [comment]
> A quick CPAN grep of \$\w+\s*=\s*\@_; matches 267 distributions, and looking at the first few hits, about 2/3 appear to be valid uses.

That also implies that, even if it took some pain to get there, such a warning would help fix an awful lot of bugs.

Hugo

**Comment by xenu** [comment]
Why warn just for `@_`? There's nothing special about `@_`, this "problem" exists for all arrays.

**Comment by tonycoz** [comment]
-1 from me, there's too many false positives.

This seems more suited as a `Perl::Critic` policy to me.

**Comment by jkeenan** [comment]
On 1/15/20 11:19 PM, Tony Cook wrote:
> -1 from me, there's too many false positives.
> 
> This seems more suited as a |Perl::Critic| policy to me.
> 

Agreed.

**Comment by Leont** [comment]
> This seems more suited as a Perl::Critic policy to me.

Agreed

**Comment by tonycoz** [comment]
The consensus seems to be to no implement this.  Closing.
