### ISSUE TITLE
[feature] The fix of 50-year bug in Time::Local 1.26 should return 1900+number when input year is below 100.

### ISSUE THREAD

**Issue by ghost** [Perl/perl5#17411]
**Description**
About the below fix of 50-year bug in Time::Local 1.26,
https://metacpan.org/changes/distribution/Time-Local#L22

Currently, if the input number is 70 at 2020 it will return 2070.
Reading of codes,
```
### my $Breakpoint  = ( $ThisYear + 50 ) % 100;
### my $NextCentury = $ThisYear - $ThisYear % 100; # 1950~2049=>2000. 2050~2149=>2100.
### $NextCentury += 100 if $Breakpoint < 50; # condition is xx50~xx99

#
# Current
# 1970 -
#    ThisYear    = 1970
#    Breakpoint  = 20
#    NextCentury = 2000
#    Century     = 1900
#
#    If input is 0-20, return 2000+input. This is a Bug.
#    But it would not happen, because user usually use number above 70 (which is 1970-1900).
#
# 2019 -
#    ThisYear    = 2019
#    Breakpoint  = 69
#    NextCentury = 2000
#    Century     = 1900
#
#    If input is 0-69, return 2000+input. This is a Bug.
#    But it would not happen, because user usually use number above 70 (which is 1970-1900).
#
# 2020 -
#    ThisYear    = 2020
#    Breakpoint  = 70
#    NextCentury = 2000
#    Century     = 1900
#
#    If input is 0-70, return 2000+input. This is a Bug.
#    !! This would happen. Because number 70 is commonly used as 1970 abbreviation.
```

This is so strange because NextCentury and Century actually not right time period.
Also, I input number (0-69) and get 2000+number while inputting number (79-99) and get 1900+number at 2019. This is confusing and leads user to fix bunch of codes when it changes.

**Ideal**
Forcing user not to input abbreviation and to use exact number is best, but not realistic.
It will force user to fix huge code because the systems using perl are mainly old.
So, Ideal is input number (0-99) just return 1900+number.

**Summary**
I would like to know if my thoughts have any problem, and if this fix should be done I would send PR.

Any response is appreciated.

**Comment by Grinnz** [comment]
This would be a breaking change for code expecting two-digit years to refer to the rolling century (this behavior is documented, not a bug). The _modern functions can be used for consistency and I have proposed another set of functions that consistently interpret it since 1900 in https://github.com/houseabsolute/Time-Local/issues/11. (and note, this module is CPAN-first so changes should go to its bugtracker.)

**Comment by ghost** [comment]
`This is a Bug` was my mistake. Sorry.

I knew it was documented, but I just felt it odd and faced bugs in fact as well as others as I mentioned.

I will try using the wrapper for safety.

Thank you for your response.
