### ISSUE TITLE
Handle getprotobyn{ame,umber} not being available [rt.cpan.org #90225]

### ISSUE THREAD

**Issue by toddr** [Perl/perl5#17436]
Migrated from [rt.cpan.org#90225](https://rt.cpan.org/Ticket/Display.html?id=90225) (status was 'new')

Requestors:
* fraserbn@gmail.com

From fraserbn@gmail.com on 2013-11-11 02:27:28:

If perl is built with -Ud_getprotobyname -Ud_getprotobynumber, or if, like in Android, the OS lacks those functions, using them will cause a runtime exception saying that they aren't implemented.
The patch below protects the calls with an eval {}, which works around the issue. Alternatively, this could be implemented as if ($Config{d_getprotobyname}) { getprotobyname() }

```diff
diff --git a/dist/IO/lib/IO/Socket/INET.pm b/dist/IO/lib/IO/Socket/INET.pm
index 4fa6a29..07f2b3f 100644
--- a/dist/IO/lib/IO/Socket/INET.pm
+++ b/dist/IO/lib/IO/Socket/INET.pm
@@ -50,7 +50,7 @@ sub _get_proto_number {
     return undef unless defined $name;
     return $proto_number{$name} if exists $proto_number{$name};
 
-    my @proto = getprotobyname($name);
+    my @proto = eval { getprotobyname($name) };
     return undef unless @proto;
     _cache_proto(@proto);
 
@@ -62,7 +62,7 @@ sub _get_proto_name {
     return undef unless defined $num;
     return $proto_name{$num} if exists $proto_name{$num};
 
-    my @proto = getprotobynumber($num);
+    my @proto = eval { getprotobynumber($num) };
     return undef unless @proto;
     _cache_proto(@proto);
 
```

From fraserbn@gmail.com on 2013-11-11 02:29:04:

Er, minor correction, in the alternative using Config, it should be checking for d_getpbyname, not d_getprotobyname.

**Comment by richardleach** [comment]
The proposed changes are in blead. Looks to have been fixed since 2014 in https://github.com/Perl/perl5/commit/02f178b3ec6512946cf6e11d1305e2e22edb4aa7.
