### ISSUE TITLE
Skip EINVAL on FreeBSD tests when binding a tcp listener on localhost.

### ISSUE THREAD

**Issue by toddr** [Perl/perl5#17433]
I'm passing this issue on from a ticket opened in IO's RT queue.

Some freebsd's disallow resolving localhost and return EINVAL when binding a tcp listener on localhost.
See my FreeBSD smoker errors: https://cirrus-ci.com/task/5137254568689664

The fix is attached.

```diff
commit f445c280ec46d0d38160b1f8227ad92425f2c0dc
Author: Reini Urban <rurban@cpan.org>
Date:   Mon Apr 1 10:14:48 2019 +0200

    IO-1.39_02
    
    Skip EINVAL on FreeBSD tests when binding a tcp listener on localhost.

diff --git dist/IO/t/io_multihomed.t dist/IO/t/io_multihomed.t
index f2a8e11f1c..c511f188b7 100644
--- dist/IO/t/io_multihomed.t
+++ dist/IO/t/io_multihomed.t
@@ -24,7 +24,6 @@ BEGIN {
 
 $| = 1;
 
-print "1..8\n";
 watchdog(15);
 
 package Multi;
@@ -73,13 +72,24 @@ sub connect
 package main;
 
 use IO::Socket;
+# Don't be locale-sensitive
+$! = Errno::EINVAL;
+my $EINVAL_STR = "$!";
 
 $listen = IO::Socket::INET->new(LocalAddr => 'localhost',
 				Listen => 2,
 				Proto => 'tcp',
 				Timeout => 5,
-			       ) or die "$!";
+                               );
+unless ($listen) {
+  if ($^O eq 'freebsd' && $! eq $EINVAL_STR) {
+    skip_all("tcp listener on localhost disallowed on this $^O");
+  } else {
+    die "$!";
+  }
+}
 
+print "1..8\n";
 print "ok 1\n";
 
 $port = $listen->sockport;
diff --git dist/IO/t/io_sock.t dist/IO/t/io_sock.t
index 37c8dad84e..6933b9f5e2 100644
--- dist/IO/t/io_sock.t
+++ dist/IO/t/io_sock.t
@@ -27,7 +27,6 @@ BEGIN {
 my $has_perlio = find PerlIO::Layer 'perlio';
 
 $| = 1;
-print "1..26\n";
 
 eval {
     $SIG{ALRM} = sub { die; };
@@ -35,6 +34,9 @@ eval {
 };
 
 use IO::Socket;
+# Don't be locale-sensitive
+$! = Errno::EINVAL;
+my $EINVAL_STR = "$!";
 
 $listen = IO::Socket::INET->new(LocalAddr => 'localhost',
 				Listen => 2,
@@ -42,8 +44,16 @@ $listen = IO::Socket::INET->new(LocalAddr => 'localhost',
 				# some systems seem to need as much as 10,
 				# so be generous with the timeout
 				Timeout => 15,
-			       ) or die "$!";
+			       );
+unless ($listen) {
+  if ($^O eq 'freebsd' && $! eq $EINVAL_STR) {
+    skip_all("tcp listener on localhost disallowed on this $^O");
+  } else {
+    die "$!";
+  }
+}
 
+print "1..26\n";
 print "ok 1\n";
 
 # Check if can fork with dynamic extensions (bug in CRT):
```

**Comment by toddr** [comment]
Transferred from https://rt.cpan.org/Public/Bug/Display.html?id=128987 which later got moved to https://github.com/Dual-Life/IO/issues/50

I am closing those tickets in favor of this one.

**Comment by jkeenan** [comment]
Todd,

While I'm not opposed to considering this patch, I should state that 
I've been smoke-testing on FreeBSD-11.2-amd64 for more than two years 
now and have not observed this failure.

Also, it appears to me that that link is reporting on cperl, not perl. 
Can you advise on how to get the data?

Thank you very much.
Jim Keenan

**Comment by toddr** [comment]
Sorry @jkeenan you now know as much as me 😞  I'm happy to close this if you think that is a good choice.

**Comment by jkeenan** [comment]
On 1/20/20 10:32 AM, Todd Rinaldo wrote:
> Sorry @jkeenan <https://github.com/jkeenan> you now know as much as me 
> :( I'm happy to close this if you think that is a good choice.
> 

Yes, let's close it.  The original description ...

"Some freebsd's disallow resolving localhost and return EINVAL when 
binding a tcp listener on localhost."

... is too vague for us to act on, IMO.  *Which* FreeBSDs?  With *what 
specific* Perl configurations?

If we get a better report we can create a new ticket/issue.

Thank you very much.
Jim Keenan

**Comment by bingos** [comment]
Just to add my three cents, I built and installed cperl 5.30.0 on FreeBSD 11.3-RELEASE and tested the latest IO-1.42 and it passed all its tests fine.
