### ISSUE TITLE
Minimum perl version mismatch [rt.cpan.org #49852]

### ISSUE THREAD

**Issue by toddr** [Perl/perl5#17462]
Migrated from [rt.cpan.org#49852](https://rt.cpan.org/Ticket/Display.html?id=49852) (status was 'new')

Requestors:
* ribasushi@leporine.io

From ribasushi@leporine.io on 2009-09-20 12:00:41:
```
Hi,

In the makefile you state the minimum perl version to be 5.6.1:
BEGIN { require 5.006_001 }

The tests however make liberal use of functions introduced by Test::More
(e.g. isa_ok, use_ok...), which in itself is not core until 5.6.2. 

Cheers
```

**Comment by xenu** [comment]
The minimum required version was bumped to 5.8.1 some time ago, so this issue is no longer relevant.
