### ISSUE TITLE
[Win32] Adding -fdiagnostics-color=never prevents perl from building

### ISSUE THREAD

**Issue by sisyphus** [Perl/perl5#17480]
IIUC: if I want to add a switch to $Config{ccflags} on Windows, then the approved method is to assign that switch to BUILDOPT.

So I specify BUILDOPT=-fdiagnostics-color=never in my build script, and everything is fine until the make process gets to:

gcc -c -I..  -I.\include -I. -I.. -DWIN32 -DWIN64 -DPERLDLL -DPERL_CORE -s -O2 -fdiagnostics-color=never -o..\toke.o  ..\toke.c
In file included from ..\perl.h:5487,
                 from ..\toke.c:40:
..\toke.c: In function 'yyl_data_handle':
..\toke.c:6560:29: error: 'RSFP_FILENO' undeclared (first use in this function);
 did you mean 'OP_FILENO'?
         if (PerlLIO_setmode(RSFP_FILENO, O_TEXT) != -1) {
                             ^~~~~~~~~~~
./win32iop.h:247:40: note: in definition of macro 'setmode'
 #define setmode(fd,mode) win32_setmode(fd,mode)
                                        ^~
..\toke.c:6560:13: note: in expansion of macro 'PerlLIO_setmode'
         if (PerlLIO_setmode(RSFP_FILENO, O_TEXT) != -1) {
             ^~~~~~~~~~~~~~~
..\toke.c:6560:29: note: each undeclared identifier is reported only once for each function it appears in
         if (PerlLIO_setmode(RSFP_FILENO, O_TEXT) != -1) {
                             ^~~~~~~~~~~
./win32iop.h:247:40: note: in definition of macro 'setmode'
 #define setmode(fd,mode) win32_setmode(fd,mode)
                                        ^~
..\toke.c:6560:13: note: in expansion of macro 'PerlLIO_setmode'
         if (PerlLIO_setmode(RSFP_FILENO, O_TEXT) != -1) {
             ^~~~~~~~~~~~~~~

Even if I then re-run the failing command without the "-fdiagnostics-color=never" switch it still fails.
So far, my only way of successfully getting -fdiagnostics-color=never into ccflags is to build perl without the switch, then insert the switch into the ccflags and ccflags_nolargefiles entries in lib/Config_heavy.pl.
This works quite well and I've now written the procedure  into my build script.
However, it would have been much simpler if my first attempt had succeeded.

Should my initial attempt have succeeded ?
Or do I misunderstand something ?

Cheers,
Rob

The perl -V output below is from a perl-5.31.8 built using that second technique.

# perl -V output goes here
```
Summary of my perl5 (revision 5 version 31 subversion 8) configuration:
   
  Platform:
    osname=MSWin32
    osvers=6.1.7601
    archname=MSWin32-x64-multi-thread
    uname=''
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags =' -DWIN32 -DWIN64  -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -D__USE_MINGW_ANSI_STDIO -fwrapv -fdiagnostics-color=never -fno-strict-aliasing -mms-bitfields'
    optimize='-s -O2'
    cppflags='-DWIN32'
    ccversion=''
    gccversion='8.3.0'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='long long'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags ='-s -L"C:\_64\blead-5.31.8\lib\CORE" -L"C:\_64\gcc-straw-830\mingw64\lib"'
    libpth=C:\_64\gcc-straw-830\mingw64\lib C:\_64\gcc-straw-830\mingw64\x86_64-w64-mingw32\lib C:\_64\msys_830\1.0\local\lib C:\_64\gcc-straw-830\mingw64\lib\gcc\x86_64-w64-mingw32\8.3.0
    libs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    libc=
    so=dll
    useshrplib=true
    libperl=libperl531.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-mdll -s -L"C:\_64\blead-5.31.8\lib\CORE" -L"C:\_64\gcc-straw-830\mingw64\lib"'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    HAVE_INTERP_INTERN
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_IMPLICIT_SYS
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under MSWin32
  Compiled at Jan 21 2020 16:01:34
  @INC:
    C:/_64/blead-5.31.8/site/lib
    C:/_64/blead-5.31.8/lib

**Comment by xenu** [comment]
Try using `BUILDOPTEXTRA` instead.

**Comment by sisyphus** [comment]
Yes, that's what I needed - thank you.
This was a user bug, not a perl bug.

Cheers,
Rob
