### ISSUE TITLE
[feature] Add IPC::System::Simple to core

### ISSUE THREAD

**Issue by cxw42** [Perl/perl5#17507]
CXW here with my first issue ever filed for perl5.  My apologies for any errors in this submission.  I did check previous issues.

The [cpantesters matrix](http://matrix.cpantesters.org/?dist=App-unbelievable) for my recent App::unbelievable is very spotty, and as far as I can tell, all the failures are due to lack of IPC::System::Simple.  Errors are all of the form:

> Error:  IPC::System::Simple required for Fatalised/autodying system() at /home/cpansand/.cpan/build/2020012706/App-unbelievable-v0.0.1-2/blib/lib/App/unbelievable/Util.pm line 15.

The relevant code is `use autodie ':all';`.

I have released App-unbelievable v0.0.2 with code to report IPC::System::Simple presence, so in a day or two I should have data relevant to my hypothesis.  ~I will report back here when I do.~  **Edit** see https://github.com/Perl/perl5/issues/17507#issuecomment-581964347

**Describe the solution you'd like**

Would you please add IPC::System::Simple to core?  That way `use autodie ':all'` will work consistently going forward without having to add a separate dependency on IPC::System::Simple.

Thank you for considering this request!  Please let me know if I should report it in IPC::System::Simple instead.

### Why do I care about this?

I have often read recommendations to use `autodie`.  For example, [computerhope](https://www.computerhope.com/unix/perlprag.htm#pragma:autodie) specifically says:

> use autodie qw(:all); # Recommended more: defaults and system/exec.

However, that example does not mention IPC::System::Simple at all!  So the recommendation is actually one that will cause compilation failures for reasons new Perl users will be completely unaware of.

As another example, even [brian d foy's treatment of autodie](https://www.learning-perl.com/2011/01/when-trytiny-and-autodie/) doesn't mention IPC::System::Simple.  A search on his site for "autodie" yields [this page](https://www.learning-perl.com/2011/01/updates-to-chapter-16-process-management/), which mentions IPC::System::Simple, but doesn't connect it to autodie.

I think adding IPC::System::Simple to core (whether dual-life or core-only) would reduce the chance of confusion on the part of new Perl users, and make autodie a more useful module.

#### How did I find out about this? (for context)

I recently discovered by accident at $work that `autodie` doesn't help with `qx{}`.  That caused me to read the POD for `autodie`, which told me about IPC::System::Simple.

**Comment by cxw42** [comment]
OK - I have the data!  [CPANtesters analysis](http://analysis.cpantesters.org/reports_by_field?distv=App-unbelievable-v0.0.2-TRIAL;field=qr%3A%28Can%27t%20locate%20%5CS%2Bpm%29) shows that, indeed, my test failures in App::unbelievable are associated with lack of IPC::System::Simple with only one (rather bizarre) exception ([1](http://www.cpantesters.org/cpan/report/110583500)).

**Comment by jkeenan** [comment]
> OK - I have the data! [CPANtesters analysis](http://analysis.cpantesters.org/reports_by_field?distv=App-unbelievable-v0.0.2-TRIAL;field=qr%3A%28Can%27t%20locate%20%5CS%2Bpm%29) shows that, indeed, my test failures in App::unbelievable are associated with lack of IPC::System::Simple with only one (rather bizarre) exception ([1](http://www.cpantesters.org/cpan/report/110583500)).

The likely solution to your problem is to add 
```
requires 'IPC::System::simple';
```
... to your `cpanfile`.  (I say that it's the 'likely' solution to your problem because you're using Minilla, a non-standard build tool with which I am not familiar and which is not part of the Perl 5 core distribution.)

The documentation for `autodie` clearly states:
```
A plain C<use autodie> implies C<use autodie qw(:default)>.  Note that
C<system> and C<exec> are not enabled by default.  C<system> requires
the optional L<IPC::System::Simple> module to be installed, and enabling
C<system> or C<exec> will invalidate their exotic forms.
```
As a module author, it's your responsibility to understand the quirks and limitations of the libraries upon which your code depends.  Adding IPC::System::Simple to the core distribution is not warranted and will not be of benefit here.

Thank you very much.
Jim Keenan

**Comment by cxw42** [comment]
Jim, thanks for your response!  I heartily agree that module users _should_ read the docs.  I think `autodie` is a special case because its use is widely recommended to beginners in Perl, who will not know where those docs are or how to find them.  **Edit** `autodie` is also unusual in that, as far as I know, it is the only pragma not fully functional with only what is included in core (please correct me if I'm wrong!).

**Comment by karenetheridge** [comment]
FWIW, adding a module to core will not help you for any existing Perl version, where that module still isn't in core.

autodie's documentation could certainly mention more prominently which situations it pulled in the optional dependency IPC::System::Simple, so users would be aware that they must add it to their own prereq list.
