### ISSUE TITLE
op.c: new build-time warning in debugging build using gcc

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#17517]
A new build-time warning generated by gcc in `op.c` *in debugging builds only* was introduced in November.  In 'make' output it appears here:

```
echo @`sh  cflags "optimize='-O2 -g'" opmini.o`  -DPERL_IS_MINIPERL -DPERL_EXTERNAL_GLOB opmini.c
@cc -c -DPERL_CORE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -std=c89 -O2 -g -Wall -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings -Werror=declaration-after-statement -DPERL_IS_MINIPERL -DPERL_EXTERNAL_GLOB opmini.c
op.c: In function ‘S_pmtrans’:
op.c:7052:22: warning: ‘r_map’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             r_map[i] = TR_UNLISTED;
```

Here is the relevant section of `op.c`:

```
 7049         /* And the mapping of each of the ranges is initialized.  Initially,
 7050          * everything is TR_UNLISTED. */
 7051         for (i = 0; i < len; i++) {
 7052             r_map[i] = TR_UNLISTED;
 7053         }
```

This was introduced in the following commit:

```
commit f34acfecc286f2eff2450db713da005d888a7317
Author:     Karl Williamson <khw@cpan.org>
AuthorDate: Mon Nov 4 21:30:48 2019 -0700
Commit:     Karl Williamson <khw@cpan.org>
CommitDate: Wed Nov 6 21:22:24 2019 -0700

    Reimplement tr/// without swashes
    
    This large commit removes the last use of swashes from core.
    
    It replaces swashes by inversion maps.  This data structure is already
    in use for some Unicode properties, such as case changing.
```

We don't get this warning in regular builds.  Nor do we get it in debugging builds using `clang` rather than `gcc`.  @khwilliamson, can you take a look?

Thank you very much.
Jim Keenan

**Comment by hvds** [comment]
Well the claim is wrong: it is not used uninitialized, it's just failing to make the link between `for (pass2 = 0; pass2 < 2; pass2++)` and the following `if (pass2) { ... } else { initialize r_map }`. But I think there's no reason not to hoist that preamble outside the loop, I've created a PR doing that.

I've preserved the order of statements and associated comments pretty precisely, but it may be that some further tweaks are valuable after that.

Hugo

**Comment by toddr** [comment]
@hvds was the pr https://github.com/Perl/perl5/pull/17519 ?

**Comment by hvds** [comment]
> @hvds was the pr #17519 ?

@toddr Yes.

**Comment by jkeenan** [comment]
https://github.com/Perl/perl5/pull/17519 was merged into blead on Feb 01.  I am no longer getting this warning in debugging builds using gcc (now version 7.5.0).  Closing.

Thank you very much.
Jim Keenan
