### ISSUE TITLE
"I see you are using the Korn shell" under Bash on Solaris 11 i86pc

### ISSUE THREAD

**Issue by noloader** [Perl/perl5#17518]
**Description**
I'm building the Perl 5.30.1 release tarball on Solaris 11 i86pc. When running `Configure` I see the message:

```
$ ./Configure ...

(I see you are using the Korn shell.  Some ksh's blow up on Configure,
mainly on older exotic systems.  If yours does, try the Bourne shell instead.)
First let's make sure your kit is complete.  Checking...
```

That message really annoys me for some reason. Mainly because I use the Bash shell, not a Korn shell. It has also been there for quite some time, and it would be nice if it goes away.

Solaris is known for antique software. I think Red Hat and Sun are in competition to see which can provide the oldest software in a modern distro. Solaris provides:

```
$ bash --version
GNU bash, version 4.1.17(1)-release (i386-pc-solaris2.11)
Copyright (C) 2009 Free Software Foundation, Inc.
```

**Perl configuration**
```
$ /usr/local/bin/perl -V
Summary of my perl5 (revision 5 version 30 subversion 1) configuration:
   
  Platform:
    osname=solaris
    osvers=2.11
    archname=i86pc-solaris-64
    uname='sunos solaris 5.11 11.3 i86pc i386 i86pc solaris '
    config_args='-des -Dprefix=/usr/local -Dlibdir=/usr/local/lib -Dpkgconfig=/usr/local/lib/pkgconfig -Dcc=gcc -Acppflags=-I/usr/local/include -DNDEBUG -Accflags=-g2 -O2 -m64 -march=native -fPIC -pthread -Aldflags=-L/usr/local/lib -m64 -Wl,-R,'$$ORIGIN/../lib' -Wl,-R,/usr/local/lib -Dextras=Text::Template Test::More'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags ='-g2 -O2 -m64 -march=native -fPIC -pthread -fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -I/usr/gnu/include -m64 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -DPERL_USE_SAFE_PUTENV'
    optimize='-O'
    cppflags='-I/usr/local/include -DNDEBUG -g2 -O2 -m64 -march=native -fPIC -pthread -fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -I/usr/gnu/include'
    ccversion=''
    gccversion='4.8.2'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='gcc'
    ldflags =' -L/usr/local/lib -m64 -Wl,-R,22124ORIGIN/../lib -Wl,-R,/usr/local/lib -fstack-protector -L/usr/gnu/lib -m64 '
    libpth=/usr/local/lib /usr/gcc/4.8/lib /usr/gcc/4.8/lib/gcc/i386-pc-solaris2.11/4.8.2/include-fixed /usr/lib /usr/gnu/lib /usr/ccs/lib
    libs=-lpthread -lsocket -lnsl -lgdbm -ldb -ldl -lm -lc
    perllibs=-lpthread -lsocket -lnsl -ldl -lm -lc
    libc=/lib/libc.so
    so=so
    useshrplib=true
    libperl=libperl.so
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='  -R /usr/local/lib/perl5/5.30.1/i86pc-solaris-64/CORE'
    cccdlflags='-fPIC'
    lddlflags=' -shared -m64 -L/usr/local/lib -Wl,-R,22124ORIGIN/../lib -Wl,-R,/usr/local/lib -L/usr/gnu/lib -fstack-protector'

Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under solaris
  Compiled at Feb  1 2020 05:00:35
  @INC:
    /usr/local/lib/perl5/site_perl/5.30.1/i86pc-solaris-64
    /usr/local/lib/perl5/site_perl/5.30.1
    /usr/local/lib/perl5/5.30.1/i86pc-solaris-64
    /usr/local/lib/perl5/5.30.1
```

**Comment by apparluk** [comment]
The message appears on other platforms too.

Nice [video](https://nurmi-labs.github.io/videos.html) for you "The Blit".

I suggest closing.

**Comment by jkeenan** [comment]
The relevant code is found in `Configure`:
```
  170 case "$inksh/$needksh-$avoidksh-" in
  171 true/--)
  172         cat <<EOM
  173 (I see you are using the Korn shell.  Some ksh's blow up on $me,
  174 mainly on older exotic systems.  If yours does, try the Bourne shell instead.)
  175 EOM
  176     ;;
  177 esac
```
I can confirm that if you are using the Korn shell, this `case` is encountered and the string evaluates to `true/--` and the warning is generated.

So the question is:  Why is this `case` encountered when using other shells?

**Comment by jkeenan** [comment]
The attached file (which is a shell script but which github forced me to rename as '.txt' to be able to upload it) may or may not clarify matters.

[ghi-17518.txt](https://github.com/Perl/perl5/files/4176455/ghi-17518.txt)

It is a clone of approximately the first 200 lines of `./Configure` -- just enough to cause the Korn shell warning to be thrown, plus some debugging code.

On OpenBSD-6.6, where I am using `ksh`, the output from this script is:
```
AAA: .:/long/list/of/directories
BBB:
UUU: inksh: true
VVV: needksh: 
WWW: avoidksh: 
XXX: true/--
HHH:
(I see you are using the Korn shell.  Some ksh's blow up on ghi-17518,
mainly on older exotic systems.  If yours does, try the Bourne shell instead.)
YYY: /bin/ksh
ZZZ: </bin/ksh> true/--
```
At line 108, the variable `newsh` is set to `/bin/ksh` -- which means that **the script is presuming that `ksh` is the operative shell until otherwise determined.**

The script gets to this `if` block and the `if` is evaluated as true.
```
if (PATH=.; alias -x) >/dev/null 2>&1; then
    echo "BBB:"
    inksh=true
fi
```
The script therefore enters the `case` HHH and generates the Korn caution.  At line 175 we test to see that the value of `newsh` is an executable file -- and, not surprisingly, on this system `ksh` is determined to be executable.  So the variable `newsh` is not unset and retains that value as displayed in ZZZ.

On FreeBSD-11, where I am using `sh` as shell, and on Linux, where I am using `bash` as shell -- and where I do not have `ksh` installed in either instance --  the output from this script is this:
```
AAA: .:/long/list/of/directories
UUU: inksh: 
VVV: needksh: 
WWW: avoidksh: 
XXX: /--
YYY: /bin/ksh
ZZZ: <> /--
```
Neither the BBB block nor any of the other `if` blocks is entered.  Neither are any of the `case` blocks entered.  At line 175, no executable is found at `/bin/ksh`, so `newsh` is unset.  `./Configure` goes on its merry way.

The key line is 110 in the attachment, equivalent to line 138 in `./Configure`.
```
if (PATH=.; alias -x) >/dev/null 2>&1; then
    echo "BBB:"
    inksh=true
fi
```
I don't understand shell enough to know what's happening in that first line -- but I suspect that on the OP's Solaris system that condition is evaluating to true; the BBB block is being entered and `inksh` is being set to the string `true`; the HHH `case` block is being entered and the Korn caution is generated; and later an executable file is found at `/bin/ksh` so `newsh` is not unset.

Please run the script on various platforms and see what you get.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
Configure experts, please take a look at this ticket:
@Tux @arc @doughera88 

Thank you very much.
Jim Keenan

**Comment by shlomif** [comment]
@jkeenan : 
On mageia linux v8 x86-64, with bash:

```
AAA: .:/home/shlomif/bin:/home/shlomif/apps/perl/modules/bin:/home/shlomif/apps/perl/modules/local/bin:/home/shlomif/apps/neovim/bin:/home/shlomif/apps/fop/fop-20140425:/home/shlomif/apps/vim/bin:/home/shlomif/apps/golang/bin:/home/shlomif/.local/bin:/home/shlomif/.perl6/bin:/home/shlomif/.cargo/bin:/usr/local/bin:/usr/bin:/usr/lib64/qt5/bin:/usr/lib64/qt4/bin:/usr/games:/bin:/usr/local:/etc:/usr/lib:/lib:/sbin:/usr/sbin:/usr/libexec
UUU: inksh: 
VVV: needksh: 
WWW: avoidksh: 
XXX: /--
YYY: /bin/ksh
ZZZ: </bin/ksh> /--
```

with ksh:

```
AAA: .:/home/shlomif/bin:/home/shlomif/apps/perl/modules/bin:/home/shlomif/apps/perl/modules/local/bin:/home/shlomif/apps/neovim/bin:/home/shlomif/apps/fop/fop-20140425:/home/shlomif/apps/vim/bin:/home/shlomif/apps/golang/bin:/home/shlomif/.local/bin:/home/shlomif/.perl6/bin:/home/shlomif/.cargo/bin:/usr/local/bin:/usr/bin:/usr/lib64/qt5/bin:/usr/lib64/qt4/bin:/usr/games:/bin:/usr/local:/etc:/usr/lib:/lib:/sbin:/usr/sbin:/usr/libexec
BBB:
UUU: inksh: true
VVV: needksh: 
WWW: avoidksh: 
XXX: true/--
HHH:
(I see you are using the Korn shell.  Some ksh's blow up on ghi-17518.bash,
mainly on older exotic systems.  If yours does, try the Bourne shell instead.)
YYY: /bin/ksh
ZZZ: </bin/ksh> true/--
```

**Comment by jkeenan** [comment]
On 2/9/20 2:39 AM, Shlomi Fish wrote:
> @jkeenan <https://github.com/jkeenan> :
> On mageia linux v8 x86-64, with bash:
> 
> |AAA: 
> .:/home/shlomif/bin:/home/shlomif/apps/perl/modules/bin:/home/shlomif/apps/perl/modules/local/bin:/home/shlomif/apps/neovim/bin:/home/shlomif/apps/fop/fop-20140425:/home/shlomif/apps/vim/bin:/home/shlomif/apps/golang/bin:/home/shlomif/.local/bin:/home/shlomif/.perl6/bin:/home/shlomif/.cargo/bin:/usr/local/bin:/usr/bin:/usr/lib64/qt5/bin:/usr/lib64/qt4/bin:/usr/games:/bin:/usr/local:/etc:/usr/lib:/lib:/sbin:/usr/sbin:/usr/libexec 
> UUU: inksh: VVV: needksh: WWW: avoidksh: XXX: /-- YYY: /bin/ksh ZZZ: 
> </bin/ksh> /-- |
> 
> with ksh:
> 
> |AAA: 
> .:/home/shlomif/bin:/home/shlomif/apps/perl/modules/bin:/home/shlomif/apps/perl/modules/local/bin:/home/shlomif/apps/neovim/bin:/home/shlomif/apps/fop/fop-20140425:/home/shlomif/apps/vim/bin:/home/shlomif/apps/golang/bin:/home/shlomif/.local/bin:/home/shlomif/.perl6/bin:/home/shlomif/.cargo/bin:/usr/local/bin:/usr/bin:/usr/lib64/qt5/bin:/usr/lib64/qt4/bin:/usr/games:/bin:/usr/local:/etc:/usr/lib:/lib:/sbin:/usr/sbin:/usr/libexec 
> BBB: UUU: inksh: true VVV: needksh: WWW: avoidksh: XXX: true/-- HHH: (I 
> see you are using the Korn shell. Some ksh's blow up on ghi-17518.bash, 
> mainly on older exotic systems. If yours does, try the Bourne shell 
> instead.) YYY: /bin/ksh ZZZ: </bin/ksh> true/-- |
> 

Shlomi, thanks for that data.  Did you change the invocation to 
./Configure between these two calls?

If not, how did you determine the operative shell?

Thank you very much.
Jim Keenan

**Comment by shlomif** [comment]
> Shlomi, thanks for that data. Did you change the invocation to ./Configure between these two calls? > If not, how did you determine the operative shell? Thank you very much. Jim Keenan

@jkeenan : I ran them using `bash ghi-17518.bash |& tee bash.output.txt` and `ksh ghi-17518.bash |& tee ksh.output.txt` from withing my interactive user shell which happens to be zsh.

**Comment by jkeenan** [comment]
On 2/9/20 10:03 AM, Shlomi Fish wrote:
>     Shlomi, thanks for that data. Did you change the invocation to
>     ./Configure between these two calls? > If not, how did you determine
>     the operative shell? Thank you very much. Jim Keenan
> 
> @jkeenan <https://github.com/jkeenan> : I ran them using |bash 
> ghi-17518.bash |& tee bash.output.txt| and |ksh ghi-17518.bash |& tee 
> ksh.output.txt| from withing my interactive user shell which happens to 
> be zsh.
> 

So, in your everyday builds of Perl, is 'zsh' the operative shell?

Thanks.

**Comment by shlomif** [comment]
> So, in your everyday builds of Perl, is 'zsh' the operative shell? Thanks.

@jkeenan : I use zsh as my login shell and as an interactive repl, but I invoke `Configure` using `sh Configure` - see https://github.com/shlomif/shlomif-computer-settings/blob/master/shlomif-settings/build-scripts/build/perl/perl-bleadperl.sh .

Thanks and you're welcome.

**Comment by jkeenan** [comment]
> **Description**
> I'm building the Perl 5.30.1 release tarball on Solaris 11 i86pc. When running `Configure` I see the message:
> 
> ```
> $ ./Configure ...
> 
> (I see you are using the Korn shell.  Some ksh's blow up on Configure,
> mainly on older exotic systems.  If yours does, try the Bourne shell instead.)
> First let's make sure your kit is complete.  Checking...
> ```
> 

If, on this Solaris machine, you say:
```
bash ./Configure ...
```
... do you get the "Korn cautionary" as you do when you simply say:
```
./Configure ...
```
(You could perform this same experiment with the ghi-17518 shell script presented earlier in this thread.)

Thank you very much.
Jim Keenan

**Comment by doughera88** [comment]
On Sat, Feb 08, 2020 at 08:06:25PM -0800, James E Keenan wrote:
> Configure experts, please take a look at this ticket:
> @Tux @arc @doughera88 

I suspect the message is correct.  The first line of Configure is
"! #/bin/sh", and, at least on the Solaris 11 x86 system I have access
to,  /bin/sh is actually a symlink to /bin/amd64/ksh93.  Thus when you
type  ./Configure, you are invoking it via /bin/sh, which is indeed the
Korn shell.  If you want the message to go away, you can type

	bash ./Configure

It is a fair question to ask whether there are still any "older, exotic"
Korn shell systems around that can't run Configure.  The message is
about 25 years old; I haven't been paying enough attention to know
where things stand today.  Certainly the ksh93 shipped with Solaris 11
handles it just fine.

-- 
    Andy Dougherty		doughera@lafayette.edu

**Comment by bingos** [comment]
![image](https://user-images.githubusercontent.com/62011/74179685-dd6b5d00-4c35-11ea-87b2-d1176118b3d7.png)

Just to confirm on my Solaris 11 system /bin/sh is indeed a symlink to ksh93 as @doughera88 has observed.

And the same on derivative OmniOS

![image](https://user-images.githubusercontent.com/62011/74180296-2e2f8580-4c37-11ea-9d3f-1b9c910139e2.png)

And OpenIndiana (Illumos)

![image](https://user-images.githubusercontent.com/62011/74180333-3c7da180-4c37-11ea-851d-4605c99e55e5.png)

**Comment by jkeenan** [comment]
> Just to confirm on my Solaris 11 system /bin/sh is indeed a symlink to ksh93 as @doughera88 has observed.
> 
> And the same on derivative OmniOS
> 
> And OpenIndiana (Illumos)
> 

And on OpenBSD-6.6, we have what appear to be 3 differently named versions of the same shell executable:
```
[openbsd66: ~] $ ls -l /bin/*sh
lrwxr-xr-x  1 root  wheel      19 Nov 22 02:20 /bin/bash -> /usr/local/bin/bash
-r-xr-xr-x  1 root  bin    455760 Oct 12 16:34 /bin/csh
-r-xr-xr-x  3 root  bin    625032 Oct 12 16:34 /bin/ksh
-r-xr-xr-x  3 root  bin    625032 Oct 12 16:34 /bin/rksh
-r-xr-xr-x  3 root  bin    625032 Oct 12 16:34 /bin/sh
```
So, while I would like to hear back from the OP, my inclination -- absent any data on `ksh` on those systems which were "older" and "exotic" even in 1994 -- is to just write some documentation which explains this peculiarity and advises users to say `sh ./Configure` rather than simply `./Configure`.

Thank you very much.
Jim Keenan

**Comment by doughera88** [comment]
On Mon, Feb 10, 2020 at 03:41:41PM -0800, James E Keenan wrote:

> So, while I would like to hear back from the OP, my inclination -- absent any data on `ksh` on those systems which were "older" and "exotic" even in 1994 -- is to just write some documentation which explains this peculiarity and advises users to say `sh ./Configure` rather than simply `./Configure`.

The INSTALL file already recommends sh Configure.  I don't know if
documenting that 'sh' might actually be something else would actually
be of much help.

-- 
    Andy Dougherty		doughera@lafayette.edu

**Comment by jkeenan** [comment]
> On Mon, Feb 10, 2020 at 03:41:41PM -0800, James E Keenan wrote: So, while I would like to hear back from the OP, my inclination -- absent any data on `ksh` on those systems which were "older" and "exotic" even in 1994 -- is to just write some documentation which explains this peculiarity and advises users to say `sh ./Configure` rather than simply `./Configure`.
> The INSTALL file already recommends sh Configure. I don't know if documenting that 'sh' might actually be something else would actually be of much help.
> […](#)
> -- Andy Dougherty doughera@lafayette.edu

I agree.  Closing ticket.
