### ISSUE TITLE
Perl 5.30.1 and failed self tests due to 02core_dst.t

### ISSUE THREAD

**Issue by noloader** [Perl/perl5#17527]
**Description**
I'm building Perl from the 5.30.1 release tarball. On Alpine Linux I'm seeing a self-test failure during `make check`. Alpine uses BusyBox and Musl.

```
Failed 2 tests out of 2446, 99.92% okay.
	../cpan/Time-Piece/t/02core_dst.t
	op/magic.t
```

**Steps to Reproduce**
After building Perl on Alpine and seeing the failure, then in the build directory:

```
$ perl ../cpan/Time-Piece/t/02core_dst.
t
1..56
ok 1
ok 2
ok 3
ok 4
ok 5
ok 6
ok 7
ok 8
ok 9
ok 10
ok 11
ok 12
ok 13
ok 14
ok 15
ok 16
ok 17
ok 18
ok 19
ok 20
ok 21
ok 22
ok 23
ok 24
ok 25
ok 26
ok 27
ok 28
ok 29
ok 30
ok 31
ok 32
ok 33
ok 34
ok 35
ok 36
ok 37
ok 38
ok 39
ok 40
ok 41
ok 42
ok 43
ok 44
ok 45
ok 46
ok 47
ok 48
ok 49
ok 50
ok 51
ok 52 - Epoch output is the same with EDT
not ok 53
#   Failed test at ../cpan/Time-Piece/t/02core_dst.t line 133.
#          got: '-14400'
#     expected: '-18000'
not ok 54
#   Failed test at ../cpan/Time-Piece/t/02core_dst.t line 134.
#          got: '2013-01-09 08:07:11 EDT'
#     expected: '2013-01-09 07:07:11 EST'
not ok 55
#   Failed test at ../cpan/Time-Piece/t/02core_dst.t line 135.
#                   '-0400'
#     doesn't match '(?^:-0500|EST)'
ok 56 - Epoch output is the same with EST
# Looks like you failed 3 tests of 56.
```

**Expected behavior**

**Perl configuration**

```
$ PERL5LIB=lib:$PERL5LIB ./perl -V
Summary of my perl5 (revision 5 version 30 subversion 1) configuration:
   
  Platform:
    osname=linux
    osvers=4.19.80-0-vanilla
    archname=x86_64-linux
    uname='linux alpine3-x64 4.19.80-0-vanilla #1-alpine smp fri oct 18 11:27:53 utc 2019 x86_64 linux '
    config_args='-des -Dprefix=/usr/local -Dlibdir=/usr/local/lib -Dpkgconfig=/usr/local/lib/pkgconfig -Dcc=gcc -Acppflags=-I/usr/local/include -DNDEBUG -Accflags=-g2 -O2 -march=native -fPIC -pthread -Aldflags=-L/usr/local/lib -Wl,-R,'$$ORIGIN/../lib' -Wl,-R,/usr/local/lib -Wl,--enable-new-dtags -Dextras=Text::Template Test::More'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags ='-g2 -O2 -march=native -fPIC -pthread -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-I/usr/local/include -DNDEBUG -g2 -O2 -march=native -fPIC -pthread -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='8.3.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='gcc'
    ldflags =' -L/usr/local/lib -Wl,-R,11928ORIGIN/../lib -Wl,-R,/usr/local/lib -Wl,--enable-new-dtags -fstack-protector-strong'
    libpth=/usr/local/lib /usr/lib /lib/../lib /usr/lib/../lib /lib
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/usr/lib/libc.a
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -Wl,-R,11928ORIGIN/../lib -Wl,-R,/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Feb  4 2020 10:32:16
  %ENV:
    PERL5LIB="lib:"
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/5.30.1/x86_64-linux
    /usr/local/lib/perl5/site_perl/5.30.1
    /usr/local/lib/perl5/5.30.1/x86_64-linux
    /usr/local/lib/perl5/5.30.1
```

----

I found one other report that mentions `02core_dst.t`: [Encode CPAN version 2.78 broke g++ build on FreeBSD-10.3](https://github.com/Perl/perl5/issues/15983). I am not sure if it is related.

----

Alpine details:

```
$ cat /etc/alpine-release
3.10.4

$ uname -a
Linux alpine3-x64 4.19.80-0-vanilla #1-Alpine SMP Fri Oct 18 11:27:53 UTC 2019 x86_64 Linux
```

**Comment by jkeenan** [comment]
Time::Piece is maintained [upstream on CPAN](https://metacpan.org/pod/Time::Piece).  It appears this problem has already been reported in that distro's bug tracker:  [RTC 128240](https://rt.cpan.org/Ticket/Display.html?id=128240).  You should probably follow up with the maintainer in that ticket.

Thank you very much.
Jim Keenan

**Comment by smith153** [comment]
Tests in 02core_dst.t have proven to be fragile (as well as redundant). In the next release they will be moved into xt/ (or something similar)

**Comment by jkeenan** [comment]
@smith153 released Time-Piece version 1.34 to CPAN and I merged it into Perl 5 blead on March 10.  I haven't observed any smoke-test failures since.  I will take this ticket for the purpose of further monitoring and close it in 7 days unless we get an objection.

Thank you very much.
Jim Keenan

**Comment by smith153** [comment]
I've released 1.3401. In my opinion, this would be a better candidate for blead. It mostly just adds more safeguards and exempts a few test files unless $ENV{AUTOMATED_TESTING} is present. Mostly done to ensure a failing Time-Piece test won't error out a perl install from source. https://github.com/Dual-Life/Time-Piece/compare/1.34...1.3401

**Comment by jkeenan** [comment]
> I've released 1.3401. In my opinion, this would be a better candidate for blead. It mostly just adds more safeguards and exempts a few test files unless $ENV{AUTOMATED_TESTING} is present. Mostly done to ensure a failing Time-Piece test won't error out a perl install from source. [Dual-Life/Time-Piece@1.34...1.3401](https://github.com/Dual-Life/Time-Piece/compare/1.34...1.3401)

Thank you for your continuing attention to Time-Piece.  However, with the release of perl-5.31.10 last month, we're now past the point where committers have _carte blanche_ to merge into blead changes in upstream distributions.  So this will have to await the pumpking's judgment.  @xsawyerx 

Speaking for myself, I'm reluctant to see a CPAN distribution with a `$VERSION` -- in this case 1.3401 -- which is, by convention, a "development" release.  In other words (and again, speaking just for myself), I'd only want this to go into 5.32 if it were version 1.35.

If this doesn't go into 5.32.0, it can certainly go into 5.33.1.

Thank you very much.
Jim Keenan

**Comment by Grinnz** [comment]
1.3401 is not a development release version by any convention I know. A minor revision if anything.

**Comment by xsawyerx** [comment]
I'm giving this an exception to merge.

**Comment by jkeenan** [comment]
> I'm giving this an exception to merge.

Since @xsawyerx has okayed this synch into blead, I'll take care of it later today.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> > I'm giving this an exception to merge.
> 
> Since @xsawyerx has okayed this synch into blead, I'll take care of it later today.
> 
> Thank you very much.
> Jim Keenan

Synched into blead with commit a5ebaea1256879b6be6776f2cf8be0a2f3ae2579

Thank you very much.
Jim Keenan

**Comment by xsawyerx** [comment]
I'm closing this ticket. Thanks, everyone, for the work.
