### ISSUE TITLE
[doc] piconv: say in *some* implementations of iconv

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#17520]
piconv man page says:

       -f,--from from_encoding
           Specifies the encoding you are converting from.  Unlike iconv, this option can be omitted.  In such
           cases, the current locale is used.

       -t,--to to_encoding
           Specifies the encoding you are converting to.  Unlike iconv, this option can be omitted.  In such
           cases, the current locale is used.

But in most / some / current ? real iconv it can also be omitted. So say "in **some** implementations of iconv...'

           Therefore, when both -f and -t are omitted, piconv just acts like cat.

Well it actually just prints a usage message.

**Comment by richardleach** [comment]
_piconv_ is pulled in from Encode (https://metacpan.org/dist/Encode) which is a CPAN-first module. 

It already has some open tickets regarding the behaviour when both -f and -t are omitted, e.g.
* https://rt.cpan.org/Ticket/Display.html?id=146804
* https://rt.cpan.org/Ticket/Display.html?id=146805

@jidanni - If you want to raise any tickets directly against Encode regarding _piconv_ documentation of `iconv` behaviour, https://rt.cpan.org/Public/Dist/Display.html?Name=Encode or https://github.com/dankogai/p5-encode are the places to do it.
