### ISSUE TITLE
Enabling PGO for Perl could cause segfault error on some modules when running "make test_harness"

### ISSUE THREAD

**Issue by dapeng-mi** [Perl/perl5#17559]
Module:

**Description**

After enabling PGO for perl 5.30.1, we found there are some segmentation faults when running "make test_harness".

Here are some examples.

sh: line 1: 60085 Segmentation fault      (core dumped) /builddir/build/BUILD/perl-5.30.1/perl "-I../lib" "-I." "tmp59383A" 2>&1
Failed test 121 - threads while in-place editing at ./test.pl line 1062
     got ""
expected "ok"
PROG:

		use threads;
		use strict;
		@ARGV = ("tmpinplace/foo");
		$^I = "";
		while (<>) {
		  threads->create(sub { })->join;
		  print "yy\n";
		}
		print "ok\n";
STATUS: 35584
Failed test 123 - file successfully saved after chdir at run/switches.t line 511
     got "xx\n"
expected "yy\n"
Failed test 129 - no extra files at run/switches.t line 593
     got "1"
expected "0"
Found XXEhNAQy, expected none

sh: line 1: 75257 Segmentation fault      (core dumped) /builddir/build/BUILD/perl-5.30.1/perl "-I../lib" "-I." "tmp75249A" 2>&1
sh: line 1: 75274 Segmentation fault      (core dumped) /builddir/build/BUILD/perl-5.30.1/perl "-I../lib" "-I." "tmp75249A" 2>&1
Failed test 2 - Verify there were no failures with simultaneous running threads at ./test.pl line 1062
     got ""
expected "1"
PROG:

        use threads;
        use strict;
        use warnings;
        use POSIX qw(locale_h);

        my $result = 1;

        my @threads = map +threads->create(sub {
            sleep 0.1;
            for (1..5_000) {
                my $s;
                my $in = 4.2; # avoid any constant folding bugs

                if ('agr_PE.UTF-8') {
                    setlocale(&LC_NUMERIC, 'agr_PE.UTF-8');
                    use locale;
                    $s = sprintf('%g', $in);
                    return 0 if ($s ne '4,2');
                }

                setlocale(&LC_NUMERIC, 'C');
                $s = sprintf('%g', $in);
                return 0 if ($s ne '4.2');
            }

            return 1;

        }), (0..3);
        $result &= $_->join for splice @threads;
        print $result
STATUS: 35584
../lib/locale_threads.t ............................................
Failed 1/2 subtests

**Steps to Reproduce**

We use rpmbuild to build the perl package. Here are the building commands from SPEC file.

		%build
		export PERL5LIB=$(find ${_builddir} -type f -name strict.pm -execdir pwd \; | head -1)
		export PERL_MM_USE_DEFAULT=1
		export PERL_CANARY_STABILITY_NOPROMPT=1
		export http_proxy=http://127.0.0.1:9/
		export https_proxy=http://127.0.0.1:9/
		export no_proxy=localhost,127.0.0.1,0.0.0.0
		export LANG=C.UTF-8
		export SOURCE_DATE_EPOCH=1579069864
		export GCC_IGNORE_WERROR=1
		export AR=gcc-ar
		export RANLIB=gcc-ranlib
		export NM=gcc-nm
		export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
		export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
		export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
		export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
		export CFLAGS_GENERATE="$CFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
		export FCFLAGS_GENERATE="$FCFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
		export FFLAGS_GENERATE="$FFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
		export CXXFLAGS_GENERATE="$CXXFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
		export LDFLAGS_GENERATE="$LDFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
		export CFLAGS_USE="$CFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
		export FCFLAGS_USE="$FCFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
		export FFLAGS_USE="$FFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
		export CXXFLAGS_USE="$CXXFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
		export LDFLAGS_USE="$LDFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
		CFLAGS="${CFLAGS_GENERATE}" CXXFLAGS="${CXXFLAGS_GENERATE}" FFLAGS="${FFLAGS_GENERATE}" FCFLAGS="${FCFLAGS_GENERATE}" LDFLAGS="${LDFLAGS_GENERATE}" %configure --disable-static -d \
		-e \
		-r \
		-Dprefix=/usr \
		-Dsiteprefix=/usr/local \
		-Dvendorprefix=/usr \
		-Dinstallman1dir='/usr/share/man/man1' \
		-Dinstallman3dir='/usr/share/man/man3' \
		-Dman1dir='/usr/share/man/man1' \
		-Dman3dir='/usr/share/man/man3' \
		-Dusethreads \
		-Duseshrplib \
		-Adefine:d_procselfexe \
		-Adefine:procselfexe='"/proc/self/exe"' \
		-Adefine:optimize="-O3 -ffunction-sections -fno-semantic-interposition -fopt-info-vec -ffat-lto-objects -flto=4 -fprofile-dir=/var/tmp/pgo " \
		-Aappend:optimize="$(echo $LDFLAGS | grep -q fprofile.generate && echo "-fprofile-generate" || echo "-fprofile-use -fprofile-correction")" \
		-Adefine:ccflags="$CFLAGS" \
		-Adefine:ldflags="$LDFLAGS" \
		-Adefine:lddflags="$LDFLAGS" \
		-U d_off64_t
		make  %{?_smp_mflags}

		make test_pgo
		make clean
		CFLAGS="${CFLAGS_USE}" CXXFLAGS="${CXXFLAGS_USE}" FFLAGS="${FFLAGS_USE}" FCFLAGS="${FCFLAGS_USE}" LDFLAGS="${LDFLAGS_USE}" %configure --disable-static -d \
		-e \
		-r \
		-Dprefix=/usr \
		-Dsiteprefix=/usr/local \
		-Dvendorprefix=/usr \
		-Dinstallman1dir='/usr/share/man/man1' \
		-Dinstallman3dir='/usr/share/man/man3' \
		-Dman1dir='/usr/share/man/man1' \
		-Dman3dir='/usr/share/man/man3' \
		-Dusethreads \
		-Duseshrplib \
		-Adefine:d_procselfexe \
		-Adefine:procselfexe='"/proc/self/exe"' \
		-Adefine:optimize="-O3 -ffunction-sections -fno-semantic-interposition -fopt-info-vec -ffat-lto-objects -flto=4 -fprofile-dir=/var/tmp/pgo " \
		-Aappend:optimize="$(echo $LDFLAGS | grep -q fprofile.generate && echo "-fprofile-generate" || echo "-fprofile-use -fprofile-correction")" \
		-Adefine:ccflags="$CFLAGS" \
		-Adefine:ldflags="$LDFLAGS" \
		-Adefine:lddflags="$LDFLAGS" \
		-U d_off64_t
		make  %{?_smp_mflags}

In above commands, the command "make test_pgo" would run perl benchmark and generate profiling files.

Here are the check commands from SPEC file.

		%check
		export LANG=C.UTF-8
		export http_proxy=http://127.0.0.1:9/
		export https_proxy=http://127.0.0.1:9/
		export no_proxy=localhost,127.0.0.1,0.0.0.0
		JOBS=1
		JOBS_ARG="%{?_smp_mflags}"
		if test -n "$JOBS_ARG"; then
		  JOBS="${JOBS_ARG#-j}"
		fi
		LC_ALL=C TEST_JOBS=$JOBS make test_harness || :

A workaround to fix these segmentation faults is to **replace "make clean" with "make distclean"** in the above building commands. I have no idea what exactly happens, but per my guess, "make clean" doesn't clean the intermediate configure files completely, it leads to some profile-generating building options are passed to the profile-using building stage, this would cause issues. 

Per my experience, it's good enough to use "make clean" between the two PGO building stages for most of packages. I'm not sure if this is a real issue. Please suggest.

**Expected behavior**

**Perl configuration**

```
# perl -V output goes here
```
Summary of my perl5 (revision 5 version 30 subversion 1) configuration:

  Platform:
    osname=linux
    osvers=5.4.11-890.native
    archname=x86_64-linux-thread-multi
    uname='linux 9431b54ea88e4a96a41ebf684eb3955e 5.4.11-890.native #1 smp sun jan 12 04:02:17 pst 2020 x86_64 gnulinux '
    config_args='--build=x86_64-generic-linux-gnu --host=x86_64-generic-linux-gnu --target=x86_64-clr-linux-gnu --program-prefix= --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/bin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/usr/com --mandir=/usr/share/man --infodir=/usr/share/info --disable-static -d -e -r -Dprefix=/usr -Dsiteprefix=/usr/local -Dvendorprefix=/usr -Dinstallman1dir=/usr/share/man/man1 -Dinstallman3dir=/usr/share/man/man3 -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/share/man/man3 -Dusethreads -Duseshrplib -Adefine:d_procselfexe -Adefine:procselfexe="/proc/self/exe" -Adefine:optimize=-O3 -ffunction-sections -fno-semantic-interposition -fopt-info-vec -ffat-lto-objects -flto=4 -fprofile-dir=/var/tmp/pgo  -Aappend:optimize=-fprofile-use -fprofile-correction -Adefine:ccflags=-O2 -g -feliminate-unused-debug-types -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -ftree-vectorize -ftree-slp-vectorize -Wl,--enable-new-dtags -fcf-protection=return -Wl,--build-id=sha1 -Wa,-mbranches-within-32B-boundaries -m64 -march=westmere -mtune=haswell -fasynchronous-unwind-tables -fno-omit-frame-pointer -Wp,-D_REENTRANT -O3 -ffat-lto-objects -flto=4  -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction  -fPIC -Adefine:ldflags= -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction  -Wl,--build-id=sha1 -Adefine:lddflags= -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction  -Wl,--build-id=sha1 -U d_off64_t'
    hint=previous
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-O2 -g -feliminate-unused-debug-types -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -ftree-vectorize -ftree-slp-vectorize -Wl,--enable-new-dtags -fcf-protection=return -Wl,--build-id=sha1 -Wa,-mbranches-within-32B-boundaries -m64 -march=westmere -mtune=haswell -fasynchronous-unwind-tables -fno-omit-frame-pointer -Wp,-D_REENTRANT -O3 -ffat-lto-objects -flto=4 -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction -fPIC -fwrapv'
    optimize='-O3 -ffunction-sections -fno-semantic-interposition -fopt-info-vec -ffat-lto-objects -flto=4 -fprofile-dir=/var/tmp/pgo -fprofile-use -fprofile-correction'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -O2 -g -feliminate-unused-debug-types -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code -Wno-error -ftree-vectorize -ftree-slp-vectorize -Wl,--enable-new-dtags -fcf-protection=return -Wl,--build-id=sha1 -Wa,-mbranches-within-32B-boundaries -m64 -march=westmere -mtune=haswell -fasynchronous-unwind-tables -fno-omit-frame-pointer -Wp,-D_REENTRANT -O3 -ffat-lto-objects -flto=4 -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic -fPIC -fwrapv -fno-strict-aliasing -fstack-protector-strong'
    ccversion=''
    gccversion='9.2.1 20200211 gcc_9_2_0_release-597-gf6e9ae4da8'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction -Wl,--build-id=sha1 -fstack-protector'
    libpth=/usr/lib64/gcc/x86_64-generic-linux/9/include-fixed /usr/lib /lib/../lib64 /usr/lib/../lib64 /lib /lib64 /usr/lib64 /usr/lib64/gcc/x86_64-generic-linux/9/include-fixed /usr/lib
    libs=-lpthread -lnsl -lgdbm -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.30.so
    so=so
    useshrplib=true
    libperl=libperl.so
    gnulibc_version='2.30'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30.1/x86_64-linux-thread-multi/CORE'
    cccdlflags='-fPIC'
    lddlflags='-shared -O3 -ffunction-sections -fno-semantic-interposition -fopt-info-vec -ffat-lto-objects -flto=4 -fprofile-dir=/var/tmp/pgo -fprofile-generate -fstack-protector-strong'

Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Jan 15 2020 06:31:04
  @INC:
    /usr/local/lib/perl5/site_perl/5.30.1/x86_64-linux-thread-multi
    /usr/local/lib/perl5/site_perl/5.30.1
    /usr/lib/perl5/vendor_perl/5.30.1/x86_64-linux-thread-multi
    /usr/lib/perl5/vendor_perl/5.30.1
    /usr/lib/perl5/5.30.1/x86_64-linux-thread-multi
    /usr/lib/perl5/5.30.1

**Comment by jkeenan** [comment]
On 2/12/20 2:27 AM, dapeng-mi wrote:


> **Description**
> 
> After enabling PGO for perl 5.30.1, we found there are some segmentation faults when running "make test_harness".
> 
> Here are some examples.
> 
> sh: line 1: 60085 Segmentation fault (core dumped) /builddir/build/BUILD/perl-5.30.1/perl "-I../lib" "-I." "tmp59383A" 2>&1
> Failed test 121 - threads while in-place editing at ./test.pl line 1062
> got ""
> expected "ok"
> PROG:
> 
> ```
> 	use threads;
> 	use strict;
> 	@ARGV = ("tmpinplace/foo");
> 	$^I = "";
> 	while (<>) {
> 	  threads->create(sub { })->join;
> 	  print "yy\n";
> 	}
> 	print "ok\n";
> ```
> 
> STATUS: 35584
> Failed test 123 - file successfully saved after chdir at run/switches.t line 511
> got "xx\n"
> expected "yy\n"
> Failed test 129 - no extra files at run/switches.t line 593
> got "1"
> expected "0"
> Found XXEhNAQy, expected none
> 
> sh: line 1: 75257 Segmentation fault (core dumped) /builddir/build/BUILD/perl-5.30.1/perl "-I../lib" "-I." "tmp75249A" 2>&1
> sh: line 1: 75274 Segmentation fault (core dumped) /builddir/build/BUILD/perl-5.30.1/perl "-I../lib" "-I." "tmp75249A" 2>&1
> Failed test 2 - Verify there were no failures with simultaneous running threads at ./test.pl line 1062
> got ""
> expected "1"
> PROG:
> 
> ```
>     use threads;
>     use strict;
>     use warnings;
>     use POSIX qw(locale_h);
> 
>     my $result = 1;
> 
>     my @threads = map +threads->create(sub {
>         sleep 0.1;
>         for (1..5_000) {
>             my $s;
>             my $in = 4.2; # avoid any constant folding bugs
> 
>             if ('agr_PE.UTF-8') {
>                 setlocale(&LC_NUMERIC, 'agr_PE.UTF-8');
>                 use locale;
>                 $s = sprintf('%g', $in);
>                 return 0 if ($s ne '4,2');
>             }
> 
>             setlocale(&LC_NUMERIC, 'C');
>             $s = sprintf('%g', $in);
>             return 0 if ($s ne '4.2');
>         }
> 
>         return 1;
> 
>     }), (0..3);
>     $result &= $_->join for splice @threads;
>     print $result
> ```
> 
> STATUS: 35584
> ../lib/locale_threads.t ............................................
> Failed 1/2 subtests
> 

To the best of my knowledge, this is the first report we've ever had where someone attempts to build perl under PGO.  So we're in uncharted waters here and we will have to ask some very basic questions.

1. Is the "PGO" you're referring to this?  https://en.wikipedia.org/wiki/Profile-guided_optimization

2. Have you tried to build perl with PGO under any previous versions of Perl 5?  If so, how did you configure perl (arguments to sh ./Configure) to get that result?


> **Steps to Reproduce**
> 
> We use rpmbuild to build the perl package. Here are the building commands from SPEC file.

3. Are you in a position to say who "We" is here?  Can you describe the purpose for which you are building this customized perl?

[snip]

> 
> Summary of my perl5 (revision 5 version 30 subversion 1) configuration:
> 
> Platform:
> osname=linux
> osvers=5.4.11-890.native
> archname=x86_64-linux-thread-multi
> uname='linux 9431b54ea88e4a96a41ebf684eb3955e 5.4.11-890.native #1 smp sun jan 12 04:02:17 pst 2020 x86_64 gnulinux '

[Line below manually broken solely for readability}
```
config_args='--build=x86_64-generic-linux-gnu --host=x86_64-generic-linux-gnu 
--target=x86_64-clr-linux-gnu --program-prefix= --prefix=/usr --exec-prefix=/usr 
--bindir=/usr/bin --sbindir=/usr/bin --sysconfdir=/etc --datadir=/usr/share 
--includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec 
--localstatedir=/var --sharedstatedir=/usr/com --mandir=/usr/share/man 
--infodir=/usr/share/info --disable-static -d -e -r -Dprefix=/usr 
-Dsiteprefix=/usr/local -Dvendorprefix=/usr -Dinstallman1dir=/usr/share/man/man1 
-Dinstallman3dir=/usr/share/man/man3 -Dman1dir=/usr/share/man/man1 
-Dman3dir=/usr/share/man/man3 -Dusethreads -Duseshrplib -Adefine:d_procselfexe 
-Adefine:procselfexe="/proc/self/exe" -Adefine:optimize=-O3 -ffunction-sections 
-fno-semantic-interposition -fopt-info-vec -ffat-lto-objects -flto=4 
-fprofile-dir=/var/tmp/pgo -Aappend:optimize=-fprofile-use -fprofile-correction 
-Adefine:ccflags=-O2 -g -feliminate-unused-debug-types -pipe -Wall 
-Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 
-Wformat -Wformat-security -Wl,-z,now,-z,relro,-z,max-page-size=0x1000,-z,separate-code 
-Wno-error -ftree-vectorize -ftree-slp-vectorize -Wl,--enable-new-dtags 
-fcf-protection=return -Wl,--build-id=sha1 -Wa,-mbranches-within-32B-boundaries 
-m64 -march=westmere -mtune=haswell -fasynchronous-unwind-tables 
-fno-omit-frame-pointer -Wp,-D_REENTRANT -O3 -ffat-lto-objects -flto=4 
-fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction -fPIC 
-Adefine:ldflags= -fprofile-use -fprofile-dir=/var/tmp/pgo 
-fprofile-correction -Wl,--build-id=sha1 -Adefine:lddflags= 
-fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction 
-Wl,--build-id=sha1 -U d_off64_t'
```
4. It's going to be very difficult for us (or anyone) to deal with this forest of configuration switches.  Starting from:
```
sh ./Configure -des -Dusedevel
```
... can you compose the smallest possible set of config_args that reproduces the problem?

[snip]

> gccversion='9.2.1 20200211 gcc_9_2_0_release-597-gf6e9ae4da8'

5.  Have you observed this problem with (a) any earlier version of gcc; or (b) any other C-compiler, e.g., clang?

**Comment by doughera88** [comment]
> A workaround to fix these segmentation faults is to **replace "make clean" with "make distclean"** in the above building commands. I have no idea what exactly happens, but per my guess, "make clean" doesn't clean the intermediate configure files completely, it leads to some profile-generating building options are passed to the profile-using building stage, this would cause issues.

Correct.  As is documented in the INSTALL file, "make distclean" also removes the old config.sh and Policy.sh files.  INSTALL then goes on to recommend 

> If you are upgrading from a previous version of perl, or if you
change systems or compilers or make other significant changes, or if
you are experiencing difficulties building perl, you should not reuse
your old config.sh.

I don't know what "PGO" is, but it's possible that some of those additional compiler flags are different enough that other stuff in config.sh ends up changing too.  To be sure, you'd have to save the intermediate config.sh files and run diff on them.

But more simply, since you are changing a bunch of compiler and linker flags, it makes sense to start from a clean slate, which is what "make distclean" is supposed to do.  I recommend closing this issue.

**Comment by dapeng-mi** [comment]
@jkeenan , here are the answers for your questions.
1. Yes, "PGO" is profile-guided optimization.
2. I tried to build perl 5.28.2 with PGO and watched same issue. we used same configuration options to build these two perl versions. I would show the detailed configuration options later.
3. I want to improve perl performance and look at whether PGO would help to improve perl performance for perl benchmark.
4. Per my experiments, the issue is related with PGO compiling and linking options. If I remove the PGO compiling and linking options, the issue would disappear.

PGO does twice buildings. The only difference between the two buildings are the PGO compiling and linking options. The first building uses the profile-generating compiling and linking options (-fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic), thus the generated binary can generate profiling files. The second building uses the profile-using comping and linking options (-fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction), thus GCC knows to use the generated profiling files to optimize the finial binary.

**Compiling and linking flags:**
	export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
	export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
	export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
	export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
	export CFLAGS_GENERATE="$CFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
	export FCFLAGS_GENERATE="$FCFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
	export FFLAGS_GENERATE="$FFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
	export CXXFLAGS_GENERATE="$CXXFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
	export LDFLAGS_GENERATE="$LDFLAGS -fprofile-generate -fprofile-dir=/var/tmp/pgo -fprofile-update=atomic "
	export CFLAGS_USE="$CFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
	export FCFLAGS_USE="$FCFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
	export FFLAGS_USE="$FFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
	export CXXFLAGS_USE="$CXXFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "
	export LDFLAGS_USE="$LDFLAGS -fprofile-use -fprofile-dir=/var/tmp/pgo -fprofile-correction "


**The configure arguments in first building:**
CFLAGS="${CFLAGS_GENERATE}" CXXFLAGS="${CXXFLAGS_GENERATE}" FFLAGS="${FFLAGS_GENERATE}" FCFLAGS="${FCFLAGS_GENERATE}" LDFLAGS="${LDFLAGS_GENERATE}" ./Configure --disable-static -d \
	-e \
	-r \
	-Dprefix=/usr \
	-Dsiteprefix=/usr/local \
	-Dvendorprefix=/usr \
	-Dinstallman1dir='/usr/share/man/man1' \
	-Dinstallman3dir='/usr/share/man/man3' \
	-Dman1dir='/usr/share/man/man1' \
	-Dman3dir='/usr/share/man/man3' \
	-Dusethreads \
	-Duseshrplib \
	-Adefine:d_procselfexe \
	-Adefine:procselfexe='"/proc/self/exe"' \
	-Adefine:optimize="-O3 -ffunction-sections -fno-semantic-interposition -fopt-info-vec -ffat-lto-objects -flto=4 -fprofile-dir=/var/tmp/pgo " \
	-Aappend:optimize="$(echo $LDFLAGS | grep -q fprofile.generate && echo "-fprofile-generate" || echo "-fprofile-use -fprofile-correction")" \
	-Adefine:ccflags="$CFLAGS" \
	-Adefine:ldflags="$LDFLAGS" \
	-Adefine:lddflags="$LDFLAGS" \
	-U d_off64_t

**The configure arguments in second building:**
CFLAGS="${CFLAGS_USE}" CXXFLAGS="${CXXFLAGS_USE}" FFLAGS="${FFLAGS_USE}" FCFLAGS="${FCFLAGS_USE}" LDFLAGS="${LDFLAGS_USE}" ./Configure --disable-static -d \
	-e \
	-r \
	-Dprefix=/usr \
	-Dsiteprefix=/usr/local \
	-Dvendorprefix=/usr \
	-Dinstallman1dir='/usr/share/man/man1' \
	-Dinstallman3dir='/usr/share/man/man3' \
	-Dman1dir='/usr/share/man/man1' \
	-Dman3dir='/usr/share/man/man3' \
	-Dusethreads \
	-Duseshrplib \
	-Adefine:d_procselfexe \
	-Adefine:procselfexe='"/proc/self/exe"' \
	-Adefine:optimize="-O3 -ffunction-sections -fno-semantic-interposition -fopt-info-vec -ffat-lto-objects -flto=4 -fprofile-dir=/var/tmp/pgo " \
	-Aappend:optimize="$(echo $LDFLAGS | grep -q fprofile.generate && echo "-fprofile-generate" || echo "-fprofile-use -fprofile-correction")" \
	-Adefine:ccflags="$CFLAGS" \
	-Adefine:ldflags="$LDFLAGS" \
	-Adefine:lddflags="$LDFLAGS" \
	-U d_off64_t

5.  No, I just tried GCC 9.2.

**Comment by jkeenan** [comment]
When I define and export the various environmental variables you list, then attempt to configure with `--disable-static`, `./Configure` quickly dies.
```
$ CFLAGS="${CFLAGS_GENERATE}" CXXFLAGS="${CXXFLAGS_GENERATE}" FFLAGS="${FFLAGS_GENERATE}" FCFLAGS="${FCFLAGS_GENERATE}" LDFLAGS="${LDFLAGS_GENERATE}" sh ./Configure --disable-static -des -Dusedevel
Configure: unknown option --disable-static
Usage: Configure [-dehrsEKOSV] [-f config.sh] [-D symbol] [-D symbol=value]
                 [-U symbol] [-U symbol=] [-A command:symbol...]
... # balance of Configure's help message
```
AFAICT, `--disable-static` is not a valid switch for our configuration program.  That string does not occur in the Perl 5 repository.  So I don't see how you are getting through configuration.

Thank you very much.
Jim Keenan

**Comment by dapeng-mi** [comment]
@jkeenan Sorry, I just realized that argument "--disable-static" only works for mock/rpmbuild environment. 

I write a script to build perl with PGO from Linux system, but the result looks a little different with form mock/rpm build environment. The perl binary can be built successfully, but when I run command "make test_harness", the test process hangs and show the following messages, thus I have no method to reproduce the segement fault issue.

../lib/DBM_Filter/t/null.t ......................................... ok
../lib/DBM_Filter/t/utf8.t ......................................... ok
../lib/DirHandle.t ................................................. ok
../lib/dumpvar.t ................................................... ok
../lib/English.t ................................................... ok
../lib/diagnostics.t ............................................... ok
===(  544718;117  225/?  21923/?   864/3886  281/?    6/213  525... )===cc1: error: too many filenames given.  Type cc1 --help for usage

Do you have some ideas on this?  Thanks.

Attach the building script and patches here.

[perl-pgo-build.zip](https://github.com/Perl/perl5/files/4203292/perl-pgo-build.zip)

**Comment by doughera88** [comment]
On Thu, Feb 13, 2020 at 11:33:22PM -0800, dapeng-mi wrote:
> @jkeenan Sorry, I just realized that argument "--disable-static" only works for mock/rpmbuild environment. 
> 
> I write a script to build perl with PGO from Linux system, but the result looks a little different with form mock/rpm build environment. The perl binary can be built successfully, but when I run command "make test_harness", the test process hangs and show the following messages, thus I have no method to reproduce the segement fault issue.
> 
> ../lib/DBM_Filter/t/null.t ......................................... ok
> ../lib/DBM_Filter/t/utf8.t ......................................... ok
> ../lib/DirHandle.t ................................................. ok
> ../lib/dumpvar.t ................................................... ok
> ../lib/English.t ................................................... ok
> ../lib/diagnostics.t ............................................... ok
> ===(  544718;117  225/?  21923/?   864/3886  281/?    6/213  525... )===cc1: error: too many filenames given.  Type cc1 --help for usage
> 
> Do you have some ideas on this?  Thanks.

You'd have to look earlier in the output to find what the actual error was.  
I can't guess from this.

But to reiterate what I wrote earlier, since you are changing a bunch of
compiler and linker flags, it makes sense to start from a clean slate,
which is what "make distclean" is supposed to do.  Run "make distclean"
between your two builds, not a plain "make clean".

Yes, you can re-use an old config.sh, but in your case, you are not
just re-using it.  You are re-using it, but then *overriding* it with
some of those -Adefine commands.  On the first pass, Configure may have
added some flags, but on the second pass you are throwing them away,
while still re-using some of the Configure results from the first pass.
The net result is that your second build is likely in an inconsistent
state.  To check this out in detail, run your first build, copy the
config.sh file somewhere safe, run the second build, and then compare
the old and new config.sh files.  I expect you will find they differ
in significant ways.  

To fix the problem, the simplest thing is to run 'make distclean'
between the two builds.  Or, you could run something like this:

    make clean
    (run a script to change the very few flags you want to change in config.sh)
    sh Configure -S
    make depend
    make

Hope that helps,

-- 
    Andy Dougherty		doughera@lafayette.edu

**Comment by dapeng-mi** [comment]
@doughera88 Thanks a lot for your comments. What your said makes sense for me. Since you think this is not a real issue. I would close this bug.
