### ISSUE TITLE
Time Off Balances displaying incorrectly 

### ISSUE THREAD

**Issue by suvishwa** [Perl/perl5#17560]
Hi Team,

This is regarding the issue reported as the adjustments made does not show in blue as per the key shown in HRC4E.

We checked in our lower instance HRDV2 , the adjustments are displaying correctly (blue color) but in QA & production it is still showing still in Grey.
[screenshot_of_holiday.docx](https://github.com/Perl/perl5/files/4192193/screenshot_of_holiday.docx)

The HRDV2 has the latest patch. And we found in the latest patch notes (i.e, 'Release notes for January 2020 (5.11.0)') there is one bug fix applied
as 'Icons are shown in grey by default instead of the theme's positive color- #1602'

Please see screenshot of view from HRC4E>Personal Time Off in both HRDV2 and PROD.

Could you please provide the hot-fix for the same.

Thanks

**Comment by jkeenan** [comment]
Off topic.

**Comment by eserte** [comment]
Worse, this is either a virus or spam. Can this be completely deleted, including the attached doc?

**Comment by toddr** [comment]
I will delete the issue unless someone objects.

**Comment by toddr** [comment]
Actually I reported this issue to github and blocked the user.

**Comment by suvishwa** [comment]
Hi All,

sorry, by mistake we had raised this GIT request under different url (instead of 'https://github.com/ApplaudSolutions/ELC-MSS/issues/').

I apologize for the inconvenience caused.
I appreciate your understanding in this regard.

Thanks & Regards,
Sushmitha
