### ISSUE TITLE
5.31.9 more t/re/reg_mesg.t failures on 32-bit Windows

### ISSUE THREAD

**Issue by sisyphus** [Perl/perl5#17574]
Module:

**Description**

t/re/reg_mesg.t fails some tests on 32-bit builds of perl-5.31.9 (released a couple of days ago), but not 64-bit builds.
These seem different to #15450 so I'm raising it as a separate issue.
Perl was built using a 32-bit, mingw-w64 port of gcc-8.3.0.

**Steps to Reproduce**

Run 'make test'.
The "Test Summary Report" provided at the end of 'make test' contains:

re/reg_mesg.t (Wstat: 0 Tests: 3146 Failed: 8)
Failed tests:  500, 503, 506, 509, 1313, 1316, 1319, 1322

All of those tests fail in exactly the same way:

\# Have: 'Use of \'\\P \' is not allowed in Unicode property wildcard subpatterns {#} m/{#}/'
\# Want: 'Use of \'\\PS\' is not allowed in Unicode property wildcard subpatterns {#} m/[\\PS{#}]/'

I haven't tested any builds with ivsize == 4.
The perl configuration given below has nvsize == 12 (long double). It's the same issue when nvsize ==  8 (double).

**Expected behavior**

**Perl configuration**

```
Summary of my perl5 (revision 5 version 31 subversion 9) configuration:
   
  Platform:
    osname=MSWin32
    osvers=6.1.7601
    archname=MSWin32-x86-multi-thread-64int-ld
    uname=''
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=define
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags =' -DWIN32 -fdiagnostics-color=never -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -D__USE_MINGW_ANSI_STDIO -fwrapv -fno-strict-aliasing -mms-bitfields'
    optimize='-s -O2'
    cppflags='-DWIN32'
    ccversion=''
    gccversion='8.3.0'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=4
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=12
    longdblkind=3
    ivtype='long long'
    ivsize=8
    nvtype='long double'
    nvsize=12
    Off_t='long long'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags ='-s -L"C:\_32\blead-5.31.9-ld\lib\MSWin32-x86-multi-thread-64int-ld\CORE" -L"C:\_32\gcc-straw-830\mingw32\lib"'
    libpth=C:\_32\gcc-straw-830\mingw32\lib C:\_32\gcc-straw-830\mingw32\i686-w64-mingw32\lib C:\_32\msys_830\1.0\local\lib C:\_32\gcc-straw-830\mingw32\lib\gcc\i686-w64-mingw32\8.3.0
    libs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    libc=
    so=dll
    useshrplib=true
    libperl=libperl531.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-mdll -s -L"C:\_32\blead-5.31.9-ld\lib\MSWin32-x86-multi-thread-64int-ld\CORE" -L"C:\_32\gcc-straw-830\mingw32\lib"'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    HAVE_INTERP_INTERN
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_IMPLICIT_SYS
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_LONG_DOUBLE
    USE_PERLIO
    USE_PERL_ATOF
  Built under MSWin32
  Compiled at Feb 21 2020 23:51:24
  @INC:
    ..\lib
    C:/_32/comp/perl-5.31.9-ld/lib

```

**Comment by khwilliamson** [comment]
Something like this is also happening on Unixy systems.  I can get it to happen on my 64 bit Linux box by compiling in 32 bit mode with -Duse64bitint.  Same on Tux's 32-bit HP-UX box.  But the 64 bit ints are required.

In running gdb, I get to where the program is about to croak with a sprintf message.  The data being passed in looks fine.  But on my box, when trying to print, something ends up NULL and an assertion failure is made.

valgrind doesn't work AFAICT on this faked 32 bit build.  Nor do I see a way to get clang and asan to work.  My educated guess is that this is a bug in pointer/IV sizes.  The compilation doesn't show any warnings to that effect for me. @sisyphus could you look at your output?

I could single step through the code, but I suspect I might miss seeing how the bug inserts itself.  If someone has ideas for debugging this, please speak up

**Comment by sisyphus** [comment]
I did a diff on the output of the 32bitint 'make' and the output of
64bitint 'make'.

There are two warnings on the 64bitint build that don't appear in the
32bitint build:

DynaLoader.xs: In function 'XS_DynaLoader_dl_load_file':
DynaLoader.xs:144:29: warning: cast from pointer to integer of different
size [-Wpointer-to-int-cast]
  retsv = sv_2mortal(newSViv((IV)retv));

and:

DynaLoader.xs: In function 'XS_DynaLoader_dl_find_symbol':
DynaLoader.xs:176:19: warning: cast from pointer to integer of different
size [-Wpointer-to-int-cast]
  sv_setiv( ST(0), (IV)retv);

There are also 2 warnings on the 32bitint build that don't appear in the
64bitint build:

RealPPPort.xs: In function 'XS_Devel__PPPort_sprintf_ivmax':
RealPPPort.xs:994:27: warning: format '%ld' expects argument of type 'long
int', but argument 2 has type 'int' [-Wformat=]
         RETVAL = newSVpvf("%" IVdf, IV_MAX);

and:

RealPPPort.xs: In function 'XS_Devel__PPPort_sprintf_uvmax':
RealPPPort.xs:1001:27: warning: format '%lu' expects argument of type 'long
unsigned int', but argument 2 has type 'unsigned int' [-Wformat=]
         RETVAL = newSVpvf("%" UVuf, UV_MAX)

They're the only differences in warnings that showed up.

Cheers,
Rob

**Comment by khwilliamson** [comment]
I believe cd2d26f fixes the problem, but will defer closing the ticket until verified by @sisyphus

**Comment by sisyphus** [comment]
Yep - that fixes it.
