### ISSUE TITLE
dist/IO/t/io_unix.t - always skips tests for Unix domain sockets on Windows

### ISSUE THREAD

**Issue by richardleach** [Perl/perl5#17575]
Module: IO

**Description**

dist/IO/t/io_unix.t currently skips all tests on Windows, but AF_UNIX is supported on Win 10 from the 1803 release: 

https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/
https://devblogs.microsoft.com/commandline/windows10v1803/
https://blogs.msdn.microsoft.com/commandline/2018/02/07/windowswsl-interop-with-af_unix/

io_unix.t passes on a recent enough version of Win 10, using Strawberry 5.30.1, if:

1. The OS check for this platform is removed
2. The definition of `$can_fork` is copied in from io_sock.t (i.e. threads be used to emulate fork)
3. The check for `(! $Config{'d_fork'})`  is changed to `(! $can_fork)` 

**Suggested Enhancement**

- Figure out a way to differentiate supporting vs non-supporting versions of Windows, rather than step 1 above!
- Implement that, along with 2. & 3. 

**Suggested Next Step**

io_unix.t currently tests whether `IO::Socket::pack_sockaddr_un('/foo/bar')` dies. It might be that it will die on versions of Windows that don't support AF_INET, but I don't have an older version of Windows readily to hand. If anyone does, please could they test this out?

**Complications?**

This functionality is supplied by a pluggable kernel driver, _afunix.sys_. It's not impossible that the driver could be disabled, e.g. in a hardened build. 

Not sure of the best way to check for that, but one way would be to check for the presence of `HKLM\SYSTEM\CurrentControlSet\Services\afunix` and if it exists, check the value of _Start_. (0x1, SERVICE_SYSTEM_START, is the default.) Tests could be skipped if any of the following is true:

- That key is missing
- Access is denied for some reason
- Start == 0x4 (SERVICE_DISABLED)

**Perl configuration**
Standard Strawberry Perl v5.30.x build with threading.

**Comment by xenu** [comment]
>io_unix.t currently tests whether `IO::Socket::pack_sockaddr_un('/foo/bar')` dies. It might be that it will die on versions of Windows that don't support AF_INET, but I don't have an older version of Windows readily to hand. If anyone does, please could they test this out?

Windows AF_UNIX socket support was implemented in Socket.pm 2.029. On the older versions `pack_sockaddr_un` will always throw, even when running on Win10 1803+.

With Socket >= 2.029, `pack_sockaddr_un` will never throw on Windows, even when AF_UNIX sockets aren't supported by the OS, so that won't help us.

I believe the easiest way to test for AF_UNIX socket support on Windows is to try to create a socket:

```perl
socket(my $sock, PF_UNIX, SOCK_STREAM, 0)
  or die "AF_UNIX isn't supported on this platform"
```

The above code will die when either the current Windows version doesn't support AF_UNIX or the afunix service is stopped.

`AF_UNIX` and `PF_UNIX` constants are safe to use because they're guaranteed to exist on all Windows versions. Even the Windows 3.1 SDK defines them!

**Comment by richardleach** [comment]
@xenu Great, thanks for that clear explanation. I'll put together a PR - unless you've started work on one?

**Comment by khwilliamson** [comment]
On 3/1/20 12:12 PM, Richard Leach wrote:
> @xenu <https://github.com/xenu> Great, thanks for that clear 
> explanation. I'll put together a PR - unless you've started work on one?
> 

Should there be some windows testing in io_sock.t?  It was completely 
disabled by

commit 037138fac4b4b8bf94c6dd36b73041ce4bab6860
Author: Nicolas R <atoomic@cpan.org>
  Date:   Fri Jan 17 10:31:35 2020 -0700

      Disable dist/IO/t/io_sock.t on windows

      Fixes #17429

**Comment by Leont** [comment]
> Should there be some windows testing in io_sock.t?  It was completely
disabled by

Yeah, I don't think it makes sense to run this test if `io_sock.t` isn't being run.

**Comment by xenu** [comment]
>Should there be some windows testing in io_sock.t?  It was completely
disabled by

It definitely should be fixed.

**Comment by xenu** [comment]
> 
> 
> @xenu Great, thanks for that clear explanation. I'll put together a PR - unless you've started work on one?

@richardleach feel free to do that.

**Comment by richardleach** [comment]
I'll start with a PR that skips if `$^O eq 'MSWin32' && $ENV{CONTINUOUS_INTEGRATION}`, to match io_sock.t. That can be relaxed if we get to the bottom of #17429.

**Comment by xsawyerx** [comment]
Fix merged. Can we resolve this issue?

**Comment by richardleach** [comment]
Thanks, happy to close it.
