### ISSUE TITLE
[doc] Obsolete link to casbah.org

### ISSUE THREAD

**Issue by Grinnz** [Perl/perl5#17589]
**Where**
https://perldoc.pl/perlpacktut#Another-Portable-Binary-Encoding

**Description**
perlpacktut refers to a "Scarab project" at casbah.org which no longer seems to exist. I can't find any explanatory websites other than the archived site: https://web.archive.org/web/20080517124048/http://www.casbah.org/

Originally posted at https://github.com/OpusVL/perldoc.perl.org/issues/99

**Comment by jkeenan** [comment]
With respect to this blead was updated by @abh in 239ca4f4759b435ace2fa30b1bcf0abec7118ec2 on Dec 11 2019.  Is there anything else we need to do about this?

Thank you very much.
Jim Keenan

**Comment by Grinnz** [comment]
Looks good, thanks.
