### ISSUE TITLE
parsing large files that assign to hashes is much slower post-5.18

### ISSUE THREAD

**Issue by cowens** [Perl/perl5#17586]
This is a bug report for perl from chas.owens@gmail.com,
generated with the help of perlbug 1.41 running under perl 5.30.1.

-----------------------------------------------------------------
[Please describe your issue here]

Generate a file that uses a lot of hash assignments:

    perl -nle 'BEGIN { print "#!/usr/bin/perl\n\nuse strict;\nuse warnings;\n\nmy %h;" } print qq{\$h{"$_"} = 1;} }{ print "print scalar keys %h, qq{\n}"' /usr/share/dict/words > words.pl

Some point after 5.18, parsing this file starts taking 15 minutes
instead sub-second.  Converting it to use a list assignment fixes the
problem:

    perl -nle 'BEGIN { print "#!/usr/bin/perl\n\nuse strict;\nuse warnings;\n\nmy %h = (" } print qq{\t"$_" => 1,} }{  print "print scalar keys %h, qq{\n}"' /usr/share/dict/words > words.pl

[Please do not change anything below this line]
-----------------------------------------------------------------
---
Flags:
    category=core
    severity=medium
---
Site configuration information for perl 5.30.1:

Configured by chas at Wed Feb 26 09:45:57 EST 2020.

Summary of my perl5 (revision 5 version 30 subversion 1) configuration:
   
  Platform:
    osname=darwin
    osvers=19.3.0
    archname=darwin-2level
    uname='darwin creditae 19.3.0 darwin kernel version 19.3.0: thu jan 9 20:58:23 pst 2020; root:xnu-6153.81.5~1release_x86_64 x86_64 '
    config_args='-Dprefix=/Users/chas/.plenv/versions/5.30.1 -de -Dversiononly -A'eval:scriptdir=/Users/chas/.plenv/versions/5.30.1/bin''
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.15 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.15 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=10.15 -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /Library/Developer/CommandLineTools/usr/lib/clang/11.0.0/lib /Library/Developer/CommandLineTools/usr/lib /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib /usr/lib
    libs=-lpthread -lgdbm -ldbm -ldl -lm -lutil -lc
    perllibs=-lpthread -ldl -lm -lutil -lc
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=10.15 -bundle -undefined dynamic_lookup -L/usr/local/lib -fstack-protector-strong'

---
@INC for perl 5.30.1:
    /Users/chas/.plenv/versions/5.30.1/lib/perl5/site_perl/5.30.1/darwin-2level
    /Users/chas/.plenv/versions/5.30.1/lib/perl5/site_perl/5.30.1
    /Users/chas/.plenv/versions/5.30.1/lib/perl5/5.30.1/darwin-2level
    /Users/chas/.plenv/versions/5.30.1/lib/perl5/5.30.1

---
Environment for perl 5.30.1:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/chas
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_TERMINAL=iTerm2
    LC_TERMINAL_VERSION=3.3.8
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/chas/.plenv/versions/5.30.1/bin:/Users/chas/.plenv/libexec:/Users/chas/.plenv/plugins/perl-build/bin:/Users/chas/bin:/Users/chas/apps/sample/bin:/Users/chas/apps/google-cloud-sdk/bin:/Users/chas/bin:/Users/chas/src/infrastructure/bin:/Users/chas/.plenv/shims:/Users/chas/.plenv/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/chas/bin:/Users/chas/apps/sample/bin:/Users/chas/src/infrastructure/bin:/Users/chas/.plenv/shims:/Users/chas/.plenv/bin:/usr/local/sbin:/Users/chas/go/bin:/Users/chas/go/bin
    PERL_BADLANG (unset)
    SHELL=/bin/zsh

**Comment by cowens** [comment]
Example of the non-linear slowdown:

```
$ perl gen_words.pl
1000_hash_assignments.pl syntax OK
        0.02 real         0.00 user         0.00 sys
2000_hash_assignments.pl syntax OK
        0.03 real         0.02 user         0.00 sys
4000_hash_assignments.pl syntax OK
        0.09 real         0.08 user         0.00 sys
8000_hash_assignments.pl syntax OK
        0.36 real         0.33 user         0.00 sys
16000_hash_assignments.pl syntax OK
        1.44 real         1.40 user         0.01 sys
32000_hash_assignments.pl syntax OK
        8.03 real         7.88 user         0.07 sys
64000_hash_assignments.pl syntax OK
       47.69 real        46.64 user         0.38 sys
```

Above was generated with

```
#!/usr/bin/perl

use v5.18.0;
use warnings;

my %h;

my $template = <<EOT;
#!/usr/bin/perl

use v5.18.0;
use warnings;

my %h;

ASSIGNMENTS

say scalar keys %h;
EOT

my @words = map { chomp; $_ } qx{cat /usr/share/dict/words};

my @sizes = (1000, 2000, 4000, 8000, 16000, 32000, 64000);

for my $size (@sizes) {
	my $assignments = join "", map { "\$h{$_} = 1;" } @words[1 .. $size];
	my $file = "${size}_hash_assignments.pl";
	open my $fh, ">", $file or die $!;
	print $fh $template =~ s/ASSIGNMENTS/$assignments/r;
	system "time perl -c $file";
	unlink $file;
}
```

**Comment by shlomif** [comment]
On mageia linux x64 v8:

- `perl words.pl` is slow and `perl words2.pl` is fast with both perl-5.18.4 from perlbrew and `/usr/bin/perl` which is 5.30.x.
- `perl words.pl` is fast and `perl words2.pl` is fast with perl-5.16.3 from perlbrew.

I used this:

```
#! /bin/bash
#
# perlissue17586.bash
#

perl -nle 'BEGIN { print "#!/usr/bin/perl\n\nuse strict;\nuse warnings;\n\nmy %h;" } print qq{\$h{"$_"} = 1;} }{ print "print scalar keys %h, qq{\n}"' /usr/share/dict/words > words.pl
perl -nle 'BEGIN { print "#!/usr/bin/perl\n\nuse strict;\nuse warnings;\n\nmy %h=(\n" } print qq{"$_" => 1,} }{ print ");\nprint scalar keys %h, qq{\n}"' /usr/share/dict/words > words2.pl
```

**Comment by shlomif** [comment]
Update: on the same system perl-5.18.0 from perlbrew is also slow when running `words.pl`.

**Comment by briang** [comment]
There's been some discussion of this on [reddit](https://www.reddit.com/r/perl/comments/f9d6g3/perl_5180_considerably_slower/)

**Comment by xenu** [comment]
While this was triggered by something else, the underlying cause is the same as in #17555 and Tony's PR (#17583) fixes this issue.

**Comment by jkeenan** [comment]
> While this was triggered by something else, the underlying cause is the same as in #17555 and Tony's PR (#17583) fixes this issue.

Here's some data to support that.  Taking Tony's PR, making it into a branch, installing it locally and running Shlomi's 2 scripts against that perl, I got:
```
$ perlbrew use perl-5.16.3
$ time perl words.pl
102305

real	0m0.330s
user	0m0.306s
sys	0m0.024s

$ time perl words2.pl
102305

real	0m0.175s
user	0m0.164s
sys	0m0.012s


$ perlbrew use perl-5.30.0
$ time perl words.pl
102305

real	3m13.211s
user	3m13.092s
sys	0m0.064s

$ time perl words2.pl
102305

real	0m0.209s
user	0m0.197s
sys	0m0.012s


$ cd ~/testing/smoke-me/jkeenan/tonyc/ghpr-17583/
$ time ./bin/perl -Ilib ~/learn/perl/p5p/words.pl
102305

real	0m0.396s
user	0m0.380s
sys	0m0.016s

$ time ./bin/perl -Ilib ~/learn/perl/p5p/words2.pl
102305

real	0m0.210s
user	0m0.186s
sys	0m0.024s
```
Thank you very much.
Jim Keenan

**Comment by shlomif** [comment]
perl-5.30.2-rc1 from perlbrew `--thread` seems to be affected by this issue as well. 😢

**Comment by xenu** [comment]
Closing because #17583 was merged.
