### ISSUE TITLE
pod2man produces bogus output

### ISSUE THREAD

**Issue by dkogan** [Perl/perl5#17592]
Hi. Let's say I have this tst.pod file:

```
=head1 abc

EVT_...()
VT_...()
T_...()
_...()
...()

EVT_...()
EVT_..()
EVT_.()
EVT_()
EVT()

EVT_...()
EVT_...(
EVT_...
EVT_..
EVT_.
```

I run pod2man:

```
$ pod2man tst.pod

... 

\&\s-1EVT_...\\fBs0()\fR
\&\s-1VT_...\\fBs0()\fR
T_...()
_...()
\&...()



\&\s-1EVT_...\\fBs0()\fR
\&\s-1EVT_..\\fBs0()\fR
\&\s-1EVT_.\\fBs0()\fR
\&\s-1\fBEVT_\s0()\fR
\&\s-1\fBEVT\s0()\fR



\&\s-1EVT_...\\fBs0()\fR
\&\s-1EVT_...\s0(
\&\s-1EVT_...
EVT_..
EVT_.\s0

...
```

Spaces added for clarity, and only the interesting things kept. Note that
sometimes pod2man like to bold things, even I never asked for it (\\fB tags).

And note that sometimes pod2man likes to add "s0", which is some sort of
leftover code that is not interpreted by the "man" tool: "man" actually displays
"s0", which is nowhere in the original text.

My understanding is that POD markup is either

- lines starting with =something
- text such as B<something> or L<something> and such

Is there some other type of markup that pod2man is trying to interpret that I'm
accidentally including in tst.pod? I don't see anything clear in the "perlpod"
manpage.

Thanks.

**Comment by Grinnz** [comment]
You are correct, nothing else within your test file would be considered POD markup.

**Comment by Grinnz** [comment]
Sorry you have been going in circles with this bug, but pod2man is part of podlators which is maintained on CPAN, the bugtracker is here: https://rt.cpan.org/Dist/Display.html?Name=podlators

**Comment by dkogan** [comment]
Heh. OK. I should go submit this bug there?

**Comment by dkogan** [comment]
I emailed them.

**Comment by dkogan** [comment]
The podlators report is here:

https://rt.cpan.org/Public/Bug/Display.html?id=132007

I'm closing this one.
