### ISSUE TITLE
github issues/perlbug don't play nicely together

### ISSUE THREAD

**Issue by dkogan** [Perl/perl5#17591]
I went to file a bug today. Github told me:

````
<!-- Note: you can also replace the whole content by the file generated by perlbug utility. -->
````

So I ran "perlbug", and filed my bug. The result was this email:

```
Hi! I'm the Perlbug Autoresponder.

The Perl 5 Bug Tracker has moved to GitHub:
https://github.com/perl/perl5/issues.

If you were trying to file a Perl bug report, we suggest going to
GitHub.
```

I guess this means that the bug I filed was thrown away? The email isn't clear about that. Suggestions:

- If perlbug is deprecated, the github message shouldn't tell me to use it. Or it should be very  clear that I should use it to generate the bug report, but not to submit it

- If the autoresponder threw away my bug report, it should very clearly tell me that in the email. And that email should contain a copy of the report so that I don't need to re-create it for "proper" submittal.

Thanks

**Comment by Grinnz** [comment]
This is to be addressed in https://github.com/Perl/perl5/issues/17197 - the documentation of perlbug is already updated for future versions. Unfortunately we can't do anything about the perlbug executables installed in older versions of perl.

**Comment by Grinnz** [comment]
The GitHub message is saying you can use the perlbug utility to generate your bug report as a file, the plan is to make this default behavior in future versions but generally this is done with `perlbug -F filename.out` or answering the interactive prompts appropriately.

**Comment by dkogan** [comment]
Hi. Thank you for replying. I realize you can't update all the deployments of "perlbug" out there, but you can update:

- The message in the github bug-report template. It already says that perlbug should be used to generate the text, but it should also say in BIG BOLD LETTERS to not use perlbug to submit the report. I saw the text that told me to go use perlbug. And perlbug then offered to take my bug report; at that point I didn't remember the wording that sent me to perlbug in the first place

- The server sending emails responding to perlbug reports. It should clearly tell me it threw away the report, and it should give me a copy so that I can cut/paste the thing into github.

Thanks agai

**Comment by jkeenan** [comment]
No further discussion in this ticket in over 4 years; closing.
