### ISSUE TITLE
Segfault in regcomp.c due to integer overflow in (?+PARNO) handling

### ISSUE THREAD

**Issue by lightsey** [Perl/perl5#17593]
**Description**
Relative numeric capture group reference numbers are limited to +/- I32_MAX in S_reg(). This limit isn't correct since the effective relative capture group is offset by the current level of nesting. With positive relative references near the I32_MAX limit, this can overflow into a negative reference without any protections to verify the reference exists.

The effects of the integer overflow manifest as a segfault in S_study_chunk()

**Steps to Reproduce**
A simple reproduction case is:
```
perl -e '/((?+2147483647))/'
```

The specific error can be pinpointed by compiling Perl with Clang's integer undefined behavior and address sanitizers enabled.

On Debian 10.3 AMD64 using clang-7 as the compiler, this can be accomplished with the following build process:
```
export UBSAN_TMP="$(mktemp -d)"

export UBSAN_OPTIONS="halt_on_error=0:log_path=${UBSAN_TMP}"

./Configure -des -Dusedevel -DDEBUGGING=-g -Doptimize=-O0  -Dcc=clang -Accflags="-g -O0 -m32 -fsanitize=address -fsanitize=undefined -fsanitize-recover=undefined -fno-omit-frame-pointer" -Aldflags="-g -O0 -m32 -fsanitize=address -fsanitize=undefined -fsanitize-recover=undefined -fno-omit-frame-pointer" -Alddlflags="-shared -g -O0 -m32 -fsanitize=address -fsanitize=undefined -fsanitize-recover=undefined -fno-omit-frame-pointer"

make regexec_cflags='extra="-fsanitize=integer -fsanitize-recover=integer"' regcomp_cflags='extra="-fsanitize=integer -fsanitize-recover=integer"'

rm -rf -- "${UBSAN_TMP}"

export UBSAN_OPTIONS='print_stacktrace=1'

./perl -e '/((?+2147483647))/'
```
**Sanitizer Output**
On blead commit 170a6378bcd18e0dc2ad6112c7bbaa3818642173 the initial ubsan error is:
```
regcomp.c:11688:37: runtime error: signed integer overflow: 2 + 2147483647 cannot be represented in type 'long'
    #0 0x87d09c6 in S_reg /home/jd/src/git/lab/perl5/regcomp.c:11688:37
    #1 0x89fcae7 in S_regatom /home/jd/src/git/lab/perl5/regcomp.c:13422:15
    #2 0x89c70c9 in S_regpiece /home/jd/src/git/lab/perl5/regcomp.c:12511:11
    #3 0x8958ce6 in S_regbranch /home/jd/src/git/lab/perl5/regcomp.c:12431:18
    #4 0x880b024 in S_reg /home/jd/src/git/lab/perl5/regcomp.c:12133:10
    #5 0x89fcae7 in S_regatom /home/jd/src/git/lab/perl5/regcomp.c:13422:15
    #6 0x89c70c9 in S_regpiece /home/jd/src/git/lab/perl5/regcomp.c:12511:11
    #7 0x8958ce6 in S_regbranch /home/jd/src/git/lab/perl5/regcomp.c:12431:18
    #8 0x880b024 in S_reg /home/jd/src/git/lab/perl5/regcomp.c:12133:10
    #9 0x873ccb7 in Perl_re_op_compile /home/jd/src/git/lab/perl5/regcomp.c:7784:9
    #10 0x81a2f26 in Perl_pmruntime /home/jd/src/git/lab/perl5/op.c:8178:6
    #11 0x86d995b in Perl_yyparse /home/jd/src/git/lab/perl5/perly.y:1260:23
    #12 0x833c54a in S_parse_body /home/jd/src/git/lab/perl5/perl.c:2579:9
    #13 0x832f713 in perl_parse /home/jd/src/git/lab/perl5/perl.c:1870:2
    #14 0x81540cc in main /home/jd/src/git/lab/perl5/perlmain.c:126:10
    #15 0xf7be6b40 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x1ab40)
    #16 0x807fd11 in _start (/home/jd/src/git/lab/perl5/perl+0x807fd11)
```

The specific overflow is here https://github.com/Perl/perl5/blob/170a6378bcd18e0dc2ad6112c7bbaa3818642173/regcomp.c#L11688

**Expected behavior**
The code for relative references should detect this overflow and throw an exception during the regex compile.

The code handles offsets above I32_MAX correctly. Negative offsets are handled somewhat correctly...it doesn't directly detect the overflow, but it does avoid crashing from it.

**Notes**
This bug was initially reported as Perl/perl5-security#131 in the security issue tracker for analysis. It was discovered by the Perl security team using AFL. This bug doesn't meet the requirements for handling as a vulnerability in Perl's regex engine.

@hvds commented on two other nearby issues during his initial analysis:

>Note that if the input is greater than I32_MAX we do not update RExC_parse after the grok_atoUV call, so will immediately fail with a slightly misleading "Expecting close bracket" before the plus.  That's the result of 22ff313 for Perl/perl5#14498 (fixing bigger problems with grok_atou), but I think it's not urgent to improve.

> For the paren == '-' .... if (num < 1) case, the "it might be a forward reference" added in 7c932d0 is not true, so this chunk can be simplified back to its original:
```
                    if (num < 1)  {
                        RExC_parse++;
                        vFAIL("Reference to nonexistent group");
                    }
```

**Comment by shlomif** [comment]
Just to note that I am getting a segfault with `/usr/bin/perl` on mageia 8 x64 and freenode's perlbot segfaults with it in both "sweval" and "basheval":

```
<rindolf> sweval: /((?+2147483647))/
<perlbot> rindolf: [Died SIGSEGV]
<rindolf> basheval: perl -e '/((?+2147483647))/'
<perlbot> rindolf: /tmp/kRjf5UeFD3: line 1:     2 Segmentation fault      perl -e '/((?+2147483647))/'␤[Exited 139]
<rindolf> https://github.com/Perl/perl5/issues/17593
```
