### ISSUE TITLE
Matching a pattern doesn't always output requested debugging info

### ISSUE THREAD

**Issue by khwilliamson** [Perl/perl5#17612]
There are two instances in pp_match() where debugging info for regexes is output.  This currently only happens on a debugging build and -Dr is specified (or the corresponding variable is set)

Regex debugging is also supposed to be enabled even on non-debugging builds by use of re.pm.  These instances in pp_match are the only ones I know of that don't work that way.

This has caused me a bunch of debugging time, as one of the outputs, is indicating that it isn't even going to try matching because the lengths of the pattern and string are such that it could never be successful.  Now that I know this can happen, I won't tear my hair out wondering why the engine doesn't seem to be outputting the debugging info I requested.  But I'm sure it has led to wasted effort by others.

**Comment by khwilliamson** [comment]
I actually have a patch prepared that fixes this.  I'm wondering if it is too late in the development cycle to apply it.  It would have a visible effect on debugging programs that unwittingly are requesting debugging info, and suddenly it shows up.

On the other hand, it is fixing a bug.

**Comment by jkeenan** [comment]
On 3/4/20 9:01 PM, Karl Williamson wrote:
> I actually have a patch prepared that fixes this. I'm wondering if it is 
> too late in the development cycle to apply it. It would have a visible 
> effect on debugging programs that unwittingly are requesting debugging 
> info, and suddenly it shows up.
> 

Strictly speaking, we are 16 days away from full code freeze.  So 
technically we could apply a patch without, say, requesting pumpking's 
permission.  However, this is part of the code base that at most 3 
people know well.  At this depth of the codebase, problems downstream 
(CPAN/performance) tend not to appear for several months.  Hence, I'm 
inclined to say, work on it in a branch and merge it for after 5.33.0.

> On the other hand, it is fixing a bug.
> 

My cautious two cents.
Jim Keenan

**Comment by hvds** [comment]
I think it would be good to get this in if possible, it looks very low risk to me for correctness and fairly low risk for speed.

It would be valuable to use `Porting/bench.pl` to show what if any impact there is on a simple case not hitting these codepaths, and on one that does (on a non-debugging perl when no debugging requested).
