### ISSUE TITLE
[doc] `perlunicode` mentions the UTF8 flag, which `perlunifaq` begs us to ignore

### ISSUE THREAD

**Issue by FGasper** [Perl/perl5#17610]
**Where**
`perlunicode`

**Description**
There are several mentions of “the UTF8 flag” in `perlunicode` whose presence seems to contradict the exhortation to ignore that same flag in `perlunifaq`.

**Comment by Grinnz** [comment]
The mentions I see are mostly in https://perldoc.pl/perlunicode#Porting-code-from-perl-5.6.X and https://perldoc.pl/perlunicode#Interaction-with-Extensions, which are cases that actually need to know about the UTF8 flag.

**Comment by FGasper** [comment]
Fair enough.
