### ISSUE TITLE
5.28.2 installation error (cpan/Time-Local/t/Local.t & Porting/exec-bit.txt)

### ISSUE THREAD

**Issue by sjfleck** [Perl/perl5#17625]
Module:

Installing perl

**Description**

I'm having an issue installing Perl 5.28.1. When I do the make test step I get an 2 errors:

_cpan/Time-Local/t/Local ........................................ #   Failed test 'timelocal year for 1970 1 2 0 0 0'
   at t/Local.t line 109.
          got: '170'
     expected: '70'
   Failed test 'timegm year for 1970 1 2 0 0 0'
   at t/Local.t line 124.
          got: '170'
     expected: '70'
 Looks like you failed 2 tests of 187.
FAILED at test 6_

and

_t/porting/exec-bit ............................................. # Failed test 87 - File ../cpan/Time-Local/lib/Time/Local.pm has shebang at porting/exec-bit.t line 58
 Failed test 88 - tarball will chmod +x ../cpan/Time-Local/lib/Time/Local.pm at porting/exec-bit.t line 60
 Remove the exec bit or add '../cpan/Time-Local/lib/Time/Local.pm' to Porting/exec-bit.txt_

I read online that there was a patch for the first issue as of 2020. I'm inexperienced with patches and had a difficult time understanding how to use it, so I just edited Local.t by hand. I reran t eliminated the first error, but another error was added below. I now had these errors:

_t/porting/exec-bit ............................................. # Failed test 87 - File ../cpan/Time-Local/lib/Time/Local.pm has shebang at porting/exec-bit.t line 58
 Failed test 88 - tarball will chmod +x ../cpan/Time-Local/lib/Time/Local.pm at porting/exec-bit.t line 60
 Remove the exec bit or add '../cpan/Time-Local/lib/Time/Local.pm' to Porting/exec-bit.txt
 Failed test 90 - tarball will chmod +x ../cpan/Time-Local/t/Local.t at porting/exec-bit.t line 60
 Remove the exec bit or add '../cpan/Time-Local/t/Local.t' to Porting/exec-bit.txt
FAILED at test 87_

I don't understand these errors too well, but they refer to lines 58 and 60 of exec-bit.txt. These lines are "Porting/sort_perldiag.pl" and "Porting/valgrindpp.pl" respectively. 

As per the error's instructions I added: 
../cpan/Time-Local/lib/Time/Local.pm
../cpan/Time-Local/t/Local.t
into 'exec-bit.txt' but that simply lead to many more errors. I'm really unsure how to move forward.

That being said, I don't understand the "Local/lib/Time/Local.pm has shebang at porting/exec-bit.t line 58" error. The only shebang was at the very top and strangely it's including a path that I really don't want. I checked some of the other .pl files in the Porting directory and they also have "#!/usr/bin/perl" or "#!/usr/bin/perl -w" at the top. This is not a directory that I designated or even have access to.

Any help with this would be greatly appreciated!

**Steps to Reproduce**

uploaded perl-5.28.2.tar.gz to '/gpfs/scratch/sjfleck/modulefiles'
_tar -xzf perl-5.30.1.tar.gz
cd perl-5.28.2
./Configure -des -Dprefix=/user/sjfleck/localperl
make
make test_ (ERROS AT THIS STEP)
_make install_ (NEVER MADE IT TO THIS STEP!)

**Expected behavior**

Installation

**Perl configuration**

```
# perl -V output goes here
```

**Comment by richardleach** [comment]
Please could you confirm:
- Which OS you're trying to build perl on?
- Where you downloaded the tar.gz from?
- Did you `tar -xzf perl-5.30.1.tar.gz` or `tar -xzf perl-5.28.2.tar.gz` ?
- What are the file permissions on local.t and Local.pm (a) now (b) from a fresh untar?

**Comment by sjfleck** [comment]
Richard,
Thank you for the very fast reply! After hours of frustration, I deleted the whole program and started over. I'm not sure what the difference was this time, but I finally got it to work. Here are the steps I took:

upload perl-5.28.2.tar.gz
_tar -zxvf perl-5.28.2.tar.gz
cd perl-5.28.2
find . -exec touch {} \;
	#I need to do this step or my University will delete the files
cd /gpfs/scratch/sjfleck/modulefiles/perl-5.28.2/cpan/Time-Local/t/
chmod -777 Local.t
rm Local.t_
*upload edited Local.t
_chmod -444 Local.t
./Configure -des -Dprefix=/user/sjfleck/localperl
make
make test_
	#All tests successful.
	#Elapsed: 881 sec
	#u=6.43  s=4.49  cu=417.23  cs=78.41  scripts=2456  tests=1157715
_make install_

Everything worked except I still don't have a file that I need to run the program I need to run. The reason that I'm using perl is because I need to use RepeatMasker. This program requires this file to exist:

/user/sjfleck/localperl/lib/site_perl/5.28.2/x86_64-linux/Text/Soundex.pm

but my /user/sjfleck/localperl/lib/site_perl/5.28.2/x86_64-linux/ directory is empty

Do you know how I can install the Text::Soundex module? Thank you

**Comment by richardleach** [comment]
[Text::Soundex](https://metacpan.org/pod/Text::Soundex) isn't a core module, so has to be installed separately.

The simplest solution, if it works in your environment, would be to use the CPAN client: https://mojolicious.org/perldoc/CPAN 

It might be as easy as:
- Launch via `cpan` or, failing that, `perl -MCPAN -e shell`
- Install with `install Text::Soundex` at the cpan> shell prompt
(note that you will be prompted for some initial configuration settings during that process)

If that doesn't work, you may have to download the module (see the download link on [Text::Soundex](https://metacpan.org/pod/Text::Soundex), upload it to your environment, and install using the instructions in the README file.

If that doesn't prove to be straightforward, your best bet is probably to ask on https://www.perlmonks.org/ or https://stackoverflow.com/ for assistance figuring out what works best in your environment.

**Comment by richardleach** [comment]
Ah, the following might also be useful to you if you have problems installing Text::Soundex:

- https://stackoverflow.com/questions/55768847/cant-locate-text-soundex-pm-in-inc
- https://stackoverflow.com/questions/43523744/perl-module-still-not-found-after-install-with-cpan

**Comment by sjfleck** [comment]
Thank you for the help! I was able to configure cpan and download it using that.
