### ISSUE TITLE
perl-5.31.10 - ext/XS-APItest/t/hv_macro.t fails on big endian architecture

### ISSUE THREAD

**Issue by sisyphus** [Perl/perl5#17667]
Module:

**Description**

**Steps to Reproduce**

In the perl-5.31.10 top level directory run:
./perl -I./lib ext/XS-APItest/t/hv_macro.t
**Expected behavior**

When I see diagnostics like:
\#          got: '0x87f0'
\#     expected: '0xf087'
I immediately think of endianness issues,
ext/XS-APItest/t/hv_macro.t produces a lot of such errors in the first 50 tests.
After that, there's lots more errors, though if the issue with them is also endianness, then it's not so obvious (to me, at least). 
I've attached in hv_macro.txt the full output of running:
./perl -I./lib ext/XS-APItest/t/hv_macro.t 

**Perl configuration**

```
Summary of my perl5 (revision 5 version 31 subversion 10) configuration:
   
  Platform:
    osname=linux
    osvers=3.2.0-4-powerpc64
    archname=ppc64-linux
    uname='linux debian-sis 3.2.0-4-powerpc64 #1 smp debian 3.2.78-1 ppc64 gnulinux '
    config_args='-des -Duse64bitall -Dcc=gcc -m64 -Uversiononly -Dusedevel -Dprefix=/home/sisyphus-sis/blead-5.31.10-d'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc -m64'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O1'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include'
    ccversion=''
    gccversion='4.6.3'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=87654321
    doublekind=4
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=6
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='gcc -m64'
    ldflags =' -fstack-protector -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/gcc/powerpc-linux-gnu/4.6/include-fixed /usr/lib /lib/powerpc-linux-gnu /lib/../lib /usr/lib/powerpc-linux-gnu /usr/lib/../lib /lib /lib64 /usr/lib64
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.13.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.13'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O1 -L/usr/local/lib -fstack-protector'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Mar 23 2020 10:41:36
  @INC:
    ./lib
    /home/sisyphus-sis/blead-5.31.10-d/lib/perl5/site_perl/5.31.10/ppc64-linux
    /home/sisyphus-sis/blead-5.31.10-d/lib/perl5/site_perl/5.31.10
    /home/sisyphus-sis/blead-5.31.10-d/lib/perl5/5.31.10/ppc64-linux
    /home/sisyphus-sis/blead-5.31.10-d/lib/perl5/5.31.10

```
[hv_macro.txt](https://github.com/Perl/perl5/files/4366762/hv_macro.txt)

**Comment by jkeenan** [comment]
> In the perl-5.31.10 top level directory run:
> ./perl -I./lib ext/XS-APItest/t/hv_macro.t
> **Expected behavior**
> 
> When I see diagnostics like:
> # got: '0x87f0'
> # expected: '0xf087'
> I immediately think of endianness issues,
> ext/XS-APItest/t/hv_macro.t produces a lot of such errors in the first 50 tests.
> After that, there's lots more errors, though if the issue with them is also endianness, then it's not so obvious (to me, at least).
> I've attached in hv_macro.txt the full output of running:
> ./perl -I./lib ext/XS-APItest/t/hv_macro.t
> 
> **Perl configuration**
> 
> ```
> Summary of my perl5 (revision 5 version 31 subversion 10) configuration:
>    
>   Platform:
>     osname=linux
>     osvers=3.2.0-4-powerpc64
>     archname=ppc64-linux
>     uname='linux debian-sis 3.2.0-4-powerpc64 #1 smp debian 3.2.78-1 ppc64 gnulinux '
>     config_args='-des -Duse64bitall -Dcc=gcc -m64 -Uversiononly -Dusedevel -Dprefix=/home/sisyphus-sis/blead-5.31.10-d'

1. Am I correct in thinking that this cannot be reproduced on this ...?
```
$ uname -m
x86_64
```
2.  Does the error manifest itself with simpler configuration switches, say just `-des -Dusedevel`?

3.  Is this a regression from correct behavior?  Or has it "always" been this way?  If the former, are you able to bisect to identify the first bad commit?

Thank you very much.
Jim Keenan

**Comment by sisyphus** [comment]
Hi Jim,
I believe (unproven) it will be reproducible on any build of perl-5.31.10
for which $Config{byteorder} is '87654321' (and perhaps also '4321').
I don't think the failure occurred when I built 5.31.7 on this machine (or
I would have reported it then), and I didn't build 5.31.8 or 5.31.9.

I don't know anything about git bisect, though I guess there's no good
excuse for not learning.

I'll do some digging and see if I can find out a bit more about the
failure. And I'll report on the progress.
The bug might even be in the test script, rather than perl itself.

Cheers,
Rob

**Comment by khwilliamson** [comment]
On 3/23/20 3:46 PM, sisyphus wrote:
> Hi Jim,
> I believe (unproven) it will be reproducible on any build of perl-5.31.10
> for which $Config{byteorder} is '87654321' (and perhaps also '4321').
> I don't think the failure occurred when I built 5.31.7 on this machine (or
> I would have reported it then), and I didn't build 5.31.8 or 5.31.9.

Note that this test script was added only in November, by this commit

commit a59c5ea3bda874535e4b730b623f5d75c5ab1a18
  Author: Yves Orton <demerphq@gmail.com>
  Date:   Wed Nov 6 00:12:49 2019 +0100

      XS-APItest: add tests for U8TO64_LE() and other hashing macros and 
code

      Includes testing siphash24 and siphash13 properly, especially
      testing against the SipHash 2-4 reference test vector,
      see https://131002.net/siphash/siphash24.c

      See also #17244 where we originally discovered there were no
      tests for the internals of the hashing code and that because
      of it we let slip in a very broken patch to the code.

      Thanks to James E Keenan, Tony Cook and Hugo Van der Sanden
      for support putting this together.

      XS-APItest: fixup issues with # directives

      for some reason the indentation of the #if clauses broke things
      under some builds, but not all. Possibly a ccache issue.

This is the comments from hv_macro.h.  Note that they are wrong at least 
in the claim that there is no such thing as U8TO28_LE; other claims look 
suspicious to me, but I didn't investigate.

/*-----------------------------------------------------------------------------
  * Endianess and util macros
  *
  * The following 3 macros are defined in this section. The other macros 
defined
  * are only needed to help derive these 3.
  *
  * U8TO16_LE(x)   Read a little endian unsigned 32-bit int
  * U8TO32_LE(x)   Read a little endian unsigned 32-bit int
  * U8TO28_LE(x)   Read a little endian unsigned 32-bit int
  * ROTL32(x,r)      Rotate x left by r bits
  * ROTL64(x,r)      Rotate x left by r bits
  * ROTR32(x,r)      Rotate x right by r bits
  * ROTR64(x,r)      Rotate x right by r bits
  */

**Comment by jkeenan** [comment]
On 3/23/20 6:29 PM, Karl Williamson wrote:
> On 3/23/20 3:46 PM, sisyphus wrote:
>  > Hi Jim,
>  > I believe (unproven) it will be reproducible on any build of perl-5.31.10
>  > for which $Config{byteorder} is '87654321' (and perhaps also '4321').
>  > I don't think the failure occurred when I built 5.31.7 on this 
> machine (or
>  > I would have reported it then), and I didn't build 5.31.8 or 5.31.9.
> 
> Note that this test script was added only in November, by this commit
> 
> commit a59c5ea3bda874535e4b730b623f5d75c5ab1a18
> Author: Yves Orton <demerphq@gmail.com>
> Date: Wed Nov 6 00:12:49 2019 +0100
> 
> XS-APItest: add tests for U8TO64_LE() and other hashing macros and
> code
> 

So, @sisyphus, if you can build blead at that commit, that should 
obviate the need for bisection.

Thanks.
jimk

**Comment by sisyphus** [comment]
$ git reset --hard a59c5ea3
HEAD is now at a59c5ea XS-APItest: add tests for U8TO64_LE() and other
hashing macros and code
$ sh Configure -des -Duse64bitall -Dcc="gcc -m64" -Uversiononly -Dusedevel
-Dprefix=/home/sisyphus-sis/blead-a59c5ea3-d && make
.... proceeds to completion
$ ./perl -I./lib ext/XS-APItest/t/hv_macro.t >hvmacro2.txt 2>&1

Running a 'diff -u' reveals that hvmacro2.txt is exactly the same as the
hv_macro.txt that I attached to my original post.
That is, it's the same failures.

If you want me to rebuild with different configure args just let me know
and I'll give it a try - though I think it surely comes down to
$Config{byteorder}, which is not going to be altered by a change to
config_args.

Cheers,
Rob

**Comment by jkeenan** [comment]
@demerphq Can you review the test failures on big-endian platforms discussed in this ticket?

Thank you very much.
Jim Keenan

**Comment by khwilliamson** [comment]
On an HP 31 box, we have

byteorder='4321'

and the tests didn't fail.

I'm trying again with a -Duse64bitall

**Comment by khwilliamson** [comment]
That still passed.  I'm attaching the config for further enlightenment
[config.txt](https://github.com/Perl/perl5/files/4373387/config.txt)

**Comment by sisyphus** [comment]
Ok - I'll see if I can build one that passes the test

Cheers,
Rob

**Comment by sisyphus** [comment]
I first tried a 32-bit build ( ivsize = 4, ivtype = long, byteorder = 4321
), with config_args of just
-des -Dusedevel

With that build hv_macro.t runs only 38 tests, 32 of which fail - including
failures which look very much like issues with endianness:

not ok 33 - U8TO32_LE works as expected (hex bytes:87 f0 e1 d2)
#   Failed test 'U8TO32_LE works as expected (hex bytes:87 f0 e1 d2)'
#   at ext/XS-APItest/t/hv_macro.t line 71.
#          got: '0x87f0e1d2'
#     expected: '0xd2e1f087'

Expanding the config_args to:
-des -Dusedevel -Dcc="gcc -m64"
results in a 64-bit build (ivsize = 8, ivtype = long, byteorder = 87654321).

With that, it's back to failing 52 tests of 63 (as reported initially).

It seems odd that something denoted as "U8TO32_LE" should even be looked at
on a big-endian architecture.
Karl, are your big-endian builds actually running those tests that are
failing for me ?

Any other suggestions on what config_args I should try in order to avoid
the failure ?

If it's only my machine that's being affected in this way, then I think we
can just ignore it. (I'm not all that fussed, personally.)

Cheers,
Rob

**Comment by khwilliamson** [comment]
On 3/24/20 2:26 AM, sisyphus wrote:
> I first tried a 32-bit build ( ivsize = 4, ivtype = long, byteorder = 4321
> ), with config_args of just
> -des -Dusedevel
> 
> With that build hv_macro.t runs only 38 tests, 32 of which fail - including
> failures which look very much like issues with endianness:
> 
> not ok 33 - U8TO32_LE works as expected (hex bytes:87 f0 e1 d2)
> # Failed test 'U8TO32_LE works as expected (hex bytes:87 f0 e1 d2)'
> # at ext/XS-APItest/t/hv_macro.t line 71.
> # got: '0x87f0e1d2'
> # expected: '0xd2e1f087'
> 
> Expanding the config_args to:
> -des -Dusedevel -Dcc="gcc -m64"
> results in a 64-bit build (ivsize = 8, ivtype = long, byteorder = 87654321).
> 
> With that, it's back to failing 52 tests of 63 (as reported initially).
> 
> It seems odd that something denoted as "U8TO32_LE" should even be looked at
> on a big-endian architecture.
> Karl, are your big-endian builds actually running those tests that are
> failing for me ?
> 
> Any other suggestions on what config_args I should try in order to avoid
> the failure ?
> 
> If it's only my machine that's being affected in this way, then I think we
> can just ignore it. (I'm not all that fussed, personally.)
> 
> Cheers,
> Rob
> 
> 
> 
> 
> 
> 
> On Tue, Mar 24, 2020 at 5:46 PM sisyphus <sisyphus359@gmail.com> wrote:
> 
>  > Ok - I'll see if I can build one that passes the test
>  >
>  > Cheers,
>  > Rob
>  >
>  > On Tue, Mar 24, 2020 at 4:44 PM Karl Williamson 
> <notifications@github.com>
>  > wrote:
>  >
>  >> That still passed. I'm attaching the config for further enlightenment
>  >> config.txt <https://github.com/Perl/perl5/files/4373387/config.txt>
>  >>
>  >> —
>  >> You are receiving this because you were mentioned.
>

It's not just you.  Blead is failing the smoke for that platform:
  ../ext/XS-APItest/t/hv_macro.t .............................. FAILED 
2-49 60-61 Non-zero exit status: 52 Bad plan.  You planned 63 tests but 
ran 61.
   [stdio/perlio/locale:en_US.utf8] -Duseithreads -Duse64bitall DEBUGGING
   [stdio/perlio/locale:en_US.utf8] -Duseithreads -Duse64bitall
   [stdio/perlio/locale:en_US.utf8] -Duse64bitall DEBUGGING
   [stdio/perlio/locale:en_US.utf8] -Duse64bitall
~~ ../ext/XS-APItest/t/hv_macro.t .............................. FAILED 
2-33 Non-zero exit status: 32

I don't know why my manual smoke worked.

**Comment by jkeenan** [comment]
The failure may not be limited to big-endian architectures.  Consider this smoke-test report:
http://perl5.test-smoke.org/report/105262

linux 5.3.12-200.fc30.x86_64 [Fedora 30]
ccache g++ version 9.2.1 20190827 (Red Hat 9.2.1-1) (*1)

If someone has (a) Linux, (b) x86_64, (c) g++-9, could you build a perl at 5.31.10 or later with that compiler, with/without threads, then run
```
cd t;./perl harness -v ../ext/XS-APItest/t/hv_macro.t;cd -
```
... to see if you can reproduce the failure reported in the smoke report cited above?

Thank you very much.
Jim Keenan

**Comment by sisyphus** [comment]
That looks to be a quite different to failure to what I'm seeing.
The report that Karl quoted also appears to report a different failure to
mine.
There's no mention of "Non-zero exit status" or "bad plan" in my testing of
hv_macro.t.

BTW, I'm using a fairly old compiler .... gcc-4.8.x.

Cheers,
Rob

**Comment by khwilliamson** [comment]
On 3/24/20 4:12 PM, sisyphus wrote:
> That looks to be a quite different to failure to what I'm seeing.
> The report that Karl quoted also appears to report a different failure to
> mine.
> There's no mention of "Non-zero exit status" or "bad plan" in my testing of
> hv_macro.t.
> 
> BTW, I'm using a fairly old compiler .... gcc-4.8.x.
> 
> Cheers,
> Rob

Note that the code appears to be trying to cope with big endian 
architectures, by swapping bytes.  That might be a fruitful place to 
look at.

**Comment by sisyphus** [comment]
> Note that the code appears to be trying to cope with big endian architectures, by swapping bytes.
> That might be a fruitful place to look at.

Where is it trying to do that ?
I couldn't quickly spot it.

Cheers,
Rob

**Comment by sisyphus** [comment]
Found it !! (What a legend .... not ;-)

Replacing:
        #define U8TO16_LE(ptr)   (_shifted_octet(U16,(ptr),1, 0)|\
                                  _shifted_octet(U16,(ptr),0, 8))

        #define U8TO32_LE(ptr)   (_shifted_octet(U32,(ptr),3, 0)|\
                                  _shifted_octet(U32,(ptr),2, 8)|\
                                  _shifted_octet(U32,(ptr),1,16)|\
                                  _shifted_octet(U32,(ptr),0,24))

        #define U8TO64_LE(ptr)   (_shifted_octet(U64,(ptr),7, 0)|\
                                  _shifted_octet(U64,(ptr),6, 8)|\
                                  _shifted_octet(U64,(ptr),5,16)|\
                                  _shifted_octet(U64,(ptr),4,24)|\
                                  _shifted_octet(U64,(ptr),3,32)|\
                                  _shifted_octet(U64,(ptr),2,40)|\
                                  _shifted_octet(U64,(ptr),1,48)|\
                                  _shifted_octet(U64,(ptr),0,56))
with:

        #define U8TO16_LE(ptr)   (_shifted_octet(U16,(ptr),1, 8)|\
                                  _shifted_octet(U16,(ptr),0, 0))

        #define U8TO32_LE(ptr)   (_shifted_octet(U32,(ptr),3,24)|\
                                  _shifted_octet(U32,(ptr),2,16)|\
                                  _shifted_octet(U32,(ptr),1, 8)|\
                                  _shifted_octet(U32,(ptr),0, 0))

        #define U8TO64_LE(ptr)   (_shifted_octet(U64,(ptr),7,56)|\
                                  _shifted_octet(U64,(ptr),6,48)|\
                                  _shifted_octet(U64,(ptr),5,40)|\
                                  _shifted_octet(U64,(ptr),4,32)|\
                                  _shifted_octet(U64,(ptr),3,24)|\
                                  _shifted_octet(U64,(ptr),2,16)|\
                                  _shifted_octet(U64,(ptr),1, 8)|\
                                  _shifted_octet(U64,(ptr),0, 0))
fixes it for me.
That is, for the big endian architecture only, reverse the order of the second column of numbers.

But what does that do for your big-endian builds Karl ?

Cheers,
Rob

**Comment by khwilliamson** [comment]
Please make a pull request, and I'll make sure it gets smoked on failing machines

**Comment by sisyphus** [comment]
Shall do.
I just want to do some more checks.
Is it correct that the following block of code pertaining to little-endian architectures:

\#ifdef USE_UNALIGNED_PTR_DEREF
\#define U8TO16_LE(ptr)   (*((const U16*)(ptr)))
\#define U8TO32_LE(ptr)   (*((const U32*)(ptr)))
\#define U8TO64_LE(ptr)   (*((const U64*)(ptr)))

is not being reproduced for the big-endian architecture ?
I'll try to check things out a bit more first.

**Comment by sisyphus** [comment]
Getting closer ... for anyone working on this:
It's looking like I don't need a separate "big-endian" block in sv_macro.h
For 32-bit builds I can certainly dispense with the distinction. and just use the code that's in the "little-endian" block for both endiannesses,
For 64-bit builds, although the first 59 tests in hv_macro.t then pass just fine, the remaining 4 (siphash) tests are still failing.
So I'll try tomorrow to work out how to fix that aspect.

Cheers,
Rob

**Comment by sisyphus** [comment]
Still unable to get tests 59 .. 63 (incl) to pass.
I have established that https://131002.net/siphash/siphash24.c works fine on this big-endian machine.
I just need to work out why the perl implementation is playing up.
 
In sv_func.h, there's a macro:
\#define PERL_SIPHASH_FNC(FNC,SIP_ROUNDS,SIP_FINAL_ROUNDS)

Inside that macro, I've tried to add some printf() statements.
I've changed the end section of that macro from:
```
  v0 ^= b;                                  \
                                            \
  v2 ^= 0xff;                               \
                                            \
  SIP_FINAL_ROUNDS                          \
                                            \
  b = v0 ^ v1 ^ v2  ^ v3;                   \
  return b;                                 \
}                                           \
```
to:
```
  v0 ^= b;                                  \
  printf("v0 = %llu %llu\n", v0, (UV)v0);   \
                                            \
  v2 ^= 0xff;                               \
  printf("v2 = %llu %llu\n", v2, (UV)v2);   \
                                            \
  SIP_FINAL_ROUNDS                          \
                                            \
  b = v0 ^ v1 ^ v2  ^ v3;                   \
  printf("b = %llu %llu\n", b, (UV)b);      \
  return b;                                 \
}                                           \
```
That's working nicely on Windows, but on this big-endian Linux machine it won't compile:
```
In file included from hv.h:663:0,
                 from perl.h:3909,
                 from op.c:163:
hv_func.h: In function ‘S_perl_hash_siphash_1_3_with_state_64’:
hv_func.h:275:1: warning: statement with no effect [-Wunused-value]
hv_func.h:275:1: error: expected ‘;’ before ‘_printf_’
hv_func.h:275:1: warning: statement with no effect [-Wunused-value]
hv_func.h:275:1: error: expected ‘;’ before ‘_printf_’
hv_func.h:275:1: warning: statement with no effect [-Wunused-value]
hv_func.h:275:1: error: expected ‘;’ before ‘_printf_’
hv_func.h: In function ‘S_perl_hash_siphash_2_4_with_state_64’:
hv_func.h:281:1: warning: statement with no effect [-Wunused-value]
hv_func.h:281:1: error: expected ‘;’ before ‘_printf_’
hv_func.h:281:1: warning: statement with no effect [-Wunused-value]
hv_func.h:281:1: error: expected ‘;’ before ‘_printf_’
hv_func.h:281:1: warning: statement with no effect [-Wunused-value]
hv_func.h:281:1: error: expected ‘;’ before ‘_printf_’
op.c: In function ‘Perl_ck_eval’:
op.c:12772:9: warning: value computed is not used [-Wunused-value]
make: *** [opmini.o] Error 1
```
Lines 275 and 281 are the lines that call the PERL_SIPHASH_FNC macro.

How do I insert printf statements into that macro such that compilation is not broken on my big-endian Linux machine ?

Cheers,
Rob

**Comment by xenu** [comment]
>How do I insert printf statements into that macro such that compilation is not broken on my big-endian Linux machine ?

It fails because of the following macro inside `nostdio.h`:
```
#define printf     _CANNOT _printf_
```
Either add `#undef printf` to your code or use `PerlIO_printf`.

**Comment by sisyphus** [comment]
Thanks @xenu.
I first tried PerlIO_printf().
I supplied PerlIO_stdout() as its first argument, as that has always worked fine for me in the past whenever I've used PerlIO_printf to print to stdout.
But that produces the following runtime error:

./perl: symbol lookup error: ./lib/auto/XS/APItest/APItest.so: undefined symbol: PerlIO_stdout

What's needed as the first argument ?

I then spent some time trying to get printf() to work ... to no avail.
Having put an "#undef printf" prior to this troublesome macro, I tried a number of things including:
printf("%" UVuf, (UV)x)
and
printf("%llu", (unsigned long long)x)

Is there another rendition I should try ?
Those 2 attempts resulted in:
error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]

Should I simply configure out that troublesome -Werror switch ?
If so, how ?

Cheers,
Rob

**Comment by khwilliamson** [comment]
On 3/27/20 7:48 PM, sisyphus wrote:
> Thanks @xenu <https://github.com/xenu>.
> I first tried PerlIO_printf().
> I supplied PerlIO_stdout() as its first argument, as that has always 
> worked fine for me in the past whenever I've used PerlIO_printf to print 
> to stdout.
> But that produces the following runtime error:
> 
> ./perl: symbol lookup error: ./lib/auto/XS/APItest/APItest.so: undefined 
> symbol: PerlIO_stdout

Here's something that works, as a template

PerlIO_printf(Perl_debug_log, "\nParse position is:%s\n", RExC_parse);

That should obviate the need for anything else.

You can wrap that in a

DEBUG_U(PerlIO_printf(Perl_debug_log, "\nParse position is:%s\n", 
RExC_parse));

And it won't print unless -DU is specified on the command line.
(This all needs to be compiled with -DDEBUGGING)

**Comment by sisyphus** [comment]
I've come up with amendments to hv_macro.h and ext/XS-APItest/APItest.xs that fix the failures.
I've forked blead by hitting the "Fork" button.
I've cloned my fork to my local machine:

$ git clone git@github.com:sisyphus/perl5.git bleadfork

In my local bleadfork repo I've replaced hv_macro.h and ext/XS-APItest/APItest.xs with the fixed versions of those files.
And I've committed and pushed my changes back to my fork on github:

sisyphus@Owner-PC311012 ~/git/bleadfork
$ git commit ext/XS-APItest/APItes.xs --file=mAPItest_t.txt
error: pathspec 'ext/XS-APItest/APItes.xs' did not match any file(s) known to git.

sisyphus@Owner-PC311012 ~/git/bleadfork
$ git commit ext/XS-APItest/APItest.xs --file=mAPItest_t.txt
[blead 1995506] ext/XS-APItest/APItest.xs - accommodate siphash issues regarding endianness.
 1 file changed, 107 insertions(+), 12 deletions(-)
 mode change 100644 => 100755 ext/XS-APItest/APItest.xs

sisyphus@Owner-PC311012 ~/git/bleadfork
$ git push
Counting objects: 8, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 1.80 KiB | 0 bytes/s, done.
Total 8 (delta 6), reused 0 (delta 0)
remote: Resolving deltas: 100% (6/6), completed with 5 local objects.
To git@github.com:sisyphus/perl5.git
   f12bbb7..1995506  blead -> blead

But when I try to make a pull request I get nowhere.

I've reached the point where the page I'm on is showing up as:
https://github.com/Perl/perl5/compare/Perl:blead...Perl:sisyphus

where the 2 pertinent boxes are showing (left) "base:blead" and (right) "compare:sisyphus" but that isn't right because it's saying that "There isn't anything to compare".
I'm stumped as to what it is that I need to do to get the PR to lock in.

Cheers,
Rob

**Comment by sisyphus** [comment]
Ooops - probably not important, but I missed out on the copy'n'paste of the hv_macro.h commit, which preceded the APItest.xs commit:

$ git commit hv_macro.h --file=mhv_macro_h.txt
[blead 85bbd28] hv_macro.h - make it the same code for all endiannesses.
 1 file changed, 19 deletions(-)
 mode change 100644 => 100755 hv_macro.h

**Comment by khwilliamson** [comment]
On 3/31/20 4:12 AM, sisyphus wrote:
> Ooops - probably not important, but I missed out on the copy'n'paste of 
> the hv_macro.h commit, which preceded the APItest.xs commit:
> 
> $ git commit hv_macro.h --file=mhv_macro_h.txt
> [blead 85bbd28 
> <https://github.com/Perl/perl5/commit/85bbd28f53e4a7899dc113adabe8f96d973b6197>] 
> hv_macro.h - make it the same code for all endiannesses.
> 1 file changed, 19 deletions(-)
> mode change 100644 => 100755 hv_macro.h
> 

I went through a few contortions, but have pushed your patches to
http://perl.develop-help.com/?b=smoke-me%2Fkhw-sisyphus

There are porting failures because those files should not have the 
execute bit set.  I changed that locally and bumped a VERSION number, 
then tested on 4 bigendian boxes that I have access to.  Things worked 
on 3, and the fourth is painfully slow, so it hasn't gotten to the 
failing tests yet.

So, I think it is basically ready to merge.  But I would like further 
explanation in the commit message as to why it is ok to remove the 
special endianness handling.  I think I understand, but it would be good 
for future maintainers to have a clear explanation of what was wrong and 
why this is a good fix.

**Comment by Grinnz** [comment]
Go to your fork at https://github.com/sisyphus/perl5 and the branch you want to make a pull request out of, and there is a pull request button.

**Comment by dur-randir** [comment]
https://github.com/Perl/perl5/compare/Perl:blead...sisyphus:blead is the proper link to pull your changes in.

**Comment by sisyphus** [comment]
> There are porting failures because those files should not have the execute bit set

Hmm ... that's happened before, when I start messing with files on Linux.
Is there a chmod command that I can run on the amended files to make sure that I haven't mucked that execute bit up ?

> But I would like further explanation in the commit message as to why it is ok to remove the special endianness handling.

A couple of points:
The original hv_macro.h had U8TO64_LE return different values between big-endian and little-endian.
Removing the endianness considerations from hv_macro.h means that U8TO64_LE returns the same value for both endians.
And this is exactly the same behaviour as the U8TO64_LE implementation in
https://131002.net/siphash/siphash24.c 
(which works fine on both endians).

Additionally, it was just the first part of the way I found to get results that showed that the process was working as intended on big-endian machines.
And I haven't found a way of demonstrating that with hv_macro.h in its original form, though there may well be one.

So, I guess what makes it ok to remove the endianness consideration in hv_macro.h is that it's unprecedented (afaik), unnecessary, and unhelpful (afaik).
Thinking about it, the "unnecessary" part has actually been proven by the fact that the APItest.xs results have now been tied to the original test vectors without the need to rewrite U8TO64_LE for big endian architecture.

So, even if at some stage in the future we feel the need to have the hashing return *identical* results on different endians, we'll know that we don't have to alter U8TO64_LE and friends.
All we have to do is follow the advice in the comments I added in APItest.xs.
(Of course, that doesn't preclude the possibility that the recommended advice might be simpler to implement if we make some appropriate alteration to U8TO64_LE and friends.)

So .... my extra comments for the commit would be something like:
 "The endianness consideration in hv_macro.h is demonstrably unnecessary, seemingly unprecedented, and not of any apparent use.
Removing it simplifies the validation of the hashing process conducted in APItest.xs."

I'll continue speculative testing to see if there is *another* way that U8TO64_LE can be written for big-endian architectures such that it *is* useful.

Cheers,
Rob

**Comment by khwilliamson** [comment]
> Hmm ... that's happened before, when I start messing with files on Linux.
Is there a chmod command that I can run on the amended files to make sure that I haven't mucked that execute bit up ?

If you run Unix chmod on the files, it causes git to mark them as modified, so you just have to commit them to get that fixed.

> So .... my extra comments for the commit would be something like:
"The endianness consideration in hv_macro.h is demonstrably unnecessary, seemingly unprecedented, and not of any apparent use.
Removing it simplifies the validation of the hashing process conducted in APItest.xs."

That sounds fine, although I like the detail in what you said above that.  You could just say, for further info, see this ticket.

**Comment by sisyphus** [comment]
Do you still want a pull request ?
Thinking back, that execute bit has been set in the past by simply running
dos2unix and/or unix2dos. So I probably just need to avoid doing that.

Cheers,
Rob

**Comment by khwilliamson** [comment]
On 4/1/20 7:51 PM, sisyphus wrote:
> Do you still want a pull request ?
> Thinking back, that execute bit has been set in the past by simply running
> dos2unix and/or unix2dos. So I probably just need to avoid doing that.
> 
> Cheers,
> Rob

I would like a pull request

**Comment by khwilliamson** [comment]
[https://github.com/Perl/perl5/commit/ccb5da6dfde4d376aa25623b9fae885ad86ce728](url) fixed this

Thanks

**Comment by demerphq** [comment]
The patch that was applied in response to this issue seems to have broken HPUX.

I would like to revert it. Can someone explain why I shouldn't? I don't understand the rationale provided in this thread.

See: [https://tux.nl/perl5/smoke/hpux1111/511/gcc/smoke.log](https://tux.nl/perl5/smoke/hpux1111/511/gcc/smoke.log)

```
#   Failed test 'U8TO16_LE works as expected (hex bytes:12 34)'
#   at t/hv_macro.t line 65.
#          got: '0x1234'
#     expected: '0x3412'

#   Failed test 'U8TO32_LE works as expected (hex bytes:12 34 56 78)'
#   at t/hv_macro.t line 71.
#          got: '0x12345678'
#     expected: '0x78563412'

#   Failed test 'U8TO64_LE works as expected (hex bytes:12 34 56 78 9a bc de f0)'
#   at t/hv_macro.t line 78.
#          got: '0x123456789abcdef0'
#     expected: '0xf0debc9a78563412'

#   Failed test 'U8TO16_LE works as expected (hex bytes:34 56)'
#   at t/hv_macro.t line 65.
#          got: '0x3456'
#     expected: '0x5634'

#   Failed test 'U8TO32_LE works as expected (hex bytes:34 56 78 9a)'
#   at t/hv_macro.t line 71.
#          got: '0x3456789a'
#     expected: '0x9a785634'

#   Failed test 'U8TO64_LE works as expected (hex bytes:34 56 78 9a bc de f0 12)'
#   at t/hv_macro.t line 78.
#          got: '0x3456789abcdef012'
#     expected: '0x12f0debc9a785634'
```
And yes, I definitely definitely expect Siphash to return *exactly* the same thing on bigendian or little endian machines. If it doesn't then something is very wrong.

**Comment by demerphq** [comment]
I wont revert it. But there is something wrong with the patch. I will make a new PR. 

The problem was the patch changed *both* direct memory loads and shifted loads. The shifted loads were wrong. However the direct memory access can only be used on little endian machines.

**Comment by demerphq** [comment]
BTW, I just discovered that probably your patch actually FIXED the smoke report I referred to. My bad for the confusion. 

However if something big-endian allows unalgined loads, then it would do the wrong thing and fail tests without the patch at:

https://github.com/Perl/perl5/pull/19530

Sorry for the noise.
