### ISSUE TITLE
Potential dereferencing of freed pointer in op.c

### ISSUE THREAD

**Issue by brodafly** [Perl/perl5#17675]
Hello!

We have a Coverity scan setup for the perl source code and it detected a potential issue for version 5.30.0. I suppose it will be detected in later verisons as well.

The issue is with the function 'S_newGIVWHENOP' defined in op.c in which the scan warns that it is possible to try and dereference the already freed pointer 'enterop'. The pointer can apparently be freed during the call to 'CHECKOP(enter_opcode, enterop)' and the exact warning from the scan is: "freed_arg: *PL_check[enter_opcode] frees enterop. (The function pointer resolves to Perl_ck_backtick". After the 'CHECKOP' call follow attempts to dereference 'enterop' which raise the complaint from the scan.

Do you think there is any validity to this issue or is it a false positive? One way of silencing the issue would probably involve checking if the pointer actually points to smething before derefing it [1].

What are your thoughts on this issue, guys and gals?

Best regards!
Stoyan

[1]
```
--- op.c.orig	2020-03-26 12:33:28.000000000 +0200
+++ op.c	2020-03-26 12:37:07.000000000 +0200
@@ -10351,8 +10351,11 @@
				       entergiven and enterwhen both
				       use ck_null() */

-    enterop->op_next = LINKLIST(block);
-    block->op_next = enterop->op_other = o;
+    if (enterop != NULL) {
+	 enterop->op_next  = LINKLIST(block);
+	 enterop->op_other = o;
+    }
+    block->op_next = o;

     return o;
 }```

**Comment by jkeenan** [comment]
> Hello!
> 
> We have a Coverity scan setup for the perl source code and it detected a potential issue for version 5.30.0. I suppose it will be detected in later verisons as well.
> 
> The issue is with the function 'S_newGIVWHENOP' defined in op.c in which the scan warns that it is possible to try and dereference the already freed pointer 'enterop'. The pointer can apparently be freed during the call to 'CHECKOP(enter_opcode, enterop)' and the exact warning from the scan is: "freed_arg: *PL_check[enter_opcode] frees enterop. (The function pointer resolves to Perl_ck_backtick". After the 'CHECKOP' call follow attempts to dereference 'enterop' which raise the complaint from the scan.
> 
> Do you think there is any validity to this issue or is it a false positive? One way of silencing the issue would probably involve checking if the pointer actually points to smething before derefing it [1].
> 
> What are your thoughts on this issue, guys and gals?
> 
> Best regards!
> Stoyan
> 
> [1]
> 
> ```
> --- op.c.orig	2020-03-26 12:33:28.000000000 +0200
> +++ op.c	2020-03-26 12:37:07.000000000 +0200
> @@ -10351,8 +10351,11 @@
> 				       entergiven and enterwhen both
> 				       use ck_null() */
> 
> -    enterop->op_next = LINKLIST(block);
> -    block->op_next = enterop->op_other = o;
> +    if (enterop != NULL) {
> +	 enterop->op_next  = LINKLIST(block);
> +	 enterop->op_other = o;
> +    }
> +    block->op_next = o;
> 
>      return o;
>  }```
> ```

Others will evaluate the patch, but in the meantime I have created a branch for smoke-testing it:
smoke-me/jkeenan/ghi-17675-pointer

**Comment by ilmari** [comment]
I don't see how the `CHECKOP(enter_opcode, enterop)` call can resolve to `Perl_ck_backtick` when `S_newGIVWHENOP` is only ever called with `OP_ENTERGIVEN` and `OP_ENTERWHEN`, both of which use `ck_null` (as indicated by the comment).

I guess Coverity assumes that `enter_opcode` could be any valid `PL_check` index and checks all the check functions, despite this being a static function only called with constant `enter_opcode` arguments.

**Comment by brodafly** [comment]
> I don't see how the `CHECKOP(enter_opcode, enterop)` call can resolve to `Perl_ck_backtick` when `S_newGIVWHENOP` is only ever called with `OP_ENTERGIVEN` and `OP_ENTERWHEN`, both of which use `ck_null` (as indicated by the comment).
> 
> I guess Coverity assumes that `enter_opcode` could be any valid `PL_check` index and checks all the check functions, despite this being a static function only called with constant `enter_opcode` arguments.

Thanks for the input! From what I understand this can safely be marked as a false positive in Coverity. I don't suppose any changes in S_newGIVWHENOP should be made in this case.

**Comment by tonycoz** [comment]
What options are you building perl with? I don't see this in our Coverity runs.

**Comment by brodafly** [comment]
Hello,

These are the args passed to Configure which is invoked through a python script, hence the synthax:

```
configure_command = [
   './Configure',
    '-der',
    '-Dmyhostname=buildhost',
    '-Dmydomain=.com',
    '-Dprivlib=.../../lib',
    '-Dsitelib=.../../lib',
    '-Darchlib=.../../lib',
    '-Dsitearch=.../../lib',
    '-Dnoextensions=GDBM_File NDBM_File ODBM_File SDBM_File',
    '-Ddynamic_ext=MIME/Base64 Socket IO Time/HiRes Cwd Encode Data/Dumper Compress/Raw/Zlib Digest/SHA',
    '-Dusethreads',
    '-Duseshrplib',
    '-Duserelocatableinc',
    '-Dprefix=%s' % self.the_install_dir,
]
```
Is that the info you needed?

Best regards,
Stoyan

**Comment by tonycoz** [comment]
> Is that the info you needed?

It is, thanks.

The main difference I can see that could have an effect is that I build with -DDEBUGGING.

Since this issue is a false positive, I'm closing it.
