### ISSUE TITLE
Version v5.26.1 Error when using !#/usr/bin/perl -F

### ISSUE THREAD

**Issue by shrisn** [Perl/perl5#17684]
ErroR:
Error when using perl version 5.26.1 with -F option in the perl script.

Reproduce:
cat test1.pl 
#!/usr/bin/perl -F
print("Test\n");
print("$ARGV[0]\n");

Run: 
./test1.pl test
Can't open test: No such file or directory.

Version:
/usr/bin/perl -v

This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-thread-multi

Copyright 1987-2017, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

**Comment by shlomif** [comment]
Hi @shrisn !
On Mon, 30 Mar 2020 01:33:36 -0700
shrisn <notifications@github.com> wrote:

> ErroR:
> Error when using perl version 5.26.1 with -F option in the perl script.
> 
> Reproduce:
> cat test1.pl 
> #!/usr/bin/perl -F
> print("Test\n");
> print("$ARGV[0]\n");
> 
> Run: 
> ./test1.pl test
> Can't open test: No such file or directory.
> 

This seems expected and reasonable given 
https://perldoc.pl/perlrun.html (perldoc perlrun):

$ perl -F -E '' notexist
Can't open notexist: No such file or directory.

So I think it is not a bug.

> Version:
> /usr/bin/perl -v
> 
> This is perl 5, version 26, subversion 1 (v5.26.1) built for
> x86_64-linux-thread-multi
> 
> Copyright 1987-2017, Larry Wall
> 
> Perl may be copied only under the terms of either the Artistic License or the
> GNU General Public License, which may be found in the Perl 5 source kit.
> 
> Complete documentation for Perl, including FAQ lists, should be found on
> this system using "man perl" or "perldoc perl".  If you have access to the
> Internet, point your browser at http://www.perl.org/, the Perl Home Page.
> 
> 



-- 

Shlomi Fish       https://www.shlomifish.org/
Apple Inc. is Evil - https://www.shlomifish.org/open-source/anti/apple/

Stray XSLT code causes more deaths than road accidents.
    — http://www.shlomifish.org/humour/bits/facts/XSLT/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shrisn** [comment]
Hi @shlomif ,

Thank you. But the same thing works fine when I run from the perl version 5.10.1
 /usr/bin/perl -v

This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi
Copyright 1987-2009, Larry Wall

cat test.pl 
#!/usr/bin/perl -F
print("Test\n");
print("$ARGV[0]\n");

Output:
./test.pl string
Test
string

It does not throw any error.

**Comment by shlomif** [comment]
On Mon, 30 Mar 2020 02:43:38 -0700
shrisn <notifications@github.com> wrote:

> Hi @shlomif ,
> 
> Thank you. But the same thing works fine when I run from the perl version
> 5.10.1 /usr/bin/perl -v
>

Hi @shrisn ,

I think in newer perls -F implies -n and -a or similar (for convenience). So it
was done on purpose.
 
> This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi
> Copyright 1987-2009, Larry Wall
> 
> cat test.pl 
> #!/usr/bin/perl -F
> print("Test\n");
> print("$ARGV[0]\n");
> 
> Output:
> ./test.pl string
> Test
> string
> 
> It does not throw any error.
> 
> 



-- 

Shlomi Fish       https://www.shlomifish.org/
Escape from GNU Autohell - http://www.shlomifish.org/open-source/anti/autohell/

It takes Summer Glau exactly a minute to write a rebuttal like in
xkcd: “Venting”, and she would sign it as Chuck Norris.
    — http://www.shlomifish.org/humour/bits/facts/Summer-Glau/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by tonycoz** [comment]
-F implying -n was added in 5.20, as @shlomif says, this isn't a bug.
