### ISSUE TITLE
[doc] Dead link on wall.org

### ISSUE THREAD

**Issue by jeffythedragonslayer** [Perl/perl5#17691]
A few years ago, I briefly thought that Perl was a no longer under active development due to this dead link:

http://www.wall.org/~larry/perl.html

**Comment by Grinnz** [comment]
Is this linked somewhere in the documentation? wall.org is Larry Wall's personal website, and so the Perl developers have no responsibility for it.

**Comment by shlomif** [comment]
Hi Dan, Jeff & all!

On Fri, 03 Apr 2020 23:34:01 -0700
Dan Book <notifications@github.com> wrote:

> Is this linked somewhere in the documentation? wall.org is Larry Wall's
> personal website, and so the Perl developers have no responsibility for it.
> 

Running:

```
[shlomif@telaviv1 perl]$ git log -p | grep larry/perl
```

in the perl5 repo gives no results.

-- 

Shlomi Fish       https://www.shlomifish.org/
Funny Anti-Terrorism Story - https://shlom.in/enemy

“The best time to plant a tree was 20 years ago. The second best time is now.”
    – A Reported Proverb

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by jeffythedragonslayer** [comment]
His personal website appears in the manpage as an email address domain under AUTHORS, but not that particular page directly.

**Comment by shlomif** [comment]
On Sat, 04 Apr 2020 00:18:44 -0700
Jeff Linahan <notifications@github.com> wrote:

> His personal website appears in the manpage as an email address domain under
> AUTHORS, but not that particular page directly.
> 

Apparently there is a link on this page: http://www.wall.org/~larry/ - titled
"Perl". You'll need to contact Larry Wall about restoring it.

-- 

Shlomi Fish       https://www.shlomifish.org/
Escape from GNU Autohell - http://www.shlomifish.org/open-source/anti/autohell/

Larry Wall has been changing the world. By modifying its very source code.
    — http://www.shlomifish.org/humour/bits/facts/Larry-Wall/

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by jkeenan** [comment]
> On Sat, 04 Apr 2020 00:18:44 -0700 Jeff Linahan ***@***.***> wrote: His personal website appears in the manpage as an email address domain under AUTHORS, but not that particular page directly.
> Apparently there is a link on this page: http://www.wall.org/~larry/ - titled "Perl". You'll need to contact Larry Wall about restoring it.
> […](#)
> -- Shlomi Fish https://www.shlomifish.org/ Escape from GNU Autohell - http://www.shlomifish.org/open-source/anti/autohell/ Larry Wall has been changing the world. By modifying its very source code. — http://www.shlomifish.org/humour/bits/facts/Larry-Wall/ Please reply to list if it's a mailing list post - http://shlom.in/reply .

There's no bug in Perl 5 here, so, closing.

Thank you very much.
Jim Keenan

**Comment by jeffythedragonslayer** [comment]
Alright, I send him an email.
