### ISSUE TITLE
[feature] Allow ".=" or "push" to "append" to hashes

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#17702]
We can do
```
my %h = (
    a => 1,
    b => 2,
    c => 3,
    d => 4,
    e => 5,
    f => 6
);
```
But let's say we first do just
```
my %h = (
    a => 1,
    b => 2,
    c => 3,
);
```
Alas we can't come along later and do
```
%h .= (
    d => 4,
    e => 5,
    f => 6
);
```
Because ".=" can't be used like that...yet (too bad!)

(Well, with minimal disruption of our file, at least we can do:)

```
%h= (
    %h,
    d => 4,
    e => 5,
    f => 6
);
```

**Comment by shlomif** [comment]
@jidanni : wouldn't `push %myhash, @LIST;` be better, given https://perldoc.perl.org/functions/push.html ?

**Comment by jidanni** [comment]
Sounds great. Then one day we could do
```
push %h,  
    d => 4,
    e => 5,
    f => 6;
```

**Comment by jidanni** [comment]
No need to add them "at the [end](https://stackoverflow.com/a/31387390/1118719)" of the hash, as hashes have no end / order. Just add them.

Anyway, we could finally use almost the same syntax we used to give birth to the hash,
instead of having to fall back to the many statement version:
`$h{d}=4; $h{e}=5; $h{f}=6;`

**Comment by jkeenan** [comment]
No syntax that implies that one can "push" onto a hash or "append" to a hash would be a good idea.  Both carry an implication that hashes are internally ordered.  As pointed out above, they are not.

Hence, I oppose this feature request.

Thank you very much.
Jim Keenan

**Comment by Grinnz** [comment]
The original solution shown of `%hash = (%hash, ....)` seems perfectly clear to me already.

**Comment by Grinnz** [comment]
> Anyway, we could finally use almost the same syntax we used to give birth to the hash,
> instead of having to fall back to the many statement version:
> `$h{d}=4; $h{e}=5; $h{f}=6;`

This can be written in one statement: `@h{'d','e','f'} = (4, 5, 6);`

**Comment by jidanni** [comment]
> The original solution shown of `%hash = (%hash, ....)` seems perfectly clear to me already.

OK, I hope it is documented somewhere on perldsc, etc.
Anyway it is still rather wasteful that we have to haul back in all the current members of the hash there on the right side of the equation, just to add more members (actually resetting the whole hash from "scratch".)

**Comment by jidanni** [comment]
> This can be written in one statement: `@h{'d','e','f'} = (4, 5, 6);`

OK, this is a single operation, and doesn't remake the whole hash from scratch... So the only thing regrettable about it is that it is radically different than how we made the first (a b c) part of the hash...

Anyway, hashes need a way for people to 'add' an even number of elements to them.

**Comment by richardleach** [comment]
> > This can be written in one statement: `@h{'d','e','f'} = (4, 5, 6);`
> 
> OK, this is a single operation, and doesn't remake the whole hash from scratch... So the only thing regrettable about it is that it is radically different than how we made the first (a b c) part of the hash...
> 

Different, but slices are documented in _perldata_ and provide much more functionality than just this use case, so it's arguably beneficial for users to become familiar with slices.

> Anyway, hashes need a way for people to 'add' an even number of elements to them.

As in `@h{'d','e'} = (4, 5);` or something different?

**Comment by jidanni** [comment]
OK, that's
```
$ perldoc -q merge #perlfaq4 How do I merge two hashes? ...
@hash1{ keys %hash2 } = values %hash2;
```
Good.
