### ISSUE TITLE
[doc] Document if "... for ..." can(not) be used with "my"

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#17703]
perlsyn mentions
```
 for (@ary) { s/foo/bar/ }
```
but it doesn't mention that this can also be written
```
s/foo/bar/ for @ary;
```
a fact that certainly should be mentioned there on perl**syn**!

(Sure, it is already mentioned on some other man page, that nobody can
find, as which page it is is not mentioned there on perlsyn's for/foreach discussion.)

OK, once that is fixed we note that perlsyn also mentions
```
for my $elem (@elements) {
           $elem *= 2;
   }
```
which we will now know can also be written
```
$elem *= 2 for my $elem @elements;
```
But of course that is a **syntax** error, and perl**syn** doesn't say how to
write it properly, or if it can be written at all.

**Comment by Grinnz** [comment]
Postfix modifiers are documented in perlsyn under https://perldoc.pl/perlsyn#Statement-Modifiers, which does not show that postfix for can specify a lexical variable.

**Comment by jidanni** [comment]
OK we see
```
       The "for(each)" modifier is an iterator: it
       executes the statement once for each item in the
       LIST (with $_ aliased to each item in turn).

           print "Hello $_!\n" for qw(world Dolly nurse);

       NOTE: The behaviour of a "my", "state", or "our"
       modified with a statement modifier conditional
       or loop construct (for example, __"my $x if
       ..."__) is undefined...
```
However it needs to one day finally mention that our particular __my__ case here is __not allowed__.

**Comment by jidanni** [comment]
I see you added
>There is no syntax to specify a C-style for loop or a lexically scoped
>iteration variable in this form.

That's great. But I think you also need to add
>e.g., ....

examples, else the reader might not grasp the legalese.

**Comment by Grinnz** [comment]
There is no example to give, because the syntax does not exist.

**Comment by jidanni** [comment]
Then simply add:

Note that one cannot convert
- for $j (1..4){print $j} 
- for my $j (1..4){print $j}

into postfix form, unless one is willing to give up the "my" and "$j":

- print for 1..4;

**Comment by kozachkov** [comment]
> Then simply add:
> 
> Note that one cannot convert
> 
> * for $j (1..4){print $j}
> * for my $j (1..4){print $j}
> 
> into postfix form, unless one is willing to give up the "my" and "$j":
> 
> * print for 1..4;

Nevertheless it is possible to use postfix form and $j together if we assign $_ to $j in the first step and add the second one by 'and' operator.

```
my $j;
$j=$_ and print $j for (1..4);
```

**Comment by jidanni** [comment]
OK, but

```
$ perl -we 'my $j; $j = $_ and print $j for 1 .. 4;'
1234
```

is the same as

```
$ perl -we 'my $j; for ( 1 .. 4 ) { $j = $_ and print $j; }'
1234
```

which nobody would want to do.
