### ISSUE TITLE
Building with -DNO_LOCALE_NUMERIC has an error in numeric.c

### ISSUE THREAD

**Issue by afresh1** [Perl/perl5#17725]
Module:

**Description**

There is a problem building perl with `NO_LOCALE_NUMERIC` defined.  This is similar to #16771, but apparently I was mistaken that it was fixed in v5.30.0 as I have the problem on that tag as well.

This could be a gcc vs clang issue as OpenBSD switched the system compiler to clang since I reported #16771 as fixed.

```
$ ./Configure -de -Accflags='-DNO_LOCALE_NUMERIC' -Dusedevel && make
...
cc -c -DPERL_CORE -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_FORTIFY_SOURCE=2 -DNO_LOCALE_NUMERIC -std=c89 -O2 -Wall -Werror=pointer-arith -Wextra -Wc++-compat -Wwrite-strings -Werror=declaration-after-statement numeric.c
numeric.c:38:8: error: ISO C90 forbids mixing declarations and code [-Werror,-Wdeclaration-after-statement]
    NV result;
       ^
1 error generated.
*** Error 1 in /home/afresh1/perl (makefile:246 'numeric.o': @`sh  cflags "optimize='-O2'" numeric.o`  numeric.c)
```

**Steps to Reproduce**

./Configure -de -Accflags='-DNO_LOCALE_NUMERIC' -Dusedevel && make

**Expected behavior**

I expect perl to build successfully and be able to run `make test`

**Perl configuration**

I don't get a working perl from this,  but it is blead@182d7c4db2d316d74a275009ee5e30226cb0121d, but I also see the issue on the v5.30.0 and v5.30.2 tags.

**Comment by hvds** [comment]
Ugh, clang appears to object to the empty statement before the declaration. `-E` output has:
```
static __inline__ NV
S_strtod( const char * const s, char ** e)
{
                                           ;
    NV result;
```

Swapping the two lines is enough to get past that, but it feels like a clang bug to me, and if we had two such lines hiding optional declarations behind macros it would become a bigger problem. Do we have some alternative "empty" macro we [c/sh]ould be using instead?

```
--- a/numeric.c
+++ b/numeric.c
@@ -34,8 +34,8 @@ values, including such things as replacements for the OS's atof() function
 PERL_STATIC_INLINE NV
 S_strtod(pTHX_ const char * const s, char ** e)
 {
-    DECLARATION_FOR_LC_NUMERIC_MANIPULATION;
     NV result;
+    DECLARATION_FOR_LC_NUMERIC_MANIPULATION;
 
     STORE_LC_NUMERIC_SET_TO_NEEDED();
 
```
