### ISSUE TITLE
interesting parsing error

### ISSUE THREAD

**Issue by karenetheridge** [Perl/perl5#17767]
This issue can be seen on perl 5.31.11 and I've also reproduced it with 5.26.3 so it's not a new blocker issue.

The original offending line and error are:

    my @test_files = sort path(File::ShareDir::dist_dir('Foo-Bar'), 'tests')->children;
    > Can't locate object method "children" via package "tests" (perhaps you forgot to load "tests"?)

(where `path` comes from Path::Tiny), but I boiled this down to not need extra modules thusly:

```
use strict;
use warnings;

package Foo {
  sub children { 'a', 'b', 'c' }
}

sub path { bless {}, 'Foo' }
sub dir { $_[0].'/hello' }

my @files = sort path(dir('foo'), 'bar')->children;
```

and produces the error:

    Can't locate object method "children" via package "bar" (perhaps you forgot to load "bar"?) at repro.pl line 11.

Grinnz helpfully suggested adding `+` to the expression passed to `sort`, which makes the error go away. Nevertheless, this is an interesting parsing bug that might warrant a look.

**Comment by haarg** [comment]
This doesn't seem like a bug.  It's using `path` as the comparison routine, and `(dir('foo'), 'bar')->children` as the list to sort.  This puts the parenthesis in scalar context, returning item after the last comma.  This sucks, but that's how sort works, and how it's documented to work.

`perlfunc` states:

> If instead you want to sort the array `@key` with the comparison routine find_records() then you can use:
> ```
> my @contact = sort { find_records() } @key;
> my @contact = sort find_records(@key);
> my @contact = sort(find_records @key);
> my @contact = sort(find_records (@key));
> ```

**Comment by tonycoz** [comment]
Yes, this is the documented behaviour, closing.
