### ISSUE TITLE
Perl_do_ncmp is not optimized for comparisons with NVs

### ISSUE THREAD

**Issue by richardleach** [Perl/perl5#17778]
**Description**
Comparison operators, such as pp_le, have a fast path for when both operands are IVs. Comparisons where one or both operands is a NV are surely also common, but better optimization for this case may be possible.

These ops call _Perl_do_ncmp()_, which starts with:
`    if (SvIV_please_nomg(right) && SvIV_please_nomg(left)) {`

For a NVs, _SvIV_please_nomg_() will result in a call to _Perl_sv_2iv_flags()_, which:
* checks the SV for magic
* checks if the SV is a RV
* checks if the SV is a FMB string or regex
* checks for SvTHINKFIRST
* finally calls S_sv_2iuv_common to upgrade the NV to a PVNV (see also #17777)

A comparable logic ordering exists in _Perl_sv_2uv_flags()_ and _Perl_sv_2nv_flags()_.

**Suggestion/Query**
Can the simple NV case be moved to the top of the list?

**Comment by richardleach** [comment]
For the both-NVs case, something like this approach might work:
```
PP(pp_lt)
{
    dSP;
    SV *left, *right;
    /* flags are ON in this U32 if they are ON in both sets of operand flags. */
    /* The exception is SVf_IVisUV, which is ON if enabled for either operand.*/
    U32 flags;
    
    tryAMAGICbin_MG(lt_amg, AMGf_numeric);
    right = POPs;
    left  = TOPs;
    flags = ( SvFLAGS(left) & SvFLAGS(right)) | 
        ((SvFLAGS(left) | SvFLAGS(right)) & SVf_IVisUV);

    SETs(boolSV(
    ((flags & (SVf_IOK|SVf_IVisUV)) == SVf_IOK)
	    ? (SvIVX(left) < SvIVX(right))
    : (flags & SVf_NOK)
        ? (SvNVX(left) < SvNVX(right))
	: (do_ncmp(left, right) == -1)
    ));
    RETURN;
```
All tests pass on a Linux x64-86 build. Still need to benchmark and also check whether the compiler can optimize for tryAMAGICbin_MG() also effectively deriving (SvFLAGS(left) | SvFLAGS(right)).

This results in there being a few more instructions, but one fewer branch, in the both-IV scenario.

If both operands are NVs, there are two differences to the way blead operates:
* a NV comparison will always occur, even if lossless conversion to IV followed by IV comparison could occur
* the RHS NV will not get upgraded to a PVNV

Do either of these matter for comparison operators?

**Comment by tonycoz** [comment]
This looks reasonable to me.

**Comment by richardleach** [comment]
Thanks Tony.

Still comparing, but from _perf_ and looking at the disassembly, it's looking like not combining the flags may actually produce better results:
```
...
    flags_and = SvFLAGS(left) & SvFLAGS(right);
    flags_or = SvFLAGS(left)|SvFLAGS(right);

    SETs(boolSV(
    ( (flags_and & SVf_IOK) && ((flags_or & SVf_IVisUV) ==0 ) )
	    ? (SvIVX(left) != SvIVX(right))
    : (flags_and & SVf_NOK)
            ? (SvNVX(left) != SvNVX(right))
...
```

**Comment by richardleach** [comment]
_Edit: discussed further in #17777. The mixed IV/NV case doesn't seem to merit further experimentation._ 

For the mixed IV/NV case, as well as for when _pp_sort_ (which has a fast case for IVs but not for NVs, looks hairier to add one there) is operating on NVs:

1. Could the _SvIV_please_nomg(sv)_ macro be changed from:
```
#define SvIV_please_nomg(sv) \
	(!(SvFLAGS(sv) & (SVf_IOK|SVp_IOK)) && (SvFLAGS(sv) & (SVf_NOK|SVf_POK)) \
	    ? (sv_2iv_flags(sv, 0), SvIOK(sv))	  \
	    : SvIOK(sv))
```
to something like:
```
#define SvIV_please_nomg(sv) \
	(!(SvFLAGS(sv) & (SVf_IOK|SVp_IOK)) && ( (SvFLAGS(sv) & (SVf_NOK|SVs_SMG|SVf_THINKFIRST) == SVf_NOK)) \
            ? ( sv_2iuv_common(aTHX_ sv) )      \
            : (SvFLAGS(sv) & (SVf_NOK|SVf_POK))   \
	    ? (sv_2iv_flags(sv, 0), SvIOK(sv))	  \
	    : SvIOK(sv))
```
The idea being that plain NVs bypass the multiple irrelevant checks in _sv_2iv_flags_ and go straight to _sv_2iuv_common_. (I haven't had chance to build and benchmark this yet.)

2. Possible alternatives for avoiding premature work on NVs that cannot be losslessly converted:

(i) modify _sv_2iuv_common_'s `(SvNOKp(sv))` branch so that it uses temporary IV/UV variables and defers making any changes to the incoming NV/PVNV until lossless conversion has been found to be possible.

(ii) use _S_lossless_NV_to_IV_ as a basis for a _S_lossless_NV_to_IV_or_UV_ inline function, which comparison, add/multiply/subtract, and pp_sort ops could then use. Such an inline function seems like the fastest path for NVs that cannot be converted, but some kind of new _nv_2_iuv_ function might then be needed to efficiently upgrade NVs that do have lossless representations.
