### ISSUE TITLE
chomp by default to strip carriage return, even on Unix

### ISSUE THREAD

**Issue by epa** [Perl/perl5#17794]
In the old days each platform had its own line ending convention.  Unix had `\n`, MS-DOS had `\r\n`, and other even stranger platforms existed.  When transferring text files you often converted them (as done by ftp's "text" transfer mode, or odd mount flags in compatibility layers like Cygwin).  But nowadays that is long gone.  People run a mixture of systems and files are transferred unchanged between them.  This means it's common to deal with `\r\n` files on Unix or `\n` on Windows -- or even a mixture of the two line endings.

On Windows, perl has some magic to let `chomp` remove either line terminator (Strawberry Perl 5.24).  This should be done on other platforms too.  It can't use exactly the same mechanism as is used for Windows builds, since they also have magic to turn `\n` into `\r\n` on output, which definitely isn't wanted elsewhere.  But either form should be accepted for input.

This might require implementing support for `$/` to be a regexp rather than a fixed string -- or perhaps you would decide that it can be a character class regexp but not a fully general one.

Just as the addition of `chomp` as a complement to `chop` made Perl more useful for text munging, so extending it to handle the different line endings will make it more useful on today's text files.

**Comment by epa** [comment]
P.S. I think that the `$` anchor in regular expressions should also recognize either line ending convention, by default.

**Comment by xenu** [comment]
>On Windows, perl has some magic to let `chomp` remove either line terminator (Strawberry Perl 5.24).

It doesn't. `chomp` works on Windows in exactly the same way as on unixes:

```
PS C:\Users\xenu> perl -E 'my $foo = qq{\r\n}; chomp $foo; say length $foo'
1
```

I think what confused you is the fact that [\:crlf perlio layer](https://perldoc.pl/PerlIO#:crlf) is enabled by default on Windows.

**Comment by epa** [comment]
Yes, I did get a bit confused, what I meant was that files with either `\r\n` or `\n` are both accepted.  The perlio layer shouldn't be used on non-Windows platforms but chomp can change to accept both line endings.

**Comment by Leont** [comment]
>  People run a mixture of systems and files are transferred unchanged between them. This means it's common to deal with \r\n files on Unix or \n on Windows -- or even a mixture of the two line endings.

In that case, just open your files with `:crlf`, even if you're on unix, and all will work just as you want.

**Comment by Grinnz** [comment]
I think it is confusing that various tutorials and possibly docs refer to `\n` as magical when it is not; the `:crlf` layer is the only component that treats `\r\n` specially.

**Comment by caribpa** [comment]
Interesting, if you try to enable the `:crlf` layer with `use open` (like you can do with `:encoding`, `:std`, etc) you get a compilation error:
```perl
use open ':crlf';  # Unknown PerlIO layer class ':crlf'
```
but no problem if you specify it as second parameter to `open`:
```perl
open my $fd, '<:crlf', 'test.pl';  # Works as expected
```
or if you enable it using PerlIO:
```perl
use PerlIO 'crlf';            # No error
open my $fd, '<', 'test.pl';  # Works as expected
```
The only difference I see on the [documentation](https://perldoc.perl.org/PerlIO.html) is that `:crlf` is a 'normal' layer and `:encoding()` is a custom layer.

This said, `:utf8` is also a 'normal' layer and there's no issue enabling it with `open`:
```perl
use open ':utf8';             # No error
open my $fd, '<', 'test.pl';  # Works as expected
```
Am I missing something?

**Comment by caribpa** [comment]
I see now that the rest of PerlIO layers can't also be enabled with `use open`, only those specified on [open's documentation](https://perldoc.perl.org/open.html).

It's still a bit confusing nevertheless.

**Comment by epa** [comment]
Thanks to those who have suggested the `:crlf` layer.  But that layer changes the content read from the file.  You no longer have the same bytes, so it can't be used for binary files.  (Whereas nobody calls chomp() on binary data.)

My intention for this feature request is to keep the current cleanliness of text filtering with Perl on Unix systems (the bytes on disk are the bytes you read in and the bytes you write out are those that go to disk) while making it, by default, also handle line endings from Windows text files.  I think it should just work (tm) but I recognize this is a change in behaviour, even if put behind a 'use 5.99' version test.

I hope people will agree and say yeah!  Easy things should be easy!  Make Perl great again!  but if things are a bit more conservative and it's more important to keep the current \n only behaviour, so be it.  That would be a pity in my view since it means that simple programs (from the Camel book and so on) won't always work.  I think you have to accept that a Unix-like system today has to handle text files from all kinds of places and some will have \r\n and some have \n.

**Comment by Grinnz** [comment]
> Interesting, if you try to enable the `:crlf` layer with `use open` (like you can do with `:encoding`, `:std`, etc) you get a compilation error:
> 
> ```perl
> use open ':crlf';  # Unknown PerlIO layer class ':crlf'
> ```

This is just a quirk of the open pragma. You need to use the IO (or IN or OUT) subpragma for layers that aren't `:utf8`, `:encoding`, or `:locale`, which I mention in my [recent updates to the documentation](https://perldoc.pl/blead/open). I have no idea why but that's how it's implemented currently.

```
use open IO => ':crlf';
```

**Comment by Grinnz** [comment]
> Thanks to those who have suggested the `:crlf` layer. But that layer changes the content read from the file. You no longer have the same bytes, so it can't be used for binary files. (Whereas nobody calls chomp() on binary data.)
> 
> My intention for this feature request is to keep the current cleanliness of text filtering with Perl on Unix systems (the bytes on disk are the bytes you read in and the bytes you write out are those that go to disk) while making it, by default, also handle line endings from Windows text files. I think it should just work (tm) but I recognize this is a change in behaviour, even if put behind a 'use 5.99' version test.
> 
> I hope people will agree and say yeah! Easy things should be easy! Make Perl great again! but if things are a bit more conservative and it's more important to keep the current \n only behaviour, so be it. That would be a pity in my view since it means that simple programs (from the Camel book and so on) won't always work. I think you have to accept that a Unix-like system today has to handle text files from all kinds of places and some will have \r\n and some have \n.

I'm not sure what you're asking for. There is no "\n only behavior" except for what the `crlf` layer does. This is the primary reason that historically you needed to `binmode` a handle to unset the `crlf` flag on handles to read binary data. (You can now also use the `:raw` pseudo-layer to unset any such translation layers.) You can't have it both ways: read exact bytes, and translate \r\n to \n, you need to do one or the other. Perl only defaults to doing the \r\n translation on Windows because it's extremely likely to be useful there, and not elsewhere.

**Comment by epa** [comment]
This feature request is specifically about the `chomp` builtin.  People helpfully mentioned IO layers and `crlf` as a way to achieve the same effect, but that's not quite the same thing.  I am suggesting that `chomp` should strip a final `\r\n` from the string if it's there.  Then simple text munging that reads a line, chomps it, and processes it would work with either line encoding or even a mix in the same file, as is commonly found in the wild nowadays.

(I did muddy the water by suggesting that `chomp` on Windows already knows about the `\r\n` line ending, which isn't the case, it is handled in the IO layer.)

**Comment by Grinnz** [comment]
I'm not sure I would agree about "commonly found in the wild", unless you are handling files uploaded to a web application, but a chomp that handles either line ending is quite trivial:

 ```
$str =~ s/\R\z//;
```

**Comment by epa** [comment]
Yes, chomp itself is quite trivial, but it's common enough to get its own builtin.  I think the builtin can be improved so that simple 'read; chomp; do something' text processing works on both kinds of input file.

I had to stop using chomp in my own code, replacing it with a regexp like the one you give, because input text files are as likely as not to have CRLF line endings.  It would be great for it to become usable again in today's heterogeneous environments, where you can no longer assume that text files get converted back and forth on transferring between systems.

**Comment by Leont** [comment]
I think we should close this issue as WONTFIX.

**Comment by khwilliamson** [comment]
No dissent in two years; closing.

Note we now have trim() in builtin:: which should always remove any CRs (but also leadings \s)

**Comment by demerphq** [comment]
Not to reopen this ticket, but perhaps @epa might want to submit a docpatch for chomp() to mention the \R pattern which does what we is requesting we change chomp() to do.

```
for my $str_const ("\r", "\n", "\r\n") { 
   my $str= $str_const;
   $str=~s/\R//;
   print length $str, "\n";
}
```
Will output 0 three times.

`\R` matches any linebreak, including multi-character linebreaks like `"\r\n"`, `"\r"` by itsekf, and `"\n"` by itself.
