### ISSUE TITLE
[doc] issues with perl5320delta.pod in 5.32.0-RC0

### ISSUE THREAD

**Issue by karenetheridge** [Perl/perl5#17819]
I would like to send a patch to fix some documentation issues to perldelta in 5.32.0-RC0. I cannot find it anywhere in git - there appears to be no branch or tag pushed to the repository and blead does not contain the changes. Where is this branch so I can send a pull request? thank you.

**Comment by jkeenan** [comment]
On 5/30/20 2:02 PM, Karen Etheridge wrote:
> I would like to send a patch to fix some documentation issues to 
> perldelta in 5.32.0-RC0. I cannot find this RC0 in git anywhere - there 
> appears to be no branch or tag pushed to the repository. Where is this 
> branch so I can send a pull request? thank you.
> 

I think you can just make a regular pull request to blead and the 
pumpking can figure out the next step.

Thank you very much.
Jim Keenan

**Comment by karenetheridge** [comment]
@jkeenan as stated, the changes I wish to patch are not in blead.

**Comment by xsawyerx** [comment]
They are in blead since yesterday evening (UTC time).

**Comment by karenetheridge** [comment]
I fixed these after the RC0 release was pushed to blead.
