### ISSUE TITLE
Preemptively convert constants to PVNVs to reduce modification of non-constants

### ISSUE THREAD

**Issue by richardleach** [Perl/perl5#17814]
**Description**
Numerical and comparison operators (possibly also others) involving a constant (e.g. an IV) and a variable (e.g. a NV) can result in the upgrade of the underlying SvTYPE of the variable (e.g. NV -> PVNV). In many common cases, this upgrade - which may not be desirable or necessary - could be avoided if the constant was upgraded at compile time and both IV/UV and NV slots populated as appropriate.

**Steps to Reproduce**
In the following example, a constant (999) and a NV ($nv) are compared: `my $nv = 4/3; (999 > $nv);` Following the comparison, the constant (which was initially an IV) has been upgraded to a PVIV and $nv (which was a NV) has been upgraded to a PVNV.

The same behaviour is observed with the addition of a constant to an IV: `1 + $nv`.

Note: #17777 discussed the behavior w.r.t. non-constants, but there did not seem to be a convincing argument for a change to be made for the general case.

**Expected behavior**

The desirable behaviour is that type of $nv not change as a result of this operation. 

**Perl configuration**
perl must have been built with _PERL_PRESERVE_IVUV_, introduced in a 5.7.x branch. This seems to be a widely-used default.

**Comment by jkeenan** [comment]
> **Description**
> Numerical and comparison operators (possibly also others) involving a constant (e.g. an IV) and a variable (e.g. a NV) can result in the upgrade of the underlying SvTYPE of the variable (e.g. NV -> PVNV). In many common cases, this upgrade - which may not be desirable or necessary - could be avoided if the constant was upgraded at compile time and both IV/UV and NV slots populated as appropriate.
> 
> **Steps to Reproduce**
> In the following example, a constant (999) and a NV ($nv) are compared: `my $nv = 4/3; (999 > $nv);` Following the comparison, the constant (which was initially an IV) has been upgraded to a PVIV and $nv (which was a NV) has been upgraded to a PVNV.
> 
> The same behaviour is observed with the addition of a constant to an IV: `1 + $nv`.
> 
> Note: #17777 discussed the behavior w.r.t. non-constants, but there did not seem to be a convincing argument for a change to be made for the general case.
> 
> **Expected behavior**
> 
> The desirable behaviour is that type of $nv not change as a result of this operation.
> 
> **Perl configuration**
> perl must have been built with _PERL_PRESERVE_IVUV_, introduced in a 5.7.x branch. This seems to be a widely-used default.

On what basis, do you claim that building with `_PERL_PRESERVE_IVUV_` is a "widely-used default"?  I've never knowingly built perl with it and have only rarely observed it in, e.g., smoke-test reports?

Thank you very much.
Jim Keenan

**Comment by xenu** [comment]
>On what basis, do you claim that building with _PERL_PRESERVE_IVUV_ is a "widely-used default"? I've never knowingly built perl with it and have only rarely observed it in, e.g., smoke-test reports?

Because perl.h contains:
```
#ifndef NO_PERL_PRESERVE_IVUV
#define PERL_PRESERVE_IVUV      /* We like our integers to stay integers. */
#endif
```

**Comment by richardleach** [comment]
To be honest, that claim came just from running `perl -V` on the various Debian and Strawberry packaged versions I have to hand and then confirming that PERL_PRESERVE_IVUV is present in my own vanilla builds. ( Deb + Strawb == widely-used in my book!)

**Comment by richardleach** [comment]
I had a crack at this, modifying Perl_ck_svconst to upgrade IV/NV to PVNV when the value could losslessly** be represented in the other type. It caused a lot of test breakage. 

On reflection, this would also probably mess up assignments, e.g. `my $should_be_iv = 3`, unless the CONST upgrade tracked what the original type was and the assignment honoured that. I'm thinking that upgrading CONSTs is maybe not a good approach. Will close this issue, unless anyone thinks it's worthwhile?


** well, if I didn't get the code wrong:
```
diff --git a/op.c b/op.c
index 481158db3f..89e52f6a31 100644
--- a/op.c
+++ b/op.c
@@ -14387,6 +14387,34 @@ Perl_ck_svconst(pTHX_ OP *o)
 # endif
     }
 #endif
+    if ((SvTYPE(sv) == SVt_IV)) {
+        IV iv = SvIVX(sv);
+        NV nv = (NV)iv;
+        if (iv == nv) {
+            sv_upgrade(sv, SVt_PVNV);
+            (void)SvNOK_on(sv);
+            SvNV_set(sv, nv);
+        }
+    } else if ((SvTYPE(sv) == SVt_NV)) {
+        NV nv = SvNVX(sv);
+#  if defined(NAN_COMPARE_BROKEN) && defined(Perl_isnan)
+    /* Normally any comparison with a NaN returns false; if we can't rely
+     * on that behaviour, check explicitly */
+    if (!(Perl_isnan(nv))) {
+# endif
+    if ((LIKELY(nv >= (NV) IV_MIN) && LIKELY(nv < IV_MAX_P1))) {
+        IV iv = (IV)nv;
+        if (iv == nv) {
+            sv_upgrade(sv, SVt_PVNV);
+            (void)SvIOK_on(sv);
+            SvIV_set(sv, iv);
+        }
+    }
+#  if defined(NAN_COMPARE_BROKEN) && defined(Perl_isnan)
+    }
+#  endif
+    }
+
     SvREADONLY_on(sv);
     return o;
 }
```

**Comment by demerphq** [comment]
Could it be that you should only set the SvIOKp_on() etc? Otherwise, yeah, maybe best to leave it, something like this could really change memory footprint if not thought through carefully.
