### ISSUE TITLE
[doc] File::Find

### ISSUE THREAD

**Issue by LadyAleena** [Perl/perl5#17815]
**Where**
[File::Find](https://metacpan.org/pod/File::Find)

**Description**
```$File::Find::dir``` is described as "the current directory name", however, it is actually the current directory path.

For example, if ```find``` is working in ```Documents/taxes```, the current directory name should be ```taxes```, but ```$File::Find::dir``` returns the full path ```Documents/taxes```.

It is way too late to change that variable name to ```$File::Find::dirpath```, but the doc could be edited to reflect what it really is.

**Comment by jkeenan** [comment]
> **Where**
> [File::Find](https://metacpan.org/pod/File::Find)
> 
> **Description**
> `$File::Find::dir` is described as "the current directory name", however, it is actually the current directory path.
> 
> For example, if `find` is working in `Documents/taxes`, the current directory name should be `taxes`, but `$File::Find::dir` returns the full path `Documents/taxes`.
> 
> It is way too late to change that variable name to `$File::Find::dirpath`, but the doc could be edited to reflect what it really is.

I don't find a compelling reason to change this documentation.

First, the context makes it clear:
```
$ perldoc File::Find
...
    $File::Find::dir is the current directory name,
    $_ is the current filename within that directory
    $File::Find::name is the complete pathname to the file.
```
And after an interruption of only one small paragraph:
```
    For example, when examining the file /some/path/foo.ext you will have:

        $File::Find::dir  = /some/path/
        $_                = foo.ext
        $File::Find::name = /some/path/foo.ext
```
Second, Unix documentation does not opt to split hairs between `directory` and `path`.  Example:
```
$ man pwd
PWD(1)       User Commands       PWD(1)

NAME
       pwd - print name of current/working directory

SYNOPSIS
       pwd [OPTION]...

DESCRIPTION
       Print the full filename of the current working directory.
```
If I'm at the command-line and I want to know my current working directory, I say, and get:
```
$ pwd
/tmp/v2LKZj9
```
Other modules (*e.g.,* `File::Spec`) may choose to make a more fine-grained distinction between directories and paths.  But Unix (in general) and Perl's `File::Find` (in particular) have survived without it for several decades now.

Thank you very much.
Jim Keenan

**Comment by xsawyerx** [comment]
Considering there's a simple example following that documentation, I'm not sure this warrants a change. Any proposed wording to make this even clearer?

**Comment by LadyAleena** [comment]
I can not think of any wording to make it clearer. As this is an issue only I had, I am closing it.
