### ISSUE TITLE
Compile-time syntax warning on lone colon without space

### ISSUE THREAD

**Issue by epa** [Perl/perl5#17839]
A double colon is a package separator.  A single colon marks a label.  If you mistype :: as : you get a rather mystifying error message:

`MyPackage:foo(55)`

`Undefined subroutine OtherPackage::foo called`

This with 5.26.3.  The explanation is that `MyPackage` is being treated as a label, followed by a statement which calls `foo(55)` in the current package.  But this is far from obvious.  Could this "paper cut" in Perl's diagnostics be improved?  Could it be reported at compile time?

Conventionally when programming Perl a label is followed by at least some white space (usually a newline character but sometimes a space).  Conventionally the package separator `::` is used without spaces either side.  So how about a warning when a lone `:` appears and has a word character immediately to its left and immediately to its right?  Those like me who like extra strictness can fatalize it with `use warnings FATAL => 'syntax'`.

The usual remarks about warnings apply.  I think the mistake is easy enough to make, hard enough to work out (even for experienced programmers), and the false positive rate low enough that it falls on the right side of the line for a warning.  If you are really concerned to minimize false positives, the warning could be given only when the word to the left of the token is itself a package name.

**Comment by jkeenan** [comment]
> A double colon is a package separator. A single colon marks a label. If you mistype :: as : you get a rather mystifying error message:
> 
> `MyPackage:foo(55)`
> 
> `Undefined subroutine OtherPackage::foo called`
> 
> This with 5.26.3. The explanation is that `MyPackage` is being treated as a label, followed by a statement which calls `foo(55)` in the current package. But this is far from obvious. Could this "paper cut" in Perl's diagnostics be improved? Could it be reported at compile time?

>[snip] 

> So how about a warning when a lone `:` appears and has a word character immediately to its left and immediately to its right?

I believe that the amount of work needed within the core to implement and maintain this new warnings will not be worth it to end-users.  While we should consider pull requests for implementing feature requests such as this, the people currently contributing to the core should be focusing on features with broader usefulness and for which there is demonstrated demand.  Hence, I believe this request should be rejected.

Thank you very much.
Jim Keenan

**Comment by epa** [comment]
Alternatively, the diagnostic could be better by saying
`Undefined subroutine OtherPackage::foo called, immediately after label MyPackage`

**Comment by richardleach** [comment]
I agree that the mistake is easy to make and it would be nice to identify it at compile time, but it looks tricky to tell it apart from a label.

For example, a case we'd like to detect:
```package BOOP; sub for { } package main; BOOP:for(1..10);```
 and an actual label:
```BOOP:for(1..10) { next BOOP }```
Both have a word character to the left and right of the single colon.

Both cases hit the `/* Is this a label? */` code in `yyl_keylookup` in _toke.c_, but I'm not sure how (even with scanning ahead) we could disambiguate the two cases.

Possibly we could do something in `Perl_rv2cv_op_cv` in _op.c_, but I'm unfamiliar with that function.

**Comment by richardleach** [comment]
> Possibly we could do something in `Perl_rv2cv_op_cv` in _op.c_, but I'm unfamiliar with that function.

`CopLABEL(PL_curcop)` / `CopLABEL(&PL_compiling)` are empty at that point. :/ Bang goes the idea of checking for a label just prior to:
```
                if (flags & RV2CVOPCV_MARK_EARLY)
                    rvop->op_private |= OPpEARLY_CV;
```

**Comment by richardleach** [comment]
> Both cases hit the `/* Is this a label? */` code in `yyl_keylookup` in _toke.c_, but I'm not sure how (even with scanning ahead) we could disambiguate the two cases.

I suppose we could scan ahead and if the colon isn't followed by any of the following, emit a warning:
* whitespace
* `{` (start of a block)
* Any of the keywords `while`, `until`, `for`, `foreach` followed by whitespace or `(`

If that works, you'd still not get an error if your method names match any of those keywords, but maybe that's good enough?

**Comment by richardleach** [comment]
Something like this?

```
./miniperl -e 'package BOOP; sub boop { } package main; BOOP:boop() if ($x == 1)'
Possible typo of package separator '::' as ':' following BOOP at -e line 1.
```

Via:
```
diff --git a/toke.c b/toke.c
index c60d301ebf..afeb5bc3f8 100644
--- a/toke.c
+++ b/toke.c
@@ -8992,6 +8992,55 @@ yyl_keylookup(pTHX_ char *s, GV *gv)
     if (!anydelim && PL_expect == XSTATE
           && d < PL_bufend && *d == ':' && *(d + 1) != ':') {
         s = d + 1;
+
+        /* It could also be a typo of :: */
+        if (!isSPACE(*s) && *s != '{') {
+            switch(*s) {
+                case 'f': /* 'LABEL:for' or 'LABEL:foreach' ? */
+                    if (s + 3 < PL_bufend) {
+                        if (!( *(s+1) == 'o' && *(s+2) == 'r' ))
+                          goto package_typo;
+                        if ( isSPACE(*(s+3)) || *(s+3) == '(' )
+                            /* Could arguably be 'LABEL:for' */
+                            break;
+                        if (s + 7 < PL_bufend) {
+                            if (!( *(s+3) == 'e' && *(s+4) == 'a' &&
+                                   *(s+5) == 'c' && *(s+6) == 'h' &&
+                                  (! (isSPACE(*(s+6)) || *(s+6) == '('))
+                            ))
+                                goto package_typo;
+                        }
+                    } /* What does it mean if (s + 3 >= PL_bufend) ?? */
+                    break;
+                case 'u': /* 'LABEL:until' ? */
+                    if (s + 5 < PL_bufend) {
+                         if (!(
+                             *(s+1) == 'n' && *(s+2) == 't' &&
+                             *(s+3) == 'i' && *(s+4) == 'l' &&
+                             (isSPACE(*(s+5)) || *(s+5) == '(')
+                         ))
+                             goto package_typo;
+                    }
+                    break;
+                case 'w':
+PerlIO_stdoutf("Buffer is '%s'\n", s);
+                    if (s + 5 < PL_bufend) {
+                         if (!(
+                             *(s+1) == 'h' && *(s+2) == 'i' &&
+                             *(s+3) == 'l' && *(s+4) == 'e' &&
+                             (isSPACE(*(s+5)) || *(s+5) == '(')
+                         ))
+                             goto package_typo;
+                    }
+                    break;
+                default:
+                  package_typo:
+                    Perl_warner(aTHX_ packWARN(WARN_SYNTAX),
+                            "Possible typo of package separator '::' as ':' following %s", PL_tokenbuf);
+                    break;
+            }
+        }
+
         pl_yylval.opval =
             newSVOP(OP_CONST, 0,
                 newSVpvn_flags(PL_tokenbuf, len, UTF ? SVf_UTF8 : 0));
```

**Comment by richardleach** [comment]
> Something like this?

Test warnings/failures for that diff (debugging line removed):

1. In _t/comp/parser.t_:
```
# Also used to crash [perl #123652]
eval{$1=eval{a:}};
```
Presumably we'd just silence the warning on that test.

2. In _t/op/blocks.t_:
```
fresh_perl_is('eval "BEGIN {goto end}"; end:', '', {}, 'RT #113934: goto out of BEGIN causes assertion failure');
```

3. In _t/op/goto.t_:
```
F1:++$x and eval 'return if ++$y == 10; goto F1;';
```
4. In _t/uni/variables.t_:
```
eval "\${\x{30cd}single:\x{30cd}colon} = 'label, not var'";
```
5. In _t/lib/croak/pp_ctl_:
```
# NAME goto into foreach
no warnings 'deprecated';
goto f;
foreach(1){f:}
EXPECT
Can't "goto" into the middle of a foreach loop at - line 3.
```
For these cases, checking for a word character after the single colon should sort them out.

**Comment by richardleach** [comment]
I'll sling in a pull request and we can see what people more familiar with parsing than me think about it.

**Comment by richardleach** [comment]
Ok, for a compile-time warning:
* changes in https://github.com/Perl/perl5/pull/22847 to just _toke.c_ won't work, because we can't distinguish between the error case and e.g.
```
sub boop{ print shift } ten:boop("hello\n");goto ten
```
* changes in _peep.c_ alone also don't work, in part because we've thrown away the exact detail seen only in _toke.c_, and also struggle to distinguish between the error case and e.g.
```
  boot:
    my $xs = dl_install_xsub("${module}::bootstrap", $boot_symbol_ref, $file);
```
This is despite doing the exact checks that `pp_entersub` does prior to its current `DIE()` behaviour.

```
diff --git a/peep.c b/peep.c
index 5b5082862c..10736c919a 100644
--- a/peep.c
+++ b/peep.c
@@ -3473,6 +3473,47 @@ Perl_rpeep(pTHX_ OP *o)
                 break;
             /* FALLTHROUGH */
         case OP_GV:
+            /* Heuristic to spot BOOP:boop() typo, when the intention was
+             * to call BOOP::boop(). */
+            if (o->op_type == OP_GV && (o->op_private & OPpEARLY_CV)
+                && o->op_flags == GVf_MULTI ){
+                OP *next = o->op_next;
+                while (next->op_type == OP_NULL)
+                    next = next->op_next;
+                if (next->op_type == OP_ENTERSUB) {
+                    STRLEN label_len;
+                    const char * label = CopLABEL_len(PL_curcop, &label_len);
+                   if (label) {
+                       GV *gv = cGVOPo_gv;
+                       /* These are checks done in pp_entersub,
+                          when SvTYPE(cv) == SVt_PVGV */
+                       CV *cv = GvCVu( (const GP *)gv);
+                       if (!cv) {
+                           HV *stash;
+                           cv = sv_2cv((SV*)gv, &stash, &gv, 0);
+                           if (!cv) {
+                               /* At this point in pp_entersub, it does:
+                                      old_savestack_ix = PL_savestack_ix;
+                                      goto try_autoload;
+                                */
+                               GV* autogv = gv_autoload_pvn(GvSTASH(gv), GvNAME(gv), GvNAMELEN(gv),
+                                     (GvNAMEUTF8(gv) ? SVf_UTF8 : 0)
+                                    |(next->op_flags & OPf_REF
+                                       ? GV_AUTOLOAD_ISMETHOD
+                                       : 0));
+                               if (!autogv) {
+const char *stash_name = HvNAME(GvSTASH(gv)); // Get the package name
+                                   Perl_warner(aTHX_ packWARN(WARN_SYNTAX),
+                                      "Possible typo of package separator '::' as ':' following %s in package %s", label, stash_name);
+Perl_op_dump(o);
+                               }
+                           }
+                       }
+
+                    }
+                }
+            }
```

I guess that the stash isn't set up in such cases during compilation, only at runtime.

**Comment by richardleach** [comment]
Maybe Perl 8 could enforce a requirement to have whitespace or a newline immediately following a `label:`. :stuck_out_tongue_winking_eye:

**Comment by jkeenan** [comment]
> Ok, for a compile-time warning:
> 
>     * changes in [toke.c: warn on potential missing colon in package separator #22847](https://github.com/Perl/perl5/pull/22847) to just _toke.c_ won't work, because we can't distinguish between the error case and e.g.
> 
> 
> ```
> sub boop{ print shift } ten:boop("hello\n");goto ten
> ```
> 
>     * changes in _peep.c_ alone also don't work, in part because we've thrown away the exact detail seen only in _toke.c_, and also struggle to distinguish between the error case and e.g.
> 
> 
> ```
>   boot:
>     my $xs = dl_install_xsub("${module}::bootstrap", $boot_symbol_ref, $file);
> ```
> 
> This is despite doing the exact checks that `pp_entersub` does prior to its current `DIE()` behaviour.
> 
> ```
> diff --git a/peep.c b/peep.c
> index 5b5082862c..10736c919a 100644
> --- a/peep.c
> +++ b/peep.c
> @@ -3473,6 +3473,47 @@ Perl_rpeep(pTHX_ OP *o)
>                  break;
>              /* FALLTHROUGH */
>          case OP_GV:
> +            /* Heuristic to spot BOOP:boop() typo, when the intention was
> +             * to call BOOP::boop(). */
> +            if (o->op_type == OP_GV && (o->op_private & OPpEARLY_CV)
> +                && o->op_flags == GVf_MULTI ){
> +                OP *next = o->op_next;
> +                while (next->op_type == OP_NULL)
> +                    next = next->op_next;
> +                if (next->op_type == OP_ENTERSUB) {
> +                    STRLEN label_len;
> +                    const char * label = CopLABEL_len(PL_curcop, &label_len);
> +                   if (label) {
> +                       GV *gv = cGVOPo_gv;
> +                       /* These are checks done in pp_entersub,
> +                          when SvTYPE(cv) == SVt_PVGV */
> +                       CV *cv = GvCVu( (const GP *)gv);
> +                       if (!cv) {
> +                           HV *stash;
> +                           cv = sv_2cv((SV*)gv, &stash, &gv, 0);
> +                           if (!cv) {
> +                               /* At this point in pp_entersub, it does:
> +                                      old_savestack_ix = PL_savestack_ix;
> +                                      goto try_autoload;
> +                                */
> +                               GV* autogv = gv_autoload_pvn(GvSTASH(gv), GvNAME(gv), GvNAMELEN(gv),
> +                                     (GvNAMEUTF8(gv) ? SVf_UTF8 : 0)
> +                                    |(next->op_flags & OPf_REF
> +                                       ? GV_AUTOLOAD_ISMETHOD
> +                                       : 0));
> +                               if (!autogv) {
> +const char *stash_name = HvNAME(GvSTASH(gv)); // Get the package name
> +                                   Perl_warner(aTHX_ packWARN(WARN_SYNTAX),
> +                                      "Possible typo of package separator '::' as ':' following %s in package %s", label, stash_name);
> +Perl_op_dump(o);
> +                               }
> +                           }
> +                       }
> +
> +                    }
> +                }
> +            }
> ```
> 
> I guess that the stash isn't set up in such cases during compilation, only at runtime.

@richardleach, thanks for that analysis.  But I think it's wise to remember that you can't always get what you want, and that the amount of internal trickery needed to generate a warning is often greater than the value of the warning itself.  This feature request should be rejected.

**Comment by richardleach** [comment]
> @richardleach, thanks for that analysis. But I think it's wise to remember that you can't always get what you want, and that the amount of internal trickery needed to generate a warning is often greater than the value of the warning itself. This feature request should be rejected.

Yes, a compile-time warning sadly seems to be unfeasible.

An enhanced run-time warning in the presence of a label seems doable, I'll raise a PR for that instead.
