### ISSUE TITLE
NetBSD longdouble builds:  commit 40bca5ae9c causes failure in t/op/sprintf2.t

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#17853]
This ticket partially supersedes https://github.com/Perl/perl5/issues/17134, "NetBSD: multiple test failures with '-Duselongdouble'."  Analysis and bisection suggest that the failures reported there were not all introduced by the same commit.  Hence, correcting the failure may require a different approach in each case.

When Perl is built on NetBSD with `-Duselongdouble`, `t/op/sprintf2.t` breaks as follows:

```
$ cd t;./perl harness op/sprintf2.t; cd -
op/sprintf2.t .. 1/1444 # Failed test 1419 - '%a' '2.71828182845904509' -> '0xa.df85458a2bb48p-2' cf '0xa.df85458a2bb4a9bp-2' at op/sprintf2.t line 454
#      got "0xa.df85458a2bb48p-2"
# expected "0xa.df85458a2bb4a9bp-2"
op/sprintf2.t .. Failed 1/1444 subtests 

Test Summary Report
-------------------
op/sprintf2.t (Wstat: 0 Tests: 1444 Failed: 1)
  Failed test:  1419
Files=1, Tests=1444,  1 wallclock secs ( 0.07 usr  0.12 sys +  0.17 cusr  0.23 csys =  0.59 CPU)
Result: FAIL
/home/jkeenan/gitwork/perl2
```
Additional data from the original ticket (harness in verbose mode):
```
# rp = 0xa., ep = 0xa. (rh df85458a2bb48p-2, eh df85458a2bb4a9bp-2)
# re = p-2, ee = p-2 (rh df85458a2bb48, eh df85458a2bb4a9b)
# (rh 8, eh a9b)
# (rh 80, eh a9b)
not ok 1459 - '%a' '2.71828182845904509' -> '0xa.df85458a2bb48p-2' cf '0xa.df85458a2bb4a9bp-2'
```

Bisecting with this invocation:
```
perl Porting/bisect.pl --start=v5.20.0 --end=v5.22.0 \
-Duselongdouble \
--target t/op/sprintf2.t
```
... points to this commit:
```
40bca5ae9c72f416f0e0e056ecf8e205a03e5be3 is the first bad commit
commit 40bca5ae9c72f416f0e0e056ecf8e205a03e5be3
Author: Jarkko Hietaniemi <jhi@iki.fi>
Date:   Tue Aug 12 08:30:56 2014 -0400
Commit:     Jarkko Hietaniemi <jhi@iki.fi>
CommitDate: Wed Aug 13 22:43:53 2014 -0400

    Hexadecimal float sprintf, for perl #122219
    
    Do not use the system sprintf since %a/%A is C99 (which we do not
    require), and even if we did, there is room for interpretation
    (for example whether to print trailing zeros or not) which means
    that existing implementations will inevitably differ.
    
    For the most common case, 64-bit doubles of IEEE 754, use first
    frexp to extract the exponent, and then ldexp to scale the result
    to a 64-bit unsigned integer.
    
    For long doubles (80-bit or 128-bit) we look directly at the mantissa
    (also known as fraction, or significand) bytes, and their 4-bit nybbles,
    and extract them in correct order.
    
    Since we bypass system printf, we need to do our own aligning, filling,
    rounding, and other printf logic.
```
Caveats:

* This is a problem that has only been reported via smoke-testing.  As yet we have no reports of this problem in production code.

* I do not have the expertise to evaluate the significance or value of building Perl with `-Duselongdouble` on NetBSD.

* As far as I know, there is no single "Perl maintainer" on NetBSD.

Thank you very much.
Jim Keenan

**Comment by tonycoz** [comment]
This is caused by expl() on NetBSD being purely a wrapper around exp().  See https://github.com/NetBSD/src/blob/b8f533f2bcd85f42b0a731eadab2bfe5d1bbbf0d/lib/libm/src/ldbl_dummy.c

We could workaround this brokeness by simply using a constant instead of exp(1), but it might save us some bug reports to simply reject building with `-Duselongdouble` on NetBSD.

I had a test case that seemed to show sane behaviour from a standalone program, but that turned out to be the compiler constant-folding `expl(1.0)` (which it apparently does without the help of libm.)

**Comment by Tux** [comment]
`hints/dec_osf.sh` already protects similarly. It is not a global disable, it depends on the OS version, leaving room for the OS to fix it in the next release.

**Comment by jkeenan** [comment]
On 6/16/20 2:01 AM, H.Merijn Brand wrote:
> |hints/dec_osf.sh| already protects similarly. It is not a global 
> disable, it depends on the OS version, leaving room for the OS to fix it 
> in the next release.
> 

Sounds like a plan!

Note that if we can't get this in 5.32, we shouldn't worry.  If we 
hadn't received smoke-test reports about --Duselongdouble, we would 
probably have never heard of the problem at all.

jimk
