### ISSUE TITLE
t/porting/globvar.t uses `nm` instead of `$Config{nm}`

### ISSUE THREAD

**Issue by kentfredric** [Perl/perl5#17864]
On a system where there is no binary called `nm` in `$PATH`, and the only `nm` is `x86_64-pc-linux-gnu-nm`, and is passed to perl `./Configure` via:

```
    -Dnm=x86_64-pc-linux-gnu-nm
```

This porting test gets skipped for a relatively useless reason:

```
porting/globvar.t .................................................. skipped: Could not run `nm globals.o 2>&1`
```

https://github.com/Perl/perl5/blob/2bb47a6fc2ed9992b5c80a483a82d25b58ff6008/t/porting/globvar.t#L25-L28

And it looks like there's at least one other place in this test where it assumes `nm` is callable by `nm`:

https://github.com/Perl/perl5/blob/2bb47a6fc2ed9992b5c80a483a82d25b58ff6008/t/porting/globvar.t#L49-L51

And although this behaviour isn't fatal, I suspect it can be improved on.

**Comment by jkeenan** [comment]
@kentfredric, can you try out the `smoke-me/jkeenan/gh-17864-nm` branch for this on an appropriate machine?

Or: https://github.com/Perl/perl5/pull/18560

Thank you very much.
Jim Keenan

**Comment by Leont** [comment]
> @kentfredric, can you try out the smoke-me/jkeenan/gh-17864-nm branch for this on an appropriate machine?

No he can't, he [passed away](https://www.facebook.com/kent.fredric/posts/10158837806906830) yesterday :-(

**Comment by jkeenan** [comment]
Resolved via pull request https://github.com/Perl/perl5/pull/18560.

Thank you very much.
Jim Keenan
