### ISSUE TITLE
[doc] perlcommunity has lots of out of date information

### ISSUE THREAD

**Issue by haarg** [Perl/perl5#17868]
The perlcommunity.pod file has many references to sites and events that no longer exist.

For example:

- References to Perl 6 (rather than Raku)
- http://use.perl.org/ is a dead link
- references to YAPC, which has changed to TPC
- OSCON has been discontinued
- https://www.theperlreview.com/community_calendar is a dead link
- The last Open Source Developers' Conference was in 2015

**Comment by Grinnz** [comment]
> * References to Perl 6 (rather than Raku)

This is already fixed in blead: https://perldoc.pl/blead/perlcommunity

**Comment by xsawyerx** [comment]
> > * References to Perl 6 (rather than Raku)
> 
> This is already fixed in blead: https://perldoc.pl/blead/perlcommunity

Not all of it. Changes in `feature.pm` required bumping the version, so this will only happen after 5.32.0 is out.

**Comment by xsawyerx** [comment]
> The perlcommunity.pod file has many references to sites and events that no longer exist.

I prepared a PR at #17876. Please review prior to today's release.

I suggest we review this document again after 5.32.0.

> For example:
> 
>     * References to Perl 6 (rather than Raku)

Mostly resolved, as noted by @Grinnz.

>     * http://use.perl.org/ is a dead link

Can't find this link.

> 
>     * references to YAPC, which has changed to TPC

Fixed.

> 
>     * OSCON has been discontinued

Fixed.

> 
>     * https://www.theperlreview.com/community_calendar is a dead link

Fixed.
 
>     * The last Open Source Developers' Conference was in 2015

Fixed.
