### ISSUE TITLE
[doc] "Allocation too large" in perldiag

### ISSUE THREAD

**Issue by epa** [Perl/perl5#17867]
perldiag describes an error

- Allocation too large: %x
(X) You can't allocate more than 64K on an MS-DOS machine.

But the old 16-bit MS-DOS port was discontinued a long time ago.  A 32-bit build with DJGPP does not have the 64K limitation.  The code raising the error was removed in commit 39c0d7ee897c13cceed4e2b5712cd4e88315336a but it wasn't removed from the documentation.

**Comment by jkeenan** [comment]
@xsawyerx, could you provide an update on the status of this ticket?

(I don't understand why there's a "do not merge" label on this.  Also, we're past the 5.33.1 milestone.)

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
Pull request filed in https://github.com/Perl/perl5/pull/19175

**Comment by richardleach** [comment]
Looks like this was resolved in https://github.com/Perl/perl5/pull/19175.
