### ISSUE TITLE
Hash %  operator, array @ operator

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#17889]
Please provide a pragma (enabled by default in Perl 8 and onwards) that allows me to write % for a hash look up and @ for an array look up as in:

my %a = (a=>1, b=>2};
my  $a = a % b;              # $a == 2 

my @a = map {$_**2} 1..3;
my $b = a @ 2;   # $b == 4

These improvements would reduce line noise which is one reason why people prefer more "modern" languages.

**Comment by choroba** [comment]
You probably mean `my $b = A @ 1`.

The array doesn't keep a record of the list the map iterated over, so you need to use the indices, i.e. 0 .. 2, not 1 .. 3. The capitalisation of A was probably just a typo.

**Comment by scottchiefbaker** [comment]
Can you elaborate on what you're requesting? I not able to decipher your example.

**Comment by rabbiveesh** [comment]
you'd really have to consider the implications of how you autoquote the string on the RHS of your operators.
Also, this may conflict with other possible features like sigil-less variables. How will we know if that % is a hash lookup or the modulo operator on two sigilless variables?

**Comment by perigrin** [comment]
I'm not sure how `A @ 2` is going to be more comparable to "modern" languages than `$A[2]`. A Quick survey of currently fashionable languages (at my workplace):

Ruby: `a[2]` 
Python: `a[2]`
Go: `a[2]`
Rust: `a[2]`
Javascript: `a[2]`

Seems that Perl's syntax is more similar. I assume without googling for the examples that a Hash or Dictionary lookup is similarly comparable.

I wonder how you plan on denoting a de-reference with this syntax? `$A->[2]` follows pretty naturally  from `$A[2]` (given Perl's admittedly archaic choice of -> for the de-reference operator)... I'm not able to guess what it would be in your syntax.
