### ISSUE TITLE
[doc] Links in .../perl-5.32.0/pod/perldelta.pod (just a couple days!) out of date

### ISSUE THREAD

**Issue by raiph** [Perl/perl5#17881]
Free free to just close this issue without taking any other action. That's probably what I'd do.

----

In https://metacpan.org/pod/release/XSAWYERX/perl-5.32.0/pod/perldelta.pod it says:

> Unicode is in the process of revising its regular expression requirements: https://www.unicode.org/draft/reports/tr18/tr18.html. As part of that they are wanting more properties to be exposed, ones that aren't part of the strict UCD (Unicode character database). These two are used for examining inputs for security purposes. Details on their usage is at https://www.unicode.org/reports/tr39/proposed.html.

* The link for a draft TR18 404s. There's a new TR18 with a publication data 2020-06-17 at https://www.unicode.org/reports/tr18/.

* The link to a TR39 proposal says "There is no proposed update of this technical report available at this time. See the latest version.". The latest version, dated 2020-02-06, is at https://www.unicode.org/reports/tr39/.

----

I'd be happy to do a PR on the perldelta.pod if someone says to do that. Here's what it would be unless someone's input suggests otherwise:

> Unicode has revised its regular expression requirements: L<https://www.unicode.org/reports/tr18/tr18-21.html>. As part of that they are wanting more properties to be exposed, ones that aren't part of the strict UCD (Unicode character database). These two are used for examining inputs for security purposes. Details on their usage is at L<https://www.unicode.org/reports/tr39/>.

----

I found only one match for "Identifier" on the perlunicode page and it didn't seem to be relevant. More generally my guess is that no change, or no change other than the above, is needed in Perl doc.

----

I originally posted about the above on reddit, noting that it was "minutiae". It's quite plausibly a lot less interesting than a typo, and no change is necessary or even desirable. The Unicode consortium switched the TR18 status pretty much simultaneously with the 5.32.0 freeze. So what? It's trivial for folk to guess that the change has now happened. I've only posted this issue because briandfoy essentially directed me to post an issue or do a PR. The perl5 repo fork in the GH XSAWYERX account is from 2014, so I've posted here.

Feel free to just close this issue, and/or point me to the right place if this is the wrong one. Alternatively, I will be happy to do a PR as I explained at the start.  I could well believe that, if any change is needed at all, it's just the above PR. Conversely, if more changes are needed, I would say I'm not the right person to write them.

My apologies to whoever is reading this if it's all just a lot of noise about nothing...

**Comment by jkeenan** [comment]
@ralph, thank you for raising this.  The output one sees in `perldoc perldelta` is generated at production release time from the `pod/perldelta*.pod` files for each monthly development release.  The only other time when (I think) it would be generated is in preparation for a maintenance release, e.g., 5.32.1.  To the best of my knowledge, we haven't begun work on such a maint release yet, so you can hold off on the p.r.

@khwilliamson , can you review?

Thank you very much.
Jim Keenan

**Comment by khwilliamson** [comment]
@ralph, We would like to get this fixed.  Thank you for reporting it.  You can issue a PR against perl532delta.pod.  We do update delta files to make corrections, and I will work with you to get your PR merged.

**Comment by raiph** [comment]
@khwilliamson, thx, where is perl532delta.pod?

**Comment by khwilliamson** [comment]
On 6/21/20 2:19 PM, raiph wrote:
> @khwilliamson <https://github.com/khwilliamson>, thx, where is 
> perl532delta.pod?
> 
Same directory as perldelta.  Maybe it isn't showing up on github; if 
not it will in a few days.

**Comment by raiph** [comment]
@khwilliamson I'd looked and hadn't found it. I'll return. *Very* nice "doing business" with @jkeenan and yourself, very nice indeed. Thx.

**Comment by raiph** [comment]
Not there yet...

https://github.com/Perl/perl5/tree/blead/pod

https://github.com/Perl/perl5/blob/blead/pod/perl.pod

**Comment by raiph** [comment]
Thanks Perl folk.
