### ISSUE TITLE
Semicolons

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#17888]
Please make semi colons optional as in Javascript via a suitable pragma enabled by default in Perl 8 and onwards?

**Comment by jkeenan** [comment]
In https://github.com/Perl/perl5/issues/17887, which you also filed today, you wrote:

> Why not have a Perl configuration file that allows each user to choose their own ideal set rather than forcing a specific set on every-one which individuals will resent as it will remind them far too much of the python approach?

So in that ticket you request that each user be free to select his own set of default pragmas.  But in this ticket you request that in a future version **we** enable a particular pragma "by default", i.e., that we **mandate** a particular pragma.

Somehow I don't think you can have it both ways.

Thank you very much.
Jim Keenan

**Comment by shlomif** [comment]
Just for the record, I really dislike JavaScript's implicit statement termination on newlines and its optional semicolons. So :-1: from me.

**Comment by Leont** [comment]
This sounds like a terrible idea. Last thing we need is more ambiguity in our language.

**Comment by dnmfarrell** [comment]
> Please make semi colons optional as in Javascript

Via [Crafting Interpreters](https://craftinginterpreters.com/scanning.html#design-note)

> Where other languages assume most newlines are meaningful and only a few should be ignored in multi-line statements, JS assumes the opposite. It treats all of your newlines as meaningless whitespace unless it encounters a parse error. If it does, it goes back and tries turning the previous newline into a semicolon to get something grammatically valid.

> This design note would turn into a design diatribe if I went into complete detail about how that even works, much less all the various ways that JavaScript’s “solution” is a bad idea. It’s a mess. JavaScript is the only language I know where many style guides demand explicit semicolons after every statement even though the language theoretically lets you elide them.

**Comment by xsawyerx** [comment]
I appreciate your desire to help the language improve. Unfortunately, I do not deem removing semicolon as any kind of improvement, to the language nor to the user. Thank you.
