### ISSUE TITLE
Pragma configuration file

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#17887]
People are going to want different sets of pragmas enabled/disabled by default in Perl 7 or Perl 32 (which I like a lot better). Why not have a Perl configuration file that allows each user to choose their own ideal set rather than forcing a specific set on every-one which individuals will resent as it will remind them far too much of the python approach?

**Comment by jgamble** [comment]
Under what circumstances would this work? If this is a development-only situation, then you have the risk of having code that depends on a pragma failing when it doesn't occur in the user's machine. I suppose you could argue that the configuration file ships with the perl program, but I see that as being more chaotic than including the pragmas in the source file.
