### ISSUE TITLE
New operators

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#17886]
Hi Perl:

I wish to define new operators with user defined precedence, just as one can in Algol 68, as opposed  to merely overloading existing operators as one currently does in Perl.  As an example: 

 op ► 5 {my ($left, $right) = @_;  return $left->{$right}} 

my $c = $a►$b;

This would give Perl a capability that no other modern language has that would engender new user enthusiasm.  Without it, our currents turn awry and we lose the name of action.

Please tell me whether you can do this?

Thanks,

Phil

**Comment by simcop2387** [comment]
If you're really going to look at doing this, you'd really want to look at Raku and how it implemented things to be able to decide what went wrong, right, or neutral there.  https://docs.raku.org/language/operators

**Comment by taboege** [comment]
re Raku: more specifically, this section explains the different user-visible parts of creating new operators more briefly than simcop's link: <https://docs.raku.org/language/functions#Defining_operators>. What syntax category it belongs to, what symbols it uses, its precedence and associativity.

**Comment by Leont** [comment]
This is really far from being possible in our current parser. It would pretty much require rewriting it from scratch using completely different parsing concepts. This is not going to happen, not necessarily because it's necessarily a bad idea, but because it's practically impossible.
