### ISSUE TITLE
[doc] Mistake in perlrecharclass

### ISSUE THREAD

**Issue by kernschmelze** [Perl/perl5#17892]
**Where**
perlrecharclass

**Description**
In the section "Special Characters Inside a Bracketed Character Class"
there is this:

$a =~ m/[$,]/; # double-quotish: matches "\t", "|", or " "

That looks utterly wrong to me.

**Comment by iabyn** [comment]
On Fri, Jun 26, 2020 at 03:27:22AM -0700, kernschmelze wrote:
> **Where**
> perrecharclass
> 
> **Description**
> In the section "Special Characters Inside a Bracketed Character Class"
> there is this:
> 
> $a =~ m/[$,]/; # double-quotish: matches "\t", "|", or " "
> 
> That looks utterly wrong to me.

What seems wrong about it? A few lines above that there is the line

    $, = "\t| ";

and the point of that section is to point out that variables are
expanded  before the regex is compiled, so the example is equivalent to

    $a =~ m/[\t| ]/;

-- 
Red sky at night - gerroff my land!
Red sky at morning - gerroff my land!
    -- old farmers' sayings #14

**Comment by jkeenan** [comment]
It took me a couple of minutes when staring at the .pod file to realize where `$,` had been assigned to.

So I'd like to suggest a little documentation patch:
https://github.com/Perl/perl5/pull/17976

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> It took me a couple of minutes when staring at the .pod file to realize where `$,` had been assigned to.
> 
> So I'd like to suggest a little documentation patch:
> #17976
> 
@khwilliamson committed that patch and one other correction from @Grinnz last month.  Closing this ticket.

Thank you very much.
Jim Keenan
