### ISSUE TITLE
OO classes

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#17890]
Please do not implement any specific Object Oriented Class system because in Perl there is always more then one way to do it - it  is our bulwark against the tyranny of other languages.  A set of orthogonal capabilities which allow the construction of many different such systems would fit better with our long tradition of diversity.

**Comment by Grinnz** [comment]
This does not seem like a feature request or issue. Perhaps a venue like the perl5-porters list or IRC channels would be a better venue for discussion.

**Comment by yuki-kimoto** [comment]
Is it possible to write a request to ISSUE that I don't want this feature implemented for Perl future?

**Comment by yuki-kimoto** [comment]
@philiprbrenan 

Personally, I think it's a valuable message.
