### ISSUE TITLE
Pragma to swap the '->' and '.' operators

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#17923]
Please provide a pragma to swap the '->' and '.' operators.

Each user should be allowed to customize the syntax of the Perl language they
use through the use of pragmata to meet their own unique needs with default
setting for each user held externally in .pragmata.perl to avoid repetition. No
other language has such a powerful capability.

**Comment by Leont** [comment]
Just double checking, are you suggesting that `->` becomes the concatenation operator under this pragma?

**Comment by karenetheridge** [comment]
@philiprbrenan You might be interested in Chip's "dots" proposal (which he got working, I believe) from circa 2014. It will give some clues as to how you might go about achieving this.

**Comment by dnmfarrell** [comment]
If Perl was a pure OO interpreted language, something like this might be possible. E.g. you can override the behavior of the `.` operator as it is a method call on the object, whose default behavior is inherited. Generally speaking this kind of flexibility can cause a high performance cost: overriding primitive behavior means you substitute a highly optimized C routine for a user-defined version. Perhaps that is avoided if you are merely swapping one primitive for another though.

With Perl it's not so easy; it is a compiled program with no intermediate bytecode representation. If you can anticipate the different behaviors, you can code different actions into the compiled code (e.g. "when this pragma is activated, swap `.` and `=>`"). But what you're asking for is a _flexible_ arrangement which _necessarily_ is not predictable.

Perl has operator [overloading](https://metacpan.org/pod/overload) which can simulate some of this though.

**Comment by tobyink** [comment]
> No other language has such a powerful capability.

Perhaps for a good reason?

If you set your ".pragmata.perl" so that `.` is interpreted as a method call, write a script which runs fine for you, and then send it to me, it won't work for me. That makes Perl look bad. I somehow figure out what the problem is, and add the right line to my ".pragmata.perl" file so that your script will run, but now my other scripts (which use `.` to mean concatenation) stop working.

**Comment by Leont** [comment]
I'm going to close for all the reasons above.

**Comment by karenetheridge** [comment]
re dots.pm - http://www.modernperlbooks.com/mt/2013/06/why-dotspm-was-not-my-favorite-feature.html
