### ISSUE TITLE
t/opbasic/magic_phase.t and three other test files are in wrong subdirectories

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#17928]
Back in 2012, the following comment was added to t/opbasic/magic_phase.t
```diff
commit 8e7b23703b052410f0a5c87c7c5863840ec8f3d3
Author:     James E Keenan <jkeenan@cpan.org>
AuthorDate: Sun Dec 2 08:45:43 2012 -0500
Commit:     James E Keenan <jkeenan@cpan.org>
CommitDate: Fri Dec 7 20:05:02 2012 -0500

    Add or amplify inline comments as to placement of file in t/opbasic.
    
    For RT #115838

...
diff --git a/t/opbasic/magic_phase.t b/t/opbasic/magic_phase.t
index 07b4c19f7d..d721705857 100644
--- a/t/opbasic/magic_phase.t
+++ b/t/opbasic/magic_phase.t
@@ -5,8 +5,9 @@ use warnings;
 
 # Test ${^GLOBAL_PHASE}
 #
-# Test::More, test.pl, etc assert plans in END, which happens before global
-# destruction, so we don't want to use those here.
+# Test::More, t/test.pl, etc., assert plans in END, which happens before global
+# destruction. We do not want to use those programs/libraries here, so we
+# place this file in directory t/opbasic.
 
 BEGIN { print "1..7\n" }
 
```
However, `t/opbasic/magic_phase.t` defines two subroutines. From `perldoc perlhack`:
```
    *   t/base, t/comp and t/opbasic

        Since we don't know if "require" works, or even subroutines, use ad
        hoc tests for these three. Step carefully to avoid using the feature
        being tested. Tests in t/opbasic, for instance, have been placed
        there rather than in t/op because they test functionality which
        t/test.pl presumes has already been demonstrated to work.
```
So placing `magic_phase.t` in `t/opbasic/` back in 2012 was a mistake.  Once blead re-opens for commits, it should be moved to `t/op`.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> 
> However, `t/opbasic/magic_phase.t` defines two subroutines. From `perldoc perlhack`:
> 
> ```
>     *   t/base, t/comp and t/opbasic
> 
>         Since we don't know if "require" works, or even subroutines, use ad
>         hoc tests for these three. Step carefully to avoid using the feature
>         being tested. Tests in t/opbasic, for instance, have been placed
>         there rather than in t/op because they test functionality which
>         t/test.pl presumes has already been demonstrated to work.
> ```
> 
> So placing `magic_phase.t` in `t/opbasic/` back in 2012 was a mistake. Once blead re-opens for commits, it should be moved to `t/op`.
> 
> Thank you very much.
> Jim Keenan

`t/comp/proto.t`, `t/comp/redef.t`  and `t/opbasic/qq.t` also define subroutines.  They should therefore also be moved out of `t/comp` to a directory where the use of subroutines is presumed valid (`t/op` ?).

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
p.r.: https://github.com/Perl/perl5/pull/17929

**Comment by tonycoz** [comment]
`t/comp/proto.t` and t/comp/redef.t` are specifically testing that subroutines work, they should stay.
