### ISSUE TITLE
Should semctl() built-in die if not provided with correct type of argument?

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#17926]
Test file `t/io/sem.t` was introduced into the core distribution in commit 64d76282359 in December 2013 and is almost entirely unchanged since then.  When run as part of the test suite, it appears entirely ordinary.
```
$ cd t;./perl harness -v io/sem.t; cd -

ok 1 - acquired semaphore
ok 2 - Initialize all 10 semaphores to zero
ok 3 - Set semaphore 3 to 17
ok 4 - Get current semaphore values
ok 5 - Make sure we get back statuses for all 10 semaphores
ok 6 - Checking value of semaphore 3
ok 7 - Check value via GETVAL
ok
All tests successful.
Files=1, Tests=7,  0 wallclock secs ( 0.01 usr  0.00 sys +  0.02 cusr  0.00 csys =  0.03 CPU)
Result: PASS
```
However, the file was written without using any warnings.  If we simply add a `-w` flag to its shebang line and re-run it, we get:
```
$ cd t;./perl harness -v io/sem.t; cd -

ok 1 - acquired semaphore
ok 2 - Initialize all 10 semaphores to zero
ok 3 - Set semaphore 3 to 17
ok 4 - Get current semaphore values
ok 5 - Make sure we get back statuses for all 10 semaphores
ok 6 - Checking value of semaphore 3
ok 7 - Check value via GETVAL
Argument "ignore" isn't numeric in semctl at io/sem.t line 50.
Argument "ignore" isn't numeric in semctl at io/sem.t line 59.
Use of uninitialized value $semvals in semctl at io/sem.t line 59.
Argument "ignored" isn't numeric in semctl at io/sem.t line 69.
ok
All tests successful.
Files=1, Tests=7,  0 wallclock secs ( 0.01 usr  0.00 sys +  0.01 cusr  0.00 csys =  0.02 CPU)
Result: PASS
```
In the core-p7 branch I've been working on making test files strict- and warnings-compliant.  In many cases, inserting a `no warnings 'numeric'` would be sufficient.  However, in this case, the warning is significant because it points to a flaw in the test file and, potentially, a flaw in `perl` itself.

Here is the first instance of the warning cited above:
```
    ok(semctl($id, "ignore", SETALL, pack("s!*",(0)x$nsem)),
       "Initialize all $nsem semaphores to zero");
```
Now, it's perfectly obvious that `"ignore"` is non-numeric; hence, the warning.  But a case can be made that semctl() should die with a non-numeric argument rather than simply warn.  `perldoc -f semctl` starts:
```
   semctl ID,SEMNUM,CMD,ARG
        Calls the System V IPC function semctl(2).
```
... but has nothing further to say about `SEMNUM` -- though that spelling suggests the argument ought to be numeric.

If, however, we look under the hood, we see that the second argument in the underlying system call *must* be an `int`.  On Linux:
```
$ man 2 semctl
SYNOPSIS
       #include <sys/types.h>
       #include <sys/ipc.h>
       #include <sys/sem.h>

       int semctl(int semid, int semnum, int cmd, ...);

DESCRIPTION
       semctl() performs the control operation specified by cmd on the System V semaphore set iden‐
       tified by semid, or on the semnum-th semaphore of that set.  (The semaphores in  a  set  are
       numbered starting at 0.)
```
On OpenBSD:
```
SYNOPSIS
     #include <sys/sem.h>

     int
     semctl(int semid, int semnum, int cmd, union semun arg);

```
Shouldn't the Perl `semctl()` built-in `die` rather than `warn` if provided the wrong type for its second argument?

Thank you very much.
Jim Keenan

**Comment by Leont** [comment]
No, it shouldn't. Why should it? Other built-ins generally don't throw exceptions either. It's the same warning you would get when numifying any string that can't be numified. It's entirely coherent with the rest of perl.

**Comment by tonycoz** [comment]
I was asked to comment on this.

I originally commented on this in there commit where this was added to `known-issues.md` in the core-p7 branch:

> In the cases where SEMNUM is `"ignored"` (SETALL, GETALL) or ARG is `"ignored"` (GETVAL) this parameter isn't used by the underlying implementation.
> 
> As to throwing an error, that seems pretty un-perlish.  Should it throw an error if that parameter was `"1"` (with the "")?  I think the warning is sufficient.

So I agree with Leont.

I don't think this prevents us updating `sem.t` to avoid that warning though, whether that's by adding `no warnings "numeric";` or adding:
```
my $ignored = 0;
...
ok(semctl($id, $ignored, SETALL, pack("s!*",(0)x$nsem)),
       "Initialize all $nsem semaphores to zero");
```

**Comment by jkeenan** [comment]
> I was asked to comment on this.
> 
> I originally commented on this in there commit where this was added to `known-issues.md` in the core-p7 branch:
> 
> > In the cases where SEMNUM is `"ignored"` (SETALL, GETALL) or ARG is `"ignored"` (GETVAL) this parameter isn't used by the underlying implementation.
> > As to throwing an error, that seems pretty un-perlish.  Should it throw an error if that parameter was `"1"` (with the "")?  I think the warning is sufficient.
> 
> So I agree with Leont.
> 
> I don't think this prevents us updating `sem.t` to avoid that warning though, whether that's by adding `no warnings "numeric";` or adding:
> 
> ```
> my $ignored = 0;
> ...
> ok(semctl($id, $ignored, SETALL, pack("s!*",(0)x$nsem)),
>        "Initialize all $nsem semaphores to zero");
> ```

In https://github.com/Perl/perl5/pull/17956#issuecomment-657220787, @Leont commented:

> In general the meaning of the 4th argument to semctl depends on the 3rd argument of semctl.
> 
> But in this case, that warning feels like a bug to me. GETVAL doesn't require any argument, so we shouldn't require anything of it either.
> 
> Quite frankly this corner of our code is rather crufty.

So it appears the issues are deeper than we originally thought.  I'm closing the associated pull request (https://github.com/Perl/perl5/pull/17956) since our path forward is unclear.

@tonycoz et. al., could you re-examine and suggest a path forward.

Thank you very much.
Jim Keenan

**Comment by tonycoz** [comment]
The handling of the fourth argument to semctl() is a bit strange from a perl-ish pov, and goes back to perl3.0 (see c2ab57d4f).

If the op isn't one of IPC_STAT, IPC_SET, GETALL or SETALL, semctl() will treat that fourth argument as an integer which is converted to a pointer.

This means technically you could call semctl() with IPC_INFO (Linux-specific), but getting the appropriate pointer value isn't trivial, and may not be safe considering COW.

Ideally this would work like IPC_STAT and IPC_SET does, except we'd have to depend on the caller to ensure the buffer is large enough, but I don't see a way to get there from here without potentially breaking code (though I expect code using this mechanism is very, very rare.)
