### ISSUE TITLE
[doc] typo in Proposal for Perl 7 wiki page

### ISSUE THREAD

**Issue by fluca1978** [Perl/perl5#17922]
**Where**
https://github.com/Perl/perl5/wiki/The-Proposal-for-Perl-7

**Description**
In the section [CPAN Compatibility with Perl 7](https://github.com/Perl/perl5/wiki/The-Proposal-for-Perl-7#cpan-compatibility-with-perl-7) there is a sentence that reads as:

```
It will to the following:
```

and I believe it should be changed to

```
It will do the following:
```

I'm reporting it here as an issue because it is not clear to me how to submit PR to wiki (that I know GitHub does not support, but it could be the wiki source is somewhere in the repository).

**Comment by jkeenan** [comment]
Submitting this p.r. was fine.  I have a commit bit and it appears that that was all that was necessary to edit the page in the github GUI.  Thanks for noticing this.
