### ISSUE TITLE
Last value of while

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#17957]
Please make **while** return the last value of the last statement it executes so that the more elegant failing case below passes as well as the first?  

    my @a = 2..4;
    ok do {my $a; $a = pop @a while @a; $a} == 2; # Pass

    my @b = 2..4;
    ok do {            pop @b while @b    } == 2; # Fail

**Comment by Leont** [comment]
It does return the last value that it executes, and that last statement is `scalar @b`
