### ISSUE TITLE
undef($string)

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#17953]
Please make it possible to attach information to **undef** so that, for example, the reason why the value **undef** is being returned is available if needed.  For example:

    sub getFirst { return undef "Empty List - no first element" }

    if (my $a = getFirst) {....} {elsif ($debug) {say $a}

**Comment by karenetheridge** [comment]
This could be done in a module with overloads.  Please prototype it on cpan to show us how the interfaces would look.

**Comment by Leont** [comment]
Undef already takes a variable as an optional argument, this syntax isn't even available.

Also, what you describe sounds like something very different from an undefined value. Maybe you should consider using exceptions instead.
