### ISSUE TITLE
dist/Text-Abbrev:  Move out of core distribution

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#17958]
In the course of working on the core-p7 branch, I came upon two files in the core distribution that I was completely unfamiliar with.
```
dist/Text-Abbrev/t/Abbrev.t
dist/Text-Abbrev/lib/Text/Abbrev.pm
```
The only place Text::Abbrev is used within the core distribution is inside CPAN::Meta.
```
$ ack -l 'Text(::|-)Abbrev' .
META.yml
META.json
dist/Text-Abbrev/t/Abbrev.t
dist/Text-Abbrev/lib/Text/Abbrev.pm
dist/Module-CoreList/lib/Module/CoreList.pm
Porting/Maintainers.pl
cpan/CPAN-Meta/t/data-fail/META-1_4.yml
cpan/CPAN-Meta/t/data-test/restrictive-1_4.yml
cpan/CPAN-Meta/t/data-test/META-1_4.yml
cpan/CPAN-Meta/t/data-test/unicode.yml
cpan/CPAN-Meta/t/data-fixable/META-1_4.yml
cpan/CPAN-Meta/t/data-fixable/meta-spec-version-trailing-zeros.yml
cpan/CPAN-Meta/t/data-fixable/invalid-meta-spec-version.yml
MANIFEST
pod/perlmodlib.PL
```
If so, then there's no reason to retain this within the core.  We can move it to CPAN-only and have CPAN::Meta and any other distributions that need it get it from there.

Would anyone like to take on the process of moving this out of the core and onto CPAN?  This would be a good "first project" for someone.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
[snip]

> If so, then there's no reason to retain this within the core. We can move it to CPAN-only and have CPAN::Meta and any other distributions that need it get it from there.
> 
> Would anyone like to take on the process of moving this out of the core and onto CPAN? This would be a good "first project" for someone.
> 

Upon further reflection (*i.e.,* more coffee), I realize that for this to work and for CPAN-Meta to remain shipped with core, CPAN-Meta would have to be adapted to provide by itself whatever functionality it's getting from Text::Abbrev.

Still, this could be an interesting research project.

Thank you very much.
Jim Keenan

**Comment by Leont** [comment]
We've been shipping this thing with perl since the late 80s; it very much predates the habit of explicitly declaring core dependencies and as such one can expect in such circumstances most distributions depending on it don't declare this dependency. If you really want to remove it, you should first tackle that.

But quite frankly I'm not really seeing the benefit of putting that much effort into something that isn't getting into anyone's way.

> This would be a good "first project" for someone.

Not really, TBH.

**Comment by leonerd** [comment]
> But quite frankly I'm not really seeing the benefit of putting that much effort into something that isn't getting into anyone's way.

As could be said for quite a lot of the "lets get rid of X" discussions, honestly.

**Comment by jkeenan** [comment]
On 7/8/20 4:49 PM, Paul Evans wrote:
>     But quite frankly I'm not really seeing the benefit of putting that
>     much effort into something that isn't getting into anyone's way.
> 
> As could be said for quite a lot of the "lets get rid of X" discussions, 
> honestly.
> 

Okay, but if we do want to increase the number of people involved in 
work on the Perl [57] core distribution, we have to shape starter 
projects for them to get their feet wet.

**Comment by karenetheridge** [comment]
What relevance does changing Text::Abbrev's status have to do with perl7? It seems totally orthogonal.

**Comment by atoomic** [comment]
the main reason Text-Abbrev distro pops during the 7 experimental [enforcing strict, warnings, ... ] is an incorrect usage of local.

`local(%x);`

which result in warnings like
```
Variable "%x" is not imported
Global symbol "%x" requires explicit package name (did you forget to declare "my %x"?)
```

IMO, these fixes could be submitted to blead unrelated to the effort made for p7.
view b26ed5824c99b6a2021ae9cebdf09499dd36e858

**Comment by Leont** [comment]
> the main reason Text-Abbrev distro pops during the 7 experimental [enforcing strict, warnings, ... ] is an incorrect usage of local.

A simple `our %x;` in that test file would fix that.

And it wasn't quite incorrect, it just predates the existence of `our`

**Comment by atoomic** [comment]
> A simple our %x; in that test file would fix that.

I agree this is the plan and what was done as part of b26ed5824c99b6a2021ae9cebdf09499dd36e858... 
thanks for pointing out the solution 

In case of doubt I can also point that the other change, removal of `$^W = 1;` does not make sense in blead as it its.
It's only relevant once warnings are enabled by default. And as this is a dual life module, this should probably not be done at all...

**Comment by karenetheridge** [comment]
> In case of doubt I can also point that the other change, removal of $^W = 1; does not make sense in blead as it its.

IMHO any changes being made to dual-life modules should not be presuming that warnings are enabled by default -- an explicit `use strict; use warnings` should be added to the files, so we can be sure that errors are noticed in other perl versions as well.

**Comment by atoomic** [comment]
I agree adding `use strict; use warnings` is part of the plan too :-)
thanks
