### ISSUE TITLE
Is this policy compatible with Perl 7?

### ISSUE THREAD

**Issue by matthewpersico** [Perl/perl5#17965]
Re: https://github.com/Perl/perl5/blob/blead/pod/perlpolicy.pod#backward-compatibility-and-deprecation

I read that whole section as 180 degrees opposed to what the plan seems to be for Perl 7. Now I am *all for Perl 7.0* and it's intended consequences. It just seems to me that this section needs something at the end like:

```
Well, that *was* the policy.
<Insert Sawyer manifesto about three user types and why we need to move forward>
```
Unless (and this is totally possible) that I am 180 degrees wrong about what this section is really describing, in which case, fell free to correct me, and anyone else who might be confused, and then close the issue. 

Thank you.

**Comment by briandfoy** [comment]
There's some discussion in the wiki: [Changes to policies in Perl 7](https://github.com/Perl/perl5/wiki/Changes-to-policies-in-Perl-7)

**Comment by tom-binary** [comment]
The absent/abusive/acolyte archetype separation is not helpful IMHO, and I don't think it'd be something to enshrine in perlpolicy without a *lot* of work. It was a very problematic characterisation at the start, and I'm hoping that we have moved away from it.

**Comment by Leont** [comment]
> The absent/abusive/acolyte archetype separation is not helpful IMHO, and I don't think it'd be something to enshrine in perlpolicy without a lot of work. It was a very problematic characterisation at the start, and I'm hoping that we have moved away from it.

I agree it's very unhelpful and problematic language.

**Comment by khwilliamson** [comment]
Is this closable?

**Comment by jkeenan** [comment]
> Is this closable?

+1 to close.
