### ISSUE TITLE
[doc] dist/Devel-PPPort/HACKERS still refers to 'perlbug'

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#17973]
In the file cited, the potential Devel-PPPort hacker is advised to send mail to `perlbug@perl.org`.
```
=head1 DESCRIPTION

=head2 How to backport something

First, make sure that what you want to backport is documented.  If it's worth
backporting, it surely is worth documenting.  Send a documentation patch to
L<perlbug@perl.org|mailto:perlbug@perl.org> if necessary.
```
My understanding is that that email address is effectively defunct.  We need to patch this documentation with whatever is our current recommended procedure.

Thank you very much.
Jim Keenan

**Comment by khwilliamson** [comment]
On 7/16/20 7:36 AM, James E Keenan wrote:
> In the file cited, the potential Devel-PPPort hacker is advised to send 
> mail to |perlbug@perl.org|.
> 
> |=head1 DESCRIPTION =head2 How to backport something First, make sure 
> that what you want to backport is documented. If it's worth backporting, 
> it surely is worth documenting. Send a documentation patch to 
> L<perlbug@perl.org|mailto:perlbug@perl.org> if necessary. |
> 
> My understanding is that that email address is effectively defunct. We 
> need to patch this documentation with whatever is our current 
> recommended procedure.
> 

This advice is given in more than a few places in core docs

**Comment by jkeenan** [comment]
> In the file cited, the potential Devel-PPPort hacker is advised to send mail to `perlbug@perl.org`.
> 
> ```
> =head1 DESCRIPTION
> 
> =head2 How to backport something
> 
> First, make sure that what you want to backport is documented.  If it's worth
> backporting, it surely is worth documenting.  Send a documentation patch to
> L<perlbug@perl.org|mailto:perlbug@perl.org> if necessary.
> ```
> 
> My understanding is that that email address is effectively defunct. We need to patch this documentation with whatever is our current recommended procedure.

This was fixed in the course of work on Devel-PPPort by @atoomic last year.
```
commit c8799aff0116bda7147dbf4e7a01f814524ee6fe
Author:     Nicolas R <atoomic@cpan.org>
AuthorDate: Mon Aug 10 11:43:51 2020 -0600
Commit:     Nicolas R <atoomic@cpan.org>
CommitDate: Mon Aug 10 17:26:40 2020 -0600
```
Closing this ticket.
