### ISSUE TITLE
[doc] problem in use perl 5.32.0

### ISSUE THREAD

**Issue by lvxin233** [Perl/perl5#17972]
**Where**

strict.pm
**Description**

I installed the perl 5.32.0 recently,  when I type the command "./setup", an error "Can't locate strict.pm in @INC" occurred.  But I already  installed the strict.pm file. I don't know what's wrong with Perl. In addition, when I use "perl Makefile.PL" command, the same problem “Can't locate strict.pm” arise again .

**Comment by shlomif** [comment]
@lvxin233 : hi! strict.pm is a core module. Please provide more information (OS/version/`perl -V` output/packing/etc.) See:

* https://github.com/shlomif/writing-the-perfect-question
* https://github.com/shlomif/how-to-share-code-online

(try reading through the whole texts)

**Comment by lvxin233** [comment]
> @lvxin233 : hi! strict.pm is a core module. Please provide more information (OS/version/`perl -V` output/packing/etc.) See:
> 
> * https://github.com/shlomif/writing-the-perfect-question
> * https://github.com/shlomif/how-to-share-code-online
> 
> (try reading through the whole texts)

Thank you very much

**Comment by jkeenan** [comment]
The string `./setup` cannot be found within the Perl 5 core distribution.
```
$ ack '\.\/setup' .
$ 
```
Closing.

Thank you very much.
Jim Keenan
