### ISSUE TITLE
scope.c: new build-time warning

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#17988]
Since the release of perl-5.32.0, we've picked up the following new build-time warning:
```
$ parse-build-warnings blead.cd2e51706549.linux.unthreaded.make-test-prep.output.txt.gz 
File:  blead.cd2e51706549.linux.unthreaded.make-test-prep.output.txt.gz

[
  {
    char   => 33,
    group  => "Wmaybe-uninitialized",
    line   => 1369,
    source => "scope.c",
    text   => "\xE2\x80\x98was_hinthv\xE2\x80\x99 may be used uninitialized in this function",
  },
...
  # SysV.xs warnings addressed in other ticket
]
```
This line was recently touched in commit ae955d3a183.
```
commit ae955d3a183337a4770d39640a21da146cf97bc7
Author:     Paul "LeoNerd" Evans <leonerd@leonerd.org.uk>
AuthorDate: Sat Jun 27 16:09:49 2020 +0100
Commit:     Paul Evans <leonerd@leonerd.org.uk>
CommitDate: Mon Jul 20 15:40:42 2020 +0100

    Ensure stack is in consistent state while restoring SAVEt_HINTS
```
@LeoNerd, can you take a look?

Thank you very much.
Jim Keenan

**Comment by leonerd** [comment]
That would be addressed by my pending PR https://github.com/Perl/perl5/pull/17985

**Comment by jkeenan** [comment]
> Since the release of perl-5.32.0, we've picked up the following new build-time warning:
> 
> ```
> $ parse-build-warnings blead.cd2e51706549.linux.unthreaded.make-test-prep.output.txt.gz 
> File:  blead.cd2e51706549.linux.unthreaded.make-test-prep.output.txt.gz
> 
> [
>   {
>     char   => 33,
>     group  => "Wmaybe-uninitialized",
>     line   => 1369,
>     source => "scope.c",
>     text   => "\xE2\x80\x98was_hinthv\xE2\x80\x99 may be used uninitialized in this function",
>   },
> ...
>   # SysV.xs warnings addressed in other ticket
> ]
> ```
> 

Resolved by https://github.com/Perl/perl5/commit/6c148c868ed02375774c3c3e9d0c93d4684a2056 for https://github.com/Perl/perl5/pull/17985.

Thank you very much.
Jim Keenan
