### ISSUE TITLE
perl build error

### ISSUE THREAD

**Issue by YYTU-Aqua** [Perl/perl5#17994]
When you build
Can't locate strict.pm in @INC (you may need to install the strict module) (@INC contains: /tools/lib/perl5/site_perl/5.26.1/x86_64-linux /tools/lib/perl5/site_perl/ 5.26.1 /tools/lib/perl5/5.26.1/x86_64-linux /tools/lib/perl5/5.26.1) at ./examples/extexi line 36.
BEGIN failed--compilation aborted at ./examples/extexi line 36.
make: *** [Makefile:5334: examples/extracted.stamp] Error 2
command failed
It will be displayed

**Comment by jkeenan** [comment]
> When you build
> Can't locate strict.pm in @inc (you may need to install the strict module) (@inc contains: /tools/lib/perl5/site_perl/5.26.1/x86_64-linux /tools/lib/perl5/site_perl/ 5.26.1 /tools/lib/perl5/5.26.1/x86_64-linux /tools/lib/perl5/5.26.1) at ./examples/extexi line 36.
> BEGIN failed--compilation aborted at ./examples/extexi line 36.
> make: *** [Makefile:5334: examples/extracted.stamp] Error 2
> command failed
> It will be displayed

You're going to have to supply a lot more information before we can help you with this.

There is no file in the Perl 5 core distribution known as `extexi`.  Neither is there a directory in that distribution known as `examples/` (at least not at the top-level).

Hence, we don't know what program you were trying to run with Perl.

Please supply this information.  In addition, please supply the output of this command run with the same `perl` that you used to attempt the above:
```
perl -V:config_args
```
Thank you very much.
Jim Keenan

**Comment by bingos** [comment]
extexi appears to be something that is in the Bison source tarball

https://fossies.org/linux/bison/examples/extexi

**Comment by YYTU-Aqua** [comment]
I am doing something from LinuxFromScratch and I got this error on a package build of it

**Comment by bingos** [comment]
It sounds like when the toolchain perl was built you missed the bit about copying the lib directory.

http://www.linuxfromscratch.org/lfs/view/8.2/chapter05/perl.html

I don't believe that this is a problem with perl itself. If you require help with Linux From Scratch there are various ways listed on their website http://www.linuxfromscratch.org/support.html

**Comment by amgadshamale** [comment]
$ perl -V:config_args
Warning: failed to load Config_git.pl, something strange about this perl...
config_args='-des -Dprefix=/usr -Dmksymlinks -Darchname=x86_64-cygwin-threads -Dlibperl=cygperl5_30.dll -Dcc=gcc -Dld=g++ -Accflags=-ggdb -O2 -pipe -Wall -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/mnt/share/cygpkgs/perl/perl.x86_64/build=/usr/src/debug/perl-5.30.3-1 -fdebug-prefix-map=/mnt/share/cygpkgs/perl/perl.x86_64/src/perl-5.30.3=/usr/src/debug/perl-5.30.3-1 -fwrapv';




???waet tehs>>>>

**Comment by jkeenan** [comment]
> I don't believe that this is a problem with perl itself. If you require help with Linux From Scratch there are various ways listed on their website http://www.linuxfromscratch.org/support.html

Agreed. Closing.
