### ISSUE TITLE
[feature] Implement the symlink function on Windows

### ISSUE THREAD

**Issue by Prince213** [Perl/perl5#18005]
I was trying to set GNU Stow on Windows 10 when I saw this: `The symlink function is unimplemented`.
The Windows API equivalent of symlink() is [CreateSymbolicLinkA](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsymboliclinka) and [CreateSymbolicLinkW](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsymboliclinkw).

**Comment by tonycoz** [comment]
This is fixed by #18306 which was merged manually
