### ISSUE TITLE
[doc] Error in the documentation of split

### ISSUE THREAD

**Issue by bojinlund** [Perl/perl5#18016]
**Where**

https://perldoc.perl.org/5.30.1/functions/split.html
**Description**

## Error in the documentation of split
In the file in perl/pod/perlfunc.pod, line 7844
### old content

    produces the output C<a:bc>, and each of these:
    
        print join(':', split(//, 'abc', 3)), "\n";
        print join(':', split(//, 'abc', 4)), "\n";
    
    produces the output C<a:b:c>.

### new content

    produces the output C<a:bc>, and each of these:
    
        print join(':', split(//, 'abc', 4)), "\n";
        print join(':', split(//, 'abc', 5)), "\n";
    
    produces the output C<a:b:c:>.

[split.pl.txt](https://github.com/Perl/perl5/files/5010540/split.pl.txt)

**Comment by jkeenan** [comment]
> **Where**
> 
> https://perldoc.perl.org/5.30.1/functions/split.html
> **Description**
> ## Error in the documentation of split
> 
> In the file in perl/pod/perlfunc.pod, line 7844
> ### old content
> 
> ```
> produces the output C<a:bc>, and each of these:
> 
>     print join(':', split(//, 'abc', 3)), "\n";
>     print join(':', split(//, 'abc', 4)), "\n";
> 
> produces the output C<a:b:c>.
> ```
> 
> ### new content
> 
> ```
> produces the output C<a:bc>, and each of these:
> 
>     print join(':', split(//, 'abc', 4)), "\n";
>     print join(':', split(//, 'abc', 5)), "\n";
> 
> produces the output C<a:b:c:>.
> ```
> 
> [split.pl.txt](https://github.com/Perl/perl5/files/5010540/split.pl.txt)

You have identified an error in the documentation, but I think it would be better to simply omit this code example:
```
print join(':', split(//, 'abc', 4)), "\n";
```
Please evaluate this pull request:  https://github.com/Perl/perl5/pull/18105

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> > **Where**
> > https://perldoc.perl.org/5.30.1/functions/split.html
> > **Description**
> > ## Error in the documentation of split
> > In the file in perl/pod/perlfunc.pod, line 7844
> > ### old content
> > ```
> > produces the output C<a:bc>, and each of these:
> > 
> >     print join(':', split(//, 'abc', 3)), "\n";
> >     print join(':', split(//, 'abc', 4)), "\n";
> > 
> > produces the output C<a:b:c>.
> > ```
> > 
> > 
> > ### new content
> > ```
> > produces the output C<a:bc>, and each of these:
> > 
> >     print join(':', split(//, 'abc', 4)), "\n";
> >     print join(':', split(//, 'abc', 5)), "\n";
> > 
> > produces the output C<a:b:c:>.
> > ```
> > 
> > 
> > [split.pl.txt](https://github.com/Perl/perl5/files/5010540/split.pl.txt)
> 
> You have identified an error in the documentation, but I think it would be better to simply omit this code example:
> 
> ```
> print join(':', split(//, 'abc', 4)), "\n";
> ```
> 
> Please evaluate this pull request: #18105

This was merged into blead on Oct 14 2020: https://github.com/Perl/perl5/pull/18105

Closing ticket.
