### ISSUE TITLE
LeakSanitizer reports leaks when running t/re/pat.t

### ISSUE THREAD

**Issue by richardleach** [Perl/perl5#18012]
**Description**
LeakSanitizer reports leaks when running _t/re/pat.t_. (See attached [S_regatom-leaks.txt](https://github.com/Perl/perl5/files/5007903/S_regatom-leaks.txt) for LS output.)

Same output with non-debugging and debugging builds.

**Steps to Reproduce**
Build _blead_ using clang-10 and ASan on either Linux or MacOS. (For the latter, explicitly enable LeakSanitizer using `ASAN_OPTIONS=detect_leaks=1`.)

**Expected behavior**
No leaks!

**Perl configuration**
See attached [perl-V.txt](https://github.com/Perl/perl5/files/5007902/perl-V.txt).

**Comment by khwilliamson** [comment]
It appears that #18054 is a duplicate of this, and has been fixed.

**Comment by hvds** [comment]
> It appears that #18054 is a duplicate of this, and has been fixed.

This issue reported "leaks", has it been verified that the fix in #18054 plugs all of them?

**Comment by khwilliamson** [comment]
Yes
