### ISSUE TITLE
[doc] document negative arguments to sleep

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#18010]
$ perldoc -f sleep | grep -ic negative
0

```
    sleep EXPR
    sleep   Causes the script to sleep for (integer) EXPR seconds, or
            forever if no argument is given. Returns the integer number of
            seconds actually slept.
```
OK, but be sure to mention what happens when a negative integer is encountered.

**Comment by richardleach** [comment]
Something like this?

```
EXPR should be a positive integer. If called with a negative integer,
L<C<sleep>|/sleep EXPR> does not sleep but instead emits a warning, sets 
$! (C<errno>), and returns zero.
```

**Comment by jidanni** [comment]
Looks great.  Else there are tons of expression
```
$ man perlglossary
       expression
           Anything you can legally say in a spot where a value is required. Typically composed of literals,
           variables, operators, functions, and subroutine calls, not necessarily in that order.
```

**Comment by richardleach** [comment]
In practice, it seems that you can pass a float (NV) to sleep() and it will still sleep for the integer part of the number, but I don't want to put that in writing in case it's unintentional and could change in the future. ;)

**Comment by jidanni** [comment]
I always thought
"Causes the script to sleep for (integer) EXPR seconds"
seemed to mean that int() was applied to what we gave it.
Also "Returns the integer number of seconds actually slept" seems
also to mean that we might have fed it 1.23 and it slept for 1 and returned 1,
not that we gave it 1 and it slept for 1.05 and returned 1... perhaps.

So
- the original wording wasn't clear.
- I'll keep on feeding it all kinds of positive numbers.

Anyway, maybe the founding fathers did mean it was OK to feed it floats...

**Comment by richardleach** [comment]
> seemed to mean that int() was applied to what we gave it.

Could well be. I haven't dug into what happens in the OP that pushes EXPR onto the argument stack.

**Comment by jidanni** [comment]
Hmmm, if int() is being applied internally, then a second int() used by users, to conform to the documentation er... could be wasteful. So it would be best to give them the whole story.

**Comment by richardleach** [comment]
> Hmmm, if int() is being applied internally, then a second int() used by users, to conform to the documentation er... could be wasteful. So it would be best to give them the whole story.

Technically it would be wasteful, but:
- The time needed to do an `int()` will be dwarfed by the cost of even just `sleep 1;`. Adding verbiage to the documentation doesn't seem worth it. Plus, if that fraction of time was important to a user, they'd probably (or should) be using `Time::HiRes` or `usleep` instead.
- Sleep's current support for float values will be related to Perl's weak typing. If the documented interface for sleep was changed to include passing floats (based on the current behaviour), but Perl gets gradual typing later on:

1. Working out how best to convert a strict float into an int here is an additional complication for the implementers, or
2. They may decide not to implement a strict float conversion, so passing a strict float to sleep is fatal

**Comment by richardleach** [comment]
@jidanni - are you happy with #18013?

**Comment by jidanni** [comment]
Okay! (You guys how much more experts at all this deep stuff.) I guess I'll close this bug now.
