### ISSUE TITLE
Porting/cherrymaint refers to previous code repository

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#18028]
I don't know what the function of this program is, but it still contains references to our former code repository.
```
$ grep -nC2 -i -E 'perl\s?5' Porting/cherrymaint 
31-  COMMIT: a git revision ID (SHA1 or symbolic reference like HEAD)
32-
33:  You must first tunnel $addr to perl5.git.perl.org:3000? E.g.
34:  \$ ssh -C -L${\ join q{:} => reverse split /:/, $addr}:3000 perl5.git.perl.org
35-
36-HERE
--
87-    die $response->status_line . << "HERE";
88-
89:Have you remembered to tunnel $addr to perl5.git.perl.org:3000? E.g.
90:  \$ ssh -C -L${\ join q{:} => reverse split /:/, $addr}:3000 perl5.git.perl.org
91-
92-Or maybe you created a different tunnel? You can specify the address to use
```

Needs updating.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> I don't know what the function of this program is, but it still contains references to our former code repository.
> 
> ```
> $ grep -nC2 -i -E 'perl\s?5' Porting/cherrymaint 
> 31-  COMMIT: a git revision ID (SHA1 or symbolic reference like HEAD)
> 32-
> 33:  You must first tunnel $addr to perl5.git.perl.org:3000? E.g.
> 34:  \$ ssh -C -L${\ join q{:} => reverse split /:/, $addr}:3000 perl5.git.perl.org
> 35-
> 36-HERE
> --
> 87-    die $response->status_line . << "HERE";
> 88-
> 89:Have you remembered to tunnel $addr to perl5.git.perl.org:3000? E.g.
> 90:  \$ ssh -C -L${\ join q{:} => reverse split /:/, $addr}:3000 perl5.git.perl.org
> 91-
> 92-Or maybe you created a different tunnel? You can specify the address to use
> ```
> 
> Needs updating.
> 
> Thank you very much.
> Jim Keenan

@steve-m-hay Are you familiar with this program?  Can you recommend a course of action?

Thank you very much.
Jim Keenan

**Comment by steve-m-hay** [comment]
Sorry, I'm not familiar with it. I think it was something to do with a mechanism for voting on changes to back-port to maint branches, but it hails from a time before I got involved in making maint releases. I'm pretty sure it isn't used now, at least.
Perhaps @xdg knows more, since he added the script to the repo (though it was 10 years ago, so it depends how good his memory is!).

**Comment by xdg** [comment]
There used to be some system for voting on cherry picks.  I suspect it's not used anymore and this script can be deleted.

**Comment by jkeenan** [comment]
> There used to be some system for voting on cherry picks. I suspect it's not used anymore and this script can be deleted.

Thanks.  I am self-assigning this ticket for the purpose of deleting `Porting/cherrymaint` within 7 days unless I hear a serious objection.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> > There used to be some system for voting on cherry picks. I suspect it's not used anymore and this script can be deleted.
> 
> Thanks. I am self-assigning this ticket for the purpose of deleting `Porting/cherrymaint` within 7 days unless I hear a serious objection.
> 

Performed in commit b0a5c47fb0.  Closing ticket.
