### ISSUE TITLE
[feature] installman profile

### ISSUE THREAD

**Issue by jflopezfernandez** [Perl/perl5#18044]
*Note: This is not an actual feature request, but I wasn't sure what issue category to select.*

Hi, I'm a new contributor looking to help out, and I saw that the [perltodo](https://github.com/Perl/perl5/blob/blead/Porting/todo.pod#profile-installman) included an item requesting someone profile the `installman` script to see what it was doing that was taking so long, so I built the latest development release and profiled it.

The original data contained 1207 distinct functions, most of which contributed negligibly to the runtime duration, so I've included only the top 100 functions. Please let me know if I can provide any additional information.

# Profiling

The profiling was conducted using the following command:

    perf record --event="{cycle_activity.stalls_total,duration_time,instructions,cpu-cycles,cache-references,cache-misses,branch-misses,context-switches,page-faults,major-faults,kmem:kmalloc,kmem:kfree,kmem:mm_page_alloc,kmem:mm_page_free}" ./installman

## Results

The following table contains the results of the profiling.

 | cycle_activity.stalls_total   | instructions  | cpu-cycles  | cache-references  | cache-misses          | function |
 | :-: | :-: | :-: | :-: | :-: | :-: |
 | 9.36%   | 33.62%  | 20.47%  | 5.40%  | 2.49%          | S_regtry |
 | 5.48%   | 3.68%  | 4.73%  | 8.95%  | 5.45%          | Perl_hv_common |
 | 5.20%   | 2.49%  | 4.45%  | 6.16%  | 4.44%          | Perl_pp_multideref |
 | 4.32%   | 1.31%  | 2.73%  | 5.10%  | 4.27%          | Perl_pp_entersub |
 | 3.49%   | 3.68%  | 3.28%  | 2.87%  | 1.98%          | Perl_sv_setsv_flags |
 | 3.41%   | 1.67%  | 2.82%  | 3.55%  | 3.27%          | Perl_pp_padsv |
 | 3.13%   | 6.78%  | 4.54%  | 1.58%  | 1.31%          | Perl_leave_scope |
 | 2.70%   | 1.92%  | 3.06%  | 3.76%  | 3.48%          | Perl_pp_nextstate |
 | 2.28%   | 2.06%  | 2.21%  | 1.99%  | 1.93%          | Perl_sv_clear |
 | 2.21%   | 0.62%  | 1.29%  | 0.42%  | 0.12%          | Perl_utf8_length |
 | 1.80%   | 0.96%  | 1.46%  | 1.92%  | 1.11%          | Perl_pp_and |
 | 1.62%   | 0.52%  | 1.10%  | 1.61%  | 0.93%          | Perl_pp_method_named |
 | 1.61%   | 0.83%  | 1.13%  | 1.05%  | 1.92%          | libc-2.31.so  | __memmove_avx_unaligned_erms |
 | 1.51%   | 1.80%  | 1.77%  | 2.06%  | 0.85%          | Perl_regexec_flags |
 | 1.46%   | 0.96%  | 1.22%  | 1.36%  | 0.94%          | Perl_pp_rv2av |
 | 1.45%   | 0.36%  | 0.83%  | 1.49%  | 1.46%          | Perl_pp_pushmark |
 | 1.36%   | 0.54%  | 0.89%  | 1.52%  | 1.13%          | Perl_fbm_instr |
 | 1.24%   | 0.96%  | 1.00%  | 1.52%  | 1.14%          | Perl_re_intuit_start |
 | 1.20%   | 0.97%  | 1.07%  | 1.34%  | 0.91%          | Perl_pp_subst |
 | 1.16%   | 0.56%  | 0.89%  | 1.01%  | 1.08%          | libc-2.31.so  | _int_malloc |
 | 1.03%   | 0.30%  | 0.56%  | 1.12%  | 0.79%          | Perl_pp_multiconcat |
 | 1.00%   | 1.39%  | 1.02%  | 0.74%  | 0.35%          | S_regrepeat |
 | 0.97%   | 0.91%  | 0.94%  | 0.90%  | 0.80%          | Perl_runops_standard |
 | 0.97%   | 0.45%  | 0.96%  | 1.43%  | 1.40%          | Perl_pp_const |
 | 0.88%   | 1.61%  | 1.24%  | 0.93%  | 1.36%          | Perl_sv_upgrade |
 | 0.88%   | 0.66%  | 0.99%  | 1.17%  | 1.24%          | Perl_pp_match |
 | 0.86%   | 0.87%  | 0.81%  | 1.44%  | 0.79%          | Perl_pp_aassign |
 | 0.84%   | 1.11%  | 0.88%  | 0.82%  | 1.10%          | libc-2.31.so  | _int_free |
 | 0.78%   | 0.30%  | 0.53%  | 0.69%  | 0.42%          | Perl_vivify_ref |
 | 0.74%   | 0.57%  | 0.89%  | 1.00%  | 0.56%          | Perl_pp_enter |
 | 0.70%   | 0.39%  | 0.51%  | 0.80%  | 0.53%          | Perl_pp_cond_expr |
 | 0.66%   | 0.52%  | 0.58%  | 0.54%  | 0.25%          | Perl_do_trans |
 | 0.66%   | 0.39%  | 0.56%  | 0.83%  | 0.71%          | Perl_pp_or |
 | 0.62%   | 0.24%  | 0.52%  | 0.74%  | 0.73%          | Perl_pp_gvsv |
 | 0.61%   | 0.35%  | 0.46%  | 0.34%  | 0.38%          | libc-2.31.so  | cfree@GLIBC_2.2.5 |
 | 0.59%   | 0.26%  | 0.39%  | 0.32%  | 0.32%          | libc-2.31.so  | __memchr_avx2 |
 | 0.58%   | 0.93%  | 0.82%  | 0.42%  | 0.53%          | libc-2.31.so  | malloc |
 | 0.58%   | 0.49%  | 0.69%  | 0.51%  | 0.47%          | Perl_pp_leave |
 | 0.58%   | 0.21%  | 0.39%  | 0.45%  | 0.23%          | Perl_pp_padav |
 | 0.55%   | 0.77%  | 0.69%  | 1.33%  | 0.74%          | Perl_pp_padrange |
 | 0.53%   | 0.35%  | 0.43%  | 0.27%  | 0.49%          | Perl_sv_catpvn_flags |
 | 0.53%   | 0.14%  | 0.28%  | 0.50%  | 0.18%          | Perl_pp_splice |
 | 0.49%   | 0.52%  | 0.55%  | 0.56%  | 0.36%          | Perl_pp_sassign |
 | 0.49%   | 0.19%  | 0.44%  | 0.57%  | 0.84%          | S_share_hek_flags |
 | 0.45%   | 0.11%  | 0.21%  | 0.32%  | 0.24%          | S_find_byclass |
 | 0.43%   | 0.18%  | 0.26%  | 0.31%  | 0.15%          | libc-2.31.so  | _int_realloc |
 | 0.42%   | 0.59%  | 0.54%  | 0.52%  | 0.33%          | Perl_av_fetch |
 | 0.42%   | 0.49%  | 0.69%  | 0.54%  | 0.50%          | Perl_pp_leavesub |
 | 0.41%   | 0.14%  | 0.25%  | 0.58%  | 0.43%          | Perl_pp_seq |
 | 0.39%   | 0.11%  | 0.24%  | 0.31%  | 0.15%          | Perl_pp_return |
 | 0.38%   | 1.74%  | 0.96%  | 0.19%  | 0.06%          | S_reginclass |
 | 0.38%   | 0.29%  | 0.29%  | 0.30%  | 0.16%          | libc-2.31.so  | __libc_calloc |
 | 0.38%   | 0.19%  | 0.24%  | 0.37%  | 0.20%          | Perl_mg_find |
 | 0.37%   | 0.16%  | 0.25%  | 0.31%  | 0.21%          | Perl_pp_defined |
 | 0.34%   | 0.19%  | 0.26%  | 0.24%  | 0.18%          | Perl_sv_force_normal_flags |
 | 0.33%   | 0.26%  | 0.26%  | 0.19%  | 0.22%          | Perl_pp_unstack |
 | 0.33%   | 0.23%  | 0.35%  | 0.46%  | 0.57%          | S_sv_uncow |
 | 0.33%   | 0.10%  | 0.19%  | 0.12%  | 0.04%          | Perl_pp_leaveloop |
 | 0.32%   | 0.36%  | 0.33%  | 0.21%  | 0.28%          | Perl_sv_free2 |
 | 0.32%   | 0.25%  | 0.29%  | 0.31%  | 0.35%          | Perl_pp_iter |
 | 0.32%   | 0.09%  | 0.25%  | 0.35%  | 0.22%          | libc-2.31.so  | __memcmp_avx2_movbe |
 | 0.32%   | 0.08%  | 0.15%  | 0.20%  | 0.10%          | Perl_pp_not |
 | 0.30%   | 0.48%  | 0.38%  | 0.56%  | 0.16%          | Perl_mg_get |
 | 0.30%   | 0.28%  | 0.33%  | 0.25%  | 0.34%          | Perl_leave_adjust_stacks |
 | 0.29%   | 0.08%  | 0.18%  | 0.13%  | 0.16%          | libc-2.31.so  | __memset_avx2_unaligned_erms |
 | 0.28%   | 0.17%  | 0.33%  | 0.80%  | 0.34%          | Perl_sv_eq_flags |
 | 0.26%   | 0.15%  | 0.21%  | 0.18%  | 0.26%          | Perl_pp_ref |
 | 0.26%   | 0.09%  | 0.18%  | 0.28%  | 0.17%          | Perl_pp_gv |
 | 0.24%   | 0.07%  | 0.09%  | 0.13%  | 0.08%          | S_find_span_end_mask |
 | 0.24%   | 0.05%  | 0.12%  | 0.20%  | 0.09%          | Perl_pp_print |
 | 0.22%   | 0.40%  | 0.39%  | 0.26%  | 0.25%          | Perl_free_tmps |
 | 0.22%   | 0.29%  | 0.19%  | 0.37%  | 0.27%          | S_pushav |
 | 0.22%   | 0.24%  | 0.28%  | 0.33%  | 0.37%          | Perl_save_clearsv |
 | 0.22%   | 0.18%  | 0.28%  | 0.36%  | 0.25%          | Perl_hfree_next_entry |
 | 0.22%   | 0.11%  | 0.23%  | 0.21%  | 0.11%          | S_reg_set_capture_string.isra.0 |
 | 0.21%   | 0.39%  | 0.28%  | 0.17%  | 0.09%          | Perl_sv_grow |
 | 0.21%   | 0.10%  | 0.13%  | 0.24%  | 0.02%          | Perl_pp_trans |
 | 0.20%   | 0.20%  | 0.16%  | 0.23%  | 0.10%          | Perl_hv_iternext_flags.constprop.0 |
 | 0.20%   | 0.18%  | 0.15%  | 0.11%  | 0.13%          | libpthread-2.31.so  | __errno_location |
 | 0.20%   | 0.14%  | 0.19%  | 0.27%  | 0.20%          | Perl_pp_enterloop |
 | 0.20%   | 0.10%  | 0.10%  | 0.08%  | 0.12%          | Perl_newSVpvn_flags |
 | 0.20%   | 0.09%  | 0.13%  | 0.28%  | 0.16%          | S_gv_fetchmeth_internal |
 | 0.20%   | 0.04%  | 0.07%  | 0.12%  | 0.00%          | Perl_pp_substr |
 | 0.18%   | 0.21%  | 0.16%  | 0.11%  | 0.06%          | Perl_safesysmalloc |
 | 0.18%   | 0.14%  | 0.23%  | 0.17%  | 0.15%          | libc-2.31.so  | realloc |
 | 0.18%   | 0.10%  | 0.12%  | 0.16%  | 0.07%          | Perl_pp_anonhash |
 | 0.18%   | 0.08%  | 0.09%  | 0.09%  | 0.04%          | Perl_sv_2pv_flags |
 | 0.18%   | 0.04%  | 0.11%  | 0.25%  | 0.06%          | Perl_pp_gt |
 | 0.17%   | 0.21%  | 0.27%  | 0.37%  | 0.14%          | Perl_pp_push |
 | 0.17%   | 0.13%  | 0.12%  | 0.25%  | 0.34%          | Perl_pp_substcont |
 | 0.17%   | 0.11%  | 0.16%  | 0.14%  | 0.03%          | S_cleanup_regmatch_info_aux |
 | 0.17%   | 0.07%  | 0.10%  | 0.15%  | 0.13%          | Perl_pp_split |
 | 0.17%   | 0.06%  | 0.10%  | 0.16%  | 0.13%          | Perl_pp_i_eq |
 | 0.17%   | 0.04%  | 0.05%  | 0.10%  | 0.13%          | Perl_pp_length |
 | 0.16%   | 0.11%  | 0.21%  | 0.23%  | 0.39%          | Perl_pp_aelemfast |
 | 0.16%   | 0.10%  | 0.09%  | 0.05%  | 0.07%          | Perl_gp_free |
 | 0.16%   | 0.08%  | 0.11%  | 0.20%  | 0.07%          | Perl_pp_concat |
 | 0.14%   | 0.17%  | 0.14%  | 0.10%  | 0.11%          | Perl_sv_unref_flags |
 | 0.14%   | 0.11%  | 0.18%  | 0.19%  | 0.27%          | Perl_pp_shift |

### Perl Version

The version of Perl I used to profile was 5.33.0, which I built immediately before the profiling. I downloaded the source package from the [CPAN](https://www.cpan.org) using [this link](https://www.cpan.org/src/5.0/perl-5.33.0.tar.gz).

#### Configuration

I configured the source package using the following command.

    ./Configure -des -Dprefix=./test-installation/ -Dusedevel -Doptimize=-O3 -Accflags=-march=native

After building, I made sure to run `make test`. Some tests were skipped, but every test that was run was successful.

The following is the output of running `perl -V -I. -Ilib`.

```
Summary of my perl5 (revision 5 version 33 subversion 0) configuration:
   
  Platform:
    osname=linux
    osvers=5.7.9-1-manjaro
    archname=x86_64-linux
    uname='linux www1 5.7.9-1-manjaro #1 smp preempt thu jul 16 08:20:05 utc 2020 x86_64 gnulinux '
    config_args='-des -Dprefix=./test-installation/ -Dusedevel -Doptimize=-O3 -Accflags=-march=native'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-march=native -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O3'
    cppflags='-march=native -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='10.1.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include-fixed /usr/lib /lib/../lib /usr/lib/../lib /lib /lib64 /usr/lib64
    libs=-lpthread -lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.31.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.31'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O3 -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Aug  8 2020 23:32:13
  @INC:
    .
    lib
    ./test-installation/lib/perl5/site_perl/5.33.0/x86_64-linux
    ./test-installation/lib/perl5/site_perl/5.33.0
    ./test-installation/lib/perl5/5.33.0/x86_64-linux
    ./test-installation/lib/perl5/5.33.0
```

### Operating System

The following is the output from `uname -a`.

    Linux www1 5.7.9-1-MANJARO #1 SMP PREEMPT Thu Jul 16 08:20:05 UTC 2020 x86_64 GNU/Linux

**Comment by jflopezfernandez** [comment]
I've created a gist of the annotated assembly output of the `S_regtry` function [here](https://gist.github.com/jflopezfernandez/7d1bd8c6c3aa46c3850b1b0a62aeba7e) if anyone's interested in what the profiler was really running.

**Comment by hvds** [comment]
I would suggest taking a look at [Devel::NYTProf](https://metacpan.org/pod/Devel::NYTProf) for a perl-level profile. That's likely to be more useful in understanding what's happening, and should be an exciting experience to someone used to the capabilities of C profilers. :)

I imagine the first step here would be making sure everything installman does is sane and using sane algorithms; it's much more likely there will be opportunities for improvement found there than by analysing the performance of individual perl ops - while the latter is also useful to attempt, it is risky to start from a single application when profiling the language engine itself.

**Comment by jflopezfernandez** [comment]
That is such a logical and well-thought out course of action that I'm genuinely embarrassed I didn't even consider it, haha. I appreciate the heads up about that module, I'd never heard of it, so I'm definitely going to check it out, and go back and start from where I probably should have :grinning:

**Comment by jflopezfernandez** [comment]
I'll wait to close the issue for a few days just in case any other members of the community want to drop their two cents; their feedback is more than welcome. Should any mods feel the need to close it before then, by all means flaunt your powers.

**Comment by jkeenan** [comment]
> I'll wait to close the issue for a few days just in case any other members of the community want to drop their two cents; their feedback is more than welcome. Should any mods feel the need to close it before then, by all means flaunt your powers.

"When you've got it, flaunt it, baby, flaunt it!"
