### ISSUE TITLE
[feature] Add head5 and head6 to perl pod

### ISSUE THREAD

**Issue by LadyAleena** [Perl/perl5#18047]
Please add `head5` and `head6` to the available commands in Plain Old Documentation (POD). Most other markup languages have 6 heading levels.

**Comment by leonerd** [comment]
I can't think of a huge reason not to do this. Chances of accidental breakage by just adding new POD keywords is very small.

I don't think `nroff`/`man` have a way to render those heading levels but that's a local problem to those formatters; ones like HTML formatting will cope fine.

**Comment by Leont** [comment]
Could things break if we add this?

**Comment by Grinnz** [comment]
I don't see how things could break, but it is really up to pod parsers to decide to support it. Until then you will generally get a pod error from the unrecognized directive and that's about it.

**Comment by Grinnz** [comment]
I think the first step would be getting pod parsers to implement it, particularly Pod::Simple (maintained at https://github.com/perl-pod/pod-simple), and then once there are implementations in the wild it would be appropriate for perlpodspec and perlpod to mention them.

**Comment by LadyAleena** [comment]
Hello.

It has been a little over a month, and I was wondering if there has been any progress on this. If not, what should I do to help make this happen? Is there a more specific repository where I can add this as an issue and also has code I could look at to see if I can help write anything?

I am not sure how many working parts this has, so please let me know.

**Comment by jkeenan** [comment]
On 9/11/20 4:53 PM, Lady Aleena wrote:
> Hello.
> 
> It has been a little over a month, and I was wondering if there has been 
> any progress on this. If not, what should I do to help make this happen? 
> Is there a more specific repository where I can add this as an issue and 
> also has code I could look at to see if I can help write anything?
> 
> I am not sure how many working parts this has, so please let me know.
> 

Because significant parts of the POD infrastructure are maintained 
"upstream" on CPAN, the previous post in this thread referenced 
https://github.com/perl-pod/pod-simple.  You could fork and clone this 
repository, then submit pull requests back to it.

Thank you very much.
Jim Keenan

**Comment by jgamble** [comment]
I went ahead and added the two tags to the code, and updated the tests. Assuming I've done this correctly, the perl-pod maintainers should have gotten a pull request message now.

One note: I just copied the CSS lines for h5 and h6 directly from h4 in HTMLBatch.pm, since I have no idea how it is supposed to present. I figured that this is a job for a separate issue.

**Comment by rjbs** [comment]
It this is to be updated, it *must* update perl5.git's `pod/perlpodspec.pod`, which is the official specification for Pod.

**Comment by jgamble** [comment]
I presume so, but that's literally a separate repository in a separate git account, so I hope that 'it' isn't referring to my changes.

**Comment by Grinnz** [comment]
We have to be cautious not to indicate in the spec something which is not popularly supported yet. For reference, if you use this with Pod::Simple currently it will indicate a pod error and the heading will be omitted in the output (following paragraphs will appear as part of the previous heading).

**Comment by jgamble** [comment]
Also, I just checked, and wow there are a lot of Pod:: modules in core. Updating Pod::Simple::* is just a start.

[Pod modules in core](https://perldoc.perl.org/index-modules-P.html).

**Comment by Grinnz** [comment]
Several of them are essentially just Pod::Simple wrappers. But yes, it will be necessary to go through and see if any of them need updating to support the new headings.

**Comment by xenu** [comment]
The spec just has to say that it's a new thing and may not be widely supported.

**Comment by LadyAleena** [comment]
Thank you to everyone who moved this forward!

**Comment by xsawyerx** [comment]
I've set up #18047 to add this to the specification (`perlpodspec`). We would need to release `Pod::Simple` (I'll look into that) and update the PR to either include the date it was released or just remove the date and keep the version number. (I generally think keeping both version number and date of `Pod::Simple` are more useful than making the reader look up the release date.)

**Comment by LadyAleena** [comment]
Hello everyone. Is this now a closed issue? :slightly_smiling_face:

**Comment by jgamble** [comment]
Depends upon whether further discussion of the Pod::Simple related modules will be held here, I guess.

(I had been investigating this, but that laptop died last week, and I am only now getting this one up to speed again.)
