### ISSUE TITLE
ExtUtils-ParseXS can redefine croak_xs_usage

### ISSUE THREAD

**Issue by atoomic** [Perl/perl5#18040]
I noticed this issue while compiling Devel-PPPort-3.58 using Perl 5.8.8

ExtUtils::ParseXS::Utilities provides a definition of croak_xs_usage
which can conflict with the definition provided by Devel-PPPort.

It defines `#define croak_xs_usage        S_croak_xs_usage` without checking if it's already define or undef it.

This leads to warnings like this when generating RealPPPort.c
`RealPPPort.c:458:1: warning: "croak_xs_usage" redefined`

In truth fixing this issue without publishing a new version of the dual life module `ExtUtils-ParseXS`
has a low value, but this does not mean we should not fix this issue in blead.

Note that Devel-PPPort is already using a protection for `#ifndef croak_xs_usage`

**Comment by tonycoz** [comment]
EU::PXS already protects against redefining over the core definition of croak_xs_usage() by checking for `PERL_ARGS_ASSERT_CROAK_XS_USAGE`, could Devel::PPPort do the same?

**Comment by atoomic** [comment]
This would work too, view https://github.com/Dual-Life/Devel-PPPort/pull/196

**Comment by jkeenan** [comment]
> This would work too, view [Dual-Life/Devel-PPPort#196](https://github.com/Dual-Life/Devel-PPPort/pull/196)

@atoomic , @tonycoz, Are there any more issues to be handled in this ticket?

Thank you very much.
Jim Keenan

**Comment by atoomic** [comment]
I do not think we should close this ticket, we should merge at least one of these two:
- https://github.com/Dual-Life/Devel-PPPort/pull/196
- #18041 

Right now both are stale, I'm not sure what action to do at this stage.

**Comment by tonycoz** [comment]
The #196 change should be applied to blead (blead is upstream, not Dual-Life).

It should probably include a comment to indicate why it is the way it is.

**Comment by jkeenan** [comment]
> The #196 change should be applied to blead (blead is upstream, not Dual-Life).
> 

I have done so in this branch:
smoke-me/jkeenan/gh-18040-parts-inc-mess

@tonycoz, @atoomic, Please review.


> It should probably include a comment to indicate why it is the way it is.

**Comment by tonycoz** [comment]
The commit message should be the one from Dual-Life/Devel-PPPort#196 (except referencing #18040).

**Comment by jkeenan** [comment]
Applied to blead in 3b75ef9494567c0660dcabcca12402e638d1cf4a.  Closing ticket.
