### ISSUE TITLE
[feature] let hexadecimal floating point strings numify like decimal ones

### ISSUE THREAD

**Issue by dankogai** [Perl/perl5#18049]
Porters,

I came across an article on hexadecimal floating-point number notations and in the article (in Japanese) the author  says he could not find a standard way to numify a hex float string in perl (besides `eval()`).

* https://qiita.com/mod_poppo/items/3fa4cdc35f9bfb352ad5

I took a look and found `POSIX::strtod()` also works.

https://ideone.com/zcYgY0

```perl
#!/usr/bin/perl
use strict;
use warnings;
use feature 'say';
use POSIX ();
my $pi_hexstr = "0x1.921fb54442d18p+1";
say 0+$pi_hexstr;	# 0, unfortunately
say eval($pi_hexstr);	# 3.14159265358979 as expected
say POSIX::strtod("0x1.921fb54442d18p+1"); # ditto
```

But considering how decimal float strings behave,  I think hex float strings should be coerced to NV on numeric operations just like decimal ones.  In other words,

```perl
say 0+$pi_hexstr; # should say 3.14159265358979
```

Dan the Numeric Perl Monger

**Comment by iabyn** [comment]
On Mon, Aug 10, 2020 at 12:09:31AM -0700, Dan Kogai wrote:
> But considering how decimal float strings behave,  I think hex float strings should be coerced to NV on numeric operations just like decimal ones.  In other words,
> 
> 
> ```perl
> say 0+$pi_hexstr; # should say 3.14159265358979
> ```

Note that currently when perl numifies a string it doesn't do *any* hex
recognition:

    print 1 + "  2";   # 3
    print 1 + "0x2";   # 1
    print 1 + "0x2.1"; # 1

so your proposal would require perl's numification of a string to start
recognising 0x prefixes for the first time, which is a major change, and
one which I would oppose.

-- 
You're only as old as you look.

**Comment by dankogai** [comment]
Okay.  I'm convinced it is not a good idea to let perl grok hex float strings straight.  But wait... we have `hex()`!!

```perl
say hex('0x1.921fb54442d18p+1'); # unfortunately 1
```

Should we not consider having `hex()` (and maybe `oct()`) accept floating point notations as well?

Dan, not so integral
