### ISSUE TITLE
outdated news page at dev.perl.org

### ISSUE THREAD

**Issue by rwp0** [Perl/perl5#18045]
**Where**

https://dev.perl.org/perl5/news/
**Description**

the last entry being `perl 5.24.1`, released on _january 14, 2017_

also, having rss on this page could be useful, having a shorter content than the metacpan [perl](https://metacpan.org/release/perl) distribution page (which has [feeds](https://metacpan.org/feed/distribution/perl) available), but that being just a suggestion, not the main concern

and, thanks for upgrading the core documentation on perldoc.perl.org to 5.32!

**Comment by Grinnz** [comment]
This site is not maintained by Perl core, but at https://github.com/perlorg/perlweb/tree/master/docs/dev/perl5/news. Thanks.
