### ISSUE TITLE
Perl 5.32.0 fails to build when using Clang 10.0.1 on FreeBSD/powerpc

### ISSUE THREAD

**Issue by pkubaj** [Perl/perl5#18068]
**Description**
I'm trying to build Perl 5.32.0 on FreeBSD head (13.0-CURRENT) on powerpc architecture. It uses Clang 10.0.1 compiler. The following command segfaults during build process when Perl is built with -O2 (which is the default in FreeBSD):
`LD_LIBRARY_PATH=/wrkdirs/usr/ports/lang/perl5.32/work/perl-5.32.0 ./miniperl -Ilib make_ext.pl lib/auto/DB_File/DB_File.so  MAKE="/usr/bin/make" LIBPERL_A=libperl.so.5.32.0 LINKTYPE=dynamic`

Building with -O1 (or -O0) mitigates this issue. It has already been patched downstream at https://svnweb.freebsd.org/ports?view=revision&revision=544611

Building on powerpc64 works fine.

Building with base GCC 4.2.1, which is used on still supported FreeBSD 12.1-RELEASE, also works fine.

**Steps to Reproduce**
Build Perl 5.32.0 on FreeBSD head on powerpc architecture.

**Expected behavior**
Perl should build.

**Perl configuration**
No configuration, since Perl doesn't build.

**Comment by atoomic** [comment]
Unfortunately I do not have access to a powerpc server.

This would be useful to try to compile with debug symbols: `-Doptimize=-g3` 
then gdb the command `./miniperl -Ilib make_ext.pl lib/auto/DB_File/DB_File.so MAKE="/usr/bin/make" LIBPERL_A=libperl.so.5.32.0 LINKTYPE=dynamic` and provide a backtrace?

Is it something you could provide?
thanks

**Comment by pkubaj** [comment]
Passing `-Doptimize=-g3` to configure flags makes the build process finish successfully.

**Comment by pkubaj** [comment]
Looks like Perl now builds out-of-the-box with -O2 after upgrading to LLVM 11 RC1. I'm closing it, because from the FreeBSD perspective, we will use LLVM 11 anyway.
