### ISSUE TITLE
provide popcount() as built-in function

### ISSUE THREAD

**Issue by wollmers** [Perl/perl5#18079]
The function `popcount' (population count) should count the bits on in an integer and is often used in logic using bit operations. Some programming or scripting languages provide it.

Alternate names:

- `bitcount`
- ' count_bits`
- `popcount`
- `popcnt`

Description

```
integer = popcount(integer)
```

Examples 

```
print popcount(3)                       # prints 2
print popcount(-1)                      # prints 64 (or 32 on 32-bit Perls)
print popcount(0xffffffffffffffff) # prints 64
```

Implementation as pure Perl and portable to any language including C:

```
sub _count_bits {
    my $v = shift;

    # use integer;
    # no warnings 'portable'; # for 0xffffffffffffffff

    if ($width == 64) {
        $v = $v - (($v >> 1) & 0x5555555555555555);
        $v = ($v & 0x3333333333333333) + (($v >> 2) & 0x3333333333333333);
        # (bytesof($v) -1) * bitsofbyte = (8-1)*8 = 56 ----------------------vv
        $v = (($v + ($v >> 4) & 0x0f0f0f0f0f0f0f0f) * 0x0101010101010101) >> 56;
        return $v;
    }
    else {
       # for exactly 32 bits
        #$v = $v - (($v >> 1) & 0x55555555);
        #$v = ($v & 0x33333333) + (($v >> 2) & 0x33333333);
        ## (bytesof($v) -1) * bitsofbyte = (4-1)*8 = 24 ------vv
        #$v = (($v + ($v >> 4) & 0x0f0f0f0f) * 0x01010101) >> 24

       # for any length
        my $c; # count
        for ($c = 0; $v; $c++) {
            $v &= $v - 1; # clear the least significant bit set
        }
       return $c;
    }
}

```

**Comment by Tux** [comment]
```
sub bitcount {
    unpack "%32b*" => pack "L" => shift;
    } # bitcount
```

**Comment by wollmers** [comment]
> ```
> sub bitcount {
>     unpack "%32b*" => pack "L" => shift;
>     } # bitcount
> ```

TIMTOWTDI;-)

The benchmarks of the pure Perl solutions:

```
$ perl 50_bitcount_bench.t
              Rate bits_any   bits64   pack64
bits_any  312076/s       --     -91%     -92%
bits64   3563121/s    1042%       --     -12%
pack64   4032984/s    1192%      13%       --
```

And C (note the difference in dimension):

```
$ ./cbench
_mm_popcnt_u64       Elapsed: 3.003925000 seconds Rate: 3328.9779 (M/sec)
__builtin_popcountll Elapsed: 3.035282000 seconds Rate: 3294.6 (M/sec)
count_bits           Elapsed: 1.468759000 seconds Rate: 680.8 (M/sec)
```

**Comment by haarg** [comment]
This doesn't really seem like something generally useful enough to belong in core. It could easily be implemented as an XS module if the extra speed was needed.

**Comment by Grinnz** [comment]
This seems extremely niche and should be provided by a CPAN module.

**Comment by khwilliamson** [comment]
On 8/21/20 8:15 AM, Dan Book wrote:
> This seems extremely niche and should be provided by a CPAN module.
> 

Note that for xs code we already have PL_bitcount[256] that knows how 
many 1 bits are set in all possible bytes

**Comment by Leont** [comment]
> This doesn't really seem like something generally useful enough to belong in core. It could easily be implemented as an XS module if the extra speed was needed.

Agreed.

**Comment by tonycoz** [comment]
I agree with the consensus, this isn't a generally useful function.  Closing.
