### ISSUE TITLE
Getopt::Long GetOptions() does not accept values like "5." as valid floating point

### ISSUE THREAD

**Issue by dkogan** [Perl/perl5#18083]
Module: Getopt::Long

Hi. Here's a demo program:

```
use Getopt::Long;

my %opt;
@ARGV=("cmd", "--opt", "5.");
GetOptions(\%opt, 'opt=f');
```

I'm telling the option parser to expect a `--opt` option with a floating-point argument. This generally works. But when I give it `5.` as the argument string, it barfs:

```
Value "5." invalid for option opt (real number expected)
```

This is simply wrong. Strings like that are valid floats in perl and everywhere else that I've seen.

Thanks.

**Comment by Grinnz** [comment]
Getopt::Long is maintained on CPAN; the issue tracker is at https://rt.cpan.org/Public/Dist/Display.html?Name=Getopt-Long.

**Comment by dkogan** [comment]
Alright. Filed there.
