### ISSUE TITLE
Building Perl on macOS 11.0 Big Sur: Configure failure as the version is not recognised

### ISSUE THREAD

**Issue by zhiyuanzhai** [Perl/perl5#18119]
~Module:~ It's a fatal error during the build process.

**Description**

Perl cannot be built on the beta version of macOS 11.0 Big Sur, failing to recognise the version of the OS.

The `./Configure -des -Dprefix=/path/to/perl` command returns an error:

```
*** Unexpected product version 11.0.
***
*** Try running sw_vers and see what its ProductVersion says.
```

And `sw_vers` says
```
ProductName:	macOS
ProductVersion:	11.0
BuildVersion:	20A5364e
```

**Steps to Reproduce**

```
./Configure -des -Dperfix=/path/to/perl
```

**Expected behavior**

Recognise the macOS version and continue.

**Perl configuration**

No configuration, since it's not even built.

**Comment by zhiyuanzhai** [comment]
This is an error reported from `spack`, a package manager.

**Comment by richardleach** [comment]
Please see https://github.com/Perl/perl5/pull/17946 - this should now be fixed in blead. If you make the same changes to hints/darwin.sh (or just copy the current version from this repository), your build will hopefully succeed.

Please let us know if this works or not.

**Comment by zhiyuanzhai** [comment]
@richardleach I would like to report this to [spack](https://github.com/spack/spack) later. Sorry for my carelessness failing to notice this PR and thank you for this information.

I actually solved this by using the perl included with the system. I'll try building it later.

**Comment by zhiyuanzhai** [comment]
Sorry to let you wait this long... The developing version of perl is configured perfectly. I will close this issue since it's fixed.
