### ISSUE TITLE
cygwin failures for op/stat.t and op/threads.t

### ISSUE THREAD

**Issue by toddr** [Perl/perl5#18193]
These tests have been failing randomly on blead and pull requests for some time on cygwin. 

This is the output extracted from a run. The link is here but the content will eventually expire. https://github.com/Perl/perl5/runs/1198894904

```
# Failed test 37 - ls and -c agreeing on /dev (14 11) at op/stat.t line 312
#      got "14"
# expected "11"
t/op/stat ........................................................ FAILED at test 37
```
```
# shmget failed: Function not implemented
# msgget failed
t/op/threads ..................................................... FAILED--unexpected output at test 3
```

**Comment by toddr** [comment]
https://cygwin.com/cygwin-api/std-notes.html

> The XSI IPC functions semctl, semget, semop, shmat, shmctl, shmdt, shmget, msgctl, msgget, msgrcv and msgsnd are only available when cygserver is running.

Maybe we should turn off parallel tests?

**Comment by wchristian** [comment]
The op/stat.t failure is not a flap, but a solid break, that happened between

Sep 24, 2020, 3:46 AM GMT+2 PASS 8f2cc613dd93c942f8161f52e47a4178c20e9f2e skip the failing dynamic vs static tests on Win32 https://github.com/Perl/perl5/actions/runs/269786053

and

Sep 24, 2020, 5:15 PM GMT+2 FAIL 98d7b5aeaad3d320d621e1a7888505217c33ef21 Update Unicode-Collate to CPAN version 1.28 https://github.com/Perl/perl5/actions/runs/270824893

From the delta between those i can't see anything that should affect op/stat.t, so that's likely something that changed on github's side, which the test was too fragile for. I'm investigating.

**Comment by wchristian** [comment]
This is caused by the following. Basic test fix is in process.

```
# ls -l /dev
total 0
crw-rw-rw-  1 runneradmin None  13, 254 Dec  1  2006 clipboard
c?????????? ? ?           ?           ?            ? conin
c?????????? ? ?           ?           ?            ? conout
c?????????? ? ?           ?           ?            ? console
crw-rw-rw-  1 runneradmin None  14,   3 Oct  4 00:52 dsp
dr-xr-xr-x  2 runneradmin None        0 Oct  4 00:52 fd
```

**Comment by wchristian** [comment]
Fix attempt is in #18204

**Comment by xsawyerx** [comment]
With @wchristian's fix attempt merged, @toddr, if you could verify this is resolved.

**Comment by wchristian** [comment]
Status of all recent cygwin FAILs known to me:

Bug:

- op/stat: The actions so far indicate that the test is indeed fine now: https://github.com/Perl/perl5/actions?query=workflow%3Atestsuite+branch%3Ablead Need to update whatever tickets are appropriate.

Flaps:

- re/pat: This was a flap, converted into a consistent failure + TODO. #18129
- re/pat_thr: Probably addressed by the above.
- op/threads: This is a *rare* flap with error message: `FAILED--unexpected output at test 3` The failed gets are irrelevant and occur even when the tests pass. #18206
- op/alarm: This is a *rare* flap with error message: `FAILED--expected 5 tests, saw 0` #18207

**Comment by toddr** [comment]
> With @wchristian's fix attempt merged, @toddr, if you could verify this is resolved.

Yep. We've had successful runs all day. Great work thanks!
