### ISSUE TITLE
BBC: Blead Breaks Devel::NYTProf

### ISSUE THREAD

**Issue by cjg-cguevara** [Perl/perl5#18215]
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.42 running under perl 5.33.3.

-----------------------------------------------------------------
[Please describe your issue here]

BBC: Blead Breaks Devel::NYTProf

Please see http://fast-matrix.cpantesters.org/?dist=Devel-NYTProf-6.06

[Please do not change anything below this line]
-----------------------------------------------------------------
---
Flags:
    category=core
    severity=low
---
Site configuration information for perl 5.33.3:

Configured by cpan at Mon Oct  5 15:17:26 EDT 2020.

Summary of my perl5 (revision 5 version 33 subversion 3) configuration:
  Commit id: dd07b88184b9bd3f6b53dc56af502937e127ee99
  Platform:
    osname=linux
    osvers=5.4.43-1-lts
    archname=x86_64-linux
    uname='linux cjg-alpine3 5.4.43-1-lts #2-alpine smp thu, 28 may 2020 20:13:48 utc x86_64 linux '
    config_args='-des -Dprefix=~/bin/perl-blead -Dscriptdir=~/bin/perl-blead/bin -Dusedevel -Duse64bitall'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong'
    ccversion=''
    gccversion='9.3.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/include/fortify /usr/lib /usr/local/lib /lib/../lib /usr/lib/../lib /lib
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/usr/lib/libc.a
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'

---
@INC for perl 5.33.3:
    /home/cpan/bin/perl-blead/lib/site_perl/5.33.3/x86_64-linux
    /home/cpan/bin/perl-blead/lib/site_perl/5.33.3
    /home/cpan/bin/perl-blead/lib/5.33.3/x86_64-linux
    /home/cpan/bin/perl-blead/lib/5.33.3

---
Environment for perl 5.33.3:
    HOME=/home/cpan
    LANG=C.UTF-8
    LANGUAGE (unset)
    LC_ALL=C
    LC_COLLATE=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl-blead/bin:/home/cpan/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

**Comment by hvds** [comment]
I think this is an issue for Devel::NYTProf to look at initially: Exporter now uses strict, so tracing it will see it follow different pathways than before.

**Comment by hvds** [comment]
I've reported it there under https://github.com/timbunce/devel-nytprof/issues/143

**Comment by hvds** [comment]
@timbunce acknowledges that the Devel::NYTProf tests are too sensitive here, but asks for help fixing them. I suggest we mark this as a blocker for 5.34 for now (how do you do that?), at least so we continue to keep an eye on it.

**Comment by jkeenan** [comment]
> @timbunce acknowledges that the Devel::NYTProf tests are too sensitive here, but asks for help fixing them. I suggest we mark this as a blocker for 5.34 for now (how do you do that?), at least so we continue to keep an eye on it.

I have created a label 'affects-5.34' and have applied it to this issue.

**Comment by jkeenan** [comment]
I have submitted a [pull request upstream](https://github.com/timbunce/devel-nytprof/pull/147) which addresses the issue in the [upstream issue](https://github.com/timbunce/devel-nytprof/issues/143) filed by @hvds on October 6 2020.

I have [applied to become a co-maintainer](https://www.nntp.perl.org/group/perl.modules/2021/04/msg102509.html) of Devel-NYTProf.  Once that has been approved, I will prepare a new CPAN release of Devel-NYTProf, which should enable us to close this ticket.

Having identified what needs to be done upstream, this ticket is no longer a blocker for perl-5.34.0 (though it is still technically a "BBC").

Thank you very much.
Jim Keenan

**Comment by hvds** [comment]
> I have submitted a pull request

Cool, thanks for working on it.

> though it is still technically a "BBC"

Not sure what you're saying here, but we should be clear that this isn't something broken in blead that is affecting NYTProf; rather, NYTProf's tests are unreasonably reliant on non-guaranteed behaviours (and not because they _need_ to be - NYTProf itself doesn't rely on those behaviours). So changing the package's tests was the correct solution.

As Tim mentioned, the acknowledged oversensitivity of those tests has caused similar issues in the past, and will likely do so again in the future.

**Comment by Leont** [comment]
> I have applied to become a co-maintainer of Devel-NYTProf. Once that has been approved, I will prepare a new CPAN release of Devel-NYTProf, which should enable us to close this ticket.

While I appreciate this, most of the challenges of Devel-NYTProf do require XS/opcode knowledge. E.g. it currently knows about neither `isa` nor `try`/`catch`. I don't think this is enough to get us there.

In particular, I think it's a bad idea to move the repository to your own github account. Instead I would propose we set up an organization for its maintenance. It seems no one has the abilities and time to do this, but perhaps together we do have both. I'm willing to be part of such an organization, and I hope @leonerd will too (since the features he's adding will be an important part of maintaining NYTProf).

**Comment by timbunce** [comment]
> Instead I would propose we set up an organization for its maintenance. It seems no one has the abilities and time to do this, but perhaps together we do have both. 

I'm certainly +1 for establishing an organization for maintenance.

**Comment by jkeenan** [comment]
> > Instead I would propose we set up an organization for its maintenance. It seems no one has the abilities and time to do this, but perhaps together we do have both.
> 
> I'm certainly +1 for establishing an organization for maintenance.

First, let's get a new CPAN release that resolves *this* ticket.  I'll be doing that today.  I will follow that quickly with some other pull requests, some of which @timbunce has already approved, which are mainly focused on extending test coverage.

After that, changes in how Devel-NYTProf is managed should be proposed in https://github.com/timbunce/devel-nytprof/issues.

Thank you very much.
Jim Keenan

**Comment by Leont** [comment]
> First, let's get a new CPAN release that resolves _this_ ticket. I'll be doing that today. I will follow that quickly with some other pull requests, some of which @timbunce has already approved, which are mainly focused on extending test coverage.
> 
> After that, changes in how Devel-NYTProf is managed should be proposed in https://github.com/timbunce/devel-nytprof/issues.


Fair

**Comment by jkeenan** [comment]
> > @timbunce acknowledges that the Devel::NYTProf tests are too sensitive here, but asks for help fixing them. I suggest we mark this as a blocker for 5.34 for now (how do you do that?), at least so we continue to keep an eye on it.
> 
> I have created a label 'affects-5.34' and have applied it to this issue.

This has been resolved with the release of Devel-NYTProf-6.07 yesterday.

Thank you very much.
Jim Keenan
