### ISSUE TITLE
ext/POSIX/t/posix.t: emits non-numeric value warning when run with warnings

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#18244]
In the core distribution, `ext/POSIX/t/posix.t` contains this code:
```
116     $todo = 1 if ($^O eq 'freebsd' && $Config{osvers} < 8)
117               || ($^O eq 'darwin' && $Config{osvers} < '6.6');
```
(Observed on blead at v5.33.2-198-gb182616363.)

When run on FreeBSD and when the file is run with warnings turned on, this code generates a runtime warning:
```
$ cd t; ./perl -w -I../lib -I. -I../ext/POSIX/lib ../ext/POSIX/t/posix.t; cd -
...
ok 10 - sig mask delayed SIGINT
Argument "11.2-stable" isn't numeric in numeric lt (<) at ../ext/POSIX/t/posix.t line 117.
ok 11 - masked SIGINT received 
...
```
And, indeed, the value stored in `$Config{osvers}` on this platform is a string, not a number.
```
$ ./perl -Ilib -MConfig -E 'say $Config{osvers}'
11.2-stable
```
Should this test file be modified?  Is `Configure` doing the right thing?

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> In the core distribution, `ext/POSIX/t/posix.t` contains this code:
> 
> ```
> 116     $todo = 1 if ($^O eq 'freebsd' && $Config{osvers} < 8)
> 117               || ($^O eq 'darwin' && $Config{osvers} < '6.6');
> ```
> 
> (Observed on blead at v5.33.2-198-gb182616363.)
> 
> When run on FreeBSD and when the file is run with warnings turned on, this code generates a runtime warning:
> 
> ```
> $ cd t; ./perl -w -I../lib -I. -I../ext/POSIX/lib ../ext/POSIX/t/posix.t; cd -
> ...
> ok 10 - sig mask delayed SIGINT
> Argument "11.2-stable" isn't numeric in numeric lt (<) at ../ext/POSIX/t/posix.t line 117.
> ok 11 - masked SIGINT received 
> ...
> ```
> 
> And, indeed, the value stored in `$Config{osvers}` on this platform is a string, not a number.
> 
> ```
> $ ./perl -Ilib -MConfig -E 'say $Config{osvers}'
> 11.2-stable
> ```
> 
> Should this test file be modified? Is `Configure` doing the right thing?
> 
> Thank you very much.
> Jim Keenan

Configure mavens (@Tux @doughera88 ) and others who have touched this file (@tomhukins, @nwc10  ) -- do you have thoughts on this issue?

Thank you very much.
Jim Keenan

**Comment by Tux** [comment]
The *only* place where this should be changed (if it should be) is `hints/freebsd.sh`. On line 52 I see a check on `-release`, which (to me) indicates that (parts of) the toolchain expects the extension to exist (as the rest of the hints file does not remove any `[^.0-9]` from `$osvers`.
IMHO the fix - if required - should be made in the POSIX test file(s)

**Comment by tomhukins** [comment]
The warning is completely harmless: the script works as intended.  If you want to silence the warning, `git grep osvers t` will show you how other test scripts do this, or you could reuse the approach from `ext/POSIX/t/mb.t` in the same distribution.

**Comment by jkeenan** [comment]
No objections were raised to https://github.com/Perl/perl5/pull/18873, so I merged it to blead. Closing this ticket.
