### ISSUE TITLE
ext/POSIX/t/posix.t: Incorrect use of prototyped testing function

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#18245]
In the core distribution (), `ext/POSIX/t/posix.t` contains this code:
```
356 SKIP: {
357     skip("locales not available", 26) unless locales_enabled(qw(NUMERIC MONETARY));
358     skip("localeconv() not available", 26) unless $Config{d_locconv};
```
When this file is run with warnings enabled, we get a compile-time error at line 357.
```
$ cd t; ./perl -w -I../lib -I. -I../ext/POSIX/lib ../ext/POSIX/t/posix.t; cd -
1..96
Useless use of a constant ("NUMERIC") in void context at ../ext/POSIX/t/posix.t line 357.
...
```
At line 357, `locales_enabled` is a function imported from `t/loc_tools.pl`.  This function is prototyped.
```
sub locales_enabled(;$) {
    # Returns 0 if no locale handling is available on this platform; otherwise
    # 1.
    #
    # The optional parameter is a reference to a list of individual POSIX
    # locale categories.  If any of the individual categories specified by the
    # optional parameter is all digits (and an optional leading minus), it is
    # taken to be the C enum for the category (e.g., &POSIX::LC_CTYPE).
    # Otherwise it should be a string name of the category, like 'LC_TIME'.
    # The initial 'LC_' is optional.  It is a fatal error to call this with
    # something that isn't a known category to this file.
    #
    # This optional parameter denotes which POSIX locale categories must be
    # available on the platform.  If any aren't available, this function
    # returns 0; otherwise it returns 1 and changes the list for the caller so
    # that any category names are converted into their equivalent numbers, and
    # sorts it to match the expectations of _trylocale.
    #
    # It is acceptable for the second parameter to be just a simple scalar
    # denoting a single category (either name or number).  No conversion into
    # a number is done in this case.
...
```
If I'm reading the prototype correctly, `locales_enabled()` takes a single, optional parameter which must be a scalar.  However, the inline comment suggests that that scalar must be an array reference.  If that is the case then to say:
```
locales_enabled(qw(NUMERIC MONETARY));
```
... would be an error because the function was being provided a list of scalars, not an array ref.

If my reasoning is correct, this patch should clear the warning:
```
diff --git a/ext/POSIX/t/posix.t b/ext/POSIX/t/posix.t
index 25099ea54a..2b317fa894 100644
--- a/ext/POSIX/t/posix.t
+++ b/ext/POSIX/t/posix.t
@@ -354,7 +354,7 @@ eval { use strict; POSIX->import("S_ISBLK"); my $x = S_ISBLK };
 unlike( $@, qr/Can't use string .* as a symbol ref/, "Can import autoloaded constants" );
 
 SKIP: {
-    skip("locales not available", 26) unless locales_enabled(qw(NUMERIC MONETARY));
+    skip("locales not available", 26) unless locales_enabled([qw(NUMERIC MONETARY)]);
     skip("localeconv() not available", 26) unless $Config{d_locconv};
     my $conv = localeconv;
     is(ref $conv, 'HASH', 'localeconv returns a hash reference');
```
I will submit a p.r. if the analysis is correct.

@khwilliamson 

Thank you very much.
Jim Keenan

**Comment by Grinnz** [comment]
> If that is the case then to say:
> 
> ```
> locales_enabled(qw(NUMERIC MONETARY));
> ```
> 
> ... would be an error because the function was being provided a list of scalars, not an array ref.

Just a nitpick on this point - it's an error because the prototype causes that to be a scalar qw, thus passing 'MONETARY' and discarding 'NUMERIC' resulting in the warning you got (much like if you did `my $foo = qw(NUMERIC MONETARY)`). Thus is the real danger of the `$` prototype. But otherwise this analysis looks correct to me.

**Comment by jkeenan** [comment]
On 10/16/20 9:46 PM, Dan Book wrote:
>     If that is the case then to say:
> 
>     |locales_enabled(qw(NUMERIC MONETARY)); |
> 
>     ... would be an error because the function was being provided a list
>     of scalars, not an array ref.
> 
> Just a nitpick on this point - it's an error because the prototype 
> causes that to be a scalar qw, thus passing 'MONETARY' and discarding 
> 'NUMERIC' resulting in the warning you got (much like if you did |my 
> $foo = qw(NUMERIC MONETARY)|). Thus is the real danger of the |$| 
> prototype. But otherwise this analysis looks correct to me.
> 

Can you explain what you mean by "scalar qw"?  (I've never encountered 
that terminology.)

Thank you very much.
Jim Keenan

**Comment by Grinnz** [comment]
The qw operator emulates the comma operator in scalar context; it will evaluate to the last item. But while using the comma operator in this instance will cause the prototype to throw an explicit error (too many arguments), the qw is interpreted as a single argument by the prototype, in scalar context.

**Comment by Grinnz** [comment]
```
print scalar(42, 43); # prints 43
print scalar qw(foo bar); # prints bar
print scalar(my @foo = (42, 43)); # prints 2, the size of the array
```
