### ISSUE TITLE
[doc] Time::Piece: mention how to deal with fractional seconds

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#18261]
Many users will be [scratching their heads](https://stackoverflow.com/questions/4012068/how-do-i-parse-microseconds-with-timepiece-strptime) about how to get e.g., 0.5 seconds parsed by Time::Piece.

Time::Piece says
>   Date Parsing
>       Time::Piece has a built-in strptime() function (from FreeBSD), allowing you **incredibly flexible** date
>       parsing routines. For example:
>
>         my $t = Time::Piece->strptime("Sunday 3rd Nov, 1943",
>                                       "%A %drd %b, %Y");

OK, but add an example of how to deal with decimal seconds: e.g., "2001-11-12T18:31:01.123Z"
Maybe the only way is
```
sub p {
    my $s = $_[0];
    $s=~s/(\.\d*)//;
    return Time::Piece->strptime( $s, "%Y-%m-%dT%H:%M:%SZ" ) + $1;
}
```
Say if that is cool or not cool. Say something, anything.
Say if one should turn to Time::HiRes here, or indeed CPAN packages.
Say if forcibly adding non integer seconds as I have above, while indeed working,
might build up residues due to float arithmetic.
Say that although in C struct tm only has intergers, but perl's Time::tm is not as strict, etc.

**Comment by Grinnz** [comment]
Time::Piece is maintained upstream on CPAN; its issue tracker can be found at https://rt.cpan.org/Public/Dist/Display.html?Name=Time-Piece.

**Comment by jidanni** [comment]
Very hard to tell that here on Debian.
```
$ man time::piece|tail -n 1
perl v5.30.3
```
OK, I made https://rt.cpan.org/Ticket/Display.html?id=133599

**Comment by jkeenan** [comment]
> Very hard to tell that here on Debian.
> 
> ```
> $ man time::piece|tail -n 1
> perl v5.30.3
> ```
> 
> OK, I made https://rt.cpan.org/Ticket/Display.html?id=133599

Issue has been sent to upstream bug-tracker.  Closing here.

Thank you very much.
Jim Keenan
