### ISSUE TITLE
[doc] perlsyn: give example when talking about "my" in "for" initialization section

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#18260]
In man perlsyn

>       There is one minor difference: if variables are declared with "my" in the initialization section of the
>      "for", the lexical scope of those variables is exactly the "for" loop (the body of the loop and the
>      control sections).

OK, but give an example saying if that syntax is
- `for my $i ($i = 1; $i < 10; $i++)` **or**
- `for (my $i = 1; $i < 10; $i++)`

(Answer: the latter is correct. But most users can only guess and then see which one creates an error and pick the other one.)

**Comment by Grinnz** [comment]
The first is invalid perl code for unrelated reasons. There are two 'for's, the C-style and the foreach style. The quoted documentation is in the C-style for loop section.

I agree that an example using `my` would be useful.

**Comment by jkeenan** [comment]
> I agree that an example using `my` would be useful.

Please review https://github.com/Perl/perl5/pull/18292.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
P.r. referenced above was superseded by commit dba7cf2eab.  Closing ticket.

Thank you very much.
Jim Keenan
