### ISSUE TITLE
[Win32] GNUmakefile and makefile.mk should define USE_MINGW_ANSI_STDIO by default

### ISSUE THREAD

**Issue by sisyphus** [Perl/perl5#18270]
Module:

**Description**

This is a resurrection of uncompleted business that was first raised in https://github.com/Perl/perl5/issues/15997
On mingw-built perls (s)printf formatting of numbers can be buggy if perl's nvtype is 'double' && perl was built without defining __USE_MINGW_ANSI_STDIO to a true value.
For example:

C:\>perl -le "printf '%.55g', 0.3;"
0.29999999999999999

https://github.com/Perl/perl5/pull/18262 appends a final test to t/op/sprintf2.t that fails if the bug is present. -Duselongdouble builds don't fail because __USE_MINGW_ANSI_STDIO is automatically defined for them.

I have been building perl with __USE_MINGW_ANSI_STDIO defined beginning with perl-5.26.0.
Strawberry Perl has also been defining it by default, beginning perl-5.26.0.
To my knowledge, no issues have been raised - apart from the occasional observation that something changed (ie was broken, now fixed) between 5.24 and 5.26.

AFAIK, there is no reason to NOT make it the default for mingw-built perls.

BTW, if you want to know whether a Windows perl has been built with "-D__USE_MINGW_ANSI_STDIO", just run <code>perl -V:ccflags</code> and check for the presence of that symbol. That's about the quickest way I can think of. 

**Steps to Reproduce**

**Expected behavior**

**Perl configuration**

```
```
[0001-Define-USE_MINGW_ANSI_STDIO-by-default.patch.txt](https://github.com/Perl/perl5/files/5434178/0001-Define-USE_MINGW_ANSI_STDIO-by-default.patch.txt)

[0002-Define-USE_MINGW_ANSI_STDIO-by-default.patch.txt](https://github.com/Perl/perl5/files/5434179/0002-Define-USE_MINGW_ANSI_STDIO-by-default.patch.txt)

**Comment by sisyphus** [comment]
I probably should provide a <code>perl -V</code> for one of these buggy Windows perls.
(Note the absence of "-D__USE_MINGW_ANSI_STDIO" from ccflags.)

Summary of my perl5 (revision 5 version 33 subversion 3) configuration:
   
  Platform:
    osname=MSWin32
    osvers=6.1.7601
    archname=MSWin32-x64-multi-thread
    uname=''
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='gcc'
    ccflags =' -DWIN32 -DWIN64 -fdiagnostics-color=never -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields'
    optimize='-s -O2'
    cppflags='-DWIN32'
    ccversion=''
    gccversion='8.3.0'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='long long'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags ='-s -L"C:\perl-5.33.3\lib\MSWin32-x64-multi-thread\CORE" -L"C:\_64\gcc-straw-830\mingw64\lib"'
    libpth=C:\_64\gcc-straw-830\mingw64\lib C:\_64\gcc-straw-830\mingw64\x86_64-w64-mingw32\lib C:\_64\msys_830\1.0\local\lib C:\_64\gcc-straw-830\mingw64\lib\gcc\x86_64-w64-mingw32\8.3.0
    libs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    libc=
    so=dll
    useshrplib=true
    libperl=libperl533.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-mdll -s -L"C:\perl-5.33.3\lib\MSWin32-x64-multi-thread\CORE" -L"C:\_64\gcc-straw-830\mingw64\lib"'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    HAVE_INTERP_INTERN
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_IMPLICIT_SYS
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under MSWin32
  Compiled at Oct 25 2020 18:37:06
  @INC:
    ..\lib
    C:/comp/perl-5.33.3/lib

**Comment by apparluk** [comment]
I recall installing the MSYS2 distribution's toolchain on top of Git-2.10.0-32-bit.exe.

Running a configure script with CFLAGS gcc-6.1.0-1 appended a duplicate entry for -mtune=.

**Comment by sisyphus** [comment]
I've now incorporated the amendments suggested here into https://github.com/Perl/perl5/pull/18262.
It might seem strange pushing win32 makefile amendments into a PR that purports to be about linux issues, but the issues raised in that PR do extend to Windows, and are fixed (for some windows systems at least) by these proposed makefie amendments.

**Comment by tonycoz** [comment]
#18262 was merged, can this be closed?

**Comment by sisyphus** [comment]
Yes - thanks Tony.
Closing.
Cheers,
Rob
