### ISSUE TITLE
missing error message in perldiag.pod for unicode properties

### ISSUE THREAD

**Issue by karenetheridge** [Perl/perl5#18276]
The diagnostic message `Unknown user-defined property name \p{%s}` is not documented in pod/perldiag.pod.
It originates from regcomp.c.

(Maybe not relevant, but it also looks like it changed, at least in some usecases, from `Can't find Unicode property definition "%s"` between 5.28 and 5.30.)

There are other error messages in this file that are also undocumented:
- "Timeout waiting for another thread to define .."
- "Infinite recursion in user-defined property"
- "Error.. in expansion of ..."
- "Insecure private-use override"

**Comment by apparluk** [comment]
The below error message but not the others is found in 5.28.3.

`Can't find Unicode property definition "%s"`

**Comment by jkeenan** [comment]
> The diagnostic message `Unknown user-defined property name \p{%s}` is not documented in pod/perldiag.pod.
> It originates from regcomp.c.
> 
> (Maybe not relevant, but it also looks like it changed, at least in some usecases, from `Can't find Unicode property definition "%s"` between 5.28 and 5.30.)
> 
> There are other error messages in this file that are also undocumented:
> 
>     * "Timeout waiting for another thread to define .."
> 
>     * "Infinite recursion in user-defined property"
> 
>     * "Error.. in expansion of ..."
> 
>     * "Insecure private-use override"

We might be able to work up some documentation by looking for places where these warnings are exercised in the test suite.

* "Unknown user-defined property name"
```
t/re/pat.t
2112:        fresh_perl_like('"q0" =~ /\p{__::Is0}/', qr/Unknown user-defined property name \\p\{__::Is0}/, {}, "GH #17384");

t/re/reg_mesg.t
266: 'm/\p{Is_Is_Any}/' => 'Unknown user-defined property name \p{main::Is_Is_Any}',
```

* "Timeout waiting for another thread to define .."
```
t/re/user_prop_race_thr.t
112:    qr/Thread \d+ terminated abnormally: Timeout waiting for another thread to define "InLongSleep" in regex/,

```
* "Infinite recursion in user-defined property"
```
t/re/regexp_unicode_prop.t
163:        'InRecursedA'   => qr/Infinite recursion in user-defined property (?#
```
* "Error.. in expansion of ..."
```
t/re/regexp_unicode_prop.t
161:                             )"0\t$overflow$utf8_comment" in expansion of (?#
164:                             )"main::InRecursedA" in expansion of (?#
165:                             )main::InRecursedC in expansion of (?#
166:                             )main::InRecursedB in expansion of (?#
171:                               )"BEEF CAGED" in expansion of main::IsNonHex/,
174:        'IsDeath'        => qr/Died.* in expansion of main::IsDeath/s,
533:fresh_perl_like(<<'EOP', qr/Can't find Unicode property definition "F000\\tF010" in expansion of InOneBadApple/, {}, "Just one component bad");
```
* "Insecure private-use override"
```
Not found in test suite
```

Thank you very much.
Jim Keenan

**Comment by khwilliamson** [comment]
Since I wrote those, I can work up the documentation.  But it's worrisome that perldiag.t did not catch that these weren't defined.

**Comment by jkeenan** [comment]
> The diagnostic message `Unknown user-defined property name \p{%s}` is not documented in pod/perldiag.pod.
> It originates from regcomp.c.
> 
> (Maybe not relevant, but it also looks like it changed, at least in some usecases, from `Can't find Unicode property definition "%s"` between 5.28 and 5.30.)
> 
> There are other error messages in this file that are also undocumented:
> 
>     * "Timeout waiting for another thread to define .."
> 
>     * "Infinite recursion in user-defined property"
> 
>     * "Error.. in expansion of ..."
> 
>     * "Insecure private-use override"

These error messages are not being recognized by the part of `t/porting/diag.t` that precedes the parsing of `pod/perldiag.pod`.  That part (i) parses `embed.fnc` to get a list of Perl internal functions which typically generate warnings or exceptions and then (ii) composes regexes which are subsequently applied to C-source files.

`regcomp.c` appears to make heavy use of internal function `sv_catpvs()` in composing error messages.  For example:
```
  unknown_user_defined:
    if (SvCUR(msg) > 0) sv_catpvs(msg, "; ");
    sv_catpvs(msg, "Unknown user-defined property name");
    goto append_name_to_msg;

  failed:
    if (non_pkg_begin != 0) {
        if (SvCUR(msg) > 0) sv_catpvs(msg, "; ");
        sv_catpvs(msg, "Illegal user-defined property name");
    }
    else {
        if (SvCUR(msg) > 0) sv_catpvs(msg, "; ");
        sv_catpvs(msg, "Can't find Unicode property definition");
    }
```
However, other C source files do not appear to make use of `sv_catpvs` for this particular purpose.  Hence, we can hypothesize that `t/porting/diag.t` is failing to flag these error messages because it can't recognize the way they're being generated in the source code.
