### ISSUE TITLE
BBC: Blead Breaks Clone

### ISSUE THREAD

**Issue by cjg-cguevara** [Perl/perl5#18295]
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.42 running under perl 5.33.4.

-----------------------------------------------------------------
[Please describe your issue here]

BBC: Blead Breaks Clone

Please see http://fast-matrix.cpantesters.org/?dist=Clone

[Please do not change anything below this line]
-----------------------------------------------------------------
---
Flags:
    category=core
    severity=low
---
Site configuration information for perl 5.33.4:

Configured by cpan at Thu Nov  5 10:45:15 EST 2020.

Summary of my perl5 (revision 5 version 33 subversion 4) configuration:
  Commit id: ec5a5b629f2f5a9b63b27eb6d71233781d32ae61
  Platform:
    osname=linux
    osvers=5.4.72-0-lts
    archname=x86_64-linux
    uname='linux cjg-alpine3 5.4.72-0-lts #1-alpine smp mon, 19 oct 2020 06:22:29 utc x86_64 linux '
    config_args='-des -Dprefix=~/bin/perl-blead -Dscriptdir=~/bin/perl-blead/bin -Dusedevel -Duse64bitall'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong'
    ccversion=''
    gccversion='9.3.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/include/fortify /usr/lib /usr/local/lib /lib/../lib /usr/lib/../lib /lib
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/usr/lib/libc.a
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'

---
@INC for perl 5.33.4:
    /home/cpan/bin/perl-blead/lib/site_perl/5.33.4/x86_64-linux
    /home/cpan/bin/perl-blead/lib/site_perl/5.33.4
    /home/cpan/bin/perl-blead/lib/5.33.4/x86_64-linux
    /home/cpan/bin/perl-blead/lib/5.33.4

---
Environment for perl 5.33.4:
    HOME=/home/cpan
    LANG=C.UTF-8
    LANGUAGE (unset)
    LC_ALL=C
    LC_COLLATE=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl-blead/bin:/home/cpan/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

**Comment by haarg** [comment]
This is due to 6bcc2902c48af9c08df64250eecdebf7d8a216b3.

Clone is using the `PERL_MAGIC_UTF8_CACHESIZE` macro, which is no longer defined without `PERL_CORE`.

**Comment by jkeenan** [comment]
> This is due to [6bcc290](https://github.com/Perl/perl5/commit/6bcc2902c48af9c08df64250eecdebf7d8a216b3).
> 

Confirmed via bisection.
```
6bcc2902c48af9c08df64250eecdebf7d8a216b3 is the first bad commit
commit 6bcc2902c48af9c08df64250eecdebf7d8a216b3
Author: Karl Williamson <khw@cpan.org>
Date:   Sat Oct 17 15:58:01 2020 -0600

    Certain PERL_UNICODE symbols are core only

```

> Clone is using the `PERL_MAGIC_UTF8_CACHESIZE` macro, which is no longer defined without `PERL_CORE`.

@khwilliamson , can you take a look at this?

Thank you very much.
Jim Keenan
