### ISSUE TITLE
[doc] Missing single quote in a "use feature ..." construct

### ISSUE THREAD

**Issue by vaitkus** [Perl/perl5#18315]
**Where**

https://perldoc.perl.org/functions/split

**Description**

Sentence
```
As of Perl 5.28, this special-cased whitespace splitting works as expected in
the scope of "use feature 'unicode_strings".
```
seems to be missing a closing single quote (``"use feature 'unicode_strings"`` instead of ``"use feature 'unicode_strings'"``).

**Comment by jkeenan** [comment]
> **Where**
> 
> https://perldoc.perl.org/functions/split
> 
> **Description**
> 
> Sentence
> 
> ```
> As of Perl 5.28, this special-cased whitespace splitting works as expected in
> the scope of "use feature 'unicode_strings".
> ```
> 
> seems to be missing a closing single quote (`"use feature 'unicode_strings"` instead of `"use feature 'unicode_strings'"`).

Thanks.  Fixed in cae6fd476d.
