### ISSUE TITLE
BBC: Blead Breaks Want

### ISSUE THREAD

**Issue by cjg-cguevara** [Perl/perl5#18321]
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.42 running under perl 5.33.4.

-----------------------------------------------------------------
[Please describe your issue here]

BBC: Blead Breaks Want

Please see http://fast-matrix.cpantesters.org/?dist=Want

[Please do not change anything below this line]
-----------------------------------------------------------------
---
Flags:
    category=core
    severity=low
---
Site configuration information for perl 5.33.4:

Configured by cpan at Sun Nov 15 06:37:36 EST 2020.

Summary of my perl5 (revision 5 version 33 subversion 4) configuration:
  Commit id: d1388a9f14b371b498f17bd56e201989bc88d12e
  Platform:
    osname=freebsd
    osvers=11.4-release-p3
    archname=amd64-freebsd
    uname='freebsd cjg-freebsd11 11.4-release-p3 freebsd 11.4-release-p3 #0: tue sep 1 08:22:33 utc 2020 root@amd64-builder.daemonology.net:usrobjusrsrcsysgeneric amd64 '
    config_args='-des -Dprefix=~/bin/perl-blead -Dscriptdir=~/bin/perl-blead/bin -Dusedevel -Duse64bitall'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    optimize='-O2'
    cppflags='-DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='FreeBSD Clang 10.0.0 (git@github.com:llvm/llvm-project.git llvmorg-10.0.0-0-gd32170dbd5b)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags ='-Wl,-E  -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/lib /usr/local/lib /usr/lib/clang/10.0.0/lib /usr/lib
    libs=-lpthread -lgdbm -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags='-DPIC -fPIC'
    lddlflags='-shared	-L/usr/local/lib -fstack-protector-strong'

---
@INC for perl 5.33.4:
    /home/cpan/bin/perl-blead/lib/site_perl/5.33.4/amd64-freebsd
    /home/cpan/bin/perl-blead/lib/site_perl/5.33.4
    /home/cpan/bin/perl-blead/lib/5.33.4/amd64-freebsd
    /home/cpan/bin/perl-blead/lib/5.33.4

---
Environment for perl 5.33.4:
    HOME=/home/cpan
    LANG (unset)
    LANGUAGE (unset)
    LC_ALL=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl-blead/bin:/home/cpan/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/cpan/bin
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/bash

**Comment by jkeenan** [comment]
> This is a bug report for perl from "Carlos Guevara" [carlos@carlosguevara.com](mailto:carlos@carlosguevara.com),
> generated with the help of perlbug 1.42 running under perl 5.33.4.
> 
> [Please describe your issue here]
> 
> BBC: Blead Breaks Want

Bisection points to the following commit:

```
a5d5855671af6956a8d1a13e419457afdffeb416 is the first bad commit
commit a5d5855671af6956a8d1a13e419457afdffeb416
Author: Karl Williamson <khw@cpan.org>
Date:   Sat Oct 17 09:20:52 2020 -0600
Commit:     Karl Williamson <khw@cpan.org>
CommitDate: Fri Nov 13 07:09:01 2020 -0700


    op.h: Restrict scope of multiconcat symbols to core
    
    These are internal only
```
@khwilliamson , can you take a look?

Thank you very much.
Jim Keenan

**Comment by khwilliamson** [comment]
reverted by e207d6495b6cf122726e0f05a14616be7cac9c74
