### ISSUE TITLE
[feature] usequadmath vs uselongdouble

### ISSUE THREAD

**Issue by PhilterPaper** [Perl/perl5#18322]
**Please do not report bugs as part of a feature request**

I have a package on CPAN that testers are throwing "long double" and "quad math" Perl builds at. I recently fixed the false fails (t-tests) for "long double" by 
```
use Config;
...
if ($Config{uselongdouble}) { ...test floating point value with extra digits... } 
else { ...test floating point value with fewer digits... }
```
Now testers are using "quad math" and the t-tests are failing again, expecting even _more_ digits of precision. Looking through Config on my local Perl, I see "uselongdouble" (V.pm) but I don't see anything mentioning "quad". According to various bits of discussion, long double =/= quad math.

I have only Perl 5.26.1 and can't upgrade to 5.3x, so it's possible that "usequadmath" or the equivalent is already in Config. Is that the correct incantation? More importantly, should "long double" always give the same results, and "quad math" (if in) give consistent results (different from "standard" math and "long double")? If not, I'll have to do some rounding in the t-tests to get to a standard representation of floats!

**Describe the solution you'd like**

If not already in Perl and the Config module, I need some sort of "usequadmath" (in addition to "uselongdouble") that allows me to test (especially in t-tests) the extended precision floating point values that a Perl built with the quad math library will return. I also need for both "long double" and "quad math" to _consistently_ return values, not dependent on the particular CPU or operating system.

**Comment by jkeenan** [comment]
> I have a package on CPAN that testers are throwing "long double" and "quad math" Perl builds at. I recently fixed the false fails (t-tests) for "long double" by
> 
> ```
> use Config;
> ...
> if ($Config{uselongdouble}) { ...test floating point value with extra digits... } 
> else { ...test floating point value with fewer digits... }
> ```
> 
> Now testers are using "quad math" and the t-tests are failing again, expecting even _more_ digits of precision. Looking through Config on my local Perl, I see "uselongdouble" (V.pm) but I don't see anything mentioning "quad". According to various bits of discussion, long double =/= quad math.

See `INSTALL` in the top-level of the Perl core distribution.  Search for `longdouble` and `quadmath`.  You'll find them described as Perl configuration options quite close by each other.  As options for `Configure`, they are spelled `uselongdouble` and `usequadmath`, i.e., without wordspaces.

> 
> I have only Perl 5.26.1 and can't upgrade to 5.3x, 

I can understand that in a production environment you might be limited to a particular version of `perl`.  However, if you are developing modules for CPAN, you would be well advised to create a development environment with tools like `perlbrew` or `plenv` that enable you to quickly switch between different versions of `perl`.

> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> If not already in Perl and the Config module, I need some sort of "usequadmath" (in addition to "uselongdouble") that allows me to test (especially in t-tests) the extended precision floating point values that a Perl built with the quad math library will return. 

As noted above, you already have it, even in perl-5.26.

> I also need for both "long double" and "quad math" to _consistently_ return values, not dependent on the particular CPU or operating system.

I'll leave it to others to comment as to whether you can hard-code values into your test suite which are guaranteed to pass regardless of "the particular CPU or operating system."

See also: https://en.wikipedia.org/wiki/Quadruple-precision_floating-point_format and https://en.wikipedia.org/wiki/Long_double

Thank you very much.
Jim Keenan

**Comment by PhilterPaper** [comment]
Hi Jim,

Thanks for the update. It sounds like I can go ahead and use `if ($Config{usequadmath}) {`. I still would like to know whether I can count on _all_ longdoubles returning the same value, and _all_ quadmaths returning the same value. For that matter, do lesser precision implementations guarantee the same results on all CPUs and OS's? If not, what's the best way to handle this? Will I have to round returned values before doing comparisons on them? What's the least precision I can count on? Currently I'm prereq'ing Perl 5.10.0 for this particular package -- is there any advantage to going to a later version?

I will look into your suggestions for setting up multiple Perl versions for testing (perlbrew or plenv). Thanks!

**Comment by tonycoz** [comment]
> 
> 
> Hi Jim,
> 
> I still would like to know whether I can count on _all_ longdoubles returning the same value, and _all_ quadmaths returning the same value. For that matter, do lesser precision implementations guarantee the same results on all CPUs and OS's?

No, you can't depend on this universally.

For at least one compiler long double is the same as double, and some long double implementations aren't simple expansions in range and precision of double.

> If not, what's the best way to handle this? Will I have to round returned values before doing comparisons on them? What's the least precision I can count on?

The usual way is to define a minimal error:

```
cmp_ok(abs($expected - $result), '<', 1e-6, "check result close to expected");
```

Note that the epsilon needs to scale with the expected result, so if expected is 1e20, you might have an epsilon of 1e12 (depending on whether we're using double, long double or quadmath.)

The minimum precision you can expect, from the C standard:
```
DBL_DECIMAL_DIG 10
LDBL_DECIMAL_DIG 10
```
from quadmath.h:
```
FLT128_DIG 33
```
The standard also defines minimal (or maximum) requirements epsilon values:

```
DBL_EPSILON 1E-9
LDBL_EPSILON 1E-9
```
and quadmath:
```
FLT128_EPSILON 1.92592994438723585305597794258492732e-34Q
``

which are the "difference between 1 and the least value greater than 1 that is representable in the
given floating point type", so it *isn't* directly usable as the epsilon above, but could be used as a basis for it.

`Data::Float` exposes some of these values.

**Comment by PhilterPaper** [comment]
Hi Tony,

Thanks for the info. It sounds like I can't depend on any level of precision math to always result in the same values, and will have to either round to a safe level, or do some sort of "epsilon" comparison. Either way, I can't use the raw values as done currently. Is there a minimum number of digits that Perl guarantees (say, IEEE short float 6 digits or IEEE double float 15 digits)? If I round to that, the same comparison should work anywhere, shouldn't it? (regardless of using long double or quad math)

The particular test case where this is showing up is
```
calculate $col_widths...
if ($Config{uselongdouble}) {
  is_deeply( $col_widths, [ 51, 300.758439703998205, 48 ], 'CalcColumnWidths - uneven');
} elsif ($Config{usequadmath}) {
  is_deeply( $col_widths, [ 51, 300.75843970399820542273901264938, 48 ], 'CalcColumnWidths - uneven');
} else {
  is_deeply( $col_widths, [ 51, 300.758439703998, 48 ], 'CalcColumnWidths - uneven');
}
...more tests...
```
Originally, it was just the last "is_deeply" test, and 15 digits is quite unnecessary for this application. Unless "is_deeply" can be told to use an epsilon or something, I'm guessing that the easiest thing would be to take `$col_widths->[1]` and round it to, say, 3 decimal digits (300.758) and doing just one check
```
$col_widths->[1] = int(1000*$col_widths->[1] + 0.5)/1000;  # round to 3 decimal places
is_deeply( $col_widths, [51, 300.758, 48], 'CalcColumnWidths - uneven');
```
Does that sound reasonably robust? I haven't tried out this code yet, but something along those lines?

By the way, since I don't have a long double or quad math Perl, what would be the best way to test for such sensitivity to decimal places, short of actually releasing a new version and waiting to see which tests fail? Would I be best off using perlbrew or plenv to do testing on Perl 32-bit, long double, and quad math builds?

**Comment by tonycoz** [comment]
No, rounding isn't the solution in general, numbers very close in value can round to different numbers, for example 1.49996 and 1.49994 round at four places to 1.5000 and 1.4999.

Perl uses double at minimum, it never uses float.

You might want to consider  [Test::Deeply::Float](https://metacpan.org/pod/Test::Deeply::Float) which does the deep comparison with an epsilon, or [Test::Deep](https://metacpan.org/pod/Test::Deep) which has a more flexible approach.

**Comment by PhilterPaper** [comment]
Tony, I will take a look at `Test::Deeply::Float` and `Test::Deep`, but for now I'm just going to carefully round my results and compare to the rounded value (keeping your caution in mind). It occurs to me that a platform using non-IEEE-754 format floating point (e.g., IBM z-series) could get different results even on "standard" doubles. I'll just have to round results as problems pop up in CPAN test logs. The effect of using an _epsilon_ value in comparisons is more or less the same as rounding to fewer significant digits.

Thank you everyone for the useful information. I will close this ticket now.
