### ISSUE TITLE
Failure in lossless_NV_to_IV()

### ISSUE THREAD

**Issue by khwilliamson** [Perl/perl5#18328]
We are getting  error messages like this
./inline.h:1983:48: warning: implicit conversion from 'IV' (aka 'long') to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-int-float-conversion]
sv.c:2058:22: warning: implicit conversion from 'UV' (aka 'unsigned long') to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Wimplicit-int-float-conversion]
sv.c:11137:27: warning: implicit conversion from 'UV' (aka 'unsigned long') to 'double' changes value from 18446744073709551615 to 18446744073709551616 [-Wimplicit-int-float-conversion]

on some smoke boxes.  Sample report
[http://perl.develop-help.com/raw/?id=260611](url)

@sisyphus do you have any ideas?

```

**Comment by sisyphus** [comment]
@khwilliamson I'm thinking (untested) that an explicit cast is all that's needed to silence the warnings.

inline.h:1983 becomes:
if (!(LIKELY(nv >= (NV)IV_MIN) && LIKELY(nv <= (NV)IV_MAX))) {

sv.c:2058:2058 becomes:
if (SvNVX(sv) <= (NV)IV_MAX) {

sv.c:11137: becomes:
if (nv != 0.0 && nv < (NV)UV_MAX) {

Line 2058 of sv.c (in its current state) looks odd, as I can't see any reason that you would cast IV_MAX to a UV before comparing it to an NV.
I suspect it's a typo, and that the original intention was to cast it to an NV.

Conditions like <code>( nv <= (NV)IV_MAX )</code> look a bit odd, because that will evaluate as true when nv is 9223372036854775808.0 (which is exactly representable as a double) and IV_MAX is 9223372036854775807.
But, if the original code was doing the right thing, then those changes will also be doing the right thing.

That is, the condition has not altered - irrespective of whether the cast to NV is explicit or implicit.

**Comment by khwilliamson** [comment]
On 11/17/20 12:53 AM, sisyphus wrote:
> @khwilliamson <https://github.com/khwilliamson> I'm thinking (untested) 
> that an explicit cast is all that's needed to silence the warnings.
> 
> inline.h:1983 becomes:
> if (!(LIKELY(nv >= (NV)IV_MIN) && LIKELY(nv <= (NV)IV_MAX))) {
> 
> sv.c:2058:2058 becomes:
> if (SvNVX(sv) <= (NV)IV_MAX) {
> 
> sv.c:11137: becomes:
> if (nv != 0.0 && nv < (NV)UV_MAX) {
> 
> Line 2058 of sv.c (in its current state) looks odd, as I can't see any 
> reason that you would cast IV_MAX to a UV before comparing it to an NV.
> I suspect it's a typo, and that the original intention was to cast it to 
> an NV.
> 
> Conditions like |( nv <= (NV)IV_MAX )| look a bit odd, because that will 
> evaluate as true when nv is 9223372036854775808.0 (which is exactly 
> representable as a double) and IV_MAX is 9223372036854775807.
> But, if the original code was doing the right thing, then those changes 
> will also be doing the right thing.
> 
> That is, the condition has not altered - irrespective of whether the 
> cast to NV is explicit or implicit.
>

I have now created a smoke test using branch smoke-me/khw-nv.  We'll see 
what happens.

But looking at the code in more detail leads me to think there is an 
inconsistency between the S_lossless_NV_to_IV() function and the I_V() 
cast macro, which calls Perl_cast_iv().  These have extra 
considerations, that we may well want to use.

**Comment by sisyphus** [comment]
Unless they already exist, there should be tests written to specifically verify that the NVs 18446744073709551616.0, 9223372036854775808.0, and -9223372036854775808.0 are being handled as intended in all of these situations.

On perls whose NV and IV are both 8 bytes, it's a bit interesting that S_lossless_NV_to_IV() returns FALSE when the NV is 9223372036854775808.0.
For that value (on that specific perl configuration), both the NV and the IV represent the same bit structure - ie  a leading 1-bit followed by 63 0-bits, with (UV)nv == nv.
So, strictly speaking, there has been no *loss of data*, yet the function returns FALSE on the basis that <code>(IV) nv != nv</code>

Still, I presume that's as intended.

**Comment by khwilliamson** [comment]
I believe that `( nv <= (NV)IV_MAX )` is more accurately written as `nv < IV_MAX_P1`, where the latter is also an NV.

The function should return false based on the above condition, but it was correctly returning false because the` (IV) nv != nv` acted as a safeguard.  9223372036854775808 is not a legal IV, and the function is for IVs.  That number is a legal UV, and if the return were a UV, there would be no loss  of data, but since the return is an IV, it does.

This whole thing leaves me uneasy though.  I wrote this function, but I was only consolidating into one consistent place several slightly different permutations of it that were scattered around the code.  I think the main issue is some compilers have broken NaN compare.  That makes me think that there are other places in the code that should be using this and aren't, and that there should be something equivalent for UVs as well.  Or these broken compilers are no longer used or are fixed, so it doesn't matter.

**Comment by sisyphus** [comment]
In short:
I think that "broken NaN compare" is very rare in C toolchains nowadays - but YMMV if you're prepared to use ancient C toolchains.
(To gain a more objective assessment of that brokenness, we'd need a perl test suite that reports it whenever it is encountered - and it seems to me that we don't have that at the moment.)

I cannot fault the job that S_lossless_NV_to_IV() does.
I reckon that eradicating those warnings that prompted the creation of this ticket is worthwhile.
And, if it were up to me. I'd just sit back and not worry about any other considerations until I was confronted with evidence that there is something else that needs to be changed.

Just my 200 rupiah's worth.
