### ISSUE TITLE
Perlbrew at /opt/perl5 installation problem.

### ISSUE THREAD

**Issue by lifeboatpres** [Perl/perl5#18336]
I was installing perlbrew at /opt/perl5 so multiple people could use the same version of Perl.

I did this installation after I had already installed perlbrew in my home directory (with the idea that I would delete that perlbrew after /opt/perl5 worked.)

This caused /opt/perl5/bin/perlbrew to start with #!/home/lifeboat/perl5/perlbrew/perls/perl-5.22.0/bin/perl which was a problem once the perlbrew in /home/lifeboat was deleted. It would have been better if the perlbrew installation script had used #!/usr/bin/perl instead.

**Comment by Grinnz** [comment]
This isn't anything core Perl can affect. The perlbrew issue tracker is at https://github.com/gugod/App-perlbrew/issues.

**Comment by Grinnz** [comment]
FWIW, I recommend installing a site-wide Perl without the complication of Perlbrew which is designed for a single user. [perl-build](http://metacpan.org/pod/perl-build) can make this easy.

**Comment by lifeboatpres** [comment]
Thank you very much for your comments!
