### ISSUE TITLE
[doc] paragraph mode discards any number of newlines at the beginning of the file

### ISSUE THREAD

**Issue by learnbyexample** [Perl/perl5#18352]
**Where**

https://perldoc.perl.org/perlvar#$/

**Description**

The document says:

>When `$/` is set to `""` and the entire file is read in with that setting, any sequence of consecutive newlines `"\n\n"` at the beginning of the file is discarded.

On testing, I find that a single newline at the beginning of the file is also discarded:

```bash
$ s='\na\nb\n\n12\n34\n\nhi'

$ printf '%b' "$s" | perl -00 -lnE 'say if $. == 1'
a
b
```

I don't think this is a bug, as this behavior is seen with `awk` too:

```bash
$ printf '%b' "$s" | awk -v RS= 'NR==1'
a
b
```

**Comment by khwilliamson** [comment]
Taking a legalistic view, a single \n can be construed as "any sequence of newlines".  But what would you like it to say instead?

**Comment by learnbyexample** [comment]
>any sequence of newlines

That would be fine with me, currently it says

>any sequence of **consecutive newlines "\n\n"**

**Comment by Grinnz** [comment]
Perhaps it would be clearest to say: "any sequence of one or more consecutive newlines"

**Comment by khwilliamson** [comment]
On 11/26/20 6:38 PM, Dan Book wrote:
> Perhaps it would be clearest to say: "any sequence of 1 or more 
> consecutive newlines"
> 

That sounds good to me; anyone want to prepare a patch?
