### ISSUE TITLE
[doc] memEQ and possible more incorrect in perlapi

### ISSUE THREAD

**Issue by toddr** [Perl/perl5#18379]
Looking at the generated docs for MemEQ: https://perldoc.perl.org/perlapi#memEQ

```
Test two buffers (which may contain embedded NUL characters, to see if they are equal. The len parameter indicates the number of bytes to compare. Returns zero if equal, or non-zero if non-equal.
```

But handy.h is doing this which I think is an inversion of what is stated?
```c
#define memEQ(s1,s2,l) (memcmp(((const void *) (s1)), ((const void *) (s2)), l) == 0)
```

**Comment by atoomic** [comment]
probably the same error from memNE 

docs are in handy.h

**Comment by toddr** [comment]
The docs for this were added in bd18bd40081 and appear to have been wrong from the start?
