### ISSUE TITLE
[doc] Add dynamic regexp modifier example

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#18387]
perlop and perlre explain everything in extreme detail, but never seem
to give an example of how to write the modifier of

```
/bla/i
```
dynamically.

Nope,

```
my $modifier='i';
/bla/$modifier
```
won't work.

Sure, one could use 'eval', but that would end up eval'ing the /bla/
part too.

So please add an example to those documentation pages.

Or mention the only way is to do
```
if($modifier eq 'i'){
... /bla/i ...
elsif($modifier eq 'ia'){
    /bla/ia ...
```
etc. Thanks.

Hmmm, reminds me of sprintf:
```
    You can also get the precision from the next argument using
     ".*", or from a specified argument (e.g., with ".*2$"):
```

**Comment by Grinnz** [comment]
https://perldoc.perl.org/perlre#(?adlupimnsx-imnsx)

**Comment by Grinnz** [comment]
Alternatively, https://perldoc.perl.org/re#'/flags'-mode

**Comment by jidanni** [comment]
That's all great news.

But please be sure to say something about it within the Modifiers section,

```
$ egrep ^=head2\|flexible /usr/share/perl/5.32.0/pod/perlre.pod
=head2 The Basics
=head2 Modifiers
=head2 Regular Expressions
=head2 Quoting metacharacters
=head2 Extended Patterns
    # more flexible:
=head2 Backtracking
```

Otherwise the user will have given up long before making it down to that section.

So at the bottom of the Modifiers sections, say "Modifiers can also be
given dynamically. See ..."

Thanks!

**Comment by jkeenan** [comment]
I'm not sure I see a real need for this addition to the documentation, but if others want it, https://github.com/Perl/perl5/pull/18481 should suffice.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
Handled by https://github.com/Perl/perl5/commit/a19f6621766baa4f472625c06f146105b33d441d; closing ticket.

Thank you very much.
Jim Keenan
