### ISSUE TITLE
[doc] Request better documentation of "my"

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#18389]
```
$ perldoc -f my
    my VARLIST
    my TYPE VARLIST
    my VARLIST : ATTRS
    my TYPE VARLIST : ATTRS
            A "my" declares the listed variables to be local (lexically) to
            the enclosing block, file, or "eval"...
```
OK but be sure to mention when its OK, and when not:

```
$ cat e.pl
use strict;
use warnings 'all';
my $e = 1;
my $e = 1;
{
    $e = 1;
    my $e = 1;
}
$ perl e.pl
"my" variable $e masks earlier declaration in same scope at e.pl line 4.
```
So only one of the three my's is bad.
So *perldoc -f my* needs to tell the *user* why. (Don't tell *me* why.)
Maybe the details are in perlsub. But we aren't using subroutines here,
so the user won't look there on his own.

**Comment by richardleach** [comment]
Some text such as the following? (Which hopefully matches up with the error description in [perldiag.pod](https://github.com/Perl/perl5/blob/blead/pod/perldiag.pod).)
`Variables should not subsequently be redeclared in the same scope or statement.`

**Comment by khwilliamson** [comment]
Please submit a PR

**Comment by richardleach** [comment]
PR coming shortly.

**Comment by richardleach** [comment]
We added additional text in https://github.com/Perl/perl5/commit/920000260c5f3f16e119b8e4840a3c9f89ba3988. Closing this issue.
