### ISSUE TITLE
Misleading 'Found = in conditional, should be ==' warning

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#18392]
Consider the following program, which is adapted from `t/op/my.t` in the Perl 5 core distribution.
```
$ cat my1.pl
use strict;
use Test::More (tests => 1);

my $i = 'outer';

if (my $i = "inner") {
    is( $i, 'inner', 'my variable inside conditional propagates inside block');
}
```
Running it, we get:
```
$ perl my1.pl 
1..1
ok 1 - my variable inside conditional propagates inside block
```

Now let's activate warnings and run the revised program:
```
$ cat my2.pl 
use strict;
use warnings;
use Test::More (tests => 1);

my $i = 'outer';

if (my $i = "inner") {
    is( $i, 'inner', 'my variable inside conditional propagates inside block');
}

$ perl my2.pl 
1..1
Found = in conditional, should be == at my2.pl line 7.
ok 1 - my variable inside conditional propagates inside block
```

That warning is misleading; there's no numeric comparison needed here.  But it appears the compiler is getting confused here.  Other than simply suppressing the warning (`no warnings 'syntax';`), is there a better way to approach this?

Thank you very much.
Jim Keenan

**Comment by Grinnz** [comment]
I would not consider this misleading since it is the correct warning - the assignment is pointless, but since you are using it as part of a syntax test, you should disable the warning.

**Comment by jkeenan** [comment]
On 12/9/20 9:15 PM, Dan Book wrote:
> I would not consider this misleading since it is the correct warning - 
> the assignment is pointless, but that you are testing an edge case where 
> the warning should be disabled.
> 

Would there be any other way of generating the condition which the test 
is designed to exercise?

**Comment by Grinnz** [comment]
```
my $i = 'outer';

if (my $i or 1) {
    is( $i, undef, 'my variable inside conditional propagates inside block');
}
```

**Comment by xenu** [comment]
>I would not consider this misleading since it is the correct warning - the assignment is pointless, but since you are using it as part of a syntax test, you should disable the warning.

It isn't pointless, it's a reasonable way to declare a variable restricted to a new scope.

Anyway, I agree that it's a bug and this warning doesn't make sense for **declarations**.

**Comment by xenu** [comment]
>Would there be any other way of generating the condition which the test
is designed to exercise?

Apparently, `if ( my($foo) = 1 ) { ... }` doesn't warn.

**Comment by Grinnz** [comment]
> > I would not consider this misleading since it is the correct warning - the assignment is pointless, but since you are using it as part of a syntax test, you should disable the warning.
> 
> It isn't pointless, it's a reasonable way to declare a variable restricted to a new scope.
> 
> Anyway, I agree that it's a bug and this warning doesn't make sense for **declarations**.

I mean that assigning a literal as an if condition is pointless.

The warning could be updated to ignore assigning to newly declared lexicals, but this example would never happen in real code.

**Comment by jkeenan** [comment]
> ```
> my $i = 'outer';
> 
> if (my $i or 1) {
>     is( $i, undef, 'my variable inside conditional propagates inside block');
> }
> ```

I like this.  The conditional is now more unambiguously described by the test description.

**Comment by Leont** [comment]
> It isn't pointless, it's a reasonable way to declare a variable restricted to a new scope.

AFAICT the warning only shows up if the right hand is a literal, it doesn't show up if it's a full expression. Otherwise I would have agreed with you.

This may also work for this test:
```
my $i = "outer";
my $j = "inner";
if (my $i = $j) {
    is( $i, 'inner', 'my variable inside conditional propagates inside block');
}
```

**Comment by happy-barney** [comment]
looking into condition in S_scalarboolean, this warning text can be considered misleading (something like "Found = in condition, assigning constant value ...")

**Comment by jkeenan** [comment]
No consensus as to need for action; closing ticket.

**Comment by mauke** [comment]
> > Other than simply suppressing the warning (`no warnings 'syntax';`), is there a better way to approach this?
> 
> Were you suggesting that there is a way to disable this warning? If so, would you mind sharing?

I am confused. The code to disable syntax warnings is right there in the message you quoted:
```perl
no warnings 'syntax';
```
