### ISSUE TITLE
[doc] Missing description for "[C99]" in POSIX.pod

### ISSUE THREAD

**Issue by t-a-k** [Perl/perl5#18404]
**Where**
POSIX.pod

**Description**
In POSIX.pod, C99 math functions are marked with `[C99]` tag, but meanings of this tag does not seem to be documented.

Current POSIX.xs seems to always provide these C99 functions with its fallback implementations, so these tag does not indicate availability of these functions in Perl.  Anyway, I think POSIX.pod should have a description for what `[C99]` means.

**Comment by khwilliamson** [comment]
I added text that addressed this omission.  There are no fallbacks for these functions in the POSIX module; instead if you are getting them, it means that the C library contains these functions, regardless of whether it is full C99 or not.

If there are improvements needed to my text, you can reopen this ticket
