### ISSUE TITLE
Please upload latest Storable version to CPAN

### ISSUE THREAD

**Issue by rovo89** [Perl/perl5#18409]
@xsawyerx @tonycoz
Could you please consider uploading the latest Storable version to CPAN? Version 3.15 had the bug with Regexp in combination with repeated references, fixed in 16f2ddb794883529d5a3ad8326974a07aae7e567. One of my scripts suffered from that issue, and when I had finally tracked it down and was ready to report it along with a vague idea of a fix, I found that it had already been fixed a while ago. Thanks!

By the way, for me the symptom was different, it didn't croak but retrieved a reference pointing to the wrong thing.

**Comment by rovo89** [comment]
FYI, this is my code for reproducing the issue:

```perl
use Storable qw(nfreeze thaw);
$Storable::canonical = 1;

my $hashref = {example => 'myvalue'};
my $original = {first  => qr/abc/, second => $hashref, third => $hashref};
my $frozen = nfreeze($original);
my $clone = thaw($frozen);

use Data::Dumper;
$Data::Dumper::Sortkeys = 1;
print Dumper($original, $clone);
```

It gives this output with Storable 3.15:
```perl
$VAR1 = {
          'first' => qr/abc/u,
          'second' => {
                        'example' => 'myvalue'
                      },
          'third' => $VAR1->{'second'}
        };

$VAR2 = {
          'first' => qr/abc/u,
          'second' => {
                        'example' => 'myvalue'
                      },
          'third' => \$VAR2->{'second'}{'example'}
        };
```

Same code is working as expected with the contents of https://github.com/Perl/perl5/tree/blead/dist/Storable and `ppport.h` 3.62.

**Comment by jkeenan** [comment]
@xsawyerx, could you handle this CPAN upload?  We're at 3.23 in core but only at 3.15 upstream.

Thank you very much.
Jim Keenan

**Comment by tonycoz** [comment]
@xsawyerx if you give me co-maint I can do it

**Comment by rovo89** [comment]
Thanks @nwc10 for the updates and for pushing them to CPAN 👍

**Comment by xsawyerx** [comment]
Sorry. I wasn't monitoring the Github issues. Next time, it's probably better to reach out directly to me. You have my contact details. :)
