### ISSUE TITLE
Including a new POD file requires much work, is inadequately documented

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#18413]
As I learned the hard way today while working on https://github.com/Perl/perl5/pull/18275, including a new POD file in the core distribution is not as simple as creating a correctly formatted file in `.pod` format, placing it in the `pod/` directory, and inserting a new entry into the proper location in the `MANIFEST`.  Because listings to `pod/*.pod` files are found in several places in the core in addition to `MANIFEST`, the task is non-trivial and would benefit from a combination of further documentation and further automation.

What follows is my re-creation of the porting problem I faced this morning for `pod/perldocstyle.pod`.  It's quite detailed, but it has to be, because even to re-create this problem for the purpose of filing this ticket took me three hours.

This will mainly be of interest to Release Managers and to commit-bit holders who apply patches and pull requests from regular contributors.  So if you don't want to get down into the weeds, you can stop reading this ticket here and simply wait for pull requests which I hope to file soon.

Thank you very much.
Jim Keenan

**BEGIN Gory Details**

As an experiment, I created a branch called `jkeenan/phonypod`.  In that branch I created a new POD file, `pod/perlphonypod.pod`, which, per `podchecker` was correctly formatted in POD format.  I also created an entry for that file in `MANIFEST`.
```
$ git show | cat
commit 2b1ee02941a2ec5a2774fe0134ad9269eb1a2339
Author: James E Keenan <jkeenan@cpan.org>
Date:   Sat Dec 19 19:52:16 2020 +0000

    Add dummy copy file for testing

diff --git a/MANIFEST b/MANIFEST
index 6e9f6c64a2..295ab0e12c 100644
--- a/MANIFEST
+++ b/MANIFEST
@@ -5293,6 +5293,7 @@ pod/perlop.pod			Perl operators and precedence
 pod/perlopentut.pod		Perl open() tutorial
 pod/perlpacktut.pod		Perl pack() and unpack() tutorial
 pod/perlperf.pod		Perl Performance and Optimization Techniques
+pod/perlphonypod.pod		Phony POD
 pod/perlpod.pod			Perl plain old documentation
 pod/perlpodspec.pod		Perl plain old documentation format specification
 pod/perlpodstyle.pod		Perl POD style guide
diff --git a/pod/perlphonypod.pod b/pod/perlphonypod.pod
new file mode 100644
index 0000000000..9fbaa47c76
--- /dev/null
+++ b/pod/perlphonypod.pod
@@ -0,0 +1,12 @@
+=encoding utf8
+
+=head1 NAME
+
+perlphonypod - Phony POD
+
+=head1 DESCRIPTION
+
+This document is nonsense.
+
+=cut
+
```
I ran my regular configuration and called `make test_prep`.  The output from the latter command indicated a looming problem.
```
[snip]
./miniperl -Ilib autodoc.pl
./miniperl -Ilib pod/perlmodlib.PL -q
./perl -Ilib -I. -f pod/buildtoc -q
pod/buildtoc: perlphonypod.pod exists but is unknown by buildtoc
cd t && (rm -f perl; /bin/ln -s ../perl perl)
```
If I set that problem aside for the moment and plunge ahead and run `make test_porting`, I get this output:
```
$ TEST_JOBS=1 make test_porting
[snip]
/usr/home/jkeenan/gitwork/perl/dist/threads-shared/../../miniperl "-I../../lib" -MExtUtils::Command::MM -e 'cp_nonempty' -- shared.bs ../../lib/auto/threads/shared/shared.bs 644
cd t && (rm -f perl; /bin/ln -s ../perl perl)
cd t &&   ./perl -Ilib -I. harness porting/*.t ../lib/diagnostics.t
porting/FindExt.t ......... ok 
[snip]    
porting/perlfunc.t ........ ok     
porting/pod_rules.t ....... Porting/pod_rules.pl: perlphonypod.pod exists but is unknown by buildtoc
porting/pod_rules.t ....... Failed 8/8 subtests 
porting/podcheck.t ........ ok         
[snip]
../lib/diagnostics.t ...... ok     

Test Summary Report
-------------------
porting/pod_rules.t     (Wstat: 0 Tests: 1 Failed: 1)
  Failed test:  1
  Parse errors: Bad plan.  You planned 8 tests but ran 1.
Files=32, Tests=43982, 40 wallclock secs ( 2.23 usr  0.10 sys + 34.96 cusr  2.48 csys = 39.77 CPU)
Result: FAIL
*** Error code 1

Stop.
```
`t/porting/pod_rules.t` failed all its subtests.  Let's run it verbosely.
```
$ cd t;./perl harness -v porting/pod_rules.t; cd -
Porting/pod_rules.pl: perlphonypod.pod exists but is unknown by buildtoc

not ok 1 # got Pod metadata
Failed 8/8 subtests 

Test Summary Report
-------------------
porting/pod_rules.t (Wstat: 0 Tests: 1 Failed: 1)
  Failed test:  1
  Parse errors: Bad plan.  You planned 8 tests but ran 1.
Files=1, Tests=1,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.11 cusr  0.00 csys =  0.12 CPU)
Result: FAIL
```
It dies very quickly.  Looking into that file, we see that it is documented inline saying:
```
# This test executes Porting/pod_rules.pl and reports the result of that
# program.
#
# Why do we test this?
# Among other reasons, to check the well-formed-ness of these files:
#   win32/makefile.mk
#   MANIFEST
#   win32/Makefile
#   win32/pod.mak
#   Makefile.SH
#   vms/descrip_mms.template
```
But there's actually very little code in this file.  It's mostly an invocation of another program in the core distribution, `Porting/pod_rules.pl`, invoked via `t/test.pl`'s `runperl`:
```
my $result = runperl(switches => ['-f', '-Ilib'],
                     progfile => 'Porting/pod_rules.pl',
                     args     => ['--tap'],
                     nolib    => 1,
                     );
```
So what happens when we run `Porting/pod_rules.pl` by itself?
```
$ ./perl -Ilib Porting/pod_rules.pl
Porting/pod_rules.pl: perlphonypod.pod exists but is unknown by buildtoc
```
This dies right away, which is consistent with the early demise of `t/porting/pod_rules.t`.  So now we have to see what lies within `Porting/pod_rules.pl`.  It is documented inline as follows:
```
# Generate the sections of files listed in %Targets from pod/perl.pod
# Mostly these are rules in Makefiles
```
That, as we shall see in a moment, is a clue to the solution.  But let's read on.  What follows discusses command-line switches.
```
# --verbose gives slightly more output
# --build-all tries to build everything
# --build-foo updates foo as follows
# --showfiles shows the files to be changed
# --test exit if perl.pod, MANIFEST are consistent, and regenerated
#   files are up to date, die otherwise.
```
It turns out that none of these switches help us solve the problem (and one of them probably doesn't exist):
```
$ ./perl -Ilib Porting/pod_rules.pl --verbose
I will be building dmake
I will be building gmake
I will be building manifest
I will be building nmake
I will be building podmak
I will be building unix
I will be building vms
Porting/pod_rules.pl: perlphonypod.pod exists but is unknown by buildtoc
Now processing win32/makefile.mk
Was not modified
Now processing win32/GNUmakefile
Was not modified
Now processing MANIFEST
Was not modified
Now processing win32/Makefile
Was not modified
Now processing win32/pod.mak
Was not modified
Now processing Makefile.SH
Was not modified
Now processing vms/descrip_mms.template
Was not modified
$ ./perl -Ilib Porting/pod_rules.pl --build-all
Porting/pod_rules.pl: perlphonypod.pod exists but is 
$ ./perl -Ilib Porting/pod_rules.pl --showfiles
Makefile.SH MANIFEST vms/descrip_mms.template win32/GNUmakefile win32/Makefile win32/makefile.mk win32/pod.mak
$ ./perl -Ilib Porting/pod_rules.pl --test
Unknown option: test
Porting/pod_rules.pl: Usage: Porting/pod_rules.pl [--verbose] [--showfiles] [--build-all | --build-dmake | --build-gmake | --build-manifest | --build-nmake | --build-podmak | --build-unix | --build-vms]
```
This program in turn `require`s in two other files:
```
require './Porting/pod_lib.pl';
require './Porting/manifest_lib.pl';
```
Let's grep for that exception, `unknown by buildtoc`.
```
$ ack 'unknown by buildtoc' .
Porting/pod_lib.pl
644:        push @inconsistent, "$0: $i exists but is unknown by buildtoc\n"
```
Ugh!  We have to study yet another file.  Having to peer into all these `Porting/` files is really getting annoying, isn't it?

`Porting/pod_rules.pl` invokes a subroutine `get_pod_metadata()` which is exported from `Porting/pod_lib.pl`.  `get_pod_metadata()` is *also* invoked by the `pod/buildtoc` program which is one of the final steps within `make test_prep` -- which explains why we say a mention of `pod/buildtoc' above.

Within `Porting/pod_rules.pl`m `get_pod_metadata()` is documented to return a `Hash reference; each element provides either a list or a lookup table for
information about various types of POD files.`  The error message we've been observing is coded some 70 lines into `get_pod_metadata()`:
```
642     my @inconsistent;
643     foreach my $i (sort keys %disk_pods) {
644         push @inconsistent, "$0: $i exists but is unknown by buildtoc\n"
645             unless $our_pods{$i} || $ignoredpods{$i};
```
From this we can infer that a particular file under examination (`$i`) which we have found in a list of files kept in `%disk_pods` must also be found either in `%our_pods` or `%ignoredpods`; otherwise, that file will be pushed onto a list (`@inconsistent`) that will ultimately result in an exception.

Earlier within `get_pod_metadata()` we have this:
```
595     # There are files that we don't want to list in perl.pod.
596     # Maybe the various stub manpages should be listed there.
597     my %ignoredpods = map { ( "$_.pod" => 1 ) } qw( );
```
This suggests that there are other files which we **do** want to find listed in `pod/perl.pod`.  Another clue!

We then see that `%our_pods` is populated from a hash internal to `Porting/pod_lib.pl`, `%state`:
```
599     # Convert these to a list of filenames.
600     ++$our_pods{"$_.pod"} foreach keys %{$state{pods}};
```
So how is the `pods` element of `%state` populated?  It's populated deep within another subroutine in `Porting/pod_lib.pl`, `__prime_state()`, which is invoked early on in `get_pod_metadata()`.
```
403 sub __prime_state {
404     my $source = 'perldelta.pod';
405     my $filename = "pod/$source";
406     my $contents = slurp_or_die($filename);
...
492             } else {
493                 $state{pods}{$podname} = $desc;
494             }
```
What is `$desc` supposed to mean?  Since your eyes are probably glazing over by this point, I'll cut to the chase.  What `__prime_state()` is (mostly) doing is reading `pod/perl.pod` line-by-line and assigning data it extracts from those lines into `%state`.  This leads us to hypothesize that the exception is being generated by lack of an entry for `pod/perlphonypod.pod` in `pod/perl.pod` corresponding to the entry we've already made in `MANIFEST`.

Let's try this hypothesis out.
```
$ git diff --staged
diff --git a/pod/perl.pod b/pod/perl.pod
index eaccc2e51c..11a232e776 100644
--- a/pod/perl.pod
+++ b/pod/perl.pod
@@ -180,6 +180,7 @@ aux h2ph h2xs perlbug pl2pm pod2html pod2man splain xsubpp
     perlcommunity      Perl community information
 
     perldoc            Look up Perl documentation in Pod format
+    perlphonypod               Phony POD
 
     perlhist           Perl history records
     perldelta          Perl changes since previous version
```
We call `make test_porting` again.
```
$ TEST_JOBS=1 make test_porting
[snip]
usr/home/jkeenan/gitwork/perl/dist/threads-shared/../../miniperl "-I../../lib" -MExtUtils::Command::MM -e 'cp_nonempty' -- shared.bs ../../lib/auto/threads/shared/shared.bs 644
./miniperl -Ilib pod/perlmodlib.PL -q
./perl -Ilib -I. -f pod/buildtoc -q
cd t && (rm -f perl; /bin/ln -s ../perl perl)
cd t &&   ./perl -Ilib -I. harness porting/*.t ../lib/diagnostics.t
porting/FindExt.t ......... ok     
[snip]
porting/perlfunc.t ........ ok     
porting/pod_rules.t ....... Failed 1/8 subtests 
porting/podcheck.t ........ ok         
[snip]
../lib/diagnostics.t ...... ok     

Test Summary Report
-------------------
porting/pod_rules.t     (Wstat: 0 Tests: 8 Failed: 1)
  Failed test:  6
Files=32, Tests=43990, 40 wallclock secs ( 2.25 usr  0.07 sys + 35.10 cusr  2.66 csys = 40.08 CPU)
Result: FAIL
*** Error code 1

Stop.
```
So now we're only failing one test in `t/porting/pod_rules.t`.  Let's again run it verbosely.
```
$ cd t;./perl harness -v porting/pod_rules.t; cd -

ok 1 # got Pod metadata
ok 2 # win32/makefile.mk is up to date
ok 3 # win32/GNUmakefile is up to date
ok 4 # MANIFEST is up to date
ok 5 # win32/Makefile is up to date
not ok 6 # win32/pod.mak is up to date
ok 7 # Makefile.SH is up to date
ok 8 # vms/descrip_mms.template is up to date
Failed 1/8 subtests 

Test Summary Report
-------------------
porting/pod_rules.t (Wstat: 0 Tests: 8 Failed: 1)
  Failed test:  6
Files=1, Tests=8,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.13 cusr  0.04 csys =  0.20 CPU)
Result: FAIL
```
The one file that is not up-to-date is `win32/pod.mak`.  You may have noticed up above in a 'Usage" statement from `Porting/pod_rules.pl` that there was a command-line switch known as `--build-podmak`.  Perhaps the `mak` in that is another clue.  Let's try this switch out:
```
$ ./perl -Ilib Porting/pod_rules.pl --build-podmak
$ git diff |cat
diff --git a/win32/pod.mak b/win32/pod.mak
index 9261aff3cd..51d72b31da 100644
--- a/win32/pod.mak
+++ b/win32/pod.mak
@@ -137,6 +137,7 @@ POD = perl.pod	\
 	perlopentut.pod	\
 	perlpacktut.pod	\
 	perlperf.pod	\
+	perlphonypod.pod	\
 	perlpod.pod	\
 	perlpodspec.pod	\
 	perlpodstyle.pod	\
@@ -303,6 +304,7 @@ MAN = perl.man	\
 	perlopentut.man	\
 	perlpacktut.man	\
 	perlperf.man	\
+	perlphonypod.man	\
 	perlpod.man	\
 	perlpodspec.man	\
 	perlpodstyle.man	\
@@ -469,6 +471,7 @@ HTML = perl.html	\
 	perlopentut.html	\
 	perlpacktut.html	\
 	perlperf.html	\
+	perlphonypod.html	\
 	perlpod.html	\
 	perlpodspec.html	\
 	perlpodstyle.html	\
@@ -635,6 +638,7 @@ TEX = perl.tex	\
 	perlopentut.tex	\
 	perlpacktut.tex	\
 	perlperf.tex	\
+	perlphonypod.tex	\
 	perlpod.tex	\
 	perlpodspec.tex	\
 	perlpodstyle.tex	\
```
So running with `--build-podmak` added entries appropriate for `perlphony` into 4 locations into `win32/pod.mak`.  Let's re-try `t/porting/pod_rules.t`.
```
$ cd t;./perl harness -v porting/pod_rules.t; cd -

ok 1 # got Pod metadata
ok 2 # win32/makefile.mk is up to date
ok 3 # win32/GNUmakefile is up to date
ok 4 # MANIFEST is up to date
ok 5 # win32/Makefile is up to date
ok 6 # win32/pod.mak is up to date
ok 7 # Makefile.SH is up to date
ok 8 # vms/descrip_mms.template is up to date
ok
All tests successful.
Files=1, Tests=8,  1 wallclock secs ( 0.02 usr  0.00 sys +  0.20 cusr  0.02 csys =  0.23 CPU)
Result: PASS
```
Looks good.  If we were to run `make test_porting` once again here, we would see that all porting tests now pass.

**END Gory Details**

That was **a lot** of work, wasn't it?

I intend to file pull requests that will better document the mechanics of the inclusion of new POD files to the core distribution.

Thanks again.

**Comment by jkeenan** [comment]
I'm seeking feedback from one other person who has recently added a new file under `pod/`.  After I get that I'll close this ticket.

Thank you very much.
Jim Keenan

**Comment by rjbs** [comment]
Hey, I'm the other person!  Reading this was pretty amusing, because I remembered going through many of these same steps just as Jim did.  I skipped one or two because a strange part of my memory retained some old unused knowledge, and in one very important place Jim did much better than I did!  I updated the makefiles by hand, not by using the --build-podmak switch, which I can't recall ever knowing about — and I used to have to edit that win32 makefile often!

Anyway, I do believe this is correct.  This is what I'd propose, before anything is documented:

1. improve the error message when the test fails, so they say:

> Are you trying to add a new piece of documentation to ./pod?  If so, run ./Porting/add-pod-file FILENAME

2. implement `add-pod-file` which would just slip it into perl.pod and rebuild the makefiles

Thanks, Jim, for not doing what I did: sighing deeply at the inconvenience and then moving on!

**Comment by jkeenan** [comment]
> Hey, I'm the other person! Reading this was pretty amusing, because I remembered going through many of these same steps just as Jim did. I skipped one or two because a strange part of my memory retained some old unused knowledge, and in one very important place Jim did much better than I did! I updated the makefiles by hand, not by using the --build-podmak switch, which I can't recall ever knowing about — and I used to have to edit that win32 makefile often!
> 
> Anyway, I do believe this is correct. This is what I'd propose, before anything is documented:
> 
>     1. improve the error message when the test fails, so they say:
> 
> 
> > Are you trying to add a new piece of documentation to ./pod?  If so, run ./Porting/add-pod-file FILENAME
> 
>     1. implement `add-pod-file` which would just slip it into perl.pod and rebuild the makefiles
> 
> 
> Thanks, Jim, for not doing what I did: sighing deeply at the inconvenience and then moving on!

@rjbs, please review https://github.com/Perl/perl5/pull/18484 -- first pass at `Porting/add-pod-file`.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
`Porting/add-pod-file` has been merged into blead, so this ticket is closable.
