### ISSUE TITLE
[doc] perldelta: invalid link for perldocstyle 

### ISSUE THREAD

**Issue by niceperl** [Perl/perl5#18420]
**Where**
perldelta

**Description**
The release of perl 5.33.5 has this text on its perldelta:

`perldocstyle has been added to pod/.`

The link provided is invalid (https://metacpan.org/pod/perldocstyle)

**Comment by Grinnz** [comment]
It is valid, it just does not exist in a release indexed by metacpan yet. You can find it at https://perldoc.perl.org/5.33.5/perldocstyle in this release.

**Comment by niceperl** [comment]
It will be valid. But now, it is not

**Comment by Grinnz** [comment]
It's not a problem that is fixable, and will be resolved once there is a stable release of Perl containing this documentation.

**Comment by jkeenan** [comment]
On 12/20/20 12:30 PM, Miguel Prz wrote:
> *Where*
> perldelta
> 
> *Description*
> The release of perl 5.33.5 has this text on its perldelta:
> 
> |perldocstyle has been added to pod/.|
> 
> The link provided is invalid (https://metacpan.org/pod/perldocstyle)
> 

When I got to metacpan.org and enter a comparable URL, say:

https://metacpan.org/pod/perlvar

... it takes me to a page which clearly labels 'perlvar' as part of 
perl-5.32.0, released on June 20 2020.

 From that I infer that what metacpan.org displays is the latest 
production release.  perl-5.33.5 is a monthly development release, not a 
production release, so I would not expect files newly added to the core 
to appear there.

When, locally, I install perl-5.33.5 (with no attempt to install HTML 
documentation), I can call 'perldoc' on both the new 'perldocstyle' as 
well as older files similarly located:

#####
$ ./perldoc perldocstyle | head -5
NAME
     perldocstyle - A style guide for writing Perl's documentation

DESCRIPTION
     This document is a guide for the authorship and maintenance of the

$ ./perldoc perlvar | head -5
NAME
     perlvar - Perl predefined variables

DESCRIPTION
   The Syntax of Variable Names
#####

I don't think this is a bug.  I would be willing to change my mind if 
you could show me installed HTML documentation for a monthly production 
release where you observe this problem.

Thank you very much.l
Jim Keenan

**Comment by jkeenan** [comment]
> On 12/20/20 12:30 PM, Miguel Prz wrote: *Where* perldelta *Description* The release of perl 5.33.5 has this text on its perldelta: |perldocstyle has been added to pod/.| The link provided is invalid (https://metacpan.org/pod/perldocstyle)

I didn't see that @Grinnz had already taken care of this.

Thank you very much.
Jim Keenan
