### ISSUE TITLE
New warning from autodoc.pl during 'make test_prep'

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#18438]
At the end of `make test_prep` we are now getting the message found in the second line below:
```
./miniperl -Ilib autodoc.pl
embed.fnc entry 'newSVsv_flags' missing 'd' flag at autodoc.pl line 399, <F> line 9745.
./miniperl -Ilib pod/perlmodlib.PL -q
./perl -Ilib -I. -f pod/buildtoc -q
cd t && (rm -f perl; /bin/ln -s ../perl perl)
```

Here are recent (last 5 weeks) commits which have modified `embed.fnc`:

commit 8dff134de1f0dc51682889d5cf8c25ab7c31bf45
commit 5c27e8a20ea252ce05ec050d1c3b2117a35067b0
commit add0fa588474394597ad4b9734b2d1646a7b225e
commit 4eff5eb8fa96cf12671631ada42a7f7a00d51c5b
commit 8528a39b09a32d3edc0074e50a82c3ffafef7016
commit e39fb0f3e5add24b2f9b432f90e130e29d2b1c8f
commit eb0353e2530a3b0f6e4e636509e31138727fdd52
commit dcb0f7c312e02aa1c22eedb5fd02a62922a9083b
commit 90df162eb2d430fdcd7cee9d6269ed70c4224c90
commit 1fc4b13275c3552852886d217b36d72d8c9e8123
commit 1065fe43314e39d95a847f7abda27bb7fc9d9cc2
commit f6ecfb3ada10f4def8a8707283cbd47b7fbc4c73
commit f0a7783c659d8808123597cbe1323c36de213ba0
commit f9e2355490f8b3197256a0c520009f2820d370d7
commit b4e8926749490c5508711d4f539744340c520fc6
commit baf0bea7d35c79152c97fb52ffa5762ff103351d
commit 6c041ec2c6e3f68af32f1ca92db0633ec2bcfd75

@khwilliamson, can you take a look?

Thank you very much.
Jim Keenan

**Comment by khwilliamson** [comment]
Fixed by 3e793456f290720aae56fa4de27535046ea3f467
