### ISSUE TITLE
[feature] Remove 'switch' from future feature bundles

### ISSUE THREAD

**Issue by Grinnz** [Perl/perl5#18497]
The 'switch' feature has been in each feature bundle since `:5.10` when the feature was introduced, but has since been less enthusiastically used and depends on the now experimental smartmatch operator. I think it should be removed from future feature bundles, such as the `:5.34` bundle currently defined in blead, to represent that it is no longer considered a best practice feature.

**Comment by tonycoz** [comment]
I think that's reasonable.

I don't think we're going to be able to remove the current version of the feature itself anytime soon :(

**Comment by leonerd** [comment]
We're getting closer to 5.34 freeze time. Do we want to consider doing this now?

**Comment by tonycoz** [comment]
I suspect this qualifies as a contentious change.

**Comment by rjbs** [comment]
Done.
