### ISSUE TITLE
Fix check glob [rt.cpan.org #76169] (Locale::Maketext)

### ISSUE THREAD

**Issue by toddr** [Perl/perl5#18503]
Migrated from [rt.cpan.org#76169](https://rt.cpan.org/Ticket/Display.html?id=76169)

Requestors: @celogeek

Attachments:
* [fix-glob-search.txt](https://rt.cpan.org/Ticket/Attachment/1056667/552824/fix-glob-search.txt)

From @celogeek on 2012-03-30 15:55:57:
I have fix a glob search in `t/01_about_verbose.t`

The next Text::More version will add stuff in name space, and one of them is a Scalar. So to 
prevent looking for something wrong, I check the if the ref is a glob.

**Comment by toddr** [comment]
The patch is:
```diff
diff --git a/t/01_about_verbose.t b/t/01_about_verbose.t
index 88a74eb..a393201 100644
--- a/t/01_about_verbose.t
+++ b/t/01_about_verbose.t
@@ -40,7 +40,7 @@ while(@stack) {
     }
     elsif (
         defined *{$this . '::ISA'} or defined &{$this . '::import'}
-            or ($this ne '' and grep defined *{$_}{'CODE'}, values %{$this . '::'})
+            or ($this ne '' and grep {defined $_ && ref $_ eq 'GLOB' && defined *{$_}{'CODE'}} values %{$this . '::'})
         # If it has an ISA, an import, or any subs...
     ) {
         # It's a class/module with no version.
```

**Comment by Leont** [comment]
This looks sensible to me

**Comment by jkeenan** [comment]
I have created a branch, `smoke-me/jkeenan/gh-18503-locale-maketext`, in which I have applied the patch originally submitted by @celogeek in 2012 and then rebroken some lines for clarity.

In the context of the Perl 5 core distribution's test suite, when run through the harness, the only thing this test file does is a `Test::More::use_ok` on Locale::Maketext.  The patch has no affect on the success or failure of that unit test.

If, however, you run the program manually, *e.g.:*
```
$ ./perl -Ilib -Idist/Locale-Maketext/lib -T dist/Locale-Maketext/t/01_about_verbose.t
```
... you see that the program pretty-prints the version number, the OS type, the contents of %INC, etc., starting with:
```
1..1
ok 1 - use Locale::Maketext;
#
#
#Perl v5.33.7 under freebsd 
# Modules in memory:
#    base v2.27;
#      base::__inc;
#        base::__inc::scope_guard;
#    Carp v1.52;
#    Config v5.033007;
...
```
My research indicates that output is not altered one way or the other by the patch in question.  The particular branch within the `elsif` condition where the code is changed is never reached during the program's execution.

So the patch does no harm, but it's not clear that, at least in the context of blead, it does any good.

Shall we apply?

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> I have created a branch, `smoke-me/jkeenan/gh-18503-locale-maketext`, in which I have applied the patch originally submitted by @celogeek in 2012 and then rebroken some lines for clarity.
> 
> In the context of the Perl 5 core distribution's test suite, when run through the harness, the only thing this test file does is a `Test::More::use_ok` on Locale::Maketext. The patch has no affect on the success or failure of that unit test.
> 
> If, however, you run the program manually, _e.g.:_
> 
> ```
> $ ./perl -Ilib -Idist/Locale-Maketext/lib -T dist/Locale-Maketext/t/01_about_verbose.t
> ```
> 
> ... you see that the program pretty-prints the version number, the OS type, the contents of %INC, etc., starting with:
> 
> ```
> 1..1
> ok 1 - use Locale::Maketext;
> #
> #
> #Perl v5.33.7 under freebsd 
> # Modules in memory:
> #    base v2.27;
> #      base::__inc;
> #        base::__inc::scope_guard;
> #    Carp v1.52;
> #    Config v5.033007;
> ...
> ```
> 
> My research indicates that output is not altered one way or the other by the patch in question. The particular branch within the `elsif` condition where the code is changed is never reached during the program's execution.
> 
> So the patch does no harm, but it's not clear that, at least in the context of blead, it does any good.
> 
> Shall we apply?
> 

I'll take the absence of responses as a "No" and will close the ticket in 7 days unless we hear otherwise.

**Comment by haarg** [comment]
I think this was likely to cope with subs installed directly in the stash, rather than in a glob. This existed for a time, but was backed out.

A better option would probably be:
```
$this ne '' and grep defined &{$this . '::' . $_}, keys %{$this . '::'}
```
