### ISSUE TITLE
Make type and ref_to_type equivalent where ref_to_type is not a legal value

### ISSUE THREAD

**Issue by Astara** [Perl/perl5#18518]
### Make Explicit Sigil and Ref to Same, Equivalent  
*(where refs to a type are not legal values)*

* Wherever the language currently requires a value of type Array or a value of type Hash will allow a reference to the same type.

* Any place where the language allows more than one type, will allow a reference to one of those allowed types.

**Note:** *This feature request excludes indeterminate behaviors.

**Comment by Grinnz** [comment]
Please provide examples of where you think this would apply. I suspect you may be revisiting the failed [autoderef](https://perldoc.perl.org/perl5240delta#The-autoderef-feature-has-been-removed) feature, which was problematic as references can be objects that can't be reliably disambiguated (the internals could be one structure, there could be an overload for another type of deref, it's unclear what it's meant to "pretend" to be if anything). It also didn't add any value to offset this ambiguity, as one can simply dereference a reference as desired.

**Comment by Astara** [comment]
The references to Arrays and Hashs are never problematic or unable to be disambiguated.  "Internals" isn't a type of value Hash or Array.  If a reference can be dereferenced "as desired", then isn't a place where the language currently requires either an Array or a Hash. 

For example, if you have:

my @vals=(1,2,3);
my %hash=(qw(one 1 two 2 three 3));
my $rvals=\\@vals;     # you can't simply dereference rvals as a hash:
*my @k=keys %$rvals;*
(Error: Not a HASH reference at -e line 4.)
my $hvals=\\%hash;     # nor can you dereference hvals as an array
*my $str=join ",",@$hvals;*
(Not an ARRAY reference at -e line 6.)
---
As examples, perl "knows" that $rvals is an Array reference, as surely as it knows @vals is an Array.
Similarly perl knows that $hvals is a Hash reference as much as it knows %hash is a Hash.

There are no ambiguities, problematic situations where perl already knows what type a reference is when it points to an array or hash.

**Comment by Grinnz** [comment]
The examples provided are entirely ambiguous because assignment of a reference already has meaning. `my $str = $hvals` will simply assign the reference to the scalar, and `my $str = join ',', $hvals` will stringify it. `keys` however is one of the functions to which the autoderef feature applied. The ambiguity is not with references to native structures, but to blessed objects.

**Comment by Astara** [comment]
Neither of your examples were on my list of proposed changes.  Why would you bring up things not proposed?  

And you state: "The ambiguity is not with references to native structures".   Exactly!  :-)  What I am proposing is strictly, not ambiguous.  

Also, in the case of keys, as it supports a hash or an array as an operand, it would support a ref to a hash or a ref to an array as being equivalent to %$hash_ref and @$array_ref, respectively.
I don't see that as being ambiguous as perl already knows they types of the ref as pointing to a hash or array. 

As long as perl already knows the type of the reference, one cannot arbitrarily place a sigil of their choice in front of the reference without perl generating an error.

**Comment by haarg** [comment]
With overloads, you can create a reference that can be dereferenced as an array or as a hash, so it is ambiguous.

**Comment by Astara** [comment]
Grinnz already said that perl's native types are not affected by the ambiguity.  Overloads are associated with a class, not perl's native types.  Please backup your assertion with an example where perl's basic, built-in types return both ARRAY and HASH at the same time.

**Comment by Astara** [comment]
Leon,  closing this with out even a comment as to why, cannot be considered anything but rude and disrespectful.  If you have anything to add to the discussion, you are welcome to contribute, but simply shutting down a thread is flaunting your disregard for perl's standards of conduct.

**Comment by karenetheridge** [comment]
related: https://www.nntp.perl.org/group/perl.perl5.porters/2021/02/msg258964.html
