### ISSUE TITLE
[doc] correction for perl 7 faq page

### ISSUE THREAD

**Issue by wchristian** [Perl/perl5#18527]
Please integrate this correction into the Perl 7 FAQ page: https://github.com/wchristian/perl5_wiki/commit/dc0cda7ca311da4d25ac32ba18631a4129d1c21d

(I'd have preferred to do a normal PR, but this isn't supported for wiki pages.)

Here's the local wiki page: https://github.com/Perl/perl5/wiki/Perl7-FAQ

**Comment by leonerd** [comment]
LGTM.

Anyone else want to comment?

**Comment by atoomic** [comment]
Looks good to me too

**Comment by karenetheridge** [comment]
the repository for the wiki is `git@github.com:Perl/perl5.wiki.git`

edit.. but it looks like https://github.com/Perl/perl5.wiki does not work, alas... so you can only make branches, not PRs...

**Comment by leonerd** [comment]
So, at this point I'm happy to do "the thing" to apply this; I'm just unclear on what "the thing" is. Can someone enlighten me?

**Comment by karenetheridge** [comment]
@leonerd I would make the commit on the command line against git@github.com:Perl/perl5.wiki.git in the master branch.

**Comment by wchristian** [comment]
Thanks y'all.

And yeah, what ether says, either checkout the perl5 wiki repo and edit that, then push. (Maybe using my repo as a remote in the local checkout as well.) Or just pasting the text into the wiki's browser interface.

**Comment by karenetheridge** [comment]
done, in commit 02fc81953e9d.
