### ISSUE TITLE
Bless undef

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#18525]
Please make it possible to **bless** **undef**  so that it is possible to attach methods to **undef** to explain (for instance) why it is not defined. Thanks!

```
my $a = undef;
bless $a, "AAA"; # Can't bless non-reference value
```

**Comment by Grinnz** [comment]
First: this isn't how bless works, it takes a reference and blesses the target of that reference. undef is not a reference, as the error message states.

Second: bless can't achieve that. This requires magic such as https://metacpan.org/pod/autobox.

**Comment by leonerd** [comment]
What's the usecase here? What are you trying to achieve?

**Comment by karenetheridge** [comment]
If I understand what you are looking for, you can achieve your usecase by using an object overload -- when the value is evaluated in scalar context it returns undef, but can be dereferenced to get your annotation message. This could be done in a cpan module, named something like Annotated::Undef perhaps (but I'm bad at naming things).

prepan.org is a great place to put out module ideas and get community feedback.

**Comment by karenetheridge** [comment]
It's been pointed out to me that there is no *scalar* overload per se.. and a blessed object will never appear as `undef` no matter what overloads are on it. I wonder if perhaps you are looking for structured exceptions instead -- which can be generated with something like https://metacpan.org/pod/Throwable, and handled with https://metacpan.org/pod/Syntax::Keyword::Try or the upcoming core feature with the same syntax.

But really, this is an [X-Y problem](https://xyproblem.info/) -- you started off asking for a particular technical solution, without describing the underlying problem, which might better be served by a different technical solution.

**Comment by iabyn** [comment]
On Wed, Feb 03, 2021 at 10:08:14AM -0800, philip r brenan wrote:
> Please make it possible to **bless** **undef**  so that it is possible to attach methods to **undef** to explain (for instance) why it is not defined. Thanks!
> 
> ```
> my $a = undef;
> bless $a, "AAA"; # Can't bless non-reference value
> ```

Whether or not it's really what you want to do, it can be done: this:

    sub Foo::DESTROY { print "DESTROY\n" }

    {
        my $u = undef;
        bless \$u, Foo;
        print "before scope exit\n";
    }
    print "after scope exit\n";

outputs:

    before scope exit
    DESTROY
    after scope exit

-- 
Indomitable in retreat, invincible in advance, insufferable in victory
    -- Churchill on Montgomery
