### ISSUE TITLE
t/op/try.t: Test case where experimental warnings have not been turned off

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#18538]
In `blead`, all tests in `t/op/try.t` currently run under:
```
no warnings 'experimental::try';
```
That's all well and good -- except that we ought to have at least one test where we demonstrate that a warning is generated and where we capture the warning and verify its content against our expectation thereof.

@leonerd and I have been discussing a patch off-list.  A pull request will come shortly.

Thank you very much.
Jim Keenan

**Comment by leonerd** [comment]
Fix is merged; I think we can close this.
