### ISSUE TITLE
undef should be blessed to the containing package

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#18559]
Please note the asymmetry below between calling a sub with an undefined value (allowed) and calling a method from an undefined value (not allowed).  Please make it possible to bless **undef** so that we can call a method from  an undefined value if we wish.  
```
sub a($) {}
my $a = undef;
a $a;   # Allowed
$a->a; # Can't call method "a" on an undefined value
```

**Comment by Leont** [comment]
Can you please explain how this is not a duplicate of #18525?

**Comment by karenetheridge** [comment]
If a value was blessed as something, it wouldn't be undefined anymore.

Perhaps you should be using try/catch when you dereference things which might be undefined?
