### ISSUE TITLE
[doc] No version in IO::Select, IO::Socket

### ISSUE THREAD

**Issue by benkasminbullock** [Perl/perl5#18556]
**Where**

IO::Select, IO::Socket

**Description**

Document the version of the module. It is normal to be able to access the installed version's number from the documentation but IO::Select and IO::Socket don't have that.

**Comment by jkeenan** [comment]
> **Where**
> 
> IO::Select, IO::Socket
> 
> **Description**
> 
> Document the version of the module. It is normal to be able to access the installed version's number from the documentation but IO::Select and IO::Socket don't have that.

This has already been fixed in blead and will appear in the next production release of Perl.
```
commit b9c2c70bf0e33ea806d9112b2e6ddd9dee5dc24d
Author:     Paul "LeoNerd" Evans <leonerd@leonerd.org.uk>
AuthorDate: Mon Jan 4 15:10:27 2021 +0000
Commit:     Tony Cook <tony@develop-help.com>
CommitDate: Mon Jan 4 21:46:42 2021 +0000

    Bump VERSION of every file in dist/IO to 1.45 consistently
```

Closing ticket.

Thank you very much.
Jim Keenan
