### ISSUE TITLE
Modify Configure Usage output to show where the quotes must go

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#18573]
Today, not for the first time, I stumbled on an invocation of `./Configure` in which some of the terms needed to be grouped within quotation marks.  For example, I first tried this **wrong** invocation:
```
$ sh ./Configure -des -Dusedevel -Duseithreads -DDEBUGGING -Dcc=clang \
>   -Accflags="-DPERL_POISON -Werror=declaration-after-statement -fsanitize=address" \
>   -Aldflags=-fsanitize=address -Doptimize=-g -O3
Configure: unknown option -3
Usage: Configure [-dehrsEKOSV] [-f config.sh] [-D symbol] [-D symbol=value]
                 [-U symbol] [-U symbol=] [-A command:symbol...]
  -d : use defaults for all answers.
  -e : go on without questioning past the production of config.sh.
  -f : specify an alternate default configuration file.
  -h : print this help message and exit (with an error status).
  -r : reuse C symbols value if possible (skips costly nm extraction).
  -s : silent mode, only echoes questions and essential information.
  -D : define symbol to have some value:
         -D symbol         symbol gets the value 'define'
         -D symbol=value   symbol gets the value 'value'
       common used examples (see INSTALL for more info):
         -Duse64bitint            use 64bit integers
         -Duse64bitall            use 64bit integers and pointers
         -Dusethreads             use thread support
         -Dinc_version_list=none  do not include older perl trees in @INC
         -DEBUGGING=none          DEBUGGING options
         -Dcc=gcc                 choose your compiler
         -Dprefix=/opt/perl5      choose your destination
  -E : stop at the end of questions, after having produced config.sh.
  -K : do not use unless you know what you are doing.
  -O : ignored for backward compatibility
  -S : perform variable substitutions on all .SH files (can mix with -f)
  -U : undefine symbol:
         -U symbol    symbol gets the value 'undef'
         -U symbol=   symbol gets completely empty
       e.g.:  -Uversiononly
  -A : manipulate symbol after the platform specific hints have been applied:
         -A append:symbol=value   append value to symbol
         -A symbol=value          like append:, but with a separating space
         -A define:symbol=value   define symbol to have value
         -A clear:symbol          define symbol to be ''
         -A define:symbol         define symbol to be 'define'
         -A eval:symbol=value     define symbol to be eval of value
         -A prepend:symbol=value  prepend value to symbol
         -A undef:symbol          define symbol to be 'undef'
         -A undef:symbol=         define symbol to be ''
       e.g.:  -A prepend:libswanted='cl pthread '
              -A ccflags=-DSOME_MACRO
  -V : print version number and exit (with a zero status).
```
I then fumbled around until I got this **acceptable** (though not necessarily optimal) invocation:
```
$ sh ./Configure -des -Dusedevel -Duseithreads -DDEBUGGING -Dcc=clang \
  -Accflags="-DPERL_POISON -Werror=declaration-after-statement -fsanitize=address" \
  -Aldflags="-fsanitize=address -Doptimize=-g -O3"
First let's make sure your kit is complete.  Checking...
Locating common programs...
...
```
Could we include something in the Usage output (above) that demonstrates what terms need to be grouped within quotation marks?

@Tux, @tonycoz, @doughera88 

Thank you very much.
Jim Keenan

**Comment by Tux** [comment]
IMHO this line
```
 e.g.:  -A prepend:libswanted='cl pthread '
```
already documents what your issue demonstrates, so what would you change/add to make it even more clear?

**Comment by jkeenan** [comment]
> IMHO this line
> 
> ```
>  e.g.:  -A prepend:libswanted='cl pthread '
> ```
> 
> already documents what your issue demonstrates, so what would you change/add to make it even more clear?

I admit that one escaped my eyes.  However, the more common case is the one I gave in the original post, where you have a *series* of strings which must be quoted, but it's not obvious (particularly from `perl -V:config_args`) where the closing quotes should go.

Thank you very much.
Jim Keenan

**Comment by doughera88** [comment]
On Sat, Feb 13, 2021 at 12:23:30PM -0800, James E Keenan wrote:
> Today, not for the first time, I stumbled on an invocation of `./Configure` in which some of the terms needed to be grouped within quotation marks.  For example, I first tried this **wrong** invocation:
> ```
> $ sh ./Configure -des -Dusedevel -Duseithreads -DDEBUGGING -Dcc=clang \
> >   -Accflags="-DPERL_POISON -Werror=declaration-after-statement -fsanitize=address" \
> >   -Aldflags=-fsanitize=address -Doptimize=-g -O3
> Configure: unknown option -3
> Usage: Configure [-dehrsEKOSV] [-f config.sh] [-D symbol] [-D symbol=value]
>                  [-U symbol] [-U symbol=] [-A command:symbol...]

> I then fumbled around until I got this **acceptable** (though not necessarily optimal) invocation:
> $ sh ./Configure -des -Dusedevel -Duseithreads -DDEBUGGING -Dcc=clang \
>   -Accflags="-DPERL_POISON -Werror=declaration-after-statement -fsanitize=address" \
>   -Aldflags="-fsanitize=address -Doptimize=-g -O3"

The general idea is that the value you are trying to set has to be a single shell word --
it has to be enclosed in quotes if it contains any spaces.

So your second example probably isn't doing what you want:

    >   -Aldflags="-fsanitize=address -Doptimize=-g -O3"

The will append "-f sanitize=address -Doptimize=-g -O3" to the ldflags variable.
It won't touch the optimize variable.  Instead, you probably want

        -Aldflags=-fsanitize=address -Doptimize="-g -O3"

Since the settings for optimize includes a space, it must be quoted.

Recreating a Configure command line from perl -V:config_args is not reliable due to these
spacing issues, though it's usually possible to guess what was intended.
If you want to be precise, though, you need to use config_argc (to get the count of
arguments) and then config_arg1, config_arg2, config_arg3, etc.

> Could we include something in the Usage output (above) that demonstrates what terms need to be grouped within quotation marks?

Would something this brief have helped?  I don't want to make the help message
too long, and this makes the line too long, but is it helpful?

diff --git a/Configure b/Configure
index 2d2f22fc08..1b04b3d11c 100755
--- a/Configure
+++ b/Configure
@@ -1833,7 +1833,7 @@ Usage: $me [-dehrsEKOSV] [-f config.sh] [-D symbol] [-D symbol=value]
   -h : print this help message and exit (with an error status).
   -r : reuse C symbols value if possible (skips costly nm extraction).
   -s : silent mode, only echoes questions and essential information.
-  -D : define symbol to have some value:
+  -D : define symbol to have some value.  (Value must be quoted if it has spaces.)
          -D symbol         symbol gets the value 'define'
          -D symbol=value   symbol gets the value 'value'
        common used examples (see INSTALL for more info):

-- 
    Andy Dougherty		doughera@lafayette.edu

**Comment by jkeenan** [comment]
@doughera88 wrote:

> Recreating a Configure command line from perl -V:config_args is not reliable due to these
> spacing issues, though it's usually possible to guess what was intended.
> If you want to be precise, though, you need to use config_argc (to get the count of
> arguments) and then config_arg1, config_arg2, config_arg3, etc.

That's the concept I was missing (and which I now see can be found in `Porting/Glossary`).
...

> Would something this brief have helped?  I don't want to make the help message
> too long, and this makes the line too long, but is it helpful?
> ```
> diff --git a/Configure b/Configure
> index 2d2f22fc08..1b04b3d11c 100755
> --- a/Configure
> +++ b/Configure
> @@ -1833,7 +1833,7 @@ Usage: $me [-dehrsEKOSV] [-f config.sh] [-D symbol] [-D symbol=value]
>    -h : print this help message and exit (with an error status).
>    -r : reuse C symbols value if possible (skips costly nm extraction).
>    -s : silent mode, only echoes questions and essential information.
> -  -D : define symbol to have some value:
> +  -D : define symbol to have some value.  (Value must be quoted if it has spaces.)
>           -D symbol         symbol gets the value 'define'
>           -D symbol=value   symbol gets the value 'value'
>         common used examples (see INSTALL for more info):
> ```

I think we can go even more simply:
```
From 6bdda163ebf77163e13467b5b2ad0eaa2d1d27c1 Mon Sep 17 00:00:00 2001
From: James E Keenan <jkeenan@cpan.org>
Date: Sun, 14 Feb 2021 20:52:46 +0000
Subject: [PATCH] Provide examples for quoting shell words

Per suggestion by Andy Dougherty.

For: https://github.com/Perl/perl5/issues/18573
---
 Configure     | 4 ++--
 configure.com | 4 ++--
 2 files changed, 4 insertions(+), 4 deletions(-)

diff --git a/Configure b/Configure
index 3fd076682a..c82ffe5da5 100755
--- a/Configure
+++ b/Configure
@@ -1834,8 +1834,8 @@ Usage: $me [-dehrsEKOSV] [-f config.sh] [-D symbol] [-D symbol=value]
   -r : reuse C symbols value if possible (skips costly nm extraction).
   -s : silent mode, only echoes questions and essential information.
   -D : define symbol to have some value:
-         -D symbol         symbol gets the value 'define'
-         -D symbol=value   symbol gets the value 'value'
+         -D symbol                symbol gets the value 'define'
+         -D symbol='some value'   symbol gets the 'some value'
        common used examples (see INSTALL for more info):
          -Duse64bitint            use 64bit integers
          -Duse64bitall            use 64bit integers and pointers
diff --git a/configure.com b/configure.com
index 77ce7ae086..d753562af3 100644
--- a/configure.com
+++ b/configure.com
@@ -341,8 +341,8 @@ $   DECK
  "-r" : reuse C symbols value if possible (skips costly nm extraction).*
  "-s" : silent mode, only echoes questions and essential information.
  -"D" : define symbol to have some value:                              *
-         -"Dsymbol"         symbol gets the value 'define'
-         -"Dsymbol=value"   symbol gets the value 'value'
+         -"Dsymbol"             symbol gets the value 'define'
+         -"Dsymbol=some value"  symbol gets the value "some value"
   -E  : stop at the end of questions, after having produced config.sh. *
   -K  : do not use unless you know what you are doing.
   -O  : let -D and -U override definitions from loaded configuration file. *
-- 
2.30.0

```
Also available in the `smoke-me/jkeenan/gh-18573/configure-usage` branch or as https://github.com/Perl/perl5/pull/18580.  Please review.

Thank you very much.
Jim Keenan

**Comment by Tux** [comment]
@jkeenan I like this last change. Before I do so, where would you put that this also counts for `-A` without widening its already wide left column? Or is the example I refered to earlier enoung here?
Why did you look in `Porting/Glossary`? If documented more in-depth, it should be in `INSTALL`. I see an example on [line 1439](https://github.com/Perl/perl5/blob/blead/INSTALL#L1439), but I agree that it is underdocumented there (as in "quotation" does not get named at all in `INSTALL`).
So, I think this change is nice, but as the help text already refers to the `INSTALL` document, **that** should get additional descriptions for using quotation (too).

**Comment by jkeenan** [comment]
> @jkeenan I like this last change. Before I do so, where would you put that this also counts for `-A` without widening its already wide left column? Or is the example I referred to earlier enough here?

I think the example for `-A` can remain as is.  Speaking for $self, I think that seeing one example of an argument with a wordspace would be sufficient.

> Why did you look in `Porting/Glossary`? 

See Andy Dougherty's comment above.  He mentioned `config_args`.  I grepped the repository for that and found the entries in `Porting/Glossary`.

> If documented more in-depth, it should be in `INSTALL`. I see an example on [line 1439](https://github.com/Perl/perl5/blob/blead/INSTALL#L1439), but I agree that it is underdocumented there (as in "quotation" does not get named at all in `INSTALL`).
> So, I think this change is nice, but as the help text already refers to the `INSTALL` document, **that** should get additional descriptions for using quotation (too).

I'm not at all averse to adding information like this to `INSTALL`.  In fact, I looked there before filing this ticket.  But I don't think we should hold up applying https://github.com/Perl/perl5/pull/18580 to wait for changes in that document.

Would you prefer a separate GH issue for changes to `INSTALL` -- or should we just keep this one open after merging 18580?

Thank you very much.
Jim Keenan

**Comment by Tux** [comment]
If it is not too much trouble, a combined patch, which I would agree to almost instantly :)

**Comment by jkeenan** [comment]
> If it is not too much trouble, a combined patch, which I would agree to almost instantly :)

Please review [updated p.r.](https://github.com/Perl/perl5/pull/18580), which adds guidance on quoting to `INSTALL`.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> > If it is not too much trouble, a combined patch, which I would agree to almost instantly :)
> 
> Please review [updated p.r.](https://github.com/Perl/perl5/pull/18580), which adds guidance on quoting to `INSTALL`.
> 
> Thank you very much.
> Jim Keenan

https://github.com/Perl/perl5/pull/18580 has been merged into blead, so this ticket is now closable.
