### ISSUE TITLE
[doc] perlnumber: "minus plus number" looks like number

### ISSUE THREAD

**Issue by rsFalse** [Perl/perl5#18584]
**Where**

https://perldoc.perl.org/perlnumber

**Description**

Quoted "minus plus number" behaves like negative number in numeric context.
Seems undocumented. Usually numbers start with either `+` or `-` or none.

(perl v5.32.0)
```
#!/usr/bin/perl

use warnings;
use strict;

$\ = $/;

my $A = "-+3";
my $B = " -+3";
my $C = "- +3";
my $D = "-+ 3";

print map "[$_]", map $_ + 1,
	$A, $B, $C, $D,
	;
```
OUTPUT:
```
Argument "-+3" isn't numeric in addition (+) at minus_plus_number_1.pl line 13.
Argument " -+3" isn't numeric in addition (+) at minus_plus_number_1.pl line 13.
Argument "- +3" isn't numeric in addition (+) at minus_plus_number_1.pl line 13.
Argument "-+ 3" isn't numeric in addition (+) at minus_plus_number_1.pl line 13.
[-2][-2][-2][1]
```

**Comment by Grinnz** [comment]
Everything behaves like a number in numeric context. As you can see from the warnings, they don't "look" like numbers. If you're suggesting it's a bug that only the last one gets truncated to 0 in numeric context, perhaps.

**Comment by karenetheridge** [comment]
Behaviour changed between 5.29.1 and 5.29.2, but I don't see anything relevant in the perldeltas. (Bisection within this range will likely give an answer though.)

```
: [ether@jaeger ~]$; perlbrew use 29.1@std
: [ether@jaeger ~]$; perl -wle'print "-+3" + 0'
Argument "-+3" isn't numeric in addition (+) at -e line 1.
0
: [ether@jaeger ~]$; perlbrew use 29.2@std
: [ether@jaeger ~]$; perl -wle'print "-+3" + 0'
Argument "-+3" isn't numeric in addition (+) at -e line 1.
-3
```

**Comment by karenetheridge** [comment]
Perhaps this is it (found in perl5300delta):

```
       •   A new function ""my_strtod"" in perlapi or its synonym, Strtod(), is now available with the same signature as the libc strtod().  It provides strotod() equivalent behavior on all
           platforms, using the best available precision, depending on platform capabilities and Configure options, while handling locale-related issues, such as if the radix character should be a
           dot or comma.
```

**Comment by t-a-k** [comment]
This seems to be because perl's string-to-number conversion function (`Perl_my_atof3`) passes a string after the first (optional) sign to `strtod`, so that sign symbols will be parsed twice.

I found an another symptom where a hexadecimal notation is sometimes (unexpectedly) recognized:
```
% perl -wle 'print "+0x123" + 0'
Argument "+0x123" isn't numeric in addition (+) at -e line 1.
0
% perl -wle 'print "+ 0x123" + 0'
Argument "+ 0x123" isn't numeric in addition (+) at -e line 1.
291
```

**Comment by sisyphus** [comment]
Just to point out that it was stated in https://github.com/Perl/perl5/issues/17062 that hexadecimal strings should numify to zero ... so I guess this erroneous handling of <code>"+ 0x123"</code> ought to be fixed.
