### ISSUE TITLE
[doc] File::Find CAVEAT, WARNINGS, and BUGS AND CAVEATS sections

### ISSUE THREAD

**Issue by benkasminbullock** [Perl/perl5#18591]
**Where**

File::Find

**Description**

The documentation has a section CAVEAT with two caveats (plural) and then under that it has another section BUGS AND CAVEATS with one caveat, which is a quite baffling statement as follows:
<blockquote>
Despite the name of the finddepth() function, both find() and finddepth() perform a depth-first search of the directory hierarchy.
</blockquote>
Perhaps this could all be one section.

**Comment by jkeenan** [comment]
> **Where**
> 
> File::Find
> 
> **Description**
> 
> The documentation has a section CAVEAT with two caveats (plural) and then under that it has another section BUGS AND CAVEATS with one caveat, which is a quite baffling statement as follows:
> 
> > Despite the name of the finddepth() function, both find() and finddepth() perform a depth-first search of the directory hierarchy.
> 
> Perhaps this could all be one section.

Would you like to submit a patch or pull request?

Thank you very much.
Jim Keenan

**Comment by benkasminbullock** [comment]
> Would you like to submit a patch or pull request?

I was going to try to submit one but I can't find it. On metacpan this is listed as the issue tracker for File::Find and also the repository for it, but where is it?

I can't see it here:

https://github.com/Perl/perl5/tree/blead/lib/File

**Comment by Grinnz** [comment]
The File-Find dist is under `ext/`.

**Comment by jkeenan** [comment]
Addressed in commit a0911914e1.  Closing ticket.
