### ISSUE TITLE
[doc] promoting 'xor' use

### ISSUE THREAD

**Issue by rsFalse** [Perl/perl5#18597]
**Where (related)**

https://perldoc.perl.org/perlstyle
https://perldoc.perl.org/perlop#Logical-or-and-Exclusive-Or
(less related, discussion about `xor`, https://perlmonks.org/?node_id=11110345 - _'xor' operator is not a sibling to 'or' and 'and'?_)

**Description**

Hello,
I want to suggest to promote rarely used `xor` operator.
It can be used in one-liners or in maintainable code. It saves punctuation, therefore it may increase readability.
Some examples to illustrate its use:
```
#!/usr/bin/perl

use warnings;
use strict;

$\ = $/;

my $count;

while( <DATA> ){
	chomp;
	
	m/^$/ and ( print 'empty line' xor next );
	
	m/[a]/ or ( print 'has "a"' xor $count ++ );
	
	print join '+', reverse split m// xor next if 5 > length;
	
	print "Found $&" xor last if m/something/;
	}

print $count;

__DATA__
asd

something
```
OUTPUT:
```
Useless use of logical xor in void context at ./xor_1.pl line 13.
Useless use of logical xor in void context at ./xor_1.pl line 15.
Useless use of logical xor in void context at ./xor_1.pl line 17.
Useless use of logical xor in void context at ./xor_1.pl line 19.
d+s+a
empty line
has "a"
Found something
1
```
The idea of using `xor` is that is has lower precedence than _comma_ operator. So if one wants only to separate expressions, but do not care about returning value, he might use `xor`.
Perlop:
```
<...>
left        , =>
nonassoc    list operators (rightward)
right       not
left        and
left        or xor
END of table
```
If one uses _comma_ to separate two expressions, but expression on the left side has lower precedence than _comma_ (that is for list operators), then he must envelope the left expression with parentheses.
Some lines of examples rewritten with comma operators (or with `do{}` "block"):
```
	m/^$/ and do { print 'empty line'; next };
	
	m/[a]/ or ( print 'has "a"' ), $count ++;
	
	( print join '+', reverse split m// ), next if 5 > length;
	
	( print "Found $&" ), last if m/something/;
```
Readability is similar. But `xor` suggests that TIMTOWT do it.
However 'xor' used in void context triggers a warning.

Other "logical" operators (`or`, `and`) do not trigger warnings because they do short-circuit, therefore they are used for flow control. Even they are used in void context.

I suggest to remove warning from void `xor` because it may be used as provided in examples.

**Comment by mauke** [comment]
> It saves punctuation, therefore it may increase readability.

I strongly disagree. The reason punctuation operators like `+`, `-`, or `=` were invented was to increase readability.

>     m/[a]/ or ( print 'has "a"' xor $count ++ );

If you have multiple logical statements in a conditional branch, the more readable alternative is good old `if`:
```perl
if (!m/[a]/) {
    print 'has "a"';
    $count++;
}
```
(This also makes it clearer that the code has a bug: It prints "has a" when there is no `a` in the current line.)

Similarly:

>     print join '+', reverse split m// xor next if 5 > length;

can be written more readably as:
```perl
if (length($_) < 5) {
    print join '+', reverse split m//;
    next;
}
```

We already have three good ways to do multiple things together: Separate statements in a block (as in "if (COND) BLOCK"), block expressions (as in "do BLOCK"), and the comma operator. I don't see the need to promote a fourth way that essentially abuses `xor` for its precedence and evaluation order.
