### ISSUE TITLE
[doc] Is SvPV properly documented?

### ISSUE THREAD

**Issue by FGasper** [Perl/perl5#18600]
**Where**
perlguts, perlxs, et al.

**Description**
This past week I’ve noticed several XS modules that give a different result when a string is utf8::upgrade()d than when it’s utf8::downgrade()d:
- URI::XSEscape
- Net::Curl
- DNS::Unbound (mea culpa)
- YAML::Syck
- DNS::LDNS

CDB_File had the same issue until [fairly recently](https://github.com/toddr/CDB_File/issues/13). (It’s still there as the default behaviour; new code can just accommodate with a new configuration.)

I believe the problem stems from how SvPV is documented. The documentation gives the impression that SvPV is the “normal” way to convert an SV to a C string. Anything that uses this macro, though, _must_ keep the UTF8 flag along with it, which the documentation doesn’t really clarify. As a result, lots of XS modules just grab the string internals and just pass those along to C, with no regard for whether the string in question is UTF8 or Latin-1.

It seems to me that most C code should actually use SvPVbyte or SvPVutf8 (or variants thereof). Thus, I’d like to update the documentation:
1) … to give SvPVbyte and SvPVutf8 “top billing” in the documentation
2) … to add appropriate warnings around SvPV

I took a first-stab recently:
https://github.com/Perl/perl5/pull/18587

There have been a few comments, which I’m happy to accommodate. Beyond those, what else should I do here to move this forward?

**Comment by FGasper** [comment]
This also implies that the default XS typemap’s `char *` and related built-in typemaps are wrong, since they’ll yield inconsistent results (with no way to know the string’s source encoding). I’m guessing it’d be too disruptive to change that … ?

**Comment by khwilliamson** [comment]
Is this now closable?

**Comment by FGasper** [comment]
I think so.
