### ISSUE TITLE
BBC: Blead Breaks Feature::Compat::Try

### ISSUE THREAD

**Issue by eserte** [Perl/perl5#18605]
Since perl 5.33.7 t/80await+try.t in PEVANS/Feature-Compat-Try-0.02.tar.gz fails:
```
# Future::AsyncAwait 0.48, Feature::Compat::Try 0.02

#   Failed test '$fdone for successful await in try/catch'
#   at t/80await+try.t line 46.
#          got: 'oopsie'
#     expected: 'result'

#   Failed test '$fdone for successful await in try/catch with return'
#   at t/80await+try.t line 77.
#          got: 'fallthrough'
#     expected: 'result'

#   Failed test 'fallthrough after try{return} did not happen'
#   at t/80await+try.t line 78.
# Looks like you failed 3 tests of 4.
t/80await+try.t ...... 
Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/4 subtests 
```

A full sample report at CPAN Testers: http://www.cpantesters.org/cpan/report/61a3e2ca-7536-11eb-a147-372e1f24ea8f

Note that the test suite passes if "Future" is not installed.

**Comment by eserte** [comment]
@leonerd FYI

**Comment by leonerd** [comment]
Yeah, this is actually the suspend/resume logic in `Future::AsyncAwait` being unaware of the new context stack type added in 5.33.7. Reported upstream on F-AA:
https://rt.cpan.org/Ticket/Display.html?id=134414

**Comment by jkeenan** [comment]
> Yeah, this is actually the suspend/resume logic in `Future::AsyncAwait` being unaware of the new context stack type added in 5.33.7. Reported upstream on F-AA:
> https://rt.cpan.org/Ticket/Display.html?id=134414

@leonerd, given that you've reported this upstream (to yourself!), do we need to keep this ticket open in core?

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> > Yeah, this is actually the suspend/resume logic in `Future::AsyncAwait` being unaware of the new context stack type added in 5.33.7. Reported upstream on F-AA:
> > https://rt.cpan.org/Ticket/Display.html?id=134414
> 
> @leonerd, given that you've reported this upstream (to yourself!), do we need to keep this ticket open in core?
> 
> Thank you very much.
> Jim Keenan

No response; closing ticket.
