### ISSUE TITLE
Replacement of PL_hash_seed with PL_hash_seed_w breaks mod_perl2

### ISSUE THREAD

**Issue by steve-m-hay** [Perl/perl5#18617]
Commit f43079cb514e3d0be0036424695438ae3fb58451 resolved #18555 (Alignment fault in perl on 64-bit OpenBSD octeon with clang) with the following change: "Replace PL_hash_seed and PL_hash_state with PL_hash_seed_w and PL_hash_state_w, and replace the old vars with defines that cast their replacements appropriately. This should force linkers to word align the data."

That sounds like the change was intended to maintain backwards compatibility with modules that are using the old names, but it doesn't account for use of them in l-value context. When building mod_perl2 I now get this compilation error:

modperl_perl.c(271): error C2102: '&' requires l-value

That's the memcpy() line in this function:

```
/* before 5.8.1, perl was using HASH_SEED=0, starting from 5.8.1
 * it randomizes if perl was compiled with ccflags -DUSE_HASH_SEED
 * or -DUSE_HASH_SEED_EXPLICIT, in which case we need to tell perl
 * to use the same seed everywhere */
void modperl_hash_seed_set(pTHX)
{
#ifdef MP_NEED_HASH_SEED_FIXUP
    if (MP_init_hash_seed_set) {
#if MP_PERL_VERSION_AT_LEAST(5, 17, 6)
        memcpy(&PL_hash_seed, &MP_init_hash_seed,
                sizeof(PL_hash_seed) > sizeof(MP_init_hash_seed) ?
                    sizeof(MP_init_hash_seed) : sizeof(PL_hash_seed));
        PL_hash_seed_set   = MP_init_hash_seed_set;
#elif MP_PERL_VERSION_AT_LEAST(5, 8, 2)
        PL_rehash_seed     = MP_init_hash_seed;
        PL_rehash_seed_set = MP_init_hash_seed_set;
#else
        PL_hash_seed       = MP_init_hash_seed;
        PL_hash_seed_set   = MP_init_hash_seed_set;
#endif
    }
#endif
}
```

@demerphq is of the opinion that mod_perl2 is wrong to be using PL_hash_seed in this way in the first place: See https://github.com/Perl/perl5/issues/18555#issuecomment-780740348.

I'm raising this ticket to raise awareness of this change and ask if anything needs to be done at the perl end. It sounds like mod_perl2 is at fault and the fix needs to be in it, but I don't understand what that code is trying to do so I don't know how to fix it. I just want to be sure whether this change to perl is going to remain as-is before I spend any time trying to fix mod_perl2.

I don't know if any other modules are using PL_hash_seed in a similar way. I only found mod_perl2 and perl on grep::cpan.

**Comment by Leont** [comment]
Actually, we can solve this on our side.  We currently define `PL_hash_seed` as  `((U8 *)PL_hash_seed_w)`, it would be an lvalue if it was instead defined as `(*(U8 **)&PL_hash_seed_w)`

**Comment by Leont** [comment]
I think this problem goes away by simply removing the ampersand in front of `PL_hash_seed`.

This mess is all the result of a special-case in the C standard, where `array` will resolve to a pointer to the same address as `&array`, but differently types. `memcpy` doesn't care about types, so we can just use the ampersend-less version.
```
--- src/modules/perl/modperl_perl.c
+++ src/modules/perl/modperl_perl.c
@@ -268,7 +268,7 @@ void modperl_hash_seed_set(pTHX)
 #ifdef MP_NEED_HASH_SEED_FIXUP
     if (MP_init_hash_seed_set) {
 #if MP_PERL_VERSION_AT_LEAST(5, 17, 6)
-        memcpy(&PL_hash_seed, &MP_init_hash_seed,
+        memcpy(PL_hash_seed, &MP_init_hash_seed,
                 sizeof(PL_hash_seed) > sizeof(MP_init_hash_seed) ?
                     sizeof(MP_init_hash_seed) : sizeof(PL_hash_seed));
         PL_hash_seed_set   = MP_init_hash_seed_set;

```

**Comment by steve-m-hay** [comment]
> I think this problem goes away by simply removing the ampersand in front of `PL_hash_seed`.
> 
> This mess is all the result of a special-case in the C standard, where `array` will resolve to a pointer to the same address as `&array`, but differently types (which doesn't matter to memcpy). `memcpy` doesn't care about tyoes, so we can just use the ampersend-less version.
> 
> ```
> --- src/modules/perl/modperl_perl.c
> +++ src/modules/perl/modperl_perl.c
> @@ -268,7 +268,7 @@ void modperl_hash_seed_set(pTHX)
>  #ifdef MP_NEED_HASH_SEED_FIXUP
>      if (MP_init_hash_seed_set) {
>  #if MP_PERL_VERSION_AT_LEAST(5, 17, 6)
> -        memcpy(&PL_hash_seed, &MP_init_hash_seed,
> +        memcpy(PL_hash_seed, &MP_init_hash_seed,
>                  sizeof(PL_hash_seed) > sizeof(MP_init_hash_seed) ?
>                      sizeof(MP_init_hash_seed) : sizeof(PL_hash_seed));
>          PL_hash_seed_set   = MP_init_hash_seed_set;
> ```

Gosh, I hadn't thought of that! Thanks for the suggestion. I will try this out tomorrow and report back.

**Comment by steve-m-hay** [comment]
Yes, that change does indeed work and make the problem go away :-)
I've committed that to mod_perl as rev. 1889014 and will hopefully get that released in time for the release of perl 5.34.0.
Thanks again, closing this issue now.

**Comment by opsec** [comment]
mod_perl2 no longer builds with perl-5.34.0 -- will there be some update for mod_perl2 ?

**Comment by xenu** [comment]
It seems it's fixed in SVN: http://svn.apache.org/viewvc?view=revision&revision=1889014

**Comment by steve-m-hay** [comment]
On Fri, 21 May 2021, 18:39 xenu, ***@***.***> wrote:

> It seems it's fixed in SVN:
> http://svn.apache.org/viewvc?view=revision&revision=1889014.
>

Indeed. I will get a new release of mod_perl2 out with this fix in it
imminently.
