### ISSUE TITLE
Could you tag the development branches as dev/beta prerelease on github?

### ISSUE THREAD

**Issue by romulasry** [Perl/perl5#18625]
Thanks in advance.

**Comment by jkeenan** [comment]
On 3/6/21 7:55 PM, romulasry wrote:
> Thanks in advance.
> 

Strictly speaking, our monthly dev releases are tarballs (in .tar.gz or 
.tar.xz format) found at https://www.cpan.org/src/5.0/.  They're not 
found on github.com.

However, at a certain point in the release process we tag releases.  For 
example, the tag corresponding to the most recent monthly dev release is 
v5.33.7.

We've always found that to be sufficient.  If that does not meet your 
needs, could you explain a bit more?

Thank you very much.
Jim Keenan

**Comment by romulasry** [comment]
I wanted the pre-releases for here: https://release-monitoring.org/project/13599/ so that if a developer wanted to update the the latest and greater he could or use the latest stable release. Tagging them as prerelease allows that.

**Comment by romulasry** [comment]
There is a prerelease status checkbox on github for example.

**Comment by Grinnz** [comment]
As @jkeenan said, the release tags on github are not intended to be the canonical release - Perl release tarballs including prereleases should be obtained from CPAN.

The tags in the repository are created via git and not the release interface, so I don't know whether they can be marked as pre-releases.

**Comment by romulasry** [comment]
Okay thanks.
