### ISSUE TITLE
[doc] Math::Trig SYNOPSIS: add some familiar examples with output

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#18626]
```
$ man Math::Trig
           use Math::Trig;

           $x = tan(0.9);
           $y = acos(3.7);
           $z = asin(2.4);

           $halfpi = pi/2;

           $rad = deg2rad(120);

```

OK but how some familiar examples with output, as the first thing in the SYNOPSIS:

```
        use Math::Trig;
        print tan( deg2rad(45) );          # 1
        print rad2deg( acos( 1 / 2 ) );    # 60
        ...
```

**Comment by jkeenan** [comment]
Math::Trig is maintained upstream on CPAN as part of the [Math-Complex distribution](https://metacpan.org/pod/Math::Trig).  Its issue tracker is found on RT:  https://rt.cpan.org/Dist/Display.html?Name=Math-Complex.  That's where a request for documentation improvements should be filed first.

**Comment by jidanni** [comment]
https://rt.cpan.org/Ticket/Create.html?Queue=Math-Complex
only has
![20211009T082500](https://user-images.githubusercontent.com/1230959/136637149-deb918eb-4c57-435c-be86-a240e5867987.jpg)
fields. Nor does the Create New Ticket button work.
I suspect the site is being retired.

**Comment by jidanni** [comment]
http://blogs.perl.org/users/martin_mcgrath/2021/01/regarding-the-closure-of-rtcpan.html

**Comment by Grinnz** [comment]
That is outdated, see https://news.perlfoundation.org/post/rt-cpan-org-upgraded

The problem is just a bad UI in RT. To see the expected options, log in by clicking "log out guest user".

**Comment by jidanni** [comment]
I wasn't guest user. I was me.
OK.
I logged out.
Now I logged back in via ￼￼"Sign in with Auth0" and chose GitHub.
OK back on https://rt.cpan.org/Ticket/Create.html?Queue=Math-Complex the problem is the same. Refreshing the page doesn't help.

**Comment by Grinnz** [comment]
Please explain the problem, "doesn't work" does not help. The page looks correct to me when logged in.

**Comment by jidanni** [comment]
All I see is
![20211009T085801](https://user-images.githubusercontent.com/1230959/136638226-39834834-e2ba-4b7d-a0e4-6d8b43b20e93.jpg)
The remainder of the page is just white, all the way to the bottom.

Regarding the blue "Create new ticket" button, it just gives "RT Error: Permission Denied".

**Comment by jidanni** [comment]
Clicking "Details" in the upper right,
![20211009T090216](https://user-images.githubusercontent.com/1230959/136638349-08f016c2-11af-49f5-b33d-76d18cd28e27.jpg)
just gives another white page.

**Comment by xenu** [comment]
Have you tried disabling adblock and similar extensions?

**Comment by jidanni** [comment]
Yes. OK trying again with virgin Firefox... Same problem.

**Comment by jidanni** [comment]
> Regarding the blue "Create new ticket" button, it just gives "RT Error: Permission Denied".

Maybe my jidanni@jidanni.org account doesn't have permission to create new issues.

**Comment by xenu** [comment]
I guess you should contact the admins. The footer says "Please report any issues with rt.cpan.org to rt-cpan-admin@bestpractical.com".

**Comment by jidanni** [comment]
OK, the admins fixed it, and I was finally able to create https://rt.cpan.org/Ticket/Display.html?id=139794 !

**Comment by pjacklam** [comment]
@jkeenan wrote:

> Math::Trig is maintained upstream on CPAN as part of the [Math-Complex distribution](https://metacpan.org/pod/Math::Trig). Its issue tracker is found on RT: https://rt.cpan.org/Dist/Display.html?Name=Math-Complex. That's where a request for documentation improvements should be filed first.

Alas, the [Math-Complex distribution](https://metacpan.org/pod/Math::Trig) is no longer maintained upstream on CPAN. The latest version was release more than 10 years ago. For several years, I contacted the maintainers asking to take over maintenance, but I never got any response. The stand-alone distribution Math-Complex is dead.
