### ISSUE TITLE
[doc] Missing information about Perl's default sort algorithm

### ISSUE THREAD

**Issue by rsFalse** [Perl/perl5#18627]
**Where**

https://perldoc.perl.org/functions/sort
https://perldoc.perl.org/sort
v5.32

**Description**

I think it would be nice to have one sentence in documentation which says which algorithm is used by `sort` function.

**Comment by dur-randir** [comment]
Btw, it's currently noted in perlsec (which isn't an obvious place for such information, but it's still present).

**Comment by tonycoz** [comment]
Fixed by 4e8fb2ba8ecc1c3307d7d4dbd776fe985723f9a3
