### ISSUE TITLE
Returning state hash-assign risks "Bizarre copy of HASH in subroutine exit"

### ISSUE THREAD

**Issue by fecundf** [Perl/perl5#18630]
**Description**
This code gives the error `Bizarre copy of HASH in subroutine exit`

**Steps to Reproduce**
```
sub tt {state %h=(a=>1)}
print tt; # prints a1
print tt; # error `Bizarre copy of HASH in subroutine exit`
```

**Expected behavior**
both lines to print "a1"

**Perl configuration**

```
Summary of my perl5 (revision 5 version 32 subversion 1) configuration:
   
  Platform:
    osname=darwin
    osvers=20.2.0
    archname=darwin-2level
    uname='darwin yarys-apple-sauce 20.2.0 darwin kernel version 20.2.0: wed dec 2 20:39:59 pst 2020; root:xnu-7195.60.75~1release_x86_64 x86_64 '
    config_args='-de -Dprefix=/Users/hluchan/perl5/perlbrew/perls/perl-5.32.1 -Aeval:scriptdir=/Users/hluchan/perl5/perlbrew/perls/perl-5.32.1/bin'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=11.1 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -I/opt/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=11.1 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -I/opt/local/include'
    ccversion=''
    gccversion='Apple LLVM 12.0.0 (clang-1200.0.32.28)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=11.1 -fstack-protector-strong -L/usr/local/lib -L/opt/local/lib'
    libpth=/usr/local/lib /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/lib /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib /Library/Developer/CommandLineTools/usr/lib /opt/local/lib /usr/lib
    libs=-lgdbm
    perllibs=
    libc=
    so=dylib
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=11.1 -bundle -undefined dynamic_lookup -L/usr/local/lib -L/opt/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under darwin
  Compiled at Jan 25 2021 12:29:31
  %ENV:
    PERLBREW_HOME="/Users/hluchan/.perlbrew"
    PERLBREW_MANPATH="/Users/hluchan/perl5/perlbrew/perls/perl-5.32.1/man"
    PERLBREW_PATH="/Users/hluchan/perl5/perlbrew/bin:/Users/hluchan/perl5/perlbrew/perls/perl-5.32.1/bin"
    PERLBREW_PERL="perl-5.32.1"
    PERLBREW_ROOT="/Users/hluchan/perl5/perlbrew"
    PERLBREW_SHELLRC_VERSION="0.87"
    PERLBREW_VERSION="0.87"
    PERL_CPANM_OPT="--mirror https://hwte.apple.com/repo/CPAN --mirror-only"
  @INC:
    /Users/hluchan/perl5/perlbrew/perls/perl-5.32.1/lib/site_perl/5.32.1/darwin-2level
    /Users/hluchan/perl5/perlbrew/perls/perl-5.32.1/lib/site_perl/5.32.1
    /Users/hluchan/perl5/perlbrew/perls/perl-5.32.1/lib/5.32.1/darwin-2level
    /Users/hluchan/perl5/perlbrew/perls/perl-5.32.1/lib/5.32.1
```

**Comment by jkeenan** [comment]
> **Description**
> This code gives the error `Bizarre copy of HASH in subroutine exit`
> 
> **Steps to Reproduce**
> 
> ```
> sub tt {state %h=(a=>1)}
> print tt; # prints a1
> print tt; # error `Bizarre copy of HASH in subroutine exit`
> ```
> 
> **Expected behavior**
> both lines to print "a1"
> 
> **Perl configuration**
> 

The behavior of these statements has changed over the years.
```
$ perlbrew use perl-5.26.2
$ perl -E 'sub tt {state %h=(a=>1)} print tt(), "\n"; print tt(), "\n";'
Initialization of state variables in list context currently forbidden at -e line 1, near ")}"
Execution of -e aborted due to compilation errors.

$ perlbrew use perl-5.28.0
$ perl -E 'sub tt {state %h=(a=>1)} print tt(), "\n"; print tt(), "\n";'
a1
Bizarre copy of HASH in subroutine exit at -e line 1.
```

**Comment by jkeenan** [comment]
> > **Description**
> > This code gives the error `Bizarre copy of HASH in subroutine exit`
> > **Steps to Reproduce**
> > ```
> > sub tt {state %h=(a=>1)}
> > print tt; # prints a1
> > print tt; # error `Bizarre copy of HASH in subroutine exit`
> > ```
> > 
> > 
> > **Expected behavior**
> > both lines to print "a1"
> > **Perl configuration**
> 
> The behavior of these statements has changed over the years.
> 
> ```
> $ perlbrew use perl-5.26.2
> $ perl -E 'sub tt {state %h=(a=>1)} print tt(), "\n"; print tt(), "\n";'
> Initialization of state variables in list context currently forbidden at -e line 1, near ")}"
> Execution of -e aborted due to compilation errors.
> 
> $ perlbrew use perl-5.28.0
> $ perl -E 'sub tt {state %h=(a=>1)} print tt(), "\n"; print tt(), "\n";'
> a1
> Bizarre copy of HASH in subroutine exit at -e line 1.
> ```

The behavior changed with this commit:
```
commit f99042c89715fdc05bfe40e3f190da7a47d83891
Author:     Zefram <zefram@fysh.org>
AuthorDate: Sat Nov 4 21:43:59 2017 +0000
Commit:     Zefram <zefram@fysh.org>
CommitDate: Sat Nov 4 21:46:47 2017 +0000

    initialisation of simple aggregate state variables
    
    We now recognise the basic cases of aggregate state variables, to
    permit initialisations of the form "state @a =" or "state @a :shared =".
    Initialisation of state variable lists remains forbidden, because the
    op flags don't let us distinguish "state(...)" from "(state(...))" in
    most cases.
```

**Comment by hvds** [comment]
> **Description**
> This code gives the error `Bizarre copy of HASH in subroutine exit`
> 
> **Steps to Reproduce**
> 
> ```
> sub tt {state %h=(a=>1)}
> print tt; # prints a1
> print tt; # error `Bizarre copy of HASH in subroutine exit`
> ```
> 
> **Expected behavior**
> both lines to print "a1"

Clearly it is a bug that you get a "Bizarre copy of HASH"; however it is not clear to me if returning `("a", 1)` would be the correct behaviour on the second call - the nature of `state` is that the assignment happens only on the first invocation, so on the second call I think the last expression evaluated by the function could equally correctly be either `%h` or nothing at all (in which case I'd expect an empty list to be returned).

**Comment by richardleach** [comment]
`sub tt {state $x = "foo"}` prints `foo` both times, so returning `%h` would be more consistent than returning an empty list.

Just had a quick glance and this error looks like it might be a parsing error / op construction error:
```
main::tt:
9  <1> leavesub[1 ref] K/REFC,1 ->(end)
-     <@> lineseq KP ->9
1        <;> nextstate(main 9 -e:1) v:%,us,fea=15 ->2
-        <1> null K/1 ->-
2           <|> once(other->3)[$:9,10] K/1 ->a
-              <0> null s ->2
8              <2> aassign[t2] KS ->9
-                 <1> ex-list lKP ->6
3                    <0> pushmark s ->4
4                    <$> const(PV "a") s/BARE ->5
5                    <$> const(IV 1) s ->6
-                 <1> ex-list lK ->8
6                    <0> pushmark s ->7
7                    <0> padhv[%h:9,10] lRM*/LVINTRO,STATE ->8
a              <0> padsv[%h:9,10] lRM*/STATE ->9
```
OP `a` should perhaps be a `padhv` OP, not a `padsv` OP. Nothing wrong with the internals of `pp_once`, that's for sure.

Note: Same sort of error with `sub tt {state @x = qw(wombat snake)} print tt(), "\n"; print tt(), "\n";`. Again in this case, a `padsv` is being used to push `@x` on to the stack, but perhaps it should be a `padav` OP.

**Comment by richardleach** [comment]
This arises in `S_newONCEOP` in op.c. Specifically, regardless of the nature of the `padop` being passed in (`padsv`, `padav`, `padhv`), a `padsv` is created as the _op_next_ target:

```
    OP *const other = newOP(OP_PADSV,
                            padop->op_flags
                            | ((padop->op_private & ~OPpLVAL_INTRO) << 8));
```
I'll self-assign it and take a look later in the week.

**Comment by richardleach** [comment]
On the face of it, this can be fixed with:
```
diff --git a/op.c b/op.c
index c3e3d89584..7bc2354a87 100644
--- a/op.c
+++ b/op.c
@@ -8598,9 +8598,9 @@ static OP *
 S_newONCEOP(pTHX_ OP *initop, OP *padop)
 {
     const PADOFFSET target = padop->op_targ;
-    OP *const other = newOP(OP_PADSV,
-                            padop->op_flags
-                            | ((padop->op_private & ~OPpLVAL_INTRO) << 8));
+    OP *const other = newOP(padop->op_type,
+                            (padop->op_flags & ~OPf_REF)
+                            | ((padop->op_private & ~(OPpLVAL_INTRO|OPpPAD_STATE)) << 8));
```
_ext/B/t/optree_varinit.t_ would need fixing up, as it expected the MOD flag to be set. 

The flags currently on the already-set-just-return-it OP seem odd to me. For example:
```
padhv[%h:9,10] lRM*/STATE
```
or
```
padhv[%h:9,10] lRM*/STATE
```
* `STATE` without `LVINTRO` seems a null-op and I've toggled it off in the patch above.
* I don't know why the `REF` (R) flag is set and if there's ever any need for it to be? It seems (logically) to need to be off to return a flattened HV or AV.
* I don't know why the `MOD` flag is set - does it only need to be for the first-time op branch?
* I don't know why the `SPECIAL` (*) flag is set - does it only need to be for the first-time op branch?
