### ISSUE TITLE
[feature] Remove warning about uninitialized value for join

### ISSUE THREAD

**Issue by KES777** [Perl/perl5#18631]
**Describe the solution you'd like**
There is no warning for `$i++`
Would be nice if there is also no warning for: `$var = join ';', $var, 'XXX' ` and for `$var = $var .'XXX'`
Probably warning should be still issued for `$var .= 'XXX'`. 

Just like `$i++` for `$var` we want to aggregate value, so we should ignore first uninitialized value.

PS. *as part of perl 7 where we improve warning reporting*

**Comment by richardleach** [comment]
This suggestion doesn't seem to have gathered support. Is it safe to say at this point that it won't happen and therefore this issue should be closed?

**Comment by jkeenan** [comment]
> This suggestion doesn't seem to have gathered support. Is it safe to say at this point that it won't happen and therefore this issue should be closed?

Agreed.  Let's give it 7 days to resolve.

**Comment by KES777** [comment]
Yeah, there is a lot of upvotes :D. Btw what is wrong with this suggested improvement?

**Comment by richardleach** [comment]
I'm not familiar enough with warnings to know why this only accumulated downvotes.

Treating  `$var = $var .'XXX'` and `$var .= 'XXX'` differently seems inappropriate though.

**Comment by jkeenan** [comment]
> I'm not familiar enough with warnings to know why this only accumulated downvotes.
> 

It's not a question of whether you are familiar with warnings or not.  It's a question of whether the work the core developers will have to do to implement the warning -- and then maintain it over the long run -- leads to something of lasting value to the language.

If, after a ticket has been open for 3-1/2 years, no one other than the original poster has spoken up on behalf of a feature request, then we can pretty safely assume that people don't see much value in that request.
