### ISSUE TITLE
can't install perl5.32.1 failed to build miniperl

### ISSUE THREAD

**Issue by BenSu55** [Perl/perl5#18663]
when i run "make"have a error for install
I searched a lot of information, but I didn't solve the problem
![image](https://user-images.githubusercontent.com/79969453/112408724-46873480-8d53-11eb-830f-4e6ded83d376.png)

**Comment by tonycoz** [comment]
Does Exporter.pm exist in dist/Exporter/lib ?

If it does, what happens if you run
```
make minitest
```
?

Please provide the output of:

```
grep '^config_arg' config.sh
```

in your build tree.

**Comment by BenSu55** [comment]
![image](https://user-images.githubusercontent.com/79969453/112421650-670eb900-8d6a-11eb-9275-0a6c4ebc1a82.png)
minitest and grep '^config_arg' config.sh

**Comment by tonycoz** [comment]
Please state whether `dist/Exporter/lib/Exporter.pm` exists. The output from:
```
ls -l dist/Exporter/lib/Exporter.pm
```
is sufficient.

If it doesn't exist you have an incomplete tree and should check the contents of your tree against the archive

You might want to check that the checksum of the archive matches the appropriate file at https://www.cpan.org/src/5.0/

Your build is failing at a very basic level, which leads me to believe it's a problem with your archive, disk space, or some problem with the environment, but it's difficult to tell.

**Comment by jkeenan** [comment]
> Please state whether `dist/Exporter/lib/Exporter.pm` exists. The output from:
> 
> ```
> ls -l dist/Exporter/lib/Exporter.pm
> ```
> 
> is sufficient.
> 
> If it doesn't exist you have an incomplete tree and should check the contents of your tree against the archive
> 
> You might want to check that the checksum of the archive matches the appropriate file at https://www.cpan.org/src/5.0/
> 
> Your build is failing at a very basic level, which leads me to believe it's a problem with your archive, disk space, or some problem with the environment, but it's difficult to tell.

Since this is probably not a perl error, I suggest we close this ticket if we don't hear back from the OP by July 1.

**Comment by jkeenan** [comment]
> [snip]
> 
> Since this is probably not a perl error, I suggest we close this ticket if we don't hear back from the OP by July 1.

Closing as per schedule.

**Comment by wdeshazer** [comment]
Even though this was closed, I didn't see a satisfactory resolution. The diagnostic suggestions were very helpful. For me, the `./Configure` command was successful if I issued it with `sudo`, but it failed with reduced privileges. I am not sure if one of the build tools requires increased privileges or if the `./Configure` is writing resources to a location requiring increased privileges, but I suspect that is the culprit.

## Update:
I ran into the same behavior in running `make test`. It failed with a similar `miniperl` message and it was resolved by running with increased privileges. If this raises any concern, it would be nice to reopen this issue and advise. If not, I am satisfied.

**Comment by iabyn** [comment]
On Sun, May 11, 2025 at 07:57:49PM -0700, Will DeShazer wrote:
> Even though this was closed, I didn't see a satisfactory resolution. The
> diagnostic suggestions were very helpful. For me, the `./Configure`
> command was successful if I issued it with `sudo`, but it failed with
> reduced privileges. I am not sure if one of the build tools requires
> increased privileges or if the `./Configure` is writing resources to a
> location requiring increased privileges, but I suspect that is the
> culprit.

A normal perl build doesn't require elevated privileges to configure,
build and test.  Nor does the install, unless you're installing to
somewhere which requires such privileges.

If you are seeing such a problem,  I suggest you raise a new ticket
against a supported perl release, showing how you are configuring perl and
what errors you are encountering.

-- 
The crew of the Enterprise encounter an alien life form which is
surprisingly neither humanoid nor made from pure energy.
    -- Things That Never Happen in "Star Trek" #22
