### ISSUE TITLE
[doc] So many warnings with perldoc ... | head

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#18677]
In UNIX school we could use head(1) on pipes,
without causing such 4th of July fireworks warnings:
```
$ perldoc -f m | head -n 1
    "m/*PATTERN*/msixpodualngc"
Can't close STDOUT: Broken pipe at (eval 26) line 1.
END failed--call queue aborted.
```

**Comment by Leont** [comment]
This should be reported in [perldoc's repository](https://github.com/mrallen1/Pod-Perldoc) instead.
