### ISSUE TITLE
[doc] Say where to file perldoc issues when reporting a documentation issue

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#18678]
1. Visit https://github.com/Perl/perl5/issues/new/choose
2. Press `Report a Perl 5 Documentation Issue`

At this point one sees
```
Issue: Report a Perl 5 Documentation Issue
Create a report to help us improve Perl 5. If this doesn’t look right, choose a different type.
```
OK, but it also should say:
"Perldoc issues [go here](https://github.com/mrallen1/Pod-Perldoc)."
Thanks.

**Comment by Leont** [comment]
It really falls under

> Report a CPAN Module Issue
> Please report issues with CPAN modules to their preferred bugtracker as indicated on their MetaCPAN page

Though I get that this is slightly confusing.

It is probably a good idea to mention things that are not obviously modules, but perldoc is far from the only one: `corelist`, `cpan` `json_pp`, `libnetcfg`, `piconv`, `pod2html`, `pod2man`, `pod2text`, `prove`, `ptar`, `ptardiff`, `ptargrep`, `shasum`, `zipdetails` are other such examples.

**Comment by jidanni** [comment]
All I know is _somebody_ told me to report [something](./18677) somewhere else.

**Comment by Grinnz** [comment]
There is not much we can do better than that except continue to notify reporters when they need to report the issue upstream.

**Comment by Grinnz** [comment]
> OK, but it also should say:
> "Perldoc issues [go here](https://github.com/mrallen1/Pod-Perldoc)."

Also, note that it goes there because it's an issue with the *perldoc program*, not with perldocs.

**Comment by richardleach** [comment]
I've opened https://github.com/Perl/perl5/pull/22845 for the perldoc case.

I'm not sure how to make things clearer for the other helper utilities. If we could have a maintainer script that maps program -> core/metacpan link and outputs a .pod somewhere, we could reference that in _.github/ISSUE_TEMPLATE/01-perlbug-core.md_ perhaps. Any thoughts?

Otherwise, this issue is probably closable.

**Comment by guest20** [comment]
A hypothetical perldocbug utility could check Module::CoreList and direct folks to the git repo / rt / maintainer mail as needed, but then somebody would need to tell everyone perldocbug exists
