### ISSUE TITLE
newAV_x( number) macros to create AV and array?

### ISSUE THREAD

**Issue by richardleach** [Perl/perl5#18695]
In various parts of core, SV* arrays are created directly - either for performance or to try to ensure very small array sizes - rather than via _av_extend()_. In other words, multiple variations on the following exist:

```
AV* const some_av = newAV();
Newx( AvALLOC(some_av), ix + 1, SV *);
AvARRAY(some_av) = AvALLOC(some_av);
AvMAX(newpad) = ix;
AvFILLp(newpad) = -1;
```
(There are probably places that do not do this, but could do so in order to save some branches/instructions.)

**Suggestion**
For consistency and future maintainability, it would seem nice to wrap that functionality up in some common macros.

Possible names - intended to imply the amalgamation of _newAV_ and the _Newx_ family of macros:
* newAV_x( ix ) - array elements are not zeroed
* newAV_xz ( ix ) - array elements are zeroed
* plus the cast variant if required, but I'm not sure that it will be

**Note**
Users of such macros might actually want to set AvFILLp to something other than -1, but if they do so soon after the macro, a decent compiler should recognize the assignment in the macro as unnecessary.

**Volunteer**
If people like this idea, I'm happy to implement it, once naming and where to put these macros (_av.h_?) has been agreed upon.

**Comment by hvds** [comment]
> In various parts of core, SV* arrays are created directly - either for performance or to try to ensure very small array sizes - rather than via _av_extend()_. In other words, multiple variations on the following exist:
> 
> ```
> AV* const some_av = newAV();
> Newx( AvALLOC(some_av), ix + 1, SV *);
> AvARRAY(some_av) = AvALLOC(some_av);
> AvMAX(newpad) = ix;
> AvFILLp(newpad) = -1;
> ```

I couldn't find any examples of this pattern after grepping for AvALLOC, could you point at a couple?

If a guarantee on the array size is an important feature of the new macro(s) that should probably also be reflected in the name, perhaps by including an adjective such as "fixed".

**Comment by richardleach** [comment]
> I couldn't find any examples of this pattern after grepping for AvALLOC, could you point at a couple?

I thought there were more than this, but all I could quickly turn up were:

- https://github.com/Perl/perl5/blob/blead/pad.c#L242 and https://github.com/Perl/perl5/blob/blead/pad.c#L2596 look to be variations.
- av_make does it: https://github.com/Perl/perl5/blob/blead/av.c#L421
- new_stackinfo sort of does it: https://github.com/Perl/perl5/blob/blead/scope.c#L76

> If a guarantee on the array size is an important feature of the new macro(s) that should probably also be reflected in the name, perhaps by including an adjective such as "fixed".

As in `newAV_x_fixed(5)` for example? (I'd expect the number of elements supplied, 5 in this case, to be incremented and passed to - in this case - `Newx`. The result would be no different - just a bit more efficient - than if you did `av = newAV(); av_extend(av, 5);` )

**Comment by hvds** [comment]
> > I couldn't find any examples of this pattern after grepping for AvALLOC, could you point at a couple?
> 
> I thought there were more than this, but all I could quickly turn up were:
> 
>     * https://github.com/Perl/perl5/blob/blead/pad.c#L242 and https://github.com/Perl/perl5/blob/blead/pad.c#L2596 look to be variations.
> 
>     * av_make does it: https://github.com/Perl/perl5/blob/blead/av.c#L421
> 
>     * new_stackinfo sort of does it: https://github.com/Perl/perl5/blob/blead/scope.c#L76

new_stackinfo does call av_extend, so the original argument does not apply. That leaves me thinking there isn't a huge call for the proposed two new macros.

> > If a guarantee on the array size is an important feature of the new macro(s) that should probably also be reflected in the name, perhaps by including an adjective such as "fixed".
> 
> As in `newAV_x_fixed(5)` for example?

Something along those lines, yes, though of course the name risks getting unwieldy now.

**Comment by richardleach** [comment]
Hmm, less intuitive but more useful might be for the macro to take two parameters:
* the requested number of elements (as originally proposed)
* a value to set for AvFILLp

Not sure on that tho..

**Comment by richardleach** [comment]
> new_stackinfo does call av_extend, so the original argument does not apply. 

True. The proposed macro would be slightly more efficient though - fewer checks on the av that we already know the answers to:
* Does it have tie magic (no)
*  Is key < -1 (no)
* is key > *maxp (yes)
* is there a shifted array (no)
* is there a shifted array to extend (no)
* is *maxp < 3 (ok, we don't know this, but perhaps we don't care about overriding the key value for this use case, so can just use the value the caller asks for?)

Perhaps it's not important enough for additional macros, but it feels like busywork that can be avoided - and there seems to be a fair amount of that about.

>That leaves me thinking there isn't a huge call for the proposed two new macros.

I might submit a bunch of PRs that could use it though. ;)

**Comment by hvds** [comment]
> > That leaves me thinking there isn't a huge call for the proposed two new macros.
> 
> I might submit a bunch of PRs that could use it though. ;)

My instinct is that it would be better to submit the first of those, and include this/these macro(s) as the first commit of that submission (or alternatively to implement without them first, and add the macro(s) as a subsequent commit that clearly simplifies things).

**Comment by richardleach** [comment]
Thanks. I'll go with that.
