### ISSUE TITLE
Cwd hard-codes location of pwd. This causes perl to fail to build on Guix.

### ISSUE THREAD

**Issue by Frosku** [Perl/perl5#18703]
Module: Cwd

**Description**
On Guix & NixOS, `/bin/pwd` does not exist, the location of most of what would usually be in `/bin/` is `/run/current-system/profile/bin` (guix) or `/run/current-system/sw/bin/` (nix). This causes building perl to fail:

```
Can't figure out your cwd! at /home/frosku/perl5/perlbrew/build/perl-5.32.1/perl-5.32.1/cpan/ExtUtils-MakeMaker/lib/ExtUtils/MakeMaker.pm line 237.
```

**Steps to Reproduce**
1. Be on Guix or NixOS
2. Download perl sources
3. `./Configure -des -Dcc=gcc -Dprefix=$HOME/perl5/`
4. `make`

**Expected behavior**
Building perl succeeds.

**Perl configuration**
N/A

**Workaround**
Add `(extra-special-file "/bin/pwd" (file-append coreutils "/bin/pwd"))` to `services` block in `/etc/config.scm` and reconfigure system. This will populate `/bin/pwd`.

**Comment by Grinnz** [comment]
The referenced error is thrown by Cwd, which tries a number of different things but hardcodes paths so it works under taint mode 🙄 https://github.com/Perl/perl5/blob/12a8085aee9a1a5ac613205b43ea06406736ac6b/dist/PathTools/Cwd.pm#L150-L164

Probably needs functionality added for this OS

**Comment by tonycoz** [comment]
This should be falling back to Internals::getcwd() in 5.32.1, assuming getcwd(2) is found.

Is `d_getcwd=define` in the config.sh generated by Configure?

It is defined here on guix, but I ran into other problems before I get to where you are (presumably from your better understanding of the platform.)

**Comment by Frosku** [comment]
> This should be falling back to Internals::getcwd() in 5.32.1, assuming getcwd(2) is found.
> 
> Is `d_getcwd=define` in the config.sh generated by Configure?
> 
> It is defined here on guix, but I ran into other problems before I get to where you are (presumably from your better understanding of the platform.)

I've since moved back to nixos because of unrelated issues, I can confirm here it's:

```ini
d_getcwd='define'
```

But I get the same build issue.

**Comment by Frosku** [comment]
I've pushed a PR to include the locations of `pwd` on guix & nixos, similar to what's already used.

**Comment by tonycoz** [comment]
I've posted a PR that fixes this for me on nixos (perlbug.t fails for me on nixos due to not being able to word-wrap the very long PATH from nix-shell setting up the environment).

If we want to maintain the distinction between getcwd() and cwd() I think the correct solution is for Configure to save a safe path to pwd, or to save a safe PATH (possibly from getconf), but I'm not sure it's worth the effort if we don't need the distinction between cwd() and getcwd().
