### ISSUE TITLE
[doc] Please describe when filename relative or absolute

### ISSUE THREAD

**Issue by KES777** [Perl/perl5#18708]
**Where**
https://perldoc.perl.org/functions/caller

**Description**
Some times `caller` returns filenames with absolute path, sometimes it is relative.

Please describe at documentation when one or another case occur

example of `paths`:

    ext/Debug/Mojolicious/Plugin/Debug.pm
    /home/kes/work/projects/www/repo2/local/lib/perl5/Mojolicious/Plugins.pm

Location for first one is specified at my program as: `use lib 'ext/Debug'`

Actually I thought that `caller` always return absolute path, but it seems not.

**Comment by Leont** [comment]
That all depends on how that file was loaded. If you don't want relative paths in there, you shouldn't put relative paths in `@INC`

**Comment by jkeenan** [comment]
Reviewing the discussion in this Issue today, my impression is that the OP's concerns were deemed inaccurate and that the Issue should therefore be closed.  I will close it in 7 days unless a strong argument is made for keeping it open.

Thank you very much.
Jim Keenan

**Comment by KES777** [comment]
Could it be documented that $filename depends on `@INC`?

Also there is unclear to which directory it is relative, what would happen if script change directory to something else and the `require` some module. For example:

    /t/app/lib/z/x.pm
    /t/app/z/x.pm

If `@INC` will have `z/`, the caller will show `z/x.pm` but which one of this two `x.pm`?

**Comment by jkeenan** [comment]
> Could it be documented that $filename depends on `@INC`?
> 
> Also there is unclear to which directory it is relative, what would happen if script change directory to something else and the `require` some module. For example:
> 
> ```
> /t/app/lib/z/x.pm
> /t/app/z/x.pm
> ```
> 
> If `@INC` will have `z/`, the caller will show `z/x.pm` but which one of this two `x.pm`?

@KES777, since at this point no one else has spoken up on behalf of the issue you raised, I recommend that you formulate a pull request and see if that garners support.

**Comment by jkeenan** [comment]
In November I requested that the OP create a pull request if he wished to pursue this issue further.  Since no p.r. has materialized, I'm closing this ticket now.
