### ISSUE TITLE
BBC: Blead Breaks POE::Component::Client::DNS

### ISSUE THREAD

**Issue by cjg-cguevara** [Perl/perl5#18714]
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.42 running under perl 5.33.9.

-----------------------------------------------------------------
[Please describe your issue here]

BBC: Blead Breaks POE::Component::Client::DNS

Please see http://matrix.cpantesters.org/?dist=POE-Component-Client-DNS

[Please do not change anything below this line]
-----------------------------------------------------------------
---
Flags:
    category=core
    severity=low
---
Site configuration information for perl 5.33.9:

Configured by cpan at Tue Apr 13 02:34:44 EDT 2021.

Summary of my perl5 (revision 5 version 33 subversion 9) configuration:
  Commit id: 29c6c80448b2dc10ab0f1f572bbc554b399f178c
  Platform:
    osname=linux
    osvers=5.10.0-5-amd64
    archname=x86_64-linux-thread-multi
    uname='linux cjg-bullseye 5.10.0-5-amd64 #1 smp debian 5.10.26-1 (2021-03-27) x86_64 gnulinux '
    config_args='-des -Dprefix=~/bin/perl-blead -Dscriptdir=~/bin/perl-blead/bin -Dusedevel -Duse64bitall -Duseithreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='10.2.1 20210110'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib /lib64 /usr/lib64
    libs=-lpthread -lnsl -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.31.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.31'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'

---
@INC for perl 5.33.9:
    /home/cpan/bin/perl-blead/lib/site_perl/5.33.9/x86_64-linux-thread-multi
    /home/cpan/bin/perl-blead/lib/site_perl/5.33.9
    /home/cpan/bin/perl-blead/lib/5.33.9/x86_64-linux-thread-multi
    /home/cpan/bin/perl-blead/lib/5.33.9

---
Environment for perl 5.33.9:
    HOME=/home/cpan
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_ALL=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl-blead/bin:/home/cpan/bin:/home/cpan/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    PERL_BADLANG (unset)
    SHELL=/bin/bash

**Comment by hvds** [comment]
Hmm, I get this failing at least back to 5.32.0. Could it be an environment change causing the failures?

Looking at the test matrix, I see for example a pass for http://www.cpantesters.org/cpan/report/95c2ae68-95fe-11eb-b10d-1eafc55c2be8 and a fail for http://www.cpantesters.org/cpan/report/fa14a2e4-9c21-11eb-a6b2-485211780bda with very similar details, covering just the last 12 commits to blead (in which very little code changed), but there is also a difference in OS and library versions.

I'll try building further back to see if I can get a pass.

**Comment by jkeenan** [comment]
The failing test references `poe.perl.org`.  That host is unreachable right now.
```
[perlmonger: POE-Component-Client-DNS-1.054] $ ping poe.perl.org
ping: cannot resolve poe.perl.org: Unknown host
[perlmonger: POE-Component-Client-DNS-1.054] $ ping www.perl.org
PING dualstack.j.sni.global.fastly.net (151.101.2.132): 56 data bytes
64 bytes from 151.101.2.132: icmp_seq=0 ttl=56 time=23.269 ms
64 bytes from 151.101.2.132: icmp_seq=1 ttl=56 time=23.293 ms
64 bytes from 151.101.2.132: icmp_seq=2 ttl=56 time=23.440 ms
```

**Comment by jkeenan** [comment]
This matter is being discussed by one of the module's maintainers and the webmaster.  It appears a DNS entry was erroneously removed.  This is not a p5p problem and we can't do anything about it.  So I'm closing this ticket.

Thank you very much.
Jim Keenan
