### ISSUE TITLE
chdir doesn't change $ENV{PWD} value: is it a bug or a feature?

### ISSUE THREAD

**Issue by kozachkov** [Perl/perl5#18724]
When we use **chdir** call the value of `$ENV{PWD}` isn't changed. It should be fixed if it is a bug and if it's not a bug the **chdir** and ENV description shoud be fixed in perlvar.pod and perlfunc.pod.

```perl
use strict;
use warnings;

print "Before using 'chdir'\n\n";

my $PWD_from_sc = `echo -n \$PWD`;
print "\$PWD from system command is: '$PWD_from_sc'\n";
print "\$ENV{PWD} from the perl script: $ENV{PWD}\n";

print "\nAfter using 'chdir'\n\n";

chdir "/" or die "Not now: $!";

$PWD_from_sc = `echo -n \$PWD`;
print "\$PWD from system command is: '$PWD_from_sc'\n";
print "\$ENV{PWD} from the perl script: $ENV{PWD}\n";

my $pid = fork;

if (!$pid) {
    print "\nIn the child process\n\n";

    $PWD_from_sc = `echo -n \$PWD`;
    print "\$PWD from system command is: '$PWD_from_sc'\n";
    print "\$ENV{PWD} from the perl script: $ENV{PWD}\n\n";

    exit;
}

wait;
exit;
```

```
./perl chdir_test.pl
Before using 'chdir'

$PWD from system command is: '/perl_source'
$ENV{PWD} from the perl script: /perl_source

After using 'chdir'

$PWD from system command is: '/'
$ENV{PWD} from the perl script: /perl_source

In the child process

$PWD from system command is: '/'
$ENV{PWD} from the perl script: /perl_source

```

Perl version:
```
./perl -v

This is perl 5, version 33, subversion 9 (v5.33.9) built for x86_64-linux
```

**Comment by Grinnz** [comment]
I don't see any documentation in perlvar or perlfunc that suggests `chdir` should interact with `$ENV{PWD}`.

**Comment by Grinnz** [comment]
Note that each invocation of readpipe (qx/backticks) runs a new shell, which seems to update the `PWD` env var in the shell you are using.

**Comment by Grinnz** [comment]
Normally in a Perl script you don't rely on the `PWD` env var, but on https://perldoc.perl.org/Cwd. https://metacpan.org/pod/File::chdir#$CWD also provides a nice interface for both reading and setting the current working directory.

**Comment by kozachkov** [comment]
> I don't see any documentation in perlvar or perlfunc that suggests `chdir` should interact with `$ENV{PWD}`.

chdir as an example of changing "current environment".

From perlvar:

    %ENV    The hash %ENV contains your current environment. Setting a value
            in "ENV" changes the environment for any child processes you
            subsequently "fork()" off.

When we do something that change the current environment the ENV hash values should be changed also but it's not always happen by different reasons (as in this case) it should be noticed in pod documentation I guess.

**Comment by Grinnz** [comment]
When that documentation entry says "environment" it is a technical term for the set of environment variables. Not a blanket term for any aspect of the programming environment.

**Comment by kozachkov** [comment]
That's what I'm talking about. Doesn't my suggestion about adding this edits to pod make sence at all?

**Comment by Grinnz** [comment]
I'm not sure what you're suggesting. Would changing "environment" to "environment variables" in that section make it clearer?

**Comment by kozachkov** [comment]
I suggest to clarify in which way ENV variables are changed if they do when we use calls such as chdir.

**Comment by Leont** [comment]
> When we do something that change the current environment the ENV hash values should be changed also but it's not always happen by different reasons

No, it shouldn't. Just because shells have this behavior doesn't mean any other program should. Nor do I think it's useful for any program outside of shell.

**Comment by jkeenan** [comment]
This ticket has received no further commentary in nearly six months, and two knowledgeable commenters believe the original poster's diagnosis is inaccurate.  So I believe the ticket is closable and will close it in 7 days unless a strong argument is made for keeping it open.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> This ticket has received no further commentary in nearly six months, and two knowledgeable commenters believe the original poster's diagnosis is inaccurate. So I believe the ticket is closable and will close it in 7 days unless a strong argument is made for keeping it open.
> 

No objection heard.  Closing ticket as per schedule.
