### ISSUE TITLE
[Win32] "-fwrapv" disappears from ccflags with gcc version 10.

### ISSUE THREAD

**Issue by sisyphus** [Perl/perl5#18739]
This had me a bit puzzled, but I guess that <code>"$(GCCVER1)" geq "5"</code> is doing string comparison, and is therefore untrue when $(GCCVER1) is in the range 10 .. 50.
(I look forward to seeing -fwrapv pop up gain when gcc-51 is released ;-)

AFAICT, the absence of -fwrapv makes no difference, and I do wonder if it was ever actually needed on Windows (or anywhere else).
Is there a simple test case for determining this ?
I'm running Windows 7. Might that make a difference ?

I've read through https://github.com/Perl/perl5/issues/13690, but found it difficult to follow, and I haven't yet managed to reproduce a case that needs that switch.

My belief is that -fwrapv is the default behaviour anyway.
If that view is correct, then I would think that the need to specify that switch must represent a bug in -fwrapv (unless, of course, it is being used to override an earlier instance of -ftrapv).

I've also built 5.33.9 (current devel, released today) without -fwrapv, using gcc-7.2.0, and all tests passed.
```
C:\comp-aux\perl-5.33.9\win32>..\perl -I..\lib -V:archname
archname='MSWin32-x64-multi-thread';

C:\comp-aux\perl-5.33.9\win32>..\perl -I..\lib -V:gccversion
gccversion='7.2.0';

C:\comp-aux\perl-5.33.9\win32>..\perl -I..\lib -V:ccflags
ccflags=' -DWIN32 -DWIN64  -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -D__USE_MINGW_ANSI_STDIO -fno-strict-aliasing -mms-bitfields';

C:\comp-aux\perl-5.33.9\win32>..\perl -I..\lib -le "print $]"
5.033009
```
AFAICT perl will no longer build with gcc-4 on Windows.
With mingw-w64 port of gcc-4.9.2, I get unresolved symbols during linking when the Win32 (core) module is being built.

I guess there's really nothing wrong with specifying -fwrapv if it's not needed.
Perhaps, since perl is no longer buildable with gcc-4.3 or earlier, all we need do is hard code the -fwrapv switch permanently into the GNUmakefile ?
Or do we really want to include that switch only when it's needed ?

Here's the full 'perl -V' output of the 7.2.0 build:
```
C:\comp-aux\perl-5.33.9\win32>..\perl -I..\lib -V
Summary of my perl5 (revision 5 version 33 subversion 9) configuration:

  Platform:
    osname=MSWin32
    osvers=6.1.7601
    archname=MSWin32-x64-multi-thread
    uname=''
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='gcc'
    ccflags =' -DWIN32 -DWIN64  -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT
-DPERL_IMPLICIT_SYS -DUSE_PERLIO -D__USE_MINGW_ANSI_STDIO -fno-strict-aliasing -
mms-bitfields'
    optimize='-s -O2'
    cppflags='-DWIN32'
    ccversion=''
    gccversion='7.2.0'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='long long'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags ='-s -L"C:\_64\blead-5.33.9\lib\CORE" -L"C:\_64\gcc-mingw-720\mingw6
4\lib" -L"C:\_64\gcc-mingw-720\mingw64\x86_64-w64-mingw32\lib" -L"C:\_64\gcc-min
gw-720\mingw64\lib\gcc\x86_64-w64-mingw32\7.2.0"'
    libpth=C:\_64\gcc-mingw-720\mingw64\lib C:\_64\gcc-mingw-720\mingw64\x86_64-
w64-mingw32\lib C:\_64\gcc-mingw-720\mingw64\lib\gcc\x86_64-w64-mingw32\7.2.0 C:
\_64\gcc-mingw-720\mingw64\x86_64-w64-mingw32\lib C:\_64\msys_720\1.0\local\lib
C:\_64\gcc-mingw-720\mingw64\lib\gcc\x86_64-w64-mingw32\7.2.0
    libs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi3
2 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversio
n -lodbc32 -lodbccp32 -lcomctl32
    perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladv
api32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lve
rsion -lodbc32 -lodbccp32 -lcomctl32
    libc=
    so=dll
    useshrplib=true
    libperl=libperl533.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-mdll -s -L"C:\_64\blead-5.33.9\lib\CORE" -L"C:\_64\gcc-mingw-720
\mingw64\lib" -L"C:\_64\gcc-mingw-720\mingw64\x86_64-w64-mingw32\lib" -L"C:\_64\
gcc-mingw-720\mingw64\lib\gcc\x86_64-w64-mingw32\7.2.0"'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    HAVE_INTERP_INTERN
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_IMPLICIT_SYS
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under MSWin32
  Compiled at Apr 21 2021 10:22:57
  @INC:
    ..\lib
    C:/comp-aux/perl-5.33.9/lib
```
Cheers,
Rob

**Comment by xenu** [comment]
>AFAICT, the absence of -fwrapv makes no difference, and I do wonder if it was ever actually needed on Windows (or anywhere else).
Is there a simple test case for determining this ?

`-fwrapv` basically means "signed integer overflow won't cause undefined behavior". In practice, gcc with this flag **disabled** will still wrap signed integers on overflow, because that's how virtually all CPUs implement signed integer arithmetic. However, what does change is the behavior of the optimizer: it will assume that all signed integers will never overflow. Because of that, the breakage caused by omission of this flag is very subtle and unpredictable, and there's no reasonable way to test for it.

Since perl does rely on signed integer overflow, we do need this flag (BTW, the same goes for `-fno-strict-aliasing`). The fact that our build scripts enable `-fwrapv` only for gcc 4.3+ is a mistake. It should be enabled for all gcc versions that support that flag, that is, 3.4+.

On a side note, personally, I consider strict aliasing and undefined signed integer overflows two of the biggest warts in the C standard. In exchange for doubtful performance gains, they make C a much less safer language.

**Comment by xenu** [comment]
>AFAICT perl will no longer build with gcc-4 on Windows.
With mingw-w64 port of gcc-4.9.2, I get unresolved symbols during linking when the Win32 (core) module is being built.

Are you setting `CCHOME` properly? `$Config{libpth}` is derived from it.

BTW, we probably should implement `CCHOME` autodection. Having to set it manually is annoying.

**Comment by sisyphus** [comment]
Good catch  @xenu .
I need to remember that the default CCHOME setting is *never* right for me. (It's rare for me to build outside my tried and proven build scripts, and when I do build outside of them I'm prone to stuffing up.)

When I do set CCHOME correctly, gcc-4.9.2 builds and tests perl-5.33.9 just fine - irrespective of whether <code>-fwrapv</code> is included in CCFLAGS or not.

But if I understand you correctly, that success without <code>-fwrapv</code> is not really relevant, because we *really* want <code>-fwrapv</code> to be included for safety - and we should therefore be taking steps to ensure that <code>-fwrapv</code> is being included in CCFLAGS with gcc-10 (and later).

The GNUmakefile simply hard codes the inclusion of <code>-fno-strict-aliasing</code> - without any consideration given to gcc version.
Can we cite that as a precedent to do the same with <code>-fwrapv</code>, or do we still have to encumber the inclusion of <code>-fwrapv</code> with those awkward gcc version checks?
To phrase that question slightly differently, the GNUmakefile already does:
```
BUILDOPT	+= -fno-strict-aliasing -mms-bitfields
MINIBUILDOPT	+= -fno-strict-aliasing
```
Why can't we simply ignore the gcc version,  and alter that to:
```
BUILDOPT	+= -fwrapv -fno-strict-aliasing -mms-bitfields
MINIBUILDOPT	+= -fwrapv -fno-strict-aliasing
```
Cheers,
Rob

**Comment by sisyphus** [comment]
For me, the attached (simple) patch to GNUmakefile sets -fwrapv into CCFLAGS  when the compiler is gcc-10.x.x.
I guess (untested) that the other double quotes in the affected line could also be removed.

If the double quotes are not needed, then I wonder why they were put there in the first place.
One possible answer could be "simple oversight". Another possible answer could be that I've overlooked something , and that those double quotes are, in fact, necessary.

[diff.txt](https://github.com/Perl/perl5/files/6362349/diff.txt)

**Comment by sisyphus** [comment]
Should this issue be deemed a blocker ?
For example, if 5.34 is released with the current win32/GNUmakefile, and Strawberry Perl decides to use gcc-10.x.x as their compiler, then all of their 5.34 builds will omit the -fwrapv switch.

**Comment by xenu** [comment]
>Why can't we simply ignore the gcc version, and alter that to:

According to [perlwin32](https://perldoc.perl.org/5.32.1/perlwin32), it seems the minimum supported gcc version is 3.4, so adding it unconditionally is indeed the right way.

**Comment by xenu** [comment]
>Should this issue be deemed a blocker ?

Unfortunately we're in full code freeze. If it were up to me, I'd merge it, because it's a very simple makefile change that's **extremely** unlikely to break anything.

I've emailed PSC to ask them to take a look at this ticket.

**Comment by sisyphus** [comment]
Thanks again, @xenu.
A few hours ago Ricardo Signes posted to p5p that this issue is a "potential blocker".
I'm not sure if that means it's a blocker, or not ... but at least it's a step in the desired direction.

**Comment by neilb** [comment]
@tonycoz @nwc10 @Leont can you take a look at this please and see if you're happy for this to be snuck into 5.34.0?

**Comment by Leont** [comment]
> According to perlwin32, it seems the minimum supported gcc version is 3.4, so adding it unconditionally is indeed the right way.

Yeah, that's sounds like the best approach to me.

**Comment by tonycoz** [comment]
> @tonycoz @nwc10 @Leont can you take a look at this please and see if you're happy for this to be snuck into 5.34.0?

It looks fine to me, either sisyphus' change or just setting it unconditionally.

**Comment by rjbs** [comment]
@nwc10 has said he'll have a look at making this unconditional.
