### ISSUE TITLE
[doc] Typo in perldelta for 5.33.9: "novinces"

### ISSUE THREAD

**Issue by Keith-S-Thompson** [Perl/perl5#18745]
**Where**

pod/perldelta.pod

**Description**

> split() is a very basic function, and the documentation should be
simple for **novinces**.

should be "novices".

**Comment by richardleach** [comment]
Thanks for the report. This has already been fixed by https://github.com/Perl/perl5/commit/fd11779cdb4d6f04f5f869d890845a060b696bba

**Comment by Keith-S-Thompson** [comment]
The day may come when I learn to do a `git pull` before reporting a typo.

\<Aragorn\>But it is not this day!\</Aragorn\>
