### ISSUE TITLE
[doc] Document when $#$_ is just a "cheap -1"

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#18748]
regarding `$#`, i.e., "...the sigil you use in front of an array name to
get the last index, like $#array..." (perlvar).

Be sure to document somewhere, that sometimes $# is just a "cheap -1":
Mainly with `$#$_`.
```
use strict;
#our mission, print b..z without resorting to temp vars, or knowing how many items there are.
my @v=( 'a' .. 'z' );
my $c;
print "$#v\n"; #works fine
print ++$c,":",( 'a' .. 'z' )[ 1 .. 25 ], "\n"; #works fine, but we have to know the length
print ++$c,":",( 'a' .. 'z' )[ 1 .. $#$_ ], "\n"; #works NOT fine, due to cheap -1
print ++$c,":",( 'a' .. 'z' )[ -25 .. $#$_ ], "\n"; #works fine, but we have to know the length
```
So we can print the first few, the last few, but not all but the first few, or all but the last few, without having to know how many items there are, <s>or resort to reverse(),</s> or use more than one statement. Too bad. You might say it is because the ".." range syntax. Anyway I hope this quirk about `$#$_` is documented somewhere.

**Comment by Grinnz** [comment]
I don't understand what you expect `$#$_` to be here. This is `$#{$_}`, or the last index of the array referenced by `$_`. You have not assigned anything to `$_`.

**Comment by jidanni** [comment]
Ah,
```
$ perl -wle 'print $#{$_}; $_=[22..33];  print $#{$_}; undef $_;  print $#{$_};'
-1
11
-1
```
So -1 is a kind of hardwired default. So there is no way to refer to the current anonymous array...

**Comment by Grinnz** [comment]
Correct. And your earlier examples are [list slices](https://perldoc.perl.org/perldata#Slices), there is not even an array.

When `$_` is undef, `$#{$_}` will [autovivify](https://perldoc.perl.org/perlref#Autovivification) it to reference an array, and since that new array is empty, `$#{$_}` returns -1.

In summary: the `$#` sigil is only usable for an array you can access via a name (or named ref).

**Comment by jidanni** [comment]
OK. Well I hope all this is documented somewhere.
And:
though one can get the first few with [0..5] there is no way to get the last few, as there is no [6..$] notation, and ".." ranges can only go up, etc. I hope that this problem is documented. I.e., -1 works fine in  [0, -1], but not in [0..-1]. I am saying the documents should "admit" there is a "problem" or at least "something one just cannot do." Thanks.

**Comment by Grinnz** [comment]
This is a limitation of the [Range Operator](https://perldoc.perl.org/perlop#Range-Operators) which cannot count backwards, I don't know if or where it could be called out better.

You may find the new [List::Util 'tail'](https://perldoc.perl.org/List::Util#tail) function useful.

**Comment by jidanni** [comment]
Actually perl simply needs a new "...." or something, that could deal with `[^ .... $] `, `[^+2 .... $-3]`, etc.

**Comment by tonycoz** [comment]
As mentioned, $#$_ isn't a "cheap -1" (it isn't cheaper and it isn't just -1).

Closing.
