### ISSUE TITLE
[doc] using read() to slurp whole files as shown in perlfaq5

### ISSUE THREAD

**Issue by farblos** [Perl/perl5#18769]
**Where**
https://github.com/Perl/perl5/blob/fa88ae8ef84c6386a43eef48f18326b51eecce55/cpan/perlfaq/lib/perlfaq5.pod#how-can-i-read-in-an-entire-file-all-at-once--

**Description**
perlfaq5 recommends

```
read( $fh, $var, -s $fh );
```

as an option to read a whole file at once.  Maybe I didn't get this right, but:

1. That function reads characters (unless binmode got requested), but the `-s` operators returns size in bytes, doesn't it?  Usually, (size in bytes) >= (size in characters), but it anyway seems fishy to mix up these here.
2. I haven't found any guarantees in fread(3), read(3) (checked on GNU/Linux), or in Perl's implementation of the read function that read() even for binary files *always* will return the number of requested bytes. In other words, it seems possible that the above call slurps in a file only partially without actually failing, that is, without returning an undefined value.

Not sure whether and how these concerns/issues should be mentioned ...

Thanks for maintaining Perl 5!

**Comment by Grinnz** [comment]
Thanks for your input. perlfaq is maintained upstream on CPAN and the repository is here: https://github.com/perl-doc-cats/perlfaq
