### ISSUE TITLE
Syntax @{hash{@elems}} treated as @hash{@elems}

### ISSUE THREAD

**Issue by Grinnz** [Perl/perl5#18800]
**Description**
The syntax `@{hash{@elems}}` gets parsed as `@hash{@elems}` for some reason, and does not throw an error under strict.

**Steps to Reproduce**
```
use strict;
my %hash = (foo => 42, bar => 'baz');
print "$_\n" for @{hash{'foo','bar'}};
```

**Expected behavior**
It would be expected that `hash{@elems}` would be used as the name of the array, which would surely result in either a syntax or strict 'subs' or strict 'refs' error depending how far it gets.

**Perl configuration**
Occurs at least back to Perl 5.8.9

**Comment by Grinnz** [comment]
This also seems to apply to other constructs like `${hash{foo}}`

**Comment by wolfsage** [comment]
This seems like the right behaviour to me. Why do you think it's not?

**Comment by Grinnz** [comment]
Can you explain? The portion inside the braces is `hash{@elems}` which doesn't seem like a valid identifier for an array to me.

**Comment by wolfsage** [comment]
Is it an identifier for an array? It looks like a hash slice which is how it's behaving and how I expect it to behave.

For example, `@what` is the same as `@{what}`.

Doesn't it follow that `@what{qw(hash keys)}` would be the same as `@{what{qw(hash keys)}}` ?

**Comment by Grinnz** [comment]
Why would it? `@what` is only equivalent to `@{what}` when the braces only contain a bareword; otherwise it is a block which evaluates to the name of the variable (and generally throws a strict refs error if it doesn't evaluate to an array reference).

**Comment by xenu** [comment]
To make @Grinnz' point more clear, this is what `hash{@elems}` evaluates to outside of `@{}`:

```
> perl -MO=Deparse,-p -e 'sub hash; hash{@elems}'
hash({@elems});
sub hash ;
-e syntax OK
```

**Comment by wolfsage** [comment]
Yeah I'm not sure I agree with this being wrong. We explicitly check for and allow this behaviour in toke.c, and even warn if it's ambiguous:
```
 Ambiguous use of %c{%s[...]} resolved to %c%s[...]
    Ambiguous use of %c{%s{...}} resolved to %c%s{...}
        (W ambiguous) You wrote something like "${foo[2]}" (where foo
        represents the name of a Perl keyword), which might be looking for
        element number 2 of the array named @foo, in which case please write
        $foo[2], or you might have meant to pass an anonymous arrayref to the
        function named foo, and then do a scalar deref on the value it
        returns. If you meant that, write "${foo([2])}".
```

```
alh@emondsfield:~$ perl -Mstrict -wE 'my %if = qw(cat dog bird mouse); say for @{if{qw(cat bird)}}'
Ambiguous use of @{if{...}} resolved to @if{...} at -e line 1.
dog
mouse
```

**Comment by Grinnz** [comment]
From that wording, it sounds like it may have been intentional, but that doesn't mean it makes any sense.

**Comment by xenu** [comment]
I guess it seems it's one of the many inconsistencies in the language. That special case should be documented somewhere.

**Comment by Leont** [comment]
I think this is one of those cases of "if you disagree with this, blame Larry for deciding this 30 years ago".

**Comment by Grinnz** [comment]
Unless it's documented somewhere I'm not aware of, it seems more of a gray area than that.

**Comment by neilb** [comment]
From perldata.pod:

```
As in some shells, you can enclose the variable name in braces to
disambiguate it from following alphanumerics (and underscores).
You must also do
this when interpolating a variable into a string to separate the
variable name from a following double-colon or an apostrophe, since
these would be otherwise treated as a package separator:
X<interpolation>

    $who = "Larry";
    print PASSWD "${who}::0:0:Superuser:/:/bin/perl\n";
    print "We use ${who}speak when ${who}'s here.\n";

Without the braces, Perl would have looked for a $whospeak, a
C<$who::0>, and a C<$who's> variable.  The last two would be the
$0 and the $s variables in the (presumably) non-existent package
C<who>.
```

**Comment by Grinnz** [comment]
That describes the syntax when the braces only contain a bareword, not something like `foo{bar}`.

**Comment by Leont** [comment]
I think the syntax makes perfect sense for perl4. It doesn't in perl5. I kind of doubt it will be helpful to change it at this stage: it will only break code without freeing up useful syntax.

**Comment by Grinnz** [comment]
Well I agree with that, but let me just mention the impetus for this ticket: someone accidentally wrote `@{hash{$key}}` instead of `@{$hash{$key}}`, and it silently did the wrong thing.

**Comment by Grinnz** [comment]
One possibility would be adding an unconditional warning when this syntax is used, and not only when it's ambiguous.

**Comment by demerphq** [comment]
I dont think this is a bug, its intentional. Consider something like code generation and you have the string `"[1]"`. Now you want to prefix it with `$foo[10]`, or something to that effect. if you spit out `"$foo[10][1]"` you are doing a multidimensional lookup. if you spit out `"${foo[10]}[10]"` you are doing a single lookup. Consider this code:

```
$ perl -le'my @foo=(1,2); print  "${foo[1]}[10]"'
2[10]
$ perl -le'my @foo=(1,2,3); print  "@{foo[1,2]}[10]"'
2 3[10]
```
I don't think this should warn. If anything we should document it better, but that is it. Its the same problem and reason we have $1 and \g{1} for regexes. Also the syntax is pretty much required to interpolate caret array variables

```
perl -le'my $str="123"; $str=~/(.)(.)(.)/ and print "${^CAPTURE}[0]"'
[0]
$ perl -le'my $str="123"; $str=~/(.)(.)(.)/ and print "${^CAPTURE[0]}"'
1
```

**Comment by Grinnz** [comment]
I don't follow your reasoning. It's not consistent with anything that is currently documented, but I would be ok with "document it at all" if we would like to start considering it a feature.

**Comment by demerphq** [comment]
On Sun, 6 Mar 2022 at 08:56, Dan Book ***@***.***> wrote:

> I don't follow your reasoning. It's not consistent with anything that is
> currently documented, but I would be ok with "document it at all" if we
> would like to start considering it a feature.
>
It is not that we will /start/ considering it a feature, it *is* a feature
and has been for a very long time, and is the *only* way you can spell
certain variable names in interpolated text.

Sure we should update the docs to explain it. But it is not a bug. And it
is not a misfeature. It is very deliberate. The relevant docs have already
been quoted to you, just because they dont happen to specify this exact
case to your satisfaction does not make it undocumented.

cheers,
Yves

**Comment by Grinnz** [comment]
The quoted docs are about enclosing a variable name, which is a known case. Enclosing a variable name with subscripts and without a sigil is not documented.

**Comment by Grinnz** [comment]
As noted previously, it makes sense as a perl 4 feature - but strict 'refs' prohibits this usage, except in the mentioned documented case of a variable name.

**Comment by demerphq** [comment]
On Sun, 6 Mar 2022 at 09:18, Dan Book ***@***.***> wrote:
>
> The quoted docs are about enclosing a variable name, which is a known case. Enclosing a variable name with subscripts and without a sigil is not documented.

This behavior is well known to old perl hands, and while its extension
to subscripts might not be spelled out to your satisfaction, all I can
say that tons of older docs do not spell out everything, and assume
that one can extrapolate from what is written. The fact that this
syntax is the ONLY way you can interpolate certain variable names is
to me a very strong indicator that it is a feature that needs to stay.

Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by demerphq** [comment]
On Sun, 6 Mar 2022 at 09:20, Dan Book ***@***.***> wrote:

> As noted previously, it makes sense as a perl 4 feature - but strict
> 'subs' prohibits this usage, except in the mentioned documented case of a
> variable name.
>
Not sure what you mean:

$ perl -le'use strict; my $str="123"; $str=~/(.)(.)(.)/ and print
"${^CAPTURE[0]}"'
1

yves

**Comment by Grinnz** [comment]
Sorry, "this usage" was ambiguous - I was referring to "dereferencing an expression that doesn't evaluate to a reference", outside of this case which the OP notes does not trip strict.

**Comment by demerphq** [comment]
On Sun, 6 Mar 2022 at 09:25, Dan Book ***@***.***> wrote:

> Sorry, "this usage" was ambiguous - I was referring to "dereferencing an
> expression that doesn't evaluate to a reference", outside of this case
> which the OP notes does not trip strict.
>
I dont know what you mean really. I think you are referring to the other
ticket,  https://github.com/Perl/perl5/issues/19497 which references the
code:

my %hash = (foo => 42, bar => 'baz');
print "$_\n" for @{hash{'foo','bar'}};

@{hash{'foo','bar'}}

is just a different way of spelling @hash{'foo','bar'} which is a hash
slice.

perl -le'use strict; my %hash=(foo=>"foo-1",bar=>"bar-1"); print
qq(@{hash{"foo","bar"}})'
foo-1 bar-1

It is not a symbolic dereference which strict would forbid.

A symbolic reference would be something like

perl -le'use strict; my %hash=(foo=>"foo-1",bar=>"bar-1"); my
$name=qq(hash{"foo","bar"}); print "@{$name}"'
Can't use string ("hash{"foo","bar"}") as an ARRAY ref while "strict refs"
in use at -e line 1.

cheers,
Yves

**Comment by demerphq** [comment]
Closing issue. Doc fix pushed.
