### ISSUE TITLE
ext/Pod-Html/t/*.pod files listed unnecessarily on metacpan home page

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#18804]
The first page on metacpan.org that anyone comes to now that perl-5.34.0 has been released is https://metacpan.org/release/XSAWYERX/perl-5.34.0.  There we see the following F<.pod> files listed:
```
ext/Pod-Html/t/cache.pod
ext/Pod-Html/t/crossref.pod
ext/Pod-Html/t/feature.pod
ext/Pod-Html/t/feature2.pod
ext/Pod-Html/t/htmldir1.pod
ext/Pod-Html/t/htmldir2.pod
ext/Pod-Html/t/htmldir3.pod
ext/Pod-Html/t/htmldir4.pod
ext/Pod-Html/t/htmldir5.pod
ext/Pod-Html/t/htmlescp.pod
ext/Pod-Html/t/htmllink.pod
ext/Pod-Html/t/htmlview.pod
ext/Pod-Html/t/poderr.pod
ext/Pod-Html/t/podnoerr.pod
ext/Pod-Html/testdir/perlpodspec-copy.pod
ext/Pod-Html/testdir/perlvar-copy.pod
```
However, all of these files are just dummy copy files for the testing of `ext/Pod-Html/lib/Pod/Html.pm`.  They're not real documentation, so we shouldn't display them on this page.

How can we fix this?

Thank you very much.
Jim Keenan

**Comment by Grinnz** [comment]
I don't think this is something perl core can necessarily fix, I think it needs to be worked around by metacpan.

**Comment by jkeenan** [comment]
> I don't think this is something perl core can necessarily fix, I think it needs to be worked around by metacpan.

Thanks.  Per comm from @oalders, I've opened this ticket upstream:
https://github.com/metacpan/metacpan-api/issues/1018

Closing this one.
