### ISSUE TITLE
grok_atoUV is in perlclib but is not public

### ISSUE THREAD

**Issue by FGasper** [Perl/perl5#18814]
`perlclib` says:
```
  stdlib.h functions
     Instead Of:                 Use:

     atof(s)                     Atof(s)
     atoi(s)                     grok_atoUV(s, &uv, &e)
     atol(s)                     grok_atoUV(s, &uv, &e)
     strtod(s, &p)               Nothing.  Just don't use it.
     strtol(s, &p, n)            grok_atoUV(s, &uv, &e)
     strtoul(s, &p, n)           grok_atoUV(s, &uv, &e)
```
Per @xenu and @tonycoz via IRC, though, this function is private.

It would be nice, IMO, to have this be public—which is why I’ve filed this as a regular bug rather than a doc bug—but if making it be public isn’t viable then `perlclib` needs an update.

Thank you!

**Comment by tonycoz** [comment]
This was done in 40adeb094cde82e3241be372d8c57edb720dbca9.
