### ISSUE TITLE
perl5340delta C<qr/{,n}/> is now accepted

### ISSUE THREAD

**Issue by LanX** [Perl/perl5#18812]
This is a bug report for perl from lanx.perl@gmail.com,
generated with the help of perlbug 1.42 running under perl 5.32.1.

-----------------------------------------------------------------
[Please describe your issue here]

regarding https://perldoc.perl.org/perl5340delta#qr/%7B,n%7D/-is-now-accepted

you say:

=head2 C<qr/{,n}/> is now accepted

An empty lower bound is now accepted for regular expression quantifiers,
like C<{,3}>.

=cut

that's not accurate and confusing, you rather meant to say

=head2 C<qr/x{,n}/> is now accepted again

An empty lower bound is now accepted again for regular expression quantifiers,
like C<x{,3}>.

=cut

This proves that qr/{,n}/ was no problem with the previous version, the curlies are taken literally.
It's the repitition syntax after a character which was broken.

C:\WINDOWS\system32>perl -Mstrict -wE "my $str = 'foobar'; say 1 if $str =~ /{,3}/; say $],':',$^O"
5.032001:MSWin32

C:\WINDOWS\system32>perl -Mstrict -wE "my $str = '{,3}'; say 1 if $str =~ /{,3}/; say $],':',$^O"
1
5.032001:MSWin32

C:\WINDOWS\system32>perl -Mstrict -wE "my $str = 'xxx'; say 1 if $str =~ /x{,3}/; say $],':',$^O"
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/x{ <-- HERE ,3}/ at -e line 1.

C:\WINDOWS\system32>

This proves the "again"

lanx@ubuntu14-large:~$ perl -Mstrict -wE 'my $str = "xxx"; say 1 if $str =~ /x{,3}/; say $],":",$^O'
5.018002:linux
lanx@ubuntu14-large:~$ 

Cheers
 Rolf

[Please do not change anything below this line]
-----------------------------------------------------------------
---
Flags:
    category=docs
    severity=medium
---
Site configuration information for perl 5.32.1:

Configured by strawberry-perl at Sun Jan 24 15:01:28 2021.

Summary of my perl5 (revision 5 version 32 subversion 1) configuration:
   
  Platform:
    osname=MSWin32
    osvers=10.0.19042.746
    archname=MSWin32-x64-multi-thread
    uname='Win32 strawberry-perl 5.32.1.1 #1 Sun Jan 24 15:00:15 2021 x64'
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags =' -DWIN32 -DWIN64 -D__USE_MINGW_ANSI_STDIO -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields'
    optimize='-s -O2'
    cppflags='-DWIN32'
    ccversion=''
    gccversion='8.3.0'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='long long'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags ='-s -L"C:\STRAWB~1\perl\lib\CORE" -L"C:\STRAWB~1\c\lib"'
    libpth=C:\STRAWB~1\c\lib C:\STRAWB~1\c\x86_64-w64-mingw32\lib C:\STRAWB~1\c\lib\gcc\x86_64-w64-mingw32\8.3.0
    libs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    libc=
    so=dll
    useshrplib=true
    libperl=libperl532.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=xs.dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-mdll -s -L"C:\STRAWB~1\perl\lib\CORE" -L"C:\STRAWB~1\c\lib"'

---
@INC for perl 5.32.1:
    C:/Strawberry/perl/site/lib/MSWin32-x64-multi-thread
    C:/Strawberry/perl/site/lib
    C:/Strawberry/perl/vendor/lib
    C:/Strawberry/perl/lib

---
Environment for perl 5.32.1:
    HOME=C:\Users\RolfLangsdorf
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\IBM\Notes\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Webex\Plugins;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Users\RolfLangsdorf\AppData\Local\Microsoft\WindowsApps;C:\Perl_524\bin;C:\Perl_524\site\bin;C:\nonBKU\Git\cmd;
    PERL_BADLANG (unset)
    SHELL (unset)

**Comment by LanX** [comment]
perlbug told me to create an issue in GitHib, if you prefer a more readable format w/o perlbug meta infos , here again

--- 
regarding https://perldoc.perl.org/perl5340delta#qr/%7B,n%7D/-is-now-accepted

you say:
```

=head2 C<qr/{,n}/> is now accepted

An empty lower bound is now accepted for regular expression quantifiers,
like C<{,3}>.

=cut

```
that's not accurate and confusing, you rather meant to say

```
=head2 C<qr/x{,n}/> is now accepted again

An empty lower bound is now accepted again for regular expression quantifiers,
like C<x{,3}>.

=cut

```
This proves that qr/{,n}/ was no problem with the previous version, the curlies are taken literally.
It's the repitition syntax after a character which was broken.

```
C:\WINDOWS\system32>perl -Mstrict -wE "my $str = 'foobar'; say 1 if $str =~ /{,3}/; say $],':',$^O"
5.032001:MSWin32

C:\WINDOWS\system32>perl -Mstrict -wE "my $str = '{,3}'; say 1 if $str =~ /{,3}/; say $],':',$^O"
1
5.032001:MSWin32

C:\WINDOWS\system32>perl -Mstrict -wE "my $str = 'xxx'; say 1 if $str =~ /x{,3}/; say $],':',$^O"
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/x{ <-- HERE ,3}/ at -e line 1.

C:\WINDOWS\system32>
```

This proves the "again", it used to work fine in older perl versions:

```
lanx@ubuntu14-large:$ perl -Mstrict -wE 'my $str = "xxx"; say 1 if $str = /x{,3}/; say $],":",$^O'
5.018002:linux
lanx@ubuntu14-large:~$

```
Cheers
Rolf

**Comment by LanX** [comment]
see also https://perlmonks.org/index.pl?node_id=11132918

**Comment by LanX** [comment]
Sorry, after checking older perlretut docs I realized that the "again" is wrong, it just didn't throw an error in older versions

so 

```
=head2 C<qr/x{,n}/> is now accepted 

An empty lower bound is now accepted for regular expression quantifiers,
like C<m/x{,3}/> meaning C<m/x{0,3}/>

=cut

```

**Comment by khwilliamson** [comment]
Thanks for the report.  Your wording is now incorporated into perl5340delta
