### ISSUE TITLE
Overload =~ and autogenerate

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#18828]
Please make it possible to overload the the regular expression match operator =~ and auto generate it if necessary?

**Comment by Grinnz** [comment]
`=~` is not a match operator, `m//` is. Interpolation or use as a regex is handled by the `qr` overload.

**Comment by Leont** [comment]
> =~ is not a match operator, m// is. Interpolation or use as a regex is handled by the qr overload.

Closing as such
