### ISSUE TITLE
Math::Trig: Mention there are actually no artificial restrictions on $way

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#18824]
Remove artificial restrictions on $way

We read:

```
   great_circle_waypoint
         use Math::Trig 'great_circle_waypoint';

         ($thetai, $phii) =
           great_circle_waypoint($theta0, $phi0, $theta1, $phi1, $way);

       Where the $way is a value from zero ($theta0, $phi0) to one ($theta1,
       $phi1).

```
Alas, these artificial restrictions on $way means there is no way to
calculate e.g.,:
- Where would we end up if we fell asleep at the wheel, and ended up
going twice as far? ($way=2)
- Not only were we asleep, but we didn't notice our vehicle was in
reverse gear too! Where did we end up? ($way=-2).

Also we need general ways to compute waypoints going the long way around
the great circle. Great circles are circles, not semicircles or less. So
the great circle functions should not be artificially restricted.

Wait! I tested it, and apparently indeed $way works just as I wished!
So the only bug is the explanation needs to make this clear!
Feel free to use my examples.

P.S., https://rt.cpan.org/Ticket/Create.html?Queue=Math-Complex is totally broken for me, jidanni@jidanni.org.

**Comment by Grinnz** [comment]
Sorry but this distribution is upstream CPAN. Issues must be reported to its bugtracker and fixed there first.

**Comment by jidanni** [comment]
(Never mind me talking to myself here:)
OK, we shall now try reporting by email.
Analyzing
https://rt.cpan.org/Public/Dist/Display.html?Name=Math-Trig
https://rt.cpan.org/Public/Dist/Display.html?Name=Math-Complex
we find that perhaps the latter is a more lucky place to report...
OK, from https://rt.cpan.org/NoAuth/RT/CPAN/Usage.html we see we are to construct an email address...

**Comment by jidanni** [comment]
And indeed let's see the headers of a previous report I seem to have sent...
https://rt.cpan.org/Public/Ticket/Attachment/WithHeaders/1005146
Alas the precious To: is missing...
OK, let's take a gamble: `bug-<distribution-name>@rt.cpan.org` must mean
bug-Math-Complex@rt.cpan.org...

**Comment by jidanni** [comment]
And lo and behold, https://rt.cpan.org/Ticket/Display.html?id=136646 is born!!
