### ISSUE TITLE
msvc100 CI is broken

### ISSUE THREAD

**Issue by tonycoz** [Perl/perl5#18822]
**Description**

The CI step for msvc100 is failing to test anything useful, since the msvc100/vcexpress2010 installer is no longer available for download.

The CI has been removed for now as workaround, we need to either:

1. remove support for vcexpress2010/msvc100,
2. find a solution to reinstate testing vcexpress2010/msvc100, or
3. continue to support msvc100 without CI

I don't see any Win32 smokes, so we can't fallback to that.

**Steps to Reproduce**

Review CI prior to e5b41663, or revert that commit.

**Expected behavior**

The msvc100 CI step successfully installs vcexpress2010 and tests perl

**Comment by argrath** [comment]
FYI: AppVeyor CI supports msvc 2010 (and 2008).

https://www.appveyor.com/docs/windows-images-software/

**Comment by xenu** [comment]
We removed that GitHub Action job a while ago. Also, in  #19172 we dropped support for Visual C++ 2012 and older.
