### ISSUE TITLE
$_, @_, %_ in signatures causes error in v5.34

### ISSUE THREAD

**Issue by agguser** [Perl/perl5#18829]
In `v5.32`, `$_`, `@_`, `%_` can be used in subroutine signatures without errors. E.g.
```(sh)
$ perl -w -E '
    use feature qw(signatures); no warnings qw(experimental::signatures);
    sub f ($x, @_) { say "$x, @_" }
    f 1, 2, 3
    '
1, 2 3
```
But in `v5.34`, it causes errors ("Can't use global @_ in subroutine signature" for the above code). Why? Is this a bug or not?

**Comment by Grinnz** [comment]
It's not a bug: https://perldoc.perl.org/perldiag#Can't-use-global-%25s-in-%25s

Note that variables used in a signature are declared as lexical variables, thus it is not the same `@_` you are trying to use.

**Comment by Grinnz** [comment]
https://github.com/Perl/perl5/commit/f27832e79a0b43f3b2bded8020491011faa617c7 may be relevant, this commit predates 5.32 though.

**Comment by agguser** [comment]
If not, why was it allowed in v5.32? (Not sure if it was allowed before that.)
In my opinion,
    `sub f ($x, $y, @_) { … }` is better than `sub f { my ($x, $y) = (shift, shift); … }` or `sub f { (my ($x, $y), @_) = @_; … }`
    ` sub f ($_) { s/a/A/r }` is better than `sub f ($s) { $s =~ s/a/A/r }` or `sub f { local $_ = shift; s/a/A/r }`

**Comment by Grinnz** [comment]
I can't reproduce it being allowed in any version that supports subroutine signatures. https://perl.bot/p/y5l3uv

`my @_` has never been allowed, and `my $_` was removed in Perl 5.24: https://perldoc.perl.org/perl5240delta#Lexical-%24_-has-been-removed

**Comment by agguser** [comment]
Yes, `my @_` is not allowed, but `sub f ($x, @_) {}` was allowed for sure!

**Comment by Grinnz** [comment]
`@_` in a subroutine signature is equivalent to declaring a lexical `@_`. See the paste.

**Comment by agguser** [comment]
But my code containing the signature worked fine until today when I upgrade to v5.34. I had to change the signature to make it works again.

**Comment by Grinnz** [comment]
Can you paste the `perl -V` output of the perl which the code works on?

**Comment by agguser** [comment]
I use Arch Linux, and there is no "previous" perl in /var/cache/pacman/pkg/ (don't know why), so I cannot downgrade to v5.32.1 (https://github.com/archlinux/svntogit-packages/commit/4c0998f93beb75db98e71ffdd5bc9371991bad23#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a)

But with your paste, I tried and found that `use utf8` is the cause for no error in v5.32.1 (https://perl.bot/p/senc5z)

**Comment by Grinnz** [comment]
Ah yes, that was a bug. https://github.com/Perl/perl5/pull/18450

**Comment by agguser** [comment]
So this issue is not a bug! But I think that allowing $_, @_, %_ in signature is useful, as shown in my examples above, isn't it?

**Comment by Grinnz** [comment]
No. Simply use another name.

**Comment by agguser** [comment]
OK, so I will close the issue.
