### ISSUE TITLE
Pod-Html: `html_escape()` not adequately tested

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#18838]
In `ext/Pod-Html/lib/Pod/Html.pm`, there is a helper subroutine `html_escape` whose purpose is, not surprisingly, to rewrite strings with proper escaping for HTML;
```
655 sub html_escape {
656     my $rest = $_[0];
657     $rest   =~ s/&/&amp;/g;
658     $rest   =~ s/</&lt;/g;
659     $rest   =~ s/>/&gt;/g;
660     $rest   =~ s/"/&quot;/g;
661     $rest =~ s/([[:^print:]])/sprintf("&#x%x;", ord($1))/aeg;
662     return $rest;
663 }
```
This subroutine's functionality is not individually tested and is exercised exactly once in the code base:
```
$ ack html_escape bin lib t
lib/Pod/Html.pm
396:    $Title = html_escape($Title);
653:# html_escape: make text safe for HTML
655:sub html_escape {
```
In none of the currently existing test files in `t/` do we manually populate `$Title` with characters needing HTML-escaping.  Consequently, we are unable to assess whether `$Title = html_escape($Title);` is DWIMming.

I am preparing a series of pull requests which will provide a lot of code cleanup for both the code and the tests in this subdirectory.  We should address this deficiency either during those p.r.s or after they're merged into blead.

(This emerged out of a discussion with @rjbs.)

**Comment by jkeenan** [comment]
> 
> In none of the currently existing test files in `t/` do we manually populate `$Title` with characters needing HTML-escaping. Consequently, we are unable to assess whether `$Title = html_escape($Title);` is DWIMming.

**Correction:**  We *do* have a test file, `t/htmlescp.t`, whose *HTML body copy* contains strings in need of HTML-escaping.  However, we have no test file whose HTML `<title>` tag has characters in need of escaping.

**Comment by oodler577** [comment]
@jkeenan happy to help here - what's needed to get this out of triage and attached to a PR (happy to create PR or review).

**Comment by jkeenan** [comment]
> @jkeenan happy to help here - what's needed to get this out of triage and attached to a PR (happy to create PR or review).

I suspect that a first draft of this could be accomplished simply by editing `ext/Pod-Html/t/htmlescp.t` and `t/htmlescp.pod`.  Please try that in a branch off blead.

**Comment by oodler577** [comment]
> > @jkeenan happy to help here - what's needed to get this out of triage and attached to a PR (happy to create PR or review).
> 
> I suspect that a first draft of this could be accomplished simply by editing `ext/Pod-Html/t/htmlescp.t` and `t/htmlescp.pod`. Please try that in a branch off blead.

Sounds good to me, thanks!

**Comment by jkeenan** [comment]
I believe https://github.com/Perl/perl5/pull/19093 will satisfy the request in this ticket.  Please review.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> I believe #19093 will satisfy the request in this ticket. Please review.
> 
> Thank you very much.
> Jim Keenan

p.r. 19093 reviewed and merged; closing this ticket.
