### ISSUE TITLE
stat() returns wrong dev and rdev values on newer FreeBSD systems

### ISSUE THREAD

**Issue by eserte** [Perl/perl5#18837]
On newer FreeBSD systems (probably starting with version 12) the `dev` and `rdev` values returned by `stat()` are wrong. Here's a quick check comparing with the output of the `stat(1)` utility:

```
$ perl -e '$file = shift; my @p = stat($file); print join(" ", @p[0,6]), "\n"' /tmp; stat -f "%d %r" /tmp
-2029977855 -1
18446744071679573761 18446744073709551615
```

On older FreeBSD systems (I have versions 9 and 10 available, but possibly this works also with version 11) the two printed lines are equal:
```
79 165976
79 165976
```

I guess that the problem is caused by the usage of `mPUSHi`, but newer FreeBSD's `dev_t` is now a `uint64` (see this code line: https://github.com/Perl/perl5/blob/ea852e0ec11bf69a13d2ea959b112905b2895ab7/pp_sys.c#L2917 ). Using `mPUSHu` instead fixes the problem (I tried this with https://github.com/eserte/perl5/commit/3fee3134f3b0849152c990451eb40b5941b5f09f ; pp_sys.c has to be compiled with `-DDEV_T_IS_UNSIGNED`).

A further note: do we have a mPUSH macro which does the correct thing dependind on the type of its argument? Something using `typeof()` or `_Generic` or so?

The problem was noticed in https://github.com/uperl/FFI-C-Stat/issues/5 . FFI::C::Stat does it right, but the test suite compares its results with perl's `stat()`, and fails on newer FreeBSD (@plicease FYI)..

**Comment by jkeenan** [comment]
@eserte,

We need to rule out the possibility that the change was in FreeBSD rather than in perl.

On FreeBSD-11:
```
[vagrant@perl-reporter-03 ~]$ uname -mrs
FreeBSD 11.1-RELEASE amd64
[vagrant@perl-reporter-03 ~]$ stat -f "dev: %d    rdev: %r" /tmp
dev: 74    rdev: 327208
```
On FreeBSD-12:
```
[perlmonger: perl] $ uname -mrs
FreeBSD 12.2-STABLE amd64
[perlmonger: perl] $ stat -f "dev: %d    rdev: %r" /tmp
dev: 11954338873668291713    rdev: 18446744073709551615
```

**Comment by eserte** [comment]
The change was in FreeBSD, the `struct stat` definition changed. The current sys/stat.h file contains the freebsd 11 version and the new version: https://github.com/freebsd/freebsd-src/blob/373ffc62c158e52cde86a5b934ab4a51307f9f2e/sys/sys/stat.h#L125

**Comment by jkeenan** [comment]
> The change was in FreeBSD, the `struct stat` definition changed. The current sys/stat.h file contains the freebsd 11 version and the new version: https://github.com/freebsd/freebsd-src/blob/373ffc62c158e52cde86a5b934ab4a51307f9f2e/sys/sys/stat.h#L125

Okay.  What action do you recommend?

Thanks.
jimk

**Comment by bingos** [comment]
```
[fever ~]$ uname -a
FreeBSD fever 13.0-RELEASE FreeBSD 13.0-RELEASE #0 releng/13.0-n244733-ea31abc261f: Fri Apr  9 04:24:09 UTC 2021     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
[fever ~]$ /opt/perl-5.34.0/bin/perl -e '$file = shift; my @p = stat($file); print join(" ", @p[0,6]), "\n"' /tmp; stat -f "%d %r" /tmp
90 2406920
90 2406920
```
```
[ffyrc ~]$ uname -a
FreeBSD ffyrc 12.2-RELEASE-p3 FreeBSD 12.2-RELEASE-p3 GENERIC  i386
[ffyrc ~]$ /opt/perl-5.34.0/bin/perl -e '$file = shift; my @p = stat($file); print join(" ", @p[0,6]), "\n"' /tmp; stat -f "%d %r" /tmp
88 4977408
88 4977408
```
```
[canker:]$ uname -a
FreeBSD canker 11.4-RELEASE-p3 FreeBSD 11.4-RELEASE-p3 #0: Tue Sep  1 08:22:33 UTC 2020     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
[canker:]$ /opt/perl-5.34.0/bin/perl -e '$file = shift; my @p = stat($file); print join(" ", @p[0,6]), "\n"' /tmp; stat -f "%d %r" /tmp
84 56103504
84 56103504
```

I can't reproduce this using the test case given.

**Comment by jkeenan** [comment]
Repeating (just to make sure I didn't call the wrong thing):
```
# FreeBSD-11
$ uname -mrs
FreeBSD 11.1-RELEASE amd64
$ perl -v | head -2 | tail -1
This is perl 5, version 26, subversion 2 (v5.26.2) built for amd64-freebsd-thread-multi
$ perl -e '$file = shift; my @p = stat($file); print join(" ", @p[0,6]), "\n"' /tmp; stat -f "%d %r" /tmp
74 327208
74 327208

# FreeBSD-12
$ uname -mrs
FreeBSD 12.2-STABLE amd64
$ perl -v | head -2 | tail -1
This is perl 5, version 32, subversion 0 (v5.32.0) built for amd64-freebsd-thread-multi
$ perl -e '$file = shift; my @p = stat($file); print join(" ", @p[0,6]), "\n"' /tmp; stat -f "%d %r" /tmp
-6492405200041259903 -1
11954338873668291713 18446744073709551615
```

**Comment by xenu** [comment]
I believe the right fix would be to reuse `st_ino` [logic](https://github.com/Perl/perl5/blob/1604cfb0273418ed479719f39def5ee559bffda2/pp_sys.c#L2918) for `st_dev`.

On a side note, I'm not a fan of that code. I don't understand why we are supporting builds with 32-bit IVs on the systems that have 64-bit integers.

**Comment by tonycoz** [comment]
> On a side note, I'm not a fan of that code. I don't understand why we are supporting builds with 32-bit IVs on the systems that have 64-bit integers.

This isn't a 32-bit vs 64-bit issue - he's building on amd64, which would give him 64-bit IVs, it's purely signedness, at least at this point.

I wonder if 32-bit FreeBSD is also using a 64-bit dev_t.

**Comment by xenu** [comment]
>This isn't a 32-bit vs 64-bit issue - he's building on amd64, which would give him 64-bit IVs, it's purely signedness, at least at this point.

I'm well aware, I was talking specifically about the stringification part of that code. It was a side note unrelated to this issue.

Anyway, the `st_ino` code does deal with the signedness issue.

**Comment by jkeenan** [comment]
@tonycoz, @xenu,

Could you work up a patch for this problem? @bingos and I could then test it on various FreeBSDs (and other platforms).

Thank you very much.
Jim Keenan
