### ISSUE TITLE
Commit 77d67a7 perl-blead breaks some CPAN module tests

### ISSUE THREAD

**Issue by timlegge** [Perl/perl5#18845]
Commit 

https://github.com/Perl/perl5/commit/77d67a71fd390db0379d24f395ddb1a7ac97d0e7 l

will likely break a few tests including Crypt::OpenSSL::VerifyX509 and Crypt::OpenSSL::Verify that are looking for the original wording:

```
my $ret;
eval {
        my $not_cert = 'foo!';
        $ret = $v->verify($not_cert);
};
#ok($@ =~ /x509 is not of type Crypt::OpenSSL::X509/);
ok($@ =~ /Expected x509 to be of type Crypt::OpenSSL::X509/);
```
https://github.com/Perl/perl5/blob/403d7eb3e4320188571cf61b9dab62ff10799f49/lib/ExtUtils/typemap#L222

I can easily update for either text but is there a better way to deal with it across versions?

Tim

**Comment by timlegge** [comment]
New releases of Crypt::OpenSSL::Verify and Crypt::OpenSSL::VerifyX509 have been released to resolve the issues there with this change.  I am fine with closing the issue.

**Comment by jkeenan** [comment]
> New releases of Crypt::OpenSSL::Verify and Crypt::OpenSSL::VerifyX509 have been released to resolve the issues there with this change. I am fine with closing the issue.

Confirmed.  Thanks for your investigation.  Closing ticket.
