### ISSUE TITLE
Correcting the wrong number of arguments message

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#18857]
Please suppress the error message below when it is obvious that, in fact, the correct number of arguments are being supplied? 
```
sub aaa($$) {} aaa(1 ? (1,2) : (2,1)); # Not enough arguments for main::aaa
```

**Comment by leonerd** [comment]
Ah this is a common misunderstanding of prototypes. The prototype `($$)` does not say that "at runtime, this function takes two parameters". No, what it says, is that "at *compiletime* this named operator takes two expressions, both in scalar context".

You supplied just one expression in scalar context, being the `(1,2)` or `(2,1)` as scalar-comma.

Compare instead to a similar idea but using signatures:

```perl
use experimental 'signatures';
sub aaa($x, $y) { say "X=$x Y=$y" }
aaa(1 ? (1,2) : (2,1));'
__END__
X=1 Y=2
```
