### ISSUE TITLE
Syntax error on splice of flat array

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#18867]
The array @b is flat like @a but **splice** seems to think it is a reference:

    my @a = (1, 2, 3);
    splice @a, 1, 1, 'A';
    splice((my @b = (1, 2, 3)), 1, 1, 'B');  # Experimental splice on scalar is now forbidden near "'B')"

(Github has uppercased the @a).

**Comment by Grinnz** [comment]
Actually it's weirder than that. The autoderef prohibition is getting confused by the argument list, it's not even getting that far. The parentheses are unnecessary due to precedence, but the error still occurs without them:

    splice my @b = 1..3, 1, 1, 'B';

**Comment by jkeenan** [comment]
> Actually it's weirder than that. The autoderef prohibition is getting confused by the argument list, it's not even getting that far. The parentheses are unnecessary due to precedence, but the error still occurs without them:
> 
> ```
> splice my @b = 1..3, 1, 1, 'B';
> ```

I don't see anything in `perldoc -f splice` that suggests that one could or should assign to an array within the first argument to `splice`.  So why should we *not* expect a syntax error in that code (albeit perhaps a differently worded syntax error)?

Thank you very much.
Jim Keenan

**Comment by tonycoz** [comment]
This was an error prior to autoderef:
```
$ ~/perl/5.12.0/bin/perl -e 'my @a = ( 1,2,3); splice @a, 1, 1, "A"; splice((my @b = (1,2,3)), 1, 1, "B")'
Type of arg 1 to splice must be array (not list assignment) at -e line 1, near ""B")
"
Execution of -e aborted due to compilation errors.
```

While a scalar assignment returns an lvalue for the scalar, a list assignment (like the above) returns a list of lvalues - not an array if the original was an array, note how "d" isn't added to `@y` here:
```
$ perl -le 'my @x = (1,2,3); (my @y = @x) = qw(a b c d); print @y'
abc
```

The error message isn't great, but perl is correctly rejecting invalid code.

**Comment by tonycoz** [comment]
Closing.
