### ISSUE TITLE
Memory corruption found

### ISSUE THREAD

**Issue by Ma-XX-oN** [Perl/perl5#18860]
This is a bug report for perl from adrianh.bsc@gmail.com,
generated with the help of perlbug 1.42 running under perl 5.32.1.

-----------------------------------------------------------------
When debugging some regex, I came across a memory corruption problem.  This occurred on gitbash's perl:

>  This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-msys-thread-multi

as well on an older version from cygwin:

>  This is perl 5, version 30, subversion 2 (v5.30.2) built for x86_64-cygwin-threads-multi

It appears to only happen when assigning to `$_` in the `indent` subroutine.  **EDIT:** ~~If change this routine to use a different variable, the problem goes away.~~ In this simple test example, it goes away, but I just tried it in my original program and found that it still fails (quite spectacularly too.  I get a lot of extended chars (> 127)) 

Test code (test.pl):
```
sub indent {
    $_ = shift;
    s/^([^\r\n]*)/  >$1</mg;
    $_;
}

sub l {
    my ($str) = @_;
    my @lines = split(/\r\n?|\n\r?/, $str);
    return indent join("\n", @lines[0..5]);
}

sub x {
  my $s = shift;
  print "$s\npre: ".l($`)."\nmatch: ".l($&)."\npost: ".l($')."\n"
}

my $regex = qr%(?{x 1})|$%;
my $str = "a\n";
$/=undef;
$str = <>;
$str =~ /$regex/;
```

Test data file (dat.txt):
```
a
```

This is a 2 byte file containing a single character `a` with a `\n` after it.

Expected output:
```
$ perl test.pl dat.txt
1
pre:   ><
  ><
  ><
  ><
  ><

match:   ><
  ><
  ><
  ><
  ><

post:   >a<
  ><
  ><
  ><
  ><
```

Test output from gitbash:
```
$ perl test.pl dat.txt
1
pre:   ><
  ><
  ><
  ><
  ><

match:   ><
  ><
  ><
  ><
  ><

post:   Q<
  ><
  ><
  ><
  ><
```

Test output from cygwin:
```
$ perl test.pl dat.txt
1
pre:   ><
  ><
  ><
  ><
  ><

match:   ><
  ><
  ><
  ><
  ><

post:   >H<
  ><
  ><
  ><
  ><
```

As you can see, the "post:" data gets screwed up on the first line in both cases.

Thx for your help.

cygwin's `perl -V` output:
Summary of my perl5 (revision 5 version 30 subversion 2) configuration:

  Platform:
    osname=cygwin
    osvers=3.1.4(0.34053)
    archname=x86_64-cygwin-threads-multi
    uname='cygwin_nt-10.0 cygwinpro 3.1.4(0.34053) 2020-02-19 08:49 x86_64 cygwin '
    config_args='-des -Dprefix=/usr -Dmksymlinks -Darchname=x86_64-cygwin-threads -Dlibperl=cygperl5_30.dll -Dcc=gcc -Dld=g++ -Accflags=-ggdb -O2 -pipe -Wall -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/mnt/share/cygpkgs/perl/perl.x86_64/build=/usr/src/debug/perl-5.30.2-1 -fdebug-prefix-map=/mnt/share/cygpkgs/perl/perl.x86_64/src/perl-5.30.2=/usr/src/debug/perl-5.30.2-1 -fwrapv'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags ='-DPERL_USE_SAFE_PUTENV -U__STRICT_ANSI__ -D_GNU_SOURCE -ggdb -O2 -pipe -Wall -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/mnt/share/cygpkgs/perl/perl.x86_64/build=/usr/src/debug/perl-5.30.2-1 -fdebug-prefix-map=/mnt/share/cygpkgs/perl/perl.x86_64/src/perl-5.30.2=/usr/src/debug/perl-5.30.2-1 -fwrapv -fno-strict-aliasing'
    optimize='-O3'
    cppflags='-DPERL_USE_SAFE_PUTENV -U__STRICT_ANSI__ -D_GNU_SOURCE -ggdb -O2 -pipe -Wall -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/mnt/share/cygpkgs/perl/perl.x86_64/build=/usr/src/debug/perl-5.30.2-1 -fdebug-prefix-map=/mnt/share/cygpkgs/perl/perl.x86_64/src/perl-5.30.2=/usr/src/debug/perl-5.30.2-1 -fwrapv -fno-strict-aliasing'
    ccversion=''
    gccversion='9.2.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags =' -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong'
    libpth=/usr/lib
    libs=-lpthread -lnsl -lgdbm -ldb -ldl -lcrypt -lgdbm_compat
    perllibs=-lpthread -lnsl -ldl -lcrypt
    libc=/usr/lib/libcygwin.a
    so=dll
    useshrplib=true
    libperl=cygperl5_30.dll
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' --shared  -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong'

Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Locally applied patches:
    Cygwin: README
    Cygwin: use auto-image-base instead of fixed DLL base address
    Cygwin: modify hints
    Cygwin: Configure correct libsearch
    Cygwin: Configure correct libpth
    Cygwin: Win32 correct UTF8 handling
    Perl:   InvLists moved back to interpreter level
  Built under cygwin
  Compiled at Mar 15 2020 09:52:28
  @INC:
    /usr/local/lib/perl5/site_perl/5.30/x86_64-cygwin-threads
    /usr/local/share/perl5/site_perl/5.30
    /usr/lib/perl5/vendor_perl/5.30/x86_64-cygwin-threads
    /usr/share/perl5/vendor_perl/5.30
    /usr/lib/perl5/5.30/x86_64-cygwin-threads
    /usr/share/perl5/5.30

[Please do not change anything below this line]
-----------------------------------------------------------------
---
Flags:
    category=core
    severity=medium
---
Site configuration information for perl 5.32.1:

Configured by VssAdministrator at Sun Jan 24 14:39:15 GMT 2021.

Summary of my perl5 (revision 5 version 32 subversion 1) configuration:

  Platform:
    osname=msys
    osvers=3.1.7-340.x86_64
    archname=x86_64-msys-thread-multi
    uname='msys_nt-10.0-14393 fv-az242-691 3.1.7-340.x86_64 2020-10-23 13:08 utc x86_64 msys '
    config_args='-des -Dusethreads -Doptimize=-march=x86-64 -mtune=generic -O2 -pipe -Dprefix=/usr -Dvendorprefix=/usr -Dprivlib=/usr/share/perl5/core_perl -Darchlib=/usr/lib/perl5/core_perl -Dsitelib=/usr/share/perl5/site_perl -Dsitearch=/usr/lib/perl5/site_perl -Dvendorlib=/usr/share/perl5/vendor_perl -Dvendorarch=/usr/lib/perl5/vendor_perl -Dscriptdir=/usr/bin/core_perl -Dsitescript=/usr/bin/site_perl -Dvendorscript=/usr/bin/vendor_perl -Dinc_version_list=none -Dman1ext=1perl -Dman3ext=3perl -Darchname=-msys-threads -Dmyarchname=-msys -Dlibperl=msys-perl5_32.dll -Dcc=gcc -Dld=g++ -Accflags=-march=x86-64 -mtune=generic -O2 -pipe -fwrapv'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags ='-DPERL_USE_SAFE_PUTENV -U__STRICT_ANSI__ -D_GNU_SOURCE -march=x86-64 -mtune=generic -O2 -pipe -fwrapv -fno-strict-aliasing -fstack-protector-strong -D_FORTIFY_SOURCE=2'
    optimize='-march=x86-64 -mtune=generic -O2 -pipe'
    cppflags='-DPERL_USE_SAFE_PUTENV -U__STRICT_ANSI__ -D_GNU_SOURCE -march=x86-64 -mtune=generic -O2 -pipe -fwrapv -fno-strict-aliasing -fstack-protector-strong'
    ccversion=''
    gccversion='10.2.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags =' -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong'
    libpth=/usr/lib
    libs=-lpthread -ldl -lcrypt
    perllibs=-lpthread -ldl -lcrypt
    libc=/usr/lib/libmsys-2.0.a
    so=dll
    useshrplib=true
    libperl=msys-perl5_32.dll
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' --shared  -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong'

---
@INC for perl 5.32.1:
    /usr/lib/perl5/site_perl
    /usr/share/perl5/site_perl
    /usr/lib/perl5/vendor_perl
    /usr/share/perl5/vendor_perl
    /usr/lib/perl5/core_perl
    /usr/share/perl5/core_perl

---
Environment for perl 5.32.1:
    HOME=/c/Users/Adrian
    LANG (unset)
    LANGUAGE (unset)
    LC_CTYPE=en_US.UTF-8
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    MSYSTEM=MINGW64
    MSYSTEM_CARCH=x86_64
    MSYSTEM_CHOST=x86_64-w64-mingw32
    MSYSTEM_PREFIX=/mingw64
    PATH=/c/Users/Adrian/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/Adrian/bin:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/ProgramData/Oracle/Java/javapath:/c/Program Files (x86)/Intel/iCLS Client:/c/Program Files/Intel/iCLS Client:/c/windows/system32:/c/windows:/c/windows/System32/Wbem:/c/windows/System32/WindowsPowerShell/v1.0:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files/OpenVPN/bin:/c/Program Files/Microsoft SQL Server/110/Tools/Binn:/c/Program Files (x86)/GNU/GnuPG/pub:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Program Files (x86)/gnuplot/bin:/c/Program Files
(x86)/Skype/Phone:/c/Program Files/LLVM/bin:/c/Program Files/Intel/WiFi/bin:/c/Program Files/Common Files/Intel/WirelessCommon:/c/Program Files/dotnet:/c/Program Files (x86)/IncrediBuild:/c/Android:/c/Windows/System32:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/ProgramData/Oracle/Java/javapath:/c/Program Files (x86)/Intel/iCLS Client:/c/Program Files/Intel/iCLS Client:/c/windows/system32:/c/windows:/c/windows/System32/Wbem:/c/windows/System32/WindowsPowerShell/v1.0:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files/OpenVPN/bin:/c/Program Files/Microsoft SQL Server/110/Tools/Binn:/c/Program Files (x86)/GNU/GnuPG/pub:/c/Program
Files/Microsoft SQL Server/130/Tools/Binn:/c/Program Files (x86)/gnuplot/bin:/c/Program Files (x86)/Skype/Phone:/c/Program Files/LLVM/bin:/c/Program Files/Intel/WiFi/bin:/c/Program Files/Common Files/Intel/WirelessCommon:/c/Program Files/dotnet:/c/Program Files (x86)/IncrediBuild:/c/Android:/c/Windows/System32:/c/program files/ffmpeg/bin:/c/Program Files (x86)/GPAC:/usr/bin/vendor_perl:/usr/bin/core_perl
    PERL_BADLANG (unset)
    SHELL=/usr/bin/bash

**Comment by Leont** [comment]
This issue stems from reusing `$_`. If you localized `$_` before assigning to it or if you used a lexical variable, this issue wouldn't happen.

**Comment by Ma-XX-oN** [comment]
Damn.  I don't know in what universe I thought that `$_` was localized by default. SMH.
