### ISSUE TITLE
[feature] my $@%a

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#18877]
Please allow:

    my $@%a;  # Can't use global $@ in "my"

as a short hand for:

    my $a; my @a, my %a;

**Comment by Grinnz** [comment]
This is both conflicting with existing syntax (`$@`, as the error shows), a bad idea to promote usage of variables with the same name, and not a useful shortcut as it decreases understandability.

**Comment by rabbiveesh** [comment]
I'm going to ask you this nicely. Why the hell would you ever write that? 

Also `$a` is a special global that you shouldn't use.

**Comment by jkeenan** [comment]
> Please allow:
> 
> ```
> my $@%a;  # Can't use global $@ in "my"
> ```
> 
> as a short hand for:
> 
> ```
> my $a; my @a, my %a; 
> ```

This is *so* ugly.  This should be rejected out-of-hand.

**Comment by Leont** [comment]
> This is both conflicting with existing syntax ($@, as the error shows), a bad idea to promote usage of variables with the same name, and not a useful shortcut as it decreases understandability.

Agreed with all of this.
