### ISSUE TITLE
perl.perl5.porters can't translate to the other language by google translation

### ISSUE THREAD

**Issue by yuki-kimoto** [Perl/perl5#18886]
**Where**

perl.perl5.porters

Site

https://www.nntp.perl.org/group/perl.perl5.porters/

Entry

https://www.nntp.perl.org/group/perl.perl5.porters/2021/06/msg260355.html

**Description**

I'm Japanese. It is difficult to read the entry by English. I read the entry using google translation for the first time.

perl.perl5.porters can't translate to the other language by google translation. the reason is I don't know(Maybe plain text?)

**Comment by tonycoz** [comment]
It translates for me, though I don't read Japanese

![image](https://user-images.githubusercontent.com/166429/121829509-1920a600-cd06-11eb-8d4a-c3ac0672c74f.png)

I'm using Firefox and manually visiting translate.google.com, not using Chrome's built-in translation.

**Comment by yuki-kimoto** [comment]
Sorry. This is Edge(Bing) translation problem.

![trans](https://user-images.githubusercontent.com/81858/121835773-052c7280-cd0d-11eb-9013-a26ff12e8f2a.jpg)

Please close this issue.

Chrome(google translation) is OK. I try this now.
