### ISSUE TITLE
Inconsistent behaviour post dereferencing bareword

### ISSUE THREAD

**Issue by happy-barney** [Perl/perl5#18906]
**Description**

Post dereferencing bareword without `strict` or `warnings` results in quite unexpected behavior
 
**Steps to Reproduce**
```
	my $foo = "xxx"; say "[1]", foo->$*;
	our $bar = "yyy"; say "[2]:", bar->$*;
	our $baz = "xxx"; { my $baz = "aaa"; say "[3]:", baz->$* };
```

Output
```
[1]
[2]:yyy
[3]:xxx
```

Problem is minor, is caused by using `PRIVATEREF` token for `my / state` variables
Problem is reasonably mitigated with `strict` or `warnings`, tough syntax `1->$*` will still be possible

**Comment by jkeenan** [comment]
> **Description**
> 
> Post dereferencing bareword without `strict` or `warnings` results in quite unexpected behavior
> 

What is the behavior you would expect (even if neither strict nor warnings were turned on)?


> **Steps to Reproduce**
> 
> ```
> 	my $foo = "xxx"; say "[1]", foo->$*;
> 	our $bar = "yyy"; say "[2]:", bar->$*;
> 	our $baz = "xxx"; { my $baz = "aaa"; say "[3]:", baz->$* };
> ```
> 

Why are you using removed variable `$*` here?

> Output
> 
> ```
> [1]
> [2]:yyy
> [3]:xxx
> ```
> 
> Problem is minor, is caused by using `PRIVATEREF` token for `my / state` variables
> Problem is reasonably mitigated with `strict` or `warnings`, tough syntax `1->$*` will still be possible

Thank you very much.
Jim Keenan

**Comment by happy-barney** [comment]
> 
> What is the behavior you would expect (even if neither strict nor warnings were turned on)?

Expression `term->$*` is treated as `${ term }`, so expected behavior is same.

> 
> Why are you using removed variable `$*` here?
> 

That is not variable `$*` but post-dereference operator

As mentioned problem lies in `toke.c` where `my` variable names are reported as `PRIVATEREF` whereas `our` variable names are reported as `BAREWORD`.

In `perly.y`, term can expand as `BAREWORD` but cannot as `PRIVATEREF`.

**Comment by khwilliamson** [comment]
@rjbs Any thoughts on this

**Comment by haarg** [comment]
The `->$*` syntax is always referred to as a dereference. The documentation does not say that `term->$*` is equivalent to `${ term }`. `foo->$*` is being treated as `${ "foo" }` which is a symbolic dereference. The current behavior feels correct to me. Possibly the documentation could be improved to clarify this.

**Comment by happy-barney** [comment]
@haarg that's not exactly true

```
return $obj->deref->$*;
return ${ $obj->deref };
```

so yes, just another inconsistence, just another reason to avoid perl

**Comment by haarg** [comment]
I'm not sure what your example is meant to demonstrate.

**Comment by haarg** [comment]
`${ $var }` is a dereference. `${ $obj->deref }` is a dereference. `${ "foo" }` is a symbolic dereference, which doesn't work under strict. `$var->$*` is a dereference. `$obj->deref->$*` is a dereference. `"foo"->$*` is a symbolic dereference. `foo->$*` is also a symbolic dereference, using `foo` as a bareword.

`${ foo }` is not a dereference. It is a delimited variable. It is equivalent to `$foo`, but sometimes more useful when interpolated in a string.

`TERM->$*` is not equivalent to `${ TERM }`, and the documentation does not state that it is. It does show some examples where that type of transformation would be equivalent, but they are cases where `${ TERM }` would be a dereference, not a delimited variable. `->$*` and other postfix ops are explicitly always dereferences.

**Comment by demerphq** [comment]
On Fri, 15 Apr 2022, 16:44 Graham Knop, ***@***.***> wrote:

> ${ $var } is a dereference. ${ $obj->deref } is a dereference. ${ "foo" }
> is a symbolic dereference, which doesn't work under strict. $var->$* is a
> dereference. $obj->deref->$* is a dereference. "foo"->$* is a symbolic
> dereference. foo->$* is also a symbolic dereference, using foo as a
> bareword.
>
> ${ foo } is not a dereference. It is a delimited variable. It is
> equivalent to $foo, but sometimes more useful when interpolated in a
> string.
>
> TERM->$* is not equivalent to ${ TERM }, and the documentation does not
> state that it is. It does show some examples where that type of
> transformation would be equivalent, but they are cases where ${ TERM }
> would be a dereference, not a delimited variable. ->$* and other postfix
> ops are explicitly always dereferences.
>

I think it might be usefult to point out that $obj->deref->$* is a
simplification of $obj->deref()->$* which is itself a simplification of
($obj->deref())->$* which is in turn a simplification of do{ my $tmp=
$obj->deref(); $tmp->$*}.

Maybe "simplification" is the wrong word, hopefully you get my point anyway.

I think the OP is getting confused about barewords and subs.

If there was a function called foo() in scope then foo->$* would be the
same as foo()->$*, when there isn't one it's the same as "foo"->().

Yves

>

**Comment by demerphq** [comment]
On Fri, 15 Apr 2022, 16:57 demerphq, ***@***.***> wrote:

>
>
> On Fri, 15 Apr 2022, 16:44 Graham Knop, ***@***.***> wrote:
>
>> ${ $var } is a dereference. ${ $obj->deref } is a dereference. ${ "foo" }
>> is a symbolic dereference, which doesn't work under strict. $var->$* is
>> a dereference. $obj->deref->$* is a dereference. "foo"->$* is a symbolic
>> dereference. foo->$* is also a symbolic dereference, using foo as a
>> bareword.
>>
>> ${ foo } is not a dereference. It is a delimited variable. It is
>> equivalent to $foo, but sometimes more useful when interpolated in a
>> string.
>>
>> TERM->$* is not equivalent to ${ TERM }, and the documentation does not
>> state that it is. It does show some examples where that type of
>> transformation would be equivalent, but they are cases where ${ TERM }
>> would be a dereference, not a delimited variable. ->$* and other postfix
>> ops are explicitly always dereferences.
>>
>
> I think it might be usefult to point out that $obj->deref->$* is a
> simplification of $obj->deref()->$* which is itself a simplification of
> ($obj->deref())->$* which is in turn a simplification of do{ my $tmp=
> $obj->deref(); $tmp->$*}.
>
> Maybe "simplification" is the wrong word, hopefully you get my point
> anyway.
>
> I think the OP is getting confused about barewords and subs.
>
> If there was a function called foo() in scope then foo->$* would be the
> same as foo()->$*, when there isn't one it's the same as "foo"->().
>

Sorry, typo: that should read "foo"->$* at the end of that last sentence.

Yves

>

**Comment by rjbs** [comment]
This whole thing appears to be rooted in confusion on the part of the OP.  Everything is working correctly.
