### ISSUE TITLE
perl-5.35.1 won't build on Windows 7, using mingw-w64 port of gcc-11.1.0

### ISSUE THREAD

**Issue by sisyphus** [Perl/perl5#18911]
Module:
dist/IO

**Description**

Attempting to build the latest devel release (perl-5.35.1) from source on Windows 7 with gcc-11.1.0 fails with:

```
In file included from IO.xs:18:
poll.h:14:12: fatal error: poll.h: No such file or directory
   14 | #  include <poll.h>
      |            ^~~~~~~~
compilation terminated.
gmake[1]: *** [Makefile:348: IO.o] Error 1
gmake[1]: Leaving directory 'C:/comp-1110/perl-5.35.1/dist/IO'
Unsuccessful make(dist/IO): code=512 at ..\make_ext.pl line 584.
make: *** [GNUmakefile:1696: Extensions] Error 2
```

I had no such trouble building blead (5.35.0) two weeks ago on the same system, using the same compiler.
That particular blead was at commit 1c1bafd87.

My first thought was that commit 52f0602 might have been the problem, but that doesn't make sense because, according to <code>git log</code> , commit 52f0602 pre-dates commit 1c1bafd87

**Perl configuration**

Obviously, there's no perl executable. Here, instead is 'miniperl -V'.
```
C:\comp-1110\perl-5.35.1\win32>..\miniperl -I..\lib -V
Summary of my perl5 (revision 5 version 35 subversion 1) configuration:

  Platform:
    osname=MSWin32
    osvers=6.1.7601
    archname=MSWin32-x64-multi-thread
    uname=''
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='gcc'
    ccflags =' -DWIN32 -DWIN64 -fdiagnostics-color=never -DPERL_TEXTMODE_SCRIPTS
 -DMULTIPLICITY -DPERL_IMPLICIT_SYS -DUSE_PERLIO -D__USE_MINGW_ANSI_STDIO -fwrap
v -fno-strict-aliasing -mms-bitfields'
    optimize='-s -O2'
    cppflags='-DWIN32'
    ccversion=''
    gccversion='11.1.0'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='long long'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags ='-s -L"C:\perl-5.35.1-1110\lib\MSWin32-x64-multi-thread\CORE" -L"C:
\_64\winlibs-gcc-1110\mingw64\lib" -L"C:\_64\winlibs-gcc-1110\mingw64\x86_64-w64
-mingw32\lib" -L"C:\_64\winlibs-gcc-1110\mingw64\lib\gcc\x86_64-w64-mingw32\11.1
.0"'
    libpth=C:\_64\winlibs-gcc-1110\mingw64\lib C:\_64\winlibs-gcc-1110\mingw64\x
86_64-w64-mingw32\lib C:\_64\winlibs-gcc-1110\mingw64\lib\gcc\x86_64-w64-mingw32
\11.1.0 C:\_64\msys_1110\1.0\local\lib
    libs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi3
2 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversio
n -lodbc32 -lodbccp32 -lcomctl32
    perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladv
api32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lve
rsion -lodbc32 -lodbccp32 -lcomctl32
    libc=
    so=dll
    useshrplib=true
    libperl=libperl535.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-mdll -s -L"C:\perl-5.35.1-1110\lib\MSWin32-x64-multi-thread\CORE
" -L"C:\_64\winlibs-gcc-1110\mingw64\lib" -L"C:\_64\winlibs-gcc-1110\mingw64\x86
_64-w64-mingw32\lib" -L"C:\_64\winlibs-gcc-1110\mingw64\lib\gcc\x86_64-w64-mingw
32\11.1.0"'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    HAVE_INTERP_INTERN
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DISABLE_PMC
    PERL_DONT_CREATE_GVSV
    PERL_EXTERNAL_GLOB
    PERL_IS_MINIPERL
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_NO_REGISTRY
    USE_PERLIO
    USE_PERL_ATOF
    USE_SITECUSTOMIZE
  Built under MSWin32
  Compiled at Jun 21 2021 12:12:01
  @INC:
    C:\comp-1110\perl-5.35.1\lib
    C:\comp-1110\perl-5.35.1\cpan\AutoLoader\lib
    C:\comp-1110\perl-5.35.1\dist\Carp\lib
    C:\comp-1110\perl-5.35.1\dist\PathTools
    C:\comp-1110\perl-5.35.1\dist\PathTools\lib
    C:\comp-1110\perl-5.35.1\cpan\ExtUtils-Install\lib
    C:\comp-1110\perl-5.35.1\cpan\ExtUtils-MakeMaker\lib
    C:\comp-1110\perl-5.35.1\cpan\ExtUtils-Manifest\lib
    C:\comp-1110\perl-5.35.1\cpan\File-Path\lib
    C:\comp-1110\perl-5.35.1\ext\re
    C:\comp-1110\perl-5.35.1\dist\Term-ReadLine\lib
    C:\comp-1110\perl-5.35.1\dist\Exporter\lib
    C:\comp-1110\perl-5.35.1\ext\File-Find\lib
    C:\comp-1110\perl-5.35.1\cpan\Text-Tabs\lib
    C:\comp-1110\perl-5.35.1\dist\constant\lib
    C:\comp-1110\perl-5.35.1\cpan\version\lib
    C:\comp-1110\perl-5.35.1\cpan\Getopt-Long\lib
    C:\comp-1110\perl-5.35.1\cpan\Text-ParseWords\lib
    C:\comp-1110\perl-5.35.1\cpan\ExtUtils-PL2Bat\lib
    C:\comp-1110\perl-5.35.1\dist\ExtUtils-ParseXS\lib
    C:\comp-1110\perl-5.35.1\cpan\parent\lib
    C:\comp-1110\perl-5.35.1\cpan\ExtUtils-Constant\lib
    .
```

**Comment by sisyphus** [comment]
Doh !!
True to form, within a minute of posting my report, I remember that I recently upgraded the mingw runtime to version 9.0.0 about two days after I successfully built that perl-5.35.0.
Sure enough, when I revert to version 8.0.0, perl-5.35.1 builds fine.

So ... this issue is apparently the result of the runtime update to v9.

For anyone interested, this gcc-11.1.0, runtime v9 combination is available at:
https://github.com/brechtsanders/winlibs_mingw/releases/download/11.1.0-12.0.0-9.0.0-r2/winlibs-x86_64-posix-seh-gcc-11.1.0-llvm-12.0.0-mingw-w64-9.0.0-r2.7z

Or, to avoid the Clang/LLVM included in that distro:
https://github.com/brechtsanders/winlibs_mingw/releases/download/11.1.0-12.0.0-9.0.0-r2/winlibs-x86_64-posix-seh-gcc-11.1.0-mingw-w64-9.0.0-r2.7z

**Comment by Jamaika1** [comment]
https://github.com/GrokImageCompression/grok/issues/252

**Comment by sisyphus** [comment]
For the record, here are the patches I used in order to build perl-5.35.1 using gcc-11.1.0 with runtime version 9.0.0.
The fist issue was that the build was trying to <code>#include <poll.h></code>, though mingw-w64 does not provide such a header.
This was happening because winsock2.h (which defines the symbol POLLWRBAND) was being included.
With runtime 8.0.0, winsock2.h defines the very same symbol - yet, for some reason. winsock2.h (apparently) does not get \#included.
I figured that one solution would be to ensure that winsock2.h is also excluded when using runtime 9.0.0:

```
C:\comp-1110\perl-5.35.1>diff -wu win32/include/sys/socket.h_orig win32/include/sys/socket.h
--- win32/include/sys/socket.h_orig     2021-02-19 00:04:48 +1100
+++ win32/include/sys/socket.h  2021-06-25 00:03:27 +1000
@@ -12,6 +12,10 @@
 #endif
 #include <windows.h>

+#if(defined(__MINGW64_VERSION_MAJOR) && __MINGW64_VERSION_MAJOR > 8)
+#include <winsock.h>
+#endif
+
 /* Too late to include winsock2.h if winsock.h has already been loaded */
 #ifndef _WINSOCKAPI_
 #  include <winsock2.h>
```
Next problem was that cpan/Socket/Socket.xs declares and defines a couple of functions (inet_pton and inet_ntop) that have already been declared elsewhere in runtime 9.0.0.
This is fixed with:
```
C:\comp-1110\perl-5.35.1>diff -wu cpan/Socket/Socket.xs_orig cpan/Socket/Socket.xs
--- cpan/Socket/Socket.xs_orig  2021-06-13 18:28:31 +1000
+++ cpan/Socket/Socket.xs       2021-06-25 11:32:14 +1000
@@ -98,6 +98,8 @@

 #endif

+#if(!defined(__MINGW64_VERSION_MAJOR) || __MINGW64_VERSION_MAJOR < 9)
+
 static int inet_pton(int af, const char *src, void *dst)
 {
   struct sockaddr_storage ss;
@@ -146,6 +148,8 @@
     return dst;
 }

+#endif /* __MINGW_VERSION_MAJOR < 9 */
+
 #define HAS_INETPTON
 #define HAS_INETNTOP
 #endif
```

Finally, for reasons that remain unknown to me, the expression <code>sizeof(struct sockaddr_storage)</code> in pp_sys.c is deemed illegal with runtime 9.
My workaround was to patch pp_sys.c as follows:
```
C:\comp-1110\perl-5.35.1>diff -wu pp_sys.c_orig pp_sys.c
--- pp_sys.c_orig       2021-06-03 16:38:28 +1000
+++ pp_sys.c    2021-06-25 12:20:32 +1000
@@ -2750,7 +2750,11 @@
         goto nuts;

 #ifdef HAS_SOCKADDR_STORAGE
+#if(defined(__MINGW64_VERSION_MAJOR) && __MINGW64_VERSION_MAJOR > 8)
+    len = 128;
+#else
     len = sizeof(struct sockaddr_storage);
+#endif /* MINGW_VERSION_MAJOR >  8 */
 #else
     len = 256;
 #endif
```

That all had the desired effect.
Hopefully that might help someone come up with a better fix.

**Comment by Leont** [comment]
> Finally, for reasons that remain unknown to me, the expression sizeof(struct sockaddr_storage) in pp_sys.c is deemed illegal with runtime 9.

That sounds like `HAS_SOCKADDR_STORAGE` should be false.

**Comment by sisyphus** [comment]
On Sat, Jun 26, 2021 at 12:10 AM Leon Timmermans ***@***.***>
wrote:

> Finally, for reasons that remain unknown to me, the expression
> sizeof(struct sockaddr_storage) in pp_sys.c is deemed illegal with runtime
> 9.
>
> That sounds like HAS_SOCKADDR_STORAGE should be false
>
I finally realized that the error message ( "invalid application of
'sizeof' to incomplete type 'struct sockaddr_storage'" ) was a consequence
of winsock2.h having NOT been #included.
And you're correct in that  HAS_SOCKADDR_STORAGE should indeed be false if
winsock2.h has not been included.
Perhaps that exclusion of winsock2.h was a consequence of my hack to
win32/include/socket.h.

It's clearly apparent that, from runtime 8 to runtime 9, the Windows API
has been altered in a way that the perl source does not currently allow for.

The Windows API is, of course, one of my many areas of inexpertise ;-)

Cheers,
Rob

**Comment by sisyphus** [comment]
I made some enquiries ( https://sourceforge.net/p/mingw-w64/mailman/message/37341428/ ) about mingw runtime-v9 changes at the mingw-64 mailing list.
I was told that these changes bring mingw-w64 runtime into alignment with MSVC runtime, and that seems to be an accurate assessment.

I've scrapped the 3 patches I came up with initially, replacing them with the following 2 patches:

```
--- cpan/Socket/Socket.xs_orig  2021-06-21 09:17:09 +1000
+++ cpan/Socket/Socket.xs       2021-08-29 21:37:33 +1000
@@ -98,6 +98,11 @@

 #endif

+/* MinGW-w64 ports of gcc with mingw runtime version >= 9 already
+ * provide inet_pton() and inet_ntop() in ws2tcpip.h.
+ */
+#if(!defined(__MINGW64_VERSION_MAJOR) || __MINGW64_VERSION_MAJOR < 9)
+
 static int inet_pton(int af, const char *src, void *dst)
 {
   struct sockaddr_storage ss;
@@ -146,6 +151,8 @@
     return dst;
 }

+#endif /* __MINGW_VERSION_MAJOR < 9 */
+
 #define HAS_INETPTON
 #define HAS_INETNTOP
 #endif

--- dist/IO/poll.h_orig 2019-11-05 09:57:20 +1100
+++ dist/IO/poll.h      2021-08-29 21:13:35 +1000
@@ -10,7 +10,7 @@
 #ifndef POLL_H
 #  define POLL_H

-#if (defined(HAS_POLL) && defined(I_POLL)) || defined(POLLWRBAND)
+#if (defined(HAS_POLL) && defined(I_POLL)) || (defined(POLLWRBAND) && !defined(_WIN32))
 #  include <poll.h>
 #elif (defined(HAS_POLL) && defined(I_SYS_POLL))
 #  include <sys/poll.h>
@@ -27,6 +27,11 @@
 #endif
 #define poll Perl_my_poll

+/* Begin mingw-runtime version 9 (and later) exclusions
+ * as these are already handled in winsock2.h
+ */
+#if !(defined(__MINGW64_VERSION_MAJOR) && __MINGW64_VERSION_MAJOR > 8)
+
 typedef struct pollfd {
     int fd;
     short events;
@@ -50,6 +55,8 @@

 int poll (struct pollfd *, unsigned long, int);

+#endif /* mingw-runtime version 9 (and later) exclusions */
+
 #ifndef HAS_POLL
 #  define HAS_POLL
 #endif

```

The new patch for cpan/Socket/Socket.xs is *essentially* unchanged from the first, and the patch to pp_sys.c has been done away with.

These patches test out fine for me with both runtime versions 8 and 9 x 32-bit and 64-bit mingw-w64.
They also test out fine with Visual Studio 2019. 

Is this now worthy of a PR, or can someone already see room for improvement ?

I can't yet understand why it is that Visual Studio 2019 builds were not suffering the same problem as faced by mingw-w64 with runtime version 9. 
And that bothers me a bit. 

I also thought it a little odd that HAS_POLL is being defined on mingw-w64 builds even though $Config{d_poll} is set to <code>undef</code>. This has been happening for some time, and my patches do not alter that behaviour.

Thoughts from @Leont , @xenu and anyone else would be welcome !!

**Comment by sisyphus** [comment]
There's also
https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-perl/007-use-winsock-socket-functions.patch
which, I assume deals with the same issue.
(This is one of a number of patches at https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-perl
It's written by a far better credentialed Windows programmer than me, so I had better investigate it, too.

**Comment by Biswa96** [comment]
I have tried to address the issue in this pull request https://github.com/Perl/perl5/pull/18862. But no reply from Socket module maintainer.

**Comment by sisyphus** [comment]
I'm just attaching the patches (r9.txt) that I'm currently using to build blead.
These work fine with both runtime version 9 and with earlier runtime versions.
I've now  partly copied what @Biswa96 was doing in #18862 by defining HAS_INETNTOP, HAS_INETPTON (in config.h), d_inetntop and d_inetpton (in %Config).
@Biswa96 also defined HAS_SOCKADDR_IN6 and d_sockaddr_in6, but I've omitted that bit because it causes cpan/IO-Socket-IP/t/04local-client-v6.t and cpan/IO-Socket-IP/t/04local-server-v6.t to fail on my builds.
(Leaving the "in6" symbols undefined means that those 2 test files are skipped, as normal.)

In my poll.h patch, I'm still finding a need to check whether we have runtime version 9 or not.
I think it should be possible (perhaps even easy) to avoid that check altogether - but I haven't yet hit upon a way to do that.

[r9.txt](https://github.com/Perl/perl5/files/7121875/r9.txt)

**Comment by jkahrman** [comment]
See also #16917

**Comment by jkahrman** [comment]
> See also #16917

Oh, that is also reported by @sisyphus

**Comment by jkahrman** [comment]
I'm running into the same issues building Perl using VS2015 after being required (for internal org reasons) to update _WIN32_WINNT and WINVER to 0x0600. @sisyphus, I'm working on applying a similar patch replacing the MinGW references with a comparison of the value of WINVER.

**Comment by jkahrman** [comment]
@sisyphus, I don't understand this part of your change to poll.h:
```
-#if (defined(HAS_POLL) && defined(I_POLL)) || defined(POLLWRBAND)
-#  include <poll.h>
+#if (defined(HAS_POLL) && defined(I_POLL)) || (defined(POLLWRBAND) && !defined(MINGW_RUNTIME_9_OR_LATER))
+#  ifdef _WIN32
+#    include <winsock2.h>
+#  else
+#    include <poll.h>
+#  endif
```

The original poll.h has this overall structure:
```
if system implements "poll" function
    include <poll.h>
else system implements "poll" function elsewhere
    include <sys/poll.h>
else 
    if system has implemented "select" function
        define what is needed to emulate poll using select
        define HAS_POLL to indicate poll is implemented (emulated) 
```
winsock2.h doesn't declare the "poll" API as far as I can see (it declares the similar API WSAPoll). So on Windows, we need to at least the following from the emulation section to be declared:
```
int poll (struct pollfd *, unsigned long, int);

#ifndef HAS_POLL
#  define HAS_POLL
#endif
```
in order for the related HAS_POLL block in dist/IO/IO.xs to be included and implement the emulated IO::Poll::poll. 

It seems appropriate to explicitly include  <winsock2.h> in poll.h on Windows, but that should be done independently of the emulation.

**Comment by sisyphus** [comment]
In a nutshell, that patch was the only incantation I could come up with that worked for all versions of mingw runtime && for Visual Studio 2019.
I've been using those patches to build perl devel releases (up to and including the latest perl-5.35.5), and they've worked well for me for both mingw and VS-2019 builds. Do they not work with VS-2015 ?

If there's a simpler way of achieving the same portability then I'll gladly make the switch to it.

I felt that there *ought* to be a simpler way, but *I* could find it :-( 
However, I think (needs to be checked) that @Biswa96 was doing something similar in #18862, and I believe that he's quite knowledgeable in this area .... so I do wonder whether that "simpler way" exists.
(The  problems for me with #18862  were that it didn't work with the older mingw runtimes, and that the d_sockaddr_in6 changes were resulting in a test failure.)

**Comment by jkahrman** [comment]
No, it didn't work for me in VS2015. And with the r9.txt patch, I don't see how the dist/IO/t/io_poll.t could ever pass using a Perl build that didn't have the MINGW_RUNTIME_9_OR_LATER macro defined. If MINGW_RUNTIME_9_OR_LATER is not defined, it will never go into the emulation section that defines HAS_POLL in order to enable the implementation of IO::Poll.

My take on your poll.h patch, @sisyphus:
[poll_h-VS2015-WINVER6.patch.txt](https://github.com/Perl/perl5/files/7530913/poll_h-VS2015-WINVER6.patch.txt)

In retrospect, it might have been more appropriate for my thread to be in #16917, instead of here.

**Comment by sisyphus** [comment]
On Sat, Nov 13, 2021 at 10:23 AM jkahrman ***@***.***> wrote:

> No, it didn't work for me in VS2015.
>
Then it fails its portability requirements, for a start.

> My take on your poll.h patch, @sisyphus <https://github.com/sisyphus>:
> poll_h-VS2015-WINVER6.patch.txt
> <https://github.com/Perl/perl5/files/7530913/poll_h-VS2015-WINVER6.patch.txt>
>
This looks much better then my attempt, and is so far testing fine for me.
I'll switch to using it from now on.
Even if my poll.h patch had been portable, I would still be making that
switch.
Thank you !!

> In retrospect, it might have been more appropriate for my thread to be in
> #16917 <https://github.com/Perl/perl5/issues/16917>, instead of here.
>
>
Perhaps ... but that thread is a couple of years old, and I had quite
forgotten about it.
I guess it ties in with this issue, but it pre-dates by a couple of years
the actual issue that prompted me to create this one.
I'm quite comfortable with having the follow-up discussions done here (in
#18911).

Should I close #16917, and refer it to #18911 ?

**Comment by jkahrman** [comment]
> Should I close #16917, and refer it to #18911 ?

Seems reasonable, but I'm not familiar with the recommended processes.

**Comment by sisyphus** [comment]
There's now also a need to amend t/porting/customized.dat.
Attached are the current patches that I'm using, including the customized.dat patch.
As soon as perl-5.36.0 has been released, I'll set about getting these patches applied to blead.

[diff.txt](https://github.com/Perl/perl5/files/8545821/diff.txt)

**Comment by sisyphus** [comment]
Fixed by https://github.com/Perl/perl5/pull/19663 and https://rt.cpan.org/Public/Bug/Display.html?id=142390.
Closing as completed.

Cheers,
Rob
