### ISSUE TITLE
[doc] open() to scalar -- can it return false?

### ISSUE THREAD

**Issue by epa** [Perl/perl5#18929]
**Where**
perlfunc / open, where it says

           Perl is built using PerlIO by default.  Unless you've changed this
           (such as building Perl with "Configure -Uuseperlio"), you can open
           filehandles directly to Perl scalars via:

               open(my $fh, ">", \$variable) || ..

**Description**
What happens on the right hand side of the `||`?  Clearly some kind of error handling, but why is it needed, and what would be the error in practice?

Checking the return value of `open()` for a file is good practice, but this documentation seems to imply that `open()` to a scalar could also return false under some circumstances.  What are they?  (And what happens if perl was not built with PerlIO?)

**Comment by Grinnz** [comment]
This documentation has been updated in recent versions of Perl: https://perldoc.perl.org/functions/open#Opening-a-filehandle-into-an-in-memory-scalar

**Comment by epa** [comment]
I do apologize, I was looking at an older version on perldoc.perl.org.
