### ISSUE TITLE
"0x00"+0 isn't numeric in addition 

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#18923]
Please make the string version and the numeric version behave the same way to minimize surprises?

    say STDERR 0x00+0;
    say STDERR "0x00"+0; # Argument "0x00" isn't numeric in addition (+)

**Comment by Grinnz** [comment]
Numeric literals and numification of strings are different in a number of ways. For example, leading 0s cause octal/hex/bin parsing in numeric literals but not numification of strings.

**Comment by sisyphus** [comment]
On Wed, Jun 23, 2021 at 5:02 PM Dan Book ***@***.***> wrote:

>
>    1. Numeric literals and numification of strings are different in a
>    number of ways. For example, leading 0s cause octal/hex/bin parsing in
>    numeric literals but not numification of strings.
>    2. 0x00 is not a numeric literal. It is the string '0' repeated zero
>    times.
>
>
That second point has me puzzled ... I'm not sure what you meant.
0x00 is not the string '0' repeated zero times.
It's actually the decimal value 0 - just as 0x15 is the decimal value 21.

I thought that you perhaps intended to state that '0'x00 is "the string '0'
repeated zero times", but that would not be quite right either. (That's
actually the empty string.)
Anyway, the OP wasn't asking about '0'x00.

The basic thing for the OP to be aware of is that perl (except for version
5.30.0) doesn't recognize  strings beginning with "0x" as having any
special meaning in numeric context.
So "0x00" is precisely the same as "0rubbish00" in numeric context and will
always have a value of zero, irrespective of what follows the "0x" ...
except for perl-5.30.0.

With current perl-5.34.0:

C:\>perl -wle "print $]; print '0x00' + 0;"
5.034000
Argument "0x00" isn't numeric in addition (+) at -e line 1.
0

C:\>perl -wle "print $]; print '123450x00' + 0;"
5.034000
Argument "123450x00" isn't numeric in addition (+) at -e line 1.
123450

 C:\>perl -wle "print $]; print '0xFF' + 0;"
5.034000
Argument "0xFF" isn't numeric in addition (+) at -e line 1.
0

And, for the record, with perl-5.30.0:

C:\>perl -wle "print $]; print '0xFF' + 0;"
5.030000
Argument "0xFF" isn't numeric in addition (+) at -e line 1.
255

(Clearly that warning wasn't warranted in perl-5.30.0, but the decision was
that the warning should stay and the behaviour should revert to what it had
previously been, This reversion was implemented in perl-5.30.1, IIRC.)

Cheers,
Rob

**Comment by Grinnz** [comment]
Yes, I removed it shortly after, but emails don't get updated.

**Comment by nwc10** [comment]
This is documented behaviour.

`0x00` is a hexadecimal constant literal, at the language level (the parser).
Using the string `"0x00"` in a numeric context will perform conversion, for which only strings which are(decimal) floating point values are accepted. (The string representations of an integer is a subset of floating point)

perldata says

```
Hexadecimal, octal, or binary, representations in string literals
(e.g. '0xff') are not automatically converted to their integer
representation.  The hex() and oct() functions make these conversions
for you.  See L<perlfunc/hex> and L<perlfunc/oct> for more details.
```

Hence the string `'0x00'` is just one case of a string which is not (in its entirety) valid floating point, hence it should warn as such, even though it **happens** to convert to the same value as its hex representation.

Not warning on this one case would be a special case. We're not going to add a special case.
Nor are we going go to change automatic conversion to handle all the formats that language permits as numeric literals

So i'm closing this.
