### ISSUE TITLE
"Modification of non-creatable array value attempted" on double but not single dereference

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#18927]
Line 2 is fine, but the very similar line 3 gets a run time error (that could have been detected at compile time).  Please make Perl behave the same way on line 2 and 3 to minimize surprises?  Thanks!

    my $t;
    $t->[-1]    //0; # OK
    $t->[-1][-1]//0; # Modification of non-creatable array value attempted, subscript -1

**Comment by haarg** [comment]
Line 2 autovivifies $t into an arrayref. It has no elements, but accessing -1 is still allowed and returns undef.
Line 3 attempts to autovivify $t->[-1], which doesn't exist so it cannot be created. An error is appropriate.

**Comment by Leont** [comment]
> Line 2 autovivifies $t into an arrayref. It has no elements, but accessing -1 is still allowed and returns undef.
> Line 3 attempts to autovivify $t->[-1], which doesn't exist so it cannot be created. An error is appropriate.

Agreed, closing.
