### ISSUE TITLE
Warn on addition to unblessed scalar reference in struct mode

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#18928]
Please allow me to urge that incrementing a non blessed scalar reference with use strict in force should at least warn that Perl is not C?
 
    use warnings FATAL => qw(all);
    use strict;

    my $t = [];
    say STDERR $t;
    say STDERR $t+0;

    # ARRAY(0x55c3cb2ae470)
    # 94299415569520

**Comment by Grinnz** [comment]
Unblessed refs used as numbers numify to their reference address. This is expected and [documented](https://perldoc.perl.org/perlref#Miscellaneous-Usage).

**Comment by Grinnz** [comment]
This could be a candidate for optional warnings, if they get implemented: #18543
