### ISSUE TITLE
syntax error at main.pl line 16, near ") {" Execution of main.pl aborted due to compilation errors.

### ISSUE THREAD

**Issue by Praveen-1982** [Perl/perl5#18937]
multi Factorial(0)
{
	1; # returning 1
}
multi Factorial(Int $n where $n > 0)
{
	$n * Factorial($n - 1); # Recursive Call
}
print Factorial(15);

**Comment by Grinnz** [comment]
This is not Perl code. It looks like Raku: https://www.raku.org
