### ISSUE TITLE
Remove unnecessary caller detection from Encode.xs

### ISSUE THREAD

**Issue by wolfdiem** [Perl/perl5#18935]
During inspection of the code of Encode.xs I noticed
in "PACKAGE = Encode::utf8" in function "Method_decode()"
the lines 644-660 between the following comments:
645 * PerlIO check -- we assume the object is of PerlIO if renewed
660 /* end PerlIO check */

(line numbers according to:
$Id: Encode.xs,v 2.48 2020/03/02 04:34:34 dankogai Exp $)

Here the variable "bool renewed" is set and later used in
the call to process_utf8() to indicate 'stop_at_partial'.
I think this detection of PerlIO is not (or no longer)
necessary, as the STOP_AT_PARTIAL bit in CHECK is always set
by PerlIO::encoding. And this STOP_AT_PARTIAL bit in check
is already used for the same purpose in process_utf8().
Thus the whole detection of PerlIO can be removed.

If process_utf8() is only called from inside Encode.xs,
then the last parameter of this subroutine could also
be removed ("bool stop_at_partial"), and the usage of
"stop_at_partial" in line 437 can be replaced by
"(check & ENCODE_STOP_AT_PARTIAL)".

This change would also lead to a better separation of
functionality, as Encode.xs is no longer involved in
decisions which should only be done by PerlIO::encoding.

**Comment by jkeenan** [comment]
Encode is maintained upstream on CPAN.  Please submit this report [there](https://rt.cpan.org/Public/Dist/Display.html?Name=Encode).

Thank you very much.
Jim Keenan
