### ISSUE TITLE
Time::HiRes clock_gettime fail with glibc

### ISSUE THREAD

**Issue by rdellison** [Perl/perl5#18953]
Module: Time::HiRes

**Description**

When Time::HiRes is compiled against glibc 2.3 clock_gettime is listed as unimplemented on the platform.
This appears to be because the module includes <sys/time.h> but clock_gettime is
defined in <time.h>.  Earlier versions of glibc appear to have included <time.h>
within <sys/time.h> to get structure definitions, but that was refactored to include 
common structure definition headers.  I found https://github.com/bminor/glibc/commit/05b68e14b146586c46121730241142256f0ef850
which appears to be the source of that change.

**Steps to Reproduce**

```
root@acmu:~# perl -e 'use Time::HiRes qw(clock_gettime CLOCK_MONOTONIC)'
Time::HiRes::clock_gettime(): unimplemented in this platform at -e line 1.
BEGIN failed--compilation aborted at -e line 1.
```

```
root@acmu:~# cat time_bad.c
#include <stdio.h>
#include <sys/time.h>
int main() {
    struct timespec now;
    if (!clock_gettime(CLOCK_MONOTONIC, &now)) {
        printf("%d.%09d\n", now.tv_sec, now.tv_nsec);
    }
}
root@acmu:~# gcc time_bad.c
time_bad.c: In function 'main':
time_bad.c:5:10: warning: implicit declaration of function 'clock_gettime' [-Wimplicit-function-declaration]
    5 |     if (!clock_gettime(CLOCK_MONOTONIC, &now)) {
      |          ^~~~~~~~~~~~~
time_bad.c:5:24: error: 'CLOCK_MONOTONIC' undeclared (first use in this function)
    5 |     if (!clock_gettime(CLOCK_MONOTONIC, &now)) {
      |                        ^~~~~~~~~~~~~~~
time_bad.c:5:24: note: each undeclared identifier is reported only once for each function it appears in
```

**Expected behavior**

clock_gettime should work.

```
root@acmu:~# cat time_good.c
#include <stdio.h>
#include <time.h>
int main() {
    struct timespec now;
    if (!clock_gettime(CLOCK_MONOTONIC, &now)) {
        printf("%d.%09d\n", now.tv_sec, now.tv_nsec);
    }
}
root@acmu:~# gcc time_good.c
root@acmu:~# ./a.out
894.991301412
```

**Perl configuration**

```
root@acmu:~# perl -V
Summary of my perl5 (revision 5 version 30 subversion 0) configuration:
(note: 'aero' is derived from Yocto 'poky' with systemd, rsyslog, udev)

  Platform:
    osname=linux
    osvers=current
    archname=aarch64-linux
    uname=''
    config_args='--prefix=/usr --libdir=/usr/lib --target=aarch64-aero-linux -Duseshrplib -Dsoname=libperl.so.5 -Dvendorprefix=/usr -Darchlibexp=/usr/lib/perl5/5.30.0/aarch64-linux --keeplog --mode=target --target=aarch64-aero-linux --targetarch=aarch64-aero-linux-gnu'
    hint=default
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=undef
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=undef
    bincompat5005=undef
  Compiler:
    cc='aarch64-aero-linux-gcc  -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security '
    ccflags =' -O2 -pipe -g -feliminate-unused-debug-types  -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-fwrapv -fno-strict-aliasing'
    cppflags=''
    ccversion='9.2.0'
    gccversion='9.2.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=0
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='aarch64-aero-linux-gcc  -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security '
    ldflags ='-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fstack-protector-strong -Wl,-z,relro,-z,now'
    libpth=/lib /usr/lib /usr/local/lib
    libs=-lm -lcrypt -lpthread -lgdbm -ldb -ldl -lgdbm_compat
    perllibs=-lm -lcrypt -ldl
    libc=
    so=so
    useshrplib=true
    libperl=libperl.so.5.30.0
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC -Wno-unused-function'
    lddlflags='-shared'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at May 18 2021 16:52:02
  @INC:
    /usr/lib/perl5/site_perl/5.30.0/aarch64-linux
    /usr/lib/perl5/site_perl/5.30.0
    /usr/lib/perl5/vendor_perl/5.30.0/aarch64-linux
    /usr/lib/perl5/vendor_perl/5.30.0
    /usr/lib/perl5/5.30.0/aarch64-linux
    /usr/lib/perl5/5.30.0
    .

```

**Comment by jkeenan** [comment]
> Module: Time::HiRes
> 
> **Description**
> 
> When Time::HiRes is compiled against glibc 2.3 clock_gettime is listed as unimplemented on the platform.
> This appears to be because the module includes <sys/time.h> but clock_gettime is
> defined in <time.h>. Earlier versions of glibc appear to have included <time.h>
> within <sys/time.h> to get structure definitions, but that was refactored to include
> common structure definition headers. I found [bminor/glibc@05b68e1](https://github.com/bminor/glibc/commit/05b68e14b146586c46121730241142256f0ef850)
> which appears to be the source of that change.
> 

Can you explain why you are filing a bug ticket with the Perl 5 core distribution about this problem?

As far as I can tell, what you are complaining about is that on Sep 23 2016 -- nearly five years ago -- someone performed a drastic restructuring of files to a (rather obscure) Linux distribution.  This restructuring now has the impact of preventing a library that ships with Perl 5 from building.

Shouldn't your complaint initially go to the people who made those changes?

Also, please note that your two C programs, notwithstanding their brevity, generate compilation warnings.  That raises doubts, at least for me, about their diagnostic value.

**Comment by Tux** [comment]
I am seeing the same on that sample code on my SUSE systemes, and I do not see those as obscure.
```
test.c: In function ‘main’:
test.c:5:10: warning: implicit declaration of function ‘clock_gettime’ [-Wimplicit-function-declaration]
     if (!clock_gettime (CLOCK_MONOTONIC, &now))
          ^~~~~~~~~~~~~
test.c:5:25: error: ‘CLOCK_MONOTONIC’ undeclared (first use in this function)
     if (!clock_gettime (CLOCK_MONOTONIC, &now))
                         ^~~~~~~~~~~~~~~
test.c:5:25: note: each undeclared identifier is reported only once for each function it appears in
test.c:6:19: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘__time_t {aka long int}’ [-Wformat=]
         printf ("%d.%09d\n", now.tv_sec, now.tv_nsec);
                  ~^          ~~~~~~~~~~
                  %ld
test.c:6:24: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘__syscall_slong_t {aka long int}’ [-Wformat=]
         printf ("%d.%09d\n", now.tv_sec, now.tv_nsec);
                     ~~~^                 ~~~~~~~~~~~
                     %09ld
```
vs
```
#include <stdio.h>
#include <time.h> /* No sys/ */
int main (int argc, char *argv[]) {
    struct timespec now;
    if (!clock_gettime (CLOCK_MONOTONIC, &now))
        printf ("%ld.%09ld\n", now.tv_sec, now.tv_nsec); /* %ld and %09ld */
    }
```
Has no warnings and works as expected.
But I had no problems whatsoever installing Time::HiRes (which I use a lot) and it works out of the box:
```
$ perl -MTime::HiRes=clock_gettime,CLOCK_MONOTONIC -wE'say clock_gettime (CLOCK_MONOTONIC)'
1132420.102566943
```
Using `perl-5.28.0` with `Time::HiRes-1.9764` on `openSUSE-Leap-15.2` in above triage

Building Time::HiRes from source, I see
```
$ make HiRes.c
$ grep include HiRes.c | head
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#  include "ppport.h"
#  include <w32api/windows.h>
#  include <time.h>
#  include <sys/time.h>
#    include <sys/select.h>
#  include <syscall.h>
#  include <lnmdef.h>

$ make HiRes.i
$ grep include.*time\.h HiRes.i
# 1 "/usr/include/time.h" 1 3 4
# 29 "/usr/include/time.h" 3 4
# 30 "/usr/include/time.h" 2 3 4
# 1 "/usr/include/bits/time.h" 1 3 4
# 73 "/usr/include/bits/time.h" 3 4
# 74 "/usr/include/bits/time.h" 2 3 4
# 34 "/usr/include/time.h" 2 3 4
# 40 "/usr/include/time.h" 2 3 4
# 48 "/usr/include/time.h" 3 4
# 49 "/usr/include/time.h" 2 3 4
# 68 "/usr/include/time.h" 3 4
# 196 "/usr/include/time.h" 3 4
# 211 "/usr/include/time.h" 3 4
# 280 "/usr/include/time.h" 3 4
# 289 "/usr/include/time.h" 3 4
# 303 "/usr/include/time.h" 3 4
# 1 "/usr/include/sys/time.h" 1 3 4
# 34 "/usr/include/sys/time.h" 3 4
# 52 "/usr/include/sys/time.h" 3 4
# 68 "/usr/include/sys/time.h" 3 4
# 186 "/usr/include/sys/time.h" 3 4
```
So on my system, `time.h` is included **before** `sys/time.h`, so all code works fine.
It is now up to you to find out why this does not work on your distribution.

It for sure is NOT a perl5 core issue

**Comment by rdellison** [comment]
I didn't see any other report an issue link on the Time::HiRes metacpan
page - that page also has no download for just this module, get the full
perl kit.
ok, there are two Time::HiRes pages with different authors and the
ATOOMIC one does have a kit.(both issues links go to perl5).
I tried compiling directly on a target rather than cross compile in case
running native perl and linking target .so was the issue.

What I see in HiRes.c only includes time.h if on WIN32

#ifdef WIN32
#  include <time.h>
#else
#  include <sys/time.h>
#endif

but perl Makefile.PL --configure does say that clock_gettime()... was
found, but no -D on the compile command, so must have hit the "#
Unlikely..." case.

aarch64-aero-linux-gcc  -fstack-protector-strong  -D_FORTIFY_SOURCE=2
-Wformat -Wformat-security -Werror=format-security  -c   -O2 -pipe -g
-feliminate-unused-debug-types -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
-fwrapv -fno-strict aliasing   -DVERSION=\"1.9764\" -DXS_VERSION=\"1.9764\"
-fPIC -Wno-unused-function "-I/usr/lib/perl5/5.30.0/aarch64-linux/CORE"
 -DTIME_HIRES_NANOSLEEP -DTIME_HIRES_CLOCKID_T -DHAS_FUTIMENS
-DHAS_UTIMENSAT -DTIME_HIRES_UTIME -DTIME_HIRES_STAT_XTIM
-DTIME_HIRES_STAT=4 -DUSE_PPPORT_H HiRes.c

If I add that definition to the makefile then it works.

***@***.***:~# diff Time-HiRes-1.9764/Makefile.PL
Time-HiRes-1.9764.patched/Makefile.PL -u
--- Time-HiRes-1.9764/Makefile.PL 2020-08-11 00:18:12.000000000 +0200
+++ Time-HiRes-1.9764.patched/Makefile.PL 2021-06-30 20:11:55.305207626
+0200
@@ -563,6 +563,7 @@
     my $has_clock_gettime_emulation;
     if (exists $Config{d_clock_gettime}) {
         $has_clock_gettime++ if $Config{d_clock_gettime}; # Unlikely...
+        $DEFINE .= ' -DTIME_HIRES_CLOCK_GETTIME';
     } elsif (has_clock_xxx('gettime')) {
         $has_clock_gettime++;
         $DEFINE .= ' -DTIME_HIRES_CLOCK_GETTIME';

***@***.***:~/Time-HiRes-1.9764.patched# make install
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- HiRes.bs
blib/arch/auto/Time/HiRes/HiRes.bs 644
Manifying 1 pod document
Files found in blib/arch: installing files in blib/lib into architecture
dependent library tree
Appending installation info to
/usr/lib/perl5/5.30.0/aarch64-linux/perllocal.pod
***@***.***:~/Time-HiRes-1.9764.patched# perl
-MTime::HiRes=clock_gettime,CLOCK_MONOTONIC -wE'say
clock_gettime(CLOCK_MONOTONIC)'
16516.406397646

**Comment by tonycoz** [comment]
> Can you explain why you are filing a bug ticket with the Perl 5 core distribution about this problem?

Because it's a bug in perl.  Per POSIX, you need  `#include <time.h>` to get access to clock_gettime() and the constant used when calling it.

https://pubs.opengroup.org/onlinepubs/9699919799/functions/clock_getres.html

**Comment by tonycoz** [comment]
> but perl Makefile.PL --configure does say that clock_gettime()... was found, but no -D on the compile command, so must have hit the "# Unlikely..." case.

Perl's Configure doesn't define `d_clock_gettime`, are you defining it somewhere?  The "Unlikely" case should only be hit if that symbol is defined, and Configure doesn't define it.

**Comment by rdellison** [comment]
I'm building using Yocto & OpenEmbedded.  The BSP vendor supports zeus release, so that's what I'm using.  This has a recipe for perl 5.30.0

`SRC_URI = "https://www.cpan.org/src/5.0/perl-${PV}.tar.gz;name=perl \
           https://github.com/arsv/perl-cross/releases/download/1.3/perl-cross-1.3.tar.gz;name=perl-cross \
           file://perl-rdepends.txt \
           file://0001-configure_tool.sh-do-not-quote-the-argument-to-comma.patch \
           file://0001-ExtUtils-MakeMaker-add-LDFLAGS-when-linking-binary-m.patch \
           file://0001-Somehow-this-module-breaks-through-the-perl-wrapper-.patch \
           file://errno_ver.diff \                                                                                                                                         
           file://native-perlinc.patch \
           file://0001-perl-cross-add-LDFLAGS-when-linking-libperl.patch \                                                                                                 
           file://perl-dynloader.patch \
           file://0001-configure_path.sh-do-not-hardcode-prefix-lib-as-libr.patch \
           file://fix-setgroup.patch \
           file://0001-enc2xs-Add-environment-variable-to-suppress-comments.patch \
           file://0002-Constant-Fix-up-shebang.patch \
           "
SRC_URI_append_class-native = " \
           file://perl-configpm-switch.patch \
"

SRC_URI[perl.md5sum] = "9770584cdf9b5631c38097645ce33549"
SRC_URI[perl.sha256sum] = "851213c754d98ccff042caa40ba7a796b2cee88c5325f121be5cbb61bbf975f2"
SRC_URI[perl-cross.md5sum] = "4dda3daf9c4fe42b3d6a5dd052852a48"
SRC_URI[perl-cross.sha256sum] = "49edea1ea2cd6c5c47386ca71beda8d150c748835781354dbe7f75b1df27e703"
`
Nothing in the recipe or the patch files contains 'clock_gettime'.

I'm working around the issue by appending a patch to the time-hires-perl recipe to add -DTIME_HIRES_CLOCK_GETTIME after the "# Unlikely" commented line.

**Comment by tonycoz** [comment]
```
perl-cross-1.3$ find . -type f -print0 | xargs -0 grep clock_gettime
./cnf/hints/android:d_clock_gettime='define'
./cnf/hints/linux:d_clock_gettime='define'
```

The hints file do define them.

Given Time::HiRes pays attention to those names it should be handling them correctly, I'll do a PR fixing them.
