### ISSUE TITLE
Array at front of my list

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#18954]
It would be nice if the code below either worked or there was a compile time error explaining why it will not work: 

    my @a = (4, 3, 2, 1);
    my (@b, $a, $b) = @a;
    print "$a  $b"; # Use of uninitialized value $a in concatenation

**Comment by Tanami** [comment]
Greedy assignment at start of ...assignment

**Comment by wolfdiem** [comment]
This is a feature, not an error.
Please see the perldata documentation:
The final element of a list assignment may be an array or a hash:

        ($a, $b, @rest) = split;
        my($a, $b, %rest) = @_;

You can actually put an array or hash anywhere in the list, but the first one in the list will soak up all the values, and anything after it will become undefined. This may be useful in a my() or local().

**Comment by neilb** [comment]
As per @wolfdiem above, this is perl working as designed and documented.
