### ISSUE TITLE
Compile time check for invalid bless values.

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#18967]
Please check for possible invalid bless values at compile time?

 {package AAA;
  use Data::Dump qw(dump);
  my $a = {};
  bless $a, undef;
  say STDERR dump($a);
 }

# Use of uninitialized value in bless
# Explicit blessing to '' (assuming package main)
# bless({}, "main")

**Comment by Grinnz** [comment]
It's not invalid. There are already two warnings telling you what went wrong.

**Comment by tonycoz** [comment]
The behaviour of `undef` when evaluated as a string, and the behaviour of the resulting `bless REF, ""` are both well defined.

**Comment by neilb** [comment]
This doesn't merit an additional warning for the specific case of `undef` – the existing warnings are fine.
