### ISSUE TITLE
Shells builtins require a terminated semicolon when using system, qx or exec

### ISSUE THREAD

**Issue by florian-pe** [Perl/perl5#18975]
**Description**
When executing a builtin shell command via system, qx{} or exec
(Normal commands that aren't shell builtins are fine.)

we get an error like this :
Can't exec "cd": No such file or directory at -e line 1.

This happens with or without arguments to the builtin, but there is no problem when you put a semicolon at the end
(with or without whitespace), which is weird, and also annoying to have to put a semicolon at the end of each builtin

(I discovered this while writing a little wrapper script around the shell to have features you couldn't add otherwise)

And intersetingly enough, this doesn't happen when there is an executable of the same name of the builtin I am trying to execute, located in /usr/bin/. This might be a clue to the bug.

On my system, the bultin that have a binary in /usr/bin/ are (echo, false, kill, printf, pwd, test, time, true).
I tested each one of these, and they all works fine.

**Steps to Reproduce**

Those trigger the error message :
```
perl -w -le 'system "cd"'
perl -w -le 'print qx{ cd }'
perl -w -le 'exec "cd"'
perl -w -le 'system "cd .. "'
perl -w -le 'print qx{ cd .. }'
perl -w -le 'exec "cd .. "'

perl -w -le 'print qx{ help }'
perl -w -le 'print qx{ shift }'
perl -w -le 'print qx{ wait }'
perl -w -le 'print qx{ trap }'
perl -w -le 'print qx{ eval }'
perl -w -le 'print qx{ pushd }'
etc ..
```

But those works fine with a semicolon
```
perl -w -le 'system "cd ..; "'
perl -w -le 'system "cd ..; pwd"'
perl -w -le 'system "help ; "'
```
And those also works fine because they are in /usr/bin/
```
perl -w -le 'print qx{ pwd }'
perl -w -le 'print qx{ echo }'
perl -w -le 'print qx{ false }'
perl -w -le 'print qx{ kill }'
etc ..
```

**Expected behavior**

There shouldn't be an error message.

**Perl configuration**

```
Summary of my perl5 (revision 5 version 34 subversion 0) configuration:
   
  Platform:
    osname=linux
    osvers=5.12.4-arch1-2
    archname=x86_64-linux-thread-multi
    uname='archlinux'
    config_args='-des -Dusethreads -Duseshrplib -Doptimize=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Dprefix=/usr -Dvendorprefix=/usr -Dprivlib=/usr/share/perl5/core_perl -Darchlib=/usr/lib/perl5/5.34/core_perl -Dsitelib=/usr/share/perl5/site_perl -Dsitearch=/usr/lib/perl5/5.34/site_perl -Dvendorlib=/usr/share/perl5/vendor_perl -Dvendorarch=/usr/lib/perl5/5.34/vendor_perl -Dscriptdir=/usr/bin/core_perl -Dsitescript=/usr/bin/site_perl -Dvendorscript=/usr/bin/vendor_perl -Dinc_version_list=none -Dman1ext=1perl -Dman3ext=3perl -Dcccdlflags='-fPIC' -Dlddlflags=-shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Dldflags=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -Dmyuname=archlinux -Dmyhostname=archlinux -Dcf_time=Sun May 23 04:04:24 PM UTC 2021'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-march=x86-64 -mtune=generic -O2 -pipe -fno-plt'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='11.1.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags ='-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib
    libs=-lpthread -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.33.so
    so=so
    useshrplib=true
    libperl=libperl.so
    gnulibc_version='2.33'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E -Wl,-rpath,/usr/lib/perl5/5.34/core_perl/CORE'
    cccdlflags='-fPIC'
    lddlflags='-shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at May 23 2021 16:04:24
  %ENV:
    PERL5LIB="/home/london/.my_configurations/perl_modules"
  @INC:
    /home/london/.my_configurations/perl_modules
    /usr/lib/perl5/5.34/site_perl
    /usr/share/perl5/site_perl
    /usr/lib/perl5/5.34/vendor_perl
    /usr/share/perl5/vendor_perl
    /usr/lib/perl5/5.34/core_perl
    /usr/share/perl5/core_perl

```

**Comment by jkeenan** [comment]
> **Description**
> When executing a builtin shell command via system, qx{} or exec
> (Normal commands that aren't shell builtins are fine.)
> 
> we get an error like this :
> Can't exec "cd": No such file or directory at -e line 1.
> 
> This happens with or without arguments to the builtin, but there is no problem when you put a semicolon at the end
> (with or without whitespace), which is weird, and also annoying to have to put a semicolon at the end of each builtin
> 
> (I discovered this while writing a little wrapper script around the shell to have features you couldn't add otherwise)
> [snip]
> And intersetingly enough, this doesn't happen when there is an executable of the same name of the builtin I am trying to execute, located in /usr/bin/. This might be a clue to the bug.
> 
> [snip]
> **Steps to Reproduce**
> 
> Those trigger the error message :
> 
> ```
> perl -w -le 'system "cd"'
> perl -w -le 'print qx{ cd }'
> perl -w -le 'exec "cd"'
> perl -w -le 'system "cd .. "'
> perl -w -le 'print qx{ cd .. }'
> perl -w -le 'exec "cd .. "'
> 
> perl -w -le 'print qx{ help }'
> perl -w -le 'print qx{ shift }'
> perl -w -le 'print qx{ wait }'
> perl -w -le 'print qx{ trap }'
> perl -w -le 'print qx{ eval }'
> perl -w -le 'print qx{ pushd }'
> etc ..
> ```

I suspect your findings are likely to be specific to some combination of operating system and shell.

Since you didn't provide examples of error messages in each case, comparison with other OS/shell combinations is difficult.  But, FWIW, here's what I got on FreeBSD-12 where I'm using the Almquist rewrite of the Bourne shell.

```
Bourne (Almquist) shell on FreeBSD-12

$ perl -w -le 'system "cd"'
$ perl -w -le 'print qx{ cd }'

$ perl -w -le 'exec "cd"'
$ perl -w -le 'system "cd" ..'
syntax error at -e line 1, at EOF
Execution of -e aborted due to compilation errors.
$ perl -w -le 'print qx{ cd .. }'

$ perl -w -le 'exec "cd .. "'
$ perl -w -le 'print qx{ help }'
Can't exec "help": No such file or directory at -e line 1.

$ perl -w -le 'print qx{ shift }'
Can't exec "shift": No such file or directory at -e line 1.

$ perl -w -le 'print qx{ wait }'

$ perl -w -le 'print qx{ trap }'
Can't exec "trap": No such file or directory at -e line 1.

$ perl -w -le 'print qx{ eval }'
Can't exec "eval": No such file or directory at -e line 1.

$ perl -w -le 'print qx{ pushd }'
Can't exec "pushd": No such file or directory at -e line 1.

$ 

```

**Comment by florian-pe** [comment]
I mistype this command
perl -w -le 'system "cd" ..'

But otherwise there is only one error message, it is the same every time : (so I didn't bother putting it more than once)
Can't exec "cd": No such file or directory at -e line 1.

except of course that in place of "cd" you have "help", "eval", etc..

I have not tested on other Operating Systems or other shells, but it is still in itself a bug for an extremely basic feature, on the most important / basic shell (sh) and on Linux and on FreeBSD thanks to your tests

**Comment by Corion** [comment]
This is documented behaviour of `system` (and  `readpipe` / `qx` ) too - see https://perldoc.perl.org/functions/system . I don't think it is a bug, since shell built-ins are not "programs" in the sense of executable files on a filesystem.

**Comment by florian-pe** [comment]
@Corion Sorry to respond only now, but could you please cite the exact involved passage in the documentation that talk about this ?
I do have read all 3 entries in perlfunc that you cited but I didn't see anywhere that a sentence that said something like "shell builtin commands require a semicolon".
And I don't see why this wouldn't be a bug (unless it is a feature) from perl in the sense that the sh binary itself doesn't require it (the semicolon). So why does perl requires it and/or why is it a desirable feature ?

**Comment by haarg** [comment]
> If there is only one scalar argument, the argument is checked for shell metacharacters, and if there are any, the entire argument is passed to the system's command shell for parsing (this is /bin/sh -c on Unix platforms, but varies on other platforms). If there are no shell metacharacters in the argument, it is split into words and passed directly to execvp, which is more efficient.

While this does not directly reference the issue with shell builtins, it explains the behavior that leads to this. If given a single argument with no shell metacharacters, the shell is not used. This results in shell builtins not working. A semicolon is a shell metacharacter and will cause perl to run the command using the shell.

**Comment by florian-pe** [comment]
Ah I understand now.
The semicolon is a metacharacter. So a builtin command with a semicolon at the end is passed to the sh binary and it woks, else it is executed with execvp, only it doesn't work for shell builtin because they don't live inside a separate binary like grep, sed or true but inside the sh binary.

Seeing how it works it may be too much clutter to add in the source code so that it would work as I originally thought/wish it should.

A quick 'ack' in the source code and I find this comment in doio.c
'''
    /* see if there are shell metacharacters in it */
'''
followed by : `memCHRs("$&*(){}[]'\";\\|?<>~`\n",*s)) {'
inside Perl_do_exec3(). This may be it.
