### ISSUE TITLE
[doc] qr is not mentioned

### ISSUE THREAD

**Issue by KES777** [Perl/perl5#18999]
**Where**
https://perldoc.perl.org/functions/qw

**Description**
The list of quote like operators does not mention `qr`

**Comment by Grinnz** [comment]
It is mentioned at https://perldoc.perl.org/functions/qr, this is a function of perldoc.perl.org splitting up perlfunc - in the source, they are nearby. https://perldoc.perl.org/perlfunc#q/STRING/

**Comment by KES777** [comment]
Probably I think wrong, but `q*` quotes and `*//` do matching (run regex). So `qr` should be listed on page which enumerate quote operators

**Comment by Grinnz** [comment]
That page does not enumerate quote operators, https://perldoc.perl.org/perlop#Quote-Like-Operators does.

**Comment by KES777** [comment]
would it be better if page will look like?
![image](https://user-images.githubusercontent.com/799021/126878342-8b4ca717-6585-410c-b31b-a018362a1646.png)
![image](https://user-images.githubusercontent.com/799021/126878357-0afbadd4-57c7-416d-8df1-3cc1216c8270.png)

**Comment by Grinnz** [comment]
This has nothing to do with the core documentation. Please raise issues regarding the extraction of function documentation from perlfunc at https://github.com/Grinnz/perldoc-browser/issues.
