### ISSUE TITLE
my &

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#19011]
Please make it possible to declare **my subs** as in Raku:

```
#!/usr/bin/perl
my &aaa {print "aaa\n"}; # syntax error
aaa;
```

**Comment by Grinnz** [comment]
The syntax for this is: `my sub aaa { ... }` (and you need to enable the experimental lexical_subs feature before Perl 5.26)

https://perldoc.perl.org/perlsub#Lexical-Subroutines
