### ISSUE TITLE
pod/perlapi.pod missing one entry; build-time warning being generated

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#19029]
Recently the following build-time warning has begun to be emitted during `make`:
```     
Empty pod for newAV_alloc_x (from av.h) at autodoc.pl line 1215.
```
This warning calls attention to this flaw in auto-generated `pod/perlapi.pod`:
```
  761 =for hackers
  762 Found in file av.h
  763 
  764 =over 4
  765 
  766 =item C<newAV_alloc_x>
  767 X<newAV_alloc_x>
  768 
  769 
  770 
  771 =over 3
  772 
  773  AV*  newAV_alloc_x(SSize_t size)
  774 
  775 =back
  776 
  777 =back
  778 
```
The relevant area in `av.h` is:
```
110 
111 /*
112 =for apidoc newAV_alloc_x
113 =for apidoc newAV_alloc_xz
114 
115 Similar to newAV(), but a SV* array is also allocated.
116 
```
I suspect that this warning was accidentally introduced in: 6e7a7813c39

I further suspect that we've encountered this problem previously.  Does anyone recall the fix?

Thank you very much.
Jim Keenan

**Comment by khwilliamson** [comment]
@richardleach is working on it, but busy

**Comment by jkeenan** [comment]
> @richardleach is working on it, but busy

Using [Devel::Git::MultiBisect::BuildTransitions](https://metacpan.org/pod/Devel::Git::MultiBisect::BuildTransitions), I was able to learn that this problem was cleared up with the following commit:
```
commit 48d21358f7bd06d60aaa4f913cd417b5eafa3fc0
Author:     Richard Leach <richardleach@users.noreply.github.com>
AuthorDate: Sun Aug 8 21:53:33 2021 +0100
Commit:     Karl Williamson <khw@cpan.org>
CommitDate: Fri Aug 27 07:12:53 2021 -0600

    av.h - better document newAV_alloc_x/newAV_alloc_xz

```
Closing ticket.  Thank you very much.
