### ISSUE TITLE
Can't use string ("") as an ARRAY ref

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#19042]
use strict;
    my $a = '';
    my @a = sort {$$b[0] <=> $$a[0]} ([1], [2]); # Can't use string ("") as an ARRAY ref

But no problems with:

    use strict;
    my @a = sort {$$b[0] <=> $$a[0]} ([1], [2]);

**Comment by leonerd** [comment]
Lexicals always override package variables:

```
eval: our $var = "package"; my $var = "lexical"; say $var;
lexical
```

Thus your sort block is seeing the outer lexical `my $a`, and not the package variable `our $a`.

This is fixable:

```
eval: use strict; my $a = ""; my @a = sort { $b->[0] <=> (our $a)->[0] } ([1], [2]); \@a
[ [ '2' ], [ '1' ] ]
```

**Comment by Grinnz** [comment]
This is also the reason for this policy: https://metacpan.org/pod/Perl::Critic::Policy::Community::DollarAB
