### ISSUE TITLE
Repurposing redundant parentheses

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#19043]
The phrase ```[(...)]``` is always equivalent to ```[...]``` making the inner parentheses redundant.  Please repurpose them to allow  ```[qw(...)]``` to be expressed more succinctly as ```[(...)]```.  Thanks!

**Comment by haarg** [comment]
Parenthesis can be inserted many places where they are redundant to allow clarifying precedence. This is by design. The proposed change will not happen.
