### ISSUE TITLE
Some words work for a * parameter, some do not

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#19060]
Some words work for a * parameter, some do not:

```
    use strict;
    sub V(*) {}
    V(aaa);  # OK
    V(sub);  # Illegal declaration of anonymous subroutine
    V(s);    # Substitution replacement not terminated
```

**Comment by Grinnz** [comment]
This has nothing to do with prototypes but is the normal priority of bareword parsing without strict 'subs' active to prevent bareword strings. You can see the same errors by just ending your program with 'sub' or 's'

**Comment by Leont** [comment]
Philip, this tracker is for bugs in perl, it's not a help channel. Can you please stop filing issues like this.
