### ISSUE TITLE
[doc] sprintf does not mention about floating point bug.

### ISSUE THREAD

**Issue by KES777** [Perl/perl5#19065]
**Where**
https://perldoc.pl/functions/sprintf

**Description**
At the documentation we see that we can use `sprintf` to round numbers, but I think this is worth to mention about `floating point` "bug", which does not belongs to perl itself. So perl users and newcomers will be aware of it.

I do not think this floating point bug should be described here, but a link to good blogpost or another page with good description would be enough

Related links:
https://www.perlmonks.org/?node_id=93305
https://stackoverflow.com/a/994779/4632019

**Comment by tonycoz** [comment]
You haven't described a bug.

There is a limitation that a base-2 floating point implementation can't represent every decimal number, but it's part of the design limitation of the implementation.

A base-3 floating point implementation wouldn't be able to represent 1/2 accurately, just as decimal can't represent 1/3 accurately without a repeating decimal notation.

The limitations of the current  implementation is described in perlnumber.pod

**Comment by KES777** [comment]
I suggest to extend this:
```
Returns a string formatted by the usual printf conventions of the C library function sprintf. 
See below for more details and see sprintf(3) or printf(3) on your system for an explanation of the general principles.
```

By this:
```
Also please read `perlnumber` about most fundamental restriction for "native" floats
```

**Comment by jkeenan** [comment]
> I suggest to extend this:
> 
> ```
> Returns a string formatted by the usual printf conventions of the C library function sprintf. 
> See below for more details and see sprintf(3) or printf(3) on your system for an explanation of the general principles.
> ```
> 
> By this:
> 
> ```
> Also please read `perlnumber` about most fundamental restriction for "native" floats
> ```

No one has supported this idea since it was originally made approx. three weeks ago.  On the basis of "motion fails for lack of a second," I recommend that this ticket be closed.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> > I suggest to extend this:
> > ```
> > Returns a string formatted by the usual printf conventions of the C library function sprintf. 
> > See below for more details and see sprintf(3) or printf(3) on your system for an explanation of the general principles.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > By this:
> > ```
> > Also please read `perlnumber` about most fundamental restriction for "native" floats
> > ```
> 
> No one has supported this idea since it was originally made approx. three weeks ago. On the basis of "motion fails for lack of a second," I recommend that this ticket be closed.


Closing.
