### ISSUE TITLE
use strict permits arithmetic on qr()

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#19070]
Please **warn** about attempts to do arithmetic on **qr()** when **strict** is in use ?
```
use strict;
use Data::Dump qw(dump);
print dump [~ qr/a/, qr/a/ + qr/b/, qr/a/ - qr/b/, qr/a/ % qr/b/, qr/a/ / qr/b/, qr/a/ * qr/b/];
[
  18446649406790479663,
  189333838184576,
  -128288,
  150384,
  1.00000000000051,
  8.96182576038369e+27,
]
```

**Comment by Corion** [comment]
This is not a bug. `qr//` returns a reference, and references evaluate to a number when used with a numerical operator.

The intended result can be achieved easily using the `overload` pragma:

```perl
#!perl
use strict;
use warnings;

{
    package Regexp;
    use overload '*', sub {
        die 'no mul!';
    }
}
print ref qr/foo/;
my $q = qr/foo/;
print 1 if $q * $q;

```
This could be wrapped into a new CPAN package, maybe `warnings::operations` or something like that.

**Comment by Leont** [comment]
Closed, as this issue tracker still isn't a help channel
