### ISSUE TITLE
Warn of numeric comparison with character constant at compile time not run time.

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#19084]
Please could Perl warn, under strict mode, of all attempts to do numeric comparisons with character constants at compile time rather than at runtime as currently appears to be the case?  Thanks!
```
use strict;
my $a = 1;
die if $a < 'h'; # Argument "h" isn't numeric in numeric lt (<)
```

**Comment by Corion** [comment]
The code as posted by you does warn neither with nor without `use strict` in play.

I can only guess that you intended to wish that `use warnings` would have this effect.

Once again, you have posted not what is a bug report but what more seems to be a feature request. Please consider revisiting the answers you received to your previous posts and follow the RFC process for such changes.

Changing the process how Perl produces warnings from runtime to compile time is hard and would involve deep changes to the optimizer.

Your question is not a bug report.
