### ISSUE TITLE
Calculation result differs for 5.22 and 5.26

### ISSUE THREAD

**Issue by masics** [Perl/perl5#19094]
When running following command: 
`print ((1<<64)-1);`

The result differs:
Perl 5.22: 0
Perl 5.26: -1

**Comment by jkeenan** [comment]
> When running following command:
> `print ((1<<64)-1);`
> 
> The result differs:
> Perl 5.22: 0
> Perl 5.26: -1

Perhaps deliberately so.  Bisection with this invocation ...
```
$ perl Porting/bisect.pl --start=v5.22.0 --end=v5.34.0 -e '$var  = ((1<<64)-1); die if $var != 0;'
```
... brings us to:
```
commit b3498293409c7838d6786f7e8997ff0391135774
Author:     Jarkko Hietaniemi <jhi@iki.fi>
AuthorDate: Sat Jun 27 22:51:38 2015 -0400
Commit:     Jarkko Hietaniemi <jhi@iki.fi>
CommitDate: Sun Jun 28 16:15:19 2015 -0400

    Define left/right shift by negative to mean the reverse shift
    
    Coverity CIDs 104765 and 104766
    
    While at it, also define shifting by more than wordsize in bits to be
    zero, except that undef 'use integer' (use IVs) right overshift for
    negative shiftees means -1.  (This is another corner where C leaves
    things undefined.  A common behavior is "shift by modulo worbits",
    so that e.g. 1 >> 64 == 1 >> (64 % 64) == 1 >> 0, but this is completely
    accidental.)  (Coverity didn't flag this, harder to detect statically.)
    
    Discussion thread at
    http://www.nntp.perl.org/group/perl.perl5.porters/2015/06/msg228842.html
```

**Comment by Leont** [comment]
This does not look like a bug to me. `-1` is exactly the answer I would expect/hope to get.

**Comment by masics** [comment]
The change in behaviour breaks the programs when changing the version.
Also, from the commit description, `1<<64 == 1<<(64%64)==1<<0==1` while the new versions return `0`.

**Comment by richardleach** [comment]
Blead and at least 5.36 return `-1` as well. This seems to conform with what's documented in https://perldoc.perl.org/perlop#Shift-Operators: `Shifting by more bits than the size of the integers means most of the time zero (all bits fall off)`.

Are we happy with this as being the desired behaviour and an unfortuate change from older perls, or is there something to keep this issue open for?

**Comment by sisyphus** [comment]
I don't see any need to keep this ticket open, but the documentation to which @richardleach has just linked seems sloppy (and wrong) to me.
I'm thinking that:
```
Shifting by more bits than the size of the integers means most of the time zero (all bits fall off), except that under use integer right overshifting a negative shiftee results in -1
```
should be rewritten as something like:
```
Shifting by more bits than ivsize-1 results in zero (all bits fall off) except that, under use integer, right overshifting a negative shiftee results in -1
```
And one of the given examples:
```
print 20 << 40;  # 5120 on 32-bit machines,
```
should be changed to:
```
print 20 << 40;  # 0 on 32-bit machines,
```

**Comment by jkeenan** [comment]
> I don't see any need to keep this ticket open, but the documentation to which @richardleach has just linked seems sloppy (and wrong) to me. I'm thinking that:
> 

@sisyphus could you provide a pull request that would improve that documentation?

Closing this ticket.
