### ISSUE TITLE
Problem with integer in GCC 12.0.0 20210826

### ISSUE THREAD

**Issue by Jamaika1** [Perl/perl5#19098]
```
utf8.c: In function 'Perl__utf8n_to_uvchr_msgs_helper':
utf8.h:631:36: warning: overflow in conversion from 'int' to 'UV' {aka 'long long unsigned int'} changes value from '(((void)(1 || (unsigned int)((((void)(1 || ((_assert((const char *)"( (sizeof((((U8) (0xFF << 6)) & 0xB0)) == 1) || ((U64) (((((U8) (0xFF << 6)) & 0xB0)) | 0)) == ((U8)((((U8) (0xFF << 6)) & 0xB0))))", (const char *)"utf8.c", 1647), 0)) != 0), 128)) | 0) == (((void)(1 || ((_assert((const char *)"( (sizeof((((U8) (0xFF << 6)) & 0xB0)) == 1) || ((U64) (((((U8) (0xFF << 6)) & 0xB0)) | 0)) == ((U8)((((U8) (0xFF << 6)) & 0xB0))))", (const char *)"utf8.c", 1647), 0)) != 0), 128)) || ((_assert((const char *)"( (sizeof(((void) ((!!(( (sizeof((((U8) (0xFF << 6)) & 0xB0)) == 1) || ((U64) (((((U8) (0xFF << 6)) & 0xB0)) | 0)) == ((U8)((((U8) (0xFF << 6)) & 0xB0)))))) || (_assert(\"( (sizeof((((U8) (0xFF << 6)) & 0xB0)) == 1) || ((U64) (((((U8) (0xFF << 6)) & 0xB0)) | 0)) == ((U8)((((U8) (0xFF << 6)) & 0xB0))))\",\"utf8.c\",1647),0)), ((U8) (((((U8) (0xFF << 6)) & 0xB0)) | 0)))) == 1) || ((U64) ((((void) ((!!(( (sizeof((((U8) (0xFF << 6)) & 0xB0)) == 1) || ((U64) (((((U8) (0xFF << 6)) & 0xB0)) | 0)) == ((U8)((((U8) (0xFF << 6)) & 0xB0)))))) || (_assert(\"( (sizeof((((U8) (0xFF << 6)) & 0xB0)) == 1) || ((U64) (((((U8) (0xFF << 6)) & 0xB0)) | 0)) == ((U8)((((U8) (0xFF << 6)) & 0xB0))))\",\"utf8.c\",1647),0)), ((U8) (((((U8) (0xFF << 6)) & 0xB0)) | 0)))) | 0)) == ((U8)(((void) ((!!(( (sizeof((((U8) (0xFF << 6)) & 0xB0)) == 1) || ((U64) (((((U8) (0xFF << 6)) & 0xB0)) | 0)) == ((U8)((((U8) (0xFF << 6)) & 0xB0)))))) || (_assert(\"( (sizeof((((U8) (0xFF << 6)) & 0xB0)) == 1) || ((U64) (((((U8) (0xFF << 6)) & 0xB0)) | 0)) == ((U8)((((U8) (0xFF << 6)) & 0xB0))))\",\"utf8.c\",1647),0)), ((U8) (((((U8) (0xFF << 6)) & 0xB0)) | 0))))))", (const char *)"utf8.c", 1646), 0)) != 0), (((void)(1 || ((_assert((const char *)"( (sizeof((((U8) (0xFF << 6)) & 0xB0)) == 1) || ((U64) (((((U8) (0xFF << 6)) & 0xB0)) | 0)) == ((U8)((((U8) (0xFF << 6)) & 0xB0))))", (const char *)"utf8.c", 1647), 0)) != 0), 128)))) & 63' to '0' [-Woverflow]
  631 |                                    | ((NATIVE_UTF8_TO_I8(new))                 \
      |                                    ^
utf8.c:1646:26: note: in expansion of macro 'UTF8_ACCUMULATE'
 1646 |                 min_uv = UTF8_ACCUMULATE(min_uv,
      |                          ^~~~~~~~~~~~~~~
```

**Comment by jkeenan** [comment]
> ```
> utf8.c: In function 'Perl__utf8n_to_uvchr_msgs_helper':
> utf8.h:631:36: warning: overflow in conversion from 'int' to 'UV' {aka 'long long unsigned int'} changes value from '(((void)(1 || (unsigned int)((((void)(1 || ((_assert((const char *)"( (sizeof((((U8) (0xFF << 6)) & 0xB0)) == 1) || ((U64) (((((U8) (0xFF << 6)) & 0xB0)) | 0)) == ((U8)((((U8) (0xFF << 6)) & 0xB0))))", (const char *)"utf8.c", 1647), 0)) != 0), 128)) | 0) == (((void)(1 || ((_assert((const char *)"( (sizeof((((U8) (0xFF << 6)) & 0xB0)) == 1) || ((U64) (((((U8) (0xFF << 6)) & 0xB0)) | 0)) == ((U8)((((U8) (0xFF << 6)) & 0xB0))))", (const char *)"utf8.c", 1647), 0)) != 0), 128)) || ((_assert((const char *)"( (sizeof(((void) ((!!(( (sizeof((((U8) (0xFF << 6)) & 0xB0)) == 1) || ((U64) (((((U8) (0xFF << 6)) & 0xB0)) | 0)) == ((U8)((((U8) (0xFF << 6)) & 0xB0)))))) || (_assert(\"( (sizeof((((U8) (0xFF << 6)) & 0xB0)) == 1) || ((U64) (((((U8) (0xFF << 6)) & 0xB0)) | 0)) == ((U8)((((U8) (0xFF << 6)) & 0xB0))))\",\"utf8.c\",1647),0)), ((U8) (((((U8) (0xFF << 6)) & 0xB0)) | 0)))) == 1) || ((U64) ((((void) ((!!(( (sizeof((((U8) (0xFF << 6)) & 0xB0)) == 1) || ((U64) (((((U8) (0xFF << 6)) & 0xB0)) | 0)) == ((U8)((((U8) (0xFF << 6)) & 0xB0)))))) || (_assert(\"( (sizeof((((U8) (0xFF << 6)) & 0xB0)) == 1) || ((U64) (((((U8) (0xFF << 6)) & 0xB0)) | 0)) == ((U8)((((U8) (0xFF << 6)) & 0xB0))))\",\"utf8.c\",1647),0)), ((U8) (((((U8) (0xFF << 6)) & 0xB0)) | 0)))) | 0)) == ((U8)(((void) ((!!(( (sizeof((((U8) (0xFF << 6)) & 0xB0)) == 1) || ((U64) (((((U8) (0xFF << 6)) & 0xB0)) | 0)) == ((U8)((((U8) (0xFF << 6)) & 0xB0)))))) || (_assert(\"( (sizeof((((U8) (0xFF << 6)) & 0xB0)) == 1) || ((U64) (((((U8) (0xFF << 6)) & 0xB0)) | 0)) == ((U8)((((U8) (0xFF << 6)) & 0xB0))))\",\"utf8.c\",1647),0)), ((U8) (((((U8) (0xFF << 6)) & 0xB0)) | 0))))))", (const char *)"utf8.c", 1646), 0)) != 0), (((void)(1 || ((_assert((const char *)"( (sizeof((((U8) (0xFF << 6)) & 0xB0)) == 1) || ((U64) (((((U8) (0xFF << 6)) & 0xB0)) | 0)) == ((U8)((((U8) (0xFF << 6)) & 0xB0))))", (const char *)"utf8.c", 1647), 0)) != 0), 128)))) & 63' to '0' [-Woverflow]
>   631 |                                    | ((NATIVE_UTF8_TO_I8(new))                 \
>       |                                    ^
> utf8.c:1646:26: note: in expansion of macro 'UTF8_ACCUMULATE'
>  1646 |                 min_uv = UTF8_ACCUMULATE(min_uv,
>       |                          ^~~~~~~~~~~~~~~
> ```

Can you supply some context for this?

What operating system were you on?

What version of perl were you using?  (*e.g.,* `perl -V`)

What were you doing when you observed these warnings?  Compiling `perl` itself?  A CPAN module?  Your own XS code?

**Comment by Jamaika1** [comment]
I use 64bit http://msystem.waw.pl/x265/mingw-gcc1200-20210826.7z
gcc.exe -std=gnu17 -ftree-vectorize -g0 -O3 -fPIC -DWIN32 -DPERL_CORE -DPERL_IS_MINIPERL -DUSE_ITHREADS -DDEBUGGING -c utf8.c -o utf8.o
I use version perl5 5.35.4-fcf33192
Let me add that gcc was used with the mingw::mutex plugins 
https://github.com/Jamaika1/mingw_std_threads

**Comment by hvds** [comment]
If we reformat the expansion, and elide the (always constant) arguments to the `_assert` calls, we get:
```
utf8.h:631:36: warning: overflow in conversion from 'int' to 'UV'
{aka 'long long unsigned int'} changes value from
'((  
    (void)(
        1 || (unsigned int)(
            ((
                (void)(1 || ((_assert(...), 0)) != 0),
                128
            )) | 0
        ) == ((
            (void)(1 || ((_assert(...), 0)) != 0),
            128
        )) || ((_assert(...), 0)) != 0
    ),  
    ((  
        (void)(1 || ((_assert(...), 0)) != 0),
        128
    ))
)) & 63'
to '0' [-Woverflow]
```

I don't see anything to complain about here (except a bunch of duplication): there's no overflow in the eventual `128 & 63`, and I don't see anything inside the `(void)` calculations that could possibly overflow either.

I've only just understood that gcc-12 hasn't actually had a release yet, so it belatedly occurs to me that maybe we shouldn't be spending too much effort on new warnings from unreleased compilers.

**Comment by Jamaika1** [comment]
Thank you for your answer. This warming also occurs in release version gcc 11.2.0. I understand that the C language has strange messages at times. 
Maybe I would report bug for gcc. Unfortunately, this isn't possible on gihub. I am not going to register on other forums.

**Comment by hvds** [comment]
Thanks @Jamaika1, I had tried to build latest gcc from git and failed, now trying to build 11.2.0 which seems to be going better.

**Comment by hvds** [comment]
Here's a form that I hope will make more sense to the gcc team as a bug report:
```
#include <assert.h>

typedef unsigned long ulong;
typedef unsigned char uchar;

#define FIT8(c) assert(((sizeof(c) == 1) || (((ulong) (c)) >> 8) == 0))
#define BE8(c) (FIT8(c), ((uchar) (c)))
#define NUM(c) ((c) | 0)

#define TESTER(old, new) ((((ulong)(old)) << 6) | (((uchar) NUM(new)) & 0x3f))

ulong tester(ulong ul) {
    return TESTER(ul, BE8(0x81));
}
```

I've already removed some asserts that don't affect it, but from this point gcc stops complaining if:
- `NUM(new)` is replaced with `new` in `TESTER`, equivalent to removing the `ASSERT_NOT_PTR()` around the argument in `NATIVE_TO_LATIN1`
- `FIT8(c),` is removed from `BE8`, equivalent to removing the `__ASSERT_(FITS_IN_8_BITS(ch))` from `I8_TO_NATIVE_UTF8`

(@khwilliamson FYI)

**Comment by hvds** [comment]
Now reported as [gcc bug 102291](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102291).

Initial response appears to confirm that it's a bug and proposes this simpler case that wrongly warns even in much earlier versions of gcc:
```
  (ulong) ((((uchar) (((void)0, ((uchar) (0x80)))|0)) & 0x3f))
/*                     ^^^^^^^^                  ^^
                       assert()            ASSERT_NOT_PTR
 */ 
```

It also relates it to another issue first reported in 2007 and still open, suggesting it may not get fixed any time soon.

@khwilliamson Unless you have another idea, I think in `NATIVE_TO_LATIN1` and similar macros we should do one of:
* drop the `FITS_IN_8_BITS` assertion
* drop the `ASSERT_NOT_PTR`
* use a pragma to disable `-Woverflow`

Thoughts?

**Comment by khwilliamson** [comment]
I pushed e72852772d35fa07c6f4def68643512939de4443 to remove the ASSERT_NOT_PTR,  I realized (face palm) that if something fits in 8 bits, it can't be a C pointer.  So the second check was useless.

**Comment by khwilliamson** [comment]
Or rather it can't be a C pointer except to extremely low memory, which we aren't ever going to access.

Please check if this fixes the problem

**Comment by hvds** [comment]
> Or rather it can't be a C pointer except to extremely low memory, which we aren't ever going to access.

Well it's probably platform-specific (except for a NULL pointer), but it certainly implies the assert offers very little additional value.

> Please check if this fixes the problem

Looks fixed to me, thanks.
