### ISSUE TITLE
gcc12: new build-time warnings associated with 1604cfb027

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#19100]
In https://github.com/Perl/perl5/issues/19098, user @Jamaika1 reports C-level warnings emanating from utf8.c and utf8.h using a devel version of gcc12.  Context is sparse; I've requested more detail.

That prompted me to install a devel version of gcc12 on FreeBSD12 (one slightly earlier than used by reporter).  I encountered build-time warnings that I did not encounter when building on the same platform with gcc10.
```
$ gcc12 --version | head -n 2
gcc12 (FreeBSD Ports Collection) 12.0.0 20210822 (experimental)
Copyright (C) 2021 Free Software Foundation, Inc.
```
I then built Perl 5 blead with `sh ./Configure -des -Dusedevel -Duseithreads -Dcc=gcc12` and parsed the build log for C-level warnings:
```
$ report-build-warnings 756f0910f9.freebsd.gcc12.threaded.maketp.output.txt.gz 
File:  756f0910f9.freebsd.gcc12.threaded.maketp.output.txt.gz

  Warray-bounds                              6
  Wc++-compat                              240
  Wempty-body                                6
  Wmaybe-uninitialized                       2
  Wsign-compare                              4
  Wtype-limits                               2
```
The last previous version of gcc I've build perl with on this machine was gcc10.  At that time I got these build-time warnings:
```
$ report-build-warnings f72873660d.freebsd.gcc10.maketp.output.txt.gz
File:  f72873660d.freebsd.gcc10.maketp.output.txt.gz

  Wc++-compat                              240
  Wempty-body                                6
  Wsign-compare                              4
  Wtype-limits                               2
```
So the `Warraybounds` warnings (6) and the `Wmaybe-uninitialized` warnings (2) are new in either gcc11 or gcc12; the others appear to have existed at least from gcc10.

The `Warraybounds` warnings are these:
```
  {
    char   => 9,
    group  => "Warray-bounds",
    line   => 461,
    source => "hv.h",
    text   => "array subscript 0 is outside array bounds of 'HEK[768614336404564650]' {aka 'struct hek[768614336404564650]'}",
  },
  {
    char   => 9,
    group  => "Warray-bounds",
    line   => 461,
    source => "hv.h",
    text   => "array subscript 0 is outside array bounds of 'HEK[768614336404564650]' {aka 'struct hek[768614336404564650]'}",
  },
...
  {
    char   => 9,
    group  => "Warray-bounds",
    line   => 461,
    source => "hv.h",
    text   => "array subscript 0 is outside array bounds of 'HEK[768614336404564650]' {aka 'struct hek[768614336404564650]'}",
  },
  {
    char   => 9,
    group  => "Warray-bounds",
    line   => 461,
    source => "hv.h",
    text   => "array subscript 0 is outside array bounds of 'HEK[768614336404564650]' {aka 'struct hek[768614336404564650]'}",
  },
  {
    char   => 9,
    group  => "Warray-bounds",
    line   => 461,
    source => "hv.h",
    text   => "array subscript 0 is outside array bounds of 'HEK[768614336404564650]' {aka 'struct hek[768614336404564650]'}",
  },
  {
    char   => 9,
    group  => "Warray-bounds",
    line   => 461,
    source => "hv.h",
    text   => "array subscript 0 is outside array bounds of 'HEK[768614336404564650]' {aka 'struct hek[768614336404564650]'}",
  },
```
Line 461 in `hv.h` was last touched in this commit:
```
commit 1604cfb0273418ed479719f39def5ee559bffda2
Author:     Michael G. Schwern <schwern@pobox.com>
AuthorDate: Mon Dec 28 18:04:52 2020 -0800
Commit:     Karl Williamson <khw@cpan.org>
CommitDate: Sun Jan 17 09:18:15 2021 -0700

    style: Detabify indentation of the C code maintained by the core.
    
    This just detabifies to get rid of the mixed tab/space indentation.
    
    Applying consistent indentation and dealing with other tabs are another issue.
    
    Done with `expand -i`.
    
    * vutil.* left alone, it's part of version.
    * Left regen managed files alone for now.
```
Relevant lines:
```
468 #define hv_exists_ent(hv, keysv, hash)                  \
469     cBOOL(hv_common((hv), (keysv), NULL, 0, 0, HV_FETCH_ISEXISTS, 0, (hash)))
470 #define hv_fetch_ent(hv, keysv, lval, hash)             \
471     ((HE *) hv_common((hv), (keysv), NULL, 0, 0,            \
472                       ((lval) ? HV_FETCH_LVALUE : 0), NULL, (hash)))
```

The `Wmaybe-uninitialized` warnings are these:
```
  {
    char   => 21,
    group  => "Wmaybe-uninitialized",
    line   => 390,
    source => "thread.h",
    text   => "'my_perl' may be used uninitialized",
  },
  {
    char   => 21,
    group  => "Wmaybe-uninitialized",
    line   => 390,
    source => "thread.h",
    text   => "'my_perl' may be used uninitialized",
  },
```
Line 390 in `thread.h` was also last touched in 1604cfb0273418ed479719f39def5ee559bffda2, committed to blead in January of this year.

Relevant lines:
```
386 #ifndef PERL_SET_CONTEXT
387 #  define PERL_SET_CONTEXT(t) \
388     STMT_START {                        \
389         int _eC_;                       \
390         if ((_eC_ = pthread_setspecific(PL_thr_key, (void *)(t))))  \
391             Perl_croak_nocontext("panic: pthread_setspecific (%d) [%s:%d]", \
392                                  _eC_, __FILE__, __LINE__); \
393     } STMT_END
394 #endif /* PERL_SET_CONTEXT */
```

But I don't see the `Woverflow` build-time warnings reported in https://github.com/Perl/perl5/issues/19098.

@schwern, @khwilliamson or anyone, can you take a look?

Thank you very much.
Jim Keenan

**Comment by Leont** [comment]
> Line 461 in hv.h was last touched in this commit:

I think you need to add a `-w` to your git blames, that commit was only a whitespace change. That line was last meaningfully changed in d1db91c62f7 from 2005.

**Comment by hvds** [comment]
1604cfb027 was (mostly) a whitespace-only commit; to see the real last change for these you need something like `git blame -w`.

For the "may be used uninitialized", the issue is not with the macro itself, but how it is being used - the warning says we may be invoking this macro before the `my_perl` structure is initialized.

In this case, my best guess is that it is complaining about the attempt to invoke `Perl_croak_nocontext` within `MUTEX_INIT` invoked via `PERL_SYS_INIT3` in `main()` - `MUTEX_INIT` should probably be using a safer croak that checks `my_perl`, and takes some alternative action if it isn't set up (possibly just `exit(1)`); we should also be ensuring we set `my_perl` back to 0 when we free it during destruction.

**Comment by jkeenan** [comment]
Okay, so the emergence of these warnings is not so much a question of the particular commit as it is of the fact that `gcc12` finds the C-coding problematic.  The practical question remains:  How can we silence these warnings?

**Comment by Leont** [comment]
>  The practical question remains: How can we silence these warnings?

It's puzzling. That line doesn't contain any array subscripting, and does deal with a `struct hek`.

That `768614336404564650` equals `0xAAAAAAAAAAAAAAA`, that's probably not a coincidence but I'm not sure what it means

**Comment by hvds** [comment]
@jkeenan could you try the following?

- cd to your perl source directory
- make sure you have at least configured to build with this gcc (so we have cflags)
- write the following to a file `test.c`:
```
#include "perl.h"

void test_hek(HEK *hek) {
    (void)share_hek_hek(hek);
}
```
- run the following:
```
`sh cflags test.o` -E test.c | perl -nle 'next unless /^void test_hek/ .. 0; print unless /^#/'
```

This should show what the preprocessor expands it too. For me it shows:
```
% `sh cflags test.o` -E test.c | perl -nle 'next unless /^void test_hek/ .. 0; print unless /^#/'
void test_hek(HEK *hek) {
 (void)(++(((struct shared_he *)(((char *)hek) - 
      __builtin_offsetof (
      struct shared_he
      , 
      shared_he_hek
      )
      )) ->shared_he_he.he_valu.hent_refcount), hek);
}
% 
```

It seems plausible that gcc treats `__builtin_offsetof` as indistinguishable from array subscripting for the purposes of this warning, but it would be worth confirming whether you get something similar to the above.

**Comment by jkeenan** [comment]
```
$ sh ./Configure -des -Dusedevel -Duseithreadds -Dcc=gcc12
...

$ ls -l cflags
-rwxr-xr-x  1 jkeenan  jkeenan  2796 Sep  7 11:00 cflags

$ `sh cflags test.o` -E test.c | perl -nle 'next unless /^void test_hek/ .. 0; print unless /^#/'
void test_hek(HEK *hek) {
    (void)(++(((struct shared_he *)(((char *)hek) - 
         __builtin_offsetof (
         struct shared_he
         , 
         shared_he_hek
         )
         )) ->shared_he_he.he_valu.hent_refcount), hek);
}

$ `sh cflags test.o` -E test.c | perl -nle 'next unless /^void test_hek/ .. 0; print unless /^#/' 1>$P5P_DIR/myhvtest.txt 2>&1

$ cd $P5P_DIR

$ diff -w myhvtest.txt hvhvtest.txt
$ [no output]
```
Modulo the whitespace caused by redirecting output to a file, the output is what you expected.

**Comment by hvds** [comment]
Ok; it's a shame it isn't giving more contextual information - if you could group these `Warray-bounds` to count how many appear for each individual source file, that would give an additional clue. (To avoid having to do a complete non-parallelizing build for that, consider doing a full build and then repeatedly remove and rebuild one of the object files corresponding to those listed below, eg: `rm hv.o ; make hv.o`.)

Looking at the references to `share_hek_hek` to group similar calls, I get:
```
./hv.c:    (void)share_hek_hek(shared);
./hv.c:    (void)share_hek_hek(shared);
./op.c:    (void)share_hek_hek(hek);
./scope.c: (void)share_hek_hek(hek);

./sv.c:    SvPV_set(dsv, HEK_KEY(share_hek_hek(SvSHARED_HEK_FROM_PV(SvPVX_const(ssv)))));
./sv.c:    SvPV_set(sv, (char *)HEK_KEY(share_hek_hek(hek)));
./sv.c:    SvPV_set(sv, (char *)HEK_KEY(share_hek_hek(hek)));
./scope.c: CvNAME_HEK_set(*svp, share_hek_hek(hek));
./pad.c:   CvNAME_HEK_set( cv , share_hek_hek(CvNAME_HEK(proto)));

#ifndef USE_ITHREADS
./hv.c:    HeKEY_hek(entry) = share_hek_hek(chain->refcounted_he_hek);

#ifdef PERL_ANY_COW
./sv.c:    new_pv = HEK_KEY(share_hek_hek(SvSHARED_HEK_FROM_PV(SvPVX_const(ssv))));
```
.. so to get 6 warnings, perhaps it is not objecting to those in void context (assuming your build sets PERL_ANY_COW and not USE_ITHREADS). That would imply 4 warnings from sv.c, and one each from scope.c and pad.c.

**Comment by hvds** [comment]
@jkeenan For the other warning, please could you check if the branch [safe-croak](https://github.com/Perl/perl5/tree/hv/safe-croak) shuts it up?

@Leont @tonycoz do one of you guys know if it would be possible/safe to write `choke_nocontext` (92439015e0) to fall back to libc fprintf, perhaps by putting it in its own file along with some `#undef fprintf` etc?

**Comment by jkeenan** [comment]
> Ok; it's a shame it isn't giving more contextual information - if you could group these `Warray-bounds` to count how many appear for each individual source file, that would give an additional clue. (To avoid having to do a complete non-parallelizing build for that, consider doing a full build and then repeatedly remove and rebuild one of the object files corresponding to those listed below, eg: `rm hv.o ; make hv.o`.)
> 
> Looking at the references to `share_hek_hek` to group similar calls, I get:
> 
> ```
> ./hv.c:    (void)share_hek_hek(shared);
> ./hv.c:    (void)share_hek_hek(shared);
> ./op.c:    (void)share_hek_hek(hek);
> ./scope.c: (void)share_hek_hek(hek);
> 
> ./sv.c:    SvPV_set(dsv, HEK_KEY(share_hek_hek(SvSHARED_HEK_FROM_PV(SvPVX_const(ssv)))));
> ./sv.c:    SvPV_set(sv, (char *)HEK_KEY(share_hek_hek(hek)));
> ./sv.c:    SvPV_set(sv, (char *)HEK_KEY(share_hek_hek(hek)));
> ./scope.c: CvNAME_HEK_set(*svp, share_hek_hek(hek));
> ./pad.c:   CvNAME_HEK_set( cv , share_hek_hek(CvNAME_HEK(proto)));
> 
> #ifndef USE_ITHREADS
> ./hv.c:    HeKEY_hek(entry) = share_hek_hek(chain->refcounted_he_hek);
> 
> #ifdef PERL_ANY_COW
> ./sv.c:    new_pv = HEK_KEY(share_hek_hek(SvSHARED_HEK_FROM_PV(SvPVX_const(ssv))));
> ```
> 
> .. so to get 6 warnings, perhaps it is not objecting to those in void context (assuming your build sets PERL_ANY_COW and not USE_ITHREADS). That would imply 4 warnings from sv.c, and one each from scope.c and pad.c.

Here's `perl -V` output:
```
$ cat perl-V-freebsd12-gcc12.txt 
Summary of my perl5 (revision 5 version 35 subversion 4) configuration:
  Commit id: 034242a8a539b024648b18318271eabddf40ca48
  Platform:
    osname=freebsd                          archname=amd64-freebsd
    osvers=12.2-stable
    uname='freebsd perlmonger.nycbug.org 12.2-stable freebsd 12.2-stable r368982 generic amd64 '
    config_args='-des -Dusedevel -Dcc=gcc12'
    hint=recommended                        use64bitall=define
    useposix=true                           uselongdouble=undef
    d_sigaction=define                      usemymalloc=n
    useithreads=undef                       default_inc_excludes_dot=define
    usemultiplicity=undef
    use64bitint=define
  Compiler:
    cc='gcc12'
    ccflags ='-DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='-DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='12.0.0 20210822 (experimental)'
    gccosandvers=''                         longdblkind=3
    intsize=4                               ivtype='long'
    longsize=8                              ivsize=8
    ptrsize=8                               nvtype='double'
    doublesize=8                            nvsize=8
    byteorder=12345678                      Off_t='off_t'
    doublekind=3                            lseeksize=8
    d_longlong=define                       alignbytes=8
    longlongsize=8                          prototype=define
    d_longdbl=define
    longdblsize=16
  Linker and Libraries:
    ld='gcc12'
    ldflags ='-Wl,-E  -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/lib /usr/local/lib
    libs=-lpthread -lgdbm -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=                                   libperl=libperl.a
    so=so                                   gnulibc_version=''
    useshrplib=false
  Dynamic Linking:
    dlsrc=dl_dlopen.xs                      ccdlflags=' '
    dlext=so                                cccdlflags='-DPIC -fPIC'
    d_dlsymun=undef
    lddlflags='-shared  -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES                               USE_LARGE_FILES
    PERLIO_LAYERS                           USE_LOCALE
    PERL_COPY_ON_WRITE                      USE_LOCALE_COLLATE
    PERL_DONT_CREATE_GVSV                   USE_LOCALE_CTYPE
    PERL_MALLOC_WRAP                        USE_LOCALE_NUMERIC
    PERL_OP_PARENT                          USE_LOCALE_TIME
    PERL_PRESERVE_IVUV                      USE_PERLIO
    PERL_USE_DEVEL                          USE_PERL_ATOF
    USE_64_BIT_ALL
    USE_64_BIT_INT
  Built under freebsd
  Compiled at Sep  8 2021 22:00:44
  %ENV:
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/5.35.4/amd64-freebsd
    /usr/local/lib/perl5/site_perl/5.35.4
    /usr/local/lib/perl5/5.35.4/amd64-freebsd
    /usr/local/lib/perl5/5.35.4
```
I've sent you the full `make` output via email.

Thanks.
jimk

**Comment by hvds** [comment]
> I've sent you the full `make` output via email.

Thanks Jim; quite different from what I had anticipated, it's actually warning about only two invocations, pad.c:S_cv_clone (twice), and op.c:Perl_newMYSUB (four times: twice for op.c, twice more for opmini.c).

In both those invocations the arg is derived at some point as `CvNAME_HEK` of a CV (but we take avoiding action if the CV is not `CvNAMED`, so we're not dealing with the case where that returns 0).

I'm no closer to understanding what it is actually complaining about, but it might be possible to start trying to create a cut-down testcase that also generates the warning. At this point I wouldn't rule out the possibility that it's a gcc bug.

**Comment by hvds** [comment]
> At this point I wouldn't rule out the possibility that it's a gcc bug.

I was able to build gcc-11.2.0 locally, and it does not warn on this; I'll try reporting it to the gcc team and see what they say.

**Comment by hvds** [comment]
> @jkeenan For the other warning, please could you check if the branch [safe-croak](https://github.com/Perl/perl5/tree/hv/safe-croak) shuts it up?
> 
> @Leont @tonycoz do one of you guys know if it would be possible/safe to write `choke_nocontext` ([9243901](https://github.com/Perl/perl5/commit/92439015e03422c6ca37b9db0dc28823ca61ea78)) to fall back to libc fprintf, perhaps by putting it in its own file along with some `#undef fprintf` etc?

Ok, while I think the mutex-init croak is a bug, it's not actually what is being warned about here. It reduces to this:
```
% gcc-11.2.0 -c -O2 -Wmaybe-uninitialized test.c
test.c: In function 'init':
test.c:15:9: warning: 'my_perl' may be used uninitialized [-Wmaybe-uninitialize]
   15 |         pthread_setspecific(PL_thr_key, PL_current_context);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test.c:10:12: note: by argument 2 of type 'const void *' to 'pthread_setspecific' declared here
   10 | extern int pthread_setspecific (unsigned int key, const void *pointer);
      |            ^~~~~~~~~~~~~~~~~~~
% cat test.c
typedef struct { char c[1]; } PerlInterpreter;
extern PerlInterpreter *PL_curinterp ;

typedef unsigned int perl_key;
extern perl_key PL_thr_key;

extern _Thread_local void *PL_current_context;

extern void *malloc (long unsigned int size);
extern int pthread_setspecific (unsigned int key, const void *pointer);

void perl_alloc(void) {
    PerlInterpreter *my_perl = (PerlInterpreter*)malloc((sizeof(PerlInterpreter)));
    PL_current_context = (void *)my_perl;
    pthread_setspecific(PL_thr_key, PL_current_context);
}   
% 
```

So I suspect this is actually about the nature of thread local storage, which I know nothing about. @nwc10 can you take a look if this could possible be a valid complaint?

**Comment by jkeenan** [comment]
> @jkeenan For the other warning, please could you check if the branch [safe-croak](https://github.com/Perl/perl5/tree/hv/safe-croak) shuts it up?
> 

I am a bit unclear as to what the "it" in the above question is.  In any case, I checked out the hv/safe-croak branch and compiled and built it with the following invocation are results:
```
$ sh ./Configure -des -Dusedevel -Duseithreads -Dcc=gcc12
...
$ report-build-warnings 92439015e0.freebsd.gcc12.threaded.safe-croak.maketp.output.txt.gz 
File:  92439015e0.freebsd.gcc12.threaded.safe-croak.maketp.output.txt.gz

  Warray-bounds                              6
  Wc++-compat                              240
  Wempty-body                                6
  Wmaybe-uninitialized                       2
  Wsign-compare                              4
  Wtype-limits                               2
```
This is the same distribution of build-time warnings as was recorded for the same configuration on blead at 756f0910f9.  So I infer that the changes in this branch do not alleviate the warnings problem.

**Comment by jkeenan** [comment]
> > @jkeenan For the other warning, please could you check if the branch [safe-croak](https://github.com/Perl/perl5/tree/hv/safe-croak) shuts it up?
> > @Leont @tonycoz do one of you guys know if it would be possible/safe to write `choke_nocontext` ([9243901](https://github.com/Perl/perl5/commit/92439015e03422c6ca37b9db0dc28823ca61ea78)) to fall back to libc fprintf, perhaps by putting it in its own file along with some `#undef fprintf` etc?
> 
> Ok, while I think the mutex-init croak is a bug, it's not actually what is being warned about here. It reduces to this:
> 
> ```
> % gcc-11.2.0 -c -O2 -Wmaybe-uninitialized test.c
> test.c: In function 'init':
> test.c:15:9: warning: 'my_perl' may be used uninitialized [-Wmaybe-uninitialize]
>    15 |         pthread_setspecific(PL_thr_key, PL_current_context);
>       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> test.c:10:12: note: by argument 2 of type 'const void *' to 'pthread_setspecific' declared here
>    10 | extern int pthread_setspecific (unsigned int key, const void *pointer);
>       |            ^~~~~~~~~~~~~~~~~~~
> % cat test.c
> typedef struct { char c[1]; } PerlInterpreter;
> extern PerlInterpreter *PL_curinterp ;
> 
> typedef unsigned int perl_key;
> extern perl_key PL_thr_key;
> 
> extern _Thread_local void *PL_current_context;
> 
> extern void *malloc (long unsigned int size);
> extern int pthread_setspecific (unsigned int key, const void *pointer);
> 
> void perl_alloc(void) {
>     PerlInterpreter *my_perl = (PerlInterpreter*)malloc((sizeof(PerlInterpreter)));
>     PL_current_context = (void *)my_perl;
>     pthread_setspecific(PL_thr_key, PL_current_context);
> }   
> % 
> ```
> 
> So I suspect this is actually about the nature of thread local storage, which I know nothing about. @nwc10 can you take a look if this could possible be a valid complaint?

Similar results with gcc12-devel:
```
$ gcc12 -c -O2 -Wmaybe-uninitialized gh-19100-test.c
gh-19100-test.c: In function 'perl_alloc':
gh-19100-test.c:15:5: warning: 'my_perl' may be used uninitialized [-Wmaybe-uninitialized]
   15 |     pthread_setspecific(PL_thr_key, PL_current_context);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gh-19100-test.c:10:12: note: by argument 2 of type 'const void *' to 'pthread_setspecific' declared here
   10 | extern int pthread_setspecific (unsigned int key, const void *pointer);
      |            ^~~~~~~~~~~~~~~~~~~
```

**Comment by nwc10** [comment]
I don't know *that* much about the details of thread local storage, other than it creates a variable which is *roughly* like `static`, but holds a different value on each thread, and (IIRC) is automatically initialised to 0 on new threads. (But in checking up on this there are rules about what you can use as an initialiser on the declaration, so maybe I've not got *all* of this straight - but for all that I've done, I've not used initialisers). Other than that, it's like any other regular storage...

(apart from the enormous pain in the compiler, linker, dynamic loader and possibly even kernel to make it work in the general case...)

Also, I don't have access to any machines with gcc11 on them (let alone a development build of 12), so I started to wonder about building one. Which got me looking at https://gcc.gnu.org/gcc-11/changes.html

> -Wmaybe-uninitialized diagnoses passing pointers or references to uninitialized memory to functions taking const-qualified arguments. 

I think that this explains why the diagnostic message is mentioning `my_perl`, not `PL_current_context`. Does this test case still warn?

```
typedef struct { char c[1]; } PerlInterpreter;
extern PerlInterpreter *PL_curinterp ;

typedef unsigned int perl_key;
extern perl_key PL_thr_key;

extern void *malloc (long unsigned int size);
extern int pthread_setspecific (unsigned int key, const void *pointer);

void perl_alloc(void) {
    PerlInterpreter *my_perl = (PerlInterpreter*)malloc(sizeof(PerlInterpreter));
    pthread_setspecific(PL_thr_key, my_perl);
}
```

If so, I get what's going on, and gcc is (maybe) being overly enthusiastic in its warnings, as (in the original code) we still have a non-`const` pointer to that same memory where we can initialise it before our code reads the value back via `pthread_getspecific`.

But I guess gcc is set in its ways on this warning, so if my reduced test case is correct, then we need to re-order our C code to do (some) initialisation of `my_perl` before passing it to `pthread_setspecific`.

**Comment by Jamaika1** [comment]
Maybe use pthread 3.0.3
https://github.com/GerHobbelt/pthread-win32

**Comment by hvds** [comment]
> I think that this explains why the diagnostic message is mentioning `my_perl`, not `PL_current_context`. Does this test case still warn?

~~No, it seems perfectly happy with `pthread_setspecific(PL_thr_key, my_perl);`, under both gcc-11.2.0 and a build from 20210829 daily snapshot.~~

This was wrong, I'd failed to supply `-Wmaybe-uninitialized` when testing it.

**Comment by hvds** [comment]
> > I think that this explains why the diagnostic message is mentioning `my_perl`, not `PL_current_context`. Does this test case still warn?
> 
> No, it seems perfectly happy with `pthread_setspecific(PL_thr_key, my_perl);`, under both gcc-11.2.0 and a build from 20210829 daily snapshot.

Ah damn, operator error: sorry, it _does_ warn the same way with that change.

**Comment by hvds** [comment]
@nwc10 I've reported it as [gcc bug 102329](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102329), with a bit more detail. I've also belatedly checked the docs for `-Wmaybe-uninitialized` in which I think the relevant part is:

> In addition, passing a pointer (or in C++, a reference) to an uninitialized object to a const-qualified function argument is also diagnosed by this warning. (-Wuninitialized is issued for built-in functions known to read the object.) Annotating the function with attribute access (none) indicates that the argument isn’t used to access the object and avoids the warning (see Common Function Attributes).

So it's nothing to do with the thread-local storage; I don't see a way to avoid it other than by writing to the object before the `pthread_setspecific()` call (writing to any element seems to be enough), or using a pragma to locally disable the warning.

**Comment by hvds** [comment]
The gcc team are suggesting that the correct way to avoid this warning on `pthread_getspecific` is to use a function attribute to hint to gcc that it won't read or write through the pointer, which I think looks like this:
```
extern int pthread_setspecific (unsigned int key, const void *pointer) __attribute__ ((access (none, 2)));
```

But I don't think that's much help to us; accordingly I've proposed #19137 to work around it by writing to an element of the structure.

**Comment by nwc10** [comment]
> But I don't think that's much help to us

Me neither. It is arguably accurate from them - "the bug is that `pthread_setspecific` isn't annotated correctly" but um yes, files in `/usr/incude` don't belong to us, and 20 years after we first made jokes about it, I **still** don't have a working time machine to nip back and file a bug report against the OS while it was still in "testing".

**Comment by hvds** [comment]
> But I don't think that's much help to us; accordingly I've proposed #19137 to work around it by writing to an element of the structure.

This PR now superseded by #19141.

**Comment by jkeenan** [comment]
Today I revisited the status of build-time warnings when we use `gcc12` as the C-compiler.  I got:
```
$ report-build-warnings 58541fd098.freebsd.gcc12.threaded.maketp.output.txt.gz 
File:  58541fd098.freebsd.gcc12.threaded.maketp.output.txt.gz

  Warray-bounds                              6
  Wc++-compat                              240
  Wempty-body                                6
  Wsign-compare                              4
  Wtype-limits                               2
```
This means that the 2 `-Wmaybe-uninitialized` warnings reported [originally](https://github.com/Perl/perl5/issues/19100#issue-989137507) have been cleared up (perhaps by one of @nwc10's commits on Sep 28).

That leaves the 6 `-Warray-bounds` warnings to be addressed in this ticket.  (The warnings in the other 4 categories are from gcc 10 or earlier.)

**Comment by hvds** [comment]
> That leaves the 6 `-Warray-bounds` warnings to be addressed in this ticket. (The warnings in the other 4 categories are from gcc 10 or earlier.)

To recap:
It's actually warning about only two invocations, pad.c:S_cv_clone (twice), and op.c:Perl_newMYSUB (four times: twice for op.c, twice more for opmini.c).

In both those invocations the arg is derived at some point as CvNAME_HEK of a CV (but we take avoiding action if the CV is not CvNAMED, so we're not dealing with the case where that returns 0).

I've no idea what it is actually complaining about, but we do get a bit tricksy with these.

Next step would be to create a cut-down testcase that still generates the warning, to clarify if this is our bug or gcc's. That's not something I'll have time for for at least a week or so.

(@jkeenan It has become rather difficult to find stuff in this ticket with multiple conversations interleaved. We might be better off with a ticket per warning type - or warning source - and use the `build-time-warnings` tag to get the overview of which are still open.)

**Comment by jkeenan** [comment]
On 10/6/21 5:29 AM, Hugo van der Sanden wrote:
[snip]
> 
> Next step would be to create a cut-down testcase that still generates 
> the warning, to clarify if this is our bug or gcc's. That's not 
> something I'll have time for for at least a week or so.
> 

Thanks for your ongoing investigations.

> ***@***.*** <https://github.com/jkeenan> It has become rather difficult to 
> find stuff in this ticket with multiple conversations interleaved. We 
> might be better off with a ticket per warning type - or warning source - 
> and use the |build-time-warnings| tag to get the overview of which are 
> still open.)
> 

Agreed.  We started tracking build-time warnings a couple of years ago 
and it took time to recognize that there are actually **three** cases we 
have to track:

1.	Situations where **we** (P5P contributor or upstream CPAN maintainer) 
change code and warnings are newly emitted from a given C-compiler 
version we had previously used.  (This typically involves just a single 
class of warnings.)

2.	Situations where a new version of a C-compiler is released with 
different criteria for compilation warnings.  (This may involve multiple 
classes of warnings, as is the case in this ticket.)

3.	Situations where we have never compiled on a given OS/C-compiler 
combination.  (This can involve a mixture of the two other cases.)

I'll try to differentiate among these cases when filing future tickets.

**Comment by jkeenan** [comment]
Compiling with `gcc12` on FreeBSD-12, I am no longer getting any build-time warnings.  Closing this ticket.

**Comment by hvds** [comment]
> I've reported it as [gcc bug 102329](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102329), with a bit more detail.

For the record, that bug was closed today as "fixed in gcc-12".
