### ISSUE TITLE
"handshake" requirements are overly restrictive (and counter-productive) on Windows

### ISSUE THREAD

**Issue by sisyphus** [Perl/perl5#19114]
**Description**

On Windows, we were accustomed to having perl extensions (eg Math::GMPz) that were built on mingw-built perls, working on msvc-built perls.
It's not such a strange concept - the perl code is identical, and a windows dll is a windows dll irrespective of whether it was built by the mingw toolchain or the msvc toolchain.
But, with the advent of the "handshake" requirements, this is no longer necessarily the case.

On my Windows 10 laptop, I build perl-5.34.0 using 32-bit Visual C++ 2010 such that archname is MSWin32-x86-multi-thread-64int.
When, on my Windows 10 laptop, I try to use the mingw-built Math::GMPz that was built for perl-5.34.0 (with same archname) on my Windows 7 machine, I get a handshake error:
```
C:\>perl -le "print $^X;"
C:\_32\perl-5.34.0-whs\bin\perl.exe

C:\>perl -V:archname
archname='MSWin32-x86-multi-thread-64int';

C:\>perl -V:cc
cc='cl';

C:\>perl -le "print $];"
5.034000

C:\>perl -MMath::GMPz -le 1
Random.c: loadable library and perl binaries are mismatched (got handshake key 0BE00080, needed 0BF00080)

C:\>
```

Yet this error is clearly rubbish.
If I build perl-5.34.0 using the same Visual C++ 2010 compiler on the same Windows 10 laptop, but having hacked util.c so that the "handshake" check  is removed, then I find that there's absolutely no problem in using this Windows 7 mingw-built Math::GMPz:
```
C:\>perl -le "print $^X;"
C:\_32\perl-5.34.0-nohs\bin\perl.exe

C:\>perl -V:archname
archname='MSWin32-x86-multi-thread-64int';

C:\>perl -V:cc
cc='cl';

C:\>perl -le "print $];"
5.034000

C:\>perl -MMath::GMPz -le 1

C:\>
```

This leads me to believe that, on Windows 10 at least, this handshake check is counter-productive, appallingly disgraceful, and downright abhorrent.
I have never accepted that there was a good reason to introduce it. (OTOH, I have never openly opposed it.)
All it has done is to replace obscure messages that we all understood with even more obscure messages that no-one understands.
(I note, with gratitude, that there are now attempts being made to reduce that obscurity.)

I am. of course, quite prepared to eat humble pie if it turns out that my summation is based upon some error that I've made.

The (above mentioned) hack to util.c, which removed the handshake test, was simply:
```
$ diff -wu util.c_orig util.c
--- util.c_orig 2021-02-21 22:01:31.000000000 +1100
+++ util.c      2021-09-11 21:06:04.943118600 +1000
@@ -5596,8 +5596,7 @@

     got = INT2PTR(void*, (UV)(key & HSm_KEY_MATCH));
     need = (void *)(HS_KEY(FALSE, FALSE, "", "") & HSm_KEY_MATCH);
-    if (UNLIKELY(got != need))
-        goto bad_handshake;
+
 /* try to catch where a 2nd threaded perl interp DLL is loaded into a process
    by a XS DLL compiled against the wrong interl DLL b/c of bad @INC, and the
    2nd threaded perl interp DLL never initialized its TLS/PERL_SYS_INIT3 so
@@ -5620,14 +5619,6 @@
     got = xs_spp;
     need = &PL_stack_sp;
 #endif
-    if(UNLIKELY(got != need)) {
-        bad_handshake:/* recycle branch and string from above */
-        if(got != (void *)HSf_NOCHK)
-            noperl_die("%s: loadable library and perl binaries are mismatched"
-                       " (got handshake key %p, needed %p)\n",
-                file, got, need);
-    }
-
     if(key & HSf_SETXSUBFN) {     /* this might be called from a module bootstrap */
         SAVEPPTR(PL_xsubfilename);/* which was require'd from a XSUB BEGIN */
         PL_xsubfilename = file;   /* so the old name must be restored for
```

**Comment by xenu** [comment]
Just because a simple example worked, it doesn't mean those two perls are fully compatible.

The first two bytes of the handshake key encode the size of `struct interpreter`. If they differ, XS code accessing interpreter variables won't work properly.

If anything, I'd argue the handshake check isn't strict enough. For example, it doesn't check whether CRT structures/types (e.g. FILE) are compatible. Unfortunately, usually they're opaque, so there's no easy way to implement that.
