### ISSUE TITLE
Implement soft call operator:

### ISSUE THREAD

**Issue by KES777** [Perl/perl5#19123]
Want to bring back old request to top:
https://www.perlmonks.org/?node_id=973015

The only reason that ~> was not implemented because on some terminals it does not look like ->
What about those terminals today?

PS. I notice we have new repository for feature requests, but it does not allow to open new issues =(

**Comment by Grinnz** [comment]
RFCs are not for feature requests but for fully formed proposals which are submitted to the mailing list.

**Comment by Grinnz** [comment]
Previous discussion: https://www.nntp.perl.org/group/perl.perl5.porters/2010/11/msg165931.html

**Comment by nwc10** [comment]
As stated on the [front page of that repository](https://github.com/Perl/RFCs)

If you would like to submit a feature request, please [email an *elevator pitch*](mailto:perl5-porters@perl.org) - a short message with 4 paragraphs:

1. Here is a problem
2. Here is the syntax that I'm proposing
3. Here are the benefits of this
4. Here are potential problems

So yes, please re-open the discussion on this idea by submitting an elevator pitch to the list. We're using issues here for bug reports and implementation PRs, not feature development.
