### ISSUE TITLE
Bug in Data::Dumper when stringify \0 and \1 values

### ISSUE THREAD

**Issue by Geballin** [Perl/perl5#19143]
Module: Data::Dumper

**Description**
When using Data::Dumper::Dumper for stringify an array or arrayref of hashref with a member containing \0 or \1 as value, Dumper output right only the first element of the array, the output is buggy for all next elements.

**Steps to Reproduce**
use Data::Dumper;
my @tab = map {{first => \0, second => \1, third => 'string'}} (0..5);
print Dumper(\@tab)."\n";

**Perl configuration**
```
This is perl 5, version 34, subversion 0 (v5.34.0) built for x86_64-linux-thread-multi
```

**Comment by haarg** [comment]
The output I get from this is:
```
$VAR1 = {
          'first' => \0,
          'third' => 'string',
          'second' => \1
        };
$VAR2 = {
          'second' => $VAR1->{'second'},
          'third' => 'string',
          'first' => $VAR1->{'first'}
        };
$VAR3 = {
          'third' => 'string',
          'second' => $VAR1->{'second'},
          'first' => $VAR1->{'first'}
        };
$VAR4 = {
          'first' => $VAR1->{'first'},
          'second' => $VAR1->{'second'},
          'third' => 'string'
        };
$VAR5 = {
          'first' => $VAR1->{'first'},
          'second' => $VAR1->{'second'},
          'third' => 'string'
        };
$VAR6 = {
          'third' => 'string',
          'second' => $VAR1->{'second'},
          'first' => $VAR1->{'first'}
        };
```

This looks exactly how I would expect. What output were you expecting?

**Comment by Geballin** [comment]
So why is there 
`'second' => $VAR1->{'second'},
 'first' => $VAR1->{'first'}`
on $VAR5 and not 
`'first' => \0,
 'second' => \1`
?
What I expect is having 
`{
          'first' => \0,
          'third' => 'string',
          'second' => \1
};`
for all elements since they all have the exact same values, they should have the exact same output.

\0 and \1 are used by some Perl libraries like JSON to represent Booleans, so not having the right value outputed by Dumper is very misleading when debugging.

**Comment by Grinnz** [comment]
This is standard Data::Dumper behavior, because there are repeated references to the same value. You can use the Deepcopy setting to control this behavior. https://perldoc.perl.org/Data::Dumper

**Comment by Grinnz** [comment]
Closing as there is no bug here.
