### ISSUE TITLE
There is no way to selectively debug matching nested regexes.

### ISSUE THREAD

**Issue by AnFunctionArray** [Perl/perl5#19178]
Module:

**Description**
If you have a nested regex using the `(??{})` syntax.

There is no way to debug it's matching steps.

**Steps to Reproduce**

```
my $var = "testtest";
my $regex =  qr{testtest};

$var =~ s{
                (??{use re 'debug'; regex})
                }{nope}xx;
```

**Expected behavior**
Show the matching steps of the nested regex.

**Perl configuration**
```
Summary of my perl5 (revision 5 version 35 subversion 5) configuration:
  Derived from: 46ba944793db8a03a67f3142e7c6388a46ae168d
  Platform:
    osname=MSWin32
    osvers=10.0.19043.1237
    archname=MSWin32-x64-multi-thread
    uname=''
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cl'
    ccflags ='-nologo -GF -W3 -MD -DWIN32 -D_CONSOLE -DNO_STRICT -DDEBUGGING -DWIN64 -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -D_WINSOCK_DEPRECATED_NO_WARNINGS  -DPERL_TEXTMODE_SCRIPTS -DMULTIPLICITY -DPERL_IMPLICIT_SYS'
    optimize='-Od -Zi -fp:precise'
    cppflags='-DWIN32'
    ccversion='19.30.30528'
    gccversion=''
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=undef
    longlongsize=8
    d_longdbl=define
    longdblsize=8
    longdblkind=0
    ivtype='__int64'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='__int64'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='link'
    ldflags ='-nologo -nodefaultlib -debug  -libpath:"c:\perl\lib\CORE"  -machine:AMD64 -subsystem:console,"5.02"'
    libpth="C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.30.30528\\lib\x64"
    libs=oldnames.lib kernel32.lib user32.lib gdi32.lib winspool.lib  comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib  netapi32.lib uuid.lib ws2_32.lib mpr.lib winmm.lib  version.lib odbc32.lib odbccp32.lib comctl32.lib msvcrt.lib vcruntime.lib ucrt.lib
    perllibs=oldnames.lib kernel32.lib user32.lib gdi32.lib winspool.lib  comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib  netapi32.lib uuid.lib ws2_32.lib mpr.lib winmm.lib  version.lib odbc32.lib odbccp32.lib comctl32.lib msvcrt.lib vcruntime.lib ucrt.lib
    libc=ucrt.lib
    so=dll
    useshrplib=true
    libperl=perl535.lib
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-dll -nologo -nodefaultlib -debug  -libpath:"c:\perl\lib\CORE"  -machine:AMD64 -subsystem:console,"5.02"'


Characteristics of this binary (from libperl):
  Compile-time options:
    DEBUGGING
    HAS_TIMES
    HAVE_INTERP_INTERN
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_SYS
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_TRACK_MEMPOOL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_THREAD_SAFE_LOCALE
  Locally applied patches:
    uncommitted-changes
  Built under MSWin32
  Compiled at Oct  9 2021 00:40:50
  @INC:
    D:/perl5/lib

```

**Comment by demerphq** [comment]
On Sat, 9 Oct 2021 at 10:54, 6a4h8 ***@***.***> wrote:

> Module:
>
> *Description*
> If you have a nested regex using the (??{}) syntax.
>
> There is no way to debug it's matching steps.
>
> *Steps to Reproduce*
>
> my $var = "testtest";
> my $regex =  qr{testtest};
>
> $var =~ s{
>                 (??{use re 'debug'; regex})
>                 }{nope}xx;
>
>
You need to enable it at regex compile time:

my $regex;
{
   use re 'debug';
   $regex= qr{testtest};
}

$var=~s{$regex}{nope};

The point being that regex engine selection is a regex compile time
activity. The way that re 'debug' mode works is that perl swaps out the
normal regex engine for one compiled with debugging enabled.  This must be
done when the regex is compiled.

We actually have facilities so you can compile the pattern without any
visible diagnostics except for run time matching. But you need to decide on
these options at the time the  qr object is constructed.

So I would argue this is not a bug.

Yves
-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by AnFunctionArray** [comment]
> On Sat, 9 Oct 2021 at 10:54, 6a4h8 ***@***.***> wrote: Module: *Description* If you have a nested regex using the (??{}) syntax. There is no way to debug it's matching steps. *Steps to Reproduce* my $var = "testtest"; my $regex = qr{testtest}; $var =~ s{ (??{use re 'debug'; regex}) }{nope}xx;
> You need to enable it at regex compile time: my $regex; { use re 'debug'; $regex= qr{testtest}; } $var=~s{$regex}{nope}; The point being that regex engine selection is a regex compile time activity. The way that re 'debug' mode works is that perl swaps out the normal regex engine for one compiled with debugging enabled. This must be done when the regex is compiled. We actually have facilities so you can compile the pattern without any visible diagnostics except for run time matching. But you need to decide on these options at the time the qr object is constructed. So I would argue this is not a bug. Yves -- perl -Mre=debug -e "/just|another|perl|hacker/"

Thanks - do you know which are those facilities that would enable only matching diagnostics?

I think it's self explanatory though  - I just checked the doc. Thanks so much for pointing me in the right direction.

**Comment by khwilliamson** [comment]
On 10/9/21 7:09 AM, 6a4h8 wrote:
> Thanks - do you know which are those facilities that would enable only 
> matching diagnostics?

use re qw(Debug EXECUTE) and kin, documented in 'perldoc re'
