### ISSUE TITLE
Remove string 'perlbug@perl.org` from core distribution

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#19183]
Sending mail to `perlbug@perl.org` now simply triggers an auto-response
redirecting the sender to our [Issues queue on
Github](https://github.com/Perl/perl5/issues).  We should therefore clean up
all remaining instances of the string `perlbug@perl.org` in the core
distribution.

I have implemented that objective in a series of 3 pull requests.  The approach I have taken is:

1. Leave intact all historical instances of this string, e.g.,
pod/perl*delta.pod and:
```
    dist/IO/Changes
    utils/perlbug.PL
```
2. Where it was being used as an email address for Perl 5 Porters, change to
`perl5-porters@perl.org`.

https://github.com/Perl/perl5/pull/19180
```
    ext/Pod-Functions/Makefile.PL
    dist/ExtUtils-ParseXS/lib/perlxs.pod
```
3. Where it was being used as address for filing bug reports, change to 
`https://github.com/Perl/perl5/issues`.  We'll let the templates on github for
creating new issues speak for themselves.

https://github.com/Perl/perl5/pull/19179
```
    dist/PathTools/lib/File/Spec/Unix.pm
    dist/FindBin/lib/FindBin.pm
    dist/IO/lib/IO/Select.pm
    dist/IO/lib/IO/Socket.pm
    dist/IO/lib/IO/Socket/UNIX.pm
    dist/IO/lib/IO/Socket/INET.pm
    dist/IO/lib/IO/Dir.pm
    dist/IO/lib/IO/Poll.pm
    dist/IO/lib/IO/Pipe.pm
    ext/I18N-Langinfo/Langinfo.pm (2 instances)
```
4. Slightly more complex cases:

https://github.com/Perl/perl5/pull/19181
```
    Configure
    configure.com
    dist/XSLoader/Makefile.PL
```
**Note:** For the purpose of this issue and the corresponding pull requests,
our focus is on the email address cited -- **not** on the `perlbug` utility
itself.  If you want to discuss `perlbug`, please discuss on the mailing list.
In this ticket, such discussion will be considered off-topic.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
All 3 pull requests have been merged, so this ticket can be closed.

**Comment by Grinnz** [comment]
Thanks for handling these cleanups!
