### ISSUE TITLE
Goto xsub forces scalar context

### ISSUE THREAD

**Issue by simon816** [Perl/perl5#19188]
**Description**

When using `goto` to jump to a subroutine, if the subroutine is an XS sub, it's always called in scalar context.
This is not the case for pure perl subroutines, which inherit the context of the caller.

**Steps to Reproduce**
Create a simple module called XS with `h2xs`

XS.xs:
```xs
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

MODULE = XS		PACKAGE = XS		

void
test()
    CODE:
        int gimme = GIMME_V;
        printf("XS Context received: %s\n", gimme == G_VOID ? "void" : gimme == G_SCALAR ? "scalar" : "list");
```

Test code:
```perl
use ExtUtils::testlib;
use XS;

sub test {
    goto &XS::test;
}
my @a = test;
```

**Expected behavior**

It should print "XS Context received: list"

**Actual behavior**

"XS Context received: scalar"

**Perl configuration**
Tested on latest stable: v5.34.0
Ubuntu 20.04: v5.30.0
CentOS 7: 5.16.3

**Analysis**
I did some analysis to figure out what was going on.

```
perl -MO=Concise,test test
main::test:
6  <1> leavesub[1 ref] K/REFC,1 ->(end)
-     <@> lineseq KP ->6
1        <;> nextstate(main 971 test:6) v:{ ->2
5        <1> goto sKS/1 ->6
4           <1> srefgen sK/1 ->5
-              <1> ex-list lKRM ->4
3                 <1> rv2cv[t1] lKRM/AMPER,TARG ->4
-                    <1> ex-list lK ->3
-                       <0> ex-pushmark s ->2
-                       <1> ex-rv2cv sK/AMPER,1 ->-
2                          <$> gv(*XS::test) s ->3
```
First thing to note, the `goto` opcode has a scalar context flag on it.

When goto is used to jump to a subroutine, it follows two different execution paths depending on whether the sub is XS or perl.

For XS subs, it sets up the arguments and ultimately performs a C call to the function pointer
https://github.com/Perl/perl5/blob/v5.34.0/pp_ctl.c#L2990
```c
(void)(*CvXSUB(cv))(aTHX_ cv);
```
For perl subs, it similarly sets up arguments, but then returns an opcode to call the subroutine
https://github.com/Perl/perl5/blob/v5.34.0/pp_ctl.c#L3046
```c
retop = CvSTART(cv);
```
In the perl case, execution continues at the new subroutine. The `gimme` has not been changed therefore it inherits from the existing context (`blk_gimme`). Issuing a `wantarray` will use `blk_gimme`.

For the XS case, **the opcode during execution is `goto`**

op_dump(PL_op):
```
1    goto UNOP(0x55c2b03ee9c8) ===> 2 [leavesub 0x55c2b03e9c08]
     PARENT ===> 3 [lineseq 0x55c2b03e9c40]
     FLAGS = (SCALAR,KIDS,STACKED,SLABBED)
     PRIVATE = (0x1)
```

Asking for the context with `GIMME_V` favours `op_flags`, which, as we saw earlier, `goto` has SCALAR set.
https://github.com/Perl/perl5/blob/v5.34.0/inline.h#L2112

This is how the xsub believes it's in scalar context.

Possible solutions: Don't give the goto opcode a scalar flag, set or clear `PL_op->op_flags` prior to calling the XS function, change the current opcode prior to calling the XS function.

**Comment by DabeDotCom** [comment]
FWIW, I was just bitten by this, too...

**Comment by jkeenan** [comment]
> When using `goto` to jump to a subroutine, if the subroutine is an XS sub, it's always called in scalar context. This is not the case for pure perl subroutines, which inherit the context of the caller.
> 

@tonycoz, @iabyn, could you take a look at this ticket?

**Comment by iabyn** [comment]
On Wed, Oct 13, 2021 at 03:12:09PM -0700, Simon816 wrote:
> When using `goto` to jump to a subroutine, if the subroutine is an XS
> sub, it's always called in scalar context.

Thanks for the report and analysis.
It should be fixed in blead by the following commit:

commit 58cf04199f69d7a775bc88024df0bbb48712ea37
Author:     David Mitchell ***@***.***>
AuthorDate: Wed Jul 6 11:14:22 2022 +0100

    goto(&xs_sub): provide correct caller context
    
    GH #19188
    
    in something like
    
        sub foo { goto &xs_sub }
    
    if the XS subroutine tries to get its caller context using GIMME_V,
    it used to always be reported as scalar, since the OP_GOTO is the
    current op being executed, and that op is marked as scalar.
    
    The correct answer should be to return the context of the caller of
    foo(), but that information is lost as, just before calling the XS sub,
    pp_goto pops the CXt_SUB off the context stack which holds the recorded
    value of the context of the caller.
    
    The fix in principle is for goto, just before calling the XS sub, to
    grab the gimme value from  the about-to-be-popped CXt_SUB frame, and set
    OP_GOTO op's op_flag field with that gimme value.
    
    However, modifying ops at runtime isn't allowed, as ops are shared
    between threads. So instead set up a fake copy of the OP_GOTO and alter
    the gimme value in that instead.
    
    I'm pretty confident that on an exception, a LEAVE_SCOPE() will always
    be done before the JMPENV_JUMP(), so PL_op will be restored to its
    original value *before* the CPU stack is restored to it's old value
    (leaving the temporary OP_GOTO as garbage in an abandoned stack frame).


Affected files ...
    M	ext/XS-APItest/APItest.pm
    M	ext/XS-APItest/APItest.xs
    M	pp_ctl.c
    M	t/op/goto.t

-- 
You never really learn to swear until you learn to drive.
