### ISSUE TITLE
GDBM_File randomly causes fatal errors in LeakSanitizer

### ISSUE THREAD

**Issue by xenu** [Perl/perl5#19189]
In #19182 @graygnuorg noticed that our GitHub Actions don't build DB_File and GDBM_File because libdb and libgdbm aren't installed. When I added those libraries to our configuration, ASan jobs started failing. It seems that GDBM-related tests indeterministically cause fatal errors in LeakSanitizer. Some examples:

```
2021-10-13T14:08:47.3064399Z Tracer caught signal 11: addr=0x0 pc=0x7f3287d6e8b0 sp=0x7f3284219ce0
2021-10-13T14:08:47.3108910Z ==55060==LeakSanitizer has encountered a fatal error.
2021-10-13T14:08:47.3111777Z ==55060==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
2021-10-13T14:08:47.3123895Z ==55060==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
2021-10-13T14:08:47.3180342Z ../ext/GDBM_File/t/count.t ........................................... 
```
```
2021-10-13T16:38:42.9895068Z Tracer caught signal 11: addr=0x0 pc=0x4d6544 sp=0x7fc328bf7d40
2021-10-13T16:38:42.9895940Z ==47346==LeakSanitizer has encountered a fatal error.
2021-10-13T16:38:42.9898747Z ==47346==HINT: For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1
2021-10-13T16:38:42.9899882Z ==47346==HINT: LeakSanitizer does not work under ptrace (strace, gdb, etc)
2021-10-13T16:38:42.9938747Z ../cpan/Memoize/t/errors.t ........................................... 
```

It isn't caused by the changes from that PR, I managed to reproduce it by cherry-picking my github actions config fix to a blead-based branch.

**Comment by xenu** [comment]
The error message says "For debugging, try setting environment variable LSAN_OPTIONS=verbosity=1:log_threads=1". I tried adding that to GitHub Actions config, but it seems it makes the fatal error go away. I'm almost certain it's a bug in ASan.

**Comment by graygnuorg** [comment]
LeakSanitizer displays these hints (in particular) when run from a non-privileged container.  This looks suspiciously similar to https://github.com/google/sanitizers/issues/1353.  Could it be that we hit the same case?  (and, as a minor note: one of the failed tests, cpan/Memoize/t/errors.t, is not related to GDBM_File at all).

**Comment by xenu** [comment]
>and, as a minor note: one of the failed tests, cpan/Memoize/t/errors.t, is not related to GDBM_File at all

It is related, [Memoize can use GDBM_File](https://github.com/Perl/perl5/blob/1d7b70436255bf0e7e5c9a8db29ffbf04371b978/cpan/Memoize/t/errors.t#L23) as a disk cache.

>LeakSanitizer displays these hints (in particular) when run from a non-privileged container. This looks suspiciously similar to google/sanitizers#1353. Could it be that we hit the same case? 

I don't know, it's possible. It's weird, though, that it only seems to happen in GDBM_File-related tests. Apart from the two I listed in my original post, it also happened in ext/GDBM_File/t/dump.t.

**Comment by graygnuorg** [comment]
> It is related, Memoize can use GDBM_File as a disk cache.

Ah, I overlooked that. Do you know if I can enable these tests on my fork to investigate them closer?

**Comment by xenu** [comment]
If you apply [this patch](https://github.com/Perl/perl5/files/7347788/0001-dassdafsd.patch.txt) to your tree, it will run ASan jobs only. You can additionally apply [this](https://github.com/Perl/perl5/files/7347789/0002-dsaas.patch.txt) to run only GDBM_File tests.

**Comment by graygnuorg** [comment]
Thanks!

**Comment by xenu** [comment]
PS. You almost certainly want to pass `-v` to `harness` so you can see the output of the tests.

**Comment by graygnuorg** [comment]
I trimmed it down to GDBM-related tests only. And.. all tests pass. See e.g. https://github.com/graygnuorg/perl5/actions/runs/1343168158

**Comment by xenu** [comment]
It happens randomly, you may need to restart it once or twice. For example, here's a failure on my branch, also trimmed to just GDBM_File tests: https://github.com/xenu/perl5/runs/3897047918

**Comment by graygnuorg** [comment]
I succeeded in reproducing it a couple of times on github.  Then I created a dedicated AWS instance with the same Ubuntu:latest as used in testsuite.yml, cloned blead and configured it exactly the same way as in testsuite, and then started the ext/GDBM_File/t/*.t cpan/Memoize/t/errors.t tests in a loop until the first failure.

By the time of this writing the loop has done over 14000 iterations, without a single failure. I don't see much sense in running it any longer.  The bug is definitely in ASan or in a way the container that runs it on github is created.

**Comment by xenu** [comment]
While GDBM_File is the most reliable trigger of LeakSanitizer crashes, it seems they can happen even when it's not present. For example, [currently in blead](https://github.com/Perl/perl5/runs/3906947746). I made a PR to disable it completely: #19195
