### ISSUE TITLE
[doc] difference between tr/// and tr''' not documented

### ISSUE THREAD

**Issue by wolfdiem** [Perl/perl5#19193]
perlop

The handling of the searchlist in tr/// between use
of 'single quote' and any other characters as delimiter is
different. See the examples (with result in second line):

<code>perl -we"print 'abcdez-' =~ tr/a-z//"
# 6</code>

<code>perl -we"print 'abcdez-' =~ tr'a-z''"
# 3</code>

It turns out that with single quotes the hyphen is not
interpreted as "range sign", but *always* taken literally.

Tested with strawberry perl v5.14.4 and v5.32.1.
Thus it seems that this is a feature (and not a bug),
and thus should be documented. But I did not find any
text on this in perlop in the sections on "q/STRING/",
or on "tr/SEARCHLIST/REPLACEMENTLIST/cdsr", or in the
introduction to "Quote and Quote-like Operators".

Wolf

**Comment by jkeenan** [comment]
> perlop
> 
> The handling of the searchlist in tr/// between use of 'single quote' and any other characters as delimiter is different. See the examples (with result in second line):
> 
> `perl -we"print 'abcdez-' =~ tr/a-z//"`
> ` `
> # `6`
> 
> `perl -we"print 'abcdez-' =~ tr'a-z''"`
> ` `
> # `3`
> 
> It turns out that with single quotes the hyphen is not interpreted as "range sign", but _always_ taken literally.
> 
> Tested with strawberry perl v5.14.4 and v5.32.1. Thus it seems that this is a feature (and not a bug), and thus should be documented. But I did not find any text on this in perlop in the sections on "q/STRING/", or on "tr/SEARCHLIST/REPLACEMENTLIST/cdsr", or in the introduction to "Quote and Quote-like Operators".
> 

While this is a good observation of an uncommon case, I think that it is covered by this documentation in `perlop`.
```
If the characters delimiting SEARCHLIST and REPLACEMENTLIST are single quotes
("tr'SEARCHLIST'REPLACEMENTLIST'"), the only interpolation is removal of "\"
from pairs of "\\".

Otherwise, a character range may be specified with a hyphen, so "tr/A-J/0-9/"
does the same replacement as "tr/ACEGIBDFHJ/0246813579/".
```

**Comment by wolfdiem** [comment]
I saw that text, but I have to admit that I did not see a range
expansion as "interpolation". And I interpreted the "otherwise"
more like "further".
This may stem from my education as EE, and not from the CS side,
and that I am not a native speaker.

So I will close this issue.

Many thanks for the explanation.

**Comment by Grinnz** [comment]
> I saw that text, but I have to admit that I did not see a range
> expansion as "interpolation".

It is not, so I have submitted #19199 to add this clarification.

**Comment by khwilliamson** [comment]
And that change is now in blead.  Thank you for bringing it to our attention.  Let us know if that is sufficient for you.

I myself have scanned that text in the past several times to make sure that the hyphen case was covered.  And it seemed to me that it was.  So it is always good to get someone who isn't so familiar with the area to look it over.

**Comment by wolfdiem** [comment]
Thanks for the change.
Also for me the new text is clear now.
