### ISSUE TITLE
[doc] perl -c: mention how to guarantee no code will be executed

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#19201]
**Where**

perlrun
**Description**

```
       -c   causes Perl to check the syntax of the program and then exit
            without executing it.
```
OK, but

```
            Actually, it will execute any "BEGIN", "UNITCHECK", or
            "CHECK" blocks and any "use" statements: these are
            considered as occurring outside the execution of your
            program. "INIT" and "END" blocks, however, will be skipped.
```

That's great... except please also mention how to turn off any
execution, so one can check random code without worrying one might also
be executing random code.

**Comment by demerphq** [comment]
On Tue, 19 Oct 2021 at 10:03, 積丹尼 Dan Jacobson ***@***.***>
wrote:

> *Where*
>
> perlrun
> *Description*
>
>        -c   causes Perl to check the syntax of the program and then exit
>             without executing it.
>
> OK, but
>
>             Actually, it will execute any "BEGIN", "UNITCHECK", or
>             "CHECK" blocks and any "use" statements: these are
>             considered as occurring outside the execution of your
>             program. "INIT" and "END" blocks, however, will be skipped.
>
> That's great... except please also mention how to turn off any
> execution, so one can check random code without worrying one might also
> be executing random code.
>
We can't mention something that doesn't exist. :-(

Best you can do is hook CORE::require() and CORE::do() to be no-ops.

But you cant stop it executing code in a BEGIN. It cant compile the rest of
the code without executing the BEGIN's in many cases.

cheers,
Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by Grinnz** [comment]
Indeed, `perl -c` by nature has to execute code. The only way so far to attempt to parse Perl code without executing it is with a static parser like PPI, which is extremely easy to fool (and not provided by core).

**Comment by jidanni** [comment]
OK, one must remove the "BEGIN{" and "}" for perl -c to check the contents of BEGINs without executing them.

**Comment by Grinnz** [comment]
No, that will likely prevent the ability to correctly parse the rest of the code. Most BEGIN code is there for a reason, and any "use" statement is also executed at the same time and by `perl -c`.

**Comment by leonerd** [comment]
A `use` statement is a BEGIN block in disguise. It invokes the importer function for the module you used.

Consider something like:

```perl
use List::Util 'reduce';
print "Total is ", reduce { $a + $b } 1 .. 5;
```

This only even compiles because the `List::Util::reduce` function has the `(&@)` prototype, which was imported into the main namespace by that `use` statement. Without that, this code would not parse correctly. In order to parse it correctly, the `BEGIN` block must be run, and must invoke` List::Util->import('reduce')`, which is now real perl code that could do anything.

**Comment by jidanni** [comment]
This all reminds me of
https://www.gnu.org/software/make/manual/html_node/Instead-of-Execution.html
where make --dry-run is still wet sometimes.

I guess the safest thing is to run such commands as user "nobody" on a
system unconnected to the network.
