### ISSUE TITLE
warning on "preincrement" wrong

### ISSUE THREAD

**Issue by wolfdiem** [Perl/perl5#19211]
The warning on "preincrement" is sometimes wrong.
See the following examples (result in 2nd line):

<code>perl -we"$x=':';$x++"
# Argument ":" isn't numeric in preincrement (++) at -e line 1.</code>

<code>perl -we"$x=':';print $x++"
# Argument ":" isn't numeric in postincrement (++) at -e line 1.</code>

While the 2nd test gives the correct warning, the 1st example should
also read 'postincrement'.

For preincrement (++$x), both cases give the correct warning.

Tested in strawberry perl v5.22.3 and v5.32.1.
Earlier Perls did not give a warning at all.

**Comment by jkeenan** [comment]
> The warning on "preincrement" is sometimes wrong. See the following examples (result in 2nd line):
> 
> `perl -we"$x=':';$x++"`
> `Argument ":" isn't numeric in preincrement (++) at -e line 1.`
> 
> `perl -we"$x=':';print $x++"`
> `Argument ":" isn't numeric in postincrement (++) at -e line 1.`
> 
> While the 2nd test gives the correct warning, the 1st example should also read 'postincrement'.
> 
> For preincrement (++$x), both cases give the correct warning.
> 
> Tested in strawberry perl v5.22.3 and v5.32.1. Earlier Perls did not give a warning at all.

This is what I'm getting on Linux on perl-5.32.0 -- and also on 5.34.0 on both Linux and FreeBSD-12:
```
$ perl -v |head -2 | tail -1
This is perl 5, version 32, subversion 0 (v5.32.0) built for x86_64-linux

$ perl -we"$x=':';$x++"
syntax error at -e line 1, near "="
Execution of -e aborted due to compilation errors.

$ perl -we"$x=':';print $x++"
syntax error at -e line 1, near "="
syntax error at -e line 1, at EOF
Execution of -e aborted due to compilation errors.
```

**Comment by Grinnz** [comment]
On linux you need to change the quoting, as double quotes in bash will attempt to interpret `$x`.

**Comment by jkeenan** [comment]
I believe the problem is broader than even the OP suggested.  There are several cases where, in our test suite, we have failed to test for non-numeric warnings in cases involving pre/post-increment/decrement operators.

In the [jkeenan/gh-19211-postincrement-warnings branch](https://github.com/Perl/perl5/tree/jkeenan/gh-19211-postincrement-warnings), I have added 3 test cases to `t/lib/warnings/sv`.
```
$ git diff blead..jkeenan/gh-19211-postincrement-warnings |cat
diff --git a/t/lib/warnings/sv b/t/lib/warnings/sv
index 8524c2c25a..9b0ef81c94 100644
--- a/t/lib/warnings/sv
+++ b/t/lib/warnings/sv
@@ -430,6 +430,60 @@ Argument "(?^:abc)" isn't numeric in preincrement (++) at - line 6.
 Argument "123x" isn't numeric in preincrement (++) at - line 7.
 Argument "123e" isn't numeric in preincrement (++) at - line 8.
 ########
+# sv.c
+my $x = "a_c";
+$x++;
+use warnings "numeric";
+$x = "a_c"; $x++;           # GH 19211
+$x = ${ qr/abc/ }; $x++;    # GH 19211
+$x = "123x"; $x++;          # GH 19211
+$x = "123e"; $x++;          # GH 19211
+$x = 0; $x++; # none of these should warn
+$x = "ABC"; $x++;
+$x = "ABC123"; $x++;
+$x = " +10"; $x++;
+EXPECT
+Argument "a_c" isn't numeric in postincrement (++) at - line 5.
+Argument "(?^:abc)" isn't numeric in postincrement (++) at - line 6.
+Argument "123x" isn't numeric in postincrement (++) at - line 7.
+Argument "123e" isn't numeric in postincrement (++) at - line 8.
+########
+# sv.c
+my $x = "a_c";
+--$x;
+use warnings "numeric";
+$x = "a_c"; --$x;
+$x = ${ qr/abc/ }; --$x;
+$x = "123x"; --$x;
+$x = "123e"; --$x;
+$x = 0; --$x; # none of these should warn
+$x = "ABC"; --$x;
+$x = "ABC123"; --$x;
+$x = " +10"; --$x;
+EXPECT
+Argument "a_c" isn't numeric in predecrement (--) at - line 5.
+Argument "(?^:abc)" isn't numeric in predecrement (--) at - line 6.
+Argument "123x" isn't numeric in predecrement (--) at - line 7.
+Argument "123e" isn't numeric in predecrement (--) at - line 8.
+########
+# sv.c
+my $x = "a_c";
+$x--;
+use warnings "numeric";
+$x = "a_c"; $x--;           # GH 19211
+$x = ${ qr/abc/ }; $x--;    # GH 19211
+$x = "123x"; $x--;          # GH 19211
+$x = "123e"; $x--;          # GH 19211
+$x = 0; $x--; # none of these should warn
+$x = "ABC"; $x--;
+$x = "ABC123"; $x--;
+$x = " +10"; $x--;
+EXPECT
+Argument "a_c" isn't numeric in postdecrement (--) at - line 5.
+Argument "(?^:abc)" isn't numeric in postdecrement (--) at - line 6.
+Argument "123x" isn't numeric in postdecrement (--) at - line 7.
+Argument "123e" isn't numeric in postdecrement (--) at - line 8.
+########
 # RT #128257 This used to SEGV
 use warnings;
 sub Foo::f {}
```
In the **postincrement** case, the test fails because -- as in the OP's case -- the generated warning message is misleading:
```
EXPECTED:
Argument "a_c" isn't numeric in postincrement (++) at - line 5.
Argument "(?^:abc)" isn't numeric in postincrement (++) at - line 6.
Argument "123x" isn't numeric in postincrement (++) at - line 7.
Argument "123e" isn't numeric in postincrement (++) at - line 8.
GOT:
Argument "a_c" isn't numeric in preincrement (++) at - line 5.
Argument "(?^:abc)" isn't numeric in preincrement (++) at - line 6.
Argument "123x" isn't numeric in preincrement (++) at - line 7.
Argument "123e" isn't numeric in preincrement (++) at - line 8.
```
In both the **predecrement** and **postdecrement** cases, I get no warnings where (AFAICT) I should clearly expect them.
```
EXPECTED:
Argument "a_c" isn't numeric in predecrement (--) at - line 5.
Argument "(?^:abc)" isn't numeric in predecrement (--) at - line 6.
Argument "123x" isn't numeric in predecrement (--) at - line 7.
Argument "123e" isn't numeric in predecrement (--) at - line 8.
GOT:

not ok 756 - test from lib/warnings/sv at line 451
```
```
EXPECTED:
Argument "a_c" isn't numeric in postdecrement (--) at - line 5.
Argument "(?^:abc)" isn't numeric in postdecrement (--) at - line 6.
Argument "123x" isn't numeric in postdecrement (--) at - line 7.
Argument "123e" isn't numeric in postdecrement (--) at - line 8.
GOT:

not ok 757 - test from lib/warnings/sv at line 469
```

**Comment by wolfdiem** [comment]
If you are extending the test suite anyhow, I wonder if the
cases for $x = '' and $x = undef should also be added.

empty string:

One could infer from the text in perlop in the section on
"autoin-/-decrement" that it should not warn on increment.
For decrement, there is only the last sentence:
"The auto-decrement operator is not magical.".
Thus it should probably warn on $x-- and --$x for $x == '',
which it does *not* currently. (or a description of the
current behaviour should be added to perlop explicitly).

undefined value:

All four cases should never warn, as described in perlsyn
in the section on "Declarations".

Note on the text in perlop on auto-increment:

The current text there reads (v5.34.0):
"The auto-increment operator has a little extra builtin magic to it.
If you increment a variable that is numeric, or that has ever been
used in a numeric context, you get a normal increment. If, however,
the variable has been used in only string contexts since it was set,
and has a value that is not the empty string and matches the pattern
/^[a-zA-Z]*[0-9]*\z/, the increment is done as a string, preserving
each character within its range, with carry: ..."

This text excludes the empty string from the 'character increment'
which is correct. But it does not say explicitly, that an empty string
is incremented numerically. And in contrast to the increment of "undef"
described further below, which returns "0" for $x++, in the case of
$x == '' the empty string is returned.
If the current handling is the intended one, then I suggest adding text 
to the documentation, to fix it as "specified".

Thanks for taking the action.

**Comment by jkeenan** [comment]
> If you are extending the test suite anyhow, I wonder if the cases for $x = '' and $x = undef should also be added.
> 

We can consider taking these actions, but first we need to get someone to analyze the relevant C-code (`sv.c`, I think), better diagnose the problem, then propose a p.r.

**Comment by jkeenan** [comment]
> 
> Tested in strawberry perl v5.22.3 and v5.32.1. Earlier Perls did not give a warning at all.

Using the following program:
```
$ cat y.pl
#use warnings;
my $x = ':';
$x++;
```
I bisected with the following invocation:
```
export ERR="/tmp/err" && \
perl Porting/bisect.pl \
--start=d7d4eceb184d8fc54797d661a6d5ff9a4a7048c3 \
--end=70f63a4c7dba89e8e48b44de7978faae4319e693 \
-e 'system("./perl -w /tmp/y.pl 2>$ENV{ERR}"); -s $ENV{ERR} and die "See $ENV{ERR} for warnings thrown";'
```
The following was identified as the first bad commit:
```
commit 3f7602fa4cd6923ae409dbb4a71c27905a0abd30 (refs/bisect/bad)
Author:     Tony Cook <tony@develop-help.com>
AuthorDate: Thu Jul 3 15:09:32 2014 +1000
Commit:     Tony Cook <tony@develop-help.com>
CommitDate: Thu Jul 3 15:55:21 2014 +1000

    [perl #3330] warn on increment of an non number/non-magically incable value
    
    The original version of this patch, introduced in
    v5.19.2-389-g8140a7a, warned confusingly when incrementing strings
    like "123abc".  This version includes the fix patch from [perl

```
@tonycoz, can you take a look?

Thank you very much.
Jim Keenan

**Comment by tonycoz** [comment]
post-increment in void context is optimized into a pre-increment:
```
$ perl -MO=Deparse -e 'my $x = ":"; $x++'
my $x = ':';
++$x;
-e syntax OK
```

so the behaviour is expected.

**Comment by jkeenan** [comment]
> post-increment in void context is optimized into a pre-increment:
> 
> ```
> $ perl -MO=Deparse -e 'my $x = ":"; $x++'
> my $x = ':';
> ++$x;
> -e syntax OK
> ```
> 
> so the behaviour is expected.

Can you help me understand why a feature that, if run with warnings, generates a misleading warning, is considered an "optimization"?
```
$ perl -MO=Deparse -w -e 'my $x = ":"; $x++; print "$x\n";'
BEGIN { $^W = 1; }
my $x = ':';
++$x;
print "$x\n";
-e syntax OK
[perl] 529 $ perl  -w -e 'my $x = ":"; $x++; print "$x\n";'
Argument ":" isn't numeric in preincrement (++) at -e line 1.
1
```
Also, do you have any comment on the lack of warnings in pre/post-decrement I noted above?

**Comment by tonycoz** [comment]
It's an optimization since pre-increment is faster than post increment.

Post increment needs to make a copy of the current value, then increment the original and push the copy.

Preincrement skips the copy, and it's an optimization since the copy would just be discarded in void context.

The other missing warnings appear to be deliberate, the code involved dates back to 2000 or so, See Perl_sv_dec() in sv.c

Some of your tests appear to allow `--$x` to not warn when $x is "ABC", but the decrement operators don't handle strings matching `/^[a-z]+\d*$/aai` the same way the increment operators do, so if if we enabled such warnings for "a_c", they should be enabled for "ABC".

But that should be a separate ticket.

**Comment by jkeenan** [comment]
> It's an optimization since pre-increment is faster than post increment.
> 
> Post increment needs to make a copy of the current value, then increment the original and push the copy.
> 
> Preincrement skips the copy, and it's an optimization since the copy would just be discarded in void context.
> 
> The other missing warnings appear to be deliberate, the code involved dates back to 2000 or so, See Perl_sv_dec() in sv.c
> 
> Some of your tests appear to allow `--$x` to not warn when $x is "ABC", but the decrement operators don't handle strings matching `/^[a-z]+\d*$/aai` the same way the increment operators do, so if if we enabled such warnings for "a_c", they should be enabled for "ABC".
> 
> But that should be a separate ticket.

Your remarks suggest that the *crement operators are considerably more complex than I had ever thought.  I suspect others will feel the same way.  Are there any improvements to the documentation (presumably, in `pod/perlop.pod`) that we can/should make to reduce confusion going forward?

**Comment by tonycoz** [comment]
> Your remarks suggest that the *crement operators are considerably more complex than I had ever thought. I suspect others will feel the same way. Are there any improvements to the documentation (presumably, in `pod/perlop.pod`) that we can/should make to reduce confusion going forward?

The difference between the increment and decrement operators is well documented, see "Auto-increment and Auto-decrement" in perlop, particularly:
```
The auto-decrement operator is not magical.
```

As to the wrong operator name in the warning, we could fix that by adding four dummy operators (one each for increment, decrement, integer increment and integer decrement) for which the pp_funcs would be the *pre*-inc/dec operators, the descriptions would be "postincrement (++) void context" etc, and the optimizations would use those instead of the pre-* operators.  I'm not sure that's worth the trouble though.

**Comment by skirmess** [comment]
What about changeing the error message to:

`Argument ":" isn't numeric in pre-/postincrement (++) at -e line 1.`

**Comment by jkeenan** [comment]
> What about changeing the error message to:
> 
> `Argument ":" isn't numeric in pre-/postincrement (++) at -e line 1.`

@tonycoz, would this documentation change be acceptable?

**Comment by tonycoz** [comment]
The operator name part of the message is generated from the operator description of the current operator, see S_not_a_number() in sv.c.  Changing it would change the operator description in most other messages too.

**Comment by jkeenan** [comment]
> S_not_a_number

Okay, I'll take that as a "No, the change suggested for the warning would not be acceptable."

I've run out of ideas for this issue.  I am taking this ticket for the purpose of closing it in 7 days unless someone else has a way forward.

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> > S_not_a_number
> 
> Okay, I'll take that as a "No, the change suggested for the warning would not be acceptable."
> 
> I've run out of ideas for this issue. I am taking this ticket for the purpose of closing it in 7 days unless someone else has a way forward.
> 
> Thank you very much. Jim Keenan

Closing as per schedule.
