### ISSUE TITLE
64b4056614 introduced output to STDERR during make

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#19249]
Every now and then commits to blead start to cause statements being printed to STDERR as `make` or `make test_prep` runs.  Sometimes these statements are exceptions or warnings generated by the C-compiler.  Sometimes they are generated by `perl` or `sh` operations invoked by `make`.  Here is a recent case of the latter.

Near the end of `make test_prep`, the following statement is being generated to STDERR.
```
Empty pod for sv_setpvn (from sv.c) at autodoc.pl line 1215.
```
Bisection indicates this began to be generated with the following commit:
```
commit 64b4056614429bb6fc7d35118e19a220459358fd
Author:     Richard Leach <richardleach@users.noreply.github.com>
AuthorDate: Wed May 26 18:00:11 2021 +0100
Commit:     Tony Cook <tony@develop-help.com>
CommitDate: Mon Nov 1 09:36:27 2021 +1100

    sv.c: add Perl_sv_grow_fresh & Perl_sv_setvpn_fresh
```
@richardleach, @tonycoz:  Can you take a look?

**Comment by richardleach** [comment]
Thanks for picking this up, @jkeenan.
I'm assuming that the second line here should be a `=for apidoc_item`, will try it out now.
```
=for apidoc sv_setpvn
=for apidoc sv_setpvn_fresh
=for apidoc_item sv_setpvn_mg
```
