### ISSUE TITLE
eb87cedb60 introduced output to STDERR during make

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#19250]
Every now and then commits to blead start to cause statements being printed to STDERR as `make` or `make test_prep` runs.  Sometimes these statements are exceptions or warnings generated by the C-compiler.  Sometimes they are generated by `perl` or `sh` operations invoked by `make`.  Here is a recent case of the latter.

Near the end of `make test_prep`, the following statement is being generated to STDERR.
```
embed.fnc entry overrides redundant information in 'Amd|char *const|phase_name|enum perl_phase' in perl.h at autodoc.pl line 494, <F> line 5429.
```
Bisection indicates this began to be generated with the following commit:
```
commit eb87cedb600ef8f1265ce27b13197ca7cbc33297
Author:     Felipe Gasper <felipe@felipegasper.com>
AuthorDate: Thu Aug 5 16:01:44 2021 -0400
Commit:     Tony Cook <tony@develop-help.com>
CommitDate: Thu Nov 25 15:07:56 2021 +1100

    Add a phase_name() macro.
```
@FGasper, @tonycoz:  Can you take a look?

**Comment by jkeenan** [comment]
Confirmed that the `embed.fnc ...` message is no longer being emitted as of e728f790bc.

Thank you very much.
Jim Keenan

**Comment by FGasper** [comment]
Thank you, @tonycoz … and sorry for the noise.
