### ISSUE TITLE
[doc] Text::Balanced doc for extract_multiple provides broken example for parsing CSV fields

### ISSUE THREAD

**Issue by djerius** [Perl/perl5#19264]
**Where**
Text::Balanced

**Description**
The documentation for `extract_multiple` provides an example of parsing a comma-separated value string:

```
@fields = extract_multiple($csv_text,
                             [
                                   sub { extract_delimited($_[0],q{'"}) },
                                   qr/([^,]+)(.*)/,
                             ],
                             undef,1);
```
However, the regular expression matches the entire string, thus stopping the parse after the first field.

For example:

```
use feature 'say';
use Data::Dumper;
use Text::Balanced qw( extract_multiple extract_delimited );

my $csv_text = "a,b,c";

my @fields = extract_multiple($csv_text,
                             [
                                   sub { extract_delimited($_[0],q{'"}) },
                                   qr/([^,]+)(.*)/,
                             ],
                             undef,1);

say Dumper \@fields;
```

Results in

```
$VAR1 = [
          'a'
        ];
```

Changing the regular expression to `qr/([^,]+)/`, returns

```
$VAR1 = [
          'a',
          'b',
          'c'
        ];

```

Which looks more reasonable.

**Comment by jkeenan** [comment]
> **Where** Text::Balanced
> 
> **Description** The documentation for `extract_multiple` provides an example of parsing a comma-separated value string:

Text-Balanced is maintained [upstream on CPAN](https://metacpan.org/pod/Text::Balanced).  Its bug tracker is [here](https://rt.cpan.org/Dist/Display.html?Name=Text-Balanced), so that is where issues should be related.

Closing this ticket. 

Thank you very much.
Jim Keenan

**Comment by djerius** [comment]
Thanks for the pointer.  Sorry for the noise!
