### ISSUE TITLE
regex is hanging inside while loop, neither going 

### ISSUE THREAD

**Issue by abdulbadii** [Perl/perl5#19292]
regex is hanging inside loop not either go on looping nor break out of it

It's in function:
`sub getEleMul`

of script: `rmHTMLmnt.pl`

This'd find an HTML element which is specified as xpath
The xpath documentation states that:
 the element name not followed by order specifier, e.g. [1], [3], will have to
search all that name element in any order repetitively so collect all
the element exist under the previous element specified e.g:
/div[3]/div

The function must obtain all divs regardless of which order it is
under div[3], the parent element

The regex to find these all elements in any order fails
The one to find the only specific element order is working smoothly

test file is: GuiTutorial.html
just run script will directly target onto it

Please help me out !

[Please do not change anything below this line]
Flags:
category=core
severity=medium
Site configuration information for perl 5.34.0:

Configured by builduser at Sun Jul 18 07:20:58 PM UTC 2021.

Summary of my perl5 (revision 5 version 34 subversion 0) configuration:

Platform:
osname=linux
osvers=5.12.15-arch1-1
archname=x86_64-linux-thread-multi
uname='archlinux'
config_args='-des -Dusethreads -Duseshrplib
-Doptimize=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt
-fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat
-Werror=format-security -fstack-clash-protection
-fcf-protection -Dprefix=/usr -Dvendorprefix=/usr
-Dprivlib=/usr/share/perl5/core_perl
-Darchlib=/usr/lib/perl5/5.34/core_perl
-Dsitelib=/usr/share/perl5/site_perl
-Dsitearch=/usr/lib/perl5/5.34/site_perl
-Dvendorlib=/usr/share/perl5/vendor_perl
-Dvendorarch=/usr/lib/perl5/5.34/vendor_perl
-Dscriptdir=/usr/bin/core_perl -Dsitescript=/usr/bin/site_perl
-Dvendorscript=/usr/bin/vendor_perl -Dinc_version_list=none
-Dman1ext=1perl -Dman3ext=3perl -Dcccdlflags='-fPIC'
-Dlddlflags=-shared -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
-Dldflags=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now'
hint=recommended
useposix=true
d_sigaction=define
useithreads=define
usemultiplicity=define
use64bitint=define
use64bitall=define
uselongdouble=undef
usemymalloc=n
default_inc_excludes_dot=define
Compiler:
cc='cc'
ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing
-pipe -fstack-protector-strong -I/usr/local/include
-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
optimize='-march=x86-64 -mtune=generic -O2 -pipe -fno-plt
-fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security
-fstack-clash-protection -fcf-protection'
cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing
-pipe -fstack-protector-strong -I/usr/local/include'
ccversion=''
gccversion='11.1.0'
gccosandvers=''
intsize=4
longsize=8
ptrsize=8
doublesize=8
byteorder=12345678
doublekind=3
d_longlong=define
longlongsize=8
d_longdbl=define
longdblsize=16
longdblkind=3
ivtype='long'
ivsize=8
nvtype='double'
nvsize=8
Off_t='off_t'
lseeksize=8
alignbytes=8
prototype=define
Linker and Libraries:
ld='cc'
ldflags ='-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now
-fstack-protector-strong -L/usr/local/lib'
libpth=/usr/local/lib /usr/lib
libs=-lpthread -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc -lgdbm_compat
perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
libc=libc-2.33.so
so=so
useshrplib=true
libperl=libperl.so
gnulibc_version='2.33'
Dynamic Linking:
dlsrc=dl_dlopen.xs
dlext=so
d_dlsymun=undef
ccdlflags='-Wl,-E -Wl,-rpath,/usr/lib/perl5/5.34/core_perl/CORE'
cccdlflags='-fPIC'
lddlflags='-shared
-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib
-fstack-protector-strong'

@inc for perl 5.34.0:
/usr/lib/perl5/5.34/site_perl
/usr/share/perl5/site_perl
/usr/lib/perl5/5.34/vendor_perl
/usr/share/perl5/vendor_perl
/usr/lib/perl5/5.34/core_perl
/usr/share/perl5/core_perl

Environment for perl 5.34.0:
HOME=/home/budi
LANG=en_US.utf8
LANGUAGE (unset)
LD_LIBRARY_PATH (unset)
LOGDIR (unset)
PATH=/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
PERL_BADLANG (unset)
SHELL=/bin/bash

-------------------------------------------------------------------------------
Tried to upload .html or .pl file type failed
Thanks now able to do:
[perl.zip](https://github.com/Perl/perl5/files/7748295/perl.zip)

**Comment by jkeenan** [comment]
In https://github.com/Perl/perl5/issues/19291, one of our most experienced contributors indicated to you that this Issue tracker is not an appropriate place to post a problem such as the one you're experiencing.  He directed you to some sites that are more appropriate.

By opening a new Github issue, you indicate that you have not followed his advice.  Having looked briefly at the program in your tarball, I concur with his judgment that this is not an appropriate place to post about that problem.

Please do not post here again unless you can document a problem with the Perl 5 language itself.

**Comment by abdulbadii** [comment]
.
