### ISSUE TITLE
[doc] perlre: Do not attempt to describe \K. Simply give examples.

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#19319]
**Where**
perlre
**Description**
We see
```
There is a special form of this construct, called "\K"
(available since Perl 5.10.0), which causes the regex engine to
"keep" everything it had matched prior to the "\K" and not
include it in $&. …
```
WRONG.
PROOF:
```
$ echo a b|perl -pwle 's/ \Kb/$&X/;'
a bX
$ echo a b|perl -pwle 's/ b/$&X/;'
a bX
```

"keep" everything it had matched PRIOR to the "\K":
The space.

"And NOT include it (the space), in $&".
Well you DID include it.

So you need to *talk clearer*.
Clear for you, not for me, and others.
But wait... No need to talk at all. See below.

And then the page goes on to discuss other things:

```
And, there is a technique that can be used to handle variable…
```

```
Note that under "/i", a few single characters match two or…
```

And then all the sudden we are back to discussing '\K':

```
The use of "\K" inside of another lookaround assertion is
allowed, but the behaviour is currently not well defined.

For various reasons "\K" may be significantly more efficient
than the equivalent "(?<=...)" construct, and it is especially
useful in situations where you want to efficiently remove
something following something else in a string. For instance

  s/(foo)bar/$1/g;

can be rewritten as the much more efficient

  s/foo\Kbar//g;
```

OK, so apparently one needs to not use $& to get the effect you are
trying to tell the user, or something.

```
$ echo abc|perl -pwle 's/b\Kc/M$&/;'
abMc
$ echo abc|perl -pwle 's/b\Kc/M/;'
abM
```

So it isn't KEEPing the b here, and NOT including it in $&,
it is keeping the c here, NOT including it in $&, but only when $& isn't
mentioned. Whatever. Tongue twisted mess.

Proposal:
FORGET trying to describe it. Say instead:
```
There is a construct, called "\K".
Its use is hard to describe.
So we will instead just give examples.
...
```

Examples could never be wrong, right?
Else trying to describe it is one big minefield.

In fact don't even mention that '\K' once stood for "keep",
else people will still think there is a way to explain it...
Just stick to examples.
I don't think it is too embarrassing to have some operators/items so complex
that any description will just make things worse. I think it is kind of neat.

(v5.32.1)

**Comment by Grinnz** [comment]
> **Where** perlre **Description** We see
> 
> ```
> There is a special form of this construct, called "\K"
> (available since Perl 5.10.0), which causes the regex engine to
> "keep" everything it had matched prior to the "\K" and not
> include it in $&. …
> ```
> 
> WRONG. PROOF:
> 
> ```
> $ echo a b|perl -pwle 's/ \Kb/$&X/;'
> a bX
> $ echo a b|perl -pwle 's/ b/$&X/;'
> a bX
> ```
> 
> "keep" everything it had matched PRIOR to the "\K": The space.
> 
> "And NOT include it (the space), in $&". Well you DID include it.

Actually the documentation is correct. In your first example, the space is not included in $&, and it is also not replaced in the string, so it remains in the string despite your replacement.

**Comment by jidanni** [comment]
Well I included the "X" to be sure indicate if the regexp matched or not.
So it did.
So fine. There are two things going on.
So the page needs a ton of examples to show what those two things are.
Better yet, just use examples, with no English trying to explain them.

**Comment by Grinnz** [comment]
Examples are not sufficient without description. But I agree improvements can be made.

**Comment by Grinnz** [comment]
> OK, so apparently one needs to not use $& to get the effect you are trying to tell the user, or something.
> 
> ```
> $ echo abc|perl -pwle 's/b\Kc/M$&/;'
> abMc
> $ echo abc|perl -pwle 's/b\Kc/M/;'
> abM
> ```
> 
> So it isn't KEEPing the b here, and NOT including it in $&, it is keeping the c here, NOT including it in $&, but only when $& isn't mentioned. Whatever. Tongue twisted mess.

This is also not correct. Use of `$&` affects whether the contents of `$&` show up in the replacement, like any other variable; it does not affect what is replaced.

**Comment by jidanni** [comment]
Also the whole "who _keeps_ what" concept is fuzzy:
- Perl keeping things for itself, and not giving them back to the user.
- The user keeping things, despite Perl normally taking them away.

**Comment by demerphq** [comment]
On Tue, 11 Jan 2022 at 23:47, 積丹尼 Dan Jacobson ***@***.***>
wrote:

> Also the whole "who *keeps* what" concept is fuzzy:
>
>    - Perl keeping things for itself, and not giving them back to the user.
>    - The user keeping things, despite Perl normally taking them away.
>
> I added this (by request IIRC) feature to the language.

The name "keep" refers to "keep the stuff to the left *out* of the match",
or from the pov of a s/PAT//; refers to "keep the stuff to the left of \K,
don't replace it"  Especially consider the case:

s/foo\Kbar//

We remove "bar" and keep "foo".

Your examples repeatedly use $&, which I think is throwing you off.
Essentially you are saying "replace the part I matched with the part I
matched". Also you keep putting the "extra" stuff as a suffix so it is not
that easy to see what is going on. Changing the "extra" stuff to be a
prefix before $& makes things more obvious:

perl -le'($_= "a b")=~s/ \Kb/X$&/; print'
a Xb

shows that the space, although in the pattern, is not part of what the
regex considers to be the "match", eg, $&.

I can try to reword this, but \K essentially says "$& starts here".

If you are trying to understand \K, try using something like this:

perl -le'($_= "a b")=~m/ \Kb/; print "$-[0],$+[0]"; print
substr($_,$-[0],$+[0]-$-[0]); print $&'
2,3
b
b

Which shows us that the match included the text starting at index 2 up to
but not including index 3, meaning it had a length of 1, which comprises
'b'.

cheers,
Yves










-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by demerphq** [comment]
I think this ticket can be closed.
