### ISSUE TITLE
Provide inclusive alternatives to whitelist and blacklist 

### ISSUE THREAD

**Issue by MikeFultonDev** [Perl/perl5#19323]
I have started working on Perl recently and am interested in making Perl source more inclusive.
One of the things I work on is the 'Words Matter' initiative at my company, and I'm keen to expand this
work to the Open Source community as well.
I noticed that Locale::Maketext refers to whitelist and blacklist (https://metacpan.org/pod/Locale::Maketext)
and was wondering if you would be willing to have an alternative set of methods for whitelist and blacklist
(perhaps allowlist and denylist) for the code?
I would be willing to suggest changes and/or do testing of the changes if that's of value.

The inclusive naming initiative (https://inclusivenaming.org/word-lists/tier-1/) has a pretty good short list
of terms worth considering for change.

Thank you, Mike Fulton

**Comment by khwilliamson** [comment]
On 1/3/22 19:34, Mike Fulton wrote:
> I have started working on Perl recently and am interested in making Perl 
> source more inclusive.
> One of the things I work on is the 'Words Matter' initiative at my 
> company, and I'm keen to expand this
> work to the Open Source community as well.
> I noticed that Locale::Maketext refers to whitelist and blacklist 
> (https://metacpan.org/pod/Locale::Maketext 
> <https://metacpan.org/pod/Locale::Maketext>)
> and was wondering if you would be willing to have an alternative set of 
> methods for whitelist and blacklist
> (perhaps allowlist and denylist) for the code?
> I would be willing to suggest changes and/or do testing of the changes 
> if that's of value.
> 
> The inclusive naming initiative 
> (https://inclusivenaming.org/word-lists/tier-1/ 
> <https://inclusivenaming.org/word-lists/tier-1/>) has a pretty good 
> short list
> of terms worth considering for change.
> 
> Thank you, Mike Fulton

+1

**Comment by Leont** [comment]
> The inclusive naming initiative (https://inclusivenaming.org/word-lists/tier-1/) has a pretty good short list
of terms worth considering for change.

Yeah, we've already been working on removing some of those words (e.g. [slave](https://github.com/Perl/perl5/pull/18854)).

**Comment by MikeFultonDev** [comment]
Thank you @Leont and @khwilliamson for the feedback. 
I requested a PAUSE id awhile ago but haven't heard back yet. I the meantime, I planned to start this work by writing some new tests using the perl5/dist/Locale-Maketext/lib/Locale tree of perl blead. If there is an alternate test suite I should be using, please tell me. 

My thoughts about the actual code would be to create a method for denylist and a method for blacklist and have them both call a common underlying method (perhaps 'exclude'). Similarly, I could create a method for allowlist and a method for whitelist and have them both call a common underlying method. whitelist and blacklist documentation could shift to be 'deprecated' and only 'for use with existing code'. allowlist and denylist documentation could shift to be the recommended interface for new code. 
blacklist and denylist would use a common list under the covers so that people could mix/match new and existing code in an application.
whitelist and allowlist would work in a similar fashion.

I would appreciate your feedback if you see this as a reasonable approach.

**Comment by MikeFultonDev** [comment]
The changes I am proposing are the following 2 patches to Maketext.pm and Maketext.pod:
https://github.com/ZOSOpenTools/perlport/tree/allow-deny-list/blead/patches/dist/Locale-Maketext/lib/Locale
and the following 2 patches to 92_blacklist.t, 93_whitelist.t and the 2 new test cases 94_denylist.t, 95_allowlist.t
https://github.com/ZOSOpenTools/perlport/tree/allow-deny-list/blead/patches/dist/Locale-Maketext/t

**Comment by MikeFultonDev** [comment]
I now have a PAUSE account (thank you to whoever did that!)
I have poked around and am not sure who to reach out to - whether it is @toddr or Sean M. Burke who is listed as the author or someone else? 
Any suggestions welcome on how to proceed.

**Comment by haarg** [comment]
Locale-Maketext is maintained as part of perl core, so you can submit a PR on this repository with your proposed changes.

**Comment by toddr** [comment]
> Locale-Maketext is maintained as part of perl core, so you can submit a PR on this repository with your proposed changes.

@MikeFultonDev: Yep. No PAUSE account needed. I just release whatever p5p merges into [dist/Locale-Maketext](https://github.com/Perl/perl5/tree/blead/dist/Locale-Maketext)

**Comment by MikeFultonDev** [comment]
Ah. Thanks @toddr and @haarg !

**Comment by xsawyerx** [comment]
To provide the patch, you can just fork the repo, create a branch, edit the files in `dist/Locale-Maketext/lib/` and then test the changes by running the command `prove -lr t/` when you're in the `dist/Locale-Maketext/` directory.

If all tests pass, it's recommended to run the entire testing suite of the language, making sure all tests pass, including administrative tests (checking version numbers, authors, etc.). You can do this by running the following commands from the repository base directory:

```
./Configure -des -Dusedevel
make -j 9 test_prep
TEST_JOBS=9 make test_harness
```

If some tests fail, please update this ticket so others can help you through those errors.

**Comment by Leont** [comment]
> If some tests fail,

In particular, update the version of Locale::Maketext when you make your change, otherwise a porting test will fail

**Comment by xsawyerx** [comment]
> > If some tests fail,
> 
> In particular, update the version of Locale::Maketext when you make your change, otherwise a porting test will fail

As well as adding yourself to the `AUTHORS` file so you get recognition for your work.

**Comment by MikeFultonDev** [comment]
Thank you @xsawyerx and @Leont

**Comment by MikeFultonDev** [comment]
```
prove -lr t/
t/01_about_verbose.t ........... ok   
t/04_use_external_lex_cache.t .. ok     
t/09_compile.t ................. ok   
t/10_make.t .................... ok   
t/20_get.t ..................... ok     
t/30_eval_dollar_at.t .......... ok     
t/40_super.t ................... ok     
t/50_super.t ................... ok     
t/60_super.t ................... ok   
t/70_fail_auto.t ............... ok   
t/90_utf8.t .................... ok   
t/91_backslash.t ............... ok   
t/92_blacklist.t ............... ok     
t/93_whitelist.t ............... ok     
t/94_denylist.t ................ ok     
t/95_allowlist.t ............... ok     
All tests successful.
Files=16, Tests=171,  1 wallclock secs ( 0.05 usr  0.05 sys +  0.91 cusr  0.29 csys =  1.30 CPU)
Result: PASS
```

**Comment by MikeFultonDev** [comment]
I updated Maketext.pm to be the 'next' version (1.30) and updated the MANIFEST to include the 2 new testcases I added and got the following results running testing on my Mac, which I believe are 'expected':
```

Test Summary Report
-------------------
io/pipe.t                                                          (Wstat: 0 Tests: 27 Failed: 1)
  Failed test:  27
../cpan/IO-Zlib/t/external.t                                       (Wstat: 0 Tests: 35 Failed: 5)
  Failed tests:  22-24, 29-30
Files=2732, Tests=1205316, 170 wallclock secs (103.82 usr 28.35 sys + 757.10 cusr 146.92 csys = 1036.19 CPU)
Result: FAIL
```

**Comment by xsawyerx** [comment]
I don't understand what "2 new testcases" you're referring to or why these tests fail.

Can you please publish this in a branch? I could run the tests and take a look at it.

Update: Nevermind, just noticed #19345.

**Comment by MikeFultonDev** [comment]
I didn’t write it clearly. My 2 new test runs clean and they are in the files I checked in. The tests that fail I expect were already failing. I can double check if you would like to confirm nothing got ‘worse’

**Comment by Leont** [comment]
> I didn’t write it clearly. My 2 new test runs clean and they are in the files I checked in. The tests that fail I expect were already failing. I can double check if you would like to confirm nothing got ‘worse’

That does sound like a problem (failures are not expected), but not one that's related to this issue.

**Comment by janissaire** [comment]
Fuck off with this faggotry.

**Comment by janissaire** [comment]
They're finally here. We've remained relatively safe from this type of mental derangement for years. It was good while it lasted.
