### ISSUE TITLE
multiple hash assignments appear to create reference

### ISSUE THREAD

**Issue by rnav1234** [Perl/perl5#19357]
To: perl5-porters@perl.org
Subject: multiple hash assignments appear to create reference
Reply-To: robn@nonamesecurity.com
Message-Id: <5.34.0_62001_1642713395@ip-192-168-1-12.ec2.internal>
Cc: root@bigsur.nonet
From: robn@nonamesecurity.com

This is a bug report for perl from robn@nonamesecurity.com,
generated with the help of perlbug 1.42 running under perl 5.34.0.

-----------------------------------------------------------------
[Please describe your issue here]

Folks,
Took some time to track down the following issue:

```
$ perl -MData::Dumper -e 'use strict; use warnings; my (%a,%b); %a = %b = (a=>{A=>1},b=>{B=>1});++$a{a}->{A}; print Dumper \%b'
$VAR1 = {
	  'a' => {
		   'A' => 2
		 },
	  'b' => {
		   'B' => 1
		 }
	};

```
Why is the second hash (%b) updated?
I expected each hash to be initialised and remain separate/unrelated variables.

[Please do not change anything below this line]
-----------------------------------------------------------------
---
Flags:
    category=core
    severity=medium
---
Site configuration information for perl 5.34.0:

Configured by root at Sat May 22 00:32:23 BST 2021.

Summary of my perl5 (revision 5 version 34 subversion 0) configuration:
   
  Platform:
    osname=darwin
    osvers=20.4.0
    archname=darwin-thread-multi-2level
    uname='darwin bigsur 20.4.0 darwin kernel version 20.4.0: thu apr 22 21:46:47 pdt 2021; root:xnu-7195.101.2~1release_x86_64 x86_64 '
    config_args='-des -Dprefix=/usr/local/Cellar/perl/5.34.0 -Dprivlib=/usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0 -Dsitelib=/usr/local/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0 -Dotherlibdirs=/usr/local/lib/perl5/site_perl/5.34.0 -Dperlpath=/usr/local/opt/perl/bin/perl -Dstartperl=#!/usr/local/opt/perl/bin/perl -Dman1dir=/usr/local/Cellar/perl/5.34.0/share/man/man1 -Dman3dir=/usr/local/Cellar/perl/5.34.0/share/man/man3 -Duseshrplib -Duselargefiles -Dusethreads -Dsed=/usr/bin/sed'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=11.3 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -DPERL_USE_SAFE_PUTENV'
    optimize='-O3'
    cppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=11.3 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='Apple LLVM 12.0.5 (clang-1205.0.22.9)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -mmacosx-version-min=11.3 -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/opt/openssl@1.1/lib /usr/local/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.5/lib /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib /usr/lib
    libs=-lgdbm -ldb
    perllibs=
    libc=
    so=dylib
    useshrplib=true
    libperl=libperl.dylib
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=bundle
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags=' -mmacosx-version-min=11.3 -bundle -undefined dynamic_lookup -L/usr/local/lib -fstack-protector-strong'

---
@INC for perl 5.34.0:
    /Users/robnavarro/perl5/lib/perl5/5.34.0/darwin-thread-multi-2level
    /Users/robnavarro/perl5/lib/perl5/5.34.0
    /Users/robnavarro/perl5/lib/perl5/darwin-thread-multi-2level
    /Users/robnavarro/perl5/lib/perl5
    /usr/local/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level
    /usr/local/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0
    /usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level
    /usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0
    /usr/local/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level
    /usr/local/lib/perl5/site_perl/5.34.0

---
Environment for perl 5.34.0:
    DYLD_LIBRARY_PATH (unset)
    HOME=/Users/robnavarro
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/Users/robnavarro/perl5/bin:/Users/robnavarro/.jenv/shims:/Users/robnavarro/.jenv/bin:/Users/robnavarro/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
    PERL5LIB=/Users/robnavarro/perl5/lib/perl5
    PERL_BADLANG (unset)
    PERL_LOCAL_LIB_ROOT=/Users/robnavarro/perl5
    PERL_MB_OPT=--install_base "/Users/robnavarro/perl5"
    PERL_MM_OPT=INSTALL_BASE=/Users/robnavarro/perl5
    SHELL=/usr/local/bin/bash

**Comment by richardleach** [comment]
> Why is the second hash (%b) updated?

This code performs what's called a _shallow copy_.

`%a = %b = (a=>{A=>1},b=>{B=>1});` doesn't create two identical versions of the nested hash structure, one for %a and one for %b. 

Instead, only one instance of each of the anonymous arrays `{A=>1}` and `{B=>1}` is created. The `a` hash entry in `%a` and the `a` hash entry in `%b` both point to the exact same `{A=>1}`. So `$a{a}->{A}` and `$b{a}->{A}` point to the exact same hash element.

`++$a{a}->{A};` updates that one anonymous array element and then it doesn't matter which of `$a{a}->{A}` or `$b{a}->{A}` you use to retrieve the value because either way, it's the same value being accessed . 

For the behaviour you expected, you would have to use a module such as [Storable](https://metacpan.org/pod/Storable#Deep-Cloning), [Clone](https://metacpan.org/pod/Clone), or [Sereal::Dclone](https://metacpan.org/pod/Sereal::Dclone). (I have no personal experience of any of these so cannot recommend one over the other. Other cloning modules also exist on CPAN.)

**Comment by richardleach** [comment]
[Make deep copies](https://www.effectiveperlprogramming.com/2010/03/make-deep-copies/) talks more around this point. Although that article uses arrays rather than hashes for its examples, its the same principle at work.

**Comment by rnav1234** [comment]
Lovely! A very helpful and complete explanation ! Thank you for taking the time to clarify :-)
