### ISSUE TITLE
cpan client is broken on fresh installation

### ISSUE THREAD

**Issue by atoomic** [Perl/perl5#19358]
I discovered that issue while building v5.35.8.
I can confirm this is not specific to v5.35.8 and thus not a blocker for this release. 

Same with v5.35.7 (and probably earlier versions too).

On a fresh install cpan client is broken out of the box due to lack of SSL support.
```
[root@mysqltest2 ~]# /usr/local/bin/cpan5.35.7
Loading internal logger. Log::Log4perl recommended for better logging
Terminal does not support AddHistory.

To fix that, maybe try>  install Term::ReadLine::Perl


cpan shell -- CPAN exploration and modules installation (v2.29)
Enter 'h' for help.

cpan[1]> install Term::ReadLine::Perl
Reading '/root/.cpan/Metadata'
Warning: Found only 0 objects in /root/.cpan/Metadata
Fetching with HTTP::Tiny:
https://cpan.org/authors/01mailrc.txt.gz
HTTP::Tiny failed with an internal error: IO::Socket::SSL 1.42 must be installed for https support
Net::SSLeay 1.49 must be installed for https support

Fetching with HTTP::Tiny:
https://cpan.org/modules/02packages.details.txt.gz
HTTP::Tiny failed with an internal error: IO::Socket::SSL 1.42 must be installed for https support
Net::SSLeay 1.49 must be installed for https support

Fetching with HTTP::Tiny:
https://cpan.org/modules/03modlist.data.gz
HTTP::Tiny failed with an internal error: IO::Socket::SSL 1.42 must be installed for https support
Net::SSLeay 1.49 must be installed for https support

Writing /root/.cpan/Metadata
Warning: Cannot install Term::ReadLine::Perl, don't know what it is.
Try the command

    i /Term::ReadLine::Perl/

to find objects with matching identifiers.
```

It would be great to consider promoting App::cpanm (or any alternate) to CORE as a replacement for CPAN client.

copy: @rjbs / @neilb

**Comment by Leont** [comment]
This is a known issue, it has been fixed in the latest trial release of CPAN.pm. Arguably that should be merged into core even if it's still trial, given how much it gets in the way.

> It would be great to consider promoting App::cpanm (or any alternate) to CORE as a replacement for CPAN client.

cpanm does not aim to have the kind of portability that cpan has, it's not a suitable replacement for core purposes.

**Comment by atoomic** [comment]
If CPAN is going to be updated in a few days we can wait for it

**Comment by wollmers** [comment]
@Leont 

Maybe related or not:

CPAN and PAUSE both use LetsEncrypt certificates, which have an alternate signature path with an EXPIRED (since Thu, 30 Sep 2021 14:01:15 UTC) root certificate. This makes problems on older systems/clients (Perl Mail::something, wget, curl, fetchmail). A work around is to use something like `--insecure` in case of curl, if an upgrade is not possible.

https://www.ssllabs.com/ssltest/analyze.html?d=cpan.org
https://www.ssllabs.com/ssltest/analyze.html?d=pause.perl.org

``` 
Path #2: Not trusted (invalid certificate [Fingerprint SHA256: 0687260331a72403d909f105e69bcf0d32e1bd2493ffc6d9206d11bcd6770739])
[...]

4 | In trust store | DST Root CA X3   Self-signed
Fingerprint SHA256: 0687260331a72403d909f105e69bcf0d32e1bd2493ffc6d9206d11bcd6770739
Pin SHA256: Vjs8r4z+80wjNcr1YKepWQboSIRi63WsWXhIMN+eWys=
RSA 2048 bits (e 65537) / SHA1withRSA
Valid until: Thu, 30 Sep 2021 14:01:15 UTC
EXPIRED
Weak or insecure signature, but no impact on root certificate
```

BTW: Grade C for Pause is very poor. And Pause does a redirect from HTTP to HTTPS.

But typical messages look like this (Perl 5.20.1, Mac OS Catalina, Dist::Milla):

```
[@Milla/ConfirmRelease] *** Preparing to release Text-Levenshtein-BV-0.06.tar.gz with @Milla/UploadToCPAN ***
Do you want to continue the release process? [Y/n]: 
[@Milla/UploadToCPAN] registering upload with PAUSE web server
[@Milla/UploadToCPAN] POSTing upload for Text-Levenshtein-BV-0.06.tar.gz to https://pause.perl.org/pause/authenquery
request failed with error code 500
  Message: Can't connect to pause.perl.org:443 (certificate verify failed)
```

Or on an old Debian installation:

```
$ wget https://cpan.org/authors/01mailrc.txt.gz
--2022-01-21 15:40:35--  https://cpan.org/authors/01mailrc.txt.gz
Resolving cpan.org (cpan.org)... 139.178.67.96
Connecting to cpan.org (cpan.org)|139.178.67.96|:443... connected.
ERROR: The certificate of ‘cpan.org’ is not trusted.
ERROR: The certificate of ‘cpan.org’ has expired.
```

While cpan works using http:

```
# cat /etc/debian_version 
8.11

# dpkg -l openssl
[...]
ii  openssl                         1.0.1t-1+deb8u12     amd64                Secure Sockets Layer toolkit - cryptographic utility

# cpan
Terminal does not support AddHistory.

cpan shell -- CPAN exploration and modules installation (v2.05)
Enter 'h' for help.

cpan[1]> install Levenshtein::BV
Reading '/root/.cpan/Metadata'
  Database was generated on Mon, 11 Oct 2021 11:55:57 GMT
Fetching with LWP:
http://www.cpan.org/authors/01mailrc.txt.gz
Reading '/root/.cpan/sources/authors/01mailrc.txt.gz'
............................................................................DONE
```

**Comment by davehodg** [comment]
Two things:

1. Is a new CPAN.pm, out in the wild now?
2. How can I do the --insecure thing with perlbrew?

This is what I get:

```
% perlbrew install perl-5.34.0
Fetching perl 5.34.0 as /Users/daveh/perl5/perlbrew/dists/perl-5.34.0.tar.gz
Download https://www.cpan.org/authors/id/X/XS/XSAWYERX/perl-5.34.0.tar.gz to /Users/daveh/perl5/perlbrew/dists/perl-5.34.0.tar.gz
ERROR: Failed to download https://www.cpan.org/authors/id/X/XS/XSAWYERX/perl-5.34.0.tar.gz
ERROR: Failed to execute the command

	curl --silent --location --fail -o /Users/daveh/perl5/perlbrew/dists/perl-5.34.0.tar.gz https://www.cpan.org/authors/id/X/XS/XSAWYERX/perl-5.34.0.tar.gz

Reason:

	5888
```

Wget on the image works fine. curl succeeds with no output.

**Comment by jkeenan** [comment]
> I discovered that issue while building v5.35.8. I can confirm this is not specific to v5.35.8 and thus not a blocker for this release.
> 
> Same with v5.35.7 (and probably earlier versions too).
> 
> On a fresh install cpan client is broken out of the box due to lack of SSL support.
> 
> ```
> [root@mysqltest2 ~]# /usr/local/bin/cpan5.35.7
> Loading internal logger. Log::Log4perl recommended for better logging
> Terminal does not support AddHistory.
> 
> To fix that, maybe try>  install Term::ReadLine::Perl
> 
> 
> cpan shell -- CPAN exploration and modules installation (v2.29)
> Enter 'h' for help.
> 
> cpan[1]> install Term::ReadLine::Perl
> Reading '/root/.cpan/Metadata'
> Warning: Found only 0 objects in /root/.cpan/Metadata
> Fetching with HTTP::Tiny:
> https://cpan.org/authors/01mailrc.txt.gz
> HTTP::Tiny failed with an internal error: IO::Socket::SSL 1.42 must be installed for https support
> Net::SSLeay 1.49 must be installed for https support
> 
> Fetching with HTTP::Tiny:
> https://cpan.org/modules/02packages.details.txt.gz
> HTTP::Tiny failed with an internal error: IO::Socket::SSL 1.42 must be installed for https support
> Net::SSLeay 1.49 must be installed for https support
> 
> Fetching with HTTP::Tiny:
> https://cpan.org/modules/03modlist.data.gz
> HTTP::Tiny failed with an internal error: IO::Socket::SSL 1.42 must be installed for https support
> Net::SSLeay 1.49 must be installed for https support
> 
> Writing /root/.cpan/Metadata
> Warning: Cannot install Term::ReadLine::Perl, don't know what it is.
> Try the command
> 
>     i /Term::ReadLine::Perl/
> 
> to find objects with matching identifiers.
> ```
> 

I really hope this gets fixed soon so that we can synch a corrected version of CPAN into cpan/CPAN in core.

For QA purposes I frequently build Perl blead, then use the `cpan` client to try to install modules from CPAN against blead.  With CPAN version 2.29, this is consistently failing, frustrating my QA efforts.  That's not helpful at this point in the production cycle.

Thank you very much.
Jim Keenan

**Comment by pierreforget13** [comment]
Got the same problem with a fresh install. On 2022-01-29. I hope they fix it soon. I had to install manually Net-SSLeay-1.92 and IO-Socket-SSL-2.074 to fix the problem. It works OK now. Cpan usually works great. Thanks for the people who posted these comemnts and thanks to the cpan team.

**Comment by jkeenan** [comment]
@andk, do you have a time frame for a new CPAN release of `CPAN`?

Thank you very much.
Jim Keenan

**Comment by haarg** [comment]
Integrating the latest trial release https://metacpan.org/release/ANDK/CPAN-2.33-TRIAL should resolve this. It shouldn't be necessary to wait for a stable release.

**Comment by atoomic** [comment]
2.33-TRIAL is now in lead we can close this case
