### ISSUE TITLE
[doc] WIFCONTINUED is documented in perlvar as being provided by POSIX, but it's missing

### ISSUE THREAD

**Issue by grr** [Perl/perl5#19385]
**Where**

perlvar

**Description**

In the section "Error Variables", the documentation states that WIFCONTINUED is provided by the POSIX module, but it is missing.

**Comment by xenu** [comment]
It was [removed](https://github.com/Perl/perl5/commit/f2febc77e262f8eeeb62843c90aecd6850631378) from perlvar in 5.34.0.
