### ISSUE TITLE
perlpod does not recognize C<@N> strings 

### ISSUE THREAD

**Issue by Julien-Elie** [Perl/perl5#19394]
When using pod2text, pod2man or like, strings like `C<@N>` are not rendered like `"@N"` but are kept untouched without any quotes around.
I have also tried `C<E<64>N>` (with an escape), but that does not change anything.

Note that `B<@N>` and `I<@N>` correctly render the string in bold, underlined or with `*` around.

I'm using Perl 5.32.1 (shipped with Debian Bullseye).

Isn't there something wrong with how `C<@N>` should be parsed and rendered?

**Comment by jkeenan** [comment]
> When using pod2text, pod2man or like, strings like `C<@N>` are not rendered like `"@N"` but are kept untouched without any quotes around. I have also tried `C<E<64>N>` (with an escape), but that does not change anything.
> 
> Note that `B<@N>` and `I<@N>` correctly render the string in bold, underlined or with `*` around.
> 
> I'm using Perl 5.32.1 (shipped with Debian Bullseye).
> 
> Isn't there something wrong with how `C<@N>` should be parsed and rendered?

In a very narrow sense, we make no promise to render something like `C<@N>` with quotation marks.  However, your point is well taken.  There appear to be 5 instances -- corresponding to 5 perl sigils -- where what we promise to happen (in the documentation) does not actually happen.

**What Do We Promise?**

From `pod/perlpod.pod`:
```
"C<code>" -- code text
    Renders code in a typewriter font, or gives some other indication
    that this represents program text (""C<gmtime($^T)>"") or some other
    form of computerese (""C<drwxr-xr-x>"").
```

**What Actually Happens?**

Play around with this `*.pod` file:
```
$ cat gh-19394-pod.pod 
=head1 GH-19394 analysis

This is text hoping to illustrate the problem described by Julien-Elie in L<this bug report|https://github.com/Perl/perl5/issues/19394>.

String with B marks: B<@N>; B<$N>; B<%N>; B<&N>; B<*N>; B<abc>.

String with I marks: I<@N>; I<$N>; I<%N>; I<&N>; I<*N>; I<abc>.

String with C marks: C<@N>; C<$N>; C<%N>; C<&N>; C<*N>; C<abc>; C<#N>; C<!N>; C<^N>; C<+N>.

String with C marks, multiple brackets: C<< @N >>; C<< $N >>; C<< %N >>; C<< &N >>; C<< abc >>.

String with C marks from F<perlpod>: C<gmtime($^T)>; C<drwxr-xr-x>.

End.

=cut
```
Run it through various commands like the following:
```
$ perldoc gh-19394-pod.pod

$ pod2text < ./gh-19394-pod.pod

$ pod2man < ./gh-19394-pod.pl > some.man; man ./some.man

$ pod2html --infile=./gh-19394-pod.pod --outfile=some.html --no-index
    # then view some.html in browswer
```

Of these, only `pod2html` can render code in a "typewriter font," so it dispenses with quotation marks in all `C<>` renderings.  The others appear to gives some other indication that the encoded string "represents program text ... or some other form of computerese" via quotation marks **except** for the 5 perl sigils. 
    
**How Has What We Promise Evolved Over Time?**
```
$ git describe
perl-5.005

    C<code> literal code

$ git describe
perl-5.6.0

    C<code>     Render code in a typewriter font, or give some other
                indication that this represents program text

$ git describe
perl-5.8.0

=item C<CE<lt>codeE<gt>> -- code text

Renders code in a typewriter font, or gives some other indication that
this represents program text ("C<CE<lt>gmtime($^T)E<gt>>") or some other
form of computerese ("C<CE<lt>drwxr-xr-xE<gt>>").

$ git describe
v5.34.0 [unchanged since perl-5.8.0]

```
**What Is To Be Done?**

A slight tweak to the documentation would be simplest and best.  We're not going to change the actual behavior, as it's been there for at least 22 years.

I don't understand the POD-parsing or rendering code well enough to identify the places in the codebase where what we do for `C<>` for the 5 sigils is different from everything else.  If someone else can identify those places, then we have a starting point for a discussion about more precise documentation.

**Comment by Julien-Elie** [comment]
Thanks James for your response.
I've opened a ticket on the podlators bug tracker: https://rt.cpan.org/Public/Bug/Display.html?id=143668

Closing this bug here.
