### ISSUE TITLE
Bleadperl broke test of PUNYTAN/sane-0.99

### ISSUE THREAD

**Issue by andk** [Perl/perl5#19411]
**Description**

The module on CPAN PUNYTAN/sane-0.99.tar.gz stopped working during the development cycle between 5.35.2 and 5.35.3.

**Steps to Reproduce**

In the cpan shell type `install PUNYTAN/sane-0.99.tar.gz`

**Expected behavior**

The tests in the make test phase should pass, not fail

**Bisect**

My bisecting was leading to the commit 915e574d30

**X-Ref**

I have also reported this story to the CPAN RT bug tracker at  https://rt.cpan.org/Ticket/Display.html?id=141301

**Bug or Feature**

I have no stance on the question whether it is a bug or a feature, I hope somebody else will let PUNYTAN know.

**Perl configuration**

```
# perl -V output goes here
% /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.2-31-g915e574d30/da1c/bin/perl -V                                                                        
Summary of my perl5 (revision 5 version 35 subversion 3) configuration:                                                    
  Commit id: 915e574d301f00ab410e345d06c5c0a992c95c1f
  Platform:
    osname=linux
    osvers=5.15.0-2-amd64
    archname=x86_64-linux
    uname='linux k93msid 5.15.0-2-amd64 #1 smp debian 5.15.5-2 (2021-12-18) x86_64 gnulinux '
    config_args='-Dprefix=/home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.2-31-g915e574d30/da1c -Dmyhostname=k93msid -Dinstallusrbinperl=n -Uversiononly -Dusedevel -des -Ui_db -Dlibswanted=cl pthread socket inet nsl gdbm dbm malloc dl ld sun m crypt sec util c cposix posix ucb BSD gdbm_compat -Uuseithreads -Uuselongdouble -DEBUGGING=-g'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2 -g'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='11.2.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.33.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.33'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under linux
  Compiled at Feb 12 2022 19:27:20
  @INC:
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.2-31-g915e574d30/da1c/lib/site_perl/5.35.3/x86_64-linux
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.2-31-g915e574d30/da1c/lib/site_perl/5.35.3
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.2-31-g915e574d30/da1c/lib/5.35.3/x86_64-linux
    /home/sand/src/perl/repoperls/installed-perls/host/k93msid/v5.35.2-31-g915e574d30/da1c/lib/5.35.3

```

**Comment by hvds** [comment]
This appears to be as expected: the module is testing that `require feature; feature->import(sprintf ":%vd", $^V);` enables the `switch` feature. The author will need to change their test (if they're just trying to demonstrate that `feature` has been called as expected) or their implementation (if they also specifically want to enable `switch`).

Either way there isn't obviously anything for us to do here, except perhaps to communicate more clearly that automatically tying your code to the latest feature bundle implies accepting a degree of risk.

**Comment by jkeenan** [comment]
> This appears to be as expected: the module is testing that `require feature; feature->import(sprintf ":%vd", $^V);` enables the `switch` feature. The author will need to change their test (if they're just trying to demonstrate that `feature` has been called as expected) or their implementation (if they also specifically want to enable `switch`).
> 
> Either way there isn't obviously anything for us to do here, except perhaps to communicate more clearly that automatically tying your code to the latest feature bundle implies accepting a degree of risk.

I have submitted a patch [upstream](https://rt.cpan.org/Ticket/Attachment/2185065/1069450/rtc-141301-sane.diff) which provides a work-around.  We can now close this ticket.
