### ISSUE TITLE
openSUSE smoke failure: op/glob.t #18

### ISSUE THREAD

**Issue by hvds** [Perl/perl5#19413]
Between eb87cedb60 and 0a91ad7bad some of @Tux's openSUSE smokes started giving this:
```
# Failed test 18 - Make sure the presence of the CORE::GLOBAL::glob typeglob does not affect whether File::Glob::csh_glob is called. at ./test.pl line 1076
#      got "Use of uninitialized value $output1 in string eq at - line 18.\nUse of uninitialized value $output2 in string eq at - line 18.\nok1\nok2"
# expected "ok1\nok2"
# PROG: 
#     if ($^O eq 'VMS') {
#         # A pattern with a double quote in it is a syntax error to LIB$FIND_FILE
#         # Should we strip quotes in Perl_vms_start_glob the way csh_glob() does?
#         print "ok1\nok2\n";
#     }
#     else {
#         ++$INC{"File/Glob.pm"}; # prevent it from loading
#         my $called1 = 0;
#         my $called2 = 0;
#         *File::Glob::csh_glob = sub { ++$called1 };
#         my $output1 = eval q{ glob(q(./"TEST")) };
#         undef *CORE::GLOBAL::glob; # but leave the typeglob itself there
#         ++$CORE::GLOBAL::glob if 0; # "used only once"
#         undef *File::Glob::csh_glob; # avoid redefinition warnings
#         *File::Glob::csh_glob = sub { ++$called2 };
#         my $output2 = eval q{ glob(q(./"TEST")) };
#         print "ok1" if $called1 eq $called2;
#         print "ok2" if $output1 eq $output2;
#     }
# STATUS: 0
```

I'm not sure what could cause `glob(q(./"TEST"))` to return undef, but it seems possible that's also why this fail appears coupled with the failure to build `cpan/Pod-Checker/podchecker` and `cpan/Pod-Usage/pod2usage` (reported by `t/porting/dual-life.t`).

I don't see anything in that range of commits likely to trigger this - @Tux, do you know of any changes on those machines that could be connected? Are you in a position to debug this?

**Comment by jkeenan** [comment]
> Between [eb87ced](https://github.com/Perl/perl5/commit/eb87cedb600ef8f1265ce27b13197ca7cbc33297) and [0a91ad7](https://github.com/Perl/perl5/commit/0a91ad7bad09fcaf7a49940068a65ce44e753743) some of @Tux's openSUSE smokes started giving this:
> 
> ```
> # Failed test 18 - Make sure the presence of the CORE::GLOBAL::glob typeglob does not affect whether File::Glob::csh_glob is called. at ./test.pl line 1076
> #      got "Use of uninitialized value $output1 in string eq at - line 18.\nUse of uninitialized value $output2 in string eq at - line 18.\nok1\nok2"
> # expected "ok1\nok2"
[snip]

@Tux, have you been able to take a look at this ticket?

**Comment by Tux** [comment]
@jkeenan I think all systems are green on this issue now. I think it is/was related to a new tcsh which had a bug
Sorry for the delayed reply

**Comment by jkeenan** [comment]
> @jkeenan I think all systems are green on this issue now. I think it is/was related to a new tcsh which had a bug Sorry for the delayed reply

If I'm reading the smoke-test aggregation reports correctly, you have 4 smoke-testing rigs running OpenSUSE.  Their hostnames:
```
tux
lx01
lx09
sv02
```
`lx01` and `sv02` are currently PASSing.  `lx09` is currently failing tests other than `t/op/glob.t` (mostly IO-Compress and similar tests), but I'm seeing failures on `tux`.  For example:
```
tux
v5.35.11-31-gfc995cf: https://perl5.test-smoke.org/report/5018197
v5.35.11-26-g92584ee: https://perl5.test-smoke.org/report/5018185
```
Can you take another look?

**Comment by Tux** [comment]
`lx09` is Tumbleweed and it has a version mismatch on `libz1` which I do not understand. `IO::Compress` won't pass tests.

On `tux`, `$Config{csh}` is set to `tcsh`, and in `op/glob.t` I cannot "reset" that temporary, as `local $Config{csh} = "/usr/bin/csh";` results in `%Config::Config is read-only`. If I alter `lib/Config_heavy.pl` so `$Config{csh}` is `csh` instead of `tcsh` I still get the same error. I get a PASS if I change these two lines, which is like sweeping the FAIL under the carpet, isn't it:
```
my $output1 = eval q{ glob(q(./"TEST")) } // ""; # default "" added
my $output2 = eval q{ glob(q(./"TEST")) } // ""; # default "" added
```
I'm open to hints in where to do deeper tests.

**Comment by haarg** [comment]
Can you check what `$@` is after each of those evals?

**Comment by Tux** [comment]
`$@` is empty in both cases.

**Comment by Tux** [comment]
So, my default for this box was:
```
$ perl -V:.*csh.*
csh='tcsh';
d_csh='define';
full_csh='/usr/bin/tcsh';
```
When I change that to
```
$ perl -V:.*csh.*
csh='csh';
d_csh='define';
full_csh='/usr/bin/csh';
```
where csh is a symlink to tcsh
```
$ path -al csh
100755 -r-x    2     root    531416  12 May 2022 17:44 /usr/bin/csh -> /bin/tcsh
100755 -r-x    2     root    531416  12 May 2022 17:44 /bin/csh -> tcsh
100755 -r-x    2     root    531416  12 May 2022 17:44 /usr/bin/X11/csh -> /bin/tcsh
```
All tests start PASSing
```
$ export C='glob ./"TEST"'
$ tcsh -c "$C" ; echo "##"
./TEST##
$ csh -c "$C" ; echo "##"
./TEST##
$
```
Anything else that I can/should dig into?

**Comment by jkeenan** [comment]
> So, my default for this box was:
> 
> ```
> $ perl -V:.*csh.*
> csh='tcsh';
> d_csh='define';
> full_csh='/usr/bin/tcsh';
> ```
> 
> When I change that to
> 
> ```
> $ perl -V:.*csh.*
> csh='csh';
> d_csh='define';
> full_csh='/usr/bin/csh';
> ```
> 
> where csh is a symlink to tcsh
> 
> ```
> $ path -al csh
> 100755 -r-x    2     root    531416  12 May 2022 17:44 /usr/bin/csh -> /bin/tcsh
> 100755 -r-x    2     root    531416  12 May 2022 17:44 /bin/csh -> tcsh
> 100755 -r-x    2     root    531416  12 May 2022 17:44 /usr/bin/X11/csh -> /bin/tcsh
> ```
> 
> All tests start PASSing
> 
> ```
> $ export C='glob ./"TEST"'
> $ tcsh -c "$C" ; echo "##"
> ./TEST##
> $ csh -c "$C" ; echo "##"
> ./TEST##
> $
> ```
> 
> Anything else that I can/should dig into?

Smoke-test reports on the `tux` host have been PASS since May 30, so this ticket looks closable.  Doing so now.  Thanks for your investigation.
