### ISSUE TITLE
Scalar-List-Utils v1.60 warns during build of perl.

### ISSUE THREAD

**Issue by demerphq** [Perl/perl5#19429]
Module:
Scalar-List-Utils, eg, List::Util

**Description**
When building Scalar-List-Utils in blead there are multiple warnings thrown about signed/unsigned errors.

**Steps to Reproduce**
make
....
ListUtil.xs: In function ‘XS_List__Util_zip’:
ListUtil.xs:1619:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 if(av_count(av) > len)
                                 ^
ListUtil.xs:1624:33: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 if(av_count(av) < len)
                                 ^
ListUtil.xs:1639:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 SV *item = (i < av_count(lists[listi])) ?
                               ^
ListUtil.xs:1658:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 SV *item = (i < av_count(lists[listi])) ?
                               ^
**Expected behavior**
No warnings.

**Perl configuration**
```
./perl -Ilib -V
Summary of my perl5 (revision 5 version 35 subversion 9) configuration:
  Derived from: 265e8585296781ded96e1e99feaeb5f5b5bc4592
  Platform:
    osname=linux
    osvers=4.15.0-166-generic
    archname=x86_64-linux-thread-multi
    uname='linux psykopsis 4.15.0-166-generic #174-ubuntu smp wed dec 8 19:07:44 utc 2021 x86_64 x86_64 x86_64 gnulinux '
    config_args='-Dusethreads -Doptimize=-g -d -Dusedevel -Dcc=ccache gcc -Dld=gcc -DDEBUGGING'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='gcc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-g'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='7.5.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='gcc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.27.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.27'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    DEBUGGING
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_TRACK_MEMPOOL
    PERL_USE_DEVEL
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Locally applied patches:
    uncommitted-changes
  Built under linux
  Compiled at Feb 16 2022 06:45:54
  %ENV:
    PERLBREW_CONFIGURE_FLAGS="-de -Dcc=ccache\ gcc -Dld=gcc"
    PERLBREW_HOME="/home/yorton/.perlbrew"
    PERLBREW_MANPATH="/home/yorton/perl5/perlbrew/perls/perl-5.24.1/man"
    PERLBREW_PATH="/home/yorton/perl5/perlbrew/bin:/home/yorton/perl5/perlbrew/perls/perl-5.24.1/bin"
    PERLBREW_PERL="perl-5.24.1"
    PERLBREW_ROOT="/home/yorton/perl5/perlbrew"
    PERLBREW_SHELLRC_VERSION="0.88"
    PERLBREW_VERSION="0.88"
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/5.35.9/x86_64-linux-thread-multi
    /usr/local/lib/perl5/site_perl/5.35.9
    /usr/local/lib/perl5/5.35.9/x86_64-linux-thread-multi
    /usr/local/lib/perl5/5.35.9
```

**Comment by leonerd** [comment]
This is now fixed by https://github.com/Dual-Life/Scalar-List-Utils/pull/119 and released to CPAN as Scalar-List-Utils 1.61.

**Comment by jkeenan** [comment]
> Module: Scalar-List-Utils, eg, List::Util
> 
> **Description** When building Scalar-List-Utils in blead there are multiple warnings thrown about signed/unsigned errors.
> 

These were previously reported upstream at https://rt.cpan.org/Ticket/Display.html?id=136985.  @leonerd, can you take a look at the patch @demerphq is suggesting?

This would be a good point in the production cycle to eliminate these build-time warnings, as they are the only such warnings being emitted during `make` using certain C-compilers.

@demerphq, FYI, we can track a ticket like this one via the `build-time warnings` label.

Thank you very much.
Jim Keenan

**Comment by demerphq** [comment]
On Wed, 16 Feb 2022 at 13:45, James E Keenan ***@***.***>
wrote:

> Module: Scalar-List-Utils, eg, List::Util
>
> *Description* When building Scalar-List-Utils in blead there are multiple
> warnings thrown about signed/unsigned errors.
>
> These were previously reported upstream at
> https://rt.cpan.org/Ticket/Display.html?id=136985. @leonerd
> <https://github.com/leonerd>, can you take a look at the patch @demerphq
> <https://github.com/demerphq> is suggesting?
>
> This would be a good point in the production cycle to eliminate these
> build-time warnings, as they are the only such warnings being emitted
> during make using certain C-compilers.
>

Actually that isnt correct, see https://github.com/Perl/perl5/issues/19432

yves

**Comment by jkeenan** [comment]
The Scalar-List-Util build-time warnings discussed in this ticket have been addressed.  Closing.
