### ISSUE TITLE
 Compress-Raw-Bzip2 produces uninitialized warnings during build in bleadperl

### ISSUE THREAD

**Issue by demerphq** [Perl/perl5#19432]
Module:
Compress-Raw-Bzip2

**Description**
During build uninitialized warnings are produced. They are bogus, but annoying and easily avoidable.

Issue has been reported upstream as:
   https://github.com/pmqs/Compress-Raw-Bzip2/issues/4

And a PR to fix upstream:
   https://github.com/pmqs/Compress-Raw-Bzip2/pull/5

**Steps to Reproduce**
```
make
....
gcc -c  -I. -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wno-declaration-after-statement -Wc++-compat -Wwrite-strings -O3   -DVERSION=\"2.101\" -DXS_VERSION=\"2.101\" -fPIC "-I../.."  -Wall -Wno-comment  -DBZ_NO_STDIO  compress.c
compress.c: In function ‘BZ2_compressBlock’:
compress.c:392:54: warning: ‘cost[5]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                for (t = 0; t < nGroups; t++) cost[t] += s->len[t][icv];
                                                      ^~
compress.c:256:11: note: ‘cost[5]’ was declared here
    UInt16 cost[BZ_N_GROUPS];
           ^~~~
compress.c:402:21: warning: ‘cost[3]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             if (cost[t] < bc) { bc = cost[t]; bt = t; };
                 ~~~~^~~
compress.c:256:11: note: ‘cost[3]’ was declared here
    UInt16 cost[BZ_N_GROUPS];
           ^~~~
compress.c:402:21: warning: ‘cost[2]’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             if (cost[t] < bc) { bc = cost[t]; bt = t; };
                 ~~~~^~~
compress.c:256:11: note: ‘cost[2]’ was declared here
    UInt16 cost[BZ_N_GROUPS];
           ^~~~
```

**Expected behavior**
No warnings during build.

**Perl configuration**
```
$ ./perl -Ilib -V
Summary of my perl5 (revision 5 version 35 subversion 9) configuration:
  Commit id: ad3f424b5f4280f9162f0b4792fe466be39a843e
  Platform:
    osname=linux
    osvers=4.15.0-166-generic
    archname=x86_64-linux-thread-multi
    uname='linux psykopsis 4.15.0-166-generic #174-ubuntu smp wed dec 8 19:07:44 utc 2021 x86_64 x86_64 x86_64 gnulinux '
    config_args='-Dusethreads -Doptimize=-O3 -d -Dusedevel -Dcc=ccache gcc -Dld=gcc'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='gcc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O3'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='7.5.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='gcc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.27.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.27'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O3 -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_DEVEL
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Feb 17 2022 02:55:02
  %ENV:
    PERLBREW_CONFIGURE_FLAGS="-de -Dcc=ccache\ gcc -Dld=gcc"
    PERLBREW_HOME="/home/yorton/.perlbrew"
    PERLBREW_MANPATH="/home/yorton/perl5/perlbrew/perls/perl-5.24.1/man"
    PERLBREW_PATH="/home/yorton/perl5/perlbrew/bin:/home/yorton/perl5/perlbrew/perls/perl-5.24.1/bin"
    PERLBREW_PERL="perl-5.24.1"
    PERLBREW_ROOT="/home/yorton/perl5/perlbrew"
    PERLBREW_SHELLRC_VERSION="0.88"
    PERLBREW_VERSION="0.88"
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/5.35.9/x86_64-linux-thread-multi
    /usr/local/lib/perl5/site_perl/5.35.9
    /usr/local/lib/perl5/5.35.9/x86_64-linux-thread-multi
    /usr/local/lib/perl5/5.35.9
```

**Comment by jkeenan** [comment]
On 2/16/22 21:41, Yves Orton wrote:
> Module:
> Compress-Raw-Bzip2
> 
> *Description*
> During build uninitialized warnings are produced. They are bogus, but 
> annoying and easily avoidable.
> 
> Issue has been reported upstream as:
> pmqs/Compress-Raw-Bzip2#4 
> <https://github.com/pmqs/Compress-Raw-Bzip2/issues/4>
> 
> And a PR to fix upstream:
> pmqs/Compress-Raw-Bzip2#5 
> <https://github.com/pmqs/Compress-Raw-Bzip2/pull/5>
> 

I should note that in past years I have reported build-time warnings in 
this distribution and similar ones to its very diligent upstream 
maintainer Paul Marquess.  He reported being aware of them but noted 
that some of the source code is itself taken from upstream sources and 
that he prefers to change the code in these CPAN distributions only when 
the upstream code changes.  (I'm not attempting to speak for him in this 
instance; just noting why those warnings haven't already been cured.)

jimk

**Comment by demerphq** [comment]
Hi,

I am a contributor to the Perl project. https://github.com/Perl/perl5

We bundle your library libbzip2 via the perl Module Compress-Raw-Bzip2,
which is hosted at:

https://github.com/pmqs/Compress-Raw-Bzip2

We are trying to ensure our builds are warning clean, however when building
this package your library produces "may be used uninitialized" warnings on
some compilers, you can see these warnings below.

While this is almost certainly a false positive warning, it is also trivial
to silence the warnings with essentially no performance hit by initializing
the cost structure with 0's at the start.

We have an open bug report for this for perl here:
https://github.com/Perl/perl5/issues/19432

And an open bug report for this for the module here:
https://github.com/pmqs/Compress-Raw-Bzip2/issues/4

And a patch for it here:
https://github.com/pmqs/Compress-Raw-Bzip2/pull/5/commits/641a440ec6229c1d368b9ead48f4968b955c0115

The maintainer of Compress-Raw-Bzip2 (on CC) is known to prefer not to
apply changes to this library code that are not upstream. (A reasonable
policy.)

I was wondering if you could apply this patch, or something equivalent that
would fix this so that the perl project could have warning free builds.
Your library is the last module we ship that produces warnings during the
build process. We target a wide range of compilers and try to keep our code
as clean as possible, and while again I accept that your code likely is not
buggy as you initialize it in a loop at line 357,

357:         for (t = 0; t < nGroups; t++) cost[t] = 0;

as far as I can tell nGroups is not a constant, and the compiler reasonably
cannot be certain that all BZ_N_GROUPS entries in the array are initialized
before use.

We in the perl development community would appreciate it if you would
release a patch that would silence these warnings for us. Then Paul could
roll a new release of his module, and we in the Perl could then use that
and be happy with a completely warning free build.

gcc -c  -I. -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing
-pipe -fstack-protector-strong -I/usr/local/include
-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Werror=pointer-arith
-Werror=vla -Wextra -Wno-long-long -Wno-declaration-after-statement
-Wc++-compat -Wwrite-strings -O3   -DVERSION=\"2.101\"
-DXS_VERSION=\"2.101\" -fPIC "-I../.."  -Wall -Wno-comment
-DBZ_NO_STDIO  compress.c
compress.c: In function ‘BZ2_compressBlock’:
compress.c:392:54: warning: ‘cost[5]’ may be used uninitialized in
this function [-Wmaybe-uninitialized]
                for (t = 0; t < nGroups; t++) cost[t] += s->len[t][icv];
                                                      ^~
compress.c:256:11: note: ‘cost[5]’ was declared here
    UInt16 cost[BZ_N_GROUPS];
           ^~~~
compress.c:402:21: warning: ‘cost[3]’ may be used uninitialized in
this function [-Wmaybe-uninitialized]
             if (cost[t] < bc) { bc = cost[t]; bt = t; };
                 ~~~~^~~
compress.c:256:11: note: ‘cost[3]’ was declared here
    UInt16 cost[BZ_N_GROUPS];
           ^~~~
compress.c:402:21: warning: ‘cost[2]’ may be used uninitialized in
this function [-Wmaybe-uninitialized]
             if (cost[t] < bc) { bc = cost[t]; bt = t; };
                 ~~~~^~~
compress.c:256:11: note: ‘cost[2]’ was declared here
    UInt16 cost[BZ_N_GROUPS];
           ^~~~

Your consideration on this matter would be much appreciated.

I have requested an account with your bug tracker and will file a formal
ticket as soon as I get an account.

Thank you very much for your time in producing this library, I
personally have made use of it many times in my career.

cheers,
Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by demerphq** [comment]
I filed a ticket with upstream libraries bug tracker:

https://sourceware.org/bugzilla/show_bug.cgi?id=28904

**Comment by pmqs** [comment]
> On 2/16/22 21:41, Yves Orton wrote: Module: Compress-Raw-Bzip2 *Description* During build uninitialized warnings are produced. They are bogus, but annoying and easily avoidable. Issue has been reported upstream as: [pmqs/Compress-Raw-Bzip2#4](https://github.com/pmqs/Compress-Raw-Bzip2/issues/4) <[pmqs/Compress-Raw-Bzip2#4](https://github.com/pmqs/Compress-Raw-Bzip2/issues/4)> And a PR to fix upstream: [pmqs/Compress-Raw-Bzip2#5](https://github.com/pmqs/Compress-Raw-Bzip2/pull/5) <[pmqs/Compress-Raw-Bzip2#5](https://github.com/pmqs/Compress-Raw-Bzip2/pull/5)>
> I should note that in past years I have reported build-time warnings in this distribution and similar ones to its very diligent upstream maintainer Paul Marquess. He reported being aware of them but noted that some of the source code is itself taken from upstream sources and that he prefers to change the code in these CPAN distributions only when the upstream code changes. (I'm not attempting to speak for him in this instance; just noting why those warnings haven't already been cured.) jimk

In general that is true. I prefer to report changes to the the definitive upstream source and then apply the change from there, but not always. 

In this instance the patch is very clear cut, so I've merged it.

**Comment by demerphq** [comment]
On Sat, 19 Feb 2022 at 14:58, Paul Marquess ***@***.***>
wrote:

> On 2/16/22 21:41, Yves Orton wrote: Module: Compress-Raw-Bzip2
> *Description* During build uninitialized warnings are produced. They are
> bogus, but annoying and easily avoidable. Issue has been reported upstream
> as: pmqs/Compress-Raw-Bzip2#4
> <https://github.com/pmqs/Compress-Raw-Bzip2/issues/4> <
> pmqs/Compress-Raw-Bzip2#4
> <https://github.com/pmqs/Compress-Raw-Bzip2/issues/4>> And a PR to fix
> upstream: pmqs/Compress-Raw-Bzip2#5
> <https://github.com/pmqs/Compress-Raw-Bzip2/pull/5> <
> pmqs/Compress-Raw-Bzip2#5
> <https://github.com/pmqs/Compress-Raw-Bzip2/pull/5>>
> I should note that in past years I have reported build-time warnings in
> this distribution and similar ones to its very diligent upstream maintainer
> Paul Marquess. He reported being aware of them but noted that some of the
> source code is itself taken from upstream sources and that he prefers to
> change the code in these CPAN distributions only when the upstream code
> changes. (I'm not attempting to speak for him in this instance; just noting
> why those warnings haven't already been cured.) jimk
>
> In general that is true. I prefer to report changes to the the definitive
> upstream source and then apply the change from there, but not always.
>
> In this instance the patch is very clear cut, so I've merged it.
>
Thanks!

cheers,
Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by pmqs** [comment]
> I filed a ticket with upstream libraries bug tracker:
> 
> https://sourceware.org/bugzilla/show_bug.cgi?id=28904

Thanks @demerphq ! I was going to do that, but you beat me to it. 

I'm not sure that sourceware is the correct place for bzip2 bug reports anymore. I think they have moved to [GitLab](https://gitlab.com/bzip2/bzip2.) The [bzip2 homepage](http://www.bzip.org/) isn't much help, but there does seem to be more recent activity on GitLab.

There was another small change I needed to pass upstream, so I've created a single change for gitlab that includes both. See https://gitlab.com/bzip2/bzip2/-/merge_requests/48

**Comment by demerphq** [comment]
On Sat, 19 Feb 2022 at 16:19, Paul Marquess ***@***.***>
wrote:

> I filed a ticket with upstream libraries bug tracker:
>
> https://sourceware.org/bugzilla/show_bug.cgi?id=28904
>
> Thanks @demerphq <https://github.com/demerphq> ! I was going to do that,
> but you beat me to it.
>
> I'm not sure that sourceware is the correct place for bzip2 bug reports
> anymore. I think they have moved to GitLab
> <https://gitlab.com/bzip2/bzip2.> The bzip2 homepage
> <http://www.bzip.org/> isn't much help, but there does seem to be more
> recent activity on GitLab.
>
> There was another small change I needed to pass upstream, so I've created
> a single change for gitlab that includes both. See
> https://gitlab.com/bzip2/bzip2/-/merge_requests/48
>
Oh cool, I didnt find that. Nice to know. Out of curiosity should there
also be an issue reported to go along with the MR?

cheers
Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by pmqs** [comment]
hmm, not sure about that. I've created one just in case.  See https://gitlab.com/bzip2/bzip2/-/issues/34

**Comment by jkeenan** [comment]
At least as of commit 9155444267, I'm not getting any of these build-time warnings when compiling with `gcc12` on FreeBSD-12.  Am self-assigning this ticket for the purpose of closing it in 7 days unless there is a serious objection.

**Comment by jkeenan** [comment]
> At least as of commit [9155444](https://github.com/Perl/perl5/commit/915544426781d184e3b057e63a20c089a32d3eba), I'm not getting any of these build-time warnings when compiling with `gcc12` on FreeBSD-12. Am self-assigning this ticket for the purpose of closing it in 7 days unless there is a serious objection.

Closing as per schedule.
