### ISSUE TITLE
[doc] isBool() referencing to Scalar::Util, but missing there 

### ISSUE THREAD

**Issue by bekuno** [Perl/perl5#19446]
**Where**
https://github.com/Perl/perl5/blob/blead/pod/perl5354delta.pod#stable-boolean-tracking

**Description**
The delta documentation states that a new function `isBool()` is now included in Scalar::Util.
The update section says that `Scalar::Util` has been updated from version 1.56 to 1.56_001.
Now `Scalar::Util` is at version 1.61, but there is no documentation for `isBool()`.

**Comment by Grinnz** [comment]
This was true in 5.35.4: https://perldoc.perl.org/5.35.4/Scalar::Util

But it was removed because the function was added to builtin instead.

The release note will need to be corrected when the perldelta for 5.36 is compiled.

**Comment by Grinnz** [comment]
Note that these dev perldeltas are primarily for internal use and may not represent what will end up in the next stable release (5.36.0). Consider bringing up issues with them on [irc](https://www.perl.org/community.html) as there is a high probability no action needs to be taken.

**Comment by bekuno** [comment]
I should use https://perldoc.perl.org as additional resource besides https://metacpan.org :-)

The change from `Scalar::Util` to `builtin` should be included in the delta documentation, imho.
The `isBool()` was already removed in 5.35.5.
