### ISSUE TITLE
[doc] builtin function documentation missing or a false reference

### ISSUE THREAD

**Issue by bekuno** [Perl/perl5#19444]
**Where**
https://github.com/Perl/perl5/blob/blead/pod/perl5357delta.pod

**Description**
In the section https://github.com/Perl/perl5/blob/blead/pod/perl5357delta.pod#builtin-functions is a link (two times) which willreference to the documentation for `builtin`: https://metacpan.org/pod/builtin.
This documentation does not exist.
Instead the current documentation is only included in the file https://github.com/Perl/perl5/blob/blead/lib/builtin.pm.

**Comment by Grinnz** [comment]
It does exist, just not in a stable version of Perl that metacpan will index yet. You can see the link works correctly at https://perldoc.perl.org/5.35.7/perl5357delta
