### ISSUE TITLE
Empty url passed for Mojo::Useragent Transactor

### ISSUE THREAD

**Issue by itsme300** [Perl/perl5#19458]
The below code hits 2 urls(jira and jfrog) which are store in a hash. Since hash values are read randomly, the error mentioned is reproduced 100% if jira is read first.

`my %urls = (
			'jira' => {
						'url' => 'https://jira.com:123/rest/api/2/issue/', 
						'token' => 'JIRA_TOKEN'
						},
			'jfrog' => {
							'url' => 'https://jfrog.com/artifactory/api/storage/path/to/artifacts',
							'token' => 'JFROG_TOKEN'
							}
			);
IO::Socket::SSL::set_defaults(SSL_verify_mode => IO::Socket::SSL::SSL_VERIFY_NONE,);
$urls_ua = Mojo::UserAgent->new();
for my $outer_elem ( keys %urls ) {
	for my $inner_elem ( keys %{$urls{$outer_elem}} ) {
		if ( !$ENV{$urls{$outer_elem}{'token'}} ) {
			$url = Mojo::URL->new($urls{$outer_elem}->{'url'})->userinfo('username:password');
		}
		else {
			if ( $inner_elem eq "jira" ) {
				$tx->req->headers->authorization("Bearer $ENV{$urls{$outer_elem}->{'token'}}");
				$url = Mojo::URL->new($urls{$outer_elem}->{'url'})
			}
		}
		print "logging in to $urls{$outer_elem}->{'url'}\n";
		$tx = $urls_ua->get($url);
		my $res = $tx->res->code;
		print "\nhttp code : $res \n";
		last;
	}
}`

Error:
logging in to https://jira.com:123/rest/api/2/issue/
**
Use of uninitialized value $url in pattern match (m//) at C:/StPerl530_x64/perl/vendor/lib/Mojo/UserAgent/Transactor.pm line 119.
Use of uninitialized value $url in concatenation (.) or string at C:/StPerl530_x64/perl/vendor/lib/Mojo/UserAgent/Transactor.pm line 119.
**
http code : 404
logging in to https://jfrog.com/artifactory/api/storage/artifacts
http code : 200

Debug Trace:

`logging in to https://jira.com:123/rest/api/2/issue/
Use of uninitialized value $url in pattern match (m//) at C:/StPerl530_x64/perl/vendor/lib/Mojo/UserAgent/Transactor.pm line 119.
 at C:/StPerl530_x64/perl/vendor/lib/Mojo/UserAgent/Transactor.pm line 119.
        Mojo::UserAgent::Transactor::tx(Mojo::UserAgent::Transactor=HASH(0x67b8e60), "GET", undef) called at C:/StPerl530_x64/perl/vendor/lib/Mojo/UserAgent.pm line 47
        Mojo::UserAgent::build_tx(Mojo::UserAgent=HASH(0x2746e70), "GET", undef) called at C:/StPerl530_x64/perl/vendor/lib/Mojo/UserAgent.pm line 37
        Mojo::UserAgent::get(Mojo::UserAgent=HASH(0x2746e70), undef) called at arjun_mojo_bug.pl line 44
Use of uninitialized value $url in concatenation (.) or string at C:/StPerl530_x64/perl/vendor/lib/Mojo/UserAgent/Transactor.pm line 119.
 at C:/StPerl530_x64/perl/vendor/lib/Mojo/UserAgent/Transactor.pm line 119.
        Mojo::UserAgent::Transactor::tx(Mojo::UserAgent::Transactor=HASH(0x67b8e60), "GET", undef) called at C:/StPerl530_x64/perl/vendor/lib/Mojo/UserAgent.pm line 47
        Mojo::UserAgent::build_tx(Mojo::UserAgent=HASH(0x2746e70), "GET", undef) called at C:/StPerl530_x64/perl/vendor/lib/Mojo/UserAgent.pm line 37
        Mojo::UserAgent::get(Mojo::UserAgent=HASH(0x2746e70), undef) called at arjun_mojo_bug.pl line 44`

**Comment by jkeenan** [comment]
> The below code hits 2 urls(jira and jfrog) which are store in a hash. Since hash values are read randomly, the error mentioned is reproduced 100% if jira is read first.
> 

Are you alleging a bug in the Perl 5 core distribution?  If not, then this is not the appropriate place to report this problem.

**Comment by itsme300** [comment]
I think the problem is with the module Mojo::UserAgent Transactor. I'll report in appropriate place. closing this for now.
