### ISSUE TITLE
Problem with function names 

### ISSUE THREAD

**Issue by Jamaika1** [Perl/perl5#19467]
I don't know perl5 is intended for gcc and can work with other libraries.
I have problem with combining some functions. My question is, can I change the names of some functions in perl5? 

I change function names :
do_close_perl5(a,b)
apply_perl5(a,b,c)
do_open_perl5(g, n, l, a, rm, rp, sf)
utf8_to_utf16_perl5
read_perl5(fd,b,s)
write_perl5(fd,b,s)

```
In file included from c:\msys1201\include\c++\12.0.1\bits\unique_ptr.h:36,
                 from c:\msys1201\include\c++\12.0.1\memory:76,
                 from c:\msys1201\x86_64-w64-mingw32\include\spdlog\common.h:12,
                 from c:\msys1201\x86_64-w64-mingw32\include\spdlog\spdlog.h:12,
                 from exif.cpp:38:
c:\msys1201\include\c++\12.0.1\tuple:1858:34: error: macro "apply" requires 3 arguments, but only 2 given
 1858 |     apply(_Fn&& __f, _Tuple&& __t)
      |                                  ^
In file included from cperl/perl.h:5762,
                 from exif.cpp:31:
cperl/embed.h:1244: note: macro "apply" defined here
 1244 | #define apply(a,b,c)            Perl_apply(aTHX_ a,b,c)
      |
In file included from c:\msys1201\x86_64-w64-mingw32\include\spdlog\fmt\fmt.h:24,
                 from c:\msys1201\x86_64-w64-mingw32\include\spdlog\common.h:45:
c:\msys1201\x86_64-w64-mingw32\include\spdlog\fmt\bundled\core.h:2658:30: error: macro "write" requires 3 arguments, but only 2 given
 2658 |       return write(begin, end);
      |                              ^
In file included from cperl/perl.h:5719:
cperl/win32iop.h:262: note: macro "write" defined here
  262 | #define write(fd,b,s)           win32_write(fd,b,s)
      |
c:\msys1201\x86_64-w64-mingw32\include\spdlog\fmt\bundled\core.h:2659:19: error: macro "write" requires 3 arguments, but only 2 given
 2659 |     write(begin, p);
      |                   ^
cperl/win32iop.h:262: note: macro "write" defined here
  262 | #define write(fd,b,s)           win32_write(fd,b,s)
      |
In file included from c:\msys1201\x86_64-w64-mingw32\include\spdlog\fmt\bundled\core.h:3234:
c:\msys1201\x86_64-w64-mingw32\include\spdlog\fmt\bundled\format.h:1193:47: error: macro "utf8_to_utf16" requires 4 arguments, but only 1 given
 1193 |   FMT_API explicit utf8_to_utf16(string_view s);
      |                                               ^
In file included from cperl/regexp.h:21,
                 from cperl/perl.h:4084:
cperl/utf8.h:89: note: macro "utf8_to_utf16" defined here
   89 | #define utf8_to_utf16(p, d, bytelen, newlen)                                \
      |
c:\msys1201\x86_64-w64-mingw32\include\spdlog\fmt\bundled\format.h:1377:61: error: macro "write" requires 3 arguments, but only 1 given
 1377 |                : base_iterator(out, write(reserve(out, size)));
      |                                                             ^
cperl/win32iop.h:262: note: macro "write" defined here
  262 | #define write(fd,b,s)           win32_write(fd,b,s)
      |
c:\msys1201\x86_64-w64-mingw32\include\spdlog\fmt\bundled\format.h:1392:45: error: macro "write" passed 4 arguments, but takes just 3
 1392 |                          locale_ref loc = {}) -> OutputIt {
      |                                             ^
cperl/win32iop.h:262: note: macro "write" defined here
  262 | #define write(fd,b,s)           win32_write(fd,b,s)
      |
c:\msys1201\x86_64-w64-mingw32\include\spdlog\fmt\bundled\format.h:1395:62: error: macro "write" passed 4 arguments, but takes just 3
 1395 |              : write(out, static_cast<int>(value), specs, loc);
      |                                                              ^
cperl/win32iop.h:262: note: macro "write" defined here
  262 | #define write(fd,b,s)           win32_write(fd,b,s)
      |
c:\msys1201\x86_64-w64-mingw32\include\spdlog\fmt\bundled\format.h:1489:49: error: macro "apply" requires 3 arguments, but only 2 given
 1489 |   Out apply(Out out, basic_string_view<C> digits) const {
      |                                                 ^
cperl/embed.h:1244: note: macro "apply" defined here
 1244 | #define apply(a,b,c)            Perl_apply(aTHX_ a,b,c)
```

**Comment by jkeenan** [comment]
> I don't know perl5 is intended for gcc and can work with other libraries. I have problem with combining some functions. My question is, can I change the names of some functions in perl5?
> 
> I change function names : do_close_perl5(a,b) apply_perl5(a,b,c) do_open_perl5(g, n, l, a, rm, rp, sf) utf8_to_utf16_perl5 read_perl5(fd,b,s) write_perl5(fd,b,s)
> 
> ```
> In file included from c:\msys1201\include\c++\12.0.1\bits\unique_ptr.h:36,
>                  from c:\msys1201\include\c++\12.0.1\memory:76,
>                  from c:\msys1201\x86_64-w64-mingw32\include\spdlog\common.h:12,
>                  from c:\msys1201\x86_64-w64-mingw32\include\spdlog\spdlog.h:12,
>                  from exif.cpp:38:
> c:\msys1201\include\c++\12.0.1\tuple:1858:34: error: macro "apply" requires 3 arguments, but only 2 given
>  1858 |     apply(_Fn&& __f, _Tuple&& __t)
>       |                                  ^
> In file included from cperl/perl.h:5762,
>                  from exif.cpp:31:
> cperl/embed.h:1244: note: macro "apply" defined here
>  1244 | #define apply(a,b,c)            Perl_apply(aTHX_ a,b,c)
>       |
> In file included from c:\msys1201\x86_64-w64-mingw32\include\spdlog\fmt\fmt.h:24,
>                  from c:\msys1201\x86_64-w64-mingw32\include\spdlog\common.h:45:
> c:\msys1201\x86_64-w64-mingw32\include\spdlog\fmt\bundled\core.h:2658:30: error: macro "write" requires 3 arguments, but only 2 given
>  2658 |       return write(begin, end);
>       |                              ^
> In file included from cperl/perl.h:5719:
> cperl/win32iop.h:262: note: macro "write" defined here
>   262 | #define write(fd,b,s)           win32_write(fd,b,s)
>       |
> c:\msys1201\x86_64-w64-mingw32\include\spdlog\fmt\bundled\core.h:2659:19: error: macro "write" requires 3 arguments, but only 2 given
>  2659 |     write(begin, p);
>       |                   ^
> cperl/win32iop.h:262: note: macro "write" defined here
>   262 | #define write(fd,b,s)           win32_write(fd,b,s)
>       |
> In file included from c:\msys1201\x86_64-w64-mingw32\include\spdlog\fmt\bundled\core.h:3234:
> c:\msys1201\x86_64-w64-mingw32\include\spdlog\fmt\bundled\format.h:1193:47: error: macro "utf8_to_utf16" requires 4 arguments, but only 1 given
>  1193 |   FMT_API explicit utf8_to_utf16(string_view s);
>       |                                               ^
> In file included from cperl/regexp.h:21,
>                  from cperl/perl.h:4084:
> cperl/utf8.h:89: note: macro "utf8_to_utf16" defined here
>    89 | #define utf8_to_utf16(p, d, bytelen, newlen)                                \
>       |
> c:\msys1201\x86_64-w64-mingw32\include\spdlog\fmt\bundled\format.h:1377:61: error: macro "write" requires 3 arguments, but only 1 given
>  1377 |                : base_iterator(out, write(reserve(out, size)));
>       |                                                             ^
> cperl/win32iop.h:262: note: macro "write" defined here
>   262 | #define write(fd,b,s)           win32_write(fd,b,s)
>       |
> c:\msys1201\x86_64-w64-mingw32\include\spdlog\fmt\bundled\format.h:1392:45: error: macro "write" passed 4 arguments, but takes just 3
>  1392 |                          locale_ref loc = {}) -> OutputIt {
>       |                                             ^
> cperl/win32iop.h:262: note: macro "write" defined here
>   262 | #define write(fd,b,s)           win32_write(fd,b,s)
>       |
> c:\msys1201\x86_64-w64-mingw32\include\spdlog\fmt\bundled\format.h:1395:62: error: macro "write" passed 4 arguments, but takes just 3
>  1395 |              : write(out, static_cast<int>(value), specs, loc);
>       |                                                              ^
> cperl/win32iop.h:262: note: macro "write" defined here
>   262 | #define write(fd,b,s)           win32_write(fd,b,s)
>       |
> c:\msys1201\x86_64-w64-mingw32\include\spdlog\fmt\bundled\format.h:1489:49: error: macro "apply" requires 3 arguments, but only 2 given
>  1489 |   Out apply(Out out, basic_string_view<C> digits) const {
>       |                                                 ^
> cperl/embed.h:1244: note: macro "apply" defined here
>  1244 | #define apply(a,b,c)            Perl_apply(aTHX_ a,b,c)
> ```

If you are changing the names of functions in Perl's internals (`*.c`, `*.h`, etc. files), you do so at your own peril.  It is unlikely that we would be able to help you out with problems you thereupon encounter.

Why do you want to do this?  What are you trying to accomplish?

**Comment by Leont** [comment]
This sort of problem between C++ and Perl is not uncommon. I would strongly recommend to include your C++ headers before including any perl headers, that should prevent most of these issues.

**Comment by Jamaika1** [comment]
> Why do you want to do this? What are you trying to accomplish?

I try to compile into gcc12 static grok c++17, spdlog c++17 and perl5 c.
If these are just internal perl5 functions that's fine. Unfortunately, spdlog uses the same names.

> This sort of problem between C++ and Perl is not uncommon. I would strongly recommend to include your C++ headers before including any perl headers, that should prevent most of these issues.

Do you mean using USE_CPLUSPLUS?

**Comment by Leont** [comment]
> Do you mean using USE_CPLUSPLUS?

No, I mean literally doing your `#include "perl.h"` after doing `#include <spdlog.h>`

**Comment by jkeenan** [comment]
Self-assigning this ticket for the purpose of closing it within a few days.
