### ISSUE TITLE
maint-5.34 Branch: ext/POSIX/t/sigaction.t Consistently Failing

### ISSUE THREAD

**Issue by cjg-cguevara** [Perl/perl5#19483]
ext/POSIX/t/sigaction.t is failing consistently on OpenBSD-7.0 for the maint-5.34 branch.

Please see smoke report at https://perl5.test-smoke.org/report/5016333 and corresponding log file at https://perl5.test-smoke.org/logfile/5016333 .

**Comment by Leont** [comment]
Is this a new failure or an old one? Did it come with a new OpenBSD version or with a recent perl version?
What does `grep 'define\s*HAS_SIGINFO_SI_' config.h` say?

**Comment by Leont** [comment]
Looking at that test: it should be skipped if `($^O.$Config{osvers}) =~ /^openbsd[0-7]\./`.

**Comment by jkeenan** [comment]
On 3/3/22 13:04, Leon Timmermans wrote:
> Looking at that test: it should be skipped if |($^O.$Config{osvers}) =~ 
> /^openbsd[0-7]\./|.
> 

The puzzling thing is that this test and all others are PASSing on 
Carlos's OpenBSD-7.0 smokers *on blead*.  The puzzling thing is this 
failure on maint-5.34.

**Comment by Leont** [comment]
> The puzzling thing is this failure on maint-5.34.

That actually explains everything. On maint-5.34 the skip is for `($^O.$Config{osvers}) =~ /^openbsd[0-6]\./`.

We may want to backport fa26526789fbf61d704bd6291823c16ed912f342 to 5.34.1

**Comment by steve-m-hay** [comment]
On Thu, 3 Mar 2022 at 18:42, Leon Timmermans ***@***.***>
wrote:

> The puzzling thing is this failure on maint-5.34.
>
> That actually explains everything. On maint-5.34 the skip is for ($^O.$Config{osvers})
> =~ /^openbsd[0-6]\./.
>
> We may want to backport fa26526
> <https://github.com/Perl/perl5/commit/fa26526789fbf61d704bd6291823c16ed912f342>
> to 5.34.1
>

Many thanks to all concerned for finding and fixing this.

**Comment by jkeenan** [comment]
@cjg-cguevara, from your smoke test reports I believe this failure has been fixed.  Can we close this ticket?

**Comment by jkeenan** [comment]
> @cjg-cguevara, from your smoke test reports I believe this failure has been fixed. Can we close this ticket?

On OpenBSD-6.9 I've got this test PASSing in both the main-5.34 branch and in build from tarball.  (My attempts to install an OpenBSD-7.1 VM have been unsuccessful.)

Closing.
