### ISSUE TITLE
UTF8 $0 patch is producing test failures.

### ISSUE THREAD

**Issue by demerphq** [Perl/perl5#19504]
**Description**
PR #19334 changed how we handle utf8 $0. But it is failing tests.

**Steps to Reproduce**
./perl t/op/magic.t
...
```
ok 104 - compare $0 to UTF8-flagged
ok 105 - compare $0 to non-UTF8-flagged
not ok 106 - /proc cmdline shows as expected (compare to UTF8-flagged)
# Failed test 106 - /proc cmdline shows as expected (compare to UTF8-flagged) at t/op/magic.t line 476
#      got '�'
# expected /(?^u:\A�\0)/
not ok 107 - /proc cmdline shows as expected (compare to non-UTF8-flagged)
# Failed test 107 - /proc cmdline shows as expected (compare to non-UTF8-flagged) at t/op/magic.t line 477
#      got '�'
# expected /(?^:\A�\0)/
ok 108 - warning after assignment of wide character
ok 109 - .. and the warning is about a wide character
ok 110 - .. and the UTF-8 version is written
not ok 111 - .. and /proc cmdline shows that
# Failed test 111 - .. and /proc cmdline shows that at t/op/magic.t line 497
#      got "hahaĀhoho"
# expected "hahaĀhoho\000"
ok 112 - $0 from wide -> local non-wide: no warning
ok 113 - one warning: wide -> local wide
ok 114 - one warning: non-wide -> local wide
```
**Expected behavior**
No test failures. 
**Perl configuration**
```
$ ./perl -Ilib -V
Summary of my perl5 (revision 5 version 35 subversion 10) configuration:
  Commit id: 7ea8b04b5a0e6952b7ffd5a8fd96468b72da6bea
  Platform:
    osname=linux
    osvers=4.15.0-166-generic
    archname=x86_64-linux-thread-multi
    uname='linux psykopsis 4.15.0-166-generic #174-ubuntu smp wed dec 8 19:07:44 utc 2021 x86_64 x86_64 x86_64 gnulinux '
    config_args='-Dusethreads -Doptimize=-g -d -Dusedevel -Dcc=ccache gcc -Dld=gcc -DDEBUGGING'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='gcc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-g'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -DDEBUGGING -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='7.5.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='gcc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=libc-2.27.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.27'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -g -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl): 
  Compile-time options:
    DEBUGGING
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_TRACK_MEMPOOL
    PERL_USE_DEVEL
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Mar  7 2022 14:05:56
  %ENV:
    PERLBREW_CONFIGURE_FLAGS="-de -Dcc=ccache\ gcc -Dld=gcc"
    PERLBREW_HOME="/home/yorton/.perlbrew"
    PERLBREW_MANPATH="/home/yorton/perl5/perlbrew/perls/perl-blead/man"
    PERLBREW_PATH="/home/yorton/perl5/perlbrew/bin:/home/yorton/perl5/perlbrew/perls/perl-blead/bin"
    PERLBREW_PERL="perl-blead"
    PERLBREW_ROOT="/home/yorton/perl5/perlbrew"
    PERLBREW_SHELLRC_VERSION="0.94"
    PERLBREW_VERSION="0.94"
  @INC:
    lib
    /usr/local/lib/perl5/site_perl/5.35.10/x86_64-linux-thread-multi
    /usr/local/lib/perl5/site_perl/5.35.10
    /usr/local/lib/perl5/5.35.10/x86_64-linux-thread-multi
    /usr/local/lib/perl5/5.35.10
```

**Comment by jkeenan** [comment]
> **Description** PR #19334 changed how we handle utf8 $0. But it is failing tests.
> 
> **Steps to Reproduce** ./perl t/op/magic.t ...
> 
> ```
> ok 104 - compare $0 to UTF8-flagged
> ok 105 - compare $0 to non-UTF8-flagged
> not ok 106 - /proc cmdline shows as expected (compare to UTF8-flagged)
> # Failed test 106 - /proc cmdline shows as expected (compare to UTF8-flagged) at t/op/magic.t line 476
> #      got '�'
> # expected /(?^u:\A�\0)/
> not ok 107 - /proc cmdline shows as expected (compare to non-UTF8-flagged)
> # Failed test 107 - /proc cmdline shows as expected (compare to non-UTF8-flagged) at t/op/magic.t line 477
> #      got '�'
> # expected /(?^:\A�\0)/
> ok 108 - warning after assignment of wide character
> ok 109 - .. and the warning is about a wide character
> ok 110 - .. and the UTF-8 version is written
> not ok 111 - .. and /proc cmdline shows that
> # Failed test 111 - .. and /proc cmdline shows that at t/op/magic.t line 497
> #      got "hahaĀhoho"
> # expected "hahaĀhoho\000"
> ok 112 - $0 from wide -> local non-wide: no warning

I have not been able to reproduce the failures reported in this ticket.

AFAIT, this is the commit that handled p.r. 19334:
```
commit 2d3b3561a39bb17fd6003fb262f52b3bc800770e
Author:     Felipe Gasper <felipe@felipegasper.com>
AuthorDate: Fri Jan 7 14:28:39 2022 -0500
Commit:     Karl Williamson <khw@cpan.org>
CommitDate: Sat Mar 5 21:06:05 2022 -0700

    Properly handle UTF8-flagged strings when assigning to $0.
```
I built a threaded, debugging perl at this commit on Linux using gcc as the C-compiler:
```
$ uname -mrs
Linux 5.10.13-x86_64-linode141 x86_64

$ gcc --version | head -1
gcc (Debian 4.9.2-10+deb8u2) 4.9.2

$ ./perl -Ilib -v | head -2 | tail -1
This is perl 5, version 35, subversion 10 (v5.35.10 (v5.35.9-82-g2d3b356)) built for x86_64-linux-thread-multi

$ ./perl -Ilib -V:config_args
config_args='-des -Dusedevel -Dusethreads -Doptimize=-g -d -Dusedevel -Dcc=gcc -Dld=gcc -DDEBUGGING'
```
When I ran the test file in question, all tests PASSed.
```
$ cd t; ./perl harness op/magic.t; cd -
op/magic.t .. ok       
All tests successful.
Files=1, Tests=208,  3 wallclock secs ( 0.12 usr  0.00 sys +  0.22 cusr  0.10 csys =  0.44 CPU)
Result: PASS
```
I should add that I was surprised to see the report of test failures, as the branch embodying this p.r. was in development for some time and hence was repeatedly exercised in our [Github actions](https://github.com/Perl/perl5/runs/5436607395?check_suite_focus=true).

Since I don't see where the test failures are coming from, I don't see the basis for the code which was recently merged to blead in https://github.com/Perl/perl5/pull/19505.  @demerphq, can you investigate?

**Comment by demerphq** [comment]
On Mon, 7 Mar 2022 at 23:34, James E Keenan ***@***.***>
wrote:

> *Description* PR #19334 <https://github.com/Perl/perl5/pull/19334>
> changed how we handle utf8 $0. But it is failing tests.
>
> *Steps to Reproduce* ./perl t/op/magic.t ...
>
> ok 104 - compare $0 to UTF8-flagged
>
> ok 105 - compare $0 to non-UTF8-flagged
>
> not ok 106 - /proc cmdline shows as expected (compare to UTF8-flagged)
>
> # Failed test 106 - /proc cmdline shows as expected (compare to UTF8-flagged) at t/op/magic.t line 476
>
> #      got '�'
>
> # expected /(?^u:\A�\0)/
>
> not ok 107 - /proc cmdline shows as expected (compare to non-UTF8-flagged)
>
> # Failed test 107 - /proc cmdline shows as expected (compare to non-UTF8-flagged) at t/op/magic.t line 477
>
> #      got '�'
>
> # expected /(?^:\A�\0)/
>
> ok 108 - warning after assignment of wide character
>
> ok 109 - .. and the warning is about a wide character
>
> ok 110 - .. and the UTF-8 version is written
>
> not ok 111 - .. and /proc cmdline shows that
>
> # Failed test 111 - .. and /proc cmdline shows that at t/op/magic.t line 497
>
> #      got "hahaĀhoho"
>
> # expected "hahaĀhoho\000"
>
> ok 112 - $0 from wide -> local non-wide: no warning
>
>
> I have not been able to reproduce the failures reported in this ticket.
>
> AFAIT, this is the commit that handled p.r. 19334:
>
> commit 2d3b3561a39bb17fd6003fb262f52b3bc800770e
>
> Author:     Felipe Gasper ***@***.***>
>
> AuthorDate: Fri Jan 7 14:28:39 2022 -0500
>
> Commit:     Karl Williamson ***@***.***>
>
> CommitDate: Sat Mar 5 21:06:05 2022 -0700
>
>
>
>     Properly handle UTF8-flagged strings when assigning to $0.
>
>
> I built a threaded, debugging perl at this commit on Linux using gcc as
> the C-compiler:
>
> $ uname -mrs
>
> Linux 5.10.13-x86_64-linode141 x86_64
>
> At first I thought that it was because I was on an older kernel, and I
still wonder if it might be that:

$ uname -mrs
Linux 4.15.0-166-generic x86_64

But:
$ ./perl -Ilib -MDevel::Peek -le'print $]; open my $fh, "<",
"/proc/$$/cmdline"; my $s= do{ local $/; <$fh>}; Dump($s); print $s=~/\0\z/
? "has null" : "no null";'
5.035010
SV = PV(0x55ebdf99feb8) at 0x55ebdfa25608
  REFCNT = 1
  FLAGS = (POK,IsCOW,pPOK)
  PV = 0x55ebdf9b8988 "./perl\x00-Ilib\x00-MDevel::Peek\x00-leprint $];
open my $fh, \"<\", \"/proc/$$/cmdline\"; my $s= do{ local $/; <$fh>};
Dump($s); print $s=~/\\0\\z/ ? \"has null\" : \"no null\";\x00"\0
  CUR = 160
  LEN = 168
  COW_REFCNT = 1
has null

shows that the strings have nulls.

However if I patch t/op/magic.t to Dump the result from reading
/proc/$$/cmdline and remove the null stripping guard:

diff --git a/t/op/magic.t b/t/op/magic.t
index 442735df49..b1bc131237 100644
--- a/t/op/magic.t
+++ b/t/op/magic.t
@@ -469,7 +469,9 @@ EOP
     open my $rfh, '<', "/proc/$$/cmdline"
       or skip "failed to read '/proc/$$/cmdline': $!", $skip;
     my $got = do { local $/; <$rfh> };
-    $got=~s/\0\z//;
+    use Devel::Peek;
+    Dump($got);
+    #$got=~s/\0\z//;
     return $got;
   };

the tests pass, and the Dump shows no null. The Sv's are properly null
terminated, but that is not part of the perl visible string.

$ ./perl t/op/magic.t
...
ok 104 - compare $0 to UTF8-flagged
ok 105 - compare $0 to non-UTF8-flagged
SV = PV(0x556a56692058) at 0x556a566895c0
  REFCNT = 1
  FLAGS = (POK,pPOK)
  PV = 0x556a56494c48 "\xE9"\0
  CUR = 1
  LEN = 10
ok 106 - /proc cmdline shows as expected (compare to UTF8-flagged)
ok 107 - /proc cmdline shows as expected (compare to non-UTF8-flagged)
ok 108 - warning after assignment of wide character
ok 109 - .. and the warning is about a wide character
ok 110 - .. and the UTF-8 version is written
SV = PV(0x556a56692058) at 0x556a566895c0
  REFCNT = 1
  FLAGS = (POK,pPOK)
  PV = 0x556a56494c48 "haha\xC4\x80hoho"\0
  CUR = 10
  LEN = 16
ok 111 - .. and /proc cmdline shows that
ok 112 - $0 from wide -> local non-wide: no warning
ok 113 - one warning: wide -> local wide
ok 114 - one warning: non-wide -> local wide
...

The old tests expected to see a perl visible NULL in there. I bet if you do
the same you will see the tests fail, and the Dump() contains an extra
null. I know that the tests failed in github CI when I pushed without the
s/\0\z// fix as I removed the NULL from the test strings they expect.

I should add that I was surprised to see the report of test failures, as
> the branch embodying this p.r. was in development for some time and hence
> was repeatedly exercised in our Github actions
> <https://github.com/Perl/perl5/runs/5436607395?check_suite_focus=true>.
>
I can only assume it's related to the kernel version difference, but so far
I haven't found a related bug report.

I just checked the code responsible for doing this: S_set_dollarzero() and
it doesn't seem to null terminate things. So I assume that in a later
kernel the result from proc/$$/cmdline was changed to armor itself against
this, but so far I can't prove it.  I got nowhere searching for a
kernel bug report related to this.  However digging into the linux
changelog I found that the linux kernal /proc/pid/cmdline stuff was
reworked in between 5.2 and 5.3, my bet is that it is related:

https://github.com/torvalds/linux/commit/d26d0cd97c88eb1a5704b42e41ab443406807810
***@***.***/

Also related is this:
https://github.com/torvalds/linux/commit/2954152298c37804dab49d630aa959625b50cf64

Those patches were merged into the 5.3 kernel. You are on 5.10, I am on 4.15

Found using
git log -P --grep 'proc/[^/]+/cmdline'

in the linux git repo.

While I haven't found the *exact* commit that changed this behavior and I
don't know enough about linux kernel dev to bisect for it, but my gut
instinct is this is a kernel change and older kernels need my test patch
and newer ones don't. A good way to prove it would be to test the patched
magic.t on a 5.2 kernel and a 5.3 kernel. If I am right with the patch it
should pass up to 5.2 and fail afterwards.

cheers,
Yves

**Comment by jkeenan** [comment]
Here is some evidence in support of the hypothesis that these test failures will only be observed on **older** versions of Linux.

On our dromedary development server, we have a **very** old (IMO) version of Linux.  I built a perl at the offending commit there and got the test failures which @demerphq observed on "Linux 4" but which I did not observe on "Linux 5.10".
```
$ uname -mrs
Linux 3.10.0-1160.15.2.el7.x86_64 x86_64

$ gcc --version | head -n 1
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

$ git describe
v5.35.9-82-g2d3b356

$ ./perl -Ilib -V:config_args
config_args='-des -Dusedevel -Dusethreads -Doptimize=-g -d -Dusedevel -Dcc=gcc -Dld=gcc -DDEBUGGING';

$ cd t; ./perl harness op/magic.t; cd -
op/magic.t .. 66/208 # Failed test 106 - /proc cmdline shows as expected (compare to UTF8-flagged) at op/magic.t line 476
#      got '�'
# expected /(?^u:\A�\0)/
# Failed test 107 - /proc cmdline shows as expected (compare to non-UTF8-flagged) at op/magic.t line 477
#      got '�'
# expected /(?^:\A�\0)/
# Failed test 111 - .. and /proc cmdline shows that at op/magic.t line 497
#      got "hahaĀhoho"
# expected "hahaĀhoho\000"
op/magic.t .. Failed 3/208 subtests 
	(less 4 skipped subtests: 201 okay)

Test Summary Report
-------------------
op/magic.t (Wstat: 0 Tests: 208 Failed: 3)
  Failed tests:  106-107, 111
Files=1, Tests=208,  4 wallclock secs ( 0.07 usr  0.01 sys +  0.19 cusr  0.13 csys =  0.40 CPU)
Result: FAIL
```

**Comment by demerphq** [comment]
Closing this issue as it is long resolved now.
