### ISSUE TITLE
.mailmap is not listed in MANIFEST and tests don't notice.

### ISSUE THREAD

**Issue by demerphq** [Perl/perl5#19511]
**Description**
The .mailmap is not listed in the MANIFEST file and tests don't notice.

**Steps to Reproduce**
make test. nothing fails, but 

git grep .mailmap MANIFEST

**Expected behavior**
It is not clear to me if the test should fail or not.

**Perl configuration**
N/A but this is true in bleadperl at 5.35.10:
```
$ ./perl -v

This is perl 5, version 35, subversion 10 (v5.35.10 (v5.35.9-105-g8d104cc776)) built for x86_64-linux-thread-multi
(with 15 registered patches, see perl -V for more detail)

```

**Comment by demerphq** [comment]
Related issue: https://github.com/Perl/perl5/issues/19512

**Comment by atoomic** [comment]
I think this is fine to do not ship `.mailmap` as part of a tarball... 
it's similar to files like `.gitignore`, `.github/workflow/*`... and we should not published them
the error IMO is to publish the tools relying on such files...

**Comment by demerphq** [comment]
Lets close this ticket and use https://github.com/Perl/perl5/issues/19512 for this conversation.

**Comment by demerphq** [comment]
Duplicate of #19512
