### ISSUE TITLE
'perl -v' | Strings requiring up-to-date information

### ISSUE THREAD

**Issue by Ricky-Tigg** [Perl/perl5#19522]
**Description**
Strings requiring up-to-date information

**Expected mentions**
- `Copyright 1987–2022, Larry Wall` | _note_: "`–`", not "`-`".
- `https://www.perl.org/`

**To reproduce**
```
$ perl -v | awk 'NF' | sed -n '1,2p;7p'
This is perl 5, version 34, subversion 0 (v5.34.0) built for x86_64-linux-thread-multi
Copyright 1987-2021, Larry Wall
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

**Comment by hvds** [comment]
> **Description** Strings requiring up-to-date information
> 
> **Expected mentions**
> 
>     * `Copyright 1987–2022, Larry Wall` | _note_: "`–`", not "`-`".

What will that look like on a non-utf8-aware terminal? This sounds unwise to me.

**Comment by Ricky-Tigg** [comment]
I would not have though about it without your comment. You are the **one** who knows.

**Comment by eserte** [comment]
The copyright end year of 2021 is correct for perl 5.34.0, as it was released in May 2021. The latest 5.35.x releases already have an end date of 2022.
