### ISSUE TITLE
dist/Locale-Maketext/t/*.t: two tests failing in some DEBUGGING builds since v5.35.10

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#19552]
Since the release of perl-5.35.10, test file `dist/Locale-Maketext/t/30_eval_dollar_at.t` has begun to fail in certain smoke-testing reports.  These failures can be searched for at this [URL](https://perl5.test-smoke.org/submatrix?test=../dist/Locale-Maketext/t/30_eval_dollar_at.t&pversion=5.35.11).

What these 5 failure reports have in common is that they were all done on `-DDEBUGGING` builds.  3 of the failures are from my FreeBSD-12 smoker; the other 2 are from @Tux on HP-UX.

I admit that I have not been able to reproduce these failures in a `-DDEBUGGING` build of a "regular" `git` checkout of the core distribution.  But in the context of Test-Smoke, this file is failing with output like [this](https://perl5.test-smoke.org/report/5016990):
```
Test failures:
~~ ../dist/Locale-Maketext/t/30_eval_dollar_at.t ............... FAILED No plan found in TAP output
```
Since I cannot yet consistently reproduce this failure, I have not attempted bisection.  The test file itself has not been modified since 2013.  `dist/Locale-Maketext/lib/Locale/Maketext.pm` last changed on January 19 of this year:
```
commit 0b66d70fe7769af01a6bea67bd2ea91b2404eb4b
Author:     Mike Fulton <mikefultonpersonal@gmail.com>
AuthorDate: Fri Jan 14 16:23:47 2022 -0800
Commit:     Karl Williamson <khw@cpan.org>
CommitDate: Wed Jan 19 18:15:54 2022 -0700

```
However, if the failures were due to that commit, I would have expected them to show up in smoke test reports in January.

Any ideas?

**Comment by jkeenan** [comment]
Here is an example of the smokecurrent.log file on the failing runs:
```
Configuration: -Dusedevel -Duseithreads -Doptimize="-O2 -pipe -fstack-protector -fno-strict-aliasing" -Dcc="clang -Qunused-arguments" -DDEBUGGING
------------------------------------------------------------------------------

../dist/Locale-Maketext/t/30_eval_dollar_at.t...............FAILED
No plan found in TAP output

Configuration: -Dusedevel -Duseithreads -Doptimize="-O2 -pipe -fstack-protector -fno-strict-aliasing" -Dcc="clang -Qunused-arguments"
------------------------------------------------------------------------------

Configuration: -Dusedevel -Duseithreads -Doptimize="-O2 -pipe -fstack-protector -fno-strict-aliasing" -Dcc="clang -Qunused-arguments" -DDEBUGGING
------------------------------------------------------------------------------

../dist/Locale-Maketext/t/30_eval_dollar_at.t...............FAILED
No plan found in TAP output

Configuration: -Dusedevel -Duseithreads -Doptimize="-O2 -pipe -fstack-protector -fno-strict-aliasing" -Dcc="clang -Qunused-arguments"
------------------------------------------------------------------------------
```

**Comment by jkeenan** [comment]
> Since the release of perl-5.35.10, test file `dist/Locale-Maketext/t/30_eval_dollar_at.t` has begun to fail in certain smoke-testing reports. These failures can be searched for at this [URL](https://perl5.test-smoke.org/submatrix?test=../dist/Locale-Maketext/t/30_eval_dollar_at.t&pversion=5.35.11).
> 
> What these 5 failure reports have in common is that they were all done on `-DDEBUGGING` builds. 3 of the failures are from my FreeBSD-12 smoker; the other 2 are from @Tux on HP-UX.
> 

Four further observations:

1. This failure has now been observed on FreeBSD-13 (in addition to FreeBSD-12); see https://perl5.test-smoke.org/report/5017038.
2.  This failure has now also been observed on OpenBSD-7.0; see https://perl5.test-smoke.org/report/5017041.
3. Most runs on `[stdio]` fail.  I haven't seen any runs on `[perlio]` that do not pass.
4. We're now also observing failures on a different test file within the same distribution:  dist/Locale-Maketext/t/04_use_external_lex_cache.t.  See:  [here](https://perl5.test-smoke.org/submatrix?test=../dist/Locale-Maketext/t/04_use_external_lex_cache.t&pversion=5.35.11).

@khwilliamson, can you take a look?  Thanks.

**Comment by jkeenan** [comment]
@MikeFultonDev, please have a look at [this issue](https://github.com/Perl/perl5/issues/19552).

Thank you very much.
Jim Keenan

**Comment by MikeFultonDev** [comment]
investigating

**Comment by MikeFultonDev** [comment]
@khwilliamson, I am not that familiar with smoke tests. I have a Mac and z/OS at my disposal. How do I see if it also fails for Mac? Is there a smoke test for it? If not, is there a dev system for one of the failing platforms I could look at? 
This is the PR that my changes went under: https://github.com/Perl/perl5/pull/19345
Nothing I did is (knowingly) platform specific, so I'm expecting that perhaps I missed updating a required file for DEBUG that I wasn't aware of?

**Comment by jkeenan** [comment]
The failures in dist/Locale-Maketext/t/04_use_external_lex_cache.t are now appearing on one Linux smoke-testing rig.  See:

https://perl5.test-smoke.org/report/5017075

**Comment by hvds** [comment]
Do we have documented somewhere how smoke tests are set up and run? It's always possible that there is some critical difference between that and a manual Configure and make test cycle which is making it harder to reproduce.

**Comment by khwilliamson** [comment]
I now am able to reproduce it on an hp-ux box.

The problem manifests as
Assertion failed: start <= s, file inline.h, line 2155

So now the debugging can begin

**Comment by jkeenan** [comment]
> I now am able to reproduce it on an hp-ux box.
> 
> The problem manifests as Assertion failed: start <= s, file inline.h, line 2155
> 
> So now the debugging can begin

Also now reproduced on the FreeBSD-12 box:
```
$ ./perl -Ilib -V:config_args
config_args='-des -Dusedevel -Duseithreads -DDEBUGGING';

$ cd t; TEST_JOBS=1 PERLIO=stdio ./perl harness -v ../dist/Locale-Maketext/t/30_eval_dollar_at.t; cd -
../dist/Locale-Maketext/t/30_eval_dollar_at.t .. Assertion failed: (start <= s), function Perl_utf8_hop_back, file ./inline.h, line 2155.
No subtests run 

Test Summary Report
-------------------
../dist/Locale-Maketext/t/30_eval_dollar_at.t (Wstat: 134 Tests: 0 Failed: 0)
  Non-zero wait status: 134
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  0 wallclock secs ( 0.01 usr  0.00 sys +  0.03 cusr  0.02 csys =  0.06 CPU)
Result: FAIL
```
Other testers were also getting errors in dist/Locale-Maketext/t/04_use_external_lex_cache.t.  I was not, nor am I getting them with the above configuration/test invocation.

**Comment by jkeenan** [comment]
Manual before/after results; commit suggested by @khwilliamson on IRC #p5p
```
$ checkoutblead
$ git checkout 32b87797e986f5d99836e16ea6b9d9ff5a56d3be^
$ sh ./Configure -des -Dusedevel -Duseithreads -DDEBUGGING && make test_prep; cd t; PERLIO=stdio ./perl harness -v ../dist/Locale-Maketext/t/30_eval_dollar_at.t; cd -
...
./perl -Ilib -I. -f pod/buildtoc -q
cd t && (rm -f perl; /bin/ln -s ../perl perl)

ok 1 - straight forward _AUTO string test
ok 2 - $@ isn't altered during calls to maketext
ok 3 - no return from eval
ok 4 - $@ shows that ] was unbalanced
ok 5 - 0 return if module is missing when _try_use is called
ok 6 - $@ is unmodified by a failed _try_use
ok 7 - 1 return using valid module Locale::Maketext::Guts
ok 8 - $@ is clean after failed _try_use
ok 9 - die event calling failure_handler on bad code
ok 10 - $@ is re-written as expected.
ok 11 - Make sure $@ is localized when passed to maketext
ok 12 - $@ wasn't modified during call
ok
All tests successful.
Files=1, Tests=12,  0 wallclock secs ( 0.01 usr  0.01 sys +  0.09 cusr  0.01 csys =  0.12 CPU)
Result: PASS

#####

$ checkoutblead
$ git checkout 32b87797e986f5d99836e16ea6b9d9ff5a56d3be
$ sh ./Configure -des -Dusedevel -Duseithreads -DDEBUGGING && make test_prep; cd t; PERLIO=stdio ./perl harness -v ../dist/Locale-Maketext/t/30_eval_dollar_at.t; cd -
...

./perl -Ilib -I. -f pod/buildtoc -q
cd t && (rm -f perl; /bin/ln -s ../perl perl)
Assertion failed: (start <= s), function Perl_utf8_hop_back, file ./inline.h, line 2155.
No subtests run 

Test Summary Report
-------------------
../dist/Locale-Maketext/t/30_eval_dollar_at.t (Wstat: 134 Tests: 0 Failed: 0)
  Non-zero wait status: 134
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  0 wallclock secs ( 0.01 usr  0.00 sys +  0.02 cusr  0.00 csys =  0.02 CPU)
Result: FAIL
```
The problematic commit:
```
commit 32b87797e986f5d99836e16ea6b9d9ff5a56d3be
Author:     Karl Williamson <khw@cpan.org>
AuthorDate: Sat Feb 12 21:47:13 2022 -0700
Commit:     Karl Williamson <khw@cpan.org>
CommitDate: Sat Mar 19 23:17:51 2022 -0600

    toke.c: merge loops, multi-byte delim
```

**Comment by jkeenan** [comment]
For me the failures have been fixed by:
```
commit 2ea73191f792b62c945c77ff01626704f7523ed0 (HEAD -> blead, origin/blead, origin/HEAD)
Author:     Karl Williamson <khw@cpan.org>
AuthorDate: Thu Mar 24 20:31:44 2022
Commit:     Karl Williamson <khw@cpan.org>
CommitDate: Thu Mar 24 22:13:30 2022

    toke.c: Add missing ptr update
```
Let's keep this ticket open until we get smoke-test reports from all the platforms mentioned above which were experiencing failures.

**Comment by khwilliamson** [comment]
This is passing all the smoke tests
