### ISSUE TITLE
Test needed for #16887

### ISSUE THREAD

**Issue by khwilliamson** [Perl/perl5#19606]
Commit bb5e773d6fb68865d8e2c5a392215c27c7b49636 refactored code so that the test added to verify that #16887 is fixed no longer is applicable.  A new test should be created.

Module:

**Description**

**Steps to Reproduce**

**Expected behavior**

**Perl configuration**

```
# perl -V output goes here
```

**Comment by tonycoz** [comment]
Which is the correct issue number #16867 (in the title) or #16887 (in the body)?

Neither appears related to the quoted commit.

**Comment by jkeenan** [comment]
> Which is the correct issue number #16867 (in the title) or #16887 (in the body)?
> 
> Neither appears related to the quoted commit.

@khwilliamson, can you help @tonycoz out with the question above?  Thanks.

**Comment by khwilliamson** [comment]
It is #16887	 I spent an hour or so trying to understand this ticket.  But I don't now understand how the commit bypasses the tests added.  I'm sorry I didn't give enough details in this ticket description.

At this point, it would require a bunch more effort to figure things out, and I don't think that it's worth it.  I'm in favor of closing it.
