### ISSUE TITLE
IO::Socket::IP generates a socket object with wrong sockdomain when an IPv4 connect succeeds after a failed IPv6 attempt

### ISSUE THREAD

**Issue by Yaribz** [Perl/perl5#19605]
### **Test case:**

Trying to connect to a hostname which can be resolved in both IPv6 and IPv4, but only the IPv4 address can be connected to (on the requested port), from a system which is configured to try IPv6 first.

### **What happens:**
- `IO::Socket::IP` tries to connect to the IPv6 address first, so it creates a `IO::Socket` object with `AF_INET6` family
- The connection fails, so `IO::Socket::IP` automatically tries the next address entry which is an IPv4 address
- `IO::Socket::IP` uses its "unbelievably dodgy hack" to keep the fileno unchanged in this case, it actually creates a new socket manually instead of calling the `SUPER` method: https://github.com/Perl/perl5/blob/bb5e773d6fb68865d8e2c5a392215c27c7b49636/cpan/IO-Socket-IP/lib/IO/Socket/IP.pm#L980 The problem is that the `SUPER` method (`IO::Socket::socket`) doesn't simply create the socket, it also updates some `IO::Socket` internal fields, in particular the ones storing the domain and the type of the socket, as seen here: https://github.com/Perl/perl5/blob/bb5e773d6fb68865d8e2c5a392215c27c7b49636/dist/IO/lib/IO/Socket.pm#L85
- So when `IO::Socket::IP` uses its hack to update the current socket, these steps are skipped and the `io_socket_domain` field can mismatch the actual new socket type. Unfortunately the `IO::Socket::sockdomain` function actually uses this field as a cache: https://github.com/Perl/perl5/blob/bb5e773d6fb68865d8e2c5a392215c27c7b49636/dist/IO/lib/IO/Socket.pm#L369
- The result is that when calling the `IO::Socket::sockdomain` method on a socket created this way, it returns `AF_INET6` whereas the actual socket family is `AF_INET`.

### **Workaround until this is fixed:**

From user code, after a socket has been created and connected, manually update the `io_socket_domain` field of the socket object in case the first address tried by `IO::Socket::IP` has a different family than the address successfully connected in the end:
`${*$sock}{'io_socket_domain'}=Socket::sockaddr_family($sock->sockname());`

This workaround doesn't seem to work on Windows systems (the IPv4 connect which should succeed after the failed IPv6 connect actually fails with "Bad address" error).

**Comment by Yaribz** [comment]
Here is a code snippet to test the "dup2 hack" of `IO::Socket::IP` :

```use warnings;
use strict;

use POSIX 'dup2';
use Socket;

my ($testHost,$testPort)=('perl.org',443);
my $tcpProto=getprotobyname('tcp');

socket(my $sock, PF_INET6, SOCK_STREAM, $tcpProto)
  or die "Could not create IPv6 socket - $!\n";
socket(my $sock2, PF_INET, SOCK_STREAM, $tcpProto)
  or die "Could not create IPv4 socket - $!\n";

dup2($sock2->fileno,$sock->fileno)
  or die "Unable to dup2 IPv4 socket onto IPv6 socket - $!\n";

my $iaddr=inet_aton($testHost);
my $paddr=sockaddr_in($testPort,$iaddr);
connect($sock,$paddr)
  or die "Failed to connect to $testHost:$testPort - $!\n";

print "Successfully connected to $testHost:$testPort\n";
```

When executed on a Linux system, it works:
`Successfully connected to perl.org:443`

When executed on a Windows system (Windows 10 21H1 19043.1586, Strawberry Perl 5.32.1-64bit), it fails:
`Failed to connect to perl.org:443 - Bad address`

This means that on Windows systems the `IO::Socket::IP` module will never be able to connect successfully to an address whose family is different than the first one tried when resolving the hostname. So it actually fails before the workaround I explained above can even be tried.

**Comment by xenu** [comment]
IO::Socket::IP is maintained on CPAN. Bugs should be reported on its bugtracker here: https://rt.cpan.org/Public/Dist/Display.html?Name=IO-Socket-IP

It seems you have already [done that](https://rt.cpan.org/Public/Bug/Display.html?id=142205), so I'm closing this ticket.

**Comment by Yaribz** [comment]
Yes sorry, I realized only afterwards that I hadn't reported this issue in the best place.
I should have closed this one.

I guess it makes sense to report here the secondary part of the issue though (`POSIX::dup2` corrupting sockets on Windows), but as it seems this issue (or platform specific behavior) is already known...
