### ISSUE TITLE
Smart match bug?

### ISSUE THREAD

**Issue by agguser** [Perl/perl5#19626]
It seems that `$r->[0]` and `@$r[0]` as a left operand of `~~` (smart match) cause different results.
```
$ perl -E '
   use strict; use warnings;
   use experimental "smartmatch";
   say $^V;

   my $r = [qw(a 11)];
   my @v = qw(a b c);

   say $r->[0] ~~ @v;
   say @$r[0] ~~ @v;
   say "@$r[0]" ~~ @v;
   '
v5.34.0
1   # match as expected
    # not match! Bug? Isn't @$r[0] a scalar?
1   # match
```

**Comment by Leont** [comment]
I suspect you meant `$$r[1]` instead of `@$r[0]`. The latter is a slice, and will therefor not do what you expect it to do (it will list compare, so it will match `qw(a)`
