### ISSUE TITLE
Unicode::Normalize does not use ppport.h

### ISSUE THREAD

**Issue by toddr** [Perl/perl5#19637]
From @khwilliamson: Having looked at this, I now realize that U:N should have been using ppport.h for a long time.  That fixes a bunch of UTF-8 bugs and holes that this otherwise could be subject to.  I'll work on a full PR for it

Any module on cpan that calls UTF-8 perl functions should be using Devel::PPPort to get the modern treatment.

_Originally posted by @khwilliamson in https://github.com/Perl/perl5/issues/19631#issuecomment-1100922593_

**Comment by demerphq** [comment]
Related, see: https://github.com/Perl/perl5/pull/19640

**Comment by khwilliamson** [comment]
Fixed by c2e0d3bb9f0e8d6999bfa6c5d969f505012bcf72
