### ISSUE TITLE
getpgrp is now more portable than docs claim

### ISSUE THREAD

**Issue by grr** [Perl/perl5#19648]
**Description**

According to the docs for `getpgrp`:

> Note that the POSIX version of "getpgrp" does not accept a PID argument, so only "PID==0" is truly portable.

But the POSIX spec made the old behavior available in the `getpgid` function, which was moved from XSI to Base in Issue 7 (2018):
https://pubs.opengroup.org/onlinepubs/9699919799/functions/getpgid.html

This comment in perl.h is 26 years old:
https://github.com/Perl/perl5/blob/2808c4d89767b5122c7c116ebeb5679e006dc0df/perl.h#L865-L866

But it shows that `getpgid` is being used under the hood for the implementation of Perl's `getpgrp` function. So the docs should probably be updated to state that it's portable on systems conforming to the relatively recent POSIX standard.

**Comment by jkeenan** [comment]
> 

Is there someone familiar with `getpgrp` and `getpgid` who could evaluate this ticket and recommend improved documentation?
