### ISSUE TITLE
Problem building perl without taint support

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#19651]
I was asked (by @neilb) to evaluate a pull request to a CPAN module I maintain.  The pull request skipped certain tests when run against a post-5.35.11 `perl` built without taint support.  I am evaluating this p.r. both on Linux and on FreeBSD.

On Linux, I was able to build a `perl` without taint support:
```
$ ./bin/perl -Ilib -V | grep -i taint
    config_args='-des -Dusedevel -Utaint_support -Dprefix=/home/jkeenan/testing/perl-5.35.11 -Uversiononly -Dman1dir=none -Dman3dir=none'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -DSILENT_NO_TAINT_SUPPORT -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    NO_TAINT_SUPPORT
    SILENT_NO_TAINT_SUPPORT
```
The module installed and all tests passed.

But on FreeBSD, when adapting my customary `./Configure` invocation, I did not end up without taint support.
```
$ sh ./Configure -des -Dusedevel -Duseithreads -Uversiononly  -Utaint_support -Dprefix=/home/jkeenan/testing/perl-5.35.11 -Dman1dir=none -Dman3dir=none -Doptimize="-O2 -pipe -fstack-protector -fno-strict-aliasing" && make && make install
```
But when I checked the installed perl, I got:
```
$ ./bin/perl -Ilib -v | head -n 2 | tail -1
This is perl 5, version 35, subversion 11 (v5.35.11 (v5.35.10-122-g96acb8b6c1)) built for amd64-freebsd-thread-multi

$ ./bin/perl -Ilib -V:config_args
config_args='-des -Dusedevel -Duseithreads -Uversiononly -Utaint_support -Dprefix=/home/jkeenan/testing/perl-5.35.11 -Dman1dir=none -Dman3dir=none -Doptimize=-O2 -pipe -fstack-protector -fno-strict-aliasing';

$ ./bin/perl -Ilib -V | grep -i taint
    config_args='-des -Dusedevel -Duseithreads -Uversiononly -Utaint_support -Dprefix=/home/jkeenan/testing/perl-5.35.11 -Dman1dir=none -Dman3dir=none -Doptimize=-O2 -pipe -fstack-protector -fno-strict-aliasing'
```
1. Any idea why I'm not getting the desired effect from `-Utaint_support` on FreeBSD, while I am on Linux?

2. I found information on configuring without taint support in `pod/perl53511delta.pod` but not in `INSTALL`.  What should that document say?

**Comment by neilb** [comment]
I don't really have any good idea, but I noticed that on FreeBSD you're including `-Duseithreads`, but you didn't on Linux. I just did the following Configure on MacOS/M1:

    ./Configure -Dusedevel -des -Utaint_support -Duseithreads -Uversiononly

And this results in a taint-free perl, as expected.

Here's a test script to confirm whether a perl supports taint:

```
use Config;
print "taint: ", !exists($Config{taint_support}) || $Config{taint_support} ? "yes" : "no", "\n";
```

What do you get if you run a minimal Configure on FreeBSD:

```
Configure -Dusedevel -des -Utaint_support
```

Does that result with a taint-free perl?

**Comment by jkeenan** [comment]
> I don't really have any good idea, but I noticed that on FreeBSD you're including `-Duseithreads`, but you didn't on Linux. I just did the following Configure on MacOS/M1:
> 
> ```
> ./Configure -Dusedevel -des -Utaint_support -Duseithreads -Uversiononly
> ```
> 
> And this results in a taint-free perl, as expected.
> 
> Here's a test script to confirm whether a perl supports taint:
> 
> ```
> use Config;
> print "taint: ", !exists($Config{taint_support}) || $Config{taint_support} ? "yes" : "no", "\n";
> ```
> 
> What do you get if you run a minimal Configure on FreeBSD:
> 
> ```
> Configure -Dusedevel -des -Utaint_support
> ```
> 
> Does that result with a taint-free perl?

I made 7 additional attempts at this on FreeBSD, perl @neilb advice.  I couldn't reproduce my original complaint in any case, so I'm closing this ticket.  Here is a summary of the 7 attempts.  In each case the desired result should be:  `taint: no`

1. Unthreaded build.
```
$ sh ./Configure -des -Dusedevel -Utaint_support && make test_prep
$ ./perl -Ilib -MConfig -E 'say "taint: ", !exists($Config{taint_support}) || $Config{taint_support} ? "yes" : "no";'
taint: no
$ ./perl -Ilib -V | grep -i taint
    config_args='-des -Dusedevel -Utaint_support'
    ccflags ='-DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -DSILENT_NO_TAINT_SUPPORT'
    NO_TAINT_SUPPORT
    SILENT_NO_TAINT_SUPPORT
```
Good.

2. Threaded build.
```
$ sh ./Configure -des -Dusedevel -Utaint_support -Duseithreads && make test_prep
$ ./perl -Ilib -MConfig -E 'say "taint: ", !exists($Config{taint_support}) || $Config{taint_support} ? "yes" : "no";'
taint: no
[ Other perl -V output similar ]
```

Good.

3. Threaded build, with one more `-U` term.

```
$ sh ./Configure -des -Dusedevel -Duseithreads -Uversiononly -Utaint_support && make test_prep
$ ./perl -Ilib -MConfig -E 'say "taint: ", !exists($Config{taint_support}) || $Config{taint
_support} ? "yes" : "no";'
taint: no
[ Other perl -V output similar ]
```

Good.

4. Same as no. 3, but with `-Doptimize` I customarily use on FreeBSD.

```
$ sh ./Configure -des -Dusedevel -Duseithreads -Uversiononly -Utaint_support -Doptimize="-O2 -pipe -fstack-protector -fno-strict-aliasing" && make test_prep
$ ./perl -Ilib -MConfig -E 'say "taint: ", !exists($Config{taint_support}) || $Config{taint
_support} ? "yes" : "no";'
taint: no
[ Other perl -V output similar ]
```

Good.

5. Same as no. 4, but putting `-Utaint_support` last.
```
$ sh ./Configure -des -Dusedevel -Duseithreads -Uversiononly -Doptimize="-O2 -pipe -fstack-protector -fno-strict-aliasing" -Utaint_support && make test_prep
$ ./perl -Ilib -MConfig -E 'say "taint: ", !exists($Config{taint_support}) || $Config{taint
_support} ? "yes" : "no";'
taint: no
[ Other perl -V output similar ]
```

Good.

6. Same as no. 4, but including other terms customarily used in installing versions of perl for testing on this machine.
```
$ sh ./Configure -des -Dusedevel -Duseithreads -Uversiononly  -Utaint_support -Dprefix=/home/jkeenan/testing/perl-5.35.11 -Dman1dir=none -Dman3dir=none -Doptimize="-O2 -pipe -fstack-protector -fno-strict-aliasing" && make test_prep
$ ./perl -Ilib -MConfig -E 'say "taint: ", !exists($Config{taint_support}) || $Config{taint
_support} ? "yes" : "no";'
taint: no
[ Other perl -V output similar ]

```

Good.

7. Same as no. 6, but installing and checking installed perl.
```
$ sh ./Configure -des -Dusedevel -Duseithreads -Uversiononly  -Utaint_support -Dprefix=/home/jkeenan/testing/perl-5.35.11 -Dman1dir=none -Dman3dir=none -Doptimize="-O2 -pipe -fstack-protector -fno-strict-aliasing" && make && make install
$ cd ~/testing/perl-5.35.11
$ ./bin/perl -Ilib -MConfig -E 'say "taint: ", !exists($Config{taint_support}) || $Config{taint_support} ? "yes" : "no";'
taint: no
[ Other perl -V output similar ]
```
