### ISSUE TITLE
Parser bug starting from 5.35.9

### ISSUE THREAD

**Issue by daniel-pfeiffer** [Perl/perl5#19675]
Module:

**Description**
I am reporting http://matrix.cpantesters.org/?dist=App-pl%20v0.63.0

It is very weird: some instances of Perl 5.35.9 still succeed, while
most repeat about the 1st two of four similar lines:

```
A signature parameter must start with '$', '@' or '%' at ../pl line 89, near "(&"
syntax error at ../pl line 89, near "(&"
Can't use global @_ in "my" at ../pl line 89, near "for @_ "
A signature parameter must start with '$', '@' or '%' at ../pl line 90, near "(&"
syntax error at ../pl line 90, near "(&"
Can't use global @_ in "my" at ../pl line 90, near "for @_"
BEGIN not safe after errors--compilation aborted at ../pl line 90.
```

**Steps to Reproduce**
These are the 5th and 6th lines of:

```
use List::Util;
use List::Util @List::Util::EXPORT_OK;
BEGIN {
    if( $] lt '5.02' ) {
	*any = sub(&@) { my $prog = shift; &$prog && return 1 for @_ };
	*all = sub(&@) { my $prog = shift; &$prog || return for @_; 1 };
	*none = sub(&@) { my $prog = shift; &$prog && return for @_; 1 };
	*notall = sub(&@) { my $prog = shift; &$prog || return 1 for @_ };
	*product = sub(@) { reduce { $a * $b } 1, @_ };
	*sum0 = sub(@) { sum 0, @_ } if !defined \&sum0;
    }
}
```

**Expected behavior**
Silently parse, as it does from 5.10.0 to 5.35.8

**Perl configuration**
Happens on many CPAN testers' 5.35.9 (oddly not on all) and always on 5.35.10 & 5.35.11

**Comment by xenu** [comment]
Your code does this:

```perl
use feature ':'.substr $^V, 1; # Enable latest optional features.
```

which enables the `signatures` feature when run on Perl 5.35.9 and newer, as documented in [perldelta of that release](https://perldoc.perl.org/5.35.9/perldelta#Subroutine-signatures-are-no-longer-experimental).

When signatures are enabled, prototypes have to be specified using the `:prototype` attribute, e.g.:

```perl
sub foo :prototype($$) { ... }
```

You can read more about signatures [here](https://perldoc.perl.org/5.34.1/perlsub#Signatures).

**Comment by Grinnz** [comment]
To be clear, feature bundles are versioned for a reason; if you enable a version dynamically, you are accepting the risk that your code *will* break.

**Comment by daniel-pfeiffer** [comment]
Thanks for the clarification!
[pl](https://perl1liner.sourceforge.io/) is a perl -E drop in replacement with a maximum of bells and whistles turned on and many additional goodies.  It doesn't use the features itself, but adds them for the user.  I didn't realise a feature could also break backward compatibility.
In that case the patch I released yesterday will only push the problem further down to the next occurrence. :-1:

**Comment by iabyn** [comment]
On Thu, Apr 28, 2022 at 11:13:20PM -0700, daniel-pfeiffer wrote:
> I didn't realise a feature could also break backward compatibility.

That's kind of the *whole point* of 'use feature XXX' and its implicit 'use
v5.YY' variant: to enable things which would otherwise break backwards
compatibility - like adding a new keyword which might clash with an
existing subroutine name.

-- 
"Strange women lying in ponds distributing swords is no basis for a system
of government. Supreme executive power derives from a mandate from the
masses, not from some farcical aquatic ceremony."
    -- Dennis, "Monty Python and the Holy Grail"
