### ISSUE TITLE
Cannot shift my @ but can push to it

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#19673]
```
use 5.30.0;
use Data::Dump qw(dump);
my @b = my @a = qw(1 2);
say dump(\@b);
eval 'shift my @a = qw(1 2)';
say $@;
```
Produces:

```
[1, 2]
Can't modify shift in scalar assignment at (eval 1) line 1, at EOF
```
which seems to imply that on the one hand ```my @a``` returns an array yet on the other hand it returns a scalar that cannot be ```shift```ed.  Might it be possible to behave more like the entirely satisfactory:

```
push my @c, 1, 2;
say dump(\@c);
 ```

which produces:
```
[1, 2]
``` 
as expected?

```pop``` and ```unshift``` produce similar puzzling behavior which I urge should be ameliorated to simplify this marvelous, but idiosyncratic  language.

**Comment by Grinnz** [comment]
This is due to prototypes - shift takes a single array argument, so that is interpreted as `shift(my @a) = ...`. Just do `shift(my @a = ...);`
