### ISSUE TITLE
No warning is provided about the useless slice even under strict

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#19697]
No warning is provided about the useless slice **a[2]** below even under strict:
```
use v5.30;
use warnings FATAL => qw(all);
use strict;

sub a{(1,2,3,4)}
say STDERR         a[2]; # 1234 - no warning that the slice is useless
say STDERR (1,2,3,4)[2]; # 3

```

**Comment by iabyn** [comment]
On Fri, May 06, 2022 at 09:02:30PM -0700, philip r brenan wrote:
> No warning is provided about the useless slice **a[2]** below even under strict:
> ```
> use v5.30;
> use warnings FATAL => qw(all);
> use strict;
> 
> sub a{(1,2,3,4)}
> say STDERR         a[2]; # 1234 - no warning that the slice is useless

That's not a useless slice, that's passing an anon array ref to a().
It's equivalent to:

a( [2] );

-- 
Dave's first rule of Opera:
If something needs saying, say it: don't warble it.
