### ISSUE TITLE
Allow control of infinite recursion check (regex)

### ISSUE THREAD

**Issue by AnFunctionArray** [Perl/perl5#19693]
Often times since I work with embedded regex same recursive pattern may be not a recursion because of different variables.

Plus additionally I may wish to investigate (if it's really a recursion) one step further.

**Comment by iabyn** [comment]
It's very unclear what you are requesting. Could you supply some sample code that demonstrates the issue, plus suggestions on how you want perl to change to address this.

**Comment by AnFunctionArray** [comment]
Well I've solved this issue now but in the past I had many occasions where it would be potentially useful to run another level after the recursion has started in order to understand the issue better.

Maybe a way to set the recursion limit to be a specific number or even infinite (for regex - I need this primarily ).

Basically first I have some logs inside the embedded regex code plus I have the debugging for regex set to execute and I see a list of executed regex plus my logs - this is what I'm tracking - and having a little more insight there would be helpful.

**Comment by AnFunctionArray** [comment]
OK
