### ISSUE TITLE
Autovivification: scalar value containing simultaneously an integer value AND an array or hash reference

### ISSUE THREAD

**Issue by florian-pe** [Perl/perl5#19742]
Here is the very weird behavior that I found : 
```
$ perl -E 'my $var=4; $var->{key}->{key2}; say $var; say $var->%*; $var->{key}="new value"; say $var; say $var->%*; '
4
keyHASH(0x5574ba389890)
4
keynew value
```
and the same behavior with array references
```
$ perl -E 'my $var=4; $var->[0]->[0]; say $var; say $var->@*; $var->[0]="new value"; say $var; say $var->@*; '
4
ARRAY(0x55d04a420890)
4
new value
```
This also happens on 5.10. But replacing `$var->@*` with `@$var` and `$var->%*` with `%$var`.

**Expected behavior**

A scalar variable shouldn't both contain an integer value and a hash or array ref,  AT THE SAME TIME !

As additional information :

`ref $var eq ""` is true and `ref $var eq "HASH"` is false.

And assigning directly to the scalar variable act as a sort of reset and suppress both of the previous simulataneous values.
```
$ perl -E 'my $var=4; $var->{key}->{key2}; say $var; say $var->%*; $var="new value"; say $var; say $var->%*; '
4
keyHASH(0x558073e23890)
new value

```

**Comment by xenu** [comment]
Your code is using `$var` as a symbolic reference, it points to `%4`. This behaviour is documented in perlref under the "[symbolic references](https://perldoc.perl.org/5.34.1/perlref#Symbolic-references)" section. 

Note that this is possible only without `use strict`.

**Comment by florian-pe** [comment]
Well damn. I can add another entry to my Perl pitfalls list.
