### ISSUE TITLE
autouse with List::Util

### ISSUE THREAD

**Issue by rwp0** [Perl/perl5#19749]
```perl
use v5.32;
use warnings;
use autodie;
use experimental qw(signatures);
use English;
use autouse qw(Data::Dumper Dumper);
use autouse qw(Carp carp cluck croak confess);
use autouse qw(Term::ANSIColor colored);
use autouse qw(List::Util any);
use if $PERL_VERSION >= v5.35, 'builtin', qw(true false ceil floor);
use if $PERL_VERSION >= v5.35, 'experimental', qw(signatures builtin);
```

```
autoused module List::Util has unique import() method at <path> line 9.
BEGIN failed--compilation aborted at <path> line 9.
```

`autodie` pragma dies used together with `List::Util`

program executes successfully if I comment line 9 ie. importing the `List::Util` module

Using perl 5.32.1 on Debian 11

**Comment by rwp0** [comment]
[autouse](https://perldoc.perl.org/autouse) mentions:
> At least if Module uses Exporter's import, otherwise it is a fatal error.

Isn't List::Util using the standard `import` method to be usable with autouse/autodie?

**Comment by haarg** [comment]
`Exporter`'s `import` is not "the standard", it is just one that is supported by the `autouse` module. `List::Util` can't use `Exporter`'s `import` directly and still work correctly. The modules are just incompatible. `autouse` is a bit too magical to work with everything.

**Comment by rwp0** [comment]
I don't understand one thing, isn't `autodie` die for failed system calls such as `open` and `close`, how `import` is related to such calls to die by?

**Comment by Leont** [comment]
> I don't understand one thing, isn't autodie die for failed system calls such as open and close, how import is related to such calls to die by?

`autodie` has nothing to do with this issue, it's all `autouse`

**Comment by haarg** [comment]
`autodie` loads `List::Util`. This means `autouse` will immediately detect the incompatibility with the `import` method. If you don't load `autodie`, it won't cause an error immediately, but as soon as you try to use `any` it will load `List::Util`, detect the problem, and throw the same error.

**Comment by tonycoz** [comment]
I believe this is documented behaviour and isn't a bug.
