### ISSUE TITLE
`sv_undef()` is missing

### ISSUE THREAD

**Issue by leonerd** [Perl/perl5#19750]
We have various specialised functions for clearing AVs, CVs or HVs, but it seems we don't actually have the most trivially obvious `undef this SV`; the XS equivalent of the Perl code

```perl
undef $sv;
```

The closest you can currently do is `sv_setsv(sv, &PL_sv_undef);`

A dedicated `sv_undef(sv)` would definitely be useful, and can take a few shortcuts knowing what it is doing, so it doesn't have to inspect the "source" SV to realise it is just clearing everything.

**Comment by leonerd** [comment]
Also @leont observes on IRC:

> It should apparently do something like https://github.com/Perl/perl5/blob/blead/pp.c#L963-L969
> Possibly with a https://github.com/Perl/perl5/blob/blead/pp.c#L889-890 first
> Or just a SV_CHECK_THINKFIRST_COW_DROP

**Comment by tonycoz** [comment]
There is:
```
sv_set_undef(sv);
```
This doesn't release the PV, but neither does `sv_setsv(sv, &PL_sv_undef)`.

**Comment by tonycoz** [comment]
Can this be closed, or are you looking for more than `sv_set_undef()` ?

**Comment by jkeenan** [comment]
> Can this be closed, or are you looking for more than `sv_set_undef()` ?

No discussion in this ticket since April 27; closing.
