### ISSUE TITLE
[doc] perldelta: the number of space after a period

### ISSUE THREAD

**Issue by argrath** [Perl/perl5#19772]
The number of spaces after a period is a controversial issue,
but it should be unified in a document at least.

**Comment by jkeenan** [comment]
> The number of spaces after a period is a controversial issue, but it should be unified in a document at least.

There are many things worth worrying about, some of which are worth arguing about.  The number of spaces after a period is not one of them.

I recommend closing this ticket.

**Comment by jkeenan** [comment]
> > The number of spaces after a period is a controversial issue, but it should be unified in a document at least.
> 
> There are many things worth worrying about, some of which are worth arguing about. The number of spaces after a period is not one of them.
> 
> I recommend closing this ticket.

No objections heard; closing.
