### ISSUE TITLE
BBC: Blead Breaks Test::Trap

### ISSUE THREAD

**Issue by cjg-cguevara** [Perl/perl5#19801]
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.42 running under perl 5.37.1.

-----------------------------------------------------------------
[Please describe your issue here]

BBC: Blead Breaks Test::Trap

Please see http://matrix.cpantesters.org/?dist=Test::Trap

[Please do not change anything below this line]
-----------------------------------------------------------------
---
Flags:
    category=core
    severity=low
---
Site configuration information for perl 5.37.1:

Configured by cpan at Sun May 29 03:22:56 EDT 2022.

Summary of my perl5 (revision 5 version 37 subversion 1) configuration:
  Commit id: 66673af5955ecc69305b0baad0a8fb6162312409
  Platform:
    osname=linux
    osvers=5.15.40-0-lts
    archname=x86_64-linux-thread-multi
    uname='linux cjg-alpine3 5.15.40-0-lts #1-alpine smp wed, 18 may 2022 08:12:19 +0000 x86_64 linux '
    config_args='-des -Dprefix=~/bin/perl-blead -Dscriptdir=~/bin/perl-blead/bin -Dusedevel -Duse64bitall -Duseithreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong'
    ccversion=''
    gccversion='10.3.1 20211027'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/lib /usr/local/lib /lib
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/usr/lib/libc.a
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'

---
@INC for perl 5.37.1:
    /home/cpan/bin/perl-blead/lib/site_perl/5.37.1/x86_64-linux-thread-multi
    /home/cpan/bin/perl-blead/lib/site_perl/5.37.1
    /home/cpan/bin/perl-blead/lib/5.37.1/x86_64-linux-thread-multi
    /home/cpan/bin/perl-blead/lib/5.37.1

---
Environment for perl 5.37.1:
    HOME=/home/cpan
    LANG=C.UTF-8
    LANGUAGE (unset)
    LC_COLLATE=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl-blead/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

**Comment by hvds** [comment]
There are 13 test failures which all look like:
```
t/10-tester.t ..................... ok
# Real fork; taint checks enabled

#   Failed test 'Take 1: exit(1)'
#   at t/11-systemsafe-basic.t line 119.
#          got: undef
#     expected: '1'
# bless({
#   " id "      => "1653985790/47754/4",
#   "die"       => "Insecure directory in \$ENV{PATH} while running with -T switch at t/11-systemsafe-basic.t line 116.\n",
#   "leaveby"   => "die",
#   "stderr"    => "",
#   "stdout"    => "",
#   "wantarray" => undef,
#   "warn"      => [],
# }, "Test::Trap")
```

I assume this is knock-on from https://github.com/Perl/perl5/pull/19645, presumably running with an empty path.

**Comment by jkeenan** [comment]
Bisecting with this invocation:
```
perl Porting/bisect.pl --start=v5.36.0 \
--end=704ee149f702a507eec39e99c71a91932da3922b \
--module=Test::Trap
```
... points to this commit:
```
92ec2fce1aace295365d7d86c61c98df8202fc9d is the first bad commit
commit 92ec2fce1aace295365d7d86c61c98df8202fc9d
Author: Yves Orton <demerphq@gmail.com>
Date:   Wed Apr 20 06:55:45 2022 +0200
Commit:     Karl Williamson <khw@cpan.org>
CommitDate: Sat May 28 15:01:00 2022 -0600
```
@demerphq @khwilliamson, can you take a look?

**Comment by jkeenan** [comment]
> Bisecting with this invocation:
> 
> ```
> perl Porting/bisect.pl --start=v5.36.0 \
> --end=704ee149f702a507eec39e99c71a91932da3922b \
> --module=Test::Trap
> ```
> 
> ... points to this commit:
> 
> ```
> 92ec2fce1aace295365d7d86c61c98df8202fc9d is the first bad commit
> commit 92ec2fce1aace295365d7d86c61c98df8202fc9d
> Author: Yves Orton <demerphq@gmail.com>
> Date:   Wed Apr 20 06:55:45 2022 +0200
> Commit:     Karl Williamson <khw@cpan.org>
> CommitDate: Sat May 28 15:01:00 2022 -0600
> ```
> 
> @demerphq @khwilliamson, can you take a look?

I've filed this ticket for Test-Trap upstream:
https://rt.cpan.org/Ticket/Display.html?id=143716

@demerphq @khwilliamson, have you had a chance to look at this BBC?

**Comment by demerphq** [comment]
On Sun, 10 Jul 2022 at 16:21, James E Keenan ***@***.***>
wrote:

> Bisecting with this invocation:
>
> perl Porting/bisect.pl --start=v5.36.0 \
> --end=704ee149f702a507eec39e99c71a91932da3922b \
> --module=Test::Trap
>
> ... points to this commit:
>
> 92ec2fce1aace295365d7d86c61c98df8202fc9d is the first bad commit
> commit 92ec2fce1aace295365d7d86c61c98df8202fc9d
> Author: Yves Orton ***@***.***>
> Date:   Wed Apr 20 06:55:45 2022 +0200
> Commit:     Karl Williamson ***@***.***>
> CommitDate: Sat May 28 15:01:00 2022 -0600
>
> @demerphq <https://github.com/demerphq> @khwilliamson
> <https://github.com/khwilliamson>, can you take a look?
>
> I've filed this ticket for Test-Trap upstream:
> https://rt.cpan.org/Ticket/Display.html?id=143716
>
> @demerphq <https://github.com/demerphq> @khwilliamson
> <https://github.com/khwilliamson>, have you had a chance to look at this
> BBC?
>
The underlying issue is that on Linux setting the path to "" is
semantically equivalent to setting it to ".", and we document that under
taint mode you can't set the path to ".", and we wont look in CWD to find
executables, so we had to ban the empty string as well.

The test code contains this:

# Protect against tainted PATH &c ...
$ENV{PATH} = '';

Something like this is probably the simplest choice:

use File::Temp;
$ENV{PATH} = tempdir( CLEANUP => 1 );

Cheers,
yves

--

perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by jkeenan** [comment]
A new version (v0.3.5) has been uploaded to CPAN.  It passes tests for me on both Linux and FreeBSD.  I'm self-assigning this ticket for the purpose of closing it within 7 days unless new problems are reported.

**Comment by jkeenan** [comment]
> A new version (v0.3.5) has been uploaded to CPAN. It passes tests for me on both Linux and FreeBSD. I'm self-assigning this ticket for the purpose of closing it within 7 days unless new problems are reported.

[CPANtester results](http://matrix.cpantesters.org/?dist=Test-Trap) look good.  Closing this ticket.
