### ISSUE TITLE
`catch` without `var` could have a more helpful error message

### ISSUE THREAD

**Issue by leonerd** [Perl/perl5#19811]
Users who are familiar with more generic `try/catch` syntax may be used to a plain `catch { ... }` block and thus forget to put the `($var)` part on. On 5.36 this results in a very vague error message:

```
$ perl5.36.0 
use feature 'try';   
no warnings 'experimental::try';

try { A() }
catch { B() }  

syntax error at - line 5, near "catch {"
Execution of - aborted due to compilation errors.
```

It would be much more useful to new users to catch (pardon the phrasing) this particular trap, if the message said something like:

```
catch blocks require a (VAR) at - line 5, near "catch {"
```

**Comment by leonerd** [comment]
Having stared around at this one some more, it seems it might be a little tricky to implement. To add it, I think it would require adding a new case to the `perly.y` grammar specifically to catch this error, and just invoke `yyerror()` inside the action block. To match the error it would have to be quite generic, probably something like:

```
    CATCH PERLY_OPEN_BRACE
      { yyerror("catch requires a (VAR)"); }
```

It would work, but it feels like quite an odd special-casing to apply for just this situation.

**Comment by iabyn** [comment]
On Mon, Jun 06, 2022 at 02:57:44AM -0700, Paul Evans wrote:
> Having stared around at this one some more, it seems it might be a little tricky to implement. To add it, I think it would require adding a new case to the `perly.y` grammar specifically to catch this error, and just invoke `yyerror()` inside the action block. To match the error it would have to be quite generic, probably something like:
> 
> ```
>     CATCH PERLY_OPEN_BRACE
>       { yyerror("catch requires a (VAR)"); }
> ```
> 
> It would work, but it feels like quite an odd special-casing to apply for just this situation. 


How about making the paren optional, but newTRYCATCHOP() croaks if passed
a NULL paren block, e.g.

    catch_paren:      empty
               |      PERLY_PAREN_OPEN
                      ...
                      PERLY_PAREN_CLOSE

    barestmt:
                      ...
            |       TRY mblock[try] CATCH catch_paren
                    mblock[catch] finally



-- 
Art is anything that has a label (especially if the label is "untitled 1")

**Comment by leonerd** [comment]
> How about making the paren optional, but newTRYCATCHOP() croaks if passed a NULL paren block, e.g.

Oh, yes. That's probably a much neater way to do it. I'll have a go.

**Comment by leonerd** [comment]
Thanks for the suggestion @iabyn; that turned out to be fairly simple to implement.

I now have a PR if you'd like to review it: https://github.com/Perl/perl5/pull/19838
