### ISSUE TITLE
Optimizations: RegEx recursive patterns.

### ISSUE THREAD

**Issue by AnFunctionArray** [Perl/perl5#19815]
I replaced regcppush and recppop to use memcpy which for my project ([regularc](https://github.com/AnFunctionArray/regularc)) by using the attached use case and the following command:

`perl regexes/parse.pl gen.c`

Improves performance over the original implementation by x2 (tested on Windows x86).

Here is the pull [request](https://github.com/Perl/perl5/pull/19814).

[gen.zip](https://github.com/Perl/perl5/files/8827167/gen.zip)

**Comment by AnFunctionArray** [comment]
https://github.com/Perl/perl5/pull/19814

**Comment by jkeenan** [comment]
> 

The pull request above was merged into blead and closed this past November.  Is there any reason to keep this ticket open?
