### ISSUE TITLE
Unexpected output from 'perl-V:uname'

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#19845]
I am not getting the output I would expect from `perl -V:uname`.

Suppose that I build `perl` on a machine with these characteristics:
```
$ uname -mrs
FreeBSD 13.0-RELEASE amd64
```
... or, more verbosely:
```
$ uname -a
FreeBSD perl-reporter-12 13.0-RELEASE FreeBSD 13.0-RELEASE #0 releng/13.0-n244733-ea31abc261f: Fri Apr  9 04:24:09 UTC 2021     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
```
... and this configuration:
```
$ ./perl -Ilib -V:config_args
config_args='-des -Dusedevel -Duseithreads -Doptimize=-O2 -pipe -fstack-protector -fno-strict-aliasing';
```
Then, I get this:
```
$ ./perl -Ilib -V:archname
archname='amd64-freebsd-thread-multi';
```
Now, given that on this machine, I get the following:
```
$ ./perl -Ilib -V | grep uname
    uname='freebsd perl-reporter-12 13.0-release freebsd 13.0-release #0 releng13.0-n244733-ea31abc261f: fri apr 9 04:24:09 utc 2021 root@releng1.nyi.freebsd.org:usrobjusrsrcamd64.amd64sysgeneric amd64 '
```
... I am surprised when I get the following:
```
$ ./perl -Ilib -V:uname
uname='uname';
```
I get similar results on Linux, *i.e.,* the only thing I get back is the string `uname`.

Is my expectation wrong, or is this a defect in `perl -V:<something>`?

**Comment by haarg** [comment]
`perl -V:uname` gives the uname program used. `perl -V:myuname` gives the uname value.

**Comment by jkeenan** [comment]
> `perl -V:uname` gives the uname program used. `perl -V:myuname` gives the uname value.

Confirmed.  Thanks.  Closing.
