### ISSUE TITLE
CPAN with Perl 5.36 Complains of Expired Certificate

### ISSUE THREAD

**Issue by fullautodotcom** [Perl/perl5#19859]
ERROR: cannot verify cpan.org's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.
To connect to cpan.org insecurely, use `--no-check-certificate'.

# cpan
Loading internal logger. Log::Log4perl recommended for better logging
Terminal does not support AddHistory.

To fix that, maybe try>  install Term::ReadLine::Perl

cpan shell -- CPAN exploration and modules installation (v2.33)
Enter 'h' for help.

cpan[1]> install Term::ReadLine::Perl
Reading '/root/.cpan/Metadata'
Warning: Found only 0 objects in /root/.cpan/Metadata

Trying with
    /usr/bin/wget -O "/root/.cpan/sources/authors/01mailrc.txt.gz.tmp17183"
to get
    https://cpan.org/authors/01mailrc.txt.gz
--2022-06-13 08:54:59--  https://cpan.org/authors/01mailrc.txt.gz
Resolving cpan.org (cpan.org)... 151.101.193.55, 151.101.1.55, 139.178.67.96, ...
Connecting to cpan.org (cpan.org)|151.101.193.55|:443... connected.
ERROR: cannot verify cpan.org's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.
To connect to cpan.org insecurely, use `--no-check-certificate'.

    Function system("/usr/bin/wget -O "/root/.cpan/sources/authors/01mailrc.txt.gz.tmp17183" "https://cpan.org/authors/01mailrc.txt.gz" ")
    returned status 5 (wstat 1280), left
/root/.cpan/sources/authors/01mailrc.txt.gz.tmp17183 with size 0

Trying with
    /usr/bin/wget -O "/root/.cpan/sources/modules/02packages.details.txt.gz.tmp17183"
to get
    https://cpan.org/modules/02packages.details.txt.gz
--2022-06-13 08:55:00--  https://cpan.org/modules/02packages.details.txt.gz
Resolving cpan.org (cpan.org)... 151.101.1.55, 151.101.193.55, 151.101.65.55, ...
Connecting to cpan.org (cpan.org)|151.101.1.55|:443... connected.
ERROR: cannot verify cpan.org's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.
To connect to cpan.org insecurely, use `--no-check-certificate'.

    Function system("/usr/bin/wget -O "/root/.cpan/sources/modules/02packages.details.txt.gz.tmp17183" "https://cpan.org/modules/02packages.details.txt.gz" ")
    returned status 5 (wstat 1280), left
/root/.cpan/sources/modules/02packages.details.txt.gz.tmp17183 with size 0

Trying with
    /usr/bin/wget -O "/root/.cpan/sources/modules/03modlist.data.gz.tmp17183"
to get
    https://cpan.org/modules/03modlist.data.gz
--2022-06-13 08:55:00--  https://cpan.org/modules/03modlist.data.gz
Resolving cpan.org (cpan.org)... 151.101.193.55, 151.101.129.55, 139.178.67.96, ...
Connecting to cpan.org (cpan.org)|151.101.193.55|:443... connected.
ERROR: cannot verify cpan.org's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.
To connect to cpan.org insecurely, use `--no-check-certificate'.

    Function system("/usr/bin/wget -O "/root/.cpan/sources/modules/03modlist.data.gz.tmp17183" "https://cpan.org/modules/03modlist.data.gz" ")
    returned status 5 (wstat 1280), left
/root/.cpan/sources/modules/03modlist.data.gz.tmp17183 with size 0
    Writing /root/.cpan/Metadata
Warning: Cannot install Term::ReadLine::Perl, don't know what it is.
Try the command

    i /Term::ReadLine::Perl/

to find objects with matching identifiers.

cpan[2]>

Module:

**Description**

**Steps to Reproduce**

**Expected behavior**

**Perl configuration**

```
# perl -V output goes here
```

**Comment by Leont** [comment]
You need to update your platform's certificate database (or wherever wget gets it from). The old LetsEncrypt certificate expired.
