### ISSUE TITLE
Need to skip AUTHOR testing for github CI sanity

### ISSUE THREAD

**Issue by khwilliamson** [Perl/perl5#19867]
A first time author will not have their workflow run on GH without approval.  If someone does approve it, it will automatically fail because the person isn't in the AUTHORS file.

So their patch can't be tested without them being an accepted author.  This doesn't make sense.  The obvious solution is to skip AUTHOR testing in such cases.

**Comment by tonycoz** [comment]
One option might be to modify `authors.t` to skip on a pull_request event.

Note that if they do test the change locally they'll see the test failure anyway, and they'll see the failure on push to their fork.

**Comment by haarg** [comment]
Wouldn't this also result in blead failing CI if a PR was merged without adding the author?

**Comment by Leont** [comment]
Yeah what tony and haarg said

**Comment by khwilliamson** [comment]
Can we make it so that failing any porting test doesn't stop the rest of the tests from running?  Yes we know that this has to be fixed before merging, but at least we'd find out soon what else might be wrong.

Just now we had a failure because a version didn't get bumped, and the rest of the tests didn't run.

**Comment by haarg** [comment]
That definitely seems worth changing. The version and author tests shouldn't prevent the rest of the tests from running. Ideally, they also would only show up as failures on a single action, and not any of the later checks.

**Comment by bram-perl** [comment]
> The version and author tests shouldn't prevent the rest of the tests from running. Ideally, they also would only show up as failures on a single action, and not any of the later checks.

In the PR I just created (#20123)  that should already be the case for the version check: it needs the full history and that's only available during the 'sanity check'.
The author tests failure will (in the current state) still show up in each build configuration but changes are being made to it which may/will result in it needing full history (which means they can only run during 'sanity check' since only that has the full history)

**Comment by bram-perl** [comment]
Only running the authors test in the sanity check run is done in PR #20124

**Comment by demerphq** [comment]
On Sat, 20 Aug 2022 at 17:46, Bram ***@***.***> wrote:
>
> Only running the authors test in the sanity check run is done in PR #20124

I dont get this. Am I missing something? At least in my branch the
authors test runs fine in all the tests.  Why do we have to restrict
it to the sanity check when there is a full clone? As far as I
understand it checks the commits it has for new authors, if it has
less authors to check it shouldnt matter.

Yves

**Comment by demerphq** [comment]
Bram has explained what I was missing: sometimes we end up with a
merge commit and sometimes we dont.

On Sat, 20 Aug 2022 at 18:00, demerphq ***@***.***> wrote:
>
> On Sat, 20 Aug 2022 at 17:46, Bram ***@***.***> wrote:
> >
> > Only running the authors test in the sanity check run is done in PR #20124
>
> I dont get this. Am I missing something? At least in my branch the
> authors test runs fine in all the tests.  Why do we have to restrict
> it to the sanity check when there is a full clone? As far as I
> understand it checks the commits it has for new authors, if it has
> less authors to check it shouldnt matter.
>
> Yves



-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by demerphq** [comment]
On Thu, 16 Jun 2022, 02:51 Karl Williamson, ***@***.***>
wrote:

> A first time author will not have their workflow run on GH without
> approval. If someone does approve it, it will automatically fail because
> the person isn't in the AUTHORS file.
>
> So their patch can't be tested without them being an accepted author. This
> doesn't make sense. The obvious solution is to skip AUTHOR testing in such
> cases
>

They should simply run the tool the test  mentions and include the required
updates and include it as part of their PR. The test should fail on their
machine before they push and then they should follow the directions to add
the required AUTHORS and mailmap changes to the PR. The idea is to prevent
changes from being merged without the corresponding Metadata being added to
the PR.

Did the OP run full 'make test', before they pushed the PR?

Yves

Yves
