### ISSUE TITLE
[doc] 

### ISSUE THREAD

**Issue by poti1** [Perl/perl5#19885]
**Where**
perlreguts

**Description**
"One, the regexp structure described in [perlreapi](https://perldoc.perl.org/perlreapi) is populated by the engine currently being. used and"

Remove the period after "being".

**Comment by rwp0** [comment]
@poti1 can you submit a PR on it?

**Comment by poti1** [comment]
I'm new to Perl PRs. Does one need permission to push?

```
git push --set-upstream origin poti1/reguts_doc_typo
ERROR: Permission to Perl/perl5.git denied to poti1.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by rwp0** [comment]
You need to fork the repository, make changes, push to your local repository, and then create a pull request.

You can also do it all-at-once via GitHub by clicking on the Edit button (with a pencil icon) on the file:

https://github.com/Perl/perl5/blob/blead/pod/perlguts.pod

**Comment by jkeenan** [comment]
> You need to fork the repository, make changes, push to your local repository, and then create a pull request.
> 

There's no need to send a first-time contributor to github bootcamp.  Fixed in commit fc5fd214d7.

@poti1, thanks for calling our attention to this.  Closing.

**Comment by poti1** [comment]
Thanks, I just saw you fixed it.
I forked perl5 and have it ready (for the next bug) :smile:

**Comment by poti1** [comment]
I guess `perlreguts` is not read too often :sweat_smile: : otherwise someone else would spot the typo much earlier.
