### ISSUE TITLE
DragonflyBSD: t/op/magic.t has test failures since v5.35.9

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#19894]
Somewhere between `v5.35.8-29-g4ccd1515c8` and `v5.35.9-114-gc3c9d6b15f` -- approximately February 2022 -- two tests (202-203) in `t/op/magic.t` began to fail in blead in DragonflyBSD -- and they continue to fail to this day.

See these smoke-test reports:
PASS https://perl5.test-smoke.org/report/5015286
FAIL https://perl5.test-smoke.org/report/5016701

We only have one person submitting smoke-test reports on this OS; @cjg-cguevara, can you supply more data?

I don't have access to DragonflyBSD, so if anyone can investigate, please do so.

**Comment by tonycoz** [comment]
The log provides more information:
```
# Failed test 202 - altering $0 is effective (testing with /proc/) at op/magic.t line 900
#      got "perl: -bar"
# expected "bar"
# Failed test 203 - altering $0 is effective (testing with `ps`) at op/magic.t line 931
#      got 'perl: -x (perl)'
# expected /(?^:^(?:(?:mini)?perl: )?x(?: \((?:mini)?perl\))?$)/
```

I don't see any changes in S_set_dollarzero() over that period.

The calling code to that was changed in 2d3b3561a39bb17fd6003fb262f52b3bc800770e but that looks fairly safe for the test that's failing.

**Comment by tonycoz** [comment]
Bisected to 2d3b3561a39bb17fd6003fb262f52b3bc800770e.

I wasn't able to make a short reproducer, but moving the tests introduced in 2d3b3561 after the existing $0 tests allows the failing (and all non-TODO) tests to pass.

**Comment by jkeenan** [comment]
> Bisected to [2d3b356](https://github.com/Perl/perl5/commit/2d3b3561a39bb17fd6003fb262f52b3bc800770e).
> 
> I wasn't able to make a short reproducer, but moving the tests introduced in [2d3b356](https://github.com/Perl/perl5/commit/2d3b3561a39bb17fd6003fb262f52b3bc800770e) after the existing $0 tests allows the failing (and all non-TODO) tests to pass.

Could you create a `smoke-me` branch so that we could confirm that that happens on Dragonfly?

**Comment by tonycoz** [comment]
https://github.com/Perl/perl5/tree/smoke-me/tonyc/19894-dflybsd-workaround

**Comment by jkeenan** [comment]
> https://github.com/Perl/perl5/tree/smoke-me/tonyc/19894-dflybsd-workaround

@cjg-cguevara, can you give this branch a spin on your DragonflyBSD smoker?  Thanks.

**Comment by tonycoz** [comment]
Looks like it's failing on -Duseshrplib builds.

**Comment by jkeenan** [comment]
> Looks like it's failing on -Duseshrplib builds.

I don't see that in smoke-test results.  (In fact, I don't *yet* see any results for this smoke-me branch.  Where are you seeing that?

**Comment by jkeenan** [comment]
> > Looks like it's failing on -Duseshrplib builds.
> 
> I don't see that in smoke-test results. (In fact, I don't _yet_ see any results for this smoke-me branch. Where are you seeing that?

Correction: I don't yet see any results for this branch run on Dragonfly BSD.

**Comment by tonycoz** [comment]
I'm looking at the github CI results, eg. https://github.com/Perl/perl5/runs/7083910270?check_suite_focus=true

**Comment by jkeenan** [comment]
> I'm looking at the github CI results, eg. https://github.com/Perl/perl5/runs/7083910270?check_suite_focus=true

@tonycoz, I think we have a bigger problem here.  I'm getting problems with `-Duseshrplib` even in blead:
On Linux:
```
$ uname -mrs
Linux 5.10.13-x86_64-linode141 x86_64

$ gitcurr
blead

$ git describe
v5.37.1-38-gee41234

$ sh ./Configure -des -Dusedevel -Dusequadmath -Duseshrplib -Dusebacktrace -Duseithreads && make test_prep
...

$ ./perl -Ilib -V:config_args
./perl: error while loading shared libraries: libperl.so: cannot open shared object file: No such file or directory
```
Configure without `-Duseshrplib`:
```
$ git clean -dfx

$ sh ./Configure -des -Dusedevel -Dusequadmath -Dusebacktrace -Duseithreads && make test_prep
...

$ ./perl -Ilib -V:config_args
config_args='-des -Dusedevel -Dusequadmath -Dusebacktrace -Duseithreads';

$ cd t;./perl harness op/magic.t; cd -
op/magic.t .. ok       
All tests successful.
Files=1, Tests=208,  4 wallclock secs ( 0.04 usr  0.01 sys +  0.12 cusr  0.12 csys =  0.29 CPU)
Result: PASS
```

On FreeBSD-12:
```
$ uname -mrs
FreeBSD 12.3-RELEASE-p1 amd64
$ gitcurr
blead
$ git describe
v5.37.1-38-gee41234643
$ sh ./Configure -des -Dusedevel -Duseshrplib && make test_prep
...
$ ./perl -Ilib -V:config_args
ld-elf.so.1: /usr/home/jkeenan/gitwork/perl/perl: Undefined symbol "PL_exit_flags"
```
I know very little about `-Duseshrplib` so I can't yet say what's going on here.

**Comment by jkeenan** [comment]
So, having just now read `perldoc INSTALL`, I realize that I know even less about `-Duseshrplib` than I thought I did.

Once I precede configuration with `LD_LIBRARY_PATH=`pwd`:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH`, on Linux, if I configure with `-Duseshrplib` in @tonycoz's branch, I can reproduce the failues in `t/op/magic.t` reported in https://github.com/Perl/perl5/runs/7083910270?check_suite_focus=true.
```
Test Summary Report
-------------------
op/magic.t (Wstat: 0 Tests: 208 Failed: 13)
  Failed tests:  143-145, 180-182, 187-192, 194
Files=1, Tests=208,  3 wallclock secs ( 0.06 usr  0.00 sys +  0.10 cusr  0.07 csys =  0.23 CPU)
Result: FAIL
```
I note in passing, however, that Tony's branch does get `t/op/magic.t` -- and, by extension, the entire test suite -- PASSing on DragonflyBSD for the first time in months.  See: https://perl5.test-smoke.org/report/5019769.

How should we proceed?

**Comment by tonycoz** [comment]
For your `-Duseshrplib` perl to run (outside of `make test`, which does the right thing) you'll need to set the equivalent of `LD_LIBRARY_PATH` to run your newly built perl.  This isn't a problem in blead.  I expect my change broke a relative path being used to find libperl.so, I'll take another look ~~tomorrow~~ later today (it's 1am here).

**Comment by tonycoz** [comment]
Note that my change isn't a *fix* - it's a workaround, I expect it will be better to TODO these tests on DragonflyBSD.

I've reproduced this from straight C code, and opened https://bugs.dragonflybsd.org/issues/3319

I'll work on a better patch, probably skipping the Unicode $0 tests on DragonflyBSD

**Comment by jkeenan** [comment]
On 6/29/22 21:12, Tony Cook wrote:
> Note that my change isn't a /fix/ - it's a workaround, I expect it will 
> be better to TODO these tests on DragonflyBSD.
> 
> I've reproduced this from straight C code, and opened 
> https://bugs.dragonflybsd.org/issues/3319 
> <https://bugs.dragonflybsd.org/issues/3319>
> 
> I'll work on a better patch, probably skipping the Unicode $0 tests on 
> DragonflyBSD
> 

Thanks.  What I had hoped to do today -- and might get to tomorrow -- 
was to create a smoke-me branch that reduced t/op/magic.t to just the 
two failing unit tests.  I hope that would enable us to see why they 
were failing as of the commit you previously cited and only on this one 
platform.

**Comment by tonycoz** [comment]
Changing `t/op/magic.t` to just the two failing tests would pass.

It seems to be all the calls to setproctitle() that cause the problem, commenting out any of the active setproctitle() calls in the C reproducer in the upstream bug stops the change in behaviour.

**Comment by tonycoz** [comment]
I've pushed https://github.com/Perl/perl5/tree/smoke-me/tonyc/19894-skip-unicode-dollarzero
