### ISSUE TITLE
[doc] Order of application of PERL5OPT relative to command line options is not documented

### ISSUE THREAD

**Issue by djerius** [Perl/perl5#19904]
**Where**
perlrun

**Description**
PERL5OPT is documented as

```
Switches in this variable are treated as if they were on every Perl command line.
```

but doesn't indicate the order relative to command line arguments in which they are applied.  For some reason I assumed that they are applied *before* command line arguments, but it appears they are applied *after*.

In the following contrived example, if I install `Data::Hive` into relative directory `local`, which is not in Perl's search path,

```
perl -MData::Hive
```

will fail to find it.

```
perl -Mlib=./local -MData::Hive
```

will find it, but

```
PERL5OPT=-Mlib=./local perl -MData::Hive
```
will not

**Comment by Grinnz** [comment]
This actually is documented: https://perldoc.perl.org/perlrun#ORDER-OF-APPLICATION

**Comment by Grinnz** [comment]
Specifically: `After normal processing of -M switches from the command line, all the -M switches in PERL5OPT are extracted. They are processed from left to right, i.e. the same as those on the command line.`

**Comment by djerius** [comment]
Ooops. I'm running 5.28 in production, which didn't have that documentation.  My mistake.
