### ISSUE TITLE
[doc] feature/experimental/strict/use v: support for third party module enabling.

### ISSUE THREAD

**Issue by EvanCarroll** [Perl/perl5#19902]
There are a few pragmas that change parsing semantics in perl,

* `use strict;`
* `use feature 'whatever';`
* `use experimental 'whatever';`

And by extension,

 * `use v5.XX`

And generally, it is also understood that

```perl
use ACMEModule;
```

Is the same as,

```perl
BEGIN {
  require ACMEModule;
  ACMEModule->import()
}
```

But is it true that in the above case, for `strict` `feature` and `experimental` there is support for third party modules enabling these pragmas in the caller's namespace? It would almost seem to me like while that implementation currently permits it, it can't actually be supported by the language. What if at some point `use v5.40` changes the semantics of imports itself?

It would be nice to know to what degree this is currently supported. Honestly, it would be my preference for this not to be supported at all? Why? Because if it wasn't supported we could statically analyze Perl without having to take into account runtime tinkering with internals that are not clearly supported anyway.

**Comment by Grinnz** [comment]
Yes, you just `strict->import;`. This enables it in the caller's scope (not namespace, as these pragmas do not affect the namespace). There's no way to do with for `use VERSION` to my knowledge. But I have no idea what this has to do with static analysis that is required not to run the code.

**Comment by Grinnz** [comment]
Closing as this is more of a discussion topic than an issue.

**Comment by EvanCarroll** [comment]
It's not documented. This is a documentation request.

**Comment by Grinnz** [comment]
If anything, I would say the "import" mechanism is not sufficiently centrally documented.
