### ISSUE TITLE
Wrong pod2man output with nested highlights

### ISSUE THREAD

**Issue by Julien-Elie** [Perl/perl5#19923]
With the following snippet:

```
=head1 Test

Testing C<B<test>> and C<I<test>> syntax.

=cut
```

pod2man from Perl 5.32.1 renders:

```
Testing \f(CW\*(C`\f(CBtest\f(CW\*(C'\fR and \f(CW\*(C`\f(CItest\f(CW\*(C'\fR syntax.
```

which is not accurate, because the right quote is included in the B<> and I<> syntax: Testing "**test"** and "_test"_ syntax.

Output from other pod2xxx programs looks fine.

**Comment by jkeenan** [comment]
Perl module `Pod::Man` and utility `pod2man` are maintained upstream on CPAN as part of the [podlators](https://metacpan.org/dist/podlators) distribution.  So the place where you should file a bug ticket is [that distribution's issue-tracker](https://rt.cpan.org/Dist/Display.html?Name=podlators).

That being said, I created a file on disk from your sample code.
```
$ cat gh-19923-pod2man.pod
=head1 Test

Testing C<B<test>> and C<I<test>> syntax.

=cut
```
I then created `man` code:
```
pod2man < gh-19923-pod2man.pod > gh-19923-pod2man.man
```
I tried this on both FreeBSD and Linux.  On FreeBSD the results were fine.  On Linux, the underscore beneath the 2nd `test` extended beneath the right double-quote, as you reported.

So, when you report this upstream, please alert the maintainers to these OS-specific considerations.

Closing this ticket.

**Comment by Julien-Elie** [comment]
Thanks James for your response.
I've opened a ticket on the podlators bug tracker: https://rt.cpan.org/Public/Bug/Display.html?id=143667
