### ISSUE TITLE
Storable bug with XS module HTTP::XSHeaders

### ISSUE THREAD

**Issue by jackdeguest** [Perl/perl5#19984]
Module: Storable

**Description**
When Storable thaws an XS object like [HTTP::XSHeaders](https://metacpan.org/pod/HTTP::XSHeaders), it makes it unusable

**Steps to Reproduce**
```perl
#!/usr/local/bin/perl
use v5.36;
use strict;
use warnings;
use Storable ();

my $h = My::Headers->new(
    Content_Type => 'text/html; charset=utf8',
);
say "Content-Type: ", $h->header( 'Content-Type' );
say "Serialising.";
my $serial = Storable::freeze( $h );
my $h2 = Storable::thaw( $serial );
say "Is $h2 an object of My::Headers? ", ( $h2->isa( 'My::Headers' ) ? 'yes' : 'no' ); # ok
say "Is $h2 an object of HTTP::XSHeaders? ", ( $h2->isa( 'HTTP::XSHeaders' ) ? 'yes' : 'no' );  # ok
say "Content-Type: ", $h2->header( 'Content-Type' ); # not ok
# Exception occurs here: "hl is not an instance of HTTP::XSHeaders"

package My::Headers;
BEGIN
{
    use strict;
    use warnings;
    use parent qw( HTTP::XSHeaders );
};

__END__
```

**Expected behavior**
Storable::thaw re-creates the module object, but somehow for XS module, although the object thus created is recognised as being of that class, it is unusable.

**Perl configuration**

```
Summary of my perl5 (revision 5 version 36 subversion 0) configuration:

  Platform:
    osname=linux
    osvers=5.15.0-39-generic
    archname=x86_64-linux-thread-multi
    uname='linux gabriel-vm.tokyo.deguest.jp 5.15.0-39-generic #42-ubuntu smp thu jun 9 23:42:32 utc 2022 x86_64 x86_64 x86_64 gnulinux '
    config_args='-des -Duseithreads -Duselargefiles -Dcc=x86_64-linux-gnu-gcc -Dcpp=x86_64-linux-gnu-cpp -A ccflags=-fPIC'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='x86_64-linux-gnu-gcc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fPIC -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-D_REENTRANT -D_GNU_SOURCE -fPIC -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='11.2.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='x86_64-linux-gnu-gcc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib/x86_64-linux-gnu /usr/lib /usr/local/src/perl-5.36.0/lib /usr/local/lib/x86_64-linux-gnu /usr/lib/postgresql/12/lib /usr/local/src/perl-5.36.0/UU /usr/lib64
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=/usr/lib/x86_64-linux-gnu/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.35'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under linux
  Compiled at Jun 18 2022 16:22:47
  %ENV:
    PERLDOC_PAGER="more"
  @INC:
    /usr/local/lib/perl5/site_perl/5.36.0/x86_64-linux-thread-multi
    /usr/local/lib/perl5/site_perl/5.36.0
    /usr/local/lib/perl5/5.36.0/x86_64-linux-thread-multi
    /usr/local/lib/perl5/5.36.0
    /usr/local/lib/perl5/site_perl/5.32.0
    /usr/local/lib/perl5/site_perl
```

**Comment by dur-randir** [comment]
- I don't see a HTTP::XSHeader on CPAN, so I can't tell you the exact reason it failed, but it doesn't matter
- you can't, without a special help from an xs module, serialize it's data, for any meaning of a serializer and any object holding C level data. Just think twice about it - XS module holds data not visible to Perl, how can Perl access it to restore back later?

**Comment by jackdeguest** [comment]
Sorry, typo. It's [HTTP::XSHeaders](https://metacpan.org/pod/HTTP::XSHeaders). Please check my code snippet to reproduce this bug.
If it is not possible as it is, then, maybe you could consider adding a callback like STORABLE_thaw_some_more if the subroutine is implemented and return what it returns? Otherwise, it makes Storable unusable for those XS modules.

**Comment by dur-randir** [comment]
There're already such hooks in place, STORABLE_freeze/STORABLE_thaw. So, it's the module's author who should implement them. But most XS authors don't as it's very time consuming for any complex internal structures. 


I'd recommend you rethink your approach - why in the first place do you need to clone this object? If you think it'd be faster then the original headers string re-parse, it won't.

**Comment by jackdeguest** [comment]
> There're already such hooks in place, STORABLE_freeze/STORABLE_thaw

Sure, but Storable discards the returned value of that hook, so pretty much useless except to modify in-place the object created by Storable itself.

> why in the first place do you need to clone this object

That object is embedded within another object, so not much choice.
I wonder why Storable completely ignores the value returned by STORABLE_thaw. I mean, even if I return a new object and return it, it is ignored.

**Comment by dur-randir** [comment]
>so pretty much useless except to modify in-place the object created by Storable itself.

This is the way. But again, you have to report this to module's author.


>even if I return a new object and return it, it is ignored.

This might be a separate feature request for Storable, but it's unrelated to this problem - as again, module's author would need to implement it.

**Comment by jackdeguest** [comment]
> This is the way. But again, you have to report this to module's author.

Well, you should document this limitation clearly in the pod to avoid waste of time or unexpected issues arising then.

I think it would be much quicker and more constructive to solve the problem at the core and have some hook in Storable for XS modules since Storable creates their object, but they are not working.

As a comparison, look at how Sereal or CBOR::XS handles it.

**Comment by dur-randir** [comment]
>As a comparison, look at how Sereal or CBOR::XS handles it.

But they still can't (de)serialise HTTP::XSHeaders, so it's not the matter of how good or bad their API is. It's a fundamental problem of having data invisible to Perl.

**Comment by jackdeguest** [comment]
> But they still can't (de)serialise HTTP::XSHeaders

It works with Sereal and CBOR:XS, because they both take what is returned by the special subroutine `THAW`

**Comment by dur-randir** [comment]
```
use HTTP::XSHeaders;

my $f = HTTP::XSHeaders->new;

use Sereal qw/encode_sereal decode_sereal/;
my $z=decode_sereal(encode_sereal($f));
$z->as_string;
```

With the expected output
```
hl is not an instance of HTTP::XSHeaders at foo.pl line 20.
```

So, out of the box, they do not work. Maybe you've written some custom handler routine and injected it into the HTTP::XSHeaders namespace, but then you can still do the same with Storable (though it'd be harder, but still not impossible).

**Comment by demerphq** [comment]
On Fri, 22 Jul 2022 at 10:43, Sergey Aleynikov ***@***.***>
wrote:

> use HTTP::XSHeaders;
>
> my $f = HTTP::XSHeaders->new;
>
> use Sereal qw/encode_sereal decode_sereal/;
> my $z=decode_sereal(encode_sereal($f));
> $z->as_string;
>
> With the expected output
>
> hl is not an instance of HTTP::XSHeaders at foo.pl line 20.
>
> So, out of the box, they do not work. Maybe you've written some custom
> handler routine and injected it into the HTTP::XSHeaders namespace, but
> then you can still do the same with Storable (though it'd be harder, but
> still not impossible).
>
I have not looked at whether HTTP::XSHeaders supports the hooks, but in
Sereal support for FREEZE/THAW is not enabled by default, you need to
enable the "freeze_callbacks" option in the encoder.

Yves





-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by dur-randir** [comment]
>you need to enable the "freeze_callbacks" option in the encoder.

It (unsurprisingly) didn't matter.

**Comment by jackdeguest** [comment]
> So, out of the box, they do not work. Maybe you've written some custom handler routine and injected it into the HTTP::XSHeaders namespace, but then you can still do the same with Storable (though it'd be harder, but still not impossible).

Please refer to my [example code to reproduce the bug](https://github.com/Perl/perl5/issues/19984#issue-1314199155), who is the issue being discussed.

Obviously, in this hypothetical `My::Headers` package, there could be a `STORABLE_thaw` subroutine, but it would not matter because Storable ignores what is returned.

When using Sereal or CBOR::XS, in this package inheriting from `HTTP::XSHeaders`, I have implemented a `FREEZE` and `THAW` subroutines and they work well.

**Comment by jackdeguest** [comment]
> > you need to enable the "freeze_callbacks" option in the encoder.
> 
> It (unsurprisingly) didn't matter.

It works well when this option is enabled. It has Sereal look for `FREEZE`, which consequently trigger `THAW` upon deserialisation, [as documented](https://metacpan.org/pod/Sereal::Encoder#FREEZE/THAW-CALLBACK-MECHANISM). Sereal and CBOR::XS both accept what is being returned by `THAW`, countrary to `Storable`.

**Comment by haarg** [comment]
It is possible for HTTP::XSHeaders to implement a `STORABLE_thaw` method which modifies the object created by Storable to make a working object. While the API of `STORABLE_thaw` is not idea, it would not prevent this from working. If you want that to work, file a request with the author or HTTP::XSHeaders.

This is not a bug.

**Comment by jackdeguest** [comment]
> This is not a bug.

Seriously? The object created by Storable does not allow effective calls to the underlying package methods, in turn leading to fatal errors, and you do not call this a bug?

**Comment by haarg** [comment]
No serialization library will be able to deserialize an HTTP::XSHeaders object without having a hook implemented. This is the case for many other objects implemented in XS which do not store their data in the standard perl data structures.

**Comment by jackdeguest** [comment]
> No serialization library will be able to deserialize an HTTP::XSHeaders object without having a hook implemented.

Maybe so, but what it produces is buggy. One cannot simply not call any method with the object hence created, and Storable ignores the output from STORABLE_thaw. In effect, this is not working and crashes, so this is truly a bug.

If you would rather, make a note on that in the documentation, or maybe have Storable die when dealing with an XS object, but do not pretend the object created and that does not work is not buggy.

**Comment by haarg** [comment]
HTTP::XSHeaders does not have a STORABLE_thaw method. If it implemented one, deserializing would work.

**Comment by jackdeguest** [comment]
> HTTP::XSHeaders does not have a STORABLE_thaw method. If it implemented one, deserializing would work.

Ok, then Storable should not create a HTTP::XSHeaders object on its own then. It should detect the `STORABLE_thaw` method is missing and die, because the resulting object created by Storable (not by HTTP::XSHeaders) does not work.

**Comment by Leont** [comment]
> Ok, then Storable should not create a HTTP::XSHeaders object on its own then. It should detect the STORABLE_thaw method is missing and die, because the resulting object created by Storable (not by HTTP::XSHeaders) does not work.

Except most objects wouldn't need that at all, so that would be even more unhelpful.

It's firmly a WONTFIX, not because we don't want to, but because it can't be done.

**Comment by jackdeguest** [comment]
Will you not even make a mention of this limitation in the documentation?

**Comment by Leont** [comment]
> Will you not even make a mention of this limitation in the documentation?

I have no idea what limitation you mean, and frankly this thread is more a support request than a bug report, for which there are many other venues.

**Comment by jackdeguest** [comment]
> I have no idea what limitation you mean

That's obviously because you have not been paying attention or read carefully the issue I raised here. Feel free to discard it, but it is what it is. Turning a blind eye on this is not proper for the module users in my opinion.

**Comment by hvds** [comment]
> > I have no idea what limitation you mean
> 
> That's obviously because you have not been paying attention or read carefully the issue I raised here. Feel free to discard it, but it is what it is. Turning a blind eye on this is not proper for the module users in my opinion.

The first line of the description in Storable's documentation reads: "The Storable package brings persistence to your Perl data structures containing SCALAR, ARRAY, HASH or REF objects". I think that is about as prominent a notice of its limitations as you could ask for.

However I _would_ like to see a more flexible interface for thawing objects - there are various situations I can imagine that would benefit from an interface that allows you to construct and return the thawed item. A feature request for the module would seem like the first step for that.

**Comment by jackdeguest** [comment]
> The first line of the description in Storable's documentation reads: "The Storable package brings persistence to your Perl data structures containing SCALAR, ARRAY, HASH or REF objects". I think that is about as prominent a notice of its limitations as you could ask for.

And an XS module object does qualify as a `REF object` and yet it fails to work, since in that [concrete example](https://github.com/Perl/perl5/issues/19984#issue-1314199155), when using that object created by Storable on that module methods, the object would die with the error: `hl is not an instance of HTTP::XSHeaders`

Thus, it seems the documentation needs to be expanded to include XS modules as well, don't you think?

**Comment by Grinnz** [comment]
Actually a blessed object could use any underlying structure (the term "object" in that sentence does not refer to blessed objects), regardless of whether it's XS. A blessed CODE object for example would not be restorable without assistance from the object class as described before, because it is not a SCALAR, ARRAY, HASH, or REF structure. A more common problematic example would be a blessed filehandle (GLOB containing an IO) like File::Temp. In this case it is not the top level object that is the problem as it's a HASH, but that it doesn't use that object to store anything because its data is stored in C structures.

**Comment by jackdeguest** [comment]
> the term "object" in that sentence does not refer to blessed objects), regardless of whether it's XS

Thank you for this clarification. What you clarified gives further ground to the need to update the documentation.
I honestly am not sure what such a big deal it is to improve a documentation. Making things clearer and more usable for the module users are always a good thing.

**Comment by Grinnz** [comment]
Of course, documentation can always be improved, suggestions in a documentation issue or PR would be welcome.

**Comment by jackdeguest** [comment]
Excellent and I am glad to read that. I have made suggestions here already, and, although I would be happy to issue a PR, given the technicality of Storable, it seems more suitable to leave the proper wording to those responsible for that module.
