### ISSUE TITLE
Format in fill-mode has inconsistent behaviour splitting on hyphen

### ISSUE THREAD

**Issue by pmqs** [Perl/perl5#19985]
[This issue is a summary of a short thread on per5-porters]

I’m using a format with fill-mode. Default characters to split a long string are space, newline and hyphen. I’m seeing inconsistent behaviour when a hyphen is used to split a string.

Here is sample code that illustrates the problem

```
$VALUE = "12345678ABC-DEFG-HI-J-abcdefg"; 
$VALUE2 = $VALUE;

format DATA =
^<<<~~ ^<<<~~
$VALUE,  $VALUE2
.

select(STDOUT);
$~ = 'DATA';

write ;
```
With perl 5.18 or less I see this. All looks fine
```
1234   1234
5678   5678
ABC-   ABC-
DEFG   DEFG
-HI-   -HI-
J-     J-
abcd   abcd
efg    efg
```
But with 5.20 or greater I get this output
```
1234   1234
5678   5678
ABC-    ABC-
DEFG-   DEFG-
HI-J-   HI-J-
abcd   abcd
efg    efg
```
Note the lines where the hyphen is used to split the string are one character too wide. That breaks the formatting.

Nick Clark (@nwc10 ) tracked down the bug to submit 9b4bdfd44e0e6d44a447f231c281f967c7ca35c9.

```
.../bisect.pl --target=miniperl -we '$VALUE = "12345678ABC-DEFG-HI-J-abcdefg"; $VALUE2 = $VALUE; formline "^<<<~~ ^<<<~~\n", $VALUE,  $VALUE2; exit(length $^A == 88)'

[fans spin]

9b4bdfd44e0e6d44a447f231c281f967c7ca35c9 is the first bad commit commit 9b4bdfd44e0e6d44a447f231c281f967c7ca35c9
Author: David Mitchell <[davem@iabyn.com](mailto:davem@iabyn.com)>
Date:   Thu Nov 7 12:17:26 2013 +0000

    fix chop formats with non PV vars

    [perl #119847],  [perl #119849], [perl #119851]

    Strange vars like ties, overloads, or stringified refs (and in recent
    perls, pure NOK vars) would generally do the wrong thing in formats
    when the var is treated as a string and repeatedly chopped, as in
    ^<<<~~ and similar. This would manifest itself in infinite loops, utf8
    errors etc. A recent change that stopped a stringified NOK getting
    converted into a POK made the same badness happen for plain NVs too.

    This commit contains two main fixes. First, the chopping was done
    using sv_chop(), which only worked on POK strings. If its !POK, we now do
    sv_setpvn() instead, which is less efficient, but will ensure the right
    thing is always done.

    Secondly, we make sure that the sv is accessed only once per cycle,
    doing s = SvPV(sv, len) or similar. After that, all access is done only
    via s and len. One place was using SvPVX(sv), and several places
    were using the sv for utf8<->byte length conversions, such as
    sv_pos_b2u().

    It turns out that all the complex utf8 handling could be enormously
    simplified. Since the code that needed to do utf8/byte length conversions
    already scanned the string looking for suitable split points (such as
    spaces or \n or \r), it was easiest to include any utf8 processing in the
    same loop - i.e. incrementing s by UTF8SKIP(s) each time, but incrementing
    the character count by 1.

    The original diagnosis and reporting of this issue was done by Nicholas
    Clark, who also supplied most of the tests.

 pp_ctl.c     | 213 ++++++----------
 t/op/write.t | 811 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-
 2 files changed, 889 insertions(+), 135 deletions(-) bisect run success
```

**Comment by jkeenan** [comment]
Behavior observed on FreeBSD as well as Linux.  Also first bad commit confirmed as:
```
commit 9b4bdfd44e0e6d44a447f231c281f967c7ca35c9 (refs/bisect/bad)
Author:     David Mitchell <davem@iabyn.com>
AuthorDate: Thu Nov 7 12:17:26 2013 +0000
Commit:     David Mitchell <davem@iabyn.com>
CommitDate: Mon Nov 11 11:21:40 2013 +0000
```
@iabyn, can you take a look?

**Comment by iabyn** [comment]
On Fri, Jul 22, 2022 at 09:23:46AM -0700, Paul Marquess wrote:
> [This issue is a summary of a short thread on per5-porters]
> 
> I’m using a format with fill-mode. Default characters to split a long string are space, newline and hyphen. I’m seeing inconsistent behaviour when a hyphen is used to split a string.

Now fixed in blead by the following commit. Note the comment about the
lack of testing!

    commit 5d7d8ffc298134400c054265830d47abb6ee7845
    Author:     David Mitchell ***@***.***>
    AuthorDate: Fri Jul 29 22:39:53 2022 +0100

    formats: fix splitting on non-spaces
    
    GH #19985
    
    formats have a mode where they can repeatedly split a string to fill
    within a fixed text width, splitting on (by default), spaces, newlines
    and hyphens.
    
    The splitting code was heavily rewritten by me in
    v5.19.5-218-g9b4bdfd44e, but in that patch I introduced a couple of
    off-by-one errors when splitting on non-white-space characters (i.e. the
    hyphen by default).
    
    It turns out that splitting on a hyphen is completely untested in core,
    and further, no one noticed the problems in the wild until this ticket,
    8 years later!
    
    The first issue, and the one in the bug report, is that when splitting,
    the calculation for how many spaces to pad to the end of the field was
    off by one, so:
    
        $v1 = "AB-CDE";
    
        format STDOUT =
        [^<<<]~~
        $v1
        .
    
        write;
    
    gives:
    
        [AB-  ]
        [CDE ]
    
    but should have given:
    
        [AB- ]
        [CDE ]
    
    The second issue was that it was detecting a hyphen one character
    further along than the maximum field length and still splitting it there:
    as above, but
    
        $v1 = "ABCD-E";
    
    gives:
    
        [ABCD-]
        [E   ]
    
    but should have given:
    
        [ABCD]
        [-E  ]
    
    The latter was because the non-space split code was using the same logic
    as the split-on-space code, which is allowed to split on a space which
    is one character beyond the maximum length.
    
    This commit fixes both issues, and adds some tests.


-- 
Diplomacy is telling someone to go to hell in such a way that they'll
look forward to the trip

**Comment by pmqs** [comment]
>     It turns out that splitting on a hyphen is completely untested in core,
>     and further, no one noticed the problems in the wild until this ticket,
>     8 years later!

I've used a format with fill-mode in [zipdetails](https://github.com/pmqs/zipdetails) for years and not noticed this issue. Only spotted it because I has a zip file that happened to include filenames with hyphens in one of my unit tests --  worked with a pre 5.20 Perl, but failed with newer versions. 

Anyway, good to see it fixed so quickly.
