### ISSUE TITLE
BBC: Blead Breaks Sub::Metadata

### ISSUE THREAD

**Issue by cjg-cguevara** [Perl/perl5#20020]
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.42 running under perl 5.37.3.

-----------------------------------------------------------------
[Please describe your issue here]

BBC: Blead Breaks Sub::Metadata

Please see http://matrix.cpantesters.org/?dist=Sub::Metadata

[Please do not change anything below this line]
-----------------------------------------------------------------
---
Flags:
    category=core
    severity=low
---
Site configuration information for perl 5.37.3:

Configured by cpan at Fri Jul 29 16:06:17 EDT 2022.

Summary of my perl5 (revision 5 version 37 subversion 3) configuration:
  Commit id: 68f7e83eef77f17571800a31dc20f6df48e72e9a
  Platform:
    osname=openbsd
    osvers=7.1
    archname=OpenBSD.amd64-openbsd-thread-multi
    uname='openbsd cjg-openbsd7 7.1 generic#3 amd64 '
    config_args='-des -Dprefix=~/bin/perl-blead -Dscriptdir=~/bin/perl-blead/bin -Dusedevel -Duse64bitall -Duseithreads'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-pthread -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    optimize='-O2'
    cppflags='-pthread -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='OpenBSD Clang 13.0.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags ='-pthread -Wl,-E  -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/lib/clang/13.0.0/lib /usr/lib /usr/local/lib
    libs=-lpthread -lm -lutil -lc
    perllibs=-lpthread -lm -lutil -lc
    libc=/usr/lib/libc.so.96.1
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags='-DPIC -fPIC '
    lddlflags='-shared -fPIC  -L/usr/local/lib -fstack-protector-strong'

---
@INC for perl 5.37.3:
    /home/cpan/bin/perl-blead/lib/site_perl/5.37.3/OpenBSD.amd64-openbsd-thread-multi
    /home/cpan/bin/perl-blead/lib/site_perl/5.37.3
    /home/cpan/bin/perl-blead/lib/5.37.3/OpenBSD.amd64-openbsd-thread-multi
    /home/cpan/bin/perl-blead/lib/5.37.3

---
Environment for perl 5.37.3:
    HOME=/home/cpan
    LANG (unset)
    LANGUAGE (unset)
    LC_ALL=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl-blead/bin:/home/cpan/bin:/home/cpan/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin:/usr/games
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/bash

**Comment by Leont** [comment]
Fix submitted as #20021

**Comment by jkeenan** [comment]
Bisection points to the following commit:
```
ec11e33811b7a90a27013992efdb3c6ca76787fd is the first bad commit
commit ec11e33811b7a90a27013992efdb3c6ca76787fd
Author: Paul "LeoNerd" Evans <leonerd@leonerd.org.uk>
Date:   Sat Jul 9 12:22:48 2022 +0100
Commit:     Paul Evans <leonerd@leonerd.org.uk>
CommitDate: Tue Jul 26 11:32:40 2022 +0100


    Rename CVf_METHOD to CVf_NOWARN_AMBIGUOUS
    
    Also renames the CvMETHOD* macro family to CvNOWARN_AMBIGUOUS*
```
That's consistent with @Leont's diagnosis and fix in https://github.com/Perl/perl5/pull/20021.  I'm now testing that branch and will merge it to blead once testing is completed satisfactorily.

**Comment by jkeenan** [comment]
Should be fixed by https://github.com/Perl/perl5/pull/20021, now merged to blead.
