### ISSUE TITLE
[doc] Issues with perlfaq4

### ISSUE THREAD

**Issue by carlos157oliveira** [Perl/perl5#20050]
## Where

perlfaq4

Link: https://perldoc.perl.org/perlfaq4

## Description
Good evening.

I have been reading perlfaq4 and noted some inconsistencies, which could be just my doubts, however I would like to point them out section by section.

### [Why doesn't & work the way I want it to?](https://perldoc.perl.org/perlfaq4#Why-doesn't-&-work-the-way-I-want-it-to?)

The final code sample checks if the result of the bit-wise AND doesn't yield a string with no null bytes, which means that it checks if the result has null bytes. It seems the opposite of the intention.

### [How do I find the day or week of the year?](https://perldoc.perl.org/perlfaq4#How-do-I-find-the-day-or-week-of-the-year?)

It says:

> To get the day of year for any date, use POSIX's mktime to get a time in epoch seconds for the argument to localtime.

but the code sample below it gets the week of the year.

### [How can I expand variables in text strings?](https://perldoc.perl.org/perlfaq4#How-can-I-expand-variables-in-text-strings?)

It says:

> The first /e evaluates $1 on the replacement side and turns it into $foo.

but from my tests, it isn't necessary the /e flag to work with the special variable $1. It is needed only if you are going to put more complex code inside the replacement. I found it nice that the author tried to be didactic to explain the */ee* flag (double-e flag), but it doesn't seem so exactly when talking about the single-e flag */e* in the path towards it.

### [How can I know how many entries are in a hash?](https://perldoc.perl.org/perlfaq4#How-can-I-know-how-many-entries-are-in-a-hash?)

The phrase:

> You can use the keys() built-in function in scalar context to find out have many entries you have in a hash:

seems misspelled. I think the correct one has "how" in the place of the first "have":

> You can use the keys() built-in function in scalar context to find out how many entries you have in a hash:

### [How do I manipulate arrays of bits?](https://perldoc.perl.org/perlfaq4#How-do-I-manipulate-arrays-of-bits?)

Using the first two code samples of this section, I tried to convert a list of integers into a bit vector then back to a list, but it didn't work as I expected. I confess that I don't fully understand the algorithm used for the conversions, maybe there is something I messed up.

## Gratitude

Thank you all for putting together Perl and the documentation. I am so sorry if in my exposing I gave the impression of being too critic. What I really want is to hang out with you guys.

**Comment by Leont** [comment]
The FAQ is maintained at https://github.com/perl-doc-cats/perlfaq, you probably want to the people over there.

**Comment by carlos157oliveira** [comment]
Thank you Mr. Leont. I opened an issue there as well.

**Comment by Grinnz** [comment]
Closing as issue is moved to https://github.com/perl-doc-cats/perlfaq/issues/101
