### ISSUE TITLE
Can not create a lexical sub in `use` declaration

### ISSUE THREAD

**Issue by EvanCarroll** [Perl/perl5#20062]
Ovid writes in MooseX::Extended,

> In fact, there are a variety of Moose functions which would work better if they ran at compile-time instead of runtime, making them look a touch more like native functions. My various attempts at solving this have failed, but I confess I didn't try too hard.

This should be easy.

```perl
package Foo;
use strict;
use warnings;

use Sub::Util;
sub import {
  my $sub = $_[1];
  printf("Calling %s\n", Sub::Util::subname($sub));
  $sub->();
}

1;
```

Followed by,

    PERL5LIB=lib perl -E'package Bar { use Foo my sub baz { 42 }; }'

However, that does not compile.

    PERL5LIB=lib perl -E'package Bar { use Foo my sub baz { 42 }; }'

But this does (though it's not useful for our case...)

    perl -MO=Deparse -E'package Bar { use Foo my $foo }'
    perl -MO=Deparse -E'package Bar { use Foo my $foo = 42 }'

Moreover, if you write this,

    PERL5LIB=lib perl -E'package Bar { use Foo my sub { 42 }; }'

You'll get this error,

> Missing name in "my sub" at -e line 1.

Which makes adding the name all the more sus that it doesn't work as intended.

**Comment by haarg** [comment]
`my sub foo` is not an expression, just like `sub foo` is not. They are statements. So they can't be used as parameters.

**Comment by EvanCarroll** [comment]
Hrm. Did not know that. That's weird. So there is no way to create a named routine as an expression without using a `do` block.

This is a very glorious language.

    perl -E'package Bar { use Foo do { my sub export { die 42 }; \&export } }'
    
Works exactly as I'd expect it.
