### ISSUE TITLE
How Would I embed perl scripts into my C program that aren't on the filesystem.

### ISSUE THREAD

**Issue by beemibrahim** [Perl/perl5#20071]
I have managed to build the **perl** source and embed **perl** into my **C** program.

I want to encrypt **perl scripts/modules** inside my **application** since they
are **private**.

I will decrypt the **perl scripts/modules** at **runtime** and feed them to the
**perl interpreter** so that it can run them.

However, every **example** on the **perldocs**, passes the **perl** script to the **executable**.

This is not what I want, since the **script** isn't going to be on the **filesystem**.

Another problem, is that my **script** includes other **scripts/modules** too, which also aren't on the **filesystsem**.

I need to somehow tell the **perl interpreter** which **script/module** I am referencing for every **include** statement.

The **perl** functions also don't have good **documentation** that I can refer to.

**Thank you**

**Comment by Leont** [comment]
There are legitimate questions, but as a bug tracker this is not the right venue for support questions. You probably should try another resource such as StackOverflow.
