### ISSUE TITLE
Embedding Perl into C throws 37 unresolved externals on Windows

### ISSUE THREAD

**Issue by beemibrahim** [Perl/perl5#20075]
I built perl statically using `ALL_STATIC` `CCTYPE=MSVC143` `BUILD_STATIC` in the win32 makefile and linked to the libraries : 

- perl537s.lib

- perl537.lib 

And when I compile it on Visual Studio I get these errors : 

```
1>perl537s.lib(util.obj) : error LNK2001: unresolved external symbol __imp_htonl
1>perl537s.lib(util.obj) : error LNK2001: unresolved external symbol __WSAFDIsSet
1>perl537s.lib(win32.obj) : error LNK2001: unresolved external symbol __imp_InitCommonControls
1>perl537s.lib(pp_sys.obj) : error LNK2001: unresolved external symbol __imp_WSAGetLastError
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_setsockopt
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_ioctlsocket
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_sendto
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_htons
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getsockopt
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_recv
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_WSASocketA
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_recvfrom
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_gethostname
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getservbyname
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_inet_ntoa
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_connect
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_ntohs
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_send
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getservbyport
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getprotobyname
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_gethostbyaddr
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol WSCEnumProtocols
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getsockname
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_inet_addr
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getpeername
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_WSAStartup
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getprotobynumber
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_WSASetLastError
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_listen
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_shutdown
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_ntohl
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_select
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_gethostbyname
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_closesocket
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_bind
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_accept
1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_WSACleanup
```

Does anybody know what I can do to resolve this ?

I did nothing wrong.

For some reason most of the unresovled symbols are coming from a file called "win32sck.obj" do I have to include a "Socket" option or something ??

This is on the latest version of perl ( 5.37.2 )

**Comment by demerphq** [comment]
On Wed, 10 Aug 2022 at 10:39, ibrahim muhmud usmani <
***@***.***> wrote:

> I compiled perl statically and linked to the libraries :
>
>    -
>
>    perl537s.lib
>    -
>
>    perl537.lib
>
> And when I compile it on Visual Studio I get these errors :
>
> 1>perl537s.lib(util.obj) : error LNK2001: unresolved external symbol __imp_htonl
> 1>perl537s.lib(util.obj) : error LNK2001: unresolved external symbol __WSAFDIsSet
> 1>perl537s.lib(win32.obj) : error LNK2001: unresolved external symbol __imp_InitCommonControls
> 1>perl537s.lib(pp_sys.obj) : error LNK2001: unresolved external symbol __imp_WSAGetLastError
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_setsockopt
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_ioctlsocket
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_sendto
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_htons
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getsockopt
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_recv
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_WSASocketA
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_recvfrom
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_gethostname
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getservbyname
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_inet_ntoa
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_connect
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_ntohs
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_send
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getservbyport
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getprotobyname
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_gethostbyaddr
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol WSCEnumProtocols
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getsockname
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_inet_addr
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getpeername
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_WSAStartup
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getprotobynumber
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_WSASetLastError
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_listen
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_shutdown
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_ntohl
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_select
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_gethostbyname
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_closesocket
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_bind
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_accept
> 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_WSACleanup
>
> Please fix this bug.
>
Hi,

We dont have a lot of Windows engineers on the project so you probably need
to try to help them help you. What have you done to debug this? What were
the steps someone needs to replicate the issue? What do you think should be
done to resolve it?

Also, do realize that nobody gets paid to do this, they do it because it is
fun, and as such saying things like "please fix this bug" isn't likely to
get the help you want, its your itch you should scratch it, that is the
whole point of open source. Saying "Does anybody know what I can do to
resolve this?" on the other hand would likely get much better results.

FWIW It sounds like you are doing some interesting stuff and I am
sure folks will want to help if you make it sound fun. ;-)

cheers,
Yves


-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by AnFunctionArray** [comment]
> CCTYPE=MSVC143

Try different CCTYPE - or rather uncomment the specific version in the make file

**Comment by beemibrahim** [comment]
> On Wed, 10 Aug 2022 at 10:39, ibrahim muhmud usmani < ***@***.***> wrote: I compiled perl statically and linked to the libraries : - perl537s.lib - perl537.lib And when I compile it on Visual Studio I get these errors : 1>perl537s.lib(util.obj) : error LNK2001: unresolved external symbol __imp_htonl 1>perl537s.lib(util.obj) : error LNK2001: unresolved external symbol __WSAFDIsSet 1>perl537s.lib(win32.obj) : error LNK2001: unresolved external symbol __imp_InitCommonControls 1>perl537s.lib(pp_sys.obj) : error LNK2001: unresolved external symbol __imp_WSAGetLastError 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_setsockopt 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_ioctlsocket 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_sendto 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_htons 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getsockopt 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_recv 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_WSASocketA 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_recvfrom 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_gethostname 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getservbyname 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_inet_ntoa 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_connect 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_ntohs 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_send 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getservbyport 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getprotobyname 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_gethostbyaddr 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol WSCEnumProtocols 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getsockname 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_inet_addr 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getpeername 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_WSAStartup 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_getprotobynumber 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_WSASetLastError 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_listen 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_shutdown 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_ntohl 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_select 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_gethostbyname 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_closesocket 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_bind 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_accept 1>perl537s.lib(win32sck.obj) : error LNK2001: unresolved external symbol __imp_WSACleanup Please fix this bug.
> Hi, We dont have a lot of Windows engineers on the project so you probably need to try to help them help you. What have you done to debug this? What were the steps someone needs to replicate the issue? What do you think should be done to resolve it? Also, do realize that nobody gets paid to do this, they do it because it is fun, and as such saying things like "please fix this bug" isn't likely to get the help you want, its your itch you should scratch it, that is the whole point of open source. Saying "Does anybody know what I can do to resolve this?" on the other hand would likely get much better results. FWIW It sounds like you are doing some interesting stuff and I am sure folks will want to help if you make it sound fun. ;-) cheers, Yves
> […](#)
> -- perl -Mre=debug -e "/just|another|perl|hacker/"

Oh you don't get paid.

I've updated the question

**Comment by beemibrahim** [comment]
> > CCTYPE=MSVC143
> 
> Try different CCTYPE - or rather uncomment the specific version in the make file

I am using Visual Studio 2022 and "MSVC143" is for Visual Studio 2022. Other options won't work for me

**Comment by AnFunctionArray** [comment]
@beemibrahim Same but nevertheless do try the other options - at least the 2019 - because I remember having similar issues with the 2022 option.

**Comment by beemibrahim** [comment]
I am gonna make a reproducible sample

**Comment by Leont** [comment]
Sounds like it isn't linking to the ws2_32 library but it should.

**Comment by beemibrahim** [comment]
Hmm, for some reason the reproducible sample didn't reproduce the error.

Well I guess I am done here.
