### ISSUE TITLE
locale changes causes failures with -Duseithreads

### ISSUE THREAD

**Issue by bram-perl** [Perl/perl5#20085]
After the merge of khw/locale-3 builds with `-Duesithreads` appear to trigger test failures.

Smoke reports:

* failure in lib/locale.t: https://perl5.test-smoke.org/report/5021335
* failure in t/uni/fold.t, t/re/subst.t, t/re/subst_wamp.t, t/re/substT.t: https://perl5.test-smoke.org/report/5021377
* failute in t/uni/fold.t, t/re/subst.t, t/re/subst_wamp.t, t/re/substT.t + others: https://perl5.test-smoke.org/report/5021356 [I am not certain if the other test failures are related, they did not appear to happen before the commits were merged]

I was able to reproduce the failure in t/re/subst.t (but need confirmation if the smoke setup is the same);
I was not yet able to reproduce the lib/locale.t failure.

Using current blead **with** `-Duseithreads`:

        $ ./Configure -des -Dusedevel -Duseithreads
        $ make -j8
        $ make test_prep
        $ cd t
        $ LC_ALL= LANG= LANGUAGE= LC_CTYPE="en_US.utf-8" ./perl harness re/subst.t
        re/subst.t .. 1/278 # Failed test 263 - \b matches Latin1 before string, mid, and end, /l at re/subst.t line 1070
        #      got "!á!.!è!"
        # expected "á.è"
        re/subst.t .. Failed 1/278 subtests

        Test Summary Report
        -------------------
        re/subst.t (Wstat: 0 Tests: 278 Failed: 1)
          Failed test:  263
        Files=1, Tests=278,  0 wallclock secs ( 0.02 usr  0.01 sys +  0.10 cusr  0.03 csys =  0.16 CPU)
        Result: FAIL

Using current blead **without** `-Duseithreads`:

        $ ./Configure -des -Dusedevel
        $ make -j8
        $ make test_prep
        $ cd t
        $ LC_ALL= LANG= LANGUAGE= LC_CTYPE="en_US.utf-8" ./perl harness re/subst.t
        re/subst.t .. ok
        All tests successful.
        Files=1, Tests=278,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.09 cusr  0.02 csys =  0.13 CPU)
        Result: PASS

**Bisecting:**

Bisecting points to commit 19e550d7feff0e915e0f181add94aebe4e22c38b ( @khwilliamson ):

        commit 19e550d7feff0e915e0f181add94aebe4e22c38b
        Author:     Karl Williamson <khw@cpan.org>
        AuthorDate: Wed Jul 20 16:31:35 2022 -0600
        Commit:     Karl Williamson <khw@cpan.org>
        CommitDate: Tue Aug 9 18:05:59 2022 -0600

            locale.c: Don't waste time executing a no-op

            If we're trying to change the locale to what it already is, that's a
            no-op.  This skips that work.  As noted in the comments, this also led
            to subtle bugs with newlocale() trying to free the basis operand, and
            giving bad results.

**Trimming:**

Trimming the test in t/re/subst.t:

        use Test::More;
        use POSIX;

        my $a_acute = "\N{LATIN SMALL LETTER A WITH ACUTE}";
        my $egrave  = "\N{LATIN SMALL LETTER E WITH GRAVE}";

        setlocale(&POSIX::LC_ALL, "C");
        use locale;

        is("$a_acute.$egrave" =~ s/\b/!/gr, "$a_acute.$egrave", '\\b matches Latin1 before string, mid, and end, /l');

        done_testing();

Running:

        $ LC_ALL= LANG= LANGUAGE= LC_CTYPE=en_US.utf-8 ./perl -I../lib foo.t
        not ok 1 - \b matches Latin1 before string, mid, and end, /l
        #   Failed test '\b matches Latin1 before string, mid, and end, /l'
        #   at foo.t line 13.
        #          got: '!á!.!è!'
        #     expected: 'á.è'
        1..1
        # Looks like you failed 1 test of 1.

        $ LC_ALL=en_US.utf-8 ./perl -I../lib foo.t
        ok 1 - \b matches Latin1 before string, mid, and end, /l
        1..1

**Additional information:**

Also observed, in the build with `-Duseithreads`:

* `LC_ALL= LANG= LANGUAGE= ./perl harness re/subst.t` => PASS
* `LC_ALL= LANG= LANGUAGE= LC_CTYPE=en_US.utf-8 ./perl harness re/subst.t` => FAIL
* `LC_ALL= LANG= LANGUAGE= LC_TIME=en_US.utf-8 ./perl harness re/subst.t` => PASS
* `LC_ALL= LANG= LANGUAGE= LC_CTYPE=en_US.utf-8 LC_TIME=en_US.utf-8 ./perl harness re/subst.t` => FAIL
* `LC_ALL= LANG= LANGUAGE= LC_CTYPE=en_US.utf-8 LC_NUMERIC=en_US.utf-8 ./perl harness re/subst.t` => PASS
* `LC_ALL= LANG= LANGUAGE= LC_CTYPE=en_US.utf-8 LC_TELEPHONE=en_US.utf-8 ./perl harness re/subst.t` => PASS

**Comment by jkeenan** [comment]
What I got on Linux:
```
$ uname -mrs
Linux 5.17.5-x86_64-linode154 x86_64

$ ./perl -Ilib -v | head -2 | tail -1
This is perl 5, version 37, subversion 3 (v5.37.3 (v5.37.2-150-gd53dc4a)) built for x86_64-linux-thread-multi

$ ./perl -Ilib -V:config_args
config_args='-des -Dusedevel -Duseithreads';

$ cd t;TEST_JOBS=1 LC_ALL= LANG= LANGUAGE= LC_CTYPE=en_US.utf-8 ./perl harness re/subst.t uni/fold.t re/subst_wamp.t re/substT.t ../lib/locale.t; cd -
re/subst.t ....... 1/278 # Failed test 263 - \b matches Latin1 before string, mid, and end, /l at re/subst.t line 1070
#      got "!�!.!�!"
# expected "�.�"
re/subst.t ....... Failed 1/278 subtests 
uni/fold.t ....... 15968/? # Failed test 18676 - use locale; fc(qq{\x{181}}), lc(qq{\x{181}}) when qq{\x{181}} is in latin-1 at uni/fold.t line 465
#      got "\x{3bc}"
# expected "�"
# Failed test 18677 - use locale; fc(qq{\x{181}}), lc(qq{\x{181}}) when qq{\x{181}} is in latin-1 at uni/fold.t line 466
#      got "\x{3bc}"
# expected "�"
# Failed test 18844 - use locale; fc(qq{\x{223}}), lc(qq{\x{223}}) when qq{\x{223}} is in latin-1 at uni/fold.t line 465
#      got "ss"
# expected "�"
# Failed test 18845 - use locale; fc(qq{\x{223}}), lc(qq{\x{223}}) when qq{\x{223}} is in latin-1 at uni/fold.t line 466
#      got "ss"
# expected "�"
uni/fold.t ....... Failed 4/19232 subtests 
re/subst_wamp.t .. 1/278 # Failed test 263 - \b matches Latin1 before string, mid, and end, /l at ./re/subst.t line 1070
#      got "!�!.!�!"
# expected "�.�"
re/subst_wamp.t .. Failed 1/278 subtests 
re/substT.t ...... 1/278 # Failed test 263 - \b matches Latin1 before string, mid, and end, /l at ./re/subst.t line 1070
#      got "!�!.!�!"
# expected "�.�"
re/substT.t ...... Failed 1/278 subtests 
../lib/locale.t .. ok     

Test Summary Report
-------------------
re/subst.t     (Wstat: 0 Tests: 278 Failed: 1)
  Failed test:  263
uni/fold.t     (Wstat: 0 Tests: 19232 Failed: 4)
  Failed tests:  18676-18677, 18844-18845
re/subst_wamp.t (Wstat: 0 Tests: 278 Failed: 1)
  Failed test:  263
re/substT.t    (Wstat: 0 Tests: 278 Failed: 1)
  Failed test:  263
Files=5, Tests=20748,  2 wallclock secs ( 1.02 usr  0.00 sys +  1.96 cusr  0.17 csys =  3.15 CPU)
Result: FAIL
```
@khwilliamson, can you take a look?

**Comment by jkeenan** [comment]
> **Bisecting:**
> 
> Bisecting points to commit [19e550d](https://github.com/Perl/perl5/commit/19e550d7feff0e915e0f181add94aebe4e22c38b) ( @khwilliamson ):
> 
> ```
>     commit 19e550d7feff0e915e0f181add94aebe4e22c38b
>     Author:     Karl Williamson <khw@cpan.org>
>     AuthorDate: Wed Jul 20 16:31:35 2022 -0600
>     Commit:     Karl Williamson <khw@cpan.org>
>     CommitDate: Tue Aug 9 18:05:59 2022 -0600
> 

@bram-perl, I wanted to try to confirm your bisection results.  On Linux I tried the following invocation:
```
perl Porting/bisect.pl -Duseithreads \
--start=66a28734f9b468c01710ae9c15b1a7bbfef04ee0 \
--end=947b444cf66f17cb2c1db85542cf34afe4311a81 \
-- LC_ALL= LANG= LANGUAGE= LC_CTYPE=en_US.utf-8 ./perl -Ilib t/re/subst.t
```
But I didn't get good results:
```
...
HEAD is now at 66a2873 locale.c: Mv declarations closer to use in function
bad - non-zero exit from LC_ALL= LANG= LANGUAGE= LC_CTYPE=en_US.utf-8 ./perl -Ilib t/re/subst.t
Runner returned 256, not 0 for start revision at Porting/bisect.pl line 240.
That took 411 seconds.
```
Could you post your bisection command so that I can figure out what I did wrong?

**Comment by bram-perl** [comment]
> ```
> perl Porting/bisect.pl -Duseithreads \
> --start=66a28734f9b468c01710ae9c15b1a7bbfef04ee0 \
> --end=947b444cf66f17cb2c1db85542cf34afe4311a81 \
> -- LC_ALL= LANG= LANGUAGE= LC_CTYPE=en_US.utf-8 ./perl -Ilib t/re/subst.t
> ```

If you look at that bisect output then you'll see:
```
Can't exec "LC_ALL=": No such file or directory at /tmp/VDkFj5QIrg line 1171.
```

You need to provide it a command.. 
So either put it in a shell script or use something like `env LC_ALL= LANG= .... ./perl ....`

Your second problem is that `./perl -Ilib t/re/substs.t` exits with status code 0 regardless of test success/test failure.
Mapping test failures to a non zero-exit code is done in t/TEST or t/harness.. which you aren't using (which means exit code will always be 0).

As for what command I used: for this few commits it was faster to just do it manually then to figure out the proper options for bisect.pl.

An easier way to confirm the bisect: `git revert 19e550d7feff0e915e0f181add94aebe4e22c38b` and then repeat the test.

**Comment by bram-perl** [comment]
The environment variables in the smoke run of https://perl5.test-smoke.org/report/5021377:
```
Inside smoke, using %ENV:
============================================================
env LC/LANG
============================================================
LANG: 'en_US.UTF-8'
LC_CTYPE: 'en_US.UTF-8'
```

With these settings however *I* can not reproduce, as soon as I set 'LANG' the problem goes away.
