### ISSUE TITLE
WHILEM: matched 65535 out of 0..65535

### ISSUE THREAD

**Issue by AnFunctionArray** [Perl/perl5#20104]
So I was wondering why it wasn't matching at a an obvious match - apparently I had reached the limit wow.

**Comment by AnFunctionArray** [comment]
I don't know if it's a bug but it's an interesting corner case at least.

**Comment by AnFunctionArray** [comment]
The obvious solution is to use recursion at the end like: `(?<pattern>(something)*+(?&pattern)?+)`.

**Comment by demerphq** [comment]
Recently we merged a patch sequence that means that it should be trivial to replace all of these short integer counts with proper sized ones. @khwilliamson @hvds

**Comment by AnFunctionArray** [comment]
@demerphq Can you clarify - I recently run into the same problem again.

**Comment by AnFunctionArray** [comment]
Ok - I'm not sure but it looks like this solution works:

`(?<pattern>(?&something)*+((?&something)(?&pattern))?+)`
