### ISSUE TITLE
Unexpected output from 'git describe'

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#20130]
Today, when I update blead to HEAD, I see the following:
```
$ git describe
v5.37.2-255-g015aea7e08
```
This surprised me, because perl-5.37.3 was released yesterday, which normally would have meant that `git describe` would start with `v5.37.3`.  In addition, [smoke-test reports done overnight](https://perl5.test-smoke.org/search) since the release are also still showing `v5.37.2` in their descriptions.

If however I try a different invocation ...
```
$ git describe --tags
v5.37.3-31-g015aea7e08
```
... which is more what I expect.

Reading the manual, I see:
```
$ man git-describe
...
By default (without --all or --tags) git describe only shows annotated
tags. For more information about creating annotated tags see the -a and
-s options to git-tag(1).
```
So I suspect the tag was added without an annotation.  Can this be repaired so that `git describe` starts with `v5.37.3`?

**Comment by jkeenan** [comment]
@neilb or @tonycoz can you take a look at this?  Thanks.

**Comment by tonycoz** [comment]
Yes, it's unannotated, compare:
```
$ git show v5.37.2
tag v5.37.2
Tagger: Nicolas R <atoomic@cpan.org>
Date:   Wed Jul 20 23:16:41 2022 +0000

Third release of the v5.37 series

commit 7f9b65d969a1c8b44028cacbb9e88596d1e5a8a3 (tag: v5.37.2)
Author: Nicolas R <atoomic@cpan.org>
Date:   Wed Jul 20 23:06:45 2022 +0000

    perlhist: update release date for 5.37.2
...
```
vs
```
$ git show v5.37.3
commit 29b290ccaa79f40de7d941c9a79810119f5c6363 (tag: v5.37.3)
Author: Neil Bowers <neilb@neilb.org>
Date:   Sat Aug 20 18:04:38 2022 +0100

    Late addition to perldelta for a change related to FreeBSD

...
```

It's possible to convert the unannotated tag to annotated, see https://stackoverflow.com/questions/5002555/can-a-lightweight-tag-be-converted-to-an-annotated-tag but there may be problems getting it to remotes that already have fetched the tag.

From reading `git fetch` it appears updating the tag won't be automatically fetched to overwrite an already fetched tag unless the user does `--force`:
```
            Since Git
           version 2.20, fetching to update refs/tags/* works the same way as
           when pushing. I.e. any updates will be rejected without + in the
           refspec (or --force).
```

**Comment by Leont** [comment]
This is a case of "please do exactly what the RMG says". It uses `git tag -m`, which implies `-a` for the annotation. I guess Neil used a manual git tag instead. Possibly the RMG should be a bit more explicit about this needing to be an annotated tag.

**Comment by jkeenan** [comment]
So, should we attempt the following:
```
$ git tag -a -f "v5.37.3" 29b290ccaa79f40de7d941c9a79810119f5c6363
```
Experimenting locally suggests that this will do the right thing, though to get the annotated tag into one's local checkout, one would have to say `git fetch -f origin`.

**Comment by demerphq** [comment]
On Mon, 22 Aug 2022 at 02:06, Leon Timmermans ***@***.***> wrote:
>
> This is a case of "please do exactly what the RMG says". It uses git tag -m, which implies -a for the annotation. I guess neil used a manual git tag instead.

I'd take that a step further: let's get rid of the need for people to
correctly follow the  RMG and make a tool that does it right. IMO
written instructions like this are very often not followed correctly
due to human error.

Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by neilb** [comment]
> This is a case of "please do exactly what the RMG says". It uses git tag -m, which implies -a for the annotation. I guess neil used a manual git tag instead.

I followed the RMG and created an annotated tag. But because I'd temporarily lost my commit bit, I did a PR rather than pushing. I don't understand why, but Bram said that I should delete my tag from my local clone and github repo, and asked someone else to recreate the tag. I guess that was created without an annotation.

The real root cause:

> The RMG says early on to check that you have a commit bit. I didn't check, as I did two releases in the 5.35 series and just assumed I'd still be ok. Mea culpa.

**Comment by bram-perl** [comment]
>  I don't understand why, but Bram said that I should delete my tag from my local clone and github repo, and asked someone else to recreate the tag. I guess that was created without an annotation.

Some context on the why:
- @neilb  used his own fork of the repo to prepare for the 5.37.3 release (i.e. https://github.com/neilb/perl5)
- @neilb did correctly create a tag for the 5.37.3 release in his fork (i.e. https://github.com/neilb/perl5)
- due to not being able to commit to the 'real' repo (i.e. https://github.com/Perl/perl5) a PR was created
- @khwilliamson merged the PR with (I assume) github rebase & merge option
- result: commit-ids of what was added on https://github.com/Perl/perl5 did **not** match commit-ids of what was added on https://github.com/neilb/perl5. This made the tagging @neilb did on his fork "incorrect" because that commit did not exist in https://github.com/Perl/perl5.

This is why I told him to delete the tag (in his fork);
I then gave wrong instruction to @khwilliamson for creating the tag; I missed that it had to be an annotated tag.

A "problem" is that the RMG assumes your working on a clone of https://github.com/Perl/perl and not on a clone of your own fork.
The instruction for creating the release branch on your own fork are not really complete.. (one must add the https://github.com/Perl/perl5 repo to get the tags; without the tags tests will fail, + you need to be able to merge later which again require the real repo to be present; using PR+Github merge leads to different commit-ids and thus an invalid tag + ...)

So either way the RMG needs to be amended,
- to describe how to correctly use your own fork to prepare for the release
- **OR** to mention very explicitly that you need to work on the "real" perl5 repo and not your own fork.

**Comment by bram-perl** [comment]
A possible other way to fix the describe is to use `git describe --tags` (I assume in `make_patchnum.pl` but I did not test) but then that may not do the right thing when people create their own tags (but I suppose that's already the case: if people create their own annotated tags it will already do the "wrong" thing, but annotated tags are a bit rarer then light-weight tags)

**Comment by bram-perl** [comment]
> A possible other way to fix the describe is to use `git describe --tags` (I assume in `make_patchnum.pl` but I did not test) but then that may not do the right thing when people create their own tags (but I suppose that's already the case: if people create their own annotated tags it will already do the "wrong" thing, but annotated tags are a bit rarer then light-weight tags)

Looking at the history, originally the code was `git describe --tags` but that was changed in commit b6194a9dbf93238df7e489901287cc0265a05f6c but the commit description lacks a reason why that change was made :(

**Comment by jkeenan** [comment]
> So, should we attempt the following:
> 
> ```
> $ git tag -a -f "v5.37.3" 29b290ccaa79f40de7d941c9a79810119f5c6363
> ```
> 
> Experimenting locally suggests that this will do the right thing, though to get the annotated tag into one's local checkout, one would have to say `git fetch -f origin`.

@tonycoz, do you think we should perform the above?

**Comment by haarg** [comment]
I would be strongly in favor of pushing a proper annotated tag.

**Comment by tonycoz** [comment]
> > So, should we attempt the following:
> > ```
> > $ git tag -a -f "v5.37.3" 29b290ccaa79f40de7d941c9a79810119f5c6363
> > ```
> > Experimenting locally suggests that this will do the right thing, though to get the annotated tag into one's local checkout, one would have to say `git fetch -f origin`.
> 
> @tonycoz, do you think we should perform the above?

That looks good to me.

**Comment by jkeenan** [comment]
This is what I did after locally deleting tag `v5.37.3` and creating a new annotated `v5.37.3`.
```
$ git push --tags origin
Enumerating objects: 978, done.
Counting objects: 100% (751/751), done.
Delta compression using up to 4 threads
Compressing objects: 100% (82/82), done.
Writing objects: 100% (300/300), 42.79 KiB | 10.70 MiB/s, done.
Total 300 (delta 262), reused 244 (delta 212), pack-reused 0
remote: Resolving deltas: 100% (262/262), completed with 211 local objects.
To github.com:Perl/perl5.git
 * [new tag]               2021-03-01-after-adapting-Pod-Simple -> 2021-03-01-after-adapting-Pod-Simple
 * [new tag]               2021-03-01-before-adapting-Pod-Simple -> 2021-03-01-before-adapting-Pod-Simple
 * [new tag]               last_before_tempdir -> last_before_tempdir
 * [new tag]               release-7.0.0-version_bump -> release-7.0.0-version_bump
 ! [rejected]              GitLive-blead -> GitLive-blead (already exists)
 ! [rejected]              GitLive-maint-5.004 -> GitLive-maint-5.004 (already exists)
 ! [rejected]              perl-5.004_04 -> perl-5.004_04 (already exists)
 ! [rejected]              perl-5.004_05 -> perl-5.004_05 (already exists)
 ! [rejected]              perl-5.7.3 -> perl-5.7.3 (already exists)
 ! [rejected]              perl-5.9.0 -> perl-5.9.0 (already exists)
 ! [rejected]              perl-5.9.1 -> perl-5.9.1 (already exists)
 ! [rejected]              perl-5.9.2 -> perl-5.9.2 (already exists)
 ! [rejected]              perl-5.9.3 -> perl-5.9.3 (already exists)
 ! [rejected]              perl-5.9.4 -> perl-5.9.4 (already exists)
 ! [rejected]              perl-5.9.5 -> perl-5.9.5 (already exists)
 ! [rejected]              the_answer -> the_answer (already exists)
 ! [rejected]              timinator -> timinator (already exists)
 ! [rejected]              timinatorII -> timinatorII (already exists)
 ! [rejected]              v5.37.3 -> v5.37.3 (already exists)
error: failed to push some refs to 'github.com:Perl/perl5.git'
hint: Updates were rejected because the tag already exists in the remote.
[perlmonger: perl] $ git push --tags --force origin
Enumerating objects: 18, done.
Counting objects: 100% (18/18), done.
Delta compression using up to 4 threads
Compressing objects: 100% (12/12), done.
Writing objects: 100% (12/12), 3.08 KiB | 3.08 MiB/s, done.
Total 12 (delta 3), reused 8 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To github.com:Perl/perl5.git
 + e909f3c7a5...da71581858 GitLive-blead -> GitLive-blead (forced update)
 + 30ce07ff13...c4fb131274 GitLive-maint-5.004 -> GitLive-maint-5.004 (forced update)
 + f53b48affb...c19300c932 perl-5.004_04 -> perl-5.004_04 (forced update)
 + f8a10d9616...8ef8d02409 perl-5.004_05 -> perl-5.004_05 (forced update)
 + 923ccbbd00...38bb8ccec9 perl-5.7.3 -> perl-5.7.3 (forced update)
 + 61bbcc3435...ea4fd6daa1 perl-5.9.0 -> perl-5.9.0 (forced update)
 + 4972f02ac2...b7a7577868 perl-5.9.1 -> perl-5.9.1 (forced update)
 + 453b2e57f9...31e0fb333b perl-5.9.2 -> perl-5.9.2 (forced update)
 + a0baf47460...a64f392e66 perl-5.9.3 -> perl-5.9.3 (forced update)
 + 9ee784662c...27e0a6173c perl-5.9.4 -> perl-5.9.4 (forced update)
 + da4d81489e...f0f8ac0057 perl-5.9.5 -> perl-5.9.5 (forced update)
 + 7fd3c5a37b...3ed00352e1 the_answer -> the_answer (forced update)
 + 578735cb63...6067526e71 timinator -> timinator (forced update)
 + 18df019f21...fed5e1a028 timinatorII -> timinatorII (forced update)
 + 29b290ccaa...9d3e6770b4 v5.37.3 -> v5.37.3 (forced update)

$ git push --tags --force origin
Enumerating objects: 18, done.
Counting objects: 100% (18/18), done.
Delta compression using up to 4 threads
Compressing objects: 100% (12/12), done.
Writing objects: 100% (12/12), 3.08 KiB | 3.08 MiB/s, done.
Total 12 (delta 3), reused 8 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To github.com:Perl/perl5.git
 + e909f3c7a5...da71581858 GitLive-blead -> GitLive-blead (forced update)
 + 30ce07ff13...c4fb131274 GitLive-maint-5.004 -> GitLive-maint-5.004 (forced update)
 + f53b48affb...c19300c932 perl-5.004_04 -> perl-5.004_04 (forced update)
 + f8a10d9616...8ef8d02409 perl-5.004_05 -> perl-5.004_05 (forced update)
 + 923ccbbd00...38bb8ccec9 perl-5.7.3 -> perl-5.7.3 (forced update)
 + 61bbcc3435...ea4fd6daa1 perl-5.9.0 -> perl-5.9.0 (forced update)
 + 4972f02ac2...b7a7577868 perl-5.9.1 -> perl-5.9.1 (forced update)
 + 453b2e57f9...31e0fb333b perl-5.9.2 -> perl-5.9.2 (forced update)
 + a0baf47460...a64f392e66 perl-5.9.3 -> perl-5.9.3 (forced update)
 + 9ee784662c...27e0a6173c perl-5.9.4 -> perl-5.9.4 (forced update)
 + da4d81489e...f0f8ac0057 perl-5.9.5 -> perl-5.9.5 (forced update)
 + 7fd3c5a37b...3ed00352e1 the_answer -> the_answer (forced update)
 + 578735cb63...6067526e71 timinator -> timinator (forced update)
 + 18df019f21...fed5e1a028 timinatorII -> timinatorII (forced update)
 + 29b290ccaa...9d3e6770b4 v5.37.3 -> v5.37.3 (forced update)

$ git fetch -f origin
$ git describe
v5.37.3-246-gf9e2b18ffd
```
While the final `git describe` is what we were aiming for, it is apparent that much more happened with that `git push --tags --force origin` than I was expecting.  I **think** that we can safely delete these two tags:
```
last_before_tempdir
release-7.0.0-version_bump
```
... but I won't take any other action until @tonycoz or others remove what I've already done (and forgiven my sins).

**Comment by jkeenan** [comment]
>  I **think** that we can safely delete these two tags:
> 
> ```
> last_before_tempdir
> release-7.0.0-version_bump
> ```
> 
> ... but I won't take any other action until @tonycoz or others remove what I've already done (and forgiven my sins).

Those two may only exist in my own checkout. Please don't worry too much about them.

**Comment by tonycoz** [comment]
2021-03-01-after-adapting-Pod-Simple and 2021-03-01-before-adapting-Pod-Simple seem to be specific to your repo too, and have also been pushed to Perl/perl5.git

https://devconnected.com/how-to-delete-local-and-remote-tags-on-git/

Stackoverflow also discusses it:

https://stackoverflow.com/questions/5480258/how-do-i-delete-a-remote-tag

discusses how to remove a remote tag.

The RMG talks about how to push the release tag[1]:
```
=head3 publish the release tag

Now that you've shipped the new perl release to PAUSE and pushed your changes
to the Perl master repository, it's time to publish the tag you created
earlier too (e.g.):

 $ git push origin tag v5.11.0
```

Would you like me to deal with it?

[1] I have a tendency to use `--tags` too, I think I've been cured of that now.

**Comment by jkeenan** [comment]
> Would you like me to deal with it?
> 

Yes, please!  It's late here; I just got out of a building shareholders' meeting; my head is spinning and I'm in need of beer!  Thanks!

> [1] I have a tendency to use `--tags` too, I think I've been cured of that now.

**Comment by tonycoz** [comment]
Done:
```
tony@venus:.../git/perl5$ git push --delete origin 2021-03-01-after-adapting-Pod-Simple
To github.com:Perl/perl5.git
 - [deleted]               2021-03-01-after-adapting-Pod-Simple
tony@venus:.../git/perl5$ git push --delete origin 2021-03-01-before-adapting-Pod-Simple
To github.com:Perl/perl5.git
 - [deleted]               2021-03-01-before-adapting-Pod-Simple
tony@venus:.../git/perl5$ git push --delete origin last_before_tempdir
To github.com:Perl/perl5.git
 - [deleted]               last_before_tempdir
tony@venus:.../git/perl5$ git push --delete origin release-7.0.0-version_bump
To github.com:Perl/perl5.git
 - [deleted]               release-7.0.0-version_bump

```

**Comment by haarg** [comment]
> This is what I did after locally deleting tag `v5.37.3` and creating a new annotated `v5.37.3`.
> 
> ```
> ...
> $ git push --tags --force origin
> Enumerating objects: 18, done.
> Counting objects: 100% (18/18), done.
> Delta compression using up to 4 threads
> Compressing objects: 100% (12/12), done.
> Writing objects: 100% (12/12), 3.08 KiB | 3.08 MiB/s, done.
> Total 12 (delta 3), reused 8 (delta 0), pack-reused 0
> remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
> To github.com:Perl/perl5.git
>  + e909f3c7a5...da71581858 GitLive-blead -> GitLive-blead (forced update)
>  + 30ce07ff13...c4fb131274 GitLive-maint-5.004 -> GitLive-maint-5.004 (forced update)
>  + f53b48affb...c19300c932 perl-5.004_04 -> perl-5.004_04 (forced update)
>  + f8a10d9616...8ef8d02409 perl-5.004_05 -> perl-5.004_05 (forced update)
>  + 923ccbbd00...38bb8ccec9 perl-5.7.3 -> perl-5.7.3 (forced update)
>  + 61bbcc3435...ea4fd6daa1 perl-5.9.0 -> perl-5.9.0 (forced update)
>  + 4972f02ac2...b7a7577868 perl-5.9.1 -> perl-5.9.1 (forced update)
>  + 453b2e57f9...31e0fb333b perl-5.9.2 -> perl-5.9.2 (forced update)
>  + a0baf47460...a64f392e66 perl-5.9.3 -> perl-5.9.3 (forced update)
>  + 9ee784662c...27e0a6173c perl-5.9.4 -> perl-5.9.4 (forced update)
>  + da4d81489e...f0f8ac0057 perl-5.9.5 -> perl-5.9.5 (forced update)
>  + 7fd3c5a37b...3ed00352e1 the_answer -> the_answer (forced update)
>  + 578735cb63...6067526e71 timinator -> timinator (forced update)
>  + 18df019f21...fed5e1a028 timinatorII -> timinatorII (forced update)
>  + 29b290ccaa...9d3e6770b4 v5.37.3 -> v5.37.3 (forced update)
> ```
> 
> ... but I won't take any other action until @tonycoz or others remove what I've already done (and forgiven my sins).

Ugh. I'm working on fixing this.

**Comment by haarg** [comment]
I've restored the accidentally pushed tags to their previous state.

**Comment by wchristian** [comment]
@jkeenan to avoid reoccurence you might also want to *locally* delete all the tags in those error messages and do git fetch to grab the authoritative data

**Comment by karenetheridge** [comment]
I would suggest going further and doing `rm -rf ~/git/perl5` (or whatever you have named your repo) and cloning a new one to start fresh. [After pushing any local branches you want to keep to a fork, of course.]

**Comment by Grinnz** [comment]
Another in the list of "ways to avoid doing something like this in the future": if you need to replace a tag or tags, delete them specifically from the remote repo (as @tonycoz described) and then you don't need the dreaded --force.

**Comment by haarg** [comment]
With the same commit checked out as in the original issue report:
```
$ git describe
v5.37.3-31-g015aea7e08
```
The new tag:
```
$ git cat-file tag v5.37.3
object 29b290ccaa79f40de7d941c9a79810119f5c6363
type commit
tag v5.37.3
tagger James E Keenan <jkeenan@cpan.org> 1662596862 +0000

Tag for v5.37.3 (replacement, annotated)
```

So this issue is fixed. I think we'll want to protect all of the release tags to prevent the bad push that happened here. But that is something that should be addressed to p5p.
