### ISSUE TITLE
Printing package names as raw bytes can hide subtle bugs

### ISSUE THREAD

**Issue by leonerd** [Perl/perl5#20146]
My XS code did:

```c
#define mPUSHpvs(s)   mPUSHp("" s "", sizeof(s))
...
      mPUSHpvs("Future::Exception");
      ...
      call_method("new", G_SCALAR);
```

Which resulted in an error message:

```
Can't locate object method "new" via package "Future::Exception" (perhaps you forgot to load "Future::Exception"?) at ...
```

Despite the fact that I am **sure** I definitely loaded the package and the method is available.

The ultimate bug? I forgot to subtract 1 from `sizeof(s)` to account for the trailing nul. So the macro ought to have been:

```c
#define mPUSHpvs(s)   mPUSHp("" s "", sizeof(s)-1)
```

That is certainly a bug in my code. However, Perl's literal printing of the package name hid the bug from me. It throws raw bytes directly at the terminal:

```
$ perl -e '"ab\0cd"->new' 2>&1 | xxd
00000000: 4361 6e27 7420 6c6f 6361 7465 206f 626a  Can't locate obj
00000010: 6563 7420 6d65 7468 6f64 2022 6e65 7722  ect method "new"
00000020: 2076 6961 2070 6163 6b61 6765 2022 6162   via package "ab
00000030: 0063 6422 2028 7065 7268 6170 7320 796f  .cd" (perhaps yo
00000040: 7520 666f 7267 6f74 2074 6f20 6c6f 6164  u forgot to load
00000050: 2022 6162 0063 6422 3f29 2061 7420 2d65   "ab.cd"?) at -e
00000060: 206c 696e 6520 312e 0a                    line 1..
```

Note specifically that it printed a literal zero NUL byte, between "ab" and "cd".

This sort of printing ought to be escaped. If instead it had done, then messages like

```
Can't locate object method "new" via package "Future::Exception\0" (perhaps you forgot to load "Future::Exception\0"?)
```

would yield a vital clue as to what's gone wrong.

**Comment by leonerd** [comment]
@demerphq I recall you recently created a "print this string with escapes and stuff", which might be handy to solve this very problem

**Comment by demerphq** [comment]
On Thu, 25 Aug 2022 at 09:40, demerphq ***@***.***> wrote:
>
> On Wed, 24 Aug 2022 at 16:18, Paul Evans ***@***.***> wrote:
> >
> > @demerphq I recall you recently created a "print this string with escapes and stuff", which might be handy to solve this very problem
>
> I did, and for exactly the same reason as you mention, hidden content
> in error messages.
>
> Let me see where it got to, I /think/ it got merged, but i dont recall
> precisely.

14ad5a85ec0616f35ca0d0b72e3a9a50c5556e6c

It is a prep patch i wrote as part of  yves/fix_universal_import_fragility.

I can queue it up as a standalone PR.

Yves


-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by demerphq** [comment]
Yep, #20153 should resolve this.

**Comment by demerphq** [comment]
@leonerd since you just had this experience maybe you want to do a perldelta for #20153? I realized it needs one. Otherwise i can do it.

**Comment by jkeenan** [comment]
@leonerd, if the patch merged in https://github.com/Perl/perl5/pull/20153 resolves your original problem, is this ticket closable?  Thanks.

**Comment by leonerd** [comment]
Yup, that does it nicely thanks.

**Comment by demerphq** [comment]
On Wed, 24 Aug 2022 at 16:18, Paul Evans ***@***.***> wrote:
>
> @demerphq I recall you recently created a "print this string with escapes and stuff", which might be handy to solve this very problem

I did, and for exactly the same reason as you mention, hidden content
in error messages.

Let me see where it got to, I /think/ it got merged, but i dont recall
precisely.

Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"
