### ISSUE TITLE
make test_porting does not flag need to update t/porting/customized.dat

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#20228]
(This issue stems from an [observation by Tony Cook](https://github.com/Perl/perl5/pull/20216#discussion_r961317924) in his review of https://github.com/Perl/perl5/pull/20216.)

Suppose I build blead as I did today at 741a5c7396a0ca90a22ea8d8e0761c70c14b0a77, and then run `make test_porting`.  All tests will PASS, including, in particular, `t/porting/customized.t`.
```
porting/customized.t ...... ok
```

Now, in the absence of any *deep* study of that test program, I would assume that that means that the data in `t/porting/customized.dat` is up-to-date -- which in turn means that all the `CUSTOMIZED` entries in `Porting/Maintainers.pl` are up-to-date and that I do *not* need to regenerate that database with this command:
```
$ cd t; ./perl -I../lib porting/customized.t --regen; cd -
```
... which appears at the top of `t/porting/customized.dat`.

That assumption turns out to be incorrect.  When I run the command above with the `--regen` switch, I get:
```
ok 1 - regenerated data file
1..1
...
$ git status
On branch blead
Your branch is up to date with 'origin/blead'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   t/porting/customized.dat

no changes added to commit (use "git add" and/or "git commit -a")

$ git diff |cat
diff --git a/t/porting/customized.dat b/t/porting/customized.dat
index dae5af2446..0c2c70e25a 100644
--- a/t/porting/customized.dat
+++ b/t/porting/customized.dat
@@ -4,17 +4,11 @@
 AutoLoader cpan/AutoLoader/t/02AutoSplit.t bb90cda13b88599ad45de4b45799d5218afcb6d8
 ExtUtils::Constant cpan/ExtUtils-Constant/lib/ExtUtils/Constant/Base.pm 7560e1018f806db5689dee78728ccb8374aea741
 ExtUtils::Constant cpan/ExtUtils-Constant/t/Constant.t 165e9c7132b003fd192d32a737b0f51f9ba4999e
-Filter::Util::Call pod/perlfilter.pod 545265af2f45741a0e59eecdd0cfc0c9e490c1e8
 Locale::Maketext::Simple cpan/Locale-Maketext-Simple/lib/Locale/Maketext/Simple.pm 57ed38905791a17c150210cd6f42ead22a7707b6
 Math::Complex cpan/Math-Complex/lib/Math/Complex.pm 66f28a17647e2de166909ca66e4ced26f8a0a62e
 Math::Complex cpan/Math-Complex/t/Complex.t 17039e03ee798539e770ea9a0d19a99364278306
 Math::Complex cpan/Math-Complex/t/Trig.t 508f8e27373c08228be13ca5d42b28812ab0e020
 Math::Complex cpan/Math-Complex/t/underbar.t 97e7b9615658eefc67a710d4b258349cc5bace63
-Memoize cpan/Memoize/Memoize.pm 902092ff91cdec9c7b4bd06202eb179e1ce26ca2
-Memoize cpan/Memoize/t/errors.t bcd0c02a4bc47dfda07a97d265d7210849871659
-Memoize cpan/Memoize/t/expmod_t.t a1c3d03fd3ec2e7c6c835f02316475756e1b16b7
-Memoize cpan/Memoize/t/speed.t 89fe8c8928f0164c9ed898b5a427dbbc814e9976
-Memoize cpan/Memoize/t/tie_gdbm.t d81c4f6208f6c925539b3878bff9a8ff1b73a37e
 Net::Ping dist/Net-Ping/t/000_load.t deff5dc2ca54dae28cb19d3631427db127279ac2
 Net::Ping dist/Net-Ping/t/001_new.t 7b24e05672e22edfe3e6b5cc0277f815efe557e5
 Net::Ping dist/Net-Ping/t/010_pingecho.t 218d7a9ee5b6d03ba2544210acaf6585f8dc5503
```
This suggests that the database was *not* updated when Memoize was last synched with CPAN on August 17 -- and since I was the committer, the omission was mine.
```
commit 9c811e448b4468014d49999f6826d6d3f0ad2b21
Author:     Aristotle Pagaltzis <pagaltzis@gmx.de>
AuthorDate: Sun Aug 14 19:35:41 2022
Commit:     James E Keenan <jkeenan@cpan.org>
CommitDate: Wed Aug 17 12:20:19 2022

    Memoize: sync with CPAN version 1.10
```
This further suggests that there's something amiss in `make test_porting`.  I am certain that I would have run that before making the commit above on Aug 17 -- but it PASSed and did not indicate that there was anything amiss.  So I was not nudged to regenerate that database.

In addition, this suggests that there's something peculiar about `pod/perlfilter.pod` that (i) warranted a `CUSTOMIZED` entry in `Porting/Maintainers.pl` and, accordingly, an entry in `t/porting/customized.dat`; and that (ii) under some circumstances, a regeneration of `customized.dat` would cause the database entry to be removed.
```
-Filter::Util::Call pod/perlfilter.pod 545265af2f45741a0e59eecdd0cfc0c9e490c1e8
```
There is indeed something ... unique about `pod/perlfilter.pod`.  It is really [maintained upstream on CPAN](https://metacpan.org/release/RURBAN/Filter-1.64/source/perlfilter.pod) as part of the `Filter` distribution.  However, it's been located under `pod/` in the core distribution at least since 2009:
```
commit 2b4f847434de297901e2c76921bae9eecb9a8929
Author:     David Mitchell <davem@iabyn.com>
AuthorDate: Wed Jun 3 01:42:20 2009 +0100
Commit:     David Mitchell <davem@iabyn.com>
CommitDate: Wed Jun 3 01:43:38 2009 +0100

    add more EXCLUDED and MAP keys to Maintainers.pl
```
`pod/perlfilter.pod` was, however, modified in the core distribution recently as part of:
```
commit d84bd0bd478e7c7ff7f57eeb94fda30ee0e34296
Author:     Paul Evans <leonerd@leonerd.org.uk>
AuthorDate: Wed Apr 6 12:47:26 2022 +0100
Commit:     Paul Evans <leonerd@leonerd.org.uk>
CommitDate: Sat Apr 23 20:09:59 2022 +0100

    Replace 'use strict; use warnings;' with 'use VERSION' in docs code examples
```
When I build perl at the commit *before* the above and run `make test_porting`, everything PASSes.  If I then regenerate the customize database, I get:
```
$ cd t; ./perl -I../lib porting/customized.t --regen; cd -
ok 1 - regenerated data file
1..1
```
The timestamp indicates that `t/porting/customized.dat` was indeed updated, but there is no difference in its contents.
```
$ git diff
$ 
```
So my inference is that the manual edit to `pod/perlfilter.pod` triggers the removal of that file's entry in `t/porting/customized.dat` -- even though the file is still listed as `CUSTOMIZED` in `Porting/Maintainers.pl`.

Hence, at this particular moment, `make test_porting` is PASSing but is failing to reflect the need to regenerate `t/porting/customized.data`.  This is an obstacle to the merge request in https://github.com/Perl/perl5/pull/20216 but is not relevant to the real subject matter of that p.r.  This will also be a consideration for [the way we maintain Math-Complex](https://github.com/Perl/perl5/pull/20215) (though [I have questions](https://github.com/Perl/perl5/pull/20215#issuecomment-1235883618) about the current form of that pull request).

I have not yet studied `t/porting/customized.t` to diagnose the problem further.

**Comment by demerphq** [comment]
On Fri, 2 Sept 2022 at 23:43, James E Keenan ***@***.***>
wrote:

> (This issue stems from an observation by Tony Cook
> <https://github.com/Perl/perl5/pull/20216#discussion_r961317924> in his
> review of #20216 <https://github.com/Perl/perl5/pull/20216>.)
>
> Suppose I build blead as I did today at 741a5c7
> <https://github.com/Perl/perl5/commit/741a5c7396a0ca90a22ea8d8e0761c70c14b0a77>,
> and then run make test_porting. All tests will PASS, including, in
> particular, t/porting/customized.t.
>
> porting/customized.t ...... ok
>
> Now, in the absence of any *deep* study of that test program, I would
> assume that that means that the data in t/porting/customized.dat is
> up-to-date -- which in turn means that all the CUSTOMIZED entries in
> Porting/Maintainers.pl are up-to-date and that I do *not* need to
> regenerate that database with this command:
>
> $ cd t; ./perl -I../lib porting/customized.t --regen; cd -
>
> ... which appears at the top of t/porting/customized.dat.
>

It seems to me it would be best if anything that is supposed to regen stuff
should be autorun by 'make regen' (as a default assumption and aside from
good reasons to do the contrary), and then this kind of thing would be
noticed much more quickly.

I have not yet studied t/porting/customized.t to diagnose the problem
> further.
>
You have piqued my interest so i will take a look, no promises tho.

Yves

-- 
perl -Mre=debug -e "/just|another|perl|hacker/"

**Comment by jkeenan** [comment]
https://github.com/Perl/perl5/pull/20237 is, I would argue, a least kludgy way of addressing this issue.

**Comment by jkeenan** [comment]
With commit dcf2c66b4ba2e50408461d7ac13a4782ba26bf1b, the immediate problem is resolved, so I'm closing this ticket.  I recommend that any further general discussion of `regen` procedures take place on the mailing list.
