### ISSUE TITLE
Git: make version tags protected

### ISSUE THREAD

**Issue by bram-perl** [Perl/perl5#20284]
The version tags are currently not protected which means someone can force push them (either by accident or intentional).

This is a request to protect them.

Ideally all of them would be protected but that may not be possible: ; reading the GitHub docs protecting 'v5*' may/will prevent the release manager from pushing the tag for a new version (assuming I read the docs right).

At a minimum the following tags should be protected:
- GitLive-blead
- GitLive-maint-5.004
- perl-5.004_04
- perl-5.004_05
- perl-5.7.3
- perl-5.9.0
- perl-5.9.1
- perl-5.9.2
- perl-5.9.3
- perl-5.9.4
- perl-5.9.5
- the_answer
- timinator
- timinatorII

Some (/all?) of these tags got fixed before - presumably because of #17321 - but the old references to these tags is still out there in some clones (as can be seen in https://github.com/Perl/perl5/issues/20130#issuecomment-1240062806 ) which means someone doing a `git push --tags --force` may - accidentally - overwrite the fixes..

**Assuming** `v5` can not be protected I think this list of patterns should do it:
```
GitLive-*
code-review/2009-07-22
if-*
perl-*
the_answer
timinator
timinatorII
v5.10.*
v5.11.*
v5.12.*
v5.13.*
v5.14.*
v5.15.*
v5.16.*
v5.17.*
v5.18.*
v5.19.*
v5.20.*
v5.21.*
v5.22.*
v5.23.*
v5.24.*
v5.25.*
v5.26.*
v5.27.*
v5.28.*
v5.29.*
v5.30.*
v5.31.*
v5.32.*
v5.33.*
v5.34.*
v5.35.*
v5.36.0*
```

That should protect all old tags and leave 5.36.1+ and 5.37.* unprotected

@toddr can you add the necessary rules in the repo settings?

**Comment by toddr** [comment]
I'm happy to set it up but I'd like an ok from someone on the PSC. @rjbs @leonerd @book

**Comment by haarg** [comment]
Restricted tags can be pushed by anyone with "maintain" permissions, but can only be deleted or overwritten with "admin" permissions.

This page show what is granted by the various permissions: https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization

If everyone doing a release was given "maintain" permissions, they would be able to push new release tags, but would also gain various other permissions.

We may be able to remove some of the old tags. I'm not sure if any of:
```
GitLive-*
code-review/2009-07-22
if-*
the_answer
timinator
timinatorII
```
are providing any value. We may also want to create `v5.8.5` style tags for all of the old releases.

**Comment by leonerd** [comment]
I know and understand almost nothing surrounding this issue, but any mechanism that makes accidentally screwing up historical version tags, without getting in anyone else's way doing useful things, sounds like a good idea to me.

So not really a +1 but more a "eh, I don't see anything to object to currently"

**Comment by toddr** [comment]
```
GitLive-*
perl-5*
v*
```

The above tags are now protected. This may break whoever is doing this month's release. If so I'm available to debug and correct permissions as-needed.
