### ISSUE TITLE
malloc.c gives compiler warnings under multiplicity

### ISSUE THREAD

**Issue by Jamaika1** [Perl/perl5#20286]
I use gcc 11.3.0. with function -DPERL_CORE -DPERL_IS_MINIPERL -DUSE_ITHREADS
https://github.com/Perl/perl5/commit/932a38d1a532eec8faccdcb6e4ce4d023fbf70be
Are these messages correct?
```
locale.c: In function 'S_my_langinfo_i':
locale.c:4144:14: warning: '___lc_codepage_func' redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
 4144 |         UINT ___lc_codepage_func(void);
      |              ^~~~~~~~~~~~~~~~~~~
malloc.c:242: warning: "croak" redefined
  242 | #    define croak       Perl_croak_nocontext
      |
In file included from perl.h:6217,
                 from malloc.c:240:
embed.h:114: note: this is the location of the previous definition
  114 | #define croak(...)              Perl_croak(aTHX_ __VA_ARGS__)
      |
malloc.c:244: warning: "warn" redefined
  244 | #    define warn        Perl_warn_nocontext
      |
In file included from perl.h:6217,
                 from malloc.c:240:
embed.h:743: note: this is the location of the previous definition
  743 | #define warn(...)               Perl_warn(aTHX_ __VA_ARGS__)
      |
```
https://github.com/Perl/perl5/pull/20289

**Comment by tonycoz** [comment]
It's unclear where you're supplying those defines, but they should only be defined by the build process.

**Comment by Jamaika1** [comment]
I supply definitions for all .c files.
for %%f in ("%~dp1*.c") do gcc.exe -std=gnu2x -ftree-vectorize -g0 -O3 -fPIC -DWIN32 -DWINVER=0x0602 -D_WIN32_WINNT=0x0602 -DWIN32_LEAN_AND_MEAN=/"/" -DNWIN32IO_IS_STDIO=/"/" -DPERL_CORE -DPERL_IS_MINIPERL -DUSE_ITHREADS -DDEBUGGING -c %%f -o %%~nf.o

**Comment by tonycoz** [comment]
Use the makefile:
```
cd win32
gmake CCHOME=c:\where\gcc\base\directory\is
```

See the top of `win32/GNUmakefile` for a summary, or read through `README.win32` for details on building perl on windows.

**Comment by Jamaika1** [comment]
I leave this problem to others
https://github.com/Perl/perl5/commit/13e5ba49b2cfe0add44db552ecbebb2f785aecbc
```
#ifndef PERL_CORE
/* Do not use these macros. They were part of PERL_OBJECT, which was an
 * implementation of multiplicity using C++ objects. They have been left
 * here solely for the sake of XS code which has incorrectly
 * cargo-culted them.
```

**Comment by Leont** [comment]
Yeah, those defines in malloc.c are no longer correct and should be updated.

**Comment by jkeenan** [comment]
> Yeah, those defines in malloc.c are no longer correct and should be updated.

@Leont, is this ticket closable?  As it stands, it does not appear that the OP has provided us enough information to proceed, but your remark suggests a different ticket should be opened.  Thanks.

**Comment by Leont** [comment]
The problem can easily be reproduced by building a perl with `-Dusemymalloc -Dusethreads`.

**Comment by jkeenan** [comment]
> The problem can easily be reproduced by building a perl with `-Dusemymalloc -Dusethreads`.

Thanks.  What would be a better Subject for this issue (than "Question")?
