### ISSUE TITLE
Dereferencing a function before it is declared works but not afterwards.

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#20298]
If I dereference a function before declaring the function, the function gets called successfully. After the function has been declared the same call does not work.  I find this surprising and difficult to explain to new Perl users.

![image](https://user-images.githubusercontent.com/7548378/189919862-a82eeb91-1e4d-46ef-badf-df29270e3bad.png)

Here is the actual code:
```
#!/usr/bin/perl
use v5.30;
use Test::More qw(no_plan);

ok a->() == 1; # OK

sub a {1};

ok a == 1;
ok a->() == 1; # Fails
```

**Comment by Grinnz** [comment]
You have not dereferenced the function. You have attempted to dereference the value the function returns, which is not a code reference. A function is called with the syntax `a()`, a bareword symbol is not a reference.
