### ISSUE TITLE
eb54d46f726 triggers new build-time warning

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#20302]
A recent commit has introduced a new build-time warning.

Using my customary configuration switches and `clang10` as the compiler on FreeBSD-12, I built `perl` at 658a5bedcf.  I got the following build-time warning:
```
$ parse-build-warnings 658a5bedcf.freebsd.threaded.maketp.output.txt.gz
File:  658a5bedcf.freebsd.threaded.maketp.output.txt.gz

[
  {
    char   => 14,
    group  => "Wunused-variable",
    line   => 12662,
    source => "toke.c",
    text   => "unused variable 'syntax_error'",
  },
]
```
The line cited in `toke.c` was added in recent commit eb54d46f726:
```
commit eb54d46f7264ff7af62c409d8a6ab984a5a34f57 (HEAD)
Author:     Yves Orton <demerphq@gmail.com>
AuthorDate: Fri Aug 26 18:26:14 2022 +0200
Commit:     Yves Orton <demerphq@gmail.com>
CommitDate: Fri Sep 9 18:48:52 2022 +0200

    Stop parsing on first syntax error.
```
Configuring and building at that commit and the one immediately preceding that commit confirmed that it was the commit which first generated the warning.

@demerphq, can you take a look?

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> A recent commit has introduced a new build-time warning.
> 
> Using my customary configuration switches and `clang10` as the compiler on FreeBSD-12, I built `perl` at [658a5be](https://github.com/Perl/perl5/commit/658a5bedcfb012a503b61de6c8cb69924cc6f6f8). I got the following build-time warning:
> 
> ```
> $ parse-build-warnings 658a5bedcf.freebsd.threaded.maketp.output.txt.gz
> File:  658a5bedcf.freebsd.threaded.maketp.output.txt.gz
> 
> [
>   {
>     char   => 14,
>     group  => "Wunused-variable",
>     line   => 12662,
>     source => "toke.c",
>     text   => "unused variable 'syntax_error'",
>   },
> ]
> ```
> 
> The line cited in `toke.c` was added in recent commit [eb54d46](https://github.com/Perl/perl5/commit/eb54d46f7264ff7af62c409d8a6ab984a5a34f57):
> 
> ```
> commit eb54d46f7264ff7af62c409d8a6ab984a5a34f57 (HEAD)
> Author:     Yves Orton <demerphq@gmail.com>
> AuthorDate: Fri Aug 26 18:26:14 2022 +0200
> Commit:     Yves Orton <demerphq@gmail.com>
> CommitDate: Fri Sep 9 18:48:52 2022 +0200
> 
>     Stop parsing on first syntax error.
> ```
> 
> Configuring and building at that commit and the one immediately preceding that commit confirmed that it was the commit which first generated the warning.
> 
> @demerphq, can you take a look?
> 
> Thank you very much. Jim Keenan

This warning is still present in 534b66374b.  Yves, @demerphq, could you take a look at it so that we can clear it up before tomorrow's release?

**Comment by demerphq** [comment]
On Mon, 19 Sept 2022, 13:13 James E Keenan, ***@***.***>
wrote:

> A recent commit has introduced a new build-time warning.
>
> Using my customary configuration switches and clang10 as the compiler on
> FreeBSD-12, I built perl at 658a5be
> <https://github.com/Perl/perl5/commit/658a5bedcfb012a503b61de6c8cb69924cc6f6f8>.
> I got the following build-time warning:
>
> $ parse-build-warnings 658a5bedcf.freebsd.threaded.maketp.output.txt.gz
> File:  658a5bedcf.freebsd.threaded.maketp.output.txt.gz
>
> [
>   {
>     char   => 14,
>     group  => "Wunused-variable",
>     line   => 12662,
>     source => "toke.c",
>     text   => "unused variable 'syntax_error'",
>   },
> ]
>
> The line cited in toke.c was added in recent commit eb54d46
> <https://github.com/Perl/perl5/commit/eb54d46f7264ff7af62c409d8a6ab984a5a34f57>
> :
>
> commit eb54d46f7264ff7af62c409d8a6ab984a5a34f57 (HEAD)
> Author:     Yves Orton ***@***.***>
> AuthorDate: Fri Aug 26 18:26:14 2022 +0200
> Commit:     Yves Orton ***@***.***>
> CommitDate: Fri Sep 9 18:48:52 2022 +0200
>
>     Stop parsing on first syntax error.
>
> Configuring and building at that commit and the one immediately preceding
> that commit confirmed that it was the commit which first generated the
> warning.
>
> @demerphq <https://github.com/demerphq>, can you take a look?
>
> Thank you very much. Jim Keenan
>
> This warning is still present in 534b663
> <https://github.com/Perl/perl5/commit/534b66374b96a50023b85157019b49970f0bd3e6>.
> Yves, @demerphq <https://github.com/demerphq>, could you take a look at
> it so that we can clear it up before tomorrow's release?
>

Sorry, no can do. I don't have compiler access until Thursday.

It's used in debugging, if someone wants to PERL_DEB it then go ahead. Or
just uncomment the commented out else if. It's not a bug, I don't think it
should be a showstopper for a dev release.

Yves

>
