### ISSUE TITLE
Behavior of combined assignment operators on a list

### ISSUE THREAD

**Issue by vinc17fr** [Perl/perl5#20342]
**Description**
On a list, I would expect combined assignment operators to be applied to each lvalue instead of just the last one.

**Steps to Reproduce**
```
% perl -e '($x,$y) = (5,8); ($x,$y) += 17; print "($x,$y)\n"'
(5,25)
```

**Expected behavior**
I would expect the "+ 17" to be applied to both $x and $y instead of just $y, i.e. I would expect (22,25) as in `($x,$y) = map { $_ + 17 } ($x,$y)`.

The [perlop](https://perldoc.perl.org/perlop) man page says "These combined assignment operators can only operate on scalars", but if this were the case, I would expect an error.

**Perl configuration**

```
Summary of my perl5 (revision 5 version 36 subversion 0) configuration:

  Platform:
    osname=android
    osvers=current
    archname=aarch64-android
    uname=''
    config_args='--target=aarch64-linux-android --with-cc=aarch64-linux-android-clang --with-ranlib=llvm-ranlib -Dosname=android -Dsysroot=-I/data/data/com.termux/files -Dprefix=/data/data/com.termux/files/usr -Dsh=/data/data/com.termux/files/usr/bin/sh -Dld=aarch64-linux-android-clang -Wl,-rpath=/data/data/com.termux/files/usr/lib -Wl,--enable-new-dtags -Dar=llvm-ar -Duseshrplib -Duseithreads -Dusemultiplicity --keeplog --mode=target --target=aarch64-linux-android --targetarch=aarch64-unknown-linux-android'
    hint=default
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=undef
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='aarch64-linux-android-clang'
    ccflags ='-I/data/data/com.termux/files/usr/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize=''
    cppflags='-I/data/data/com.termux/files/usr/include'
    ccversion=''
    gccversion='0.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=0
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='aarch64-linux-android-clang -Wl,-rpath=/data/data/com.termux/files/usr/lib -Wl,--enable-new-dtags'
    ldflags ='-I/data/data/com.termux/files/usr/include'
    libpth=/data/data/com.termux/files/usr/lib /data/data/com.termux/files/usr/local/lib
    libs=-lm -ldl
    perllibs=-lm -ldl
    libc=
    so=so
    useshrplib=true
    libperl=libperl.so
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC -Wno-unused-function'
    lddlflags='-I/data/data/com.termux/files/usr/include -shared -I/data/data/com.termux/files/usr/include'

Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
    USE_THREAD_SAFE_LOCALE
  Built under android
  Compiled at Aug 15 2022 20:03:14
  @INC:
    /data/data/com.termux/files/usr/lib/perl5/site_perl/5.36.0/aarch64-android
    /data/data/com.termux/files/usr/lib/perl5/site_perl/5.36.0
    /data/data/com.termux/files/usr/lib/perl5/5.36.0/aarch64-android
    /data/data/com.termux/files/usr/lib/perl5/5.36.0
```

Note: same issue with Debian's perl 5.34.

**Comment by jkeenan** [comment]
> **Description** On a list, I would expect combined assignment operators to be applied to each lvalue instead of just the last one.
> 
> **Steps to Reproduce**
> 
> ```
> % perl -e '($x,$y) = (5,8); ($x,$y) += 17; print "($x,$y)\n"'
> (5,25)
> ```
> 

My instinctive reaction to that code is: "In 20+ years of writing Perl I've never thought to try that.  What is he thinking of?"

> **Expected behavior** I would expect the "+ 17" to be applied to both $x and $y instead of just $y, i.e. I would expect (22,25) as in `($x,$y) = map { $_ + 17 } ($x,$y)`.
> 

Well, to me (at least) that expectation is ruled out by (i) the documentation you quote below and (ii) the fact that Perl has behaved this way since at least perl-5.6.2 (oldest I have) and probably forever.

> The [perlop](https://perldoc.perl.org/perlop) man page says "These combined assignment operators can only operate on scalars", but if this were the case, I would expect an error.
> 

A warning, perhaps, prompting the user to re-consider what he/she is attempting.  But this is such an edge case that the likelihood of introducing bugs when introducing such a warning to the source code is greater than the benefit to users of the warning.

**Comment by jkeenan** [comment]
> > **Description** On a list, I would expect combined assignment operators to be applied to each lvalue instead of just the last one.
> > **Steps to Reproduce**
> > ```
> > % perl -e '($x,$y) = (5,8); ($x,$y) += 17; print "($x,$y)\n"'
> > (5,25)
> > ```
> 
> My instinctive reaction to that code is: "In 20+ years of writing Perl I've never thought to try that. What is he thinking of?"
> 
> > **Expected behavior** I would expect the "+ 17" to be applied to both $x and $y instead of just $y, i.e. I would expect (22,25) as in `($x,$y) = map { $_ + 17 } ($x,$y)`.
> 
> Well, to me (at least) that expectation is ruled out by (i) the documentation you quote below and (ii) the fact that Perl has behaved this way since at least perl-5.6.2 (oldest I have) and probably forever.
> 
> > The [perlop](https://perldoc.perl.org/perlop) man page says "These combined assignment operators can only operate on scalars", but if this were the case, I would expect an error.
> 
> A warning, perhaps, prompting the user to re-consider what he/she is attempting. But this is such an edge case that the likelihood of introducing bugs when introducing such a warning to the source code is greater than the benefit to users of the warning.

We could, of course, clarify the documentation in `pod/perlop.pod` to show that using a combined assignment operator to assign to a list does not produce easily understandable results.

**Comment by vinc17fr** [comment]
> > **Expected behavior** I would expect the "+ 17" to be applied to both $x and $y instead of just $y, i.e. I would expect (22,25) as in `($x,$y) = map { $_ + 17 } ($x,$y)`.
> 
> Well, to me (at least) that expectation is ruled out by (i) the documentation you quote below

Yes, with the current version of Perl, but the documentation implies that the code is erroneous and should have produced an error instead of an unintuitive and useless result (useless because someone who just wants to add 17 to $y would write `$y += 17`). Then Perl can evolve to provide more features.

> and (ii) the fact that Perl has behaved this way since at least perl-5.6.2 (oldest I have) and probably forever.

Code that expects the current behavior (if ever such code exists) could be regarded as buggy as the documentation currently says that this works only on scalars. BTW,
```
zira% perl -e '($x,$y) = (5,8); ($x,$y) += (10,17); print "($x,$y)\n"'
(5,25)
```
is even more confusing.

**Comment by Leont** [comment]
> The [perlop](https://perldoc.perl.org/perlop) man page says "These combined assignment operators can only operate on scalars", but if this were the case, I would expect an error.

`($x,$y)` in scalar context is perfectly well-defined to return `$y` (it's actually the comma operator that does that, the parentheses are just for precedence). Is it a silly thing to do? Yes. But Perl is not the sort of language that prevents you from trying to do silly things; perlcritic is your friend if you hate silliness.

**Comment by vinc17fr** [comment]
OK, it returns the last element in a scalar context (but my point was to regard this in a list context, just like assignments), and the result is still inconsistent with
```
% perl -e '($x,$y) = (5,8); ($x,$y) = ($x,$y) + 17; print "($x,$y)\n"'
(25,)
```

At least, the similar `++` operator returns an error:
```
% perl -e '($x,$y) = (5,8); ++($x,$y); print "($x,$y)\n"'
Too many arguments for preincrement (++) at -e line 1, near ");"
Execution of -e aborted due to compilation errors.
```

**Comment by Leont** [comment]
> OK, it returns the last element in a scalar context (but my point was to regard this in a list context, just like assignments), and the result is still inconsistent with

It works exactly as designed; one `($x,$y)` is in list context and the other is in scalar context. Like it or not, there's no bug here, nor is there a behavior that we can realistically change it this point in perl's evolution.

**Comment by vinc17fr** [comment]
Sorry, but you're wrong. `($x,$y) = 25` returns `(25,)`, not `(5,25)`. So `(5,25)` is definitely incorrect as the result of `($x,$y) += (10,17)`.

**Comment by Leont** [comment]
> So (5,25) is definitely incorrect as the result of ($x,$y) += (10,17).

The result of `($x,$y) += (10,17)` is not `(5,25)`, it's `25`. You may find it surprising or confusing, but it's not incorrect.

This tracker is not a perl help channel, if you need explanation of how the language works there are other more suitable venues.

**Comment by vinc17fr** [comment]
> > So (5,25) is definitely incorrect as the result of ($x,$y) += (10,17).
> 
> The result of `($x,$y) += (10,17)` is not `(5,25)`, it's `25`. You may find it surprising or confusing, but it's not incorrect.

I meant what is assigned to $x and $y. Here's what I get:
```
% perl -e '($x,$y) = (5,8); ($x,$y) += (10,17); print "($x,$y)\n"'
(5,25)
```
as opposed to
```
% perl -e '($x,$y) = (5,8); ($x,$y) = 25; print "($x,$y)\n"'
(25,)
```
since `($x,$y) + (10,17)` gives the result 25.

**Comment by Leont** [comment]
`+`, and by extension `+=` enforces scalar context. `($x,$y) += (10,17)` is just a really silly way of writing `$y += 17`. All augmented assignment operators in Perl do this, as they're all based on scalar operators.

`=` is the normal assignment operator, and as such can work in both scalar and list context, unlike any of the scalar assignment operators. The left hand is forcing the operator to be listy, hence the observed behavior.
