### ISSUE TITLE
1102a6f006 breaks IO-Socket-SSL tests, prevents CPANtester reports from blead

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#20468]
Today I attempted to install Task::CPAN::Reporter against blead.  The installation failed due to failures in two test programs in the IO-Socket-SSL test suite.
```
$ uname -mrs
Linux 5.10.0-18-amd64 x86_64

$ bleadperl -v | head -2 | tail -1
This is perl 5, version 37, subversion 6 (v5.37.6 (v5.37.5-90-g6848aea2c8)) built for x86_64-linux

$ bleadperl -V:config_args
config_args='-des -Dusedevel -Uversiononly -Dprefix=/home/jkeenan/testing/blead -Dman1dir=none -Dman3dir=none';

$ cd ~/testing/blead
$ ./bin/cpan IO::Socket::SSL

# [failures in two tests]

$ bleadperl -Iblib/lib t/public_suffix_lib_encode_idn.t
Segmentation fault
$ bleadperl -Iblib/lib t/public_suffix_lib_libidn.t
Segmentation fault
```
Bisecting with this invocation:
```
perl Porting/bisect.pl --start=v5.37.5 --module=IO::Socket::SSL
```
... pointed to recent commit 1102a6f006f2bb626d2c7f1c5b7d360c28518129
```
1102a6f006f2bb626d2c7f1c5b7d360c28518129 is the first bad commit
commit 1102a6f006f2bb626d2c7f1c5b7d360c28518129
Author: chromatic <chromatic@wgz.org>
Date:   Thu Oct 27 11:24:58 2022 +0200
Commit:     Yves Orton <demerphq@gmail.com>
CommitDate: Tue Nov 1 09:46:16 2022 +0100


    Enable `use feature 'module_true'`
```
@chromatic, @demerphq, can you take a look?

**Comment by demerphq** [comment]
Ill pick this up, i shepherded it into core.

**Comment by jkeenan** [comment]
On a threaded build on FreeBSD-12 just now I got failures in **3** test programs, not just the 2 in Linux:

```
$ uname -mrs
FreeBSD 12.3-RELEASE-p1 amd64

$ ./bin/perl -v | head -2 | tail -1
This is perl 5, version 37, subversion 6 (v5.37.6 (v5.37.5-93-g5f112c0ac6)) built for amd64-freebsd-thread-multi

$ ./bin/perl -Ilib -V:config_args
config_args='-des -Dusedevel -Uversiononly -Dprefix=/home/jkeenan/testing/blead -Dman1dir=none -Dman3dir=none -Duseithreads -Doptimize=-O2 -pipe -fstack-protector -fno-strict-aliasing';

...

t/public_suffix_lib_encode_idn.t (Wstat: 139 (Signal: SEGV, dumped core) Tests: 0 Failed: 0)
  Non-zero wait status: 139
  Parse errors: No plan found in TAP output
t/public_suffix_lib_libidn.t    (Wstat: 139 (Signal: SEGV, dumped core) Tests: 0 Failed: 0)
  Non-zero wait status: 139
  Parse errors: No plan found in TAP output
t/public_suffix_lib_uri.t       (Wstat: 139 (Signal: SEGV, dumped core) Tests: 0 Failed: 0)
  Non-zero wait status: 139
  Parse errors: No plan found in TAP output
```

**Comment by jkeenan** [comment]
I stumbled upon this problem while attempting to diagnose some problems with Module-Pluggable.  In the same build of perl on FreeBSD as above, I am now getting a segfault in one test program.
```
[perlmonger: Module-Pluggable-5.2-0] $ bleadperl -v | head -2 | tail -1
This is perl 5, version 37, subversion 6 (v5.37.6 (v5.37.5-93-g5f112c0ac6)) built for amd64-freebsd-thread-multi

[perlmonger: Module-Pluggable-5.2-0] $ bleadperl -Ilib -V:config_args
config_args='-des -Dusedevel -Uversiononly -Dprefix=/home/jkeenan/testing/blead -Dman1dir=none -Dman3dir=none -Duseithreads -Doptimize=-O2 -pipe -fstack-protector -fno-strict-aliasing';

[perlmonger: Module-Pluggable-5.2-0] $ bleadprove -vb t/22trigger.t 
t/22trigger.t .. 
1..7
ok 1 - Created new TriggerTest
Failed 6/7 subtests 

Test Summary Report
-------------------
t/22trigger.t (Wstat: 139 (Signal: SEGV, dumped core) Tests: 1 Failed: 0)
  Non-zero wait status: 139
  Parse errors: Bad plan.  You planned 7 tests but ran 1.
Files=1, Tests=1,  0 wallclock secs ( 0.03 usr  0.00 sys +  0.09 cusr  0.03 csys =  0.15 CPU)
Result: FAIL
```
I cannot yet specifically attribute this segfault to 1102a6f006 because both Task-CPAN-Reporter and `Porting/bisect.pl --module=Module::Pluggable` depend upon IO-Socket-SSL.

**Comment by haarg** [comment]
Reduced test case:
```
touch Guff.pm
perl -e'require "./Guff.pm";'
```
It will segfault on requiring any file that is empty, or an `@INC` hook producing an empty output.

**Comment by jkeenan** [comment]
> On a threaded build on FreeBSD-12 just now I got failures in **3** test programs, not just the 2 in Linux:
> 
> ```
> $ uname -mrs
> FreeBSD 12.3-RELEASE-p1 amd64
> 
> $ ./bin/perl -v | head -2 | tail -1
> This is perl 5, version 37, subversion 6 (v5.37.6 (v5.37.5-93-g5f112c0ac6)) built for amd64-freebsd-thread-multi
> 
> $ ./bin/perl -Ilib -V:config_args
> config_args='-des -Dusedevel -Uversiononly -Dprefix=/home/jkeenan/testing/blead -Dman1dir=none -Dman3dir=none -Duseithreads -Doptimize=-O2 -pipe -fstack-protector -fno-strict-aliasing';
> 
> ...
> 
> t/public_suffix_lib_encode_idn.t (Wstat: 139 (Signal: SEGV, dumped core) Tests: 0 Failed: 0)
>   Non-zero wait status: 139
>   Parse errors: No plan found in TAP output
> t/public_suffix_lib_libidn.t    (Wstat: 139 (Signal: SEGV, dumped core) Tests: 0 Failed: 0)
>   Non-zero wait status: 139
>   Parse errors: No plan found in TAP output
> t/public_suffix_lib_uri.t       (Wstat: 139 (Signal: SEGV, dumped core) Tests: 0 Failed: 0)
>   Non-zero wait status: 139
>   Parse errors: No plan found in TAP output
> ```
Bringing my unthreaded build on Linux up to HEAD, I now get 3 test failures in IO-Socket-SSL here as well.
```
$ bleadperl -v | head -2 | tail -1
This is perl 5, version 37, subversion 6 (v5.37.6 (v5.37.5-93-g5f112c0ac6)) built for x86_64-linux
...
Test Summary Report
-------------------
t/public_suffix_lib_encode_idn.t (Wstat: 11 (Signal: SEGV) Tests: 0 Failed: 0)
  Non-zero wait status: 11
  Parse errors: No plan found in TAP output
t/public_suffix_lib_libidn.t    (Wstat: 11 (Signal: SEGV) Tests: 0 Failed: 0)
  Non-zero wait status: 11
  Parse errors: No plan found in TAP output
t/public_suffix_lib_uri.t       (Wstat: 11 (Signal: SEGV) Tests: 0 Failed: 0)
  Non-zero wait status: 11
  Parse errors: No plan found in TAP output
Files=42, Tests=569, 47 wallclock secs ( 0.14 usr  0.03 sys +  3.97 cusr  0.55 csys =  4.69 CPU)
Result: FAIL
```

**Comment by jkeenan** [comment]
> perl -e'require "./Guff.pm";'

Confirmed.  Segfaults on both Linux and FreeBSD.

**Comment by haarg** [comment]
Alternative test case not requiring an external file:
```
perl -e'unshift @INC, sub { \"" }; require "guff";'
```
Using an `@INC` hook but amounting to the same thing: requiring an empty file.

**Comment by demerphq** [comment]
Should be fixed. Ill let @jkeenan close it once he is happy it works in blead.

**Comment by jkeenan** [comment]
> Should be fixed. Ill let @jkeenan close it once he is happy it works in blead.

Thanks for your investigation.  I can now install IO::Socket::SSL and Module::Pluggable against blead and then install Task::CPAN::Reporter.  Closing ticket.
