### ISSUE TITLE
Build fails on -Duse64bitint -DEBUGGING on 32-bit target

### ISSUE THREAD

**Issue by t-a-k** [Perl/perl5#20504]
**Description**
I've tried to build `blead` (d7c0b58cf68aeb7b08eee56a9e693a161f3f9106) for 32-bit x86 with `-Duse64bitint -DEBUGGING`, but build failed:
```
$ ./Configure -de -Dusedevel -DEBUGGING -Dcc='gcc -m32' -Duse64bitint
$ make
...
./miniperl -w -Ilib -Idist/Exporter/lib -MExporter -e '<?>' || sh -c 'echo >&2 Failed to build miniperl.  Please run make minitest; exit 1'
miniperl: mg.c:3659: S_restore_magic: Assertion `sizeof((IV)(unsigned long)(p)) == sizeof(SSize_t)' failed.
Aborted
Failed to build miniperl. Please run make minitest
make: *** [makefile:377: lib/buildcustomize.pl] Error 1
```
Bisecting points to commit 1a2b24d857d6903bb734c2fcb6cc2a72e1007059.

**Steps to Reproduce**
```
$ ./Configure -de -Dusedevel -DEBUGGING -Dcc='gcc -m32' -Duse64bitint
$ make
```

**Expected behavior**
Build succeeds.

**Comment by jkeenan** [comment]
The failure message is similar to that reported in https://github.com/Perl/perl5/issues/20490, and the OP has bisected the problem to the same commit identified in that ticket.

@tonycoz, can you investigate and recommend a course of action?  Thanks.

**Comment by jkeenan** [comment]
@t-a-k, could you please check out the branch developed by @Tonycoz in https://github.com/Perl/perl5/pull/20519 and let us know whether you can build in your environment?

**Comment by t-a-k** [comment]
> @t-a-k, could you please check out the branch developed by @tonycoz in #20519 and let us know whether you can build in your environment?

Sorry for delayed response.  I was able to build `20504-assertion-sssize_t` branch successfully (and `make test` passed).  It looks good to me.
