### ISSUE TITLE
Documentation for substr does not follow convention

### ISSUE THREAD

**Issue by KES777** [Perl/perl5#20560]
**Where**
https://perldoc.perl.org/functions/substr

**Description**
These are EXPR,OFFSET,LENGTH uppercased at text, but REPLACEMENT not.

Here it should be:
```diff
-An alternative to using [substr](https://perldoc.perl.org/functions/substr) as an lvalue is to specify the replacement string as the 4th argument.
+An alternative to using [substr](https://perldoc.perl.org/functions/substr) as an lvalue is to specify the REPLACEMENT string as the 4th argument.
```

**Comment by jkeenan** [comment]
> **Where** https://perldoc.perl.org/functions/substr
> 
> **Description** These are EXPR,OFFSET,LENGTH uppercased at text, but REPLACEMENT not.
> 
> Here it should be:
> 
> ```diff
> -An alternative to using [substr](https://perldoc.perl.org/functions/substr) as an lvalue is to specify the replacement string as the 4th argument.
> +An alternative to using [substr](https://perldoc.perl.org/functions/substr) as an lvalue is to specify the REPLACEMENT string as the 4th argument.
> ```

I'm on the fence with respect to this.  The all-lower-case phrase *replacement string* is perfectly fine English -- which argues against a revision.   However, later in the same paragraph we have *EXPR* in all-upper-case.
```
An alternative to using "substr" as an lvalue is to specify the
replacement string as the 4th argument.  This allows you to
replace parts of the EXPR and return what was there before in
one operation, just as you can with "splice".
```
So I'll do `s/replacement/REPLACEMENT/` in several days ... but allow for a few days of bikeshedding.

**Comment by khwilliamson** [comment]
LGTM as requested

**Comment by jkeenan** [comment]
Handled in d0a777fffc; closing ticket.
