### ISSUE TITLE
B on CPAN fails on older Perl releases

### ISSUE THREAD

**Issue by PhilterPaper** [Perl/perl5#20573]
Module: B

**Description**

This is more of a nuisance issue than an out-and-out bug. The B package found on cpan.org only installs/upgrades with the matching latest Perl release (currently 5.36). A lower Perl version fails:
```
cpan> upgrade B

Package namespace         installed    latest  in CPAN file
B                              1.80      1.83  RJBS/perl-5.36.0.tar.gz
Running install for module 'B'
The most recent version "1.83" of the module "B"
is part of the perl-5.36.0 distribution. To install that, you need to run
  force install B   --or--
  install RJBS/perl-5.36.0.tar.gz
Stopping: 'install' failed for 'B'.
Failed during this command:
 RJBS/perl-5.36.0.tar.gz                      : make NO isa perl

cpan>
```
The problem is that the next time I run the update process, it tries to install B again, and fails every time... It's just a waste of my time and CPU cycles to go through this every time. I _don't_ want to force a later B package on an earlier Perl version. I _do_ have a wrapper around cpan install/upgrade to avoid trying to do a B install (I daily update my Strawberry Perl 5.24, 5.26, and 5.32 installations), but it's still a nuisance (especially for others who don't create such tools).

This may really be more of an issue with CPAN and how it determines what packages/modules need updating, but I can't see how to file an issue against CPAN and its tools itself.

**Steps to Reproduce**

cpan> upgrade B  (while running Perl 5.34 or lower, Windows 10, Strawberry Perl 5.32)

**Expected behavior**

Either quietly skip any attempt to install/upgrade B on a mismatched Perl version (i.e., claim success?), or better yet, find some way for the cpan module to deliver the correct (matching) level of the B package. The cpan running on my machine would have to supply the Perl version to the server, which would then supply the matching B package. Does 'B' ever get updated between Perl releases?

**Perl configuration**

```
# perl -V output goes here
C:\Users\Phil>perl -V
Summary of my perl5 (revision 5 version 32 subversion 1) configuration:

  Platform:
    osname=MSWin32
    osvers=10.0.19042.746
    archname=MSWin32-x64-multi-thread
    uname='Win32 strawberry-perl 5.32.1.1 #1 Sun Jan 24 15:00:15 2021 x64'
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags =' -DWIN32 -DWIN64 -D__USE_MINGW_ANSI_STDIO -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields'
    optimize='-s -O2'
    cppflags='-DWIN32'
    ccversion=''
    gccversion='8.3.0'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='long long'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags ='-s -L"C:\Strawberry\perl\lib\CORE" -L"C:\Strawberry\c\lib"'
    libpth=C:\Strawberry\c\lib C:\Strawberry\c\x86_64-w64-mingw32\lib C:\Strawberry\c\lib\gcc\x86_64-w64-mingw32\8.3.0
    libs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    libc=
    so=dll
    useshrplib=true
    libperl=libperl532.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=xs.dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-mdll -s -L"C:\Strawberry\perl\lib\CORE" -L"C:\Strawberry\c\lib"'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    HAVE_INTERP_INTERN
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_IMPLICIT_SYS
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under MSWin32
  Compiled at Jan 24 2021 15:05:42
  @INC:
    C:/Strawberry/perl/site/lib/MSWin32-x64-multi-thread
    C:/Strawberry/perl/site/lib
    C:/Strawberry/perl/vendor/lib
    C:/Strawberry/perl/lib

C:\Users\Phil>
```

**Comment by jkeenan** [comment]
The `B` module is part of the Perl core distribution.  It is located under the `ext/` directory, which implies that it is maintained by Perl 5 Porters (not upstream on CPAN), does not get a separate CPAN release (as it would if it were located under `dist/`) and is specific to the production version of `perl` with which it is released.

To me, that suggests that `B` is *not* upgradeable.  So, I agree with you that the `cpan` utility's attempt to upgrade you on this module is unexpected behavior.  Let's see if we can get some commentary on that.
@briandfoy @andk, any thoughts?

**Comment by Grinnz** [comment]
The behavior is correct (it refuses to install because it finds the module is indexed to the `perl` distribution, which cannot be upgraded by cpan), but the error message is clearly nonideal; it should not be recommending ways to attempt to install the `perl` distribution, it should state that the module is not upgradeable via cpan.

**Comment by PhilterPaper** [comment]
Should B even be on CPAN in the first place? Does it get upgraded (within a Perl version) from time to time? Does a major.minor version of B work with any Perl fix release of the appropriate major.minor version? I see that the B major.minor is independent of the Perl major.minor -- perhaps they should use the same version? If there _is_ need to have it available on cpan.org, the cpan utility (and its relatives, such as cpanm) would probably have to be upgraded to either 

1. Only flag B to be upgraded if your Perl version is correct (matches B's), or
2. Query your installation to find your Perl version, and then compare your B against the appropriate version to see if updating is necessary. This means keeping many B versions around and not just one.

And of course, remove the suggestion to force install a mismatched B level (is that part of the B installation code?).

**Comment by Grinnz** [comment]
B is not on CPAN separately, it is part of the perl distribution, which as a whole is on CPAN. It cannot be upgraded.

**Comment by jkeenan** [comment]
> B is not on CPAN separately, it is part of the perl distribution, which as a whole is on CPAN. It cannot be upgraded.

I've opened this ticket upstream so that the maintainers of `cpan` can investigate:
https://rt.cpan.org/Ticket/Display.html?id=145471

Closing this ticket.
