### ISSUE TITLE
IO::Select and other modules in the IO package report version 1.49 whle IO itself is 1.50

### ISSUE THREAD

**Issue by szabgab** [Perl/perl5#20609]
```
$ cpanm IO::Select
--> Working on IO::Select
Fetching http://www.cpan.org/authors/id/T/TO/TODDR/IO-1.50.tar.gz ... OK
Configuring IO-1.50 ... OK
Building and testing IO-1.50 ... OK
Successfully installed IO-1.50 (upgraded from 1.46)
1 distribution installed
$ (gabor@code-maven:~/os/Marpa--R2/cpan) (ci) $ mversion IO::Select
1.49
```

On MetaCPAN we can also see that some (maybe all) the modules in IO-1.50 are internally 1.49. 
https://metacpan.org/pod/IO::Select

I know that IO.pm and IO/Select.pm can have different version numbers, but this is confusing.

**Comment by sisyphus** [comment]
Should already be fixed in blead by PR #19663.
Perhaps CPAN has not caught up yet ?

Cheers,
Rob

**Comment by Leont** [comment]
> Perhaps CPAN has not caught up yet ?

Sounds like someone should nudge @toddr

**Comment by toddr** [comment]
I'll take a look and make it happen by Sunday.

**Comment by jkeenan** [comment]
> I'll take a look and make it happen by Sunday.

@toddr, do you have a recommendation as to how we should proceed in this case?

**Comment by toddr** [comment]
Sorry I'll publish this afternoon

**Comment by toddr** [comment]
1.51 is now on CPAN.
