### ISSUE TITLE
This Perl not built to support threads

### ISSUE THREAD

**Issue by Veera2908** [Perl/perl5#20610]
--- 
I have declared the threads using "  use threads ;  ", I have executed the perl file,it throws " This Perl not built to support threads " , please find below perl version details and  Error output .

Perlverion  = V5.34.1

Error Output 
-------------------
This Perl not built to support threads

**Comment by Leont** [comment]
This is not a bug. You're using a perl that is defined without that feature, so then it doesn't work. This is also not the right place for this kind of usage problem, site like [stackoverflow](https://stackoverflow.com/questions/22036985/error-using-thread-module-this-perl-not-built-to-support-threads) are better places for usage issues.

**Comment by rwp0** [comment]
Basically, run `perl -V:useithreads` and check its output, if it shows `useithreads='define';` you can `use threads;` in your code.
If not, have to build Perl with `ithreads` (or install a readily built one with that option).
Many operating systems come with Perl built with `ithreads` feature, but it's not the default option for Perl distribution.

For the details please read the `INSTALL` file.

https://metacpan.org/dist/perl/view/INSTALL#Threads
