### ISSUE TITLE
Document OP_NEXT's use of OPf_SPECIAL in op.h

### ISSUE THREAD

**Issue by wolfsage** [Perl/perl5#20611]
See cd97dc8d499d664d75b7362093b5f93b8eef282d for its meaning

All ops that use the OPf_SPECIAL flag should be documented in op.h where OPf_SPECIAL is defined. This one is missing and should be pretty easy to add.

**Comment by leonerd** [comment]
Hrm; your link shows the code where the flag is tested by `pp_next`. I've been hunting around for the code which sets it but so far I've come up blank. `OP_NEXT` doesn't have an opchecker, nor does `peep.c` have much to do with an `OP_NEXT` at all.

**Comment by leonerd** [comment]
Ah, I see it. It's directly in the parser as a direct consequence of `next` vs `next LABEL`:

```
	|	LOOPEX  /* loop exiting command (goto, last, dump, etc) */
			{ $$ = newOP($LOOPEX, OPf_SPECIAL);
			    PL_hints |= HINT_BLOCK_SCOPE; }
	|	LOOPEX term[operand]
			{ $$ = newLOOPEX($LOOPEX,$operand); }
```

**Comment by iabyn** [comment]
On Fri, Dec 16, 2022 at 02:39:27AM -0800, Paul Evans wrote:
> Hrm; your link shows the code where the flag is tested by `pp_next`.
> I've been hunting around for the code which sets it but so far I've come
> up blank. `OP_NEXT` doesn't have an opchecker, nor does `peep.c` have
> much to do with an `OP_NEXT` at all.

perly.y: for the LOOPEX without arg case, it calls newOP($LOOPEX, OPf_SPECIAL)

There's a relatively easy way to answer 'where does this flag get set' in
gdb. Break at a point where you know the flag has been set, set a watchpoint
on the flag's storage location, then rerun and continue until the flag
changes:

$ PERL_HASH_SEED=0 gdb ./perl
(gdb) b Perl_pp_next
(gdb) run -e'for (1) { next; }'
Breakpoint 1, Perl_pp_next (my_perl=0xa8f2a0) at pp_ctl.c:2715
2715	    cx = CX_CUR();
(gdb) p my_perl->Iop->op_flags
$1 = 0x81
(gdb) wa -l my_perl->Iop->op_flags
(gdb) r
Hardware watchpoint 2: -location my_perl->Iop->op_flags

Old value = <unreadable>
New value = 0x0
0x00007ffff7ccb25b in __memset_evex_unaligned_erms () from /lib64/libc.so.6
(gdb) c
Hardware watchpoint 2: -location my_perl->Iop->op_flags

Old value = 0x0
New value = 0x80
Perl_newOP (my_perl=0xa8f2a0, type=0xd2, flags=0x80) at op.c:5418
5418	    o->op_next = o;
(gdb) up
#1  0x00000000004f5d9f in Perl_yyparse (my_perl=0xa8f2a0, gramtype=0x102)
    at /home/davem/perl5/git/bleed/perly.y:1356
1356				{ $$ = newOP($LOOPEX, OPf_SPECIAL);


-- 
A major Starfleet emergency breaks out near the Enterprise, but
fortunately some other ships in the area are able to deal with it to
everyone's satisfaction.
    -- Things That Never Happen in "Star Trek" #13

**Comment by leonerd** [comment]
Ah interesting. I've never had much luck with rerunning programs in gdb like that because often it gets different memory addresses. But that hint of `PERL_HASH_SEED=0` might do the trick.

**Comment by leonerd** [comment]
I believe #20614 fixes this now. @wolfsage Can this be closed?

**Comment by wolfsage** [comment]
Yes thank you. 

> I've never had much luck with rerunning programs in gdb like that because often it gets different memory addresses.

I think that's what https://rr-project.org/ aims to solve?
