### ISSUE TITLE
amagic_find() doesn't handle method fallback properly.

### ISSUE THREAD

**Issue by demerphq** [Perl/perl5#20627]
**Description**
The new amagic_find() only checks for one method, and includes a bunch of overhead before it does. This means it isn't really suitable  currently for determining if something "has a string overload" as it does not consult the fallback logic as amagic_call() would. I think we need to change amagic_find() so the method parameter is a *int and we need to change it so it can detect fallback methods as amagic_call() does. I don't think that we should reimplement amagic_call() with amagic_find(), as I think the code in amagic_call() takes into account a lot of independent issues that aren't relevant  to amagic_find(). (eg, amagic_call() knows about two variables for binary operations, and how to reorder arguments, etc, things which arent relevant for single SV api like amagic_find().  However we should ensure that amagic_find() returns true when amagic_call() would actually trigger a method. 

@ericherman, @book, @leonerd and @haarg may be interested in this ticket.

**Steps to Reproduce**
See https://github.com/Perl/perl5/pull/20626 for an example of internals logic using amgic_find() and getting the wrong answer for fallbacks.

**Expected behavior**
amagic_find() should return a CV for an object with fallback =1, a numeric overload, when it is asked for the string_amg method of the SV, it probably should also write the actual method it is returning back into the method argument.

**Perl configuration**
agmagic_find was added in 5.37.7 (very recently: bab261c9114a5ca4aee6acea592e42b95068af70 via https://github.com/Perl/perl5/pull/20604) and has not be used in anger yet. It is marked API. We should not let it be released in a production release with its current interface.

**Comment by ericherman** [comment]
I'd like help creating a failing test case, something a bit more focused than https://github.com/Perl/perl5/pull/20626 

Until then, it would be trivial to 
* add an unused parameter to the API,
* change the `int method` parameter to be an `int *`,
* or simply revert the patch.

While not as focused, maybe it can be tested indirectly. The code was extracted from https://github.com/Perl/perl5/pull/20503 ... perhaps there is a way to trigger the fallback oversight with the join tests?

@book pointed me to https://perldoc.perl.org/overload#Magic-Autogeneration as a way to possibly get fallback for `concat_amg`, but perhaps there is something more straight-forward.

Guidance welcome.

**Comment by demerphq** [comment]
On Mon, 19 Dec 2022, 13:16 Eric Herman, ***@***.***> wrote:

> I'd like help creating a failing test case, something a bit more focused
> than #20626 <https://github.com/Perl/perl5/pull/20626>
>
> Until then, it would be trivial to add an unused parameter to the API, or
> simply revert the patch.
>
> While not as focused, maybe it can be tested indirectly. The code was
> extracted from #20503 <https://github.com/Perl/perl5/pull/20503> ...
> perhaps there is a way to trigger the fallback oversight with the join
> tests?
>
> @book <https://github.com/book> pointed me to
> https://perldoc.perl.org/overload#Magic-Autogeneration as a way to
> possibly get fallback for concat, but perhaps there is something more
> straight-forward
>

What I would do is rip out the switch logic from amagic_call and duplicate
it in a reduced form. I'd make the method parameter a pointer to int, and
write back into that pointer the actual _amount value returned.

The switch in amagic_call solves a number of issues we don't care about, so
I would just the copy fallback method logic.

The "bug" that exists is if I ask amagic_find() for the string_amg it finds
that and only that. If I do the same thing with amagic_call it might
execute that or one of several other methods.

The PR  I showed demonstrates this, push an object with numification
defined, no stringification, but with fallback set to true, into @INC and
then require something that doesn't exist. You will see an error message.
If an object of this configuration is stringified it will call the
numification method, and thus amagic_find should also return true. About
half of the overload methods are affected by this, so it doesn't make sense
for every caller to have to know the rules. Also having each caller know
the rules and call amagic_find multiple times would be inefficient.

Anyway, definitely don't revert. If anything we could change it from "A" to
"E" in embed. This is something we should iterate on, not throw away
because it's not perfect.

Yves

>

**Comment by demerphq** [comment]
Sorry i was on my phone earlier.

In amagic_call() we have logic like this:

```
    if (cvp && amtp->fallback > AMGfallNEVER && flags & AMGf_unary) {
      int logic;

      /* look for substituted methods */
      /* In all the covered cases we should be called with assign==0. */
         switch (method) {
         case inc_amg:
           force_cpy = 1;
           if ((cv = cvp[off=add_ass_amg])
               || ((cv = cvp[off = add_amg])
                   && (force_cpy = 0, (postpr = 1)))) {
             right = &PL_sv_yes; lr = -1; assign = 1;
           }
           break;

```

Ilya really liked minimal code, so this is very dense. But basically the cv = cvp[off=add_ass_amg] type statements in there are what we want to extract. Some of the other stuff concerns the finer details of what magic_call() will do, which we dont care about. For instance 'force_cpy', 'postpr', 'right', 'lr',' and 'assign' arent relevant to us. We just want to know the final 'off'/cv pair that takes effect from that code. 

For a stringification operation for instance we have:

```
         case string_amg:
           (void)((cv = cvp[off=numer_amg]) || (cv = cvp[off=bool__amg]));
           break;
```

so really a call to amagic_find() for a string_amg should return the string_amg, numer_amg, or bool_amg CV, and assuming we change the method parameter to a pointer to integer, it should set the method argument to which one was found. Also there are various forms of fallback, so there are more than one set of rules for this stuff, so in practice there will likely be more than one switch just like in amagic_call()

The alternative is a caller needs to know these rules, and then has to write:

```
amagic_find(..,string_amg,...) || amagic_find(...,numer_amg,...) || amagic_find(..,bool__amg,...)
```
would would be a nightmare if the rules were ever changed, also quite duplicative and inefficient, as the API is operating on the RV, not on the underlying object, so each call would have to repeat the same setup validation logic.

We can maybe have a flag that says "literal search" where no fallback is applied, but honestly I cant see why anyone would do that. The main use for this function as far I can tell is to ask "what would overload do with this item", not "what exact methods does this particular overloaded object implement", which means we need to apply the same fallback rules as well.

FWIW, when I approved of this originally I thought that fallback was implemented by pre-computing the fallbacks and then populating the table appropriately, thus meaning that asking for string_amg would just Do The Right Thing. That was what i meant when I said that this function /should/ return the same thing that overload::Method() does.  Since that isn't the case I think we need to refine the function further.

**Comment by demerphq** [comment]
@ericherman turns out it needs two int* pointers. Some methods can be fallback to multiple method calls. Eg, abs_amg. :-( see the second commit in https://github.com/Perl/perl5/pull/20626 for what I think we should do. (My plans changed, i had a few hours to put it together.)

**Comment by demerphq** [comment]
Assuming I dont rebase I mean: https://github.com/Perl/perl5/pull/20626/commits/3ecba84330636061a8a97638a4a741a882dba26c

**Comment by demerphq** [comment]
A fix was merged for this in https://github.com/Perl/perl5/pull/20635, closing as fixed.
