### ISSUE TITLE
Bitwise OR unexpected behavior lacks warnings

### ISSUE THREAD

**Issue by rsFalse** [Perl/perl5#20648]
Module:

**Description**

DWIM sometimes fail. Reading numbers from the input treats them as stings and produces unexpected Bitwise OR results. Maybe some warnings would be helpful?

Although perlop states:
> Although no warning is currently raised, the results are not well defined when these operations are performed on operands that aren't either numbers (see ["Integer Arithmetic"](https://perldoc.perl.org/perlop#Integer-Arithmetic)) nor bitstrings (see ["Bitwise String Operators"](https://perldoc.perl.org/perlop#Bitwise-String-Operators)).

**Steps to Reproduce**

```
#!/usr/bin/perl

use warnings;
use strict;
# use integer;

$\ = $/;

my @A = qw( 1 5 6 );

my @x = split ' ', <DATA>;
my @y = ( 8, 7 );

# uncommenting any of following line makes x[0] numerical
# $x[ 0 ] | 0;
# $x[ 0 ] > 0;
# $x[ 0 ] + 0;
# $x[ 0 ] + 0; $x[ 0 ] . '';

for my $i ( 0 .. 1 ){
	
	print "[@A][$x[$i]][$y[$i]]";
	
	print 'x ', $_ | $x[ $i ] for @A;
	print 'y ', $_ | $y[ $i ] for @A;
	
	}

__DATA__
8 7

```
OUTPUT:
```
[1 5 6][8][8]
x 9
x =
x >
y 9
y 13
y 14
[1 5 6][7][7]
x 7
x 7
x 7
y 7
y 7
y 7
```
**Expected behavior**

Some warning may be useful, as numbers treated as strings.

**Perl configuration**

5.36, 5.14

**Comment by Grinnz** [comment]
This is why the [bitwise feature](https://perldoc.perl.org/feature#The-'bitwise'-feature) was introduced.
