### ISSUE TITLE
[doc] wrong syntax highlight in https://perldoc.perl.org/perlembed#Maintaining-a-persistent-interpreter 

### ISSUE THREAD

**Issue by Freed-Wu** [Perl/perl5#20640]
**Where**

https://perldoc.perl.org/perlembed#Maintaining-a-persistent-interpreter

**Description**

![screen-2022-12-22-20-29-41](https://user-images.githubusercontent.com/32936898/209134901-6e21d85a-3fd9-4638-b8ec-23b69e288794.jpg)

**Comment by jkeenan** [comment]
> **Where**
> 
> https://perldoc.perl.org/perlembed#Maintaining-a-persistent-interpreter
> 

The same code renders satisfactorily in a text editor (vim) and at https://github.com/Perl/perl5/blob/blead/pod/perlembed.pod.

The Perl 5 Porters do not have responsibility for maintaining the web site https://perldoc.perl.org.  Should you wish the text highlighting improved on that site, please follow the instructions at the bottom of https://perldoc.perl.org/.

Closing this ticket. 

Thank you very much.
Jim Keenan
