### ISSUE TITLE
 [rt.cpan.org #136654] Math::Trig: mention that $way defaults to 0.5 if not given

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#20721]
<URL: https://rt.cpan.org/Ticket/Display.html?id=136654 >

On Sat May 29 16:07:49 2021, jidanni@jidanni.org wrote:
> On the man page mention that $way defaults to 0.5 if not given.
> (Proof: the source code has
>    $point = 0.5 unless defined $point;
> )

> Since Math-Complex is now maintained as part of the Perl 5 core distribution, if you wish to pursue this bug report you should open an issue at https://github.com/Perl/perl5/issues.

**Comment by jkeenan** [comment]
> <URL: https://rt.cpan.org/Ticket/Display.html?id=136654 >
> 
> On Sat May 29 16:07:49 2021, [jidanni@jidanni.org](mailto:jidanni@jidanni.org) wrote:
> 
> > On the man page mention that $way defaults to 0.5 if not given.
> > (Proof: the source code has
> > $point = 0.5 unless defined $point;
> > )
> 

I don't think this change is necessary, and no one spoke up for it when it was still a ticket on rt.cpan.org.  However, if someone produces a pull request in the next two weeks, we will give it consideration.

**Comment by jkeenan** [comment]
> > <URL: https://rt.cpan.org/Ticket/Display.html?id=136654 >
> > On Sat May 29 16:07:49 2021, [jidanni@jidanni.org](mailto:jidanni@jidanni.org) wrote:
> > > On the man page mention that $way defaults to 0.5 if not given.
> > > (Proof: the source code has
> > > $point = 0.5 unless defined $point;
> > > )
> 
> I don't think this change is necessary, and no one spoke up for it when it was still a ticket on rt.cpan.org. However, if someone produces a pull request in the next two weeks, we will give it consideration.

No pull request has been presented; closing as per schedule.
