### ISSUE TITLE
 [rt.cpan.org #123108] [PATCH] Give angle from London in degrees too

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#20720]
<URL: https://rt.cpan.org/Ticket/Display.html?id=123108 >

On Fri Sep 22 10:51:17 2017, jidanni@jidanni.org wrote:
> The example needs to output degrees also. Because:
> 1. Initial input was in degrees, not radians.
> 2. Nobody uses radian when discussing geography. Only degrees.
> 
> --- /usr/share/perl/5.26.0/Math/Trig.pm	2017-09-12 23:07:07.000000000 +0800
> +++ /tmp/Trig.pm	2017-09-22 19:46:00.234885768 +0800
> @@ -660,9 +660,10 @@
>  The direction you would have to go from London to Tokyo (in radians,
>  straight north being zero, straight east being pi/2).
>  
> -    use Math::Trig qw(great_circle_direction);
> +    use Math::Trig qw(great_circle_direction rad2deg);
>  
>      my $rad = great_circle_direction(@L, @T); # About 0.547 or 0.174 pi.
> +    my $deg = rad2deg($rad); # 31.32 degrees east of north.
>  
>  The midpoint between London and Tokyo being

> Math-Complex is now maintained as part of the Perl 5 core distribution.  Hence, this RT ticket should be transformed into a ticket in Perl's own issue tracker at https://github.com/Perl/perl5/issues.
https://rt.cpan.org/Public/Bug/Display.html?id=123108

**Comment by jkeenan** [comment]
> <URL: https://rt.cpan.org/Ticket/Display.html?id=123108 >
> 
> On Fri Sep 22 10:51:17 2017, [jidanni@jidanni.org](mailto:jidanni@jidanni.org) wrote:
> 
> > The example needs to output degrees also. Because:
> > 
> > 1. Initial input was in degrees, not radians.
> > 2. Nobody uses radian when discussing geography. Only degrees.
> > 

I don't think this change is necessary, and no one spoke up for it when it was still a ticket on rt.cpan.org.  However, if someone produces a pull request in the next two weeks, we will give it consideration.

**Comment by jkeenan** [comment]
> > <URL: https://rt.cpan.org/Ticket/Display.html?id=123108 >
> > On Fri Sep 22 10:51:17 2017, [jidanni@jidanni.org](mailto:jidanni@jidanni.org) wrote:
> > > The example needs to output degrees also. Because:
> > > 
> > > 1. Initial input was in degrees, not radians.
> > > 2. Nobody uses radian when discussing geography. Only degrees.
> 
> I don't think this change is necessary, and no one spoke up for it when it was still a ticket on rt.cpan.org. However, if someone produces a pull request in the next two weeks, we will give it consideration.

No pull request has been presented; closing as per schedule.
