### ISSUE TITLE
n-at-a-time `foreach` does not print a warning about odd-sized list

### ISSUE THREAD

**Issue by leonerd** [Perl/perl5#20760]
When assigning to a hash, an even-sized list is required. If an odd-sized list is presented, perl prints a warning:

```
my %h = (1, 2, 3);
Odd number of elements in hash assignment at (eval 7) line 1.
```

The new n-at-a-time `foreach` syntax never gives a warning in similar circumstances:

```
use experimental 'for_list'; foreach my ($k, $v) (1,2,3) {}
# no warning
```

Perhaps it should? It can't be worded quite the same way, because "odd vs even" is only a useful concept for n=2. But perhaps some wording such as:

```
Insufficient elements for final bundle of foreach list at ...
```

**Comment by haarg** [comment]
Previous discussion about what the behavior should be: https://github.com/Perl/perl5/pull/18925#discussion_r709852571

When I was writing the RFC for map/grep with multiple variables, I forgot to check it against what the current behavior of for was. I ended up writing that if there were insufficient elements for the final iteration, a warning should be issued. Depending on what gets decided here, I'll be updating the RFC to match. But throwing warnings for this does seem reasonable.

**Comment by iabyn** [comment]
On Wed, Feb 01, 2023 at 02:53:27PM -0800, Paul Evans wrote:
> use experimental 'for_list'; foreach my ($k, $v) (1,2,3) {}
> # no warning
> ```
> 
> Perhaps it should? It can't be worded quite the same way, because "odd vs even" is only a useful concept for n=2. But perhaps some wording such as:

I don't think it should warn. Having the list not an exact multiple of the
number of variables has documented behaviour, and in many circumstances,
that will be reasonable behaviour.

The code will already get a warning from subsequently using the undefined
value as-is:

    $ perl -we'for my ($x,$y) (1,2,3) { $t += $y }'
    ...
    Use of uninitialized value in addition (+) at -e line 1.




-- 
Counsellor Troi states something other than the blindingly obvious.
    -- Things That Never Happen in "Star Trek" #16

**Comment by tobyink** [comment]
> Having the list not an exact multiple of the number of variables has documented behaviour, and in many circumstances, that will be reasonable behaviour.

Isn't that also true of `my %hash = ( "foo" );`, which _does_ warn?

**Comment by Grinnz** [comment]
Yes, but it seems much more likely and useful to intentionally use an uneven list in this case than in hash assignment (particularly since this isn't only for 2 at a time)

**Comment by tonycoz** [comment]
I don't think this should warn, just as `my ($x, $y, $z) = (1, 2)` doesn't warn, but I can see why there's discussion about it.

**Comment by tonycoz** [comment]
This is closable as WONTFIX I think, based on the [discussion on the list](https://www.nntp.perl.org/group/perl.perl5.porters/2024/03/msg268109.html) (including by @leonerd who opened the ticket.)

**Comment by jkeenan** [comment]
> This is closable as WONTFIX I think, based on the [discussion on the list](https://www.nntp.perl.org/group/perl.perl5.porters/2024/03/msg268109.html) (including by @leonerd who opened the ticket.)

Since April, no one has called for keeping this ticket open.  Closing now.
