### ISSUE TITLE
[MSWin32] Devel-Peek failing its test suite.

### ISSUE THREAD

**Issue by sisyphus** [Perl/perl5#20851]
**Description**

The issue arises with the current devel release (5.37.9) if and only if I am doing a -Duse64bitint build of 32-bit (x86) perl on MS Windows.
And the failure occurs (in the cleanup) only during the running of the test suite (ext/Devel-Peek/Peek.t).
That failure is reported as:
```
../ext/Devel-Peek/t/Peek.t ...... Dubious, test returned 5 (wstat 1280, 0x500)
All 33 subtests passed
```
If that test script is run outside of the testing harness, it runs fine - though the cleanup, after all tests have been reported as passing, typically takes around 4 seconds.
It makes no difference whether we build with a Microsoft compiler, or with a MinGW compiler.
It makes no difference whether the build is threaded (multi-thread) or unthreaded (perlio) - except that the cleanup at the end of Peek.t happens instantly when it is run outside of the harness on an unthreaded perl.

I would think that this issue is related to:
```
commit a405f1587e7ebdf2d76c4158dee7f80e14bb4003
Author: Yves Orton <demerphq@gmail.com>
Date:   Fri Jan 20 16:19:36 2023 +0100
```
AFAICS, the only change between Devel-Peek-1.32 (perl-5.37.8) and Devel-Peek-1.33 (perl-5.37.9) is in t/Peek.t.
(So I'm thinking that the issue is probably in dump.c.)

Cheers,
Rob
```
Summary of my perl5 (revision 5 version 37 subversion 9) configuration:

  Platform:
    osname=MSWin32
    osvers=10.0.22000.1574
    archname=MSWin32-x86-multi-thread-64int
    uname=''
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='gcc'
    ccflags =' -DWIN32 -D_WIN32_WINNT=0x0a00 -fdiagnostics-color=never -DPERL_TEXTMODE_SCRIPTS -DMULTIPLICITY -DPERL_IMPLICIT_SYS -DUSE_PERLIO -D__USE_MINGW_ANSI_STDIO -fwrapv -fno-strict-aliasing -mms-bitfields'
    optimize='-O2'
    cppflags='-DWIN32'
    ccversion=''
    gccversion='12.2.0'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=4
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=12
    longdblkind=3
    ivtype='long long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='long long'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags ='-s -L"D:\perl-5.37.9-1220\lib\MSWin32-x86-multi-thread-64int\CORE" -L"C:\winlibs-gcc-1220\mingw32\lib" -L"C:\winlibs-gcc-1220\mingw32\i686-w64-mingw32\lib" -L"C:\winlibs-gcc-1220\mingw32\lib\gcc\i686-w64-mingw32\12.2.0"'
    libpth=C:\winlibs-gcc-1220\mingw32\lib C:\winlibs-gcc-1220\mingw32\i686-w64-mingw32\lib C:\winlibs-gcc-1220\mingw32\lib\gcc\i686-w64-mingw32\12.2.0 D:\_32\msys_1220\1.0\local\lib
    libs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    libc=
    so=dll
    useshrplib=true
    libperl=libperl537.a
    gnulibc_version=''
    mingwrt_version='10.0.0'
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-shared -s -L"D:\perl-5.37.9-1220\lib\MSWin32-x86-multi-thread-64int\CORE" -L"C:\winlibs-gcc-1220\mingw32\lib" -L"C:\winlibs-gcc-1220\mingw32\i686-w64-mingw32\lib" -L"C:\winlibs-gcc-1220\mingw32\lib\gcc\i686-w64-mingw32\12.2.0"'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    HAVE_INTERP_INTERN
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_IMPLICIT_SYS
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under MSWin32
  Compiled at Feb 21 2023 21:11:09
  @INC:
    D:/perl-5.37.9-1220/site/lib/MSWin32-x86-multi-thread-64int
    D:/perl-5.37.9-1220/site/lib
    D:/perl-5.37.9-1220/lib/MSWin32-x86-multi-thread-64int
    D:/perl-5.37.9-1220/lib
```

**Comment by demerphq** [comment]
> The issue arises with the current devel release (5.37.9) if and only if I am doing a -Duse64bitint build of 32-bit (x86) perl on MS Windows

Just to clarify, does that mean you tried it on linux and it was fine?

**Comment by demerphq** [comment]
>  If that test script is run outside of the testing harness, it runs fine - though the cleanup, after all tests have been reported as passing, typically takes around 4 seconds.

Can you run it with valgrind or asan or anything like that?

**Comment by sisyphus** [comment]
> Just to clarify, does that mean you tried it on linux and it was fine?

Frustratingly, I've not been able to  test on Linux.
My ppc64 box with Debian wheezy allowed building of 32-bit perls with ease .... but I've been unable to boot it since about September last year.

On my Acer laptop that houses freebsd-12 I do have a 32-bit build of perl-5.30.0, but now find I'm unable to do 32-bit builds on it, too.
Configure now complains that /usr/bin/ld is incompatible - even when I try to rebuild that very same perl-5.30.0 from source using the same configuration args as reported by <code>perl -V:config_args</code>:
```
/usr/bin/ld: error: /usr/local/lib/libgdbm.so is incompatible with elf_i386_fbsd
cc: error: linker command failed with exit code 1 (use -v to see invocation)
I can't compile the test program.
```
And I've never been able to build 32-bit perls on Ubuntu. (I think I first need to install a 32-bit toolchain.)

Also, no experience with valgrind and async, here.

It'd be good if someone who *can* build a 32-bit linux perl would do so (with <code>-Duse64bitint</code>) so that we can find out.
I'll continue to try to rediscover the secret of 32-bit builds on freebsd-12.

Cheers,
Rob

**Comment by demerphq** [comment]
>It'd be good if someone who can build a 32-bit linux perl would do so (with -Duse64bitint) so that we can find out.

I have found some minor type warning issues, but nothing that would explain what you report, nor any test failures.

**Comment by sisyphus** [comment]
> I have found some minor type warning issues, but nothing that would explain what you report, nor any test failures.

Well ... the merging of #20853 into blead has resolved the issue.
Turns out that my report was a little inaccurate (for some questionable definition of "little").
Irrespective of whether t/Peek.t was being run inside or outside of the test harness, the script was crashing silently following the completion of test 33 and before the completion of test 34.
Inside the testing harness, the problem was noticed and reported.
Outside the testing harness, however, there was no output to indicate that anything had gone awry - which fooled me into thinking that the script had reached its completion, and exited normally.

All done .... thanks @demerphq !!

Cheers,
Rob

**Comment by demerphq** [comment]
Oh. Nice. 😀 glad it worked out. I assumed when I couldn't reproduce that I was "just" silencing some build noise. Glad to hear it actually did fix the issue. Thanks for getting back to me so quickly.

**Comment by iabyn** [comment]
On Fri, Feb 24, 2023 at 07:32:12PM -0800, sisyphus wrote:
> If that test script is run outside of the testing harness, it runs fine

For future reference: that's usually because the test harness sets
the environment variable PERL_DESTRUCT_LEVEL to 2, which triggers an extra
bunch of clean up at the end.

-- 
I before E. Except when it isn't.
