### ISSUE TITLE
BBC: Bleadperl breaks eval error message tests by adding "Execution of ... aborted due to compilation errors." to compile errors.

### ISSUE THREAD

**Issue by eserte** [Perl/perl5#20864]
t/30_slaymake.t in Slay-Makefile-0.13 started to fail with 5.37.9:
```
t/30_slaymake.t .......... 1/9 
#   Failed test 'bad_opt_e.ok'
#   at /home/e/eserte/src/CPAN/Slay-Makefile/t/runtests.pm line 51.
#          got: '1c1,2
# < 1: syntax error at -e line 2, near "4)" at ../../blib/script/slaymake line 314159
# ---
# > 1: syntax error at -e line 2, near "4)"
# > Execution of -e aborted due to compilation errors. at ../../blib/script/slaymake line 314159
# '
#     expected: ''
t/30_slaymake.t .......... 7/9 # Looks like you failed 1 test of 9.
t/30_slaymake.t .......... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/9 subtests 
```

**Comment by demerphq** [comment]
You need to fix your test. As of https://github.com/Perl/perl5/pull/20357 eval now behaves consistently with regard to errors. That means that when it fails to eval the error message consistently includes the text: "Execution of ... aborted due to compilation errors". Prior to that PR whether this would show up would depend on the nature and count of errors encountered in the eval'ed text. Now it shows up always.

**Comment by demerphq** [comment]
Fixed with https://github.com/eserte/Slay-Makefile/pull/5

**Comment by andk** [comment]
For the record: the actual commit that introduced the relevant change was v5.37.8-202-g21938ae5a2 (a.k.a. 21938ae5a2)

Consequently I'll use this issue to report any "also affected" here.

Also affected: PSCUST/Text-MacroScript-2.11.tar.gz
Sample fail report: http://www.cpantesters.org/cpan/report/aa56d040-b5fd-11ed-8031-ba59a0688e59
Note: the cpantesters reports webpage is not responsive at the time of this writing

Also affected:  TATE/Text-Template-Compact-0.1.12.tar.gz
Sample fail report: http://www.cpantesters.org/cpan/report/e05a86ee-b460-11ed-b32f-f38261820048

**Comment by demerphq** [comment]
> Also affected: TATE/Text-Template-Compact-0.1.12.tar.gz

Patch posted as https://rt.cpan.org/Ticket/Display.html?id=146913

**Comment by demerphq** [comment]
> Also affected: PSCUST/Text-MacroScript-2.11.tar.gz:

Patch pushed as: https://github.com/pauloscustodio/Text-MacroScript/pull/65

**Comment by rjbs** [comment]
Closed, not a blocker.
