### ISSUE TITLE
[doc] perlsub still refers to signatures as experimental

### ISSUE THREAD

**Issue by robrwo** [Perl/perl5#20925]
Near line 101,
```pod
Aside from an experimental facility (see L</Signatures> below),
Perl does not have named formal parameters.
```

But signatures are no longer experimental as of v5.36.

In the Signatures section of perlsub:
```pod
=head2 Signatures

B<WARNING>: Subroutine signatures are experimental.  The feature may be
modified or removed in future versions of Perl.

Perl has an experimental facility to allow a subroutine's formal
parameters to be introduced by special syntax, separate from the
procedural code of the subroutine body.
```

**Comment by tonycoz** [comment]
I don't see this in perlsub in 5.36, or in blead.

Both of these wer removed in 088588be (v5.35.8-119-g088588be57), which is part of 5.36.

**Comment by robrwo** [comment]
Hm, The blead branch of the git repo is still on v5.35.

**Comment by Grinnz** [comment]
It is not - perhaps you are looking at blead on an out of date fork?

**Comment by robrwo** [comment]
> It is not - perhaps you are looking at blead on an out of date fork?

Possiblly, my mistake then.
