### ISSUE TITLE
Blead breaks MAUKE/HTML-Blitz-0.07

### ISSUE THREAD

**Issue by mauke** [Perl/perl5#20945]
Sample report: https://www.cpantesters.org/cpan/report/e1513e54-c6b1-11ed-a7e8-4514ef0028d7

This is due to the following change:

5.36.0:
```
(v5.36.0) $ perl -we 'my $flork; ($flork = undef) =~ s/a/b/'
Use of uninitialized value $flork in substitution (s///) at -e line 1.
```
Blead:
```
(667b5e4) $ ./perl -we 'my $flork; ($flork = undef) =~ s/a/b/'
Use of uninitialized value in substitution (s///) at -e line 1.
```
The variable name is gone from the error message.

A simple bisect points to

> commit 9fdd7fc4796d89d16dceea42f2af91e4fde296ed
> Author: Richard Leach <rich+perl@hyphen-dash-hyphen.info>
> Date:   2022-07-08 14:52:19 +0000
> 
>    Implement OP_PADSV_STORE - combined sassign/padsv OP

as the source of the regression.

**Comment by jkeenan** [comment]
@richardleach can you take a look? Thanks.

**Comment by mauke** [comment]
@jkeenan I think he already did: https://github.com/Perl/perl5/pull/20946#issuecomment-1477120018
