### ISSUE TITLE
HPUX Itanium fails build with -Duselongdouble

### ISSUE THREAD

**Issue by demerphq** [Perl/perl5#20959]
**Description**
When building with uselongdouble HPUX fails many tests related number stringification. This may be related to #20953 which is a test failure from the same platform but with the 'uselongdouble' in configure.

**Steps to Reproduce**
```
./Configure -Duse64bitall -Dusethreads -Duseithreads -Duselongdouble -Doptimize=-g -d -Dusedevel -DDEBUGGING
```
and then run make test on an HPUX box (@tux can provide access to the one I used). It will fail lots of tests related to stringifying numbers. 

A notable clase of failures come from building XS modules and stringifying their XS_VERSION info:

```
# cc -c   -D_POSIX_C_SOURCE=199506L -D_REENTRANT -Ae -Wp,-H150000 -D_HPUX_SOURCE -Wl,+vnocompatwarnings +DD64 -DDEBUGGING -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -g   -DVERSION=\"1.19999999999999995559107901499374\" -DXS_VERSION=\"1.19999999999999995559107901499374\" +Z "-I../../../../.."   file.c
```

A simpler example is the following:

```
$ ./perl -Ilib /data/perl/usr/yorton/perl5/t/base/num.t               
1..56
ok 1
ok 2
ok 3
ok 4
not ok 5 # 0.100000000000000005551115123125783
not ok 6 # -0.100000000000000005551115123125783
not ok 7 # 0.100000000000000005551115123125783
not ok 8 # -0.100000000000000005551115123125783
not ok 9 # 10.0099999999999997868371792719699
ok 10
ok 11
ok 12
ok 13
ok 14
ok 15
ok 16
ok 17
ok 18
ok 19
ok 20
ok 21
ok 22
ok 23
ok 24
ok 25
ok 26
ok 27
ok 28
ok 29
ok 30
not ok 31 # 0.0100000000000000002081668171172169
not ok 32 # 0.00100000000000000002081668171172169
not ok 33 # 0.00010000000000000000479217360238593
not ok 34 # 9.00000000000000056682089577542172e-05
not ok 35 # 1.10000000000000008881784197001252
not ok 36 # 1.01000000000000000888178419700125
not ok 37 # 1.00099999999999988986587595718447
not ok 38 # 1.00009999999999998898658759571845
not ok 39 # 1.00001000000000006551204023708124
not ok 40 # 1.0000009999999999177333620536956
ok 41
ok 42
ok 43
not ok 44 # 123.456000000000003069544618483633
not ok 45 # 9.99999999999999945575230987042816e+33
ok 46
ok 47
ok 48
ok 49
ok 50
ok 51
ok 52
ok 53
ok 54
ok 55
ok 56
```

**Expected behavior**
We shouldn't fail any test under this build mode. 

**Perl configuration**
```
./perl -Ilib -V
Summary of my perl5 (revision 5 version 37 subversion 11) configuration:
  Commit id: d27f115fb570a13a37ff51b85a3d176a6b06b3e8
  Platform:
    osname=hpux
    osvers=11.31
    archname=IA64.ARCHREV_0-thread-multi-LP64-ld
    uname='hp-ux x2 b.11.31 u ia64 1894272509 unlimited-user license '
    config_args='-Duse64bitall -Dusethreads -Duseithreads -Duselongdouble -Doptimize=-g -d -Dusedevel -DDEBUGGING'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=define
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags =' -D_POSIX_C_SOURCE=199506L -D_REENTRANT -Ae -Wp,-H150000 -D_HPUX_SOURCE -Wl,+vnocompatwarnings +DD64 -DDEBUGGING -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 '
    optimize='-g'
    cppflags='-Aa -D__STDC_EXT__ -D_HPUX_SOURCE -D_POSIX_C_SOURCE=199506L -D_REENTRANT -Ae -Wp,-H150000 -D_HPUX_SOURCE -Wl,+vnocompatwarnings +DD64 -DDEBUGGING -I/usr/local/include'
    ccversion='B3910B A.06.28.02'
    gccversion=''
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=87654321
    doublekind=4
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=2
    ivtype='long'
    ivsize=8
    nvtype='long double'
    nvsize=16
    Off_t='off_t'
    lseeksize=8
    alignbytes=16
    prototype=define
  Linker and Libraries:
    ld='/usr/bin/ld'
    ldflags =' +DD64 -L/usr/local/lib -L/usr/lib/hpux64'
    libpth=/usr/local/lib /usr/lib/hpux64 /lib /usr/lib /usr/ccs/lib
    libs=-lcl -lpthread -ldl -lm -lsec -lc
    perllibs=-lcl -lpthread -ldl -lm -lsec -lc
    libc=/usr/lib/hpux64/libc.so
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_hpux.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E -Wl,-B,deferred '
    cccdlflags='+Z'
    lddlflags='-b +vnocompatwarnings -L/usr/local/lib -L/usr/lib/hpux64'


Characteristics of this binary (from libperl): 
  Compile-time options:
    DEBUGGING
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_TRACK_MEMPOOL
    PERL_USE_DEVEL
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_LONG_DOUBLE
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
  Built under hpux
  Compiled at Mar 23 2023 14:04:28
  @INC:
    lib
    /opt/perl5/lib/site_perl/5.37.11/IA64.ARCHREV_0-thread-multi-LP64-ld
    /opt/perl5/lib/site_perl/5.37.11
    /opt/perl5/lib/5.37.11/IA64.ARCHREV_0-thread-multi-LP64-ld
    /opt/perl5/lib/5.37.11
```

**Comment by demerphq** [comment]
@sisyphus do you have any suggestions on this one?

**Comment by demerphq** [comment]
Note all my tests on this were on top of https://github.com/Perl/perl5/pull/20958

**Comment by sisyphus** [comment]
><code> not ok 5 # 0.100000000000000005551115123125783</code>

The failure I've just quoted is in response to this test:
```
$a = 0.1; "$a";
print $a eq "0.1"     ? "ok 5\n"  : "not ok 5 # $a\n"
```
The nvtype is the big-endian IEEE 754 long double (essentially the same as the big endian __float128).

For some reason, $a is the double 0.1, not the long double 0.1.
I can't yet see why that would be. 
Could it have anything to with the specialness of "$a" ? That seems unlikely, but the question could be answered by just checking the output of:
```
perl -le 'print 0.1;'
```
I can reproduce the obtaiing of that value just fine on my perls (built with nvtype of 'double'), by assigning the double 0.1 to a 113-bit precision Math::MPFR object:
```
D:\>perl -MMath::MPFR=":mpfr" -le "Rmpfr_set_default_prec(113); print Math::MPFR->new(0.1);"
1.00000000000000005551115123125782702e-1
```
Your HPUX perl then does the expected thing of rounding away the last 3 digits, resulting in <code>0.100000000000000005551115123125783</code>

I've assumed that the other failures are due to the same issue.
@demerphq - If there's evidence of any additional issues, please feel free to draw my attention to them.

UPDATE: This issue is unrelated to https://github.com/Perl/perl5/issues/20953

Cheers,
Rob

**Comment by demerphq** [comment]
> Could it have anything to with the specialness of "$a" ? That seems unlikely, 

Yeah, I would find that surprising.

> but the question could be answered by just checking the output of:

-bash-5.1$ ./perl -le'print 0.1'
0.100000000000000005551115123125783

So it happens there as well.

**Comment by sisyphus** [comment]
Ok - so if you look at the mantissa of this long double 0.1, you will see that the first 53 bits match the mantissa of the double 0.1.
The next 60 bits of this long double 0.1 are zeros. (IOW, it's just zero-padding a double.)
That is not the correct long double representation of 0.1.

I guess this behaviour is determined by the the toolchain that builds this perl - which I now notice is not GNU C.
Is it possible to build perl on this machine using a recent gcc instead ?
If so, it might make a difference here, as well as (perhaps) to https://github.com/Perl/perl5/issues/20953 .

Out of curiosity, what does this one-liner output:
```
perl -le 'print "ok" if 0.1 == 1 / 10;'
```

@Tux has  contacted me off line, offering ssh access to this system.
I'll take him up on the offer, and will therefore soon be able to test out some of these things for myself,

Cheers,
Rob

**Comment by Tux** [comment]
On Fri, 24 Mar 2023 01:45:19 -0700, sisyphus ***@***.***> wrote:

> Ok - so if you look at the mantissa of this long double 0.1, you will
> see that the first 53 bits match the mantissa of the double 0.1. The
> next 60 bits of this long double 0.1 are zeros. (IOW, it's just
> zero-padding a double.) That is not the correct long double
> representation of 0.1.
> 
> I guess this behaviour is determined by the the toolchain that builds
> this perl - which I now notice is not GNU C. Is it possible to build
> perl on this machine using a recent gcc instead ?

Sorry, no: HP does not have a "recent" gcc available and I never
managed to get a working gcc compiled beyond version 4.7.2 on this
machine. It has to do with a combination of dependencies on GNU as,
mpfr, mpc and gmp and as bonus a stack limitation

> If so, it might make a difference here, as well as (perhaps) to
> https://github.com/Perl/perl5/issues/20953 .
> 
> Out of curiosity, what does this one-liner output:
> ```
> perl -le 'print "ok" if 0.1 == 1 / 10;'
> ```
> 
> @Tux has  contacted me off line, offering ssh access to this system.
> I'll take him up on the offer, and will therefore soon be able to
> test out some of these things for myself,
> 
> Rob

-- 
H.Merijn Brand  https://tux.nl   Perl Monger   http://amsterdam.pm.org/
using perl5.00307 .. 5.37        porting perl5 on HP-UX, AIX, and Linux
https://tux.nl/email.html http://qa.perl.org https://www.test-smoke.org

**Comment by demerphq** [comment]
On Fri, 24 Mar 2023, 09:45 sisyphus, ***@***.***> wrote:

> Out of curiosity, what does this one-liner output:
>
> perl -le 'print "ok" if 0.1 == 1 / 10;'
>
> <https://github.com/Tux>
>
I'm at the dentist just now, can tell you in about an hour


@Tux <https://github.com/Tux> has contacted me off line, offering ssh
> access to this system.
> I'll take him up on the offer, and will therefore soon be able to test out
> some of these things for myself,
>

I have a branch in a PR which fixes a bunch of build warnings. Afaik the
numeric issues happen with or without the branch. I strongly recommend you
build my branch or you will drown in warnings

Yves

>

**Comment by demerphq** [comment]
@sisyphus asked:
> Out of curiosity, what does this one-liner output:

I tweaked it a bit. The original output nothing.

```
$ ./perl -le 'printf "%sok\n", 0.1 == 1 / 10 ? "" : "not "; print 1/10; print 0.1;' 
not ok
0.1
0.100000000000000005551115123125783
```

**Comment by demerphq** [comment]
BTW, a couple of tips for working on the HPUX box that @Tux provides devs.

1. Add the /prob/bin stuff your path:
```
export PATH=/pro/local/bin:/pro/bin:$PATH
```
2. Compile with -g0 *not* simply -g: 
```
./Configure -Duse64bitall -Dusethreads -Duseithreads -Duselongdouble -Doptimize=-g0 -d -Dusedevel -DDEBUGGING
```
3. Use parallel build to run make and tests:
```
make -j16 test_prep
TEST_JOBS=16 make test_harness
TEST_JOBS=16 make test_harness TEST_ARGS="-v -re sprintf2"
```
4. Use gdb64 which does not support the --args parameter: 
```
gdb64 ./perl
(gdb) r -le'print 0.1'
```

Notably the --args option to gdb is not supported, so you need to do the two step process to run a oneliner, you can supply the program to the r command once you are in gdb. It accepts multiple arguments.

**Comment by Tux** [comment]
That HP-UX only has 4 CPU's, so `-j16` is huge overkill, certainly if there are also others working on that box. It is old and not equiped with as much RAM as one normally finds on modern machines. RAM was expansive those days.

**Comment by demerphq** [comment]
> That HP-UX only has 4 CPU's, so -j16 is huge overkill,

Sorry. Force of habit. Ill reduce it. But the core-count and the job count don't always line up.  If many jobs are blocking on IO having a high count than cores can still speed things up.

Also @Tux  I believe i have gotten to the bottom of this. For some reason HAS_LONG_DOUBLE is not defined on the HPUX build, so the code goes through strtod instead of strtold() in S_strtod(). I think this is a Configure issue, but I am not 100% certain yet. If you have a few moments to poke at it or tell me how i can force the define to be true I'll try `-Accflags=-DHAS_LONG_DOUBLE=1` in a few minutes.

**Comment by demerphq** [comment]
> For some reason HAS_LONG_DOUBLE is not defined on the HPUX build, so the code goes through strtod instead of strtold() in S_strtod().

Actually this isn't correct.  It is HAS_STRTOLD which isn't defined? I see some stuff in the hints file about this. I wonder if it is related?

**Comment by demerphq** [comment]
And yep, it is related:
```
strtold() found.
Hmm.  Based on the hints in hints/hpux.sh, 
the recommended value for $d_strtold on this machine was "undef"!
    Keep the recommended value? [y]  
```

Im going to see what happens if i disable that hint for now.

**Comment by demerphq** [comment]
FWIW, I am testing right now with improved hints logic for hpux. so far it looks good. I think I have cracked this one.

**Comment by demerphq** [comment]
This is fixed with https://github.com/Perl/perl5/pull/20958
