### ISSUE TITLE
Warning: Cast truncates Constant Value

### ISSUE THREAD

**Issue by mubinskt** [Perl/perl5#20999]
Module:

**Description**

The inline.h file reports warning C4310 
https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4310?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C4310)%26rd%3Dtrue&view=msvc-170

![image](https://user-images.githubusercontent.com/48523534/229121937-2e76feac-cd0c-4252-94f0-57aa521d53ac.png)

**Steps to Reproduce**

Rebuild in a MFC Windows application referring perl files.

**Expected behavior**

**Perl configuration**

```

This is perl 5, version 32, subversion 1 (v5.32.1) built for MSWin32-x64-multi-thread

Copyright 1987-2021, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.
```

**Comment by demerphq** [comment]
As far as I can tell this is a bug in the MSVC, which is getting confused. There is a fairly long set of defines involved here:

```
#define NATIVE_BYTE_IS_INVARIANT(c)     UVCHR_IS_INVARIANT(c)
#define UVCHR_IS_INVARIANT(cp)  (OFFUNI_IS_INVARIANT(NATIVE_TO_UNI(cp)))
#define NATIVE_TO_UNI(ch)        ((UV) ASSERT_NOT_PTR(ch))
```

I believe the above define is where the trouble starts, the U8 argument is cast to a UV.

```
#define OFFUNI_IS_INVARIANT(c)                                              \
                        (((WIDEST_UTYPE)(c)) < UTF_MIN_CONTINUATION_BYTE)
```

So the UV is then cast to WIDEST_UTYPE, which might be smaller than a UV. It is defined as:

```
#define WIDEST_UTYPE PERL_UINTMAX_T
```

I assume that you are building a 32 bit perl, and that this:

```
    typedef U32TYPE PERL_UINTMAX_T;
```

is how PERL_UINTMAX_T is defined. (I make this assumption because if it were a 64 bit perl PERL_UINTMAX_T would be U64 which is what UV should be defined to be.)

Regardless since the variable in the first place starts off as a U8, (eg a unsinged char) I dont see how this warning can be right at all.

**Comment by Leont** [comment]
Still, if that `(UV)` cast is changed to `(WIDEST_UTYPE)` this warning should go away right? Or the other way around in `OFFUNI_IS_INVARIANT`

**Comment by khwilliamson** [comment]
That macro expands to
   ` (((PERL_UINTMAX_T)(((UV) ((((byte) | 0)) | 0)))) < (((U8) (0xFF << 6)) & 0xB0))`
And yes, `(U8) (0xFF << 6)` is truncated (deliberately).  That could be replaced by
`((0xFF << UTF_ACCUMULATION_SHIFT) & 0xFF)`
If this were runtime, that would be an extra '&` that the cast avoids.  But since it is compile time, they all get folded then

**Comment by sisyphus** [comment]
FWIW, on my VS-2022 builds of perl-5.37.10, for the 32-bit (ivsize=4) build I see no compiler warnings at all.

On the 32-bit (ivsize = 8) build I get:
<code>D:\perl-5.37.10-vs\lib\MSWin32-x86-multi-thread-64int\CORE\inline.h(455): warning C4244: '=': conversion from 'const UV' to 'STRLEN', possible loss of data</code>

On the 64-bit build I get:
<code>D:\perl-5.37.10-vs\lib\MSWin32-x64-multi-thread\CORE\inline.h(2815): warning C4244: '=': conversion from '__int64' to 'I32', possible loss of data
D:\perl-5.37.10-vs\lib\MSWin32-x64-multi-thread\CORE\inline.h(2890): warning C4244: '=': conversion from '__int64' to 'I32', possible loss of data
D:\perl-5.37.10-vs\lib\MSWin32-x64-multi-thread\CORE\inline.h(2951): warning C4244: '=': conversion from '__int64' to 'I32', possible loss of data</code>

I note that the OP's build was 64-bit perl-5.32.1. Was it Strawberry Perl ?
The compilations on these VS-2022 builds of mine are done at warnings level 3 - but I don't see any C4310 warnings at all.
Perhaps I'm just not taking the correct steps to generate them.
(All I'm doing is running an Inline::C <code>printf("hello world\n")</code> script, and looking at the compilation output.)

I don't have a perl-5.32.1 that was built with a Microsoft compiler - though I'll give that a go and see if it makes any difference.
(Right at this moment, I don't have an msvc-built perl older than 5.36.0.)

If these warnings are unrelated to the issue under discussion here, then let me know and I'll file them in a new issue.

EDIT: why is it that my typos that go undetected at "Preview" time become glaringly obvious after I hit the "Comment" button ?

<b>UPDATE:</b> I see essentially the same behaviour with perl-5.32.1.
Again, there are no warnings with 32-bit perl-5.32.1 (ivsize=4).

With 32-bit perl-5.32.1 (ivsize=8) I see:
<code>D:\perl-5.32.1-vs\lib\MSWin32-x86-multi-thread-64int\CORE\inline.h(338): warning C4244: '=': conversion from 'const UV' to 'STRLEN', possible loss of data</code>

With 64-bit perl-5.32.1 I see:
<code>D:\perl-5.32.1-vs\lib\MSWin32-x64-multi-thread\CORE\inline.h(2165): warning C4244: '=': conversion from '__int64' to 'I32', possible loss of data
D:\perl-5.32.1-vs\lib\MSWin32-x64-multi-thread\CORE\inline.h(2240): warning C4244: '=': conversion from '__int64' to 'I32', possible loss of data
D:\perl-5.32.1-vs\lib\MSWin32-x64-multi-thread\CORE\inline.h(2284): warning C4244: '=': conversion from '__int64' to 'I32', possible loss of data</code>

Cheers,
Rob

**Comment by tonycoz** [comment]
> The inline.h file reports warning C4310

Do you have a minimal .cpp file that illustrates this? (I assume C++ since you're building an MFC app)

Which version of MSVC are you using here?

Are you building based on strawberry perl or did you build perl with MSVC?

Edit: Also, did the compiler provide any further information on the warning?  What level of warnings did you build the project with?

**Comment by sisyphus** [comment]
> What level of warnings did you build the project with?

Heh ... @mubinskt linked to an explanatory MS doc webpage that included <code>warning-level-3</code> in its title.
I got suckered into thinking that it was therefore a warning that got triggered at level <code>-W3</code>, but it actually doesn't get triggered until level <code>-W4</code>.

When I override <code>ccflags</code> from <code>-W3</code> to <code>-W4</code>, I then see the C4310 warnings on my 64-bit (VS-2022) build of perl-5.32.1:
```
D:\pscrpt\inline>perl try.pl
validate Stage

   Any header files specified relative to
   D:/pscrpt/inline
   will be included only if no file of the same relative path and
   name is found elsewhere in the search locations (including those
   specified in $ENV{INCLUDE}).
   Otherwise, that header file "found elsewhere" will be included.
   at D:/perl-5.32.1-vs/site/lib/Inline/C.pm line 59.
Starting Build Preprocess Stage
get_maps Stage
Finished Build Preprocess Stage

Starting Build Parse Stage
Finished Build Parse Stage

Starting Build Glue 1 Stage
Finished Build Glue 1 Stage

Starting Build Glue 2 Stage
Finished Build Glue 2 Stage

Starting Build Glue 3 Stage
Finished Build Glue 3 Stage

Starting Build Compile Stage
  Starting "perl Makefile.PL" Stage
Generating a nmake-style Makefile
Writing Makefile for try_pl_2f285
Writing MYMETA.yml and MYMETA.json
  Finished "perl Makefile.PL" Stage

  Starting "make" Stage

Microsoft (R) Program Maintenance Utility Version 14.33.31630.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Running Mkbootstrap for try_pl_2f285 ()
        "D:\perl-5.32.1-vs\bin\MSWin32-x64-multi-thread\perl.exe" -MExtUtils::Command -e chmod -- 644 "try_pl_2f285.bs"
        "D:\perl-5.32.1-vs\bin\MSWin32-x64-multi-thread\perl.exe" -MExtUtils::Command::MM -e cp_nonempty -- try_pl_2f285.bs blib\arch\auto\try_pl_2f285\try_pl_2f285.bs 644
        "D:\perl-5.32.1-vs\bin\MSWin32-x64-multi-thread\perl.exe" "D:\perl-5.32.1-vs\lib\ExtUtils\xsubpp"  -typemap "D:\perl-5.32.1-vs\lib\ExtUtils\typemap"  try_pl_2f285.xs > try_pl_2f285.xsc
        "D:\perl-5.32.1-vs\bin\MSWin32-x64-multi-thread\perl.exe" -MExtUtils::Command -e mv -- try_pl_2f285.xsc try_pl_2f285.c
        cl -c    -nologo -GF -W3 -MD -DWIN32 -D_CONSOLE -DNO_STRICT -DWIN64 -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -D_WINSOCK_DEPRECATED_NO_WARNINGS  -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -W4 -O1 -Zi -GL -fp:precise    -DVERSION=\"0.00\"  -DXS_VERSION=\"0.00\"  "-ID:\perl-5.32.1-vs\lib\MSWin32-x64-multi-thread\CORE"   -Fdtry_pl_2f285.pdb try_pl_2f285.c
cl : Command line warning D9025 : overriding '/W3' with '/W4'
try_pl_2f285.c
D:\perl-5.32.1-vs\lib\MSWin32-x64-multi-thread\CORE\win32.h(320): warning C4201: nonstandard extension used: nameless struct/union
D:\perl-5.32.1-vs\lib\MSWin32-x64-multi-thread\CORE\cop.h(34): warning C4324: 'jmpenv': structure was padded due to alignment specifier
D:\perl-5.32.1-vs\lib\MSWin32-x64-multi-thread\CORE\inline.h(309): warning C4310: cast truncates constant value
D:\perl-5.32.1-vs\lib\MSWin32-x64-multi-thread\CORE\inline.h(312): warning C4310: cast truncates constant value
D:\perl-5.32.1-vs\lib\MSWin32-x64-multi-thread\CORE\inline.h(313): warning C4310: cast truncates constant value
D:\perl-5.32.1-vs\lib\MSWin32-x64-multi-thread\CORE\inline.h(460): warning C4310: cast truncates constant value
D:\perl-5.32.1-vs\lib\MSWin32-x64-multi-thread\CORE\inline.h(505): warning C4310: cast truncates constant value
D:\perl-5.32.1-vs\lib\MSWin32-x64-multi-thread\CORE\inline.h(925): warning C4310: cast truncates constant value
D:\perl-5.32.1-vs\lib\MSWin32-x64-multi-thread\CORE\inline.h(1447): warning C4310: cast truncates constant value
D:\perl-5.32.1-vs\lib\MSWin32-x64-multi-thread\CORE\inline.h(1515): warning C4310: cast truncates constant value
D:\perl-5.32.1-vs\lib\MSWin32-x64-multi-thread\CORE\inline.h(1600): warning C4310: cast truncates constant value
D:\perl-5.32.1-vs\lib\MSWin32-x64-multi-thread\CORE\inline.h(2165): warning C4244: '=': conversion from '__int64' to 'I32', possible loss of data
D:\perl-5.32.1-vs\lib\MSWin32-x64-multi-thread\CORE\inline.h(2240): warning C4244: '=': conversion from '__int64' to 'I32', possible loss of data
D:\perl-5.32.1-vs\lib\MSWin32-x64-multi-thread\CORE\inline.h(2284): warning C4244: '=': conversion from '__int64' to 'I32', possible loss of data
try_pl_2f285.c(168): warning C4100: 'my_perl': unreferenced formal parameter
try_pl_2f285.c(199): warning C4100: 'my_perl': unreferenced formal parameter
        "D:\perl-5.32.1-vs\bin\MSWin32-x64-multi-thread\perl.exe" -MExtUtils::Mksymlists  -e "Mksymlists('NAME'=>\"try_pl_2f285\", 'DLBASE' => 'try_pl_2f285', 'DL_FUNCS' => {  }, 'FUNCLIST' => [], 'IMPORTS' => {  }, 'DL_VARS' => []);"
        link -out:blib\arch\auto\try_pl_2f285\try_pl_2f285.dll -dll -nologo -nodefaultlib -debug -opt:ref,icf -ltcg  -libpath:"D:\perl-5.32.1-vs\lib\MSWin32-x64-multi-thread\CORE"  -machine:AMD64 -subsystem:console,"5.02" try_pl_2f285.obj   "D:\perl-5.32.1-vs\lib\MSWin32-x64-multi-thread\CORE\perl532.lib" oldnames.lib kernel32.lib user32.lib gdi32.lib winspool.lib  comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib  netapi32.lib uuid.lib ws2_32.lib mpr.lib winmm.lib  version.lib odbc32.lib odbccp32.lib comctl32.lib msvcrt.lib vcruntime.lib ucrt.lib -def:try_pl_2f285.def
   Creating library blib\arch\auto\try_pl_2f285\try_pl_2f285.lib and object blib\arch\auto\try_pl_2f285\try_pl_2f285.exp
Generating code
D:\pscrpt\inline\_Inline\build\try_pl_2f285\try_pl_2f285.c(190) : warning C4702: unreachable code
Finished generating code
        if exist blib\arch\auto\try_pl_2f285\try_pl_2f285.dll.manifest mt -nologo -manifest blib\arch\auto\try_pl_2f285\try_pl_2f285.dll.manifest -outputresource:blib\arch\auto\try_pl_2f285\try_pl_2f285.dll;2
        if exist blib\arch\auto\try_pl_2f285\try_pl_2f285.dll.manifest del blib\arch\auto\try_pl_2f285\try_pl_2f285.dll.manifest
        "D:\perl-5.32.1-vs\bin\MSWin32-x64-multi-thread\perl.exe" -MExtUtils::Command -e chmod -- 755 blib\arch\auto\try_pl_2f285\try_pl_2f285.dll
  Finished "make" Stage

  Starting "make install" Stage

Microsoft (R) Program Maintenance Utility Version 14.33.31630.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        "D:\perl-5.32.1-vs\bin\MSWin32-x64-multi-thread\perl.exe" -MExtUtils::Command::MM -e cp_nonempty -- try_pl_2f285.bs blib\arch\auto\try_pl_2f285\try_pl_2f285.bs 644
Files found in blib\arch: installing files in blib\lib into architecture dependent library tree
Installing D:\pscrpt\inline\_Inline\lib\auto\try_pl_2f285\try_pl_2f285.dll
Installing D:\pscrpt\inline\_Inline\lib\auto\try_pl_2f285\try_pl_2f285.exp
Installing D:\pscrpt\inline\_Inline\lib\auto\try_pl_2f285\try_pl_2f285.lib
Installing D:\pscrpt\inline\_Inline\lib\auto\try_pl_2f285\try_pl_2f285.pdb
  Finished "make install" Stage

  Starting Cleaning Up Stage
  Finished Cleaning Up Stage

Finished Build Compile Stage

Hello World
```
The script that generated the above output was:
```
use strict;
use warnings;

use Inline C => Config =>
 BUILD_NOISY => 1,
 CCFLAGSEX => '-W4',
 USING => 'ParseRegExp',
;

use Inline C => <<'EOC';

void foo(void) {
  printf("Hello World\n");
}

EOC

foo();
```
I, too, wondered whether the @mubinskt's perl was Strawberry Perl or not.
In the context of this bug report, I'm now thinking that it doesn't really matter.
Either way, I think inline.h will be the same.

Cheers,
Rob

**Comment by tonycoz** [comment]
Thanks, reproduced here with blead.

Masking the `UTF_IS_CONTINUATION_MASK` value prevents this particular warning.

The conversion warnings you mentioned are covered by #20841
