### ISSUE TITLE
[doc] Documentation for 'goto &NAME' should mention that it does not return

### ISSUE THREAD

**Issue by jeremyhetzler** [Perl/perl5#21003]
**Where**
perlfunc -f goto

**Description**
'goto &NAME' does not return. The documentation should mention this explicitly.

**Comment by khwilliamson** [comment]
How would you like it to be worded?

**Comment by mauke** [comment]
I mean, it does say "it exits the current subroutine" (and `goto` is not generally known for returning, anyway). What's a better wording?

I do think it should mention something along the lines of "explicit tail call", though.

**Comment by jeremyhetzler** [comment]
> How would you like it to be worded?

Perhaps something like this:

```
    goto LABEL
    goto EXPR
    goto &NAME

            "goto" transfers execution to a specified point in the program.
            Unlike a subroutine call, it does not return.
            
            The "goto LABEL" form finds [...]
```
