### ISSUE TITLE
maint-5.36: backport requests for Clang 16 compatibility

### ISSUE THREAD

**Issue by thesamesam** [Perl/perl5#21016]
Hi folks,

Apologies if this is the wrong venue.

Would it be possible for these two commits to be backported for Clang 16 compatibility in 5.36:
- https://github.com/Perl/perl5/commit/e1ca9a418fa6b7d26fbb1931c9164141035262c3
- https://github.com/Perl/perl5/commit/fc35cee89c1a42558f50a37a6b4d5186b77f058b

Note that it may conflict with https://github.com/Perl/perl5/commit/1a4a6dfa87902852c5b99dbf5dd7d4c7bd10f837 which was applied on blead _after_ those commits.

Both Gentoo and Fedora have backported these already and had no issues.

**Comment by Leont** [comment]
@steve-m-hay this ticket is relevant for you

**Comment by steve-m-hay** [comment]
Thanks both. I have added the commits to the voting file:

https://perl5.git.perl.org/perl5.git/commit/a258b7b2f614026c4235a189354795ff44df3e2c

If committer folks deem them to be okay then I'll make an RC3 with these commits in.

**Comment by thesamesam** [comment]
Thank you both for considering it & explaining the process!

**Comment by khwilliamson** [comment]
On 4/12/23 11:42, Steve Hay wrote:
> Thanks both. I have added the commits to the voting file:

The requisite number of votes have now been cast

**Comment by steve-m-hay** [comment]
> On 4/12/23 11:42, Steve Hay wrote: Thanks both. I have added the commits to the voting file:
> The requisite number of votes have now been cast

Thanks. These are now in 5.36. (Actually, e1ca9a418f was rendered redundant by the earlier cherry-pick of d8a109ccd8, which Sam did give us a heads-up about, but none of us quite cottoned on to ;-))
I will wait until the weekend before rolling out RC3 to give a little more time for any further issues to come to light. That will still leave another week before the currently projected release date on 23rd April.
