### ISSUE TITLE
reftype( \$tiedarray[i] ) is always 'SCALAR', not 'REF' when reference member contains a ref

### ISSUE THREAD

**Issue by jimav** [Perl/perl5#21075]
If a reference is taken to a member of a tied array, the reftype() of the reference is initially 'SCALAR' even if the referenced datum is itself a ref (in that case the reftype should be 'REF' not 'SCALAR').    **After that particular reference is de-referenced, then it's reftype() becomes correct.**

Empirically, I'm guessing that a reference to data inside a tied thing is a magic intermediary which will FETCH the datum if and when the ref is de-referenced, but which does not FETCH the datum when the reference is first created.

This bug could be fixed by FETCHing the datum whenever such a reference is created, but that would impose a performance penalty.   So it might be better to just clearly document that references to members of tied things may have an incorrect reftype().

I don't know whether it is better to fix the bug or document the behaviour.  

```
#!/usr/bin/env perl
use strict; use warnings; use feature 'say';

package MyTie;
use Tie::Array;
our @ISA = ('Tie::StdArray');

package main;
use Scalar::Util qw/reftype/;

tie my @a, 'MyTie' or die;
@a = (100, {}, 900);

my $r = \$a[1];
say "reftype = ", reftype($r);
say "Value is ", $$r;
say "reftype = ", reftype($r);
```
RESULTS:
```
reftype = SCALAR
Value is HASH(0x555555920558)
reftype = REF
```

perl 5, version 37, subversion 10 (v5.37.10) built for x86_64-linux

**Comment by Leont** [comment]
I'm not sure I'd classify this as a bug, I think it's more like surprising behavior. I certainly don't think doing an early `FETCH` is the right solution.

**Comment by demerphq** [comment]
> I'm not sure I'd classify this as a bug

Agreed. It is not clear why we distinguish between REF And SCALAR anyway, if anything the bug is that we do that at all, and it is far far too late to do anything about it anyway.

**Comment by jkeenan** [comment]
> > I'm not sure I'd classify this as a bug
> 
> Agreed. It is not clear why we distinguish between REF And SCALAR anyway, if anything the bug is that we do that at all, and it is far far too late to do anything about it anyway.

The discussion in this ticket suggests "Not A Bug."  I'm taking the ticket for the purpose of closing it in 7 days unless there is serious objection.
