### ISSUE TITLE
[doc] `perldoc locale` does not mention `:{not_,}characters

### ISSUE THREAD

**Issue by hvds** [Perl/perl5#21097]
`perldoc -f lc` mentions that `use locale ':not_characters'` affects the behaviour of `lc()`; however `perldoc locale` has no mention of this import tag.

In the `locale.pm` source I see that it is actually built up from a `:characters` tag and a generic `not_` prefix, but neither of these is mentioned in the docs either.

**Comment by khwilliamson** [comment]
locale.pm contains stub information about locales.  This page is what you get when you say `perldoc locale`.  It includes this line though 

> See perllocale for more detailed information on how Perl supports
locales.
 
If you said instead `perldoc perllocale` you would find the information you're seeking.

I've never understood why there are two pages

**Comment by hvds** [comment]
Hmm ok. I actually just skimmed the doc looking for mention of `not_characters`, but had I noticed that line it wouldn't have occurred to me that it would be relevant to my question - I wasn't looking for information on how Perl supports locales, just on the interface of the `locale` module.

There seems to be a deficiency here, but I'm open to the idea that it isn't the one I thought I had identified.

It would make sense to me, for example, if the *only* content of the `locale` manpage were "See perllocale". But as long as that is not the case, it feels like the full interface of the module should be described here.

**Comment by khwilliamson** [comment]
On 5/15/23 18:25, Hugo van der Sanden wrote:
> Hmm ok. I actually just skimmed the doc looking for mention of 
> |not_characters|, but had I noticed that line it wouldn't have occurred 
> to me that it would be relevant to my question - I wasn't looking for 
> information on how Perl supports locales, just on the interface of the 
> |locale| module.
> 
> There seems to be a deficiency here, but I'm open to the idea that it 
> isn't the one I thought I had identified.
> 
> It would make sense to me, for example, if the /only/ content of the 
> |locale| manpage were "See perllocale". But as long as that is not the 
> case, it feels like the full interface of the module should be described 
> here.
> 

I'm persuaded.
