### ISSUE TITLE
configure script is incorrectly checking for clang

### ISSUE THREAD

**Issue by ismell** [Perl/perl5#21099]
https://github.com/Perl/perl5/blob/1515f807817872eac26fdb0ff7469e2b71ebc6b5/hints/linux.sh#L169

The configure script runs the following code:
```
# Ubuntu 11.04 (and later, presumably) doesn't keep most libraries
# (such as -lm) in /lib or /usr/lib.  So we have to ask gcc to tell us
# where to look.  We don't want gcc's own libraries, however, so we
# filter those out.
# This could be conditional on Unbuntu, but other distributions may
# follow suit, and this scheme seems to work even on rather old gcc's.
# This unconditionally uses gcc because even if the user is using another
# compiler, we still need to find the math library and friends, and I don't
# know how other compilers will cope with that situation.
# Morever, if the user has their own gcc earlier in $PATH than the system gcc,
# we don't want its libraries. So we try to prefer the system gcc
# Still, as an escape hatch, allow Configure command line overrides to
# plibpth to bypass this check.
if [ -x /usr/bin/gcc ] ; then
    gcc=/usr/bin/gcc
# clang also provides -print-search-dirs
elif ${cc:-cc} --version 2>/dev/null | grep -q '^clang ' ; then
    gcc=${cc:-cc}
else
    gcc=gcc
fi
```

When running on a system that only has clang, and not gcc. i.e., `cc=x86_64-pc-linux-gnu-clang`, we hit the `elif` branch. The grep command is a bit too strict when determining if the compiler is clang.

```
$ clang --version
Debian clang version 14.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
```
# x86_64-pc-linux-gnu-clang --version
Chromium OS 17.0_pre496208_p20230501-r1 clang version 17.0.0 (/mnt/host/source/src/third_party/llvm-project 98f5a340975bc00197c57e39eb4ca26e2da0e8a2)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

It looks like 'clang' doesn't appear at the beginning of the line like expected, but in the middle. Changing the check to `grep -q '\bclang\b'` for me works as expected.

**Comment by jkeenan** [comment]
> if [ -x /usr/bin/gcc ] ; then
>     gcc=/usr/bin/gcc
> \# clang also provides -print-search-dirs
> elif ${cc:-cc} --version 2>/dev/null | grep -q '^clang ' ; then
>     gcc=${cc:-cc}
> else
>     gcc=gcc
> fi
> ```
> 
> When running on a system that only has clang, and not gcc. i.e., `cc=x86_64-pc-linux-gnu-clang`, we hit the `elif` branch. The grep command is a bit too strict when determining if the compiler is clang.
> 
> ```
> $ clang --version
> Debian clang version 14.0.6
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /usr/bin
> ```
> 
> ```
> \# x86_64-pc-linux-gnu-clang --version
> Chromium OS 17.0_pre496208_p20230501-r1 clang version 17.0.0 (/mnt/host/source/src/third_party/llvm-project 98f5a340975bc00197c57e39eb4ca26e2da0e8a2)
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /usr/bin
> ```
> 
> It looks like 'clang' doesn't appear at the beginning of the line like expected, but in the middle. Changing the check to `grep -q '\bclang\b'` for me works as expected.

This complaint looks plausible, but I don't have a `gcc`-less Linux system on which to test it.

@Tux, any thoughts?

**Comment by Tux** [comment]
I have thoughts already :)

This will work on your system, but *not* on systems with old grep that is still supported, as `\b` is unsupported on those

```
$ echo "clang version 16.0.3" | /usr/bin/grep '^clang '
clang version 16.0.3
$ echo "clang version 16.0.3" | /usr/bin/grep '\bclang\b'
Exit 1
$ echo "clang version 16.0.3" | /usr/bin/grep 'clang version'
clang version 16.0.3
```
I think the only correct solution is to change `^clang` to something like

`grep -e '^clang version' -e ' clang version'`

or make it a `case` instead of an `if`

```
$ echo "babonix clang version 16.0.3" | /usr/bin/grep -e '^clang version' -e ' clang version'
babonix clang version 16.0.3
$ echo "clang version 16.0.3" | /usr/bin/grep -e '^clang version' -e ' clang version'
clang version 16.0.3
```

**Comment by ismell** [comment]
I wasn't sure when `\b` was implemented in `grep`. I think having two expressions is a good way to go.
