### ISSUE TITLE
t/rebigfuzzy.t, t/re/pat_psycho.t fail during ASAN build

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#21106]
Today, in the course of verifying https://github.com/Perl/perl5/pull/21104 (now merged), I had to occasion to configure blead with these switches:
```
$ sh ./Configure -des -Dusedevel -Dcc=clang -Accflags="-g -fno-omit-frame-pointer -fsanitize=address  -fno-common -fsanitize-blacklist=`pwd`/asan_ignore" -Aldflags="-fsanitize=address"

$ uname -mrs; git describe
Linux 5.19.0-41-generic x86_64
v5.37.11-54-g5a3ae03cdc
```
After confirming that one test in `t/lib/croak/class` would be skipped as intended, I then went on to run the full test harness.  I got two test failures, described below.  When I ran each of these tests individually via the harness, however, each of these two test files passed.

Since I rarely attempt "ASAN builds" I don't know how significant these results are.  Should I feel relieved that the test files passed when run individually, but not as part of a full `make test_harness`?

**Two failing test files during full harness**
```
t/re/bigfuzzy_not_utf8.t

===(  152034;97     0/1473  43/44  0/?  1/1  29/?  56/?  15/?   ... )===# Failed test 1 - [perl \#134329] at re/bigfuzzy_not_utf8.t line 37
#      got "Killed"
# expected ""
# PROG: 
# qr/((8|||�@P�׸||(G|||,d^Z)*(8|||ccccc����GW2G2=@GG|G���@P���||G�^Z�!G)*׸||��W2G�i+��@׸a׸|!G)*(G����?2G�i+��@�|,W��@GG|�|�|,h@^@GG||||||||||||||||||||||||| and many more lines
...
|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||�|�|,h!@i+|,����W2G�i+�@^Z�|�|,d^Z)*(�||G��n����^)*(G|||,d^Z)*(8|||ccccccccGG���@P���||G�^Z�!G)*׸||��W2G�i+��@׸a׸|!G)*(G����?2G�i+��@�|,W��@GG|�|�|,h@^@GG|�|�|,h!@i+|,����W2G�i+�@^Z�!G)*(G����W2G�i@i+|,����W2G�i+�@@׸a׸|||,���i5|,�||!�G)*+�)*n?G�p���/
# STATUS: 35072
re/bigfuzzy_not_utf8.t ............................................... Failed 1/1 subtests 
```
```
re/pat_psycho.t ...................................................... # Test process timed out - terminating
re/pat_psycho.t ...................................................... Failed 15/15 subtests 
```
After this harness run, I noticed that approximately 8 tabs in 3 windows of Firefox had crashed (though Firefox as a whole did not crash).

What does this data indicate?

Thank you very much.
Jim Keenan

**Comment by demerphq** [comment]
> What does this data indicate?

FWIW, I cant replicate it with the same build options.

**Comment by hvds** [comment]
My **guess** would be that a) those two test cases (judging by the name) take an unusually large amount of memory; b) ASAN runs use much more memory than normal runs (potentially many bytes per normal byte); and so c) those tests ended up exhausting both all physical memory and all of swap to the extent it caused other processes (such as your browser tabs) to fail as well.

Based on that guess I'd say it indicates a natural limitation of ASAN for certain extreme cases in our tests on machines with limited resources, and probably not a problem in perl.

I'm not aware of a way to test ASAN's actual memory usage: if I understand correctly, it uses a huge virtual memory area all of which is unmapped until pagefaults occur, so diagnostic tools such as top simply show it always using 1TB of memory.

**Comment by jkeenan** [comment]
> My **guess** would be that a) those two test cases (judging by the name) take an unusually large amount of memory; b) ASAN runs use much more memory than normal runs (potentially many bytes per normal byte); and so c) those tests ended up exhausting both all physical memory and all of swap to the extent it caused other processes (such as your browser tabs) to fail as well.
> 
> Based on that guess I'd say it indicates a natural limitation of ASAN for certain extreme cases in our tests on machines with limited resources, and probably not a problem in perl.
> 
> I'm not aware of a way to test ASAN's actual memory usage: if I understand correctly, it uses a huge virtual memory area all of which is unmapped until pagefaults occur, so diagnostic tools such as top simply show it always using 1TB of memory.

Thanks.  I'm going to proceed on the assumption that running these tests through the harness (TEST_JOBX => 4) on an ASAN build is an inherently memory-challenging task and that, as long as I can run each of these test files *individually* without failures or crashes, I'm good.

I'll take this ticket for the purpose of closing it within 7 days, to allow time for anyone else to comment.

**Comment by jkeenan** [comment]
> > My **guess** would be that a) those two test cases (judging by the name) take an unusually large amount of memory; b) ASAN runs use much more memory than normal runs (potentially many bytes per normal byte); and so c) those tests ended up exhausting both all physical memory and all of swap to the extent it caused other processes (such as your browser tabs) to fail as well.
> > Based on that guess I'd say it indicates a natural limitation of ASAN for certain extreme cases in our tests on machines with limited resources, and probably not a problem in perl.
> > I'm not aware of a way to test ASAN's actual memory usage: if I understand correctly, it uses a huge virtual memory area all of which is unmapped until pagefaults occur, so diagnostic tools such as top simply show it always using 1TB of memory.
> 
> Thanks. I'm going to proceed on the assumption that running these tests through the harness (TEST_JOBX => 4) on an ASAN build is an inherently memory-challenging task and that, as long as I can run each of these test files _individually_ without failures or crashes, I'm good.
> 
> I'll take this ticket for the purpose of closing it within 7 days, to allow time for anyone else to comment.

No further comments; closing as per schedule.

**Comment by khwilliamson** [comment]
FWIW, I often use ASAN, and have never had a problem with running in parallel, with 64G memory.
