### ISSUE TITLE
Bit vector size > 32 non-portable

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#21119]
Please tell me how to suppress the message:  ```Bit vector size > 32 non-portable at line 4.``` in the code below?  Attempts to search for a solution online are hampered by the shortness and generic nature of the current error message.  Perhaps the error message could be given an unique identifier to assist such searches in the future?

```
#!/usr/bin/perl
use v5.30;
my $a;
vec($a, 0, 64) = 1;
# Bit vector size > 32 non-portable at line 4.
```

**Comment by haarg** [comment]
Running the script with -Mdiagnostics will show that the warning category to disable is `portable`.
