### ISSUE TITLE
[doc] perldelta v5.38.0 (Draft) nitpicks

### ISSUE THREAD

**Issue by esabol** [Perl/perl5#21115]
**Where**
[perldelta v5.38.0 (Draft)](https://github.com/Perl/perl5/blob/8db19a86dfa8408a91845da20ea7063f7646a913/pod/perldelta.pod) 

This link to the draft of perldelta for Perl 5.38.0 was posted on Reddit. I have a few nitpicks. I couldn't find the branch for this draft in order to submit a PR, so I'm just opening an issue. If you point me to the correct branch, I could submit a PR if you prefer.

**Description**
Please make the following changes:

1. Change "This remains a new and experimental feature, and is very much still under development" to "This remains a new and experimental feature, and it is very much still under development". (Alternatively, remove the comma before "and is very".) You should only put a comma before the conjunction when combining two independent clauses. As written, the part that comes after "and" is not an independent clause since the subject is missing from that clause.
2. Very similarly, change "This has resulted in two main type of problems in downstream CPAN modules, and may also occur in your code:" to "This has resulted in two main **types** of problems in downstream CPAN modules, and **these problems** may also occur in your code:". Note that "type" should be plural.
3. Change "If your code encounters and error on the stream while reading" to "If your code encounters **an** error on the stream while reading". Typo!

**Bold** indicates inserted or modified words in my changes (for clarity), and this bold styling should not be included when making the changes.

**Comment by rwp0** [comment]
@rjbs FYI

**Comment by rjbs** [comment]
Thanks.  I have applied the second change.  The third was already applied.  The first, I decline to apply, as I find the text as it stands just fine as idiomatic English writing.
