### ISSUE TITLE
Digest::MD5 segfaults when calling a method with the bareword Digest::MD5

### ISSUE THREAD

**Issue by florian-pe** [Perl/perl5#21126]
Those examples reproduce the segmentation fault:
```
perl -MDigest::MD5 -E 'Digest::MD5->add("")'
perl -MDigest::MD5 -E 'Digest::MD5::add(Digest::MD5)'
perl -MDigest::MD5 -E 'Digest::MD5::addfile(Digest::MD5, ARGV)'
```
whereas this is code produce the expected error:
```
perl -MDigest::MD5 -E 'Digest::MD5::add("abc")'
Not a reference to a Digest::MD5 object at -e line 2.

$ perl -MDigest::MD5 -E 'Digest::MD5::add( Digest::MD )'
Not a reference to a Digest::MD5 object at -e line 2.
```

This segmentation fault is almost certainly due to an incomplete "type check" in this function:
https://github.com/Perl/perl5/blob/blead/cpan/Digest-MD5/MD5.xs#L455
```
static MD5_CTX* get_md5_ctx(pTHX_ SV* sv)
{
    MAGIC *mg;

    if (!sv_derived_from(sv, "Digest::MD5"))
	croak("Not a reference to a Digest::MD5 object");

    for (mg = SvMAGIC(SvRV(sv)); mg; mg = mg->mg_moremagic) {
	if (mg->mg_type == PERL_MAGIC_ext
	    && mg->mg_virtual == (const MGVTBL * const)&vtbl_md5) {
	    return (MD5_CTX *)mg->mg_ptr;
	}
    }

    croak("Failed to get MD5_CTX pointer");
    return (MD5_CTX*)0; /* some compilers insist on a return value */
}
```

**Comment by Leont** [comment]
> This segmentation fault is almost certainly due to an incomplete "type check" in this function:

Indeed. Calling `SvRV` without checking `SvROK` is wrong, and as is calling `SvMAGIC` without checking if it is `SVtPVMG`/`SvMAGICAL`.

This should be reported [upstream](https://github.com/Dual-Life/digest-md5/issues) though instead of here.

**Comment by florian-pe** [comment]
>This should be reported upstream though instead of here.

Alright, it did seem that this issue was out of place.
