### ISSUE TITLE
[doc] perl5370delta is missing (actually want rationale for removing switch constructs)

### ISSUE THREAD

**Issue by jimav** [Perl/perl5#21141]
The 5.37.1 perldelta.pod at https://metacpan.org/release/WOLFSAGE/perl-5.37.1/view/pod/perldelta.pod says to first read  https://metacpan.org/pod/perl5370delta but that leads to **404 File Not Found**.

I wanted to read the rationale for removing the `for ($var) { when (/regex/) {...} } ` switch construct which was previously documented as mainstream non-experimental (e.g. perl-5.14.4) and so there exists code which uses it.   Presumably that rationale is in the earlier perldelta ...

These constructs have been retroactively made experimental and I'm wondering what the core issues are which makes complete removal necessary rather than simplifying their semantics under a suitable pragma as described in perlpolicy(1).  I'm sure this has been "discussed at length" somewhere...

**Comment by Grinnz** [comment]
It will not be present in an indexed release until 5.38.0 is released. Use perldoc.perl.org for working interlinks in core perldocs. https://perldoc.perl.org/5.37.1/perldelta

**Comment by haarg** [comment]
Unfortunately the `perl5370delta.pod` file included with the perl 5.37 releases has had a broken NAME section. This interferes with how MetaCPAN tries to interlink the files.

**Comment by jkeenan** [comment]
> The 5.37.1 perldelta.pod at https://metacpan.org/release/WOLFSAGE/perl-5.37.1/view/pod/perldelta.pod says to first read https://metacpan.org/pod/perl5370delta but that leads to **404 File Not Found**.
> 
> I wanted to read the rationale for removing the `for ($var) { when (/regex/) {...} } ` switch construct which was previously documented as mainstream non-experimental (e.g. perl-5.14.4) and so there exists code which uses it. Presumably that rationale is in the earlier perldelta ...
> 
> These constructs have been retroactively made experimental and I'm wondering what the core issues are which makes complete removal necessary rather than simplifying their semantics under a suitable pragma as described in perlpolicy(1). I'm sure this has been "discussed at length" somewhere...

I believe this ticket should be closed.  As previous comments have suggested, it's almost accidental that the page you referenced on metacpan.org (which is maintained by people other than Perl 5 Porters) is still visible.  I haven't been able to locate similar pages for other development releases.  So the documentation problem would be a WONTFIX.

As to the given/when discussion, you are correct in thinking that this has been discussed at length elsewhere.  The place for such discussions is on the perl5-porters mailing list/newsgroup, so that is where I recommend you go to review such discussion.

Taking this ticket for the purpose of closing it within 7 days unless there is serious objection.

**Comment by xenu** [comment]
https://www.nntp.perl.org/group/perl.perl5.porters/2022/06/msg264087.html
https://www.nntp.perl.org/group/perl.perl5.porters/2022/12/msg265180.html

**Comment by jimav** [comment]
@xenu - thanks for the links, they explain clearly.   I would not readily know how to find them myself from the mailing list.

I suggest including these links in the release notes if there is another 5.37.x release.

**Comment by jkeenan** [comment]
> [snip] 
> Taking this ticket for the purpose of closing it within 7 days unless there is serious objection.

Although there was further discussion in this ticket, there was no objection to closing it.  Doing so now.
