### ISSUE TITLE
field syntax sometimes provokes "subroutine attributes must come before the signature" error

### ISSUE THREAD

**Issue by leonerd** [Perl/perl5#21158]
This is fine:

```
$ perl5.38.0-RC1 -Mv5.38 -Mexperimental=class -c
class Bar {
  field $x :param;
}
- syntax OK
```

This too:

```
$ perl5.38.0-RC1 -Mv5.38 -Mexperimental=class -c
{ sub foo($x,$y) { } }

class Bar {
  field $x :param;
}
- syntax OK
```

However, without the block wrapping:

```
$ perl5.38.0-RC1 -Mv5.38 -Mexperimental=class -c
sub foo($x,$y) { }

class Bar {
  field $x :param;
Subroutine attributes must come before the signature at - line 4.
```

**Comment by ilmari** [comment]
This does not require the `class` feature at all, just a non-`sub` item with an attribute after a signature was parsed:

```
$ perl -E 'sub foo ($x) { my $bar :baz; }'
Subroutine attributes must come before the signature at -e line 1.
$ perl -E 'sub foo ($x) { } my $bar :baz;'
Subroutine attributes must come before the signature at -e line 1.
```

`PL_parser->sig_seen` needs to be cleared as soon as the opening curly brace of the signatured sub body is seen.

**Comment by Ovid** [comment]
@leonerd Maybe change the name of the ticket? Per @ilmari's comment, it looks like the `class` syntax isn't at fault here. However, someone else on Facebook was bitten by this today when using `class` and the `class` attributes makes it easier for this to crop up.

**Comment by blues1875** [comment]
I am the person Ovid is referring to. I came across this while converting some old Moo code using the class feature. Even if not directly related to the class feature, I have a feeling that more people will hit it as they experiment with the new feature.
