### ISSUE TITLE
BBC 5.37.x breaks B::Hooks::Parser

### ISSUE THREAD

**Issue by leonerd** [Perl/perl5#21162]
E.g. 

```
Parser.xs:175:73: error: macro "scan_word" requires 6 arguments, but only 5 given
  175 |         return scan_word (base_s, dest, destlen, handle_package, res_len);
      |                                                                         ^
```
(from http://www.cpantesters.org/cpan/report/62c5a506-04c9-11ee-8cc4-947bc154cd3f)

Seems like it is using an internal API function, whose signature was changed recently.

**Comment by jkeenan** [comment]
> E.g.
> 
> ```
> Parser.xs:175:73: error: macro "scan_word" requires 6 arguments, but only 5 given
>   175 |         return scan_word (base_s, dest, destlen, handle_package, res_len);
>       |                                                                         ^
> ```
> 
> (from http://www.cpantesters.org/cpan/report/62c5a506-04c9-11ee-8cc4-947bc154cd3f)
> 
> Seems like it is using an internal API function, whose signature was changed recently.

This breakage was reported upstream three weeks ago at [RT 148418](https://rt.cpan.org/Ticket/Display.html?id=148418).

The code in this module is apparently very sensitive to changes in the core distribution.  Previous breakage in B::Hooks::Parser was reported (and resolved) in https://github.com/Perl/perl5/issues/16603 (2019), https://github.com/Perl/perl5/issues/15440 (2016), https://github.com/Perl/perl5/issues/12364 (2012).

Am currently bisecting to try to identify the breaking commit.

@karenetheridge  @zefram

**Comment by jkeenan** [comment]
> E.g.
> 
> ```
> Parser.xs:175:73: error: macro "scan_word" requires 6 arguments, but only 5 given
>   175 |         return scan_word (base_s, dest, destlen, handle_package, res_len);
>       |                                                                         ^
> ```
> 
> (from http://www.cpantesters.org/cpan/report/62c5a506-04c9-11ee-8cc4-947bc154cd3f)
> 
> Seems like it is using an internal API function, whose signature was changed recently.

Bisection points to 7e2d91e6d3a09e2ebb61242bb18ff95d30d9560d.
```
commit 7e2d91e6d3a09e2ebb61242bb18ff95d30d9560d (HEAD, refs/bisect/bad)
Author:     Tony Cook <tony@develop-help.com>
AuthorDate: Wed Dec 7 16:17:45 2022 +1100
Commit:     Tony Cook <tony@develop-help.com>
CommitDate: Tue Feb 7 10:37:30 2023 +1100

    toke.c: deprecation warning for ' as a package separator
    
    First stage of RFC 0015.
    
    This also changes the warning for ' as package separator in
    quoted strings to also be a deprecation warning.
```
@tonycoz, can you take a look?
