### ISSUE TITLE
Perlmod says "Perl has no special class syntax"

### ISSUE THREAD

**Issue by castaway** [Perl/perl5#21188]
https://github.com/Perl/perl5/blob/149c2e48b61bd93a9e4ee06b920ca68dd97b717c/pod/perlmod.pod?plain=1#L429

This probably needs amending with the inclusion of the new "class" keyword.

**Comment by leonerd** [comment]
Mmm. There's no *stable* class syntax, but there is a new experimental one. Perhaps it should be reworded to talk about that in that context.

**Comment by rwp0** [comment]
> Mmm. There's no *stable* class syntax, but there is a new experimental one. Perhaps it should be reworded to talk about that in that context.

Haha, I was also thinking appending _stable_ in front of it (to distinguish from experimental).

**Comment by castaway** [comment]
" No stable" and a link to the perlclass doc?

**Comment by jkeenan** [comment]
> " No stable" and a link to the perlclass doc?

@castaway and @leonerd, could you put your heads together and propose a pull request for this.  It doesn't have to be perfect, merely something we could refine over the current dev cycle.  Thanks.

**Comment by bmeneg** [comment]
I'm willing to start contributing to Perl and would like to take on this issue to start getting used to its source tree.
May I create the PR for getting this doc fixed?

**Comment by xenu** [comment]
Sure, go ahead, it's been almost two months and nobody else has got around to it.

**Comment by castaway** [comment]
I kept forgetting, help yourself!
