### ISSUE TITLE
dist/ExtUtils-ParseXS/t/002-more.t failing on Win32 (mingw64)

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#21202]
GH Actions tests on "Windows mingw64" are failing on multiple pull requests on different branches.  See, *e.g.,*

https://github.com/Perl/perl5/actions/runs/5447805747/jobs/9910433855?pr=21200

https://github.com/Perl/perl5/actions/runs/5448721934/jobs/9912356883?pr=21201

https://github.com/Perl/perl5/actions/runs/5447537853/jobs/9909828212?pr=21199

Sample failures:
```
...
../dist/ExtUtils-ParseXS/t/001-basic.t ............................... ok

#   Failed test 'No error message recorded, as expected'
#   at t/002-more.t line 65.
#          got: 'Can't load 'D:\a\perl5\perl5\dist\ExtUtils-ParseXS\t/XSMore.dll' for module XSMore: load_file:Invalid access to memory location at D:\a\perl5\perl5\lib/DynaLoader.pm line 206.
../dist/ExtUtils-ParseXS/t/002-more.t ................................ 
# '
Failed 26/33 subtests 
#     expected: ''

#   Failed test 'the BOOT keyword'
#   at t/002-more.t line 68.
#          got: undef
#     expected: '100'
Undefined subroutine &XSMore::include_ok called at t/002-more.t line 70.
# Looks like your test exited with 2 just after 9.
../dist/ExtUtils-ParseXS/t/003-usage.t ............................... ok
...

Test Summary Report
-------------------
../dist/ExtUtils-ParseXS/t/002-more.t                              (Wstat: 512 (exited 2) Tests: 9 Failed: 2)
  Failed tests:  7, 9
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 33 tests but ran 9.
../dist/Net-Ping/t/450_service.t                                   (Wstat: 0 Tests: 26 Failed: 0)
  TODO passed:   9
../ext/IPC-Open3/t/IPC-Open3.t                                     (Wstat: 0 Tests: 45 Failed: 0)
  TODO passed:   25
Files=2767, Tests=1128665, 1839 wallclock secs (103.00 usr +  8.31 sys = 111.31 CPU)
Result: FAIL
Finished test run at Mon Jul  3 19:19:37 2023.
gmake: *** [GNUMakefile:1840: test] Error 2
Error: Process completed with exit code 2
```
I have no access to Windows, so I can't diagnose further.

**Comment by jkeenan** [comment]
Correction: The failing file is:

dist/ExtUtils-ParseXS/t/002-more.t

**Comment by tonycoz** [comment]
It appears to be failing in the LoadLibraryExA() call when loading XSMore.dll, the name passed to LoadLibraryExA() appears to be fine (we display it just fine in the message, and debugging code before the call prints the path just fine).

We don't have a DllMain() in  and the boot_*() function isn't called so I don't see where the "Invalid access to memory location" is happening.

**Comment by tonycoz** [comment]
I tested a few commits, it succeeds up to 76298ae68a and starts failing in 2083cfe50f1095a8f93484de8314e601c4abf109.

That change doesn't include any significant code changes so I can only assume some sort of build issue.

I did notice a few instances of missing 38 -> 39 changes which is what 2083cfe50f10 is about, but I wouldn't expect this type of failure from that.

**Comment by tonycoz** [comment]
I've done some more testing, the error only happens when you link perl with symbols, for example, this succeeds:
```
gmake -j10 CCHOME=c:\strawberry-perl-5.32.1.1-64bit-portable\c test TEST_FILES=..\dist\ExtUtils-ParseXS\t\*.t OPTIMIZE="-g -Os"
```
while this fails:
```
gmake -j10 CCHOME=c:\strawberry-perl-5.32.1.1-64bit-portable\c test TEST_FILES=..\dist\ExtUtils-ParseXS\t\*.t OPTIMIZE="-g -Os" LINK_DBG=-g
```
LINK_DBG defaults to `-s` which strips the binary.

So this seems like a link bug.

If I build with the gcc included with the current in progress release of strawberry perl:
```
C:\Users\Tony\dev\perl\git\perl\win32>perl -V:gccversion
gccversion='13.1.0';
```
the problematic test passes.

I'm going to try a native mingw64 build, since that's also on the runners.
