### ISSUE TITLE
Segfault because of uninitialized data in AV

### ISSUE THREAD

**Issue by genuaboro** [Perl/perl5#21235]
**Description**
It seems that since Perl 5.34 (probably commit 399fef93 or ce9f3c9c) there is a bug in av.c:Perl_av_extend_guts() which may cause the underlying array of an AV to have uninitialized (non zeroed) data. This leads to segfaults (or possible other errors depending on the data) if the uninitialized data is accessed.

**Steps to Reproduce**
I mostly debugged this issue with OpenBSD 7.3 (since they switched in 7.3 from Perl 5.32.1 to 5.36.0), but also verified the crash in manually build Perl versions 5.34.0, 5.38.0 and blead. Additionally I reproduced it on an Ubuntu 22.04.1 system which runs perl 5.34.0.

The following code should be able to reproduce the issue (sometimes it took up to 10 tries to crash).

```perl
#!/usr/bin/perl

use strict;
use warnings;

use Data::Dumper;
use Devel::Peek;

my $x = [];
print STDERR "$x\n";
Dump $x;
#    ARRAY = 0x0
#    FILL = -1
#    MAX = -1

$x->[0] ||= [];
print STDERR "set 0\n";
Dump$x;
#    ARRAY = 0x26d4ca951a0
#    FILL = 0
#    MAX = 3

shift @$x;
print STDERR "shift 1\n";
Dump$x;
#    ARRAY = 0x26d4ca951a8 (offset=1)
#    ALLOC = 0x26d4ca951a0
#    FILL = -1
#    MAX = 2

$x->[22] = [];
print STDERR "set 22\n";
Dump$x;
#    ARRAY = 0x26d4ca84a30
#    FILL = 22
#    MAX = 25

shift @$x for 1 .. 5;
print STDERR "shift 5\n";
Dump$x;
#    ARRAY = 0x26d4ca84a58 (offset=5)
#    ALLOC = 0x26d4ca84a30
#    FILL = 17
#    MAX = 20

$x->[19] ||= [];
print STDERR "set 19\n";
Dump$x;
#    ARRAY = 0x26d4ca84a58 (offset=5)
#    ALLOC = 0x26d4ca84a30
#    FILL = 19
#    MAX = 20

print Dumper$x;
```

I found it easy to use Data::Dumper to reproduce the issue but Perl may also crash while just iterating over the array or even doing "nothing" (crash on exit in Perl_sv_clear()).
Besides segfaults I also observed errors like "Attempt to free unreferenced scalar: SV 0x563787eab3f0, Perl interpreter: 0x563787d5a2a0.".

**More observations**
I included some of the Devel::Peek output above because I used it to reproduce the issue. There seems to be a very specific code path where the data is not zeroed correctly.

I build Perl with debug output and it seems that the array gets "corrupted" when it is extended to 22/25. Inspecting the array at that time shows that while Zero() is called in Perl_av_extend_guts(), the last two elements in the array are not actually zeroed. I assume that either the logic in that code path is incorrect so the arguments to Zero() are wrong or that some of the internal data (like MAX) has to be adjusted at some point.

Let me know if I can be of any more help or if there are any issues with this report. I don't know how the internal AV data structures should work in the above case so I can't really propose a fix for this issue.

**Comment by jkeenan** [comment]
Building a threaded, debugging perl at blead ...
```
$ ./bin/perl -Ilib -v |head -2 | tail -1
This is perl 5, version 39, subversion 0 (v5.39.0-86-gaa2db5a4d4) built for x86_64-linux-thread-multi

$ ./bin/perl -Ilib -V:config_args
config_args='-des -Dusedevel -Dusethreads -Uversiononly -Dprefix=/home/jkeenan/testing/blead -Dman1dir=none -Dman3dir=none -DDEBUGGING';
```
... then running the OP's test program twice on Ubuntu Linux, the first time the program appears to complete with a warning ...
```
$ ./bin/perl -Ilib $P5P_DIR/gh-21235-segfault.pl
ARRAY(0x560c64d39580)
SV = IV(0x560c64d69a90) at 0x560c64d69aa0
  REFCNT = 1
  FLAGS = (ROK)
  RV = 0x560c64d39580
  SV = PVAV(0x560c64d3b040) at 0x560c64d39580
    REFCNT = 1
    FLAGS = ()
    ARRAY = 0x0
    FILL = -1
    MAX = -1
    FLAGS = (REAL)
set 0
SV = IV(0x560c64d69a90) at 0x560c64d69aa0
  REFCNT = 1
  FLAGS = (ROK)
  RV = 0x560c64d39580
  SV = PVAV(0x560c64d3b040) at 0x560c64d39580
    REFCNT = 1
    FLAGS = ()
    ARRAY = 0x560c64f0a8f8
    FILL = 0
    MAX = 3
    FLAGS = (REAL)
    Elt No. 0
    SV = IV(0x560c64d39588) at 0x560c64d39598
      REFCNT = 1
      FLAGS = (ROK)
      RV = 0x560c64d39760
      SV = PVAV(0x560c64d3b090) at 0x560c64d39760
        REFCNT = 1
        FLAGS = ()
        ARRAY = 0x0
        FILL = -1
        MAX = -1
        FLAGS = (REAL)
shift 1
SV = IV(0x560c64d69a90) at 0x560c64d69aa0
  REFCNT = 1
  FLAGS = (ROK)
  RV = 0x560c64d39580
  SV = PVAV(0x560c64d3b040) at 0x560c64d39580
    REFCNT = 1
    FLAGS = ()
    ARRAY = 0x560c64f0a900 (offset=1)
    ALLOC = 0x560c64f0a8f8
    FILL = -1
    MAX = 2
    FLAGS = (REAL)
set 22
SV = IV(0x560c64d69a90) at 0x560c64d69aa0
  REFCNT = 1
  FLAGS = (ROK)
  RV = 0x560c64d39580
  SV = PVAV(0x560c64d3b040) at 0x560c64d39580
    REFCNT = 1
    FLAGS = ()
    ARRAY = 0x560c64e7fc88
    FILL = 22
    MAX = 25
    FLAGS = (REAL)
    Elt No. 0
    SV = 0
    Elt No. 1
    SV = 0
    Elt No. 2
    SV = 0
    Elt No. 3
    SV = 0
shift 5
SV = IV(0x560c64d69a90) at 0x560c64d69aa0
  REFCNT = 1
  FLAGS = (ROK)
  RV = 0x560c64d39580
  SV = PVAV(0x560c64d3b040) at 0x560c64d39580
    REFCNT = 1
    FLAGS = ()
    ARRAY = 0x560c64e7fcb0 (offset=5)
    ALLOC = 0x560c64e7fc88
    FILL = 17
    MAX = 20
    FLAGS = (REAL)
    Elt No. 0
    SV = 0
    Elt No. 1
    SV = 0
    Elt No. 2
    SV = 0
    Elt No. 3
    SV = 0
set 19
SV = IV(0x560c64d69a90) at 0x560c64d69aa0
  REFCNT = 1
  FLAGS = (ROK)
  RV = 0x560c64d39580
  SV = PVAV(0x560c64d3b040) at 0x560c64d39580
    REFCNT = 1
    FLAGS = ()
    ARRAY = 0x560c64e7fcb0 (offset=5)
    ALLOC = 0x560c64e7fc88
    FILL = 19
    MAX = 20
    FLAGS = (REAL)
    Elt No. 0
    SV = 0
    Elt No. 1
    SV = 0
    Elt No. 2
    SV = 0
    Elt No. 3
    SV = 0
$VAR1 = [
          undef,
          undef,
          undef,
          undef,
          undef,
          undef,
          undef,
          undef,
          undef,
          undef,
          undef,
          undef,
          undef,
          undef,
          undef,
          undef,
          undef,
          [],
          undef,
          []
        ];
Attempt to free unreferenced scalar: SV 0x560c64d36428, Perl interpreter: 0x560c64d362a0.
```
... the second with a segfault.
```
$ ./bin/perl -Ilib $P5P_DIR/gh-21235-segfault.pl 
ARRAY(0x5640b06b9580)
SV = IV(0x5640b06e9b70) at 0x5640b06e9b80
  REFCNT = 1
  FLAGS = (ROK)
  RV = 0x5640b06b9580
  SV = PVAV(0x5640b06bb040) at 0x5640b06b9580
    REFCNT = 1
    FLAGS = ()
    ARRAY = 0x0
    FILL = -1
    MAX = -1
    FLAGS = (REAL)
set 0
SV = IV(0x5640b06e9b70) at 0x5640b06e9b80
  REFCNT = 1
  FLAGS = (ROK)
  RV = 0x5640b06b9580
  SV = PVAV(0x5640b06bb040) at 0x5640b06b9580
    REFCNT = 1
    FLAGS = ()
    ARRAY = 0x5640b088ac68
    FILL = 0
    MAX = 3
    FLAGS = (REAL)
    Elt No. 0
    SV = IV(0x5640b06b9588) at 0x5640b06b9598
      REFCNT = 1
      FLAGS = (ROK)
      RV = 0x5640b06b9760
      SV = PVAV(0x5640b06bb090) at 0x5640b06b9760
        REFCNT = 1
        FLAGS = ()
        ARRAY = 0x0
        FILL = -1
        MAX = -1
        FLAGS = (REAL)
shift 1
SV = IV(0x5640b06e9b70) at 0x5640b06e9b80
  REFCNT = 1
  FLAGS = (ROK)
  RV = 0x5640b06b9580
  SV = PVAV(0x5640b06bb040) at 0x5640b06b9580
    REFCNT = 1
    FLAGS = ()
    ARRAY = 0x5640b088ac70 (offset=1)
    ALLOC = 0x5640b088ac68
    FILL = -1
    MAX = 2
    FLAGS = (REAL)
set 22
SV = IV(0x5640b06e9b70) at 0x5640b06e9b80
  REFCNT = 1
  FLAGS = (ROK)
  RV = 0x5640b06b9580
  SV = PVAV(0x5640b06bb040) at 0x5640b06b9580
    REFCNT = 1
    FLAGS = ()
    ARRAY = 0x5640b080c4a8
    FILL = 22
    MAX = 25
    FLAGS = (REAL)
    Elt No. 0
    SV = 0
    Elt No. 1
    SV = 0
    Elt No. 2
    SV = 0
    Elt No. 3
    SV = 0
shift 5
SV = IV(0x5640b06e9b70) at 0x5640b06e9b80
  REFCNT = 1
  FLAGS = (ROK)
  RV = 0x5640b06b9580
  SV = PVAV(0x5640b06bb040) at 0x5640b06b9580
    REFCNT = 1
    FLAGS = ()
    ARRAY = 0x5640b080c4d0 (offset=5)
    ALLOC = 0x5640b080c4a8
    FILL = 17
    MAX = 20
    FLAGS = (REAL)
    Elt No. 0
    SV = 0
    Elt No. 1
    SV = 0
    Elt No. 2
    SV = 0
    Elt No. 3
    SV = 0
set 19
SV = IV(0x5640b06e9b70) at 0x5640b06e9b80
  REFCNT = 1
  FLAGS = (ROK)
  RV = 0x5640b06b9580
  SV = PVAV(0x5640b06bb040) at 0x5640b06b9580
    REFCNT = 1
    FLAGS = ()
    ARRAY = 0x5640b080c4d0 (offset=5)
    ALLOC = 0x5640b080c4a8
    FILL = 19
    MAX = 20
    FLAGS = (REAL)
    Elt No. 0
    SV = 0
    Elt No. 1
    SV = 0
    Elt No. 2
    SV = 0
    Elt No. 3
    SV = 0
Segmentation fault (core dumped)
```

**Comment by jkeenan** [comment]
> **Description** It seems that since Perl 5.34 (probably commit [399fef9](https://github.com/Perl/perl5/commit/399fef93c903aedee05a74de780b57eeeb571b32) or [ce9f3c9](https://github.com/Perl/perl5/commit/ce9f3c9c0043030e2d05cbb64bbfd4d50fc94b6b)) there is a bug in av.c:Perl_av_extend_guts() which may cause the underlying array of an AV to have uninitialized (non zeroed) data. This leads to segfaults (or possible other errors depending on the data) if the uninitialized data is accessed.
> 

@genuaboro, have you observed this on *non-debugging* builds of perl (threaded or unthreaded)?

@richardleach, the two commits the author cites were from you a couple of years back.  Could you take a look?

Thank you very much.
Jim Keenan

**Comment by richardleach** [comment]
I'll try to take a look this evening, but may not have much proper time before the weekend.

**Comment by richardleach** [comment]
Yeah, the calculation of `to_null` in `Perl_av_extend_guts` is incorrect when an AV is unshifted AND still needs resizing.

Apologies for the inconvenience this has caused.

I don't have time to work up a fix tonight, but will try to do so ASAP.

**Comment by richardleach** [comment]
The fix is probably something like this, but I haven't fully thought it through or tested it yet:
```
diff --git a/av.c b/av.c
index d9868f4407..3bbae7fb43 100644
--- a/av.c
+++ b/av.c
@@ -116,6 +116,7 @@ Perl_av_extend_guts(pTHX_ AV *av, SSize_t key, SSize_t *maxp, SV ***allocp,
 
             if (key > *maxp - 10) {
                 newmax = key + *maxp;
+                to_null = *maxp - AvFILLp(av);
                 goto resize;
             }
         } else if (*allocp) { /* a full SV* array exists */
```

**Comment by genuaboro** [comment]
> @genuaboro, have you observed this on _non-debugging_ builds of perl (threaded or unthreaded)?

I just launched several Perl builds with perlbrew and "--debug" / "--thread" build options. All variations seem to be affected. Originally I observed this in the default OpenBSD Perl which is built without debugging. I can provide "perl -V" if necessary.

> The fix is probably something like this, but I haven't fully thought it through or tested it yet:

Thanks for looking into this. I can provide additional testing on my end.

FWIW at a first glance this does seem to fix the original issue I observed and derived the sample code from. I am currently looking into several issues that came with the Perl upgrade to 5.36.0. My hope is that the other issues are related to this, but either way I will report back with more extensive tests.

**Comment by richardleach** [comment]
I think the fix above - with some additional comments - seems right and have started work on a PR. Mostly now just need to write the commit message.

**Comment by genuaboro** [comment]
FWIW the fix above runs stable here since last week. I didn't see any segfaults or other issues since.

**Comment by richardleach** [comment]
> FWIW the fix above runs stable here since last week. I didn't see any segfaults or other issues since.

Great, thanks for the feedback.
