### ISSUE TITLE
[doc] No documentation for "class" experiment

### ISSUE THREAD

**Issue by autarch** [Perl/perl5#21243]
**Where**

* https://perldoc.pl/perlexperiment
* https://perldoc.pl/experimental

**Description**

Neither of the `perlexperiment` doc nor the `experimental` pragma's docs mention the new "class" feature.

It's also not mentioned in `perlobj` or `perlootut`. And in fact `perlobj` still says that there is no special syntax for classes. See https://perldoc.pl/perlobj#An-Object-is-Simply-a-Data-Structure

**Comment by jkeenan** [comment]
> **Where**
> 
>     * https://perldoc.pl/perlexperiment
> 
>     * https://perldoc.pl/experimental
> 
> 
> **Description**
> 
> Neither of the `perlexperiment` doc nor the `experimental` pragma's docs mention the new "class" feature.
> 
> It's also not mentioned in `perlobj` or `perlootut`. And in fact `perlobj` still says that there is no special syntax for classes. See https://perldoc.pl/perlobj#An-Object-is-Simply-a-Data-Structure

@leonerd, can you speak to @autarch's documentation concerns ^^?  Thanks.
