### ISSUE TITLE
Compress-Raw-Bzip2 customizations in core distribution: removable?

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#21262]
Today while preparing to run `Porting/sync-with-cpan` to bring Compress-Raw-Bzip2's new release (version 2.205) into blead, I was notified that there are customizations in blead which presumably differ from corresponding files upstream.  From `Porting/Maintainers.pl`:
```
    'Compress::Raw::Bzip2' => {
        'DISTRIBUTION' => 'PMQS/Compress-Raw-Bzip2-2.204.tar.gz',
        'FILES'        => q[cpan/Compress-Raw-Bzip2],
        'EXCLUDED'     => [
            qr{^t/Test/},
            qr{^t/meta},
            'bzip2-src/bzip2-const.patch',
            'bzip2-src/bzip2-cpp.patch',
            'bzip2-src/bzip2-unsigned.patch',
        ],
        'CUSTOMIZED'   => [
            # https://github.com/pmqs/Compress-Raw-Bzip2/issues/11
            'Bzip2.xs',
            'lib/Compress/Raw/Bzip.pm'
        ],
    },
```
However, when I cloned @pqms's repository for this distribution on CPAN, I (a) could not find any differences between blead and upstream in `Bzip2.xs`:
```
[Compress-Raw-Bzip2] 2006 $ diff Bzip2.xs ~/gitwork/perl/cpan/Compress-Raw-Bzip2/Bzip2.xs 
[Compress-Raw-Bzip2] 2007 $ 
```
... and the only differences I found in `Bzip2.pm` were the version numbers:
```
$ diff lib/Compress/Raw/Bzip2.pm ~/gitwork/perl/cpan/Compress-Raw-Bzip2/lib/Compress/Raw/Bzip2.pm 
14c14
< $VERSION = '2.205';
---
> $VERSION = '2.204_001';
```
(@pqms: Note that the GH issue filed by @tonycoz in your repository is still open, although the p.r. he proposed has been merged.)

From this I infer that the entire `CUSTOMIZED` element in the configuration for `Compress::Raw::Bzip2` can be removed?  Is that inference correct?

@pqms; @tonycoz

Thank you very much.
Jim Keenan

**Comment by demerphq** [comment]
@jkeenan I think the customized entry can be removed.

**Comment by jkeenan** [comment]
Handled in commit 93297d40ce99d18d487e4f22a5b782728babd158; closing.  Thanks.
