### ISSUE TITLE
t/porting/authors.t fails in symlink directory

### ISSUE THREAD

**Issue by yangmingtai** [Perl/perl5#21272]
Module:

**Description**
During the construction of perl-5.38.0, there was a test case failure

**Steps to Reproduce**
```
#!/bin/sh
# Assume a git checkout is in /tmp/perl-git
mkdir build
cd build
sh /tmp/perl-git/Configure -Dmksymlinks -des
make 
make test
cd t
./perl harness -v porting/authors.t 
exit

```
![image](https://github.com/Perl/perl5/assets/17870505/c2365a18-b03c-4a49-aaf3-908f745d6bc5)

Others have the same problem
https://www.nntp.perl.org/group/perl.perl5.porters/2023/06/msg266520.html

**Comment by jkeenan** [comment]
A "first draft" p.r. for this problem is [here](https://github.com/Perl/perl5/pull/21274).

However, if the people who worked on `Porting/updateAUTHORS.p[lm]` want to provide something else, that would be okay.

**Comment by demerphq** [comment]
> want to provide something else, that would be okay.

We could also check if .git is present if we dont already, but your patch should work fine.
