### ISSUE TITLE
[doc] use v5.36, only partially enables warnings

### ISSUE THREAD

**Issue by druud** [Perl/perl5#21271]
perl5360delta says:

`Furthermore, use v5.36 will also enable warnings as if you'd written use warnings.`

but the 'once' warning is an exception:

```
perl -e'use v5.36; no strict; print $i' 
Use of uninitialized value $i in print at -e line 1.
```

vs:

```
perl -e'use v5.36; no strict; use warnings; print $i'
Name "main::i" used only once: possible typo at -e line 1.
Use of uninitialized value $i in print at -e line 1.
```

**Comment by Leont** [comment]
I don't think this is a documentation bug but a code bug.

**Comment by Leont** [comment]
I guess this is a side-effect of the optimizer, because adding almost any `use` line (other than strict?) will make the once warning reappear.

**Comment by tonycoz** [comment]
Perl_utilize() isn't setting `G_WARN_ONCE` in `PL_dowarn`, which triggers the scan for "used only once" symbols after compilation.

I expect the other module you were `use`ing was doing a `use warnings;` which would set `G_WARN_ONCE` when `warnings.pm` set `${^WARNING_BITS}`.
