### ISSUE TITLE
[doc] Fix a year for license

### ISSUE THREAD

**Issue by EugenKon** [Perl/perl5#21300]
**Where**
https://dev.perl.org/licenses/

**Description**
Nowdays is 2023. Should we fix license year?
![image](https://github.com/Perl/perl5/assets/139780495/24e76335-f639-445a-83ea-932b56b26118)

**Comment by jkeenan** [comment]
Perl 5 Porters does not control perl.org or dev.perl.org.  So this is is not the correct place to file a bug ticket for that problem.  Please see https://www.perl.org/siteinfo.html.
