### ISSUE TITLE
Possible crash with DynaLoader

### ISSUE THREAD

**Issue by GJDuck** [Perl/perl5#21317]
I am not sure if this is by design, but the `DynaLoader::dl_*()` functions do not seem validate the `libhandle` parameter.  E.g.:

```
    $ perl
    use DynaLoader;
    my $sym = DynaLoader::dl_find_symbol(0x1234567,'name');
    print $sym;
    Segmentation fault
```

It segfaults because the integer `0x1234567` is cast to `(void *)` and directly passed to `dlsym()`.

**Comment by Leont** [comment]
I'm not sure what you expect such validation to look like to be honest. A safer interface would have been nice, but given how DynaLoader works that is not necessarily easy.

**Comment by GJDuck** [comment]
Thanks, I was not sure about this, and I do not know enough about Perl.  The crash was picked up by an analysis tool, but if this is "by design" then the issue can be closed.
