### ISSUE TITLE
New locale.c warning suppresses line number information

### ISSUE THREAD

**Issue by sisyphus** [Perl/perl5#21352]
**Steps to Reproduce**
D:\>perl -MPOSIX="setlocale" -le "setlocale( LC_ALL, 'Korean_Korea.949' );"
Locale 'Korean_Korea.949' is unsupported, and may crash the interpreter.

**Expected behavior**
It's the <code>use warnings;</code> in POSIX.pm that enables the warning in this instance.
We're so used to seeing line numbers quoted in warnings enabled by the warnings pragma, that a couple of us have been slow to realize that it is, in fact, such a warning. (I'm not quite sure exactly what we thought it was .... other than a bit weird ;-)

The simple fix is to remove the <code>.\n</code> from the end of the message in the offending sub (which is located in locale.c).
The removal of the <code>\n</code> fixes the issue of course, and the full stop should also be removed for readability (IMO).
I suggest that @khw could maybe just incorporate this fix into his  excellent ongoing locale-related work as a "typo fix".

**Perl configuration**

```
D:\>perl -V
Summary of my perl5 (revision 5 version 38 subversion 0) configuration:

  Platform:
    osname=MSWin32
    osvers=10.0.22621.1848
    archname=MSWin32-x64-multi-thread-quadmath
    uname=''
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='gcc'
    ccflags =' -DWIN32 -DWIN64 -fdiagnostics-color=never -DPERL_TEXTMODE_SCRIPTS -DMULTIPLICITY -DPERL_IMPLICIT_SYS -DUSE_PERLIO -D__USE_MINGW_ANSI_STDIO -fwrapv -fno-strict-aliasing -mms-bitfields'
    optimize='-Os'
    cppflags='-DWIN32'
    ccversion=''
    gccversion='13.1.0'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long long'
    ivsize=8
    nvtype='__float128'
    nvsize=16
    Off_t='long long'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags ='-s -L"C:\perl-5.38.0-1310-mcf\lib\MSWin32-x64-multi-thread-quadmath\CORE" -L"C:\winlibs-gcc-1310\mingw64\lib" -L"C:\winlibs-gcc-1310\mingw64\x86_64-w64-mingw32\lib" -L"C:\winlibs-gcc-1310\mingw64\lib\gcc\x86_64-w64-mingw32\13.1.0"'
    libpth=C:\winlibs-gcc-1310\mingw64\lib C:\winlibs-gcc-1310\mingw64\x86_64-w64-mingw32\lib C:\winlibs-gcc-1310\mingw64\lib\gcc\x86_64-w64-mingw32\13.1.0 D:\_64\msys_1310\1.0\local\lib
    libs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32 -lquadmath
    perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32 -lquadmath
    libc=
    so=dll
    useshrplib=true
    libperl=libperl538.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-shared -s -L"C:\perl-5.38.0-1310-mcf\lib\MSWin32-x64-multi-thread-quadmath\CORE" -L"C:\winlibs-gcc-1310\mingw64\lib" -L"C:\winlibs-gcc-1310\mingw64\x86_64-w64-mingw32\lib" -L"C:\winlibs-gcc-1310\mingw64\lib\gcc\x86_64-w64-mingw32\13.1.0"'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_LONG_DOUBLE
    HAS_STRTOLD
    HAS_TIMES
    HAVE_INTERP_INTERN
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_HASH_FUNC_SIPHASH13
    PERL_HASH_USE_SBOX32
    PERL_IMPLICIT_SYS
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    PERL_USE_SAFE_PUTENV
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_QUADMATH
  Built under MSWin32
  Compiled at Jul  3 2023 11:50:02
  @INC:
    C:/perl-5.38.0-1310-mcf/site/lib/MSWin32-x64-multi-thread-quadmath
    C:/perl-5.38.0-1310-mcf/site/lib
    C:/perl-5.38.0-1310-mcf/lib/MSWin32-x64-multi-thread-quadmath
    C:/perl-5.38.0-1310-mcf/lib
```
Cheers,
Rob

**Comment by jkeenan** [comment]
> **Steps to Reproduce** D:>perl -MPOSIX="setlocale" -le "setlocale( LC_ALL, 'Korean_Korea.949' );" Locale 'Korean_Korea.949' is unsupported, and may crash the interpreter.
> 

@sisyphus I'm not getting this with perl-5.38.0 on either Linux or FreeBSD.
```
$ uname -mrs
FreeBSD 13.2-RELEASE-p1 amd64

$ ./bin/perl -Ilib -v | head -2 | tail -1
This is perl 5, version 38, subversion 0 (v5.38.0) built for amd64-freebsd-thread-multi

$ ./bin/perl -Ilib -MPOSIX="setlocale" -le "setlocale( LC_ALL, 'Korean_Korea.949' );"
```
Could this be a Windows-specific problem?

**Comment by khwilliamson** [comment]
On 8/9/23 13:54, James E Keenan wrote:
>     *Steps to Reproduce* D:>perl -MPOSIX="setlocale" -le "setlocale(
>     LC_ALL, 'Korean_Korea.949' );" Locale 'Korean_Korea.949' is
>     unsupported, and may crash the interpreter.
> 
> @sisyphus <https://github.com/sisyphus> I'm not getting this with 
> perl-5.38.0 on either Linux or FreeBSD.
> 
> |$ uname -mrs FreeBSD 13.2-RELEASE-p1 amd64 $ ./bin/perl -Ilib -v | head 
> -2 | tail -1 This is perl 5, version 38, subversion 0 (v5.38.0) built 
> for amd64-freebsd-thread-multi $ ./bin/perl -Ilib -MPOSIX="setlocale" 
> -le "setlocale( LC_ALL, 'Korean_Korea.949' );" |
> 
> Could this be a Windows-specific problem?

That locale is only on certain platforms; likely to be confined to 
Windows.  On your BSD box, the setlocale failed, returning undef, since 
the locale doesn't exist.  On Windows, the setlocale succeeded, but the 
locale has some characteristics that perl can't handle, so the warning 
is generated.
