### ISSUE TITLE
Test-Harness-2.46: test failures under Porting/sync-with-cpan

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#21368]
Today, in anticipation of a perl-5.39.2 release on August 20 (release manager TBD), I attempted to sync Test-Harness-2.46 into blead:
```
perl Porting/sync-with-cpan Test::Harness
```
I had first gone to http://fast-matrix.cpantesters.org/?dist=Test-Harness and observed that the latest version of Test-Harness was doing well on CPANtesters.  I had installed blead on two different platforms and then successfully installed Test-Harness-2.46 against that perl.

So I was confident that I could use our program to sync this into blead.  However, the program failed, with output like this:
```
Starting `make test-harness TEST_ARGS='-re Test-Harness'` and saving its output to 'make.log' ...
Finished `make test-harness TEST_ARGS='-re Test-Harness'`
Test Summary Report
-------------------
../cpan/Test-Harness/t/harness.t                   (Wstat: 768 (exited 3) Tests: 133 Failed: 3)
  Failed tests:  47, 52, 57
  Non-zero exit status: 3
Files=58, Tests=11909,  3 wallclock secs ( 0.41 usr  0.06 sys +  4.35 cusr  0.84 csys =  5.66 CPU)
Result: FAIL
Finished test run at Sat Aug 12 15:32:42 2023.
make: *** [makefile:855: test-harness] Error 3
Running `make` failed, see 'make.log' for more details
```
... and here's that output:
```
#   Failed test '... and the output should be correct'
#   at t/harness.t line 138.
#     Structures begin differing at:
#          $got->[5] = '[[green]]'
#     $expected->[5] = 'ok'

#   Failed test '... and the output should be correct'
#   at t/harness.t line 171.
#     Structures begin differing at:
#          $got->[5] = '[[green]]'
#     $expected->[5] = 'ok'
../cpan/Test-Harness/t/grammar.t ..................... ok
../cpan/Test-Harness/t/file.t ........................ ok

#   Failed test '... and the output should be correct'
#   at t/harness.t line 212.
#     Structures begin differing at:
#          $got->[5] = '[[green]]'
#     $expected->[5] = 'ok'
../cpan/Test-Harness/t/harness-subclass.t ............ ok
...
```
I spent some time on this but could not figure it out.  @LeonT, can you take a look?  Thanks.

**Comment by haarg** [comment]
`t/harness.t` needs to be removed from `CUSTOMIZED`.

**Comment by jkeenan** [comment]
On 8/12/23 16:52, Graham Knop wrote:
> |t/harness.t| needs to be removed from |CUSTOMIZED|.

Yes, that's what I'm checking out right now.  Will report results.

**Comment by jkeenan** [comment]
> On 8/12/23 16:52, Graham Knop wrote: |t/harness.t| needs to be removed from |CUSTOMIZED|.
> Yes, that's what I'm checking out right now. Will report results.

Agreed.  Here's a p.r. which first decustomizes Test::Harness in Porting/Maintainers.pl and then performs the sync of Test-Harness-3.46 into blead.
https://github.com/Perl/perl5/pull/21369

**Comment by jkeenan** [comment]
Fixed by https://github.com/Perl/perl5/pull/21369
