### ISSUE TITLE
On macOS, calling localtime before fork causes slow localtime inside child

### ISSUE THREAD

**Issue by marioroy** [Perl/perl5#21401]
Re: [Time::Piece extremely slow under MCE::Loop on MacOS](https://github.com/marioroy/mce-perl/issues/18)

The following code takes 16 seconds on macOS (Intel Mac). Removing the first line takes 0.122 seconds.

```perl
my $t = localtime();

my $pid = fork;
die "fork failed: $!" unless defined $pid;

if (!$pid) {
    # child
    print "child  $$\n";
    my $t = localtime() for 1..100000;
    exit;
}

# parent
print "parent $$\n";
waitpid($pid, 0);
```

**Comment by dkechag** [comment]
Similar on M1 Pro, 6.7s with the extra call on parent, 0.04s otherwise. I can reproduce on MacOS BigSur and Ventura.

**Comment by jkeenan** [comment]
> Similar on M1 Pro, 6.7s with the extra call on parent, 0.04s otherwise. I can reproduce on MacOS BigSur and Ventura.

This appears to be OS-specific.  I get no significant differences with/without first statement on Linux or FreeBSD.

**Comment by jkeenan** [comment]
> Re: [Time::Piece extremely slow under MCE::Loop on MacOS](https://github.com/marioroy/mce-perl/issues/18)
> 
> The following code takes 16 seconds on macOS (Intel Mac). Removing the first line takes 0.122 seconds.
> 

Can you try this with older/newer versions of Perl on this platform?

**Comment by dkechag** [comment]
> 



> 

Can confirm with perl 5.20.3 to 5.38.0

**Comment by dkechag** [comment]
And just tried 5.8.4 out of curiosity. Same behaviour.

**Comment by marioroy** [comment]
I factored out Perl. The same behavior is seen running Python.

```python
# https://docs.python.org/3/library/multiprocessing.html
# usage: python3 test.py

import os, time
import multiprocessing as mp

def f():
    print(f"child  {os.getpid()}")

    for i in range(100000):
        t = time.localtime()

if __name__ == '__main__':
    print(f"parent {os.getpid()}")
    t = time.localtime()

  # ctx = mp.get_context('spawn')  # okay
  # p = ctx.Process(target=f, args=())
  # p.start()
  # p.join()

    ctx = mp.get_context('fork')   # slow localtime
    p = ctx.Process(target=f, args=())
    p.start()
    p.join()
```

**Spawn context (default on macOS and Windows):**

```bash
$ time python3 test.py
parent 25915
child  25917

real   0m0.283s
user   0m0.235s
sys    0m0.039s
```

**Fork context (default on Unix):**

```bash
$ time python3 test.py
parent 25922
child  25923

real   0m16.844s
user   0m6.825s
sys    0m10.006s
```

**Comment by marioroy** [comment]
I'm closing the issue as this is macOS-specific, after factoring out Perl.
