### ISSUE TITLE
Maintainers.pl: Package-global variables

### ISSUE THREAD

**Issue by rwp0** [Perl/perl5#21410]
Is it okay that `%Maintainers` hash and `@IGNORABLE` array are package-global in `Maintainers.pl`?

Maybe declare (scope) with `my`, or `our` if used outside?

https://github.com/Perl/perl5/blob/e428e4926379aac606b464db8efb8f43735d2e33/Porting/Maintainers.pl#L127

https://github.com/Perl/perl5/blob/e428e4926379aac606b464db8efb8f43735d2e33/Porting/Maintainers.pl#L18

**Comment by Leont** [comment]
That is on purpose, `Maintainers.pm`, `core-cpan-diff` and `cmpVERSION.pl` all depend on it being accessible. That said, making them `our` so you can add a «use strict» sounds fine.
