### ISSUE TITLE
Wrong camel in Github's repository "About" section

### ISSUE THREAD

**Issue by bbrtj** [Perl/perl5#21417]
**Description**
The unicode camel emoji in the description seems to be Bactrian Camel: 🐫 (https://www.compart.com/en/unicode/U+1F42B). This is the camel OCaml uses in its logo.

![obraz](https://github.com/Perl/perl5/assets/44323413/2b3c7934-f1ab-46c0-b74a-5acc2f3a0cdc)

**Expected behavior**
The proper emoji should be Dromedary Camel: 🐪 (https://www.compart.com/en/unicode/U+1F42A). This is the camel from the original camel book and it is currently used on perl.org.

**Comment by haarg** [comment]
Fixed.

**Comment by rwp0** [comment]
Also I wish the website was "https://www.perl.org/" for the sake of simplicity
