### ISSUE TITLE
Porting/Maintainers.pl: outdated entry for ExtUtils-ParseXS

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#21459]
In blead, all the non-test `*.pm` files for ExtUtils-ParseXS are at `$VERSION` 3.51:
```
$ find dist/ExtUtils-ParseXS/ -type f | xargs grep -n -E '\$VERSION\s*='
dist/ExtUtils-ParseXS/lib/ExtUtils/ParseXS.pm:14:  $VERSION = '3.51';
dist/ExtUtils-ParseXS/lib/ExtUtils/ParseXS.pm:20:$VERSION = eval $VERSION if $VERSION =~ /_/;
dist/ExtUtils-ParseXS/lib/ExtUtils/Typemaps.pm:5:our $VERSION = '3.51';
dist/ExtUtils-ParseXS/lib/ExtUtils/ParseXS/Constants.pm:6:our $VERSION = '3.51';
dist/ExtUtils-ParseXS/lib/ExtUtils/ParseXS/CountLines.pm:4:our $VERSION = '3.51';
dist/ExtUtils-ParseXS/lib/ExtUtils/ParseXS/Eval.pm:5:our $VERSION = '3.51';
dist/ExtUtils-ParseXS/lib/ExtUtils/ParseXS/Utilities.pm:8:our $VERSION = '3.51';
dist/ExtUtils-ParseXS/lib/ExtUtils/Typemaps/Type.pm:7:our $VERSION = '3.51';
dist/ExtUtils-ParseXS/lib/ExtUtils/Typemaps/Cmd.pm:5:our $VERSION = '3.51';
dist/ExtUtils-ParseXS/lib/ExtUtils/Typemaps/InputMap.pm:5:our $VERSION = '3.51';
dist/ExtUtils-ParseXS/lib/ExtUtils/Typemaps/OutputMap.pm:5:our $VERSION = '3.51';
dist/ExtUtils-ParseXS/lib/perlxstut.pod:150:    our $VERSION = '0.01';
dist/ExtUtils-ParseXS/t/XSUsage.pm:5:$VERSION = '0.01';
dist/ExtUtils-ParseXS/t/XSTest.pm:5:$VERSION = '0.01';
dist/ExtUtils-ParseXS/t/002-more.t:59:    our $VERSION = 42;
```
3.51 is also the [latest release to CPAN](https://metacpan.org/dist/ExtUtils-ParseXS/changes).

However, the entry for this distribution in `Porting/Maintainers.pl` remains at 3.44 (with a different most recent releasor as well):
```
$ grep -n -A3 'ExtUtils::ParseXS' Porting/Maintainers.pl
523:    'ExtUtils::ParseXS' => {
524-        'DISTRIBUTION' => 'XSAWYERX/ExtUtils-ParseXS-3.44.tar.gz',
525-        'FILES'        => q[dist/ExtUtils-ParseXS],
526-    },
```
Is there any reason why we should *not* update this entry to `LEONT/ExtUtils-ParseXS-3.51.tar.gz`?

@LeonT

**Comment by Leont** [comment]
Good catch. I don't think I've ever released an upstream=blead dist before, so I totally forgot about this part.

**Comment by jkeenan** [comment]
> Good catch. I don't think I've ever released an upstream=blead dist before, so I totally forgot about this part.

Yeah, very few of us have, as it was previously the pumpking's responsibility but way down on the/any pumpking's TODO list.  See, for example, https://www.nntp.perl.org/group/perl.perl5.porters/2023/07/msg266743.html, which remains unresponded to > 6 weeks later! :-(
