### ISSUE TITLE
dist/*/*.json files point to search.cpan.org

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#21494]
Metadata files for libraries shipped under `dist/` are maintained here in blead (and only subsequently released to CPAN).  There are two such files where the "meta-spec : url" value points to `http://search.cpan.org`:
```
$ find dist -type f -name '*.json' | xargs ack -C3 'search\.cpan\.org'
dist/if/META.json
9-      "perl_5"
10-   ],
11-   "meta-spec" : {
12:      "url" : "http://search.cpan.org/perldoc?CPAN::Meta::Spec",
13-      "version" : "2"
14-   },
15-   "name" : "if",

dist/PathTools/META.json
9-      "perl_5"
10-   ],
11-   "meta-spec" : {
12:      "url" : "http://search.cpan.org/perldoc?CPAN::Meta::Spec",
13-      "version" : "2"
14-   },
15-   "name" : "PathTools",
```
That URL has not existed for several years now.  It redirects to https://metacpan.org/pod/CPAN::Meta::Spec.  Should we use that URL instead?

**Note:** This will also be relevant to https://github.com/Perl/perl5/pull/21349, where the request is to update the metadata for Safe, which may once upon a time have been maintained upstream on CPAN but is now also in blead's jurisdiction. (@ehuelsmann).

**Comment by Leont** [comment]
This URL is correct for historical reasons. I think there has been discussion of changing it, but some toolchainy thing might get confused if you do right now.

**Comment by haarg** [comment]
The URL isn't really used for anything, and other URLs are allowed by the spec. If I remember correctly, the problem with changing it was that there are various toolchain modules with tests that expect specific metadata, and coordinating a change across all of them wasn't very viable.

The part forward would probably be to make sure that all of the appropriate tests would accept a different URL. Changing the generated value could happen some time after that, although possibly much later.

The search.cpan.org URL still works fine, so there isn't really any rush to get this changed.

**Comment by jkeenan** [comment]
> The URL isn't really used for anything, and other URLs are allowed by the spec. If I remember correctly, the problem with changing it was that there are various toolchain modules with tests that expect specific metadata, and coordinating a change across all of them wasn't very viable.
> 
> The part forward would probably be to make sure that all of the appropriate tests would accept a different URL. Changing the generated value could happen some time after that, although possibly much later.
> 
> The search.cpan.org URL still works fine, so there isn't really any rush to get this changed.

@haarg, thanks for that explanation.  How would we determine what "all of the appropriate tests" would be?  For example, if we had checked every module under https://github.com/Perl-Toolchain-Gang/, would that be sufficient?

I won't pursue this anytime soon, but I do think we should have some idea of what we're going to do down the road.  Thanks.

**Comment by Leont** [comment]
One important case that would have to be updated in CPAN::Meta::Merge, which would currently refuse to merge two fragments with a different URL. Likewise CPAN::Meta::Converter would probably also need to change to output the new URL, but CPAN::Meta::Validator is probably fine.
