### ISSUE TITLE
Math-BigInt-1.999840: Problems synching into blead

### ISSUE THREAD

**Issue by jkeenan** [Perl/perl5#21504]
@pjacklam,

Running `Porting/core-cpan-diff -x -a` today, I noticed that you have uploaded new versions of CPAN distributions [Math-BigInt](https://metacpan.org/pod/Math::BigInt) and [Math-BigInt-FastCalc](https://metacpan.org/pod/Math::BigInt::FastCalc).  I then attempt to sync Math-BigInt into Perl 5 blead, first configuring, then calling `perl Porting/sync-with-cpan Math::BigInt --yes`.

This failed during `make test_porting`:
```
Finished `make test-porting`
Test Summary Report
-------------------
porting/exec-bit.t      (Wstat: 0 Tests: 145 Failed: 5)
  Failed tests:  82, 84, 86, 88, 90
```
Investigation suggested that these failure were associated with the addition of these 5 files to core during the synch process.
```
+cpan/Math-BigInt/dev/bblsft-table.pl                   Math-BigInt
+cpan/Math-BigInt/dev/bbrsft-table.pl                   Math-BigInt
+cpan/Math-BigInt/dev/blrsft-table.pl                   Math-BigInt
+cpan/Math-BigInt/dev/brsft-table.pl                    Math-BigInt
+cpan/Math-BigInt/dev/brsft-test.pl                     Math-BigInt
```
I'm puzzled here.  Comparing CPAN tarballs for 1.999839 and 1.999840, I see that the `dev/` directory and these 5 files thereunder were indeed added in the later version:
```
$ diff Math-BigInt-1.999839/MANIFEST Math-BigInt-1.999840/MANIFEST
3a4,8
> dev/bblsft-table.pl
> dev/bbrsft-table.pl
> dev/blrsft-table.pl
> dev/brsft-table.pl
> dev/brsft-test.pl
45a51
> t/Math/BigFloat/BareSubclass.pm
107a114,115
> xt/author/bblsft.t
> xt/author/bbrsft.t
```
However, I do **not** see any `dev/` directory in a checkout from your [GH repository](https://github.com/pjacklam/p5-Math-BigInt):
```
$ pwd
/home/jkeenan/gitwork/zzzothers/p5-Math-BigInt

$ ls
BUGS     CREDITS   GOALS    lib      Makefile.PL    NEW     README.md  TODO
CHANGES  examples  HISTORY  LICENSE  MANIFEST.SKIP  README  t          xt
```
Can you explain what the 5 files in `dev/` in the tarball are for?

Now, I suspect that the way Perl 5 core should deal with this is simply to exclude the `dev/` directory from being synched into core, *i.e.,* committing
```
commit 6258469ea6d348a79a65d3b6bc25f01588d464ac
Author: James E Keenan <jkeenan@cpan.org>
Date:   Thu Sep 21 09:09:48 2023 -0400

    Add dev/ to EXCLUDED for Math-BigInt
    
    Let's see if this works.

diff --git a/Porting/Maintainers.pl b/Porting/Maintainers.pl
index 1d148149af..c3e2d14b75 100755
--- a/Porting/Maintainers.pl
+++ b/Porting/Maintainers.pl
@@ -762,6 +762,7 @@ our %Modules = (
         'EXCLUDED'     => [
             qr{^xt/},
             qr{^examples/},
+            qr{^dev/},
             qw( t/00sig.t
                 t/01load.t
                 ),
```
... before running `Porting/sync-with-cpan`.  Doing so enabled `make test_porting` and `make test_harness` to PASS.  But before I do that I'd like to understand what the 5 `dev/*.pl` files are doing in the tarball?

I suspect we may have similar problems with Math-BigInt-FastCalc ... but one step at a time.

Thank you very much for your continued attention to the Math* distributions.

**Comment by pjacklam** [comment]
The files `/dev` should _not_ have been in the distribution. I included the necessary entry to `.gitignore`, but forgot to do the same to `MANIFEST.SKIP`. I noticed the error yesterday, but haven't had time to upload a new version of the distribution yet. I'm sorry about the error. I'll upload a new version of the distribution without these files.

**Comment by jkeenan** [comment]
> The files `/dev` should _not_ have been in the distribution. I included the necessary entry to `.gitignore`, but forgot to do the same to `MANIFEST.SKIP`. I noticed the error yesterday, but haven't had time to upload a new version of the distribution yet. I'm sorry about the error. I'll upload a new version of the distribution without these files.

Thanks for your rapid response!

**Comment by pjacklam** [comment]
I have uploaded Math-BigInt-1.999841 to PAUSE. It is identical to Math-BigInt-1.999840 except that it doesn't contain the `/dev` directory.

**Comment by jkeenan** [comment]
> I have uploaded Math-BigInt-1.999841 to PAUSE. It is identical to Math-BigInt-1.999840 except that it doesn't contain the `/dev` directory.

Thanks.  I'll give 1.999841 a couple of days to percolate thru CPANtesters, then proceed with synching.

**Comment by jkeenan** [comment]
> > I have uploaded Math-BigInt-1.999841 to PAUSE. It is identical to Math-BigInt-1.999840 except that it doesn't contain the `/dev` directory.
> 
> Thanks. I'll give 1.999841 a couple of days to percolate thru CPANtesters, then proceed with synching.

The latest CPAN versions of Math-BigInt and Math-BigInt-Calc have been synched into blead.
```
commit 41d0ddc96a06ae00a2a5d821dd25fba6f7ee0a41 (HEAD -> blead, origin/blead, origin/HEAD)
Author: Peter John Acklam <pjacklam@online.no>

    cpan/Math-BigInt-FastCalc - Update to version 0.5015

commit 6a237533fb6ad7883b9a6ec8f8afeed0de3bd8b6
Author: Peter John Acklam <pjacklam@online.no>

    cpan/Math-BigInt - Update to version 1.999841
```
