### ISSUE TITLE
BBC: Blead Breaks CryptX

### ISSUE THREAD

**Issue by cjg-cguevara** [Perl/perl5#21518]
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.43 running under perl 5.39.4.

-----------------------------------------------------------------

BBC: Blead Breaks CryptX

Please see http://fast-matrix.cpantesters.org/?dist=CryptX%200.078

---
**Flags**
- category=core
- severity=low
---
**Perl configuration**
```
Site configuration information for perl 5.39.4:

Configured by cpan at Mon Sep 25 13:36:02 EDT 2023.

Summary of my perl5 (revision 5 version 39 subversion 4) configuration:
  Commit id: f1a9bff9425f5b43d0d63d1c4be758d25dd17925
  Platform:
    osname=openbsd
    osvers=7.3
    archname=OpenBSD.amd64-openbsd
    uname='openbsd cjg-openbsd7 7.3 generic#3 amd64 '
    config_args='-des -Dprefix=/home/cpan/bin/perl -Dscriptdir=/home/cpan/bin/perl/bin -Dusedevel -Duse64bitall'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    optimize='-O2'
    cppflags='-fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='OpenBSD Clang 13.0.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags ='-Wl,-E  -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/lib/clang/13.0.0/lib /usr/lib /usr/local/lib
    libs=-lpthread -lm -lutil -lc
    perllibs=-lpthread -lm -lutil -lc
    libc=/usr/lib/libc.so.97.0
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags='-DPIC -fPIC '
    lddlflags='-shared -fPIC  -L/usr/local/lib -fstack-protector-strong'


---
@INC for perl 5.39.4:
    /home/cpan/bin/perl/lib/site_perl/5.39.4/OpenBSD.amd64-openbsd
    /home/cpan/bin/perl/lib/site_perl/5.39.4
    /home/cpan/bin/perl/lib/5.39.4/OpenBSD.amd64-openbsd
    /home/cpan/bin/perl/lib/5.39.4

---
Environment for perl 5.39.4:
    HOME=/home/cpan
    LANG (unset)
    LANGUAGE (unset)
    LC_ALL=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl/bin:/home/cpan/bin:/home/cpan/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin:/usr/local/bin:/usr/local/sbin
    PERL_BADLANG (unset)
    SHELL=/usr/local/bin/bash
```

**Comment by hvds** [comment]
Sample fail report http://www.cpantesters.org/cpan/report/fdc0c49a-5a47-11ee-9ece-aaae1ab0edc7 suggests this is falling foul of the planned changes to `Math::BigInt` handling of `>>`. @pjacklam can you take a look, and perhaps talk with @karel-m about adapting to the changes?

**Comment by mauke** [comment]
Yeah, a bisect points to commit 6a237533fb6ad78 ("cpan/Math-BigInt - Update to version 1.999841"), so this is really a [Math::BigInt](https://metacpan.org/pod/Math::BigInt) issue, isn't it?

**Comment by pjacklam** [comment]
I'll take a look.

**Comment by jkeenan** [comment]
Given the large number of CPAN distros that depend on Math-BigInt, there is likely to be a lot of breakage.  I'm doing a CPANtesters run of the 189 first-order revdeps so that we get some idea of the scope of the problem.  (This will take some hours to run.)

**Comment by sisyphus** [comment]
> ... and perhaps talk with @karel-m about adapting to the changes?

Yes - these recent changes actually bring Math::BigInt's shift operations into line with the way perl's shift operators deal with negative arguments.

OTOH, if you wanted to advocate that the old behaviour be retained you'd probably point out that such operations are "undefined behaviour" in C99.

Cheers,
Rob

**Comment by pjacklam** [comment]
> Yes - these recent changes actually bring Math::BigInt's shift operations into line with the way perl's shift operators deal with negative arguments.

Yes, more specifically when the second operand, the number of places to shift, is negative. The changes also bring Math::BigFloat's shift operations into line with the way perl’s shift operators deal with non-integer arguments.

While many distributions use Math::BigInt, I am not sure how common it is to use negative shifts, e.g., `$x << -3`, especially since this used to return a `NaN` anyway. And using `<<` and `>>` on non-integer values was considered a “corner case” in a recent discussion. Making the behaviour of `<<` and `>>` in line with core Perl will also make `bignum`’s claim “transparent big number support for Perl” less misleading. Also note that the changes only affect the shift operators `<<` and `>>`. The methods `blsft()` and `brsft()` work as before.

The CryptX distribution seems to be using test files directly copied from the Math-BigInt distribution, so the simplest solution to the failing tests is to copy the latest test files from the Math-BigInt distribution.

As for how much breakage this causes, I’ll wait for the results from @jkeenan. If the damage is too great to be justified, I will revert the change.

**Comment by jkeenan** [comment]
> 
> The CryptX distribution seems to be using test files directly copied from the Math-BigInt distribution, so the simplest solution to the failing tests is to copy the latest test files from the Math-BigInt distribution.
> 
> As for how much breakage this causes, I’ll wait for the results from @jkeenan. If the damage is too great to be justified, I will revert the change.

I think we may have dodged a bullet here.  AFAICT, the *only* CPAN distribution which is *directly* dependent on Math-BigInt and which has suffered a failure in CPANtesters as a result of the recent upgrade to M-BI version 1.999841 (and its subsequent synching into the Perl core distribution in 6a237533fb6 on Sep 24) is the one originally reported in this ticket:  CryptX.

Here is what I did to reach this inference.

I screen-scraped http://deps.cpantesters.org/depended-on-by.pl?dist=Math-BigInt, then wrote a program (available upon request) that processed that data into a list of CPAN modules suitable for passing as arguments to `cpan`.
```
$ perl $P5P_DIR/math-bigint-revdeps.pl | wc -l
189

$ perl $P5P_DIR/math-bigint-revdeps.pl 
Acme::Affinity
Acme::KeyboardMarathon
Affix
Algorithm::Bayesian
Algorithm::BitVector
Algorithm::RandomMatrixGeneration
Algorithm::Voting
Alt::Crypt::RSA::BigInt
Alt::Data::Frame::ButMore
Astro::Units
Authen::Bitcard
Authen::HOTP
Authen::OATH
Authen::OATH::OCRA
Authen::TypeKey
Avro
BSON
Bencher::Scenario::BigFloat
Bencher::Scenario::BigInt
Bencher::Scenarios::MathBigFloat
BioPerl
Bitcoin::Crypto
Bitmask::Data
Blockchain::Contract::Solidity::ABI
Blockchain::Ethereum::ABI
Bundle::Zavitan
Business::IBAN
Business::RO::TaxDeduction
CAD::Calc
CLDR::Number
CORBA::IDL
CPU::x86_64::InstructionWriter
CXC::Number
Chart::Math::Axis
Chemistry::Canonicalize
Chemistry::Harmonia
Chicken::Ipsum
Convert::ASN1
Crixa
Crypt::AES::CTR
Crypt::AppleTwoFish
Crypt::DH
Crypt::DRBG
Crypt::DSA
Crypt::DSA::GMP
Crypt::HSXKPasswd
Crypt::MagicSignatures::Key
Crypt::OpenSSL::Base::Func
Crypt::PBC
Crypt::RFC8188
Crypt::SRP
CryptX
DBD::Firebird
DBD::Oracle
DBIx::Class::InflateColumn::BigFloat
DBIx::Class::Tree::Mobius
DBIx::CouchLike
DNS::Bananafonana
DOCSIS::ConfigFile
Data::Dumper::Interp
Data::Frame
Data::LazyACL
Data::MEID
Data::MessagePack
Data::Money
Data::ParseBinary
Data::UUID::Concise
Data::UUID::NCName
Data::Validate
DateTime::Format::Epoch
DateTime::Format::WindowsFileTime
DateTime::Util::Astro
DateTime::Util::Calc
Dev::Bollocks
Devel::Cover
ELF::Writer
Encode::Base58::BigInt
Encode::Positive::Digits
Encode::Positive::Pairs
Enterprise::Licence
Ethereum::RPC::Client
FFI::Raw
Finance::Tax::Aruba
Form::Sensible::Reflector::MySQL
Format::Util
FunctionalPerl
Geo::Calc
Geo::Code
Geo::Code::XYZ
Geo::Code::XYZEN
GnuPG::Interface
Google::ProtocolBuffers
Hashids
Hessian::Tiny
IP::Geolocation::MMDB
IPDR
InterMine::TypeLibrary
JSON::Schema::Modern
JSON::Schema::Tiny
Ledger::Parser
Library::CallNumber::LC
Logwatch::RecordTree
MRS::Client
Mac::Alias::Parse
Mac::PropertyList
Mail::Graph
MarpaX::ESLIF
MarpaX::Java::ClassFile
MarpaX::Languages::ECMAScript::AST
MarpaX::Languages::IDL::AST
MarpaX::Languages::SQL2003::AST
Math::Algebra::Symbols
Math::Assistant
Math::Base36
Math::Base85
Math::BaseCnv
Math::BaseConvert
Math::Big
Math::BigInt::BitVect
Math::BigInt::Constant
Math::BigInt::FastCalc
Math::BigInt::GMP
Math::BigInt::GMPz
Math::BigInt::Lite
Math::BigInt::Named
Math::BigInt::Pari
Math::BigInt::Parts
Math::BigInt::Random
Math::BigInt::Random::OO
Math::BigRat
Math::Counting
Math::Currency
Math::DyckWords
Math::FractionManip
Math::Int128
Math::Logic::Ternary
Math::ModInt
Math::Prime::Util::GMP
Math::ProvablePrime
Math::RandomOrg
Math::Revhash
Math::Roman
Math::String
MaxMind::DB::Common
MooseX::Types::XMLSchema
Music::RecRhythm
Net::Amazon::HadoopEC2::S3fs
Net::Async::Blockchain
Net::BitTorrent
Net::Ethereum
Net::IP::Identifier
Net::IP::XS
Net::IPAddress::Util
Net::IPv6Addr
Net::Netmask
Net::OpenID::Common
Net::SNMP
Number::Format::BigFloat
Number::WithError
OPTIMADE::Filter
Object::Import
PGObject::Type::BigFloat
Parse::StackTrace
Pass::OTP
Path::Hilbert
Protocol::CassandraCQL
RDF::Helper
RDF::Trine
REFECO::Blockchain::Contract::Solidity::ABI
REFECO::Blockchain::Contract::Solidity::ABI::Encoder
Rose::DB::Object
SNMP::Info
SQL::Translator::Parser::OpenAPI
Sphinx::Search
Statistics::Test::RandomWalk
Statistics::Test::Sequence
Store::Digest
TOML::Tiny
Template::Mustache
Text::Wrap::Smart
Time::Duration::Object
Time::Moment::Epoch
Tk::ObjScanner
Types::Numbers
Types::XMLSchema
WARC
Win32::UrlCache
Win32API::File
perfSONAR_PS::Services::MA::perfSONARBUOY
```
On FreeBSD-13, I built a threaded `perl` in my customary manner at f1a9bff942 (which was HEAD yesterday afternoon).
```
$ ./bin/perl -Ilib -v |head -2 | tail -1
This is perl 5, version 39, subversion 4 (v5.39.4 (v5.39.3-49-gf1a9bff942)) built for amd64-freebsd-thread-multi
```
I then installed Task::CPAN::Reporter against that `perl` and emptied out my data base CPAN-Reporter reports sent.  In a screen session, I then called:
```
$ perl $P5P_DIR/math-bigint-revdeps.pl | xargs ./bin/cpan
```
I checked the results today:
```
$ wc -l reports-sent.db
     846 reports-sent.db

$ grep -c FAIL reports-sent.db
21

$ grep FAIL ~/.cpanreporter/reports-sent.db
test FAIL CryptX-0.078 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
test FAIL Astro-Units-1.10 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
test FAIL Data-Clone-0.004 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
test FAIL Data-Sah-Coerce-0.053 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
test FAIL Devel-Size-0.83 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
test FAIL BSD-Sysctl-0.11 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
test FAIL Bitmask-Data-2.05 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
test FAIL CXC-Number-0.12 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
test FAIL Net-AMQP-RabbitMQ-2.40010 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
test FAIL Crypt-HSXKPasswd-v3.6 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
test FAIL Crypt-OpenSSL-Base-Func-0.037 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
test FAIL DBIx-CouchLike-0.16 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
test FAIL DateTime-Util-Astro-0.12000 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
test FAIL Dev-Bollocks-0.06 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
test FAIL Ethereum-RPC-Client-0.05 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
test FAIL Form-Sensible-0.20023 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
test FAIL FunctionalPerl-0.72.76 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
test FAIL GnuPG-Interface-1.03 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
test FAIL Unicode-Map8-0.13 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
test FAIL Math-RandomOrg-0.04 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
test FAIL Net-BitTorrent-0.052 (perl-5.39.4) amd64-freebsd-thread-multi 13.2-release-p1
```
Of the 21 distributions that were graded `FAIL`, some (*e.g.,* Devel-Size) were those I recognized from earlier CPAN-River-3000 testing as failing to build on FreeBSD for years.  Many of the others have not built on *any* platform for years.  Only [CryptX's failure](http://www.cpantesters.org/cpan/report/67491bf2-5bdc-11ee-ba47-a4c9bac039ce) was directly attributable to Math::BigInt.

*However,* I caution that my inspection of CPANtesters reports for the 21 FAILs was strictly visual, so my eyes might have missed something.

I further caution that no Windows-specific distributions (or prerequisites therefor) were tested.

Nonetheless, we don't yet have any evidence that the recent upgrade to Math-BigInt will cause widespread breakage once it goes into wide release with the release of perl-5.40 next May.

**Comment by sisyphus** [comment]
> The methods <code>blsft()</code> and <code>brsft()</code> work as before.

I'm seeing different behaviour regarding <code>blsft()</code> and <code>brsft()</code> withM-BI-1.999839 and M-BI-1.999841

Using 1.999839:
```
D:\>perl -MMath::BigInt -le "print $Math::BigInt::VERSION; print Math::BigInt->new(12345)->blsft(-1);"
1.999839
NaN

D:\>perl -MMath::BigInt -le "print $Math::BigInt::VERSION; print Math::BigInt->new(12345)->brsft(-1);"
1.999839
NaN
```

But I get something different when using 1.999841:
```
D:\>perl -MMath::BigInt -le "print $Math::BigInt::VERSION; print Math::BigInt->new(12345)->blsft(-1);"
1.999841
6172

D:\>perl -MMath::BigInt -le "print $Math::BigInt::VERSION; print Math::BigInt->new(12345)->brsft(-1);"
1.999841
24690
```
Sorry if I've misunderstood what you mean by "work as before" ?

Cheers,
Rob

**Comment by pjacklam** [comment]
@sisyphus, you are of course correct, and I am suitably humbled. I have to keep better track of the changes I make.

I did indeed make some changes to `blsft()` and `brsft()` partly based on wishes from users and partly based on my desire for consistency and fixing bugs. The methods `blsft()` and `brsft()` should support shifting an arbitrary value `$x` an arbitrary number of places `$n` in an arbitrary base `$b`.

* As you show above, I added support for negative values of `$n`.
* I improved the handling of NaNs. For example, the following now gives the correct result NaN, but with version 1.999839 you get
```
$ perl -MMath::BigInt -wle '$x = Math::BigInt -> new(2); print $x -> blsft(3, "NaN")'
0
```
* I added support for arbitrarily large bases `$b`. In previous versions, a very large base would give the error “Base is too large”.

I will update the appropriate entry in the CHANGES file and also check/update the documentation and tests for the two methods.

Thank you very much for pointing this out, and sorry for being sloppy.

**Comment by andk** [comment]
From the 21 FAIL reports above one would want to point out that CXC-Number-0.12 has a solid history of PASS reports on Linux in the matrix: http://matrix.cpantesters.org/?dist=CXC-Number

But then from http://www.cpantesters.org/cpan/report/9c3c52ca-5ba5-11ee-8668-ee14a3603691

```
Deep recursion on subroutine "Math::BigInt::babs" at /home/sand/src/perl/repoperls/installed-perls/host/k93jammy/v5.39.3/322f/lib/site_perl/5.39.3/Math/BigInt.pm line 1603.
```

**Comment by pjacklam** [comment]
That looks pretty bad. I'll dig into it and see what is causing this and what I need to change/revert.

**Comment by pjacklam** [comment]
> From the 21 FAIL reports above one would want to point out that CXC-Number-0.12 has a solid history of PASS reports on Linux in the matrix: […]

I have gone through all the 21 modules that failed. Most of them failed because of issues not related to the Math::Big* modules, but there were some exceptions.
* CryptX fails for known reasons (see above). Hopefully it is sufficient to update test files.
* Astro::Units started failing with Math-BigInt 1.999829 released 2021-12-29 when div_scale() started requiring a positive argument. Astro::Units sets div_scale to zero, which doesn't make much sense, since it is the fall-back value for the accuracy when accuracy or precision hasn't been set explicitly. Astro::Units seems like a useful module, so I can change the behaviour from throwing an error to a giving a warning and setting the div_scale to 1.
* Dev::Bollocks has failed for a long time. I'll have a look at why it fails, but it seems like a module made just for fun, so this has lower priority.
* CXC::Number fails because of a recent attempt at improving the handling of subclasses. Unfortunately, when Math::BigInt upgrades to Math::BigFloat, and Math::BigFloat inherits a method from Math::BigInt, this can result in an endless loop. The following illustrates the problem:
```
$ perl -MMath::BigFloat -le 'Math::BigInt -> upgrade("Math::BigFloat"); $x = Math::BigFloat -> bone() -> babs()'
Deep recursion on subroutine "Math::BigInt::babs" at /usr/local/lib/perl5/Math/BigInt.pm line 1603.
```
I will release a new version of the Math-BigInt distribution as soon as I can.

**Comment by pjacklam** [comment]
I have just now uploaded Math-BigInt-1.999842.tar.gz to PAUSE. That should solve the issue with CXC::Number (and Astro::Units).

**Comment by jkeenan** [comment]
> I have just now uploaded Math-BigInt-1.999842.tar.gz to PAUSE. That should solve the issue with CXC::Number (and Astro::Units).

LGTM so far.  On FreeBSD-13, I get:
```
$ ./bin/perl -Ilib -MMath::BigInt -MAstro::Units -MCXC::Number -E 'say join("\t", $Math::BigInt::VERSION, $Astro::Units::VERSION, $CXC::Number::VERSION);'
1.999842	1.10	0.12
```
We'll synch this into blead in a few days.  Thanks.

**Comment by jkeenan** [comment]
Math-BigInt-1.999842 has been synched into blead.  We'll keep this ticket open for a few days to see whether the reported test failures have cleared up.

**Comment by twata1** [comment]
FYI.
It appears to me that the testing of CryptX-0.078_001 with Math-BigInt-1.999842 has started to fail, at least in my Strawberry Perl environment.

Sample fail report:
http://www.cpantesters.org/cpan/report/2d79862b-6c41-1014-a5fe-390bf0aa1848

**Comment by jkeenan** [comment]
> FYI. It appears to me that the testing of CryptX-0.078_001 with Math-BigInt-1.999842 has started to fail, at least in my Strawberry Perl environment.
> 
> Sample fail report: http://www.cpantesters.org/cpan/report/2d79862b-6c41-1014-a5fe-390bf0aa1848

I acknowledge that, however at this point we need to get some feedback from @karel-m, the author/maintainer of CryptX, in order to proceed.  The `_001` in the name of that tarball suggests that it's a trial version of the distribution; we don't yet know exactly what the author is trying out.

**Comment by pjacklam** [comment]
> […] at this point we need to get some feedback from @karel-m, the author/maintainer of CryptX, in order to proceed.

I have sent an e-mail to Karel Miko referencing this issue. We had a similar issue some years ago. It was solved by simply copying the test files from Math-BigInt into CryptX, but I don't know whether this is an acceptable solution this time.

Note that CryptX uses Math::BigInt and Math::BigFloat only for the tests. The reason for CryptX depending on Math::BigInt and Math::BigFloat is that CryptX provides Math::BigInt::LTM, which is a backend library intended to be compatible with the other Math::BigInt::* backend libraries (Math::BigInt::FastCalc, Math::BigInt::GMP etc.). To verify this compatibility, CryptX uses test files copied from the Math::BigInt distribution.

**Comment by karel-m** [comment]
I have released CryptX-0.079_001 

The test suite fix: https://github.com/DCIT/perl-CryptX/commit/62fde623598a7d04081fc63bc992c0d860e875df (@pjacklam please have a look whether I got the root cause of the problem)

**Comment by jkeenan** [comment]
> I have released CryptX-0.079_001
> 
> The test suite fix: [DCIT/perl-CryptX@62fde62](https://github.com/DCIT/perl-CryptX/commit/62fde623598a7d04081fc63bc992c0d860e875df) (@pjacklam please have a look whether I got the root cause of the problem)

I built a tarball from https://github.com/DCIT/perl-CryptX/commit/107629dff1ab27597e8e814c7018100b9e8ef8c8 in your repository, then used `cpanm` to install it against a very recent build of blead with Math-BigInt 1.999842 installed.  All tests passed.  Note that I have not tested this against *older* perls where Math-BigInt has been upgraded yet.

**Comment by pjacklam** [comment]
> Note that I have not tested this against _older_ perls where Math-BigInt has been upgraded yet.

I tested CryptX-0.079_002, CryptX-0.079_003, and CryptX-0.079_004 against perl 5.16.0, which comes with Math-BigInt 1.998, and all tests passed.

I then upgraded Math-BigInt on perl 5.16.0 to 1.999842 and tested the same versions of CryptX. Again, all tests passed.

**Comment by sisyphus** [comment]
For me, on Windows, perl-5.39.3 (with Math::BigInt updated to version 1.999842) I see the expected test failures:
```
Test Summary Report
-------------------
t/mbi_ltm_bigfltpm.t              (Wstat: 768 (exited 3) Tests: 2396 Failed: 3)
  Failed tests:  307, 313, 2394
  Non-zero exit status: 3
t/mbi_ltm_bigintpm.t              (Wstat: 1024 (exited 4) Tests: 3718 Failed: 4)
  Failed tests:  701, 713, 733, 745
  Non-zero exit status: 4
Files=136, Tests=24428, 19 wallclock secs ( 0.00 usr +  0.00 sys =  0.00 CPU)
Result: FAIL
Failed 2/136 test programs. 7/24428 subtests failed.
make: *** [Makefile:1798: test_dynamic] Error 255
```
Probably unrelated to this particular issue, but CryptX-0.079_005 is failing dreadfully on the same build of perl, with many segfaults:
```
Test Summary Report
-------------------
t/auth_enc_ccm.t                  (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 15 tests but ran 0.
t/auth_enc_ccm_test_vector_ltc.t  (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 16 tests but ran 0.
t/auth_enc_eax.t                  (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 14 tests but ran 0.
t/auth_enc_eax_test_vector_ltc.t  (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 56 tests but ran 0.
t/auth_enc_gcm.t                  (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 14 tests but ran 0.
t/auth_enc_gcm_test_vector_ltc.t  (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 42 tests but ran 0.
t/auth_enc_ocb.t                  (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 12 tests but ran 0.
t/auth_enc_ocb_test_vectors_ietf.t (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 51 tests but ran 0.
t/cipher_aes.t                    (Wstat: 1280 (exited 5) Tests: 20 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 38 tests but ran 20.
t/cipher_aes_test_vectors_bc.t    (Wstat: 1280 (exited 5) Tests: 1 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 25 tests but ran 1.
t/cipher_test_vectors_ltc.t       (Wstat: 1280 (exited 5) Tests: 50 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 2000 tests but ran 50.
t/cipher_test_vectors_openssl.t   (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 356 tests but ran 0.
t/digest_chaes.t                  (Wstat: 1280 (exited 5) Tests: 4 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 76 tests but ran 4.
t/digest_test_vectors_ltc.t       (Wstat: 1280 (exited 5) Tests: 2 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 1739 tests but ran 2.
t/mac_f9.t                        (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 82 tests but ran 0.
t/mac_hmac_test_vectors_ltc.t     (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 1739 tests but ran 0.
t/mac_omac.t                      (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 82 tests but ran 0.
t/mac_omac_test_vectors_ltc.t     (Wstat: 1280 (exited 5) Tests: 17 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 452 tests but ran 17.
t/mac_pelican.t                   (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 82 tests but ran 0.
t/mac_pmac.t                      (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 82 tests but ran 0.
t/mac_pmac_test_vectors_ltc.t     (Wstat: 1280 (exited 5) Tests: 17 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 452 tests but ran 17.
t/mac_xcbc.t                      (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 82 tests but ran 0.
t/mode_cbc.t                      (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 314 tests but ran 0.
t/mode_cfb.t                      (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 12 tests but ran 0.
t/mode_ctr.t                      (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 24 tests but ran 0.
t/mode_ecb.t                      (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 266 tests but ran 0.
t/mode_ofb.t                      (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 12 tests but ran 0.
t/pk_enc_pem.t                    (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 27 tests but ran 0.
t/prng_fortuna.t                  (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 19 tests but ran 0.
t/prng_yarrow.t                   (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 19 tests but ran 0.
t/sshkey.t                        (Wstat: 1280 (exited 5) Tests: 13 Failed: 0)
  Non-zero exit status: 5
  Parse errors: Bad plan.  You planned 341 tests but ran 13.
Files=137, Tests=16005, 126 wallclock secs ( 0.00 usr +  0.03 sys =  0.03 CPU)
Result: FAIL
Failed 31/137 test programs. 0/16005 subtests failed.
make: *** [Makefile:1798: test_dynamic] Error 5
```
With 0.079_005 (but not 0.079) I see the following compilation warnings near the beginning of the build:
```
ltc/ciphers/aes/aes.c: In function 'rijndael_setup':
ltc/ciphers/aes/aes.c:116:17: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  116 |     K = (void*)((unsigned long)&skey->rijndael.K[15] & (~0xFuL));
      |                 ^
ltc/ciphers/aes/aes.c:116:9: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  116 |     K = (void*)((unsigned long)&skey->rijndael.K[15] & (~0xFuL));
      |         ^
........

ltc/ciphers/aes/aesni.c: In function 'aesni_setup':
ltc/ciphers/aes/aesni.c:64:16: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   64 |    K = (void*)((unsigned long)&skey->rijndael.K[15] & (~0xFuL));
      |                ^
ltc/ciphers/aes/aesni.c:64:8: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   64 |    K = (void*)((unsigned long)&skey->rijndael.K[15] & (~0xFuL));
      |
```

Cheers,
Rob

**Comment by karel-m** [comment]
@sisyphus this is an unrelated issue caused by enabled AES-NI + troubles with unaligned dynamically allocated memory. AES-NI requires 16B alignment which works fine with malloc(..) from glibc; however, on MS Windows it is more complicated.

**Comment by jkeenan** [comment]
With Math::BigInt updated to version 1.999842 and CryptX now up to version 0.080, [CPANtester results](http://fast-matrix.cpantesters.org/?dist=CryptX) are looking good.  I plan to close this ticket in a few days unless there is serious objection.

**Comment by jkeenan** [comment]
> With Math::BigInt updated to version 1.999842 and CryptX now up to version 0.080, [CPANtester results](http://fast-matrix.cpantesters.org/?dist=CryptX) are looking good. I plan to close this ticket in a few days unless there is serious objection.

[CPANtester results for CryptX-0.080](http://fast-matrix.cpantesters.org/?dist=CryptX%200.080) continue to look good.  The only failures being reported pre-date recent changes to Math::BigInt or core and were [reported upstream back in May](https://github.com/DCIT/perl-CryptX/issues/90).  So this ticket is closable.  Thanks to all who examined this problem, but in particular to @pjacklam and @karel-m who did the heavy lifting with respect to code revisions.
