### ISSUE TITLE
Getopt::Long 'rgbcolor=i{3}' calls sub three times

### ISSUE THREAD

**Issue by jimav** [Perl/perl5#21514]
Getopt::Long version 2.54

If the experimental {number} option is used but the referent is a subref, the sub is called multiple times, once for each value.  It is not documented how the sub should be called, but this doesn't seem right.  

I can guess that the new feature was implemented by faking multiple separate options, but it would be nice if it could do so while collecting results in a temp array and calling the real sub once, passing a ref to the array in `$_[1]`.  That way, if the user provides a sub it can get all values at once.
```
#!/usr/bin/perl
use strict; use warnings;
use Data::Dumper qw/Dumper/;
use Getopt::Long qw/GetOptions/;
sub mydumper($) { Data::Dumper->new([$_[0]])->Terse(1)->Dump };

@ARGV = ("--rgb", 111, 222, 333);
GetOptions(
  "rgb=s{3}"  => sub{
                   print "rgb sub called with \$_[0]=$_[0] (stringified)\n";
                   print "   \$_[1]=", mydumper($_[1]);
                   print "   \$_[2]=", mydumper($_[2]);
                 }
) or die;
```
Output:
```
rgb sub called with $_[0]=rgb (stringified)
   $_[1]=111
   $_[2]=undef
rgb sub called with $_[0]=rgb (stringified)
   $_[1]=222
   $_[2]=undef
rgb sub called with $_[0]=rgb (stringified)
   $_[1]=333
   $_[2]=undef
```

**Comment by Grinnz** [comment]
Getopt::Long is maintained on CPAN, its issue tracker can be found here: https://github.com/sciurius/perl-Getopt-Long/issues

**Comment by jimav** [comment]
Sorry.
https://github.com/sciurius/perl-Getopt-Long/issues/19
