### ISSUE TITLE
BBC: Blead Breaks Devel::Size

### ISSUE THREAD

**Issue by cjg-cguevara** [Perl/perl5#21522]
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.43 running under perl 5.39.4.

-----------------------------------------------------------------

BBC: Blead Breaks Devel::Size

Please see http://fast-matrix.cpantesters.org/?dist=Devel::Size

---
**Flags**
- category=core
- severity=low
---
**Perl configuration**
```
Site configuration information for perl 5.39.4:

Configured by cpan at Tue Sep 26 14:11:09 EDT 2023.

Summary of my perl5 (revision 5 version 39 subversion 4) configuration:
  Commit id: b5f24b1f49b3a977a4b039f4bf3a593941351661
  Platform:
    osname=linux
    osvers=6.1.55-0-lts
    archname=x86_64-linux
    uname='linux cjg-alpine3 6.1.55-0-lts #1-alpine smp preempt_dynamic sun, 24 sep 2023 23:14:02 +0000 x86_64 linux '
    config_args='-des -Dprefix=/home/cpan/bin/perl -Dscriptdir=/home/cpan/bin/perl/bin -Dusedevel -Duse64bitall'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64'
    optimize='-O2'
    cppflags='-D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong'
    ccversion=''
    gccversion='12.2.1 20220924'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/lib /usr/local/lib /lib
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/usr/lib/libc.a
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


---
@INC for perl 5.39.4:
    /home/cpan/bin/perl/lib/site_perl/5.39.4/x86_64-linux
    /home/cpan/bin/perl/lib/site_perl/5.39.4
    /home/cpan/bin/perl/lib/5.39.4/x86_64-linux
    /home/cpan/bin/perl/lib/5.39.4

---
Environment for perl 5.39.4:
    HOME=/home/cpan
    LANG=C.UTF-8
    LANGUAGE (unset)
    LC_COLLATE=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash
```

**Comment by mauke** [comment]
```
Output from '/usr/bin/make test':

"/home/cpan/bin/perl/bin/perl5.39.4" -MExtUtils::Command::MM -e 'cp_nonempty' -- Size.bs blib/arch/auto/Devel/Size/Size.bs 644
PERL_DL_NONLAZY=1 "/home/cpan/bin/perl/bin/perl5.39.4" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/basic.t ....... ok

#   Failed test 'CvOUTSIDE is now NULL on cloned closures, unless they have eval'
#   at t/code.t line 101.
#     '25271'
#         >
#     '25511'
# Looks like you failed 1 test of 20.
t/code.t ........ 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/20 subtests 
```
Sounds like commit 386907f061c1812ecaa5f3c88d9f729828408097, Revert "[perl #89544] Non-eval closures don’t need CvOUTSIDE".
@tonycoz ?

**Comment by jkeenan** [comment]
Bisection confirms that the first bad commit is 386907f061c1812ecaa5f3c88d9f729828408097.

**Comment by tonycoz** [comment]
This needs to be fixed downstream.  I've opened https://rt.cpan.org/Ticket/Display.html?id=149902

**Comment by leonerd** [comment]
@nwc10 - Can you take a look at this one? The linked ticket on RT appears to contain a patch to fix it so hopefully it's an easy one.

**Comment by nwc10** [comment]
I'm about to be offline until Easter Monday, so I certainly won't have anything uploaded by then.

However, tea, power and gravity work where I'm going, so if I pack properly I hope to have time while I'm incommunicado.

**Comment by nwc10** [comment]
Sorry for the delay. A lot of things happened. I was still writing talks on the train to http://act.yapc.eu/gpw2024/

We now have http://matrix.cpantesters.org/?dist=Devel-Size+0.83_50 but it's currently blank

**Comment by mauke** [comment]
http://fast-matrix.cpantesters.org/?dist=Devel-Size%200.83_50 is looking good.

**Comment by nwc10** [comment]
Well, my PAUSE session says that 0.84 is indexed - ie https://pause.perl.org/pause/authenquery?ACTION=show_files

But nothing else seems to have noticed it yet. I'm not sure what I can do, other than hope that someone at PTS notices this and knows what is going on.

**Comment by haarg** [comment]
MetaCPAN is currently having some hardware problems, which is probably why it isn't showing up elsewhere. Will hopefully be resolved soon.

But with the new release out, we can consider this complete.

Thanks!

**Comment by jkeenan** [comment]
> Well, my PAUSE session says that 0.84 is indexed - ie https://pause.perl.org/pause/authenquery?ACTION=show_files
> 
> But nothing else seems to have noticed it yet. I'm not sure what I can do, other than hope that someone at PTS notices this and knows what is going on.

@nwc10, you seem to have been caught in the same mess I've been posting about:
https://www.nntp.perl.org/group/perl.perl5.porters/2024/03/msg268095.html;
https://www.nntp.perl.org/group/perl.cpan.workers/2024/04/msg1681.html

Let's hope this gets fixed soon.
