### ISSUE TITLE
Intermittent failure of Perl ptest t/op/sigsystem

### ISSUE THREAD

**Issue by wlyu2** [Perl/perl5#21546]
This bug is found and tracked in the Yocto Project (Bug 15136):
https://bugzilla.yoctoproject.org/show_bug.cgi?id=15136

Alexandre Belloni provided the following error output in the above link:
> `# Failed test 3 - Reaped only one process at op/sigsystem.t line 42`
> `FAIL: t/op/sigsystem`

Note that this ptest failure is intermittent. 

This issue is potentially related to the following two currently open issues in Perl:
- https://github.com/Perl/perl5/issues/12802
- https://github.com/Perl/perl5/issues/12896

**Comment by jkeenan** [comment]
p.r. https://github.com/Perl/perl5/pull/21547 has been submitted with reference to this.

**Comment by jkeenan** [comment]
Closed by manual processing of https://github.com/Perl/perl5/pull/21547 in 75d974a58c
