### ISSUE TITLE
Parentheses around array slices work, but not around hash slices

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#21565]
Parentheses around array slices work as expected as shown on line **5** versus line **4**, but not around hash slices as illustrated on line **9** versus line **8**.  May I urge that the two paradigms should be consistent to minimize surprise?

![perlArrayHashSlicesWithParentheses](https://github.com/Perl/perl5/assets/7548378/f017b18e-8033-428b-a372-22b83a22b730)

The code in the above image reproduced below as text:

```
use v5.34;

my $a = [1, 2, 3, 4, 5];
say( @$a [qw(1 2 3)]);                     # 234
say((@$a)[qw(1 2 3)]);                     # 234

my $h = {a=>1, b=>2, c=>3, d=>4, e=>5};
say( @$h {qw(b c d)});                     # 234
say((@$h){qw(b c d)});                     # syntax error at line 9, near "){"
```

**Comment by Grinnz** [comment]
This is not a bug, but one of the few cases where parentheses are syntactically significant. The `(list)[indices]` syntax is a list slice, which works similarly enough to array slicing where you get the proper result in your example. There is no equivalent `(list){keys}` syntax. See https://perldoc.perl.org/perldata#Slices
