### ISSUE TITLE
Cannot forward declare my sub.

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#21587]
Apparently one cannot forward declare a **my** **sub**:

![error](https://github.com/Perl/perl5/assets/7548378/0c423d95-92bc-4d5c-9793-2efa8d93f693)

Code :
```
#!/usr/bin/perl
require v5.34;
my sub aaa();
my sub aaa() {say STDERR "aaa"}; # "my" subroutine &aaa masks earlier declaration in same scope.
```

Please allow me to urge that it should be possible to forward declare a **my sub**.

**Comment by mauke** [comment]
IIRC you can do it, but the syntax is bizarre:

```perl
my sub aaa ();
sub aaa () { }
```

**Comment by mauke** [comment]
It's documented in `perldoc perlsub`:

> It is possible to predeclare a lexical subroutine.  The `sub foo {...}` subroutine definition syntax respects any previous `my sub;` or `state sub;` declaration. [...]

> ```perl
>     my sub baz;         # predeclaration
>     sub baz {           # define the "my" sub
> ```

**Comment by jkeenan** [comment]
> It's documented in `perldoc perlsub`:
> 
> > It is possible to predeclare a lexical subroutine.  The `sub foo {...}` subroutine definition syntax respects any previous `my sub;` or `state sub;` declaration. [...]
> 
> > ```perl
> >     my sub baz;         # predeclaration
> >     sub baz {           # define the "my" sub
> > ```

It appears that @mauke has responded to the OP's concern, so I'm labeling this ticket as Closable.  I will close it in a few days unless there is serious objection.

**Comment by tonycoz** [comment]
I also think this is closable, closing.
