### ISSUE TITLE
`perl5db.pl`: Indirect syntax

### ISSUE THREAD

**Issue by rwp0** [Perl/perl5#21589]
https://github.com/Perl/perl5/blob/blead/lib/perl5db.pl#L874

Found via `/import [A-Z]+::/` GH search.

**Comment by rwp0** [comment]
Planning to create a corresponding PR next

**Comment by jkeenan** [comment]
> https://github.com/Perl/perl5/blob/blead/lib/perl5db.pl#L874
> 
> Found via `/import [A-Z]+::/` GH search.

I think there's something conceptually amiss in this p.r., as well as in https://github.com/Perl/perl5/issues/21590.  The Subject line suggests that the problem or deficiency is `Indirect syntax`.  However, AFAICT this string does not occur anywhere in the Perl core distribution.
```
$ ack -i 'indirect syntax' .
$ 
```
It is true that the `require MODULE; import MODULE (sub1, sub2, ...)` is somewhat old-school, but I can't recall that it was ever designated as "indirect syntax."  This syntax is not listed in `perldoc perldeprecation`, nor have I heard that it is officially "discouraged."  Has there been a discussion on the mailing list about discouraging this syntax?  If not, then that's where such a discussion should start.

**Comment by rwp0** [comment]
> I think there's something conceptually amiss in this p.r., as well as in https://github.com/Perl/perl5/issues/21590. The Subject line suggests that the problem or deficiency is Indirect syntax. However, AFAICT this string does not occur anywhere in the Perl core distribution.
> 
> $ ack -i 'indirect syntax' .
> $ 
> It is true that the require MODULE; import MODULE (sub1, sub2, ...) is somewhat old-school, but I can't recall that it was ever designated as "indirect syntax." This syntax is not listed in perldoc perldeprecation, nor have I heard that it is officially "discouraged." Has there been a discussion on the mailing list about discouraging this syntax? If not, then that's where such a discussion should start.

That's one place where it's discouraged:

https://perldoc.perl.org/perlobj#Indirect-Object-Syntax

> We recommend that you avoid this syntax, for several reasons.
>
> ... (the list goes on) ...

"indirect syntax" here is just a short name for Indirect **Object** Syntax as manifested in [indirect](https://metacpan.org/pod/indirect) distribution or the [`indirect`](https://perldoc.perl.org/feature#The-'indirect'-feature)feature of the core Perl.

---

And there's another good implication of discouragement there:

> This feature is present in older feature version bundles, but was **removed from the :5.36 bundle**; so a [use VERSION](https://perldoc.perl.org/perlfunc#use-VERSION) declaration of v5.36 or above will also disable the feature.
> 
> use v5.36;
> indirect object syntax is no longer available

ie. the syntax discouraged by the way of removing this syntax from the recent version bundles.

And since we aim to support 5.36 and 5.38 only (as for now) we shouldn't be using it in core, I think.

**Comment by jwrightecs** [comment]
Should probably add a note to perlfunc/import about indirect object syntax or remove perlfunc/import completely as it has the syntax as 
`import LIST`
