### ISSUE TITLE
cpan can download tar.gz but can not install (cpan stuck)

### ISSUE THREAD

**Issue by hfl112** [Perl/perl5#21588]
Module:
perl - 5.26.2
cpan

**Description**

cpan stucked installing packages:
```
$ cpan
Loading internal null logger. Install Log::Log4perl for logging messages
Terminal does not support AddHistory.
CPAN.pm panic: Found invalid lockfile '/home/hef/.cpan/.lock', please remove. Cannot proceed.

```
then I remove this .cpan and try cpan agian, it stucked here forever:
```$ cpan
Loading internal null logger. Install Log::Log4perl for logging messages

CPAN.pm requires configuration, but most of it can be done automatically.
If you answer 'no' below, you will enter an interactive dialog for each
configuration option instead.

Would you like to configure as much as possible automatically? [yes] yes

Use of uninitialized value $what in concatenation (.) or string at /home/hef/Tools/miniconda3/lib/5.26.2/App/Cpan.pm line 669, <STDIN> line 1.
 <install_help>

Warning: You do not have write permission for Perl library directories.

To install modules, you need to configure a local Perl library directory or
escalate your privileges.  CPAN can help you by bootstrapping the local::lib
module or by configuring itself to use 'sudo' (if available).  You may also
resolve this problem manually if you need to customize your setup.

What approach do you want?  (Choose 'local::lib', 'sudo' or 'manual')
 [local::lib] local::lib


Autoconfiguration complete.

Attempting to bootstrap local::lib...

Writing /home/hef/.cpan/CPAN/MyConfig.pm for bootstrap...
commit: wrote '/home/hef/.cpan/CPAN/MyConfig.pm'
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/01mailrc.txt.gz
Reading '/home/hef/.cpan/sources/authors/01mailrc.txt.gz'
............................................................................DONE
Fetching with HTTP::Tiny:
http://www.cpan.org/modules/02packages.details.txt.gz
Reading '/home/hef/.cpan/sources/modules/02packages.details.txt.gz'
  Database was generated on Wed, 25 Oct 2023 17:41:01 GMT
  HTTP::Date not available
..............
  New CPAN.pm version (v2.36) available.
  [Currently running version is v2.18]
  You might want to try
    install CPAN
    reload cpan
  to both upgrade CPAN.pm and run the new version without leaving
  the current session.


..............................................................DONE
Fetching with HTTP::Tiny:
http://www.cpan.org/modules/03modlist.data.gz
Reading '/home/hef/.cpan/sources/modules/03modlist.data.gz'
DONE
Writing /home/hef/.cpan/Metadata
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/H/HA/HAARG/local-lib-2.000029.tar.gz

```
then I tried perl -MCPAN -e "install Log::Log4perl", I can see the tar.gz have been downloaded but the it didn't start to install the package
```
Reading '/home/hef/.cpan/Metadata'
  Database was generated on Wed, 25 Oct 2023 13:17:02 GMT
Running install for module 'Log::Log4perl'
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/id/E/ET/ETJ/Log-Log4perl-1.57.tar.gz
```

**Steps to Reproduce**

I installed perl by conda.
and cpan didn't work even if I upgraded perl to the lastest version
**Expected behavior**

**Perl configuration**

```
Summary of my perl5 (revision 5 version 26 subversion 2) configuration:

  Platform:
    osname=linux
    osvers=4.15.0-1098-azure
    archname=x86_64-linux-thread-multi
    uname='linux 2f4e83381d95 4.15.0-1098-azure #109~16.04.1-ubuntu smp wed sep 30 18:53:14 utc 2020 x86_64 x86_64 x86_64 gnulinux '
    config_args='-de -Dprefix=/home/hef/Tools/miniconda3 -Dusethreads -Duserelocatableinc -Dcccdlflags=-fPIC -Dldflags=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/hef/Tools/miniconda3/lib -Wl,-rpath-link,/home/hef/Tools/miniconda3/lib -L/home/hef/Tools/miniconda3/lib -Ddefault_inc_excludes_dot=n -Dcc=/home/hef/Tools/miniconda3/bin/..//bin/x86_64-conda-linux-gnu-gcc -Dar=/home/hef/Tools/miniconda3/bin/..//bin/x86_64-conda-linux-gnu-ar -Dlddlflags=-shared -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/hef/Tools/miniconda3/lib -Wl,-rpath-link,/home/hef/Tools/miniconda3/lib -L/home/hef/Tools/miniconda3/lib -Dsysroot=/home/hef/Tools/miniconda3/bin/..//x86_64-conda-linux-gnu/sysroot'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=undef
    bincompat5005=undef
  Compiler:
    cc='/home/hef/Tools/miniconda3/bin/..//bin/x86_64-conda-linux-gnu-gcc'
    ccflags ='-D_REENTRANT -D_GNU_SOURCE --sysroot=/home/hef/Tools/miniconda3/bin/..//x86_64-conda-linux-gnu/sysroot -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='--sysroot=/home/hef/Tools/miniconda3/bin/..//x86_64-conda-linux-gnu/sysroot -D_REENTRANT -D_GNU_SOURCE --sysroot=/home/hef/Tools/miniconda3/bin/..//x86_64-conda-linux-gnu/sysroot -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong'
    ccversion=''
    gccversion='7.5.0'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='/home/hef/Tools/miniconda3/bin/..//bin/x86_64-conda-linux-gnu-gcc'
    ldflags ='-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/hef/Tools/miniconda3/lib -Wl,-rpath-link,/home/hef/Tools/miniconda3/lib -L/home/hef/Tools/miniconda3/lib -fstack-protector-strong'
    libpth=/home/hef/Tools/miniconda3/bin/..//bin/../lib/gcc/x86_64-conda-linux-gnu/7.5.0/include-fixed /home/hef/Tools/miniconda3/bin/..//x86_64-conda-linux-gnu/sysroot/usr/lib /home/hef/Tools/miniconda3/bin/..//x86_64-conda-linux-gnu/sysroot/lib /home/hef/Tools/miniconda3/bin/..//x86_64-conda-linux-gnu/sysroot/lib64 /home/hef/Tools/miniconda3/bin/..//x86_64-conda-linux-gnu/sysroot/usr/lib64
    libs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc
    libc=
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.12'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC --sysroot=/home/hef/Tools/miniconda3/bin/..//x86_64-conda-linux-gnu/sysroot'
    lddlflags='-shared -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/home/hef/Tools/miniconda3/lib -Wl,-rpath-link,/home/hef/Tools/miniconda3/lib -L/home/hef/Tools/miniconda3/lib --sysroot /home/hef/Tools/miniconda3/bin/..//x86_64-conda-linux-gnu/sysroot -fstack-protector-strong'


Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_ALL
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
    USE_REENTRANT_API
  Built under linux
  Compiled at Oct 28 2020 22:51:00
  @INC:
    /home/hef/Tools/miniconda3/lib/site_perl/5.26.2/x86_64-linux-thread-multi
    /home/hef/Tools/miniconda3/lib/site_perl/5.26.2
    /home/hef/Tools/miniconda3/lib/5.26.2/x86_64-linux-thread-multi
    /home/hef/Tools/miniconda3/lib/5.26.2
    .

```

**Comment by hfl112** [comment]
interestingly, I can cd to cpan folder and manually install this tar.gz:
```$ cd local-lib-2.000029/

$ perl Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for local::lib
Writing MYMETA.yml and MYMETA.json
LaLaLa_Genie 13:49   ~/.cpan/sources/authors/id/H/HA/HAARG/local-lib-2.000029
$ make
cp lib/local/lib.pm blib/lib/local/lib.pm
cp lib/POD2/PT_BR/local/lib.pod blib/lib/POD2/PT_BR/local/lib.pod
cp lib/POD2/DE/local/lib.pod blib/lib/POD2/DE/local/lib.pod
cp lib/lib/core/only.pm blib/lib/lib/core/only.pm
Manifying 4 pod documents
LaLaLa_Genie 13:49   ~/.cpan/sources/authors/id/H/HA/HAARG/local-lib-2.000029
$ make install
Manifying 4 pod documents
Installing /home/hef/Tools/miniconda3/lib/site_perl/5.26.2/local/lib.pm
Installing /home/hef/Tools/miniconda3/lib/site_perl/5.26.2/POD2/PT_BR/local/lib.pod
Installing /home/hef/Tools/miniconda3/lib/site_perl/5.26.2/POD2/DE/local/lib.pod
Installing /home/hef/Tools/miniconda3/lib/site_perl/5.26.2/lib/core/only.pm
Installing /home/hef/Tools/miniconda3/man/man3/POD2::DE::local::lib.3
Installing /home/hef/Tools/miniconda3/man/man3/POD2::PT_BR::local::lib.3
Installing /home/hef/Tools/miniconda3/man/man3/lib::core::only.3
Installing /home/hef/Tools/miniconda3/man/man3/local::lib.3
Appending installation info to /home/hef/Tools/miniconda3/lib/5.26.2/x86_64-linux-thread-multi/perllocal.pod
```

**Comment by jkeenan** [comment]
> Module: perl - 5.26.2 cpan
> 
> **Description**
> 
> cpan stucked installing packages:
> 

There is no bug in `perl` or in `cpan` here.  You have likely misunderstood how to start the `cpan` shell program and then work inside it.


> ```
> $ cpan
> Loading internal null logger. Install Log::Log4perl for logging messages
> Terminal does not support AddHistory.
> CPAN.pm panic: Found invalid lockfile '/home/hef/.cpan/.lock', please remove. Cannot proceed.
> ```
> 

That suggests that this was not your first attempt at using `cpan`, but you figured out how to proceed.  Good.

> then I remove this .cpan and try cpan agian, it stucked here forever:
> 
> ```
> Loading internal null logger. Install Log::Log4perl for logging messages
> 
> CPAN.pm requires configuration, but most of it can be done automatically.
> If you answer 'no' below, you will enter an interactive dialog for each
> configuration option instead.
> 
> Would you like to configure as much as possible automatically? [yes] yes
> 
> Use of uninitialized value $what in concatenation (.) or string at /home/hef/Tools/miniconda3/lib/5.26.2/App/Cpan.pm line 669, <STDIN> line 1.
>  <install_help>
> 
> Warning: You do not have write permission for Perl library directories.
> 
> To install modules, you need to configure a local Perl library directory or
> escalate your privileges.  CPAN can help you by bootstrapping the local::lib
> module or by configuring itself to use 'sudo' (if available).  You may also
> resolve this problem manually if you need to customize your setup.
> 
> What approach do you want?  (Choose 'local::lib', 'sudo' or 'manual')
>  [local::lib] local::lib
> 
> 
> Autoconfiguration complete.
> 
> Attempting to bootstrap local::lib...
> 
> Writing /home/hef/.cpan/CPAN/MyConfig.pm for bootstrap...
> commit: wrote '/home/hef/.cpan/CPAN/MyConfig.pm'
> Fetching with HTTP::Tiny:
> http://www.cpan.org/authors/01mailrc.txt.gz
> Reading '/home/hef/.cpan/sources/authors/01mailrc.txt.gz'
> ............................................................................DONE
> Fetching with HTTP::Tiny:
> http://www.cpan.org/modules/02packages.details.txt.gz
> Reading '/home/hef/.cpan/sources/modules/02packages.details.txt.gz'
>   Database was generated on Wed, 25 Oct 2023 17:41:01 GMT
>   HTTP::Date not available
> ..............
>   New CPAN.pm version (v2.36) available.
>   [Currently running version is v2.18]
>   You might want to try
>     install CPAN
>     reload cpan
>   to both upgrade CPAN.pm and run the new version without leaving
>   the current session.
> 
> 
> ..............................................................DONE
> Fetching with HTTP::Tiny:
> http://www.cpan.org/modules/03modlist.data.gz
> Reading '/home/hef/.cpan/sources/modules/03modlist.data.gz'
> DONE
> Writing /home/hef/.cpan/Metadata
> Fetching with HTTP::Tiny:
> http://www.cpan.org/authors/id/H/HA/HAARG/local-lib-2.000029.tar.gz
> ```
> 

It's not clear from what you have pasted here whether or not at this point you exited from the `cpan` shell program.  If you were still in the `cpan` shell program, the next correct action would be to invoke the following command at the `cpan` prompt:

    > install Log::Log4perl

If, however, you had exited from the `cpan` shell program and were back at the terminal's command-prompt, then `perl -MCPAN -e "install Log::Log4perl"` should have worked, *i.e.,* you should have downloaded the tarball and installed Log::Log4perl.  I recommend that you study the `cpan` shell program's own documentation, which can be invoked with either:
```
$ perldoc cpan
```
or
```
$ cpan -h
```
You subsequently chanced upon yet another way to work with the `cpan` shell, which is to `cd` to a directory in which you have unpacked a tarball and there called `cpan .`.  This, too, is documented via the invocations above.

**Comment by hfl112** [comment]
> > Module: perl - 5.26.2 cpan
> > **Description**
> > cpan stucked installing packages:
> 
> There is no bug in `perl` or in `cpan` here. You have likely misunderstood how to start the `cpan` shell program and then work inside it.
> 
> > ```
> > $ cpan
> > Loading internal null logger. Install Log::Log4perl for logging messages
> > Terminal does not support AddHistory.
> > CPAN.pm panic: Found invalid lockfile '/home/hef/.cpan/.lock', please remove. Cannot proceed.
> > ```
> 
> That suggests that this was not your first attempt at using `cpan`, but you figured out how to proceed. Good.
> 
> > then I remove this .cpan and try cpan agian, it stucked here forever:
> > ```
> > Loading internal null logger. Install Log::Log4perl for logging messages
> > 
> > CPAN.pm requires configuration, but most of it can be done automatically.
> > If you answer 'no' below, you will enter an interactive dialog for each
> > configuration option instead.
> > 
> > Would you like to configure as much as possible automatically? [yes] yes
> > 
> > Use of uninitialized value $what in concatenation (.) or string at /home/hef/Tools/miniconda3/lib/5.26.2/App/Cpan.pm line 669, <STDIN> line 1.
> >  <install_help>
> > 
> > Warning: You do not have write permission for Perl library directories.
> > 
> > To install modules, you need to configure a local Perl library directory or
> > escalate your privileges.  CPAN can help you by bootstrapping the local::lib
> > module or by configuring itself to use 'sudo' (if available).  You may also
> > resolve this problem manually if you need to customize your setup.
> > 
> > What approach do you want?  (Choose 'local::lib', 'sudo' or 'manual')
> >  [local::lib] local::lib
> > 
> > 
> > Autoconfiguration complete.
> > 
> > Attempting to bootstrap local::lib...
> > 
> > Writing /home/hef/.cpan/CPAN/MyConfig.pm for bootstrap...
> > commit: wrote '/home/hef/.cpan/CPAN/MyConfig.pm'
> > Fetching with HTTP::Tiny:
> > http://www.cpan.org/authors/01mailrc.txt.gz
> > Reading '/home/hef/.cpan/sources/authors/01mailrc.txt.gz'
> > ............................................................................DONE
> > Fetching with HTTP::Tiny:
> > http://www.cpan.org/modules/02packages.details.txt.gz
> > Reading '/home/hef/.cpan/sources/modules/02packages.details.txt.gz'
> >   Database was generated on Wed, 25 Oct 2023 17:41:01 GMT
> >   HTTP::Date not available
> > ..............
> >   New CPAN.pm version (v2.36) available.
> >   [Currently running version is v2.18]
> >   You might want to try
> >     install CPAN
> >     reload cpan
> >   to both upgrade CPAN.pm and run the new version without leaving
> >   the current session.
> > 
> > 
> > ..............................................................DONE
> > Fetching with HTTP::Tiny:
> > http://www.cpan.org/modules/03modlist.data.gz
> > Reading '/home/hef/.cpan/sources/modules/03modlist.data.gz'
> > DONE
> > Writing /home/hef/.cpan/Metadata
> > Fetching with HTTP::Tiny:
> > http://www.cpan.org/authors/id/H/HA/HAARG/local-lib-2.000029.tar.gz
> > ```
> 
> It's not clear from what you have pasted here whether or not at this point you exited from the `cpan` shell program. If you were still in the `cpan` shell program, the next correct action would be to invoke the following command at the `cpan` prompt:
> 
> ```
> > install Log::Log4perl
> ```
> 
> If, however, you had exited from the `cpan` shell program and were back at the terminal's command-prompt, then `perl -MCPAN -e "install Log::Log4perl"` should have worked, _i.e.,_ you should have downloaded the tarball and installed Log::Log4perl. I recommend that you study the `cpan` shell program's own documentation, which can be invoked with either:
> 
> ```
> $ perldoc cpan
> ```
> 
> or
> 
> ```
> $ cpan -h
> ```
> 
> You subsequently chanced upon yet another way to work with the `cpan` shell, which is to `cd` to a directory in which you have unpacked a tarball and there called `cpan .`. This, too, is documented via the invocations above.

Thanks jkeenan, you are correct.
it's not due to perl or cpan itself, it's actually because our server got sth wrong in writing
