### ISSUE TITLE
`Benchmark.pm`: Indirect syntax 

### ISSUE THREAD

**Issue by rwp0** [Perl/perl5#21590]
https://github.com/Perl/perl5/blob/blead/lib/Benchmark.pm#L497

**Fact**: Found via `/import [A-Z]+::/` GH search.

Planning to create a corresponding PR next.

**Comment by rwp0** [comment]
There seems to be only two non-test instances of the indirect syntax according to the regex search in the entire Perl distribution.

**Comment by guest20** [comment]
Your regex won't match `import warnings` as seen here: https://github.com/Perl/perl5/blob/4b5c1775cec6d4fe978b19274b2c24098bb9f151/cpan/Digest-SHA/Makefile.PL#L19

**Comment by rwp0** [comment]
> Your regex won't match `import warnings` as seen here:
> 
> https://github.com/Perl/perl5/blob/4b5c1775cec6d4fe978b19274b2c24098bb9f151/cpan/Digest-SHA/Makefile.PL#L19

Yeah, that was a quick one, maybe I should make it case-insensitive at some point in time, but I'm good with avoiding pragmas for now (and they're all lowercase).

---

Also [Digest-SHA ](https://metacpan.org/dist/Digest-SHA)is a separately developed CPAN distribution (that happens to be in core too) that will need to be upstream-synced by the way of a collaboration with its maintainer ([Mark Shelor](https://metacpan.org/author/MSHELOR)).

**Comment by guest20** [comment]
`warnings` was just the first example I came up with for a package who's name:
- does not include capitals 
- does not include `::`

Package names can contain `_` too, but since you're not shipping this regex in a tool to help people un-indirect their code, it's likely fine to gloss over that too.

**Comment by nicomen** [comment]
Modules can also contain `'` as a separator. Although I think I have sent in pull requests to migrate all of them to `::` in perl5 

This regex might help even further with a few false positives, depending on how deep you want to do changes:

`✔  16:31 ~/projects/perl5 [ blead | …606 ] $ ack -t perl -T perltest '(;|,|^)\s*import .*?;$' | less # drop -T perltest to include .t files`

```
utils/enc2xs
9:    require Config; import Config;

t/re/fold_grind.pl
15:    require Config; import Config;

t/loc_tools.pl
23:eval { require POSIX; import POSIX 'locale_h'; };

cpan/Encode/t/rt.pl
13:    require Config; import Config;

cpan/Encode/bin/enc2xs
6:    require Config; import Config;

cpan/Pod-Checker/t/pod/testpchk.pl
12:   import TestCompare;

cpan/Test-Simple/lib/Test/More.pm
148:  use Test::More tests => 23, import => ['!fail'];
215:            push @$list, import => [grep $_ ne '$TODO', @EXPORT];

cpan/Digest-SHA/Makefile.PL
19:	eval "require warnings; import warnings";

cpan/IO-Compress/t/compress/generic.pl
17:    my $st = eval { require Test::NoWarnings ;  import Test::NoWarnings; 1; };

cpan/IO-Compress/t/compress/multi.pl
14:        if eval { require Test::NoWarnings ;  import Test::NoWarnings; 1 };

cpan/IO-Compress/t/compress/destroy.pl
18:        if eval { require Test::NoWarnings ;  import Test::NoWarnings; 1 };

cpan/IO-Compress/t/compress/anyunc.pl
15:        if eval { require Test::NoWarnings ;  import Test::NoWarnings; 1 };

cpan/IO-Compress/t/compress/encode.pl
22:    my $st = eval { require Test::NoWarnings ;  import Test::NoWarnings; 1; };

cpan/IO-Compress/t/compress/merge.pl
20:        if eval { require Test::NoWarnings ;  import Test::NoWarnings; 1 };

cpan/IO-Compress/t/compress/any.pl
15:        if eval { require Test::NoWarnings ;  import Test::NoWarnings; 1 };

cpan/IO-Compress/t/compress/newtied.pl
30:        if eval { require Test::NoWarnings ;  import Test::NoWarnings; 1 };

cpan/IO-Compress/t/compress/zlib-generic.pl
14:        if eval { require Test::NoWarnings ;  import Test::NoWarnings; 1 };

cpan/IO-Compress/t/compress/prime.pl
20:        if eval { require Test::NoWarnings ;  import Test::NoWarnings; 1 };

cpan/IO-Compress/t/compress/oneshot.pl
17:        if eval { require Test::NoWarnings ;  import Test::NoWarnings; 1 };

cpan/IO-Compress/t/compress/tied.pl
20:        if eval { require Test::NoWarnings ;  import Test::NoWarnings; 1 };

cpan/IO-Compress/lib/File/GlobMapper.pm
13:        require File::BSDGlob; import File::BSDGlob qw(:glob) ;
19:        require File::Glob; import File::Glob qw(:glob) ;

cpan/Getopt-Long/lib/Getopt/Long.pm
1518:	import Pod::Usage;

dist/threads/lib/threads.pm
59:            import overload ('""' => \&tid);

pod/perlthrtut.pod
189:            import MyMod_threaded;
192:            import MyMod_unthreaded;

pod/perldata.pod
639:"Inf" + 1.  (You can, however, import them from the POSIX extension;

lib/perl5db.pl
874:        import threads::shared qw(share);

lib/File/GlobMapper.pm
13:        require File::BSDGlob; import File::BSDGlob qw(:glob) ;
19:        require File::Glob; import File::Glob qw(:glob) ;

lib/locale.pm
113:            eval { require POSIX; import POSIX 'locale_h'; };

lib/Benchmark.pm
497:	import Time::HiRes qw(time);

lib/Test/More.pm
148:  use Test::More tests => 23, import => ['!fail'];
215:            push @$list, import => [grep $_ ne '$TODO', @EXPORT];

lib/Getopt/Long.pm
1518:	import Pod::Usage;

lib/threads.pm
59:            import overload ('""' => \&tid);
```

**Comment by rwp0** [comment]
Thanks, as we can see most modules are maintained separately on CPAN, and for `Getopt-Long` I've already submitted https://github.com/sciurius/perl-Getopt-Long/pull/20

And this syntax helped me with GitHub (I was initially searching on the Mobile version 🙂):

```
repo:Perl/perl5 /import [A-Z]+::/ -path:*.t #
```

`-path` excludes tests here.

https://gist.github.com/rwp0/bc519f7a51269a71c8e73630d4c63bdd
