### ISSUE TITLE
Unambiguous call incorrectly flagged as syntax error

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#21613]
In the following code the call to **or** is flagged as a syntax error, which is surprising in this context because **or** is clearly being used as a subroutine call.  May I urge that this message should be removed in this context so this otherwise legitimate program can be executed? Likewise the message about ambiguity would also appear to be incorrect and might reasonably be suppressed?
```
use v5.34;

sub or($$) {1}

or(1,1);  # syntax error near "or"
          # Ambiguous call resolved as CORE::or(), qualify as such or use &
```

**Comment by mauke** [comment]
`or` is a keyword. If you really want to call a subroutine whose name is a keyword, the error message tells you how:
```perl
&or(1,1);
```
Unfortunately the use of `&` also overrides the `($$)` prototype. But the general solution is to not name your subroutines after keywords.

**Comment by mauke** [comment]
Here's an example that would silently parse differently under this change:
```perl
print STDERR or (log_err(), abort());
```
Currently this parses as
```perl
print STDERR $_ or log_err(), abort();
```
which is equivalent to
```perl
log_err(), abort() unless print STDERR $_;
```
If we changed the meaning of `or`, this would parse instead as:
```perl
print STDERR &or(log_err(), abort());
```
i.e. the result of calling the `or` subroutine would be printed to `STDERR` and `$_` wouldn't be used.

That's why I'm opposed to making the parsing of `or` context-dependent.

**Comment by guest20** [comment]
How about `::or 1,1`?

**Comment by jkeenan** [comment]
> How about `::or 1,1`?

I can't figure out how that question is pertinent to this ticket.  @mauke has provided a good explanation why we should not make changes with respect to the question raised in this ticket.

Self-assigning for the purpose of closing within 7 days unless a cogent reason is provided to keep it open.

**Comment by jkeenan** [comment]
> > How about `::or 1,1`?
> 
> I can't figure out how that question is pertinent to this ticket. @mauke has provided a good explanation why we should not make changes with respect to the question raised in this ticket.
> 
> Self-assigning for the purpose of closing within 7 days unless a cogent reason is provided to keep it open.

Closing as per schedule.
