### ISSUE TITLE
Variable incorrectly flagged as only being used once.

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#21632]
In the following code the variable **$c** is flagged as only being used once.  But this is not the case as the successful execution of the program demonstrates.  This messages does not appear if one uses **$a** as the variable instead of **$c**. May I therefore urge that this message be suppressed in this context as it is both inconsistent and misleading?  

```
my sub c:lvalue {$c}           # Name "main::c" used only once: possible typo 

c = 'ccc'; say STDERR c.c.c;   # ccccccccc
```

**Comment by Grinnz** [comment]
The 'once' warnings are often misleading but fortunately they are obsolete if you use lexical variables wherever possible. It does not appear for `$a` because this is a special sort variable which you should not be using anyway.

**Comment by Leont** [comment]
Yeah, the warning has a higher false-positive rate than I'd like, but it's doing strictly what it advertises. I would recommend using lexicals which don't have this issue.
