### ISSUE TITLE
malloc_consolidate(): invalid chunk size when running pure Perl code

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#21649]
When running pure Perl code,  Perl terminates with the surprising message:

```
malloc_consolidate(): invalid chunk size
```
as can be seen in:

![PerlDoubleFree](https://github.com/Perl/perl5/assets/7548378/3bb362bc-35b9-44b0-b1cf-988d1cec0f1f)

as shown at:

https://github.com/philiprbrenan/PerlDoubleFree/actions/runs/6923588447/job/18831663179

Possibly this indicates that the problem is not attributable to an external library but to Perl itself?

**Comment by jkeenan** [comment]
> When running pure Perl code, Perl terminates with the surprising message:
> 
> ```
> malloc_consolidate(): invalid chunk size
> ```
> 
> as can be seen in:
> 
> ![PerlDoubleFree](https://user-images.githubusercontent.com/7548378/284097611-3bb362bc-35b9-44b0-b1cf-988d1cec0f1f.png)
> 
> as shown at:
> 
> https://github.com/philiprbrenan/PerlDoubleFree/actions/runs/6923588447/job/18831663179
> 
> Possibly this indicates that the problem is not attributable to an external library but to Perl itself?

Possibly -- but it's up to **you** to demonstrate that it is a defect in the Perl language.

This ticket should be closed.

**Comment by karenetheridge** [comment]
A reproduction case (concise, self-contained code) is needed to go anywhere with this.
