### ISSUE TITLE
Double free during Perl syntax analysis

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#21652]
I am getting a segmentation fault during Perl syntax analysis ( -c ): 

2851 Segmentation fault      (core dumped) perl -c -Idtt/lib -Isvg/lib lib/Silicon/Chip.pm

![PerlDoubleFreeSyntax](https://github.com/Perl/perl5/assets/7548378/35d1310a-44e4-4804-b4f0-d62510955386)

as demonstrated by:

https://github.com/philiprbrenan/PerlDoubleFreeSyntax/actions/runs/6932564051/job/18856802994

**Comment by mauke** [comment]
No code, no instructions, no information. Just a screenshot of a perl process crashing.
What exactly do you expect us to do with this ticket?

**Comment by jkeenan** [comment]
> I am getting a segmentation fault during Perl syntax analysis ( -c ):
> 
> 2851 Segmentation fault (core dumped) perl -c -Idtt/lib -Isvg/lib lib/Silicon/Chip.pm
> 
> ![PerlDoubleFreeSyntax](https://user-images.githubusercontent.com/7548378/284323156-35d1310a-44e4-4804-b4f0-d62510955386.png)
> 
> as demonstrated by:
> 
> https://github.com/philiprbrenan/PerlDoubleFreeSyntax/actions/runs/6932564051/job/18856802994

@philiprbrenan, this ticket is an inappropriate use of https://github.com/Perl/perl5/issues.  This is **not** a Perl help site, *i.e.,* it is not a site one should turn to when one can't figure out what's going wrong with one's program.  It is a site for analyzing problems with the Perl programming language and its ongoing development.  Filing tickets like this one here simply wastes everyone's time, including your own.  Please do not file such tickets here in the future.

**Comment by iabyn** [comment]
On Mon, Nov 20, 2023 at 08:57:50AM -0800, James E Keenan wrote:
> @philiprbrenan, this ticket is an inappropriate use of https://github.com/Perl/perl5/issues.  This is **not** a Perl help site, *i.e.,* it is not a site one should turn to when one can't figure out what's going wrong with one's program.  It is a site for analyzing problems with the Perl programming language and its ongoing development.  Filing tickets like this one here simply wastes everyone's 

But he was reporting a SEGV, which perl isn't supposed to do. That means
that its either a bug in perl or (more likely) in some included XS code.

Which means it is an appropriate issue to raise.

The main criticism seems to be the lack of information about how to
reproduce the bug.


-- 
Counsellor Troi states something other than the blindingly obvious.
    -- Things That Never Happen in "Star Trek" #16
