### ISSUE TITLE
[doc] Document 'use' single colon

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#21681]
`perldoc -f use` doesn't mention what this weird single colon stuff
means, e.g.,
```
use Math::Trig ':pi';
use Math::Trig ':radial';
use Math::Trig ':great_circle';
```

Also, `perldoc -f use` should mention how to combine e.g.,
```
use Math::Trig;
use Math::Trig qw(:pi :great_circle deg2rad rad2deg);
```
into just one line. Or it should mention there is no way to.

**Comment by mauke** [comment]
`':pi'` is a string containing three characters: a colon, a 'p', and an 'i'. That should be documented in perlop somewhere.

**Comment by jidanni** [comment]
Well if it is the same as https://stackoverflow.com/questions/1367374/what-does-colon-mean-in-perl then be sure `perldoc -f use` mentions it.

**Comment by mauke** [comment]
It is not the same. Strings are not executed as code. They're just ... strings.

**Comment by jidanni** [comment]
OK, I'm getting warmer... https://www.reddit.com/r/perl/comments/vybyoq/comment/ig1c4oa/

**Comment by Grinnz** [comment]
Again, it has nothing to do with Perl's syntax parsing. The only relevant part of that comment is the answer to what it means here: "The start of an export tag, like use Some::Module qw(:all), but that's really just something that Exporter decides to do with a string."

**Comment by mauke** [comment]
Math::Trig is documented here: https://metacpan.org/pod/Math::Trig#SYNOPSIS

```perl
    # Import constants pi2, pip2, pip4 (2*pi, pi/2, pi/4).
    use Math::Trig ':pi';
 
    # Import the conversions between cartesian/spherical/cylindrical.
    use Math::Trig ':radial';
 
        # Import the great circle formulas.
    use Math::Trig ':great_circle';
```

**Comment by jidanni** [comment]
OK, so as Exporter is already mentioned on `perldoc -f use`,
now all that is left for `perldoc -f use` to mention is how
to combine the two `use` lines.

If the user must read `man Exporter`, to figure out how to combine two `use` lines,
that would be overkill.

**Comment by mauke** [comment]
Dude. What are you talking about? The two `use` lines mean (as explained in `perldoc -f use`):
```perl
BEGIN {
    require Math::Trig;
    Math::Trig->import();
}
BEGIN {
    require Math::Trig;
    Math::Trig->import( qw(:pi :great_circle deg2rad rad2deg) );
}
```
Now, the two adjacent `BEGIN` blocks can be merged and the second `require` is redundant, leaving us with:
```perl
BEGIN {
    require Math::Trig;
    Math::Trig->import();
    Math::Trig->import( qw(:pi :great_circle deg2rad rad2deg) );
}
```
But whether the two `import` method calls can be combined depends entirely on what the `Math::Trig->import` method does. `use` itself doesn't know or care. You'll have to take it up with the module you're using.

**Comment by jidanni** [comment]
OK, so
```
use Math::Trig;
use Math::Trig qw(:pi);
```
cannot necessarily be combined into a single line.
I suppose it is not the responsibility of `perldoc -f use`
to answer such cosmetic questions, as the user's program will
at least still run despite looking funny. So OK, I'll close this.
