### ISSUE TITLE
[doc] podchecker: add -quiet to not print success messages

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#21687]
podchecker perhaps could add a -quiet option to not print success
messages. That way one could use it with other commands without extra
messages if all is OK.

P.S., man podchecker says

>        Please report bugs using <http://rt.cpan.org>.

I'm guessing that since it comes with Package perl, then maybe it should
say report them on github... or at least mention something like
https://metacpan.org/release/NWCLARK/perl-5.8.3/view/pod/podchecker.PL

**Comment by jkeenan** [comment]
> podchecker perhaps could add a -quiet option to not print success messages. That way one could use it with other commands without extra messages if all is OK.
> 
> P.S., man podchecker says
> 
> > ```
> >    Please report bugs using <http://rt.cpan.org>.
> > ```
> 
> I'm guessing that since it comes with Package perl, then maybe it should say report them on github... or at least mention something like https://metacpan.org/release/NWCLARK/perl-5.8.3/view/pod/podchecker.PL

`podchecker` is maintained upstream on CPAN.  Hence, proposals to change its behavior should be filed at its issue tracker, which is https://rt.cpan.org/Dist/Display.html?Name=Pod-Checker.  Please file at that location; closing this ticket.

**Comment by jidanni** [comment]
OK. Created https://rt.cpan.org/Ticket/Display.html?id=150660 .

**Comment by sighook** [comment]
I've created about 4 months ago the following ticket:
https://rt.cpan.org/Public/Bug/Display.html?id=149267

Also, I believe there is no need to create a new cmdline flag: just follow Unix style. Ok-messages should go to `stdout`, error messages to `stderr`. Now both types of messages are sent to `stderr`.

**Comment by jidanni** [comment]
Well, some people would like them on standard,  some people like them on standard out. So there should be a --silent key in any case.
