### ISSUE TITLE
[doc] if Configure'd to "Use Strict by default", 5.38.2 build fails because assorted build scripts break under "use strict"

### ISSUE THREAD

**Issue by gsteemso** [Perl/perl5#21732]
At a minimum, offending scripts appear to include "regen/embed_lib.pl" (as called by "autodoc.pl") and "base/cond.t" (as called by minitest).  Each of them failed hard with a slew of "did you forget to declare variable $such-and-such?" messages.

If it turns out that these do in fact run successfully with "use strict", I will be very confused, because disabling that option in Configure allowed compilation and installation to succeed.

**Comment by jkeenan** [comment]
> At a minimum, offending scripts appear to include "regen/embed_lib.pl" (as called by "autodoc.pl") and "base/cond.t" (as called by minitest). Each of them failed hard with a slew of "did you forget to declare variable $such-and-such?" messages.
> 
> If it turns out that these do in fact run successfully with "use strict", I will be very confused, because disabling that option in Configure allowed compilation and installation to succeed.

Can you post the `./Configure` command you used in this investigation?

**Comment by tonycoz** [comment]
```
$ ./Configure -des -Dusedevel -Dusedefaultstrict
...
$ make -j2 test-prep
...
$ ./miniperl -Ilib autodoc.pl
...
Global symbol "$n" requires explicit package name (did you forget to declare "my $n"?) at ./regen/embed_lib.pl line 3.
Global symbol "$n" requires explicit package name (did you forget to declare "my $n"?) at ./regen/embed_lib.pl line 4.
Global symbol "$n" requires explicit package name (did you forget to declare "my $n"?) at ./regen/embed_lib.pl line 5.
Global symbol "$n" requires explicit package name (did you forget to declare "my $n"?) at ./regen/embed_lib.pl line 6.
Global symbol "$n" requires explicit package name (did you forget to declare "my $n"?) at ./regen/embed_lib.pl line 7.
BEGIN not safe after errors--compilation aborted at ./regen/embed_lib.pl line 10.
Compilation failed in require at autodoc.pl line 89.
```

**Comment by jkeenan** [comment]
> At a minimum, offending scripts appear to include "regen/embed_lib.pl" (as called by "autodoc.pl") and "base/cond.t" (as called by minitest). Each of them failed hard with a slew of "did you forget to declare variable $such-and-such?" messages.
> 
> If it turns out that these do in fact run successfully with "use strict", I will be very confused, because disabling that option in Configure allowed compilation and installation to succeed.

From `pod/perl5340delta.pod`, with respect to `-Dusedefaultstrict`:
```
This setting provides a diagnostic mechanism intended for development
purposes only and is thus undefined by default.
```
During the (now discontinued) "Perl 7" project in summer/fall 2020, we spent hundreds of hours overhauling the core distribution (mainly, its test suite), so that it would build and test correctly under "strict by default".  (I don't think it was formulated as a Configure-switch back then.)  We did it, but it was a tremendous effort and probably ultimately not worth it.

So while we should fix the example reported in this ticket -- and I see @tonycoz is preparing a patch -- we should not, IMO, obsess over each thing we find.

**Comment by gsteemso** [comment]
Very interesting!

In light of the reasoning there, I would suggest that the feature be removed.  I submit that, if it was not intended to be used and in fact cannot be used, then it should not be left out where people might try to use it.

I will freely admit to having a somewhat biased opinion. :¬)

**Comment by haarg** [comment]
It would probably be reasonable to leave the `USE_STRICT_BY_DEFAULT` define one place, but remove `usedefaultstrict`.

**Comment by jkeenan** [comment]
> It would probably be reasonable to leave the `USE_STRICT_BY_DEFAULT` define one place, but remove `usedefaultstrict`.

@haarg, would you like to open a ticket for the removal of `usedefaultstrict`?

Apart from that, I don't think there's anything more to be done in *this* ticket.

**Comment by gsteemso** [comment]
Agreed.  Marking it closed.
