### ISSUE TITLE
Assert failures from `pad.c` after compilation errors involving imported builtins

### ISSUE THREAD

**Issue by leonerd** [Perl/perl5#21852]
While testing a question related to lexical import/unimport, I encountered this failure:

```
$ ./perl -Mstrict -E 'my sub true () { "OK" } { use builtin "true"; no builtin "true"; say "True is ", true }'
Bareword "true" not allowed while "strict subs" in use at -e line 1.
Execution of -e aborted due to compilation errors.
perl: pad.c:416: Perl_cv_undef_flags: Assertion `inner_rc' failed.
Aborted
```

The first two lines of output are roughly the error I was expecting. The assert failure from `pad.c` line 416 however shouldn't happen.

**Comment by jkeenan** [comment]
```
$ git describe
v5.39.7-32-gaf9733f1e2
```
Attempting to build an unthreaded perl in a checkout of blead on Linux at the commit above, I get:
```
$ ./perl -Mstrict -E 'my sub true () { "OK" } { use builtin "true"; no builtin "true"; say "True is ", true }'
Can't locate strict.pm in @INC (you may need to install the strict module) (@INC entries checked: /usr/local/lib/perl5/site_perl/5.39.8/x86_64-linux /usr/local/lib/perl5/site_perl/5.39.8 /usr/local/lib/perl5/5.39.8/x86_64-linux /usr/local/lib/perl5/5.39.8).
BEGIN failed--compilation aborted.
```
Okay, let's add `-Ilib` to that invocation:
```
$ ./perl -Ilib -Mstrict -E 'my sub true () { "OK" } { use builtin "true"; no builtin "true"; say "True is ", true }'
Bareword "true" not allowed while "strict subs" in use at -e line 1.
Execution of -e aborted due to compilation errors.
```
No assert failure ... but wait, maybe this should have been a debugging build?
```
sh ./Configure -des -Dusedevel -DDEBUGGING && make test_prep
...
$ ./perl -Ilib -Mstrict -E 'my sub true () { "OK" } { use builtin "true"; no builtin "true"; say "True is ", true }'
Bareword "true" not allowed while "strict subs" in use at -e line 1.
Execution of -e aborted due to compilation errors.
```
Hmm ... still no mention of an assert failure.  Can you say more about how you configured such that you saw this failure (or what I am doing wrong)?

**Comment by leonerd** [comment]
Huh this is weird. Now I try to recreate it to debug it further, I can't trigger it any more. Perhaps it was a weird artefact of some partly rebuilt code I had checked out.

I'll close this for now but I can reöpen it if I notice it again.
