### ISSUE TITLE
BBC: blead breaks Safe when `use`-ing modules without an `import` method.

### ISSUE THREAD

**Issue by mkende** [Perl/perl5#21867]
Module: Safe

**Description**

`use` of a module inside a `Safe` container fails if the module does not expose an `import` method.

This seems related to https://perldoc.perl.org/5.39.1/perldelta#Calling-the-import-method-of-an-unknown-package-produces-an-error. However, the module I’m using exists and I’m calling `use` without any argument, so this is not the case described in this `perldelta` entry.

**Steps to Reproduce**

```
perl -MSafe -e '$s = Safe->new(); $s->deny_only(); $s->reval("use Tie::Scalar;"); print $@;'
```

**Expected behavior**

No output is written as the `reval` call should succeed and `$@` should be empty, which is what happens on Perl 5.38.0 as well as all older versions that I tried.

**Actual behavior**

With Perl 5.39.1 and later, the `reval` call fails and `$@` is printed with the following content:

> Can't locate object method "import" via package "Tie::Scalar" at (eval 7) line 1.
> BEGIN failed--compilation aborted at (eval 7) line 1.

Note, that just `perl -e 'use Tie::Scalar'` still compiles successfully. So `use`-ing a module that does not expose an `import` method is still allowed, as per the [documentation](https://perldoc.perl.org/5.39.6/functions/use).

**Perl configuration**

I tested this on a default perl 5.39.8 built using `perlbrew install blead` under Debian (running in WSL).

See the attached [perl_version.txt](https://github.com/Perl/perl5/files/14015527/perl_version.txt) for the full output of `perl -V`.

```
Summary of my perl5 (revision 5 version 39 subversion 8) configuration:
  Snapshot of: ea7611b58ba1e09cf59415d24fe10105fe55ea8c
  Platform:
    osname=linux
    osvers=5.15.133.1-microsoft-standard-wsl2
    archname=x86_64-linux
    uname='linux mathias-2022 5.15.133.1-microsoft-standard-wsl2 #1 smp thu oct 5 21:02:42 utc 2023 x86_64 gnulinux '
    config_args='-de -Dprefix=/home/mathias/perl5/perlbrew/perls/perl-blead -Dman1dir=none -Dman3dir=none -Dusedevel -Aeval:scriptdir=/home/mathias/perl5/perlbrew/perls/perl-blead/bin'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
```

**Comment by jkeenan** [comment]
I suspect this may be (unintended?) fallout from this commit:
```
commit f1cf82e77b0865c6a2f3a6cb94f074196dbc6df2
Author:     Yves Orton <demerphq@gmail.com>
AuthorDate: Tue Jul 25 18:18:43 2023 +0200
Commit:     Yves Orton <demerphq@gmail.com>
CommitDate: Wed Jul 26 21:25:17 2023 +0200

    universal.c - change import with args error to be a deprecated warning
```
@demerphq, could you take a look? Thanks.

**Comment by haarg** [comment]
It should just be a matter of adding `&UNIVERSAL::import` and `&UNIVERSAL::unimport` to Safe's `$default_share` list.

**Comment by mkende** [comment]
Thanks @haarg for the pointers. I sent #21883 to fix this.
