### ISSUE TITLE
Wanted: `cpan --tidyup` or similar

### ISSUE THREAD

**Issue by leonerd** [Perl/perl5#21914]
If you run an `cpan` interactive shell and `install Some::Module`, buried deep in the cache manager code there's a call to the `tidyup` function, which cleans up old build dirs in your `$HOME/.cpan/build` so you don't run out of disk space. As far as I can tell, doing it via the interactive shell is the *only* path that causes this. Simply doing `cpan Some::Module` does not.

This means, if you have a large automated installation setup, your disk space grows all the time until you run out of disk space. Not fun.

Additionally as far as I can tell, there does not appear to be a way to gain access to that behaviour from outside.

It'd be great if we had some sort of option or flag, maybe so I could add

```
cpan --tidyup
```

in my cron.daily and thus have it keep the disk space managed and not fill it all.

**Comment by jkeenan** [comment]
> 
> It'd be great if we had some sort of option or flag, maybe so I could add
> 
> ```
> cpan --tidyup
> ```
> 
> in my cron.daily and thus have it keep the disk space managed and not fill it all.

CPAN.pm and the `cpan` utility are both maintained upstream on (wait for it!) CPAN.  So that's where this feature request will have to be filed.

**Comment by Tux** [comment]
I have a local script `cpan-clean` which I was to post here as example, but it reflects too many personal preferences to be used in general. I can share with whoever can look through that
```
🐧 cpan-clean --help
usage: cpan-clean [--reset]
```
`--reset` also cleans out `FTP* Metadata histfile cpan* sources/authors/01* sources/modules/0*`

I also have `cpan-buildcheck` written for systems that are installing a fresh perl using a bundle from the previous perl but do not have enough disk space to process the complete list, so it cleans up all stuff that has been built and installed successfully while cpan purrs along
```
🐧 cpan-buildcheck --help
usage: cpan-buildcheck [--cleanup]
```

**Comment by rwp0** [comment]
Another similar request could be for `cpan uninstall` command to revert module installation. I mean we shouldn't have to install `cpanm` in order to uninstall (`with --uninstall`) distributions (we installed with `cpan`) easily.

This issue could be transferred to:
https://github.com/andk/cpanpm

**Comment by rwp0** [comment]
Another similar request could be for `cpan uninstall` command to revert the module installation. I mean we shouldn't have to install `cpanm` in order to uninstall (`with --uninstall`) distributions (we installed with `cpan`) easily.

This issue could be transferred to:
https://github.com/andk/cpanpm
