### ISSUE TITLE
Should have caught "priint" first, not "$h{x"

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#22049]
Here's another compiler warning issue. Feel free to close it if there is nothing new here.

```
$ perl -we 'use strict; my %h=(x=>1); priint $h{x}; my $m=delete $h{x};'
syntax error at -e line 1, near "$h{x"
Execution of -e aborted due to compilation errors.
```

Better would be to say something about
"priint". Else the user needs to check all
his "$h{x"'s, even thinking maybe he didn't
put in final "}"'s. And then after several
minutes and scratching his head, finally gaze
upon "priint"!

I'm starting to think "AI would do a better job at finding the problem..."

**Comment by Corion** [comment]
You could maybe better highlight that specific error by prohibiting indirect syntax:

```
perl -wE 'no indirect; use strict; my %h=(x=>1); priint $h{x}; my $m=delete $h{x};'
Indirect call of method "priint" on object "$h" at -e line 1.
syntax error at -e line 1, near "$h{x"
Execution of -e aborted due to compilation errors.
```

**Comment by guest20** [comment]
Why's that `$h->priint` and not `$h{x}->priint`?

**Comment by jkeenan** [comment]
> Here's another compiler warning issue. Feel free to close it if there is nothing new here.
> 

Nothing new here.  We're never going to be able to *exactly* identify the location of each and ever compilation error.  Closing.
