### ISSUE TITLE
a use in a map is not really part of an expression.

### ISSUE THREAD

**Issue by guest20** [Perl/perl5#22058]
**Description**

`use` in `map` claims it's in an expression, but this feels like void context to me. It's not part of the expression the map is generating, and were this a loop or a block instead this would be void context...

**Steps to Reproduce**

Do a `use` in `map` block: 
```
% perl -E 'my @things = map { use Data::Dumper;  Dumper $_ } @ARGV '
"use" not allowed in expression at -e line 1, at end of line
BEGIN not safe after errors--compilation aborted at -e line 1.
```

`grep` will punish you in a similar way:
```
% perl -E 'my @things = grep { use Data::Dumper;  Dumper $_ } @ARGV '
"use" not allowed in expression at -e line 1, at end of line
BEGIN not safe after errors--compilation aborted at -e line 1.
```

**Expected behaviour**

The `use` should be able to do its normal time travel to `BEGIN` time and include the requested software.

**Perl**

I don't think this come from any compilation flags. 
```
% perl -V
Summary of my perl5 (revision 5 version 20 subversion 2) configuration:
```

**Comment by d-c-d** [comment]
I don't get any warnings or errors in Perl 5.36.3
( chatgpt suggest that the change was made in 5.22 )

The bug is mentioned in [https://github.com/perl/perl5/issues/16791](https://github.com/perl/perl5/issues/16791)
with a workaround for the case reported

**Comment by d-c-d** [comment]
The release notes for perl5220delta include a reference t

   *   "use", "no", statement labels, special blocks ("BEGIN") and pod are
    now permitted as the first thing in a "map" or "grep" block, the
    block after "print" or "say" (or other functions) returning a
    handle, and within "${...}", "@{...}", etc. [GH #14088]
    <https://github.com/Perl/perl5/issues/14088>.

**Comment by guest20** [comment]
Searched issues, didn't search the commit log.

**Comment by mauke** [comment]
Duplicate of #14088.
