### ISSUE TITLE
[doc] New behavior of multiple use VERSION needs to be documented

### ISSUE THREAD

**Issue by haarg** [Perl/perl5#22055]
**Where**
perlfunc

**Description**
The behavior of use VERSION needs to be updated to match the new behavior. This includes not allowing multiple `use VERSION` declarations with different versions, as well as `builtin` imports.

**Comment by jkeenan** [comment]
As of May 11 12:33 UTC, this is the only issue still bearing a Release Blocker label.  (Of course, we should still be on the lookout for potential blockers.)

**Comment by book** [comment]
Fixed by #22235
