### ISSUE TITLE
Update Fnctl with flags found in a modern fcntl.h file

### ISSUE THREAD

**Issue by richardleach** [Perl/perl5#22072]
Module: Fcntl

**Description**
The _Fnctl_ module is intended to be a translation of the C _fcntl.h_ file, but it has clearly not kept up, since we recently merged https://github.com/Perl/perl5/commit/8acce4d00738c76438f5d28f1711b6c7e93d664d and I've just raised https://github.com/Perl/perl5/pull/22071. It would be surprising if those are the only flags from a modern _fcntl.h_ that we are missing.

**Expected behavior**
The _Fnctl_ module contains all the flags you might find on a stable release of a mainstream Linux distro.

**Perl configuration**
Blead

**Comment by tonycoz** [comment]
Fixed by 22071
