### ISSUE TITLE
Colon as dot dot

### ISSUE THREAD

**Issue by philiprbrenan** [Perl/perl5#22106]
Might it be feasible to use **:** as well as **..** to represent a range as shown below given that at the moment the use of **:** is a syntax error? 

```
my @i = 1..10;

my @j = 1:10; # syntax error
```

**Comment by mauke** [comment]
Similarly, since `1 ] 10` is currently a syntax error, couldn't we use `]` to mean string concatenation, like `.`?

\</sarcasm>
