### ISSUE TITLE
[doc] perlfunc split: my @x = split(//, "abc", 4); # ("a", "b", "c")   <-- wrong, should be  ("a", "b", "c", "") 

### ISSUE THREAD

**Issue by MarkB-L** [Perl/perl5#22150]
I think there is a mistake in the perlfunc documentation for split().

It currently says...
my @x = split(//, "abc", 3); # ("a", "b", "c")
my @x = split(//, "abc", 4); # ("a", "b", "c")

It should say
my @x = split(//, "abc", 3); # ("a", "b", "c")
my @x = split(//, "abc", 4); # ("a", "b", "c", "")

**Comment by Grinnz** [comment]
You're correct but this is probably an unfortunate example. It most likely intends to show that the LIMIT is a maximum, so for example `split /x/, "axbxc", 4` will only produce three fields. But the empty split produces a 4th trailing field (but not, for example, a 5th with a limit of 5).

**Comment by MarkB-L** [comment]
I agree, but shouldn't the doc be changed to your example, or changed to:-my @x = split(//, "abc", 4); # ("a", "b", "c", "")my @x = split(//, "abc", 5); # ("a", "b", "c", "")

    On Tuesday, April 16, 2024 at 05:58:24 PM GMT+1, Dan Book ***@***.***> wrote:  
 
 


You're correct but this is probably an unfortunate example. It most likely intends to show that the LIMIT is a maximum, so for example split /x/, "axbxc", 4 will only produce three fields. But the empty split produces a 4th trailing field (but not, for example, a 5th with a limit of 5).
