### ISSUE TITLE
Attempt to free unreferenced scalar: SV ... at ../lib/B/Deparse.t line 83, <DATA> chunk 288.

### ISSUE THREAD

**Issue by cjg-cguevara** [Perl/perl5#22164]
Perl smoke tests beginning at commit 4a55343 started logging

```
Attempt to free unreferenced scalar: SV 0x621000481308 at ../lib/B/Deparse.t line 83, <DATA> chunk 288.
```
and
```
Attempt to free unreferenced scalar: SV 0x62100045f1f8, Perl interpreter: 0x620000000080 at ../lib/B/Deparse.t line 83, <DATA> chunk 288.
```

Some examples:
https://perl.develop-help.com/dblog/5053000
https://perl.develop-help.com/dblog/5052991
https://perl.develop-help.com/dblog/5053001

**Comment by iabyn** [comment]
This has been fixed by v5.39.9-66-g17535c984a
