### ISSUE TITLE
[doc] Don't say $. in "Use of uninitialized value $. in range"

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#22198]
```
$ perl -lwe '$m=0; print 0 .. ($m?1:11)'
01234567891011
```
All's OK, but what if the user did
```
$ perl -lwe '$m=0; print 0 .. $m?1:11'
Use of uninitialized value $. in range (or flip) at -e line 1.
1
```
All I know is on man perlvar `$.` is current line number. Therefore please say something else, like, "Maybe you forgot the parentheses." In fact there are two messages that need to get fixed:
```
$ perl -we 'print 0 .. 0?1:11'
Use of uninitialized value $. in range (or flip) at -e line 1.
Use of uninitialized value $. in range (or flop) at -e line 1.
```

**Comment by mauke** [comment]
Without parentheses, your code parses as `print((0 .. $m) ? 1 : 11)`. That is, the `..` operator is now an operand of `?:`, which puts it in scalar (boolean) context.

https://perldoc.perl.org/perlop#Range-Operators

> In scalar context, `..` returns a boolean value. The operator is bistable, like a flip-flop, and emulates the line-range (comma) operator of **sed**, **awk**, and various editors. Each `..` operator maintains its own boolean state, even across calls to a subroutine that contains it. It is false as long as its left operand is false. Once the left operand is true, the range operator stays true until the right operand is true, *AFTER* which the range operator becomes false again.

...

> If either operand of scalar `..` is a constant expression, that operand is considered true if it is equal (`==`) to the current input line number (the `$.` variable).

The warning is correct: Your code does compare `$. == 0`.

**Comment by jidanni** [comment]
Well fine. We see it guesses two possibilities,
> Use of uninitialized value $. in range (or flip)

But it could guess a third too.
