### ISSUE TITLE
[doc] Don't use two dashes at the top of man pages

### ISSUE THREAD

**Issue by jidanni** [Perl/perl5#22213]
Man pages need only one dash, not two.
```
$ apropos --sections=1 . | grep --invert-match --count -- '- -'
1490
$ apropos --sections=1 . | grep --count -- '- -'
2
$ apropos --sections=1 . | grep -- '- -'
enc2xs (1)           - - Perl Encode Module Generator
piconv (1)           - - iconv(1), reinvented in perl
```

And doing the experiment a second time, without --sections=1, reveals even more, all perl's.

However many of perl's man pages don't have this problem. Just some rebellious ones.

**Comment by Leont** [comment]
Both of these are from Encode, so I would suggest filing this [upstream](https://github.com/dankogai/p5-encode)
