### ISSUE TITLE
UNIVERSAL.pm docfix

### ISSUE THREAD

**Issue by Lamprecht** [Perl/perl5#22210]
**Where**
UNIVERSAL.pm

**Description**
Documentation of method `isa`. The sentence below makes no sense:

 _If you want to be sure that you're calling isa as a method, not a class, check the invocand with blessed from [Scalar::Util](https://perldoc.perl.org/Scalar::Util) first:_

Suggested fix:

index 5e9537daae..79dda9459e 100644
--- a/lib/UNIVERSAL.pm
+++ b/lib/UNIVERSAL.pm
@@ -82,7 +82,7 @@ reference. The L<C<isa> operator|perlop/"Class Instance Operator"> is an
 alternative that simply returns false in this case, so the C<eval> is not
 needed.
 
-If you want to be sure that you're calling C<isa> as a method, not a class,
+If you want to be sure that you're calling C<isa> on an instance, not a class,
 check the invocand with C<blessed> from L<Scalar::Util> first:
 
   use Scalar::Util 'blessed';

**Comment by book** [comment]
Thanks, applied as 869c089e65e7abdd5791c0f4592caf4487d8abce.
