### ISSUE TITLE
makerel should always set --format=ustar

### ISSUE THREAD

**Issue by haarg** [Perl/perl5#22245]
Everything we need from the release tarball should be compatible with ustar. Setting ustar will eliminate all of the extra header files that may be produced by tar including extended attributes that we don't need.

This is more reliable than trying to set COPYFILE_DISABLE (on macOS) or similar methods.

**Comment by jkeenan** [comment]
> Everything we need from the release tarball should be compatible with ustar. Setting ustar will eliminate all of the extra header files that may be produced by tar including extended attributes that we don't need.
> 
> This is more reliable than trying to set COPYFILE_DISABLE (on macOS) or similar methods.

Was this issue created in response to some problem reported on list or in another GH issue?

**Comment by haarg** [comment]
No, just based on things I've seen making perl or CPAN releases.

**Comment by haarg** [comment]
This was implemented with #22273
