### ISSUE TITLE
[doc] Typo in perl.pod "Divining"

### ISSUE THREAD

**Issue by poti1** [Perl/perl5#22258]
**Where**
perl.pod

**Description**

Pretty sure "Divining" is a typo (unless the author wanted to have another meaning):

![Screenshot_2024-06-04-07-51-36-89_84d3000e3f4017145260f7618db1d683](https://github.com/Perl/perl5/assets/75398062/7b029d9c-7baf-4033-94a3-425af66525aa)

**Comment by mauke** [comment]
https://en.wiktionary.org/wiki/divine#Verb

> 2. ([*transitive*](https://en.wiktionary.org/wiki/Appendix:Glossary#transitive)) To [guess](https://en.wiktionary.org/wiki/guess#English) or [discover](https://en.wiktionary.org/wiki/discover#English) (something) through [intuition](https://en.wiktionary.org/wiki/intuition#English) or [insight](https://en.wiktionary.org/wiki/insight#English).

**Comment by poti1** [comment]
Learned a new word today. Thanks
