### ISSUE TITLE
[doc] perlretut grammar

### ISSUE THREAD

**Issue by poti1** [Perl/perl5#22260]
**Where**
perlretut

**Description**
I would update the bold from:

"The answer to 1) is that Unicode characters greater than chr(255) are represented using the \x{hex} notation, because \xXY (**without curly braces and XY are two hex digits**) doesn't go further than 255. (Starting in Perl 5.14, if you're an octal fan, you can also use \o{oct}.)"

To:
"without curly braces, XY are two hex digits"

**Comment by khwilliamson** [comment]
Sounds good; I will prepare a pull request

**Comment by khwilliamson** [comment]
Actually, looking deeper, I think having the parentheses is better.

**Comment by rwp0** [comment]
@khwilliamson, I think the author is asking here to "update" the `and` specifically.

> without curly braces **and** XY are two hex digits

> without curly braces, XY are two hex digits

@poti1, why not create a quick PR using GitHub's edit file feature?

https://github.com/Perl/perl5/edit/blead/pod/perlretut.pod

**Comment by Grinnz** [comment]
That would be incorrect; it is stating two conditions, that no curly braces are used, and that it is followed by two hex digits. The presence of curly braces does not affect whether the digits are hex.

**Comment by poti1** [comment]
Instead of swapping the "and" for a comma,
Rephrasing of the parenthetical clause (as done in the pull request) seems to make the thought clearer.
