### ISSUE TITLE
builtin::stringify not documented as experimental

### ISSUE THREAD

**Issue by ikegami** [Perl/perl5#22277]
In the 5.40.0's documentation for builtin, `stringify` isn't documented as experimental even though the newly-added function issues an experimental warning.

```
$ perl -v | grep 'This is'
This is perl 5, version 40, subversion 0 (v5.40.0) built for x86_64-linux-thread-multi

$ perl -e'use builtin qw( stringify ); stringify 123'
Built-in function 'builtin::stringify' is experimental at -e line 1.
```

**Comment by rwp0** [comment]
Here's an easy solution modelled on `create_as_string`'s documentation:

https://github.com/Perl/perl5/pull/22279
