### ISSUE TITLE
[doc] The to This

### ISSUE THREAD

**Issue by poti1** [Perl/perl5#22285]
**Where**
https://perldoc.perl.org/perlfaq5#How-do-I-change,-delete,-or-insert-a-line-in-a-file,-or-append-to-the-beginning-of-a-file?

**Description**

Change "The" to "This":

"The happens for every line, so be sure that you're supposed to do that on every line!"

**Comment by Grinnz** [comment]
perlfaq is maintained at https://github.com/perl-doc-cats/perlfaq. I have opened https://github.com/perl-doc-cats/perlfaq/pull/120
