### ISSUE TITLE
[doc] Plural Objects

### ISSUE THREAD

**Issue by poti1** [Perl/perl5#22284]
**Where**
https://perldoc.perl.org/perlfaq4#How-do-I-define-methods-for-every-class/object?

**Description**

Should be plural objects:

"If possible, it would be better to have all your object inherit from some common base class, ..."

**Comment by Grinnz** [comment]
moved to https://github.com/perl-doc-cats/perlfaq/pull/121

**Comment by guest20** [comment]
@Grinnz What is a `perl-doc-cats`? don't perldocs live in `perl5.git`?

**Comment by jkeenan** [comment]
On 6/16/24 07:35, guest20 wrote:
> @Grinnz <https://github.com/Grinnz> What is a |perl-doc-cats|? don't 
> perldocs live in |perl5.git|?
> 

In the Perl core distribution, perlfaq is found under the cpan/ 
directory.  Everything under cpan/ is maintained upstream on CPAN. 
Therefore, changes in those documents should be directed toward the 
repositories indicated on their respective metacpan.org pages.
