### ISSUE TITLE
[doc] perlclass is not linked to in obvious places

### ISSUE THREAD

**Issue by Altreus** [Perl/perl5#22350]
**Where**
https://perldoc.perl.org/functions/class

https://perldoc.perl.org/perlobj

**Description**
functions/class mentions the concept of a class but doesn't link to it, but if you search for "class" on ppo you just get back to where you came from, so it's hard to find what it's talking about.

perlobj should link to perlclass just out of practicality, although justifiably we might not want to do that while it's still experimental.

**Comment by jkeenan** [comment]
> **Description** functions/class mentions the concept of a class but doesn't link to it, but if you search for "class" on ppo you just get back to where you came from, so it's hard to find what it's talking about.

Handled in GH #22384.

> 
> perlobj should link to perlclass just out of practicality, although justifiably we might not want to do that while it's still experimental.

We can consider this once the experimental status has changed.  Closing ticket.
