### ISSUE TITLE
Unable to build 5.40.0 - infinite loop trying to build IO-Socket-SSL

### ISSUE THREAD

**Issue by robrwo** [Perl/perl5#22389]
I am trying to build Perl 5.40 on a system to install in /opt/perl5.40.0, but it seems to get stuck in an infinite loop trying to install IO-Socket-SSL:
```
Running make for S/SU/SULLR/IO-Socket-SSL-2.087.tar.gz
---- Unsatisfied dependencies detected during ----
----     SULLR/IO-Socket-SSL-2.087.tar.gz     ----
    Mozilla::CA [requires]
Running make for module 'Mozilla::CA'
  LWP/Mozilla-CA-20240313.tar.gz
  Has already been unwrapped into directory /home/rrothenberg/.cpan/build/Mozilla-CA-20240313-1
  LWP/Mozilla-CA-20240313.tar.gz
  Has already been prepared
  LWP/Mozilla-CA-20240313.tar.gz
  Has already been made
  SULLR/IO-Socket-SSL-2.087.tar.gz
  Has already been unwrapped into directory /home/rrothenberg/.cpan/build/IO-Socket-SSL-2.087-1
  SULLR/IO-Socket-SSL-2.087.tar.gz
  Has already been prepared
```
Perl 5.38.2 was installed with no problems on this server, and has IO::Socket::SSL (v2.085) installed.

**Comment by robrwo** [comment]
After several tries re-running `Configure` it seems to be fine. I think the cause was installing extra CPAN modules, so I disabled that step.

**Comment by jkeenan** [comment]
> After several tries re-running `Configure` it seems to be fine. I think the cause was installing extra CPAN modules, so I disabled that step.

It appears there's nothing for P5P to do here, so let's close this ticket.  Thanks.

**Comment by robrwo** [comment]
I suspect there is something with the extra modules option causing this. I've been unable to diagnose it since the workaround is to not use that feature and install them afterwards. But others may run into the same issue in the future.

**Comment by haarg** [comment]
Diagnosing this would require a more complete build log.
