### ISSUE TITLE
Cannot build without another Perl

### ISSUE THREAD

**Issue by JonathanWilbur** [Perl/perl5#22390]
**Description**
Perl cannot be built without using another Perl. I found a repo [where](https://github.com/fosslinux/live-bootstrap/tree/master/steps/perl-5.000) somebody managed to bootstrap Perl by using hard-coded files and other tricks, but having to pull of this much of a stunt just to build Perl without an existing Perl is obnoxious. It would be really nice if there were just C programs that would compile and run to perform any setup needed for a build.

**Expected behavior**
Be able to build Perl without an existing Perl.

**Perl configuration**
I am trying this with Perl 5.40.0, fetched from the CPAN website.

I would like to add that I would be will to submit a PR to convert the Perl scripts to C programs, if somebody can just point out what/where these are, and if this idea isn't rejected outright.

**Comment by guest20** [comment]
@JonathanWilbur Where were you building it? Some kind of jail, or a docker or something like that?

**Comment by JonathanWilbur** [comment]
It was in docker, yes.

**Comment by xenu** [comment]
I've just built perl-5.40.0 on a clean Alpine Linux installation with no perl present, and it finished successfully.

What errors are you getting?

**Comment by mauke** [comment]
> Perl cannot be built without using another Perl.

citation needed

**Comment by demerphq** [comment]
I wonder if there is a difference between building Perl using a git repo, and using a tarball.  I STR that we *do* require Perl to build from a git checkout, but we dont for a tarball.

**Comment by demerphq** [comment]
The linked repo seems to be for 5.000?

**Comment by JonathanWilbur** [comment]
I see. That was a mistake on my part. I guess it _used to_ require an existing Perl?

Building with no existing Perl did work for me; it didn't work the first time because I was copying generated files into the Docker container, which is obviously not how it was intended to be used.

Sorry, I guess I should have actually tested it for myself, _but_ I assumed this to still be true when I saw this in `INSTALL`:

```
First, make sure you have an up-to-date version of Perl.
```

In light of my reading that you need an existing Perl, I interpreted the above sentence to mean that you need an existing Perl.

Sorry to have jumped the gun, but I guess now you have a "tombstone issue" so others can see that this is no longer a requirement to build. Thank you for your help! Closing.

**Comment by mauke** [comment]
What `INSTALL` means is really: "First, make sure you have an up-to-date version of [the] Perl [source code]."

You don't need perl just to build perl and I don't think you ever did.

If you're a developer working on perl, you may have to regenerate certain derived files, which requires perl. But that's exactly why those files are generated during development: So users can just compile them without having to install bison or a binary version of perl first.
