### ISSUE TITLE
Cross compilation

### ISSUE THREAD

**Issue by nivelus** [Perl/perl5#22506]
**Description**
I am trying to cross compile perl 5.36. I made config.sh, and running `make perl` in Cross directory gives me this weird error:
```
"../../miniperl" "-I../../lib" "-I../../lib" scripts/pod2man.PL scripts/pod2man
Can't undef active subroutine at /usr/lib/perl/5.36.0/Config_heavy.pl line 1527.
Compilation failed in require at ../../lib/Config.pm line 80.
```
Any ideas what is wrong? Thanks in advance.

**Comment by jkeenan** [comment]
> **Description** I am trying to cross compile perl 5.36. I made config.sh, and running `make perl` in Cross directory gives me this weird error:
> 
> ```
> "../../miniperl" "-I../../lib" "-I../../lib" scripts/pod2man.PL scripts/pod2man
> Can't undef active subroutine at /usr/lib/perl/5.36.0/Config_heavy.pl line 1527.
> Compilation failed in require at ../../lib/Config.pm line 80.
> ```
> 
> Any ideas what is wrong? Thanks in advance.

Can you tell us what platform/OS you were compiling **on** and what platform/OS you were attempting to compile **to**?

Please attach the output of `perl -V` for the perl you were using when attempting the cross-compilation.  Also please supply the arguments to `./Configure` you used when attempting to build perl on the targeted platform.

**Comment by Leont** [comment]
Are you using [perl-cross](https://github.com/arsv/perl-cross)? Perl's own support for cross-compilation is sadly fairly limited.

**Comment by nivelus** [comment]
Well, using perl-cross seems to be the easiest way.
