### ISSUE TITLE
[doc] https://perldoc.perl.org/functions/readdir

### ISSUE THREAD

**Issue by dervikxx** [Perl/perl5#22632]
**Where**
https://perldoc.perl.org/functions/readdir

**Description**
incorrect first example, array will be all time empty - `grep { /^\./ && -f "$some_dir/$_" }`

**Comment by haarg** [comment]
The text in the first example reads `grep { /^\./ && -f "$some_dir/$_" }`. Is the backslash not appearing for you?

**Comment by haarg** [comment]
The example is trying to find files starting with a `.`. The code accomplishes that. Why do you think that the array would be empty?

**Comment by tonycoz** [comment]
The example works and no response from the OP, closing.
