### ISSUE TITLE
BBC: Blead Breaks Module::CoreList

### ISSUE THREAD

**Issue by cjg-cguevara** [Perl/perl5#22693]
This is a bug report for perl from "Carlos Guevara" <carlos@carlosguevara.com>,
generated with the help of perlbug 1.43 running under perl 5.41.6.

-----------------------------------------------------------------

BBC: Blead Breaks Module::CoreList

Please see http://fast-matrix.cpantesters.org/?dist=Module::CoreList

---
**Flags**
- category=core
- severity=low
---
**Perl configuration**
```
Site configuration information for perl 5.41.6:

Configured by cpan at Tue Oct 22 13:44:34 EDT 2024.

Summary of my perl5 (revision 5 version 41 subversion 6) configuration:
  Commit id: 7242922c377e3bda34b27f55f92ac90ac893edcb
  Platform:
    osname=linux
    osvers=5.14.0-427.40.1.el9_4.x86_64
    archname=x86_64-linux
    uname='linux cjg-rhel9 5.14.0-427.40.1.el9_4.x86_64 #1 smp preempt_dynamic fri oct 4 15:22:45 edt 2024 x86_64 x86_64 x86_64 gnulinux '
    config_args='-des -Dprefix=/home/cpan/bin/perl -Dscriptdir=/home/cpan/bin/perl/bin -Dusedevel -Duse64bitall'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
  Compiler:
    cc='cc'
    ccflags ='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'
    optimize='-O2'
    cppflags='-fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'
    ccversion=''
    gccversion='11.4.1 20231218 (Red Hat 11.4.1-3)'
    gccosandvers=''
    intsize=4
    longsize=8
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='off_t'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='cc'
    ldflags =' -fstack-protector-strong -L/usr/local/lib'
    libpth=/usr/local/lib /usr/lib /usr/lib64 /usr/local/lib64
    libs=-lpthread -ldb -ldl -lm -lcrypt -lutil -lc
    perllibs=-lpthread -ldl -lm -lcrypt -lutil -lc
    libc=/lib/../lib64/libc.so.6
    so=so
    useshrplib=false
    libperl=libperl.a
    gnulibc_version='2.34'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs
    dlext=so
    d_dlsymun=undef
    ccdlflags='-Wl,-E'
    cccdlflags='-fPIC'
    lddlflags='-shared -O2 -L/usr/local/lib -fstack-protector-strong'


---
@INC for perl 5.41.6:
    /home/cpan/bin/perl/lib/site_perl/5.41.6/x86_64-linux
    /home/cpan/bin/perl/lib/site_perl/5.41.6
    /home/cpan/bin/perl/lib/5.41.6/x86_64-linux
    /home/cpan/bin/perl/lib/5.41.6

---
Environment for perl 5.41.6:
    HOME=/home/cpan
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LC_ALL=C
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/cpan/bin/perl/bin:/home/cpan/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
    PERL_BADLANG (unset)
    SHELL=/bin/bash
```

**Comment by richardleach** [comment]
I think this is the tail end task for the 5.41.5 release this past weekend. I hadn't twigged that @bingos had updated `Module::CoreList` on CPAN. I'll look at this now.

**Comment by richardleach** [comment]
I've pushed https://github.com/Perl/perl5/commit/2cc57abff5ac5e77d58e028d24bcaa99a72c764d to blead, which should finish off the 5.41.5 release.

I'm not sure that this fixes this BBC though. Possibly I derped the ordering of changes prior to the CPAN release?

**Comment by jkeenan** [comment]
> I've pushed [2cc57ab](https://github.com/Perl/perl5/commit/2cc57abff5ac5e77d58e028d24bcaa99a72c764d) to blead, which should finish off the 5.41.5 release.
> 
> I'm not sure that this fixes this BBC though. Possibly I derped the ordering of changes prior to the CPAN release?

Blead (v5.41.5-17-g161ff7336a) is passing, but if I install it locally, then say `./bin/cpan` and, inside the cpan shell, say `test Module::CoreList`, I am asked whether I want to downgrade that module.
```
The current configuration of allow_installing_outdated_dists is 'ask/no', but for this option we would need 'CPAN::DistnameInfo' installed. Please install 'CPAN::DistnameInfo' as soon as possible. As long as we are not equipped with 'CPAN::DistnameInfo' this option does not take effect
allow_installing_module_downgrades: BINGOS/Module-CoreList-5.20241020.tar.gz (called for Module::CoreList) contains downgrading module(s) (e.g. 'Module/CoreList.pm' would downgrade installed '5.20241120' to '5.20241020'). Do you want to allow installing it? [no] 
Testing/Installation stopped: allow_installing_module_downgrades: BINGOS/Module-CoreList-5.20241020.tar.gz (called for Module::CoreList) contains downgrading module(s) (e.g. 'Module/CoreList.pm' would downgrade installed '5.20241120' to '5.20241020')
  BINGOS/Module-CoreList-5.20241020.tar.gz
  [testing] -- NOT OK
Failed during this command:
 BINGOS/Module-CoreList-5.20241020.tar.gz     : make_test NO -- testing/installation stopped due allow_installing_module_downgrades: BINGOS/Module-CoreList-5.20241020.tar.gz (called for Module::CoreList) contains downgrading module(s) (e.g. 'Module/CoreList.pm' would downgrade installed '5.20241120' to '5.20241020')

cpan[2]> bye
```
So I *think* Module::CoreList needs a new CPAN release.

**Comment by bingos** [comment]
There is no way that the Module::CoreList released to CPAN following blead-point release can ever pass its tests when run against a Perl with a version that it **does not know about**

In this instance, Module-CoreList-5.20241020 has data on every Perl up to Perl v5.41.5

If you then test that against Perl v5.41.6 it doesn't know about that version and can't possibly know about that without using a time machine.

This is how we have always released Module::CoreList. It gets copied from a checkout of the tag of the blead-point release and I do the release to CPAN.

It isn't anything new either, go back through CPAN Testers results for previous months release of Module::CoreList and you see the same, fails from testing on a Perl version that M::CL has no knowledge of.

http://fast-matrix.cpantesters.org/?dist=Module-CoreList%205.20240920
http://fast-matrix.cpantesters.org/?dist=Module-CoreList%205.20240720
http://fast-matrix.cpantesters.org/?dist=Module-CoreList%205.20240702
etc etc etc.

There is no need for a new CPAN release.

I will put some sanity checks into is_core.t to skip those two tests if it doesn't have data for the version of Perl is being run as.

**Comment by richardleach** [comment]
Phew. Thanks @bingos!

**Comment by richardleach** [comment]
No actual breakage, bingos has added some sanity checking to _is_core.t_ to help avoid this BBC report after future releases. Closing the issue,
