### ISSUE TITLE
BBC: POWERMAN/Crypt-MatrixSSL3-v3.9.3.tar.gz: leak test may fail

### ISSUE THREAD

**Issue by eserte** [Perl/perl5#22705]
t/leak.t may fail since 5.41.something like this:
```
#   Failed test 'MEM: newkeys_deletekeys'
#   at t/leak.t line 270.
#     '336'
#         <=
#     '288'
# Looks like you failed 1 test of 26.
t/leak.t .................................. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/26 subtests 
```

However, there are also mixed results here. For 5.41.4, both pass and fail reports exist:
* http://www.cpantesters.org/cpan/report/6842daba-8206-11ef-b2ad-38246748ae50 (pass)
* http://www.cpantesters.org/cpan/report/d4bd6670-8e35-11ef-b6e9-5e516e8775ea (fail)

Note also that the module has a different issue with -DDEBUGGING perls, so https://fast2-matrix.cpantesters.org/?dist=Crypt-MatrixSSL3%20v3.9.3 shows also fail reports with older perl versions.

**Comment by jkeenan** [comment]
> t/leak.t may fail since 5.41.something like this:
> 
> ```
> #   Failed test 'MEM: newkeys_deletekeys'
> #   at t/leak.t line 270.
> #     '336'
> #         <=
> #     '288'
> # Looks like you failed 1 test of 26.
> t/leak.t .................................. 
> Dubious, test returned 1 (wstat 256, 0x100)
> Failed 1/26 subtests 
> ```
> 
> However, there are also mixed results here. For 5.41.4, both pass and fail reports exist:

I'm getting similarly inconsistent results with my CPANtesters reports (http://fast-matrix.cpantesters.org/?dist=Crypt-MatrixSSL3;os=linux;reports=1#sl=6,1).  Bisection has been frustrated by runs that report the `end` version passing.  Not sure how to proceed.

**Comment by jkeenan** [comment]
> 
> Note also that the module has a different issue with -DDEBUGGING perls, so https://fast2-matrix.cpantesters.org/?dist=Crypt-MatrixSSL3%20v3.9.3 shows also fail reports with older perl versions.

The issue on `-DDEBUGGING` builds was reported by @andk upstream at https://github.com/powerman/perl-Crypt-MatrixSSL3/issues/42 and was bisected to 6ba07ce12b from back in 2015:
```
commit 6ba07ce12b615587e55caf4477539992d4b3e79b
Author:     Jarkko Hietaniemi <jhi@iki.fi>
AuthorDate: Fri Aug 7 22:14:55 2015 -0400
Commit:     Jarkko Hietaniemi <jhi@iki.fi>
CommitDate: Fri Aug 14 15:49:58 2015 -0400

    No __attribute__((nonnull(...))) from NN.
```
(I have trouble building perls at commits that old, so I haven't been able to confirm the bisection.)

Andreas pointed to a [CPANtesters failure](http://www.cpantesters.org/cpan/report/b2e9e990-b699-11ec-b926-22d9aadf4e95) on a threaded debugging build run in 2022.  If we were to resolve that older failure it might give us a clue to dealing with the current one.

**Comment by richardleach** [comment]
> > t/leak.t may fail since 5.41.something like this:
> > ```
> > #   Failed test 'MEM: newkeys_deletekeys'
> > #   at t/leak.t line 270.
> > #     '336'
> > #         <=
> > #     '288'
> > # Looks like you failed 1 test of 26.
> > t/leak.t .................................. 
> > Dubious, test returned 1 (wstat 256, 0x100)
> > Failed 1/26 subtests 

This might also be partially https://github.com/Perl/perl5/commit/06e421c559c63975f29c35ba3588a0e6b0c75eca - test code no longer leaking as before. I'll take a look after putting in a PR for https://github.com/Perl/perl5/issues/22704

**Comment by richardleach** [comment]
> This might also be partially [06e421c](https://github.com/Perl/perl5/commit/06e421c559c63975f29c35ba3588a0e6b0c75eca)

It is. More simulated  leaking of a string buffer. PR submitted as https://github.com/powerman/perl-Crypt-MatrixSSL3/pull/45

**Comment by jkeenan** [comment]
> > This might also be partially [06e421c](https://github.com/Perl/perl5/commit/06e421c559c63975f29c35ba3588a0e6b0c75eca)
> 
> It is. More simulated leaking of a string buffer. PR submitted as [powerman/perl-Crypt-MatrixSSL3#45](https://github.com/powerman/perl-Crypt-MatrixSSL3/pull/45)

This pull request was accepted by the upstream maintainer and Crypt-MatrixSSL3-v3.9.4 was released on Nov 5.  I tested that on my CPANtesters rigs where the tests were previously failing.  They are now passing, so this ticket can be closed.  Doing so now.
