### ISSUE TITLE
[doc] typos in header files

### ISSUE THREAD

**Issue by sobrado8086** [Perl/perl5#22739]
**Where**

There are a few typos in regnodes.h and perl.h.

**Description**

See attached diffs for details.
[perl.h.patch](https://github.com/user-attachments/files/17735359/perl.h.patch)
[regnodes.h.patch](https://github.com/user-attachments/files/17735360/regnodes.h.patch)

**Comment by mauke** [comment]
`regnodes.h` is a generated file.
