### ISSUE TITLE
Devel::Size total_size segmentation fault

### ISSUE THREAD

**Issue by poti1** [Perl/perl5#22818]
Module:
`Devel::Size`

**Description**
Segmentation when using Devel::Size::total_size on a very nested structure.

**Steps to Reproduce**

```perl
perl -MDevel::Size -e '
   my $s
    $s=[$s] for 1..500_000;
    Devel::Size::total_size $s;
 '
Segmentation fault (core dumped)
 ```
 
**Expected behavior**
No segmentation fault. Maybe just report its too complex/big to calculate.

**Comment by jkeenan** [comment]
> Module: `Devel::Size`
> 

Devel::Size is not part of the Perl 5 core distribution, so this is not the place to report bugs in it.

Please file a ticket upstream at https://rt.cpan.org/Dist/Display.html?Name=Devel-Size.

Closing this ticket.
