### ISSUE TITLE
Embedded perl and putenv() don't always play nicely

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#339]
Migrated from [rt.perl.org#1170](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=1170) (status was 'open')

Searchable as RT1170$

**Comment by p5pRT** [comment]
### From Chris.Mihaly@disney.com

&nbsp;    Some recap on events\.  We were using perl 5\.005\_02 and have several
programs that have embeded perl in them\.  These programs would
sporadically coredump\.  After a lot of research\, we debugged it back to
the fact that the C\+\+ code was calling putenv after perl had run\.  When
perl ran\, it had copied the \_environ array into perl memory which then
caused putenv to die since it wanted to use the system memory routines\. 
Note that it is one application space but mutliple dynamic libraries\. 
Rasmus Tamstorf and myself submitted this problem quite a long time ago\,
and Rasmus had submitted what we thought would fix this problem and
Gurusamy had put in a better patch to the perl code based on this
requested change\.  

&nbsp;    We then rebuilt perl 5\.005\_03 with the patch from Gurusamy\.  We first
tried to use the PERL\_USE\_SAFE\_PUTENV method which worked in a limited
case\.  It would fail with a core dump if you ever did a 'delete
$ENV\{foo\}'\, since the delete thought it was perl memory and tried to
remove it as such\, which it was not and it would core dump\. There are
probably other such scenarios where perl intrinsics thought the $ENV\{\}
was in perl memory\.

&nbsp;    We then went back to EMBEDMYMALLOC which caused perl to use system
memory routines for dealing with the \_environ array\. This worked\, well
for a while\.  When 7\.2\.1 came out\, this stopped working\. Our program did
not core dump\, but when our C\+\+ program called putenv\, these changes
were having no effect and subsequent subprocess would not see the new
environment variables\.  Our guess is that the \_environ array cannot be
simply reassigned\, that there is some other internal procesing that
keeps a copy of the pointer or the array\.  This is used by the new
putenv system call\, but since perl realloced the array\, in essense there
are now two environ arrays\.  This is highly speculative since we have
not had the ability to track this down yet\, but the case is that it does
not work\.

&nbsp;    I have no solution for this\.  The original way causes core dumps
because of mismatched memory usage\, the EMBEDMYMALLOC causes putenv\(\)
calls to be disregarded in embedded applications and the SAFE\_PUTENV
causes many intrinsic perl operations to fail\. We will continue to
investigate this problem\, but the way that perl is handling the
environment is not compatable with embedded applications on SGIs\.

&nbsp;    Chris

Gurusamy Sarathy wrote&#8203;:
> 
> On Tue\, 08 Jun 1999 19&#8203;:44&#8203;:23 PDT\, Chris Mihaly wrote&#8203;:
> >       We already are using EMBEDMYMALLOC\. The problem we were trying to
> >resolve was how the \*environ object is being handled by our C\+\+ program
> >and embedded perl\.
> 
> Ahh\, got it\.
> 
> >                   The fix you included below was to make perl use the
> >system malloc when dealing with environ rather than copying it into a
> >Perl allocated space\.
> >
> >       We are a production environment\, so we are a bit weary of putting out
> >the latest dev version of Perl\.  So we though we would cheat\, and take
> >the latest official release and try to put in your patch\. However\, I
> >think what is happening is that your patch is against a version that is
> >already much latter than 5\.005\_03\.  Is what we are doing hopless and we
> >should either wait until an offiical release is out or venture into the
> >latest development version?
> 
> It should be safe to change the places identified by the patch that use
> New/Safefree/Renew \(for allocating stuff pointed at by environ\) to use
> safemalloc/safefree/saferealloc instead\.  That should be a straightforward
> change\.  I'd suggest ignoring the change in the name from safefoo\(\) to
> safesysfoo\(\) for your purposes\.
> 
> Sarathy
> gsar@&#8203;activestate\.com

\-\- 
Christopher Mihaly         Email&#8203;: Chris\.Mihaly@&#8203;disney\.com
Walt Disney Feature Animation   Phone&#8203;: \(818\) 560\-9409
500 S\. Buena Vista St\.         Fax&#8203;:   \(818\) 560\-8290
Burbank\, CA 91521\-4970

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Chris Mihaly writes&#8203;:
> but the way that perl is handling the environment is not compatable
> with embedded applications on SGIs\.

\(Chris\, I'm a baby porter\, so don't take anything I say as holy
gospel\)

Given that Perl can't assume anything about how the process implements
its environment\, it sounds like some kind of manual resync will be
required\.  That is\, Perl maintains %ENV in Perl memory land\, and every
change to %ENV corresponds to a putenv\(\) call\.  However\, if you're in
C world and do a putenv\(\)\, you would have a Perl\_restore\_environment\(\)
call to ensure %ENV knows about the changed environment\.

It appears that Perl can't use the process's environment space\.  If
Perl and C are to both be changing the environment\, this \(somewhat
kludgy\) approach would seem to be the only way out\.

Am I smoking crack?

Nat

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Thu\, 5 Aug 1999\, Nathan Torkington wrote&#8203;:

> Chris Mihaly writes&#8203;:
> > but the way that perl is handling the environment is not compatable
> > with embedded applications on SGIs\.
> 
> \(Chris\, I'm a baby porter\, so don't take anything I say as holy
> gospel\)
> 
> Given that Perl can't assume anything about how the process implements
> its environment\, it sounds like some kind of manual resync will be
> required\.  That is\, Perl maintains %ENV in Perl memory land\, and every
> change to %ENV corresponds to a putenv\(\) call\.  However\, if you're in
> C world and do a putenv\(\)\, you would have a Perl\_restore\_environment\(\)
> call to ensure %ENV knows about the changed environment\.

The approach you're describing here is in theory what PERL\_USE\_SAFE\_PUTENV
does\, but the implementation is incomplete in that 'delete $ENV\{foo\}' will
attempt to operate as if %ENV lives in perl memory\. This causes a core
dump :\-\(

> Am I smoking crack?

Nah\, not quite\, but whoever created the original semantics for putenv\(\)
must have\, 'cause otherwise we wouldn't have all these problems ;\)

Rasmus



---
Rasmus\.Tamstorf@&#8203;disney\.com         "A problem worthy of attack\, 
Walt Disney Feature Animation       proves its worth by hitting back" Kumbel


---

**Comment by Michael1095** [comment]
Bruh its been 21 years, can someone fix this please lmao

**Comment by toddr** [comment]
@Michael1095 how do you suggest we fix it?

**Comment by toddr** [comment]
For starters, $0 scribbles on envp sometimes in order to lengthen it. https://github.com/Perl/perl5/blob/blead/perl.c#L1801

**Comment by toddr** [comment]
4efc5df63c2 seems to have added this comment after this ticket was opened:
```C
/* only the parent thread can clobber the process environment */
```

**Comment by toddr** [comment]
The problem here (restated) appears to be C handing to Perl which manipulates %ENV and then wants to hand it back to C so more stuff can be done. It also appears to be re-using the memory provided to it by C to store the env vars. Perl doesn't understand that when it hands back, it needs to sync back %ENV into the C strings. 

I SUSPECT that given the changes to SHEKs and COW over the years, this problem may be very different in a modern Perl these days.

Given the age of this ticket and lacking any practical examples to reproduce this issue or access to the referred to patch, I am closing this. If someone has more details or a recent example, please open a new ticket. Thanks!
