### ISSUE TITLE
Not a bug, but did perl really mean that?

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#40]
Migrated from [rt.perl.org#842](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=842) (status was 'resolved')

Searchable as RT842$

**Comment by p5pRT** [comment]
### From jmh@mail.msen.com

Truth in perl can be a problem when dealing with bitwise operators\.
A scalar is true if it is not '' or "0" or undef\.

If we want to work with pipes\, we play with select\(\) a lot\.

pipe\(A\,B\);
pipe\(C\,D\);

\# Setup pipes\, fork\, etc\.

vec\($ready\_a\, fileno\(A\)\, 1\) = 1;
vec\($ready\_c\, fileno\(C\)\, 1\) = 1;

\#Get ready for select
vec\($rin\, fileno\(A\)\, 1\) = 1;
vec\($rin\, fileno\(C\)\, 1\) = 1;

select\($rout=$rin\, undef\, undef\, 10\);

In C\, if we want to see if a particular selector is set\, we can say&#8203;:

if \($rout & $ready\_a\) \{ \# do something useful \}

We can't do this in perl because the return of \($rout & $ready\_a\)
is "\\0" when nothing is set\.

This can be gotten around by saying&#8203;:
if \(\($rout & $ready\_a\) eq $ready\_a\) \{ \# do something useful \}

Unfortunately\, I don't know if this is good for 100% of the cases
since the items set by the vec\(\) may create strings of differing
length \(?\)\.  E\.g\. the return may be "\\0\\0"\.

Trying to evaluate things in a numeric context using == doesn't
seem to do the right thing\.

What would be most useful is\, when dealing with vectors\, to
define TRUE to not include the string of all "\\0" characters\.

I realize that using the bitcounting operator is a useful workaround\,
but it is also inelegant\.

\-\- 
Jeffrey Haas \-\+\- jmh@&#8203;msen\.com \-\+\- http&#8203;://www\.msen\.com/~jmh 
/\\/\\sen\, Inc\. "Michigan's Best Run Internet Service Provider\."

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Jeff\,

You pointed out that a string consisting of \\0 bytes isn't false\,
and so it's hard to test for in Perl\.  Solutions are&#8203;:
&nbsp;  if \($mask =~ /^\\0\*$/\)
and
&nbsp;  use IO&#8203;::Select;

I've marked the bugreport as closed\.

Cheers;

Nat

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

>Jeff\,

>You pointed out that a string consisting of \\0 bytes isn't false\,
>and so it's hard to test for in Perl\.  Solutions are&#8203;:
>  if \($mask =~ /^\\0\*$/\)

I don't think that that does what you wish it did\.

&nbsp;    open\(NEWFH\, ">/dev/null"\) || die $\!;
&nbsp;    $mask = '';
&nbsp;    vec\($mask\, fileno\(NEWFH\)\, 1\) = 1;
&nbsp;    vec\($mask\, fileno\(STDOUT\)\, 1\) = 1;
&nbsp;    if \($mask =~ /^\\0\*$/\) \{
&nbsp;    print "No bits here\!\\n";
&nbsp;    \} else \{
&nbsp;    print "Got those bits\!\\n";
&nbsp;    \} 

Prints "No bits here\."   See why? :\-\)

\-\-tom

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Tom Christiansen writes&#8203;:
> chr\( \(1 \<\< 1\) | \(1 \<\< 3\) \) eq "\\n"
> 
> and "\\n" always matches /^\\0\*$/ 
> 
> Zap\!

Oh bollocks\.  Change the regexp&#8203;:
&nbsp;  /\\A\\0\*\\Z/

Thanks for pointing that out\, Tom\.

Nat

**Comment by p5pRT** [comment]
### From @tamias

On Mon\, Mar 20\, 2000 at 09&#8203;:20&#8203;:23PM \-0700\, Nathan Torkington wrote&#8203;:
> Tom Christiansen writes&#8203;:
> > chr\( \(1 \<\< 1\) | \(1 \<\< 3\) \) eq "\\n"
> > 
> > and "\\n" always matches /^\\0\*$/ 
> > 
> > Zap\!
> 
> Oh bollocks\.  Change the regexp&#8203;:
>   /\\A\\0\*\\Z/
> 
> Thanks for pointing that out\, Tom\.

I think that should be \\z\.  \\Z can also match before a newline\.

Ronald

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Ronald J Kimball writes&#8203;:
> > Oh bollocks\.  Change the regexp&#8203;:
> >   /\\A\\0\*\\Z/
> 
> I think that should be \\z\.  \\Z can also match before a newline\.

That's it\, I'm taking up Python\.

Nat

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

>I think that should be \\z\.  \\Z can also match before a newline\.

That's right\.  That's why I\, and even moreso Greg\, went it and fixed a 
million Perl libraries that were doing /^blah$/ and meaning /\\Ablah\\z/\.
The \\Z is seductive for parallism\.  Just don't write /\\ablah\\z/\.  Ding\.

\-\-tom

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Mar 20\, Nathan Torkington said&#8203;:

>Ronald J Kimball writes&#8203;:
>> > Oh bollocks\.  Change the regexp&#8203;:
>> >   /\\A\\0\*\\Z/
>> 
>> I think that should be \\z\.  \\Z can also match before a newline\.
>
>That's it\, I'm taking up Python\.

Yeah\, good idea\.  Quadruple backslash to get a single backslash in a
regex\.  Unless you use raw string quoting\.  Nevermind\.

\-\- 
MIDN 4/C PINYAN\, NROTCURPI\, US Naval Reserve             japhy@&#8203;pobox\.com
http&#8203;://www\.pobox\.com/~japhy/                  http&#8203;://pinyaj\.stu\.rpi\.edu/
PerlMonth \- An Online Perl Magazine            http&#8203;://www\.perlmonth\.com/
The Perl Archive \- Articles\, Forums\, etc\.    http&#8203;://www\.perlarchive\.com/

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]


Tom Christiansen wrote&#8203;:
> 
> The \\Z is seductive for parallism\.

Only when using \\A\.  There is no need for \\A in /\\Ablah\\z/ since it is
only meaningful with /m\.  

&nbsp;    /^blah\\z/

I find the lack of symmetry here makes the intent clearer\.

\-\- 
Rick Delaney
rick\.delaney@&#8203;home\.com

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

>Tom Christiansen wrote&#8203;:
>> 
>> The \\Z is seductive for parallism\.

>Only when using \\A\.  There is no need for \\A in /\\Ablah\\z/ since it is
>only meaningful with /m\.  

>    /^blah\\z/

>I find the lack of symmetry here makes the intent clearer\.

That's not correct\.    $\* may be set\.

\-\-tom

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]


Tom Christiansen wrote&#8203;:
> 
> That's not correct\.    $\* may be set\.

print "The meaning of deprecated in perl is "\,
&nbsp;    \(qw/crazy sensible/\)\[1\]\,
&nbsp;    "\.\\n";

Set $\[ appropriately\.

\-\- 
Rick Delaney
rick\.delaney@&#8203;home\.com

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

>Tom Christiansen wrote&#8203;:
>> 
>> That's not correct\.    $\* may be set\.

>print "The meaning of deprecated in perl is "\,
>    \(qw/crazy sensible/\)\[1\]\,
>    "\.\\n";

>Set $\[ appropriately\.

No\, that's not the same\.  $\[ is lexical\.  $\* is global\.
You can't do anything about what someone else did in code
you're not looking at\.

\-\-tom

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]


Tom Christiansen wrote&#8203;:
> 
> >Set $\[ appropriately\.
> 
> No\, that's not the same\.  $\[ is lexical\.  $\* is global\.
&nbsp;                            ^^^^^^^^^^^^^
This\, I didn't know\, or if I ever did I promptly forgot since I never
use $\[\.

> You can't do anything about what someone else did in code
> you're not looking at\.

You are correct\.  Does it not make more sense to remove such
action\-at\-a\-distance behaviour rather than code around it?

\-\- 
Rick Delaney
rick\.delaney@&#8203;home\.com

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

>> You can't do anything about what someone else did in code
>> you're not looking at\.

>You are correct\.  Does it not make more sense to remove such
>action\-at\-a\-distance behaviour rather than code around it?

One does what one can\, as one can\.  Right now\, one can code
defensively\.  Spooky action at a distance is often disconcerting\.
I don't know whether making $\* lexical like $\] is something we
could do yet\.  

\-\-tom

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]


Tom Christiansen wrote&#8203;:
> 
> One does what one can\, as one can\.  Right now\, one can code

And that is appreciated\.

> defensively\.  Spooky action at a distance is often disconcerting\.
> I don't know whether making $\* lexical like $\] is something we
> could do yet\.

I see no reason to ever go there\.  IMHO\, it is time for $\* to retire
gracefully\.  He's been deprecated long enough and the younger players /s
and /m seem to be competing quite nicely\.

\-\- 
Rick Delaney
rick\.delaney@&#8203;home\.com

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Is this right?

% P \-MO=Showlex\,retval \-e 'sub retval \{ my $self = shift; my $n = sub \{ my $arg = shift;  return $self\->\{$arg\} \} \} '
Pad of lexical names for &retval has 5 entries
0&#8203;: SPECIAL \#1 &PL\_sv\_undef
1&#8203;: PVNV \(0x8193810\) "$self"
2&#8203;: SPECIAL \#1 &PL\_sv\_undef
3&#8203;: PVNV \(0x81938a0\) "$n"
4&#8203;: PVNV \(0x81938ac\) "&"
Pad of lexical values for &retval has 5 entries
0&#8203;: AV \(0x81944f4\) FILL \-1
1&#8203;: NULL \(0x80f522c\)
2&#8203;: NULL \(0x8193804\)
3&#8203;: NULL \(0x8193894\)
4&#8203;: CV \(0x81938b8\) 0

What's all that well\, stuff?  And what's the thing whose name is
"&" all about?  You run with Xref and it doesn't show up\.

% P \-MO=Xref  \-e 'sub retval \{ my $self = shift; my $n = sub \{ my $arg = shift;  return $self\->\{$arg\} \} \} '
File \-e
&nbsp;  Subroutine \(definitions\)
&nbsp;    Package UNIVERSAL
&nbsp;      &VERSION          s0
&nbsp;      &can              s0
&nbsp;      &isa              s0
&nbsp;    Package attributes
&nbsp;      &bootstrap        s0
&nbsp;    Package main
&nbsp;      &retval           s1
&nbsp;  Subroutine retval
&nbsp;    Package \(lexical\)
&nbsp;      $n                i1
&nbsp;      $self             i1
&nbsp;    Package main
&nbsp;      @&#8203;\_                1

Here are more\.

% perl \-MO=Showlex /tmp/testit
Pad of lexical names for comppadlist has 0 entries
Pad of lexical values for comppadlist has 1 entries
0&#8203;: SPECIAL \#1 &PL\_sv\_undef
/tmp/testit syntax OK

% perl \-MO=Showlex\,start /tmp/testit
Pad of lexical names for &start has 27 entries
0&#8203;: SPECIAL \#1 &PL\_sv\_undef
1&#8203;: PVNV \(0x8193774\) "$self"
2&#8203;: PVNV \(0x81937f8\) "$tag"
3&#8203;: PVNV \(0x8193810\) "$attr"
4&#8203;: PVNV \(0x8193828\) "$attrseq"
5&#8203;: PVNV \(0x8193840\) "$orig"
6&#8203;: SPECIAL \#1 &PL\_sv\_undef
7&#8203;: SPECIAL \#1 &PL\_sv\_undef
8&#8203;: SPECIAL \#1 &PL\_sv\_undef
9&#8203;: SPECIAL \#1 &PL\_sv\_undef
10&#8203;: SPECIAL \#1 &PL\_sv\_undef
11&#8203;: PVNV \(0x8194458\) "$tmp"
12&#8203;: SPECIAL \#1 &PL\_sv\_undef
13&#8203;: SPECIAL \#1 &PL\_sv\_undef
14&#8203;: SPECIAL \#1 &PL\_sv\_undef
15&#8203;: PVNV \(0x81944dc\) "$encoded"
16&#8203;: SPECIAL \#1 &PL\_sv\_undef
17&#8203;: SPECIAL \#1 &PL\_sv\_undef
18&#8203;: SPECIAL \#1 &PL\_sv\_undef
19&#8203;: SPECIAL \#1 &PL\_sv\_undef
20&#8203;: SPECIAL \#1 &PL\_sv\_undef
21&#8203;: SPECIAL \#1 &PL\_sv\_undef
22&#8203;: SPECIAL \#1 &PL\_sv\_undef
23&#8203;: SPECIAL \#1 &PL\_sv\_undef
24&#8203;: SPECIAL \#1 &PL\_sv\_undef
25&#8203;: SPECIAL \#1 &PL\_sv\_undef
26&#8203;: SPECIAL \#1 &PL\_sv\_undef
Pad of lexical values for &start has 27 entries
0&#8203;: AV \(0x81945e4\) FILL \-1
1&#8203;: NULL \(0x80f56a8\)
2&#8203;: NULL \(0x8193768\)
3&#8203;: NULL \(0x8193804\)
4&#8203;: NULL \(0x819381c\)
5&#8203;: NULL \(0x8193834\)
6&#8203;: NULL \(0x819384c\)
7&#8203;: NULL \(0x8194404\)
8&#8203;: NULL \(0x8194428\)
9&#8203;: NULL \(0x8194440\)
10&#8203;: NULL \(0x8194464\)
11&#8203;: NULL \(0x819444c\)
12&#8203;: NULL \(0x8194488\)
13&#8203;: NULL \(0x81944b8\)
14&#8203;: NULL \(0x81944c4\)
15&#8203;: NULL \(0x81944d0\)
16&#8203;: NULL \(0x81944e8\)
17&#8203;: NULL \(0x819450c\)
18&#8203;: NULL \(0x819453c\)
19&#8203;: NULL \(0x8194548\)
20&#8203;: NULL \(0x8194560\)
21&#8203;: NULL \(0x8194518\)
22&#8203;: NULL \(0x819456c\)
23&#8203;: NULL \(0x8194578\)
24&#8203;: NULL \(0x8194584\)
25&#8203;: NULL \(0x819
\[truncate \-\-tchrist\]

That was from this guy that you saw before&#8203;:

% cat /tmp/testit 
sub start \{
&nbsp;   my\($self\, $tag\, $attr\, $attrseq\, $orig\) = @&#8203;\_;
&nbsp;   if \($tag eq 'a' && exists $attr\->\{href\}\) \{
&nbsp;       if \($attr\->\{href\} =~ s/\\Q$from/$to/g\) \{
&nbsp;           \# must reconstruct the start tag based on $tag and $attr\.
&nbsp;           \# wish we instead were told the extent of the 'href' value
&nbsp;           \# in $orig\.
&nbsp;           my $tmp = "\<$tag";
&nbsp;           for \(@&#8203;$attrseq\) \{
&nbsp;               my $encoded = encode\_entities\($attr\->\{$\_\}\);
&nbsp;               $tmp \.= qq\( $\_="$encoded "\);
&nbsp;           \}
&nbsp;           $tmp \.= ">";
&nbsp;           $self\->output\($tmp\);
&nbsp;           return;
&nbsp;       \}
&nbsp;   \}
&nbsp;   $self\->output\($orig\);
\}

\-\-tom

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

>However\, it blows up completely in the B&#8203;:CC case\.  

\.\.\.

>Finally\, if your program does something like 'use Fcntl'\, you get
>142 lines of the following form&#8203;:

\.\.\.\.

Note that those two\, at least\, are not platform specific\.

\-\-tom

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

>This seems to better match expected usage and desirable properties\.
>Can anybody think of any good reason why the debugger should not
>be fixed to work this way?  \(Actually\, I've already got the patch\,
>but wanted to run the idea by the world first\.\)

Well\, I've heard nothing\, so here's the patch that implements this\.

<details><summary>Inline Patch</summary>

```diff
--- perl5db.pl-presig	Tue Mar 14 18:42:13 2000
+++ perl5db.pl	Wed Mar 15 06:23:49 2000
@@ -346,16 +346,24 @@
     return 1;
 }
 
-if (-f $rcfile) {
-    safe_do("./$rcfile");
-} 
-elsif (defined $ENV{HOME} && -f "$ENV{HOME}/$rcfile") {
+{ 
+    my @sb;	# stat buff to check duplicate loading
+    if (defined $ENV{HOME} && -f "$ENV{HOME}/$rcfile") {
+	@sb = stat(_);
     safe_do("$ENV{HOME}/$rcfile");
-}
-elsif (defined $ENV{LOGDIR} && -f "$ENV{LOGDIR}/$rcfile") {
+    }
+    elsif (defined $ENV{LOGDIR} && -f "$ENV{LOGDIR}/$rcfile") {
+	@sb = stat(_);
     safe_do("$ENV{LOGDIR}/$rcfile");
-} 
+    } 
 
+    if (-f $rcfile) {
+	if (@sb && $sb[0] != (stat _)[0] && $sb[1] != (stat _)[1]) { 
+	    safe_do("./$rcfile");
+	}
+    } 
+
+}
 if (defined $ENV{PERLDB_OPTS}) {
     parse_options($ENV{PERLDB_OPTS});
 }
```
</details>

**Comment by suraj-rixing** [comment]
How long has it been, dear god.

**Comment by iabyn** [comment]
On Fri, Mar 08, 2024 at 05:07:30PM -0800, dao.rixing wrote:
> How long has it been, dear god.

How long has *what* been? What exactly are you trying to contribute to, or
a complain about, in relation to this long-closed ticket?

-- 
All wight. I will give you one more chance. This time, I want to hear
no Wubens. No Weginalds. No Wudolf the wed-nosed weindeers.
    -- Life of Brian
