### ISSUE TITLE
core dump in Perl_regexec_flags

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#4997]
Migrated from [rt.perl.org#8476](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=8476) (status was 'open')

Searchable as RT8476$

**Comment by p5pRT** [comment]
### From @eserte


This is a bug report for perl from eserte@&#8203;vran\.herceg\.de\,
generated with the help of perlbug 1\.33 running under perl v5\.7\.2\.




---
I'm not sure whether this is a Perl/Tk or perl problem&#8203;:

In Perl/Tk there is a call to pregexec with a NULL as 6th argument&#8203;:

 return pregexec\(re\,string\,string\+strlen\(string\)\,start\,0\,NULL\,1\);

\(this is in file tkGlue\.c\)\.

In perl's Perl\_regexec\_flags function\, a core will be dumped at line
1427&#8203;:

&nbsp;    bool do\_utf8 = DO\_UTF8\(sv\);

The problem is fixed if I change the line to&#8203;:

&nbsp;    bool do\_utf8 = sv && DO\_UTF8\(sv\);

Regards\,
&nbsp;    Slaven



---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=medium


---
Site configuration information for perl v5\.7\.2&#8203;:

Configured by eserte at Sat Feb  9 22&#8203;:33&#8203;:02 CET 2002\.

Summary of my perl5 \(revision 5\.0 version 7 subversion 2 patch 14574\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=freebsd\, osvers=4\.3\-stable\, archname=i386\-freebsd\-64int
&nbsp;    uname='freebsd vran\.herceg\.de 4\.3\-stable freebsd 4\.3\-stable \#6&#8203;: mon jul 9 11&#8203;:49&#8203;:47 cest 2001 root@&#8203;vran\.herceg\.de&#8203;:vranhomesrcfreebsd\-4srcsyscompilevran i386 '
&nbsp;    config\_args='\-Doptimize=\-g \-DPERL\_DEBUGGING\_MSTATS \-Dusemymalloc=y \-Dprefix=/usr/perl5\.7\.2d \-D usedevel=define \-de \-D hintfile=myfreebsd'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=define use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=y\, bincompat5005=define
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-DHAS\_FPSETMASK \-DHAS\_FLOATINGPOINT\_H \-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include'\,
&nbsp;    optimize='\-g \-DPERL\_DEBUGGING\_MSTATS'\,
&nbsp;    cppflags='\-DHAS\_FPSETMASK \-DHAS\_FLOATINGPOINT\_H \-DDEBUGGING \-fno\-strict\-aliasing \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='2\.95\.3 \[FreeBSD\] 20010315 \(release\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags ='\-Wl\,\-E  \-L/usr/local/lib'
&nbsp;    libpth=/usr/lib /usr/local/lib
&nbsp;    libs=\-lbind \-lgdbm \-ldb \-lm \-lc \-lcrypt \-lutil
&nbsp;    perllibs=\-lbind \-lm \-lc \-lcrypt \-lutil
&nbsp;    libc=\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags='\-DPIC \-fpic'\, lddlflags='\-shared  \-L/usr/local/lib'

Locally applied patches&#8203;:
&nbsp;    DEVEL14574



---
@&#8203;INC for perl v5\.7\.2&#8203;:
&nbsp;    lib
&nbsp;    /usr/perl5\.7\.2d/lib/5\.7\.2/i386\-freebsd\-64int
&nbsp;    /usr/perl5\.7\.2d/lib/5\.7\.2
&nbsp;    /usr/perl5\.7\.2d/lib/site\_perl/5\.7\.2/i386\-freebsd\-64int
&nbsp;    /usr/perl5\.7\.2d/lib/site\_perl/5\.7\.2
&nbsp;    /usr/perl5\.7\.2d/lib/site\_perl
&nbsp;    \.



---
Environment for perl v5\.7\.2&#8203;:
&nbsp;    HOME=/home/e/eserte
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LC\_ALL=de\_DE\.ISO\_8859\-1
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/usr/X11R6/bin&#8203;:/usr/X11/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/gnu/bin&#8203;:/usr/TeX/bin&#8203;:/usr/local/sbin&#8203;:/usr/sbin&#8203;:/sbin&#8203;:/usr/local/pilot/bin&#8203;:/home/e/eserte/bin/FreeBSD&#8203;:/home/e/eserte/bin/sh&#8203;:/home/e/eserte/bin&#8203;:/usr/X386/bin&#8203;:/usr/games&#8203;:/home/e/eserte/devel
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/usr/local/bin/tcsh

**Comment by p5pRT** [comment]
### From @vanstyn

Slaven Rezic \<eserte@&#8203;vran\.herceg\.de> wrote&#8203;:
:I'm not sure whether this is a Perl/Tk or perl problem&#8203;:
\[\.\.\.\]
:
:In perl's Perl\_regexec\_flags function\, a core will be dumped at line
:1427&#8203;:
:    bool do\_utf8 = DO\_UTF8\(sv\);

That's a problem with the regexp engine\.

:The problem is fixed if I change the line to&#8203;:
:
:    bool do\_utf8 = sv && DO\_UTF8\(sv\);

That's fine as a starting point\, but I suspect we need the ability to
match on an SV\-less UTF8 string as well\. Perhaps we should add a flag
for the purpose? Then the above could be&#8203;:
&nbsp;  bool do\_utf8 = sv ? DO\_UTF8\(sv\) : flags & REXEC\_UTF8;

Note also that this would require some fixup for the debugging \(which
assumes an sv if utf8\) and for screaminstr\(\) calls \(which assume an sv
if REXEC\_SCREAM\)\.

Hugo

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

Hugo Van Der Sanden \<hv@&#8203;crypt0\.demon\.co\.uk> writes&#8203;:
>Slaven Rezic \<eserte@&#8203;vran\.herceg\.de> wrote&#8203;:
>&#8203;:I'm not sure whether this is a Perl/Tk or perl problem&#8203;:
>\[\.\.\.\]
>&#8203;:
>&#8203;:In perl's Perl\_regexec\_flags function\, a core will be dumped at line
>&#8203;:1427&#8203;:
>&#8203;:    bool do\_utf8 = DO\_UTF8\(sv\);
>
>That's a problem with the regexp engine\.

And Tk ;\-\)

>
>&#8203;:The problem is fixed if I change the line to&#8203;:
>&#8203;:
>&#8203;:    bool do\_utf8 = sv && DO\_UTF8\(sv\);
>
>That's fine as a starting point\, 

There are other references to sv further down \- some guarded\, some not
\(in my quick scan\)\.

>but I suspect we need the ability to
>match on an SV\-less UTF8 string as well\. 

I have no real problem requiring an SV for this\.
I just patched Tk to construct one\.
What mislead me was that SV \* parameter used to be called 'screamer' 
and was something to do with 'study'\. I never understood that and did 
not known that SV \* \_was\_ the string\. 

When Unicode\-aware Tk gets out it will only ever use this on UTF\-8 strings\.

>Perhaps we should add a flag
>for the purpose? Then the above could be&#8203;:
>  bool do\_utf8 = sv ? DO\_UTF8\(sv\) : flags & REXEC\_UTF8;
>
>Note also that this would require some fixup for the debugging \(which
>assumes an sv if utf8\) and for screaminstr\(\) calls \(which assume an sv
>if REXEC\_SCREAM\)\.
>
>Hugo
\-\- 
Nick Ing\-Simmons
http&#8203;://www\.ni\-s\.u\-net\.com/

**Comment by p5pRT** [comment]
### From @khwilliamson

Is this still an issue?
\-\- 
Karl Williamson

**Comment by khwilliamson** [comment]
I'm closing this.  I asked  two years ago if this is still an issue, without response.  Further investigation reveals that this parameter may no longer be NULL, since 
commit 4373e329bbd25cac77cfe128757db8cbb63c47bb
 Author: Andy Lester <andy@petdance.com>
 Date:   Wed May 4 23:55:00 2005 +0000
