### ISSUE TITLE
FW: use lines crash Perl.exe

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#56]
Migrated from [rt.perl.org#858](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=858) (status was 'resolved')

Searchable as RT858$

**Comment by p5pRT** [comment]
### From wgd@adelaide.on.net

Sent again due to a problem with your mail script\.

\-\-\-\-\-Original Message\-\-\-\-\-
From&#8203;: Alex \[mailto&#8203;:wgd@&#8203;adelaide\.on\.net\]
Sent&#8203;: Saturday\, 29 May 1999 15&#8203;:13
To&#8203;: perlbug@&#8203;perl\.com
Subject&#8203;: use lines crash Perl\.exe


Hi\, this is about a problem I'm having with any perl script which contains
any of these lines&#8203;:

use Socket;
use Fcntl;

Anything that doesn't have Library&#8203;::Something will make it crash \(except use
strict\)\.
My Perl exe file is perl5\.00503\.exe in the ActivePerl
build 516 distribution\. I'm running Sambar Server 4\.1 using Netscape
Navigator 4\.08 to test my scripts\. The script\, Dr Watson report\, and perl \-V
output is enclosed\.
I seriously need this to work ASAP\!

Thanks for your help and keep up the excellent work\.

Alex\, mailto&#8203;:arangas@&#8203;yahoo\.com\.au
TOUECCANS \- http&#8203;://www\.geocities\.com/SiliconValley/Way/5843/
Eye Candy\, Fractals and Raytracing with Reviews\, Downloads and Links\!

**Comment by p5pRT** [comment]
### From wgd@adelaide.on.net


Microsoft \(R\) Windows NT \(TM\) Version 4\.00 DrWtsn32
Copyright \(C\) 1985\-1996 Microsoft Corp\. All rights reserved\.



Application exception occurred&#8203;:
&nbsp;        App&#8203;:  \(pid=192\)
&nbsp;        When&#8203;: 5/25/1999 @&#8203; 16&#8203;:33&#8203;:54\.216
&nbsp;        Exception number&#8203;: c0000005 \(access violation\)

\*\-\-\-\-> System Information \<\-\-\-\-\*
&nbsp;        Computer Name&#8203;: CONTROL
&nbsp;        User Name&#8203;: Administrator
&nbsp;        Number of Processors&#8203;: 1
&nbsp;        Processor Type&#8203;: x86 Family 6 Model 3 Stepping 4
&nbsp;        Windows Version&#8203;: 4\.0
&nbsp;        Current Build&#8203;: 1381
&nbsp;        Service Pack&#8203;: 4
&nbsp;        Current Type&#8203;: Uniprocessor Free
&nbsp;        Registered Organization&#8203;: 
&nbsp;        Registered Owner&#8203;: A R Angas

\*\-\-\-\-> Task List \<\-\-\-\-\*
&nbsp;   0 Idle\.exe
&nbsp;   2 System\.exe
&nbsp;  20 smss\.exe
&nbsp;  26 CSRSS\.exe
&nbsp;  34 WINLOGON\.exe
&nbsp;  40 SERVICES\.exe
&nbsp;  43 LSASS\.exe
&nbsp;  70 SPOOLSS\.exe
&nbsp;  78 amgrsrvc\.exe
&nbsp;  87 Mcshield\.exe
&nbsp;  93 NDDEAGNT\.exe
 100 EXPLORER\.exe
 105 VsTskMgr\.exe
 119 mgasc\.exe
 126 RPCSS\.exe
 127 mgactrl\.exe
 138 TAPISRV\.exe
&nbsp;  97 RASMAN\.exe
 149 esserver\.exe
 157 PSTORES\.exe
 160 LOADWC\.exe
 162 sens\.exe
 168 shstat\.exe
 166 mgahook\.exe
 180 NDetect\.exe
 182 starter\.exe
 185 Taskmenu\.exe
 199 EditPad\.exe
 227 NTVDM\.exe
 228 server\.exe
 146 netscape\.exe
 192 PERL\.exe
 203 DRWTSN32\.exe
&nbsp;   0 \_Total\.exe

\(00400000 \- 00400000\) 
\(77f60000 \- 77fbc000\) dll\\ntdll\.dbg
\(00240000 \- 00240000\) 
\(77f00000 \- 77f5e000\) dll\\kernel32\.dbg
\(77e70000 \- 77ec4000\) dll\\user32\.dbg
\(77ed0000 \- 77efc000\) dll\\gdi32\.dbg
\(77dc0000 \- 77dff000\) dll\\advapi32\.dbg
\(77e10000 \- 77e67000\) dll\\rpcrt4\.dbg
\(002a0000 \- 002a0000\) 
\(10000000 \- 10000000\) 
\(78000000 \- 78000000\) 

State Dump for Thread Id 0xbc

eax=008842f0 ebx=00000001 ecx=00000000 edx=10005860 esi=0030eed8 edi=0030eed8
eip=10003855 esp=0012fcf8 ebp=00000000 iopl=0         nv up ei pl zr na po nc
cs=001b  ss=0023  ds=0023  es=0023  fs=0038  gs=0000             efl=00010246


function&#8203;: \<nosymbols>
&nbsp;        1000382a 56               push    esi
&nbsp;        1000382b 57               push    edi
&nbsp;        1000382c 6860580010       push    0x10005860
&nbsp;        10003831 ff1508400010     call    dword ptr \[10004008\]   ds&#8203;:10004008=77f674c0
&nbsp;        10003837 8b742430         mov     esi\,\[esp\+0x30\]         ss&#8203;:0158e6ff=????????
&nbsp;        1000383b 893578580010     mov     \[10005878\]\,esi         ds&#8203;:10005878=0030eed8
&nbsp;        10003841 8b8e5c060000     mov     ecx\,\[esi\+0x65c\]        ds&#8203;:0030f534=00000000
&nbsp;        10003847 8b8628060000     mov     eax\,\[esi\+0x628\]        ds&#8203;:0030f500=008842f0
&nbsp;        1000384d 8b9e1c060000     mov     ebx\,\[esi\+0x61c\]        ds&#8203;:0030f4f4=00000001
&nbsp;        10003853 33ed             xor     ebp\,ebp
FAULT \->10003855 8b11             mov     edx\,\[ecx\]              ds&#8203;:00000000=????????
&nbsp;        10003857 83c1fc           add     ecx\,0xfc
&nbsp;        1000385a 898e5c060000     mov     \[esi\+0x65c\]\,ecx        ds&#8203;:0030f534=00000000
&nbsp;        10003860 896c2424         mov     \[esp\+0x24\]\,ebp         ss&#8203;:0158e6ff=????????
&nbsp;        10003864 8d1490           lea     edx\,\[eax\+edx\*4\]        ds&#8203;:10005860=003f03a0
&nbsp;        10003867 896c2410         mov     \[esp\+0x10\]\,ebp         ss&#8203;:0158e6ff=????????
&nbsp;        1000386b 8bfa             mov     edi\,edx
&nbsp;        1000386d 2bda             sub     ebx\,edx
&nbsp;        1000386f 2bf8             sub     edi\,eax
&nbsp;        10003871 c1ff02           sar     edi\,0x2
&nbsp;        10003874 47               inc     edi
&nbsp;        10003875 c1fb02           sar     ebx\,0x2

\*\-\-\-\-> Stack Back Trace \<\-\-\-\-\*

FramePtr ReturnAd Param\#1  Param\#2  Param\#3  Param\#4  Function Name
00000000 00000000 00000000 00000000 00000000 00000000 \<nosymbols> 

\*\-\-\-\-> Raw Stack Dump \<\-\-\-\-\*
0012fcf8  d8 ee 30 00 00 00 00 00 \- 68 fd 12 00 dc 62 8c 00  \.\.0\.\.\.\.\.h\.\.\.\.b\.\.
0012fd08  30 07 89 00 1c 99 8c 00 \- dc 62 8c 00 b0 ff 12 00  0\.\.\.\.\.\.\.\.b\.\.\.\.\.\.
0012fd18  d8 3e 00 10 ff ff ff ff \- 56 01 2d 00 dc 62 8c 00  \.>\.\.\.\.\.\.V\.\-\.\.b\.\.
0012fd28  d8 ee 30 00 06 00 00 00 \- 08 4e 88 00 30 07 89 00  \.\.0\.\.\.\.\.\.N\.\.0\.\.\.
0012fd38  00 00 00 00 10 4c 88 00 \- 02 00 00 00 24 d4 8c 00  \.\.\.\.\.L\.\.\.\.\.\.$\.\.\.
0012fd48  68 fd 12 00 0c 4c 88 00 \- 68 fd 12 01 80 00 00 00  h\.\.\.\.L\.\.h\.\.\.\.\.\.\.
0012fd58  1b 00 00 00 d8 ee 30 00 \- 06 00 00 00 0c 4c 88 00  \.\.\.\.\.\.0\.\.\.\.\.\.L\.\.
0012fd68  70 fd 12 00 51 ce 2d 00 \- f0 fd 12 00 dc 60 2b 00  p\.\.\.Q\.\-\.\.\.\.\.\.\`\+\.
0012fd78  01 00 00 00 c4 c4 88 00 \- 54 c5 88 00 0c fe 12 00  \.\.\.\.\.\.\.\.T\.\.\.\.\.\.\.
0012fd88  f0 fd 12 00 08 4e 88 00 \- d8 ee 30 00 06 00 00 00  \.\.\.\.\.N\.\.\.\.0\.\.\.\.\.
0012fd98  78 fd 12 00 ed 5f 2b 00 \- b0 ff 12 00 ff ff ff ff  x\.\.\.\.\_\+\.\.\.\.\.\.\.\.\.
0012fda8  00 00 00 00 00 00 00 00 \- 00 00 00 00 00 00 00 00  \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.
0012fdb8  00 00 00 00 00 00 00 00 \- 00 00 00 00 42 00 00 00  \.\.\.\.\.\.\.\.\.\.\.\.B\.\.\.
0012fdc8  00 00 b0 fd 12 00 00 00 \- c4 c4 88 00 00 00 00 00  \.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.
0012fdd8  00 00 00 00 2c 44 24 00 \- 03 00 00 00 08 00 00 00  \.\.\.\.\,D$\.\.\.\.\.\.\.\.\.
0012fde8  00 00 00 00 04 4c 88 00 \- 44 fe 12 00 13 85 2b 00  \.\.\.\.\.L\.\.D\.\.\.\.\.\+\.
0012fdf8  c4 c4 88 00 06 00 00 00 \- 58 f0 88 00 c4 c4 88 00  \.\.\.\.\.\.\.\.X\.\.\.\.\.\.\.
0012fe08  01 00 00 00 0c ff 12 00 \- 44 fe 12 00 54 c5 88 00  \.\.\.\.\.\.\.\.D\.\.\.T\.\.\.
0012fe18  01 00 00 00 c4 c4 88 00 \- 00 fe 12 00 92 84 2b 00  \.\.\.\.\.\.\.\.\.\.\.\.\.\.\+\.
0012fe28  b0 ff 12 00 ff ff ff ff \- 00 00 00 00 00 19 2a 00  \.\.\.\.\.\.\.\.\.\.\.\.\.\.\*\.

**Comment by p5pRT** [comment]
### From wgd@adelaide.on.net

[altest.pl](https://rt-archive.perl.org/perl5/Ticket/Attachment/3983/3695/altest.pl)

**Comment by p5pRT** [comment]
### From wgd@adelaide.on.net

Summary of my perl5 \(5\.0 patchlevel 5 subversion 03\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=MSWin32\, osvers=4\.0\, archname=MSWin32\-x86\-object
&nbsp;    uname=''
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=undef
&nbsp;    usethreads=undef useperlio=undef d\_sfio=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cl\.exe'\, optimize='\-Od \-MD \-DNDEBUG \-TP \-GX'\, gccversion=
&nbsp;    cppflags='\-DWIN32'
&nbsp;    ccflags ='\-Od \-MD \-DNDEBUG \-TP \-GX \-DWIN32 \-D\_CONSOLE \-DNO\_STRICT  \-DHAVE\_DES\_FCRYPT \-DPERL\_OBJECT'
&nbsp;    stdchar='char'\, d\_stdstdio=define\, usevfork=false
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8
&nbsp;    d\_longlong=undef\, longlongsize=8\, d\_longdbl=define\, longdblsize=10
&nbsp;    alignbytes=8\, usemymalloc=n\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='link'\, ldflags ='\-nologo \-nodefaultlib \-release \-machine&#8203;:x86'
&nbsp;    libpth="C&#8203;:\\Perl\\lib\\core" 
&nbsp;    libs= oldnames\.lib kernel32\.lib user32\.lib gdi32\.lib  winspool\.lib comdlg32\.lib advapi32\.lib shell32\.lib ole32\.lib  oleaut32\.lib netapi32\.lib uuid\.lib wsock32\.lib mpr\.lib winmm\.lib  version\.lib odbc32\.lib odbccp32\.lib PerlCRT\.lib
&nbsp;    libc=C&#8203;:\\Perl\\lib\\CORE\\PerlCRT\.lib\, so=dll\, useshrplib=yes\, libperl=perlcore\.lib
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_win32\.xs\, dlext=dll\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags=' '\, lddlflags='\-dll \-nologo \-nodefaultlib \-release \-machine&#8203;:x86'


Characteristics of this binary \(from libperl\)&#8203;: 
&nbsp;  Locally applied patches&#8203;:
&nbsp;      ActivePerl Build 516
&nbsp;  Built under MSWin32
&nbsp;  Compiled at May 14 1999 19&#8203;:54&#8203;:31
&nbsp;  @&#8203;INC&#8203;:
&nbsp;    C&#8203;:/Perl/lib
&nbsp;    C&#8203;:/Perl/site/lib
&nbsp;    \.

**Comment by IM-TECHNO** [comment]
Why hasn't this been closed yet ?
