### ISSUE TITLE
DJGPP input buffering bug while system()

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6056]
Migrated from [rt.perl.org#18218](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=18218) (status was 'open')

Searchable as RT18218$

**Comment by p5pRT** [comment]
### From DanVDascalescu@yahoo.com

This is a bug report for perl from danvdascalescu@&#8203;yahoo\.com\,
generated with the help of perlbug 1\.34 running under perl v5\.6\.1\.

\#\! perl \-w
\# This program outputs itself to STDOUT under most perl builds\, except DJGPP\.
\# Tested with perl 5\.8\.0 built for DJGPP\. Setting $| to 1 for FH and STDOUT
\# doesn't help \(this is an \*input\* buffering problem and $| is documented to
\# affect only output\)\. Opening the file only for reading doesn't reproduce
\# the bug\.

open FH\, "\+\< $0" or die "Can't open myself\! \(R/O\)?";  \# read\-write mode\!

while \(\<FH>\)
&nbsp;  \{ print;
&nbsp;    \`perl \-\-version\`;
&nbsp;  \}



Hope this helps\,
Dan V\. Dascalescu



---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=medium


---
Site configuration information for perl v5\.6\.1&#8203;:

Configured by Zastai at Sat Oct  6 14&#8203;:15&#8203;:40 CEST 2001\.

Summary of my perl5 \(revision 5\.0 version 6 subversion 1\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=dos\, osvers=djgpp\, archname=dos\-djgpp
&nbsp;    uname='ms\-dos fatboyti 8 00 pc '
&nbsp;    config\_args=''
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
&nbsp;    useperlio=undef d\_sfio=undef uselargefiles=undef usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc'\, ccflags ='\-DPERL\_EXTERNAL\_GLOB \-fno\-strict\-aliasing'\,
&nbsp;    optimize='\-O6'\,
&nbsp;    cppflags='\-DPERL\_EXTERNAL\_GLOB \-fno\-strict\-aliasing'
&nbsp;    ccversion=''\, gccversion='2\.95\.2 19991024 \(release\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=4
&nbsp;    alignbytes=4\, usemymalloc=n\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ld'\, ldflags ='\-s'
&nbsp;    libpth=/dev/env/DJDIR/lib
&nbsp;    libs=\-lgdbm \-lm \-lc \-liconv \-lcharset
&nbsp;    perllibs=\-lgdbm \-lm \-lc \-liconv \-lcharset
&nbsp;    libc=/dev/env/DJDIR/lib/libc\.a\, so=none\, useshrplib=false\, libperl=libperl\.a
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_none\.xs\, dlext=none\, d\_dlsymun=undef\, ccdlflags=''
&nbsp;    cccdlflags=''\, lddlflags=''

Locally applied patches&#8203;:




---
@&#8203;INC for perl v5\.6\.1&#8203;:
&nbsp;    /dev/env/DJDIR/lib/perl5
&nbsp;    /dev/env/DJDIR/lib/perl5/site
&nbsp;    /dev/env/DJDIR/lib/perl5/site
&nbsp;    /dev/env/DJDIR/lib/perl5/site
&nbsp;    \.



---
Environment for perl v5\.6\.1&#8203;:
&nbsp;    HOME \(unset\)
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=C&#8203;:\\DN;D&#8203;:\\DJGPP\\BIN;D&#8203;:\\PRG\\ASM;D&#8203;:\\PRG\\BP;D&#8203;:\\PRG\\BC\\BIN;C&#8203;:\\WINDOWS;C&#8203;:\\WINDOWS\\COMMAND;
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL \(unset\)



---
Xnet scaneaza automat toate mesajele impotriva virusilor folosind RAV AntiVirus\.
Xnet automatically scans all messages for viruses using RAV AntiVirus\.

Nota&#8203;: RAV AntiVirus poate sa nu detecteze toti virusii noi sau toate variantele lor\. Va rugam sa luati in considerare ca exista un risc de fiecare data cand deschideti fisiere atasate si ca MobiFon nu este responsabila pentru nici un prejudiciu cauzat de virusi\.
Disclaimer&#8203;: RAV AntiVirus may not be able to detect all new viruses and variants\. Please be aware that there is a risk involved whenever opening e\-mail attachments to your computer and that MobiFon is not responsible for any damages caused by viruses\.

**Comment by p5pRT** [comment]
@chorny - Status changed from 'new' to 'stalled'

**Comment by p5pRT** [comment]
### From @Hugmeir

On Mon Nov 04 08&#8203;:14&#8203;:23 2002\, dandv wrote&#8203;:
> \# This program outputs itself to STDOUT under most perl builds\, except
>    DJGPP\.
> \# Tested with perl 5\.8\.0 built for DJGPP\. Setting $| to 1 for FH and
>    STDOUT

Is anyone still building Perl on DJGPP? If so\, could we get an update on 
the status of this ticket?
Otherwise\, maybe we should start considering removing this port from the 
core\.

\-\-hugmeir

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'stalled' to 'open'

**Comment by p5pRT** [comment]
### From @jkeenan

On 5/28/12 7&#8203;:32 PM\, Brian Fraser via RT wrote&#8203;:
> On Mon Nov 04 08&#8203;:14&#8203;:23 2002\, dandv wrote&#8203;:
>> \# This program outputs itself to STDOUT under most perl builds\, except
>>     DJGPP\.
>> \# Tested with perl 5\.8\.0 built for DJGPP\. Setting $| to 1 for FH and
>>     STDOUT
>
> Is anyone still building Perl on DJGPP? If so\, could we get an update on
> the status of this ticket?
> Otherwise\, maybe we should start considering removing this port from the
> core\.
>
> \-\-hugmeir
>
>

The web site is still functional&#8203;:  http&#8203;://www\.delorie\.com/djgpp/\, though 
it looks as if the last major release was years ago\.  There still 
appears to be a news group devoted to DJGPP; it's summarized here&#8203;:
http&#8203;://groups\.google\.com/group/comp\.os\.msdos\.djgpp/topics\.  Presumably\, 
we could post there to gauge the interest for Perl 5 maintenance\.

jimk

**Comment by ilmari** [comment]
With #19176 merged, the DOS/DJGPP port no longer exists, closing this issue.
