### ISSUE TITLE
perl5.6.1 dos (djgpp) source build broke

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6352]
Migrated from [rt.perl.org#21461](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=21461) (status was 'stalled')

Searchable as RT21461$

**Comment by p5pRT** [comment]
### From gelgin@yahoo.com

Neither of the automated methods of building perl 5\.6\.1 worked ie\.

&nbsp;    \./djgpp/configure\.bat \-de
&nbsp;    \./configure\.gnu  \-\-prefix=c&#8203;:/perl

i tried various combinations of flags reinstalling src each time

\- So In the top level directory i did

&nbsp;    \./Makefile\.SH

and the build still broke

\- In the x2p directory

so there i did

&nbsp;    make veryclean
&nbsp;    \./Makefile\.SH
&nbsp;    make makedepend
 \*  I had to edit the GNUMakefile to get rid of lines like
\.\.\.$\(EXT\_OBJ\)&#8203;: \<built\-in>
 and
\.\.\.$\(EXT\_OBJ\)&#8203;: \<command>

at this point the make still did not work so had to do

&nbsp;     \./cflags\.sh

\- Back in the top directory

&nbsp;    i had to repeat step \*

then everything fell in place\. 

\- in the t directory make harness produced
&nbsp;     lib/posix\.\.\.\.\.\.\.\.\.\.\.FAILED test 2


which may be ok\. I suspect Configure\.sh \-Dgcc with another \-D \`might\`
fix the 2 missing targets \<command> and \<built\-in> which should
happen automatically on the configure\.bat \-d\.

as a final suggestion one might consider a change to the dos hint's
file using c&#8203;:\\perl as the prefix \(for dos\)\. putting it in with
c&#8203;:\\djgpp\\\.\. means that it is really hard to get rid of\. not to
minimize dj's hard work\, but in unix would you want to reinstall bash
before you upgrade perl\.

attached is the myconfig output\.

=====

George J\. Elgin 

home&#8203;:\(859\) 781\-8028 
email&#8203;: gelgin@&#8203;internut\.com 
resume&#8203;:  http&#8203;://www\.sharemation\.com/gelgin/pub/Resume\.doc

check out my shareware stockpicking MicroSoft Access DB http&#8203;://www\.sharemation\.com/gelgin/db/MyFin\.zip

===== plain text email preferred\. word attachments NOT accepted\. 


\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
Do you Yahoo\!?
Yahoo\! Tax Center \- forms\, calculators\, tips\, more
http&#8203;://taxes\.yahoo\.com/

**Comment by p5pRT** [comment]
### From gelgin@yahoo.com

Summary of my perl5 \(revision 5\.0 version 6 subversion 1\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=dos\, osvers=djgpp\, archname=dos\-djgpp
&nbsp;    uname='ms\-dos oh2008lo 7 00 pc unknown '
&nbsp;    config\_args='\-ds \-e \-Dprefix=c&#8203;:/perl'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=undef use5005threads=undef useithreads=undef usemultiplicity=undef
&nbsp;    useperlio=undef d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc'\, ccflags ='\-DPERL\_EXTERNAL\_GLOB \-fno\-strict\-aliasing'\,
&nbsp;    optimize='\-O2 \-malign\-loops=2 \-malign\-jumps=2 \-malign\-functions=2'\,
&nbsp;    cppflags='\-DPERL\_EXTERNAL\_GLOB \-fno\-strict\-aliasing'
&nbsp;    ccversion=''\, gccversion='3\.2\.1'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=4
&nbsp;    alignbytes=4\, usemymalloc=n\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ld'\, ldflags ='\-s'
&nbsp;    libpth=c&#8203;:/djgpp/lib
&nbsp;    libs=\-lm \-lc
&nbsp;    perllibs=\-lm \-lc
&nbsp;    libc=c&#8203;:/djgpp/lib/libc\.a\, so=none\, useshrplib=false\, libperl=libperl\.a
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_none\.xs\, dlext=none\, d\_dlsymun=undef\, ccdlflags=''
&nbsp;    cccdlflags=''\, lddlflags=''

**Comment by p5pRT** [comment]
### From @schwern

Anybody tried djgpp in a while?

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tux

On Thu\, 14 Jul 2005 20&#8203;:18&#8203;:56 \-0700\, "Michael G Schwern via RT"
\<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:

> Anybody tried djgpp in a while?

I abandoned djgpp looooooong ago\, after several weeks of self\-punishment\.
IMHO it's the most horrible \(unix like\) development environment I ever had to
work in

\-\- 
H\.Merijn Brand        Amsterdam Perl Mongers \(http&#8203;://amsterdam\.pm\.org/\)
using Perl 5\.6\.2\, 5\.8\.0\, 5\.8\.5\, & 5\.9\.2  on HP\-UX 10\.20\, 11\.00 & 11\.11\,
 AIX 4\.3 & 5\.2\, SuSE 9\.2 & 9\.3\, and Cygwin\. http&#8203;://www\.cmve\.net/~merijn
Smoking perl&#8203;: http&#8203;://www\.test\-smoke\.org\,    perl QA&#8203;: http&#8203;://qa\.perl\.org
 reports  to&#8203;: smokers\-reports@&#8203;perl\.org\,                perl\-qa@&#8203;perl\.org

**Comment by p5pRT** [comment]
### From gelgin@internut.com

i still use their bash and window\, on a win95 machine but abandoned their perl in favor of ActiveState\. Not only did it not build right\, but MakeMaker et al were very problematic\.
 
recently i installed rxvt under cygwin for a xp machine which seems like the way to go\.

"H\. Merijn Brand via RT" \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
On Thu\, 14 Jul 2005 20&#8203;:18&#8203;:56 \-0700\, "Michael G Schwern via RT"

wrote&#8203;:

> Anybody tried djgpp in a while?

I abandoned djgpp looooooong ago\, after several weeks of self\-punishment\.
IMHO it's the most horrible \(unix like\) development environment I ever had to
work in

\-\- 
H\.Merijn Brand Amsterdam Perl Mongers \(http&#8203;://amsterdam\.pm\.org/\)
using Perl 5\.6\.2\, 5\.8\.0\, 5\.8\.5\, & 5\.9\.2 on HP\-UX 10\.20\, 11\.00 & 11\.11\,
AIX 4\.3 & 5\.2\, SuSE 9\.2 & 9\.3\, and Cygwin\. http&#8203;://www\.cmve\.net/~merijn
Smoking perl&#8203;: http&#8203;://www\.test\-smoke\.org\, perl QA&#8203;: http&#8203;://qa\.perl\.org
reports to&#8203;: smokers\-reports@&#8203;perl\.org\, perl\-qa@&#8203;perl\.org



&nbsp;        


---
 Start your day with Yahoo\! \- make it your home page

**Comment by p5pRT** [comment]
@chorny - Status changed from 'open' to 'stalled'

**Comment by ilmari** [comment]
With #19176 merged, the DOS/DJGPP port no longer exists, closing this issue.
