### ISSUE TITLE
Assignment to $0 broken

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6586]
Migrated from [rt.perl.org#22811](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=22811) (status was 'resolved')

Searchable as RT22811$

**Comment by p5pRT** [comment]
### From @andk

I'm trying to perlbug this dialog for future references\. There's more to come\.


\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- Start of forwarded message \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
Date&#8203;: Thu Jun 26 15&#8203;:54&#8203;:42 2003
From&#8203;: Various
Subject&#8203;: Digested Articles

Topics&#8203;:
&nbsp;   Assignment to $0 still broken
&nbsp;   Re&#8203;: Assignment to $0 still broken
&nbsp;   the $0
&nbsp;   Re&#8203;: the $0




---
Date&#8203;: Wed\, 25 Jun 2003 02&#8203;:20&#8203;:41 \+0200
From&#8203;: Andreas J Koenig \<andreas\.koenig@&#8203;anima\.de>
To&#8203;: The Perl5 Porters Mailing List \<perl5\-porters@&#8203;perl\.org>
Subject&#8203;: Assignment to $0 still broken
Message\-ID&#8203;: \<87znk7j9d2\.fsf@&#8203;franz\.ak\.mind\.de>
Content\-Type&#8203;: text/plain; charset=us\-ascii
MIME\-Version&#8203;: 1\.0

18229 fixed the bug that had disabled assigning to $0\. But the fix is
incomplete\. Setting $0 to a string that is shorter than the original
$0 sets the value that is visible from outside to that string but pads
it with blanks\. This testscript demonstrates the bug on Linux for me
\(depends on external ps\)&#8203;:

% cat ak\-dollarzero\.pl  
\#\!/usr/bin/perl

use strict;
use warnings;
my $verbose = 0;
$verbose = 1 if @&#8203;ARGV && $ARGV\[0\] eq "\-v";
sub myps \{
&nbsp;  my\($arg\) = shift;
&nbsp;  $0 = $arg;
&nbsp;  chomp\(my $ps = \`ps \-o command= \-p $$\`\);
&nbsp;  printf "%sok\\n"\, $0 ne $arg || $ps ne $arg ? "not " : "";
&nbsp;  printf "  \[%s\]\\n"\, $ps if $verbose;
\}

myps\("x"\);
myps\(join\(""\, 0\.\.9\) x 4\);
myps\("x"\);


% perl ak\-dollarzero\.pl \-v
not ok
&nbsp;  \[x                       \]
ok
&nbsp;  \[0123456789012345678901234567890123456789\]
not ok
&nbsp;  \[x                       \]

Interestingly\, the test in ext/threads/t/join\.t might be aware of this
problem\, since it tests

&nbsp;        if \(/\\sfoobar\\b/\) \{

and not the more appropriate /\\sfoobar$/\.

The above testscript printed 3 times "ok" for perl 5\.6\.0


\- \- 
andreas




---
Date&#8203;: Wed\, 25 Jun 2003 19&#8203;:50&#8203;:19 \+0300
From&#8203;: Jarkko Hietaniemi \<jhi@&#8203;iki\.fi>
To&#8203;: andreas\.koenig@&#8203;anima\.de
Cc&#8203;: perl5\-porters@&#8203;perl\.org
Subject&#8203;: Re&#8203;: Assignment to $0 still broken
Message\-ID&#8203;: \<20030625165019\.GA8944@&#8203;vipunen\.hut\.fi>
Content\-Type&#8203;: text/plain; charset=us\-ascii
Mime\-Version&#8203;: 1\.0
Content\-Disposition&#8203;: inline

> Setting $0 to a string that is shorter than the original $0 sets the
> value that is visible from outside to that string but pads it with
> blanks\.

Confirmed in Debian/x86 3\.0\.

But right now I have no idea of why this is not working\.  If I set
a breakpoint to Perl\_mg\_set\(\)\, the '0' branch of the switch statement\,
I see the code doing the right modifications to the PL\_origargv\.
After the modifications are done\, I climb upwards in the call stack
all the way to main\(\) and the argv\[\] has been modified \(argv\[0\] set
to the myps\(\) argument and argv\[1\] and \[2\] to empty strings\)\.
And that particular code has not changed functionally since 5\.6\.1\.

\- \- 
Jarkko Hietaniemi \<jhi@&#8203;iki\.fi> http&#8203;://www\.iki\.fi/jhi/ "There is this special
biologist word we use for 'stable'\.  It is 'dead'\." \-\- Jack Cohen




---
Date&#8203;: Wed\, 25 Jun 2003 23&#8203;:33&#8203;:38 \+0300
From&#8203;: Jarkko Hietaniemi \<jhi@&#8203;iki\.fi>
To&#8203;: andreas\.koenig@&#8203;anima\.de
Subject&#8203;: the $0
Message\-ID&#8203;: \<20030625203338\.GB8944@&#8203;vipunen\.hut\.fi>
Content\-Type&#8203;: text/plain; charset=us\-ascii
Mime\-Version&#8203;: 1\.0
Content\-Disposition&#8203;: inline

Try binsearchaperl to see which patch between 5\.6\.0 and 5\.8\.0 broke
the $0 padding\, was it the same that broke the $0 setting in general?

\- \- 
Jarkko Hietaniemi \<jhi@&#8203;iki\.fi> http&#8203;://www\.iki\.fi/jhi/ "There is this special
biologist word we use for 'stable'\.  It is 'dead'\." \-\- Jack Cohen




---
Date&#8203;: Thu\, 26 Jun 2003 11&#8203;:01&#8203;:24 \+0200
From&#8203;: Andreas J Koenig \<andreas\.koenig@&#8203;anima\.de>
To&#8203;: jhi@&#8203;iki\.fi
Cc&#8203;: andreas\.koenig@&#8203;anima\.de
Subject&#8203;: Re&#8203;: the $0
Message\-ID&#8203;: \<873chxb4bf\.fsf@&#8203;franz\.ak\.mind\.de>
References&#8203;: \<20030625203338\.GB8944@&#8203;vipunen\.hut\.fi>
Content\-Type&#8203;: text/plain; charset=us\-ascii
MIME\-Version&#8203;: 1\.0

Jarkko Hietaniemi \<jhi@&#8203;iki\.fi> writes&#8203;:

> Try binsearchaperl to see which patch between 5\.6\.0 and 5\.8\.0 broke
> the $0 padding\, was it the same that broke the $0 setting in general?

Yes\, it was the same&#8203;: 11559\. At least I see no change in behaviour
between 11559 and your 18229\.

Ahh\, now I understand what you probably mean&#8203;: Reverse apply 11559
during the binary search and see where the padding was introduced\. I
manually tried that with the randomly chosen 15226 and 18228&#8203;: yes\,
15226 was OK\, 18228 was not OK\. So I'm on an interesting track\.

You'll hear from me again soon\.

\- \- 
andreas




---
End of forward5051isv Digest
\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*\*

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\- End of forwarded message \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

\-\- 
andreas

**Comment by p5pRT** [comment]
### From @andk

[dollarzero-ntry01.tar.gz](https://rt-archive.perl.org/perl5/Ticket/Attachment/59922/44370/dollarzero-ntry01.tar.gz)

**Comment by p5pRT** [comment]
### From @jhi

I believe this issue has been now fixed as far as Linux lets us\.

**Comment by p5pRT** [comment]
@jhi - Status changed from 'new' to 'resolved'

**Comment by FGasper** [comment]
This issue presents in certain Linuxes as well. Try `perl -w -e'$0 = "hihi"; print `ps aux | grep $$` on AlmaLinux 8, for example.
