### ISSUE TITLE
NOT OK: perl-5.8.0-RC4 on dos-djgpp

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6684]
Migrated from [rt.perl.org#23232](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=23232) (status was 'stalled')

Searchable as RT23232$

**Comment by p5pRT** [comment]
### From Philip.Newton@gmx.net

I tried to build RC4 on DJGPP\.

The first hurdle was that djgpp/configure\.bat "doesn't work"\. I
"executed" it manually \(using /dev/brain as $SHELL\, as it were\)\.
\(That seems to be because it's in Unix LF format; converting it
to DOS CRLF format makes it work\.\)

Then I got a warning&#8203;:

d&#8203;:/djgpp/bin/sed\.exe&#8203;: can't read ext/GDBM\_File/gdbm\.t&#8203;: No such file or directory \(ENOENT\)

Next\, I ran into lots and lots of warnings; first during certain
Configure tests and then at every compiled source file\. These say&#8203;:

cc1\.exe&#8203;: warning&#8203;: \-malign\-loops is obsolete\, use \-falign\-loops
cc1\.exe&#8203;: warning&#8203;: \-malign\-jumps is obsolete\, use \-falign\-jumps
cc1\.exe&#8203;: warning&#8203;: \-malign\-functions is obsolete\, use \-falign\-functions

Hm\, those appear to come from hints/dos\_djgpp\.sh\. Bad Hints file\.

I'm using&#8203;:

sh\-2\.04$ gcc \-v
Reading specs from d&#8203;:/djgpp/lib/gcc\-lib/djgpp/3\.21/specs
Configured with&#8203;: /devel/gnu/gcc/3\.2/gnu/gcc\-3\.21/configure i586\-pc\-msdosdjgpp \-\-prefix=/dev/env/DJDIR \-\-disable\-nls
Thread model&#8203;: single
gcc version 3\.2\.1

The questions "Pathname where the public executables will reside?"
and "Pathname where the site\-specific manual pages should be
installed?" and "Pathname where the site\-specific library manual
pages should be installed?" don't have a default value so you have
to type one in rather than being able to accept the default with
\<Return>\.

Configure also complains about&#8203;:

uname\(\) was found\, but you're running xenix\, and older versions of xenix
have a broken uname\(\)\. If you don't really know whether your xenix is old
enough to have a broken system call\, use the default answer\.

Is your uname\(\) broken? \[y\]

I'm not sure where it gets the idea that I'm running Xenix\.
Hmm\.\.\. \./xenix exists and consists solely of 'exit 1'\, yet
executing '\./xenix; echo $?' gives '0'\.



Then 'make' failed after building miniperl&#8203;:

gcc \-s \-o miniperl \\
&nbsp;    miniperlmain\.o opmini\.o libperl\.a \-lsocket \-lm \-lc
\./miniperl \-w \-Ilib \-MExporter \-e '\<?>' || d&#8203;:/djgpp/bin/make\.exe minitest
make\.exe&#8203;: \[extra\.pods\] Error 1 \(ignored\)
\./miniperl \-Ilib configpm configpm\.tmp
Perl lib version \(5\_8\_1\) doesn't match executable version \(5\.8\.1\) at configpm\.tmp line 33\.
Compilation failed in require at configpm line 662\.
make\.exe&#8203;: \*\*\* \[lib/Config\.pm\] Error \-1


I grepped for '5\_8\_1' and found it only in three files&#8203;: config\.sh
has "version='5\_8\_1'" and "xs\_apiversion='5\_8\_1'"\, config\.h has
'\#define PERL\_XS\_APIVERSION "5\_8\_1"'\, and configpm\.tmp\, the
failing file\, has this&#8203;:

die "Perl lib version \(5\_8\_1\) doesn't match executable version \($\]\)"
&nbsp;    unless $^V;

my $exever = sprintf\("%vd"\,$^V\);
$exever eq "5\_8\_1"    \# \<\-\- line 33
&nbsp;    or die "Perl lib version \(5\_8\_1\) doesn't match executable version \($exever\)";


I'm not sure where this 5\_8\_1 comes from\, though\. Any ideas?

Running a clean Configure turns it up in config\.sh already\.


Cheers\,
Philip

**Comment by p5pRT** [comment]
### From @JohnPeacock

Philip Newton \(via RT\) wrote&#8203;:

> '\#define PERL\_XS\_APIVERSION "5\_8\_1"'\, and configpm\.tmp\, the
> failing file\, has this&#8203;:
> 

\<snip>

> I'm not sure where this 5\_8\_1 comes from\, though\. Any ideas?
> 

configpm\.tmp is created from configpm by miniperl\.  But apparently config\.sh 
already has the underscores\, so the fact that configpm\.tmp is failing is a false 
lead\.  It looks like Configure is messing up config\.sh; I'm sorry\, I am past the 
point where I know what is going on here\.\.\.

John

\-\- 
John Peacock
Director of Information Research and Technology
Rowman & Littlefield Publishing Group
4501 Forbes Boulevard
Suite H
Lanham\, MD  20706
301\-459\-3366 x\.5010
fax 301\-429\-5748

**Comment by p5pRT** [comment]
### From @richardfoley

Old installation \- superceded by more recent releases\.

**Comment by p5pRT** [comment]
@richardfoley - Status changed from 'open' to 'stalled'

**Comment by pne** [comment]
Hi - OP here. As far as I'm concerned, this ticket can simply be closed. (I don't use djgpp any more and, as noted, 5.8.x is ancient.)
