### ISSUE TITLE
IO::Handle::error doesn't report errors

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6799]
Migrated from [rt.perl.org#24067](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=24067) (status was 'open')

Searchable as RT24067$

**Comment by p5pRT** [comment]
### From peff-perlbug@peff.net


This is a bug report for perl from peff\-perlbug@&#8203;peff\.net\,
generated with the help of perlbug 1\.34 running under perl v5\.8\.0\.




---
The following perl program writes 4096 bytes to a file\, checking for errors&#8203;:

$ cat foo\.pl
use IO&#8203;::File;
my $fh = new IO&#8203;::File\($ARGV\[0\]\, 'w'\);
$fh\->print\('a' x 4096\) || print "print failed&#8203;: $\!\\n";
print "errors&#8203;: " \. \($fh\->error\(\) ? "yes \($\!\)" : "no"\) \. "\\n";

When running it on a regular file\, it works as expected&#8203;:
$ perl foo\.pl foo\.out
errors&#8203;: no

However\, when an error actually occurs\, the print statement returns an error
but $fh\->error does not return true&#8203;:
$ perl foo\.pl /dev/full
print failed&#8203;: No space left on device
errors&#8203;: no

IO\.xs shows that IO&#8203;::Handle&#8203;::error just calls PerlIO\_error\, which typically
just calls PerlIOBase\_error to check the PERLIO\_F\_ERROR flag\. However\, if I
run gdb on the perl binary\, I see that&#8203;:

 \- PerlIO\_write is called with \(in my case\) f=0x81a70e4
 \- PerlIOBuf\_flush correctly sets the flag with the same f=0x81a70e4\, and
&nbsp;   sets the PERLIO\_F\_ERROR flag on f\->flags
 \- PerlIO\_error gets called with f=0x81a70e4 \(from Perl\_do\_print\)\, and
&nbsp;   correctly returns that an error occurred
 \- PerlIO\_error gets called with f=0x81a70e0\, whose flags don't have an
&nbsp;   error; this is \*not\* for the error message printed to stdout \(I also saw
&nbsp;   that happen\, and it has a different address\)\.

Whatever the address of the original PerlIO handle is\, the final call to
PerlIO\_error always has an address 4 bytes less \(the size of a pointer on my
platform\)\.

I haven't been able to follow it past here since I'm unclear on exactly where
that pointer comes from \(a backtrace shows it comes from XS\_IO\_\_Handle\_error\,
but I can't trace into that\)\.


---


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=low


---
Site configuration information for perl v5\.8\.0&#8203;:

Configured by Debian Project at Thu Sep 11 20&#8203;:57&#8203;:21 EST 2003\.

Summary of my perl5 \(revision 5\.0 version 8 subversion 0\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=linux\, osvers=2\.4\.21\-xfs\+ti1211\, archname=i386\-linux\-thread\-multi
&nbsp;    uname='linux kosh 2\.4\.21\-xfs\+ti1211 \#1 sat jul 12 10&#8203;:35&#8203;:04 est 2003 i686 gnulinux '
&nbsp;    config\_args='\-Dusethreads \-Duselargefiles \-Dccflags=\-DDEBIAN \-Dcccdlflags=\-fPIC \-Darchname=i386\-linux \-Dprefix=/usr \-Dprivlib=/usr/share/perl/5\.8\.0 \-Darchlib=/usr/lib/perl/5\.8\.0 \-Dvendorprefix=/usr \-Dvendorlib=/usr/share/perl5 \-Dvendorarch=/usr/lib/perl5 \-Dsiteprefix=/usr/local \-Dsitelib=/usr/local/share/perl/5\.8\.0 \-Dsitearch=/usr/local/lib/perl/5\.8\.0 \-Dman1dir=/usr/share/man/man1 \-Dman3dir=/usr/share/man/man3 \-Dman1ext=1 \-Dman3ext=3perl \-Dpager=/usr/bin/sensible\-pager \-Uafs \-Ud\_csh \-Uusesfio \-Uusenm \-Duseshrplib \-Dlibperl=libperl\.so\.5\.8\.0 \-Dd\_dosuid \-des'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fno\-strict\-aliasing \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O3'\,
&nbsp;    cppflags='\-D\_REENTRANT \-D\_GNU\_SOURCE \-DDEBIAN \-fno\-strict\-aliasing'
&nbsp;    ccversion=''\, gccversion='3\.3\.2 20030908 \(Debian prerelease\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=4\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='cc'\, ldflags =' \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /lib /usr/lib
&nbsp;    libs=\-lgdbm \-ldb \-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    perllibs=\-ldl \-lm \-lpthread \-lc \-lcrypt
&nbsp;    libc=/lib/libc\-2\.3\.2\.so\, so=so\, useshrplib=true\, libperl=libperl\.so\.5\.8\.0
&nbsp;    gnulibc\_version='2\.3\.2'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags='\-rdynamic'
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-shared \-L/usr/local/lib'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl v5\.8\.0&#8203;:
&nbsp;    /home/peff/local/share/perl/5\.8\.0
&nbsp;    /home/peff/local/share/perl
&nbsp;    /home/peff/local/lib/perl5/site\_perl
&nbsp;    /home/peff/local/lib/perl/5\.8\.0
&nbsp;    /home/peff/local/lib/perl
&nbsp;    /etc/perl
&nbsp;    /usr/local/lib/perl/5\.8\.0
&nbsp;    /usr/local/share/perl/5\.8\.0
&nbsp;    /usr/lib/perl5
&nbsp;    /usr/share/perl5
&nbsp;    /usr/lib/perl/5\.8\.0
&nbsp;    /usr/share/perl/5\.8\.0
&nbsp;    /usr/local/lib/site\_perl
&nbsp;    \.



---
Environment for perl v5\.8\.0&#8203;:
&nbsp;    HOME=/home/peff
&nbsp;    LANG=C
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/home/peff/local/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/bin/X11&#8203;:/usr/games&#8203;:/sbin&#8203;:/usr/sbin&#8203;:/home/peff/fenris/build/bin&#8203;:/home/peff/work/mmake/bin&#8203;:/home/peff/work/sadm/bin
&nbsp;    PERL5LIB=/home/peff/local/share/perl&#8203;:/home/peff/local/lib/perl5/site\_perl&#8203;:/home/peff/local/lib/perl
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @iabyn

On Mon\, Sep 29\, 2003 at 03&#8203;:43&#8203;:41PM \-0000\, peff\-perlbug@&#8203;peff\.net \(via RT\) wrote&#8203;:
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> The following perl program writes 4096 bytes to a file\, checking for errors&#8203;:
> 
> $ cat foo\.pl
> use IO&#8203;::File;
> my $fh = new IO&#8203;::File\($ARGV\[0\]\, 'w'\);
> $fh\->print\('a' x 4096\) || print "print failed&#8203;: $\!\\n";
> print "errors&#8203;: " \. \($fh\->error\(\) ? "yes \($\!\)" : "no"\) \. "\\n";
> 
> When running it on a regular file\, it works as expected&#8203;:
> $ perl foo\.pl foo\.out
> errors&#8203;: no
> 
> However\, when an error actually occurs\, the print statement returns an error
> but $fh\->error does not return true&#8203;:
> $ perl foo\.pl /dev/full
> print failed&#8203;: No space left on device
> errors&#8203;: no
> 
> IO\.xs shows that IO&#8203;::Handle&#8203;::error just calls PerlIO\_error\, which typically
> just calls PerlIOBase\_error to check the PERLIO\_F\_ERROR flag\. However\, if I
> run gdb on the perl binary\, I see that&#8203;:
> 
>  \- PerlIO\_write is called with \(in my case\) f=0x81a70e4
>  \- PerlIOBuf\_flush correctly sets the flag with the same f=0x81a70e4\, and
>    sets the PERLIO\_F\_ERROR flag on f\->flags
>  \- PerlIO\_error gets called with f=0x81a70e4 \(from Perl\_do\_print\)\, and
>    correctly returns that an error occurred
>  \- PerlIO\_error gets called with f=0x81a70e0\, whose flags don't have an
>    error; this is \*not\* for the error message printed to stdout \(I also saw
>    that happen\, and it has a different address\)\.
> 
> Whatever the address of the original PerlIO handle is\, the final call to
> PerlIO\_error always has an address 4 bytes less \(the size of a pointer on my
> platform\)\.

In IO\.xs\, XS\_IO\_\_Handle\_error is set up to report errors on the input
stream only\, which is why it's seeing the wrong result\.
That is to say\, it effectively calls PerlIO\_error\(IoIFP\(io\)\) rather than
IoOFP\(io\)\.  Anyone have a clue how to handle this\, because I dont\!

Dave\.

\-\- 
"Strange women lying in ponds distributing swords is no basis for a system
of government\. Supreme executive power derives from a mandate from the
masses\, not from some farcical aquatic ceremony\."
Dennis \- Monty Python and the Holy Grail\.

**Comment by p5pRT** [comment]
### From @jkeenan

On Sat Oct 18 04&#8203;:58&#8203;:34 2003\, davem wrote&#8203;:
> On Mon\, Sep 29\, 2003 at 03&#8203;:43&#8203;:41PM \-0000\, peff\-perlbug@&#8203;peff\.net \(via
> RT\) wrote&#8203;:
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > The following perl program writes 4096 bytes to a file\, checking for
> errors&#8203;:
> >
> > $ cat foo\.pl
> > use IO&#8203;::File;
> > my $fh = new IO&#8203;::File\($ARGV\[0\]\, 'w'\);
> > $fh\->print\('a' x 4096\) || print "print failed&#8203;: $\!\\n";
> > print "errors&#8203;: " \. \($fh\->error\(\) ? "yes \($\!\)" : "no"\) \. "\\n";
> >
> > When running it on a regular file\, it works as expected&#8203;:
> > $ perl foo\.pl foo\.out
> > errors&#8203;: no
> >
> > However\, when an error actually occurs\, the print statement returns
> an error
> > but $fh\->error does not return true&#8203;:
> > $ perl foo\.pl /dev/full
> > print failed&#8203;: No space left on device
> > errors&#8203;: no
> >

Reviewing this older ticket this evening\, I could reproduce the OP's
results with Perl 5\.12 on Linux/i386&#8203;:

\#\#\#\#\#\#\#\#\#
$ cat 24067\.pl
use IO&#8203;::File;
my $fh = new IO&#8203;::File\($ARGV\[0\]\, 'w'\);
$fh\->print\('a' x 4096\) || print "print failed&#8203;: $\!\\n";
print "errors&#8203;: " \. \($fh\->error\(\) ? "yes \($\!\)" : "no"\) \. "\\n";

$ /usr/local/bin/perl5\.12\.0 24067\.pl /dev/full
print failed&#8203;: No space left on device
errors&#8203;: no
\#\#\#\#\#\#\#\#\#

However\, on 5\.14 and 5\.16\, I don't get the print failure message\, even
though I still get the "errors&#8203;: no"&#8203;:

\#\#\#\#\#\#\#\#\#
$ /usr/local/bin/perl5\.14\.0 24067\.pl /dev/full
errors&#8203;: no

$ /usr/local/bin/perl5\.16\.0 24067\.pl /dev/full
errors&#8203;: no
\#\#\#\#\#\#\#\#\#

> > IO\.xs shows that IO&#8203;::Handle&#8203;::error just calls PerlIO\_error\, which
> typically
> > just calls PerlIOBase\_error to check the PERLIO\_F\_ERROR flag\.
> However\, if I
> > run gdb on the perl binary\, I see that&#8203;:
> >
> >  \- PerlIO\_write is called with \(in my case\) f=0x81a70e4
> >  \- PerlIOBuf\_flush correctly sets the flag with the same
> f=0x81a70e4\, and
> >    sets the PERLIO\_F\_ERROR flag on f\->flags
> >  \- PerlIO\_error gets called with f=0x81a70e4 \(from Perl\_do\_print\)\,
> and
> >    correctly returns that an error occurred
> >  \- PerlIO\_error gets called with f=0x81a70e0\, whose flags don't have
> an
> >    error; this is \*not\* for the error message printed to stdout \(I
> also saw
> >    that happen\, and it has a different address\)\.
> >
> > Whatever the address of the original PerlIO handle is\, the final
> call to
> > PerlIO\_error always has an address 4 bytes less \(the size of a
> pointer on my
> > platform\)\.
> 
> In IO\.xs\, XS\_IO\_\_Handle\_error is set up to report errors on the input
> stream only\, which is why it's seeing the wrong result\.
> That is to say\, it effectively calls PerlIO\_error\(IoIFP\(io\)\) rather
> than
> IoOFP\(io\)\.  Anyone have a clue how to handle this\, because I dont\!
> 
> Dave\.
> 

Does anyone know what has changed\, for better or worse?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From @arc

James E Keenan via RT \<perlbug\-followup@&#8203;perl\.org> wrote&#8203;:
> On Sat Oct 18 04&#8203;:58&#8203;:34 2003\, davem wrote&#8203;:
>> On Mon\, Sep 29\, 2003 at 03&#8203;:43&#8203;:41PM \-0000\, peff\-perlbug@&#8203;peff\.net \(via
>> RT\) wrote&#8203;:
>> > The following perl program writes 4096 bytes to a file\, checking for errors&#8203;:
> Reviewing this older ticket this evening\, I could reproduce the OP's
> results with Perl 5\.12 on Linux/i386&#8203;:
>
> However\, on 5\.14 and 5\.16\, I don't get the print failure message\, even
> though I still get the "errors&#8203;: no"&#8203;:
>
> Does anyone know what has changed\, for better or worse?

I can reproduce the OP's results under 5\.16 by increasing the constant
4096 to 8192\.  I believe that's because of this commit that first went
into 5\.14&#8203;:

commit b83080de5c42543809ce9004bcdbcd3162a00e70
Author&#8203;: Craig A\. Berry \<craigberry@&#8203;mac\.com>
Date&#8203;:   Thu Feb 17 14&#8203;:24&#8203;:39 2011 \-0600

&nbsp;    Increase PERLIOBUF\_DEFAULT\_BUFSIZ to larger of 8192 and BUFSIZ\.

&nbsp;    The previous default size of a PerlIO buffer \(4096 bytes\) was
&nbsp;    chosen many years ago before PerlIO was even the default I/O scheme
&nbsp;    for Perl\.  Benchmarks show that doubling this decade\-old default
&nbsp;    increases read and write performance in the neighborhood of 25%
&nbsp;    to 50% when using the default layers of perlio on top of unix\.

&nbsp;    The only situation without a noticeable performance benefit so
&nbsp;    far appears to be when physical I/O is so slow that it dwarfs
&nbsp;    any savings from the reduction in layer shuffling\, but there
&nbsp;    is also no performance penalty in this case\.

&nbsp;    BUFSIZ will be chosen in the unlikely event that it's larger
&nbsp;    than 8192 on the assumption that the system maintainers would
&nbsp;    not set such a value without good reason\.

&nbsp;    If the new size causes problems\, or to try an even bigger size\,
&nbsp;    configure with&#8203;:

&nbsp;      \./Configure \-Accflags=\-DPERLIOBUF\_DEFAULT\_BUFSIZ=N

&nbsp;    where N is the desired size in bytes; it should probably be a
&nbsp;    multiple of your page size\.

That is\, when the amount of data written is less than the buffer size\,
no OS\-level write\(\) call gets issued because of the Perl print\.  So
the increase in Perl's default buffer size means that a larger print
is needed to trigger this behaviour\.

But it does look like a bug to me that $fh\->error returns false after
$fh\->print has failed\.

\-\- 
Aaron Crane \*\* http&#8203;://aaroncrane\.co\.uk/

**Comment by p5pRT** [comment]
### From @peff

On Sun\, Sep 30\, 2012 at 06&#8203;:14&#8203;:05AM \-0700\, Aaron Crane via RT wrote&#8203;:

> > However\, on 5\.14 and 5\.16\, I don't get the print failure message\, even
> > though I still get the "errors&#8203;: no"&#8203;:
> >
> > Does anyone know what has changed\, for better or worse?
> 
> I can reproduce the OP's results under 5\.16 by increasing the constant
> 4096 to 8192\.  I believe that's because of this commit that first went
> into 5\.14&#8203;:

I think my original test was flaky; it should flush explicitly rather
than assuming that print will flush\. So this is more realistic for a
program that is trying to be careful about whether output succeeded&#8203;:

&nbsp;  use IO&#8203;::File;
&nbsp;  my $fh = new IO&#8203;::File\($ARGV\[0\]\, 'w'\);
&nbsp;  \($fh\->print\('a' x 4096\) && $fh\->flush\) || print "print failed&#8203;: $\!\\n";
&nbsp;  print "errors&#8203;: " \. \($fh\->error\(\) ? "yes \($\!\)" : "no"\) \. "\\n";

> But it does look like a bug to me that $fh\->error returns false after
> $fh\->print has failed\.

Right\, that's the main thing I was trying to report with the test\.

\-Peff

**Comment by p5pRT** [comment]
### From @jkeenan

On Sat Oct 18 04&#8203;:58&#8203;:34 2003\, davem wrote&#8203;:
> 
> In IO\.xs\, XS\_IO\_\_Handle\_error is set up to report errors on the input
> stream only\, which is why it's seeing the wrong result\.
> That is to say\, it effectively calls PerlIO\_error\(IoIFP\(io\)\) rather
> than
> IoOFP\(io\)\.  Anyone have a clue how to handle this\, because I dont\!
> 

This is the source code you're referring to \-\- correct?

dist/IO/IO\.xs
\#\#\#\#\#

&nbsp;    345 int
&nbsp;    346 ferror\(handle\)
&nbsp;    347     InputStream handle
&nbsp;    348     CODE&#8203;:
&nbsp;    349     if \(handle\)
&nbsp;    350 \#ifdef PerlIO
&nbsp;    351         RETVAL = PerlIO\_error\(handle\);
&nbsp;    352 \#else
&nbsp;    353         RETVAL = ferror\(handle\);
&nbsp;    354 \#endif
&nbsp;    355     else \{
&nbsp;    356         RETVAL = \-1;
&nbsp;    357         errno = EINVAL;
&nbsp;    358     \}
&nbsp;    359     OUTPUT&#8203;:
&nbsp;    360     RETVAL
\#\#\#\#\#

**Comment by tonycoz** [comment]
Perl's I/O objects (that is the IO SV , not PerlIO) can have both an input (PerlIO) file handle and an output file handle.  For files that output handle is the same as the input handle, and if you try the error method on a file:
```
# to a full filesystem
$ ./perl -Ilib -MDevel::Peek -MIO::File -le 'my $fh = new IO::File->new(shift, "w") or die; $fh->print("a" x 4096) && $fh->flush; print $fh->error; close($fh);' /home/tony/mnt/empty.txt
1
```

For a character device (like /dev/full) or a socket, perl [creates](https://github.com/Perl/perl5/blob/6319bad96eba493c5f3bc7857e1c58687c461d70/doio.c#L1068) a second PerlIO object on the same fd to use as the output handle, and that causes the behaviour this ticket documents.

```
$ ./perl -Ilib -MDevel::Peek -MIO::File -le 'my $fh = new IO::File->new(shift, "w") or die; $fh->print("a" x 4096) && $fh->flush; print $fh->error; close($fh);' /dev/full
0
```

The separate handle allows sockets and character devices to have separate input and output buffers, but it does make this method less useful.

**Comment by peff** [comment]
@tonycoz Yeah, that makes sense. Since the fact that one `IO` object is represented under the hood as two individual PerlIO handles is an implementation detail not known to callers of `IO`, would it be reasonable for `$fh->error` to return `PerlIO_error(input_handle) || PerlIO_error(output_handle)`? I think that would match the single-handle case more closely (where an error on either side would cause the handle to report an error).

It's possible that some existing callers using sockets could be relying on ignoring output errors, but it seems unlikely (and I think it could be argued they're in the wrong).

**Comment by tonycoz** [comment]
I'm working on such a PR now, I also want to check clearerr() works here.
