### ISSUE TITLE
SDBM_File sometimes fails with "sdbm store() returned -1"

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#6841]
Migrated from [rt.perl.org#24206](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=24206) (status was 'open')

Searchable as RT24206$

**Comment by p5pRT** [comment]
### From @steve-m-hay

This is a bug report for perl from steve\.hay@&#8203;uk\.radan\.com\,
generated with the help of perlbug 1\.34 running under perl v5\.8\.1\.


Hashes tied to SDBM\_File don't seem to be able to cope with certain kinds of
data\. I've experienced breakage with "real" data involving many small\, 
similar
keys and large \(but not too large\!\) values; the test program below 
reproduces
the problem using data like that&#8203;:

WARNING\! This program will create a \*very\* large file\, so make sure you
don't run out of space in your filesystem\!

=====
use strict;
use warnings;

use Fcntl;
use SDBM\_File;

tie my %h\, 'SDBM\_File'\, 'testsdbm'\, O\_RDWR | O\_CREAT | O\_TRUNC\, 0666
&nbsp;    or die "Couldn't tie SDBM file 'testsdbm'&#8203;: $\!\\n";

for my $i \(0 \.\. 255\) \{
&nbsp;    for my $j \(0 \.\. 255\) \{
&nbsp;        printf "%03d \- %03d\\n"\, $i\, $j;
&nbsp;        for my $k \(0 \.\. 5\) \{
&nbsp;            my $key = chr\($i\) \. chr\($j\) \. chr\($k\);
&nbsp;            my $val = ' ' x 1000;
&nbsp;            $h\{$key\} = $val;
&nbsp;        \}
&nbsp;    \}
\}

untie %h;
=====

The combined length of the key \+ value here is always 1003\, which is
within the 1008 limit imposed by sdbm\, so there should be no problem
there\.

However\, the above program always crashes with this error&#8203;:

&nbsp;    sdbm store returned \-1\, errno 22\, key "\.\.\."

at the point where i==1 and j==0\.

I've hacked the ext/SDBM\_File/sdbm/sdbm\.c file in the Perl source to
include some fprintf\(stderr\, \.\.\.\) statements in pertinent places\, and I
have found that it is the last lseek\(\) within the main while \{ \.\.\. \}
loop in makroom\(\) that fails\. The offset that is being passed to that
lseek\(\) is \-130153472 \(when formatted with %ld\, which should be correct
since the offset is a "long"\)\.

At the point where it failed\, the \.pag file was 1\.87GB \(to be exact\, it
was 2\,017\,331\,200 bytes\)\, so I wondered if this might be a "large file"
problem with a 2GB limit since my Perl doesn't have large file support?

However\, I retried the same program using ActivePerl Build 806 \(which
has large file support enabled\) and got the same error at the same
point\.

The same program completes without error if I just change SDBM\_File to
DB\_File\. The \(single\) file which it creates is only about 0\.5GB when the
program is finished\!



---
Flags&#8203;:
&nbsp;    category=library
&nbsp;    severity=medium


---
Site configuration information for perl v5\.8\.1&#8203;:

Configured by steveh at Thu Sep 25 17&#8203;:01&#8203;:07 2003\.

Summary of my perl5 \(revision 5 version 8 subversion 1\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=MSWin32\, osvers=4\.0\, archname=MSWin32\-x86\-perlio
&nbsp;    uname=''
&nbsp;    config\_args='undef'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=undef
&nbsp;    usethreads=undef use5005threads=undef useithreads=undef 
usemultiplicity=undef
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=undef usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=y\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cl'\, ccflags ='\-nologo \-Gf \-W3 \-MD \-DNDEBUG \-O1 \-DWIN32 
\-D\_CONSOLE \-DNO\_STRICT \-DHAVE\_DES\_FCRYPT  \-DPERL\_DEBUGGING\_MSTATS 
\-DUSE\_PERLIO \-DPERL\_MSVCRT\_READFIX'\,
&nbsp;    optimize='\-MD \-DNDEBUG \-O1'\,
&nbsp;    cppflags='\-DWIN32'
&nbsp;    ccversion=''\, gccversion=''\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=undef\, longlongsize=8\, d\_longdbl=define\, longdblsize=10
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, 
lseeksize=4
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='link'\, ldflags ='\-nologo \-nodefaultlib \-release  
\-libpath&#8203;:"C&#8203;:\\perl5\\lib\\CORE"  \-machine&#8203;:x86'
&nbsp;    libpth=C&#8203;:\\PROGRA~1\\MICROS~2\\VC98\\lib
&nbsp;    libs=  oldnames\.lib kernel32\.lib user32\.lib gdi32\.lib winspool\.lib  
comdlg32\.lib advapi32\.lib shell32\.lib ole32\.lib oleaut32\.lib  
netapi32\.lib uuid\.lib wsock32\.lib mpr\.lib winmm\.lib  version\.lib 
odbc32\.lib odbccp32\.lib msvcrt\.lib
&nbsp;    perllibs=  oldnames\.lib kernel32\.lib user32\.lib gdi32\.lib 
winspool\.lib  comdlg32\.lib advapi32\.lib shell32\.lib ole32\.lib 
oleaut32\.lib  netapi32\.lib uuid\.lib wsock32\.lib mpr\.lib winmm\.lib  
version\.lib odbc32\.lib odbccp32\.lib msvcrt\.lib
&nbsp;    libc=msvcrt\.lib\, so=dll\, useshrplib=yes\, libperl=perl58\.lib
&nbsp;    gnulibc\_version='undef'
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_win32\.xs\, dlext=dll\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags=' '\, lddlflags='\-dll \-nologo \-nodefaultlib \-release  
\-libpath&#8203;:"C&#8203;:\\perl5\\lib\\CORE"  \-machine&#8203;:x86'

Locally applied patches&#8203;:
&nbsp;   



---
@&#8203;INC for perl v5\.8\.1&#8203;:
&nbsp;    C&#8203;:/perl5/lib
&nbsp;    C&#8203;:/perl5/site/lib
&nbsp;    \.



---
Environment for perl v5\.8\.1&#8203;:
&nbsp;    HOME \(unset\)
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    
PATH=C&#8203;:\\WINDOWS\\system32;C&#8203;:\\WINDOWS;C&#8203;:\\WINDOWS\\System32\\Wbem;C&#8203;:\\perl5\\bin
&nbsp;    PERL5LIB \(unset\)
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL \(unset\)

**Comment by p5pRT** [comment]
### From @jkeenan

On Tue Oct 14 08&#8203;:54&#8203;:57 2003\, shay wrote&#8203;:
> 
> However\, the above program always crashes with this error&#8203;:
> 
>     sdbm store returned \-1\, errno 22\, key "\.\.\."
> 
> at the point where i==1 and j==0\.
> 

With the attached program 24206\.pl\, I was able to set how large a matrix
I wanted to try\.  I had no problem at 127\, but when I tried the OP's
suggested 255\, my program got farther than his but ultimately died with
a similar error\.

069 \- 128
sdbm store returned \-1\, errno 22\, key "E?" at 24206\.pl line 25\.

This was on Darwin \(Mac OS X 10\.4\.11\)\.

Does anyone have any insight into this?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From @jkeenan

[24206.pl](https://rt-archive.perl.org/perl5/Ticket/Attachment/1025744/505926/24206.pl)

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @tonycoz

On Thu\, Dec 01\, 2011 at 06&#8203;:06&#8203;:28PM \-0800\, James E Keenan via RT wrote&#8203;:
> On Tue Oct 14 08&#8203;:54&#8203;:57 2003\, shay wrote&#8203;:
> > 
> > However\, the above program always crashes with this error&#8203;:
> > 
> >     sdbm store returned \-1\, errno 22\, key "\.\.\."
> > 
> > at the point where i==1 and j==0\.
> > 
> 
> With the attached program 24206\.pl\, I was able to set how large a matrix
> I wanted to try\.  I had no problem at 127\, but when I tried the OP's
> suggested 255\, my program got farther than his but ultimately died with
> a similar error\.
> 
> 069 \- 128
> sdbm store returned \-1\, errno 22\, key "E?" at 24206\.pl line 25\.
> 
> This was on Darwin \(Mac OS X 10\.4\.11\)\.
> 
> Does anyone have any insight into this?

I suspect you're running into a 32\-bit long issue\.

On x64 Linux with a 64\-bit long your test ran successfully\, producing&#8203;:

\-rw\-r\-\-r\-\- 1 tony tony    1048576 Dec  2 20&#8203;:54 testsdbm\.dir
\-rw\-r\-\-r\-\- 1 tony tony 8589907968 Dec  2 20&#8203;:54 testsdbm\.pag

which a 64\-bit offset can seek within successfully\, not not 32\-bit\.

Tony

**Comment by vrkosk** [comment]
Yes, definitely a 32-bit issue on Windows. I saw this bug today with a script we typically run in production on Linux and wanted to see if it can be run on Windows. On Linux, our script creates a ~64GB .pag file. On Windows, it fails with "sdbm store returned -1, errno 22" when the .pag file reaches almost 2**31 bytes, 2147471360 to be exact.

Is this connected to issue #12227?

**Comment by tonycoz** [comment]
It might be partly connected to #12227.  

Another problem is "long" is 32-bits for both 32 and 64-bit Win32: https://docs.microsoft.com/en-us/cpp/cpp/integer-limits?view=msvc-170

and sdbm.c casts its page numbers to long when calculating the seek offsets, which limits the offsets to long.
