### ISSUE TITLE
Class::Struct, accessor overrides not called from constructor

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7272]
Migrated from [rt.perl.org#29230](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=29230) (status was 'resolved')

Searchable as RT29230$

**Comment by p5pRT** [comment]
### From perl@rhesa.com

This is a bug report for perl from perl@&#8203;rhesa\.com\,
generated with the help of perlbug 1\.34 running under perl v5\.8\.2\.




---
Class&#8203;::Struct allows you to override the accessors it creates\, but it 
doesn't call them in its constructor\.
In other words\,

&nbsp;     $struct\->field\('blah'\);

calls my override\, but

&nbsp;     $struct = structure\->new\('field' => 'blah'\);

doesn't\. Class&#8203;::Struct simply does

&nbsp;     $r\->\{'field'\} = $init\{'field'\}

but it would be more useful if it did

&nbsp;     $r\->field\($init\{'field'\}\)

See the sample code below for a demonstration\.
I have also attached a diff with fixes to the code\, and the results from 
running Struct\.t\, the test script for Class&#8203;::Struct as found in the perl 
5\.8\.4 distribution\.

Thank you for your attention\,
Rhesa Rozendaal


Demonstration script&#8203;:

\#\!/usr/bin/perl
use strict;
use warnings;
use Class&#8203;::Struct;
use Data&#8203;::Dumper;

\#\#\# define struct
struct memory => \{
&nbsp;     swap    =>    '$'\,
&nbsp;     free    =>    '$'\,
\};

\#\#\# override accessor for free
sub memory&#8203;::free \{
&nbsp;     my $r = shift;
&nbsp;     die 'Too many args to free' if @&#8203;\_ > 1;
&nbsp;     if\(@&#8203;\_\) \{
&nbsp;         my $id = shift;
&nbsp;         if\( $id > 100 or $id \< 0 \) \{
&nbsp;             warn "free \`$id\` should be between 0 and 100";
&nbsp;         \} else \{
&nbsp;             $r\->\{'memory&#8203;::free'\} = $id;
&nbsp;         \}
&nbsp;     \}

&nbsp;     $r\->\{'memory&#8203;::free'\};
\}

\#\#\# create object and dump
my $m = memory\->new\(free=>110\, swap => 100\);
print Dumper\($m\);        \# free contains 110\, but undef is expected

$m\->free\(120\);            \# warns and doesn't update\, as expected
print Dumper\($m\);

$m\->free\(25\);            \# sets free to 25
print Dumper\($m\);

\_\_END\_\_;


diff of fixed code&#8203;:

Compare&#8203;: \(\<\)D&#8203;:\\APM\\Perl\\lib\\Class\\Struct\.pm \(20512 bytes\)
&nbsp;    with&#8203;: \(>\)D&#8203;:\\APM\\Perl\\lib\\Class\\Struct\_new\.pm \(21188 bytes\)

133a133\,135
 >
 >     $out \.= "    bless \\$r\, \\$class;\\n\\n";
 >
153c156
\<             $out \.= "    \\$r\->$elem = $init \[\];$cmt\\n";


---
 >             $out \.= "    \\$r\->$name\( $init \[\] \);$cmt\\n";
159c162
\<             $out \.= "    \\$r\->$elem = $init \{\};$cmt\\n";


---
 >             $out \.= "    \\$r\->$name\( $init \{\} \);$cmt\\n";
163c166
\<             $out \.= "    \\$r\->$elem = $init undef;$cmt\\n";


---
 >             $out \.= "    \\$r\->$name\( $init undef \);$cmt\\n";
168c171
\<             $out \.= "            \{ \\$r\->$elem = 
$type\->new\(\\%\{\\$init\{'$name'\}\}\) \} $cmt\\n";


---
 >             $out \.= "            \{ \\$r\->$name\( 
$type\->new\(\\%\{\\$init\{'$name'\}\}\) \) \} $cmt\\n";
170c173
\<             $out \.= "            \{ \\$r\->$elem = \\$init\{'$name'\} \} $cmt\\n";


---
 >             $out \.= "            \{ \\$r\->$name\( \\$init\{'$name'\} \) \} 
$cmt\\n";
181c184
\<     $out \.= "    bless \\$r\, \\$class;\\n  \}\\n";


---
 >     $out \.= "\\n    \\$r;\\n  \}\\n";


Test results&#8203;:

1\.\.24
ok 1 \- The object isa MyObj
ok 2
ok 3 \- The object isa ARRAY
ok 4
ok 5
ok 6 \- The object isa HASH
ok 7
ok 8
ok 9
ok 10 \- The object isa aClass
ok 11
ok 12 \- The object isa MyOther
ok 13
ok 14 \- The object isa ARRAY
ok 15
ok 16
ok 17 \- The object isa HASH
ok 18
ok 19
ok 20
ok 21 \- The object isa aClass
ok 22
ok 23
ok 24 \- The object isa RecClass




---


---
Flags&#8203;:
&nbsp;     category=library
&nbsp;     severity=low


---
Site configuration information for perl v5\.8\.2&#8203;:

Configured by rhesa at Wed Dec 31 09&#8203;:46&#8203;:19 2003\.

Summary of my perl5 \(revision 5 version 8 subversion 2\) configuration&#8203;:
&nbsp;   Platform&#8203;:
&nbsp;     osname=MSWin32\, osvers=4\.0\, archname=MSWin32\-x86\-multi\-thread
&nbsp;     uname=''
&nbsp;     config\_args='undef'
&nbsp;     hint=recommended\, useposix=true\, d\_sigaction=undef
&nbsp;     usethreads=undef use5005threads=undef useithreads=define 
usemultiplicity=define
&nbsp;     useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;     use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;     usemymalloc=n\, bincompat5005=undef
&nbsp;   Compiler&#8203;:
&nbsp;     cc='cl'\, ccflags ='\-nologo \-Gf \-W3 \-MD \-DNDEBUG \-O1 \-DWIN32 
\-D\_CONSOLE \-DNO\_STRICT \-DHAVE\_DES\_FCRYPT  \-DNO\_HASH\_SEED 
\-DPERL\_IMPLICIT\_CONTEXT \-DPERL\_IMPLICIT\_SYS \-DUSE\_PERLIO 
\-DPERL\_MSVCRT\_READFIX'\,
&nbsp;     optimize='\-MD \-DNDEBUG \-O1'\,
&nbsp;     cppflags='\-DWIN32'
&nbsp;     ccversion=''\, gccversion=''\, gccosandvers=''
&nbsp;     intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;     d\_longlong=undef\, longlongsize=8\, d\_longdbl=define\, longdblsize=10
&nbsp;     ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, 
Off\_t='\_\_int64'\, lseeksize=8
&nbsp;     alignbytes=8\, prototype=define
&nbsp;   Linker and Libraries&#8203;:
&nbsp;     ld='link'\, ldflags ='\-nologo \-nodefaultlib \-release 
\-libpath&#8203;:"d&#8203;:\\apm\\Perl\\lib\\CORE"  \-machine&#8203;:x86'
&nbsp;     libpth=\\lib
&nbsp;     libs=  oldnames\.lib kernel32\.lib user32\.lib gdi32\.lib winspool\.lib 
&nbsp;  comdlg32\.lib advapi32\.lib shell32\.lib ole32\.lib oleaut32\.lib 
netapi32\.lib uuid\.lib wsock32\.lib mpr\.lib winmm\.lib  version\.lib 
odbc32\.lib odbccp32\.lib msvcrt\.lib
&nbsp;     perllibs=  oldnames\.lib kernel32\.lib user32\.lib gdi32\.lib 
winspool\.lib  comdlg32\.lib advapi32\.lib shell32\.lib ole32\.lib 
oleaut32\.lib  netapi32\.lib uuid\.lib wsock32\.lib mpr\.lib winmm\.lib 
version\.lib odbc32\.lib odbccp32\.lib msvcrt\.lib
&nbsp;     libc=msvcrt\.lib\, so=dll\, useshrplib=yes\, libperl=perl58\.lib
&nbsp;     gnulibc\_version='undef'
&nbsp;   Dynamic Linking&#8203;:
&nbsp;     dlsrc=dl\_win32\.xs\, dlext=dll\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;     cccdlflags=' '\, lddlflags='\-dll \-nologo \-nodefaultlib \-release 
\-libpath&#8203;:"d&#8203;:\\apm\\Perl\\lib\\CORE"  \-machine&#8203;:x86'

Locally applied patches&#8203;:
&nbsp;     ACTIVEPERL\_LOCAL\_PATCHES\_ENTRY
&nbsp;     21846 Configure gets d\_u32align wrong
&nbsp;     21739 \[perl \#24493\] install\.html not working
&nbsp;     21737 Ooops\. left an XXX comment in\, and worse still it's a // comment
&nbsp;     21735 utf8 keys now work for tied hashes
&nbsp;     21734 Accessing unicode keys in tie hashes via hv\_exists was broken
&nbsp;     21733 ext/threads/t/problem\.t
&nbsp;     21732 Config&#8203;::myconfig\(\) fails under ithreads
&nbsp;     21728 Update perlhist with 5\.6\.2
&nbsp;     21723 Include 'SCCS' in the list of dir names ignored by installperl
&nbsp;     21718 Empty subroutine as object method segfaults in 5\.8\.2 \(sometimes\)
&nbsp;     21714 Fix bug \#24380&#8203;: assigning list with duplicated keys to a hash
&nbsp;     21706 \[perl \#24460\] \[DOC PATCH\] the begincheck program
&nbsp;     21693 must copy changes from win32/makeifle\.mk to wince/makefile\.ce
&nbsp;     21691 Update the list of pumpkings in perlhist\.pod
&nbsp;     21687 \[PATCH 5\.6\.2\-RC1 pod/perlhist\.pod\]  Updated
&nbsp;     21677 OS/2 docu
&nbsp;     21676 Bug \#24407&#8203;: key for shared hash got stringified into wrong pool
&nbsp;     21673 Be sure to use \-fPIC not \-fpic on Linux/SPARC
&nbsp;     21672 extending the hash attack test
&nbsp;     21671 Benchmark\.pm cmpthese segfault
&nbsp;     21662 'make minitest' fails for op/cproto and op/pat
&nbsp;     21586 Comment that this 'optimisation' is actually a necessary fixup
&nbsp;     21548 Sync with Pod&#8203;::Perldoc 3\.12
&nbsp;     21540 Fix backward\-compatibility issues in if\.pm



---
@&#8203;INC for perl v5\.8\.2&#8203;:
&nbsp;     D&#8203;:/APM/Perl/lib
&nbsp;     D&#8203;:/APM/Perl/site/lib
&nbsp;     \.



---
Environment for perl v5\.8\.2&#8203;:
&nbsp;     HOME=c&#8203;:/
&nbsp;     LANG=NL
&nbsp;     LANGUAGE \(unset\)
&nbsp;     LD\_LIBRARY\_PATH \(unset\)
&nbsp;     LOGDIR \(unset\)
&nbsp;     PATH=c&#8203;:\\program 
files\\imagemagick\-5\.5\.7\-q8;C&#8203;:\\Cygwin\\bin;C&#8203;:\\PerlForDotNet\\bin\\;C&#8203;:\\Program 
Files\\Microsoft\.Net\\FrameworkSDK\\Bin\\;C&#8203;:\\WINNT\\Microsoft\.NET\\Framework\\v1\.0\.2204\\;C&#8203;:\\Perl\\bin\\;C&#8203;:\\WINNT\\system32;C&#8203;:\\WINNT;C&#8203;:\\WINNT\\System32\\Wbem;C&#8203;:\\Program 
Files\\Microsoft SDK for Java 4\.0\\Bin;C&#8203;:\\Program 
Files\\InstallShield\\InstallShield 5\.5 Professional 
Edition\\Program;C&#8203;:\\MSSQL7\\BINN;C&#8203;:\\Program 
Files\\cvsnt;c&#8203;:\\data\\rrdtool\\bin;c&#8203;:\\program 
files\\kevterm;C&#8203;:\\GnuPG;C&#8203;:\\Program Files\\ImageMagick\-5\.5\.6\-Q8;C&#8203;:\\Program 
Files\\Microsoft Visual Studio\\Common\\Tools\\WinNT;C&#8203;:\\Program 
Files\\Microsoft Visual Studio\\Common\\MSDev98\\Bin;C&#8203;:\\Program 
Files\\Microsoft Visual Studio\\Common\\Tools;C&#8203;:\\Program Files\\Microsoft 
Visual Studio\\VC98\\bin;C&#8203;:\\Program Files\\deskwin\\shortcuts
&nbsp;     PERLDB\_OPTS=RemotePort=127\.0\.0\.1&#8203;:2000
&nbsp;     PERL\_BADLANG \(unset\)
&nbsp;     SHELL \(unset\)

**Comment by p5pRT** [comment]
### From @schwern

> \[rhesa \- Wed Apr 28 11&#8203;:12&#8203;:56 2004\]&#8203;:
> 
> Class&#8203;::Struct allows you to override the accessors it creates\, but it
> doesn't call them in its constructor\.
> In other words\,
> 
>      $struct\->field\('blah'\);
> 
> calls my override\, but
> 
>      $struct = structure\->new\('field' => 'blah'\);
> 
> doesn't\. Class&#8203;::Struct simply does
> 
>      $r\->\{'field'\} = $init\{'field'\}
> 
> but it would be more useful if it did
> 
>      $r\->field\($init\{'field'\}\)

Sounds like a valid complaint to me\.  Example 2 in the docs demonstrates
 overriding Class&#8203;::Struct accessors and the constructor should follow suit\.

Pumpkings\, there's a patch with this ticket to fix this\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From renee.baecker@smart-websolutions.de

Hi\,

I've tested the patch by Rhesa Rozendaal and made a unified diff \(that
is attached\)\.\.\.

Cheers\,
Renee

**Comment by p5pRT** [comment]
### From renee.baecker@smart-websolutions.de

<details><summary>Struct.patch</summary>

```diff
--- lib/Class/Struct.pm.orig	2008-08-31 11:03:38.000000000 +0200
+++ lib/Class/Struct.pm	2008-08-31 11:11:36.000000000 +0200
@@ -130,6 +130,9 @@
     elsif( $base_type eq 'ARRAY' ){
         $out .= "    my(\$r) = [];\n";
     }
+
+    $out .= " bless \$r, \$class;\n\n";
+
     while( $idx < @decls ){
         $name = $decls[$idx];
         $type = $decls[$idx+1];
@@ -150,24 +153,24 @@
         if( $type eq '@' ){
             $out .= "    croak 'Initializer for $name must be array reference'\n"; 
             $out .= "        if defined(\$init{'$name'}) && ref(\$init{'$name'}) ne 'ARRAY';\n";
-            $out .= "    \$r->$elem = $init [];$cmt\n"; 
+            $out .= "    \$r->$name( $init [] );$cmt\n"; 
             $arrays{$name}++;
         }
         elsif( $type eq '%' ){
             $out .= "    croak 'Initializer for $name must be hash reference'\n";
             $out .= "        if defined(\$init{'$name'}) && ref(\$init{'$name'}) ne 'HASH';\n";
-            $out .= "    \$r->$elem = $init {};$cmt\n";
+            $out .= "    \$r->$name( $init {} );$cmt\n";
             $hashes{$name}++;
         }
         elsif ( $type eq '$') {
-            $out .= "    \$r->$elem = $init undef;$cmt\n";
+            $out .= "    \$r->$name( $init undef );$cmt\n";
         }
         elsif( $type =~ /^\w+(?:::\w+)*$/ ){
             $out .= "    if (defined(\$init{'$name'})) {\n";
            $out .= "       if (ref \$init{'$name'} eq 'HASH')\n";
-            $out .= "            { \$r->$elem = $type->new(\%{\$init{'$name'}}) } $cmt\n";
+            $out .= "            { \$r->$name( $type->new(\%{\$init{'$name'}}) ) } $cmt\n";
            $out .= "       elsif (UNIVERSAL::isa(\$init{'$name'}, '$type'))\n";
-            $out .= "            { \$r->$elem = \$init{'$name'} } $cmt\n";
+            $out .= "            { \$r->$name( \$init{'$name'} ) } $cmt\n";
             $out .= "       else { croak 'Initializer for $name must be hash or $type reference' }\n";
             $out .= "    }\n";
             $classes{$name} = $type;
@@ -178,7 +181,8 @@
         }
         $idx += 2;
     }
-    $out .= "    bless \$r, \$class;\n  }\n";
+
+    $out .= "\n \$r;\n}\n";
 
     # Create accessor methods.
 

```
</details>

**Comment by p5pRT** [comment]
### From @Hugmeir

On Sun Aug 31 02&#8203;:16&#8203;:51 2008\, renee\.baecker@&#8203;smart\-websolutions\.de wrote&#8203;:
> Hi\,
> 
> I've tested the patch by Rhesa Rozendaal and made a unified diff \(that
> is attached\)\.\.\.
> 
> Cheers\,
> Renee

Could someone review/apply the patch in this ticket?

\-\-hugmeir

**Comment by p5pRT** [comment]
### From @cpansprout

On Sun May 27 04&#8203;:21&#8203;:46 2012\, Hugmeir wrote&#8203;:
> On Sun Aug 31 02&#8203;:16&#8203;:51 2008\, renee\.baecker@&#8203;smart\-websolutions\.de wrote&#8203;:
> > Hi\,
> > 
> > I've tested the patch by Rhesa Rozendaal and made a unified diff \(that
> > is attached\)\.\.\.
> > 
> > Cheers\,
> > Renee
> 
> Could someone review/apply the patch in this ticket?
> 
> \-\-hugmeir

It’s not only committers who can review patches\. :\-\)

I’ve never used Class&#8203;::Struct before\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From @cpansprout

On Fri Jun 08 20&#8203;:34&#8203;:30 2012\, sprout wrote&#8203;:
> On Sun May 27 04&#8203;:21&#8203;:46 2012\, Hugmeir wrote&#8203;:
> > On Sun Aug 31 02&#8203;:16&#8203;:51 2008\, renee\.baecker@&#8203;smart\-websolutions\.de wrote&#8203;:
> > > Hi\,
> > > 
> > > I've tested the patch by Rhesa Rozendaal and made a unified diff \(that
> > > is attached\)\.\.\.
> > > 
> > > Cheers\,
> > > Renee
> > 
> > Could someone review/apply the patch in this ticket?
> > 
> > \-\-hugmeir
> 
> It’s not only committers who can review patches\. :\-\)
> 
> I’ve never used Class&#8203;::Struct before\.

But I’ve just had a look at the patch anyway\, and it looks good\, except
it lacks tests\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From mailinglisten@renee-baecker.de

On 09\.06\.2012 05&#8203;:41\, Father Chrysostomos via RT wrote&#8203;:
> But I’ve just had a look at the patch anyway\, and it looks good\, except
> it lacks tests\.

Attached is a patch that add two tests\.\.\.


\- Renee

**Comment by p5pRT** [comment]
### From mailinglisten@renee-baecker.de

<details><summary>0001-add-tests-for-overridden-Class-Struct-accessors.patch</summary>

```diff
From a06895e8db0e5e1a0de2ee2715e5fc1fd5d56de1 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Renee=20B=C3=A4cker?= <perl@renee-baecker.de>
Date: Sat, 9 Jun 2012 04:17:18 -0700
Subject: [PATCH] add tests for overridden Class::Struct accessors

---
 lib/Class/Struct.t |   26 +++++++++++++++++++++++++-
 1 files changed, 25 insertions(+), 1 deletions(-)

diff --git a/lib/Class/Struct.t b/lib/Class/Struct.t
index 694d622..71cdaa3 100644
--- a/lib/Class/Struct.t
+++ b/lib/Class/Struct.t
@@ -33,11 +33,29 @@ package MyOther;
 use Class::Struct s => '$', a => '@', h => '%', c => 'aClass';
 
 #
+# test overriden accessors
+#
+package OverrideAccessor;
+use Class::Struct;
+
+struct( 'OverrideAccessor', { count => '$' } );
+
+sub count {
+  my ($self,$count) = @_;
+
+  if ( @_ >= 2 ) {
+    $self->{'OverrideAccessor::count'} = $count + 9;
+  }
+
+  return $self->{'OverrideAccessor::count'};
+}
+
+#
 # back to main...
 #
 package main;
 
-use Test::More tests => 24;
+use Test::More tests => 26;
 
 my $obj = MyObj->new;
 isa_ok $obj, 'MyObj';
@@ -101,3 +119,9 @@ is $obk->SomeElem(), 123;
 my $recobj = RecClass->new();
 isa_ok $recobj, 'RecClass';
 
+my $override_obj = OverrideAccessor->new( count => 3 );
+is $override_obj->count, 12;
+
+$override_obj->count( 1 );
+is $override_obj->count, 10;
+
-- 
1.7.5.4


```
</details>

**Comment by p5pRT** [comment]
### From @cpansprout

On Sat Jun 09 04&#8203;:22&#8203;:47 2012\, mailinglisten@&#8203;renee\-baecker\.de wrote&#8203;:
> On 09\.06\.2012 05&#8203;:41\, Father Chrysostomos via RT wrote&#8203;:
> > But I’ve just had a look at the patch anyway\, and it looks good\, except
> > it lacks tests\.
> 
> Attached is a patch that add two tests\.\.\.

Thank you\.  I have applied the original patch as a79a48c06 and the tests
as 61dc4abcc6d\.

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
@cpansprout - Status changed from 'open' to 'resolved'

**Comment by freonpsandoz** [comment]
I'm using ActiveState Perl 5.20 built 20 July 2015. It has Class::Struct 0.65 and it doesn't seem to have this fix. What version of Class::Struct has this fix, and where can I get it? CPAN shows version 0.66 with no changes since 2001. Thanks.

**Comment by iabyn** [comment]
On Tue, May 09, 2023 at 08:44:29AM +0000, freonpsandoz wrote:
> I'm using ActiveState Perl 5.20 built 20 July 2015. It has Class::Struct
> 0.65 and it doesn't seem to have this fix. What version of Class::Struct
> has this fix, and where can I get it? CPAN shows version 0.66 with no
> changes since 2001. Thanks.

The fix mentioned in this ticket was applied to the version of
Class::Struct bundled with perl - it appeared first in Class::Struct
version 0.64, which was bundled with perl 5.18.0.

-- 
In my day, we used to edit the inodes by hand.  With magnets.
