### ISSUE TITLE
Installation problem - dos/djgpp platform

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7350]
Migrated from [rt.perl.org#30104](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=30104) (status was 'stalled')

Searchable as RT30104$

**Comment by p5pRT** [comment]
### From pjmooney@panix.com

To whom it may concern&#8203;:

I believe that I have found a bug in the Perl installation process on a 
dos/djgpp platform\.  When I ran the configure\.bat file\, I eventually 
got these messages&#8203;:
Run make depend now? \[y\]
make\.exe&#8203;:\*\*\* No rule to make target 'depend'\.   Stop\.

After configure ended\, I tried to run make\, but I got this error 
message&#8203;:
make\.exe&#8203;: \*\*\* No targets specified and no makefile found\.  Stop\.

I could not compile a build of Perl\, and could not run perlbug\.  I 
managed to run myconfig\.sh\, and to generate a myconfig output 
file\, which I have attached to this e\-mail message as an ASCII file\.
There were other problems which I was able to fix \(these will be for 
another e\-mail message\)\.  But I can't seem to get a handle on this 
one\.  Please advise\.

Sincerely Yours\,

Paul J Mooney

**Comment by p5pRT** [comment]
### From pjmooney@panix.com

The following section of this message contains a file attachment
prepared for transmission using the Internet MIME message format\.
If you are using Pegasus Mail\, or any another MIME\-compliant system\,
you should be able to save it or view it from within your mailer\.
If you cannot\, please ask your system administrator for assistance\.

&nbsp;   \-\-\-\- File information \-\-\-\-\-\-\-\-\-\-\-
&nbsp;     File&#8203;:  myconfig
&nbsp;     Date&#8203;:  7 Jun 2004\, 2&#8203;:59
&nbsp;     Size&#8203;:  1744 bytes\.
&nbsp;     Type&#8203;:  Text

**Comment by p5pRT** [comment]
### From pjmooney@panix.com

[myconfig](https://rt-archive.perl.org/perl5/Ticket/Attachment/89908/63164/myconfig)

**Comment by p5pRT** [comment]
### From @ysth

On Tue\, Jun 08\, 2004 at 07&#8203;:03&#8203;:48AM \-0000\, Paul J Mooney wrote&#8203;:
> I believe that I have found a bug in the Perl installation process on a 
> dos/djgpp platform\.  When I ran the configure\.bat file\, I eventually 
> got these messages&#8203;:
> Run make depend now? \[y\]
> make\.exe&#8203;:\*\*\* No rule to make target 'depend'\.   Stop\.

Not a djgpp user myself\, but it sounds like you didn't get a Makefile
built\.  Could you go ahead and send your whole config\.sh \(attached\)?

Try running Makefile\.SH directly and see if you see any errors\.

Did any of the \*\.SH scripts successfully run? \(Each creates a file
with similar name\.\)  Configure \-S will retry running them\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From pjmooney@panix.com



On 8 Jun 04\, at 16&#8203;:32\, Yitzchak Scott\-Thoennes via R wrote&#8203;:

> Not a djgpp user myself\, but it sounds like you didn't get a Makefile
> built\.  Could you go ahead and send your whole config\.sh \(attached\)?
> 
> Try running Makefile\.SH directly and see if you see any errors\.
> 
> Did any of the \*\.SH scripts successfully run? \(Each creates a file
> with similar name\.\)  Configure \-S will retry running them\.
> 
> 
> 
I've attached the config\.sh file\, as you requested\.
I ran Makefile\.SH directly\.  I didn't see any errors\.
I also ran Configure \-S\.  I didn't see any errors there either\.
I'm sorry that I didn't reply sooner\.  I've been really tied up over the 
last few days\.  Thank you for responding so promptly\.

Paul J Mooney
10 East St
PO Box 721 
Middle Island\, NY\, 11953
631\-924\-0284

**Comment by p5pRT** [comment]
### From pjmooney@panix.com

The following section of this message contains a file attachment
prepared for transmission using the Internet MIME message format\.
If you are using Pegasus Mail\, or any another MIME\-compliant system\,
you should be able to save it or view it from within your mailer\.
If you cannot\, please ask your system administrator for assistance\.

&nbsp;   \-\-\-\- File information \-\-\-\-\-\-\-\-\-\-\-
&nbsp;     File&#8203;:  config\.sh
&nbsp;     Date&#8203;:  7 Jun 2004\, 2&#8203;:50
&nbsp;     Size&#8203;:  29720 bytes\.
&nbsp;     Type&#8203;:  Text

**Comment by p5pRT** [comment]
### From pjmooney@panix.com

[config.sh](https://rt-archive.perl.org/perl5/Ticket/Attachment/90347/63388/config.sh)

**Comment by p5pRT** [comment]
### From @ysth

On Fri\, Jun 11\, 2004 at 04&#8203;:07&#8203;:36AM \-0500\, Paul J Mooney \<pjmooney@&#8203;panix\.com> wrote&#8203;:
Content\-Description&#8203;: Mail message body
> 
> 
> On 8 Jun 04\, at 16&#8203;:32\, Yitzchak Scott\-Thoennes via R wrote&#8203;:
> 
> > Not a djgpp user myself\, but it sounds like you didn't get a Makefile
> > built\.  Could you go ahead and send your whole config\.sh \(attached\)?
> > 
> > Try running Makefile\.SH directly and see if you see any errors\.
> > 
> > Did any of the \*\.SH scripts successfully run? \(Each creates a file
> > with similar name\.\)  Configure \-S will retry running them\.
> > 
> > 
> > 
> I've attached the config\.sh file\, as you requested\.
> I ran Makefile\.SH directly\.  I didn't see any errors\.
> I also ran Configure \-S\.  I didn't see any errors there either\.
> I'm sorry that I didn't reply sooner\.  I've been really tied up over the 
> last few days\.  Thank you for responding so promptly\.

And was a Makefile created?

**Comment by p5pRT** [comment]
### From abe@ztreet.demon.nl

Op een zonnige lentedag \(Monday 14 June 2004 01&#8203;:17\)\, schreef Yitzchak 
Scott\-Thoennes&#8203;:

> On Fri\, Jun 11\, 2004 at 04&#8203;:07&#8203;:36AM \-0500\, Paul J Mooney
> \<pjmooney@&#8203;panix\.com> wrote&#8203;: Content\-Description&#8203;: Mail message body
> > I've attached the config\.sh file\, as you requested\.
> > I ran Makefile\.SH directly\.  I didn't see any errors\.
> > I also ran Configure \-S\.  I didn't see any errors there either\.
> > I'm sorry that I didn't reply sooner\.  I've been really tied up over the
> > last few days\.  Thank you for responding so promptly\.
>
> And was a Makefile created?

I have just installed a fresh djgpp and followed the instructions in 
README\.dos and got to this stage&#8203;:

&nbsp;        Making DynaLoader \(static\)
Writing Makefile for DynaLoader
make\.exe\[1\]&#8203;: Entering directory 
\`c&#8203;:/djgpp/home/abeltje/Test\-Smoke/perl\-current/ext/DynaLoader'
make\.exe\[1\]&#8203;: \*\*\* No rule to make target \`blibdirs\_exists'\, needed by \`config'\.
Stop\.
make\.exe\[1\]&#8203;: Leaving directory 
\`c&#8203;:/djgpp/home/abeltje/Test\-Smoke/perl\-current/ext/DynaLoader'
c&#8203;:/djgpp/bin/make\.exe config failed\, continuing anyway\.\.\.
make\.exe\[1\]&#8203;: Entering directory 
\`c&#8203;:/djgpp/home/abeltje/Test\-Smoke/perl\-current/ext/DynaLoader'
make\.exe\[1\]&#8203;: \*\*\* No rule to make target \`blibdirs\_exists'\, needed by \`config'\.
Stop\.
make\.exe\[1\]&#8203;: Leaving directory 
\`c&#8203;:/djgpp/home/abeltje/Test\-Smoke/perl\-current/ext/DynaLoader'
make\.exe&#8203;: \*\*\* \[lib/auto/DynaLoader/DynaLoader\.a\] Error 2
bash\-2\.04$        Making DynaLoader \(static\)
Writing Makefile for DynaLoader
make\.exe\[1\]&#8203;: Entering directory 
\`c&#8203;:/djgpp/home/abeltje/Test\-Smoke/perl\-current/ext/DynaLoader'
make\.exe\[1\]&#8203;: \*\*\* No rule to make target \`blibdirs\_exists'\, needed by \`config'\.
Stop\.
make\.exe\[1\]&#8203;: Leaving directory 
\`c&#8203;:/djgpp/home/abeltje/Test\-Smoke/perl\-current/ext/DynaLoader'
c&#8203;:/djgpp/bin/make\.exe config failed\, continuing anyway\.\.\.
make\.exe\[1\]&#8203;: Entering directory 
\`c&#8203;:/djgpp/home/abeltje/Test\-Smoke/perl\-current/ext/DynaLoader'
make\.exe\[1\]&#8203;: \*\*\* No rule to make target \`blibdirs\_exists'\, needed by \`config'\.
Stop\.
make\.exe\[1\]&#8203;: Leaving directory 
\`c&#8203;:/djgpp/home/abeltje/Test\-Smoke/perl\-current/ext/DynaLoader'
make\.exe&#8203;: \*\*\* \[lib/auto/DynaLoader/DynaLoader\.a\] Error 2
bash\-2\.04$

Good luck\,

Abe
\-\- 
NI\-S> Next game is to try and convert all that chinese spam I get into
NI\-S> test data and see it in tkmail\.\.\.

If you need more I can forward you mine\, one never knows if one might
need ship\-building grade steel by the ton\.\.\.\.
&nbsp;                                   \-\- Jarkko Hietaniemi on p5p @&#8203; 2002\-04\-11

**Comment by p5pRT** [comment]
### From pjmooney@panix.com

On 14 Jun 04\, at 19&#8203;:38\, Abe Timmerman via RT wrote&#8203;:

> 
> I have just installed a fresh djgpp and followed the instructions in
> README\.dos and got to this stage&#8203;:
> 
>         Making DynaLoader \(static\)
> Writing Makefile for DynaLoader
> make\.exe\[1\]&#8203;: Entering directory 
> \`c&#8203;:/djgpp/home/abeltje/Test\-Smoke/perl\-current/ext/DynaLoader'
> make\.exe\[1\]&#8203;: \*\*\* No rule to make target \`blibdirs\_exists'\, needed by
> \`config'\. Stop\. make\.exe\[1\]&#8203;: Leaving directory
> \`c&#8203;:/djgpp/home/abeltje/Test\-Smoke/perl\-current/ext/DynaLoader'
> c&#8203;:/djgpp/bin/make\.exe config failed\, continuing anyway\.\.\. make\.exe\[1\]&#8203;:
> Entering directory
> \`c&#8203;:/djgpp/home/abeltje/Test\-Smoke/perl\-current/ext/DynaLoader'
> make\.exe\[1\]&#8203;: \*\*\* No rule to make target \`blibdirs\_exists'\, needed by
> \`config'\. Stop\. make\.exe\[1\]&#8203;: Leaving directory
> \`c&#8203;:/djgpp/home/abeltje/Test\-Smoke/perl\-current/ext/DynaLoader'
> make\.exe&#8203;: \*\*\* \[lib/auto/DynaLoader/DynaLoader\.a\] Error 2 bash\-2\.04$   
>     Making DynaLoader \(static\) Writing Makefile for DynaLoader
> make\.exe\[1\]&#8203;: Entering directory
> \`c&#8203;:/djgpp/home/abeltje/Test\-Smoke/perl\-current/ext/DynaLoader'
> make\.exe\[1\]&#8203;: \*\*\* No rule to make target \`blibdirs\_exists'\, needed by
> \`config'\. Stop\. make\.exe\[1\]&#8203;: Leaving directory
> \`c&#8203;:/djgpp/home/abeltje/Test\-Smoke/perl\-current/ext/DynaLoader'
> c&#8203;:/djgpp/bin/make\.exe config failed\, continuing anyway\.\.\. make\.exe\[1\]&#8203;:
> Entering directory
> \`c&#8203;:/djgpp/home/abeltje/Test\-Smoke/perl\-current/ext/DynaLoader'
> make\.exe\[1\]&#8203;: \*\*\* No rule to make target \`blibdirs\_exists'\, needed by
> \`config'\. Stop\. make\.exe\[1\]&#8203;: Leaving directory
> \`c&#8203;:/djgpp/home/abeltje/Test\-Smoke/perl\-current/ext/DynaLoader'
> make\.exe&#8203;: \*\*\* \[lib/auto/DynaLoader/DynaLoader\.a\] Error 2 bash\-2\.04$
> 
> Good luck\,
> 
> Abe
> \-\- 
When I set up DJGPP to build\, I found that\, in addition to the files 
listed in the README\.dos file\, I needed to install these files as 
well&#8203;:
&nbsp;             v2/djtzn203\.zip 
&nbsp;             v2gnu/lss374b\.zip

I needed to installl djtzn203\.zip because configure called for time 
zone information in processing files' time and date stamps\.  

I needed to install lss374b\.zip \(less\.exe\) because configure queried 
for a lister program\.  Also\, the configur\.bat file in the \*\\perl\\djgpp 
directory had "\*\\djgpp\\bin\\less\.exe" as the lister\.  
Without lss\*\.zip\, configure would call\, as a default\, another lister 
program that I didn't even have installed \(I can't remember what that 
file was\, offhand\)\.  Even when I had less\.exe installed\, it would 
query for it\, saying that it wasn't installed\.  I replied to this query to 
accept it nonetheless\.  This seemed to work\.

I also installed these files \(among others\)&#8203;:
v2\\gpp333b\.zip
v2gnu\\byacc19b\.zip
v2gnu\\bsn135b\.zip
Configure looked for these on my setup\.  They may help you to get 
past the stage that you are now\, at least\.  

If you want to run configure in non\-interactive mode\, with the \-des 
option\, I'd suggest that you install byacc19b\.zip\.  Configure called 
yacc \(byacc\) over bison \-y as a default\, even when byacc wasn't 
installed\.  This was another problem I had with configure\. I was 
able to straighten this one out\, so I was waiting until I had my 
current problem resolved \(when\, hopefully\, I could get perlbug up 
and running\!\) before reporting this and the other problems I had\.
Thanks for your input\.  And best of luck\.

Paul

**Comment by p5pRT** [comment]
### From @doughera88

On Tue\, 15 Jun 2004\, Paul J Mooney wrote&#8203;:

> On 14 Jun 04\, at 19&#8203;:38\, Abe Timmerman via RT wrote&#8203;:
>
> >
> > I have just installed a fresh djgpp and followed the instructions in
> > README\.dos and got to this stage&#8203;:
> >
> >         Making DynaLoader \(static\)
> > Writing Makefile for DynaLoader
> > make\.exe\[1\]&#8203;: Entering directory
> > \`c&#8203;:/djgpp/home/abeltje/Test\-Smoke/perl\-current/ext/DynaLoader'
> > make\.exe\[1\]&#8203;: \*\*\* No rule to make target \`blibdirs\_exists'\, needed by
> > \`config'\. Stop\. make\.exe\[1\]&#8203;: Leaving directory

> > \-\-
> When I set up DJGPP to build\, I found that\, in addition to the files
> listed in the README\.dos file\, I needed to install these files as
> well&#8203;:
>              v2/djtzn203\.zip
>              v2gnu/lss374b\.zip
>
> I needed to installl djtzn203\.zip because configure called for time
> zone information in processing files' time and date stamps\.

Do you remember exactly which part of Configure needs that?  It's
certainly not intentional\.

> I needed to install lss374b\.zip \(less\.exe\) because configure queried
> for a lister program\.  Also\, the configur\.bat file in the \*\\perl\\djgpp
> directory had "\*\\djgpp\\bin\\less\.exe" as the lister\.
> Without lss\*\.zip\, configure would call\, as a default\, another lister
> program that I didn't even have installed \(I can't remember what that
> file was\, offhand\)\.  Even when I had less\.exe installed\, it would
> query for it\, saying that it wasn't installed\.  I replied to this query to
> accept it nonetheless\.  This seemed to work\.

You shouldn't need this either \-\- it's not used during either the
Configure or build process\, though various perl programs may well
look for $Config\{'pager'\}\.

> I also installed these files \(among others\)&#8203;:
> v2\\gpp333b\.zip
> v2gnu\\byacc19b\.zip
> v2gnu\\bsn135b\.zip
> Configure looked for these on my setup\.  They may help you to get
> past the stage that you are now\, at least\.
>
> If you want to run configure in non\-interactive mode\, with the \-des
> option\, I'd suggest that you install byacc19b\.zip\.  Configure called
> yacc \(byacc\) over bison \-y as a default\, even when byacc wasn't
> installed\.  This was another problem I had with configure\. I was
> able to straighten this one out\, so I was waiting until I had my
> current problem resolved \(when\, hopefully\, I could get perlbug up
> and running\!\) before reporting this and the other problems I had\.
> Thanks for your input\.  And best of luck\.

Although Configure looks for byacc\, it's not necessary\, except on EBCDIC
systems \(which is definitely not the case here\)\.  You should be able
to proceed without either byacc or bison\.

Not that any of this helps the original poster \.\.\. I don't recognize
that error message at all\.

\-\- 
&nbsp;    Andy Dougherty        doughera@&#8203;lafayette\.edu

**Comment by p5pRT** [comment]
### From pjmooney@panix.com



On 16 Jun 04\, at 14&#8203;:21\, Andy Dougherty via RT wrote&#8203;:

> On Tue\, 15 Jun 2004\, Paul J Mooney wrote&#8203;:
> 
> > I needed to installl djtzn203\.zip because configure called for time
> > zone information in processing files' time and date stamps\.
> 
> Do you remember exactly which part of Configure needs that?  It's
> certainly not intentional\.

As I recall\, it was at the beginning that Configure called for it\.

> 
> > I needed to install lss374b\.zip \(less\.exe\) because configure queried
> > for a lister program\.  Also\, the configur\.bat file in the
> > \*\\perl\\djgpp directory had "\*\\djgpp\\bin\\less\.exe" as the lister\.
> > Without lss\*\.zip\, configure would call\, as a default\, another lister
> > program that I didn't even have installed \(I can't remember what
> > that file was\, offhand\)\.  Even when I had less\.exe installed\, it
> > would query for it\, saying that it wasn't installed\.  I replied to
> > this query to accept it nonetheless\.  This seemed to work\.
> 
> You shouldn't need this either \-\- it's not used during either the
> Configure or build process\, though various perl programs may well look
> for $Config\{'pager'\}\.
> 
Okay\, but I just didn't like it when Configure was setting up with 
files that I didn't have installed\.  I chose less\.exe because it would 
be the most compatible pager with the Unix emulator\.  And\, as I 
stated before\, the configur\.bat file in the \*\\perl\\djgpp directory listed 
less\.exe as part of the setup in the comments\.  I was trying to get 
my build to work\, and I saw no reason not to\.

> > I also installed these files \(among others\)&#8203;:
> > v2\\gpp333b\.zip
> > v2gnu\\byacc19b\.zip
> > v2gnu\\bsn135b\.zip
> > Configure looked for these on my setup\.  They may help you to get
> > past the stage that you are now\, at least\.
> >
> 
> Although Configure looks for byacc\, it's not necessary\, except on
> EBCDIC systems \(which is definitely not the case here\)\.  You should be
> able to proceed without either byacc or bison\.
> 
All right\. But as I said before\, I couldn't get my build to work\, and I 
didn't know what else to do\.  It seemed worth a try\.

> Not that any of this helps the original poster \.\.\. I don't recognize
> that error message at all\.
> 
> \-\- 
>     Andy Dougherty        doughera@&#8203;lafayette\.edu
> 
> 
> 
Thanks for the input\.

Paul

**Comment by p5pRT** [comment]
### From pjmooney@panix.com

To whom it may concern&#8203;:
There was something else that I forgot to mention in my previous 
emails\.
Toward the end of the configure program's run\, there was an error 
message that appeared when it attempted to generate Perl's 
dependencies&#8203;:    
"Run make depend now? \[y\]  
make\.exe&#8203;: \*\*\* No rule to make target \`depend'\.  Stop\."
Also\, I tried to run "make depend" manually\, but that didn't work 
either\.  I hope that this sheds some light on the problem\. I 
apologize for not pointing this out earlier\, but I've been sidetracked 
by moving to a new apartment\, an illness\, and other things\.

Sincerely yours\,
Paul Mooney

**Comment by p5pRT** [comment]
### From @ysth

On Mon\, Mar 07\, 2005 at 02&#8203;:19&#8203;:32PM \-0500\, Paul J Mooney wrote&#8203;:
> To whom it may concern&#8203;:
> There was something else that I forgot to mention in my previous 
> emails\.
> Toward the end of the configure program's run\, there was an error 
> message that appeared when it attempted to generate Perl's 
> dependencies&#8203;:    
> "Run make depend now? \[y\]  
> make\.exe&#8203;: \*\*\* No rule to make target \`depend'\.  Stop\."
> Also\, I tried to run "make depend" manually\, but that didn't work 
> either\.  I hope that this sheds some light on the problem\. I 
> apologize for not pointing this out earlier\, but I've been sidetracked 
> by moving to a new apartment\, an illness\, and other things\.

Hmm\. It had sounded like you had got beyond this problem\, and on to
problems building extensions\.

Can you verify that Makefile\.SH \(run by Configure\) is indeed creating
a file named "Makefile"?  Is your make program perhaps looking by
default for some other name?  Try "make \-f Makefile depend" or
"make /f Makefile depend"\.

**Comment by p5pRT** [comment]
@chorny - Status changed from 'open' to 'stalled'

**Comment by ilmari** [comment]
With #19176 merged, the DOS/DJGPP port no longer exists, closing this issue.
