### ISSUE TITLE
METABUG - (?{...}) and (??{...}) regexp issues

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7802]
Migrated from [rt.perl.org#34161](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=34161) (status was 'open')

Searchable as RT34161$

**Comment by p5pRT** [comment]
### From @smpeters

This bug is a meta\-bug\.  It exists to serve as a parent ticket to the various
other tickets that are caused by various issues with the embedding Perl
code into regular expressions\.

**Comment by p5pRT** [comment]
@smpeters - Status changed from 'new' to 'open'

**Comment by khwilliamson** [comment]
This meta bug has zero tickets in it.  Do we keep it open and move things into it.  Another option is to close it and add a label to such tickets that would have come here

**Comment by jkeenan** [comment]
> This meta bug has zero tickets in it. Do we keep it open and move things into it. Another option is to close it and add a label to such tickets that would have come here

We can close it.  Give it a day or two to hear any objections, then proceed. Thanks.

**Comment by iabyn** [comment]
On Thu, Apr 14, 2022 at 05:25:18AM -0700, James E Keenan wrote:
> > This meta bug has zero tickets in it. Do we keep it open and move things into it. Another option is to close it and add a label to such tickets that would have come here
> 
> We can close it.  Give it a day or two to hear any objections, then proceed. Thanks.

+1

-- 
"Procrastination grows to fill the available time"
    -- Mitchell's corollary to Parkinson's Law
