### ISSUE TITLE
Win32: cannot create hard links on mounted network share

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#7963]
Migrated from [rt.perl.org#36232](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=36232) (status was 'open')

Searchable as RT36232$

**Comment by p5pRT** [comment]
### From mkoeppe@gmx.de

This is a bug report for perl from mkoeppe@gmx.de,
generated with the help of perlbug 1.35 running under perl v5.8.6.

With ActivePerl 5.8.6.811, creating a hard link on a local NTFS formatted
drive (Win2000) works as expected, but it fails on a mounted network share
(Win2003 server, of course the underlying filesystem is NTFS, too).

The hardlink can be created independantly of ActivePerl with Interix tools,
however, on both the local disk and on the mounted share as well.

Perl 5.8.7 doesn't fix this.

More details and a suggestion for a fix can be found on ActiveState's
bug number 39027 at
http://bugs.activestate.com/show_bug.cgi?id=39027

I first reported it there, but then found, that the responsible source
code can be found within
http://www.cpan.org/src/stable.tar.bz2
so it might not be solely related to ActiveState.

<details><summary>Perl Info</summary>

```
---
Flags:
category=core
severity=low
---
Site configuration information for perl v5.8.6:

Configured by ActiveState at Mon Dec 13 09:51:32 2004.

Summary of my perl5 (revision 5 version 8 subversion 6) configuration:
Platform:
osname=MSWin32, osvers=4.0, archname=MSWin32-x86-multi-thread
uname=''
config_args='undef'
hint=recommended, useposix=true, d_sigaction=undef
usethreads=define use5005threads=undef useithreads=define
usemultiplicity=define
useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
use64bitint=undef use64bitall=undef uselongdouble=undef
usemymalloc=n, bincompat5005=undef
Compiler:
cc='cl', ccflags ='-nologo -Gf -W3 -MD -Zi -DNDEBUG -O1 -DWIN32
-D_CONSOLE -DNO_STRICT -DHAVE_DES_FCRYPT -DNO_HASH_SEED
-DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO
-DPERL_MSVCRT_READFIX',
optimize='-MD -Zi -DNDEBUG -O1',
cppflags='-DWIN32'
ccversion='', gccversion='', gccosandvers=''
intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
d_longlong=undef, longlongsize=8, d_longdbl=define, longdblsize=10
ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='__int64',
lseeksize=8
alignbytes=8, prototype=define
Linker and Libraries:
ld='link', ldflags ='-nologo -nodefaultlib -debug -opt:ref,icf
-libpath:"C:\Perl\lib\CORE" -machine:x86'
libpth=\lib
libs= oldnames.lib kernel32.lib user32.lib gdi32.lib winspool.lib
comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib netapi32.lib
uuid.lib ws2_32.lib mpr.lib winmm.lib version.lib odbc32.lib odbccp32.lib
msvcrt.lib
perllibs= oldnames.lib kernel32.lib user32.lib gdi32.lib winspool.lib
comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib netapi32.lib
uuid.libws2_32.lib mpr.lib winmm.lib version.lib odbc32.lib odbccp32.lib
msvcrt.lib
libc=msvcrt.lib, so=dll, useshrplib=yes, libperl=perl58.lib
gnulibc_version='undef'
Dynamic Linking:
dlsrc=dl_win32.xs, dlext=dll, d_dlsymun=undef, ccdlflags=' '
cccdlflags=' ', lddlflags='-dll -nologo -nodefaultlib -debug
-opt:ref,icf -libpath:"C:\Perl\lib\CORE" -machine:x86'

Locally applied patches:
ACTIVEPERL_LOCAL_PATCHES_ENTRY
21540 Fix backward-compatibility issues in if.pm
23565 Wrong MANIFEST.SKIP

---
@INC for perl v5.8.6:
C:/Perl/lib
C:/Perl/site/lib
.

---
Environment for perl v5.8.6:
HOME (unset)
LANG (unset)
LANGUAGE (unset)
LD_LIBRARY_PATH=/usr/lib:/usr/X11R6/lib
LOGDIR (unset)

PATH=C:\Perl\bin\;C:\WINNT\system32;C:\WINNT;C:\WINNT\system32\WBEM;C:\SFU\common\;C:\SFU\Perl\bin\
PERL_BADLANG (unset)
SHELL (unset)
```
<details>

**Comment by p5pRT** [comment]
### From @smpeters



Have you tried the module Win32&#8203;::Hardlink?

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From mkoeppe@gmx.de


No\, I didn't know of it\. I now looked at it \(especially at the C source
of it\) and I think it's more or less useless\, as it duplicates the
functionality of the already builtin 'link' on Win32\.
Both use the Win32 API function CreateHardLink\, but this is the problem\!
Read my ActivePerl bug report 39027 for more details\.
 
Martin

**Comment by toddr** [comment]
Given the suggested fix is no longer accessible, I suggest closing this. It certainly sounds like a CPAN fix if nothing else.

**Comment by richardleach** [comment]
NTFS hard links under modern Windows are specifically same-volume only: https://docs.microsoft.com/en-us/windows/win32/fileio/hard-links-and-junctions

Perl should not be able to create a cross-volume hard link via the Windows API nowadays, so there's no action here to take.

**Comment by toddr** [comment]
Thank you!

**Comment by toddr** [comment]
@richardleach thanks. the close button should be available to you.
