### ISSUE TITLE
sysread in utf8 mode returns undefined result, but read input

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8184]
Migrated from [rt.perl.org#37585](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=37585) (status was 'open')

Searchable as RT37585$

**Comment by p5pRT** [comment]
### From jutta@pobox.com

#### Created by jutta@pobox.com



This has been seen on perl 5\.8\.7 and 5\.8\.6\.

I'm reading via a nonblocking binary TCP socket in "utf8" mode\,
using sysread\.

I'm reading a certain number of characters\.  If a server sends
me that exact number of \_bytes\_\, but fewer than that many \_characters\_
\-\- in other words\, if the server's data contains UTF\-8 characters
and happens to just have exactly my buffer size \-\-\, the sysread
returns with an undefined character count and errno set to EAGAIN\.

The buffer I pass in nevertheless contains the bytes read from 
the socket \- they're there\, it's just that sysread's return value
denies their existence\.

Instead of returning undefined\, sysread\(\)s result should reflect the
number of characters appended to the passed\-in buffer\, and the EAGAIN
should not be returned until the client's next attempt to read\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium

This perlbug was built using Perl v5.8.6 - Sat Mar 19 17:36:09 UTC 2005
It is being executed now by  Perl v5.8.6 - Sat Mar 19 17:31:24 UTC 2005.

Site configuration information for perl v5.8.6:

Configured by abuild at Sat Mar 19 17:31:24 UTC 2005.

Summary of my perl5 (revision 5 version 8 subversion 6) configuration:
  Platform:
    osname=linux, osvers=2.6.9, archname=x86_64-linux-thread-multi
    uname='linux bach 2.6.9 #1 smp fri jul 2 14:21:59 utc 2004 x86_64 x86_64 x86_64 gnulinux '
    config_args='-ds -e -Dprefix=/usr -Dvendorprefix=/usr -Dinstallusrbinperl -Dusethreads -Di_db -Di_dbm -Di_ndbm -Di_gdbm -Duseshrplib=true -Doptimize=-O2 -fmessage-length=0 -Wall -g -Wall -pipe'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=define use64bitall=define uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -DDEBUGGING -fno-strict-aliasing -pipe -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2 -fmessage-length=0 -Wall -g -Wall -pipe',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -DDEBUGGING -fno-strict-aliasing -pipe'
    ccversion='', gccversion='3.3.5 20050117 (prerelease) (SUSE Linux)', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib64'
    libpth=/lib64 /usr/lib64 /usr/local/lib64
    libs=-lm -ldl -lcrypt -lpthread
    perllibs=-lm -ldl -lcrypt -lpthread
    libc=/lib64//lib64/libc.so.6, so=so, useshrplib=true, libperl=libperl.so
    gnulibc_version='2.3.4'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E -Wl,-rpath,/usr/lib/perl5/5.8.6/x86_64-linux-thread-multi/CORE'
    cccdlflags='-fPIC', lddlflags='-shared -L/usr/local/lib64'

Locally applied patches:
    


@INC for perl v5.8.6:
    /usr/lib/perl5/5.8.6/x86_64-linux-thread-multi
    /usr/lib/perl5/5.8.6
    /usr/lib/perl5/site_perl/5.8.6/x86_64-linux-thread-multi
    /usr/lib/perl5/site_perl/5.8.6
    /usr/lib/perl5/site_perl
    /usr/lib/perl5/vendor_perl/5.8.6/x86_64-linux-thread-multi
    /usr/lib/perl5/vendor_perl/5.8.6
    /usr/lib/perl5/vendor_perl
    .


Environment for perl v5.8.6:
    HOME=/home/jutta
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH=/usr/X11R6/lib64:/usr/X11R6/lib
    LOGDIR (unset)
    PATH=/sbin:/usr/sbin:/home/jutta/shf:/sbin:/usr/sbin:/home/jutta/shf:/sbin:/usr/sbin:/home/jutta/shf:/sbin:/usr/sbin:/home/jutta/shf:/sbin:/usr/sbin:/home/jutta/shf:/sbin:/usr/sbin:/home/jutta/shf:/home/jutta/bin:/usr/local/bin:/usr/bin:/usr/X11R6/bin:/bin:/usr/games:/opt/gnome/bin:/opt/kde3/bin
    PERL_BADLANG (unset)
    SHELL=/bin/bash

--3D161130687.1130893811/jutta.metaweb.com--


```
</details>

**Comment by p5pRT** [comment]
### From @smpeters

> \[jutta@&#8203;pobox\.com \- Tue Nov 01 18&#8203;:57&#8203;:51 2005\]&#8203;:
> 
> 
> This is a bug report for perl from jutta@&#8203;pobox\.com\,
> generated with the help of perlbug 1\.35 running under perl v5\.8\.6\.
> 
> 
> \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> \[Please enter your report here\]
> 
> This has been seen on perl 5\.8\.7 and 5\.8\.6\.
> 
> I'm reading via a nonblocking binary TCP socket in "utf8" mode\,
> using sysread\.
> 
> I'm reading a certain number of characters\.  If a server sends
> me that exact number of \_bytes\_\, but fewer than that many \_characters\_
> \-\- in other words\, if the server's data contains UTF\-8 characters
> and happens to just have exactly my buffer size \-\-\, the sysread
> returns with an undefined character count and errno set to EAGAIN\.
> 
> The buffer I pass in nevertheless contains the bytes read from
> the socket \- they're there\, it's just that sysread's return value
> denies their existence\.
> 
> Instead of returning undefined\, sysread\(\)s result should reflect the
> number of characters appended to the passed\-in buffer\, and the EAGAIN
> should not be returned until the client's next attempt to read\.
> 

Would it be possible for you to send us some sample code that
demonstrates the problem?  It makes it difficult to replicate and test
the problem without it\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From jutta@panix.com

\[Steve Peters via RT\]
> > \[jutta@&#8203;pobox\.com \- Tue Nov 01 18&#8203;:57&#8203;:51 2005\]&#8203;:
> > 
> > 
> > This is a bug report for perl from jutta@&#8203;pobox\.com\,
> > generated with the help of perlbug 1\.35 running under perl v5\.8\.6\.
> > 
> > 
> > \-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
> > \[Please enter your report here\]
> > 
> > This has been seen on perl 5\.8\.7 and 5\.8\.6\.
> > 
> > I'm reading via a nonblocking binary TCP socket in "utf8" mode\,
> > using sysread\.
> > 
> > I'm reading a certain number of characters\.  If a server sends
> > me that exact number of \_bytes\_\, but fewer than that many \_characters\_
> > \-\- in other words\, if the server's data contains UTF\-8 characters
> > and happens to just have exactly my buffer size \-\-\, the sysread
> > returns with an undefined character count and errno set to EAGAIN\.
> > 
> > The buffer I pass in nevertheless contains the bytes read from
> > the socket \- they're there\, it's just that sysread's return value
> > denies their existence\.
> > 
> > Instead of returning undefined\, sysread\(\)s result should reflect the
> > number of characters appended to the passed\-in buffer\, and the EAGAIN
> > should not be returned until the client's next attempt to read\.
> > 
> 
> Would it be possible for you to send us some sample code that
> demonstrates the problem?  It makes it difficult to replicate and test
> the problem without it\.

Sure\.  Here's a little TCP server\, written in C\, and a perl
client\.  \(The server is probably a two\-line perl script\, but I
don't actually speak perl well enough to be really sure what's
going on\, so bear with me\.\)

This should compile under anything unixy \-\- save to foo\.c\, gcc \-o
foo foo\.c\, \./foo 1234 to start on port 1234 \(which is what the client
uses\.\)

================================= BEGIN =============================
\#include \<unistd\.h>
\#include \<stdlib\.h>
\#include \<stdio\.h>
\#include \<errno\.h>
\#include \<string\.h>
\#include \<sys/types\.h>
\#include \<sys/stat\.h>
\#include \<sys/socket\.h>
\#include \<arpa/inet\.h>
\#include \<netdb\.h>
\#include \<netinet/in\.h>
\#include \<fcntl\.h>
\#include \<assert\.h>

static int
setup\_listen\_sock\(char const \* interface\, short port\) \{

&nbsp;    int one = 1;
&nbsp;    int s;
&nbsp;    int rc;
&nbsp;    struct sockaddr\_in server;

&nbsp;    s = socket\(AF\_INET\, SOCK\_STREAM\, 0\);
&nbsp;    assert\(s \!= \-1\);

&nbsp;    memset\(&server\, 0\, sizeof\(server\)\);
&nbsp;    server\.sin\_family = AF\_INET;
&nbsp;    server\.sin\_port   = htons\(port\);
&nbsp;    if \(interface\)
&nbsp;            server\.sin\_addr\.s\_addr     = inet\_addr\(interface\);
&nbsp;    else     server\.sin\_addr\.s\_addr    = INADDR\_ANY;

&nbsp;    setsockopt\(s\, SOL\_SOCKET\, SO\_REUSEADDR\, \(void \*\)&one\, sizeof\(one\)\);

&nbsp;    umask\(0\);
&nbsp;    rc = bind\(s\, \(struct sockaddr \*\)&server\, sizeof\(server\)\);
&nbsp;    if \(rc == \-1\) \{
&nbsp;        close\(s\);
&nbsp;        return \-1;
&nbsp;    \}

&nbsp;    if \(listen\(s\, 100\) == \-1\) \{
&nbsp;        close\(s\);
&nbsp;        return \-1;
&nbsp;    \}
&nbsp;    return s;
\}

int main\(int ac\, char \*\*av\)
\{
&nbsp;    int         listener;
&nbsp;    int         conn;
&nbsp;    size\_t         len;
&nbsp;    struct sockaddr\_in client;
&nbsp;    short         port;
&nbsp;    char const    \* interface = NULL;

&nbsp;    if \(ac \< 2 || ac > 3\) \{
&nbsp;        fprintf\(stderr\, "usage&#8203;: %s port \[interface\]\\n"\, av\[0\]\);
&nbsp;        exit\(64\);
&nbsp;    \}

&nbsp;    port = atoi\(av\[1\]\);
&nbsp;    if \(ac > 2\)
&nbsp;        interface = av\[2\];

&nbsp;    listener = setup\_listen\_sock\(interface\, port\);
&nbsp;    if \(listener == \-1\) \{
&nbsp;        printf\("setup\_listen\_sock returned \-1&#8203;: %s\\n"\, strerror\(errno\)\);
&nbsp;        exit \(1\);
&nbsp;    \}

&nbsp;    memset\(&client\, 0\, sizeof\(client\)\);
&nbsp;    len = sizeof\(client\);

&nbsp;    while\(1\) \{
&nbsp;        /\* Twelve normal bytes\, followed by twelve bytes that include
&nbsp;         \* three encoding UCS \#2019\, an old\-fashioned apostrope\.  \*/

&nbsp;        static char const greeting\[\] =
&nbsp;             "0123456789a>we\\342\\200\\231re done";
&nbsp;        size\_t     greeting\_n = sizeof\(greeting\) \- 1;
&nbsp;        ssize\_t     cc;

&nbsp;        conn = accept\(
&nbsp;            listener\,
&nbsp;            \(struct sockaddr \*\)&client\, 
&nbsp;            \(socklen\_t \*\)&len\);
&nbsp;        assert\(conn \!= \-1\);
&nbsp;        cc = write\(conn\, greeting\, greeting\_n\);
&nbsp;        assert\(cc == greeting\_n\);

&nbsp;        /\* Pretend that with the first part of the protocol completed\,
&nbsp;         \* the application now waits for a reaction from the other
&nbsp;         \* side\.\.\.
&nbsp;         \*/
&nbsp;    \}
\}
================================= END =============================

And here's the perl "client" that reads in blocks of 12 UTF characters\.

================================= BEGIN =============================
\#\!/usr/bin/perl \-w

use strict;
use utf8;

\# constants
my\( $HOST \) = "localhost";
my\( $PORT \) = "1234";
my\( $BUFSIZE \) = "12";

\# libraries
use IO&#8203;::Socket;
use POSIX qw\(&#8203;:errno\_h\);

\# open a socket
my\( $socket \) =
&nbsp;    IO&#8203;::Socket&#8203;::INET\->
&nbsp;        new\( Proto => "tcp"\,
&nbsp;             PeerAddr => $HOST\,
&nbsp;             PeerPort => "gdb\(" \. $PORT \. "\)"\,
&nbsp;             Blocking => 0 \);


\# put the socket in UTF\-8 mode\.
binmode $socket\, "&#8203;:utf8";

my\( $retval\, $buffer \);

\# read from the socket\.

while \(1\) \{

&nbsp;    $retval = sysread\($socket\, $buffer\, $BUFSIZE\);

&nbsp;    if \( \!defined\($retval\) && \( $\! == EAGAIN \)\)
&nbsp;    \{
&nbsp;        print "read failed&#8203;: "\, $\!\, "\\r\\n";
&nbsp;        print "\(buffer is&#8203;: '"\, $buffer\, "'\)\\r\\n";
&nbsp;        last;
&nbsp;    \}
&nbsp;    if \( $retval == 0 \) \{ last; \}

&nbsp;    print "read&#8203;: "\, $retval\, "\, buffer&#8203;: '"\, $buffer\, "'\\r\\n";
\}

exit 0;
================================= END =============================

The client's socket is set to is non\-blocking\.  So\, if\, as in
the second case\, fewer than 12 UTF\-8 characters are available
\(namely\, 10\)\, I'd expect to simply be returned those ten \-\- with
the next read returning EAGAIN\.

If you replace the UTF8 apostrophe from the server data wtih a
simple us\-ascii '\, that's exactly what happens \-\-

&nbsp;    \./test\.pl
&nbsp;    read&#8203;: 12\, buffer&#8203;: '0123456789a>'
&nbsp;    read&#8203;: 10\, buffer&#8203;: 'we're done'
&nbsp;    read failed&#8203;: Resource temporarily unavailable
&nbsp;    \(buffer is&#8203;: 'we're done'\)

And if you make the text just one byte shorter or longer \(E\.g\. write
"we're ok\." or "we're done\." rather than "we're done"\)\,
that's exactly what happens\-\-

&nbsp;    \./test\.pl
&nbsp;    read&#8203;: 12\, buffer&#8203;: 0123456789a>'
&nbsp;    Wide character in print at \./test\.pl line 45\.
&nbsp;    read&#8203;: 9\, buffer&#8203;: weâre ok\.'
&nbsp;    read failed&#8203;: Resource temporarily unavailable
&nbsp;    Wide character in print at \./test\.pl line 39\.
&nbsp;    \(buffer is&#8203;: weâre ok\.\)

and
&nbsp;    \./test\.pl
&nbsp;    read&#8203;: 12\, buffer&#8203;: 0123456789a>'
&nbsp;    Wide character in print at \./test\.pl line 45\.
&nbsp;    read&#8203;: 11\, buffer&#8203;: weâre done\.'
&nbsp;    read failed&#8203;: Resource temporarily unavailable
&nbsp;    Wide character in print at \./test\.pl line 39\.
&nbsp;    \(buffer is&#8203;: weâre done\.\)

it's only if there's an UTF\-8 character present and the \_byte\_ \-\-
not character \-\- count hits the buffer size exactly that the error
result from the second "refill" UTF8 read inside sysread
implementation somehow overrides the partial results from
the first read&#8203;:

&nbsp;    \./utf8read\.pl
&nbsp;    read&#8203;: 12\, buffer&#8203;: '0123456789a>'
&nbsp;    read failed&#8203;: Resource temporarily unavailable
&nbsp;    \(buffer is&#8203;: 'we\\xe2\\x80\\x99re done'\)

Note that the characters did "make it" into the buffer\, it's
just that the return value doesn't count them\.

Hope this reproduces on your system and helps explain what's
going on\-\-let me know if you need more\.

Cheers\,

Jutta \<jutta@&#8203;pobox\.com>

**Comment by Leont** [comment]
`sysread` and `syswrite` are no longer allowed on `:utf8` handles, so this ticket can be closed.
