### ISSUE TITLE
DynaLoader corrupts %ENV

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8505]
Migrated from [rt.perl.org#39647](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=39647) (status was 'stalled')

Searchable as RT39647$

**Comment by p5pRT** [comment]
### From occitan@t-online.de

This is a bug report for perl from occitan@&#8203;esperanto\.org\,
generated with the help of perlbug 1\.35 running under perl v5\.8\.7\.




---
Using Term&#8203;::ReadLine&#8203;::Gnu the assignment to ENV gives&#8203;:

$ perl \-MTerm&#8203;::ReadLine \-e 'new Term&#8203;::ReadLine; $ENV\{GOGO1\} = "fffff"'
Out of memory\!

Term&#8203;::ReadLine&#8203;::Gnu was compiled the official way\.  We actually found
this bug with a big Swig generated Library\.  There it is enough to
invoke DynaLoader's bootstrap before assigning to %ENV to trigger this
error\.  Our own library was compiled by picking the relevant stuff out
of %Config\.

In both cases we definitely used the Perl executable described below\,
both for the build and the execution\.  However I tried doing the same
thing \(\-M and call a function to trigger autoloading\) with many of the
standard Modules which require DynaLoader\, and none had this bug\.

Some versions of our evolving own library have this\, and others do not\. 
But a given setup will reproducably give this error\.  Unlike the %ENV
extract perlbug generated\, here is the exact env I have whittled this
down to\.  For the example above\, it doesn't matter what is in the
variables\, but if I unset one more\, the error goes away&#8203;:

$ env
A=
B=
C=
HOME=/home/dpfeiff
PATH=/usr/local/bin&#8203;:/bin&#8203;:/usr/bin
TERM=xterm
$ uname \-a
SunOS fraurauscher1 5\.10 Generic\_118833\-03 sun4u sparc
SUNW\,Sun\-Fire\-V890

We strongly think that we once had this with ActiveState Perl\, but
cannot easily verify that\, since we have since migrated to a self
compiled one\.



---


---
Flags&#8203;:
&nbsp;    category=library
&nbsp;    severity=critical


---
Site configuration information for perl v5\.8\.7&#8203;:

Summary of my perl5 \(revision 5 version 8 subversion 7\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=solaris\, osvers=2\.10\, archname=sun4\-solaris
&nbsp;    uname='sunos 5\.10 s10\_60 sun4u sparc sunw\,ultra\-5\_10 '
&nbsp;    config\_args='\-Dcc=gcc \-B/usr/ccs/bin/'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=undef use5005threads=undef useithreads=undef
usemultiplicity=undef
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc \-B/usr/ccs/bin/'\, ccflags ='\-fno\-strict\-aliasing \-pipe
\-I/usr/local/include \-D\_LARGEFILE\_SOURCE \-D\_FILE\_OFFSET\_BITS=64'\,
&nbsp;    optimize='\-O'\,
&nbsp;    cppflags='\-fno\-strict\-aliasing \-pipe \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='2\.95\.3 20010315 \(release\)'\,
gccosandvers='solaris2\.10'
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=4321
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\,
lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='gcc \-B/usr/ccs/bin/'\, ldflags =' \-L/usr/local/lib '
&nbsp;    libpth=/usr/local/lib /usr/lib /usr/ccs/lib
&nbsp;    libs=\-lsocket \-lnsl \-ldl \-lm \-lc
&nbsp;    perllibs=\-lsocket \-lnsl \-ldl \-lm \-lc
&nbsp;    libc=/lib/libc\.so\, so=so\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=so\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags='\-fPIC'\, lddlflags='\-G \-L/usr/local/lib'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl v5\.8\.7&#8203;:
&nbsp;    /usr/local/lib/perl5/5\.8\.7/sun4\-solaris
&nbsp;    /usr/local/lib/perl5/5\.8\.7
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.8\.7/sun4\-solaris
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.8\.7
&nbsp;    /usr/local/lib/perl5/site\_perl
&nbsp;    \.



---
Environment for perl v5\.8\.7&#8203;:
&nbsp;    HOME=/home/dpfeiff
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/usr/local/bin&#8203;:/bin&#8203;:/usr/bin
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL \(unset\)

**Comment by p5pRT** [comment]
### From @rgs

occitan@&#8203;t\-online\.de wrote&#8203;:
> Using Term&#8203;::ReadLine&#8203;::Gnu the assignment to ENV gives&#8203;:
> 
> $ perl \-MTerm&#8203;::ReadLine \-e 'new Term&#8203;::ReadLine; $ENV\{GOGO1\} = "fffff"'
> Out of memory\!

I don't reproduce this on linux\, either with 5\.8\.7\, 5\.8\.8 or bleadperl\,
with a similar configuration \(no threads\, usemymalloc=n\) with and
without Term&#8203;::ReadLine&#8203;::Gnu installed\. Maybe I missed something\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From occitan@esperanto.org

la 28\.06\.2006 11&#8203;:32 Rafael Garcia\-Suarez via RT skribis&#8203;:
> occitan@&#8203;t\-online\.de wrote&#8203;:
>   
>> Using Term&#8203;::ReadLine&#8203;::Gnu the assignment to ENV gives&#8203;:
>>
>> $ perl \-MTerm&#8203;::ReadLine \-e 'new Term&#8203;::ReadLine; $ENV\{GOGO1\} = "fffff"'
>> Out of memory\!
>>     
>
> I don't reproduce this on linux\, either with 5\.8\.7\, 5\.8\.8 or bleadperl\,
> with a similar configuration \(no threads\, usemymalloc=n\) with and
> without Term&#8203;::ReadLine&#8203;::Gnu installed\. Maybe I missed something\.
Nor do I\, only on Solaris\.  IIRC\, when building perl myself many years 
ago\, I was given a choice of DynaLoad mechanisms and had a hard time to 
get it running\.  Since the contents of the loaded library decide whether 
this happens or not\, maybe there is some memory overwriting happening\, 
the effect of which depends on the precise layout of the library \-\- and 
probably on the dl mechanism\.

I also forgot to mention that I trussed \(that's strace for Linuxers\) the 
programm\, and no system calls were failing \(besides a few irrelevant 
ENOENTs while searching for files\)\.  So that would suggest that an 
internal malloc wrapper is failing\.

coralament / best Grötens / liebe Grüße / best regards / elkorajn salutojn
Daniel Pfeiffer

\-\- 
lerne / learn / apprends / lär dig / ucz się    Esperanto&#8203;:
&nbsp;                    http&#8203;://lernu\.net  /  http&#8203;://ikurso\.net

**Comment by p5pRT** [comment]
### From @rgarcia

On 28/06/06\, Daniel Pfeiffer \<dapfy@&#8203;t\-online\.de> wrote&#8203;:
> I also forgot to mention that I trussed \(that's strace for Linuxers\) the
> programm\, and no system calls were failing \(besides a few irrelevant
> ENOENTs while searching for files\)\.  So that would suggest that an
> internal malloc wrapper is failing\.

But your perl uses the system's malloc\. \(like mine\)
You could try to compile a perl configured with \-Dusemymalloc to see
if you have the same problem with perl's builtin malloc\.

> coralament / best Grötens / liebe Grüße / best regards / elkorajn salutojn

Cordialement\,
\-\-

**Comment by p5pRT** [comment]
### From dapfy@t-online.de

Well\, due to the loading of binary libs we have to have the identical perl in dev\, test and production\, which is pretty much beyond our control :\-\(  That's why we moved away from ActiveState\, which for esoteric reasons is not tolerated as a production platform\.\.\.

The thing is that this error seems to be a moving target\, so it's dissapperance would only prove that we are currently not seeing it\.  And if it comes back later\, once we're in production\, it would really bite us\.

We have tried debugging it\, but it's a stripped perl\, which is not very helpful\.  If you think you could make something out of it on Sparc Solaris\, I could send you the perl and its libs\.

**Comment by p5pRT** [comment]
### From dapfy@t-online.de

Hi\,

In trying to get a different tack at this problem\, instead of our
homebuilt one\, I just installed
ActivePerl\-5\.8\.8\.817\-sun4\-solaris\-2\.6\-cc\-257965 to ~/perl\.  When trying
to install Term&#8203;::ReadLine&#8203;::Gnu to it\, I already get the out of memory in
one of the tests\.

If I install it nevertheless\, the test I originally posted also gives
this error\.  So it's not the build method \(our perl is definitely not
binary compatible with ActiveState's\, so they must have some different
compiler
options\) nor the version\, as we get this on 5\.8\.7 and 5\.8\.8\.

Since ActiveState is not compiled for debug either\, I compiled 5\.8\.8
from scratch with default options \(but for debug and prefix\)\.  As I had
feared\, the error went away\.  Just to double check\, I rebuilt 5\.8\.8 from
scratch once more without debug\.  Still no error\.

So it seems that it is possible to compile perl in such a way that even
a Makefile\.PL based installation leads to a broken DynaLoader\.  This bug
has cost us a lot of time\, so it would be great if somebody could figure
out from my posted \(or ActiveState's\) perl \-V output\, how things can go
so broken\!  We're fine now\, but others might fall into the same trap\.

best regards
Daniel

\-\-\-\-\-Original Message\-\-\-\-\-
Date&#8203;: Thu\, 29 Jun 2006 15&#8203;:38&#8203;:59 \+0200
Subject&#8203;: Re&#8203;: \[perl \#39647\] DynaLoader corrupts %ENV
From&#8203;: "dapfy@&#8203;t\-online\.de" \<dapfy@&#8203;t\-online\.de>
To&#8203;: perlbug\-followup@&#8203;perl\.org

Well\, due to the loading of binary libs we have to have the identical
perl in dev\, test and production\, which is pretty much beyond our
control :\-\(  That's why we moved away from ActiveState\, which for
esoteric reasons is not tolerated as a production platform\.\.\.

The thing is that this error seems to be a moving target\, so it's
dissapperance would only prove that we are currently not seeing it\.  And
if it comes back later\, once we're in production\, it would really bite
us\.

We have tried debugging it\, but it's a stripped perl\, which is not very
helpful\.  If you think you could make something out of it on Sparc
Solaris\, I could send you the perl and its libs\.

**Comment by p5pRT** [comment]
p5p@spam.wizbit.be - Status changed from 'open' to 'stalled'

**Comment by toddr** [comment]
Given the age of this case, I recommend this case be closed as not reproducible. The reporter's email isn't even reachable at this point.
