### ISSUE TITLE
Data::Dumper crashing on filehandle type via CGI upload

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8588]
Migrated from [rt.perl.org#40298](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=40298) (status was 'stalled')

Searchable as RT40298$

**Comment by p5pRT** [comment]
### From michael_soulier@mitel.com

I am using CGI&#8203;::Persistent in a CGI file upload\. It appears to be trying
to serialize the session to a file using Data&#8203;::Dumper\, via
Persistence&#8203;::Object&#8203;::Simple\.

\# line 125 in Simple\.pm
&nbsp;    print \{ $locked\_fh ? $locked\_fh : $fh \}
&nbsp;    defined &Data&#8203;::Dumper&#8203;::Dumpxs ? $d\->Dumpxs\(\) : $d\->Dump\(\);

On our configuration\, on CentOS 4\.3 with

This is perl\, v5\.8\.5 built for i386\-linux\-thread\-multi

even though I have an eval block around the code to catch any fatal
exceptions\, my catch \(an if $@&#8203;\) isn't called\, so I can only assume that
the interpreter itself is crashing in the Dumpxs code\.

If I drop the eval\, then I see the error itself as

"Can't coerce GLOB to string in entersub at
/usr/lib/perl5/site\_perl/5\.8\.0/Persistence/Object/Simple\.pm line 125\."

Through my experimentation\, I've been able to workaround the problem if
I patch P&#8203;::O&#8203;::S and D&#8203;::D\, like so

\-\-\- /usr/lib/perl5/site\_perl/5\.8\.0/Persistence/Object/Simple\.pm\.orig
2006\-09\-07 05&#8203;:54&#8203;:02\.000000000 \-0400
\+\+\+ /usr/lib/perl5/site\_perl/5\.8\.0/Persistence/Object/Simple\.pm
2006\-09\-07 05&#8203;:55&#8203;:26\.000000000 \-0400
@&#8203;@&#8203; \-122\,8 \+122\,10 @&#8203;@&#8203;
&nbsp;         \}
&nbsp;     \}

\+    \#print \{ $locked\_fh ? $locked\_fh : $fh \}
\+\#      defined &Data&#8203;::Dumper&#8203;::Dumpxs ? $d\->Dumpxs\(\) : $d\->Dump\(\);
&nbsp;     print \{ $locked\_fh ? $locked\_fh : $fh \}
\-       defined &Data&#8203;::Dumper&#8203;::Dumpxs ? $d\->Dumpxs\(\) : $d\->Dump\(\);
\+       $d\->Dump\(\);
&nbsp;     close $fh if $fh;

&nbsp;     if \( ref $self \) \{

\-\-\- /usr/lib/perl5/5\.8\.5/i386\-linux\-thread\-multi/Data/Dumper\.pm\.orig
2006\-09\-07 05&#8203;:54&#8203;:06\.000000000 \-0400
\+\+\+ /usr/lib/perl5/5\.8\.5/i386\-linux\-thread\-multi/Data/Dumper\.pm
2006\-09\-07 05&#8203;:55&#8203;:46\.000000000 \-0400
@&#8203;@&#8203; \-155\,10 \+155\,10 @&#8203;@&#8203;
 sub DESTROY \{\}

 sub Dump \{
\-    return &Dumpxs
\-       unless $Data&#8203;::Dumper&#8203;::Useperl || \(ref\($\_\[0\]\) && $\_\[0\]\->\{useperl\}\) ||
\-              $Data&#8203;::Dumper&#8203;::Useqq   || \(ref\($\_\[0\]\) && $\_\[0\]\->\{useqq\}\) ||
\-              $Data&#8203;::Dumper&#8203;::Deparse || \(ref\($\_\[0\]\) && $\_\[0\]\->\{deparse\}\);
\+    \#return &Dumpxs
\+\#      unless $Data&#8203;::Dumper&#8203;::Useperl || \(ref\($\_\[0\]\) && $\_\[0\]\->\{useperl\}\) ||
\+\#             $Data&#8203;::Dumper&#8203;::Useqq   || \(ref\($\_\[0\]\) && $\_\[0\]\->\{useqq\}\) ||
\+\#             $Data&#8203;::Dumper&#8203;::Deparse || \(ref\($\_\[0\]\) && $\_\[0\]\->\{deparse\}\);
&nbsp;     return &Dumpperl;
 \}

@&#8203;@&#8203; \-172\,6 \+172\,8 @&#8203;@&#8203;
&nbsp;   my\($i\) = 0;
&nbsp;   local\(@&#8203;post\);

\+  warn "in \_dump&#8203;: \\$s = $s\, \\$val = $val\, \\$name = $name\\n";
\+
&nbsp;   $s = $s\->new\(@&#8203;\_\) unless ref $s;

&nbsp;   for $val \(@&#8203;\{$s\->\{todump\}\}\) \{

So essentially\, I force the Dumpperl version instead of the XS\, and then
I stringify the incoming variables\. This apparently initializes
something internally to the perl interpreter\, which prevents the crash\,
and my upload dialog works fine\.

Regards\,
Mike
\-\- 
Michael P\. Soulier \<michael\_soulier@&#8203;mitel\.com>\, 613\-592\-2122 x2522
"Any intelligent fool can make things bigger and more complex\.\.\. It
takes a touch of genius \- and a lot of courage to move in the opposite
direction\." \-\-Albert Einstein

**Comment by p5pRT** [comment]
### From @smpeters

On Thu Sep 07 09&#8203;:28&#8203;:52 2006\, michael\_soulier@&#8203;mitel\.com wrote&#8203;:
> I am using CGI&#8203;::Persistent in a CGI file upload\. It appears to be trying
> to serialize the session to a file using Data&#8203;::Dumper\, via
> Persistence&#8203;::Object&#8203;::Simple\.
> 
> \# line 125 in Simple\.pm
>     print \{ $locked\_fh ? $locked\_fh : $fh \}
>     defined &Data&#8203;::Dumper&#8203;::Dumpxs ? $d\->Dumpxs\(\) : $d\->Dump\(\);
> 
> On our configuration\, on CentOS 4\.3 with
> 
> This is perl\, v5\.8\.5 built for i386\-linux\-thread\-multi
> 
> even though I have an eval block around the code to catch any fatal
> exceptions\, my catch \(an if $@&#8203;\) isn't called\, so I can only assume that
> the interpreter itself is crashing in the Dumpxs code\.
> 
> If I drop the eval\, then I see the error itself as
> 
> "Can't coerce GLOB to string in entersub at
> /usr/lib/perl5/site\_perl/5\.8\.0/Persistence/Object/Simple\.pm line 125\."
> 
> Through my experimentation\, I've been able to workaround the problem if
> I patch P&#8203;::O&#8203;::S and D&#8203;::D\, like so
> 
> \-\-\- /usr/lib/perl5/site\_perl/5\.8\.0/Persistence/Object/Simple\.pm\.orig
> 2006\-09\-07 05&#8203;:54&#8203;:02\.000000000 \-0400
> \+\+\+ /usr/lib/perl5/site\_perl/5\.8\.0/Persistence/Object/Simple\.pm
> 2006\-09\-07 05&#8203;:55&#8203;:26\.000000000 \-0400
> @&#8203;@&#8203; \-122\,8 \+122\,10 @&#8203;@&#8203;
>          \}
>      \}
> 
> \+    \#print \{ $locked\_fh ? $locked\_fh : $fh \}
> \+\#      defined &Data&#8203;::Dumper&#8203;::Dumpxs ? $d\->Dumpxs\(\) : $d\->Dump\(\);
>      print \{ $locked\_fh ? $locked\_fh : $fh \}
> \-       defined &Data&#8203;::Dumper&#8203;::Dumpxs ? $d\->Dumpxs\(\) : $d\->Dump\(\);
> \+       $d\->Dump\(\);
>      close $fh if $fh;
> 
>      if \( ref $self \) \{
> 
> \-\-\- /usr/lib/perl5/5\.8\.5/i386\-linux\-thread\-multi/Data/Dumper\.pm\.orig
> 2006\-09\-07 05&#8203;:54&#8203;:06\.000000000 \-0400
> \+\+\+ /usr/lib/perl5/5\.8\.5/i386\-linux\-thread\-multi/Data/Dumper\.pm
> 2006\-09\-07 05&#8203;:55&#8203;:46\.000000000 \-0400
> @&#8203;@&#8203; \-155\,10 \+155\,10 @&#8203;@&#8203;
>  sub DESTROY \{\}
> 
>  sub Dump \{
> \-    return &Dumpxs
> \-       unless $Data&#8203;::Dumper&#8203;::Useperl || \(ref\($\_\[0\]\) &&
$\_\[0\]\->\{useperl\}\) ||
> \-              $Data&#8203;::Dumper&#8203;::Useqq   || \(ref\($\_\[0\]\) && $\_\[0\]\->\{useqq\}\) ||
> \-              $Data&#8203;::Dumper&#8203;::Deparse || \(ref\($\_\[0\]\) && $\_\[0\]\->\{deparse\}\);
> \+    \#return &Dumpxs
> \+\#      unless $Data&#8203;::Dumper&#8203;::Useperl || \(ref\($\_\[0\]\) &&
$\_\[0\]\->\{useperl\}\) ||
> \+\#             $Data&#8203;::Dumper&#8203;::Useqq   || \(ref\($\_\[0\]\) && $\_\[0\]\->\{useqq\}\) ||
> \+\#             $Data&#8203;::Dumper&#8203;::Deparse || \(ref\($\_\[0\]\) && $\_\[0\]\->\{deparse\}\);
>      return &Dumpperl;
>  \}
> 
> @&#8203;@&#8203; \-172\,6 \+172\,8 @&#8203;@&#8203;
>    my\($i\) = 0;
>    local\(@&#8203;post\);
> 
> \+  warn "in \_dump&#8203;: \\$s = $s\, \\$val = $val\, \\$name = $name\\n";
> \+
>    $s = $s\->new\(@&#8203;\_\) unless ref $s;
> 
>    for $val \(@&#8203;\{$s\->\{todump\}\}\) \{
> 
> So essentially\, I force the Dumpperl version instead of the XS\, and then
> I stringify the incoming variables\. This apparently initializes
> something internally to the perl interpreter\, which prevents the crash\,
> and my upload dialog works fine\.
> 

Is there any way you can provide a simplified test case so that we can
actually examine the problem?  Also\, the Perl you are using \(5\.8\.0\) is
amazingly over four years old\.  Any chance you could try with a newer
Perl to see if the bug has already been fixed?

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From michael_soulier@mitel.com

Steve Peters via RT wrote&#8203;:

> Is there any way you can provide a simplified test case so that we can
> actually examine the problem?  Also\, the Perl you are using \(5\.8\.0\) is
> amazingly over four years old\.  Any chance you could try with a newer
> Perl to see if the bug has already been fixed?

We're using Perl 5\.8\.5\, but thanks to RedHat we have 5\.8\.0 paths on the
system\. I included the perl version in the report\.

I tried a backport of 5\.8\.8 but a ton of things broke and I wasn't able
to test the app in question\. CGI&#8203;::Persistent broke on me\, unable to
compose filenames correctly\. I'd likely have to upgrade that too\, and
rebuild a bunch of modules against 5\.8\.8 to get them working\.

I'll try to supply a simple CGI that uses this and tickles the problem\.
Tuits needed\.

Mike
\-\- 
Michael P\. Soulier \<michael\_soulier@&#8203;mitel\.com>\, 613\-592\-2122 x2522
"Any intelligent fool can make things bigger and more complex\.\.\. It
takes a touch of genius \- and a lot of courage to move in the opposite
direction\." \-\-Albert Einstein

**Comment by p5pRT** [comment]
### From michael_soulier@mitel.com

Steve Peters via RT wrote&#8203;:
> Is there any way you can provide a simplified test case so that we can
> actually examine the problem?  Also\, the Perl you are using \(5\.8\.0\) is
> amazingly over four years old\.  Any chance you could try with a newer
> Perl to see if the bug has already been fixed?

I was not able to reproduce this in a simple example\. It apparently has
to do with the interaction of several of the modules in our FormMagick
framework\. The ultimate culprit was Data&#8203;::Dumper\, with the Dumpxs call
causing the Perl interpreter to crash\.

Forcing the Dumpperl subroutine instead\, I can at least catch the
exception\.

I am attaching patches to CGI&#8203;::Persistent and Object&#8203;::Persistence that
seem to work around the issue\.

I tried upgrading but churn in CGI&#8203;::Persistent prevented me from testing
at all\, as much of how the sessions are stored has changed\.

Cheers\,
Mike
\-\- 
Michael P\. Soulier \<michael\_soulier@&#8203;mitel\.com>\, 613\-592\-2122 x2522
"Any intelligent fool can make things bigger and more complex\.\.\. It
takes a touch of genius \- and a lot of courage to move in the opposite
direction\." \-\-Albert Einstein

**Comment by p5pRT** [comment]
### From michael_soulier@mitel.com

<details><summary>Inline Patch</summary>

```diff
diff -Nur -x '*.orig' -x '*.rej' CGI-Persistent-0.22/lib/CGI/Persistent.pm mezzanine_patched_CGI-Persistent-0.22/lib/CGI/Persistent.pm
--- CGI-Persistent-0.22/lib/CGI/Persistent.pm	2006-09-13 13:51:47.292925000 -0400
+++ mezzanine_patched_CGI-Persistent-0.22/lib/CGI/Persistent.pm	2006-09-13 13:51:40.122767000 -0400
@@ -48,6 +48,13 @@
 
     $cgi->{sessiondir} = $po->{sessiondir};
 
+    # Stringify the params. This is black magic to work around an interpreter
+    # crash in Data::Dumper.
+    foreach my $param ($cgi->param)
+    {
+        my $s = "param $param is " . $cgi->param($param) . "\n";
+    }
+
     $po->commit ();
     return bless $cgi, $class; 
 
```
</details>

**Comment by p5pRT** [comment]
### From michael_soulier@mitel.com

<details><summary>Inline Patch</summary>

```diff
diff -Nur -x '*.orig' -x '*.rej' Object-Persistence-0.92/lib/Persistence/Object/Simple.pm mezzanine_patched_Object-Persistence-0.92/lib/Persistence/Object/Simple.pm
--- Object-Persistence-0.92/lib/Persistence/Object/Simple.pm	Wed Sep 13 13:33:09 2006
+++ mezzanine_patched_Object-Persistence-0.92/lib/Persistence/Object/Simple.pm	Wed Sep 13 13:31:50 2006
@@ -119,8 +119,7 @@
         }
     } 
 
-    print { $locked_fh ? $locked_fh : $fh } 
-	defined &Data::Dumper::Dumpxs ? $d->Dumpxs() : $d->Dump(); 
+    print { $locked_fh ? $locked_fh : $fh } $d->Dumpperl();
     close $fh if $fh; 
 
     if ( ref $self ) { 
```
</details>

**Comment by p5pRT** [comment]
p5p@spam.wizbit.be - Status changed from 'open' to 'stalled'

**Comment by richardleach** [comment]
This ticket hasn't seen any action in over 13 years. In that time:

-  CGI has been ejected from core
- CGI::Persistent has incorporated Michael's patch above. (Present in 1.11 release: https://metacpan.org/release/CGI-Persistent/source/lib/CGI/Persistent.pm)

Persistence::Object::Simple hasn't incorporated the second patch, but this module isn't in core either.

Given the above, and the absence of an available test case, can this ticket be closed?

**Comment by atoomic** [comment]
seems legit to close
