### ISSUE TITLE
MSWin32: can't disable crlf trans. on STDxxx using :raw or binmode

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8688]
Migrated from [rt.perl.org#40964](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=40964) (status was 'open')

Searchable as RT40964$

**Comment by p5pRT** [comment]
### From vaclav.ovsik@i.cz

This is a bug report for perl from zito@&#8203;bobekw\,
generated with the help of perlbug 1\.35 running under perl v5\.8\.8\.

Hello\,
i compiled perl 5\.8\.8 on win32 in a standard way using
MSVC6 \(with service pack 6 and PSDK\) on Windows XP\.
All tests passed after compilation\.

I found\, that I can't disable lf \<\-> crlf translations
using layer \`raw' nor using binmode on filehandle
of STDOUT or STDERR \(STDIN not tested\)\. Newly opened
files are ok\.

\(Tests are run on cygwin prompt\, but without cygwins perl\.
Native perl is on the PATH\.\)


&nbsp;    zito@&#8203;bobekw&#8203;:\~$ mytest\(\) \{
&nbsp;    > perl \-e 'print "\\n";' |xxd
&nbsp;    > perl \-e 'print join\("\, "\, PerlIO&#8203;::get\_layers\(STDOUT\)\)\, "\\n";'
&nbsp;    > \}


&nbsp;    zito@&#8203;bobekw&#8203;:\~$ mytest
&nbsp;    0000000&#8203;: 0d0a                                     \.\.
&nbsp;    unix\, crlf
Ok

&nbsp;    zito@&#8203;bobekw&#8203;:\~$ PERLIO='&#8203;:raw' mytest
&nbsp;    0000000&#8203;: 0d0a                                     \.\.
&nbsp;    unix
Bug?

&nbsp;    zito@&#8203;bobekw&#8203;:\~$ PERLIO='&#8203;:stdio' mytest
&nbsp;    0000000&#8203;: 0d0a                                     \.\.
&nbsp;    stdio
Bug?

&nbsp;    zito@&#8203;bobekw&#8203;:\~$ PERLIO='&#8203;:perlio' mytest
&nbsp;    0000000&#8203;: 0a                                       \.
&nbsp;    unix\, perlio
Ok?
Interesting\! Layer unix alone produces crlf\,
but unix\+perlio behaves ok?

&nbsp;    zito@&#8203;bobekw&#8203;:\~$ PERLIO='&#8203;:win32' mytest
&nbsp;    0000000&#8203;: 0a                                       \.
&nbsp;    win32
Ok

Layer win32 is considered experimental in PerlIO pod\, so should
I workaround problem with perlio? Is it safe?

Thanks for any comments on this\.
Maybe\, I misuderstood something\.
\-\- 
Vaclav Ovsik



---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=low


---
Site configuration information for perl v5\.8\.8&#8203;:

Configured by zito at Wed Nov  1 18&#8203;:05&#8203;:58 2006\.

Summary of my perl5 \(revision 5 version 8 subversion 8\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=MSWin32\, osvers=5\.1\, archname=MSWin32\-x86\-multi\-thread
&nbsp;    uname=''
&nbsp;    config\_args='undef'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=undef
&nbsp;    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cl'\, ccflags ='\-nologo \-Gf \-W3 \-MD \-Zi \-DNDEBUG \-O1 \-DWIN32 \-D\_CONSOLE \-DNO\_STRICT \-DHAVE\_DES\_FCRYPT  \-DPERL\_IMPLICIT\_CONTEXT \-DPERL\_IMPLICIT\_SYS \-DUSE\_PERLIO \-DPERL\_MSVCRT\_READFIX'\,
&nbsp;    optimize='\-MD \-Zi \-DNDEBUG \-O1'\,
&nbsp;    cppflags='\-DWIN32'
&nbsp;    ccversion='12\.00\.8168'\, gccversion=''\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=undef\, longlongsize=8\, d\_longdbl=define\, longdblsize=10
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='\_\_int64'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='link'\, ldflags ='\-nologo \-nodefaultlib \-debug \-opt&#8203;:ref\,icf  \-libpath&#8203;:"d&#8203;:\\perl\\lib\\CORE"  \-machine&#8203;:x86'
&nbsp;    libpth=C&#8203;:\\PROGRA~1\\MICROS~2\\VC98\\lib
&nbsp;    libs=  oldnames\.lib kernel32\.lib user32\.lib gdi32\.lib winspool\.lib  comdlg32\.lib advapi32\.lib shell32\.lib ole32\.lib oleaut32\.lib  netapi32\.lib uuid\.lib ws2\_32\.lib mpr\.lib winmm\.lib  version\.lib odbc32\.lib odbccp32\.lib msvcrt\.lib
&nbsp;    perllibs=  oldnames\.lib kernel32\.lib user32\.lib gdi32\.lib winspool\.lib  comdlg32\.lib advapi32\.lib shell32\.lib ole32\.lib oleaut32\.lib  netapi32\.lib uuid\.lib ws2\_32\.lib mpr\.lib winmm\.lib  version\.lib odbc32\.lib odbccp32\.lib msvcrt\.lib
&nbsp;    libc=msvcrt\.lib\, so=dll\, useshrplib=yes\, libperl=perl58\.lib
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_win32\.xs\, dlext=dll\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags=' '\, lddlflags='\-dll \-nologo \-nodefaultlib \-debug \-opt&#8203;:ref\,icf  \-libpath&#8203;:"d&#8203;:\\perl\\lib\\CORE"  \-machine&#8203;:x86'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl v5\.8\.8&#8203;:
&nbsp;    d&#8203;:/perl/lib
&nbsp;    d&#8203;:/perl/site/lib
&nbsp;    \.



---
Environment for perl v5\.8\.8&#8203;:
&nbsp;    CYGWIN=server ntsec
&nbsp;    HOME \(unset\)
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=C&#8203;:\\WINDOWS\\system32;C&#8203;:\\WINDOWS;C&#8203;:\\WINDOWS\\System32\\Wbem;C&#8203;:\\Program Files\\Microsoft SDK\\Bin;C&#8203;:\\Program Files\\Microsoft SDK\\Bin\\WinNT;C&#8203;:\\PROGRA~1\\MICROS~2\\Common\\msdev98\\BIN;C&#8203;:\\PROGRA~1\\MICROS~2\\VC98\\BIN;C&#8203;:\\PROGRA~1\\MICROS~2\\Common\\TOOLS\\WINNT;C&#8203;:\\PROGRA~1\\MICROS~2\\Common\\TOOLS;d&#8203;:\\apache;d&#8203;:\\apache\\bin;d&#8203;:\\openssl\\bin;d&#8203;:\\perl\\bin;c&#8203;:\\utl;c&#8203;:\\cygwin\\bin
&nbsp;    PERLIO=win32
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL \(unset\)

**Comment by p5pRT** [comment]
### From vaclav.ovsik@i.cz

This is a bug report for perl from zito@&#8203;bobekw\,
generated with the help of perlbug 1\.35 running under perl v5\.8\.8\.

Hello\,
i compiled perl 5\.8\.8 on win32 in a standard way using
MSVC6 \(with service pack 6 and PSDK\) on Windows XP\.
All tests passed after compilation\.

I found\, that I can't disable lf \<\-> crlf translations
using layer \`raw' nor using binmode on filehandle
of STDOUT or STDERR \(STDIN not tested\)\. Newly opened
files are ok\.

\(Tests are run on cygwin prompt\, but without cygwins perl\.
Native perl is on the PATH\.\)


&nbsp;    zito@&#8203;bobekw&#8203;:\~$ mytest\(\) \{
&nbsp;    > perl \-e 'print "\\n";' |xxd
&nbsp;    > perl \-e 'print join\("\, "\, PerlIO&#8203;::get\_layers\(STDOUT\)\)\, "\\n";'
&nbsp;    > \}


&nbsp;    zito@&#8203;bobekw&#8203;:\~$ mytest
&nbsp;    0000000&#8203;: 0d0a                                     \.\.
&nbsp;    unix\, crlf
Ok

&nbsp;    zito@&#8203;bobekw&#8203;:\~$ PERLIO='&#8203;:raw' mytest
&nbsp;    0000000&#8203;: 0d0a                                     \.\.
&nbsp;    unix
Bug?

&nbsp;    zito@&#8203;bobekw&#8203;:\~$ PERLIO='&#8203;:stdio' mytest
&nbsp;    0000000&#8203;: 0d0a                                     \.\.
&nbsp;    stdio
Bug?

&nbsp;    zito@&#8203;bobekw&#8203;:\~$ PERLIO='&#8203;:perlio' mytest
&nbsp;    0000000&#8203;: 0a                                       \.
&nbsp;    unix\, perlio
Ok?
Interesting\! Layer unix alone produces crlf\,
but unix\+perlio behaves ok?

&nbsp;    zito@&#8203;bobekw&#8203;:\~$ PERLIO='&#8203;:win32' mytest
&nbsp;    0000000&#8203;: 0a                                       \.
&nbsp;    win32
Ok

Layer win32 is considered experimental in PerlIO pod\, so should
I workaround problem with perlio? Is it safe?

Thanks for any comments on this\.
Maybe\, I misuderstood something\.
\-\- 
Vaclav Ovsik



---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=low


---
Site configuration information for perl v5\.8\.8&#8203;:

Configured by zito at Wed Nov  1 18&#8203;:05&#8203;:58 2006\.

Summary of my perl5 \(revision 5 version 8 subversion 8\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=MSWin32\, osvers=5\.1\, archname=MSWin32\-x86\-multi\-thread
&nbsp;    uname=''
&nbsp;    config\_args='undef'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=undef
&nbsp;    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=undef use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cl'\, ccflags ='\-nologo \-Gf \-W3 \-MD \-Zi \-DNDEBUG \-O1 \-DWIN32 \-D\_CONSOLE \-DNO\_STRICT \-DHAVE\_DES\_FCRYPT  \-DPERL\_IMPLICIT\_CONTEXT \-DPERL\_IMPLICIT\_SYS \-DUSE\_PERLIO \-DPERL\_MSVCRT\_READFIX'\,
&nbsp;    optimize='\-MD \-Zi \-DNDEBUG \-O1'\,
&nbsp;    cppflags='\-DWIN32'
&nbsp;    ccversion='12\.00\.8168'\, gccversion=''\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=undef\, longlongsize=8\, d\_longdbl=define\, longdblsize=10
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='\_\_int64'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='link'\, ldflags ='\-nologo \-nodefaultlib \-debug \-opt&#8203;:ref\,icf  \-libpath&#8203;:"d&#8203;:\\perl\\lib\\CORE"  \-machine&#8203;:x86'
&nbsp;    libpth=C&#8203;:\\PROGRA~1\\MICROS~2\\VC98\\lib
&nbsp;    libs=  oldnames\.lib kernel32\.lib user32\.lib gdi32\.lib winspool\.lib  comdlg32\.lib advapi32\.lib shell32\.lib ole32\.lib oleaut32\.lib  netapi32\.lib uuid\.lib ws2\_32\.lib mpr\.lib winmm\.lib  version\.lib odbc32\.lib odbccp32\.lib msvcrt\.lib
&nbsp;    perllibs=  oldnames\.lib kernel32\.lib user32\.lib gdi32\.lib winspool\.lib  comdlg32\.lib advapi32\.lib shell32\.lib ole32\.lib oleaut32\.lib  netapi32\.lib uuid\.lib ws2\_32\.lib mpr\.lib winmm\.lib  version\.lib odbc32\.lib odbccp32\.lib msvcrt\.lib
&nbsp;    libc=msvcrt\.lib\, so=dll\, useshrplib=yes\, libperl=perl58\.lib
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_win32\.xs\, dlext=dll\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags=' '\, lddlflags='\-dll \-nologo \-nodefaultlib \-debug \-opt&#8203;:ref\,icf  \-libpath&#8203;:"d&#8203;:\\perl\\lib\\CORE"  \-machine&#8203;:x86'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl v5\.8\.8&#8203;:
&nbsp;    d&#8203;:/perl/lib
&nbsp;    d&#8203;:/perl/site/lib
&nbsp;    \.



---
Environment for perl v5\.8\.8&#8203;:
&nbsp;    CYGWIN=server ntsec
&nbsp;    HOME \(unset\)
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=C&#8203;:\\WINDOWS\\system32;C&#8203;:\\WINDOWS;C&#8203;:\\WINDOWS\\System32\\Wbem;C&#8203;:\\Program Files\\Microsoft SDK\\Bin;C&#8203;:\\Program Files\\Microsoft SDK\\Bin\\WinNT;C&#8203;:\\PROGRA~1\\MICROS~2\\Common\\msdev98\\BIN;C&#8203;:\\PROGRA~1\\MICROS~2\\VC98\\BIN;C&#8203;:\\PROGRA~1\\MICROS~2\\Common\\TOOLS\\WINNT;C&#8203;:\\PROGRA~1\\MICROS~2\\Common\\TOOLS;d&#8203;:\\apache;d&#8203;:\\apache\\bin;d&#8203;:\\openssl\\bin;d&#8203;:\\perl\\bin;c&#8203;:\\utl;c&#8203;:\\cygwin\\bin
&nbsp;    PERLIO=win32
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL \(unset\)

**Comment by p5pRT** [comment]
### From @jkeenan

On Wed Nov 22 06&#8203;:19&#8203;:43 2006\, zito wrote&#8203;:
> This is a bug report for perl from zito@&#8203;bobekw\,
> generated with the help of perlbug 1\.35 running under perl v5\.8\.8\.
> 
> Hello\,
> i compiled perl 5\.8\.8 on win32 in a standard way using
> MSVC6 \(with service pack 6 and PSDK\) on Windows XP\.
> All tests passed after compilation\.
> 
> I found\, that I can't disable lf \<\-> crlf translations
> using layer \`raw' nor using binmode on filehandle
> of STDOUT or STDERR \(STDIN not tested\)\. Newly opened
> files are ok\.
> 
> \(Tests are run on cygwin prompt\, but without cygwins perl\.
> Native perl is on the PATH\.\)
> 
> 
>     zito@&#8203;bobekw&#8203;:\~$ mytest\(\) \{
>     > perl \-e 'print "\\n";' |xxd
>     > perl \-e 'print join\("\, "\, PerlIO&#8203;::get\_layers\(STDOUT\)\)\, "\\n";'
>     > \}
> 
> 
>     zito@&#8203;bobekw&#8203;:\~$ mytest
>     0000000&#8203;: 0d0a                                     \.\.
>     unix\, crlf
> Ok
> 
>     zito@&#8203;bobekw&#8203;:\~$ PERLIO='&#8203;:raw' mytest
>     0000000&#8203;: 0d0a                                     \.\.
>     unix
> Bug?
> 
>     zito@&#8203;bobekw&#8203;:\~$ PERLIO='&#8203;:stdio' mytest
>     0000000&#8203;: 0d0a                                     \.\.
>     stdio
> Bug?
> 
>     zito@&#8203;bobekw&#8203;:\~$ PERLIO='&#8203;:perlio' mytest
>     0000000&#8203;: 0a                                       \.
>     unix\, perlio
> Ok?
> Interesting\! Layer unix alone produces crlf\,
> but unix\+perlio behaves ok?
> 
>     zito@&#8203;bobekw&#8203;:\~$ PERLIO='&#8203;:win32' mytest
>     0000000&#8203;: 0a                                       \.
>     win32
> Ok
> 
> Layer win32 is considered experimental in PerlIO pod\, so should
> I workaround problem with perlio? Is it safe?
> 
> Thanks for any comments on this\.
> Maybe\, I misuderstood something\.


Is there anyone who has Perl 5\.18 on Windows and who is familiar with
layers who could take a look at this older ticket?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @Leont

On Wed Nov 22 06&#8203;:19&#8203;:43 2006\, zito wrote&#8203;:
>     zito@&#8203;bobekw&#8203;:\~$ mytest
>     0000000&#8203;: 0d0a                                     \.\.
>     unix\, crlf
> Ok

Correct\.

>     zito@&#8203;bobekw&#8203;:\~$ PERLIO='&#8203;:raw' mytest
>     0000000&#8203;: 0d0a                                     \.\.
>     unix
> Bug?

Part of this is a bug that has been fixed in 5\.14 \(open :raw used to
nuke the top layer\)\, part of it is a very subtle issue in the way :unix
can be triggered to do \*native\* crlf transformation on std\{in\,out\,err\}
because the bootstrap explicitly marks them as text\. Any other
filehandles should be non\-crlf\.

Actually\, because the first bug is fixed\, you should only be able to
observe this on modern perls when doing PERLIO='&#8203;:pop'\.

>     zito@&#8203;bobekw&#8203;:\~$ PERLIO='&#8203;:stdio' mytest
>     0000000&#8203;: 0d0a                                     \.\.
>     stdio
> Bug?

No\, that's exactly what you should expect\.

>     zito@&#8203;bobekw&#8203;:\~$ PERLIO='&#8203;:perlio' mytest
>     0000000&#8203;: 0a                                       \.
>     unix\, perlio
> Ok?

That's correct :\-\)

> Interesting\! Layer unix alone produces crlf\,
> but unix\+perlio behaves ok?
> 
>     zito@&#8203;bobekw&#8203;:\~$ PERLIO='&#8203;:win32' mytest
>     0000000&#8203;: 0a                                       \.
>     win32
> Ok

That appears to be correct\, though not necessarily the most useful
course of action\.

Leon

**Comment by toddr** [comment]
I believe @Leont 's response here is: Fixed in 5.14
