### ISSUE TITLE
Fallback (replacement char) with encode() vs binmode/open

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#8950]
Migrated from [rt.perl.org#43390](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=43390) (status was 'open')

Searchable as RT43390$

**Comment by p5pRT** [comment]
### From nospam-abuse@bloodgate.com

#### Created by nospam-abuse@bloodgate.com



Moin\,

consider the three programs below\. They take an UTF\-8 text containing
russian characters and convert it to ISO\-8859\-1\, which can not express
these characters\. This means they should get replaced by '?'\. However&#8203;:

\* it doesn't seem possible to say what replacement char is uses\, '?'
&nbsp;  seems the only possible choice and default
\* only the encode\(\) variant actually works\, the other two warn and
&nbsp;  do not produce the right output

I believe this is a bug\, all three programs should work like encode\.pl&#8203;:

&nbsp;        \# perl encode\.pl
&nbsp;        ???????
&nbsp;        \# perl binmode\.pl
&nbsp;        "\\x\{0420\}" does not map to iso\-8859\-1 at binmode\.pl line 12\.
&nbsp;        "\\x\{0443\}" does not map to iso\-8859\-1 at binmode\.pl line 12\.
&nbsp;        "\\x\{0441\}" does not map to iso\-8859\-1 at binmode\.pl line 12\.
&nbsp;        "\\x\{0441\}" does not map to iso\-8859\-1 at binmode\.pl line 12\.
&nbsp;        "\\x\{043a\}" does not map to iso\-8859\-1 at binmode\.pl line 12\.
&nbsp;        "\\x\{0438\}" does not map to iso\-8859\-1 at binmode\.pl line 12\.
&nbsp;        "\\x\{0439\}" does not map to iso\-8859\-1 at binmode\.pl line 12\.
&nbsp;        \\x\{0420\}\\x\{0443\}\\x\{0441\}\\x\{0441\}\\x\{043a\}\\x\{0438\}\\x\{0439\}
&nbsp;        \# perl open\.pl
&nbsp;        "\\x\{0420\}" does not map to iso\-8859\-1\.
&nbsp;        "\\x\{0443\}" does not map to iso\-8859\-1\.
&nbsp;        "\\x\{0441\}" does not map to iso\-8859\-1\.
&nbsp;        "\\x\{0441\}" does not map to iso\-8859\-1\.
&nbsp;        "\\x\{043a\}" does not map to iso\-8859\-1\.
&nbsp;        "\\x\{0438\}" does not map to iso\-8859\-1\.
&nbsp;        "\\x\{0439\}" does not map to iso\-8859\-1\.
&nbsp;        \# cat test\.txt
&nbsp;        \\x\{0420\}\\x\{0443\}\\x\{0441\}\\x\{0441\}\\x\{043a\}\\x\{0438\}\\x\{0439\}

encode\.pl&#8203;:

&nbsp;    \#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
&nbsp;    \#\!/usr/bin/perl \-w
&nbsp;    use Encode qw/encode/;
&nbsp;    use utf8;
&nbsp;    no warnings 'utf8';
&nbsp;    my $russki = 'Русский';
&nbsp;    my $enc = '&#8203;:encoding\(iso\-8859\-1\)';
&nbsp;    my $encoded = encode\('iso\-8859\-1'\, $russki\);
&nbsp;    binmode \(STDOUT\, $enc\) or 
&nbsp;        die \("Cannot do binmode\(STDOUT\,$enc\)&#8203;: $\!"\);
&nbsp;    print $encoded\,"\\n";
&nbsp;    \#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#

binmode\.pl&#8203;:

&nbsp;    \#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
&nbsp;    use Encode qw/encode/;
&nbsp;    use utf8;
&nbsp;    no warnings 'utf8';
&nbsp;    my $russki = 'Русский';
&nbsp;    my $enc = '&#8203;:encoding\(iso\-8859\-1\)';
&nbsp;    binmode \(STDOUT\, $enc\) or 
&nbsp;        die \("Cannot do binmode\(STDOUT\,$enc\)&#8203;: $\!"\);
&nbsp;    print $encoded\,"\\n";
&nbsp;    \#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#

open\.pl&#8203;:

&nbsp;    \#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
&nbsp;    use Encode qw/encode/;
&nbsp;    use utf8;
&nbsp;    no warnings 'utf8';
&nbsp;    my $russki = 'Русский';
&nbsp;    my $enc = '&#8203;:encoding\(iso\-8859\-1\)';
&nbsp;    open my $FILE\, ">$enc"\, 'test\.txt' or
&nbsp;        die \("Cannot open \(STDOUT\,$enc\)&#8203;: $\!"\);
&nbsp;    print $FILE $russki\,"\\n";
&nbsp;    \#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#

All the best\,

Tels

<details><summary>Perl Info</summary>

``` -----------------------------------------------------------------
- ---
Flags:
    category=core
    severity=medium
- ---
This perlbug was built using Perl v5.8.8 - Sat Apr 22 23:31:53 UTC 2006
It is being executed now by  Perl v5.8.8 - Sat Apr 22 23:26:49 UTC 2006.

Site configuration information for perl v5.8.8:

Configured by abuild at Sat Apr 22 23:26:49 UTC 2006.

Summary of my perl5 (revision 5 version 8 subversion 8) configuration:
  Platform:
    osname=linux, osvers=2.6.16, archname=x86_64-linux-thread-multi
    uname='linux dvorak 2.6.16 #1 smp mon apr 10 04:51:13 utc 2006 x86_64 
x86_64 x86_64 gnulinux '
    
config_args='-ds -e -Dprefix=/usr -Dvendorprefix=/usr -Dinstallusrbinperl -Dusethreads -Di_db -Di_dbm -Di_ndbm -Di_gdbm -Duseshrplib=true -Doptimize=-O2 -fmessage-length=0 -Wall -D_FORTIFY_SOURCE=2 -g -Wall -pipe'
    hint=recommended, useposix=true, d_sigaction=define
    usethreads=define use5005threads=undef useithreads=define 
usemultiplicity=define
    useperlio=define d_sfio=undef uselargefiles=define usesocks=undef
    use64bitint=define use64bitall=define uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags 
='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -DDEBUGGING -fno-strict-aliasing -pipe -Wdeclaration-after-statement -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    
optimize='-O2 -fmessage-length=0 -Wall -D_FORTIFY_SOURCE=2 -g -Wall -pipe',
    
cppflags='-D_REENTRANT -D_GNU_SOURCE -DTHREADS_HAVE_PIDS -DDEBUGGING -fno-strict-aliasing -pipe -Wdeclaration-after-statement'
    ccversion='', gccversion='4.1.0 (SUSE Linux)', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', 
lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib64'
    libpth=/lib64 /usr/lib64 /usr/local/lib64
    libs=-lm -ldl -lcrypt -lpthread
    perllibs=-lm -ldl -lcrypt -lpthread
    libc=/lib64/libc-2.4.so, so=so, useshrplib=true, libperl=libperl.so
    gnulibc_version='2.4'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, 
ccdlflags='-Wl,-E -Wl,-rpath,/usr/lib/perl5/5.8.8/x86_64-linux-thread-multi/CORE'
    cccdlflags='-fPIC', lddlflags='-shared -L/usr/local/lib64'

Locally applied patches:
    

- ---
@INC for perl v5.8.8:
    /usr/lib/perl5/5.8.8/x86_64-linux-thread-multi
    /usr/lib/perl5/5.8.8
    /usr/lib/perl5/site_perl/5.8.8/x86_64-linux-thread-multi
    /usr/lib/perl5/site_perl/5.8.8
    /usr/lib/perl5/site_perl
    /usr/lib/perl5/vendor_perl/5.8.8/x86_64-linux-thread-multi
    /usr/lib/perl5/vendor_perl/5.8.8
    /usr/lib/perl5/vendor_perl
    .

- ---
Environment for perl v5.8.8:
    HOME=/home/te
    LANG=en_US.UTF-8
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    
PATH=/usr/local/bin:/usr/bin:/usr/X11R6/bin:/bin:/usr/games:/opt/gnome/bin:/opt/kde3/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/home/te/.local/bin:/home/te/games/dirkdashing:/home/te/games/dirkdashing:/home/te/games/dirkdashing
    PERL_BADLANG (unset)
    SHELL=/bin/bash

- -- 
 Signed on Wed Jun 27 07:48:26 2007 with key 0x93B84C15.
 View my photo gallery: http://bloodgate.com/photos
 PGP key on http://bloodgate.com/tels.asc or per email.

 I am "Times Person of the Year 2006" 

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.2 (GNU/Linux)

iQEVAwUBRoH6bncLPEOTuEwVAQKizgf+OG87FsP/FDjuwC4TSsgSRvTs03pLLIOk
iIL0SZFYaUwufjNidplK05Pvw2/wY3KbE1vN+oXR4fmCFCwx/KL+UcNJMfN20DFa
9OyV9ZjfW4djOQ83CTTTrat6gx+wFkQHol/cSagPxfqUBynPvkTFFQNbYN2ojQWR
0IC86+BFqLAC5XF70vz1Mkb38ZY3IeNbo3RqidFO0YVkpBSG8gbEdmhEBsdkY/7p
99KHphrPyokhuCvYYru6Atlqd+Nb5ACMZv4jc1PnGwGhqzqtuQOCX2Q0c4S14Wx5
bxbUto1X/G1LzCUyUK0laovVuUQ2SqUvOR79Mn58Gb8vndH8aBvE3g==
=olFV
-----END PGP SIGNATURE-----

```
</details>

**Comment by p5pRT** [comment]
### From @Juerd

Tels skribis 2007\-06\-26 22&#8203;:51 \(\-0700\)&#8203;:
> \* it doesn't seem possible to say what replacement char is uses\, '?'
>   seems the only possible choice and default

It's possible\, but not entirely obvious&#8203;:

&nbsp;    juerd@&#8203;nano&#8203;:\~$ perl \-MEncode \-le'print encode latin1 => "foo\\x\{0420\}bar\\x\{e9\}"\, sub \{ "%" \}' | hexdump \-C
&nbsp;    00000000  66 6f 6f 25 62 61 72 e9  0a                       |foo%bar\.\.|
&nbsp;    00000009

> \* only the encode\(\) variant actually works\, the other two warn and
>   do not produce the right output

They seem to be using FB\_PERLQQ for CHECK\. The documentation says&#8203;:

&nbsp;    When the layer is pushed\, the current value of
&nbsp;    $PerlIO&#8203;::encoding&#8203;::fallback is saved and used as the CHECK argument
&nbsp;    when calling the Encode methods encode\(\) and decode\(\)\.

This doesn't seem to work\.
\-\- 
korajn salutojn\,

&nbsp;  juerd waalboer&#8203;:  perl hacker  \<juerd@&#8203;juerd\.nl>  \<http&#8203;://juerd\.nl/sig>
&nbsp;  convolution&#8203;:     ict solutions and consultancy \<sales@&#8203;convolution\.nl>

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by khwilliamson** [comment]
These now print \x{...} for all characters not representable in 8859-1
