### ISSUE TITLE
scientific notation parsing/conversion problems

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9095]
Migrated from [rt.perl.org#47087](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=47087) (status was 'open')

Searchable as RT47087$

**Comment by p5pRT** [comment]
### From davidp@lanl.gov


This is a bug report for perl from davidp@&#8203;lanl\.gov\,
generated with the help of perlbug 1\.35 running under perl v5\.8\.8\.

Upon investigation I've discovered some disturbing things&#8203;:

1\.    perl \-e 'print eval\($ARGV\[0\]\)\,"\\n"'
'\(1\.818343814922934E\+05\-1\.818343815129567E\+05\)/1\.450606250000001E\+02'
&nbsp;    returns \-1\.4244604399474e\-07
2\.    Using the attached programs\, gcc\, pgf90\, SunWSPro cc and f90\, MIPS f90\, gfortran and g95 all
calculate
&nbsp;    the following from the identical expression \(on Sun\, Cygwin\, 32\-bit Linux\, 64\-bit Linux\,
SGI\)&#8203;:
&nbsp;    \-1\.424458433625532e\-07

If that's not disturbing enough\, then read on \.\.\.

The most disturbing fact occurs when I remove the scientific notation from the literals&#8203;:

1\.    perl \-e 'print eval\($ARGV\[0\]\)\,"\\n"'
'\(181834\.3814922934\-181834\.3815129567\)/145\.0606250000001'
&nbsp;    returns \-1\.42445843362553e\-07

Compilers are the bane of my life \.\.\. sigh\.

The following was suggested to me&#8203;:

&nbsp;    perl \-e 'printf\("%\.15E\\n"\, eval\($ARGV\[0\]\)\)\,"\\n"' \\
&nbsp;            '\(1\.818343814922934E\+05\-1\.818343815129567E\+05\)/1\.450606250000001E\+02'
&nbsp;    \-1\.424458433625532E\-07
&nbsp;    Perl print uses the default C printf precision of six places\. To get more you have to
explicitly ask using printf\.

It was not portable to Cygwin since my Cygwin build of Perl continued to produce the original\,
incorrect value\. So\, here is an alternative script that avoids the precision problem on all
platforms I've tested so far \(i686 Linux\, Sun\, SGI\, i686 Cygwin on Windows XP\, IBM AIX Power PC\,
Darwin Power PC\, i386 Darwin Mac\)&#8203;:

perl \-e '$s=$ARGV\[0\]; $s=~s/\[eE\]\(\[\+\-\]?\\d\+\)/\*10\*\*$1/g; printf "%s =\\n%s
=\\n%\.15e\\n"\,$ARGV\[0\]\,$s\,eval\($s\);' \\
&nbsp;          '\(1\.818343814922934E\+05\-1\.818343815129567E\+05\)/1\.450606250000001E\+02'
yields&#8203;:
\(1\.818343814922934E\+05\-1\.818343815129567E\+05\)/1\.450606250000001E\+02 =
\(1\.818343814922934\*10\*\*\+05\-1\.818343815129567\*10\*\*\+05\)/1\.450606250000001\*10\*\*\+02 =
\-1\.424458433625532e\-03

Basically\, I convert the scientific notation numbers to standard floating point numbers with regex\,
and then run eval on the resulting string expression\. This indicates to me that "print" is not the
culprit here\, but that Perl is not correctly converting scientific notation from the expression\.


---
Flags&#8203;:
&nbsp;    category=core
&nbsp;    severity=medium


---
Site configuration information for perl v5\.8\.8&#8203;:

Configured by rurban at Sun Jul  8 19&#8203;:08&#8203;:44 GMT 2007\.

Summary of my perl5 \(revision 5 version 8 subversion 8\) configuration&#8203;:
&nbsp;  Platform&#8203;:
&nbsp;    osname=cygwin\, osvers=1\.5\.24\(0\.15642\)\, archname=cygwin\-thread\-multi\-64int
&nbsp;    uname='cygwin\_nt\-5\.1 reini 1\.5\.24\(0\.15642\) 2007\-01\-31 10&#8203;:57 i686 cygwin '
&nbsp;    config\_args='\-de \-Dmksymlinks \-Duse64bitint \-Dusethreads \-Uusemymalloc \-Doptimize=\-O3
\-Dman3ext=3pm \-Dusesitecustomize \-Dusedevel'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    usethreads=define use5005threads=undef useithreads=define usemultiplicity=define
&nbsp;    useperlio=define d\_sfio=undef uselargefiles=define usesocks=undef
&nbsp;    use64bitint=define use64bitall=undef uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='gcc'\, ccflags ='\-DPERL\_USE\_SAFE\_PUTENV \-fno\-strict\-aliasing \-pipe
\-Wdeclaration\-after\-statement'\,
&nbsp;    optimize='\-O3'\,
&nbsp;    cppflags='\-DPERL\_USE\_SAFE\_PUTENV \-fno\-strict\-aliasing \-pipe \-Wdeclaration\-after\-statement'
&nbsp;    ccversion=''\, gccversion='3\.4\.4 \(cygming special\, gdc 0\.12\, using dmd 0\.125\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=12345678
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=12
&nbsp;    ivtype='long long'\, ivsize=8\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='ld2'\, ldflags =' \-s \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib /lib
&nbsp;    libs=\-lgdbm \-ldb \-ldl \-lcrypt \-lgdbm\_compat
&nbsp;    perllibs=\-ldl \-lcrypt \-lgdbm\_compat
&nbsp;    libc=/usr/lib/libc\.a\, so=dll\, useshrplib=true\, libperl=libperl\.a
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=dll\, d\_dlsymun=undef\, ccdlflags=' \-s'
&nbsp;    cccdlflags=' '\, lddlflags=' \-s \-L/usr/local/lib'

Locally applied patches&#8203;:
&nbsp;    CYG01 \- hints\.cygwin\.sh ldflags \-s
&nbsp;    CYG02 \- lib\-ExtUtils\-Embed insensitive against leading \\\\s
&nbsp;    CYG03 \- lib\-Test\-Harness\-Straps $ENV\{PERL5LIB\} = ''
&nbsp;    CYG04 \- major\.version\.cygwin\.sh cygperl\-5\_8\.dll and not cygperl\-5\_8\_x\.dll
&nbsp;    CYG05 \- add Win32CORE to core
&nbsp;    CYG07 \- File\-Spec\-Cygwin\-TMPDIR\.patch
&nbsp;    Bug\#38628 \- allow legacy Cwd\->cwd\(\)
&nbsp;    Bug\#40103 \- File\-Spec\-case\_tolerant\.patch from 5\.9\.5



---
@&#8203;INC for perl v5\.8\.8&#8203;:
&nbsp;    /usr/lib/perl5/5\.8/cygwin
&nbsp;    /usr/lib/perl5/5\.8
&nbsp;    /usr/lib/perl5/site\_perl/5\.8/cygwin
&nbsp;    /usr/lib/perl5/site\_perl/5\.8
&nbsp;    /usr/lib/perl5/site\_perl/5\.8
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8/cygwin
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8
&nbsp;    /usr/lib/perl5/vendor\_perl/5\.8
&nbsp;    \.



---
Environment for perl v5\.8\.8&#8203;:
&nbsp;    HOME=/cygdrive/d/Users/120181/cyghome
&nbsp;    LANG \(unset\)
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
 
PATH=/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/cygdrive/c/PROGRA~1/GNU/WinCvs&#8203;:/eclipse&#8203;:/cygdrive/c/absoft90/bin&#8203;:
/cygdrive/d/Users/120181/cyghome/SCRIPTS&#8203;:/usr/X11R6/bin&#8203;:\.&#8203;:/usr/local/bin&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bi
n&#8203;:/usr/local/bin&#8203;:/usr/bin&#8203;:/bin&#8203;:/usr/X11R6/bin&#8203;:/cygdrive/c/Program Files/Microsoft Visual
Studio/Common/Tools&#8203;:/cygdrive/c/Program Files/Microsoft Visual
Studio/Common/Msdev98/BIN&#8203;:/cygdrive/c/Program Files/Microsoft Visual
Studio/DF98/BIN&#8203;:/cygdrive/c/Program Files/Microsoft Visual
Studio/VC98/BIN&#8203;:/cygdrive/c/WINDOWS/system32&#8203;:/cygdrive/c/WINDOWS&#8203;:/cygdrive/c/WINDOWS/System32/Wbem&#8203;:/
cygdrive/c/Program Files/ATI Technologies/ATI Control Panel&#8203;:/cygdrive/c/Program
Files/WRQ/RSecure/&#8203;:/cygdrive/c/Program Files/Reflection/&#8203;:/cygdrive/c/Program Files/Diskeeper
Corporation/Diskeeper/&#8203;:/cygdrive/c/Program Files/IDM Computer
Solutions/UltraEdit\-32&#8203;:/cygdrive/c/Program Files/Common Files/Adobe/AGL&#8203;:/cygdrive/c/Program
Files/QuickTime/QTSystem/&#8203;:/cygdrive/c/Program Files/Common Files/Roxio Shared/\!
 DLLShared&#8203;:/cygdrive/c/Program Files/Microsoft Visual Studio/Common/Tools/WinNT&#8203;:/cygdrive/c/Program
Files/Microsoft Visual Studio/Common/MSDev98/Bin&#8203;:/cygdrive/c/Program Files/Microsoft Visual
Studio/Common/Tools&#8203;:/cygdrive/c/Program Files/Microsoft Visual Studio/VC98/bin&#8203;:/cygdrive/c/Program
Files/IDM Computer
Solutions/UltraCompare&#8203;:/usr/lib/lapack&#8203;:/usr/local/bin/Graphviz/bin&#8203;:/usr/local/bin/default/intel\-cygw
in&#8203;:/cygdrive/d/Users/120181/MYDOCU~1/eospac6/Source/scripts
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/tcsh

**Comment by p5pRT** [comment]
### From @dcollinsn

$ perl5\.25\.2 \-e 'print eval\("\(1\.818343814922934E\+05\-1\.818343815129567E\+05\)"\)\,"\\n"'
\-2\.06633121706545e\-05
$ perl5\.25\.2 \-e 'print eval\("\(181834\.3814922934\-181834\.3815129567\)"\)\,"\\n"'
\-2\.06632830668241e\-05

What gives?

\-\- 
Respectfully\,
Dan Collins

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Dan Collins via RT wrote&#8203;:
>What gives?

$ perl \-MData&#8203;::Float=float\_hex \-le 'print float\_hex\($\_\) for 181834\.3814922934\, 1\.818343814922934e5'
\+0x1\.632530d4bd4dfp\+17
\+0x1\.632530d4bd4dep\+17

Looks like another form of \[perl \#41202\]\.  The former is the true closest
representable value&#8203;:

$ perl \-le 'printf "%\.60f\\n"\, $\_ for 181834\.3814922934\, 1\.818343814922934e5'
181834\.381492293410701677203178405761718750000000000000000000000000
181834\.381492293381597846746444702148437500000000000000000000000000

\-zefram

**Comment by p5pRT** [comment]
### From @khwilliamson

On 07/16/2016 05&#8203;:40 PM\, Zefram wrote&#8203;:
> Dan Collins via RT wrote&#8203;:
>> What gives?
>
> $ perl \-MData&#8203;::Float=float\_hex \-le 'print float\_hex\($\_\) for 181834\.3814922934\, 1\.818343814922934e5'
> \+0x1\.632530d4bd4dfp\+17
> \+0x1\.632530d4bd4dep\+17
>
> Looks like another form of \[perl \#41202\]\.  The former is the true closest
> representable value&#8203;:
>
> $ perl \-le 'printf "%\.60f\\n"\, $\_ for 181834\.3814922934\, 1\.818343814922934e5'
> 181834\.381492293410701677203178405761718750000000000000000000000000
> 181834\.381492293381597846746444702148437500000000000000000000000000
>
> \-zefram
>

I've wondered if things like this would be improved if we were to take 
the advice of someone whose name I don't recall of treating 10\*\*x as 
5\*\*x \* 2\*\*x\.  The first term is much smaller than 10\*\*x\, and the second 
term is just shifting\.  But my knowledge of floating point 
implementations stopped at the CDC 7600\.

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Karl Williamson wrote&#8203;:
>I've wondered if things like this would be improved if we were to take the
>advice of someone whose name I don't recall of treating 10\*\*x as 5\*\*x \* 2\*\*x\.

No\, it would not\.  When putting multiple digits together\, we still need
their weights to be 10\*\*x apart\, not 5\*\*x\.

\-zefram

**Comment by khwilliamson** [comment]
Please see GH #7586 for a similar issue

**Comment by khwilliamson** [comment]
RT #41202 (GH #8730 ) was fixed in 5.30.  I just ran Dan Collins examples on blead, and both now give the same result.  So I'm closing this ticket:

blead -le 'print eval("(1.818343814922934E+05-1.818343815129567E+05)"),"\n"'          
-2.06632830668241e-05

blead -le 'print eval("(181834.3814922934-181834.3815129567)"),"\n"'
-2.06632830668241e-05
