### ISSUE TITLE
 perlcc code compiles but won't run: WHY????

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#94]
Migrated from [rt.perl.org#898](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=898) (status was 'resolved')

Searchable as RT898$

**Comment by p5pRT** [comment]
### From The RT System itself

I've spent three days looking through online documents and I can't
find anything that even gives me a clue as to how to solve my Perl
problem\. Can someone PLEASE help\, or at least tell me the best place
to look \(yes\, I've been all through CPAN\)\.

Specifically\, my problem is this&#8203;:

I just started attempting to use perlcc with Redhat Linux 5\.2 on an 
Intel platform \(Pentium 133\)\. My perl code seems to compile okay using 
perlcc\, but it won't run\. What is SEEMS to be choking on is 
subroutine calls\, even though it tells me the syntax of my code 
was okay during the compile phase\. What I get when I run my code
is a "segmentation fault" and a core dump\. Note&#8203;: I am NOT using any 
modules and I have tested the problem by using a simple program which 
does nothing except call a subroutine which prints "hello world"\.
If I had written this in fortran\, I would think this is some kind of
link error\, but Perl doesn't link\, does it?

HELP PLEASE\!

Rick Johnson
firespring@&#8203;nfx\.net


 Rick Johnson \<firespring@&#8203;nfx\.net>

**Comment by amcareem** [comment]
One of the oldest problems. Can anyone say like what would has caused this problem? Just curious to know

**Comment by jkeenan** [comment]
> One of the oldest problems. Can anyone say like what would has caused this problem? Just curious to know

Please note that this problem was marked Resolved way back in 2003 when the ticket was being tracked in RT.  Indeed, the original filing date suggests that this ticket may have been filed even before we moved to RT.  The original poster does not provide sufficient detail for someone to understand the problem and never followed up.  That is probably the reason the ticket was closed.
