### ISSUE TITLE
pad_alloc and fold_constants are not members of public API

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9403]
Migrated from [rt.perl.org#56536](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=56536) (status was 'open')

Searchable as RT56536$

**Comment by p5pRT** [comment]
### From dk@tetsuo.karasik.eu.org

#### Created by dk@tetsuo.karasik.eu.org




B&#8203;::Generate doesn't compile on MSWin32\, requiring Perl\_pad\_alloc and
Perl\_fold\_constants in perl\.dll\. Here's a patch that exports these
function\, and allows B&#8203;::Generate to be useful also on MSWin32\.

<details><summary>Inline Patch</summary>

```diff
--- embed.fnc.0	2008-05-21 15:35:50.000000000 +0200
+++ embed.fnc	2008-07-02 20:35:36.000000000 +0200
@@ -276,7 +276,7 @@
 p	|char*	|find_script	|NN const char *scriptname|bool dosearch \
 				|NULLOK const char *const *const search_ext|I32 flags
 p	|OP*	|force_list	|NULLOK OP* arg
-p	|OP*	|fold_constants	|NN OP *o
+Ap	|OP*	|fold_constants	|NN OP *o
 Afpd	|char*	|form		|NN const char* pat|...
 Ap	|char*	|vform		|NN const char* pat|NULLOK va_list* args
 Ap	|void	|free_tmps
@@ -653,7 +653,7 @@
 #else
 p	|void	|package	|NN OP* o
 #endif
-pd	|PADOFFSET|pad_alloc	|I32 optype|U32 tmptype
+Apd	|PADOFFSET|pad_alloc	|I32 optype|U32 tmptype
 p	|PADOFFSET|allocmy	|NN const char *const name
 pdR	|PADOFFSET|pad_findmy	|NN const char* name
 Ap	|PADOFFSET|find_rundefsvoffset	|
```
</details>


<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=medium


```
</details>

**Comment by p5pRT** [comment]
### From @rgs

2008/7/2 dk@&#8203;tetsuo\.karasik\.eu\.org \(via RT\) \<perlbug\-followup@&#8203;perl\.org>&#8203;:
>
> B&#8203;::Generate doesn't compile on MSWin32\, requiring Perl\_pad\_alloc and
> Perl\_fold\_constants in perl\.dll\. Here's a patch that exports these
> function\, and allows B&#8203;::Generate to be useful also on MSWin32\.

I think that it's OK for fold\_constants\(\) to go in the public API\, but
the interface to pad\_alloc\(\) might change\. Do you really need it\, or
can't you export it just by tweaking makedef\.pl instead ?

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @dk

I don't need these functions to be part of public API\, I just need
B&#8203;::Generate to work on win32\. I found the easiest way to do that was
hacking embed\.fnc\, I've also looked before at makedef\.pl but got lost
there; you're welcome to rework the patch so embed\.fnc stays intact\, I
won't insist on the publicity of these functions\.

**Comment by p5pRT** [comment]
### From @dk

Wasn't that scary after all\. Here's the patch that does it with
makedef\.pl only&#8203;:

<details><summary>Inline Patch</summary>

```diff
--- makedef.pl.0	2007-12-18 11:47:08.000000000 +0100
+++ makedef.pl	2008-07-28 21:58:34.000000000 +0200
@@ -1219,6 +1219,8 @@
 			    Perl_thread_create
 			    Perl_win32_init
 			    Perl_win32_term
+			    Perl_pad_alloc
+			    Perl_fold_constants
 			    RunPerl
 			    win32_async_check
 			    win32_errno
```
</details>

**Comment by richardleach** [comment]
The primary driver of this ticket was that B::Generate doesn't compile on Windows.

RURBAN/B-Generate-1.56.tar.gz has just installed perfectly happily for me on a copy of Strawberry Perl 5.28.2 on Windows 10.

**Comment by toddr** [comment]
Glad to hear. Thanks!
