### ISSUE TITLE
Devel::Peek fails 2 tests when perl is built with NO_PERL_PRESERVE_IVUV

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9766]
Migrated from [rt.perl.org#66584](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=66584) (status was 'open')

Searchable as RT66584$

**Comment by p5pRT** [comment]
### From @sisyphus

#### Created by Rob@desktop2



Not sure of the approved way of building perl with NO\_PERL\_PRESERVE\_IVUV on 
Win32\.
I simply placed a '\#define NO\_PERL\_PRESERVE\_IVUV' at the beginning of 
perl\.h\.

Tests 21 and 23 of ext/Devel/Peek/t/Peek\.t are the only tests that failed 
during the running of the test suite\. The output I get for those 2 tests is 
given below\.

Not sure if the garbage \(for want of a better word\) in the "expected" output 
is part of the failure\, but I note that the "got" output terminates with&#8203;:

\#       REFCNT = 1
\#       FLAGS = \(IOK\,NOK\,pIOK\,pNOK\)
\#       IV = 456
\#       NV = 456
\#       PV = 0

whereas the "expected" output terminates with&#8203;:

\#       REFCNT = 1
\#       FLAGS = \\\(IOK\,pIOK\\\)
\#       IV = 456\\Z\)/

Anyway\, here's the full output for those tests&#8203;:

\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#
ok 20
not ok 21
\# Failed at \.\./ext/Devel/Peek/t/Peek\.t line 72
\#      got 'SV = RV\(0x2792da8\) at 0x2792d9c
\#   REFCNT = 1
\#   FLAGS = \(ROK\)
\#   RV = 0x308c24
\#   SV = PVAV\(0x309bcc\) at 0x308c24
\#     REFCNT = 1
\#     FLAGS = \(\)
\#     ARRAY = 0x4f6f3c
\#     FILL = 1
\#     MAX = 1
\#     ARYLEN = 0x0
\#     FLAGS = \(REAL\)
\#     Elt No\. 0
\#     SV = IV\(0x2792be8\) at 0x2792bec
\#       REFCNT = 1
\#       FLAGS = \(IOK\,pIOK\)
\#       IV = 123
\#     Elt No\. 1
\#     SV = PVNV\(0x4dd4f4\) at 0x308c34
\#       REFCNT = 1
\#       FLAGS = \(IOK\,NOK\,pIOK\,pNOK\)
\#       IV = 456
\#       NV = 456
\#       PV = 0
\# '
\# expected /\(?ms\-xi&#8203;:\\A\(?&#8203;:ALLOCATED at \.\*?
\# \)?SV = RV\\\(0x\[\[&#8203;:xdigit&#8203;:\]\]\+\\\) at 0x\[\[&#8203;:xdigit&#8203;:\]\]\+
\#   REFCNT = 1
\#   FLAGS = \\\(ROK\\\)
\#   RV = 0x\[\[&#8203;:xdigit&#8203;:\]\]\+
\# \(?&#8203;:  ALLOCATED at \.\*?
\# \)?  SV = PVAV\\\(0x\[\[&#8203;:xdigit&#8203;:\]\]\+\\\) at 0x\[\[&#8203;:xdigit&#8203;:\]\]\+
\#     REFCNT = 1
\#     FLAGS = \\\(\\\)
\#     ARRAY = 0x\[\[&#8203;:xdigit&#8203;:\]\]\+
\#     FILL = 1
\#     MAX = 1
\#     ARYLEN = 0x0
\#     FLAGS = \\\(REAL\\\)
\#     Elt No\. 0
\# \(?&#8203;:    ALLOCATED at \.\*?
\# \)?    SV = IV\\\(0x\[\[&#8203;:xdigit&#8203;:\]\]\+\\\) at 0x\[\[&#8203;:xdigit&#8203;:\]\]\+
\#       REFCNT = 1
\#       FLAGS = \\\(IOK\,pIOK\\\)
\#       IV = 123
\#     Elt No\. 1
\# \(?&#8203;:    ALLOCATED at \.\*?
\# \)?    SV = IV\\\(0x\[\[&#8203;:xdigit&#8203;:\]\]\+\\\) at 0x\[\[&#8203;:xdigit&#8203;:\]\]\+
\#       REFCNT = 1
\#       FLAGS = \\\(IOK\,pIOK\\\)
\#       IV = 456\\Z\)/
ok 22
not ok 23
\# Failed at \.\./ext/Devel/Peek/t/Peek\.t line 72
\#      got 'SV = RV\(0x2792bf8\) at 0x2792bec
\#   REFCNT = 1
\#   FLAGS = \(ROK\)
\#   RV = 0x2792d9c
\#   SV = PVHV\(0x4250c8\) at 0x2792d9c
\#     REFCNT = 1
\#     FLAGS = \(SHAREKEYS\)
\#     ARRAY = 0x43ccbc  \(0&#8203;:7\, 1&#8203;:1\)
\#     hash quality = 100\.0%
\#     KEYS = 1
\#     FILL = 1
\#     MAX = 7
\#     RITER = \-1
\#     EITER = 0x0
\#     Elt "123" HASH = 0x29b8dfb0
\#     SV = PVNV\(0x4dd4f4\) at 0x308c24
\#       REFCNT = 1
\#       FLAGS = \(IOK\,NOK\,pIOK\,pNOK\)
\#       IV = 456
\#       NV = 456
\#       PV = 0
\# '
\# expected /\(?ms\-xi&#8203;:\\A\(?&#8203;:ALLOCATED at \.\*?
\# \)?SV = RV\\\(0x\[\[&#8203;:xdigit&#8203;:\]\]\+\\\) at 0x\[\[&#8203;:xdigit&#8203;:\]\]\+
\#   REFCNT = 1
\#   FLAGS = \\\(ROK\\\)
\#   RV = 0x\[\[&#8203;:xdigit&#8203;:\]\]\+
\# \(?&#8203;:  ALLOCATED at \.\*?
\# \)?  SV = PVHV\\\(0x\[\[&#8203;:xdigit&#8203;:\]\]\+\\\) at 0x\[\[&#8203;:xdigit&#8203;:\]\]\+
\#     REFCNT = 1
\#     FLAGS = \\\(SHAREKEYS\\\)
\#     ARRAY = 0x\[\[&#8203;:xdigit&#8203;:\]\]\+  \\\(0&#8203;:7\, 1&#8203;:1\\\)
\#     hash quality = 100\.0%
\#     KEYS = 1
\#     FILL = 1
\#     MAX = 7
\#     RITER = \-1
\#     EITER = 0x0
\#     Elt "123" HASH = 0x\[\[&#8203;:xdigit&#8203;:\]\]\+
\# \(?&#8203;:    ALLOCATED at \.\*?
\# \)?    SV = IV\\\(0x\[\[&#8203;:xdigit&#8203;:\]\]\+\\\) at 0x\[\[&#8203;:xdigit&#8203;:\]\]\+
\#       REFCNT = 1
\#       FLAGS = \\\(IOK\,pIOK\\\)
\#       IV = 456\\Z\)/
\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#

Same results with a recent \(though not latest\) build of blead\.

Cheers\,
Rob

<details><summary>Perl Info</summary>

```

Flags:
    category=library
    severity=medium

Site configuration information for perl 5.10.0:

Configured by Rob at Sat Jun 13 10:47:53 2009.

Summary of my perl5 (revision 5 version 10 subversion 0) configuration:
  Platform:
    osname=MSWin32, osvers=6.0, archname=MSWin32-x64-multi-thread
    uname=''
    config_args='undef'
    hint=recommended, useposix=true, d_sigaction=undef
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=undef, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags 
' -s -O2 -DWIN32 -DHAVE_DES_FCRYPT  -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS 
 -fno-strict-aliasing -DPERL_MSVCRT_READFIX',
    optimize='-s -O2',
    cppflags='-DWIN32'
    ccversion='', gccversion='3.4.5', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=undef, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='long long', 
lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='g++', ldflags 
='-s -L"c:\perl510_NV\5.10.0\lib\CORE" -L"C:\home\rob\mingw_vista\i686-pc-mingw32\lib"'
    libpth=C:\home\rob\mingw_vista\i686-pc-mingw32\lib
    libs=-lmsvcrt -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 
 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm 
 -lversion -lodbc32 -lodbccp32
    perllibs=-lmsvcrt -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 
 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm 
 -lversion -lodbc32 -lodbccp32
    libc=-lmsvcrt, so=dll, useshrplib=true, libperl=libperl510.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs, dlext=dll, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', 
lddlflags='-mdll -s -L"c:\perl510_NV\5.10.0\lib\CORE" -L"C:\home\rob\mingw_vista\i686-pc-mingw32\lib"'

Locally applied patches:



@INC for perl 5.10.0:
    C:/perl510_NV/5.10.0/lib
    C:/perl510_NV/site/5.10.0/lib
    .


Environment for perl 5.10.0:
    HOME (unset)
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=C:\perl510_NV\5.10.0\bin;c:\ruby\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\batch
    PERL_BADLANG (unset)
    SHELL (unset)


```
</details>

**Comment by p5pRT** [comment]
### From @sisyphus


\-\-\-\-\- Original Message \-\-\-\-\- 
From&#8203;: "Sisyphus \(via RT\)" \<perlbug\-followup@&#8203;perl\.org>

> Same results with a recent \(though not latest\) build of blead\.

Ooops \- that could be taken to mean that the problem is fixed in the latest 
blead\, but that's not what I meant\.
I haven't checked using the latest blead\. I have checked using only a recent 
\(~6 weeks old version of blead\) and the failure was still present in that 
blead build\.

Cheers\,
Rob

**Comment by p5pRT** [comment]
### From @jkeenan

It seems to me that there are two\, connected issues raised in this ticket\.

One is the general problem of how one would build Perl with
'NO\_PERL\_PRESERVE\_IVUV' and the circumstances where one would want to do
that\.

The other is any Win32\-specific problem\, such as getting tests to pass
once we have figured out how to build with this option\.

For the reference of anyone who can address this ticket\, here's some
relevant source code&#8203;:

from perl\.h&#8203;:
\#\#\#
\#ifndef NO\_PERL\_PRESERVE\_IVUV
\#define PERL\_PRESERVE\_IVUV      /\* We like our integers to stay integers\. \*/
\#endif
\#\#\#

\.\.\. and this comments precedes several tests in ext/Devel\-Peek/t/Peek\.t
\#\#\#
\# If perl is built with PERL\_PRESERVE\_IVUV then maths is done as integers
\# where possible and this scalar will be an IV\. If NO\_PERL\_PRESERVE\_IVUV
then
\# maths is done in floating point always\, and this scalar will be an NV\.
\# \(\[NI\]\) captures the type\, referred to by \\1 in this regexp and $type for
\# building subsequent regexps\.
\#\#\#

Rob\, have you had any further experience with this bug since originally
filing the ticket?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @jkeenan



There has been no further discussion in this ticket since I last posted
twenty months ago\.

I am taking the ticket for the purpose of closing it within 7 days
unless there is further discussion\.

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From @Hugmeir


It's possible to reproduce this failure by compiling perl like this&#8203;:
\./Configure \-des \-Dusedevel \-Dccflags='\-DNO\_PERL\_PRESERVE\_IVUV'

I imagine that building a perl with that option would give you a different
performance profile\, at the price of getting possibly questionable behavior\.
Coincidentally\, I am in the process of reviewing ifdefs like this\, and was
writing about this and other undocumented symbols\, but I'll leave that for
another mail\.

It's not clear to me if Peek\.t should be fixed to accommodate perls built
like this\. In a sense\, we're implicitly saying that this is supporting by
checking if the symbol is defined\. But on the other hand\, we could treat
this like NO\_TAINT\_SUPPORT \-\- the option is there\, but we don't guarantee
that the resulting perl will be equally functional\.

**Comment by p5pRT** [comment]
### From @jkeenan


Since there has been additional discussion within the 7\-day timespan\, I
will not close this ticket\.

Thank you very much\.
Jim Keenan

**Comment by toddr** [comment]
@Hugmeir did you find anything?

**Comment by jkeenan** [comment]
> @Hugmeir did you find anything?

This ticket was filed years ago from a Windows machine.  I do not have Windows available.  However, I compiled blead just now on Linux with the config options suggested by @Hugmeir.
```
./Configure -des -Dusedevel -Dccflags='-DNO_PERL_PRESERVE_IVUV'
```
Devel-Peek PASSed its tests and was installed.

Does that make this ticket closable (again)?

**Comment by toddr** [comment]
I vote yes.
