### ISSUE TITLE
installperl does not delete files before copying

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9880]
Migrated from [rt.perl.org#69302](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=69302) (status was 'open')

Searchable as RT69302$

**Comment by p5pRT** [comment]
### From @cpansprout

In Snow Leopard\, Apple replaced the scripts that come with perl  
\(pod2html\, perlbug\, etc\.\) with wrappers that delegate to the script  
with the version number tacked on the end \(pod2html5\.8\.9 or  
pod2html5\.10\.0 \[Snow Leopard comes with two versions of perl\]\)\. All  
these wrappers are actually hard links to the same file\.

I was trying to install 5\.10\.1 over the system perl \(with \-Dprefix=/ 
usr\)\, and\, since the scripts already installed are all the same file\,  
psed ended up being installed with a dozen different names\, it being  
the last script to be installed\.

Shouldn’t installperl be unlinking files if they already exist?


Use of uninitialized value in concatenation \(\.\) or string at /usr/bin/ 
perlbug line 639\.
Use of uninitialized value in concatenation \(\.\) or string at /usr/bin/ 
perlbug line 639\.


---
Flags&#8203;:
&nbsp;    category=install
&nbsp;    severity=high


---
Site configuration information for perl 5\.10\.1&#8203;:

Configured by sprout at Tue Sep 22 08&#8203;:35&#8203;:48 PDT 2009\.

Summary of my perl5 \(revision 5 version 10 subversion 1\) configuration&#8203;:

&nbsp;  Platform&#8203;:
&nbsp;    osname=darwin\, osvers=10\.0\.0\, archname=darwin\-thread\-multi\-2level
&nbsp;    uname='darwin pint\.local 10\.0\.0 darwin kernel version 10\.0\.0&#8203;: fri  
jul 31 22&#8203;:47&#8203;:34 pdt 2009; root&#8203;:xnu\-1456\.1\.25~1release\_i386 i386 '
&nbsp;    config\_args='\-sed \-Duseithreads \-Dprefix=/usr \-Dman3ext=3pm \- 
Duseshrplib \-Dotherlibdirs=/System/Library/Perl/Extras/5\.10\.0'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=define\, usemultiplicity=define
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-fno\-common \-DPERL\_DARWIN \-no\-cpp\-precomp \-fno\- 
strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'\,
&nbsp;    optimize='\-O3'\,
&nbsp;    cppflags='\-no\-cpp\-precomp \-fno\-common \-DPERL\_DARWIN \-no\-cpp\- 
precomp \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/ 
include'
&nbsp;    ccversion=''\, gccversion='4\.2\.1 \(Apple Inc\. build 5646\)'\,  
gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\,  
lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='env MACOSX\_DEPLOYMENT\_TARGET=10\.3 cc'\, ldflags =' \-fstack\- 
protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib
&nbsp;    libs=\-ldbm \-ldl \-lm \-lutil \-lc
&nbsp;    perllibs=\-ldl \-lm \-lutil \-lc
&nbsp;    libc=/usr/lib/libc\.dylib\, so=dylib\, useshrplib=true\,  
libperl=libperl\.dylib
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=bundle\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags=' '\, lddlflags=' \-bundle \-undefined dynamic\_lookup \-L/ 
usr/local/lib \-fstack\-protector'

Locally applied patches&#8203;:




---
@&#8203;INC for perl 5\.10\.1&#8203;:
&nbsp;    /System/Library/Perl/5\.10\.1/darwin\-thread\-multi\-2level
&nbsp;    /System/Library/Perl/5\.10\.1
&nbsp;    /Library/Perl/5\.10\.1/darwin\-thread\-multi\-2level
&nbsp;    /Library/Perl/5\.10\.1
&nbsp;    /Library/Perl/5\.10\.0/darwin\-thread\-multi\-2level
&nbsp;    /Library/Perl/5\.10\.0
&nbsp;    /Library/Perl/5\.8\.9
&nbsp;    /Library/Perl/5\.8\.6
&nbsp;    /Library/Perl/5\.8\.1
&nbsp;    /Library/Perl
&nbsp;    /Network/Library/Perl/5\.10\.1/darwin\-thread\-multi\-2level
&nbsp;    /Network/Library/Perl/5\.10\.1
&nbsp;    /Network/Library/Perl
&nbsp;    /System/Library/Perl/Extras/5\.10\.0/darwin\-thread\-multi\-2level
&nbsp;    /System/Library/Perl/Extras/5\.10\.0
&nbsp;    \.



---
Environment for perl 5\.10\.1&#8203;:
&nbsp;    DYLD\_LIBRARY\_PATH \(unset\)
&nbsp;    HOME=/Users/sprout
&nbsp;    LANG=en\_US\.UTF\-8
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/usr/bin&#8203;:/bin&#8203;:/usr/sbin&#8203;:/sbin&#8203;:/usr/local/bin&#8203;:/usr/X11/bin&#8203;:/ 
usr/local/bin
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From @obra

On Tue Sep 22 21&#8203;:31&#8203;:51 2009\, sprout@&#8203;cpan\.org wrote&#8203;:
> In Snow Leopard\, Apple replaced the scripts that come with perl  
> \(pod2html\, perlbug\, etc\.\) with wrappers that delegate to the script  
> with the version number tacked on the end \(pod2html5\.8\.9 or  
> pod2html5\.10\.0 \[Snow Leopard comes with two versions of perl\]\)\. All  
> these wrappers are actually hard links to the same file\.
> 
> I was trying to install 5\.10\.1 over the system perl \(with \-Dprefix=/ 
> usr\)\, and\, since the scripts already installed are all the same file\,  
> psed ended up being installed with a dozen different names\, it being  
> the last script to be installed\.
> 
> Shouldn’t installperl be unlinking files if they already exist?

So\, we talked about "don't do this" in this specific case\, but it'd be nice to come 
to a conclusion on how best to bulletproof Perl's install procedure against overly 
clever vendors\.

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout


On Oct 10\, 2009\, at 12&#8203;:27 PM\, Jesse via RT wrote&#8203;:

> On Tue Sep 22 21&#8203;:31&#8203;:51 2009\, sprout@&#8203;cpan\.org wrote&#8203;:
>> In Snow Leopard\, Apple replaced the scripts that come with perl
>> \(pod2html\, perlbug\, etc\.\) with wrappers that delegate to the script
>> with the version number tacked on the end \(pod2html5\.8\.9 or
>> pod2html5\.10\.0 \[Snow Leopard comes with two versions of perl\]\)\. All
>> these wrappers are actually hard links to the same file\.
>>
>> I was trying to install 5\.10\.1 over the system perl \(with \-Dprefix=/
>> usr\)\, and\, since the scripts already installed are all the same file\,
>> psed ended up being installed with a dozen different names\, it being
>> the last script to be installed\.
>>
>> Shouldn’t installperl be unlinking files if they already exist?
>
> So\, we talked about "don't do this" in this specific case\,

I actually consider the slight possibility of having to type ‘sudo ln  
perl5\.10\.0 perl’ some day far less painful than changing every script  
that begins with \#\!/usr/bin/perl \-C\. Anyway\, I’ve seen some of Apple’s  
install code\. It is simplistic enough it would probably run under  
5\.00\. I don’t think it will break\.

> but it'd be nice to come
> to a conclusion on how best to bulletproof Perl's install procedure  
> against overly
> clever vendors\.

I think the easiest way is to add ‘unlink’ to installperl\. Attached is  
a patch\. \(I first tried modifying File&#8203;::Copy\, but half the tests for  
permissions failed\.\) It does leave a bit of redundancy\, in that there  
is another unlink a few lines below \(in case the copy fails\)\, but I  
don’t understand that code\. Specifically\, why would you chmod a file\,  
and not its directory\, before unlinking? So I thought I’d best leave  
that alone\, in case it is needed on some system\.

**Comment by p5pRT** [comment]
### From @cpansprout

<details><summary>Inline Patch</summary>

```diff
diff -rup blead/installperl bleadcopy/installperl
--- blead/installperl	2009-10-01 16:57:11.000000000 -0700
+++ bleadcopy/installperl	2009-10-10 17:26:03.000000000 -0700
@@ -692,6 +692,12 @@ sub copy {
 	unless $opts{silent};
     print "  creating new version of $xto\n"
 	if $Is_VMS and -e $to and !$opts{silent};
+    if(!$Is_VMS and $Config{d_link}) {
+        # Some vendors put hard-linked wrapper scripts in their default
+        # perl installations. This would prevent a proper install over the
+        # top of a vendor's perl without the unlink.
+        unlink $to;
+    }
     unless ($opts{notify} or File::Copy::copy($from, $to)) {
 	# Might have been that F::C::c can't overwrite the target
 	warn "Couldn't copy $from to $to: $!\n"
```
</details>

**Comment by p5pRT** [comment]
### From @nwc10

On Sun\, Oct 18\, 2009 at 02&#8203;:42&#8203;:15PM \-0700\, Father Chrysostomos wrote&#8203;:
> 
> On Oct 10\, 2009\, at 12&#8203;:27 PM\, Jesse via RT wrote&#8203;:
> 
> >On Tue Sep 22 21&#8203;:31&#8203;:51 2009\, sprout@&#8203;cpan\.org wrote&#8203;:
> >>In Snow Leopard\, Apple replaced the scripts that come with perl
> >>\(pod2html\, perlbug\, etc\.\) with wrappers that delegate to the script
> >>with the version number tacked on the end \(pod2html5\.8\.9 or
> >>pod2html5\.10\.0 \[Snow Leopard comes with two versions of perl\]\)\. All
> >>these wrappers are actually hard links to the same file\.
> >>
> >>I was trying to install 5\.10\.1 over the system perl \(with \-Dprefix=/
> >>usr\)\, and\, since the scripts already installed are all the same file\,
> >>psed ended up being installed with a dozen different names\, it being
> >>the last script to be installed\.
> >>
> >>Shouldn?t installperl be unlinking files if they already exist?
> >
> >So\, we talked about "don't do this" in this specific case\,
> 
> I actually consider the slight possibility of having to type ?sudo ln  
> perl5\.10\.0 perl? some day far less painful than changing every script  
> that begins with \#\!/usr/bin/perl \-C\. Anyway\, I?ve seen some of Apple?s  
> install code\. It is simplistic enough it would probably run under  
> 5\.00\. I don?t think it will break\.

I still don't think that we want to do this\.

Nicholas Clark

**Comment by p5pRT** [comment]
### From @jkeenan

On Mon Oct 19 01&#8203;:14&#8203;:19 2009\, nicholas wrote&#8203;:
> On Sun\, Oct 18\, 2009 at 02&#8203;:42&#8203;:15PM \-0700\, Father Chrysostomos wrote&#8203;:
> > 
> > On Oct 10\, 2009\, at 12&#8203;:27 PM\, Jesse via RT wrote&#8203;:
> > 
> > >On Tue Sep 22 21&#8203;:31&#8203;:51 2009\, sprout@&#8203;cpan\.org wrote&#8203;:
> > >>In Snow Leopard\, Apple replaced the scripts that come with perl
> > >>\(pod2html\, perlbug\, etc\.\) with wrappers that delegate to the script
> > >>with the version number tacked on the end \(pod2html5\.8\.9 or
> > >>pod2html5\.10\.0 \[Snow Leopard comes with two versions of perl\]\)\. All
> > >>these wrappers are actually hard links to the same file\.
> > >>
> > >>I was trying to install 5\.10\.1 over the system perl \(with \-Dprefix=/
> > >>usr\)\, and\, since the scripts already installed are all the same file\,
> > >>psed ended up being installed with a dozen different names\, it being
> > >>the last script to be installed\.
> > >>
> > >>Shouldn?t installperl be unlinking files if they already exist?
> > >
> > >So\, we talked about "don't do this" in this specific case\,
> > 
> > I actually consider the slight possibility of having to type ?sudo ln  
> > perl5\.10\.0 perl? some day far less painful than changing every script  
> > that begins with \#\!/usr/bin/perl \-C\. Anyway\, I?ve seen some of Apple?s  
> > install code\. It is simplistic enough it would probably run under  
> > 5\.00\. I don?t think it will break\.
> 
> I still don't think that we want to do this\.
> 
> Nicholas Clark
> 


This ticket has generated no correspondence in nearly four years\.

Can we conclude that we do not want to modify installperl to delete
files before copying \(and thereby enable us to close the ticket\)?

Thank you very much\.
Jim Keenan

**Comment by p5pRT** [comment]
### From @cpansprout

On Thu Aug 08 16&#8203;:38&#8203;:58 2013\, jkeenan wrote&#8203;:
> On Mon Oct 19 01&#8203;:14&#8203;:19 2009\, nicholas wrote&#8203;:
> > On Sun\, Oct 18\, 2009 at 02&#8203;:42&#8203;:15PM \-0700\, Father Chrysostomos wrote&#8203;:
> > > 
> > > On Oct 10\, 2009\, at 12&#8203;:27 PM\, Jesse via RT wrote&#8203;:
> > > 
> > > >On Tue Sep 22 21&#8203;:31&#8203;:51 2009\, sprout@&#8203;cpan\.org wrote&#8203;:
> > > >>In Snow Leopard\, Apple replaced the scripts that come with perl
> > > >>\(pod2html\, perlbug\, etc\.\) with wrappers that delegate to the script
> > > >>with the version number tacked on the end \(pod2html5\.8\.9 or
> > > >>pod2html5\.10\.0 \[Snow Leopard comes with two versions of perl\]\)\. All
> > > >>these wrappers are actually hard links to the same file\.
> > > >>
> > > >>I was trying to install 5\.10\.1 over the system perl \(with \-Dprefix=/
> > > >>usr\)\, and\, since the scripts already installed are all the same
file\,
> > > >>psed ended up being installed with a dozen different names\, it being
> > > >>the last script to be installed\.
> > > >>
> > > >>Shouldn?t installperl be unlinking files if they already exist?
> > > >
> > > >So\, we talked about "don't do this" in this specific case\,
> > > 
> > > I actually consider the slight possibility of having to type ?sudo
ln  
> > > perl5\.10\.0 perl? some day far less painful than changing every
script  
> > > that begins with \#\!/usr/bin/perl \-C\. Anyway\, I?ve seen some of
Apple?s  
> > > install code\. It is simplistic enough it would probably run under  
> > > 5\.00\. I don?t think it will break\.
> > 
> > I still don't think that we want to do this\.
> > 
> > Nicholas Clark
> > 
> 
> 
> This ticket has generated no correspondence in nearly four years\.
> 
> Can we conclude that we do not want to modify installperl to delete
> files before copying \(and thereby enable us to close the ticket\)?

Well\, \*I\* don’t agree with that\! :\-\)

\-\- 

Father Chrysostomos

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Thu Aug 08 16&#8203;:38&#8203;:58 2013\, jkeenan wrote&#8203;:
> On Mon Oct 19 01&#8203;:14&#8203;:19 2009\, nicholas wrote&#8203;:
> > On Sun\, Oct 18\, 2009 at 02&#8203;:42&#8203;:15PM \-0700\, Father Chrysostomos wrote&#8203;:
> > > 
> > > On Oct 10\, 2009\, at 12&#8203;:27 PM\, Jesse via RT wrote&#8203;:
> > > 
> > > >On Tue Sep 22 21&#8203;:31&#8203;:51 2009\, sprout@&#8203;cpan\.org wrote&#8203;:
> > > >>In Snow Leopard\, Apple replaced the scripts that come with perl
> > > >>\(pod2html\, perlbug\, etc\.\) with wrappers that delegate to the script
> > > >>with the version number tacked on the end \(pod2html5\.8\.9 or
> > > >>pod2html5\.10\.0 \[Snow Leopard comes with two versions of perl\]\)\. All
> > > >>these wrappers are actually hard links to the same file\.
> > > >>
> > > >>I was trying to install 5\.10\.1 over the system perl \(with \-Dprefix=/
> > > >>usr\)\, and\, since the scripts already installed are all the same
file\,
> > > >>psed ended up being installed with a dozen different names\, it being
> > > >>the last script to be installed\.
> > > >>
> > > >>Shouldn?t installperl be unlinking files if they already exist?
> > > >
> > > >So\, we talked about "don't do this" in this specific case\,
> > > 
> > > I actually consider the slight possibility of having to type ?sudo
ln  
> > > perl5\.10\.0 perl? some day far less painful than changing every
script  
> > > that begins with \#\!/usr/bin/perl \-C\. Anyway\, I?ve seen some of
Apple?s  
> > > install code\. It is simplistic enough it would probably run under  
> > > 5\.00\. I don?t think it will break\.
> > 
> > I still don't think that we want to do this\.
> > 
> > Nicholas Clark
> > 
> 
> 
> This ticket has generated no correspondence in nearly four years\.
> 
> Can we conclude that we do not want to modify installperl to delete
> files before copying \(and thereby enable us to close the ticket\)?

Well\, \*I\* don’t agree with that\! :\-\)

\-\- 

Father Chrysostomos

**Comment by jkeenan** [comment]
The patch provided by @cpansprout has not gained any endorsements since it was first proposed in 2009.  Two former pumpkings have expressed doubt as to its merits.

I no longer have a working Mac, so I can't evaluate this Darwin-specific problem.  However, I am very skeptical of the idea that we should be trying to compensate for weird choices made in a "vendor perl" installation by overwriting files in that installation.  We have long followed the adage "the system perl is for the system."

I'm taking this ticket for the purpose of closing it in 7 days unless someone wants to re-open the discussion (preferably with suggestions tested on Darwin).

Thank you very much.
Jim Keenan

**Comment by jkeenan** [comment]
> The patch provided by @cpansprout has not gained any endorsements since it was first proposed in 2009. Two former pumpkings have expressed doubt as to its merits.
> 
> I no longer have a working Mac, so I can't evaluate this Darwin-specific problem. However, I am very skeptical of the idea that we should be trying to compensate for weird choices made in a "vendor perl" installation by overwriting files in that installation. We have long followed the adage "the system perl is for the system."
> 
> I'm taking this ticket for the purpose of closing it in 7 days unless someone wants to re-open the discussion (preferably with suggestions tested on Darwin).
> 

Closing ticket per previously announced schedule.

Thank you very much.
Jim Keenan
