### ISSUE TITLE
B::Deparse fail on "my" with attributes

### ISSUE THREAD

**Issue by p5pRT** [Perl/perl5#9946]
Migrated from [rt.perl.org#70205](https://rt-archive.perl.org/perl5/Ticket/Display.html?id=70205) (status was 'open')

Searchable as RT70205$

**Comment by p5pRT** [comment]
### From zefram@fysh.org

#### Created by zefram@fysh.org



Investigating around a B&#8203;::Deparse problem that Nicholas just reported\,
I found this&#8203;:

$ perl \-MO=Deparse \-e 'my $pi :shared = 4'
use attributes \(\);
\('attributes'\->import\('main'\, \\$pi\, 'shared'\)\, my $pi\) = 4;
\-e syntax OK

Note that \\$pi is referenced before "my $pi" comes into scope\, so the
reference is wrong\.  Also\, the attempt at a comma operator on the LHS
of assignment ends up doing a list assignment\, and attempting to assign
4 to the return value of the \->import\.  Need cleverer code generation\.

<details><summary>Perl Info</summary>

```

Flags:
    category=core
    severity=low

Site configuration information for perl 5.10.0:

Configured by Debian Project at Fri Aug 28 22:30:10 UTC 2009.

Summary of my perl5 (revision 5 version 10 subversion 0) configuration:
  Platform:
    osname=linux, osvers=2.6.26-2-amd64, archname=i486-linux-gnu-thread-multi
    uname='linux puccini 2.6.26-2-amd64 #1 smp fri aug 14 07:12:04 utc 2009 i686 gnulinux '
    config_args='-Dusethreads -Duselargefiles -Dccflags=-DDEBIAN -Dcccdlflags=-fPIC -Darchname=i486-linux-gnu -Dprefix=/usr -Dprivlib=/usr/share/perl/5.10 -Darchlib=/usr/lib/perl/5.10 -Dvendorprefix=/usr -Dvendorlib=/usr/share/perl5 -Dvendorarch=/usr/lib/perl5 -Dsiteprefix=/usr/local -Dsitelib=/usr/local/share/perl/5.10.0 -Dsitearch=/usr/local/lib/perl/5.10.0 -Dman1dir=/usr/share/man/man1 -Dman3dir=/usr/share/man/man3 -Dsiteman1dir=/usr/local/man/man1 -Dsiteman3dir=/usr/local/man/man3 -Dman1ext=1 -Dman3ext=3perl -Dpager=/usr/bin/sensible-pager -Uafs -Ud_csh -Ud_ualarm -Uusesfio -Uusenm -DDEBUGGING=-g -Doptimize=-O2 -Duseshrplib -Dlibperl=libperl.so.5.10.0 -Dd_dosuid -des'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=undef, use64bitall=undef, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64',
    optimize='-O2 -g',
    cppflags='-D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fno-strict-aliasing -pipe -I/usr/local/include'
    ccversion='', gccversion='4.3.2', gccosandvers=''
    intsize=4, longsize=4, ptrsize=4, doublesize=8, byteorder=1234
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=12
    ivtype='long', ivsize=4, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=4, prototype=define
  Linker and Libraries:
    ld='cc', ldflags =' -L/usr/local/lib'
    libpth=/usr/local/lib /lib /usr/lib /usr/lib64
    libs=-lgdbm -lgdbm_compat -ldb -ldl -lm -lpthread -lc -lcrypt
    perllibs=-ldl -lm -lpthread -lc -lcrypt
    libc=/lib/libc-2.7.so, so=so, useshrplib=true, libperl=libperl.so.5.10.0
    gnulibc_version='2.7'
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=so, d_dlsymun=undef, ccdlflags='-Wl,-E'
    cccdlflags='-fPIC', lddlflags='-shared -O2 -g -L/usr/local/lib'

Locally applied patches:
    


@INC for perl 5.10.0:
    /etc/perl
    /usr/local/lib/perl/5.10.0
    /usr/local/share/perl/5.10.0
    /usr/lib/perl5
    /usr/share/perl5
    /usr/lib/perl/5.10
    /usr/share/perl/5.10
    /usr/local/lib/site_perl
    .


Environment for perl 5.10.0:
    HOME=/home/zefram
    LANG (unset)
    LANGUAGE (unset)
    LD_LIBRARY_PATH (unset)
    LOGDIR (unset)
    PATH=/home/zefram/pub/i686-pc-linux-gnu/bin:/home/zefram/pub/common/bin:/usr/bin:/usr/X11R6/bin:/bin:/usr/local/bin:/usr/games
    PERL_BADLANG (unset)
    SHELL=/usr/bin/zsh

```
</details>

**Comment by p5pRT** [comment]
@pjf - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

This is even more amusing than what our $foo&#8203;:shared \(\#70201\) produces&#8203;:

$ \./perl \-Ilib \-MO=Deparse \-e 'my $x :shared = 4'
use attributes \(\);
\('attributes'\->import\('main'\, \\$x\, 'shared'\)\, my $x\) = 4;
\-e syntax OK

$ \./perl \-Ilib \-MO=Deparse \-E 'state $x :shared = 4'
use attributes \(\);
BEGIN \{
&nbsp;    $^H\{'feature\_unicode'\} = q\(1\);
&nbsp;    $^H\{'feature\_say'\} = q\(1\);
&nbsp;    $^H\{'feature\_state'\} = q\(1\);
&nbsp;    $^H\{'feature\_switch'\} = q\(1\);
\}
\('attributes'\->import\('main'\, \\$x\, 'shared'\)\, state $x\) = 4;
\-e syntax OK


---
Flags&#8203;:
&nbsp;    category=library
&nbsp;    severity=low


---
Site configuration information for perl 5\.13\.7&#8203;:

Configured by sprout at Thu Dec  9 14&#8203;:53&#8203;:58 PST 2010\.

Summary of my perl5 \(revision 5 version 13 subversion 7\) configuration&#8203;:
&nbsp;  Snapshot of&#8203;: 9e9fdd5de1676d607ddf9b9f10b8df2659af3ded
&nbsp;  Platform&#8203;:
&nbsp;    osname=darwin\, osvers=10\.4\.0\, archname=darwin\-2level
&nbsp;    uname='darwin pint\.local 10\.4\.0 darwin kernel version 10\.4\.0&#8203;: fri apr 23 18&#8203;:28&#8203;:53 pdt 2010; root&#8203;:xnu\-1504\.7\.4~1release\_i386 i386 '
&nbsp;    config\_args='\-de \-Dusedevel \-DDEBUGGING'
&nbsp;    hint=recommended\, useposix=true\, d\_sigaction=define
&nbsp;    useithreads=undef\, usemultiplicity=undef
&nbsp;    useperlio=define\, d\_sfio=undef\, uselargefiles=define\, usesocks=undef
&nbsp;    use64bitint=undef\, use64bitall=undef\, uselongdouble=undef
&nbsp;    usemymalloc=n\, bincompat5005=undef
&nbsp;  Compiler&#8203;:
&nbsp;    cc='cc'\, ccflags ='\-fno\-common \-DPERL\_DARWIN \-no\-cpp\-precomp \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'\,
&nbsp;    optimize='\-O3 \-g'\,
&nbsp;    cppflags='\-no\-cpp\-precomp \-fno\-common \-DPERL\_DARWIN \-no\-cpp\-precomp \-DDEBUGGING \-fno\-strict\-aliasing \-pipe \-fstack\-protector \-I/usr/local/include'
&nbsp;    ccversion=''\, gccversion='4\.2\.1 \(Apple Inc\. build 5664\)'\, gccosandvers=''
&nbsp;    intsize=4\, longsize=4\, ptrsize=4\, doublesize=8\, byteorder=1234
&nbsp;    d\_longlong=define\, longlongsize=8\, d\_longdbl=define\, longdblsize=16
&nbsp;    ivtype='long'\, ivsize=4\, nvtype='double'\, nvsize=8\, Off\_t='off\_t'\, lseeksize=8
&nbsp;    alignbytes=8\, prototype=define
&nbsp;  Linker and Libraries&#8203;:
&nbsp;    ld='env MACOSX\_DEPLOYMENT\_TARGET=10\.3 cc'\, ldflags =' \-fstack\-protector \-L/usr/local/lib'
&nbsp;    libpth=/usr/local/lib /usr/lib
&nbsp;    libs=\-ldbm \-ldl \-lm \-lutil \-lc
&nbsp;    perllibs=\-ldl \-lm \-lutil \-lc
&nbsp;    libc=/usr/lib/libc\.dylib\, so=dylib\, useshrplib=false\, libperl=libperl\.a
&nbsp;    gnulibc\_version=''
&nbsp;  Dynamic Linking&#8203;:
&nbsp;    dlsrc=dl\_dlopen\.xs\, dlext=bundle\, d\_dlsymun=undef\, ccdlflags=' '
&nbsp;    cccdlflags=' '\, lddlflags=' \-bundle \-undefined dynamic\_lookup \-L/usr/local/lib \-fstack\-protector'

Locally applied patches&#8203;:
&nbsp;    



---
@&#8203;INC for perl 5\.13\.7&#8203;:
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.13\.7/darwin\-2level
&nbsp;    /usr/local/lib/perl5/site\_perl/5\.13\.7
&nbsp;    /usr/local/lib/perl5/5\.13\.7/darwin\-2level
&nbsp;    /usr/local/lib/perl5/5\.13\.7
&nbsp;    /usr/local/lib/perl5/site\_perl
&nbsp;    \.



---
Environment for perl 5\.13\.7&#8203;:
&nbsp;    DYLD\_LIBRARY\_PATH \(unset\)
&nbsp;    HOME=/Users/sprout
&nbsp;    LANG=en\_US\.UTF\-8
&nbsp;    LANGUAGE \(unset\)
&nbsp;    LD\_LIBRARY\_PATH \(unset\)
&nbsp;    LOGDIR \(unset\)
&nbsp;    PATH=/usr/bin&#8203;:/bin&#8203;:/usr/sbin&#8203;:/sbin&#8203;:/usr/local/bin&#8203;:/usr/X11/bin&#8203;:/usr/local/bin
&nbsp;    PERL\_BADLANG \(unset\)
&nbsp;    SHELL=/bin/bash

**Comment by p5pRT** [comment]
### From zefram@fysh.org

Father Chrysostomos wrote&#8203;:
>Subject&#8203;: \[perl \#80634\] Deparsing my/state with attributes 

This is a duplicate of \[perl \#70205\]\.

\-zefram

**Comment by p5pRT** [comment]
The RT System itself - Status changed from 'new' to 'open'

**Comment by p5pRT** [comment]
### From @cpansprout

On Sun Dec 12 12&#8203;:38&#8203;:35 2010\, zefram@&#8203;fysh\.org wrote&#8203;:
> Father Chrysostomos wrote&#8203;:
> >Subject&#8203;: \[perl \#80634\] Deparsing my/state with attributes 
> 
> This is a duplicate of \[perl \#70205\]\.
> 
> \-zefram
> 

So it is\. Thank you\.

Interestingly\, you wrote it that ticket&#8203;:
> Investigating around a B&#8203;::Deparse problem that Nicholas just reported\,
> I found this&#8203;:

That’s exactly what I was doing\. :\-\)

**Comment by p5pRT** [comment]
### From [Unknown Contact. See original ticket]

On Sun Dec 12 12&#8203;:38&#8203;:35 2010\, zefram@&#8203;fysh\.org wrote&#8203;:
> Father Chrysostomos wrote&#8203;:
> >Subject&#8203;: \[perl \#80634\] Deparsing my/state with attributes 
> 
> This is a duplicate of \[perl \#70205\]\.
> 
> \-zefram
> 

So it is\. Thank you\.

Interestingly\, you wrote it that ticket&#8203;:
> Investigating around a B&#8203;::Deparse problem that Nicholas just reported\,
> I found this&#8203;:

That’s exactly what I was doing\. :\-\)

**Comment by jkeenan** [comment]
Back in November 2009, Zefram reported this:

> Investigating around a B​::Deparse problem that Nicholas just reported, I found this​:
> 
>
```
$ perl -MO=Deparse -e 'my $pi :shared = 4'
use attributes ();
('attributes'->import('main', \$pi, 'shared'), my $pi) = 4;
-e syntax OK
```
> 
> Note that \$pi is referenced before "my $pi" comes into scope, so the reference is wrong. Also, the attempt at a comma operator on the LHS of assignment ends up doing a list assignment, and attempting to assign 4 to the return value of the ->import. Need cleverer code generation.

Running that command in perl-5.38 today, I got:
```
$ perl -MO=Deparse -e 'my $pi :shared = 4'
use attributes ();
my $pi :shared = 4;
-e syntax OK
```
Now, I don't know enough about B::Deparse to know whether the current code is correct or not.  However, I became curious as to **when** the output changed.  I wrote a test file, tested it with various production releases installed via `perlbrew`, and used it to bisect the change.
```
$ cat /tmp/gh-9946-deparse.pl 
my @lines = `$^X -Ilib -MO=Deparse -e 'my \$pi :shared = 4'`;
my $seen = grep { /:shared/ } @lines;
print "Count: $seen\n";
die "Saw ':shared'" if $seen;
```
```
$ perl Porting/bisect.pl \
--start=v5.26.0 \
--end=v5.28.0 \
--target=test_prep \
-- ./perl -Ilib /tmp/gh-9946-deparse.pl
```
Bisection pointed to this commit:
```
commit 82ab48fa8c6c51b80c9b69419850061640110339
Author:     David Mitchell <davem@iabyn.nospamdeletethisbit.com>
AuthorDate: Fri Feb 24 14:32:28 2017 +0000
Commit:     David Mitchell <davem@iabyn.nospamdeletethisbit.com>
CommitDate: Mon Jun 5 12:52:18 2017 +0100

    Deparse my var attributes correctly
```
@iabyn, does that make this ticket closable?

**Note:** Back in 2009, there was a companion ticket created by @nwc10 for the case of `our` variables: https://github.com/Perl/perl5/issues/9944.  The output Nick reported there (and found anomalous) is unchanged in perl-5.38.
```
$ perl -MO=Deparse -e 'our $pi :shared = 4'
use attributes ('main', \undef, 'shared');
our $pi = 4;
-e syntax OK
```

**Comment by iabyn** [comment]
On Sun, Oct 29, 2023 at 03:23:00PM -0700, James E Keenan wrote:
> @iabyn, does that make this ticket closable?

Yes.

> 
> **Note:** Back in 2009, there was a companion ticket created by @nwc10 for the case of `our` variables: https://github.com/Perl/perl5/issues/9944.  The output Nick reported there (and found anomalous) is unchanged in perl-5.38.
> ```
> $ perl -MO=Deparse -e 'our $pi :shared = 4'
> use attributes ('main', \undef, 'shared');
> our $pi = 4;
> -e syntax OK

Yeah, that still needs fixing.

-- 
If life gives you lemons, you'll probably develop a citric acid allergy.
